In [1]:
%config Completer.use_jedi = False

In [2]:
import os
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
pd.reset_option('all')
pd.set_option('mode.chained_assignment',  None)
import numpy as np
from scipy.stats import mode

In [3]:
def get_weather_filelist(path = './weather'):
    fs = sorted(os.listdir(path))
    file_df = pd.DataFrame(columns = ['h_dong', 'file_list' , 'start' , 'end', 'file_name'])

    for f_num , f_name in enumerate(fs):
        if 'ipy' in f_name:
            pass
        else:
            f_name = f_name.split('.')[0]
            f_split = f_name.split('_')
            file_df.loc[f_num, 'h_dong'] = f_split[0]
            file_df.loc[f_num, 'file_list'] = f_split[1]
            file_df.loc[f_num, 'start'] = f_split[2]
            file_df.loc[f_num, 'end'] = f_split[3]
            file_df.loc[f_num, 'file_name'] = f_name+'.csv'
    file_df.reset_index(inplace=True,drop = True)
    return file_df

In [4]:
all_df = get_weather_filelist()
all_df['file_name'] = './weather/' + all_df['file_name']

In [5]:
all_df

     h_dong file_list   start     end                                file_name
0       강남동   12시간강수량  200901  200912  ./weather/강남동_12시간강수량_200901_200912.csv
1       강남동   12시간강수량  201001  201012  ./weather/강남동_12시간강수량_201001_201012.csv
2       강남동   12시간강수량  201101  201112  ./weather/강남동_12시간강수량_201101_201112.csv
3       강남동   12시간강수량  201201  201212  ./weather/강남동_12시간강수량_201201_201212.csv
4       강남동   12시간강수량  201301  201312  ./weather/강남동_12시간강수량_201301_201312.csv
...     ...       ...     ...     ...                                      ...
1496   후평3동        풍속  201601  201612      ./weather/후평3동_풍속_201601_201612.csv
1497   후평3동        풍속  201701  201712      ./weather/후평3동_풍속_201701_201712.csv
1498   후평3동        풍속  201801  201812      ./weather/후평3동_풍속_201801_201812.csv
1499   후평3동        풍속  201901  201912      ./weather/후평3동_풍속_201901_201912.csv
1500   후평3동        풍속  202001  202012      ./weather/후평3동_풍속_202001_202012.csv

[1501 rows x 5 columns]

In [6]:
for year in range(2010,2021):
    year_idx = str(year) + '01'
    year_df = all_df[all_df['start'] == year_idx]
    year_df.reset_index(inplace=True, drop = True)
    for dong in sorted(year_df['h_dong'].unique()):
        dong_year_df = year_df[year_df['h_dong'] == dong]
        if len(dong_year_df) != 5:
            print(f'{year} {dong}   {len(dong_year_df)}')
    print()

In [7]:
all_df[all_df['start'] == '202001'][:10]

    h_dong file_list   start     end                               file_name
16     강남동     3시간기온  202001  202012   ./weather/강남동_3시간기온_202001_202012.csv
23     강남동    6시간강수량  202001  202012  ./weather/강남동_6시간강수량_202001_202012.csv
35     강남동      강수형태  202001  202012    ./weather/강남동_강수형태_202001_202012.csv
47     강남동        습도  202001  202012      ./weather/강남동_습도_202001_202012.csv
59     강남동        풍속  202001  202012      ./weather/강남동_풍속_202001_202012.csv
76      교동     3시간기온  202001  202012    ./weather/교동_3시간기온_202001_202012.csv
83      교동    6시간강수량  202001  202012   ./weather/교동_6시간강수량_202001_202012.csv
95      교동      강수형태  202001  202012     ./weather/교동_강수형태_202001_202012.csv
107     교동        습도  202001  202012       ./weather/교동_습도_202001_202012.csv
119     교동        풍속  202001  202012       ./weather/교동_풍속_202001_202012.csv

In [8]:
all_df[all_df['start'] == '201001'][:10]

    h_dong file_list   start     end                                file_name
1      강남동   12시간강수량  201001  201012  ./weather/강남동_12시간강수량_201001_201012.csv
6      강남동     3시간기온  201001  201012    ./weather/강남동_3시간기온_201001_201012.csv
25     강남동      강수형태  201001  201012     ./weather/강남동_강수형태_201001_201012.csv
37     강남동        습도  201001  201012       ./weather/강남동_습도_201001_201012.csv
49     강남동        풍속  201001  201012       ./weather/강남동_풍속_201001_201012.csv
61      교동   12시간강수량  201001  201012   ./weather/교동_12시간강수량_201001_201012.csv
66      교동     3시간기온  201001  201012     ./weather/교동_3시간기온_201001_201012.csv
85      교동      강수형태  201001  201012      ./weather/교동_강수형태_201001_201012.csv
97      교동        습도  201001  201012        ./weather/교동_습도_201001_201012.csv
109     교동        풍속  201001  201012        ./weather/교동_풍속_201001_201012.csv

In [9]:
abc = pd.read_csv('./weather/강남동_3시간기온_201001_201012.csv')
row_idx = abc[abc.columns[0]].unique()#[:42]
row_idx

array([' 1', ' 2', ' 3', ' 4', ' 5', ' 6', ' 7', ' 8', ' 9', ' 10', ' 11',
       ' 12', ' 13', ' 14', ' 15', ' 16', ' 17', ' 18', ' 19', ' 20',
       ' 21', ' 22', ' 23', ' 24', ' 25', ' 26', ' 27', ' 28', ' 29',
       ' 30', ' 31', ' Start : 20100201 ', ' Start : 20100301 ',
       ' Start : 20100401 ', ' Start : 20100501 ', ' Start : 20100601 ',
       ' Start : 20100701 ', ' Start : 20100801 ', ' Start : 20100901 ',
       ' Start : 20101001 ', ' Start : 20101101 ', ' Start : 20101201 '],
      dtype=object)

In [10]:
for idx in all_df.index:
    f_name = all_df['file_name'].iloc[idx]
    tmp = pd.read_csv(f_name)

    del_idx = tmp[tmp[' format: day'].str.contains('format')].index
    if del_idx > 0:
        print(f'{f_name} have {del_idx}')
        tmp.drop(del_idx, inplace=True)
        tmp.reset_index(inplace=True, drop = True)
        tmp.to_csv(f_name, index=False)

./weather/강남동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/강남동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/강남동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/강남동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/교동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/교동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/교동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/교동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/근화동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/근화동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/근화동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/근화동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/남면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/남면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/남면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/남면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/남산면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/남산면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/남산면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/남산면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동내면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/동내면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동내면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동내면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/동면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동산면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/동산면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동산면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/동산면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/북산면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/북산면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/북산면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/북산면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/사북면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/사북면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/사북면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/사북면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/서면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/서면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/서면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/서면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/석사동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/석사동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/석사동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/석사동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/소양동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/소양동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/소양동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/소양동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신동면_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/신동면_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신동면_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신동면_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신북읍_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/신북읍_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신북읍_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신북읍_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신사우동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/신사우동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신사우동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/신사우동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/약사명동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/약사명동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/약사명동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/약사명동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/조운동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/조운동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/조운동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/조운동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/퇴계동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/퇴계동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/퇴계동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/퇴계동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자1동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/효자1동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자1동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자1동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자2동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/효자2동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자2동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자2동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자3동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/효자3동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자3동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/효자3동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평1동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/후평1동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평1동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평1동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평2동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/후평2동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평2동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평2동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평3동_12시간강수량_200901_200912.csv have Int64Index([5479], dtype='int64')
./weather/후평3동_3시간기온_200901_200912.csv have Int64Index([48191], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평3동_강수형태_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:

./weather/후평3동_습도_200901_200912.csv have Int64Index([46293], dtype='int64')

<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0:
<ipython-input-10-2dfc41f52059>:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if del_idx > 0: