In [1]:
%config Completer.use_jedi = False

In [2]:
import os
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
pd.reset_option('all')
import numpy as np

def get_weather_filelist(path = './weather'):
    fs = sorted(os.listdir(path))
    file_df = pd.DataFrame(columns = ['h_dong', 'file_list' , 'start' , 'end', 'file_name'])

    for f_num , f_name in enumerate(fs):
        if 'ipy' in f_name:
            pass
        else:
            f_name = f_name.split('.')[0]
            f_split = f_name.split('_')
            file_df.loc[f_num, 'h_dong'] = f_split[0]
            file_df.loc[f_num, 'file_list'] = f_split[1]
            file_df.loc[f_num, 'start'] = f_split[2]
            file_df.loc[f_num, 'end'] = f_split[3]
            file_df.loc[f_num, 'file_name'] = f_name+'.csv'
    file_df.reset_index(inplace=True,drop = True)
    return file_df


all_df = get_weather_filelist()
all_df

     h_dong file_list   start     end                      file_name
0       강남동   12시간강수량  201001  201012  강남동_12시간강수량_201001_201012.csv
1       강남동   12시간강수량  201101  201112  강남동_12시간강수량_201101_201112.csv
2       강남동   12시간강수량  201201  201212  강남동_12시간강수량_201201_201212.csv
3       강남동   12시간강수량  201301  201312  강남동_12시간강수량_201301_201312.csv
4       강남동     3시간기온  201001  201012    강남동_3시간기온_201001_201012.csv
...     ...       ...     ...     ...                            ...
1375   후평3동      하늘상태  201101  201112    후평3동_하늘상태_201101_201112.csv
1376   후평3동      하늘상태  201201  201212    후평3동_하늘상태_201201_201212.csv
1377   후평3동      하늘상태  201301  201312    후평3동_하늘상태_201301_201312.csv
1378   후평3동      하늘상태  201401  201412    후평3동_하늘상태_201401_201412.csv
1379   후평3동      하늘상태  201501  201512    후평3동_하늘상태_201501_201512.csv

[1380 rows x 5 columns]

# 2010년

In [3]:
df2010 = all_df[all_df['start'] == '201001']
df2010['file_name'] = './weather/' + df2010['file_name']
df2010.reset_index(inplace=True , drop=True)

null_2010_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2010_df['h_dong'] = df2010['h_dong']
null_2010_df['file_list'] = df2010['file_list']
null_2010_df['file_name'] = df2010['file_name']

for idx in null_2010_df.index:
    csv = pd.read_csv(null_2010_df['file_name'].loc[idx])
    null_2010_df.loc[idx, 'file_length'] = len(csv)
    null_2010_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2010_df.loc[idx , int(col[13:15])] = 1
null_2010_df

<ipython-input-3-0b1e65782115>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2010['file_name'] = './weather/' + df2010['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,12시간강수량,./weather/강남동_12시간강수량_201001_201012.csv,9875,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,3시간기온,./weather/강남동_3시간기온_201001_201012.csv,48191,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,강수형태,./weather/강남동_강수형태_201001_201012.csv,48191,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,습도,./weather/강남동_습도_201001_201012.csv,48191,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,풍속,./weather/강남동_풍속_201001_201012.csv,44098,1,1,1,1,1,1,1,NaN,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,후평3동,12시간강수량,./weather/후평3동_12시간강수량_201001_201012.csv,9875,1,1,1,1,1,1,1,1,1,1,1,1
120,후평3동,3시간기온,./weather/후평3동_3시간기온_201001_201012.csv,48191,1,1,1,1,1,1,1,1,1,1,1,1
121,후평3동,강수형태,./weather/후평3동_강수형태_201001_201012.csv,48191,1,1,1,1,1,1,1,1,1,1,1,1
122,후평3동,습도,./weather/후평3동_습도_201001_201012.csv,48191,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,풍속,./weather/후평3동_풍속_201001_201012.csv,44098,1,1,1,1,1,1,1,NaN,1,1,1,1

In [4]:
for fl in null_2010_df['file_list'].unique():
    print(f'{fl}',null_2010_df[null_2010_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2010_df.isnull().sum()

12시간강수량 [9875]
3시간기온 [48191]
강수형태 [48191]
습도 [48191]
풍속 [44098]
--------------------

h_dong          0
file_list       0
file_name       0
file_length     0
1               0
2               0
3               0
4               0
5               0
6               0
7               0
8              25
9               0
10              0
11              0
12              0
dtype: int64

In [5]:
df2011 = all_df[all_df['start'] == '201101']
df2011['file_name'] = './weather/' + df2011['file_name']
df2011.reset_index(inplace=True , drop=True)

null_2011_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2011_df['h_dong'] = df2011['h_dong']
null_2011_df['file_list'] = df2011['file_list']
null_2011_df['file_name'] = df2011['file_name']

for idx in null_2011_df.index:
    csv = pd.read_csv(null_2011_df['file_name'].loc[idx])
    null_2011_df.loc[idx, 'file_length'] = len(csv)
    null_2011_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2011_df.loc[idx , int(col[13:15])] = 1
null_2011_df

<ipython-input-5-925c435481eb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2011['file_name'] = './weather/' + df2011['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,12시간강수량,./weather/강남동_12시간강수량_201101_201112.csv,4493,1,1,NaN,1,1,NaN,1,1,NaN,1,1,NaN
1,강남동,3시간기온,./weather/강남동_3시간기온_201101_201112.csv,44577,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,습도,./weather/강남동_습도_201101_201112.csv,44577,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,풍속,./weather/강남동_풍속_201101_201112.csv,40682,1,1,1,1,1,1,1,NaN,1,1,1,1
4,강남동,하늘상태,./weather/강남동_하늘상태_201101_201112.csv,40484,1,1,1,1,1,1,1,NaN,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,후평3동,12시간강수량,./weather/후평3동_12시간강수량_201101_201112.csv,4493,1,1,NaN,1,1,NaN,1,1,NaN,1,1,NaN
121,후평3동,3시간기온,./weather/후평3동_3시간기온_201101_201112.csv,44577,1,1,1,1,1,1,1,1,1,1,1,1
122,후평3동,습도,./weather/후평3동_습도_201101_201112.csv,44577,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,풍속,./weather/후평3동_풍속_201101_201112.csv,40682,1,1,1,1,1,1,1,NaN,1,1,1,1
124,후평3동,하늘상태,./weather/후평3동_하늘상태_201101_201112.csv,40484,1,1,1,1,1,1,1,NaN,1,1,1,1

In [6]:
for fl in null_2011_df['file_list'].unique():
    print(f'{fl}',null_2011_df[null_2011_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2011_df.isnull().sum()

12시간강수량 [4493]
3시간기온 [44577]
습도 [44577]
풍속 [40682]
하늘상태 [40484]
--------------------

h_dong          0
file_list       0
file_name       0
file_length     0
1               0
2               0
3              25
4               0
5               0
6              25
7               0
8              50
9              25
10              0
11              0
12             25
dtype: int64

# 2012

In [7]:
df2012 = all_df[all_df['start'] == '201201']
df2012['file_name'] = './weather/' + df2012['file_name']
df2012.reset_index(inplace=True , drop=True)

null_2012_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2012_df['h_dong'] = df2012['h_dong']
null_2012_df['file_list'] = df2012['file_list']
null_2012_df['file_name'] = df2012['file_name']

for idx in null_2012_df.index:
    csv = pd.read_csv(null_2012_df['file_name'].loc[idx])
    null_2012_df.loc[idx, 'file_length'] = len(csv)
    null_2012_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2012_df.loc[idx , int(col[13:15])] = 1
null_2012_df

<ipython-input-7-5c548cbf27aa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2012['file_name'] = './weather/' + df2012['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,12시간강수량,./weather/강남동_12시간강수량_201201_201212.csv,7952,1,1,NaN,1,1,NaN,1,1,1,1,1,1
1,강남동,3시간기온,./weather/강남동_3시간기온_201201_201212.csv,48320,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,습도,./weather/강남동_습도_201201_201212.csv,45249,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,풍속,./weather/강남동_풍속_201201_201212.csv,20068,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN
4,강남동,하늘상태,./weather/강남동_하늘상태_201201_201212.csv,32212,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,후평3동,12시간강수량,./weather/후평3동_12시간강수량_201201_201212.csv,7952,1,1,NaN,1,1,NaN,1,1,1,1,1,1
121,후평3동,3시간기온,./weather/후평3동_3시간기온_201201_201212.csv,48320,1,1,1,1,1,1,1,1,1,1,1,1
122,후평3동,습도,./weather/후평3동_습도_201201_201212.csv,45249,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,풍속,./weather/후평3동_풍속_201201_201212.csv,20068,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN
124,후평3동,하늘상태,./weather/후평3동_하늘상태_201201_201212.csv,32212,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1

In [8]:
for fl in null_2012_df['file_list'].unique():
    print(f'{fl}',null_2012_df[null_2012_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2012_df.isnull().sum()

12시간강수량 [7952]
3시간기온 [48320]
습도 [45249]
풍속 [20068]
하늘상태 [32212]
--------------------

h_dong          0
file_list       0
file_name       0
file_length     0
1               0
2               0
3              25
4              50
5              50
6              75
7              50
8               0
9               0
10             25
11             25
12             25
dtype: int64

# 2013

In [9]:
df2013 = all_df[all_df['start'] == '201301']
df2013['file_name'] = './weather/' + df2013['file_name']
df2013.reset_index(inplace=True , drop=True)

null_2013_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2013_df['h_dong'] = df2013['h_dong']
null_2013_df['file_list'] = df2013['file_list']
null_2013_df['file_name'] = df2013['file_name']

for idx in null_2013_df.index:
    csv = pd.read_csv(null_2013_df['file_name'].loc[idx])
    null_2013_df.loc[idx, 'file_length'] = len(csv)
    null_2013_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2013_df.loc[idx , int(col[13:15])] = 1
null_2013_df

<ipython-input-9-d766307b27ba>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2013['file_name'] = './weather/' + df2013['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,12시간강수량,./weather/강남동_12시간강수량_201301_201312.csv,6596,1,1,NaN,1,1,NaN,1,1,NaN,1,1,1
1,강남동,3시간기온,./weather/강남동_3시간기온_201301_201312.csv,96383,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,6시간강수량,./weather/강남동_6시간강수량_201301_201312.csv,14559,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1
3,강남동,습도,./weather/강남동_습도_201301_201312.csv,96383,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,풍속,./weather/강남동_풍속_201301_201312.csv,94171,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,후평2동,풍속,./weather/후평2동_풍속_201301_201312.csv,94171,1,1,1,1,1,1,1,1,1,1,1,1
138,후평2동,하늘상태,./weather/후평2동_하늘상태_201301_201312.csv,96383,1,1,1,1,1,1,1,1,1,1,1,1
139,후평3동,3시간기온,./weather/후평3동_3시간기온_201301_201312.csv,96383,1,1,1,1,1,1,1,1,1,1,1,1
140,후평3동,6시간강수량,./weather/후평3동_6시간강수량_201301_201312.csv,14559,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1
141,후평3동,하늘상태,./weather/후평3동_하늘상태_201301_201312.csv,96383,1,1,1,1,1,1,1,1,1,1,1,1

In [10]:
for fl in null_2013_df['file_list'].unique():
    print(f'{fl}',null_2013_df[null_2013_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2013_df.isnull().sum()

12시간강수량 [6596]
3시간기온 [96383]
6시간강수량 [14559]
습도 [96383]
풍속 [94171]
하늘상태 [96383]
--------------------

h_dong          0
file_list       0
file_name       0
file_length     0
1               0
2              25
3              49
4              25
5              25
6              24
7               0
8               0
9              24
10              0
11              0
12              0
dtype: int64

# 2014

In [11]:
df2014 = all_df[all_df['start'] == '201401']
df2014['file_name'] = './weather/' + df2014['file_name']
df2014.reset_index(inplace=True , drop=True)

null_2014_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2014_df['h_dong'] = df2014['h_dong']
null_2014_df['file_list'] = df2014['file_list']
null_2014_df['file_name'] = df2014['file_name']

for idx in null_2014_df.index:
    csv = pd.read_csv(null_2014_df['file_name'].loc[idx])
    null_2014_df.loc[idx, 'file_length'] = len(csv)
    null_2014_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2014_df.loc[idx , int(col[13:15])] = 1
null_2014_df

<ipython-input-11-ee5cf0c6cdbb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2014['file_name'] = './weather/' + df2014['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,3시간기온,./weather/강남동_3시간기온_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,6시간강수량,./weather/강남동_6시간강수량_201401_201412.csv,22634,1,1,1,1,1,1,NaN,1,1,1,1,1
2,강남동,습도,./weather/강남동_습도_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,풍속,./weather/강남동_풍속_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,하늘상태,./weather/강남동_하늘상태_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,후평3동,3시간기온,./weather/후평3동_3시간기온_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1
121,후평3동,6시간강수량,./weather/후평3동_6시간강수량_201401_201412.csv,22634,1,1,1,1,1,1,NaN,1,1,1,1,1
122,후평3동,습도,./weather/후평3동_습도_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,풍속,./weather/후평3동_풍속_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1
124,후평3동,하늘상태,./weather/후평3동_하늘상태_201401_201412.csv,52095,1,1,1,1,1,1,1,1,1,1,1,1

In [12]:
for fl in null_2014_df['file_list'].unique():
    print(f'{fl}',null_2014_df[null_2014_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2014_df.isnull().sum()

3시간기온 [52095]
6시간강수량 [22634]
습도 [52095]
풍속 [52095]
하늘상태 [52095]
--------------------

h_dong          0
file_list       0
file_name       0
file_length     0
1               0
2               0
3               0
4               0
5               0
6               0
7              25
8               0
9               0
10              0
11              0
12              0
dtype: int64

# 2015

In [13]:
df2015 = all_df[all_df['start'] == '201501']
df2015['file_name'] = './weather/' + df2015['file_name']
df2015.reset_index(inplace=True , drop=True)

null_2015_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2015_df['h_dong'] = df2015['h_dong']
null_2015_df['file_list'] = df2015['file_list']
null_2015_df['file_name'] = df2015['file_name']

for idx in null_2015_df.index:
    csv = pd.read_csv(null_2015_df['file_name'].loc[idx])
    null_2015_df.loc[idx, 'file_length'] = len(csv)
    null_2015_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2015_df.loc[idx , int(col[13:15])] = 1
null_2015_df

<ipython-input-13-38865a67b71a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2015['file_name'] = './weather/' + df2015['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,3시간기온,./weather/강남동_3시간기온_201501_201512.csv,52530,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,6시간강수량,./weather/강남동_6시간강수량_201501_201512.csv,26980,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,습도,./weather/강남동_습도_201501_201512.csv,52198,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,풍속,./weather/강남동_풍속_201501_201512.csv,52530,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,하늘상태,./weather/강남동_하늘상태_201501_201512.csv,52530,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,후평3동,3시간기온,./weather/후평3동_3시간기온_201501_201512.csv,52530,1,1,1,1,1,1,1,1,1,1,1,1
121,후평3동,6시간강수량,./weather/후평3동_6시간강수량_201501_201512.csv,26980,1,1,1,1,1,1,1,1,1,1,1,1
122,후평3동,습도,./weather/후평3동_습도_201501_201512.csv,52198,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,풍속,./weather/후평3동_풍속_201501_201512.csv,52530,1,1,1,1,1,1,1,1,1,1,1,1
124,후평3동,하늘상태,./weather/후평3동_하늘상태_201501_201512.csv,52530,1,1,1,1,1,1,1,1,1,1,1,1

In [14]:
for fl in null_2015_df['file_list'].unique():
    print(f'{fl}',null_2015_df[null_2015_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2015_df.isnull().sum()

3시간기온 [52530]
6시간강수량 [26980]
습도 [52198]
풍속 [52530]
하늘상태 [52530]
--------------------

h_dong         0
file_list      0
file_name      0
file_length    0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0
10             0
11             0
12             0
dtype: int64

# 2016

In [15]:
df2016 = all_df[all_df['start'] == '201601']
df2016['file_name'] = './weather/' + df2016['file_name']
df2016.reset_index(inplace=True , drop=True)

null_2016_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2016_df['h_dong'] = df2016['h_dong']
null_2016_df['file_list'] = df2016['file_list']
null_2016_df['file_name'] = df2016['file_name']

for idx in null_2016_df.index:
    csv = pd.read_csv(null_2016_df['file_name'].loc[idx])
    null_2016_df.loc[idx, 'file_length'] = len(csv)
    null_2016_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2016_df.loc[idx , int(col[13:15])] = 1
null_2016_df

<ipython-input-15-56b98bfd6c4f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2016['file_name'] = './weather/' + df2016['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,3시간기온,./weather/강남동_3시간기온_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,6시간강수량,./weather/강남동_6시간강수량_201601_201612.csv,55655,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,강수형태,./weather/강남동_강수형태_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,습도,./weather/강남동_습도_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,풍속,./weather/강남동_풍속_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,후평3동,3시간기온,./weather/후평3동_3시간기온_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1
117,후평3동,6시간강수량,./weather/후평3동_6시간강수량_201601_201612.csv,55655,1,1,1,1,1,1,1,1,1,1,1,1
118,후평3동,강수형태,./weather/후평3동_강수형태_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1
119,후평3동,습도,./weather/후평3동_습도_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1
120,후평3동,풍속,./weather/후평3동_풍속_201601_201612.csv,108359,1,1,1,1,1,1,1,1,1,1,1,1

In [16]:
for fl in null_2016_df['file_list'].unique():
    print(f'{fl}',null_2016_df[null_2016_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2016_df.isnull().sum()

3시간기온 [108359]
6시간강수량 [55655]
강수형태 [108359]
습도 [108359]
풍속 [108359]
하늘상태 [99181]
--------------------

h_dong          0
file_list       0
file_name       0
file_length     0
1               0
2              16
3               0
4               0
5               0
6               0
7               0
8               0
9               0
10              0
11              0
12              0
dtype: int64

# 2017

In [17]:
df2017 = all_df[all_df['start'] == '201701']
df2017['file_name'] = './weather/' + df2017['file_name']
df2017.reset_index(inplace=True , drop=True)

null_2017_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2017_df['h_dong'] = df2017['h_dong']
null_2017_df['file_list'] = df2017['file_list']
null_2017_df['file_name'] = df2017['file_name']

for idx in null_2017_df.index:
    csv = pd.read_csv(null_2017_df['file_name'].loc[idx])
    null_2017_df.loc[idx, 'file_length'] = len(csv)
    null_2017_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2017_df.loc[idx , int(col[13:15])] = 1
null_2017_df

<ipython-input-17-89f16183d148>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2017['file_name'] = './weather/' + df2017['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,3시간기온,./weather/강남동_3시간기온_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,6시간강수량,./weather/강남동_6시간강수량_201701_201712.csv,27751,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,강수형태,./weather/강남동_강수형태_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,습도,./weather/강남동_습도_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,풍속,./weather/강남동_풍속_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,후평3동,3시간기온,./weather/후평3동_3시간기온_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
121,후평3동,6시간강수량,./weather/후평3동_6시간강수량_201701_201712.csv,27751,1,1,1,1,1,1,1,1,1,1,1,1
122,후평3동,강수형태,./weather/후평3동_강수형태_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,습도,./weather/후평3동_습도_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
124,후평3동,풍속,./weather/후평3동_풍속_201701_201712.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1

In [18]:
for fl in null_2017_df['file_list'].unique():
    print(f'{fl}',null_2017_df[null_2017_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2017_df.isnull().sum()

3시간기온 [54031]
6시간강수량 [27751]
강수형태 [54031]
습도 [54031]
풍속 [54031]
--------------------

h_dong         0
file_list      0
file_name      0
file_length    0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0
10             0
11             0
12             0
dtype: int64

# 2018

In [19]:
df2018 = all_df[all_df['start'] == '201801']
df2018['file_name'] = './weather/' + df2018['file_name']
df2018.reset_index(inplace=True , drop=True)

null_2018_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2018_df['h_dong'] = df2018['h_dong']
null_2018_df['file_list'] = df2018['file_list']
null_2018_df['file_name'] = df2018['file_name']

for idx in null_2018_df.index:
    csv = pd.read_csv(null_2018_df['file_name'].loc[idx])
    null_2018_df.loc[idx, 'file_length'] = len(csv)
    null_2018_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2018_df.loc[idx , int(col[13:15])] = 1
null_2018_df

<ipython-input-19-d4bf0c5004b8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2018['file_name'] = './weather/' + df2018['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,3시간기온,./weather/강남동_3시간기온_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,6시간강수량,./weather/강남동_6시간강수량_201801_201812.csv,27751,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,강수형태,./weather/강남동_강수형태_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,습도,./weather/강남동_습도_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,풍속,./weather/강남동_풍속_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,후평3동,3시간기온,./weather/후평3동_3시간기온_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
121,후평3동,6시간강수량,./weather/후평3동_6시간강수량_201801_201812.csv,27751,1,1,1,1,1,1,1,1,1,1,1,1
122,후평3동,강수형태,./weather/후평3동_강수형태_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,습도,./weather/후평3동_습도_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
124,후평3동,풍속,./weather/후평3동_풍속_201801_201812.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1

In [20]:
for fl in null_2018_df['file_list'].unique():
    print(f'{fl}',null_2018_df[null_2018_df['file_list']== fl]['file_length'].unique())
print('-'*22)
null_2018_df.isnull().sum()

3시간기온 [54031]
6시간강수량 [27751]
강수형태 [54031]
습도 [54031]
풍속 [54031]
----------------------

h_dong         0
file_list      0
file_name      0
file_length    0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0
10             0
11             0
12             0
dtype: int64

# 2019

In [21]:
df2019 = all_df[all_df['start'] == '201901']
df2019['file_name'] = './weather/' + df2019['file_name']
df2019.reset_index(inplace=True , drop=True)

null_2019_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2019_df['h_dong'] = df2019['h_dong']
null_2019_df['file_list'] = df2019['file_list']
null_2019_df['file_name'] = df2019['file_name']

for idx in null_2019_df.index:
    csv = pd.read_csv(null_2019_df['file_name'].loc[idx])
    null_2019_df.loc[idx, 'file_length'] = len(csv)
    null_2019_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2019_df.loc[idx , int(col[13:15])] = 1
null_2019_df

<ipython-input-21-f62a3c681eeb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2019['file_name'] = './weather/' + df2019['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,3시간기온,./weather/강남동_3시간기온_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,6시간강수량,./weather/강남동_6시간강수량_201901_201912.csv,27751,1,1,1,1,1,1,1,1,1,1,1,1
2,강남동,강수형태,./weather/강남동_강수형태_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
3,강남동,습도,./weather/강남동_습도_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
4,강남동,풍속,./weather/강남동_풍속_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,후평3동,3시간기온,./weather/후평3동_3시간기온_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
121,후평3동,6시간강수량,./weather/후평3동_6시간강수량_201901_201912.csv,27751,1,1,1,1,1,1,1,1,1,1,1,1
122,후평3동,강수형태,./weather/후평3동_강수형태_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
123,후평3동,습도,./weather/후평3동_습도_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1
124,후평3동,풍속,./weather/후평3동_풍속_201901_201912.csv,54031,1,1,1,1,1,1,1,1,1,1,1,1

In [22]:
for fl in null_2019_df['file_list'].unique():
    print(f'{fl}',null_2019_df[null_2019_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2019_df.isnull().sum()

3시간기온 [54031]
6시간강수량 [27751]
강수형태 [54031]
습도 [54031]
풍속 [54031]
--------------------

h_dong         0
file_list      0
file_name      0
file_length    0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0
10             0
11             0
12             0
dtype: int64

# 2020

In [23]:
df2020 = all_df[all_df['start'] == '202001']
df2020['file_name'] = './weather/' + df2020['file_name']
df2020.reset_index(inplace=True , drop=True)

null_2020_df = pd.DataFrame(columns=['h_dong' , 'file_list','file_name','file_length',1,2,3,4,5,6,7,8,9,10,11,12])
null_2020_df['h_dong'] = df2020['h_dong']
null_2020_df['file_list'] = df2020['file_list']
null_2020_df['file_name'] = df2020['file_name']

for idx in null_2020_df.index:
    csv = pd.read_csv(null_2020_df['file_name'].loc[idx])
    null_2020_df.loc[idx, 'file_length'] = len(csv)
    null_2020_df.loc[idx , 1] = 1

    csv = csv[csv.columns[0]].unique()
    for col in csv[pd.Series(csv).str.contains('Start')]:
        null_2020_df.loc[idx , int(col[13:15])] = 1
null_2020_df

<ipython-input-23-139ee5ef1b93>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2020['file_name'] = './weather/' + df2020['file_name']

,h_dong,file_list,file_name,file_length,1,2,3,4,5,6,7,8,9,10,11,12
0,강남동,3시간기온,./weather/강남동_3시간기온_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1
1,강남동,강수형태,./weather/강남동_강수형태_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1
2,교동,3시간기온,./weather/교동_3시간기온_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1
3,교동,6시간강수량,./weather/교동_6시간강수량_202001_202012.csv,27827,1,1,1,1,1,1,1,1,1,1,1,1
4,교동,강수형태,./weather/교동_강수형태_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,후평3동,3시간기온,./weather/후평3동_3시간기온_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1
113,후평3동,6시간강수량,./weather/후평3동_6시간강수량_202001_202012.csv,27827,1,1,1,1,1,1,1,1,1,1,1,1
114,후평3동,강수형태,./weather/후평3동_강수형태_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1
115,후평3동,습도,./weather/후평3동_습도_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1
116,후평3동,풍속,./weather/후평3동_풍속_202001_202012.csv,54179,1,1,1,1,1,1,1,1,1,1,1,1

In [24]:
for fl in null_2020_df['file_list'].unique():
    print(f'{fl}',null_2020_df[null_2020_df['file_list']== fl]['file_length'].unique())
print('-'*20)
null_2020_df.isnull().sum()

3시간기온 [54179]
강수형태 [54179]
6시간강수량 [27827]
습도 [54179]
풍속 [54179]
--------------------

h_dong         0
file_list      0
file_name      0
file_length    0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0
10             0
11             0
12             0
dtype: int64