In [1]:
# jupyter notebook 전체화면으로 변경  
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [7]:
# load module
import os
#os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

import copy
import warnings
import torch
import optuna
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path
from tqdm import tqdm

import pytorch_lightning as pl
import seaborn as sns

from my_funs import *
from plot_round_cut import *


from itertools import product
from sklearn import metrics
from matplotlib import gridspec
from pytorch_lightning.callbacks import EarlyStopping, LearningRateMonitor
from pytorch_lightning.loggers import TensorBoardLogger


from pytorch_forecasting import Baseline, TemporalFusionTransformer, TimeSeriesDataSet , EncoderNormalizer , GroupNormalizer
from pytorch_forecasting.metrics import SMAPE, PoissonLoss, QuantileLoss
#from pytorch_forecasting.models.temporal_fusion_transformer.tuning import optimize_hyperparameters

#import tensorflow as tf 
import tensorboard as tb 
#tf.io.gfile = tb.compat.tensorflow_stub.io.gfile

import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
warnings.filterwarnings("ignore")  # avoid printing out absolute paths
plt.rcParams['font.family'] = 'NanumGothic'

dongs = ['강남동', '교  동', '근화동', '남  면', '남산면', '동  면', '동내면', '동산면', '북산면',
       '사북면', '서  면', '석사동', '소양동', '신동면', '신북읍', '신사우동', '약사명동', '조운동',
       '퇴계동', '효자1동', '후평1동']

In [ ]:
# epoch 100
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[0]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 100 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

In [9]:
# epoch 200
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[1]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 200 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
13        2        0.5  0.122061
4         1        0.5  0.122061
22        3        0.5  0.122061
2         1        0.3  0.119399
20        3        0.3  0.119399
11        2        0.3  0.119399
3         1        0.4  0.117588
21        3        0.4  0.117588
12        2        0.4  0.117588
10        2        0.2  0.106872
1         1        0.2  0.106872
19        3        0.2  0.106872
5         1        0.6  0.095826
23        3        0.6  0.095826
14        2        0.6  0.095826
18        3        0.1  0.093775
0         1        0.1  0.093775
9         2        0.1  0.093775
15        2        0.7  0.068088
6         1        0.7  0.068088
24        3        0.7  0.068088
16        2        0.8  0.013671
7         1        0.8  0.013671
25        3        0.8  0.013671
17        2        0.9  0.007018
8         1        0.9  0.007018
26        3        0.9  0.007018

In [10]:
# epoch 300
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[2]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 300 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
13        2        0.5  0.119918
4         1        0.5  0.119918
22        3        0.5  0.119918
2         1        0.3  0.119620
20        3        0.3  0.119620
11        2        0.3  0.119620
3         1        0.4  0.119025
21        3        0.4  0.119025
12        2        0.4  0.119025
5         1        0.6  0.110310
23        3        0.6  0.110310
14        2        0.6  0.110310
10        2        0.2  0.108515
1         1        0.2  0.108515
19        3        0.2  0.108515
18        3        0.1  0.092469
0         1        0.1  0.092469
9         2        0.1  0.092469
15        2        0.7  0.077275
6         1        0.7  0.077275
24        3        0.7  0.077275
16        2        0.8  0.048924
7         1        0.8  0.048924
25        3        0.8  0.048924
17        2        0.9  0.020450
8         1        0.9  0.020450
26        3        0.9  0.020450

In [11]:
# epoch 300
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[2]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 300 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
13        2        0.5  0.119918
4         1        0.5  0.119918
22        3        0.5  0.119918
2         1        0.3  0.119620
20        3        0.3  0.119620
11        2        0.3  0.119620
3         1        0.4  0.119025
21        3        0.4  0.119025
12        2        0.4  0.119025
5         1        0.6  0.110310
23        3        0.6  0.110310
14        2        0.6  0.110310
10        2        0.2  0.108515
1         1        0.2  0.108515
19        3        0.2  0.108515
18        3        0.1  0.092469
0         1        0.1  0.092469
9         2        0.1  0.092469
15        2        0.7  0.077275
6         1        0.7  0.077275
24        3        0.7  0.077275
16        2        0.8  0.048924
7         1        0.8  0.048924
25        3        0.8  0.048924
17        2        0.9  0.020450
8         1        0.9  0.020450
26        3        0.9  0.020450

In [12]:
# epoch 400
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[3]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 400 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
3         1        0.4  0.118876
21        3        0.4  0.118876
12        2        0.4  0.118876
2         1        0.3  0.111427
20        3        0.3  0.111427
11        2        0.3  0.111427
1         1        0.2  0.103955
19        3        0.2  0.103955
10        2        0.2  0.103955
13        2        0.5  0.097440
4         1        0.5  0.097440
22        3        0.5  0.097440
18        3        0.1  0.087841
0         1        0.1  0.087841
9         2        0.1  0.087841
14        2        0.6  0.061659
5         1        0.6  0.061659
23        3        0.6  0.061659
15        2        0.7  0.033738
6         1        0.7  0.033738
24        3        0.7  0.033738
16        2        0.8  0.010438
7         1        0.8  0.010438
25        3        0.8  0.010438
17        2        0.9  0.007042
8         1        0.9  0.007042
26        3        0.9  0.007042

In [13]:
# epoch 500
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[4]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 500 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
3         1        0.4  0.138026
21        3        0.4  0.138026
12        2        0.4  0.138026
13        2        0.5  0.136351
4         1        0.5  0.136351
22        3        0.5  0.136351
2         1        0.3  0.125751
20        3        0.3  0.125751
11        2        0.3  0.125751
10        2        0.2  0.108946
1         1        0.2  0.108946
19        3        0.2  0.108946
5         1        0.6  0.094267
23        3        0.6  0.094267
14        2        0.6  0.094267
18        3        0.1  0.085538
0         1        0.1  0.085538
9         2        0.1  0.085538
15        2        0.7  0.075873
6         1        0.7  0.075873
24        3        0.7  0.075873
16        2        0.8  0.042450
7         1        0.8  0.042450
25        3        0.8  0.042450
17        2        0.9  0.023443
8         1        0.9  0.023443
26        3        0.9  0.023443

In [3]:
# epoch 600
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[5]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 600 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
2         1        0.3  0.125751
20        3        0.3  0.125751
11        2        0.3  0.125751
3         1        0.4  0.121951
21        3        0.4  0.121951
12        2        0.4  0.121951
10        2        0.2  0.107703
1         1        0.2  0.107703
19        3        0.2  0.107703
13        2        0.5  0.107252
4         1        0.5  0.107252
22        3        0.5  0.107252
5         1        0.6  0.090234
23        3        0.6  0.090234
14        2        0.6  0.090234
18        3        0.1  0.089913
0         1        0.1  0.089913
9         2        0.1  0.089913
15        2        0.7  0.032916
6         1        0.7  0.032916
24        3        0.7  0.032916
16        2        0.8  0.013671
7         1        0.8  0.013671
25        3        0.8  0.013671
17        2        0.9  0.010431
8         1        0.9  0.010431
26        3        0.9  0.010431

In [4]:
# epoch 700
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[6]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 700 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
3         1        0.4  0.110744
21        3        0.4  0.110744
12        2        0.4  0.110744
2         1        0.3  0.107292
20        3        0.3  0.107292
11        2        0.3  0.107292
1         1        0.2  0.104910
19        3        0.2  0.104910
10        2        0.2  0.104910
0         1        0.1  0.094512
18        3        0.1  0.094512
9         2        0.1  0.094512
22        3        0.5  0.089052
13        2        0.5  0.089052
4         1        0.5  0.089052
14        2        0.6  0.071473
5         1        0.6  0.071473
23        3        0.6  0.071473
15        2        0.7  0.050201
6         1        0.7  0.050201
24        3        0.7  0.050201
16        2        0.8  0.024055
7         1        0.8  0.024055
25        3        0.8  0.024055
17        2        0.9  0.013850
8         1        0.9  0.013850
26        3        0.9  0.013850

In [5]:
# epoch 800
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[7]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 800 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
2         1        0.3  0.122577
20        3        0.3  0.122577
11        2        0.3  0.122577
3         1        0.4  0.119919
21        3        0.4  0.119919
12        2        0.4  0.119919
1         1        0.2  0.105862
19        3        0.2  0.105862
10        2        0.2  0.105862
13        2        0.5  0.103557
4         1        0.5  0.103557
22        3        0.5  0.103557
18        3        0.1  0.086385
0         1        0.1  0.086385
9         2        0.1  0.086385
14        2        0.6  0.066385
5         1        0.6  0.066385
23        3        0.6  0.066385
15        2        0.7  0.046022
6         1        0.7  0.046022
24        3        0.7  0.046022
16        2        0.8  0.023842
7         1        0.8  0.023842
25        3        0.8  0.023842
17        2        0.9  0.017265
8         1        0.9  0.017265
26        3        0.9  0.017265

In [6]:
# epoch 900
setting = pd.read_csv('EPOCH_setting.csv')

funs = moving_average_alpha
factor = 0.2
cut_off = [1, 2, 3]
round_cut = np.arange(1,10)/ 10

f2_df = pd.DataFrame(product(cut_off, round_cut) , columns = ['cut_off' , 'round_cut'])

model_ckpt = setting['model_ckpt'].loc[8]
train_data = data_processing('../../train.csv' , factor , funs)
test_data = data_processing('../../test.csv' , factor, funs)
training = get_training(train_data,24, 24*7)
tft = TemporalFusionTransformer.load_from_checkpoint(model_ckpt)

for idx in f2_df.index:
    cut_off = f2_df['cut_off'].loc[idx]
    round_cut = f2_df['round_cut'].loc[idx]
    f2_df.loc[idx, 'f2_score'] = dong_f2_all(training, tft, test_data, cut_off, round_cut)
    #confusion_matrix_plot_round_cut(training, tft ,test_data, cut_off ,'강남동' , f'epoch 900 / cut_off {cut_off} / round_cut {round_cut}' , round_cut)
f2_df.sort_values(by = 'f2_score' ,  ascending=False)

    cut_off  round_cut  f2_score
3         1        0.4  0.132511
21        3        0.4  0.132511
12        2        0.4  0.132511
2         1        0.3  0.110837
20        3        0.3  0.110837
11        2        0.3  0.110837
13        2        0.5  0.108557
4         1        0.5  0.108557
22        3        0.5  0.108557
1         1        0.2  0.102443
19        3        0.2  0.102443
10        2        0.2  0.102443
18        3        0.1  0.089355
0         1        0.1  0.089355
9         2        0.1  0.089355
14        2        0.6  0.067609
5         1        0.6  0.067609
23        3        0.6  0.067609
15        2        0.7  0.016938
6         1        0.7  0.016938
24        3        0.7  0.016938
16        2        0.8  0.010497
7         1        0.8  0.010497
25        3        0.8  0.010497
17        2        0.9  0.000000
8         1        0.9  0.000000
26        3        0.9  0.000000