In [1]:
%config Completer.use_jedi = False

In [2]:
# resact function
import mariadb
import sys
import pandas as pd
import datetime
import itertools
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'NanumGothic'

In [3]:
# resact function
import mariadb
import sys
import pandas as pd
import datetime
import itertools
import numpy as np
import matplotlib.pyplot as plt

def get_csv(table_name, gugun='춘천시'):
    try:
        conn = mariadb.connect(
        user = "root",
        password = "133nplab",
        host = "localhost",
        port = 3306,
        database = "TC"
        )
    except mariadb.Error as e:
        print(e)
        
    cur = conn.cursor()
    sql_query = "SELECT * from " + table_name
    cur.execute(sql_query)
    rows = cur.fetchall()
    table_query = "DESC " + table_name
    cur.execute(table_query)
    schema = cur.fetchall()
    columns = [name[0] for name in schema]
    recs = [rec for rec in rows]
    df = pd.DataFrame(recs,columns=columns)
    del rows
    return df[df['OCC_GUGUN_NM']== gugun]
    
def Format(time):
    try:
        tmp = datetime.datetime.strptime(str(time),'%Y%m%d%H%M%f')
        d = datetime.date(tmp.year , tmp.month, tmp.day)
        t = datetime.time(tmp.hour, tmp.minute)
        return datetime.datetime.combine(d, t)
    except:
        tmp = datetime.datetime.strptime(str(time),'%Y-%m-%d %H%M%f')
        d = datetime.date(tmp.year , tmp.month, tmp.day)
        t = datetime.time(tmp.hour, tmp.minute)
        return datetime.datetime.combine(d, t)

def hourFormat(time):
    try:
        tmp = datetime.datetime.strptime(str(time),'%Y-%m-%d %H:%M:%f').replace(minute=0)
        return tmp
    except:
        tmp = datetime.datetime.strptime(str(time),'%Y%m%d%H%M%f').replace(minute=0)
        return tmp
    
    
adam = ['신북읍','동면','동산면','신동면','동내면','남면','남산면',
         '서면','사북면','북산면','소양동','교동','조운동','약사명동','근화동',
         '후평1동','후평2동','후평3동','효자1동','효자2동','효자3동','석사동','퇴계동','강남동','신사우동']

etc_h_dong = {'소양동' : ['소양로2가' , '소양로3가' , '소양로4가' , '봉의동' , '옥천동' , '요선동' , '낙원동' , '중앙로1가'],
              '신사우동' : ['사농동' , '신동' , '우두동'],
              '근화동' : ['소양로1가' ,'중도동'],
              '약사명동' : ['약사동' , '중앙로2가' , '중앙로3가' , '죽림동'],
              '조운동' : ['조양동' , '운교동'],
              '후평동' : ['후평1동' , '후평2동' , '후평3동'],
              '강남동' : ['삼천동' , '송암동' , '온의동' , '칠전동'],
              '효자1동' : ['효자동'],
              '효자2동' : ['효자동'],
              '효자3동' : ['효자동'],
              '후평1동' : ['후평동'],
              '후평2동' : ['후평동'],
              '후평3동' : ['후평동'],
             }
h_dong = ['신북읍', '동면', '동산면', '신동면', '동내면', '남면', '남산면', '서면', '사북면', '북산면', '소양동', '교동', '조운동', '약사명동', 
          '근화동', '후평1동', '후평2동', '후평3동', '효자1동', '효자2동', '효자3동', '석사동', '퇴계동', '강남동', '신사우동']

def get_h_dong(dong_nm):
    if dong_nm in h_dong:
        return dong_nm
    else:
        for key in etc_h_dong.keys():
            if dong_nm in etc_h_dong[key]: 
                return key
            
def nm_space(dong_nm):
    if len(dong_nm) == 2:
        return f'{dong_nm[0]}  {dong_nm[1]}'
    else:
        return dong_nm

# df에서 원하는 기간 선택
def df_count(start , end , df , time_columns):
    '''
    start = Format(20211201000000)
    end   = Format(20211215000000)
    '''
    start = Format(start)
    end   = Format(end)

    time_line = pd.date_range(start=start, end=end , freq='1h')  
    in_time = df[df['REG_DTIME'].isin(time_line)]
    return in_time , time_line

In [4]:
class processing_data():
    def __init__(self, gugun = '춘천시'):
        self.data = get_csv("tc_resact", gugun)
        self.data['h_dong'] = self.data['OCC_DONG_NM'].apply(lambda x : get_h_dong(x))
        self.data['h_dong'] = self.data['h_dong'].apply(lambda x : nm_space(x))
        for idx in self.data.index:
            self.data.loc[idx ,'REG_DTIME'] = self.data['DSP_DAY'].loc[idx] + self.data['DSP_TIME'].loc[idx]
        self.data['REG_DTIME'] = self.data['REG_DTIME'].apply(lambda x : hourFormat(x))
        self.data = self.data[['REG_DTIME' , 'ACT_DESC' , 'GUIDE', 'h_dong']]
        self.data.sort_values(by = 'REG_DTIME', inplace = True)
        
        
    def select_time(self, start = 20100101000000, end = 20220401000000):
        in_time , time_line = df_count(start, end , self.data , 'REG_DTIME' )
        
        in_time.sort_values(by = 'REG_DTIME', inplace = True)
        return in_time , time_line
    
    def get_count(self):
        in_time, time_line = self.select_time()
        time_line = pd.date_range('2010/01/01' , '2022/03/01', freq='1h')#.astype(str)
        h_dong_idx = in_time['h_dong'].unique()
        mulit_index = list(itertools.product(time_line , h_dong_idx))
        #print(mulit_index)
        count_df = pd.DataFrame(columns = ['REG_DTIME' , 'h_dong' , 'count' , 'ACT_DESC' , 'GUIDE'])
        IDX = 0
        SUM = 0
        for time , h_dong in mulit_index:
        
            df_idxs = (in_time['REG_DTIME'] == time) & (in_time['h_dong'] == h_dong)
            if sum(df_idxs) == 0:
                count_df.loc[IDX] = [time , h_dong ,sum(df_idxs) , None , None]
            else:
                count_df.loc[IDX] = [time , h_dong ,sum(df_idxs) , list(in_time[df_idxs]['ACT_DESC']) , list(in_time[df_idxs]['GUIDE'])]
                SUM += sum(df_idxs)
                print(f'\n ---------- {time} : {h_dong}   {SUM} ---------- \n')
            IDX += 1
        
        return count_df

            
    def get_resact(self, path = 'resact_count.csv'):
        df =  pd.read_csv(path)
        count_df = df[['REG_DTIME', 'h_dong' , 'count']]        
        self.count_df = count_df 
        return count_df
    
    def orgnal_count_plot(self , year):
        df = self.get_resact()
        dongs = df['h_dong'].unique()
        year_s = f'{year}/1/1/00'
        year_e = f'{year+1}/1/1/00'
        dt = pd.date_range(year_s ,year_e, freq='h')[:-1]        
        year_df = df[df['REG_DTIME'].isin(dt.astype(str))]
        f , axes = plt.subplots(21,1 , figsize=(20,66))
        x = range(len(year_df[year_df['h_dong'] == '강남동']['count']))
        for i,dong_nm in enumerate(df['h_dong'].unique()):
            year_dong_df = year_df[year_df['h_dong'] == dong_nm]['count']
            rat = len(year_dong_df[year_dong_df > 0]) / len(year_dong_df)
            axes[i].set_title(f'{dong_nm} count in {year} , ratio : {rat:.4f}')
            axes[i].scatter(x,year_dong_df , s=1)
        plt.show()

In [5]:
pdata  = processing_data()
data = pdata.get_count()

#pdata.orgnal_count_plot(2021)

<ipython-input-4-5634852b3d66>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  in_time.sort_values(by = 'REG_DTIME', inplace = True)

 ---------- 2010-01-01 00:00:00 : 석사동   1 ----------


 ---------- 2010-01-01 06:00:00 : 신동면   2 ----------


 ---------- 2010-01-01 09:00:00 : 강남동   3 ----------


 ---------- 2010-01-01 10:00:00 : 강남동   4 ----------


 ---------- 2010-01-01 10:00:00 : 서  면   5 ----------


 ---------- 2010-01-01 14:00:00 : 남  면   7 ----------


 ---------- 2010-01-02 13:00:00 : 서  면   9 ----------


 ---------- 2010-01-02 17:00:00 : 사북면   10 ----------


 ---------- 2010-01-02 19:00:00 : 동내면   11 ----------


 ---------- 2010-01-02 22:00:00 : 효자1동   12 ----------


 ---------- 2010-01-02 22:00:00 : 남산면   14 ----------


 ---------- 2010-01-03 06:00:00 : 남산면   15 ----------


 ---------- 2010-01-03 19:00:00 : 근화동   16 ----------


 ---------- 2010-01-03 23:00:00 : 효자1동   17 ----------


 ---------- 2010-01-04 10:00:00 : 신사우동   18 ----------


 ---------- 2010-01-04 11:00:00 : 남  면   21 ----------


 ---------- 2010-01-04 15:00:00 : 근화동   22 ----------


 ---------- 2010-01-04 16:00:00 : 근화동   24 ----------


 ---------- 2010-01-05 14:00:00 : 강남동   25 ----------


 ---------- 2010-01-05 16:00:00 : 신북읍   26 ----------


 ---------- 2010-01-07 11:00:00 : 효자1동   27 ----------


 ---------- 2010-01-07 16:00:00 : 소양동   28 ----------


 ---------- 2010-01-07 20:00:00 : 근화동   29 ----------


 ---------- 2010-01-08 11:00:00 : 강남동   30 ----------


 ---------- 2010-01-08 21:00:00 : 효자1동   32 ----------


 ---------- 2010-01-08 23:00:00 : 신사우동   33 ----------


 ---------- 2010-01-09 11:00:00 : 강남동   35 ----------


 ---------- 2010-01-10 05:00:00 : 석사동   37 ----------


 ---------- 2010-01-10 09:00:00 : 남산면   39 ----------


 ---------- 2010-01-10 09:00:00 : 약사명동   40 ----------


 ---------- 2010-01-10 16:00:00 : 소양동   41 ----------


 ---------- 2010-01-11 08:00:00 : 동내면   43 ----------


 ---------- 2010-01-11 09:00:00 : 동  면   44 ----------


 ---------- 2010-01-11 16:00:00 : 효자1동   45 ----------


 ---------- 2010-01-11 17:00:00 : 강남동   46 ----------


 ---------- 2010-01-11 18:00:00 : 후평1동   47 ----------


 ---------- 2010-01-12 13:00:00 : 신북읍   48 ----------


 ---------- 2010-01-12 15:00:00 : 사북면   49 ----------


 ---------- 2010-01-12 21:00:00 : 후평1동   50 ----------


 ---------- 2010-01-13 04:00:00 : 후평1동   51 ----------


 ---------- 2010-01-13 07:00:00 : 서  면   52 ----------


 ---------- 2010-01-13 08:00:00 : 효자1동   53 ----------


 ---------- 2010-01-13 09:00:00 : 신사우동   54 ----------


 ---------- 2010-01-13 12:00:00 : 동  면   55 ----------


 ---------- 2010-01-13 20:00:00 : 근화동   56 ----------


 ---------- 2010-01-15 02:00:00 : 강남동   57 ----------


 ---------- 2010-01-15 17:00:00 : 신북읍   58 ----------


 ---------- 2010-01-15 18:00:00 : 신동면   59 ----------


 ---------- 2010-01-16 03:00:00 : 효자1동   60 ----------


 ---------- 2010-01-16 08:00:00 : 퇴계동   61 ----------


 ---------- 2010-01-16 09:00:00 : 남산면   63 ----------


 ---------- 2010-01-16 13:00:00 : 남산면   65 ----------


 ---------- 2010-01-17 12:00:00 : 신북읍   66 ----------


 ---------- 2010-01-17 13:00:00 : 남산면   68 ----------


 ---------- 2010-01-17 13:00:00 : 소양동   69 ----------


 ---------- 2010-01-17 22:00:00 : 신북읍   70 ----------


 ---------- 2010-01-18 00:00:00 : 석사동   71 ----------


 ---------- 2010-01-18 14:00:00 : 소양동   72 ----------


 ---------- 2010-01-19 17:00:00 : 강남동   73 ----------


 ---------- 2010-01-20 02:00:00 : 효자1동   75 ----------


 ---------- 2010-01-20 07:00:00 : 후평1동   76 ----------


 ---------- 2010-01-20 20:00:00 : 후평1동   77 ----------


 ---------- 2010-01-20 23:00:00 : 근화동   78 ----------


 ---------- 2010-01-21 14:00:00 : 남산면   80 ----------


 ---------- 2010-01-22 09:00:00 : 소양동   81 ----------


 ---------- 2010-01-22 12:00:00 : 북산면   82 ----------


 ---------- 2010-01-22 19:00:00 : 효자1동   83 ----------


 ---------- 2010-01-22 22:00:00 : 퇴계동   84 ----------


 ---------- 2010-01-23 10:00:00 : 동내면   85 ----------


 ---------- 2010-01-23 10:00:00 : 신북읍   86 ----------


 ---------- 2010-01-23 22:00:00 : 후평1동   87 ----------


 ---------- 2010-01-24 09:00:00 : 서  면   88 ----------


 ---------- 2010-01-24 10:00:00 : 강남동   90 ----------


 ---------- 2010-01-24 10:00:00 : 남산면   92 ----------


 ---------- 2010-01-25 01:00:00 : 후평1동   93 ----------


 ---------- 2010-01-25 07:00:00 : 석사동   95 ----------


 ---------- 2010-01-25 23:00:00 : 조운동   96 ----------


 ---------- 2010-01-26 15:00:00 : 서  면   98 ----------


 ---------- 2010-01-27 09:00:00 : 후평1동   99 ----------


 ---------- 2010-01-27 14:00:00 : 석사동   100 ----------


 ---------- 2010-01-27 19:00:00 : 동내면   101 ----------


 ---------- 2010-01-27 21:00:00 : 신사우동   102 ----------


 ---------- 2010-01-28 00:00:00 : 후평1동   103 ----------


 ---------- 2010-01-28 07:00:00 : 신동면   104 ----------


 ---------- 2010-01-29 00:00:00 : 석사동   105 ----------


 ---------- 2010-01-29 03:00:00 : 석사동   106 ----------


 ---------- 2010-01-29 11:00:00 : 신사우동   107 ----------


 ---------- 2010-01-29 11:00:00 : 후평1동   108 ----------


 ---------- 2010-01-29 21:00:00 : 퇴계동   109 ----------


 ---------- 2010-01-30 02:00:00 : 강남동   110 ----------


 ---------- 2010-01-30 08:00:00 : 동  면   111 ----------


 ---------- 2010-01-30 09:00:00 : 남산면   113 ----------


 ---------- 2010-01-30 16:00:00 : 동산면   114 ----------


 ---------- 2010-01-30 17:00:00 : 남산면   116 ----------


 ---------- 2010-01-31 03:00:00 : 퇴계동   117 ----------


 ---------- 2010-01-31 05:00:00 : 동산면   118 ----------


 ---------- 2010-01-31 11:00:00 : 남산면   120 ----------


 ---------- 2010-01-31 12:00:00 : 남산면   121 ----------


 ---------- 2010-01-31 16:00:00 : 신동면   122 ----------


 ---------- 2010-01-31 17:00:00 : 신동면   123 ----------


 ---------- 2010-01-31 20:00:00 : 석사동   124 ----------


 ---------- 2010-02-01 03:00:00 : 효자1동   125 ----------


 ---------- 2010-02-01 04:00:00 : 퇴계동   126 ----------


 ---------- 2010-02-01 06:00:00 : 남  면   127 ----------


 ---------- 2010-02-01 18:00:00 : 석사동   128 ----------


 ---------- 2010-02-02 13:00:00 : 동  면   129 ----------


 ---------- 2010-02-03 10:00:00 : 근화동   130 ----------


 ---------- 2010-02-03 13:00:00 : 동내면   131 ----------


 ---------- 2010-02-03 18:00:00 : 서  면   132 ----------


 ---------- 2010-02-05 00:00:00 : 효자1동   133 ----------


 ---------- 2010-02-05 01:00:00 : 강남동   134 ----------


 ---------- 2010-02-05 17:00:00 : 효자1동   135 ----------


 ---------- 2010-02-05 20:00:00 : 서  면   136 ----------


 ---------- 2010-02-05 20:00:00 : 남산면   137 ----------


 ---------- 2010-02-05 21:00:00 : 후평1동   138 ----------


 ---------- 2010-02-06 04:00:00 : 효자1동   139 ----------


 ---------- 2010-02-06 14:00:00 : 신북읍   140 ----------


 ---------- 2010-02-06 20:00:00 : 서  면   141 ----------


 ---------- 2010-02-07 15:00:00 : 동산면   142 ----------


 ---------- 2010-02-07 21:00:00 : 남  면   143 ----------


 ---------- 2010-02-08 14:00:00 : 신사우동   144 ----------


 ---------- 2010-02-09 07:00:00 : 신동면   145 ----------


 ---------- 2010-02-09 09:00:00 : 동산면   146 ----------


 ---------- 2010-02-09 20:00:00 : 약사명동   147 ----------


 ---------- 2010-02-10 08:00:00 : 남산면   149 ----------


 ---------- 2010-02-10 10:00:00 : 조운동   150 ----------


 ---------- 2010-02-10 14:00:00 : 남산면   151 ----------


 ---------- 2010-02-11 13:00:00 : 동산면   152 ----------


 ---------- 2010-02-11 14:00:00 : 북산면   153 ----------


 ---------- 2010-02-11 20:00:00 : 석사동   154 ----------


 ---------- 2010-02-12 05:00:00 : 조운동   155 ----------


 ---------- 2010-02-12 18:00:00 : 약사명동   156 ----------


 ---------- 2010-02-13 07:00:00 : 후평1동   158 ----------


 ---------- 2010-02-13 08:00:00 : 신동면   160 ----------


 ---------- 2010-02-14 06:00:00 : 효자1동   161 ----------


 ---------- 2010-02-14 06:00:00 : 근화동   162 ----------


 ---------- 2010-02-14 19:00:00 : 석사동   163 ----------


 ---------- 2010-02-15 05:00:00 : 소양동   164 ----------


 ---------- 2010-02-15 11:00:00 : 강남동   165 ----------


 ---------- 2010-02-15 17:00:00 : 신사우동   166 ----------


 ---------- 2010-02-16 08:00:00 : 효자1동   167 ----------


 ---------- 2010-02-16 18:00:00 : 퇴계동   168 ----------

 ---------- 2010-02-17 10:00:00 : 근화동   169 ----------


 ---------- 2010-02-17 16:00:00 : 서  면   171 ----------


 ---------- 2010-02-17 20:00:00 : 약사명동   172 ----------


 ---------- 2010-02-18 00:00:00 : 남산면   173 ----------


 ---------- 2010-02-18 19:00:00 : 남  면   175 ----------


 ---------- 2010-02-19 02:00:00 : 석사동   176 ----------


 ---------- 2010-02-19 19:00:00 : 근화동   177 ----------


 ---------- 2010-02-19 21:00:00 : 근화동   178 ----------


 ---------- 2010-02-20 01:00:00 : 석사동   179 ----------


 ---------- 2010-02-20 08:00:00 : 신사우동   180 ----------


 ---------- 2010-02-20 09:00:00 : 신사우동   181 ----------


 ---------- 2010-02-20 11:00:00 : 강남동   182 ----------


 ---------- 2010-02-21 04:00:00 : 후평1동   183 ----------


 ---------- 2010-02-21 22:00:00 : 석사동   184 ----------


 ---------- 2010-02-22 10:00:00 : 북산면   185 ----------


 ---------- 2010-02-22 12:00:00 : 후평1동   186 ----------


 ---------- 2010-02-22 16:00:00 : 남산면   187 ----------


 ---------- 2010-02-22 18:00:00 : 소양동   188 ----------


 ---------- 2010-02-23 09:00:00 : 신사우동   189 ----------


 ---------- 2010-02-23 12:00:00 : 석사동   190 ----------


 ---------- 2010-02-23 14:00:00 : 퇴계동   191 ----------


 ---------- 2010-02-23 19:00:00 : 효자1동   192 ----------


 ---------- 2010-02-24 06:00:00 : 조운동   194 ----------


 ---------- 2010-02-24 07:00:00 : 동내면   195 ----------


 ---------- 2010-02-24 13:00:00 : 남산면   196 ----------


 ---------- 2010-02-24 15:00:00 : 동산면   197 ----------


 ---------- 2010-02-24 19:00:00 : 신북읍   198 ----------


 ---------- 2010-02-24 22:00:00 : 신사우동   199 ----------


 ---------- 2010-02-25 02:00:00 : 소양동   200 ----------


 ---------- 2010-02-25 02:00:00 : 후평1동   201 ----------


 ---------- 2010-02-25 20:00:00 : 석사동   202 ----------


 ---------- 2010-02-25 21:00:00 : 후평1동   203 ----------


 ---------- 2010-02-25 22:00:00 : 효자1동   204 ----------


 ---------- 2010-02-27 13:00:00 : 근화동   205 ----------


 ---------- 2010-02-28 17:00:00 : 퇴계동   206 ----------


 ---------- 2010-02-28 23:00:00 : 북산면   207 ----------


 ---------- 2010-03-01 08:00:00 : 효자1동   208 ----------


 ---------- 2010-03-02 06:00:00 : 동내면   209 ----------


 ---------- 2010-03-02 09:00:00 : 남산면   210 ----------


 ---------- 2010-03-02 10:00:00 : 동  면   211 ----------


 ---------- 2010-03-02 12:00:00 : 후평1동   212 ----------


 ---------- 2010-03-02 21:00:00 : 남산면   214 ----------


 ---------- 2010-03-03 04:00:00 : 신북읍   215 ----------


 ---------- 2010-03-03 07:00:00 : 신사우동   216 ----------


 ---------- 2010-03-04 19:00:00 : 효자1동   217 ----------


 ---------- 2010-03-05 09:00:00 : 근화동   218 ----------


 ---------- 2010-03-05 12:00:00 : 후평1동   219 ----------


 ---------- 2010-03-06 08:00:00 : 조운동   220 ----------


 ---------- 2010-03-06 15:00:00 : 신사우동   221 ----------


 ---------- 2010-03-08 10:00:00 : 퇴계동   222 ----------


 ---------- 2010-03-09 00:00:00 : 동  면   223 ----------


 ---------- 2010-03-09 11:00:00 : 남산면   224 ----------


 ---------- 2010-03-09 16:00:00 : 동산면   225 ----------


 ---------- 2010-03-10 04:00:00 : 효자1동   226 ----------


 ---------- 2010-03-10 10:00:00 : 동산면   227 ----------


 ---------- 2010-03-10 16:00:00 : 약사명동   228 ----------


 ---------- 2010-03-10 19:00:00 : 후평1동   230 ----------


 ---------- 2010-03-11 08:00:00 : 후평1동   231 ----------


 ---------- 2010-03-11 15:00:00 : 후평1동   232 ----------


 ---------- 2010-03-12 10:00:00 : 신북읍   233 ----------


 ---------- 2010-03-12 12:00:00 : 효자1동   234 ----------


 ---------- 2010-03-12 12:00:00 : 약사명동   235 ----------


 ---------- 2010-03-12 13:00:00 : 조운동   236 ----------


 ---------- 2010-03-12 19:00:00 : 약사명동   237 ----------


 ---------- 2010-03-13 16:00:00 : 효자1동   238 ----------


 ---------- 2010-03-13 22:00:00 : 동  면   239 ----------


 ---------- 2010-03-14 05:00:00 : 동내면   240 ----------


 ---------- 2010-03-14 12:00:00 : 신동면   241 ----------


 ---------- 2010-03-14 17:00:00 : 신북읍   242 ----------


 ---------- 2010-03-15 18:00:00 : 후평1동   243 ----------


 ---------- 2010-03-15 23:00:00 : 후평1동   244 ----------


 ---------- 2010-03-16 03:00:00 : 효자1동   245 ----------


 ---------- 2010-03-16 12:00:00 : 효자1동   246 ----------


 ---------- 2010-03-16 12:00:00 : 남산면   247 ----------


 ---------- 2010-03-16 13:00:00 : 서  면   248 ----------


 ---------- 2010-03-16 13:00:00 : 남산면   249 ----------


 ---------- 2010-03-16 18:00:00 : 신북읍   250 ----------


 ---------- 2010-03-16 21:00:00 : 후평1동   251 ----------


 ---------- 2010-03-17 13:00:00 : 서  면   252 ----------


 ---------- 2010-03-17 19:00:00 : 석사동   253 ----------


 ---------- 2010-03-17 19:00:00 : 강남동   254 ----------


 ---------- 2010-03-17 22:00:00 : 남  면   256 ----------


 ---------- 2010-03-18 09:00:00 : 효자1동   257 ----------


 ---------- 2010-03-18 15:00:00 : 후평1동   258 ----------


 ---------- 2010-03-18 21:00:00 : 효자1동   259 ----------


 ---------- 2010-03-18 23:00:00 : 동산면   261 ----------


 ---------- 2010-03-19 05:00:00 : 약사명동   262 ----------


 ---------- 2010-03-19 07:00:00 : 퇴계동   263 ----------


 ---------- 2010-03-19 09:00:00 : 효자1동   264 ----------


 ---------- 2010-03-19 15:00:00 : 강남동   266 ----------


 ---------- 2010-03-19 16:00:00 : 석사동   267 ----------


 ---------- 2010-03-20 09:00:00 : 소양동   268 ----------


 ---------- 2010-03-20 18:00:00 : 강남동   269 ----------


 ---------- 2010-03-21 10:00:00 : 석사동   270 ----------


 ---------- 2010-03-22 15:00:00 : 남산면   272 ----------


 ---------- 2010-03-22 18:00:00 : 약사명동   273 ----------


 ---------- 2010-03-22 19:00:00 : 동내면   274 ----------


 ---------- 2010-03-23 10:00:00 : 석사동   275 ----------


 ---------- 2010-03-23 13:00:00 : 근화동   276 ----------


 ---------- 2010-03-23 14:00:00 : 효자1동   277 ----------


 ---------- 2010-03-23 22:00:00 : 강남동   278 ----------


 ---------- 2010-03-23 22:00:00 : 근화동   279 ----------


 ---------- 2010-03-24 07:00:00 : 효자1동   280 ----------


 ---------- 2010-03-24 09:00:00 : 후평1동   281 ----------


 ---------- 2010-03-24 16:00:00 : 효자1동   282 ----------


 ---------- 2010-03-24 18:00:00 : 퇴계동   283 ----------


 ---------- 2010-03-24 22:00:00 : 신북읍   284 ----------


 ---------- 2010-03-25 09:00:00 : 동내면   286 ----------


 ---------- 2010-03-25 21:00:00 : 후평1동   287 ----------


 ---------- 2010-03-26 11:00:00 : 석사동   288 ----------


 ---------- 2010-03-26 14:00:00 : 남산면   290 ----------


 ---------- 2010-03-26 15:00:00 : 퇴계동   291 ----------


 ---------- 2010-03-26 18:00:00 : 효자1동   292 ----------


 ---------- 2010-03-26 19:00:00 : 소양동   293 ----------


 ---------- 2010-03-27 16:00:00 : 남산면   295 ----------


 ---------- 2010-03-28 11:00:00 : 남  면   296 ----------


 ---------- 2010-03-28 12:00:00 : 서  면   297 ----------


 ---------- 2010-03-28 15:00:00 : 퇴계동   298 ----------


 ---------- 2010-03-28 22:00:00 : 근화동   299 ----------


 ---------- 2010-03-29 02:00:00 : 퇴계동   300 ----------


 ---------- 2010-03-29 11:00:00 : 동산면   302 ----------


 ---------- 2010-03-29 13:00:00 : 후평1동   303 ----------


 ---------- 2010-03-29 19:00:00 : 동산면   304 ----------


 ---------- 2010-03-30 14:00:00 : 효자1동   305 ----------


 ---------- 2010-03-31 09:00:00 : 후평1동   306 ----------


 ---------- 2010-03-31 10:00:00 : 석사동   307 ----------


 ---------- 2010-03-31 21:00:00 : 신북읍   308 ----------


 ---------- 2010-04-01 03:00:00 : 약사명동   309 ----------


 ---------- 2010-04-01 06:00:00 : 사북면   310 ----------


 ---------- 2010-04-02 02:00:00 : 교  동   311 ----------


 ---------- 2010-04-02 04:00:00 : 조운동   312 ----------


 ---------- 2010-04-02 16:00:00 : 동산면   313 ----------


 ---------- 2010-04-02 17:00:00 : 강남동   314 ----------


 ---------- 2010-04-02 17:00:00 : 후평1동   315 ----------


 ---------- 2010-04-02 18:00:00 : 동내면   316 ----------


 ---------- 2010-04-03 00:00:00 : 후평1동   317 ----------


 ---------- 2010-04-03 10:00:00 : 신북읍   318 ----------


 ---------- 2010-04-03 15:00:00 : 후평1동   319 ----------


 ---------- 2010-04-04 02:00:00 : 동  면   320 ----------


 ---------- 2010-04-05 01:00:00 : 후평1동   321 ----------


 ---------- 2010-04-05 13:00:00 : 약사명동   322 ----------

 ---------- 2010-04-06 13:00:00 : 남산면   323 ----------


 ---------- 2010-04-06 13:00:00 : 퇴계동   324 ----------


 ---------- 2010-04-06 14:00:00 : 후평1동   325 ----------


 ---------- 2010-04-07 00:00:00 : 사북면   326 ----------


 ---------- 2010-04-07 14:00:00 : 남  면   328 ----------


 ---------- 2010-04-08 14:00:00 : 퇴계동   329 ----------


 ---------- 2010-04-08 17:00:00 : 후평1동   330 ----------


 ---------- 2010-04-08 23:00:00 : 석사동   331 ----------


 ---------- 2010-04-09 17:00:00 : 신사우동   332 ----------


 ---------- 2010-04-09 21:00:00 : 효자1동   333 ----------


 ---------- 2010-04-10 04:00:00 : 근화동   334 ----------


 ---------- 2010-04-10 05:00:00 : 근화동   335 ----------


 ---------- 2010-04-10 08:00:00 : 석사동   336 ----------


 ---------- 2010-04-11 14:00:00 : 신북읍   337 ----------


 ---------- 2010-04-11 20:00:00 : 근화동   338 ----------


 ---------- 2010-04-12 18:00:00 : 퇴계동   339 ----------


 ---------- 2010-04-13 22:00:00 : 석사동   340 ----------


 ---------- 2010-04-14 10:00:00 : 동산면   341 ----------


 ---------- 2010-04-14 11:00:00 : 남산면   343 ----------


 ---------- 2010-04-14 15:00:00 : 근화동   344 ----------


 ---------- 2010-04-15 06:00:00 : 석사동   345 ----------


 ---------- 2010-04-15 12:00:00 : 동내면   346 ----------


 ---------- 2010-04-15 14:00:00 : 동내면   347 ----------


 ---------- 2010-04-15 17:00:00 : 효자1동   348 ----------


 ---------- 2010-04-15 18:00:00 : 석사동   349 ----------


 ---------- 2010-04-16 02:00:00 : 효자1동   350 ----------


 ---------- 2010-04-16 13:00:00 : 동  면   351 ----------


 ---------- 2010-04-16 13:00:00 : 퇴계동   352 ----------


 ---------- 2010-04-16 17:00:00 : 동내면   353 ----------


 ---------- 2010-04-17 07:00:00 : 후평1동   354 ----------


 ---------- 2010-04-17 08:00:00 : 북산면   356 ----------


 ---------- 2010-04-17 17:00:00 : 동내면   357 ----------


 ---------- 2010-04-17 18:00:00 : 동내면   358 ----------


 ---------- 2010-04-17 20:00:00 : 후평1동   359 ----------


 ---------- 2010-04-18 09:00:00 : 강남동   360 ----------


 ---------- 2010-04-18 13:00:00 : 후평1동   361 ----------


 ---------- 2010-04-18 15:00:00 : 서  면   362 ----------


 ---------- 2010-04-18 15:00:00 : 효자1동   363 ----------


 ---------- 2010-04-18 16:00:00 : 남산면   364 ----------


 ---------- 2010-04-18 17:00:00 : 강남동   365 ----------


 ---------- 2010-04-19 04:00:00 : 강남동   366 ----------


 ---------- 2010-04-19 11:00:00 : 남산면   368 ----------


 ---------- 2010-04-19 14:00:00 : 남  면   370 ----------


 ---------- 2010-04-19 21:00:00 : 남산면   371 ----------


 ---------- 2010-04-19 22:00:00 : 효자1동   372 ----------


 ---------- 2010-04-21 00:00:00 : 신사우동   373 ----------


 ---------- 2010-04-21 04:00:00 : 조운동   374 ----------


 ---------- 2010-04-21 05:00:00 : 후평1동   375 ----------


 ---------- 2010-04-21 11:00:00 : 효자1동   376 ----------


 ---------- 2010-04-21 18:00:00 : 퇴계동   377 ----------


 ---------- 2010-04-22 06:00:00 : 퇴계동   378 ----------


 ---------- 2010-04-22 09:00:00 : 석사동   379 ----------


 ---------- 2010-04-22 18:00:00 : 남산면   380 ----------


 ---------- 2010-04-22 22:00:00 : 퇴계동   381 ----------


 ---------- 2010-04-23 10:00:00 : 신사우동   382 ----------


 ---------- 2010-04-23 14:00:00 : 석사동   383 ----------


 ---------- 2010-04-23 14:00:00 : 신북읍   384 ----------


 ---------- 2010-04-23 22:00:00 : 효자1동   385 ----------


 ---------- 2010-04-24 05:00:00 : 서  면   386 ----------


 ---------- 2010-04-24 08:00:00 : 효자1동   388 ----------


 ---------- 2010-04-24 10:00:00 : 신동면   389 ----------


 ---------- 2010-04-24 10:00:00 : 동내면   390 ----------


 ---------- 2010-04-24 11:00:00 : 신동면   391 ----------


 ---------- 2010-04-24 14:00:00 : 신사우동   392 ----------


 ---------- 2010-04-24 14:00:00 : 퇴계동   393 ----------


 ---------- 2010-04-25 01:00:00 : 퇴계동   394 ----------


 ---------- 2010-04-25 12:00:00 : 동  면   395 ----------


 ---------- 2010-04-25 13:00:00 : 후평1동   396 ----------


 ---------- 2010-04-25 16:00:00 : 신사우동   397 ----------


 ---------- 2010-04-25 18:00:00 : 남산면   401 ----------


 ---------- 2010-04-26 00:00:00 : 소양동   402 ----------


 ---------- 2010-04-26 10:00:00 : 강남동   403 ----------


 ---------- 2010-04-26 16:00:00 : 신사우동   404 ----------


 ---------- 2010-04-26 21:00:00 : 석사동   405 ----------


 ---------- 2010-04-26 22:00:00 : 동  면   406 ----------


 ---------- 2010-04-26 23:00:00 : 신사우동   407 ----------


 ---------- 2010-04-27 04:00:00 : 신사우동   408 ----------


 ---------- 2010-04-27 11:00:00 : 강남동   409 ----------


 ---------- 2010-04-27 17:00:00 : 동산면   410 ----------


 ---------- 2010-04-27 18:00:00 : 동산면   412 ----------


 ---------- 2010-04-27 20:00:00 : 석사동   413 ----------


 ---------- 2010-04-27 22:00:00 : 효자1동   414 ----------


 ---------- 2010-04-28 09:00:00 : 서  면   415 ----------


 ---------- 2010-04-28 23:00:00 : 후평1동   416 ----------


 ---------- 2010-04-29 04:00:00 : 남  면   417 ----------


 ---------- 2010-04-29 08:00:00 : 남산면   418 ----------


 ---------- 2010-04-29 08:00:00 : 퇴계동   419 ----------


 ---------- 2010-04-30 08:00:00 : 사북면   420 ----------


 ---------- 2010-04-30 21:00:00 : 강남동   422 ----------


 ---------- 2010-04-30 21:00:00 : 조운동   423 ----------


 ---------- 2010-04-30 23:00:00 : 강남동   425 ----------


 ---------- 2010-05-01 05:00:00 : 석사동   426 ----------


 ---------- 2010-05-01 07:00:00 : 동내면   427 ----------


 ---------- 2010-05-01 17:00:00 : 남산면   429 ----------


 ---------- 2010-05-01 21:00:00 : 석사동   430 ----------


 ---------- 2010-05-01 23:00:00 : 동  면   431 ----------


 ---------- 2010-05-01 23:00:00 : 퇴계동   432 ----------


 ---------- 2010-05-02 02:00:00 : 후평1동   433 ----------


 ---------- 2010-05-02 12:00:00 : 동내면   434 ----------


 ---------- 2010-05-03 14:00:00 : 효자1동   435 ----------


 ---------- 2010-05-03 17:00:00 : 조운동   436 ----------


 ---------- 2010-05-03 20:00:00 : 후평1동   437 ----------


 ---------- 2010-05-03 22:00:00 : 석사동   438 ----------


 ---------- 2010-05-03 23:00:00 : 석사동   439 ----------


 ---------- 2010-05-04 11:00:00 : 남  면   440 ----------


 ---------- 2010-05-04 12:00:00 : 사북면   441 ----------


 ---------- 2010-05-04 15:00:00 : 신사우동   442 ----------


 ---------- 2010-05-05 02:00:00 : 근화동   443 ----------


 ---------- 2010-05-05 06:00:00 : 남산면   444 ----------


 ---------- 2010-05-05 13:00:00 : 서  면   445 ----------


 ---------- 2010-05-06 07:00:00 : 효자1동   446 ----------


 ---------- 2010-05-06 13:00:00 : 남산면   448 ----------


 ---------- 2010-05-07 13:00:00 : 효자1동   449 ----------


 ---------- 2010-05-07 17:00:00 : 효자1동   450 ----------


 ---------- 2010-05-07 18:00:00 : 사북면   451 ----------


 ---------- 2010-05-07 22:00:00 : 동내면   452 ----------


 ---------- 2010-05-08 00:00:00 : 퇴계동   453 ----------


 ---------- 2010-05-08 13:00:00 : 신동면   454 ----------


 ---------- 2010-05-08 17:00:00 : 소양동   455 ----------


 ---------- 2010-05-08 20:00:00 : 근화동   456 ----------


 ---------- 2010-05-09 08:00:00 : 신사우동   457 ----------


 ---------- 2010-05-09 10:00:00 : 북산면   458 ----------


 ---------- 2010-05-09 11:00:00 : 약사명동   459 ----------


 ---------- 2010-05-09 11:00:00 : 동산면   460 ----------


 ---------- 2010-05-09 17:00:00 : 퇴계동   461 ----------


 ---------- 2010-05-09 22:00:00 : 신사우동   462 ----------


 ---------- 2010-05-09 23:00:00 : 효자1동   463 ----------


 ---------- 2010-05-10 02:00:00 : 효자1동   464 ----------


 ---------- 2010-05-10 06:00:00 : 서  면   465 ----------


 ---------- 2010-05-10 10:00:00 : 효자1동   466 ----------


 ---------- 2010-05-10 12:00:00 : 조운동   467 ----------


 ---------- 2010-05-10 13:00:00 : 동산면   468 ----------


 ---------- 2010-05-10 16:00:00 : 효자1동   469 ----------


 ---------- 2010-05-10 17:00:00 : 남산면   470 ----------


 ---------- 2010-05-10 18:00:00 : 후평1동   471 ----------


 ---------- 2010-05-10 19:00:00 : 후평1동   472 ----------


 ---------- 2010-05-10 23:00:00 : 소양동   473 ----------


 ---------- 2010-05-11 17:00:00 : 남산면   474 ----------


 ---------- 2010-05-11 21:00:00 : 소양동   475 ----------


 ---------- 2010-05-12 00:00:00 : 석사동   476 ----------


 ---------- 2010-05-12 13:00:00 : 소양동   477 ----------

 ---------- 2010-05-12 17:00:00 : 남산면   478 ----------


 ---------- 2010-05-12 18:00:00 : 남산면   479 ----------


 ---------- 2010-05-12 23:00:00 : 효자1동   480 ----------


 ---------- 2010-05-13 13:00:00 : 신사우동   481 ----------


 ---------- 2010-05-13 15:00:00 : 후평1동   482 ----------


 ---------- 2010-05-14 14:00:00 : 신사우동   483 ----------


 ---------- 2010-05-14 20:00:00 : 남  면   484 ----------


 ---------- 2010-05-15 02:00:00 : 퇴계동   485 ----------


 ---------- 2010-05-15 09:00:00 : 동내면   486 ----------


 ---------- 2010-05-15 11:00:00 : 남산면   487 ----------


 ---------- 2010-05-16 02:00:00 : 동내면   488 ----------


 ---------- 2010-05-16 09:00:00 : 동내면   489 ----------


 ---------- 2010-05-16 14:00:00 : 북산면   492 ----------


 ---------- 2010-05-16 18:00:00 : 후평1동   493 ----------


 ---------- 2010-05-17 13:00:00 : 후평1동   494 ----------


 ---------- 2010-05-17 17:00:00 : 교  동   495 ----------


 ---------- 2010-05-17 22:00:00 : 남  면   496 ----------


 ---------- 2010-05-18 17:00:00 : 석사동   497 ----------


 ---------- 2010-05-18 23:00:00 : 신북읍   498 ----------


 ---------- 2010-05-19 00:00:00 : 소양동   499 ----------


 ---------- 2010-05-19 12:00:00 : 석사동   500 ----------


 ---------- 2010-05-19 14:00:00 : 신사우동   502 ----------


 ---------- 2010-05-19 19:00:00 : 후평1동   503 ----------


 ---------- 2010-05-19 21:00:00 : 강남동   504 ----------


 ---------- 2010-05-20 14:00:00 : 남산면   506 ----------


 ---------- 2010-05-20 23:00:00 : 남산면   507 ----------


 ---------- 2010-05-21 05:00:00 : 신사우동   508 ----------


 ---------- 2010-05-21 17:00:00 : 후평1동   509 ----------


 ---------- 2010-05-21 23:00:00 : 사북면   510 ----------


 ---------- 2010-05-22 01:00:00 : 동  면   511 ----------


 ---------- 2010-05-22 12:00:00 : 석사동   512 ----------


 ---------- 2010-05-22 22:00:00 : 퇴계동   513 ----------


 ---------- 2010-05-22 23:00:00 : 남  면   514 ----------


 ---------- 2010-05-23 09:00:00 : 후평1동   515 ----------


 ---------- 2010-05-23 16:00:00 : 남  면   517 ----------


 ---------- 2010-05-24 20:00:00 : 후평1동   519 ----------


 ---------- 2010-05-25 02:00:00 : 석사동   520 ----------


 ---------- 2010-05-25 07:00:00 : 동내면   521 ----------


 ---------- 2010-05-25 09:00:00 : 근화동   522 ----------


 ---------- 2010-05-25 10:00:00 : 강남동   523 ----------


 ---------- 2010-05-26 00:00:00 : 후평1동   524 ----------


 ---------- 2010-05-26 07:00:00 : 신사우동   525 ----------


 ---------- 2010-05-27 07:00:00 : 동산면   526 ----------


 ---------- 2010-05-27 17:00:00 : 근화동   527 ----------


 ---------- 2010-05-27 18:00:00 : 석사동   528 ----------


 ---------- 2010-05-28 00:00:00 : 강남동   529 ----------


 ---------- 2010-05-28 07:00:00 : 동산면   530 ----------


 ---------- 2010-05-28 09:00:00 : 사북면   532 ----------


 ---------- 2010-05-28 10:00:00 : 약사명동   533 ----------


 ---------- 2010-05-28 14:00:00 : 남산면   534 ----------


 ---------- 2010-05-28 20:00:00 : 신북읍   535 ----------


 ---------- 2010-05-29 04:00:00 : 사북면   536 ----------


 ---------- 2010-05-29 05:00:00 : 사북면   537 ----------


 ---------- 2010-05-29 06:00:00 : 석사동   539 ----------


 ---------- 2010-05-29 15:00:00 : 후평1동   540 ----------


 ---------- 2010-05-30 10:00:00 : 신북읍   541 ----------


 ---------- 2010-05-30 11:00:00 : 소양동   542 ----------


 ---------- 2010-05-30 13:00:00 : 신동면   544 ----------


 ---------- 2010-05-31 13:00:00 : 남산면   545 ----------


 ---------- 2010-05-31 15:00:00 : 신북읍   546 ----------


 ---------- 2010-05-31 16:00:00 : 효자1동   547 ----------


 ---------- 2010-05-31 22:00:00 : 후평1동   548 ----------


 ---------- 2010-05-31 23:00:00 : 효자1동   549 ----------


 ---------- 2010-06-01 00:00:00 : 효자1동   550 ----------


 ---------- 2010-06-01 00:00:00 : 퇴계동   551 ----------


 ---------- 2010-06-01 01:00:00 : 퇴계동   552 ----------


 ---------- 2010-06-01 07:00:00 : 근화동   553 ----------


 ---------- 2010-06-01 09:00:00 : 남산면   555 ----------


 ---------- 2010-06-01 13:00:00 : 소양동   556 ----------


 ---------- 2010-06-01 17:00:00 : 소양동   558 ----------


 ---------- 2010-06-01 22:00:00 : 효자1동   559 ----------


 ---------- 2010-06-02 05:00:00 : 후평1동   560 ----------


 ---------- 2010-06-02 06:00:00 : 신동면   561 ----------


 ---------- 2010-06-02 08:00:00 : 서  면   562 ----------


 ---------- 2010-06-02 19:00:00 : 동산면   563 ----------


 ---------- 2010-06-03 13:00:00 : 석사동   564 ----------


 ---------- 2010-06-03 17:00:00 : 서  면   566 ----------


 ---------- 2010-06-04 09:00:00 : 퇴계동   567 ----------


 ---------- 2010-06-04 10:00:00 : 효자1동   568 ----------


 ---------- 2010-06-04 17:00:00 : 서  면   569 ----------


 ---------- 2010-06-04 22:00:00 : 신사우동   570 ----------


 ---------- 2010-06-05 08:00:00 : 효자1동   571 ----------


 ---------- 2010-06-05 08:00:00 : 약사명동   572 ----------


 ---------- 2010-06-05 09:00:00 : 석사동   573 ----------


 ---------- 2010-06-05 11:00:00 : 신사우동   574 ----------


 ---------- 2010-06-05 14:00:00 : 남산면   575 ----------


 ---------- 2010-06-05 16:00:00 : 조운동   576 ----------


 ---------- 2010-06-05 17:00:00 : 남산면   578 ----------


 ---------- 2010-06-05 19:00:00 : 신동면   580 ----------


 ---------- 2010-06-05 19:00:00 : 퇴계동   581 ----------


 ---------- 2010-06-06 00:00:00 : 강남동   582 ----------


 ---------- 2010-06-06 02:00:00 : 석사동   583 ----------


 ---------- 2010-06-06 11:00:00 : 석사동   584 ----------


 ---------- 2010-06-06 20:00:00 : 후평1동   585 ----------


 ---------- 2010-06-06 21:00:00 : 신사우동   586 ----------


 ---------- 2010-06-06 21:00:00 : 후평1동   587 ----------


 ---------- 2010-06-07 00:00:00 : 동산면   588 ----------


 ---------- 2010-06-07 03:00:00 : 효자1동   589 ----------


 ---------- 2010-06-07 08:00:00 : 서  면   591 ----------


 ---------- 2010-06-07 12:00:00 : 남산면   592 ----------


 ---------- 2010-06-07 13:00:00 : 남산면   593 ----------


 ---------- 2010-06-07 18:00:00 : 근화동   594 ----------


 ---------- 2010-06-07 19:00:00 : 퇴계동   595 ----------


 ---------- 2010-06-08 08:00:00 : 석사동   596 ----------


 ---------- 2010-06-08 08:00:00 : 퇴계동   597 ----------


 ---------- 2010-06-08 19:00:00 : 신사우동   598 ----------


 ---------- 2010-06-08 20:00:00 : 소양동   599 ----------


 ---------- 2010-06-08 21:00:00 : 소양동   600 ----------


 ---------- 2010-06-08 22:00:00 : 효자1동   601 ----------


 ---------- 2010-06-09 00:00:00 : 효자1동   602 ----------


 ---------- 2010-06-09 01:00:00 : 신북읍   603 ----------


 ---------- 2010-06-09 17:00:00 : 신사우동   604 ----------


 ---------- 2010-06-10 12:00:00 : 남산면   606 ----------


 ---------- 2010-06-10 13:00:00 : 남  면   607 ----------


 ---------- 2010-06-11 07:00:00 : 후평1동   608 ----------


 ---------- 2010-06-11 12:00:00 : 남  면   609 ----------


 ---------- 2010-06-11 12:00:00 : 동산면   610 ----------


 ---------- 2010-06-11 18:00:00 : 석사동   611 ----------


 ---------- 2010-06-11 21:00:00 : 후평1동   612 ----------


 ---------- 2010-06-12 07:00:00 : 퇴계동   613 ----------


 ---------- 2010-06-12 13:00:00 : 약사명동   614 ----------


 ---------- 2010-06-12 16:00:00 : 후평1동   615 ----------


 ---------- 2010-06-12 22:00:00 : 남산면   616 ----------


 ---------- 2010-06-13 02:00:00 : 후평1동   617 ----------


 ---------- 2010-06-13 03:00:00 : 교  동   618 ----------


 ---------- 2010-06-13 04:00:00 : 퇴계동   619 ----------


 ---------- 2010-06-13 12:00:00 : 신사우동   620 ----------


 ---------- 2010-06-13 13:00:00 : 후평1동   621 ----------


 ---------- 2010-06-13 23:00:00 : 강남동   622 ----------


 ---------- 2010-06-14 06:00:00 : 신사우동   623 ----------


 ---------- 2010-06-14 14:00:00 : 동산면   624 ----------


 ---------- 2010-06-14 17:00:00 : 동내면   625 ----------


 ---------- 2010-06-15 10:00:00 : 퇴계동   626 ----------


 ---------- 2010-06-15 14:00:00 : 후평1동   627 ----------


 ---------- 2010-06-15 16:00:00 : 강남동   628 ----------


 ---------- 2010-06-15 23:00:00 : 퇴계동   629 ----------


 ---------- 2010-06-16 08:00:00 : 효자1동   630 ----------


 ---------- 2010-06-16 16:00:00 : 신동면   631 ----------


 ---------- 2010-06-16 17:00:00 : 후평1동   632 ----------


 ---------- 2010-06-16 21:00:00 : 교  동   633 ----------


 ---------- 2010-06-16 22:00:00 : 동  면   634 ----------

 ---------- 2010-06-17 13:00:00 : 조운동   635 ----------


 ---------- 2010-06-18 16:00:00 : 효자1동   636 ----------


 ---------- 2010-06-18 23:00:00 : 후평1동   637 ----------


 ---------- 2010-06-19 10:00:00 : 조운동   638 ----------


 ---------- 2010-06-19 11:00:00 : 강남동   639 ----------


 ---------- 2010-06-19 18:00:00 : 남  면   640 ----------


 ---------- 2010-06-19 20:00:00 : 퇴계동   641 ----------


 ---------- 2010-06-19 21:00:00 : 퇴계동   642 ----------


 ---------- 2010-06-19 22:00:00 : 후평1동   643 ----------


 ---------- 2010-06-20 13:00:00 : 퇴계동   644 ----------


 ---------- 2010-06-20 15:00:00 : 신북읍   645 ----------


 ---------- 2010-06-20 23:00:00 : 퇴계동   646 ----------


 ---------- 2010-06-21 07:00:00 : 소양동   647 ----------


 ---------- 2010-06-21 11:00:00 : 후평1동   648 ----------


 ---------- 2010-06-21 15:00:00 : 강남동   649 ----------


 ---------- 2010-06-22 03:00:00 : 석사동   650 ----------


 ---------- 2010-06-22 13:00:00 : 퇴계동   651 ----------


 ---------- 2010-06-22 20:00:00 : 효자1동   652 ----------


 ---------- 2010-06-23 03:00:00 : 신사우동   653 ----------


 ---------- 2010-06-23 17:00:00 : 강남동   654 ----------


 ---------- 2010-06-23 19:00:00 : 퇴계동   655 ----------


 ---------- 2010-06-24 10:00:00 : 서  면   656 ----------


 ---------- 2010-06-24 14:00:00 : 사북면   658 ----------


 ---------- 2010-06-24 16:00:00 : 신사우동   659 ----------


 ---------- 2010-06-25 11:00:00 : 신북읍   660 ----------


 ---------- 2010-06-25 12:00:00 : 남  면   661 ----------


 ---------- 2010-06-25 20:00:00 : 신사우동   662 ----------


 ---------- 2010-06-26 07:00:00 : 남  면   663 ----------


 ---------- 2010-06-26 22:00:00 : 소양동   664 ----------


 ---------- 2010-06-27 04:00:00 : 석사동   665 ----------


 ---------- 2010-06-27 08:00:00 : 동내면   666 ----------


 ---------- 2010-06-27 21:00:00 : 신사우동   667 ----------


 ---------- 2010-06-28 05:00:00 : 신사우동   668 ----------


 ---------- 2010-06-28 10:00:00 : 남  면   669 ----------


 ---------- 2010-06-28 11:00:00 : 퇴계동   670 ----------


 ---------- 2010-06-28 18:00:00 : 동산면   671 ----------


 ---------- 2010-06-28 23:00:00 : 강남동   672 ----------


 ---------- 2010-06-29 16:00:00 : 석사동   673 ----------


 ---------- 2010-06-29 16:00:00 : 신동면   674 ----------


 ---------- 2010-06-29 18:00:00 : 석사동   675 ----------


 ---------- 2010-06-29 20:00:00 : 석사동   676 ----------


 ---------- 2010-06-29 23:00:00 : 강남동   677 ----------


 ---------- 2010-06-30 06:00:00 : 석사동   678 ----------


 ---------- 2010-06-30 09:00:00 : 신북읍   679 ----------


 ---------- 2010-06-30 12:00:00 : 동내면   680 ----------


 ---------- 2010-06-30 13:00:00 : 석사동   681 ----------


 ---------- 2010-06-30 19:00:00 : 석사동   682 ----------


 ---------- 2010-06-30 19:00:00 : 근화동   683 ----------


 ---------- 2010-07-01 05:00:00 : 석사동   684 ----------


 ---------- 2010-07-01 07:00:00 : 근화동   685 ----------


 ---------- 2010-07-01 08:00:00 : 동산면   687 ----------


 ---------- 2010-07-01 12:00:00 : 퇴계동   688 ----------


 ---------- 2010-07-01 17:00:00 : 강남동   689 ----------


 ---------- 2010-07-01 17:00:00 : 신사우동   690 ----------


 ---------- 2010-07-02 00:00:00 : 조운동   691 ----------


 ---------- 2010-07-02 10:00:00 : 강남동   692 ----------


 ---------- 2010-07-02 19:00:00 : 조운동   693 ----------


 ---------- 2010-07-02 23:00:00 : 석사동   694 ----------


 ---------- 2010-07-03 00:00:00 : 후평1동   695 ----------


 ---------- 2010-07-03 01:00:00 : 후평1동   696 ----------


 ---------- 2010-07-03 12:00:00 : 조운동   698 ----------


 ---------- 2010-07-03 14:00:00 : 약사명동   699 ----------


 ---------- 2010-07-03 14:00:00 : 후평1동   700 ----------


 ---------- 2010-07-03 17:00:00 : 퇴계동   701 ----------


 ---------- 2010-07-03 19:00:00 : 신북읍   702 ----------


 ---------- 2010-07-03 20:00:00 : 신북읍   703 ----------


 ---------- 2010-07-04 03:00:00 : 소양동   704 ----------


 ---------- 2010-07-04 10:00:00 : 석사동   705 ----------


 ---------- 2010-07-04 11:00:00 : 동  면   706 ----------


 ---------- 2010-07-04 13:00:00 : 북산면   708 ----------


 ---------- 2010-07-04 18:00:00 : 효자1동   709 ----------


 ---------- 2010-07-04 19:00:00 : 신사우동   710 ----------


 ---------- 2010-07-05 08:00:00 : 강남동   711 ----------


 ---------- 2010-07-05 09:00:00 : 근화동   712 ----------


 ---------- 2010-07-05 20:00:00 : 사북면   713 ----------


 ---------- 2010-07-05 21:00:00 : 강남동   714 ----------


 ---------- 2010-07-06 11:00:00 : 동  면   715 ----------


 ---------- 2010-07-06 12:00:00 : 교  동   716 ----------


 ---------- 2010-07-06 15:00:00 : 신사우동   717 ----------


 ---------- 2010-07-06 17:00:00 : 강남동   719 ----------


 ---------- 2010-07-06 20:00:00 : 신북읍   720 ----------


 ---------- 2010-07-06 20:00:00 : 동  면   721 ----------


 ---------- 2010-07-07 01:00:00 : 퇴계동   722 ----------


 ---------- 2010-07-07 04:00:00 : 조운동   723 ----------


 ---------- 2010-07-07 05:00:00 : 효자1동   725 ----------


 ---------- 2010-07-07 11:00:00 : 남산면   726 ----------


 ---------- 2010-07-07 22:00:00 : 퇴계동   727 ----------


 ---------- 2010-07-08 01:00:00 : 강남동   728 ----------


 ---------- 2010-07-08 09:00:00 : 신사우동   729 ----------


 ---------- 2010-07-08 14:00:00 : 퇴계동   730 ----------


 ---------- 2010-07-08 16:00:00 : 남  면   732 ----------


 ---------- 2010-07-08 18:00:00 : 효자1동   733 ----------


 ---------- 2010-07-08 22:00:00 : 효자1동   734 ----------


 ---------- 2010-07-09 04:00:00 : 근화동   735 ----------


 ---------- 2010-07-09 08:00:00 : 남  면   736 ----------


 ---------- 2010-07-09 10:00:00 : 후평1동   737 ----------


 ---------- 2010-07-09 11:00:00 : 신동면   738 ----------


 ---------- 2010-07-09 11:00:00 : 신북읍   739 ----------


 ---------- 2010-07-09 13:00:00 : 퇴계동   740 ----------


 ---------- 2010-07-10 02:00:00 : 남산면   741 ----------


 ---------- 2010-07-10 13:00:00 : 신동면   742 ----------


 ---------- 2010-07-10 14:00:00 : 석사동   743 ----------


 ---------- 2010-07-10 19:00:00 : 후평1동   744 ----------


 ---------- 2010-07-10 21:00:00 : 조운동   745 ----------


 ---------- 2010-07-11 03:00:00 : 퇴계동   746 ----------


 ---------- 2010-07-11 06:00:00 : 서  면   747 ----------


 ---------- 2010-07-11 20:00:00 : 동산면   748 ----------


 ---------- 2010-07-12 00:00:00 : 근화동   749 ----------


 ---------- 2010-07-12 02:00:00 : 효자1동   750 ----------


 ---------- 2010-07-12 07:00:00 : 효자1동   751 ----------


 ---------- 2010-07-12 14:00:00 : 석사동   752 ----------


 ---------- 2010-07-12 15:00:00 : 남산면   753 ----------


 ---------- 2010-07-12 16:00:00 : 남산면   754 ----------


 ---------- 2010-07-12 18:00:00 : 퇴계동   755 ----------


 ---------- 2010-07-12 23:00:00 : 동내면   756 ----------


 ---------- 2010-07-13 00:00:00 : 효자1동   757 ----------


 ---------- 2010-07-13 01:00:00 : 효자1동   759 ----------


 ---------- 2010-07-13 02:00:00 : 효자1동   760 ----------


 ---------- 2010-07-13 07:00:00 : 효자1동   761 ----------


 ---------- 2010-07-13 11:00:00 : 남산면   762 ----------


 ---------- 2010-07-13 14:00:00 : 조운동   763 ----------


 ---------- 2010-07-13 15:00:00 : 석사동   764 ----------


 ---------- 2010-07-13 18:00:00 : 후평1동   765 ----------


 ---------- 2010-07-14 10:00:00 : 석사동   766 ----------


 ---------- 2010-07-14 17:00:00 : 효자1동   767 ----------


 ---------- 2010-07-14 17:00:00 : 동  면   768 ----------


 ---------- 2010-07-14 19:00:00 : 신사우동   769 ----------


 ---------- 2010-07-14 20:00:00 : 퇴계동   770 ----------


 ---------- 2010-07-15 00:00:00 : 남산면   772 ----------


 ---------- 2010-07-15 01:00:00 : 소양동   773 ----------


 ---------- 2010-07-15 08:00:00 : 석사동   774 ----------


 ---------- 2010-07-15 08:00:00 : 근화동   775 ----------


 ---------- 2010-07-15 20:00:00 : 석사동   776 ----------


 ---------- 2010-07-16 05:00:00 : 신사우동   777 ----------


 ---------- 2010-07-16 10:00:00 : 석사동   778 ----------


 ---------- 2010-07-16 13:00:00 : 사북면   780 ----------


 ---------- 2010-07-16 15:00:00 : 동산면   781 ----------


 ---------- 2010-07-16 18:00:00 : 조운동   782 ----------


 ---------- 2010-07-16 20:00:00 : 동산면   783 ----------


 ---------- 2010-07-16 22:00:00 : 근화동   784 ----------


 ---------- 2010-07-16 23:00:00 : 동내면   785 ----------

 ---------- 2010-07-17 11:00:00 : 동산면   786 ----------


 ---------- 2010-07-17 13:00:00 : 석사동   787 ----------


 ---------- 2010-07-17 19:00:00 : 동내면   788 ----------


 ---------- 2010-07-17 23:00:00 : 후평1동   789 ----------


 ---------- 2010-07-18 13:00:00 : 남산면   790 ----------


 ---------- 2010-07-18 15:00:00 : 후평1동   791 ----------


 ---------- 2010-07-18 19:00:00 : 석사동   792 ----------


 ---------- 2010-07-19 09:00:00 : 남  면   793 ----------


 ---------- 2010-07-19 09:00:00 : 후평1동   794 ----------


 ---------- 2010-07-19 09:00:00 : 퇴계동   795 ----------


 ---------- 2010-07-19 10:00:00 : 석사동   796 ----------


 ---------- 2010-07-19 12:00:00 : 신동면   797 ----------


 ---------- 2010-07-19 13:00:00 : 효자1동   798 ----------


 ---------- 2010-07-19 15:00:00 : 남산면   799 ----------


 ---------- 2010-07-19 19:00:00 : 동  면   800 ----------


 ---------- 2010-07-20 04:00:00 : 석사동   801 ----------


 ---------- 2010-07-20 08:00:00 : 남산면   803 ----------


 ---------- 2010-07-20 09:00:00 : 동내면   804 ----------


 ---------- 2010-07-20 09:00:00 : 퇴계동   805 ----------


 ---------- 2010-07-20 10:00:00 : 후평1동   806 ----------


 ---------- 2010-07-20 14:00:00 : 소양동   807 ----------


 ---------- 2010-07-20 16:00:00 : 남  면   808 ----------


 ---------- 2010-07-20 17:00:00 : 동  면   809 ----------


 ---------- 2010-07-20 22:00:00 : 동  면   810 ----------


 ---------- 2010-07-21 00:00:00 : 강남동   811 ----------


 ---------- 2010-07-21 01:00:00 : 강남동   812 ----------


 ---------- 2010-07-21 03:00:00 : 신동면   813 ----------


 ---------- 2010-07-21 09:00:00 : 남산면   814 ----------


 ---------- 2010-07-21 10:00:00 : 효자1동   815 ----------


 ---------- 2010-07-21 10:00:00 : 소양동   816 ----------


 ---------- 2010-07-21 11:00:00 : 효자1동   817 ----------


 ---------- 2010-07-21 13:00:00 : 동  면   818 ----------


 ---------- 2010-07-21 19:00:00 : 동내면   819 ----------


 ---------- 2010-07-22 08:00:00 : 동내면   820 ----------


 ---------- 2010-07-22 08:00:00 : 교  동   821 ----------


 ---------- 2010-07-22 12:00:00 : 동  면   822 ----------


 ---------- 2010-07-22 13:00:00 : 후평1동   823 ----------


 ---------- 2010-07-22 15:00:00 : 남산면   824 ----------


 ---------- 2010-07-22 20:00:00 : 동  면   825 ----------


 ---------- 2010-07-23 01:00:00 : 서  면   826 ----------


 ---------- 2010-07-23 07:00:00 : 효자1동   827 ----------


 ---------- 2010-07-23 11:00:00 : 동  면   829 ----------


 ---------- 2010-07-23 16:00:00 : 강남동   830 ----------


 ---------- 2010-07-23 18:00:00 : 석사동   831 ----------


 ---------- 2010-07-23 21:00:00 : 퇴계동   832 ----------


 ---------- 2010-07-24 10:00:00 : 동  면   834 ----------


 ---------- 2010-07-24 10:00:00 : 조운동   835 ----------


 ---------- 2010-07-24 11:00:00 : 서  면   836 ----------


 ---------- 2010-07-24 13:00:00 : 석사동   837 ----------


 ---------- 2010-07-24 13:00:00 : 근화동   838 ----------


 ---------- 2010-07-24 17:00:00 : 남산면   840 ----------


 ---------- 2010-07-24 18:00:00 : 근화동   841 ----------


 ---------- 2010-07-24 19:00:00 : 서  면   842 ----------


 ---------- 2010-07-24 23:00:00 : 신사우동   843 ----------


 ---------- 2010-07-25 02:00:00 : 석사동   844 ----------


 ---------- 2010-07-25 09:00:00 : 소양동   845 ----------


 ---------- 2010-07-25 10:00:00 : 남산면   846 ----------


 ---------- 2010-07-25 15:00:00 : 서  면   847 ----------


 ---------- 2010-07-25 15:00:00 : 북산면   849 ----------


 ---------- 2010-07-25 16:00:00 : 북산면   850 ----------


 ---------- 2010-07-25 21:00:00 : 남  면   852 ----------


 ---------- 2010-07-26 00:00:00 : 신북읍   853 ----------


 ---------- 2010-07-26 02:00:00 : 석사동   854 ----------


 ---------- 2010-07-26 10:00:00 : 남  면   855 ----------


 ---------- 2010-07-26 12:00:00 : 신북읍   856 ----------


 ---------- 2010-07-26 15:00:00 : 남산면   857 ----------


 ---------- 2010-07-27 00:00:00 : 효자1동   859 ----------


 ---------- 2010-07-27 05:00:00 : 신사우동   860 ----------


 ---------- 2010-07-27 05:00:00 : 동  면   861 ----------


 ---------- 2010-07-27 08:00:00 : 서  면   862 ----------


 ---------- 2010-07-27 09:00:00 : 퇴계동   863 ----------


 ---------- 2010-07-27 13:00:00 : 신동면   864 ----------


 ---------- 2010-07-27 15:00:00 : 석사동   865 ----------


 ---------- 2010-07-27 15:00:00 : 효자1동   866 ----------


 ---------- 2010-07-27 16:00:00 : 후평1동   867 ----------


 ---------- 2010-07-27 18:00:00 : 퇴계동   868 ----------


 ---------- 2010-07-28 13:00:00 : 석사동   871 ----------


 ---------- 2010-07-28 13:00:00 : 남산면   872 ----------


 ---------- 2010-07-28 14:00:00 : 효자1동   873 ----------


 ---------- 2010-07-28 14:00:00 : 남산면   874 ----------


 ---------- 2010-07-28 14:00:00 : 퇴계동   875 ----------


 ---------- 2010-07-28 17:00:00 : 효자1동   876 ----------


 ---------- 2010-07-28 20:00:00 : 소양동   877 ----------


 ---------- 2010-07-28 21:00:00 : 후평1동   878 ----------


 ---------- 2010-07-29 08:00:00 : 후평1동   879 ----------


 ---------- 2010-07-29 14:00:00 : 남  면   880 ----------


 ---------- 2010-07-29 14:00:00 : 동내면   881 ----------


 ---------- 2010-07-29 14:00:00 : 후평1동   882 ----------


 ---------- 2010-07-29 15:00:00 : 신북읍   883 ----------


 ---------- 2010-07-29 15:00:00 : 후평1동   884 ----------


 ---------- 2010-07-29 15:00:00 : 북산면   888 ----------


 ---------- 2010-07-29 22:00:00 : 동산면   889 ----------


 ---------- 2010-07-30 02:00:00 : 소양동   890 ----------


 ---------- 2010-07-30 08:00:00 : 신사우동   893 ----------


 ---------- 2010-07-30 09:00:00 : 동  면   894 ----------


 ---------- 2010-07-30 10:00:00 : 교  동   895 ----------


 ---------- 2010-07-30 11:00:00 : 근화동   896 ----------


 ---------- 2010-07-30 13:00:00 : 남산면   898 ----------


 ---------- 2010-07-30 13:00:00 : 조운동   899 ----------


 ---------- 2010-07-30 14:00:00 : 남산면   900 ----------


 ---------- 2010-07-30 15:00:00 : 남  면   901 ----------


 ---------- 2010-07-30 19:00:00 : 퇴계동   902 ----------


 ---------- 2010-07-31 08:00:00 : 신사우동   903 ----------


 ---------- 2010-07-31 13:00:00 : 근화동   904 ----------


 ---------- 2010-07-31 16:00:00 : 석사동   905 ----------


 ---------- 2010-07-31 16:00:00 : 서  면   906 ----------


 ---------- 2010-07-31 16:00:00 : 조운동   907 ----------


 ---------- 2010-07-31 17:00:00 : 신동면   908 ----------


 ---------- 2010-08-01 10:00:00 : 남산면   910 ----------


 ---------- 2010-08-01 13:00:00 : 남산면   911 ----------


 ---------- 2010-08-01 15:00:00 : 사북면   912 ----------


 ---------- 2010-08-01 17:00:00 : 강남동   913 ----------


 ---------- 2010-08-01 17:00:00 : 사북면   914 ----------


 ---------- 2010-08-02 06:00:00 : 후평1동   915 ----------


 ---------- 2010-08-02 06:00:00 : 북산면   916 ----------


 ---------- 2010-08-02 09:00:00 : 서  면   917 ----------


 ---------- 2010-08-02 09:00:00 : 신사우동   918 ----------


 ---------- 2010-08-02 10:00:00 : 사북면   919 ----------


 ---------- 2010-08-02 10:00:00 : 남산면   921 ----------


 ---------- 2010-08-02 10:00:00 : 소양동   922 ----------


 ---------- 2010-08-02 11:00:00 : 사북면   923 ----------


 ---------- 2010-08-02 11:00:00 : 신사우동   924 ----------


 ---------- 2010-08-02 13:00:00 : 사북면   926 ----------


 ---------- 2010-08-02 15:00:00 : 남산면   927 ----------


 ---------- 2010-08-02 15:00:00 : 근화동   928 ----------


 ---------- 2010-08-02 16:00:00 : 후평1동   929 ----------


 ---------- 2010-08-02 17:00:00 : 퇴계동   930 ----------


 ---------- 2010-08-02 18:00:00 : 근화동   931 ----------


 ---------- 2010-08-02 19:00:00 : 효자1동   932 ----------


 ---------- 2010-08-02 23:00:00 : 효자1동   933 ----------


 ---------- 2010-08-03 04:00:00 : 후평1동   934 ----------


 ---------- 2010-08-03 09:00:00 : 동내면   935 ----------


 ---------- 2010-08-03 10:00:00 : 석사동   936 ----------


 ---------- 2010-08-03 10:00:00 : 남산면   937 ----------


 ---------- 2010-08-03 13:00:00 : 남산면   938 ----------


 ---------- 2010-08-03 13:00:00 : 북산면   939 ----------


 ---------- 2010-08-03 17:00:00 : 효자1동   940 ----------


 ---------- 2010-08-03 18:00:00 : 석사동   941 ----------


 ---------- 2010-08-04 00:00:00 : 소양동   942 ----------


 ---------- 2010-08-04 10:00:00 : 북산면   943 ----------


 ---------- 2010-08-04 11:00:00 : 후평1동   944 ----------

 ---------- 2010-08-04 12:00:00 : 북산면   946 ----------


 ---------- 2010-08-04 13:00:00 : 신동면   947 ----------


 ---------- 2010-08-04 14:00:00 : 남  면   948 ----------


 ---------- 2010-08-04 17:00:00 : 후평1동   949 ----------


 ---------- 2010-08-05 06:00:00 : 약사명동   951 ----------


 ---------- 2010-08-05 08:00:00 : 신사우동   952 ----------


 ---------- 2010-08-05 09:00:00 : 석사동   953 ----------


 ---------- 2010-08-05 09:00:00 : 강남동   954 ----------


 ---------- 2010-08-05 11:00:00 : 동  면   955 ----------


 ---------- 2010-08-05 14:00:00 : 남산면   956 ----------


 ---------- 2010-08-05 15:00:00 : 후평1동   957 ----------


 ---------- 2010-08-05 21:00:00 : 강남동   959 ----------


 ---------- 2010-08-06 00:00:00 : 동내면   960 ----------


 ---------- 2010-08-06 01:00:00 : 남산면   961 ----------


 ---------- 2010-08-06 04:00:00 : 신북읍   962 ----------


 ---------- 2010-08-06 09:00:00 : 강남동   964 ----------


 ---------- 2010-08-06 09:00:00 : 동내면   965 ----------


 ---------- 2010-08-06 10:00:00 : 서  면   966 ----------


 ---------- 2010-08-06 16:00:00 : 후평1동   967 ----------


 ---------- 2010-08-06 18:00:00 : 퇴계동   968 ----------


 ---------- 2010-08-06 19:00:00 : 남산면   969 ----------


 ---------- 2010-08-06 19:00:00 : 신사우동   970 ----------


 ---------- 2010-08-06 21:00:00 : 후평1동   971 ----------


 ---------- 2010-08-07 05:00:00 : 신사우동   972 ----------


 ---------- 2010-08-07 09:00:00 : 신동면   973 ----------


 ---------- 2010-08-07 10:00:00 : 사북면   974 ----------


 ---------- 2010-08-07 10:00:00 : 소양동   975 ----------


 ---------- 2010-08-07 11:00:00 : 석사동   976 ----------


 ---------- 2010-08-07 11:00:00 : 소양동   977 ----------


 ---------- 2010-08-07 12:00:00 : 동내면   978 ----------


 ---------- 2010-08-07 12:00:00 : 동  면   979 ----------


 ---------- 2010-08-07 13:00:00 : 석사동   980 ----------


 ---------- 2010-08-07 13:00:00 : 소양동   981 ----------


 ---------- 2010-08-07 15:00:00 : 후평1동   982 ----------


 ---------- 2010-08-07 17:00:00 : 남산면   983 ----------


 ---------- 2010-08-08 13:00:00 : 후평1동   984 ----------


 ---------- 2010-08-08 14:00:00 : 서  면   985 ----------


 ---------- 2010-08-08 15:00:00 : 석사동   986 ----------


 ---------- 2010-08-08 16:00:00 : 사북면   988 ----------


 ---------- 2010-08-08 17:00:00 : 퇴계동   989 ----------


 ---------- 2010-08-08 18:00:00 : 소양동   990 ----------


 ---------- 2010-08-08 19:00:00 : 후평1동   991 ----------


 ---------- 2010-08-08 20:00:00 : 사북면   992 ----------


 ---------- 2010-08-09 09:00:00 : 약사명동   993 ----------


 ---------- 2010-08-09 12:00:00 : 소양동   994 ----------


 ---------- 2010-08-09 13:00:00 : 남산면   995 ----------


 ---------- 2010-08-09 13:00:00 : 동  면   996 ----------


 ---------- 2010-08-09 14:00:00 : 후평1동   997 ----------


 ---------- 2010-08-09 15:00:00 : 강남동   998 ----------


 ---------- 2010-08-09 15:00:00 : 서  면   999 ----------


 ---------- 2010-08-09 15:00:00 : 사북면   1000 ----------


 ---------- 2010-08-09 17:00:00 : 퇴계동   1001 ----------


 ---------- 2010-08-09 18:00:00 : 근화동   1002 ----------


 ---------- 2010-08-09 19:00:00 : 동내면   1003 ----------


 ---------- 2010-08-09 21:00:00 : 남산면   1005 ----------


 ---------- 2010-08-10 08:00:00 : 신동면   1006 ----------


 ---------- 2010-08-10 08:00:00 : 동내면   1007 ----------


 ---------- 2010-08-10 09:00:00 : 동내면   1008 ----------


 ---------- 2010-08-10 09:00:00 : 동산면   1009 ----------


 ---------- 2010-08-10 10:00:00 : 신동면   1010 ----------


 ---------- 2010-08-10 10:00:00 : 사북면   1011 ----------


 ---------- 2010-08-10 11:00:00 : 신동면   1013 ----------


 ---------- 2010-08-10 13:00:00 : 동  면   1014 ----------


 ---------- 2010-08-10 16:00:00 : 석사동   1015 ----------


 ---------- 2010-08-10 20:00:00 : 후평1동   1016 ----------


 ---------- 2010-08-10 22:00:00 : 사북면   1017 ----------


 ---------- 2010-08-10 22:00:00 : 후평1동   1018 ----------


 ---------- 2010-08-11 03:00:00 : 남산면   1019 ----------


 ---------- 2010-08-11 07:00:00 : 신북읍   1020 ----------


 ---------- 2010-08-11 07:00:00 : 퇴계동   1021 ----------


 ---------- 2010-08-11 08:00:00 : 서  면   1022 ----------


 ---------- 2010-08-11 09:00:00 : 신북읍   1023 ----------


 ---------- 2010-08-11 11:00:00 : 사북면   1024 ----------


 ---------- 2010-08-11 11:00:00 : 동내면   1025 ----------


 ---------- 2010-08-11 11:00:00 : 남산면   1026 ----------


 ---------- 2010-08-11 13:00:00 : 퇴계동   1027 ----------


 ---------- 2010-08-11 17:00:00 : 후평1동   1028 ----------


 ---------- 2010-08-12 01:00:00 : 신사우동   1029 ----------


 ---------- 2010-08-12 09:00:00 : 서  면   1031 ----------


 ---------- 2010-08-12 09:00:00 : 남산면   1032 ----------


 ---------- 2010-08-12 11:00:00 : 동내면   1033 ----------


 ---------- 2010-08-12 12:00:00 : 신사우동   1034 ----------


 ---------- 2010-08-12 13:00:00 : 신북읍   1035 ----------


 ---------- 2010-08-12 14:00:00 : 근화동   1036 ----------


 ---------- 2010-08-12 16:00:00 : 석사동   1037 ----------


 ---------- 2010-08-12 18:00:00 : 동산면   1038 ----------


 ---------- 2010-08-13 01:00:00 : 교  동   1039 ----------


 ---------- 2010-08-13 09:00:00 : 동내면   1041 ----------


 ---------- 2010-08-13 12:00:00 : 남산면   1042 ----------


 ---------- 2010-08-13 13:00:00 : 퇴계동   1043 ----------


 ---------- 2010-08-13 17:00:00 : 동내면   1044 ----------


 ---------- 2010-08-13 22:00:00 : 효자1동   1045 ----------


 ---------- 2010-08-13 23:00:00 : 남산면   1046 ----------


 ---------- 2010-08-14 01:00:00 : 효자1동   1047 ----------


 ---------- 2010-08-14 02:00:00 : 퇴계동   1048 ----------


 ---------- 2010-08-14 06:00:00 : 석사동   1049 ----------


 ---------- 2010-08-14 09:00:00 : 강남동   1051 ----------


 ---------- 2010-08-14 11:00:00 : 동  면   1053 ----------


 ---------- 2010-08-14 13:00:00 : 동  면   1054 ----------


 ---------- 2010-08-14 14:00:00 : 퇴계동   1055 ----------


 ---------- 2010-08-14 18:00:00 : 효자1동   1056 ----------


 ---------- 2010-08-14 22:00:00 : 신사우동   1057 ----------


 ---------- 2010-08-14 23:00:00 : 신동면   1058 ----------


 ---------- 2010-08-15 02:00:00 : 퇴계동   1059 ----------


 ---------- 2010-08-15 03:00:00 : 사북면   1060 ----------


 ---------- 2010-08-15 04:00:00 : 신북읍   1061 ----------


 ---------- 2010-08-15 10:00:00 : 강남동   1062 ----------


 ---------- 2010-08-15 10:00:00 : 후평1동   1063 ----------


 ---------- 2010-08-15 11:00:00 : 강남동   1064 ----------


 ---------- 2010-08-15 13:00:00 : 근화동   1065 ----------


 ---------- 2010-08-15 14:00:00 : 사북면   1067 ----------


 ---------- 2010-08-15 15:00:00 : 동  면   1068 ----------


 ---------- 2010-08-15 16:00:00 : 강남동   1069 ----------


 ---------- 2010-08-15 16:00:00 : 남산면   1070 ----------


 ---------- 2010-08-16 09:00:00 : 남  면   1071 ----------


 ---------- 2010-08-16 09:00:00 : 동내면   1072 ----------


 ---------- 2010-08-16 09:00:00 : 남산면   1073 ----------


 ---------- 2010-08-16 09:00:00 : 동  면   1074 ----------


 ---------- 2010-08-16 09:00:00 : 후평1동   1075 ----------


 ---------- 2010-08-16 13:00:00 : 근화동   1076 ----------


 ---------- 2010-08-16 13:00:00 : 동산면   1077 ----------


 ---------- 2010-08-16 14:00:00 : 동내면   1078 ----------


 ---------- 2010-08-16 14:00:00 : 후평1동   1079 ----------


 ---------- 2010-08-16 16:00:00 : 신사우동   1080 ----------


 ---------- 2010-08-16 18:00:00 : 동내면   1081 ----------


 ---------- 2010-08-16 18:00:00 : 조운동   1082 ----------


 ---------- 2010-08-16 22:00:00 : 강남동   1083 ----------


 ---------- 2010-08-17 09:00:00 : 신동면   1084 ----------


 ---------- 2010-08-17 10:00:00 : 남  면   1085 ----------


 ---------- 2010-08-17 10:00:00 : 동내면   1086 ----------


 ---------- 2010-08-17 11:00:00 : 강남동   1087 ----------


 ---------- 2010-08-17 11:00:00 : 동  면   1088 ----------


 ---------- 2010-08-17 12:00:00 : 신사우동   1089 ----------


 ---------- 2010-08-17 13:00:00 : 석사동   1090 ----------


 ---------- 2010-08-17 13:00:00 : 퇴계동   1091 ----------


 ---------- 2010-08-17 15:00:00 : 근화동   1092 ----------


 ---------- 2010-08-17 16:00:00 : 동내면   1093 ----------


 ---------- 2010-08-17 17:00:00 : 신사우동   1094 ----------


 ---------- 2010-08-18 00:00:00 : 근화동   1096 ----------

 ---------- 2010-08-18 07:00:00 : 교  동   1098 ----------


 ---------- 2010-08-18 09:00:00 : 신사우동   1099 ----------


 ---------- 2010-08-18 13:00:00 : 효자1동   1100 ----------


 ---------- 2010-08-18 13:00:00 : 소양동   1101 ----------


 ---------- 2010-08-18 13:00:00 : 동  면   1102 ----------


 ---------- 2010-08-18 13:00:00 : 후평1동   1104 ----------


 ---------- 2010-08-18 15:00:00 : 동산면   1105 ----------


 ---------- 2010-08-18 16:00:00 : 석사동   1106 ----------


 ---------- 2010-08-18 17:00:00 : 동  면   1107 ----------


 ---------- 2010-08-18 23:00:00 : 동산면   1108 ----------


 ---------- 2010-08-19 06:00:00 : 후평1동   1109 ----------


 ---------- 2010-08-19 08:00:00 : 퇴계동   1110 ----------


 ---------- 2010-08-19 10:00:00 : 동내면   1111 ----------


 ---------- 2010-08-19 10:00:00 : 동  면   1112 ----------


 ---------- 2010-08-19 10:00:00 : 퇴계동   1113 ----------


 ---------- 2010-08-19 11:00:00 : 근화동   1114 ----------


 ---------- 2010-08-19 12:00:00 : 석사동   1115 ----------


 ---------- 2010-08-19 13:00:00 : 후평1동   1116 ----------


 ---------- 2010-08-19 19:00:00 : 남산면   1117 ----------


 ---------- 2010-08-20 09:00:00 : 서  면   1118 ----------


 ---------- 2010-08-20 10:00:00 : 석사동   1119 ----------


 ---------- 2010-08-20 10:00:00 : 동  면   1120 ----------


 ---------- 2010-08-20 11:00:00 : 서  면   1121 ----------


 ---------- 2010-08-20 11:00:00 : 남산면   1122 ----------


 ---------- 2010-08-20 11:00:00 : 퇴계동   1123 ----------


 ---------- 2010-08-20 13:00:00 : 신동면   1124 ----------


 ---------- 2010-08-20 14:00:00 : 석사동   1125 ----------


 ---------- 2010-08-20 14:00:00 : 소양동   1126 ----------


 ---------- 2010-08-20 16:00:00 : 강남동   1127 ----------


 ---------- 2010-08-20 16:00:00 : 남산면   1128 ----------


 ---------- 2010-08-20 17:00:00 : 신동면   1129 ----------


 ---------- 2010-08-21 01:00:00 : 석사동   1130 ----------


 ---------- 2010-08-21 04:00:00 : 남산면   1132 ----------


 ---------- 2010-08-21 05:00:00 : 동  면   1133 ----------


 ---------- 2010-08-21 09:00:00 : 서  면   1134 ----------


 ---------- 2010-08-21 10:00:00 : 서  면   1135 ----------


 ---------- 2010-08-21 11:00:00 : 퇴계동   1136 ----------


 ---------- 2010-08-21 12:00:00 : 남  면   1137 ----------


 ---------- 2010-08-21 12:00:00 : 후평1동   1138 ----------


 ---------- 2010-08-21 16:00:00 : 소양동   1139 ----------


 ---------- 2010-08-21 17:00:00 : 석사동   1141 ----------


 ---------- 2010-08-21 17:00:00 : 효자1동   1142 ----------


 ---------- 2010-08-21 18:00:00 : 근화동   1143 ----------


 ---------- 2010-08-21 18:00:00 : 신사우동   1144 ----------


 ---------- 2010-08-21 20:00:00 : 조운동   1145 ----------


 ---------- 2010-08-21 22:00:00 : 약사명동   1146 ----------


 ---------- 2010-08-21 23:00:00 : 석사동   1147 ----------


 ---------- 2010-08-22 02:00:00 : 효자1동   1148 ----------


 ---------- 2010-08-22 09:00:00 : 남산면   1149 ----------


 ---------- 2010-08-22 10:00:00 : 효자1동   1150 ----------


 ---------- 2010-08-22 15:00:00 : 신사우동   1151 ----------


 ---------- 2010-08-22 15:00:00 : 퇴계동   1152 ----------


 ---------- 2010-08-22 16:00:00 : 남  면   1153 ----------


 ---------- 2010-08-22 22:00:00 : 퇴계동   1154 ----------


 ---------- 2010-08-23 05:00:00 : 후평1동   1155 ----------


 ---------- 2010-08-23 06:00:00 : 효자1동   1156 ----------


 ---------- 2010-08-23 06:00:00 : 퇴계동   1157 ----------


 ---------- 2010-08-23 07:00:00 : 신북읍   1158 ----------


 ---------- 2010-08-23 09:00:00 : 신동면   1159 ----------


 ---------- 2010-08-23 10:00:00 : 강남동   1160 ----------


 ---------- 2010-08-23 11:00:00 : 강남동   1161 ----------


 ---------- 2010-08-23 11:00:00 : 후평1동   1162 ----------


 ---------- 2010-08-23 12:00:00 : 서  면   1163 ----------


 ---------- 2010-08-23 13:00:00 : 사북면   1164 ----------


 ---------- 2010-08-23 14:00:00 : 남산면   1166 ----------


 ---------- 2010-08-23 19:00:00 : 후평1동   1167 ----------


 ---------- 2010-08-24 07:00:00 : 서  면   1168 ----------


 ---------- 2010-08-24 09:00:00 : 신사우동   1171 ----------


 ---------- 2010-08-24 09:00:00 : 동  면   1172 ----------


 ---------- 2010-08-24 10:00:00 : 사북면   1173 ----------


 ---------- 2010-08-24 11:00:00 : 동  면   1175 ----------


 ---------- 2010-08-24 13:00:00 : 서  면   1176 ----------


 ---------- 2010-08-24 13:00:00 : 신사우동   1177 ----------


 ---------- 2010-08-24 16:00:00 : 효자1동   1178 ----------


 ---------- 2010-08-24 16:00:00 : 후평1동   1180 ----------


 ---------- 2010-08-24 17:00:00 : 동내면   1181 ----------


 ---------- 2010-08-24 19:00:00 : 동내면   1182 ----------


 ---------- 2010-08-24 20:00:00 : 강남동   1184 ----------


 ---------- 2010-08-24 20:00:00 : 약사명동   1185 ----------


 ---------- 2010-08-24 21:00:00 : 후평1동   1188 ----------


 ---------- 2010-08-24 22:00:00 : 후평1동   1189 ----------


 ---------- 2010-08-25 01:00:00 : 효자1동   1191 ----------


 ---------- 2010-08-25 10:00:00 : 석사동   1192 ----------


 ---------- 2010-08-25 10:00:00 : 강남동   1193 ----------


 ---------- 2010-08-25 12:00:00 : 퇴계동   1194 ----------


 ---------- 2010-08-25 13:00:00 : 석사동   1197 ----------


 ---------- 2010-08-25 16:00:00 : 남  면   1198 ----------


 ---------- 2010-08-25 17:00:00 : 서  면   1199 ----------


 ---------- 2010-08-25 20:00:00 : 석사동   1200 ----------


 ---------- 2010-08-26 01:00:00 : 석사동   1201 ----------


 ---------- 2010-08-26 09:00:00 : 서  면   1202 ----------


 ---------- 2010-08-26 09:00:00 : 남산면   1204 ----------


 ---------- 2010-08-26 10:00:00 : 신사우동   1205 ----------


 ---------- 2010-08-26 13:00:00 : 동  면   1206 ----------


 ---------- 2010-08-26 13:00:00 : 후평1동   1207 ----------


 ---------- 2010-08-26 14:00:00 : 퇴계동   1208 ----------


 ---------- 2010-08-26 15:00:00 : 서  면   1210 ----------


 ---------- 2010-08-26 20:00:00 : 효자1동   1211 ----------


 ---------- 2010-08-27 08:00:00 : 퇴계동   1212 ----------


 ---------- 2010-08-27 09:00:00 : 석사동   1213 ----------


 ---------- 2010-08-27 09:00:00 : 사북면   1214 ----------


 ---------- 2010-08-27 10:00:00 : 효자1동   1215 ----------


 ---------- 2010-08-27 12:00:00 : 소양동   1216 ----------


 ---------- 2010-08-27 13:00:00 : 서  면   1217 ----------


 ---------- 2010-08-27 13:00:00 : 소양동   1218 ----------


 ---------- 2010-08-27 14:00:00 : 남  면   1222 ----------


 ---------- 2010-08-27 14:00:00 : 신사우동   1223 ----------


 ---------- 2010-08-27 14:00:00 : 동산면   1224 ----------


 ---------- 2010-08-27 15:00:00 : 강남동   1225 ----------


 ---------- 2010-08-27 15:00:00 : 남산면   1226 ----------


 ---------- 2010-08-27 21:00:00 : 효자1동   1227 ----------


 ---------- 2010-08-28 09:00:00 : 강남동   1228 ----------


 ---------- 2010-08-28 09:00:00 : 동  면   1229 ----------


 ---------- 2010-08-28 10:00:00 : 효자1동   1231 ----------


 ---------- 2010-08-28 11:00:00 : 서  면   1232 ----------


 ---------- 2010-08-28 13:00:00 : 후평1동   1233 ----------


 ---------- 2010-08-28 15:00:00 : 동내면   1234 ----------


 ---------- 2010-08-28 16:00:00 : 근화동   1235 ----------


 ---------- 2010-08-28 18:00:00 : 효자1동   1236 ----------


 ---------- 2010-08-28 21:00:00 : 강남동   1237 ----------


 ---------- 2010-08-28 23:00:00 : 신사우동   1238 ----------


 ---------- 2010-08-28 23:00:00 : 퇴계동   1239 ----------


 ---------- 2010-08-29 01:00:00 : 효자1동   1240 ----------


 ---------- 2010-08-29 01:00:00 : 신사우동   1242 ----------


 ---------- 2010-08-29 09:00:00 : 동  면   1243 ----------


 ---------- 2010-08-29 10:00:00 : 퇴계동   1244 ----------


 ---------- 2010-08-29 12:00:00 : 후평1동   1245 ----------


 ---------- 2010-08-29 15:00:00 : 강남동   1246 ----------


 ---------- 2010-08-29 18:00:00 : 소양동   1247 ----------


 ---------- 2010-08-29 20:00:00 : 교  동   1248 ----------


 ---------- 2010-08-29 21:00:00 : 퇴계동   1249 ----------


 ---------- 2010-08-30 09:00:00 : 서  면   1250 ----------


 ---------- 2010-08-30 09:00:00 : 후평1동   1251 ----------


 ---------- 2010-08-30 10:00:00 : 석사동   1252 ----------


 ---------- 2010-08-30 11:00:00 : 사북면   1253 ----------


 ---------- 2010-08-30 13:00:00 : 소양동   1254 ----------


 ---------- 2010-08-30 14:00:00 : 동  면   1255 ----------


 ---------- 2010-08-30 15:00:00 : 석사동   1256 ----------

 ---------- 2010-08-30 17:00:00 : 동  면   1257 ----------


 ---------- 2010-08-30 20:00:00 : 퇴계동   1259 ----------


 ---------- 2010-08-30 22:00:00 : 석사동   1260 ----------


 ---------- 2010-08-31 08:00:00 : 신북읍   1261 ----------


 ---------- 2010-08-31 10:00:00 : 동  면   1262 ----------


 ---------- 2010-08-31 11:00:00 : 교  동   1263 ----------


 ---------- 2010-08-31 13:00:00 : 사북면   1264 ----------


 ---------- 2010-08-31 13:00:00 : 동  면   1265 ----------


 ---------- 2010-08-31 16:00:00 : 동  면   1266 ----------


 ---------- 2010-08-31 17:00:00 : 신사우동   1267 ----------


 ---------- 2010-08-31 19:00:00 : 후평1동   1268 ----------


 ---------- 2010-08-31 21:00:00 : 퇴계동   1269 ----------


 ---------- 2010-09-01 01:00:00 : 효자1동   1270 ----------


 ---------- 2010-09-01 09:00:00 : 동내면   1271 ----------


 ---------- 2010-09-01 12:00:00 : 후평1동   1273 ----------


 ---------- 2010-09-01 15:00:00 : 석사동   1274 ----------


 ---------- 2010-09-01 15:00:00 : 서  면   1275 ----------


 ---------- 2010-09-01 16:00:00 : 동내면   1276 ----------


 ---------- 2010-09-01 16:00:00 : 효자1동   1277 ----------


 ---------- 2010-09-01 16:00:00 : 후평1동   1278 ----------


 ---------- 2010-09-01 17:00:00 : 근화동   1279 ----------


 ---------- 2010-09-01 19:00:00 : 퇴계동   1280 ----------


 ---------- 2010-09-02 04:00:00 : 효자1동   1281 ----------


 ---------- 2010-09-02 06:00:00 : 효자1동   1283 ----------


 ---------- 2010-09-02 07:00:00 : 효자1동   1284 ----------


 ---------- 2010-09-02 07:00:00 : 소양동   1285 ----------


 ---------- 2010-09-02 07:00:00 : 동  면   1289 ----------


 ---------- 2010-09-02 07:00:00 : 후평1동   1293 ----------


 ---------- 2010-09-02 08:00:00 : 효자1동   1294 ----------


 ---------- 2010-09-02 08:00:00 : 후평1동   1295 ----------


 ---------- 2010-09-02 08:00:00 : 퇴계동   1297 ----------


 ---------- 2010-09-02 09:00:00 : 강남동   1298 ----------


 ---------- 2010-09-02 09:00:00 : 신북읍   1299 ----------


 ---------- 2010-09-02 09:00:00 : 동  면   1300 ----------


 ---------- 2010-09-02 09:00:00 : 교  동   1301 ----------


 ---------- 2010-09-02 10:00:00 : 신북읍   1302 ----------


 ---------- 2010-09-02 11:00:00 : 석사동   1304 ----------


 ---------- 2010-09-02 11:00:00 : 강남동   1305 ----------


 ---------- 2010-09-02 13:00:00 : 신사우동   1306 ----------


 ---------- 2010-09-02 14:00:00 : 동  면   1307 ----------


 ---------- 2010-09-02 15:00:00 : 소양동   1308 ----------


 ---------- 2010-09-02 16:00:00 : 석사동   1309 ----------


 ---------- 2010-09-02 17:00:00 : 동내면   1310 ----------


 ---------- 2010-09-02 18:00:00 : 남산면   1312 ----------


 ---------- 2010-09-02 18:00:00 : 후평1동   1313 ----------


 ---------- 2010-09-02 19:00:00 : 후평1동   1314 ----------


 ---------- 2010-09-03 00:00:00 : 동내면   1315 ----------


 ---------- 2010-09-03 05:00:00 : 조운동   1316 ----------


 ---------- 2010-09-03 08:00:00 : 동  면   1317 ----------


 ---------- 2010-09-03 09:00:00 : 강남동   1318 ----------


 ---------- 2010-09-03 10:00:00 : 신동면   1319 ----------


 ---------- 2010-09-03 10:00:00 : 근화동   1320 ----------


 ---------- 2010-09-03 10:00:00 : 신북읍   1321 ----------


 ---------- 2010-09-03 10:00:00 : 소양동   1322 ----------


 ---------- 2010-09-03 11:00:00 : 퇴계동   1323 ----------


 ---------- 2010-09-03 13:00:00 : 동내면   1324 ----------


 ---------- 2010-09-03 13:00:00 : 소양동   1325 ----------


 ---------- 2010-09-03 14:00:00 : 퇴계동   1326 ----------


 ---------- 2010-09-03 15:00:00 : 서  면   1327 ----------


 ---------- 2010-09-03 15:00:00 : 퇴계동   1329 ----------


 ---------- 2010-09-03 16:00:00 : 서  면   1330 ----------


 ---------- 2010-09-03 16:00:00 : 후평1동   1332 ----------


 ---------- 2010-09-03 19:00:00 : 소양동   1333 ----------


 ---------- 2010-09-03 19:00:00 : 퇴계동   1334 ----------


 ---------- 2010-09-03 22:00:00 : 효자1동   1335 ----------


 ---------- 2010-09-03 22:00:00 : 신북읍   1336 ----------


 ---------- 2010-09-04 04:00:00 : 후평1동   1337 ----------


 ---------- 2010-09-04 06:00:00 : 퇴계동   1338 ----------


 ---------- 2010-09-04 12:00:00 : 효자1동   1339 ----------


 ---------- 2010-09-04 13:00:00 : 동내면   1340 ----------


 ---------- 2010-09-04 13:00:00 : 조운동   1341 ----------


 ---------- 2010-09-04 15:00:00 : 퇴계동   1343 ----------


 ---------- 2010-09-04 16:00:00 : 동내면   1344 ----------


 ---------- 2010-09-04 19:00:00 : 강남동   1345 ----------


 ---------- 2010-09-05 09:00:00 : 신북읍   1346 ----------


 ---------- 2010-09-05 09:00:00 : 동  면   1347 ----------


 ---------- 2010-09-05 11:00:00 : 퇴계동   1348 ----------


 ---------- 2010-09-05 12:00:00 : 사북면   1349 ----------


 ---------- 2010-09-05 14:00:00 : 후평1동   1350 ----------


 ---------- 2010-09-05 16:00:00 : 효자1동   1351 ----------


 ---------- 2010-09-05 18:00:00 : 후평1동   1352 ----------


 ---------- 2010-09-05 22:00:00 : 석사동   1353 ----------


 ---------- 2010-09-06 08:00:00 : 신북읍   1354 ----------


 ---------- 2010-09-06 12:00:00 : 근화동   1355 ----------


 ---------- 2010-09-06 12:00:00 : 동  면   1356 ----------


 ---------- 2010-09-06 12:00:00 : 후평1동   1357 ----------


 ---------- 2010-09-06 13:00:00 : 신동면   1359 ----------


 ---------- 2010-09-06 14:00:00 : 신북읍   1360 ----------


 ---------- 2010-09-06 14:00:00 : 교  동   1361 ----------


 ---------- 2010-09-06 15:00:00 : 석사동   1362 ----------


 ---------- 2010-09-06 15:00:00 : 소양동   1363 ----------


 ---------- 2010-09-06 15:00:00 : 퇴계동   1364 ----------


 ---------- 2010-09-06 17:00:00 : 근화동   1365 ----------


 ---------- 2010-09-07 00:00:00 : 후평1동   1366 ----------


 ---------- 2010-09-07 03:00:00 : 후평1동   1367 ----------


 ---------- 2010-09-07 05:00:00 : 동산면   1368 ----------


 ---------- 2010-09-07 08:00:00 : 사북면   1369 ----------


 ---------- 2010-09-07 09:00:00 : 퇴계동   1370 ----------


 ---------- 2010-09-07 10:00:00 : 동내면   1371 ----------


 ---------- 2010-09-07 10:00:00 : 후평1동   1372 ----------


 ---------- 2010-09-07 11:00:00 : 석사동   1373 ----------


 ---------- 2010-09-07 11:00:00 : 남산면   1375 ----------


 ---------- 2010-09-07 12:00:00 : 효자1동   1376 ----------


 ---------- 2010-09-07 13:00:00 : 남산면   1377 ----------


 ---------- 2010-09-07 13:00:00 : 소양동   1378 ----------


 ---------- 2010-09-07 14:00:00 : 석사동   1379 ----------


 ---------- 2010-09-07 15:00:00 : 동산면   1381 ----------


 ---------- 2010-09-07 16:00:00 : 근화동   1382 ----------


 ---------- 2010-09-07 16:00:00 : 동산면   1383 ----------


 ---------- 2010-09-07 21:00:00 : 석사동   1384 ----------


 ---------- 2010-09-08 01:00:00 : 동  면   1385 ----------


 ---------- 2010-09-08 10:00:00 : 석사동   1386 ----------


 ---------- 2010-09-08 10:00:00 : 약사명동   1387 ----------


 ---------- 2010-09-08 14:00:00 : 서  면   1388 ----------


 ---------- 2010-09-08 14:00:00 : 신북읍   1389 ----------


 ---------- 2010-09-08 14:00:00 : 소양동   1390 ----------


 ---------- 2010-09-08 20:00:00 : 약사명동   1391 ----------


 ---------- 2010-09-09 08:00:00 : 남산면   1392 ----------


 ---------- 2010-09-09 09:00:00 : 동내면   1393 ----------


 ---------- 2010-09-09 10:00:00 : 퇴계동   1394 ----------


 ---------- 2010-09-09 11:00:00 : 서  면   1395 ----------


 ---------- 2010-09-09 15:00:00 : 퇴계동   1396 ----------


 ---------- 2010-09-09 16:00:00 : 동산면   1399 ----------


 ---------- 2010-09-09 20:00:00 : 약사명동   1400 ----------


 ---------- 2010-09-10 15:00:00 : 남산면   1402 ----------


 ---------- 2010-09-10 16:00:00 : 퇴계동   1403 ----------


 ---------- 2010-09-10 17:00:00 : 서  면   1405 ----------


 ---------- 2010-09-10 19:00:00 : 남  면   1406 ----------


 ---------- 2010-09-10 19:00:00 : 남산면   1408 ----------


 ---------- 2010-09-10 19:00:00 : 후평1동   1409 ----------


 ---------- 2010-09-10 20:00:00 : 남산면   1410 ----------


 ---------- 2010-09-10 22:00:00 : 효자1동   1411 ----------


 ---------- 2010-09-11 01:00:00 : 효자1동   1412 ----------


 ---------- 2010-09-11 07:00:00 : 약사명동   1413 ----------


 ---------- 2010-09-11 09:00:00 : 동산면   1414 ----------


 ---------- 2010-09-11 10:00:00 : 강남동   1415 ----------


 ---------- 2010-09-11 10:00:00 : 남산면   1417 ----------


 ---------- 2010-09-11 13:00:00 : 후평1동   1418 ----------

 ---------- 2010-09-11 15:00:00 : 신사우동   1419 ----------


 ---------- 2010-09-11 16:00:00 : 동내면   1420 ----------


 ---------- 2010-09-12 08:00:00 : 사북면   1421 ----------


 ---------- 2010-09-12 09:00:00 : 동  면   1423 ----------


 ---------- 2010-09-12 13:00:00 : 석사동   1424 ----------


 ---------- 2010-09-12 19:00:00 : 남산면   1425 ----------


 ---------- 2010-09-12 23:00:00 : 북산면   1427 ----------


 ---------- 2010-09-13 01:00:00 : 효자1동   1428 ----------


 ---------- 2010-09-13 06:00:00 : 후평1동   1430 ----------


 ---------- 2010-09-13 07:00:00 : 동내면   1431 ----------


 ---------- 2010-09-13 11:00:00 : 신사우동   1432 ----------


 ---------- 2010-09-13 13:00:00 : 약사명동   1433 ----------


 ---------- 2010-09-13 15:00:00 : 신북읍   1434 ----------


 ---------- 2010-09-13 18:00:00 : 신사우동   1435 ----------


 ---------- 2010-09-13 19:00:00 : 신북읍   1436 ----------


 ---------- 2010-09-13 20:00:00 : 동내면   1437 ----------


 ---------- 2010-09-14 00:00:00 : 후평1동   1438 ----------


 ---------- 2010-09-14 01:00:00 : 교  동   1439 ----------


 ---------- 2010-09-14 12:00:00 : 효자1동   1441 ----------


 ---------- 2010-09-14 13:00:00 : 사북면   1442 ----------


 ---------- 2010-09-14 13:00:00 : 퇴계동   1443 ----------


 ---------- 2010-09-14 14:00:00 : 신동면   1444 ----------


 ---------- 2010-09-14 14:00:00 : 서  면   1446 ----------


 ---------- 2010-09-14 15:00:00 : 석사동   1447 ----------


 ---------- 2010-09-14 15:00:00 : 퇴계동   1448 ----------


 ---------- 2010-09-14 16:00:00 : 석사동   1449 ----------


 ---------- 2010-09-14 16:00:00 : 서  면   1450 ----------


 ---------- 2010-09-14 16:00:00 : 신사우동   1451 ----------


 ---------- 2010-09-14 17:00:00 : 후평1동   1452 ----------


 ---------- 2010-09-15 08:00:00 : 석사동   1454 ----------


 ---------- 2010-09-15 10:00:00 : 후평1동   1455 ----------


 ---------- 2010-09-15 13:00:00 : 사북면   1456 ----------


 ---------- 2010-09-15 13:00:00 : 동내면   1457 ----------


 ---------- 2010-09-15 14:00:00 : 서  면   1458 ----------


 ---------- 2010-09-15 14:00:00 : 후평1동   1460 ----------


 ---------- 2010-09-15 15:00:00 : 석사동   1461 ----------


 ---------- 2010-09-15 15:00:00 : 동산면   1462 ----------


 ---------- 2010-09-15 19:00:00 : 퇴계동   1463 ----------


 ---------- 2010-09-15 20:00:00 : 소양동   1464 ----------


 ---------- 2010-09-15 20:00:00 : 퇴계동   1465 ----------


 ---------- 2010-09-15 22:00:00 : 퇴계동   1466 ----------


 ---------- 2010-09-16 14:00:00 : 강남동   1468 ----------


 ---------- 2010-09-16 18:00:00 : 효자1동   1469 ----------


 ---------- 2010-09-16 21:00:00 : 퇴계동   1470 ----------


 ---------- 2010-09-16 22:00:00 : 퇴계동   1471 ----------


 ---------- 2010-09-17 00:00:00 : 퇴계동   1472 ----------


 ---------- 2010-09-17 09:00:00 : 사북면   1473 ----------


 ---------- 2010-09-17 11:00:00 : 남산면   1475 ----------


 ---------- 2010-09-17 11:00:00 : 후평1동   1476 ----------


 ---------- 2010-09-17 13:00:00 : 남산면   1477 ----------


 ---------- 2010-09-17 13:00:00 : 후평1동   1478 ----------


 ---------- 2010-09-17 19:00:00 : 신사우동   1479 ----------


 ---------- 2010-09-17 22:00:00 : 석사동   1480 ----------


 ---------- 2010-09-18 08:00:00 : 근화동   1481 ----------


 ---------- 2010-09-18 18:00:00 : 후평1동   1482 ----------


 ---------- 2010-09-18 23:00:00 : 효자1동   1483 ----------


 ---------- 2010-09-19 03:00:00 : 후평1동   1484 ----------


 ---------- 2010-09-19 04:00:00 : 후평1동   1485 ----------


 ---------- 2010-09-19 08:00:00 : 신사우동   1486 ----------


 ---------- 2010-09-19 09:00:00 : 신사우동   1487 ----------


 ---------- 2010-09-19 10:00:00 : 동  면   1488 ----------


 ---------- 2010-09-19 11:00:00 : 석사동   1489 ----------


 ---------- 2010-09-19 11:00:00 : 동  면   1490 ----------


 ---------- 2010-09-19 13:00:00 : 남산면   1491 ----------


 ---------- 2010-09-19 13:00:00 : 동  면   1492 ----------


 ---------- 2010-09-19 13:00:00 : 후평1동   1493 ----------


 ---------- 2010-09-19 15:00:00 : 신사우동   1495 ----------


 ---------- 2010-09-20 00:00:00 : 석사동   1496 ----------


 ---------- 2010-09-20 04:00:00 : 석사동   1497 ----------


 ---------- 2010-09-20 11:00:00 : 후평1동   1498 ----------


 ---------- 2010-09-20 13:00:00 : 동내면   1499 ----------


 ---------- 2010-09-20 13:00:00 : 동  면   1500 ----------


 ---------- 2010-09-20 14:00:00 : 근화동   1501 ----------


 ---------- 2010-09-20 14:00:00 : 퇴계동   1502 ----------


 ---------- 2010-09-20 16:00:00 : 조운동   1503 ----------


 ---------- 2010-09-20 21:00:00 : 효자1동   1504 ----------


 ---------- 2010-09-21 01:00:00 : 석사동   1505 ----------


 ---------- 2010-09-21 09:00:00 : 동  면   1506 ----------


 ---------- 2010-09-21 12:00:00 : 동  면   1508 ----------


 ---------- 2010-09-21 13:00:00 : 서  면   1510 ----------


 ---------- 2010-09-22 05:00:00 : 동산면   1511 ----------


 ---------- 2010-09-22 08:00:00 : 강남동   1512 ----------


 ---------- 2010-09-22 12:00:00 : 남산면   1513 ----------


 ---------- 2010-09-22 22:00:00 : 신사우동   1514 ----------


 ---------- 2010-09-23 07:00:00 : 동산면   1515 ----------


 ---------- 2010-09-23 10:00:00 : 근화동   1516 ----------


 ---------- 2010-09-23 11:00:00 : 후평1동   1517 ----------


 ---------- 2010-09-23 14:00:00 : 남산면   1518 ----------


 ---------- 2010-09-23 16:00:00 : 석사동   1519 ----------


 ---------- 2010-09-23 18:00:00 : 사북면   1520 ----------


 ---------- 2010-09-23 18:00:00 : 동내면   1521 ----------


 ---------- 2010-09-24 13:00:00 : 강남동   1522 ----------


 ---------- 2010-09-24 14:00:00 : 퇴계동   1523 ----------


 ---------- 2010-09-24 16:00:00 : 강남동   1524 ----------


 ---------- 2010-09-24 17:00:00 : 교  동   1525 ----------


 ---------- 2010-09-24 21:00:00 : 강남동   1526 ----------


 ---------- 2010-09-25 00:00:00 : 퇴계동   1527 ----------


 ---------- 2010-09-25 09:00:00 : 신사우동   1528 ----------


 ---------- 2010-09-25 11:00:00 : 퇴계동   1529 ----------


 ---------- 2010-09-25 14:00:00 : 석사동   1530 ----------


 ---------- 2010-09-25 17:00:00 : 퇴계동   1531 ----------


 ---------- 2010-09-25 18:00:00 : 남산면   1532 ----------


 ---------- 2010-09-25 19:00:00 : 남산면   1533 ----------


 ---------- 2010-09-26 00:00:00 : 근화동   1534 ----------


 ---------- 2010-09-26 08:00:00 : 동내면   1535 ----------


 ---------- 2010-09-26 11:00:00 : 동산면   1536 ----------


 ---------- 2010-09-26 15:00:00 : 약사명동   1537 ----------


 ---------- 2010-09-26 18:00:00 : 동내면   1538 ----------


 ---------- 2010-09-26 18:00:00 : 북산면   1540 ----------


 ---------- 2010-09-26 19:00:00 : 강남동   1541 ----------


 ---------- 2010-09-27 02:00:00 : 신사우동   1542 ----------


 ---------- 2010-09-27 07:00:00 : 석사동   1543 ----------


 ---------- 2010-09-27 09:00:00 : 후평1동   1544 ----------


 ---------- 2010-09-27 11:00:00 : 강남동   1546 ----------


 ---------- 2010-09-27 13:00:00 : 동  면   1547 ----------


 ---------- 2010-09-27 14:00:00 : 사북면   1548 ----------


 ---------- 2010-09-27 19:00:00 : 신사우동   1549 ----------


 ---------- 2010-09-27 21:00:00 : 신북읍   1550 ----------


 ---------- 2010-09-27 22:00:00 : 동  면   1551 ----------


 ---------- 2010-09-28 02:00:00 : 석사동   1552 ----------


 ---------- 2010-09-28 09:00:00 : 동산면   1554 ----------


 ---------- 2010-09-28 10:00:00 : 석사동   1555 ----------


 ---------- 2010-09-28 10:00:00 : 사북면   1556 ----------


 ---------- 2010-09-28 13:00:00 : 효자1동   1557 ----------


 ---------- 2010-09-28 14:00:00 : 동  면   1558 ----------


 ---------- 2010-09-28 15:00:00 : 남산면   1559 ----------


 ---------- 2010-09-28 19:00:00 : 북산면   1561 ----------


 ---------- 2010-09-28 21:00:00 : 후평1동   1562 ----------


 ---------- 2010-09-29 10:00:00 : 석사동   1563 ----------


 ---------- 2010-09-29 14:00:00 : 동내면   1564 ----------


 ---------- 2010-09-29 19:00:00 : 퇴계동   1565 ----------


 ---------- 2010-09-29 22:00:00 : 퇴계동   1566 ----------


 ---------- 2010-09-30 10:00:00 : 석사동   1567 ----------


 ---------- 2010-09-30 14:00:00 : 서  면   1568 ----------


 ---------- 2010-09-30 16:00:00 : 동  면   1569 ----------


 ---------- 2010-09-30 20:00:00 : 동내면   1570 ----------


 ---------- 2010-10-01 10:00:00 : 신북읍   1571 ----------


 ---------- 2010-10-02 01:00:00 : 후평1동   1572 ----------


 ---------- 2010-10-02 01:00:00 : 퇴계동   1573 ----------


 ---------- 2010-10-02 02:00:00 : 강남동   1574 ----------

 ---------- 2010-10-02 10:00:00 : 근화동   1575 ----------


 ---------- 2010-10-02 15:00:00 : 북산면   1576 ----------


 ---------- 2010-10-03 03:00:00 : 석사동   1577 ----------


 ---------- 2010-10-03 14:00:00 : 석사동   1578 ----------


 ---------- 2010-10-03 14:00:00 : 북산면   1579 ----------


 ---------- 2010-10-03 15:00:00 : 북산면   1580 ----------


 ---------- 2010-10-03 20:00:00 : 남산면   1581 ----------


 ---------- 2010-10-03 21:00:00 : 강남동   1582 ----------


 ---------- 2010-10-04 10:00:00 : 강남동   1583 ----------


 ---------- 2010-10-04 19:00:00 : 남산면   1585 ----------


 ---------- 2010-10-05 08:00:00 : 동산면   1586 ----------


 ---------- 2010-10-05 13:00:00 : 소양동   1587 ----------


 ---------- 2010-10-05 15:00:00 : 퇴계동   1588 ----------


 ---------- 2010-10-05 18:00:00 : 동내면   1589 ----------


 ---------- 2010-10-05 18:00:00 : 동  면   1590 ----------


 ---------- 2010-10-05 22:00:00 : 석사동   1591 ----------


 ---------- 2010-10-06 13:00:00 : 동내면   1592 ----------


 ---------- 2010-10-06 21:00:00 : 동  면   1593 ----------


 ---------- 2010-10-06 23:00:00 : 조운동   1594 ----------


 ---------- 2010-10-07 11:00:00 : 조운동   1596 ----------


 ---------- 2010-10-07 13:00:00 : 동내면   1597 ----------


 ---------- 2010-10-07 15:00:00 : 남산면   1598 ----------


 ---------- 2010-10-07 15:00:00 : 신북읍   1599 ----------


 ---------- 2010-10-07 17:00:00 : 신사우동   1600 ----------


 ---------- 2010-10-07 21:00:00 : 석사동   1601 ----------


 ---------- 2010-10-07 21:00:00 : 사북면   1602 ----------


 ---------- 2010-10-07 22:00:00 : 후평1동   1603 ----------


 ---------- 2010-10-08 09:00:00 : 후평1동   1604 ----------


 ---------- 2010-10-08 18:00:00 : 동내면   1605 ----------


 ---------- 2010-10-09 14:00:00 : 서  면   1606 ----------


 ---------- 2010-10-09 19:00:00 : 동  면   1607 ----------


 ---------- 2010-10-09 22:00:00 : 강남동   1608 ----------


 ---------- 2010-10-09 23:00:00 : 효자1동   1609 ----------


 ---------- 2010-10-10 00:00:00 : 석사동   1610 ----------


 ---------- 2010-10-10 02:00:00 : 퇴계동   1611 ----------


 ---------- 2010-10-10 16:00:00 : 강남동   1612 ----------


 ---------- 2010-10-10 19:00:00 : 남산면   1614 ----------


 ---------- 2010-10-11 02:00:00 : 후평1동   1615 ----------


 ---------- 2010-10-11 13:00:00 : 동  면   1616 ----------


 ---------- 2010-10-11 13:00:00 : 교  동   1617 ----------


 ---------- 2010-10-11 15:00:00 : 강남동   1618 ----------


 ---------- 2010-10-11 18:00:00 : 신사우동   1619 ----------


 ---------- 2010-10-11 21:00:00 : 약사명동   1621 ----------


 ---------- 2010-10-11 22:00:00 : 효자1동   1622 ----------


 ---------- 2010-10-12 01:00:00 : 석사동   1623 ----------


 ---------- 2010-10-12 01:00:00 : 후평1동   1624 ----------


 ---------- 2010-10-12 09:00:00 : 남산면   1625 ----------


 ---------- 2010-10-12 10:00:00 : 소양동   1626 ----------


 ---------- 2010-10-12 17:00:00 : 소양동   1627 ----------


 ---------- 2010-10-12 21:00:00 : 효자1동   1628 ----------


 ---------- 2010-10-12 23:00:00 : 후평1동   1629 ----------


 ---------- 2010-10-13 10:00:00 : 신사우동   1630 ----------


 ---------- 2010-10-13 12:00:00 : 석사동   1631 ----------


 ---------- 2010-10-13 13:00:00 : 서  면   1632 ----------


 ---------- 2010-10-13 13:00:00 : 신북읍   1633 ----------


 ---------- 2010-10-13 14:00:00 : 신북읍   1634 ----------


 ---------- 2010-10-13 21:00:00 : 소양동   1635 ----------


 ---------- 2010-10-14 01:00:00 : 신북읍   1636 ----------


 ---------- 2010-10-14 11:00:00 : 퇴계동   1637 ----------


 ---------- 2010-10-15 05:00:00 : 효자1동   1638 ----------


 ---------- 2010-10-15 10:00:00 : 북산면   1639 ----------


 ---------- 2010-10-15 12:00:00 : 효자1동   1640 ----------


 ---------- 2010-10-15 13:00:00 : 효자1동   1641 ----------


 ---------- 2010-10-15 14:00:00 : 남산면   1642 ----------


 ---------- 2010-10-16 01:00:00 : 동산면   1644 ----------


 ---------- 2010-10-16 09:00:00 : 동산면   1645 ----------


 ---------- 2010-10-16 12:00:00 : 남산면   1646 ----------


 ---------- 2010-10-16 14:00:00 : 효자1동   1647 ----------


 ---------- 2010-10-16 15:00:00 : 효자1동   1648 ----------


 ---------- 2010-10-16 17:00:00 : 후평1동   1649 ----------


 ---------- 2010-10-17 03:00:00 : 남산면   1651 ----------


 ---------- 2010-10-17 03:00:00 : 교  동   1652 ----------


 ---------- 2010-10-17 07:00:00 : 후평1동   1653 ----------


 ---------- 2010-10-17 11:00:00 : 후평1동   1654 ----------


 ---------- 2010-10-17 16:00:00 : 신사우동   1655 ----------


 ---------- 2010-10-17 22:00:00 : 남산면   1656 ----------


 ---------- 2010-10-18 12:00:00 : 남산면   1657 ----------


 ---------- 2010-10-18 14:00:00 : 남산면   1658 ----------


 ---------- 2010-10-18 20:00:00 : 석사동   1660 ----------


 ---------- 2010-10-18 23:00:00 : 남산면   1662 ----------


 ---------- 2010-10-19 00:00:00 : 강남동   1663 ----------


 ---------- 2010-10-19 00:00:00 : 서  면   1664 ----------


 ---------- 2010-10-19 08:00:00 : 동산면   1665 ----------


 ---------- 2010-10-19 12:00:00 : 남산면   1666 ----------


 ---------- 2010-10-19 18:00:00 : 신동면   1667 ----------


 ---------- 2010-10-19 21:00:00 : 효자1동   1668 ----------


 ---------- 2010-10-19 21:00:00 : 조운동   1669 ----------


 ---------- 2010-10-20 08:00:00 : 조운동   1670 ----------


 ---------- 2010-10-20 13:00:00 : 석사동   1671 ----------


 ---------- 2010-10-20 16:00:00 : 소양동   1673 ----------


 ---------- 2010-10-20 16:00:00 : 조운동   1674 ----------


 ---------- 2010-10-20 17:00:00 : 동  면   1675 ----------


 ---------- 2010-10-20 19:00:00 : 효자1동   1676 ----------


 ---------- 2010-10-20 23:00:00 : 후평1동   1677 ----------


 ---------- 2010-10-21 16:00:00 : 강남동   1678 ----------


 ---------- 2010-10-21 19:00:00 : 교  동   1679 ----------


 ---------- 2010-10-22 10:00:00 : 신북읍   1680 ----------


 ---------- 2010-10-22 11:00:00 : 조운동   1681 ----------


 ---------- 2010-10-22 12:00:00 : 석사동   1682 ----------


 ---------- 2010-10-22 14:00:00 : 북산면   1683 ----------


 ---------- 2010-10-22 15:00:00 : 남산면   1684 ----------


 ---------- 2010-10-22 19:00:00 : 퇴계동   1685 ----------


 ---------- 2010-10-23 01:00:00 : 신사우동   1686 ----------


 ---------- 2010-10-23 08:00:00 : 후평1동   1687 ----------


 ---------- 2010-10-23 14:00:00 : 서  면   1689 ----------


 ---------- 2010-10-23 15:00:00 : 서  면   1690 ----------


 ---------- 2010-10-24 09:00:00 : 신사우동   1691 ----------


 ---------- 2010-10-24 11:00:00 : 서  면   1692 ----------


 ---------- 2010-10-24 12:00:00 : 서  면   1693 ----------


 ---------- 2010-10-24 12:00:00 : 북산면   1694 ----------


 ---------- 2010-10-24 15:00:00 : 퇴계동   1695 ----------


 ---------- 2010-10-24 19:00:00 : 동내면   1698 ----------


 ---------- 2010-10-24 23:00:00 : 신사우동   1699 ----------


 ---------- 2010-10-25 16:00:00 : 남산면   1700 ----------


 ---------- 2010-10-25 17:00:00 : 퇴계동   1701 ----------


 ---------- 2010-10-26 12:00:00 : 석사동   1702 ----------


 ---------- 2010-10-26 15:00:00 : 남산면   1703 ----------


 ---------- 2010-10-26 15:00:00 : 신사우동   1704 ----------


 ---------- 2010-10-26 21:00:00 : 동산면   1705 ----------


 ---------- 2010-10-27 16:00:00 : 효자1동   1706 ----------


 ---------- 2010-10-27 16:00:00 : 동  면   1707 ----------


 ---------- 2010-10-27 16:00:00 : 후평1동   1708 ----------


 ---------- 2010-10-27 20:00:00 : 효자1동   1709 ----------


 ---------- 2010-10-28 02:00:00 : 후평1동   1710 ----------


 ---------- 2010-10-28 06:00:00 : 효자1동   1711 ----------


 ---------- 2010-10-28 06:00:00 : 후평1동   1712 ----------


 ---------- 2010-10-28 09:00:00 : 서  면   1714 ----------


 ---------- 2010-10-28 11:00:00 : 후평1동   1715 ----------


 ---------- 2010-10-28 12:00:00 : 강남동   1716 ----------


 ---------- 2010-10-28 13:00:00 : 소양동   1717 ----------


 ---------- 2010-10-28 17:00:00 : 후평1동   1718 ----------


 ---------- 2010-10-29 11:00:00 : 남산면   1719 ----------


 ---------- 2010-10-29 13:00:00 : 후평1동   1720 ----------


 ---------- 2010-10-29 18:00:00 : 신동면   1722 ----------


 ---------- 2010-10-30 12:00:00 : 동산면   1723 ----------


 ---------- 2010-10-30 14:00:00 : 효자1동   1724 ----------


 ---------- 2010-10-30 15:00:00 : 서  면   1725 ----------


 ---------- 2010-10-30 19:00:00 : 후평1동   1727 ----------

 ---------- 2010-10-31 08:00:00 : 강남동   1728 ----------


 ---------- 2010-10-31 16:00:00 : 남  면   1730 ----------


 ---------- 2010-10-31 16:00:00 : 퇴계동   1731 ----------


 ---------- 2010-10-31 22:00:00 : 동산면   1733 ----------


 ---------- 2010-10-31 23:00:00 : 효자1동   1734 ----------


 ---------- 2010-11-01 15:00:00 : 퇴계동   1735 ----------


 ---------- 2010-11-01 18:00:00 : 남산면   1736 ----------


 ---------- 2010-11-01 19:00:00 : 남산면   1737 ----------


 ---------- 2010-11-02 06:00:00 : 퇴계동   1738 ----------


 ---------- 2010-11-02 08:00:00 : 남산면   1740 ----------


 ---------- 2010-11-02 14:00:00 : 동  면   1741 ----------


 ---------- 2010-11-02 23:00:00 : 후평1동   1742 ----------


 ---------- 2010-11-03 05:00:00 : 석사동   1743 ----------


 ---------- 2010-11-03 08:00:00 : 약사명동   1744 ----------


 ---------- 2010-11-03 10:00:00 : 남산면   1745 ----------


 ---------- 2010-11-03 14:00:00 : 후평1동   1746 ----------


 ---------- 2010-11-03 20:00:00 : 퇴계동   1747 ----------


 ---------- 2010-11-03 23:00:00 : 남산면   1748 ----------


 ---------- 2010-11-04 01:00:00 : 신사우동   1749 ----------


 ---------- 2010-11-04 05:00:00 : 석사동   1750 ----------


 ---------- 2010-11-04 08:00:00 : 서  면   1751 ----------


 ---------- 2010-11-04 16:00:00 : 남산면   1752 ----------


 ---------- 2010-11-04 17:00:00 : 퇴계동   1753 ----------


 ---------- 2010-11-05 18:00:00 : 약사명동   1754 ----------


 ---------- 2010-11-05 18:00:00 : 퇴계동   1755 ----------


 ---------- 2010-11-05 20:00:00 : 북산면   1756 ----------


 ---------- 2010-11-05 20:00:00 : 동산면   1758 ----------


 ---------- 2010-11-06 01:00:00 : 효자1동   1759 ----------


 ---------- 2010-11-06 03:00:00 : 효자1동   1760 ----------


 ---------- 2010-11-06 05:00:00 : 효자1동   1761 ----------


 ---------- 2010-11-06 08:00:00 : 소양동   1762 ----------


 ---------- 2010-11-06 09:00:00 : 퇴계동   1763 ----------


 ---------- 2010-11-06 11:00:00 : 동내면   1764 ----------


 ---------- 2010-11-06 15:00:00 : 북산면   1766 ----------


 ---------- 2010-11-06 16:00:00 : 남산면   1767 ----------


 ---------- 2010-11-06 16:00:00 : 북산면   1768 ----------


 ---------- 2010-11-06 18:00:00 : 퇴계동   1769 ----------


 ---------- 2010-11-06 21:00:00 : 신동면   1770 ----------


 ---------- 2010-11-07 00:00:00 : 퇴계동   1771 ----------


 ---------- 2010-11-07 07:00:00 : 후평1동   1772 ----------


 ---------- 2010-11-07 11:00:00 : 효자1동   1773 ----------


 ---------- 2010-11-07 14:00:00 : 사북면   1774 ----------


 ---------- 2010-11-07 14:00:00 : 북산면   1775 ----------


 ---------- 2010-11-07 16:00:00 : 서  면   1776 ----------


 ---------- 2010-11-07 16:00:00 : 사북면   1777 ----------


 ---------- 2010-11-07 16:00:00 : 효자1동   1778 ----------


 ---------- 2010-11-07 17:00:00 : 조운동   1779 ----------


 ---------- 2010-11-08 21:00:00 : 후평1동   1780 ----------


 ---------- 2010-11-08 23:00:00 : 퇴계동   1781 ----------


 ---------- 2010-11-09 08:00:00 : 석사동   1783 ----------


 ---------- 2010-11-09 14:00:00 : 조운동   1784 ----------


 ---------- 2010-11-09 20:00:00 : 신사우동   1785 ----------


 ---------- 2010-11-10 11:00:00 : 교  동   1786 ----------


 ---------- 2010-11-10 15:00:00 : 사북면   1787 ----------


 ---------- 2010-11-10 17:00:00 : 강남동   1788 ----------


 ---------- 2010-11-10 19:00:00 : 신사우동   1789 ----------


 ---------- 2010-11-11 05:00:00 : 교  동   1790 ----------


 ---------- 2010-11-11 07:00:00 : 동  면   1791 ----------


 ---------- 2010-11-11 08:00:00 : 남산면   1793 ----------


 ---------- 2010-11-11 10:00:00 : 남산면   1794 ----------


 ---------- 2010-11-11 12:00:00 : 신북읍   1795 ----------


 ---------- 2010-11-11 13:00:00 : 퇴계동   1796 ----------


 ---------- 2010-11-11 15:00:00 : 퇴계동   1797 ----------


 ---------- 2010-11-11 16:00:00 : 신사우동   1798 ----------


 ---------- 2010-11-11 18:00:00 : 신북읍   1800 ----------


 ---------- 2010-11-11 19:00:00 : 남산면   1801 ----------


 ---------- 2010-11-11 20:00:00 : 남산면   1802 ----------


 ---------- 2010-11-11 21:00:00 : 효자1동   1803 ----------


 ---------- 2010-11-11 23:00:00 : 후평1동   1804 ----------


 ---------- 2010-11-12 05:00:00 : 근화동   1806 ----------


 ---------- 2010-11-12 14:00:00 : 서  면   1809 ----------


 ---------- 2010-11-12 16:00:00 : 신동면   1810 ----------


 ---------- 2010-11-13 00:00:00 : 효자1동   1811 ----------


 ---------- 2010-11-13 01:00:00 : 석사동   1812 ----------


 ---------- 2010-11-13 06:00:00 : 동내면   1813 ----------


 ---------- 2010-11-13 06:00:00 : 소양동   1814 ----------


 ---------- 2010-11-13 08:00:00 : 신북읍   1815 ----------


 ---------- 2010-11-13 16:00:00 : 동내면   1816 ----------


 ---------- 2010-11-13 17:00:00 : 조운동   1817 ----------


 ---------- 2010-11-13 18:00:00 : 조운동   1818 ----------


 ---------- 2010-11-13 23:00:00 : 후평1동   1819 ----------


 ---------- 2010-11-14 07:00:00 : 후평1동   1820 ----------


 ---------- 2010-11-14 12:00:00 : 북산면   1822 ----------


 ---------- 2010-11-14 13:00:00 : 남산면   1824 ----------


 ---------- 2010-11-14 13:00:00 : 북산면   1826 ----------


 ---------- 2010-11-14 15:00:00 : 남산면   1828 ----------


 ---------- 2010-11-14 17:00:00 : 석사동   1829 ----------


 ---------- 2010-11-15 02:00:00 : 남산면   1830 ----------


 ---------- 2010-11-15 03:00:00 : 후평1동   1831 ----------


 ---------- 2010-11-15 16:00:00 : 소양동   1832 ----------


 ---------- 2010-11-15 16:00:00 : 후평1동   1834 ----------


 ---------- 2010-11-16 09:00:00 : 신사우동   1835 ----------


 ---------- 2010-11-16 14:00:00 : 동내면   1836 ----------


 ---------- 2010-11-16 23:00:00 : 후평1동   1837 ----------


 ---------- 2010-11-17 01:00:00 : 남산면   1838 ----------


 ---------- 2010-11-17 09:00:00 : 후평1동   1839 ----------


 ---------- 2010-11-17 13:00:00 : 퇴계동   1840 ----------


 ---------- 2010-11-17 14:00:00 : 효자1동   1841 ----------


 ---------- 2010-11-17 19:00:00 : 후평1동   1842 ----------


 ---------- 2010-11-18 09:00:00 : 동내면   1843 ----------


 ---------- 2010-11-18 13:00:00 : 동내면   1844 ----------


 ---------- 2010-11-18 14:00:00 : 신동면   1845 ----------


 ---------- 2010-11-18 15:00:00 : 남산면   1847 ----------


 ---------- 2010-11-19 14:00:00 : 후평1동   1848 ----------


 ---------- 2010-11-20 04:00:00 : 후평1동   1849 ----------


 ---------- 2010-11-21 02:00:00 : 석사동   1850 ----------


 ---------- 2010-11-21 03:00:00 : 효자1동   1851 ----------


 ---------- 2010-11-21 04:00:00 : 후평1동   1852 ----------


 ---------- 2010-11-21 10:00:00 : 후평1동   1854 ----------


 ---------- 2010-11-21 19:00:00 : 신사우동   1855 ----------


 ---------- 2010-11-21 19:00:00 : 후평1동   1856 ----------


 ---------- 2010-11-21 22:00:00 : 서  면   1857 ----------


 ---------- 2010-11-22 03:00:00 : 효자1동   1858 ----------


 ---------- 2010-11-22 04:00:00 : 남산면   1859 ----------


 ---------- 2010-11-22 12:00:00 : 효자1동   1860 ----------


 ---------- 2010-11-22 12:00:00 : 조운동   1861 ----------


 ---------- 2010-11-22 21:00:00 : 퇴계동   1862 ----------


 ---------- 2010-11-23 07:00:00 : 신사우동   1863 ----------


 ---------- 2010-11-23 14:00:00 : 소양동   1864 ----------


 ---------- 2010-11-23 16:00:00 : 소양동   1865 ----------


 ---------- 2010-11-24 22:00:00 : 석사동   1866 ----------


 ---------- 2010-11-25 14:00:00 : 후평1동   1867 ----------


 ---------- 2010-11-25 18:00:00 : 석사동   1868 ----------


 ---------- 2010-11-25 23:00:00 : 후평1동   1869 ----------


 ---------- 2010-11-26 08:00:00 : 강남동   1870 ----------


 ---------- 2010-11-26 08:00:00 : 소양동   1871 ----------


 ---------- 2010-11-26 09:00:00 : 퇴계동   1872 ----------


 ---------- 2010-11-26 15:00:00 : 남  면   1873 ----------


 ---------- 2010-11-26 20:00:00 : 동  면   1874 ----------


 ---------- 2010-11-27 07:00:00 : 서  면   1878 ----------


 ---------- 2010-11-27 08:00:00 : 근화동   1880 ----------


 ---------- 2010-11-27 08:00:00 : 동  면   1881 ----------


 ---------- 2010-11-27 15:00:00 : 강남동   1882 ----------


 ---------- 2010-11-27 17:00:00 : 소양동   1883 ----------


 ---------- 2010-11-27 18:00:00 : 근화동   1884 ----------


 ---------- 2010-11-27 20:00:00 : 후평1동   1885 ----------


 ---------- 2010-11-28 00:00:00 : 석사동   1886 ----------


 ---------- 2010-11-28 08:00:00 : 후평1동   1887 ----------

 ---------- 2010-11-28 22:00:00 : 남산면   1889 ----------


 ---------- 2010-11-28 23:00:00 : 소양동   1890 ----------


 ---------- 2010-11-29 20:00:00 : 근화동   1891 ----------


 ---------- 2010-11-29 23:00:00 : 후평1동   1892 ----------


 ---------- 2010-11-30 06:00:00 : 동내면   1893 ----------


 ---------- 2010-11-30 08:00:00 : 신동면   1895 ----------


 ---------- 2010-11-30 12:00:00 : 신사우동   1896 ----------


 ---------- 2010-11-30 22:00:00 : 효자1동   1897 ----------


 ---------- 2010-11-30 23:00:00 : 강남동   1898 ----------


 ---------- 2010-12-01 20:00:00 : 효자1동   1899 ----------


 ---------- 2010-12-02 00:00:00 : 신북읍   1900 ----------


 ---------- 2010-12-02 01:00:00 : 조운동   1901 ----------


 ---------- 2010-12-02 01:00:00 : 교  동   1902 ----------


 ---------- 2010-12-02 09:00:00 : 동내면   1903 ----------


 ---------- 2010-12-02 15:00:00 : 동내면   1904 ----------


 ---------- 2010-12-02 15:00:00 : 후평1동   1905 ----------


 ---------- 2010-12-02 15:00:00 : 퇴계동   1906 ----------


 ---------- 2010-12-02 22:00:00 : 후평1동   1907 ----------


 ---------- 2010-12-03 00:00:00 : 강남동   1908 ----------


 ---------- 2010-12-03 01:00:00 : 신동면   1909 ----------


 ---------- 2010-12-03 07:00:00 : 후평1동   1910 ----------


 ---------- 2010-12-03 11:00:00 : 동  면   1912 ----------


 ---------- 2010-12-03 22:00:00 : 후평1동   1913 ----------


 ---------- 2010-12-04 01:00:00 : 퇴계동   1914 ----------


 ---------- 2010-12-04 17:00:00 : 동  면   1915 ----------


 ---------- 2010-12-04 18:00:00 : 후평1동   1916 ----------


 ---------- 2010-12-05 10:00:00 : 신사우동   1917 ----------


 ---------- 2010-12-05 16:00:00 : 동내면   1918 ----------


 ---------- 2010-12-05 19:00:00 : 석사동   1919 ----------


 ---------- 2010-12-05 20:00:00 : 효자1동   1920 ----------


 ---------- 2010-12-06 00:00:00 : 강남동   1921 ----------


 ---------- 2010-12-06 02:00:00 : 소양동   1922 ----------


 ---------- 2010-12-06 05:00:00 : 효자1동   1923 ----------


 ---------- 2010-12-06 06:00:00 : 효자1동   1924 ----------


 ---------- 2010-12-06 08:00:00 : 강남동   1925 ----------


 ---------- 2010-12-06 15:00:00 : 효자1동   1926 ----------


 ---------- 2010-12-07 10:00:00 : 석사동   1927 ----------


 ---------- 2010-12-07 15:00:00 : 퇴계동   1928 ----------


 ---------- 2010-12-08 11:00:00 : 신동면   1930 ----------


 ---------- 2010-12-09 10:00:00 : 효자1동   1931 ----------


 ---------- 2010-12-09 15:00:00 : 신동면   1933 ----------


 ---------- 2010-12-09 22:00:00 : 퇴계동   1934 ----------


 ---------- 2010-12-10 02:00:00 : 효자1동   1935 ----------


 ---------- 2010-12-10 11:00:00 : 후평1동   1936 ----------


 ---------- 2010-12-10 12:00:00 : 사북면   1937 ----------


 ---------- 2010-12-10 19:00:00 : 서  면   1938 ----------


 ---------- 2010-12-10 21:00:00 : 남산면   1940 ----------


 ---------- 2010-12-10 21:00:00 : 후평1동   1942 ----------


 ---------- 2010-12-10 22:00:00 : 남산면   1943 ----------


 ---------- 2010-12-11 05:00:00 : 후평1동   1945 ----------


 ---------- 2010-12-11 12:00:00 : 남산면   1947 ----------


 ---------- 2010-12-11 13:00:00 : 서  면   1948 ----------


 ---------- 2010-12-11 14:00:00 : 서  면   1950 ----------


 ---------- 2010-12-11 14:00:00 : 동내면   1951 ----------


 ---------- 2010-12-12 00:00:00 : 퇴계동   1952 ----------


 ---------- 2010-12-12 01:00:00 : 남산면   1953 ----------


 ---------- 2010-12-12 10:00:00 : 남산면   1954 ----------


 ---------- 2010-12-12 11:00:00 : 남산면   1955 ----------


 ---------- 2010-12-12 12:00:00 : 강남동   1956 ----------


 ---------- 2010-12-12 21:00:00 : 동산면   1957 ----------


 ---------- 2010-12-13 09:00:00 : 신사우동   1958 ----------


 ---------- 2010-12-13 11:00:00 : 신사우동   1959 ----------


 ---------- 2010-12-13 14:00:00 : 석사동   1960 ----------


 ---------- 2010-12-14 14:00:00 : 효자1동   1961 ----------


 ---------- 2010-12-14 15:00:00 : 효자1동   1962 ----------


 ---------- 2010-12-14 16:00:00 : 후평1동   1963 ----------


 ---------- 2010-12-14 21:00:00 : 후평1동   1964 ----------


 ---------- 2010-12-15 05:00:00 : 동내면   1965 ----------


 ---------- 2010-12-15 11:00:00 : 남산면   1966 ----------


 ---------- 2010-12-15 14:00:00 : 남산면   1967 ----------


 ---------- 2010-12-15 22:00:00 : 후평1동   1968 ----------


 ---------- 2010-12-15 23:00:00 : 강남동   1969 ----------


 ---------- 2010-12-16 06:00:00 : 서  면   1970 ----------


 ---------- 2010-12-16 14:00:00 : 효자1동   1971 ----------


 ---------- 2010-12-16 15:00:00 : 신사우동   1972 ----------


 ---------- 2010-12-16 17:00:00 : 효자1동   1973 ----------


 ---------- 2010-12-16 23:00:00 : 효자1동   1974 ----------


 ---------- 2010-12-17 19:00:00 : 석사동   1975 ----------


 ---------- 2010-12-18 07:00:00 : 동  면   1976 ----------


 ---------- 2010-12-18 09:00:00 : 서  면   1977 ----------


 ---------- 2010-12-18 11:00:00 : 동산면   1978 ----------


 ---------- 2010-12-18 13:00:00 : 신사우동   1979 ----------


 ---------- 2010-12-18 16:00:00 : 동내면   1980 ----------


 ---------- 2010-12-18 20:00:00 : 동  면   1981 ----------


 ---------- 2010-12-19 12:00:00 : 남산면   1982 ----------


 ---------- 2010-12-19 16:00:00 : 남산면   1984 ----------


 ---------- 2010-12-19 17:00:00 : 동내면   1985 ----------


 ---------- 2010-12-20 00:00:00 : 동  면   1986 ----------


 ---------- 2010-12-20 00:00:00 : 퇴계동   1987 ----------


 ---------- 2010-12-20 12:00:00 : 동  면   1988 ----------


 ---------- 2010-12-20 13:00:00 : 동산면   1989 ----------


 ---------- 2010-12-20 17:00:00 : 남산면   1991 ----------


 ---------- 2010-12-20 22:00:00 : 신동면   1992 ----------


 ---------- 2010-12-21 11:00:00 : 동  면   1993 ----------


 ---------- 2010-12-21 20:00:00 : 동내면   1994 ----------


 ---------- 2010-12-21 21:00:00 : 강남동   1995 ----------


 ---------- 2010-12-22 10:00:00 : 교  동   1996 ----------


 ---------- 2010-12-22 12:00:00 : 근화동   1997 ----------


 ---------- 2010-12-22 19:00:00 : 효자1동   1998 ----------


 ---------- 2010-12-22 20:00:00 : 소양동   1999 ----------


 ---------- 2010-12-22 22:00:00 : 효자1동   2000 ----------


 ---------- 2010-12-23 07:00:00 : 효자1동   2001 ----------


 ---------- 2010-12-23 08:00:00 : 신사우동   2002 ----------


 ---------- 2010-12-23 12:00:00 : 강남동   2003 ----------


 ---------- 2010-12-24 04:00:00 : 석사동   2004 ----------


 ---------- 2010-12-24 04:00:00 : 퇴계동   2005 ----------


 ---------- 2010-12-24 14:00:00 : 퇴계동   2006 ----------


 ---------- 2010-12-24 15:00:00 : 신사우동   2007 ----------


 ---------- 2010-12-24 22:00:00 : 약사명동   2008 ----------


 ---------- 2010-12-25 08:00:00 : 신북읍   2009 ----------


 ---------- 2010-12-25 14:00:00 : 남산면   2011 ----------


 ---------- 2010-12-25 15:00:00 : 남산면   2012 ----------


 ---------- 2010-12-26 12:00:00 : 사북면   2013 ----------


 ---------- 2010-12-26 21:00:00 : 효자1동   2014 ----------


 ---------- 2010-12-27 10:00:00 : 약사명동   2015 ----------


 ---------- 2010-12-27 14:00:00 : 남  면   2017 ----------


 ---------- 2010-12-27 16:00:00 : 서  면   2019 ----------


 ---------- 2010-12-27 18:00:00 : 근화동   2020 ----------


 ---------- 2010-12-28 13:00:00 : 신동면   2021 ----------


 ---------- 2010-12-28 14:00:00 : 퇴계동   2022 ----------


 ---------- 2010-12-28 19:00:00 : 신북읍   2023 ----------


 ---------- 2010-12-28 21:00:00 : 남산면   2024 ----------


 ---------- 2010-12-28 22:00:00 : 동  면   2025 ----------


 ---------- 2010-12-29 11:00:00 : 서  면   2028 ----------


 ---------- 2010-12-29 20:00:00 : 강남동   2029 ----------


 ---------- 2010-12-30 08:00:00 : 석사동   2030 ----------


 ---------- 2010-12-30 14:00:00 : 약사명동   2032 ----------


 ---------- 2010-12-30 15:00:00 : 남산면   2033 ----------


 ---------- 2010-12-30 20:00:00 : 석사동   2034 ----------


 ---------- 2010-12-30 21:00:00 : 근화동   2035 ----------


 ---------- 2010-12-30 21:00:00 : 소양동   2036 ----------


 ---------- 2010-12-31 02:00:00 : 신사우동   2037 ----------


 ---------- 2010-12-31 06:00:00 : 조운동   2038 ----------


 ---------- 2010-12-31 13:00:00 : 동내면   2039 ----------


 ---------- 2010-12-31 14:00:00 : 석사동   2040 ----------


 ---------- 2010-12-31 18:00:00 : 조운동   2041 ----------


 ---------- 2010-12-31 21:00:00 : 남산면   2043 ----------


 ---------- 2011-01-01 10:00:00 : 남  면   2045 ----------


 ---------- 2011-01-01 11:00:00 : 강남동   2046 ----------

 ---------- 2011-01-01 15:00:00 : 사북면   2047 ----------


 ---------- 2011-01-01 17:00:00 : 후평1동   2048 ----------


 ---------- 2011-01-02 15:00:00 : 사북면   2049 ----------


 ---------- 2011-01-02 16:00:00 : 북산면   2050 ----------


 ---------- 2011-01-02 20:00:00 : 신사우동   2051 ----------


 ---------- 2011-01-03 13:00:00 : 동내면   2052 ----------


 ---------- 2011-01-03 14:00:00 : 신사우동   2053 ----------


 ---------- 2011-01-03 15:00:00 : 북산면   2055 ----------


 ---------- 2011-01-04 00:00:00 : 약사명동   2056 ----------


 ---------- 2011-01-04 01:00:00 : 남산면   2058 ----------


 ---------- 2011-01-04 09:00:00 : 퇴계동   2059 ----------


 ---------- 2011-01-04 14:00:00 : 남산면   2061 ----------


 ---------- 2011-01-04 16:00:00 : 남  면   2063 ----------


 ---------- 2011-01-04 17:00:00 : 후평1동   2064 ----------


 ---------- 2011-01-05 23:00:00 : 후평1동   2065 ----------


 ---------- 2011-01-06 10:00:00 : 석사동   2066 ----------


 ---------- 2011-01-06 10:00:00 : 약사명동   2067 ----------


 ---------- 2011-01-06 11:00:00 : 신북읍   2069 ----------


 ---------- 2011-01-06 14:00:00 : 신북읍   2070 ----------


 ---------- 2011-01-07 00:00:00 : 석사동   2071 ----------


 ---------- 2011-01-07 00:00:00 : 동  면   2072 ----------


 ---------- 2011-01-07 10:00:00 : 후평1동   2073 ----------


 ---------- 2011-01-08 03:00:00 : 서  면   2075 ----------


 ---------- 2011-01-08 10:00:00 : 사북면   2076 ----------


 ---------- 2011-01-08 11:00:00 : 동내면   2078 ----------


 ---------- 2011-01-08 12:00:00 : 퇴계동   2079 ----------


 ---------- 2011-01-09 03:00:00 : 남산면   2080 ----------


 ---------- 2011-01-09 08:00:00 : 약사명동   2081 ----------


 ---------- 2011-01-09 13:00:00 : 석사동   2082 ----------


 ---------- 2011-01-10 03:00:00 : 약사명동   2083 ----------


 ---------- 2011-01-10 04:00:00 : 석사동   2084 ----------


 ---------- 2011-01-10 21:00:00 : 동내면   2085 ----------


 ---------- 2011-01-11 07:00:00 : 효자1동   2086 ----------


 ---------- 2011-01-11 07:00:00 : 퇴계동   2087 ----------


 ---------- 2011-01-11 08:00:00 : 서  면   2089 ----------


 ---------- 2011-01-11 12:00:00 : 남산면   2090 ----------


 ---------- 2011-01-11 21:00:00 : 동  면   2091 ----------


 ---------- 2011-01-12 02:00:00 : 효자1동   2092 ----------


 ---------- 2011-01-12 14:00:00 : 신북읍   2093 ----------


 ---------- 2011-01-12 21:00:00 : 후평1동   2094 ----------


 ---------- 2011-01-13 03:00:00 : 석사동   2095 ----------


 ---------- 2011-01-13 06:00:00 : 석사동   2096 ----------


 ---------- 2011-01-13 07:00:00 : 후평1동   2097 ----------


 ---------- 2011-01-14 06:00:00 : 남산면   2098 ----------


 ---------- 2011-01-14 08:00:00 : 강남동   2099 ----------


 ---------- 2011-01-14 08:00:00 : 퇴계동   2100 ----------


 ---------- 2011-01-14 09:00:00 : 효자1동   2101 ----------


 ---------- 2011-01-14 10:00:00 : 효자1동   2102 ----------


 ---------- 2011-01-14 11:00:00 : 효자1동   2103 ----------


 ---------- 2011-01-14 15:00:00 : 남산면   2105 ----------


 ---------- 2011-01-14 15:00:00 : 신사우동   2106 ----------


 ---------- 2011-01-14 23:00:00 : 신동면   2107 ----------


 ---------- 2011-01-15 00:00:00 : 효자1동   2108 ----------


 ---------- 2011-01-15 02:00:00 : 소양동   2109 ----------


 ---------- 2011-01-15 05:00:00 : 동  면   2110 ----------


 ---------- 2011-01-15 06:00:00 : 남산면   2111 ----------


 ---------- 2011-01-15 12:00:00 : 신동면   2112 ----------


 ---------- 2011-01-15 21:00:00 : 석사동   2113 ----------


 ---------- 2011-01-16 16:00:00 : 신북읍   2114 ----------


 ---------- 2011-01-16 17:00:00 : 신북읍   2115 ----------


 ---------- 2011-01-16 22:00:00 : 강남동   2116 ----------


 ---------- 2011-01-16 23:00:00 : 근화동   2117 ----------


 ---------- 2011-01-17 00:00:00 : 약사명동   2118 ----------


 ---------- 2011-01-17 12:00:00 : 후평1동   2119 ----------


 ---------- 2011-01-17 16:00:00 : 효자1동   2120 ----------


 ---------- 2011-01-17 19:00:00 : 남산면   2121 ----------


 ---------- 2011-01-18 00:00:00 : 동  면   2122 ----------


 ---------- 2011-01-18 09:00:00 : 조운동   2123 ----------


 ---------- 2011-01-18 19:00:00 : 동  면   2124 ----------


 ---------- 2011-01-19 07:00:00 : 동내면   2125 ----------


 ---------- 2011-01-19 08:00:00 : 북산면   2126 ----------


 ---------- 2011-01-19 12:00:00 : 동내면   2127 ----------


 ---------- 2011-01-19 12:00:00 : 조운동   2128 ----------


 ---------- 2011-01-19 13:00:00 : 교  동   2129 ----------


 ---------- 2011-01-19 19:00:00 : 동  면   2130 ----------


 ---------- 2011-01-19 23:00:00 : 신북읍   2131 ----------


 ---------- 2011-01-20 04:00:00 : 강남동   2132 ----------


 ---------- 2011-01-20 08:00:00 : 소양동   2133 ----------


 ---------- 2011-01-20 12:00:00 : 효자1동   2134 ----------


 ---------- 2011-01-20 14:00:00 : 남산면   2135 ----------


 ---------- 2011-01-20 16:00:00 : 퇴계동   2136 ----------


 ---------- 2011-01-20 20:00:00 : 후평1동   2137 ----------


 ---------- 2011-01-20 21:00:00 : 후평1동   2138 ----------


 ---------- 2011-01-21 00:00:00 : 강남동   2139 ----------


 ---------- 2011-01-21 03:00:00 : 석사동   2140 ----------


 ---------- 2011-01-21 04:00:00 : 효자1동   2141 ----------


 ---------- 2011-01-21 07:00:00 : 동  면   2142 ----------


 ---------- 2011-01-21 08:00:00 : 석사동   2143 ----------


 ---------- 2011-01-21 14:00:00 : 동  면   2144 ----------


 ---------- 2011-01-21 15:00:00 : 후평1동   2145 ----------


 ---------- 2011-01-21 16:00:00 : 근화동   2146 ----------


 ---------- 2011-01-22 12:00:00 : 남산면   2148 ----------


 ---------- 2011-01-22 14:00:00 : 신사우동   2149 ----------


 ---------- 2011-01-22 18:00:00 : 강남동   2150 ----------


 ---------- 2011-01-23 02:00:00 : 서  면   2151 ----------


 ---------- 2011-01-23 02:00:00 : 신사우동   2152 ----------


 ---------- 2011-01-23 07:00:00 : 소양동   2153 ----------


 ---------- 2011-01-23 12:00:00 : 남산면   2155 ----------


 ---------- 2011-01-23 14:00:00 : 서  면   2157 ----------


 ---------- 2011-01-23 16:00:00 : 서  면   2159 ----------


 ---------- 2011-01-24 00:00:00 : 동  면   2160 ----------


 ---------- 2011-01-24 13:00:00 : 남산면   2162 ----------


 ---------- 2011-01-24 22:00:00 : 퇴계동   2163 ----------


 ---------- 2011-01-25 09:00:00 : 후평1동   2164 ----------


 ---------- 2011-01-25 11:00:00 : 신사우동   2165 ----------


 ---------- 2011-01-25 13:00:00 : 신북읍   2166 ----------


 ---------- 2011-01-25 15:00:00 : 신사우동   2167 ----------


 ---------- 2011-01-25 19:00:00 : 남산면   2169 ----------


 ---------- 2011-01-25 21:00:00 : 퇴계동   2170 ----------


 ---------- 2011-01-26 01:00:00 : 소양동   2171 ----------


 ---------- 2011-01-26 21:00:00 : 후평1동   2172 ----------


 ---------- 2011-01-26 22:00:00 : 후평1동   2173 ----------


 ---------- 2011-01-27 18:00:00 : 후평1동   2174 ----------


 ---------- 2011-01-27 20:00:00 : 동  면   2175 ----------


 ---------- 2011-01-27 20:00:00 : 후평1동   2176 ----------


 ---------- 2011-01-28 06:00:00 : 근화동   2177 ----------


 ---------- 2011-01-28 06:00:00 : 후평1동   2178 ----------


 ---------- 2011-01-28 07:00:00 : 교  동   2179 ----------


 ---------- 2011-01-28 09:00:00 : 후평1동   2180 ----------


 ---------- 2011-01-28 17:00:00 : 퇴계동   2181 ----------


 ---------- 2011-01-29 01:00:00 : 석사동   2182 ----------


 ---------- 2011-01-29 09:00:00 : 퇴계동   2183 ----------


 ---------- 2011-01-29 12:00:00 : 동내면   2184 ----------


 ---------- 2011-01-29 13:00:00 : 석사동   2185 ----------


 ---------- 2011-01-29 15:00:00 : 남산면   2186 ----------


 ---------- 2011-01-29 22:00:00 : 퇴계동   2187 ----------


 ---------- 2011-01-30 00:00:00 : 강남동   2188 ----------


 ---------- 2011-01-30 12:00:00 : 퇴계동   2190 ----------


 ---------- 2011-01-30 14:00:00 : 서  면   2191 ----------


 ---------- 2011-01-30 14:00:00 : 효자1동   2192 ----------


 ---------- 2011-01-30 15:00:00 : 남산면   2194 ----------


 ---------- 2011-01-30 16:00:00 : 동내면   2195 ----------


 ---------- 2011-01-31 09:00:00 : 신북읍   2196 ----------


 ---------- 2011-01-31 23:00:00 : 석사동   2197 ----------


 ---------- 2011-01-31 23:00:00 : 서  면   2199 ----------


 ---------- 2011-02-01 07:00:00 : 사북면   2200 ----------


 ---------- 2011-02-01 10:00:00 : 신사우동   2201 ----------


 ---------- 2011-02-01 12:00:00 : 근화동   2202 ----------

 ---------- 2011-02-01 14:00:00 : 효자1동   2203 ----------


 ---------- 2011-02-01 16:00:00 : 효자1동   2204 ----------


 ---------- 2011-02-01 19:00:00 : 후평1동   2205 ----------


 ---------- 2011-02-02 09:00:00 : 효자1동   2206 ----------


 ---------- 2011-02-02 10:00:00 : 효자1동   2207 ----------


 ---------- 2011-02-02 14:00:00 : 효자1동   2208 ----------


 ---------- 2011-02-02 15:00:00 : 소양동   2209 ----------


 ---------- 2011-02-02 20:00:00 : 동내면   2210 ----------


 ---------- 2011-02-02 21:00:00 : 조운동   2211 ----------


 ---------- 2011-02-02 22:00:00 : 효자1동   2212 ----------


 ---------- 2011-02-03 16:00:00 : 남산면   2213 ----------


 ---------- 2011-02-03 18:00:00 : 남  면   2215 ----------


 ---------- 2011-02-03 19:00:00 : 남  면   2216 ----------


 ---------- 2011-02-03 21:00:00 : 후평1동   2217 ----------


 ---------- 2011-02-04 10:00:00 : 동  면   2218 ----------


 ---------- 2011-02-04 17:00:00 : 석사동   2219 ----------


 ---------- 2011-02-04 19:00:00 : 동  면   2220 ----------


 ---------- 2011-02-05 13:00:00 : 강남동   2221 ----------


 ---------- 2011-02-05 23:00:00 : 신동면   2222 ----------


 ---------- 2011-02-06 01:00:00 : 효자1동   2223 ----------


 ---------- 2011-02-06 01:00:00 : 약사명동   2224 ----------


 ---------- 2011-02-06 09:00:00 : 후평1동   2225 ----------


 ---------- 2011-02-06 11:00:00 : 동내면   2226 ----------


 ---------- 2011-02-06 13:00:00 : 신동면   2227 ----------


 ---------- 2011-02-06 14:00:00 : 신동면   2229 ----------


 ---------- 2011-02-06 15:00:00 : 석사동   2230 ----------


 ---------- 2011-02-06 15:00:00 : 신동면   2231 ----------


 ---------- 2011-02-06 19:00:00 : 남산면   2232 ----------


 ---------- 2011-02-06 20:00:00 : 석사동   2233 ----------


 ---------- 2011-02-06 21:00:00 : 남산면   2234 ----------


 ---------- 2011-02-07 01:00:00 : 동내면   2235 ----------


 ---------- 2011-02-07 02:00:00 : 동  면   2236 ----------


 ---------- 2011-02-07 10:00:00 : 남산면   2237 ----------


 ---------- 2011-02-08 03:00:00 : 소양동   2238 ----------


 ---------- 2011-02-08 17:00:00 : 후평1동   2239 ----------


 ---------- 2011-02-09 08:00:00 : 서  면   2241 ----------


 ---------- 2011-02-09 08:00:00 : 동  면   2242 ----------


 ---------- 2011-02-09 13:00:00 : 동내면   2243 ----------


 ---------- 2011-02-09 15:00:00 : 후평1동   2244 ----------


 ---------- 2011-02-09 18:00:00 : 남  면   2246 ----------


 ---------- 2011-02-10 07:00:00 : 효자1동   2247 ----------


 ---------- 2011-02-10 11:00:00 : 후평1동   2248 ----------


 ---------- 2011-02-10 17:00:00 : 소양동   2249 ----------


 ---------- 2011-02-10 18:00:00 : 신동면   2250 ----------


 ---------- 2011-02-11 02:00:00 : 강남동   2251 ----------


 ---------- 2011-02-11 18:00:00 : 신동면   2252 ----------


 ---------- 2011-02-12 12:00:00 : 동산면   2253 ----------


 ---------- 2011-02-12 13:00:00 : 남산면   2255 ----------


 ---------- 2011-02-12 15:00:00 : 교  동   2256 ----------


 ---------- 2011-02-12 17:00:00 : 조운동   2257 ----------


 ---------- 2011-02-12 23:00:00 : 효자1동   2258 ----------


 ---------- 2011-02-13 00:00:00 : 후평1동   2259 ----------


 ---------- 2011-02-13 03:00:00 : 신동면   2260 ----------


 ---------- 2011-02-13 14:00:00 : 남산면   2262 ----------


 ---------- 2011-02-13 22:00:00 : 소양동   2263 ----------


 ---------- 2011-02-14 07:00:00 : 후평1동   2264 ----------


 ---------- 2011-02-14 12:00:00 : 효자1동   2265 ----------


 ---------- 2011-02-14 19:00:00 : 후평1동   2266 ----------


 ---------- 2011-02-15 04:00:00 : 석사동   2267 ----------


 ---------- 2011-02-15 09:00:00 : 후평1동   2268 ----------


 ---------- 2011-02-15 12:00:00 : 동  면   2269 ----------


 ---------- 2011-02-15 14:00:00 : 효자1동   2270 ----------


 ---------- 2011-02-15 16:00:00 : 약사명동   2271 ----------


 ---------- 2011-02-16 03:00:00 : 남산면   2272 ----------


 ---------- 2011-02-16 07:00:00 : 퇴계동   2273 ----------


 ---------- 2011-02-16 10:00:00 : 동  면   2274 ----------


 ---------- 2011-02-16 11:00:00 : 석사동   2275 ----------


 ---------- 2011-02-16 18:00:00 : 남산면   2276 ----------


 ---------- 2011-02-16 19:00:00 : 후평1동   2277 ----------


 ---------- 2011-02-17 07:00:00 : 남산면   2279 ----------


 ---------- 2011-02-17 11:00:00 : 조운동   2280 ----------


 ---------- 2011-02-17 12:00:00 : 근화동   2281 ----------


 ---------- 2011-02-17 18:00:00 : 신사우동   2282 ----------


 ---------- 2011-02-18 11:00:00 : 후평1동   2283 ----------


 ---------- 2011-02-18 14:00:00 : 퇴계동   2284 ----------


 ---------- 2011-02-19 00:00:00 : 후평1동   2285 ----------


 ---------- 2011-02-19 01:00:00 : 신사우동   2286 ----------


 ---------- 2011-02-19 08:00:00 : 소양동   2287 ----------


 ---------- 2011-02-19 18:00:00 : 신북읍   2288 ----------


 ---------- 2011-02-19 19:00:00 : 퇴계동   2289 ----------


 ---------- 2011-02-20 02:00:00 : 석사동   2290 ----------


 ---------- 2011-02-20 09:00:00 : 서  면   2292 ----------


 ---------- 2011-02-20 13:00:00 : 근화동   2293 ----------


 ---------- 2011-02-20 13:00:00 : 신북읍   2295 ----------


 ---------- 2011-02-21 02:00:00 : 남산면   2296 ----------


 ---------- 2011-02-21 13:00:00 : 동내면   2297 ----------


 ---------- 2011-02-21 14:00:00 : 소양동   2298 ----------


 ---------- 2011-02-22 10:00:00 : 퇴계동   2299 ----------


 ---------- 2011-02-22 11:00:00 : 신동면   2300 ----------


 ---------- 2011-02-22 18:00:00 : 교  동   2301 ----------


 ---------- 2011-02-23 09:00:00 : 퇴계동   2302 ----------


 ---------- 2011-02-23 14:00:00 : 강남동   2303 ----------


 ---------- 2011-02-23 23:00:00 : 효자1동   2304 ----------


 ---------- 2011-02-24 18:00:00 : 동  면   2305 ----------


 ---------- 2011-02-24 20:00:00 : 근화동   2306 ----------


 ---------- 2011-02-25 06:00:00 : 남산면   2307 ----------


 ---------- 2011-02-25 12:00:00 : 석사동   2308 ----------


 ---------- 2011-02-26 14:00:00 : 퇴계동   2309 ----------


 ---------- 2011-02-26 20:00:00 : 동내면   2310 ----------


 ---------- 2011-02-26 23:00:00 : 석사동   2311 ----------


 ---------- 2011-02-27 01:00:00 : 서  면   2312 ----------


 ---------- 2011-02-27 05:00:00 : 동  면   2313 ----------


 ---------- 2011-02-27 08:00:00 : 동  면   2314 ----------


 ---------- 2011-02-27 16:00:00 : 북산면   2315 ----------


 ---------- 2011-02-27 18:00:00 : 강남동   2316 ----------


 ---------- 2011-02-27 18:00:00 : 남산면   2317 ----------


 ---------- 2011-02-27 19:00:00 : 동내면   2319 ----------


 ---------- 2011-02-27 19:00:00 : 퇴계동   2320 ----------


 ---------- 2011-02-27 21:00:00 : 남산면   2321 ----------


 ---------- 2011-02-28 04:00:00 : 남  면   2322 ----------


 ---------- 2011-02-28 16:00:00 : 동내면   2323 ----------


 ---------- 2011-02-28 18:00:00 : 석사동   2324 ----------


 ---------- 2011-03-01 13:00:00 : 신사우동   2326 ----------


 ---------- 2011-03-01 18:00:00 : 효자1동   2327 ----------


 ---------- 2011-03-02 00:00:00 : 퇴계동   2329 ----------


 ---------- 2011-03-02 15:00:00 : 석사동   2330 ----------


 ---------- 2011-03-02 19:00:00 : 근화동   2331 ----------


 ---------- 2011-03-03 00:00:00 : 소양동   2332 ----------


 ---------- 2011-03-03 09:00:00 : 퇴계동   2333 ----------


 ---------- 2011-03-03 19:00:00 : 신사우동   2334 ----------


 ---------- 2011-03-04 02:00:00 : 후평1동   2338 ----------


 ---------- 2011-03-04 03:00:00 : 효자1동   2339 ----------


 ---------- 2011-03-04 20:00:00 : 소양동   2340 ----------


 ---------- 2011-03-05 12:00:00 : 동산면   2341 ----------


 ---------- 2011-03-05 16:00:00 : 북산면   2342 ----------


 ---------- 2011-03-05 18:00:00 : 강남동   2343 ----------


 ---------- 2011-03-05 18:00:00 : 동내면   2344 ----------


 ---------- 2011-03-05 18:00:00 : 조운동   2346 ----------


 ---------- 2011-03-05 19:00:00 : 효자1동   2347 ----------


 ---------- 2011-03-05 21:00:00 : 동  면   2348 ----------


 ---------- 2011-03-06 00:00:00 : 후평1동   2349 ----------


 ---------- 2011-03-06 05:00:00 : 효자1동   2350 ----------


 ---------- 2011-03-06 14:00:00 : 서  면   2351 ----------


 ---------- 2011-03-06 15:00:00 : 서  면   2353 ----------


 ---------- 2011-03-06 16:00:00 : 퇴계동   2354 ----------


 ---------- 2011-03-06 16:00:00 : 조운동   2355 ----------


 ---------- 2011-03-06 17:00:00 : 석사동   2356 ----------


 ---------- 2011-03-06 21:00:00 : 동  면   2357 ----------

 ---------- 2011-03-07 01:00:00 : 동  면   2358 ----------


 ---------- 2011-03-07 07:00:00 : 효자1동   2359 ----------


 ---------- 2011-03-07 11:00:00 : 동산면   2360 ----------


 ---------- 2011-03-07 15:00:00 : 남  면   2362 ----------


 ---------- 2011-03-07 16:00:00 : 동  면   2364 ----------


 ---------- 2011-03-08 08:00:00 : 강남동   2365 ----------


 ---------- 2011-03-08 10:00:00 : 동  면   2366 ----------


 ---------- 2011-03-08 13:00:00 : 동  면   2367 ----------


 ---------- 2011-03-09 01:00:00 : 남  면   2368 ----------


 ---------- 2011-03-09 02:00:00 : 신북읍   2369 ----------


 ---------- 2011-03-09 09:00:00 : 약사명동   2370 ----------


 ---------- 2011-03-09 09:00:00 : 동  면   2372 ----------


 ---------- 2011-03-09 14:00:00 : 효자1동   2373 ----------


 ---------- 2011-03-09 17:00:00 : 북산면   2375 ----------


 ---------- 2011-03-10 02:00:00 : 조운동   2376 ----------


 ---------- 2011-03-10 15:00:00 : 남산면   2378 ----------


 ---------- 2011-03-11 03:00:00 : 효자1동   2379 ----------


 ---------- 2011-03-11 05:00:00 : 석사동   2380 ----------


 ---------- 2011-03-11 11:00:00 : 효자1동   2381 ----------


 ---------- 2011-03-12 06:00:00 : 약사명동   2382 ----------


 ---------- 2011-03-12 09:00:00 : 동  면   2383 ----------


 ---------- 2011-03-12 10:00:00 : 서  면   2385 ----------


 ---------- 2011-03-12 10:00:00 : 교  동   2386 ----------


 ---------- 2011-03-12 16:00:00 : 교  동   2387 ----------


 ---------- 2011-03-12 21:00:00 : 동산면   2388 ----------


 ---------- 2011-03-13 15:00:00 : 서  면   2391 ----------


 ---------- 2011-03-13 15:00:00 : 소양동   2392 ----------


 ---------- 2011-03-13 20:00:00 : 동  면   2393 ----------


 ---------- 2011-03-14 12:00:00 : 신사우동   2394 ----------


 ---------- 2011-03-14 21:00:00 : 후평1동   2395 ----------


 ---------- 2011-03-14 22:00:00 : 효자1동   2396 ----------


 ---------- 2011-03-14 23:00:00 : 퇴계동   2397 ----------


 ---------- 2011-03-15 03:00:00 : 효자1동   2398 ----------


 ---------- 2011-03-15 04:00:00 : 동산면   2399 ----------


 ---------- 2011-03-15 21:00:00 : 후평1동   2400 ----------


 ---------- 2011-03-15 22:00:00 : 신동면   2402 ----------


 ---------- 2011-03-16 11:00:00 : 서  면   2403 ----------


 ---------- 2011-03-16 12:00:00 : 신사우동   2404 ----------


 ---------- 2011-03-16 18:00:00 : 석사동   2405 ----------


 ---------- 2011-03-16 23:00:00 : 조운동   2406 ----------


 ---------- 2011-03-17 04:00:00 : 후평1동   2408 ----------


 ---------- 2011-03-17 09:00:00 : 신북읍   2409 ----------


 ---------- 2011-03-17 10:00:00 : 서  면   2411 ----------


 ---------- 2011-03-17 10:00:00 : 남산면   2412 ----------


 ---------- 2011-03-17 11:00:00 : 동내면   2413 ----------


 ---------- 2011-03-17 23:00:00 : 동내면   2414 ----------


 ---------- 2011-03-18 03:00:00 : 소양동   2415 ----------


 ---------- 2011-03-18 08:00:00 : 효자1동   2416 ----------


 ---------- 2011-03-18 09:00:00 : 퇴계동   2417 ----------


 ---------- 2011-03-18 22:00:00 : 효자1동   2418 ----------


 ---------- 2011-03-18 23:00:00 : 신사우동   2420 ----------


 ---------- 2011-03-19 08:00:00 : 신사우동   2422 ----------


 ---------- 2011-03-19 11:00:00 : 석사동   2423 ----------


 ---------- 2011-03-19 13:00:00 : 효자1동   2424 ----------


 ---------- 2011-03-19 14:00:00 : 동내면   2425 ----------


 ---------- 2011-03-19 18:00:00 : 동산면   2426 ----------


 ---------- 2011-03-20 00:00:00 : 석사동   2427 ----------


 ---------- 2011-03-20 01:00:00 : 동산면   2428 ----------


 ---------- 2011-03-21 12:00:00 : 동산면   2429 ----------


 ---------- 2011-03-21 16:00:00 : 후평1동   2430 ----------


 ---------- 2011-03-21 19:00:00 : 신사우동   2431 ----------


 ---------- 2011-03-22 11:00:00 : 동내면   2432 ----------


 ---------- 2011-03-22 23:00:00 : 석사동   2433 ----------


 ---------- 2011-03-23 11:00:00 : 서  면   2434 ----------


 ---------- 2011-03-23 15:00:00 : 근화동   2435 ----------


 ---------- 2011-03-23 16:00:00 : 남산면   2436 ----------


 ---------- 2011-03-23 22:00:00 : 후평1동   2437 ----------


 ---------- 2011-03-24 10:00:00 : 약사명동   2438 ----------


 ---------- 2011-03-24 14:00:00 : 신동면   2439 ----------


 ---------- 2011-03-24 14:00:00 : 동산면   2440 ----------


 ---------- 2011-03-24 17:00:00 : 후평1동   2441 ----------


 ---------- 2011-03-24 21:00:00 : 퇴계동   2442 ----------


 ---------- 2011-03-24 22:00:00 : 후평1동   2443 ----------


 ---------- 2011-03-25 02:00:00 : 후평1동   2444 ----------


 ---------- 2011-03-25 11:00:00 : 후평1동   2445 ----------


 ---------- 2011-03-26 03:00:00 : 후평1동   2446 ----------


 ---------- 2011-03-26 12:00:00 : 서  면   2448 ----------


 ---------- 2011-03-26 18:00:00 : 후평1동   2449 ----------


 ---------- 2011-03-27 06:00:00 : 소양동   2450 ----------


 ---------- 2011-03-27 16:00:00 : 강남동   2451 ----------


 ---------- 2011-03-27 19:00:00 : 퇴계동   2452 ----------


 ---------- 2011-03-27 20:00:00 : 후평1동   2453 ----------


 ---------- 2011-03-27 23:00:00 : 남  면   2455 ----------


 ---------- 2011-03-28 13:00:00 : 남산면   2456 ----------


 ---------- 2011-03-28 19:00:00 : 효자1동   2457 ----------


 ---------- 2011-03-29 00:00:00 : 근화동   2458 ----------


 ---------- 2011-03-29 09:00:00 : 동  면   2459 ----------


 ---------- 2011-03-29 11:00:00 : 동내면   2460 ----------


 ---------- 2011-03-29 13:00:00 : 강남동   2461 ----------


 ---------- 2011-03-29 14:00:00 : 동  면   2462 ----------


 ---------- 2011-03-30 15:00:00 : 신북읍   2463 ----------


 ---------- 2011-03-31 19:00:00 : 석사동   2464 ----------


 ---------- 2011-03-31 20:00:00 : 강남동   2465 ----------


 ---------- 2011-04-01 11:00:00 : 효자1동   2466 ----------


 ---------- 2011-04-01 13:00:00 : 후평1동   2467 ----------


 ---------- 2011-04-01 17:00:00 : 후평1동   2468 ----------


 ---------- 2011-04-02 01:00:00 : 약사명동   2469 ----------


 ---------- 2011-04-02 09:00:00 : 사북면   2470 ----------


 ---------- 2011-04-02 14:00:00 : 석사동   2471 ----------


 ---------- 2011-04-02 15:00:00 : 서  면   2473 ----------


 ---------- 2011-04-02 16:00:00 : 신사우동   2474 ----------


 ---------- 2011-04-03 01:00:00 : 소양동   2475 ----------


 ---------- 2011-04-03 12:00:00 : 북산면   2476 ----------


 ---------- 2011-04-03 13:00:00 : 퇴계동   2477 ----------


 ---------- 2011-04-03 17:00:00 : 신북읍   2478 ----------


 ---------- 2011-04-03 19:00:00 : 북산면   2479 ----------


 ---------- 2011-04-03 23:00:00 : 후평1동   2480 ----------


 ---------- 2011-04-04 09:00:00 : 강남동   2481 ----------


 ---------- 2011-04-04 09:00:00 : 서  면   2483 ----------


 ---------- 2011-04-04 10:00:00 : 서  면   2484 ----------


 ---------- 2011-04-04 13:00:00 : 후평1동   2485 ----------


 ---------- 2011-04-04 14:00:00 : 후평1동   2486 ----------


 ---------- 2011-04-05 01:00:00 : 강남동   2487 ----------


 ---------- 2011-04-05 02:00:00 : 신사우동   2488 ----------


 ---------- 2011-04-05 10:00:00 : 신사우동   2489 ----------


 ---------- 2011-04-05 20:00:00 : 동산면   2491 ----------


 ---------- 2011-04-06 01:00:00 : 효자1동   2492 ----------


 ---------- 2011-04-06 08:00:00 : 석사동   2493 ----------


 ---------- 2011-04-06 11:00:00 : 동내면   2494 ----------


 ---------- 2011-04-06 20:00:00 : 남산면   2495 ----------


 ---------- 2011-04-06 23:00:00 : 효자1동   2496 ----------


 ---------- 2011-04-07 08:00:00 : 후평1동   2497 ----------


 ---------- 2011-04-08 01:00:00 : 강남동   2498 ----------


 ---------- 2011-04-08 15:00:00 : 근화동   2499 ----------


 ---------- 2011-04-08 19:00:00 : 퇴계동   2500 ----------


 ---------- 2011-04-08 20:00:00 : 후평1동   2501 ----------


 ---------- 2011-04-09 09:00:00 : 효자1동   2502 ----------


 ---------- 2011-04-09 10:00:00 : 남  면   2503 ----------


 ---------- 2011-04-09 10:00:00 : 후평1동   2504 ----------


 ---------- 2011-04-09 11:00:00 : 남  면   2505 ----------


 ---------- 2011-04-09 23:00:00 : 남산면   2506 ----------


 ---------- 2011-04-10 01:00:00 : 남산면   2507 ----------


 ---------- 2011-04-10 05:00:00 : 사북면   2508 ----------


 ---------- 2011-04-10 13:00:00 : 동  면   2509 ----------


 ---------- 2011-04-10 15:00:00 : 남산면   2511 ----------


 ---------- 2011-04-10 17:00:00 : 교  동   2512 ----------


 ---------- 2011-04-11 09:00:00 : 교  동   2513 ----------


 ---------- 2011-04-11 18:00:00 : 교  동   2514 ----------

 ---------- 2011-04-11 21:00:00 : 후평1동   2515 ----------


 ---------- 2011-04-12 06:00:00 : 서  면   2516 ----------


 ---------- 2011-04-12 10:00:00 : 신동면   2517 ----------


 ---------- 2011-04-12 11:00:00 : 신동면   2518 ----------


 ---------- 2011-04-12 14:00:00 : 신북읍   2519 ----------


 ---------- 2011-04-12 15:00:00 : 신북읍   2520 ----------


 ---------- 2011-04-12 16:00:00 : 교  동   2521 ----------


 ---------- 2011-04-12 20:00:00 : 교  동   2522 ----------


 ---------- 2011-04-13 07:00:00 : 신동면   2523 ----------


 ---------- 2011-04-13 09:00:00 : 효자1동   2524 ----------


 ---------- 2011-04-13 13:00:00 : 후평1동   2525 ----------


 ---------- 2011-04-13 16:00:00 : 조운동   2526 ----------


 ---------- 2011-04-13 21:00:00 : 후평1동   2527 ----------


 ---------- 2011-04-13 23:00:00 : 교  동   2528 ----------


 ---------- 2011-04-14 07:00:00 : 동내면   2529 ----------


 ---------- 2011-04-14 10:00:00 : 동내면   2530 ----------


 ---------- 2011-04-14 14:00:00 : 사북면   2531 ----------


 ---------- 2011-04-14 19:00:00 : 신사우동   2532 ----------


 ---------- 2011-04-14 23:00:00 : 석사동   2533 ----------


 ---------- 2011-04-15 12:00:00 : 석사동   2534 ----------


 ---------- 2011-04-15 21:00:00 : 석사동   2535 ----------


 ---------- 2011-04-15 22:00:00 : 퇴계동   2536 ----------


 ---------- 2011-04-16 03:00:00 : 약사명동   2537 ----------


 ---------- 2011-04-16 04:00:00 : 신사우동   2538 ----------


 ---------- 2011-04-16 05:00:00 : 효자1동   2539 ----------


 ---------- 2011-04-16 07:00:00 : 효자1동   2540 ----------


 ---------- 2011-04-16 10:00:00 : 서  면   2541 ----------


 ---------- 2011-04-16 12:00:00 : 신동면   2542 ----------


 ---------- 2011-04-16 18:00:00 : 동산면   2544 ----------


 ---------- 2011-04-16 19:00:00 : 소양동   2545 ----------


 ---------- 2011-04-17 03:00:00 : 석사동   2547 ----------


 ---------- 2011-04-17 03:00:00 : 근화동   2548 ----------


 ---------- 2011-04-17 09:00:00 : 동  면   2549 ----------


 ---------- 2011-04-17 09:00:00 : 후평1동   2550 ----------


 ---------- 2011-04-17 16:00:00 : 후평1동   2551 ----------


 ---------- 2011-04-17 18:00:00 : 북산면   2552 ----------


 ---------- 2011-04-17 22:00:00 : 동  면   2553 ----------


 ---------- 2011-04-18 06:00:00 : 약사명동   2554 ----------


 ---------- 2011-04-18 17:00:00 : 동산면   2555 ----------


 ---------- 2011-04-18 19:00:00 : 신동면   2556 ----------


 ---------- 2011-04-18 21:00:00 : 퇴계동   2557 ----------


 ---------- 2011-04-19 00:00:00 : 효자1동   2558 ----------


 ---------- 2011-04-19 01:00:00 : 후평1동   2559 ----------


 ---------- 2011-04-19 05:00:00 : 소양동   2560 ----------


 ---------- 2011-04-19 12:00:00 : 석사동   2561 ----------


 ---------- 2011-04-19 14:00:00 : 석사동   2562 ----------


 ---------- 2011-04-19 18:00:00 : 남  면   2563 ----------


 ---------- 2011-04-19 21:00:00 : 석사동   2564 ----------


 ---------- 2011-04-19 22:00:00 : 동산면   2565 ----------


 ---------- 2011-04-20 14:00:00 : 남산면   2567 ----------


 ---------- 2011-04-20 20:00:00 : 후평1동   2568 ----------


 ---------- 2011-04-21 02:00:00 : 근화동   2569 ----------


 ---------- 2011-04-21 15:00:00 : 석사동   2570 ----------


 ---------- 2011-04-21 20:00:00 : 퇴계동   2571 ----------


 ---------- 2011-04-21 21:00:00 : 효자1동   2572 ----------


 ---------- 2011-04-22 11:00:00 : 북산면   2573 ----------


 ---------- 2011-04-23 13:00:00 : 석사동   2574 ----------


 ---------- 2011-04-24 05:00:00 : 후평1동   2575 ----------


 ---------- 2011-04-24 08:00:00 : 동내면   2576 ----------


 ---------- 2011-04-24 10:00:00 : 신북읍   2577 ----------


 ---------- 2011-04-24 13:00:00 : 퇴계동   2578 ----------


 ---------- 2011-04-25 09:00:00 : 동내면   2579 ----------


 ---------- 2011-04-25 13:00:00 : 효자1동   2580 ----------


 ---------- 2011-04-25 19:00:00 : 효자1동   2581 ----------


 ---------- 2011-04-26 01:00:00 : 석사동   2582 ----------


 ---------- 2011-04-26 02:00:00 : 석사동   2583 ----------


 ---------- 2011-04-26 02:00:00 : 효자1동   2584 ----------


 ---------- 2011-04-26 13:00:00 : 후평1동   2585 ----------


 ---------- 2011-04-27 04:00:00 : 퇴계동   2586 ----------


 ---------- 2011-04-27 06:00:00 : 동  면   2587 ----------


 ---------- 2011-04-27 06:00:00 : 후평1동   2588 ----------


 ---------- 2011-04-27 08:00:00 : 신북읍   2589 ----------


 ---------- 2011-04-27 18:00:00 : 남산면   2590 ----------


 ---------- 2011-04-28 04:00:00 : 효자1동   2591 ----------


 ---------- 2011-04-28 08:00:00 : 동내면   2592 ----------


 ---------- 2011-04-28 15:00:00 : 후평1동   2593 ----------


 ---------- 2011-04-28 18:00:00 : 서  면   2594 ----------


 ---------- 2011-04-28 20:00:00 : 석사동   2595 ----------


 ---------- 2011-04-28 20:00:00 : 근화동   2596 ----------


 ---------- 2011-04-29 12:00:00 : 석사동   2597 ----------


 ---------- 2011-04-29 13:00:00 : 북산면   2598 ----------


 ---------- 2011-04-29 16:00:00 : 신동면   2600 ----------


 ---------- 2011-04-29 18:00:00 : 신사우동   2601 ----------


 ---------- 2011-04-29 18:00:00 : 동  면   2602 ----------


 ---------- 2011-04-29 19:00:00 : 후평1동   2603 ----------


 ---------- 2011-04-30 03:00:00 : 효자1동   2604 ----------


 ---------- 2011-04-30 04:00:00 : 석사동   2605 ----------


 ---------- 2011-04-30 04:00:00 : 신동면   2607 ----------


 ---------- 2011-04-30 09:00:00 : 석사동   2609 ----------


 ---------- 2011-04-30 10:00:00 : 남산면   2610 ----------


 ---------- 2011-04-30 18:00:00 : 남산면   2612 ----------


 ---------- 2011-05-01 21:00:00 : 퇴계동   2613 ----------


 ---------- 2011-05-02 02:00:00 : 교  동   2614 ----------


 ---------- 2011-05-03 08:00:00 : 퇴계동   2615 ----------


 ---------- 2011-05-03 10:00:00 : 신사우동   2616 ----------


 ---------- 2011-05-03 18:00:00 : 신사우동   2617 ----------


 ---------- 2011-05-03 18:00:00 : 퇴계동   2618 ----------


 ---------- 2011-05-03 19:00:00 : 후평1동   2619 ----------


 ---------- 2011-05-04 10:00:00 : 석사동   2620 ----------


 ---------- 2011-05-04 21:00:00 : 강남동   2621 ----------


 ---------- 2011-05-05 09:00:00 : 동  면   2622 ----------


 ---------- 2011-05-05 14:00:00 : 서  면   2624 ----------


 ---------- 2011-05-05 16:00:00 : 효자1동   2625 ----------


 ---------- 2011-05-05 18:00:00 : 신사우동   2626 ----------


 ---------- 2011-05-05 21:00:00 : 후평1동   2627 ----------


 ---------- 2011-05-06 13:00:00 : 퇴계동   2628 ----------


 ---------- 2011-05-06 14:00:00 : 약사명동   2629 ----------


 ---------- 2011-05-06 16:00:00 : 약사명동   2630 ----------


 ---------- 2011-05-06 18:00:00 : 강남동   2631 ----------


 ---------- 2011-05-07 19:00:00 : 사북면   2632 ----------


 ---------- 2011-05-07 20:00:00 : 석사동   2633 ----------


 ---------- 2011-05-08 12:00:00 : 신동면   2636 ----------


 ---------- 2011-05-08 13:00:00 : 후평1동   2637 ----------


 ---------- 2011-05-08 14:00:00 : 소양동   2638 ----------


 ---------- 2011-05-08 17:00:00 : 남  면   2639 ----------


 ---------- 2011-05-08 20:00:00 : 남산면   2640 ----------


 ---------- 2011-05-09 13:00:00 : 근화동   2641 ----------


 ---------- 2011-05-09 14:00:00 : 서  면   2642 ----------


 ---------- 2011-05-09 14:00:00 : 사북면   2643 ----------


 ---------- 2011-05-10 14:00:00 : 신북읍   2644 ----------


 ---------- 2011-05-10 18:00:00 : 석사동   2645 ----------


 ---------- 2011-05-10 19:00:00 : 동산면   2646 ----------


 ---------- 2011-05-10 20:00:00 : 동  면   2647 ----------


 ---------- 2011-05-11 09:00:00 : 북산면   2648 ----------


 ---------- 2011-05-11 13:00:00 : 사북면   2649 ----------


 ---------- 2011-05-11 19:00:00 : 동내면   2650 ----------


 ---------- 2011-05-12 11:00:00 : 후평1동   2651 ----------


 ---------- 2011-05-12 15:00:00 : 동  면   2652 ----------


 ---------- 2011-05-12 21:00:00 : 근화동   2653 ----------


 ---------- 2011-05-13 11:00:00 : 동산면   2654 ----------


 ---------- 2011-05-14 14:00:00 : 효자1동   2655 ----------


 ---------- 2011-05-14 20:00:00 : 근화동   2656 ----------


 ---------- 2011-05-15 09:00:00 : 사북면   2658 ----------


 ---------- 2011-05-15 11:00:00 : 후평1동   2659 ----------


 ---------- 2011-05-15 12:00:00 : 동  면   2660 ----------


 ---------- 2011-05-15 13:00:00 : 퇴계동   2661 ----------


 ---------- 2011-05-15 15:00:00 : 후평1동   2662 ----------


 ---------- 2011-05-16 03:00:00 : 석사동   2663 ----------

 ---------- 2011-05-16 10:00:00 : 동내면   2664 ----------


 ---------- 2011-05-16 13:00:00 : 동내면   2665 ----------


 ---------- 2011-05-16 15:00:00 : 후평1동   2666 ----------


 ---------- 2011-05-16 23:00:00 : 효자1동   2667 ----------


 ---------- 2011-05-17 00:00:00 : 효자1동   2668 ----------


 ---------- 2011-05-17 02:00:00 : 석사동   2669 ----------


 ---------- 2011-05-17 07:00:00 : 신사우동   2670 ----------


 ---------- 2011-05-17 16:00:00 : 강남동   2671 ----------


 ---------- 2011-05-17 18:00:00 : 후평1동   2672 ----------


 ---------- 2011-05-17 20:00:00 : 남산면   2673 ----------


 ---------- 2011-05-18 00:00:00 : 후평1동   2674 ----------


 ---------- 2011-05-18 03:00:00 : 효자1동   2675 ----------


 ---------- 2011-05-18 04:00:00 : 신사우동   2676 ----------


 ---------- 2011-05-18 06:00:00 : 퇴계동   2677 ----------


 ---------- 2011-05-18 08:00:00 : 동내면   2678 ----------


 ---------- 2011-05-18 11:00:00 : 석사동   2679 ----------


 ---------- 2011-05-18 13:00:00 : 소양동   2680 ----------


 ---------- 2011-05-18 14:00:00 : 근화동   2681 ----------


 ---------- 2011-05-18 15:00:00 : 신동면   2682 ----------


 ---------- 2011-05-18 19:00:00 : 소양동   2683 ----------


 ---------- 2011-05-19 01:00:00 : 신사우동   2684 ----------


 ---------- 2011-05-19 07:00:00 : 서  면   2685 ----------


 ---------- 2011-05-19 09:00:00 : 근화동   2686 ----------


 ---------- 2011-05-19 18:00:00 : 신북읍   2687 ----------


 ---------- 2011-05-19 21:00:00 : 효자1동   2688 ----------


 ---------- 2011-05-19 23:00:00 : 남산면   2689 ----------


 ---------- 2011-05-20 11:00:00 : 후평1동   2690 ----------


 ---------- 2011-05-20 21:00:00 : 강남동   2691 ----------


 ---------- 2011-05-20 23:00:00 : 동내면   2692 ----------


 ---------- 2011-05-21 20:00:00 : 동  면   2693 ----------


 ---------- 2011-05-22 00:00:00 : 후평1동   2694 ----------


 ---------- 2011-05-22 05:00:00 : 효자1동   2696 ----------


 ---------- 2011-05-22 10:00:00 : 서  면   2698 ----------


 ---------- 2011-05-22 12:00:00 : 서  면   2699 ----------


 ---------- 2011-05-22 13:00:00 : 서  면   2700 ----------


 ---------- 2011-05-22 16:00:00 : 동내면   2701 ----------


 ---------- 2011-05-22 17:00:00 : 북산면   2702 ----------


 ---------- 2011-05-23 08:00:00 : 신동면   2703 ----------


 ---------- 2011-05-23 10:00:00 : 신동면   2705 ----------


 ---------- 2011-05-23 17:00:00 : 후평1동   2706 ----------


 ---------- 2011-05-23 18:00:00 : 강남동   2707 ----------


 ---------- 2011-05-23 19:00:00 : 근화동   2708 ----------


 ---------- 2011-05-24 00:00:00 : 효자1동   2710 ----------


 ---------- 2011-05-24 17:00:00 : 신동면   2711 ----------


 ---------- 2011-05-25 06:00:00 : 신사우동   2712 ----------


 ---------- 2011-05-25 11:00:00 : 약사명동   2713 ----------


 ---------- 2011-05-25 14:00:00 : 신동면   2714 ----------


 ---------- 2011-05-25 16:00:00 : 석사동   2715 ----------


 ---------- 2011-05-25 20:00:00 : 동내면   2717 ----------


 ---------- 2011-05-25 20:00:00 : 조운동   2718 ----------


 ---------- 2011-05-26 05:00:00 : 동  면   2719 ----------


 ---------- 2011-05-26 13:00:00 : 서  면   2720 ----------


 ---------- 2011-05-26 15:00:00 : 석사동   2721 ----------


 ---------- 2011-05-26 20:00:00 : 석사동   2722 ----------


 ---------- 2011-05-27 03:00:00 : 효자1동   2723 ----------


 ---------- 2011-05-27 12:00:00 : 후평1동   2724 ----------


 ---------- 2011-05-27 15:00:00 : 근화동   2725 ----------


 ---------- 2011-05-27 22:00:00 : 후평1동   2726 ----------


 ---------- 2011-05-28 08:00:00 : 신사우동   2727 ----------


 ---------- 2011-05-28 10:00:00 : 석사동   2729 ----------


 ---------- 2011-05-28 15:00:00 : 북산면   2732 ----------


 ---------- 2011-05-28 17:00:00 : 강남동   2733 ----------


 ---------- 2011-05-28 22:00:00 : 동내면   2734 ----------


 ---------- 2011-05-29 02:00:00 : 동산면   2735 ----------


 ---------- 2011-05-29 05:00:00 : 신북읍   2737 ----------


 ---------- 2011-05-29 11:00:00 : 서  면   2739 ----------


 ---------- 2011-05-29 11:00:00 : 소양동   2740 ----------


 ---------- 2011-05-29 14:00:00 : 남  면   2742 ----------


 ---------- 2011-05-29 15:00:00 : 북산면   2743 ----------


 ---------- 2011-05-29 16:00:00 : 신북읍   2744 ----------


 ---------- 2011-05-30 03:00:00 : 석사동   2745 ----------


 ---------- 2011-05-30 12:00:00 : 신동면   2746 ----------


 ---------- 2011-05-31 11:00:00 : 효자1동   2747 ----------


 ---------- 2011-06-01 19:00:00 : 석사동   2749 ----------


 ---------- 2011-06-02 15:00:00 : 효자1동   2750 ----------


 ---------- 2011-06-02 16:00:00 : 조운동   2751 ----------


 ---------- 2011-06-02 19:00:00 : 동산면   2752 ----------


 ---------- 2011-06-02 20:00:00 : 효자1동   2753 ----------


 ---------- 2011-06-03 02:00:00 : 강남동   2754 ----------


 ---------- 2011-06-03 11:00:00 : 소양동   2755 ----------


 ---------- 2011-06-03 13:00:00 : 신동면   2756 ----------


 ---------- 2011-06-03 15:00:00 : 후평1동   2757 ----------


 ---------- 2011-06-03 22:00:00 : 후평1동   2758 ----------


 ---------- 2011-06-03 23:00:00 : 후평1동   2759 ----------


 ---------- 2011-06-04 02:00:00 : 퇴계동   2760 ----------


 ---------- 2011-06-04 03:00:00 : 약사명동   2761 ----------


 ---------- 2011-06-04 13:00:00 : 근화동   2762 ----------


 ---------- 2011-06-04 14:00:00 : 북산면   2763 ----------


 ---------- 2011-06-04 19:00:00 : 동내면   2764 ----------


 ---------- 2011-06-05 08:00:00 : 동내면   2765 ----------


 ---------- 2011-06-05 09:00:00 : 동내면   2766 ----------


 ---------- 2011-06-05 11:00:00 : 남산면   2768 ----------


 ---------- 2011-06-05 12:00:00 : 사북면   2769 ----------


 ---------- 2011-06-05 14:00:00 : 동산면   2770 ----------


 ---------- 2011-06-05 15:00:00 : 동산면   2772 ----------


 ---------- 2011-06-05 20:00:00 : 약사명동   2773 ----------


 ---------- 2011-06-06 01:00:00 : 근화동   2774 ----------


 ---------- 2011-06-06 08:00:00 : 석사동   2775 ----------


 ---------- 2011-06-06 10:00:00 : 신북읍   2776 ----------


 ---------- 2011-06-06 13:00:00 : 사북면   2777 ----------


 ---------- 2011-06-06 15:00:00 : 신북읍   2778 ----------


 ---------- 2011-06-06 19:00:00 : 조운동   2779 ----------


 ---------- 2011-06-06 20:00:00 : 효자1동   2780 ----------


 ---------- 2011-06-06 20:00:00 : 퇴계동   2781 ----------


 ---------- 2011-06-07 01:00:00 : 퇴계동   2782 ----------


 ---------- 2011-06-07 07:00:00 : 후평1동   2783 ----------


 ---------- 2011-06-07 09:00:00 : 신사우동   2784 ----------


 ---------- 2011-06-07 10:00:00 : 동산면   2785 ----------


 ---------- 2011-06-07 14:00:00 : 강남동   2786 ----------


 ---------- 2011-06-08 00:00:00 : 근화동   2787 ----------


 ---------- 2011-06-08 01:00:00 : 효자1동   2788 ----------


 ---------- 2011-06-08 02:00:00 : 석사동   2789 ----------


 ---------- 2011-06-08 05:00:00 : 동  면   2790 ----------


 ---------- 2011-06-08 13:00:00 : 동  면   2791 ----------


 ---------- 2011-06-08 16:00:00 : 후평1동   2792 ----------


 ---------- 2011-06-09 08:00:00 : 사북면   2794 ----------


 ---------- 2011-06-09 23:00:00 : 근화동   2795 ----------


 ---------- 2011-06-10 08:00:00 : 남산면   2797 ----------


 ---------- 2011-06-10 09:00:00 : 석사동   2798 ----------


 ---------- 2011-06-10 13:00:00 : 조운동   2799 ----------


 ---------- 2011-06-10 14:00:00 : 서  면   2802 ----------


 ---------- 2011-06-10 15:00:00 : 서  면   2803 ----------


 ---------- 2011-06-10 15:00:00 : 신사우동   2804 ----------


 ---------- 2011-06-11 13:00:00 : 석사동   2805 ----------


 ---------- 2011-06-11 14:00:00 : 동  면   2806 ----------


 ---------- 2011-06-11 19:00:00 : 신동면   2807 ----------


 ---------- 2011-06-12 09:00:00 : 강남동   2808 ----------


 ---------- 2011-06-12 13:00:00 : 서  면   2809 ----------


 ---------- 2011-06-12 17:00:00 : 퇴계동   2810 ----------


 ---------- 2011-06-12 22:00:00 : 신북읍   2811 ----------


 ---------- 2011-06-12 23:00:00 : 후평1동   2812 ----------


 ---------- 2011-06-13 02:00:00 : 후평1동   2813 ----------


 ---------- 2011-06-13 06:00:00 : 신동면   2814 ----------


 ---------- 2011-06-13 10:00:00 : 동  면   2815 ----------


 ---------- 2011-06-13 16:00:00 : 서  면   2816 ----------


 ---------- 2011-06-14 10:00:00 : 신북읍   2817 ----------


 ---------- 2011-06-15 14:00:00 : 북산면   2818 ----------


 ---------- 2011-06-15 22:00:00 : 퇴계동   2819 ----------

 ---------- 2011-06-16 00:00:00 : 후평1동   2821 ----------


 ---------- 2011-06-16 03:00:00 : 석사동   2822 ----------


 ---------- 2011-06-16 09:00:00 : 석사동   2823 ----------


 ---------- 2011-06-16 11:00:00 : 서  면   2824 ----------


 ---------- 2011-06-16 14:00:00 : 석사동   2825 ----------


 ---------- 2011-06-16 16:00:00 : 강남동   2828 ----------


 ---------- 2011-06-16 16:00:00 : 후평1동   2829 ----------


 ---------- 2011-06-16 19:00:00 : 후평1동   2830 ----------


 ---------- 2011-06-16 20:00:00 : 퇴계동   2832 ----------


 ---------- 2011-06-17 12:00:00 : 소양동   2833 ----------


 ---------- 2011-06-18 08:00:00 : 효자1동   2834 ----------


 ---------- 2011-06-18 11:00:00 : 교  동   2835 ----------


 ---------- 2011-06-18 13:00:00 : 남산면   2836 ----------


 ---------- 2011-06-18 15:00:00 : 소양동   2837 ----------


 ---------- 2011-06-18 16:00:00 : 동산면   2840 ----------


 ---------- 2011-06-19 03:00:00 : 신북읍   2841 ----------


 ---------- 2011-06-19 04:00:00 : 석사동   2842 ----------


 ---------- 2011-06-19 14:00:00 : 퇴계동   2843 ----------


 ---------- 2011-06-19 15:00:00 : 석사동   2844 ----------


 ---------- 2011-06-20 01:00:00 : 동내면   2845 ----------


 ---------- 2011-06-20 10:00:00 : 동  면   2846 ----------


 ---------- 2011-06-20 12:00:00 : 소양동   2847 ----------


 ---------- 2011-06-20 13:00:00 : 신사우동   2848 ----------


 ---------- 2011-06-20 14:00:00 : 퇴계동   2849 ----------


 ---------- 2011-06-21 09:00:00 : 강남동   2850 ----------


 ---------- 2011-06-21 11:00:00 : 근화동   2851 ----------


 ---------- 2011-06-21 13:00:00 : 후평1동   2852 ----------


 ---------- 2011-06-21 14:00:00 : 신사우동   2853 ----------


 ---------- 2011-06-21 14:00:00 : 퇴계동   2854 ----------


 ---------- 2011-06-21 16:00:00 : 남산면   2856 ----------


 ---------- 2011-06-21 20:00:00 : 효자1동   2857 ----------


 ---------- 2011-06-22 03:00:00 : 효자1동   2858 ----------


 ---------- 2011-06-22 12:00:00 : 남산면   2859 ----------


 ---------- 2011-06-22 12:00:00 : 동  면   2860 ----------


 ---------- 2011-06-22 12:00:00 : 퇴계동   2861 ----------


 ---------- 2011-06-22 13:00:00 : 근화동   2862 ----------


 ---------- 2011-06-22 17:00:00 : 신사우동   2864 ----------


 ---------- 2011-06-22 17:00:00 : 동산면   2868 ----------


 ---------- 2011-06-23 00:00:00 : 신사우동   2869 ----------


 ---------- 2011-06-23 03:00:00 : 조운동   2870 ----------


 ---------- 2011-06-23 07:00:00 : 소양동   2871 ----------


 ---------- 2011-06-23 11:00:00 : 신동면   2873 ----------


 ---------- 2011-06-23 12:00:00 : 후평1동   2875 ----------


 ---------- 2011-06-23 14:00:00 : 효자1동   2876 ----------


 ---------- 2011-06-23 16:00:00 : 효자1동   2877 ----------


 ---------- 2011-06-23 16:00:00 : 후평1동   2878 ----------


 ---------- 2011-06-23 17:00:00 : 효자1동   2879 ----------


 ---------- 2011-06-24 08:00:00 : 퇴계동   2880 ----------


 ---------- 2011-06-24 09:00:00 : 강남동   2881 ----------


 ---------- 2011-06-24 10:00:00 : 동내면   2882 ----------


 ---------- 2011-06-24 12:00:00 : 후평1동   2883 ----------


 ---------- 2011-06-24 15:00:00 : 후평1동   2884 ----------


 ---------- 2011-06-24 22:00:00 : 동내면   2885 ----------


 ---------- 2011-06-25 01:00:00 : 강남동   2886 ----------


 ---------- 2011-06-26 00:00:00 : 석사동   2887 ----------


 ---------- 2011-06-26 05:00:00 : 석사동   2888 ----------


 ---------- 2011-06-26 06:00:00 : 약사명동   2889 ----------


 ---------- 2011-06-26 18:00:00 : 동내면   2890 ----------


 ---------- 2011-06-27 04:00:00 : 효자1동   2891 ----------


 ---------- 2011-06-27 06:00:00 : 남산면   2892 ----------


 ---------- 2011-06-27 10:00:00 : 효자1동   2893 ----------


 ---------- 2011-06-27 11:00:00 : 퇴계동   2894 ----------


 ---------- 2011-06-27 13:00:00 : 서  면   2895 ----------


 ---------- 2011-06-27 14:00:00 : 동  면   2896 ----------


 ---------- 2011-06-27 16:00:00 : 효자1동   2897 ----------


 ---------- 2011-06-27 22:00:00 : 신사우동   2898 ----------


 ---------- 2011-06-28 08:00:00 : 남산면   2899 ----------


 ---------- 2011-06-28 11:00:00 : 신동면   2901 ----------


 ---------- 2011-06-28 14:00:00 : 남산면   2902 ----------


 ---------- 2011-06-28 15:00:00 : 강남동   2903 ----------


 ---------- 2011-06-28 16:00:00 : 남산면   2904 ----------


 ---------- 2011-06-28 16:00:00 : 후평1동   2905 ----------


 ---------- 2011-06-28 18:00:00 : 소양동   2906 ----------


 ---------- 2011-06-29 06:00:00 : 남  면   2907 ----------


 ---------- 2011-06-29 06:00:00 : 근화동   2908 ----------


 ---------- 2011-06-29 11:00:00 : 동  면   2910 ----------


 ---------- 2011-06-29 12:00:00 : 약사명동   2911 ----------


 ---------- 2011-06-29 13:00:00 : 퇴계동   2912 ----------


 ---------- 2011-06-29 14:00:00 : 동산면   2913 ----------


 ---------- 2011-06-29 15:00:00 : 후평1동   2914 ----------


 ---------- 2011-06-29 16:00:00 : 동내면   2915 ----------


 ---------- 2011-06-29 17:00:00 : 동  면   2916 ----------


 ---------- 2011-06-29 18:00:00 : 남  면   2917 ----------


 ---------- 2011-06-29 19:00:00 : 후평1동   2918 ----------


 ---------- 2011-06-29 21:00:00 : 동산면   2920 ----------


 ---------- 2011-06-30 16:00:00 : 석사동   2921 ----------


 ---------- 2011-06-30 19:00:00 : 효자1동   2922 ----------


 ---------- 2011-06-30 19:00:00 : 약사명동   2923 ----------


 ---------- 2011-07-01 09:00:00 : 석사동   2924 ----------


 ---------- 2011-07-01 21:00:00 : 퇴계동   2925 ----------


 ---------- 2011-07-02 07:00:00 : 강남동   2926 ----------


 ---------- 2011-07-02 08:00:00 : 서  면   2927 ----------


 ---------- 2011-07-02 09:00:00 : 석사동   2928 ----------


 ---------- 2011-07-02 10:00:00 : 근화동   2929 ----------


 ---------- 2011-07-02 11:00:00 : 남산면   2930 ----------


 ---------- 2011-07-02 14:00:00 : 서  면   2932 ----------


 ---------- 2011-07-02 15:00:00 : 서  면   2933 ----------


 ---------- 2011-07-02 16:00:00 : 서  면   2934 ----------


 ---------- 2011-07-02 16:00:00 : 퇴계동   2935 ----------


 ---------- 2011-07-02 18:00:00 : 효자1동   2936 ----------


 ---------- 2011-07-02 19:00:00 : 강남동   2937 ----------


 ---------- 2011-07-02 19:00:00 : 동  면   2938 ----------


 ---------- 2011-07-02 20:00:00 : 교  동   2939 ----------


 ---------- 2011-07-02 21:00:00 : 조운동   2940 ----------


 ---------- 2011-07-03 03:00:00 : 석사동   2941 ----------


 ---------- 2011-07-03 06:00:00 : 석사동   2942 ----------


 ---------- 2011-07-03 12:00:00 : 효자1동   2943 ----------


 ---------- 2011-07-03 15:00:00 : 서  면   2945 ----------


 ---------- 2011-07-03 15:00:00 : 남산면   2946 ----------


 ---------- 2011-07-03 16:00:00 : 효자1동   2947 ----------


 ---------- 2011-07-03 21:00:00 : 동내면   2948 ----------


 ---------- 2011-07-04 13:00:00 : 퇴계동   2949 ----------


 ---------- 2011-07-04 16:00:00 : 후평1동   2951 ----------


 ---------- 2011-07-04 19:00:00 : 동  면   2952 ----------


 ---------- 2011-07-05 11:00:00 : 석사동   2953 ----------


 ---------- 2011-07-05 12:00:00 : 후평1동   2954 ----------


 ---------- 2011-07-05 16:00:00 : 신북읍   2955 ----------


 ---------- 2011-07-05 19:00:00 : 강남동   2956 ----------


 ---------- 2011-07-05 19:00:00 : 소양동   2957 ----------


 ---------- 2011-07-05 22:00:00 : 석사동   2958 ----------


 ---------- 2011-07-06 00:00:00 : 후평1동   2959 ----------


 ---------- 2011-07-06 08:00:00 : 동  면   2960 ----------


 ---------- 2011-07-06 13:00:00 : 퇴계동   2961 ----------


 ---------- 2011-07-06 14:00:00 : 사북면   2962 ----------


 ---------- 2011-07-06 14:00:00 : 효자1동   2963 ----------


 ---------- 2011-07-06 15:00:00 : 근화동   2964 ----------


 ---------- 2011-07-06 17:00:00 : 조운동   2965 ----------


 ---------- 2011-07-06 22:00:00 : 신사우동   2966 ----------


 ---------- 2011-07-07 11:00:00 : 퇴계동   2967 ----------


 ---------- 2011-07-07 17:00:00 : 사북면   2968 ----------


 ---------- 2011-07-07 20:00:00 : 강남동   2969 ----------


 ---------- 2011-07-08 02:00:00 : 효자1동   2971 ----------


 ---------- 2011-07-08 09:00:00 : 남산면   2973 ----------


 ---------- 2011-07-08 13:00:00 : 동  면   2974 ----------


 ---------- 2011-07-08 16:00:00 : 남  면   2977 ----------


 ---------- 2011-07-08 16:00:00 : 동내면   2978 ----------


 ---------- 2011-07-08 20:00:00 : 효자1동   2979 ----------


 ---------- 2011-07-09 00:00:00 : 석사동   2980 ----------

 ---------- 2011-07-09 01:00:00 : 소양동   2981 ----------


 ---------- 2011-07-09 06:00:00 : 동산면   2983 ----------


 ---------- 2011-07-09 12:00:00 : 신사우동   2984 ----------


 ---------- 2011-07-09 17:00:00 : 남산면   2985 ----------


 ---------- 2011-07-09 22:00:00 : 강남동   2986 ----------


 ---------- 2011-07-09 23:00:00 : 강남동   2987 ----------


 ---------- 2011-07-10 02:00:00 : 동산면   2988 ----------


 ---------- 2011-07-10 03:00:00 : 효자1동   2989 ----------


 ---------- 2011-07-10 10:00:00 : 신북읍   2990 ----------


 ---------- 2011-07-10 12:00:00 : 남산면   2992 ----------


 ---------- 2011-07-10 13:00:00 : 남산면   2993 ----------


 ---------- 2011-07-10 16:00:00 : 서  면   2994 ----------


 ---------- 2011-07-10 17:00:00 : 효자1동   2995 ----------


 ---------- 2011-07-10 18:00:00 : 효자1동   2996 ----------


 ---------- 2011-07-11 03:00:00 : 후평1동   2997 ----------


 ---------- 2011-07-11 10:00:00 : 신동면   2998 ----------


 ---------- 2011-07-11 11:00:00 : 효자1동   2999 ----------


 ---------- 2011-07-11 15:00:00 : 남산면   3000 ----------


 ---------- 2011-07-11 16:00:00 : 효자1동   3001 ----------


 ---------- 2011-07-11 16:00:00 : 남산면   3002 ----------


 ---------- 2011-07-11 19:00:00 : 동  면   3003 ----------


 ---------- 2011-07-11 20:00:00 : 후평1동   3004 ----------


 ---------- 2011-07-11 22:00:00 : 신북읍   3005 ----------


 ---------- 2011-07-12 00:00:00 : 후평1동   3006 ----------


 ---------- 2011-07-12 07:00:00 : 약사명동   3007 ----------


 ---------- 2011-07-12 11:00:00 : 후평1동   3008 ----------


 ---------- 2011-07-12 17:00:00 : 근화동   3009 ----------


 ---------- 2011-07-12 19:00:00 : 동내면   3010 ----------


 ---------- 2011-07-13 10:00:00 : 근화동   3011 ----------


 ---------- 2011-07-13 12:00:00 : 남산면   3012 ----------


 ---------- 2011-07-13 15:00:00 : 사북면   3014 ----------


 ---------- 2011-07-13 17:00:00 : 남  면   3016 ----------


 ---------- 2011-07-13 19:00:00 : 효자1동   3017 ----------


 ---------- 2011-07-13 21:00:00 : 신사우동   3018 ----------


 ---------- 2011-07-14 14:00:00 : 후평1동   3019 ----------


 ---------- 2011-07-14 21:00:00 : 교  동   3020 ----------


 ---------- 2011-07-15 01:00:00 : 소양동   3021 ----------


 ---------- 2011-07-15 09:00:00 : 강남동   3022 ----------


 ---------- 2011-07-15 10:00:00 : 퇴계동   3023 ----------


 ---------- 2011-07-15 13:00:00 : 동산면   3025 ----------


 ---------- 2011-07-15 17:00:00 : 석사동   3026 ----------


 ---------- 2011-07-15 18:00:00 : 동내면   3027 ----------


 ---------- 2011-07-15 22:00:00 : 신사우동   3028 ----------


 ---------- 2011-07-15 22:00:00 : 소양동   3029 ----------


 ---------- 2011-07-16 09:00:00 : 신사우동   3031 ----------


 ---------- 2011-07-16 10:00:00 : 퇴계동   3032 ----------


 ---------- 2011-07-16 11:00:00 : 남  면   3033 ----------


 ---------- 2011-07-16 16:00:00 : 효자1동   3034 ----------


 ---------- 2011-07-16 18:00:00 : 사북면   3035 ----------


 ---------- 2011-07-17 04:00:00 : 퇴계동   3036 ----------


 ---------- 2011-07-17 06:00:00 : 사북면   3037 ----------


 ---------- 2011-07-17 10:00:00 : 동내면   3038 ----------


 ---------- 2011-07-17 12:00:00 : 석사동   3039 ----------


 ---------- 2011-07-17 12:00:00 : 약사명동   3040 ----------


 ---------- 2011-07-17 13:00:00 : 효자1동   3041 ----------


 ---------- 2011-07-17 13:00:00 : 남산면   3042 ----------


 ---------- 2011-07-17 15:00:00 : 소양동   3043 ----------


 ---------- 2011-07-17 15:00:00 : 북산면   3044 ----------


 ---------- 2011-07-17 19:00:00 : 후평1동   3045 ----------


 ---------- 2011-07-18 02:00:00 : 신북읍   3046 ----------


 ---------- 2011-07-18 09:00:00 : 강남동   3047 ----------


 ---------- 2011-07-18 14:00:00 : 남  면   3049 ----------


 ---------- 2011-07-18 20:00:00 : 효자1동   3050 ----------


 ---------- 2011-07-19 12:00:00 : 동  면   3051 ----------


 ---------- 2011-07-19 15:00:00 : 북산면   3052 ----------


 ---------- 2011-07-19 16:00:00 : 효자1동   3053 ----------


 ---------- 2011-07-20 00:00:00 : 약사명동   3054 ----------


 ---------- 2011-07-20 08:00:00 : 남산면   3055 ----------


 ---------- 2011-07-20 09:00:00 : 북산면   3056 ----------


 ---------- 2011-07-20 15:00:00 : 남산면   3057 ----------


 ---------- 2011-07-21 01:00:00 : 강남동   3058 ----------


 ---------- 2011-07-21 07:00:00 : 강남동   3059 ----------


 ---------- 2011-07-21 09:00:00 : 동내면   3060 ----------


 ---------- 2011-07-21 11:00:00 : 후평1동   3061 ----------


 ---------- 2011-07-22 00:00:00 : 후평1동   3062 ----------


 ---------- 2011-07-22 02:00:00 : 남산면   3063 ----------


 ---------- 2011-07-22 03:00:00 : 강남동   3064 ----------


 ---------- 2011-07-22 03:00:00 : 퇴계동   3065 ----------


 ---------- 2011-07-22 09:00:00 : 강남동   3067 ----------


 ---------- 2011-07-22 09:00:00 : 서  면   3068 ----------


 ---------- 2011-07-22 10:00:00 : 효자1동   3069 ----------


 ---------- 2011-07-22 12:00:00 : 동  면   3070 ----------


 ---------- 2011-07-22 14:00:00 : 후평1동   3071 ----------


 ---------- 2011-07-22 16:00:00 : 후평1동   3072 ----------


 ---------- 2011-07-23 03:00:00 : 효자1동   3073 ----------


 ---------- 2011-07-23 08:00:00 : 조운동   3074 ----------


 ---------- 2011-07-23 09:00:00 : 석사동   3075 ----------


 ---------- 2011-07-23 11:00:00 : 신북읍   3076 ----------


 ---------- 2011-07-23 15:00:00 : 북산면   3078 ----------


 ---------- 2011-07-23 16:00:00 : 강남동   3079 ----------


 ---------- 2011-07-23 17:00:00 : 석사동   3080 ----------


 ---------- 2011-07-23 17:00:00 : 강남동   3081 ----------


 ---------- 2011-07-23 17:00:00 : 신북읍   3082 ----------


 ---------- 2011-07-23 17:00:00 : 동  면   3083 ----------


 ---------- 2011-07-23 23:00:00 : 석사동   3084 ----------


 ---------- 2011-07-24 06:00:00 : 신사우동   3085 ----------


 ---------- 2011-07-24 07:00:00 : 북산면   3086 ----------


 ---------- 2011-07-24 08:00:00 : 북산면   3087 ----------


 ---------- 2011-07-24 09:00:00 : 신사우동   3088 ----------


 ---------- 2011-07-24 10:00:00 : 후평1동   3089 ----------


 ---------- 2011-07-24 11:00:00 : 소양동   3090 ----------


 ---------- 2011-07-24 14:00:00 : 서  면   3091 ----------


 ---------- 2011-07-24 15:00:00 : 신동면   3092 ----------


 ---------- 2011-07-24 15:00:00 : 후평1동   3093 ----------


 ---------- 2011-07-24 18:00:00 : 동내면   3095 ----------


 ---------- 2011-07-24 18:00:00 : 신북읍   3097 ----------


 ---------- 2011-07-25 00:00:00 : 석사동   3100 ----------


 ---------- 2011-07-25 01:00:00 : 동  면   3102 ----------


 ---------- 2011-07-25 07:00:00 : 석사동   3103 ----------


 ---------- 2011-07-25 09:00:00 : 신사우동   3104 ----------


 ---------- 2011-07-25 18:00:00 : 석사동   3105 ----------


 ---------- 2011-07-25 21:00:00 : 석사동   3106 ----------


 ---------- 2011-07-26 01:00:00 : 남산면   3107 ----------


 ---------- 2011-07-26 08:00:00 : 근화동   3108 ----------


 ---------- 2011-07-26 09:00:00 : 신사우동   3109 ----------


 ---------- 2011-07-26 10:00:00 : 효자1동   3110 ----------


 ---------- 2011-07-26 10:00:00 : 근화동   3111 ----------


 ---------- 2011-07-26 10:00:00 : 약사명동   3112 ----------


 ---------- 2011-07-26 15:00:00 : 남  면   3113 ----------


 ---------- 2011-07-26 16:00:00 : 동  면   3114 ----------


 ---------- 2011-07-26 16:00:00 : 조운동   3115 ----------


 ---------- 2011-07-26 17:00:00 : 신사우동   3116 ----------


 ---------- 2011-07-26 19:00:00 : 조운동   3117 ----------


 ---------- 2011-07-26 21:00:00 : 강남동   3118 ----------


 ---------- 2011-07-26 23:00:00 : 근화동   3119 ----------


 ---------- 2011-07-27 01:00:00 : 신북읍   3123 ----------


 ---------- 2011-07-27 06:00:00 : 신동면   3124 ----------


 ---------- 2011-07-27 17:00:00 : 퇴계동   3125 ----------


 ---------- 2011-07-27 20:00:00 : 효자1동   3126 ----------


 ---------- 2011-07-27 20:00:00 : 신사우동   3127 ----------


 ---------- 2011-07-27 23:00:00 : 서  면   3129 ----------


 ---------- 2011-07-27 23:00:00 : 남산면   3130 ----------


 ---------- 2011-07-28 01:00:00 : 강남동   3131 ----------


 ---------- 2011-07-28 01:00:00 : 남산면   3134 ----------


 ---------- 2011-07-28 08:00:00 : 북산면   3135 ----------


 ---------- 2011-07-28 10:00:00 : 교  동   3136 ----------


 ---------- 2011-07-28 13:00:00 : 서  면   3137 ----------


 ---------- 2011-07-28 16:00:00 : 남산면   3139 ----------

 ---------- 2011-07-29 09:00:00 : 서  면   3141 ----------


 ---------- 2011-07-29 10:00:00 : 남  면   3142 ----------


 ---------- 2011-07-29 13:00:00 : 강남동   3143 ----------


 ---------- 2011-07-29 13:00:00 : 서  면   3144 ----------


 ---------- 2011-07-29 14:00:00 : 석사동   3145 ----------


 ---------- 2011-07-29 17:00:00 : 퇴계동   3146 ----------


 ---------- 2011-07-29 19:00:00 : 후평1동   3147 ----------


 ---------- 2011-07-29 21:00:00 : 퇴계동   3148 ----------


 ---------- 2011-07-29 22:00:00 : 석사동   3149 ----------


 ---------- 2011-07-29 22:00:00 : 신사우동   3150 ----------


 ---------- 2011-07-30 09:00:00 : 퇴계동   3151 ----------


 ---------- 2011-07-30 10:00:00 : 동내면   3152 ----------


 ---------- 2011-07-30 19:00:00 : 남산면   3153 ----------


 ---------- 2011-07-30 20:00:00 : 후평1동   3154 ----------


 ---------- 2011-07-30 22:00:00 : 후평1동   3155 ----------


 ---------- 2011-07-31 00:00:00 : 남산면   3157 ----------


 ---------- 2011-07-31 02:00:00 : 후평1동   3158 ----------


 ---------- 2011-07-31 03:00:00 : 신사우동   3159 ----------


 ---------- 2011-07-31 06:00:00 : 후평1동   3160 ----------


 ---------- 2011-07-31 09:00:00 : 석사동   3161 ----------


 ---------- 2011-07-31 09:00:00 : 동산면   3162 ----------


 ---------- 2011-07-31 12:00:00 : 남산면   3163 ----------


 ---------- 2011-07-31 13:00:00 : 동산면   3165 ----------


 ---------- 2011-07-31 16:00:00 : 신동면   3166 ----------


 ---------- 2011-08-01 10:00:00 : 북산면   3168 ----------


 ---------- 2011-08-01 14:00:00 : 사북면   3170 ----------


 ---------- 2011-08-01 14:00:00 : 신북읍   3171 ----------


 ---------- 2011-08-01 17:00:00 : 사북면   3173 ----------


 ---------- 2011-08-01 21:00:00 : 효자1동   3174 ----------


 ---------- 2011-08-01 21:00:00 : 퇴계동   3175 ----------


 ---------- 2011-08-01 22:00:00 : 석사동   3176 ----------


 ---------- 2011-08-01 23:00:00 : 강남동   3177 ----------


 ---------- 2011-08-01 23:00:00 : 퇴계동   3178 ----------


 ---------- 2011-08-02 00:00:00 : 강남동   3180 ----------


 ---------- 2011-08-02 06:00:00 : 동산면   3181 ----------


 ---------- 2011-08-02 08:00:00 : 동산면   3182 ----------


 ---------- 2011-08-02 09:00:00 : 동산면   3183 ----------


 ---------- 2011-08-02 17:00:00 : 효자1동   3184 ----------


 ---------- 2011-08-02 17:00:00 : 소양동   3185 ----------


 ---------- 2011-08-02 19:00:00 : 동  면   3186 ----------


 ---------- 2011-08-02 22:00:00 : 효자1동   3187 ----------


 ---------- 2011-08-02 23:00:00 : 남산면   3188 ----------


 ---------- 2011-08-03 09:00:00 : 신동면   3189 ----------


 ---------- 2011-08-03 09:00:00 : 신사우동   3191 ----------


 ---------- 2011-08-03 09:00:00 : 소양동   3192 ----------


 ---------- 2011-08-03 13:00:00 : 강남동   3193 ----------


 ---------- 2011-08-03 13:00:00 : 남산면   3194 ----------


 ---------- 2011-08-03 15:00:00 : 남산면   3195 ----------


 ---------- 2011-08-03 15:00:00 : 근화동   3197 ----------


 ---------- 2011-08-03 17:00:00 : 석사동   3198 ----------


 ---------- 2011-08-03 17:00:00 : 효자1동   3199 ----------


 ---------- 2011-08-03 19:00:00 : 사북면   3200 ----------


 ---------- 2011-08-03 20:00:00 : 서  면   3202 ----------


 ---------- 2011-08-03 21:00:00 : 석사동   3203 ----------


 ---------- 2011-08-04 04:00:00 : 조운동   3204 ----------


 ---------- 2011-08-04 09:00:00 : 서  면   3205 ----------


 ---------- 2011-08-04 10:00:00 : 석사동   3206 ----------


 ---------- 2011-08-04 11:00:00 : 신북읍   3208 ----------


 ---------- 2011-08-04 14:00:00 : 효자1동   3209 ----------


 ---------- 2011-08-04 17:00:00 : 강남동   3210 ----------


 ---------- 2011-08-04 19:00:00 : 동  면   3211 ----------


 ---------- 2011-08-04 20:00:00 : 동  면   3212 ----------


 ---------- 2011-08-04 21:00:00 : 후평1동   3214 ----------


 ---------- 2011-08-05 01:00:00 : 효자1동   3215 ----------


 ---------- 2011-08-05 09:00:00 : 석사동   3216 ----------


 ---------- 2011-08-05 09:00:00 : 서  면   3217 ----------


 ---------- 2011-08-05 14:00:00 : 남산면   3218 ----------


 ---------- 2011-08-05 14:00:00 : 퇴계동   3219 ----------


 ---------- 2011-08-05 14:00:00 : 동산면   3220 ----------


 ---------- 2011-08-05 15:00:00 : 신동면   3222 ----------


 ---------- 2011-08-05 16:00:00 : 남산면   3223 ----------


 ---------- 2011-08-05 17:00:00 : 남산면   3225 ----------


 ---------- 2011-08-05 18:00:00 : 퇴계동   3226 ----------


 ---------- 2011-08-05 19:00:00 : 조운동   3227 ----------


 ---------- 2011-08-05 22:00:00 : 조운동   3228 ----------


 ---------- 2011-08-06 09:00:00 : 동  면   3229 ----------


 ---------- 2011-08-06 12:00:00 : 석사동   3230 ----------


 ---------- 2011-08-06 14:00:00 : 동내면   3231 ----------


 ---------- 2011-08-06 14:00:00 : 남산면   3234 ----------


 ---------- 2011-08-06 14:00:00 : 동  면   3235 ----------


 ---------- 2011-08-06 16:00:00 : 사북면   3236 ----------


 ---------- 2011-08-06 16:00:00 : 동내면   3237 ----------


 ---------- 2011-08-06 16:00:00 : 근화동   3238 ----------


 ---------- 2011-08-06 16:00:00 : 신사우동   3240 ----------


 ---------- 2011-08-06 16:00:00 : 동  면   3241 ----------


 ---------- 2011-08-06 17:00:00 : 사북면   3243 ----------


 ---------- 2011-08-06 23:00:00 : 신동면   3246 ----------


 ---------- 2011-08-07 12:00:00 : 남산면   3247 ----------


 ---------- 2011-08-07 12:00:00 : 신북읍   3248 ----------


 ---------- 2011-08-07 13:00:00 : 강남동   3249 ----------


 ---------- 2011-08-07 14:00:00 : 남  면   3250 ----------


 ---------- 2011-08-07 14:00:00 : 후평1동   3252 ----------


 ---------- 2011-08-07 19:00:00 : 신사우동   3253 ----------


 ---------- 2011-08-07 20:00:00 : 서  면   3254 ----------


 ---------- 2011-08-08 01:00:00 : 석사동   3255 ----------


 ---------- 2011-08-08 06:00:00 : 효자1동   3256 ----------


 ---------- 2011-08-08 09:00:00 : 후평1동   3257 ----------


 ---------- 2011-08-08 12:00:00 : 퇴계동   3258 ----------


 ---------- 2011-08-08 13:00:00 : 석사동   3259 ----------


 ---------- 2011-08-08 13:00:00 : 교  동   3260 ----------


 ---------- 2011-08-08 14:00:00 : 퇴계동   3261 ----------


 ---------- 2011-08-08 15:00:00 : 신동면   3262 ----------


 ---------- 2011-08-08 17:00:00 : 동  면   3263 ----------


 ---------- 2011-08-08 18:00:00 : 신사우동   3264 ----------


 ---------- 2011-08-09 00:00:00 : 동  면   3265 ----------


 ---------- 2011-08-09 02:00:00 : 남산면   3266 ----------


 ---------- 2011-08-09 04:00:00 : 근화동   3267 ----------


 ---------- 2011-08-09 08:00:00 : 북산면   3269 ----------


 ---------- 2011-08-09 10:00:00 : 동내면   3270 ----------


 ---------- 2011-08-09 12:00:00 : 효자1동   3271 ----------


 ---------- 2011-08-09 13:00:00 : 강남동   3272 ----------


 ---------- 2011-08-09 15:00:00 : 강남동   3273 ----------


 ---------- 2011-08-09 16:00:00 : 동  면   3274 ----------


 ---------- 2011-08-09 17:00:00 : 효자1동   3275 ----------


 ---------- 2011-08-09 20:00:00 : 신사우동   3276 ----------


 ---------- 2011-08-09 20:00:00 : 퇴계동   3277 ----------


 ---------- 2011-08-10 10:00:00 : 동  면   3279 ----------


 ---------- 2011-08-10 12:00:00 : 동  면   3280 ----------


 ---------- 2011-08-10 13:00:00 : 석사동   3281 ----------


 ---------- 2011-08-10 14:00:00 : 사북면   3283 ----------


 ---------- 2011-08-10 14:00:00 : 근화동   3284 ----------


 ---------- 2011-08-10 15:00:00 : 사북면   3285 ----------


 ---------- 2011-08-10 15:00:00 : 남산면   3286 ----------


 ---------- 2011-08-10 17:00:00 : 동내면   3287 ----------


 ---------- 2011-08-10 17:00:00 : 근화동   3289 ----------


 ---------- 2011-08-11 07:00:00 : 후평1동   3290 ----------


 ---------- 2011-08-11 09:00:00 : 남산면   3291 ----------


 ---------- 2011-08-11 10:00:00 : 후평1동   3292 ----------


 ---------- 2011-08-11 13:00:00 : 강남동   3293 ----------


 ---------- 2011-08-11 15:00:00 : 석사동   3295 ----------


 ---------- 2011-08-11 15:00:00 : 동  면   3296 ----------


 ---------- 2011-08-11 16:00:00 : 효자1동   3297 ----------


 ---------- 2011-08-11 16:00:00 : 신사우동   3298 ----------


 ---------- 2011-08-11 18:00:00 : 근화동   3301 ----------


 ---------- 2011-08-11 19:00:00 : 석사동   3303 ----------


 ---------- 2011-08-11 23:00:00 : 서  면   3305 ----------


 ---------- 2011-08-12 09:00:00 : 석사동   3306 ----------


 ---------- 2011-08-12 11:00:00 : 신사우동   3307 ----------

 ---------- 2011-08-12 13:00:00 : 효자1동   3308 ----------


 ---------- 2011-08-12 15:00:00 : 교  동   3309 ----------


 ---------- 2011-08-12 16:00:00 : 신동면   3310 ----------


 ---------- 2011-08-13 01:00:00 : 석사동   3312 ----------


 ---------- 2011-08-13 05:00:00 : 석사동   3314 ----------


 ---------- 2011-08-13 11:00:00 : 후평1동   3317 ----------


 ---------- 2011-08-13 14:00:00 : 사북면   3318 ----------


 ---------- 2011-08-13 16:00:00 : 북산면   3319 ----------


 ---------- 2011-08-13 18:00:00 : 동  면   3320 ----------


 ---------- 2011-08-13 23:00:00 : 효자1동   3321 ----------


 ---------- 2011-08-13 23:00:00 : 근화동   3322 ----------


 ---------- 2011-08-14 01:00:00 : 소양동   3323 ----------


 ---------- 2011-08-14 15:00:00 : 남산면   3324 ----------


 ---------- 2011-08-14 15:00:00 : 동산면   3326 ----------


 ---------- 2011-08-14 16:00:00 : 남산면   3327 ----------


 ---------- 2011-08-14 17:00:00 : 동내면   3328 ----------


 ---------- 2011-08-14 18:00:00 : 석사동   3329 ----------


 ---------- 2011-08-14 21:00:00 : 근화동   3331 ----------


 ---------- 2011-08-15 06:00:00 : 북산면   3332 ----------


 ---------- 2011-08-15 08:00:00 : 근화동   3333 ----------


 ---------- 2011-08-15 10:00:00 : 퇴계동   3334 ----------


 ---------- 2011-08-15 14:00:00 : 서  면   3336 ----------


 ---------- 2011-08-15 16:00:00 : 효자1동   3337 ----------


 ---------- 2011-08-15 19:00:00 : 근화동   3339 ----------


 ---------- 2011-08-16 07:00:00 : 동  면   3340 ----------


 ---------- 2011-08-16 07:00:00 : 북산면   3341 ----------


 ---------- 2011-08-16 09:00:00 : 석사동   3342 ----------


 ---------- 2011-08-16 09:00:00 : 남산면   3343 ----------


 ---------- 2011-08-16 09:00:00 : 동  면   3344 ----------


 ---------- 2011-08-16 10:00:00 : 서  면   3345 ----------


 ---------- 2011-08-16 10:00:00 : 효자1동   3347 ----------


 ---------- 2011-08-16 11:00:00 : 퇴계동   3348 ----------


 ---------- 2011-08-16 13:00:00 : 동산면   3349 ----------


 ---------- 2011-08-16 15:00:00 : 서  면   3352 ----------


 ---------- 2011-08-16 15:00:00 : 동  면   3354 ----------


 ---------- 2011-08-16 16:00:00 : 신동면   3355 ----------


 ---------- 2011-08-16 17:00:00 : 후평1동   3356 ----------


 ---------- 2011-08-17 04:00:00 : 서  면   3358 ----------


 ---------- 2011-08-17 11:00:00 : 신사우동   3359 ----------


 ---------- 2011-08-17 11:00:00 : 소양동   3360 ----------


 ---------- 2011-08-17 11:00:00 : 동  면   3361 ----------


 ---------- 2011-08-17 14:00:00 : 사북면   3362 ----------


 ---------- 2011-08-17 19:00:00 : 사북면   3363 ----------


 ---------- 2011-08-17 20:00:00 : 동  면   3365 ----------


 ---------- 2011-08-18 08:00:00 : 효자1동   3366 ----------


 ---------- 2011-08-18 09:00:00 : 서  면   3367 ----------


 ---------- 2011-08-18 09:00:00 : 동내면   3368 ----------


 ---------- 2011-08-18 09:00:00 : 퇴계동   3369 ----------


 ---------- 2011-08-18 10:00:00 : 강남동   3370 ----------


 ---------- 2011-08-18 10:00:00 : 남  면   3371 ----------


 ---------- 2011-08-18 12:00:00 : 후평1동   3372 ----------


 ---------- 2011-08-18 13:00:00 : 동내면   3373 ----------


 ---------- 2011-08-18 13:00:00 : 남산면   3374 ----------


 ---------- 2011-08-18 14:00:00 : 신동면   3375 ----------


 ---------- 2011-08-18 14:00:00 : 남산면   3379 ----------


 ---------- 2011-08-18 15:00:00 : 효자1동   3380 ----------


 ---------- 2011-08-18 16:00:00 : 효자1동   3381 ----------


 ---------- 2011-08-18 23:00:00 : 남산면   3382 ----------


 ---------- 2011-08-19 09:00:00 : 효자1동   3383 ----------


 ---------- 2011-08-19 10:00:00 : 교  동   3384 ----------


 ---------- 2011-08-19 11:00:00 : 서  면   3385 ----------


 ---------- 2011-08-19 12:00:00 : 동내면   3386 ----------


 ---------- 2011-08-19 14:00:00 : 동  면   3387 ----------


 ---------- 2011-08-19 15:00:00 : 효자1동   3388 ----------


 ---------- 2011-08-19 16:00:00 : 후평1동   3389 ----------


 ---------- 2011-08-19 17:00:00 : 석사동   3390 ----------


 ---------- 2011-08-19 19:00:00 : 퇴계동   3391 ----------


 ---------- 2011-08-20 02:00:00 : 소양동   3392 ----------


 ---------- 2011-08-20 08:00:00 : 효자1동   3394 ----------


 ---------- 2011-08-20 09:00:00 : 남  면   3397 ----------


 ---------- 2011-08-20 10:00:00 : 석사동   3398 ----------


 ---------- 2011-08-20 10:00:00 : 사북면   3399 ----------


 ---------- 2011-08-20 11:00:00 : 동내면   3400 ----------


 ---------- 2011-08-20 12:00:00 : 서  면   3401 ----------


 ---------- 2011-08-20 14:00:00 : 동산면   3402 ----------


 ---------- 2011-08-20 15:00:00 : 신동면   3403 ----------


 ---------- 2011-08-20 15:00:00 : 남산면   3404 ----------


 ---------- 2011-08-21 08:00:00 : 강남동   3405 ----------


 ---------- 2011-08-21 09:00:00 : 동  면   3407 ----------


 ---------- 2011-08-21 10:00:00 : 신사우동   3408 ----------


 ---------- 2011-08-21 11:00:00 : 후평1동   3409 ----------


 ---------- 2011-08-21 13:00:00 : 신북읍   3410 ----------


 ---------- 2011-08-21 14:00:00 : 신사우동   3411 ----------


 ---------- 2011-08-21 16:00:00 : 석사동   3412 ----------


 ---------- 2011-08-21 16:00:00 : 남산면   3413 ----------


 ---------- 2011-08-21 17:00:00 : 남산면   3415 ----------


 ---------- 2011-08-22 05:00:00 : 서  면   3416 ----------


 ---------- 2011-08-22 05:00:00 : 남산면   3417 ----------


 ---------- 2011-08-22 08:00:00 : 동내면   3418 ----------


 ---------- 2011-08-22 08:00:00 : 효자1동   3419 ----------


 ---------- 2011-08-22 09:00:00 : 남산면   3421 ----------


 ---------- 2011-08-22 10:00:00 : 남  면   3423 ----------


 ---------- 2011-08-22 10:00:00 : 남산면   3424 ----------


 ---------- 2011-08-22 11:00:00 : 후평1동   3426 ----------


 ---------- 2011-08-22 12:00:00 : 석사동   3427 ----------


 ---------- 2011-08-22 12:00:00 : 남산면   3428 ----------


 ---------- 2011-08-22 12:00:00 : 소양동   3430 ----------


 ---------- 2011-08-22 13:00:00 : 동내면   3431 ----------


 ---------- 2011-08-22 14:00:00 : 남산면   3432 ----------


 ---------- 2011-08-22 14:00:00 : 후평1동   3433 ----------


 ---------- 2011-08-22 15:00:00 : 신사우동   3434 ----------


 ---------- 2011-08-22 16:00:00 : 신사우동   3436 ----------


 ---------- 2011-08-22 17:00:00 : 강남동   3437 ----------


 ---------- 2011-08-22 22:00:00 : 후평1동   3439 ----------


 ---------- 2011-08-23 08:00:00 : 남  면   3440 ----------


 ---------- 2011-08-23 09:00:00 : 석사동   3441 ----------


 ---------- 2011-08-23 09:00:00 : 사북면   3442 ----------


 ---------- 2011-08-23 09:00:00 : 남산면   3443 ----------


 ---------- 2011-08-23 09:00:00 : 동  면   3444 ----------


 ---------- 2011-08-23 09:00:00 : 후평1동   3445 ----------


 ---------- 2011-08-23 10:00:00 : 동내면   3446 ----------


 ---------- 2011-08-23 13:00:00 : 남산면   3447 ----------


 ---------- 2011-08-23 14:00:00 : 동내면   3448 ----------


 ---------- 2011-08-23 14:00:00 : 퇴계동   3449 ----------


 ---------- 2011-08-23 15:00:00 : 서  면   3450 ----------


 ---------- 2011-08-23 17:00:00 : 신사우동   3451 ----------


 ---------- 2011-08-23 17:00:00 : 퇴계동   3452 ----------


 ---------- 2011-08-23 19:00:00 : 퇴계동   3453 ----------


 ---------- 2011-08-23 21:00:00 : 효자1동   3454 ----------


 ---------- 2011-08-24 05:00:00 : 남산면   3455 ----------


 ---------- 2011-08-24 08:00:00 : 남산면   3457 ----------


 ---------- 2011-08-24 09:00:00 : 석사동   3458 ----------


 ---------- 2011-08-24 09:00:00 : 강남동   3459 ----------


 ---------- 2011-08-24 09:00:00 : 후평1동   3460 ----------


 ---------- 2011-08-24 10:00:00 : 강남동   3462 ----------


 ---------- 2011-08-24 10:00:00 : 서  면   3463 ----------


 ---------- 2011-08-24 10:00:00 : 남산면   3464 ----------


 ---------- 2011-08-24 10:00:00 : 동산면   3465 ----------


 ---------- 2011-08-24 12:00:00 : 효자1동   3467 ----------


 ---------- 2011-08-24 12:00:00 : 남산면   3468 ----------


 ---------- 2011-08-24 12:00:00 : 신사우동   3469 ----------


 ---------- 2011-08-24 13:00:00 : 신사우동   3470 ----------


 ---------- 2011-08-24 13:00:00 : 퇴계동   3471 ----------


 ---------- 2011-08-24 14:00:00 : 신북읍   3472 ----------


 ---------- 2011-08-24 18:00:00 : 효자1동   3473 ----------


 ---------- 2011-08-24 19:00:00 : 퇴계동   3474 ----------


 ---------- 2011-08-25 00:00:00 : 석사동   3475 ----------


 ---------- 2011-08-25 05:00:00 : 강남동   3477 ----------

 ---------- 2011-08-25 09:00:00 : 신사우동   3478 ----------


 ---------- 2011-08-25 09:00:00 : 조운동   3479 ----------


 ---------- 2011-08-25 10:00:00 : 석사동   3480 ----------


 ---------- 2011-08-25 10:00:00 : 남산면   3481 ----------


 ---------- 2011-08-25 11:00:00 : 석사동   3482 ----------


 ---------- 2011-08-25 11:00:00 : 사북면   3483 ----------


 ---------- 2011-08-25 11:00:00 : 퇴계동   3484 ----------


 ---------- 2011-08-25 12:00:00 : 효자1동   3485 ----------


 ---------- 2011-08-25 12:00:00 : 동  면   3486 ----------


 ---------- 2011-08-25 13:00:00 : 동  면   3487 ----------


 ---------- 2011-08-25 13:00:00 : 퇴계동   3488 ----------


 ---------- 2011-08-25 14:00:00 : 서  면   3489 ----------


 ---------- 2011-08-25 15:00:00 : 동산면   3490 ----------


 ---------- 2011-08-25 16:00:00 : 강남동   3491 ----------


 ---------- 2011-08-25 16:00:00 : 후평1동   3492 ----------


 ---------- 2011-08-25 17:00:00 : 퇴계동   3493 ----------


 ---------- 2011-08-25 22:00:00 : 남  면   3494 ----------


 ---------- 2011-08-26 08:00:00 : 후평1동   3495 ----------


 ---------- 2011-08-26 09:00:00 : 신사우동   3496 ----------


 ---------- 2011-08-26 10:00:00 : 강남동   3497 ----------


 ---------- 2011-08-26 10:00:00 : 신사우동   3498 ----------


 ---------- 2011-08-26 10:00:00 : 신북읍   3499 ----------


 ---------- 2011-08-26 11:00:00 : 조운동   3500 ----------


 ---------- 2011-08-26 13:00:00 : 신사우동   3501 ----------


 ---------- 2011-08-26 14:00:00 : 석사동   3502 ----------


 ---------- 2011-08-26 14:00:00 : 근화동   3503 ----------


 ---------- 2011-08-26 14:00:00 : 동  면   3504 ----------


 ---------- 2011-08-26 14:00:00 : 퇴계동   3505 ----------


 ---------- 2011-08-26 15:00:00 : 동내면   3506 ----------


 ---------- 2011-08-26 15:00:00 : 신사우동   3507 ----------


 ---------- 2011-08-26 16:00:00 : 동내면   3508 ----------


 ---------- 2011-08-26 16:00:00 : 신북읍   3509 ----------


 ---------- 2011-08-26 17:00:00 : 후평1동   3510 ----------


 ---------- 2011-08-26 20:00:00 : 강남동   3511 ----------


 ---------- 2011-08-27 00:00:00 : 조운동   3512 ----------


 ---------- 2011-08-27 01:00:00 : 퇴계동   3514 ----------


 ---------- 2011-08-27 09:00:00 : 서  면   3516 ----------


 ---------- 2011-08-27 09:00:00 : 퇴계동   3517 ----------


 ---------- 2011-08-27 12:00:00 : 석사동   3518 ----------


 ---------- 2011-08-27 13:00:00 : 퇴계동   3519 ----------


 ---------- 2011-08-27 14:00:00 : 강남동   3520 ----------


 ---------- 2011-08-27 16:00:00 : 석사동   3521 ----------


 ---------- 2011-08-27 16:00:00 : 남산면   3523 ----------


 ---------- 2011-08-27 17:00:00 : 퇴계동   3524 ----------


 ---------- 2011-08-28 02:00:00 : 효자1동   3525 ----------


 ---------- 2011-08-28 08:00:00 : 신동면   3526 ----------


 ---------- 2011-08-28 11:00:00 : 강남동   3527 ----------


 ---------- 2011-08-28 15:00:00 : 퇴계동   3528 ----------


 ---------- 2011-08-28 19:00:00 : 퇴계동   3529 ----------


 ---------- 2011-08-29 07:00:00 : 남산면   3530 ----------


 ---------- 2011-08-29 09:00:00 : 석사동   3531 ----------


 ---------- 2011-08-29 10:00:00 : 근화동   3532 ----------


 ---------- 2011-08-29 11:00:00 : 근화동   3533 ----------


 ---------- 2011-08-29 12:00:00 : 강남동   3534 ----------


 ---------- 2011-08-29 12:00:00 : 후평1동   3535 ----------


 ---------- 2011-08-29 13:00:00 : 남산면   3536 ----------


 ---------- 2011-08-29 15:00:00 : 신동면   3537 ----------


 ---------- 2011-08-29 15:00:00 : 후평1동   3538 ----------


 ---------- 2011-08-29 20:00:00 : 후평1동   3540 ----------


 ---------- 2011-08-30 09:00:00 : 강남동   3541 ----------


 ---------- 2011-08-30 12:00:00 : 효자1동   3542 ----------


 ---------- 2011-08-30 13:00:00 : 석사동   3543 ----------


 ---------- 2011-08-31 00:00:00 : 후평1동   3544 ----------


 ---------- 2011-08-31 07:00:00 : 신북읍   3545 ----------


 ---------- 2011-08-31 09:00:00 : 석사동   3547 ----------


 ---------- 2011-08-31 09:00:00 : 효자1동   3548 ----------


 ---------- 2011-08-31 09:00:00 : 근화동   3549 ----------


 ---------- 2011-08-31 10:00:00 : 석사동   3550 ----------


 ---------- 2011-08-31 13:00:00 : 동내면   3551 ----------


 ---------- 2011-08-31 13:00:00 : 신사우동   3552 ----------


 ---------- 2011-08-31 14:00:00 : 석사동   3553 ----------


 ---------- 2011-08-31 15:00:00 : 후평1동   3554 ----------


 ---------- 2011-08-31 16:00:00 : 남산면   3555 ----------


 ---------- 2011-08-31 16:00:00 : 동  면   3556 ----------


 ---------- 2011-08-31 17:00:00 : 남산면   3557 ----------


 ---------- 2011-08-31 17:00:00 : 후평1동   3558 ----------


 ---------- 2011-08-31 19:00:00 : 강남동   3559 ----------


 ---------- 2011-08-31 20:00:00 : 퇴계동   3560 ----------


 ---------- 2011-09-01 00:00:00 : 후평1동   3561 ----------


 ---------- 2011-09-01 02:00:00 : 동산면   3562 ----------


 ---------- 2011-09-01 08:00:00 : 소양동   3563 ----------


 ---------- 2011-09-01 09:00:00 : 석사동   3564 ----------


 ---------- 2011-09-01 09:00:00 : 남산면   3567 ----------


 ---------- 2011-09-01 09:00:00 : 신북읍   3568 ----------


 ---------- 2011-09-01 09:00:00 : 퇴계동   3569 ----------


 ---------- 2011-09-01 10:00:00 : 남산면   3570 ----------


 ---------- 2011-09-01 11:00:00 : 석사동   3571 ----------


 ---------- 2011-09-01 12:00:00 : 사북면   3572 ----------


 ---------- 2011-09-01 13:00:00 : 서  면   3573 ----------


 ---------- 2011-09-01 13:00:00 : 사북면   3575 ----------


 ---------- 2011-09-01 13:00:00 : 남산면   3576 ----------


 ---------- 2011-09-01 14:00:00 : 신사우동   3577 ----------


 ---------- 2011-09-01 14:00:00 : 동  면   3578 ----------


 ---------- 2011-09-01 15:00:00 : 사북면   3580 ----------


 ---------- 2011-09-01 15:00:00 : 후평1동   3581 ----------


 ---------- 2011-09-01 16:00:00 : 신북읍   3583 ----------


 ---------- 2011-09-01 19:00:00 : 서  면   3584 ----------


 ---------- 2011-09-01 21:00:00 : 서  면   3585 ----------


 ---------- 2011-09-02 00:00:00 : 강남동   3587 ----------


 ---------- 2011-09-02 01:00:00 : 동  면   3590 ----------


 ---------- 2011-09-02 08:00:00 : 남산면   3591 ----------


 ---------- 2011-09-02 09:00:00 : 강남동   3592 ----------


 ---------- 2011-09-02 09:00:00 : 후평1동   3593 ----------


 ---------- 2011-09-02 10:00:00 : 석사동   3594 ----------


 ---------- 2011-09-02 11:00:00 : 후평1동   3595 ----------


 ---------- 2011-09-02 12:00:00 : 동내면   3596 ----------


 ---------- 2011-09-02 13:00:00 : 석사동   3597 ----------


 ---------- 2011-09-02 13:00:00 : 신동면   3598 ----------


 ---------- 2011-09-02 13:00:00 : 남산면   3599 ----------


 ---------- 2011-09-02 15:00:00 : 북산면   3601 ----------


 ---------- 2011-09-02 20:00:00 : 후평1동   3602 ----------


 ---------- 2011-09-03 06:00:00 : 근화동   3603 ----------


 ---------- 2011-09-03 09:00:00 : 북산면   3605 ----------


 ---------- 2011-09-03 13:00:00 : 남산면   3606 ----------


 ---------- 2011-09-04 09:00:00 : 북산면   3608 ----------


 ---------- 2011-09-04 10:00:00 : 후평1동   3609 ----------


 ---------- 2011-09-04 13:00:00 : 동  면   3610 ----------


 ---------- 2011-09-04 13:00:00 : 후평1동   3611 ----------


 ---------- 2011-09-04 14:00:00 : 남산면   3613 ----------


 ---------- 2011-09-04 19:00:00 : 동내면   3614 ----------


 ---------- 2011-09-04 19:00:00 : 조운동   3616 ----------


 ---------- 2011-09-05 01:00:00 : 동  면   3617 ----------


 ---------- 2011-09-05 08:00:00 : 동내면   3619 ----------


 ---------- 2011-09-05 09:00:00 : 서  면   3620 ----------


 ---------- 2011-09-05 09:00:00 : 동내면   3621 ----------


 ---------- 2011-09-05 09:00:00 : 북산면   3622 ----------


 ---------- 2011-09-05 10:00:00 : 소양동   3623 ----------


 ---------- 2011-09-05 12:00:00 : 신사우동   3624 ----------


 ---------- 2011-09-05 13:00:00 : 석사동   3626 ----------


 ---------- 2011-09-05 13:00:00 : 후평1동   3627 ----------


 ---------- 2011-09-05 13:00:00 : 퇴계동   3628 ----------


 ---------- 2011-09-05 14:00:00 : 효자1동   3629 ----------


 ---------- 2011-09-05 14:00:00 : 근화동   3630 ----------


 ---------- 2011-09-05 14:00:00 : 후평1동   3632 ----------


 ---------- 2011-09-05 15:00:00 : 동내면   3633 ----------


 ---------- 2011-09-05 15:00:00 : 동  면   3634 ----------


 ---------- 2011-09-05 17:00:00 : 사북면   3636 ----------


 ---------- 2011-09-05 18:00:00 : 효자1동   3637 ----------


 ---------- 2011-09-06 01:00:00 : 효자1동   3638 ----------


 ---------- 2011-09-06 01:00:00 : 근화동   3639 ----------

 ---------- 2011-09-06 03:00:00 : 효자1동   3641 ----------


 ---------- 2011-09-06 06:00:00 : 소양동   3642 ----------


 ---------- 2011-09-06 09:00:00 : 서  면   3643 ----------


 ---------- 2011-09-06 10:00:00 : 소양동   3644 ----------


 ---------- 2011-09-06 10:00:00 : 동  면   3645 ----------


 ---------- 2011-09-06 11:00:00 : 동내면   3646 ----------


 ---------- 2011-09-06 12:00:00 : 석사동   3647 ----------


 ---------- 2011-09-06 13:00:00 : 효자1동   3649 ----------


 ---------- 2011-09-06 16:00:00 : 신동면   3650 ----------


 ---------- 2011-09-06 17:00:00 : 신동면   3651 ----------


 ---------- 2011-09-07 06:00:00 : 서  면   3652 ----------


 ---------- 2011-09-07 06:00:00 : 동내면   3653 ----------


 ---------- 2011-09-07 10:00:00 : 신북읍   3654 ----------


 ---------- 2011-09-07 11:00:00 : 신북읍   3655 ----------


 ---------- 2011-09-07 13:00:00 : 후평1동   3656 ----------


 ---------- 2011-09-07 14:00:00 : 퇴계동   3658 ----------


 ---------- 2011-09-07 15:00:00 : 동내면   3659 ----------


 ---------- 2011-09-07 23:00:00 : 사북면   3661 ----------


 ---------- 2011-09-08 09:00:00 : 동내면   3662 ----------


 ---------- 2011-09-08 09:00:00 : 북산면   3663 ----------


 ---------- 2011-09-08 11:00:00 : 북산면   3664 ----------


 ---------- 2011-09-08 14:00:00 : 동내면   3665 ----------


 ---------- 2011-09-08 16:00:00 : 동  면   3667 ----------


 ---------- 2011-09-08 20:00:00 : 석사동   3668 ----------


 ---------- 2011-09-09 09:00:00 : 신동면   3669 ----------


 ---------- 2011-09-09 09:00:00 : 동내면   3670 ----------


 ---------- 2011-09-09 09:00:00 : 북산면   3671 ----------


 ---------- 2011-09-09 15:00:00 : 강남동   3672 ----------


 ---------- 2011-09-10 08:00:00 : 북산면   3673 ----------


 ---------- 2011-09-10 09:00:00 : 북산면   3674 ----------


 ---------- 2011-09-10 12:00:00 : 신사우동   3675 ----------


 ---------- 2011-09-10 18:00:00 : 후평1동   3676 ----------


 ---------- 2011-09-11 03:00:00 : 강남동   3678 ----------


 ---------- 2011-09-11 09:00:00 : 북산면   3679 ----------


 ---------- 2011-09-11 11:00:00 : 소양동   3680 ----------


 ---------- 2011-09-11 12:00:00 : 효자1동   3681 ----------


 ---------- 2011-09-11 12:00:00 : 약사명동   3683 ----------


 ---------- 2011-09-11 17:00:00 : 신북읍   3684 ----------


 ---------- 2011-09-11 21:00:00 : 효자1동   3685 ----------


 ---------- 2011-09-12 00:00:00 : 서  면   3687 ----------


 ---------- 2011-09-12 10:00:00 : 서  면   3688 ----------


 ---------- 2011-09-12 10:00:00 : 북산면   3689 ----------


 ---------- 2011-09-12 11:00:00 : 효자1동   3690 ----------


 ---------- 2011-09-12 13:00:00 : 강남동   3691 ----------


 ---------- 2011-09-12 14:00:00 : 신동면   3692 ----------


 ---------- 2011-09-12 14:00:00 : 신사우동   3693 ----------


 ---------- 2011-09-12 14:00:00 : 북산면   3694 ----------


 ---------- 2011-09-12 16:00:00 : 동  면   3695 ----------


 ---------- 2011-09-12 17:00:00 : 효자1동   3696 ----------


 ---------- 2011-09-12 21:00:00 : 석사동   3698 ----------


 ---------- 2011-09-13 09:00:00 : 동내면   3699 ----------


 ---------- 2011-09-13 09:00:00 : 북산면   3700 ----------


 ---------- 2011-09-13 10:00:00 : 북산면   3701 ----------


 ---------- 2011-09-13 12:00:00 : 석사동   3702 ----------


 ---------- 2011-09-13 14:00:00 : 근화동   3703 ----------


 ---------- 2011-09-13 14:00:00 : 북산면   3704 ----------


 ---------- 2011-09-13 19:00:00 : 사북면   3705 ----------


 ---------- 2011-09-13 21:00:00 : 후평1동   3706 ----------


 ---------- 2011-09-14 00:00:00 : 강남동   3708 ----------


 ---------- 2011-09-14 00:00:00 : 근화동   3710 ----------


 ---------- 2011-09-14 01:00:00 : 효자1동   3712 ----------


 ---------- 2011-09-14 09:00:00 : 신동면   3713 ----------


 ---------- 2011-09-14 10:00:00 : 서  면   3714 ----------


 ---------- 2011-09-14 10:00:00 : 신북읍   3715 ----------


 ---------- 2011-09-14 10:00:00 : 북산면   3716 ----------


 ---------- 2011-09-14 11:00:00 : 동내면   3717 ----------


 ---------- 2011-09-14 12:00:00 : 사북면   3718 ----------


 ---------- 2011-09-14 12:00:00 : 신북읍   3719 ----------


 ---------- 2011-09-14 13:00:00 : 석사동   3720 ----------


 ---------- 2011-09-14 13:00:00 : 강남동   3721 ----------


 ---------- 2011-09-14 13:00:00 : 동  면   3722 ----------


 ---------- 2011-09-14 14:00:00 : 석사동   3723 ----------


 ---------- 2011-09-14 14:00:00 : 신사우동   3724 ----------


 ---------- 2011-09-14 15:00:00 : 석사동   3725 ----------


 ---------- 2011-09-14 15:00:00 : 조운동   3726 ----------


 ---------- 2011-09-14 16:00:00 : 동내면   3727 ----------


 ---------- 2011-09-14 17:00:00 : 석사동   3728 ----------


 ---------- 2011-09-14 17:00:00 : 남산면   3729 ----------


 ---------- 2011-09-14 23:00:00 : 근화동   3730 ----------


 ---------- 2011-09-15 07:00:00 : 사북면   3732 ----------


 ---------- 2011-09-15 08:00:00 : 효자1동   3733 ----------


 ---------- 2011-09-15 09:00:00 : 동  면   3734 ----------


 ---------- 2011-09-15 10:00:00 : 석사동   3735 ----------


 ---------- 2011-09-15 10:00:00 : 강남동   3737 ----------


 ---------- 2011-09-15 10:00:00 : 북산면   3738 ----------


 ---------- 2011-09-15 11:00:00 : 동  면   3739 ----------


 ---------- 2011-09-15 12:00:00 : 동  면   3740 ----------


 ---------- 2011-09-15 13:00:00 : 신북읍   3741 ----------


 ---------- 2011-09-15 14:00:00 : 신북읍   3742 ----------


 ---------- 2011-09-15 15:00:00 : 동내면   3743 ----------


 ---------- 2011-09-15 15:00:00 : 동  면   3744 ----------


 ---------- 2011-09-15 16:00:00 : 석사동   3746 ----------


 ---------- 2011-09-15 16:00:00 : 효자1동   3750 ----------


 ---------- 2011-09-15 16:00:00 : 남산면   3751 ----------


 ---------- 2011-09-15 17:00:00 : 소양동   3752 ----------


 ---------- 2011-09-15 18:00:00 : 신사우동   3753 ----------


 ---------- 2011-09-15 18:00:00 : 후평1동   3757 ----------


 ---------- 2011-09-15 19:00:00 : 소양동   3758 ----------


 ---------- 2011-09-15 20:00:00 : 소양동   3759 ----------


 ---------- 2011-09-16 09:00:00 : 신동면   3760 ----------


 ---------- 2011-09-16 09:00:00 : 후평1동   3761 ----------


 ---------- 2011-09-16 10:00:00 : 후평1동   3762 ----------


 ---------- 2011-09-16 10:00:00 : 북산면   3763 ----------


 ---------- 2011-09-16 11:00:00 : 강남동   3764 ----------


 ---------- 2011-09-16 11:00:00 : 동내면   3765 ----------


 ---------- 2011-09-16 12:00:00 : 퇴계동   3766 ----------


 ---------- 2011-09-16 15:00:00 : 신북읍   3767 ----------


 ---------- 2011-09-16 15:00:00 : 조운동   3768 ----------


 ---------- 2011-09-17 00:00:00 : 신북읍   3770 ----------


 ---------- 2011-09-17 01:00:00 : 후평1동   3771 ----------


 ---------- 2011-09-17 08:00:00 : 동  면   3772 ----------


 ---------- 2011-09-17 09:00:00 : 강남동   3773 ----------


 ---------- 2011-09-17 09:00:00 : 신사우동   3774 ----------


 ---------- 2011-09-17 09:00:00 : 북산면   3775 ----------


 ---------- 2011-09-17 10:00:00 : 석사동   3776 ----------


 ---------- 2011-09-17 10:00:00 : 후평1동   3777 ----------


 ---------- 2011-09-17 11:00:00 : 동내면   3778 ----------


 ---------- 2011-09-17 11:00:00 : 남산면   3779 ----------


 ---------- 2011-09-17 13:00:00 : 석사동   3780 ----------


 ---------- 2011-09-17 13:00:00 : 동내면   3781 ----------


 ---------- 2011-09-17 13:00:00 : 효자1동   3783 ----------


 ---------- 2011-09-17 14:00:00 : 북산면   3784 ----------


 ---------- 2011-09-17 15:00:00 : 신동면   3785 ----------


 ---------- 2011-09-17 15:00:00 : 서  면   3786 ----------


 ---------- 2011-09-17 15:00:00 : 퇴계동   3787 ----------


 ---------- 2011-09-17 16:00:00 : 강남동   3788 ----------


 ---------- 2011-09-17 18:00:00 : 퇴계동   3790 ----------


 ---------- 2011-09-17 19:00:00 : 동내면   3791 ----------


 ---------- 2011-09-18 03:00:00 : 서  면   3792 ----------


 ---------- 2011-09-18 09:00:00 : 서  면   3793 ----------


 ---------- 2011-09-18 13:00:00 : 서  면   3796 ----------


 ---------- 2011-09-18 14:00:00 : 동  면   3797 ----------


 ---------- 2011-09-18 15:00:00 : 북산면   3798 ----------


 ---------- 2011-09-18 16:00:00 : 남산면   3800 ----------


 ---------- 2011-09-18 22:00:00 : 석사동   3801 ----------


 ---------- 2011-09-19 01:00:00 : 강남동   3802 ----------


 ---------- 2011-09-19 03:00:00 : 퇴계동   3803 ----------


 ---------- 2011-09-19 07:00:00 : 약사명동   3804 ----------


 ---------- 2011-09-19 09:00:00 : 신사우동   3805 ----------

 ---------- 2011-09-19 13:00:00 : 효자1동   3807 ----------


 ---------- 2011-09-19 14:00:00 : 효자1동   3808 ----------


 ---------- 2011-09-19 15:00:00 : 북산면   3809 ----------


 ---------- 2011-09-19 19:00:00 : 후평1동   3810 ----------


 ---------- 2011-09-19 22:00:00 : 석사동   3812 ----------


 ---------- 2011-09-20 09:00:00 : 후평1동   3813 ----------


 ---------- 2011-09-20 10:00:00 : 신북읍   3814 ----------


 ---------- 2011-09-20 11:00:00 : 동내면   3815 ----------


 ---------- 2011-09-20 13:00:00 : 퇴계동   3816 ----------


 ---------- 2011-09-20 14:00:00 : 근화동   3817 ----------


 ---------- 2011-09-20 15:00:00 : 북산면   3818 ----------


 ---------- 2011-09-20 16:00:00 : 석사동   3819 ----------


 ---------- 2011-09-20 18:00:00 : 동  면   3820 ----------


 ---------- 2011-09-21 08:00:00 : 동  면   3821 ----------


 ---------- 2011-09-21 09:00:00 : 강남동   3822 ----------


 ---------- 2011-09-21 09:00:00 : 동내면   3823 ----------


 ---------- 2011-09-21 12:00:00 : 서  면   3824 ----------


 ---------- 2011-09-21 13:00:00 : 북산면   3825 ----------


 ---------- 2011-09-21 14:00:00 : 후평1동   3827 ----------


 ---------- 2011-09-22 03:00:00 : 퇴계동   3828 ----------


 ---------- 2011-09-22 07:00:00 : 후평1동   3829 ----------


 ---------- 2011-09-22 09:00:00 : 효자1동   3830 ----------


 ---------- 2011-09-22 11:00:00 : 남산면   3831 ----------


 ---------- 2011-09-22 14:00:00 : 북산면   3832 ----------


 ---------- 2011-09-22 16:00:00 : 소양동   3834 ----------


 ---------- 2011-09-22 19:00:00 : 서  면   3835 ----------


 ---------- 2011-09-22 20:00:00 : 북산면   3836 ----------


 ---------- 2011-09-23 00:00:00 : 효자1동   3837 ----------


 ---------- 2011-09-23 06:00:00 : 효자1동   3838 ----------


 ---------- 2011-09-23 08:00:00 : 신사우동   3839 ----------


 ---------- 2011-09-23 09:00:00 : 동  면   3840 ----------


 ---------- 2011-09-23 12:00:00 : 남산면   3841 ----------


 ---------- 2011-09-23 12:00:00 : 후평1동   3842 ----------


 ---------- 2011-09-23 13:00:00 : 효자1동   3843 ----------


 ---------- 2011-09-23 16:00:00 : 동내면   3844 ----------


 ---------- 2011-09-23 18:00:00 : 근화동   3845 ----------


 ---------- 2011-09-23 19:00:00 : 신사우동   3847 ----------


 ---------- 2011-09-23 20:00:00 : 동  면   3848 ----------


 ---------- 2011-09-24 03:00:00 : 근화동   3849 ----------


 ---------- 2011-09-24 09:00:00 : 강남동   3850 ----------


 ---------- 2011-09-24 09:00:00 : 동  면   3851 ----------


 ---------- 2011-09-24 13:00:00 : 남산면   3852 ----------


 ---------- 2011-09-24 13:00:00 : 약사명동   3853 ----------


 ---------- 2011-09-24 13:00:00 : 북산면   3855 ----------


 ---------- 2011-09-24 14:00:00 : 석사동   3856 ----------


 ---------- 2011-09-24 14:00:00 : 남산면   3857 ----------


 ---------- 2011-09-24 15:00:00 : 북산면   3858 ----------


 ---------- 2011-09-24 18:00:00 : 강남동   3859 ----------


 ---------- 2011-09-24 18:00:00 : 퇴계동   3860 ----------


 ---------- 2011-09-25 02:00:00 : 후평1동   3861 ----------


 ---------- 2011-09-25 03:00:00 : 신사우동   3862 ----------


 ---------- 2011-09-25 07:00:00 : 퇴계동   3863 ----------


 ---------- 2011-09-25 11:00:00 : 신북읍   3864 ----------


 ---------- 2011-09-25 14:00:00 : 근화동   3865 ----------


 ---------- 2011-09-25 16:00:00 : 석사동   3866 ----------


 ---------- 2011-09-26 10:00:00 : 석사동   3867 ----------


 ---------- 2011-09-26 10:00:00 : 강남동   3868 ----------


 ---------- 2011-09-26 10:00:00 : 신사우동   3869 ----------


 ---------- 2011-09-26 15:00:00 : 석사동   3870 ----------


 ---------- 2011-09-26 16:00:00 : 남산면   3871 ----------


 ---------- 2011-09-27 09:00:00 : 후평1동   3872 ----------


 ---------- 2011-09-27 10:00:00 : 후평1동   3873 ----------


 ---------- 2011-09-27 13:00:00 : 강남동   3874 ----------


 ---------- 2011-09-27 15:00:00 : 남산면   3875 ----------


 ---------- 2011-09-27 15:00:00 : 후평1동   3876 ----------


 ---------- 2011-09-27 15:00:00 : 퇴계동   3877 ----------


 ---------- 2011-09-27 16:00:00 : 후평1동   3878 ----------


 ---------- 2011-09-27 18:00:00 : 효자1동   3879 ----------


 ---------- 2011-09-27 19:00:00 : 신북읍   3880 ----------


 ---------- 2011-09-27 20:00:00 : 후평1동   3881 ----------


 ---------- 2011-09-27 21:00:00 : 근화동   3882 ----------


 ---------- 2011-09-27 22:00:00 : 신사우동   3883 ----------


 ---------- 2011-09-28 10:00:00 : 효자1동   3884 ----------


 ---------- 2011-09-28 11:00:00 : 강남동   3885 ----------


 ---------- 2011-09-28 12:00:00 : 약사명동   3887 ----------


 ---------- 2011-09-28 17:00:00 : 근화동   3888 ----------


 ---------- 2011-09-28 21:00:00 : 신사우동   3890 ----------


 ---------- 2011-09-29 10:00:00 : 북산면   3891 ----------


 ---------- 2011-09-29 13:00:00 : 사북면   3892 ----------


 ---------- 2011-09-29 14:00:00 : 남산면   3894 ----------


 ---------- 2011-09-29 20:00:00 : 소양동   3895 ----------


 ---------- 2011-09-29 21:00:00 : 소양동   3897 ----------


 ---------- 2011-09-30 03:00:00 : 교  동   3898 ----------


 ---------- 2011-09-30 08:00:00 : 북산면   3899 ----------


 ---------- 2011-09-30 09:00:00 : 남산면   3900 ----------


 ---------- 2011-09-30 09:00:00 : 퇴계동   3901 ----------


 ---------- 2011-09-30 11:00:00 : 서  면   3902 ----------


 ---------- 2011-09-30 13:00:00 : 동내면   3903 ----------


 ---------- 2011-09-30 13:00:00 : 퇴계동   3904 ----------


 ---------- 2011-09-30 15:00:00 : 강남동   3905 ----------


 ---------- 2011-09-30 15:00:00 : 근화동   3906 ----------


 ---------- 2011-09-30 23:00:00 : 효자1동   3908 ----------


 ---------- 2011-10-01 11:00:00 : 서  면   3910 ----------


 ---------- 2011-10-01 13:00:00 : 동  면   3911 ----------


 ---------- 2011-10-01 15:00:00 : 신사우동   3912 ----------


 ---------- 2011-10-02 04:00:00 : 효자1동   3913 ----------


 ---------- 2011-10-02 10:00:00 : 효자1동   3914 ----------


 ---------- 2011-10-02 12:00:00 : 사북면   3915 ----------


 ---------- 2011-10-02 12:00:00 : 북산면   3918 ----------


 ---------- 2011-10-02 16:00:00 : 남산면   3921 ----------


 ---------- 2011-10-02 18:00:00 : 강남동   3922 ----------


 ---------- 2011-10-02 18:00:00 : 후평1동   3924 ----------


 ---------- 2011-10-02 19:00:00 : 서  면   3926 ----------


 ---------- 2011-10-02 23:00:00 : 강남동   3927 ----------


 ---------- 2011-10-03 12:00:00 : 효자1동   3929 ----------


 ---------- 2011-10-03 15:00:00 : 효자1동   3931 ----------


 ---------- 2011-10-03 15:00:00 : 남산면   3934 ----------


 ---------- 2011-10-03 20:00:00 : 동  면   3935 ----------


 ---------- 2011-10-04 09:00:00 : 석사동   3936 ----------


 ---------- 2011-10-04 09:00:00 : 신북읍   3937 ----------


 ---------- 2011-10-04 12:00:00 : 동  면   3938 ----------


 ---------- 2011-10-04 20:00:00 : 효자1동   3940 ----------


 ---------- 2011-10-05 09:00:00 : 강남동   3941 ----------


 ---------- 2011-10-05 11:00:00 : 신동면   3942 ----------


 ---------- 2011-10-05 13:00:00 : 퇴계동   3943 ----------


 ---------- 2011-10-05 15:00:00 : 강남동   3944 ----------


 ---------- 2011-10-05 16:00:00 : 석사동   3945 ----------


 ---------- 2011-10-05 16:00:00 : 신동면   3947 ----------


 ---------- 2011-10-05 16:00:00 : 후평1동   3948 ----------


 ---------- 2011-10-05 17:00:00 : 근화동   3950 ----------


 ---------- 2011-10-06 00:00:00 : 후평1동   3951 ----------


 ---------- 2011-10-06 09:00:00 : 신사우동   3952 ----------


 ---------- 2011-10-06 11:00:00 : 신동면   3953 ----------


 ---------- 2011-10-06 11:00:00 : 강남동   3954 ----------


 ---------- 2011-10-06 12:00:00 : 석사동   3956 ----------


 ---------- 2011-10-06 13:00:00 : 서  면   3957 ----------


 ---------- 2011-10-06 13:00:00 : 신사우동   3958 ----------


 ---------- 2011-10-06 14:00:00 : 석사동   3959 ----------


 ---------- 2011-10-06 21:00:00 : 석사동   3960 ----------


 ---------- 2011-10-07 00:00:00 : 소양동   3961 ----------


 ---------- 2011-10-07 01:00:00 : 석사동   3963 ----------


 ---------- 2011-10-07 09:00:00 : 강남동   3964 ----------


 ---------- 2011-10-07 11:00:00 : 동산면   3966 ----------


 ---------- 2011-10-07 16:00:00 : 강남동   3968 ----------


 ---------- 2011-10-07 20:00:00 : 신동면   3969 ----------


 ---------- 2011-10-07 22:00:00 : 후평1동   3970 ----------


 ---------- 2011-10-08 14:00:00 : 남산면   3971 ----------


 ---------- 2011-10-09 08:00:00 : 서  면   3972 ----------


 ---------- 2011-10-09 08:00:00 : 동  면   3973 ----------

 ---------- 2011-10-09 12:00:00 : 신사우동   3975 ----------


 ---------- 2011-10-09 13:00:00 : 서  면   3976 ----------


 ---------- 2011-10-09 17:00:00 : 효자1동   3977 ----------


 ---------- 2011-10-10 09:00:00 : 북산면   3978 ----------


 ---------- 2011-10-10 14:00:00 : 석사동   3979 ----------


 ---------- 2011-10-10 14:00:00 : 동내면   3980 ----------


 ---------- 2011-10-10 23:00:00 : 퇴계동   3983 ----------


 ---------- 2011-10-11 01:00:00 : 신동면   3985 ----------


 ---------- 2011-10-11 11:00:00 : 북산면   3986 ----------


 ---------- 2011-10-11 12:00:00 : 서  면   3987 ----------


 ---------- 2011-10-11 13:00:00 : 석사동   3988 ----------


 ---------- 2011-10-11 13:00:00 : 동내면   3989 ----------


 ---------- 2011-10-11 13:00:00 : 신사우동   3990 ----------


 ---------- 2011-10-11 14:00:00 : 신동면   3991 ----------


 ---------- 2011-10-11 14:00:00 : 서  면   3993 ----------


 ---------- 2011-10-11 14:00:00 : 남산면   3995 ----------


 ---------- 2011-10-11 14:00:00 : 신사우동   3996 ----------


 ---------- 2011-10-11 14:00:00 : 동  면   3997 ----------


 ---------- 2011-10-11 15:00:00 : 남산면   3998 ----------


 ---------- 2011-10-11 15:00:00 : 퇴계동   3999 ----------


 ---------- 2011-10-11 21:00:00 : 석사동   4001 ----------


 ---------- 2011-10-12 11:00:00 : 근화동   4002 ----------


 ---------- 2011-10-12 13:00:00 : 효자1동   4003 ----------


 ---------- 2011-10-12 20:00:00 : 효자1동   4004 ----------


 ---------- 2011-10-13 09:00:00 : 후평1동   4005 ----------


 ---------- 2011-10-13 13:00:00 : 남산면   4006 ----------


 ---------- 2011-10-13 14:00:00 : 사북면   4007 ----------


 ---------- 2011-10-13 14:00:00 : 퇴계동   4008 ----------


 ---------- 2011-10-13 18:00:00 : 후평1동   4009 ----------


 ---------- 2011-10-13 20:00:00 : 효자1동   4010 ----------


 ---------- 2011-10-14 14:00:00 : 동산면   4011 ----------


 ---------- 2011-10-15 10:00:00 : 강남동   4012 ----------


 ---------- 2011-10-15 12:00:00 : 후평1동   4014 ----------


 ---------- 2011-10-16 00:00:00 : 동  면   4015 ----------


 ---------- 2011-10-16 09:00:00 : 효자1동   4017 ----------


 ---------- 2011-10-16 10:00:00 : 서  면   4019 ----------


 ---------- 2011-10-16 13:00:00 : 신사우동   4020 ----------


 ---------- 2011-10-16 14:00:00 : 석사동   4021 ----------


 ---------- 2011-10-16 15:00:00 : 남산면   4023 ----------


 ---------- 2011-10-16 21:00:00 : 강남동   4024 ----------


 ---------- 2011-10-16 23:00:00 : 약사명동   4025 ----------


 ---------- 2011-10-17 10:00:00 : 효자1동   4026 ----------


 ---------- 2011-10-17 15:00:00 : 약사명동   4028 ----------


 ---------- 2011-10-18 15:00:00 : 신북읍   4030 ----------


 ---------- 2011-10-19 11:00:00 : 강남동   4032 ----------


 ---------- 2011-10-19 12:00:00 : 동내면   4033 ----------


 ---------- 2011-10-19 15:00:00 : 신사우동   4034 ----------


 ---------- 2011-10-19 21:00:00 : 북산면   4035 ----------


 ---------- 2011-10-20 05:00:00 : 남산면   4036 ----------


 ---------- 2011-10-20 10:00:00 : 신북읍   4038 ----------


 ---------- 2011-10-20 11:00:00 : 석사동   4040 ----------


 ---------- 2011-10-20 12:00:00 : 북산면   4041 ----------


 ---------- 2011-10-20 13:00:00 : 석사동   4042 ----------


 ---------- 2011-10-20 14:00:00 : 효자1동   4043 ----------


 ---------- 2011-10-21 15:00:00 : 효자1동   4046 ----------


 ---------- 2011-10-21 20:00:00 : 약사명동   4047 ----------


 ---------- 2011-10-22 00:00:00 : 동  면   4048 ----------


 ---------- 2011-10-22 03:00:00 : 후평1동   4049 ----------


 ---------- 2011-10-22 10:00:00 : 사북면   4050 ----------


 ---------- 2011-10-22 13:00:00 : 신사우동   4052 ----------


 ---------- 2011-10-22 14:00:00 : 강남동   4053 ----------


 ---------- 2011-10-22 16:00:00 : 약사명동   4054 ----------


 ---------- 2011-10-22 19:00:00 : 효자1동   4056 ----------


 ---------- 2011-10-23 13:00:00 : 북산면   4059 ----------


 ---------- 2011-10-23 14:00:00 : 강남동   4060 ----------


 ---------- 2011-10-23 14:00:00 : 효자1동   4061 ----------


 ---------- 2011-10-23 16:00:00 : 석사동   4063 ----------


 ---------- 2011-10-23 22:00:00 : 석사동   4064 ----------


 ---------- 2011-10-24 10:00:00 : 강남동   4065 ----------


 ---------- 2011-10-24 10:00:00 : 신북읍   4066 ----------


 ---------- 2011-10-24 10:00:00 : 후평1동   4067 ----------


 ---------- 2011-10-24 11:00:00 : 석사동   4068 ----------


 ---------- 2011-10-24 19:00:00 : 약사명동   4069 ----------


 ---------- 2011-10-24 23:00:00 : 후평1동   4070 ----------


 ---------- 2011-10-25 01:00:00 : 효자1동   4071 ----------


 ---------- 2011-10-25 10:00:00 : 신사우동   4072 ----------


 ---------- 2011-10-25 21:00:00 : 약사명동   4073 ----------


 ---------- 2011-10-25 21:00:00 : 후평1동   4074 ----------


 ---------- 2011-10-25 23:00:00 : 남산면   4076 ----------


 ---------- 2011-10-26 22:00:00 : 효자1동   4077 ----------


 ---------- 2011-10-27 17:00:00 : 신사우동   4078 ----------


 ---------- 2011-10-27 23:00:00 : 석사동   4079 ----------


 ---------- 2011-10-28 08:00:00 : 신사우동   4080 ----------


 ---------- 2011-10-28 09:00:00 : 신사우동   4081 ----------


 ---------- 2011-10-28 11:00:00 : 신사우동   4082 ----------


 ---------- 2011-10-28 14:00:00 : 석사동   4083 ----------


 ---------- 2011-10-28 15:00:00 : 석사동   4084 ----------


 ---------- 2011-10-28 17:00:00 : 동내면   4085 ----------


 ---------- 2011-10-28 22:00:00 : 신동면   4088 ----------


 ---------- 2011-10-29 11:00:00 : 후평1동   4089 ----------


 ---------- 2011-10-29 15:00:00 : 북산면   4091 ----------


 ---------- 2011-10-29 15:00:00 : 동산면   4092 ----------


 ---------- 2011-10-29 18:00:00 : 서  면   4094 ----------


 ---------- 2011-10-30 10:00:00 : 동내면   4095 ----------


 ---------- 2011-10-30 13:00:00 : 동  면   4096 ----------


 ---------- 2011-10-30 16:00:00 : 신사우동   4097 ----------


 ---------- 2011-10-30 18:00:00 : 동내면   4098 ----------


 ---------- 2011-10-30 21:00:00 : 조운동   4099 ----------


 ---------- 2011-10-31 06:00:00 : 신북읍   4100 ----------


 ---------- 2011-10-31 09:00:00 : 사북면   4101 ----------


 ---------- 2011-10-31 10:00:00 : 신사우동   4102 ----------


 ---------- 2011-10-31 10:00:00 : 후평1동   4103 ----------


 ---------- 2011-10-31 12:00:00 : 약사명동   4105 ----------


 ---------- 2011-10-31 20:00:00 : 후평1동   4106 ----------


 ---------- 2011-11-01 10:00:00 : 강남동   4108 ----------


 ---------- 2011-11-01 11:00:00 : 퇴계동   4109 ----------


 ---------- 2011-11-01 15:00:00 : 남산면   4110 ----------


 ---------- 2011-11-01 15:00:00 : 후평1동   4111 ----------


 ---------- 2011-11-01 20:00:00 : 후평1동   4112 ----------


 ---------- 2011-11-01 20:00:00 : 퇴계동   4113 ----------


 ---------- 2011-11-01 23:00:00 : 효자1동   4115 ----------


 ---------- 2011-11-02 09:00:00 : 효자1동   4116 ----------


 ---------- 2011-11-02 22:00:00 : 남산면   4117 ----------


 ---------- 2011-11-03 09:00:00 : 근화동   4118 ----------


 ---------- 2011-11-03 10:00:00 : 후평1동   4119 ----------


 ---------- 2011-11-03 17:00:00 : 퇴계동   4121 ----------


 ---------- 2011-11-03 20:00:00 : 후평1동   4122 ----------


 ---------- 2011-11-04 05:00:00 : 후평1동   4124 ----------


 ---------- 2011-11-04 22:00:00 : 조운동   4125 ----------


 ---------- 2011-11-04 23:00:00 : 신사우동   4126 ----------


 ---------- 2011-11-05 04:00:00 : 소양동   4128 ----------


 ---------- 2011-11-05 09:00:00 : 효자1동   4130 ----------


 ---------- 2011-11-05 09:00:00 : 조운동   4132 ----------


 ---------- 2011-11-05 13:00:00 : 효자1동   4133 ----------


 ---------- 2011-11-05 14:00:00 : 후평1동   4134 ----------


 ---------- 2011-11-05 15:00:00 : 효자1동   4135 ----------


 ---------- 2011-11-05 16:00:00 : 서  면   4136 ----------


 ---------- 2011-11-06 10:00:00 : 서  면   4138 ----------


 ---------- 2011-11-06 13:00:00 : 퇴계동   4139 ----------


 ---------- 2011-11-06 15:00:00 : 북산면   4141 ----------


 ---------- 2011-11-06 16:00:00 : 북산면   4142 ----------


 ---------- 2011-11-07 09:00:00 : 서  면   4143 ----------


 ---------- 2011-11-07 13:00:00 : 동  면   4145 ----------


 ---------- 2011-11-07 13:00:00 : 교  동   4146 ----------


 ---------- 2011-11-07 14:00:00 : 교  동   4147 ----------


 ---------- 2011-11-07 15:00:00 : 동내면   4148 ----------


 ---------- 2011-11-07 16:00:00 : 강남동   4149 ----------


 ---------- 2011-11-08 05:00:00 : 후평1동   4150 ----------

 ---------- 2011-11-09 01:00:00 : 신북읍   4151 ----------


 ---------- 2011-11-09 03:00:00 : 후평1동   4152 ----------


 ---------- 2011-11-09 13:00:00 : 강남동   4154 ----------


 ---------- 2011-11-09 14:00:00 : 신사우동   4156 ----------


 ---------- 2011-11-09 18:00:00 : 강남동   4157 ----------


 ---------- 2011-11-10 10:00:00 : 효자1동   4158 ----------


 ---------- 2011-11-10 11:00:00 : 남산면   4160 ----------


 ---------- 2011-11-10 13:00:00 : 서  면   4162 ----------


 ---------- 2011-11-10 14:00:00 : 북산면   4164 ----------


 ---------- 2011-11-10 15:00:00 : 북산면   4165 ----------


 ---------- 2011-11-10 20:00:00 : 석사동   4166 ----------


 ---------- 2011-11-11 00:00:00 : 효자1동   4167 ----------


 ---------- 2011-11-11 08:00:00 : 동내면   4170 ----------


 ---------- 2011-11-11 13:00:00 : 후평1동   4172 ----------


 ---------- 2011-11-12 09:00:00 : 효자1동   4173 ----------


 ---------- 2011-11-12 10:00:00 : 남산면   4174 ----------


 ---------- 2011-11-13 01:00:00 : 남  면   4176 ----------


 ---------- 2011-11-13 14:00:00 : 동  면   4177 ----------


 ---------- 2011-11-13 22:00:00 : 후평1동   4178 ----------


 ---------- 2011-11-14 01:00:00 : 석사동   4179 ----------


 ---------- 2011-11-14 05:00:00 : 효자1동   4181 ----------


 ---------- 2011-11-14 11:00:00 : 석사동   4182 ----------


 ---------- 2011-11-14 12:00:00 : 석사동   4183 ----------


 ---------- 2011-11-14 16:00:00 : 퇴계동   4185 ----------


 ---------- 2011-11-14 17:00:00 : 서  면   4187 ----------


 ---------- 2011-11-14 20:00:00 : 효자1동   4188 ----------


 ---------- 2011-11-14 21:00:00 : 신사우동   4189 ----------


 ---------- 2011-11-15 14:00:00 : 후평1동   4190 ----------


 ---------- 2011-11-15 21:00:00 : 동  면   4191 ----------


 ---------- 2011-11-15 23:00:00 : 남  면   4192 ----------


 ---------- 2011-11-17 12:00:00 : 조운동   4194 ----------


 ---------- 2011-11-17 16:00:00 : 석사동   4195 ----------


 ---------- 2011-11-17 17:00:00 : 퇴계동   4196 ----------


 ---------- 2011-11-18 02:00:00 : 효자1동   4197 ----------


 ---------- 2011-11-18 08:00:00 : 신동면   4199 ----------


 ---------- 2011-11-18 10:00:00 : 조운동   4200 ----------


 ---------- 2011-11-18 19:00:00 : 퇴계동   4202 ----------


 ---------- 2011-11-19 00:00:00 : 강남동   4204 ----------


 ---------- 2011-11-20 05:00:00 : 소양동   4205 ----------


 ---------- 2011-11-20 22:00:00 : 석사동   4206 ----------


 ---------- 2011-11-21 19:00:00 : 근화동   4207 ----------


 ---------- 2011-11-21 20:00:00 : 동산면   4208 ----------


 ---------- 2011-11-21 21:00:00 : 효자1동   4209 ----------


 ---------- 2011-11-22 15:00:00 : 퇴계동   4211 ----------


 ---------- 2011-11-23 01:00:00 : 남산면   4212 ----------


 ---------- 2011-11-23 12:00:00 : 효자1동   4213 ----------


 ---------- 2011-11-23 19:00:00 : 서  면   4215 ----------


 ---------- 2011-11-24 09:00:00 : 석사동   4216 ----------


 ---------- 2011-11-24 09:00:00 : 후평1동   4217 ----------


 ---------- 2011-11-24 12:00:00 : 석사동   4219 ----------


 ---------- 2011-11-24 15:00:00 : 동산면   4221 ----------


 ---------- 2011-11-25 08:00:00 : 북산면   4222 ----------


 ---------- 2011-11-25 10:00:00 : 신사우동   4224 ----------


 ---------- 2011-11-25 12:00:00 : 남산면   4226 ----------


 ---------- 2011-11-26 01:00:00 : 후평1동   4227 ----------


 ---------- 2011-11-26 03:00:00 : 남산면   4229 ----------


 ---------- 2011-11-26 15:00:00 : 남산면   4231 ----------


 ---------- 2011-11-26 17:00:00 : 서  면   4233 ----------


 ---------- 2011-11-26 20:00:00 : 남산면   4235 ----------


 ---------- 2011-11-27 00:00:00 : 근화동   4236 ----------


 ---------- 2011-11-27 06:00:00 : 사북면   4237 ----------


 ---------- 2011-11-27 07:00:00 : 효자1동   4240 ----------


 ---------- 2011-11-27 08:00:00 : 서  면   4241 ----------


 ---------- 2011-11-27 18:00:00 : 효자1동   4243 ----------


 ---------- 2011-11-27 22:00:00 : 효자1동   4245 ----------


 ---------- 2011-11-29 04:00:00 : 서  면   4248 ----------


 ---------- 2011-11-29 19:00:00 : 신사우동   4249 ----------


 ---------- 2011-11-30 09:00:00 : 강남동   4250 ----------


 ---------- 2011-11-30 15:00:00 : 후평1동   4251 ----------


 ---------- 2011-11-30 21:00:00 : 강남동   4252 ----------


 ---------- 2011-12-01 07:00:00 : 신사우동   4253 ----------


 ---------- 2011-12-01 19:00:00 : 신사우동   4254 ----------


 ---------- 2011-12-02 11:00:00 : 동  면   4256 ----------


 ---------- 2011-12-02 16:00:00 : 후평1동   4257 ----------


 ---------- 2011-12-02 18:00:00 : 석사동   4258 ----------


 ---------- 2011-12-02 21:00:00 : 석사동   4259 ----------


 ---------- 2011-12-02 22:00:00 : 석사동   4261 ----------


 ---------- 2011-12-03 02:00:00 : 퇴계동   4262 ----------


 ---------- 2011-12-03 19:00:00 : 후평1동   4263 ----------


 ---------- 2011-12-04 02:00:00 : 석사동   4265 ----------


 ---------- 2011-12-04 04:00:00 : 후평1동   4266 ----------


 ---------- 2011-12-04 11:00:00 : 신사우동   4267 ----------


 ---------- 2011-12-04 23:00:00 : 석사동   4268 ----------


 ---------- 2011-12-05 13:00:00 : 동  면   4269 ----------


 ---------- 2011-12-06 08:00:00 : 조운동   4270 ----------


 ---------- 2011-12-06 13:00:00 : 동내면   4271 ----------


 ---------- 2011-12-06 17:00:00 : 근화동   4272 ----------


 ---------- 2011-12-07 08:00:00 : 퇴계동   4273 ----------


 ---------- 2011-12-07 09:00:00 : 근화동   4274 ----------


 ---------- 2011-12-07 15:00:00 : 효자1동   4276 ----------


 ---------- 2011-12-08 16:00:00 : 석사동   4278 ----------


 ---------- 2011-12-08 17:00:00 : 효자1동   4279 ----------


 ---------- 2011-12-08 22:00:00 : 강남동   4280 ----------


 ---------- 2011-12-08 23:00:00 : 약사명동   4281 ----------


 ---------- 2011-12-09 09:00:00 : 강남동   4283 ----------


 ---------- 2011-12-09 14:00:00 : 근화동   4284 ----------


 ---------- 2011-12-09 22:00:00 : 신동면   4285 ----------


 ---------- 2011-12-10 01:00:00 : 퇴계동   4287 ----------


 ---------- 2011-12-10 10:00:00 : 효자1동   4288 ----------


 ---------- 2011-12-10 10:00:00 : 후평1동   4289 ----------


 ---------- 2011-12-10 22:00:00 : 강남동   4290 ----------


 ---------- 2011-12-10 23:00:00 : 남  면   4291 ----------


 ---------- 2011-12-11 00:00:00 : 약사명동   4292 ----------


 ---------- 2011-12-11 15:00:00 : 후평1동   4293 ----------


 ---------- 2011-12-13 10:00:00 : 강남동   4295 ----------


 ---------- 2011-12-13 15:00:00 : 서  면   4298 ----------


 ---------- 2011-12-13 16:00:00 : 서  면   4299 ----------


 ---------- 2011-12-13 16:00:00 : 후평1동   4300 ----------


 ---------- 2011-12-13 21:00:00 : 약사명동   4301 ----------


 ---------- 2011-12-15 00:00:00 : 후평1동   4302 ----------


 ---------- 2011-12-15 02:00:00 : 후평1동   4303 ----------


 ---------- 2011-12-15 07:00:00 : 동  면   4304 ----------


 ---------- 2011-12-15 18:00:00 : 신사우동   4305 ----------


 ---------- 2011-12-15 18:00:00 : 약사명동   4306 ----------


 ---------- 2011-12-15 20:00:00 : 동내면   4307 ----------


 ---------- 2011-12-16 03:00:00 : 후평1동   4308 ----------


 ---------- 2011-12-16 13:00:00 : 남산면   4310 ----------


 ---------- 2011-12-16 19:00:00 : 후평1동   4311 ----------


 ---------- 2011-12-17 00:00:00 : 석사동   4314 ----------


 ---------- 2011-12-17 06:00:00 : 효자1동   4316 ----------


 ---------- 2011-12-17 17:00:00 : 서  면   4317 ----------


 ---------- 2011-12-17 17:00:00 : 신사우동   4319 ----------


 ---------- 2011-12-18 09:00:00 : 사북면   4320 ----------


 ---------- 2011-12-18 17:00:00 : 신북읍   4321 ----------


 ---------- 2011-12-18 18:00:00 : 신동면   4323 ----------


 ---------- 2011-12-18 23:00:00 : 동  면   4324 ----------


 ---------- 2011-12-19 08:00:00 : 퇴계동   4326 ----------


 ---------- 2011-12-19 15:00:00 : 신북읍   4328 ----------


 ---------- 2011-12-19 15:00:00 : 동  면   4329 ----------


 ---------- 2011-12-20 10:00:00 : 신사우동   4330 ----------


 ---------- 2011-12-21 02:00:00 : 후평1동   4331 ----------


 ---------- 2011-12-21 09:00:00 : 강남동   4332 ----------


 ---------- 2011-12-21 12:00:00 : 효자1동   4334 ----------


 ---------- 2011-12-21 13:00:00 : 신사우동   4335 ----------


 ---------- 2011-12-21 16:00:00 : 신북읍   4336 ----------


 ---------- 2011-12-21 19:00:00 : 후평1동   4337 ----------


 ---------- 2011-12-21 23:00:00 : 후평1동   4339 ----------


 ---------- 2011-12-22 08:00:00 : 강남동   4341 ----------

 ---------- 2011-12-22 15:00:00 : 조운동   4342 ----------


 ---------- 2011-12-22 16:00:00 : 후평1동   4343 ----------


 ---------- 2011-12-23 09:00:00 : 신북읍   4344 ----------


 ---------- 2011-12-23 16:00:00 : 소양동   4345 ----------


 ---------- 2011-12-24 07:00:00 : 퇴계동   4347 ----------


 ---------- 2011-12-24 08:00:00 : 효자1동   4348 ----------


 ---------- 2011-12-24 08:00:00 : 퇴계동   4349 ----------


 ---------- 2011-12-24 09:00:00 : 남산면   4353 ----------


 ---------- 2011-12-24 12:00:00 : 동내면   4354 ----------


 ---------- 2011-12-24 13:00:00 : 동내면   4355 ----------


 ---------- 2011-12-24 21:00:00 : 남  면   4356 ----------


 ---------- 2011-12-24 22:00:00 : 강남동   4357 ----------


 ---------- 2011-12-25 03:00:00 : 근화동   4358 ----------


 ---------- 2011-12-25 04:00:00 : 남  면   4359 ----------


 ---------- 2011-12-25 11:00:00 : 퇴계동   4361 ----------


 ---------- 2011-12-25 13:00:00 : 효자1동   4362 ----------


 ---------- 2011-12-25 19:00:00 : 강남동   4364 ----------


 ---------- 2011-12-25 21:00:00 : 강남동   4365 ----------


 ---------- 2011-12-26 00:00:00 : 효자1동   4366 ----------


 ---------- 2011-12-26 01:00:00 : 후평1동   4367 ----------


 ---------- 2011-12-26 04:00:00 : 후평1동   4368 ----------


 ---------- 2011-12-26 07:00:00 : 동내면   4369 ----------


 ---------- 2011-12-26 13:00:00 : 효자1동   4372 ----------


 ---------- 2011-12-26 13:00:00 : 후평1동   4373 ----------


 ---------- 2011-12-26 13:00:00 : 퇴계동   4375 ----------


 ---------- 2011-12-26 18:00:00 : 후평1동   4376 ----------


 ---------- 2011-12-26 19:00:00 : 근화동   4377 ----------


 ---------- 2011-12-26 21:00:00 : 석사동   4378 ----------


 ---------- 2011-12-27 07:00:00 : 신사우동   4379 ----------


 ---------- 2011-12-27 14:00:00 : 효자1동   4380 ----------


 ---------- 2011-12-27 14:00:00 : 소양동   4382 ----------


 ---------- 2011-12-27 15:00:00 : 서  면   4383 ----------


 ---------- 2011-12-28 06:00:00 : 동내면   4386 ----------


 ---------- 2011-12-28 12:00:00 : 퇴계동   4387 ----------


 ---------- 2011-12-28 17:00:00 : 신사우동   4388 ----------


 ---------- 2011-12-28 18:00:00 : 남산면   4389 ----------


 ---------- 2011-12-28 18:00:00 : 동  면   4392 ----------


 ---------- 2011-12-28 20:00:00 : 사북면   4393 ----------


 ---------- 2011-12-28 22:00:00 : 효자1동   4394 ----------


 ---------- 2011-12-28 23:00:00 : 동  면   4397 ----------


 ---------- 2011-12-29 16:00:00 : 소양동   4398 ----------


 ---------- 2011-12-29 18:00:00 : 소양동   4399 ----------


 ---------- 2011-12-30 01:00:00 : 효자1동   4401 ----------


 ---------- 2011-12-30 02:00:00 : 신사우동   4402 ----------


 ---------- 2011-12-30 06:00:00 : 조운동   4403 ----------


 ---------- 2011-12-30 09:00:00 : 신동면   4405 ----------


 ---------- 2011-12-31 00:00:00 : 석사동   4407 ----------


 ---------- 2011-12-31 14:00:00 : 강남동   4410 ----------


 ---------- 2011-12-31 18:00:00 : 남산면   4411 ----------


 ---------- 2011-12-31 22:00:00 : 석사동   4412 ----------


 ---------- 2012-01-01 16:00:00 : 서  면   4414 ----------


 ---------- 2012-01-01 17:00:00 : 서  면   4415 ----------


 ---------- 2012-01-01 18:00:00 : 강남동   4418 ----------


 ---------- 2012-01-01 18:00:00 : 퇴계동   4419 ----------


 ---------- 2012-01-01 20:00:00 : 효자1동   4420 ----------


 ---------- 2012-01-02 08:00:00 : 퇴계동   4422 ----------


 ---------- 2012-01-02 14:00:00 : 동내면   4423 ----------


 ---------- 2012-01-02 15:00:00 : 효자1동   4424 ----------


 ---------- 2012-01-02 15:00:00 : 퇴계동   4426 ----------


 ---------- 2012-01-03 11:00:00 : 석사동   4427 ----------


 ---------- 2012-01-03 13:00:00 : 석사동   4429 ----------


 ---------- 2012-01-04 01:00:00 : 후평1동   4430 ----------


 ---------- 2012-01-04 11:00:00 : 남산면   4433 ----------


 ---------- 2012-01-04 12:00:00 : 동산면   4434 ----------


 ---------- 2012-01-04 17:00:00 : 후평1동   4435 ----------


 ---------- 2012-01-05 08:00:00 : 신북읍   4436 ----------


 ---------- 2012-01-05 15:00:00 : 퇴계동   4437 ----------


 ---------- 2012-01-05 18:00:00 : 동  면   4438 ----------


 ---------- 2012-01-06 01:00:00 : 동내면   4440 ----------


 ---------- 2012-01-06 01:00:00 : 소양동   4441 ----------


 ---------- 2012-01-06 06:00:00 : 효자1동   4442 ----------


 ---------- 2012-01-06 12:00:00 : 신북읍   4445 ----------


 ---------- 2012-01-06 18:00:00 : 동  면   4446 ----------


 ---------- 2012-01-06 20:00:00 : 사북면   4448 ----------


 ---------- 2012-01-06 20:00:00 : 후평1동   4449 ----------


 ---------- 2012-01-07 00:00:00 : 효자1동   4451 ----------


 ---------- 2012-01-07 02:00:00 : 신동면   4452 ----------


 ---------- 2012-01-07 02:00:00 : 남산면   4453 ----------


 ---------- 2012-01-07 06:00:00 : 근화동   4454 ----------


 ---------- 2012-01-07 08:00:00 : 남산면   4455 ----------


 ---------- 2012-01-07 15:00:00 : 강남동   4457 ----------


 ---------- 2012-01-07 18:00:00 : 남산면   4458 ----------


 ---------- 2012-01-07 18:00:00 : 동  면   4459 ----------


 ---------- 2012-01-07 19:00:00 : 남산면   4461 ----------


 ---------- 2012-01-07 22:00:00 : 효자1동   4462 ----------


 ---------- 2012-01-08 02:00:00 : 퇴계동   4463 ----------


 ---------- 2012-01-08 14:00:00 : 석사동   4464 ----------


 ---------- 2012-01-08 16:00:00 : 남  면   4466 ----------


 ---------- 2012-01-08 17:00:00 : 신사우동   4467 ----------


 ---------- 2012-01-09 06:00:00 : 동산면   4469 ----------


 ---------- 2012-01-09 07:00:00 : 동내면   4470 ----------


 ---------- 2012-01-09 21:00:00 : 남산면   4472 ----------


 ---------- 2012-01-09 21:00:00 : 후평1동   4474 ----------


 ---------- 2012-01-09 22:00:00 : 후평1동   4476 ----------


 ---------- 2012-01-10 03:00:00 : 효자1동   4477 ----------


 ---------- 2012-01-10 10:00:00 : 사북면   4478 ----------


 ---------- 2012-01-10 13:00:00 : 동내면   4479 ----------


 ---------- 2012-01-10 17:00:00 : 소양동   4480 ----------


 ---------- 2012-01-10 21:00:00 : 후평1동   4481 ----------


 ---------- 2012-01-11 02:00:00 : 후평1동   4482 ----------


 ---------- 2012-01-11 18:00:00 : 퇴계동   4483 ----------


 ---------- 2012-01-12 00:00:00 : 석사동   4485 ----------


 ---------- 2012-01-12 03:00:00 : 퇴계동   4487 ----------


 ---------- 2012-01-12 15:00:00 : 사북면   4488 ----------


 ---------- 2012-01-12 18:00:00 : 효자1동   4490 ----------


 ---------- 2012-01-14 05:00:00 : 신사우동   4491 ----------


 ---------- 2012-01-14 17:00:00 : 석사동   4492 ----------


 ---------- 2012-01-14 21:00:00 : 동산면   4494 ----------


 ---------- 2012-01-14 23:00:00 : 남산면   4495 ----------


 ---------- 2012-01-15 00:00:00 : 퇴계동   4496 ----------


 ---------- 2012-01-15 01:00:00 : 서  면   4497 ----------


 ---------- 2012-01-15 18:00:00 : 사북면   4499 ----------


 ---------- 2012-01-16 12:00:00 : 신동면   4500 ----------


 ---------- 2012-01-17 09:00:00 : 석사동   4501 ----------


 ---------- 2012-01-17 15:00:00 : 동내면   4502 ----------


 ---------- 2012-01-17 16:00:00 : 강남동   4503 ----------


 ---------- 2012-01-18 06:00:00 : 강남동   4504 ----------


 ---------- 2012-01-18 15:00:00 : 소양동   4505 ----------


 ---------- 2012-01-18 16:00:00 : 신북읍   4506 ----------


 ---------- 2012-01-18 18:00:00 : 소양동   4507 ----------


 ---------- 2012-01-19 09:00:00 : 서  면   4508 ----------


 ---------- 2012-01-19 12:00:00 : 사북면   4509 ----------


 ---------- 2012-01-19 12:00:00 : 소양동   4511 ----------


 ---------- 2012-01-19 13:00:00 : 신사우동   4512 ----------


 ---------- 2012-01-19 13:00:00 : 신북읍   4514 ----------


 ---------- 2012-01-19 13:00:00 : 북산면   4516 ----------


 ---------- 2012-01-19 16:00:00 : 북산면   4518 ----------


 ---------- 2012-01-19 19:00:00 : 동내면   4519 ----------


 ---------- 2012-01-19 21:00:00 : 효자1동   4520 ----------


 ---------- 2012-01-19 22:00:00 : 퇴계동   4522 ----------


 ---------- 2012-01-20 19:00:00 : 근화동   4523 ----------


 ---------- 2012-01-20 19:00:00 : 퇴계동   4524 ----------


 ---------- 2012-01-20 20:00:00 : 근화동   4526 ----------


 ---------- 2012-01-20 23:00:00 : 강남동   4527 ----------


 ---------- 2012-01-20 23:00:00 : 근화동   4529 ----------


 ---------- 2012-01-21 00:00:00 : 강남동   4530 ----------


 ---------- 2012-01-21 15:00:00 : 신동면   4532 ----------


 ---------- 2012-01-21 23:00:00 : 퇴계동   4533 ----------


 ---------- 2012-01-22 00:00:00 : 서  면   4534 ----------

 ---------- 2012-01-22 05:00:00 : 강남동   4537 ----------


 ---------- 2012-01-22 18:00:00 : 효자1동   4538 ----------


 ---------- 2012-01-23 06:00:00 : 신북읍   4539 ----------


 ---------- 2012-01-24 22:00:00 : 후평1동   4540 ----------


 ---------- 2012-01-25 10:00:00 : 남산면   4541 ----------


 ---------- 2012-01-25 10:00:00 : 동산면   4544 ----------


 ---------- 2012-01-25 19:00:00 : 남산면   4546 ----------


 ---------- 2012-01-25 21:00:00 : 석사동   4547 ----------


 ---------- 2012-01-26 05:00:00 : 신북읍   4548 ----------


 ---------- 2012-01-26 14:00:00 : 강남동   4549 ----------


 ---------- 2012-01-26 14:00:00 : 후평1동   4550 ----------


 ---------- 2012-01-26 20:00:00 : 후평1동   4551 ----------


 ---------- 2012-01-26 21:00:00 : 석사동   4552 ----------


 ---------- 2012-01-26 21:00:00 : 동산면   4554 ----------


 ---------- 2012-01-27 00:00:00 : 퇴계동   4556 ----------


 ---------- 2012-01-27 14:00:00 : 효자1동   4558 ----------


 ---------- 2012-01-27 14:00:00 : 후평1동   4559 ----------


 ---------- 2012-01-27 20:00:00 : 퇴계동   4561 ----------


 ---------- 2012-01-27 21:00:00 : 북산면   4562 ----------


 ---------- 2012-01-28 02:00:00 : 서  면   4563 ----------


 ---------- 2012-01-28 22:00:00 : 강남동   4564 ----------


 ---------- 2012-01-29 03:00:00 : 후평1동   4565 ----------


 ---------- 2012-01-29 15:00:00 : 근화동   4567 ----------


 ---------- 2012-01-29 16:00:00 : 후평1동   4568 ----------


 ---------- 2012-01-29 19:00:00 : 퇴계동   4569 ----------


 ---------- 2012-01-29 22:00:00 : 근화동   4571 ----------


 ---------- 2012-01-30 04:00:00 : 후평1동   4572 ----------


 ---------- 2012-01-30 11:00:00 : 퇴계동   4574 ----------


 ---------- 2012-01-30 12:00:00 : 퇴계동   4575 ----------


 ---------- 2012-01-30 22:00:00 : 석사동   4576 ----------


 ---------- 2012-01-31 08:00:00 : 후평1동   4577 ----------


 ---------- 2012-01-31 10:00:00 : 동내면   4578 ----------


 ---------- 2012-01-31 11:00:00 : 조운동   4579 ----------


 ---------- 2012-01-31 16:00:00 : 사북면   4580 ----------


 ---------- 2012-01-31 16:00:00 : 동내면   4582 ----------


 ---------- 2012-02-01 10:00:00 : 동  면   4584 ----------


 ---------- 2012-02-01 21:00:00 : 남  면   4586 ----------


 ---------- 2012-02-02 07:00:00 : 동내면   4588 ----------


 ---------- 2012-02-02 13:00:00 : 서  면   4589 ----------


 ---------- 2012-02-02 17:00:00 : 동내면   4590 ----------


 ---------- 2012-02-02 17:00:00 : 효자1동   4591 ----------


 ---------- 2012-02-02 19:00:00 : 강남동   4592 ----------


 ---------- 2012-02-02 21:00:00 : 소양동   4593 ----------


 ---------- 2012-02-02 21:00:00 : 퇴계동   4594 ----------


 ---------- 2012-02-03 07:00:00 : 퇴계동   4595 ----------


 ---------- 2012-02-03 07:00:00 : 교  동   4597 ----------


 ---------- 2012-02-03 10:00:00 : 강남동   4598 ----------


 ---------- 2012-02-03 14:00:00 : 석사동   4599 ----------


 ---------- 2012-02-03 17:00:00 : 후평1동   4600 ----------


 ---------- 2012-02-03 21:00:00 : 효자1동   4601 ----------


 ---------- 2012-02-04 00:00:00 : 서  면   4603 ----------


 ---------- 2012-02-04 03:00:00 : 석사동   4605 ----------


 ---------- 2012-02-04 06:00:00 : 동  면   4606 ----------


 ---------- 2012-02-04 14:00:00 : 남산면   4607 ----------


 ---------- 2012-02-04 19:00:00 : 동내면   4608 ----------


 ---------- 2012-02-05 09:00:00 : 동내면   4610 ----------


 ---------- 2012-02-05 17:00:00 : 석사동   4611 ----------


 ---------- 2012-02-05 21:00:00 : 근화동   4612 ----------


 ---------- 2012-02-06 13:00:00 : 효자1동   4613 ----------


 ---------- 2012-02-06 16:00:00 : 사북면   4615 ----------


 ---------- 2012-02-06 17:00:00 : 남산면   4616 ----------


 ---------- 2012-02-07 15:00:00 : 남  면   4617 ----------


 ---------- 2012-02-07 17:00:00 : 신사우동   4618 ----------


 ---------- 2012-02-07 19:00:00 : 퇴계동   4619 ----------


 ---------- 2012-02-09 09:00:00 : 동산면   4620 ----------


 ---------- 2012-02-09 14:00:00 : 후평1동   4621 ----------


 ---------- 2012-02-10 00:00:00 : 근화동   4622 ----------


 ---------- 2012-02-10 02:00:00 : 후평1동   4623 ----------


 ---------- 2012-02-10 10:00:00 : 소양동   4624 ----------


 ---------- 2012-02-10 11:00:00 : 동  면   4625 ----------


 ---------- 2012-02-10 13:00:00 : 석사동   4626 ----------


 ---------- 2012-02-10 17:00:00 : 동산면   4627 ----------


 ---------- 2012-02-10 19:00:00 : 후평1동   4628 ----------


 ---------- 2012-02-11 01:00:00 : 후평1동   4629 ----------


 ---------- 2012-02-11 02:00:00 : 효자1동   4630 ----------


 ---------- 2012-02-11 08:00:00 : 동산면   4631 ----------


 ---------- 2012-02-11 09:00:00 : 석사동   4632 ----------


 ---------- 2012-02-11 12:00:00 : 남산면   4634 ----------


 ---------- 2012-02-11 13:00:00 : 신동면   4636 ----------


 ---------- 2012-02-11 14:00:00 : 퇴계동   4637 ----------


 ---------- 2012-02-12 00:00:00 : 후평1동   4638 ----------


 ---------- 2012-02-12 01:00:00 : 소양동   4639 ----------


 ---------- 2012-02-12 06:00:00 : 약사명동   4640 ----------


 ---------- 2012-02-12 08:00:00 : 동내면   4641 ----------


 ---------- 2012-02-12 14:00:00 : 약사명동   4642 ----------


 ---------- 2012-02-13 17:00:00 : 소양동   4643 ----------


 ---------- 2012-02-14 01:00:00 : 교  동   4644 ----------


 ---------- 2012-02-14 03:00:00 : 동  면   4645 ----------


 ---------- 2012-02-14 07:00:00 : 효자1동   4646 ----------


 ---------- 2012-02-14 12:00:00 : 효자1동   4647 ----------


 ---------- 2012-02-15 08:00:00 : 신동면   4648 ----------


 ---------- 2012-02-15 09:00:00 : 효자1동   4650 ----------


 ---------- 2012-02-15 11:00:00 : 강남동   4651 ----------


 ---------- 2012-02-16 13:00:00 : 신사우동   4652 ----------


 ---------- 2012-02-16 19:00:00 : 석사동   4653 ----------


 ---------- 2012-02-16 19:00:00 : 약사명동   4654 ----------


 ---------- 2012-02-16 21:00:00 : 후평1동   4655 ----------


 ---------- 2012-02-17 03:00:00 : 석사동   4656 ----------


 ---------- 2012-02-17 03:00:00 : 신사우동   4657 ----------


 ---------- 2012-02-17 08:00:00 : 사북면   4659 ----------


 ---------- 2012-02-17 08:00:00 : 신북읍   4661 ----------


 ---------- 2012-02-17 13:00:00 : 남산면   4662 ----------


 ---------- 2012-02-17 14:00:00 : 효자1동   4663 ----------


 ---------- 2012-02-17 17:00:00 : 동내면   4664 ----------


 ---------- 2012-02-17 23:00:00 : 후평1동   4665 ----------


 ---------- 2012-02-18 14:00:00 : 서  면   4666 ----------


 ---------- 2012-02-18 15:00:00 : 효자1동   4667 ----------


 ---------- 2012-02-18 17:00:00 : 사북면   4668 ----------


 ---------- 2012-02-18 21:00:00 : 신동면   4669 ----------


 ---------- 2012-02-19 00:00:00 : 조운동   4670 ----------


 ---------- 2012-02-19 08:00:00 : 동내면   4671 ----------


 ---------- 2012-02-19 08:00:00 : 신사우동   4672 ----------


 ---------- 2012-02-19 12:00:00 : 후평1동   4673 ----------


 ---------- 2012-02-19 17:00:00 : 신사우동   4674 ----------


 ---------- 2012-02-19 20:00:00 : 석사동   4675 ----------


 ---------- 2012-02-19 20:00:00 : 동  면   4676 ----------


 ---------- 2012-02-20 07:00:00 : 동내면   4677 ----------


 ---------- 2012-02-20 20:00:00 : 서  면   4680 ----------


 ---------- 2012-02-20 20:00:00 : 동내면   4682 ----------


 ---------- 2012-02-20 22:00:00 : 남산면   4684 ----------


 ---------- 2012-02-20 23:00:00 : 석사동   4685 ----------


 ---------- 2012-02-21 08:00:00 : 서  면   4686 ----------


 ---------- 2012-02-21 11:00:00 : 신사우동   4687 ----------


 ---------- 2012-02-21 16:00:00 : 사북면   4688 ----------


 ---------- 2012-02-22 04:00:00 : 근화동   4689 ----------


 ---------- 2012-02-22 05:00:00 : 신동면   4690 ----------


 ---------- 2012-02-22 13:00:00 : 신사우동   4691 ----------


 ---------- 2012-02-23 10:00:00 : 동산면   4692 ----------


 ---------- 2012-02-23 11:00:00 : 효자1동   4693 ----------


 ---------- 2012-02-23 15:00:00 : 후평1동   4694 ----------


 ---------- 2012-02-23 18:00:00 : 퇴계동   4695 ----------


 ---------- 2012-02-23 23:00:00 : 후평1동   4696 ----------


 ---------- 2012-02-24 10:00:00 : 퇴계동   4697 ----------


 ---------- 2012-02-24 12:00:00 : 조운동   4698 ----------


 ---------- 2012-02-24 14:00:00 : 효자1동   4699 ----------


 ---------- 2012-02-24 20:00:00 : 신사우동   4700 ----------


 ---------- 2012-02-25 01:00:00 : 퇴계동   4701 ----------


 ---------- 2012-02-25 02:00:00 : 동  면   4703 ----------

 ---------- 2012-02-25 20:00:00 : 신북읍   4704 ----------


 ---------- 2012-02-26 04:00:00 : 북산면   4706 ----------


 ---------- 2012-02-28 01:00:00 : 후평1동   4707 ----------


 ---------- 2012-02-28 06:00:00 : 신사우동   4708 ----------


 ---------- 2012-02-28 11:00:00 : 남산면   4709 ----------


 ---------- 2012-02-28 14:00:00 : 소양동   4710 ----------


 ---------- 2012-02-28 15:00:00 : 효자1동   4711 ----------


 ---------- 2012-02-28 18:00:00 : 근화동   4712 ----------


 ---------- 2012-02-28 21:00:00 : 효자1동   4713 ----------


 ---------- 2012-02-29 09:00:00 : 후평1동   4714 ----------


 ---------- 2012-02-29 13:00:00 : 효자1동   4715 ----------


 ---------- 2012-02-29 14:00:00 : 동  면   4716 ----------


 ---------- 2012-02-29 20:00:00 : 남산면   4717 ----------


 ---------- 2012-03-01 00:00:00 : 조운동   4718 ----------


 ---------- 2012-03-01 13:00:00 : 신사우동   4719 ----------


 ---------- 2012-03-01 20:00:00 : 퇴계동   4720 ----------


 ---------- 2012-03-02 07:00:00 : 신사우동   4721 ----------


 ---------- 2012-03-02 16:00:00 : 동산면   4723 ----------


 ---------- 2012-03-02 23:00:00 : 신사우동   4724 ----------


 ---------- 2012-03-03 05:00:00 : 동산면   4725 ----------


 ---------- 2012-03-03 09:00:00 : 동산면   4726 ----------


 ---------- 2012-03-03 10:00:00 : 서  면   4727 ----------


 ---------- 2012-03-03 13:00:00 : 효자1동   4728 ----------


 ---------- 2012-03-03 14:00:00 : 후평1동   4729 ----------


 ---------- 2012-03-03 15:00:00 : 근화동   4730 ----------


 ---------- 2012-03-03 19:00:00 : 소양동   4731 ----------


 ---------- 2012-03-03 22:00:00 : 석사동   4732 ----------


 ---------- 2012-03-04 08:00:00 : 근화동   4733 ----------


 ---------- 2012-03-04 18:00:00 : 신사우동   4734 ----------


 ---------- 2012-03-04 19:00:00 : 석사동   4735 ----------


 ---------- 2012-03-04 22:00:00 : 소양동   4736 ----------


 ---------- 2012-03-05 02:00:00 : 효자1동   4737 ----------


 ---------- 2012-03-05 09:00:00 : 약사명동   4739 ----------


 ---------- 2012-03-05 21:00:00 : 후평1동   4740 ----------


 ---------- 2012-03-06 08:00:00 : 신북읍   4741 ----------


 ---------- 2012-03-06 09:00:00 : 효자1동   4742 ----------


 ---------- 2012-03-06 17:00:00 : 신사우동   4743 ----------


 ---------- 2012-03-07 00:00:00 : 강남동   4745 ----------


 ---------- 2012-03-07 14:00:00 : 석사동   4746 ----------


 ---------- 2012-03-07 15:00:00 : 석사동   4747 ----------


 ---------- 2012-03-07 19:00:00 : 동  면   4748 ----------


 ---------- 2012-03-09 20:00:00 : 후평1동   4749 ----------


 ---------- 2012-03-09 22:00:00 : 후평1동   4750 ----------


 ---------- 2012-03-10 17:00:00 : 신사우동   4751 ----------


 ---------- 2012-03-10 22:00:00 : 효자1동   4752 ----------


 ---------- 2012-03-10 23:00:00 : 효자1동   4753 ----------


 ---------- 2012-03-11 00:00:00 : 효자1동   4755 ----------


 ---------- 2012-03-11 04:00:00 : 퇴계동   4756 ----------


 ---------- 2012-03-11 05:00:00 : 근화동   4757 ----------


 ---------- 2012-03-11 05:00:00 : 후평1동   4758 ----------


 ---------- 2012-03-11 14:00:00 : 신북읍   4759 ----------


 ---------- 2012-03-11 15:00:00 : 후평1동   4760 ----------


 ---------- 2012-03-11 19:00:00 : 후평1동   4761 ----------


 ---------- 2012-03-12 05:00:00 : 남산면   4763 ----------


 ---------- 2012-03-12 23:00:00 : 근화동   4765 ----------


 ---------- 2012-03-13 04:00:00 : 효자1동   4767 ----------


 ---------- 2012-03-13 18:00:00 : 후평1동   4768 ----------


 ---------- 2012-03-14 02:00:00 : 퇴계동   4770 ----------


 ---------- 2012-03-14 05:00:00 : 효자1동   4772 ----------


 ---------- 2012-03-14 09:00:00 : 동내면   4773 ----------


 ---------- 2012-03-14 09:00:00 : 신사우동   4774 ----------


 ---------- 2012-03-14 15:00:00 : 후평1동   4775 ----------


 ---------- 2012-03-14 17:00:00 : 동  면   4776 ----------


 ---------- 2012-03-14 20:00:00 : 소양동   4777 ----------


 ---------- 2012-03-14 20:00:00 : 퇴계동   4779 ----------


 ---------- 2012-03-14 21:00:00 : 후평1동   4780 ----------


 ---------- 2012-03-15 14:00:00 : 동내면   4781 ----------


 ---------- 2012-03-15 15:00:00 : 동  면   4782 ----------


 ---------- 2012-03-15 16:00:00 : 석사동   4783 ----------


 ---------- 2012-03-15 23:00:00 : 강남동   4784 ----------


 ---------- 2012-03-16 12:00:00 : 석사동   4785 ----------


 ---------- 2012-03-16 12:00:00 : 신동면   4787 ----------


 ---------- 2012-03-16 22:00:00 : 약사명동   4788 ----------


 ---------- 2012-03-18 09:00:00 : 서  면   4790 ----------


 ---------- 2012-03-18 10:00:00 : 근화동   4791 ----------


 ---------- 2012-03-18 13:00:00 : 후평1동   4792 ----------


 ---------- 2012-03-18 15:00:00 : 근화동   4793 ----------


 ---------- 2012-03-18 19:00:00 : 남산면   4794 ----------


 ---------- 2012-03-20 07:00:00 : 신사우동   4795 ----------


 ---------- 2012-03-20 09:00:00 : 소양동   4796 ----------


 ---------- 2012-03-21 05:00:00 : 남  면   4797 ----------


 ---------- 2012-03-21 15:00:00 : 근화동   4798 ----------


 ---------- 2012-03-21 18:00:00 : 효자1동   4799 ----------


 ---------- 2012-03-21 19:00:00 : 남산면   4800 ----------


 ---------- 2012-03-21 23:00:00 : 사북면   4802 ----------


 ---------- 2012-03-22 03:00:00 : 석사동   4803 ----------


 ---------- 2012-03-22 22:00:00 : 석사동   4805 ----------


 ---------- 2012-03-23 15:00:00 : 서  면   4807 ----------


 ---------- 2012-03-23 18:00:00 : 남산면   4808 ----------


 ---------- 2012-03-23 21:00:00 : 서  면   4809 ----------


 ---------- 2012-03-24 12:00:00 : 석사동   4810 ----------


 ---------- 2012-03-24 13:00:00 : 효자1동   4811 ----------


 ---------- 2012-03-24 15:00:00 : 서  면   4812 ----------


 ---------- 2012-03-24 16:00:00 : 남산면   4814 ----------


 ---------- 2012-03-24 17:00:00 : 석사동   4815 ----------


 ---------- 2012-03-25 05:00:00 : 소양동   4816 ----------


 ---------- 2012-03-25 18:00:00 : 퇴계동   4818 ----------


 ---------- 2012-03-25 19:00:00 : 후평1동   4819 ----------


 ---------- 2012-03-25 20:00:00 : 서  면   4821 ----------


 ---------- 2012-03-26 06:00:00 : 근화동   4822 ----------


 ---------- 2012-03-26 12:00:00 : 신북읍   4823 ----------


 ---------- 2012-03-26 18:00:00 : 동내면   4824 ----------


 ---------- 2012-03-26 20:00:00 : 신사우동   4825 ----------


 ---------- 2012-03-27 02:00:00 : 동산면   4827 ----------


 ---------- 2012-03-27 10:00:00 : 남산면   4829 ----------


 ---------- 2012-03-27 11:00:00 : 남산면   4830 ----------


 ---------- 2012-03-27 15:00:00 : 남산면   4831 ----------


 ---------- 2012-03-27 15:00:00 : 동  면   4832 ----------


 ---------- 2012-03-27 21:00:00 : 효자1동   4833 ----------


 ---------- 2012-03-28 09:00:00 : 동산면   4834 ----------


 ---------- 2012-03-28 11:00:00 : 동  면   4835 ----------


 ---------- 2012-03-28 19:00:00 : 효자1동   4836 ----------


 ---------- 2012-03-28 22:00:00 : 효자1동   4837 ----------


 ---------- 2012-03-29 00:00:00 : 남산면   4839 ----------


 ---------- 2012-03-29 06:00:00 : 신북읍   4840 ----------


 ---------- 2012-03-29 10:00:00 : 후평1동   4841 ----------


 ---------- 2012-03-29 13:00:00 : 석사동   4842 ----------


 ---------- 2012-03-29 21:00:00 : 소양동   4843 ----------


 ---------- 2012-03-29 23:00:00 : 신동면   4844 ----------


 ---------- 2012-03-30 09:00:00 : 효자1동   4846 ----------


 ---------- 2012-03-30 16:00:00 : 동내면   4847 ----------


 ---------- 2012-03-30 16:00:00 : 효자1동   4848 ----------


 ---------- 2012-03-30 16:00:00 : 후평1동   4850 ----------


 ---------- 2012-03-30 22:00:00 : 후평1동   4851 ----------


 ---------- 2012-03-31 12:00:00 : 석사동   4852 ----------


 ---------- 2012-03-31 17:00:00 : 후평1동   4853 ----------


 ---------- 2012-04-01 16:00:00 : 석사동   4854 ----------


 ---------- 2012-04-01 23:00:00 : 석사동   4855 ----------


 ---------- 2012-04-02 07:00:00 : 퇴계동   4856 ----------


 ---------- 2012-04-02 12:00:00 : 신사우동   4857 ----------


 ---------- 2012-04-02 19:00:00 : 신북읍   4859 ----------


 ---------- 2012-04-04 11:00:00 : 소양동   4860 ----------


 ---------- 2012-04-04 12:00:00 : 후평1동   4861 ----------


 ---------- 2012-04-04 22:00:00 : 신북읍   4862 ----------


 ---------- 2012-04-05 16:00:00 : 퇴계동   4864 ----------


 ---------- 2012-04-05 17:00:00 : 후평1동   4865 ----------


 ---------- 2012-04-06 03:00:00 : 석사동   4866 ----------


 ---------- 2012-04-06 11:00:00 : 퇴계동   4867 ----------

 ---------- 2012-04-06 18:00:00 : 후평1동   4868 ----------


 ---------- 2012-04-06 19:00:00 : 후평1동   4869 ----------


 ---------- 2012-04-07 07:00:00 : 남  면   4871 ----------


 ---------- 2012-04-07 07:00:00 : 신북읍   4872 ----------


 ---------- 2012-04-07 15:00:00 : 강남동   4873 ----------


 ---------- 2012-04-08 03:00:00 : 근화동   4875 ----------


 ---------- 2012-04-08 11:00:00 : 남산면   4877 ----------


 ---------- 2012-04-08 12:00:00 : 남산면   4880 ----------


 ---------- 2012-04-08 16:00:00 : 서  면   4881 ----------


 ---------- 2012-04-08 17:00:00 : 사북면   4882 ----------


 ---------- 2012-04-08 22:00:00 : 동내면   4884 ----------


 ---------- 2012-04-09 02:00:00 : 동내면   4885 ----------


 ---------- 2012-04-09 10:00:00 : 효자1동   4886 ----------


 ---------- 2012-04-09 13:00:00 : 후평1동   4887 ----------


 ---------- 2012-04-09 15:00:00 : 남산면   4888 ----------


 ---------- 2012-04-09 16:00:00 : 신북읍   4889 ----------


 ---------- 2012-04-10 10:00:00 : 교  동   4890 ----------


 ---------- 2012-04-10 12:00:00 : 후평1동   4891 ----------


 ---------- 2012-04-10 16:00:00 : 소양동   4892 ----------


 ---------- 2012-04-10 21:00:00 : 사북면   4894 ----------


 ---------- 2012-04-11 05:00:00 : 사북면   4896 ----------


 ---------- 2012-04-11 10:00:00 : 서  면   4899 ----------


 ---------- 2012-04-11 10:00:00 : 퇴계동   4900 ----------


 ---------- 2012-04-11 11:00:00 : 석사동   4901 ----------


 ---------- 2012-04-11 13:00:00 : 석사동   4902 ----------


 ---------- 2012-04-12 08:00:00 : 퇴계동   4903 ----------


 ---------- 2012-04-12 17:00:00 : 남산면   4905 ----------


 ---------- 2012-04-13 11:00:00 : 퇴계동   4906 ----------


 ---------- 2012-04-13 23:00:00 : 신동면   4907 ----------


 ---------- 2012-04-14 01:00:00 : 효자1동   4908 ----------


 ---------- 2012-04-14 04:00:00 : 남산면   4909 ----------


 ---------- 2012-04-14 04:00:00 : 동산면   4910 ----------


 ---------- 2012-04-15 01:00:00 : 신북읍   4911 ----------


 ---------- 2012-04-15 06:00:00 : 퇴계동   4912 ----------


 ---------- 2012-04-15 11:00:00 : 강남동   4914 ----------


 ---------- 2012-04-15 12:00:00 : 강남동   4915 ----------


 ---------- 2012-04-16 13:00:00 : 근화동   4916 ----------


 ---------- 2012-04-16 16:00:00 : 퇴계동   4917 ----------


 ---------- 2012-04-16 17:00:00 : 후평1동   4918 ----------


 ---------- 2012-04-16 20:00:00 : 효자1동   4919 ----------


 ---------- 2012-04-16 21:00:00 : 후평1동   4920 ----------


 ---------- 2012-04-17 00:00:00 : 효자1동   4921 ----------


 ---------- 2012-04-17 14:00:00 : 효자1동   4922 ----------


 ---------- 2012-04-17 15:00:00 : 효자1동   4923 ----------


 ---------- 2012-04-18 02:00:00 : 동내면   4924 ----------


 ---------- 2012-04-18 08:00:00 : 신북읍   4925 ----------


 ---------- 2012-04-18 15:00:00 : 신동면   4926 ----------


 ---------- 2012-04-18 15:00:00 : 강남동   4927 ----------


 ---------- 2012-04-18 16:00:00 : 강남동   4928 ----------


 ---------- 2012-04-18 19:00:00 : 석사동   4929 ----------


 ---------- 2012-04-19 05:00:00 : 퇴계동   4930 ----------


 ---------- 2012-04-19 10:00:00 : 남산면   4932 ----------


 ---------- 2012-04-19 13:00:00 : 동내면   4933 ----------


 ---------- 2012-04-19 18:00:00 : 신동면   4935 ----------


 ---------- 2012-04-19 19:00:00 : 효자1동   4936 ----------


 ---------- 2012-04-20 08:00:00 : 동산면   4937 ----------


 ---------- 2012-04-20 11:00:00 : 북산면   4940 ----------


 ---------- 2012-04-20 16:00:00 : 신사우동   4941 ----------


 ---------- 2012-04-20 17:00:00 : 신북읍   4942 ----------


 ---------- 2012-04-20 18:00:00 : 남  면   4943 ----------


 ---------- 2012-04-21 05:00:00 : 소양동   4944 ----------


 ---------- 2012-04-21 10:00:00 : 신동면   4945 ----------


 ---------- 2012-04-21 10:00:00 : 서  면   4947 ----------


 ---------- 2012-04-21 10:00:00 : 근화동   4949 ----------


 ---------- 2012-04-21 11:00:00 : 서  면   4950 ----------


 ---------- 2012-04-21 19:00:00 : 동내면   4951 ----------


 ---------- 2012-04-21 19:00:00 : 동  면   4952 ----------


 ---------- 2012-04-21 21:00:00 : 후평1동   4953 ----------


 ---------- 2012-04-22 01:00:00 : 석사동   4954 ----------


 ---------- 2012-04-22 17:00:00 : 신사우동   4955 ----------


 ---------- 2012-04-22 19:00:00 : 남  면   4956 ----------


 ---------- 2012-04-23 09:00:00 : 후평1동   4957 ----------


 ---------- 2012-04-23 12:00:00 : 퇴계동   4958 ----------


 ---------- 2012-04-23 18:00:00 : 동  면   4959 ----------


 ---------- 2012-04-24 10:00:00 : 효자1동   4960 ----------


 ---------- 2012-04-24 10:00:00 : 약사명동   4961 ----------


 ---------- 2012-04-24 13:00:00 : 석사동   4962 ----------


 ---------- 2012-04-24 13:00:00 : 퇴계동   4963 ----------


 ---------- 2012-04-24 14:00:00 : 후평1동   4965 ----------


 ---------- 2012-04-24 15:00:00 : 남산면   4966 ----------


 ---------- 2012-04-24 17:00:00 : 퇴계동   4967 ----------


 ---------- 2012-04-24 22:00:00 : 석사동   4968 ----------


 ---------- 2012-04-25 09:00:00 : 남산면   4970 ----------


 ---------- 2012-04-25 13:00:00 : 후평1동   4971 ----------


 ---------- 2012-04-25 18:00:00 : 조운동   4972 ----------


 ---------- 2012-04-25 20:00:00 : 서  면   4974 ----------


 ---------- 2012-04-25 23:00:00 : 퇴계동   4976 ----------


 ---------- 2012-04-26 13:00:00 : 효자1동   4977 ----------


 ---------- 2012-04-26 16:00:00 : 동  면   4978 ----------


 ---------- 2012-04-26 17:00:00 : 후평1동   4979 ----------


 ---------- 2012-04-26 19:00:00 : 강남동   4981 ----------


 ---------- 2012-04-27 05:00:00 : 남산면   4982 ----------


 ---------- 2012-04-27 10:00:00 : 후평1동   4983 ----------


 ---------- 2012-04-27 12:00:00 : 효자1동   4984 ----------


 ---------- 2012-04-27 15:00:00 : 서  면   4987 ----------


 ---------- 2012-04-27 15:00:00 : 후평1동   4988 ----------


 ---------- 2012-04-27 23:00:00 : 후평1동   4989 ----------


 ---------- 2012-04-28 00:00:00 : 후평1동   4990 ----------


 ---------- 2012-04-28 02:00:00 : 효자1동   4991 ----------


 ---------- 2012-04-28 03:00:00 : 효자1동   4992 ----------


 ---------- 2012-04-28 11:00:00 : 석사동   4993 ----------


 ---------- 2012-04-28 13:00:00 : 석사동   4994 ----------


 ---------- 2012-04-28 15:00:00 : 서  면   4996 ----------


 ---------- 2012-04-28 17:00:00 : 동  면   4997 ----------


 ---------- 2012-04-28 18:00:00 : 석사동   4998 ----------


 ---------- 2012-04-29 12:00:00 : 남산면   5001 ----------


 ---------- 2012-04-29 13:00:00 : 서  면   5004 ----------


 ---------- 2012-04-29 17:00:00 : 동산면   5006 ----------


 ---------- 2012-04-29 19:00:00 : 동내면   5007 ----------


 ---------- 2012-04-30 00:00:00 : 신동면   5009 ----------


 ---------- 2012-04-30 09:00:00 : 근화동   5010 ----------


 ---------- 2012-04-30 10:00:00 : 약사명동   5012 ----------


 ---------- 2012-04-30 12:00:00 : 신동면   5014 ----------


 ---------- 2012-04-30 13:00:00 : 신동면   5015 ----------


 ---------- 2012-04-30 17:00:00 : 석사동   5016 ----------


 ---------- 2012-05-01 08:00:00 : 신사우동   5017 ----------


 ---------- 2012-05-01 08:00:00 : 소양동   5018 ----------


 ---------- 2012-05-01 11:00:00 : 동내면   5020 ----------


 ---------- 2012-05-01 12:00:00 : 동내면   5021 ----------


 ---------- 2012-05-01 15:00:00 : 동산면   5022 ----------


 ---------- 2012-05-01 17:00:00 : 퇴계동   5023 ----------


 ---------- 2012-05-01 21:00:00 : 퇴계동   5024 ----------


 ---------- 2012-05-02 10:00:00 : 동내면   5025 ----------


 ---------- 2012-05-02 12:00:00 : 강남동   5026 ----------


 ---------- 2012-05-02 15:00:00 : 서  면   5028 ----------


 ---------- 2012-05-02 17:00:00 : 효자1동   5029 ----------


 ---------- 2012-05-02 22:00:00 : 후평1동   5031 ----------


 ---------- 2012-05-03 02:00:00 : 약사명동   5032 ----------


 ---------- 2012-05-03 08:00:00 : 서  면   5034 ----------


 ---------- 2012-05-03 09:00:00 : 서  면   5035 ----------


 ---------- 2012-05-03 13:00:00 : 석사동   5036 ----------


 ---------- 2012-05-03 22:00:00 : 퇴계동   5037 ----------


 ---------- 2012-05-04 08:00:00 : 남산면   5038 ----------


 ---------- 2012-05-04 09:00:00 : 신동면   5039 ----------


 ---------- 2012-05-04 09:00:00 : 강남동   5040 ----------


 ---------- 2012-05-04 09:00:00 : 후평1동   5041 ----------


 ---------- 2012-05-04 10:00:00 : 신사우동   5042 ----------


 ---------- 2012-05-04 13:00:00 : 후평1동   5043 ----------

 ---------- 2012-05-04 14:00:00 : 동  면   5044 ----------


 ---------- 2012-05-04 18:00:00 : 신사우동   5045 ----------


 ---------- 2012-05-05 02:00:00 : 동  면   5046 ----------


 ---------- 2012-05-05 03:00:00 : 석사동   5047 ----------


 ---------- 2012-05-05 09:00:00 : 근화동   5048 ----------


 ---------- 2012-05-05 14:00:00 : 신동면   5050 ----------


 ---------- 2012-05-05 14:00:00 : 서  면   5051 ----------


 ---------- 2012-05-05 16:00:00 : 서  면   5054 ----------


 ---------- 2012-05-05 18:00:00 : 후평1동   5055 ----------


 ---------- 2012-05-05 19:00:00 : 퇴계동   5056 ----------


 ---------- 2012-05-05 22:00:00 : 후평1동   5057 ----------


 ---------- 2012-05-06 05:00:00 : 동산면   5058 ----------


 ---------- 2012-05-06 14:00:00 : 퇴계동   5059 ----------


 ---------- 2012-05-06 16:00:00 : 소양동   5061 ----------


 ---------- 2012-05-06 21:00:00 : 동내면   5064 ----------


 ---------- 2012-05-07 16:00:00 : 후평1동   5065 ----------


 ---------- 2012-05-07 17:00:00 : 서  면   5067 ----------


 ---------- 2012-05-07 17:00:00 : 남산면   5068 ----------


 ---------- 2012-05-07 19:00:00 : 신사우동   5069 ----------


 ---------- 2012-05-07 21:00:00 : 후평1동   5070 ----------


 ---------- 2012-05-08 00:00:00 : 약사명동   5071 ----------


 ---------- 2012-05-08 04:00:00 : 후평1동   5072 ----------


 ---------- 2012-05-08 10:00:00 : 효자1동   5073 ----------


 ---------- 2012-05-08 11:00:00 : 신사우동   5074 ----------


 ---------- 2012-05-08 14:00:00 : 서  면   5076 ----------


 ---------- 2012-05-08 21:00:00 : 석사동   5077 ----------


 ---------- 2012-05-09 10:00:00 : 강남동   5079 ----------


 ---------- 2012-05-09 16:00:00 : 퇴계동   5080 ----------


 ---------- 2012-05-09 21:00:00 : 퇴계동   5081 ----------


 ---------- 2012-05-10 08:00:00 : 신북읍   5082 ----------


 ---------- 2012-05-10 10:00:00 : 석사동   5083 ----------


 ---------- 2012-05-10 12:00:00 : 조운동   5084 ----------


 ---------- 2012-05-10 23:00:00 : 남산면   5085 ----------


 ---------- 2012-05-11 09:00:00 : 효자1동   5086 ----------


 ---------- 2012-05-11 13:00:00 : 효자1동   5087 ----------


 ---------- 2012-05-11 17:00:00 : 서  면   5088 ----------


 ---------- 2012-05-11 19:00:00 : 동산면   5090 ----------


 ---------- 2012-05-11 22:00:00 : 남산면   5091 ----------


 ---------- 2012-05-12 07:00:00 : 동  면   5092 ----------


 ---------- 2012-05-12 11:00:00 : 북산면   5094 ----------


 ---------- 2012-05-12 11:00:00 : 동산면   5095 ----------


 ---------- 2012-05-12 13:00:00 : 약사명동   5096 ----------


 ---------- 2012-05-12 15:00:00 : 남산면   5098 ----------


 ---------- 2012-05-12 21:00:00 : 효자1동   5099 ----------


 ---------- 2012-05-12 22:00:00 : 강남동   5101 ----------


 ---------- 2012-05-12 23:00:00 : 강남동   5102 ----------


 ---------- 2012-05-12 23:00:00 : 후평1동   5103 ----------


 ---------- 2012-05-13 14:00:00 : 남  면   5106 ----------


 ---------- 2012-05-13 15:00:00 : 서  면   5108 ----------


 ---------- 2012-05-13 16:00:00 : 서  면   5109 ----------


 ---------- 2012-05-13 19:00:00 : 신북읍   5110 ----------


 ---------- 2012-05-13 19:00:00 : 후평1동   5111 ----------


 ---------- 2012-05-13 20:00:00 : 석사동   5113 ----------


 ---------- 2012-05-13 20:00:00 : 퇴계동   5114 ----------


 ---------- 2012-05-14 06:00:00 : 퇴계동   5115 ----------


 ---------- 2012-05-14 20:00:00 : 동산면   5116 ----------


 ---------- 2012-05-15 18:00:00 : 효자1동   5117 ----------


 ---------- 2012-05-16 13:00:00 : 효자1동   5118 ----------


 ---------- 2012-05-16 18:00:00 : 퇴계동   5120 ----------


 ---------- 2012-05-16 19:00:00 : 남  면   5121 ----------


 ---------- 2012-05-16 22:00:00 : 효자1동   5123 ----------


 ---------- 2012-05-17 00:00:00 : 후평1동   5124 ----------


 ---------- 2012-05-17 11:00:00 : 강남동   5125 ----------


 ---------- 2012-05-17 13:00:00 : 남산면   5126 ----------


 ---------- 2012-05-17 16:00:00 : 동내면   5127 ----------


 ---------- 2012-05-17 17:00:00 : 남산면   5128 ----------


 ---------- 2012-05-18 00:00:00 : 사북면   5129 ----------


 ---------- 2012-05-18 00:00:00 : 퇴계동   5130 ----------


 ---------- 2012-05-18 11:00:00 : 퇴계동   5131 ----------


 ---------- 2012-05-18 13:00:00 : 효자1동   5132 ----------


 ---------- 2012-05-19 00:00:00 : 후평1동   5133 ----------


 ---------- 2012-05-19 02:00:00 : 조운동   5136 ----------


 ---------- 2012-05-19 11:00:00 : 동  면   5137 ----------


 ---------- 2012-05-19 20:00:00 : 신북읍   5138 ----------


 ---------- 2012-05-19 21:00:00 : 강남동   5139 ----------


 ---------- 2012-05-19 22:00:00 : 남  면   5142 ----------


 ---------- 2012-05-19 23:00:00 : 효자1동   5144 ----------


 ---------- 2012-05-19 23:00:00 : 신사우동   5145 ----------


 ---------- 2012-05-20 15:00:00 : 남산면   5147 ----------


 ---------- 2012-05-20 16:00:00 : 신북읍   5148 ----------


 ---------- 2012-05-20 18:00:00 : 서  면   5150 ----------


 ---------- 2012-05-20 20:00:00 : 효자1동   5151 ----------


 ---------- 2012-05-20 21:00:00 : 동  면   5152 ----------


 ---------- 2012-05-20 23:00:00 : 퇴계동   5154 ----------


 ---------- 2012-05-21 08:00:00 : 남  면   5156 ----------


 ---------- 2012-05-21 13:00:00 : 남  면   5158 ----------


 ---------- 2012-05-21 14:00:00 : 소양동   5159 ----------


 ---------- 2012-05-21 17:00:00 : 신동면   5160 ----------


 ---------- 2012-05-21 17:00:00 : 남산면   5161 ----------


 ---------- 2012-05-22 11:00:00 : 퇴계동   5162 ----------


 ---------- 2012-05-22 12:00:00 : 신사우동   5163 ----------


 ---------- 2012-05-22 21:00:00 : 남산면   5164 ----------


 ---------- 2012-05-23 10:00:00 : 남산면   5165 ----------


 ---------- 2012-05-23 14:00:00 : 신사우동   5166 ----------


 ---------- 2012-05-24 03:00:00 : 남산면   5167 ----------


 ---------- 2012-05-24 09:00:00 : 후평1동   5169 ----------


 ---------- 2012-05-24 15:00:00 : 남산면   5170 ----------


 ---------- 2012-05-24 16:00:00 : 신사우동   5171 ----------


 ---------- 2012-05-24 17:00:00 : 남산면   5173 ----------


 ---------- 2012-05-24 19:00:00 : 신동면   5174 ----------


 ---------- 2012-05-24 19:00:00 : 강남동   5175 ----------


 ---------- 2012-05-24 23:00:00 : 서  면   5176 ----------


 ---------- 2012-05-25 02:00:00 : 소양동   5177 ----------


 ---------- 2012-05-25 09:00:00 : 서  면   5178 ----------


 ---------- 2012-05-25 12:00:00 : 동산면   5179 ----------


 ---------- 2012-05-25 13:00:00 : 신북읍   5180 ----------


 ---------- 2012-05-25 13:00:00 : 교  동   5181 ----------


 ---------- 2012-05-25 17:00:00 : 사북면   5183 ----------


 ---------- 2012-05-25 19:00:00 : 사북면   5184 ----------


 ---------- 2012-05-25 19:00:00 : 퇴계동   5186 ----------


 ---------- 2012-05-26 13:00:00 : 남산면   5188 ----------


 ---------- 2012-05-26 13:00:00 : 후평1동   5189 ----------


 ---------- 2012-05-26 17:00:00 : 동  면   5190 ----------


 ---------- 2012-05-26 20:00:00 : 효자1동   5191 ----------


 ---------- 2012-05-26 20:00:00 : 신사우동   5192 ----------


 ---------- 2012-05-26 21:00:00 : 후평1동   5193 ----------


 ---------- 2012-05-27 00:00:00 : 효자1동   5194 ----------


 ---------- 2012-05-27 03:00:00 : 효자1동   5196 ----------


 ---------- 2012-05-27 10:00:00 : 남산면   5198 ----------


 ---------- 2012-05-27 11:00:00 : 소양동   5199 ----------


 ---------- 2012-05-27 12:00:00 : 강남동   5200 ----------


 ---------- 2012-05-27 16:00:00 : 사북면   5201 ----------


 ---------- 2012-05-27 18:00:00 : 동  면   5202 ----------


 ---------- 2012-05-27 22:00:00 : 후평1동   5203 ----------


 ---------- 2012-05-28 15:00:00 : 후평1동   5204 ----------


 ---------- 2012-05-28 20:00:00 : 효자1동   5205 ----------


 ---------- 2012-05-29 08:00:00 : 후평1동   5206 ----------


 ---------- 2012-05-29 09:00:00 : 북산면   5207 ----------


 ---------- 2012-05-29 10:00:00 : 근화동   5208 ----------


 ---------- 2012-05-29 12:00:00 : 북산면   5210 ----------


 ---------- 2012-05-29 15:00:00 : 남산면   5211 ----------


 ---------- 2012-05-29 21:00:00 : 석사동   5212 ----------


 ---------- 2012-05-29 21:00:00 : 효자1동   5213 ----------


 ---------- 2012-05-29 23:00:00 : 근화동   5215 ----------


 ---------- 2012-05-30 03:00:00 : 효자1동   5216 ----------


 ---------- 2012-05-30 04:00:00 : 효자1동   5218 ----------


 ---------- 2012-05-30 09:00:00 : 신사우동   5219 ----------


 ---------- 2012-05-31 00:00:00 : 동내면   5221 ----------

 ---------- 2012-05-31 05:00:00 : 후평1동   5222 ----------


 ---------- 2012-05-31 17:00:00 : 퇴계동   5223 ----------


 ---------- 2012-05-31 18:00:00 : 동내면   5224 ----------


 ---------- 2012-05-31 18:00:00 : 동  면   5225 ----------


 ---------- 2012-05-31 22:00:00 : 남산면   5226 ----------


 ---------- 2012-06-01 00:00:00 : 효자1동   5227 ----------


 ---------- 2012-06-01 17:00:00 : 신사우동   5229 ----------


 ---------- 2012-06-02 09:00:00 : 근화동   5230 ----------


 ---------- 2012-06-02 12:00:00 : 서  면   5233 ----------


 ---------- 2012-06-02 13:00:00 : 효자1동   5234 ----------


 ---------- 2012-06-02 15:00:00 : 후평1동   5235 ----------


 ---------- 2012-06-03 00:00:00 : 근화동   5236 ----------


 ---------- 2012-06-03 06:00:00 : 강남동   5237 ----------


 ---------- 2012-06-03 12:00:00 : 퇴계동   5240 ----------


 ---------- 2012-06-03 17:00:00 : 후평1동   5241 ----------


 ---------- 2012-06-03 21:00:00 : 남산면   5242 ----------


 ---------- 2012-06-03 21:00:00 : 신북읍   5243 ----------


 ---------- 2012-06-04 03:00:00 : 소양동   5245 ----------


 ---------- 2012-06-04 05:00:00 : 석사동   5246 ----------


 ---------- 2012-06-04 07:00:00 : 후평1동   5247 ----------


 ---------- 2012-06-04 18:00:00 : 석사동   5248 ----------


 ---------- 2012-06-04 19:00:00 : 석사동   5249 ----------


 ---------- 2012-06-04 21:00:00 : 남산면   5252 ----------


 ---------- 2012-06-05 00:00:00 : 퇴계동   5253 ----------


 ---------- 2012-06-05 04:00:00 : 석사동   5254 ----------


 ---------- 2012-06-05 14:00:00 : 신북읍   5256 ----------


 ---------- 2012-06-05 20:00:00 : 신북읍   5257 ----------


 ---------- 2012-06-06 06:00:00 : 석사동   5258 ----------


 ---------- 2012-06-06 09:00:00 : 남산면   5259 ----------


 ---------- 2012-06-06 15:00:00 : 남산면   5260 ----------


 ---------- 2012-06-06 19:00:00 : 동  면   5261 ----------


 ---------- 2012-06-06 22:00:00 : 조운동   5262 ----------


 ---------- 2012-06-07 07:00:00 : 효자1동   5263 ----------


 ---------- 2012-06-07 14:00:00 : 동  면   5264 ----------


 ---------- 2012-06-07 14:00:00 : 후평1동   5265 ----------


 ---------- 2012-06-08 04:00:00 : 효자1동   5267 ----------


 ---------- 2012-06-08 10:00:00 : 퇴계동   5268 ----------


 ---------- 2012-06-08 12:00:00 : 소양동   5269 ----------


 ---------- 2012-06-08 23:00:00 : 퇴계동   5270 ----------


 ---------- 2012-06-09 06:00:00 : 후평1동   5271 ----------


 ---------- 2012-06-09 13:00:00 : 동  면   5272 ----------


 ---------- 2012-06-09 13:00:00 : 북산면   5273 ----------


 ---------- 2012-06-09 17:00:00 : 강남동   5274 ----------


 ---------- 2012-06-09 21:00:00 : 강남동   5275 ----------


 ---------- 2012-06-09 23:00:00 : 신사우동   5276 ----------


 ---------- 2012-06-10 03:00:00 : 남산면   5277 ----------


 ---------- 2012-06-10 09:00:00 : 남산면   5278 ----------


 ---------- 2012-06-10 13:00:00 : 사북면   5279 ----------


 ---------- 2012-06-10 13:00:00 : 남산면   5282 ----------


 ---------- 2012-06-10 14:00:00 : 사북면   5283 ----------


 ---------- 2012-06-11 11:00:00 : 퇴계동   5284 ----------


 ---------- 2012-06-11 13:00:00 : 퇴계동   5285 ----------


 ---------- 2012-06-12 04:00:00 : 석사동   5286 ----------


 ---------- 2012-06-12 04:00:00 : 퇴계동   5287 ----------


 ---------- 2012-06-12 06:00:00 : 동산면   5288 ----------


 ---------- 2012-06-12 08:00:00 : 신사우동   5289 ----------


 ---------- 2012-06-12 10:00:00 : 효자1동   5290 ----------


 ---------- 2012-06-12 13:00:00 : 동내면   5291 ----------


 ---------- 2012-06-12 15:00:00 : 동산면   5294 ----------


 ---------- 2012-06-12 16:00:00 : 후평1동   5295 ----------


 ---------- 2012-06-12 23:00:00 : 강남동   5297 ----------


 ---------- 2012-06-13 01:00:00 : 신사우동   5298 ----------


 ---------- 2012-06-13 12:00:00 : 동내면   5299 ----------


 ---------- 2012-06-13 12:00:00 : 조운동   5300 ----------


 ---------- 2012-06-13 13:00:00 : 퇴계동   5301 ----------


 ---------- 2012-06-13 17:00:00 : 동  면   5302 ----------


 ---------- 2012-06-13 21:00:00 : 후평1동   5303 ----------


 ---------- 2012-06-14 01:00:00 : 동  면   5304 ----------


 ---------- 2012-06-14 10:00:00 : 석사동   5305 ----------


 ---------- 2012-06-14 18:00:00 : 강남동   5306 ----------


 ---------- 2012-06-14 18:00:00 : 신사우동   5307 ----------


 ---------- 2012-06-15 00:00:00 : 강남동   5308 ----------


 ---------- 2012-06-15 08:00:00 : 동내면   5309 ----------


 ---------- 2012-06-15 12:00:00 : 석사동   5310 ----------


 ---------- 2012-06-15 12:00:00 : 퇴계동   5312 ----------


 ---------- 2012-06-15 14:00:00 : 동내면   5313 ----------


 ---------- 2012-06-15 14:00:00 : 남산면   5314 ----------


 ---------- 2012-06-15 15:00:00 : 석사동   5315 ----------


 ---------- 2012-06-15 15:00:00 : 사북면   5316 ----------


 ---------- 2012-06-15 16:00:00 : 근화동   5317 ----------


 ---------- 2012-06-15 20:00:00 : 후평1동   5318 ----------


 ---------- 2012-06-16 13:00:00 : 동내면   5319 ----------


 ---------- 2012-06-16 13:00:00 : 남산면   5320 ----------


 ---------- 2012-06-16 16:00:00 : 서  면   5321 ----------


 ---------- 2012-06-16 17:00:00 : 퇴계동   5322 ----------


 ---------- 2012-06-16 19:00:00 : 신북읍   5323 ----------


 ---------- 2012-06-17 07:00:00 : 효자1동   5325 ----------


 ---------- 2012-06-17 12:00:00 : 효자1동   5326 ----------


 ---------- 2012-06-17 13:00:00 : 북산면   5327 ----------


 ---------- 2012-06-17 14:00:00 : 신동면   5330 ----------


 ---------- 2012-06-17 15:00:00 : 근화동   5331 ----------


 ---------- 2012-06-17 17:00:00 : 석사동   5333 ----------


 ---------- 2012-06-18 09:00:00 : 남산면   5335 ----------


 ---------- 2012-06-18 14:00:00 : 남산면   5337 ----------


 ---------- 2012-06-19 01:00:00 : 사북면   5338 ----------


 ---------- 2012-06-19 01:00:00 : 효자1동   5339 ----------


 ---------- 2012-06-19 10:00:00 : 석사동   5340 ----------


 ---------- 2012-06-19 17:00:00 : 동내면   5341 ----------


 ---------- 2012-06-19 22:00:00 : 퇴계동   5343 ----------


 ---------- 2012-06-20 01:00:00 : 강남동   5344 ----------


 ---------- 2012-06-20 01:00:00 : 교  동   5345 ----------


 ---------- 2012-06-20 10:00:00 : 석사동   5346 ----------


 ---------- 2012-06-20 13:00:00 : 남산면   5348 ----------


 ---------- 2012-06-20 13:00:00 : 신사우동   5350 ----------


 ---------- 2012-06-20 14:00:00 : 남  면   5351 ----------


 ---------- 2012-06-20 14:00:00 : 남산면   5352 ----------


 ---------- 2012-06-20 14:00:00 : 동  면   5353 ----------


 ---------- 2012-06-20 16:00:00 : 후평1동   5354 ----------


 ---------- 2012-06-20 18:00:00 : 동  면   5356 ----------


 ---------- 2012-06-20 21:00:00 : 소양동   5357 ----------


 ---------- 2012-06-21 00:00:00 : 후평1동   5358 ----------


 ---------- 2012-06-21 01:00:00 : 신북읍   5359 ----------


 ---------- 2012-06-21 02:00:00 : 남산면   5361 ----------


 ---------- 2012-06-21 08:00:00 : 석사동   5362 ----------


 ---------- 2012-06-21 09:00:00 : 동  면   5363 ----------


 ---------- 2012-06-21 11:00:00 : 약사명동   5365 ----------


 ---------- 2012-06-21 11:00:00 : 퇴계동   5366 ----------


 ---------- 2012-06-21 12:00:00 : 북산면   5368 ----------


 ---------- 2012-06-21 13:00:00 : 효자1동   5369 ----------


 ---------- 2012-06-21 14:00:00 : 후평1동   5370 ----------


 ---------- 2012-06-21 17:00:00 : 후평1동   5371 ----------


 ---------- 2012-06-21 18:00:00 : 북산면   5372 ----------


 ---------- 2012-06-22 02:00:00 : 신북읍   5373 ----------


 ---------- 2012-06-22 09:00:00 : 후평1동   5376 ----------


 ---------- 2012-06-22 11:00:00 : 남산면   5377 ----------


 ---------- 2012-06-22 17:00:00 : 강남동   5379 ----------


 ---------- 2012-06-22 18:00:00 : 남산면   5381 ----------


 ---------- 2012-06-22 19:00:00 : 서  면   5382 ----------


 ---------- 2012-06-23 10:00:00 : 석사동   5384 ----------


 ---------- 2012-06-23 13:00:00 : 남산면   5385 ----------


 ---------- 2012-06-23 13:00:00 : 후평1동   5386 ----------


 ---------- 2012-06-23 14:00:00 : 석사동   5387 ----------


 ---------- 2012-06-23 14:00:00 : 신북읍   5388 ----------


 ---------- 2012-06-23 18:00:00 : 동  면   5389 ----------


 ---------- 2012-06-23 22:00:00 : 석사동   5390 ----------


 ---------- 2012-06-23 22:00:00 : 퇴계동   5391 ----------


 ---------- 2012-06-23 23:00:00 : 사북면   5392 ----------


 ---------- 2012-06-24 09:00:00 : 석사동   5393 ----------


 ---------- 2012-06-24 09:00:00 : 사북면   5394 ----------


 ---------- 2012-06-24 09:00:00 : 신북읍   5395 ----------

 ---------- 2012-06-24 10:00:00 : 북산면   5396 ----------


 ---------- 2012-06-24 12:00:00 : 사북면   5397 ----------


 ---------- 2012-06-24 15:00:00 : 서  면   5398 ----------


 ---------- 2012-06-24 17:00:00 : 퇴계동   5399 ----------


 ---------- 2012-06-24 21:00:00 : 후평1동   5400 ----------


 ---------- 2012-06-24 22:00:00 : 동  면   5401 ----------


 ---------- 2012-06-24 23:00:00 : 조운동   5402 ----------


 ---------- 2012-06-25 06:00:00 : 후평1동   5405 ----------


 ---------- 2012-06-25 10:00:00 : 석사동   5406 ----------


 ---------- 2012-06-25 13:00:00 : 동내면   5407 ----------


 ---------- 2012-06-25 13:00:00 : 남산면   5409 ----------


 ---------- 2012-06-25 13:00:00 : 후평1동   5410 ----------


 ---------- 2012-06-25 14:00:00 : 퇴계동   5411 ----------


 ---------- 2012-06-25 15:00:00 : 서  면   5412 ----------


 ---------- 2012-06-25 19:00:00 : 동내면   5413 ----------


 ---------- 2012-06-26 09:00:00 : 남산면   5414 ----------


 ---------- 2012-06-26 11:00:00 : 동내면   5415 ----------


 ---------- 2012-06-26 11:00:00 : 동산면   5416 ----------


 ---------- 2012-06-26 12:00:00 : 후평1동   5417 ----------


 ---------- 2012-06-26 13:00:00 : 석사동   5418 ----------


 ---------- 2012-06-26 13:00:00 : 남산면   5419 ----------


 ---------- 2012-06-26 16:00:00 : 후평1동   5420 ----------


 ---------- 2012-06-26 17:00:00 : 동내면   5421 ----------


 ---------- 2012-06-26 17:00:00 : 후평1동   5422 ----------


 ---------- 2012-06-26 19:00:00 : 동내면   5423 ----------


 ---------- 2012-06-26 23:00:00 : 석사동   5424 ----------


 ---------- 2012-06-27 01:00:00 : 효자1동   5426 ----------


 ---------- 2012-06-27 01:00:00 : 동  면   5427 ----------


 ---------- 2012-06-27 05:00:00 : 남산면   5428 ----------


 ---------- 2012-06-27 07:00:00 : 효자1동   5429 ----------


 ---------- 2012-06-27 12:00:00 : 석사동   5430 ----------


 ---------- 2012-06-27 12:00:00 : 동  면   5431 ----------


 ---------- 2012-06-27 15:00:00 : 동산면   5432 ----------


 ---------- 2012-06-27 17:00:00 : 후평1동   5433 ----------


 ---------- 2012-06-27 18:00:00 : 석사동   5434 ----------


 ---------- 2012-06-28 05:00:00 : 신북읍   5435 ----------


 ---------- 2012-06-28 09:00:00 : 서  면   5437 ----------


 ---------- 2012-06-28 10:00:00 : 남산면   5438 ----------


 ---------- 2012-06-28 12:00:00 : 남  면   5439 ----------


 ---------- 2012-06-28 13:00:00 : 서  면   5440 ----------


 ---------- 2012-06-28 14:00:00 : 남산면   5441 ----------


 ---------- 2012-06-28 14:00:00 : 조운동   5442 ----------


 ---------- 2012-06-28 15:00:00 : 남산면   5443 ----------


 ---------- 2012-06-28 15:00:00 : 약사명동   5444 ----------


 ---------- 2012-06-28 16:00:00 : 퇴계동   5445 ----------


 ---------- 2012-06-28 18:00:00 : 조운동   5446 ----------


 ---------- 2012-06-29 02:00:00 : 퇴계동   5447 ----------


 ---------- 2012-06-29 08:00:00 : 근화동   5448 ----------


 ---------- 2012-06-29 09:00:00 : 강남동   5450 ----------


 ---------- 2012-06-29 10:00:00 : 서  면   5451 ----------


 ---------- 2012-06-29 13:00:00 : 동내면   5452 ----------


 ---------- 2012-06-29 15:00:00 : 동산면   5453 ----------


 ---------- 2012-06-29 16:00:00 : 남산면   5454 ----------


 ---------- 2012-06-29 16:00:00 : 후평1동   5455 ----------


 ---------- 2012-06-29 18:00:00 : 사북면   5456 ----------


 ---------- 2012-06-29 23:00:00 : 남산면   5457 ----------


 ---------- 2012-06-30 10:00:00 : 후평1동   5458 ----------


 ---------- 2012-06-30 13:00:00 : 후평1동   5459 ----------


 ---------- 2012-06-30 14:00:00 : 신동면   5460 ----------


 ---------- 2012-06-30 14:00:00 : 남산면   5461 ----------


 ---------- 2012-06-30 19:00:00 : 동산면   5462 ----------


 ---------- 2012-06-30 21:00:00 : 근화동   5463 ----------


 ---------- 2012-06-30 21:00:00 : 후평1동   5464 ----------


 ---------- 2012-07-01 02:00:00 : 남산면   5465 ----------


 ---------- 2012-07-01 03:00:00 : 동산면   5466 ----------


 ---------- 2012-07-01 06:00:00 : 근화동   5468 ----------


 ---------- 2012-07-01 09:00:00 : 남산면   5469 ----------


 ---------- 2012-07-01 09:00:00 : 신사우동   5470 ----------


 ---------- 2012-07-01 12:00:00 : 강남동   5471 ----------


 ---------- 2012-07-01 13:00:00 : 강남동   5473 ----------


 ---------- 2012-07-01 13:00:00 : 소양동   5474 ----------


 ---------- 2012-07-01 14:00:00 : 강남동   5475 ----------


 ---------- 2012-07-01 14:00:00 : 동내면   5476 ----------


 ---------- 2012-07-01 14:00:00 : 동산면   5477 ----------


 ---------- 2012-07-01 15:00:00 : 퇴계동   5478 ----------


 ---------- 2012-07-01 16:00:00 : 신동면   5480 ----------


 ---------- 2012-07-01 16:00:00 : 소양동   5481 ----------


 ---------- 2012-07-01 16:00:00 : 퇴계동   5482 ----------


 ---------- 2012-07-01 17:00:00 : 남산면   5483 ----------


 ---------- 2012-07-01 19:00:00 : 효자1동   5484 ----------


 ---------- 2012-07-01 20:00:00 : 신북읍   5485 ----------


 ---------- 2012-07-01 23:00:00 : 근화동   5486 ----------


 ---------- 2012-07-02 09:00:00 : 남산면   5488 ----------


 ---------- 2012-07-02 11:00:00 : 효자1동   5489 ----------


 ---------- 2012-07-02 13:00:00 : 사북면   5490 ----------


 ---------- 2012-07-02 13:00:00 : 동내면   5491 ----------


 ---------- 2012-07-02 14:00:00 : 소양동   5492 ----------


 ---------- 2012-07-02 14:00:00 : 동산면   5493 ----------


 ---------- 2012-07-02 15:00:00 : 신사우동   5494 ----------


 ---------- 2012-07-02 16:00:00 : 효자1동   5495 ----------


 ---------- 2012-07-02 17:00:00 : 신사우동   5496 ----------


 ---------- 2012-07-02 18:00:00 : 약사명동   5497 ----------


 ---------- 2012-07-03 09:00:00 : 신동면   5498 ----------


 ---------- 2012-07-03 09:00:00 : 강남동   5499 ----------


 ---------- 2012-07-03 09:00:00 : 사북면   5500 ----------


 ---------- 2012-07-03 09:00:00 : 동  면   5501 ----------


 ---------- 2012-07-03 09:00:00 : 후평1동   5502 ----------


 ---------- 2012-07-03 11:00:00 : 강남동   5503 ----------


 ---------- 2012-07-03 12:00:00 : 소양동   5504 ----------


 ---------- 2012-07-03 13:00:00 : 강남동   5505 ----------


 ---------- 2012-07-03 13:00:00 : 남산면   5506 ----------


 ---------- 2012-07-03 14:00:00 : 남산면   5507 ----------


 ---------- 2012-07-03 14:00:00 : 신북읍   5508 ----------


 ---------- 2012-07-03 16:00:00 : 석사동   5509 ----------


 ---------- 2012-07-03 17:00:00 : 동내면   5510 ----------


 ---------- 2012-07-03 17:00:00 : 후평1동   5511 ----------


 ---------- 2012-07-03 20:00:00 : 근화동   5512 ----------


 ---------- 2012-07-04 00:00:00 : 효자1동   5514 ----------


 ---------- 2012-07-04 09:00:00 : 남  면   5515 ----------


 ---------- 2012-07-04 09:00:00 : 근화동   5516 ----------


 ---------- 2012-07-04 10:00:00 : 서  면   5517 ----------


 ---------- 2012-07-04 12:00:00 : 석사동   5518 ----------


 ---------- 2012-07-04 14:00:00 : 신사우동   5519 ----------


 ---------- 2012-07-04 15:00:00 : 퇴계동   5520 ----------


 ---------- 2012-07-04 18:00:00 : 석사동   5521 ----------


 ---------- 2012-07-04 22:00:00 : 효자1동   5522 ----------


 ---------- 2012-07-05 10:00:00 : 근화동   5523 ----------


 ---------- 2012-07-05 10:00:00 : 후평1동   5525 ----------


 ---------- 2012-07-05 11:00:00 : 사북면   5527 ----------


 ---------- 2012-07-05 13:00:00 : 강남동   5528 ----------


 ---------- 2012-07-05 14:00:00 : 남산면   5529 ----------


 ---------- 2012-07-05 14:00:00 : 후평1동   5530 ----------


 ---------- 2012-07-05 15:00:00 : 서  면   5531 ----------


 ---------- 2012-07-05 15:00:00 : 남산면   5532 ----------


 ---------- 2012-07-05 15:00:00 : 신북읍   5534 ----------


 ---------- 2012-07-05 16:00:00 : 남산면   5535 ----------


 ---------- 2012-07-05 16:00:00 : 신사우동   5536 ----------


 ---------- 2012-07-05 16:00:00 : 퇴계동   5537 ----------


 ---------- 2012-07-05 17:00:00 : 퇴계동   5538 ----------


 ---------- 2012-07-05 19:00:00 : 강남동   5539 ----------


 ---------- 2012-07-05 23:00:00 : 효자1동   5540 ----------


 ---------- 2012-07-06 08:00:00 : 신동면   5542 ----------


 ---------- 2012-07-06 09:00:00 : 석사동   5543 ----------


 ---------- 2012-07-06 10:00:00 : 동  면   5544 ----------


 ---------- 2012-07-06 11:00:00 : 남산면   5546 ----------


 ---------- 2012-07-06 14:00:00 : 후평1동   5547 ----------


 ---------- 2012-07-06 15:00:00 : 신사우동   5548 ----------


 ---------- 2012-07-06 15:00:00 : 동산면   5550 ----------


 ---------- 2012-07-06 17:00:00 : 후평1동   5551 ----------

 ---------- 2012-07-06 21:00:00 : 근화동   5552 ----------


 ---------- 2012-07-06 23:00:00 : 후평1동   5553 ----------


 ---------- 2012-07-07 03:00:00 : 서  면   5554 ----------


 ---------- 2012-07-07 09:00:00 : 사북면   5555 ----------


 ---------- 2012-07-07 09:00:00 : 남산면   5556 ----------


 ---------- 2012-07-07 10:00:00 : 후평1동   5558 ----------


 ---------- 2012-07-07 10:00:00 : 퇴계동   5559 ----------


 ---------- 2012-07-07 11:00:00 : 동내면   5561 ----------


 ---------- 2012-07-07 11:00:00 : 남산면   5563 ----------


 ---------- 2012-07-07 11:00:00 : 동  면   5564 ----------


 ---------- 2012-07-07 12:00:00 : 후평1동   5565 ----------


 ---------- 2012-07-07 13:00:00 : 사북면   5566 ----------


 ---------- 2012-07-07 13:00:00 : 남산면   5567 ----------


 ---------- 2012-07-07 15:00:00 : 남산면   5568 ----------


 ---------- 2012-07-07 15:00:00 : 소양동   5569 ----------


 ---------- 2012-07-07 15:00:00 : 퇴계동   5570 ----------


 ---------- 2012-07-07 16:00:00 : 동내면   5571 ----------


 ---------- 2012-07-07 17:00:00 : 퇴계동   5572 ----------


 ---------- 2012-07-07 18:00:00 : 동내면   5573 ----------


 ---------- 2012-07-07 18:00:00 : 퇴계동   5574 ----------


 ---------- 2012-07-07 21:00:00 : 동내면   5575 ----------


 ---------- 2012-07-08 03:00:00 : 남산면   5576 ----------


 ---------- 2012-07-08 10:00:00 : 석사동   5577 ----------


 ---------- 2012-07-08 10:00:00 : 남산면   5578 ----------


 ---------- 2012-07-08 11:00:00 : 서  면   5581 ----------


 ---------- 2012-07-08 11:00:00 : 북산면   5582 ----------


 ---------- 2012-07-08 12:00:00 : 소양동   5583 ----------


 ---------- 2012-07-08 12:00:00 : 동  면   5584 ----------


 ---------- 2012-07-08 13:00:00 : 소양동   5585 ----------


 ---------- 2012-07-08 14:00:00 : 강남동   5587 ----------


 ---------- 2012-07-08 14:00:00 : 남산면   5588 ----------


 ---------- 2012-07-08 15:00:00 : 석사동   5589 ----------


 ---------- 2012-07-08 17:00:00 : 남산면   5590 ----------


 ---------- 2012-07-08 18:00:00 : 효자1동   5591 ----------


 ---------- 2012-07-08 18:00:00 : 동  면   5592 ----------


 ---------- 2012-07-09 01:00:00 : 석사동   5593 ----------


 ---------- 2012-07-09 01:00:00 : 퇴계동   5594 ----------


 ---------- 2012-07-09 05:00:00 : 소양동   5596 ----------


 ---------- 2012-07-09 09:00:00 : 석사동   5597 ----------


 ---------- 2012-07-09 09:00:00 : 강남동   5598 ----------


 ---------- 2012-07-09 09:00:00 : 신사우동   5600 ----------


 ---------- 2012-07-09 09:00:00 : 동  면   5601 ----------


 ---------- 2012-07-09 10:00:00 : 강남동   5602 ----------


 ---------- 2012-07-09 13:00:00 : 서  면   5603 ----------


 ---------- 2012-07-09 13:00:00 : 남산면   5604 ----------


 ---------- 2012-07-09 14:00:00 : 강남동   5605 ----------


 ---------- 2012-07-09 14:00:00 : 서  면   5606 ----------


 ---------- 2012-07-09 15:00:00 : 석사동   5607 ----------


 ---------- 2012-07-09 16:00:00 : 퇴계동   5608 ----------


 ---------- 2012-07-09 17:00:00 : 동내면   5609 ----------


 ---------- 2012-07-09 17:00:00 : 교  동   5610 ----------


 ---------- 2012-07-09 18:00:00 : 후평1동   5611 ----------


 ---------- 2012-07-09 22:00:00 : 퇴계동   5612 ----------


 ---------- 2012-07-09 23:00:00 : 동내면   5613 ----------


 ---------- 2012-07-09 23:00:00 : 퇴계동   5614 ----------


 ---------- 2012-07-10 08:00:00 : 퇴계동   5615 ----------


 ---------- 2012-07-10 08:00:00 : 북산면   5616 ----------


 ---------- 2012-07-10 09:00:00 : 후평1동   5617 ----------


 ---------- 2012-07-10 10:00:00 : 신북읍   5618 ----------


 ---------- 2012-07-10 10:00:00 : 후평1동   5619 ----------


 ---------- 2012-07-10 10:00:00 : 북산면   5620 ----------


 ---------- 2012-07-10 12:00:00 : 소양동   5621 ----------


 ---------- 2012-07-10 13:00:00 : 동  면   5622 ----------


 ---------- 2012-07-10 13:00:00 : 퇴계동   5623 ----------


 ---------- 2012-07-10 15:00:00 : 효자1동   5624 ----------


 ---------- 2012-07-10 16:00:00 : 석사동   5625 ----------


 ---------- 2012-07-10 18:00:00 : 사북면   5626 ----------


 ---------- 2012-07-10 18:00:00 : 후평1동   5627 ----------


 ---------- 2012-07-11 10:00:00 : 후평1동   5628 ----------


 ---------- 2012-07-11 14:00:00 : 신사우동   5629 ----------


 ---------- 2012-07-11 16:00:00 : 동  면   5630 ----------


 ---------- 2012-07-11 17:00:00 : 남산면   5631 ----------


 ---------- 2012-07-11 19:00:00 : 후평1동   5632 ----------


 ---------- 2012-07-12 08:00:00 : 신사우동   5633 ----------


 ---------- 2012-07-12 08:00:00 : 동산면   5634 ----------


 ---------- 2012-07-12 09:00:00 : 강남동   5635 ----------


 ---------- 2012-07-12 09:00:00 : 동내면   5638 ----------


 ---------- 2012-07-12 09:00:00 : 근화동   5639 ----------


 ---------- 2012-07-12 10:00:00 : 강남동   5640 ----------


 ---------- 2012-07-12 11:00:00 : 사북면   5641 ----------


 ---------- 2012-07-12 14:00:00 : 퇴계동   5642 ----------


 ---------- 2012-07-12 16:00:00 : 남산면   5643 ----------


 ---------- 2012-07-12 18:00:00 : 남  면   5644 ----------


 ---------- 2012-07-12 18:00:00 : 남산면   5645 ----------


 ---------- 2012-07-13 09:00:00 : 강남동   5646 ----------


 ---------- 2012-07-13 10:00:00 : 석사동   5647 ----------


 ---------- 2012-07-13 10:00:00 : 사북면   5648 ----------


 ---------- 2012-07-13 10:00:00 : 남산면   5649 ----------


 ---------- 2012-07-13 12:00:00 : 석사동   5651 ----------


 ---------- 2012-07-13 12:00:00 : 동내면   5652 ----------


 ---------- 2012-07-13 12:00:00 : 소양동   5653 ----------


 ---------- 2012-07-13 13:00:00 : 남산면   5654 ----------


 ---------- 2012-07-13 14:00:00 : 남  면   5655 ----------


 ---------- 2012-07-13 14:00:00 : 사북면   5656 ----------


 ---------- 2012-07-13 14:00:00 : 효자1동   5658 ----------


 ---------- 2012-07-13 16:00:00 : 소양동   5659 ----------


 ---------- 2012-07-13 17:00:00 : 강남동   5660 ----------


 ---------- 2012-07-13 19:00:00 : 후평1동   5661 ----------


 ---------- 2012-07-14 09:00:00 : 동내면   5662 ----------


 ---------- 2012-07-14 09:00:00 : 퇴계동   5663 ----------


 ---------- 2012-07-14 10:00:00 : 강남동   5664 ----------


 ---------- 2012-07-14 10:00:00 : 사북면   5665 ----------


 ---------- 2012-07-14 10:00:00 : 동내면   5666 ----------


 ---------- 2012-07-14 11:00:00 : 남산면   5667 ----------


 ---------- 2012-07-14 13:00:00 : 퇴계동   5668 ----------


 ---------- 2012-07-14 15:00:00 : 동  면   5669 ----------


 ---------- 2012-07-14 15:00:00 : 퇴계동   5670 ----------


 ---------- 2012-07-14 16:00:00 : 퇴계동   5671 ----------


 ---------- 2012-07-14 17:00:00 : 신북읍   5672 ----------


 ---------- 2012-07-15 02:00:00 : 석사동   5673 ----------


 ---------- 2012-07-15 07:00:00 : 남  면   5674 ----------


 ---------- 2012-07-15 11:00:00 : 서  면   5676 ----------


 ---------- 2012-07-15 11:00:00 : 동산면   5677 ----------


 ---------- 2012-07-15 13:00:00 : 효자1동   5678 ----------


 ---------- 2012-07-15 13:00:00 : 후평1동   5679 ----------


 ---------- 2012-07-15 13:00:00 : 퇴계동   5680 ----------


 ---------- 2012-07-15 15:00:00 : 석사동   5681 ----------


 ---------- 2012-07-15 15:00:00 : 신동면   5682 ----------


 ---------- 2012-07-15 15:00:00 : 서  면   5683 ----------


 ---------- 2012-07-15 16:00:00 : 석사동   5684 ----------


 ---------- 2012-07-15 18:00:00 : 퇴계동   5685 ----------


 ---------- 2012-07-15 19:00:00 : 동  면   5686 ----------


 ---------- 2012-07-16 06:00:00 : 남산면   5688 ----------


 ---------- 2012-07-16 09:00:00 : 효자1동   5689 ----------


 ---------- 2012-07-16 10:00:00 : 석사동   5690 ----------


 ---------- 2012-07-16 10:00:00 : 신동면   5692 ----------


 ---------- 2012-07-16 10:00:00 : 남산면   5693 ----------


 ---------- 2012-07-16 10:00:00 : 후평1동   5694 ----------


 ---------- 2012-07-16 13:00:00 : 사북면   5695 ----------


 ---------- 2012-07-16 13:00:00 : 남산면   5696 ----------


 ---------- 2012-07-16 14:00:00 : 강남동   5698 ----------


 ---------- 2012-07-16 15:00:00 : 신동면   5699 ----------


 ---------- 2012-07-16 15:00:00 : 퇴계동   5700 ----------


 ---------- 2012-07-16 16:00:00 : 남산면   5701 ----------


 ---------- 2012-07-16 17:00:00 : 퇴계동   5702 ----------


 ---------- 2012-07-16 18:00:00 : 석사동   5703 ----------


 ---------- 2012-07-16 21:00:00 : 퇴계동   5704 ----------


 ---------- 2012-07-17 07:00:00 : 동  면   5705 ----------


 ---------- 2012-07-17 08:00:00 : 서  면   5706 ----------

 ---------- 2012-07-17 09:00:00 : 동내면   5707 ----------


 ---------- 2012-07-17 09:00:00 : 퇴계동   5708 ----------


 ---------- 2012-07-17 10:00:00 : 근화동   5709 ----------


 ---------- 2012-07-17 10:00:00 : 소양동   5710 ----------


 ---------- 2012-07-17 10:00:00 : 약사명동   5711 ----------


 ---------- 2012-07-17 11:00:00 : 퇴계동   5712 ----------


 ---------- 2012-07-17 13:00:00 : 신북읍   5713 ----------


 ---------- 2012-07-17 13:00:00 : 후평1동   5714 ----------


 ---------- 2012-07-17 14:00:00 : 석사동   5715 ----------


 ---------- 2012-07-17 14:00:00 : 남산면   5716 ----------


 ---------- 2012-07-17 15:00:00 : 효자1동   5717 ----------


 ---------- 2012-07-17 16:00:00 : 신동면   5718 ----------


 ---------- 2012-07-17 16:00:00 : 신사우동   5719 ----------


 ---------- 2012-07-17 16:00:00 : 동  면   5720 ----------


 ---------- 2012-07-17 17:00:00 : 신사우동   5721 ----------


 ---------- 2012-07-17 19:00:00 : 석사동   5722 ----------


 ---------- 2012-07-17 20:00:00 : 남산면   5723 ----------


 ---------- 2012-07-18 00:00:00 : 근화동   5724 ----------


 ---------- 2012-07-18 09:00:00 : 동내면   5725 ----------


 ---------- 2012-07-18 09:00:00 : 소양동   5726 ----------


 ---------- 2012-07-18 10:00:00 : 효자1동   5727 ----------


 ---------- 2012-07-18 10:00:00 : 신사우동   5728 ----------


 ---------- 2012-07-18 11:00:00 : 퇴계동   5729 ----------


 ---------- 2012-07-18 12:00:00 : 동내면   5730 ----------


 ---------- 2012-07-18 12:00:00 : 남산면   5731 ----------


 ---------- 2012-07-18 13:00:00 : 동내면   5732 ----------


 ---------- 2012-07-18 13:00:00 : 신사우동   5733 ----------


 ---------- 2012-07-18 13:00:00 : 소양동   5734 ----------


 ---------- 2012-07-18 14:00:00 : 석사동   5735 ----------


 ---------- 2012-07-18 14:00:00 : 강남동   5736 ----------


 ---------- 2012-07-18 14:00:00 : 서  면   5737 ----------


 ---------- 2012-07-18 14:00:00 : 동내면   5738 ----------


 ---------- 2012-07-18 15:00:00 : 동  면   5739 ----------


 ---------- 2012-07-18 22:00:00 : 사북면   5740 ----------


 ---------- 2012-07-19 00:00:00 : 약사명동   5741 ----------


 ---------- 2012-07-19 01:00:00 : 효자1동   5742 ----------


 ---------- 2012-07-19 04:00:00 : 효자1동   5744 ----------


 ---------- 2012-07-19 06:00:00 : 석사동   5745 ----------


 ---------- 2012-07-19 10:00:00 : 남산면   5746 ----------


 ---------- 2012-07-19 10:00:00 : 소양동   5747 ----------


 ---------- 2012-07-19 11:00:00 : 동산면   5748 ----------


 ---------- 2012-07-19 12:00:00 : 후평1동   5749 ----------


 ---------- 2012-07-19 13:00:00 : 남산면   5750 ----------


 ---------- 2012-07-19 13:00:00 : 소양동   5751 ----------


 ---------- 2012-07-19 15:00:00 : 동내면   5752 ----------


 ---------- 2012-07-19 15:00:00 : 소양동   5753 ----------


 ---------- 2012-07-19 15:00:00 : 조운동   5754 ----------


 ---------- 2012-07-19 17:00:00 : 강남동   5755 ----------


 ---------- 2012-07-19 23:00:00 : 퇴계동   5756 ----------


 ---------- 2012-07-20 04:00:00 : 남산면   5758 ----------


 ---------- 2012-07-20 08:00:00 : 남산면   5760 ----------


 ---------- 2012-07-20 09:00:00 : 서  면   5761 ----------


 ---------- 2012-07-20 09:00:00 : 사북면   5762 ----------


 ---------- 2012-07-20 09:00:00 : 근화동   5763 ----------


 ---------- 2012-07-20 10:00:00 : 서  면   5764 ----------


 ---------- 2012-07-20 10:00:00 : 근화동   5765 ----------


 ---------- 2012-07-20 11:00:00 : 서  면   5766 ----------


 ---------- 2012-07-20 11:00:00 : 효자1동   5767 ----------


 ---------- 2012-07-20 12:00:00 : 강남동   5768 ----------


 ---------- 2012-07-20 12:00:00 : 후평1동   5770 ----------


 ---------- 2012-07-20 13:00:00 : 강남동   5771 ----------


 ---------- 2012-07-20 13:00:00 : 서  면   5772 ----------


 ---------- 2012-07-20 13:00:00 : 퇴계동   5773 ----------


 ---------- 2012-07-20 14:00:00 : 신사우동   5774 ----------


 ---------- 2012-07-20 15:00:00 : 남  면   5775 ----------


 ---------- 2012-07-20 15:00:00 : 후평1동   5776 ----------


 ---------- 2012-07-20 16:00:00 : 효자1동   5777 ----------


 ---------- 2012-07-20 16:00:00 : 남산면   5778 ----------


 ---------- 2012-07-20 16:00:00 : 동산면   5779 ----------


 ---------- 2012-07-20 17:00:00 : 남산면   5780 ----------


 ---------- 2012-07-20 18:00:00 : 서  면   5781 ----------


 ---------- 2012-07-20 21:00:00 : 후평1동   5782 ----------


 ---------- 2012-07-21 08:00:00 : 근화동   5783 ----------


 ---------- 2012-07-21 08:00:00 : 조운동   5784 ----------


 ---------- 2012-07-21 08:00:00 : 동산면   5785 ----------


 ---------- 2012-07-21 09:00:00 : 신동면   5786 ----------


 ---------- 2012-07-21 09:00:00 : 남산면   5787 ----------


 ---------- 2012-07-21 10:00:00 : 서  면   5788 ----------


 ---------- 2012-07-21 10:00:00 : 퇴계동   5789 ----------


 ---------- 2012-07-21 12:00:00 : 강남동   5790 ----------


 ---------- 2012-07-21 12:00:00 : 남산면   5791 ----------


 ---------- 2012-07-21 13:00:00 : 신동면   5792 ----------


 ---------- 2012-07-21 13:00:00 : 소양동   5794 ----------


 ---------- 2012-07-21 14:00:00 : 퇴계동   5795 ----------


 ---------- 2012-07-21 15:00:00 : 신북읍   5796 ----------


 ---------- 2012-07-21 16:00:00 : 동내면   5797 ----------


 ---------- 2012-07-21 16:00:00 : 남산면   5798 ----------


 ---------- 2012-07-21 16:00:00 : 신북읍   5799 ----------


 ---------- 2012-07-21 19:00:00 : 조운동   5800 ----------


 ---------- 2012-07-22 02:00:00 : 신사우동   5802 ----------


 ---------- 2012-07-22 02:00:00 : 후평1동   5803 ----------


 ---------- 2012-07-22 06:00:00 : 서  면   5804 ----------


 ---------- 2012-07-22 08:00:00 : 남산면   5805 ----------


 ---------- 2012-07-22 08:00:00 : 동산면   5806 ----------


 ---------- 2012-07-22 09:00:00 : 사북면   5807 ----------


 ---------- 2012-07-22 11:00:00 : 사북면   5808 ----------


 ---------- 2012-07-22 15:00:00 : 남산면   5809 ----------


 ---------- 2012-07-22 16:00:00 : 신사우동   5810 ----------


 ---------- 2012-07-22 18:00:00 : 후평1동   5811 ----------


 ---------- 2012-07-23 08:00:00 : 서  면   5812 ----------


 ---------- 2012-07-23 08:00:00 : 사북면   5813 ----------


 ---------- 2012-07-23 09:00:00 : 강남동   5814 ----------


 ---------- 2012-07-23 09:00:00 : 동내면   5815 ----------


 ---------- 2012-07-23 09:00:00 : 신북읍   5816 ----------


 ---------- 2012-07-23 10:00:00 : 강남동   5819 ----------


 ---------- 2012-07-23 10:00:00 : 근화동   5820 ----------


 ---------- 2012-07-23 12:00:00 : 동  면   5821 ----------


 ---------- 2012-07-23 13:00:00 : 동내면   5822 ----------


 ---------- 2012-07-23 13:00:00 : 남산면   5823 ----------


 ---------- 2012-07-23 13:00:00 : 근화동   5824 ----------


 ---------- 2012-07-23 14:00:00 : 후평1동   5825 ----------


 ---------- 2012-07-23 15:00:00 : 남산면   5826 ----------


 ---------- 2012-07-23 15:00:00 : 신사우동   5827 ----------


 ---------- 2012-07-23 15:00:00 : 후평1동   5828 ----------


 ---------- 2012-07-23 15:00:00 : 퇴계동   5829 ----------


 ---------- 2012-07-23 16:00:00 : 신북읍   5830 ----------


 ---------- 2012-07-23 18:00:00 : 동내면   5831 ----------


 ---------- 2012-07-23 19:00:00 : 서  면   5832 ----------


 ---------- 2012-07-23 21:00:00 : 퇴계동   5833 ----------


 ---------- 2012-07-24 08:00:00 : 남  면   5834 ----------


 ---------- 2012-07-24 09:00:00 : 사북면   5835 ----------


 ---------- 2012-07-24 10:00:00 : 서  면   5836 ----------


 ---------- 2012-07-24 11:00:00 : 동내면   5837 ----------


 ---------- 2012-07-24 11:00:00 : 남산면   5838 ----------


 ---------- 2012-07-24 12:00:00 : 근화동   5839 ----------


 ---------- 2012-07-24 12:00:00 : 동  면   5840 ----------


 ---------- 2012-07-24 12:00:00 : 후평1동   5841 ----------


 ---------- 2012-07-24 13:00:00 : 후평1동   5842 ----------


 ---------- 2012-07-24 14:00:00 : 신사우동   5843 ----------


 ---------- 2012-07-24 15:00:00 : 후평1동   5844 ----------


 ---------- 2012-07-24 16:00:00 : 동  면   5845 ----------


 ---------- 2012-07-24 17:00:00 : 후평1동   5846 ----------


 ---------- 2012-07-24 19:00:00 : 효자1동   5847 ----------


 ---------- 2012-07-25 09:00:00 : 남  면   5848 ----------


 ---------- 2012-07-25 10:00:00 : 동  면   5849 ----------


 ---------- 2012-07-25 10:00:00 : 퇴계동   5850 ----------


 ---------- 2012-07-25 11:00:00 : 북산면   5852 ----------


 ---------- 2012-07-25 12:00:00 : 동내면   5853 ----------

 ---------- 2012-07-25 13:00:00 : 남산면   5854 ----------


 ---------- 2012-07-25 13:00:00 : 동  면   5855 ----------


 ---------- 2012-07-25 13:00:00 : 후평1동   5856 ----------


 ---------- 2012-07-25 13:00:00 : 조운동   5857 ----------


 ---------- 2012-07-25 14:00:00 : 남산면   5858 ----------


 ---------- 2012-07-25 14:00:00 : 근화동   5859 ----------


 ---------- 2012-07-25 14:00:00 : 신사우동   5860 ----------


 ---------- 2012-07-25 15:00:00 : 강남동   5861 ----------


 ---------- 2012-07-25 15:00:00 : 효자1동   5862 ----------


 ---------- 2012-07-25 15:00:00 : 북산면   5863 ----------


 ---------- 2012-07-25 16:00:00 : 신동면   5864 ----------


 ---------- 2012-07-25 16:00:00 : 신사우동   5865 ----------


 ---------- 2012-07-25 16:00:00 : 동산면   5866 ----------


 ---------- 2012-07-25 17:00:00 : 석사동   5867 ----------


 ---------- 2012-07-25 17:00:00 : 남  면   5868 ----------


 ---------- 2012-07-25 17:00:00 : 효자1동   5869 ----------


 ---------- 2012-07-25 18:00:00 : 서  면   5871 ----------


 ---------- 2012-07-26 07:00:00 : 신동면   5872 ----------


 ---------- 2012-07-26 07:00:00 : 서  면   5873 ----------


 ---------- 2012-07-26 09:00:00 : 강남동   5874 ----------


 ---------- 2012-07-26 09:00:00 : 남산면   5875 ----------


 ---------- 2012-07-26 10:00:00 : 신동면   5876 ----------


 ---------- 2012-07-26 11:00:00 : 신동면   5877 ----------


 ---------- 2012-07-26 12:00:00 : 조운동   5878 ----------


 ---------- 2012-07-26 13:00:00 : 신동면   5879 ----------


 ---------- 2012-07-26 14:00:00 : 효자1동   5880 ----------


 ---------- 2012-07-26 14:00:00 : 남산면   5881 ----------


 ---------- 2012-07-26 14:00:00 : 북산면   5882 ----------


 ---------- 2012-07-26 15:00:00 : 석사동   5883 ----------


 ---------- 2012-07-26 15:00:00 : 남  면   5884 ----------


 ---------- 2012-07-26 17:00:00 : 석사동   5885 ----------


 ---------- 2012-07-26 17:00:00 : 동  면   5886 ----------


 ---------- 2012-07-26 17:00:00 : 교  동   5887 ----------


 ---------- 2012-07-26 18:00:00 : 후평1동   5888 ----------


 ---------- 2012-07-26 23:00:00 : 신북읍   5889 ----------


 ---------- 2012-07-27 01:00:00 : 동내면   5890 ----------


 ---------- 2012-07-27 01:00:00 : 남산면   5892 ----------


 ---------- 2012-07-27 08:00:00 : 강남동   5893 ----------


 ---------- 2012-07-27 09:00:00 : 신동면   5894 ----------


 ---------- 2012-07-27 09:00:00 : 강남동   5896 ----------


 ---------- 2012-07-27 10:00:00 : 남산면   5897 ----------


 ---------- 2012-07-27 10:00:00 : 동  면   5898 ----------


 ---------- 2012-07-27 10:00:00 : 동산면   5899 ----------


 ---------- 2012-07-27 11:00:00 : 남산면   5900 ----------


 ---------- 2012-07-27 12:00:00 : 강남동   5901 ----------


 ---------- 2012-07-27 12:00:00 : 효자1동   5902 ----------


 ---------- 2012-07-27 12:00:00 : 신사우동   5903 ----------


 ---------- 2012-07-27 13:00:00 : 강남동   5904 ----------


 ---------- 2012-07-27 13:00:00 : 남산면   5905 ----------


 ---------- 2012-07-27 13:00:00 : 신북읍   5906 ----------


 ---------- 2012-07-27 13:00:00 : 동  면   5907 ----------


 ---------- 2012-07-27 14:00:00 : 석사동   5908 ----------


 ---------- 2012-07-27 14:00:00 : 신동면   5910 ----------


 ---------- 2012-07-27 14:00:00 : 강남동   5912 ----------


 ---------- 2012-07-27 14:00:00 : 남산면   5913 ----------


 ---------- 2012-07-27 15:00:00 : 석사동   5914 ----------


 ---------- 2012-07-27 15:00:00 : 신동면   5915 ----------


 ---------- 2012-07-27 15:00:00 : 남  면   5916 ----------


 ---------- 2012-07-27 15:00:00 : 동산면   5917 ----------


 ---------- 2012-07-27 16:00:00 : 동내면   5918 ----------


 ---------- 2012-07-27 17:00:00 : 석사동   5919 ----------


 ---------- 2012-07-27 18:00:00 : 남산면   5920 ----------


 ---------- 2012-07-27 19:00:00 : 동내면   5921 ----------


 ---------- 2012-07-27 23:00:00 : 석사동   5922 ----------


 ---------- 2012-07-28 00:00:00 : 동내면   5923 ----------


 ---------- 2012-07-28 07:00:00 : 석사동   5924 ----------


 ---------- 2012-07-28 07:00:00 : 후평1동   5925 ----------


 ---------- 2012-07-28 08:00:00 : 서  면   5926 ----------


 ---------- 2012-07-28 08:00:00 : 남산면   5927 ----------


 ---------- 2012-07-28 08:00:00 : 소양동   5928 ----------


 ---------- 2012-07-28 09:00:00 : 강남동   5929 ----------


 ---------- 2012-07-28 09:00:00 : 서  면   5930 ----------


 ---------- 2012-07-28 09:00:00 : 효자1동   5932 ----------


 ---------- 2012-07-28 09:00:00 : 교  동   5933 ----------


 ---------- 2012-07-28 10:00:00 : 석사동   5934 ----------


 ---------- 2012-07-28 10:00:00 : 강남동   5936 ----------


 ---------- 2012-07-28 10:00:00 : 동  면   5937 ----------


 ---------- 2012-07-28 11:00:00 : 남  면   5938 ----------


 ---------- 2012-07-28 11:00:00 : 효자1동   5939 ----------


 ---------- 2012-07-28 11:00:00 : 동산면   5940 ----------


 ---------- 2012-07-28 12:00:00 : 사북면   5941 ----------


 ---------- 2012-07-28 13:00:00 : 서  면   5943 ----------


 ---------- 2012-07-28 13:00:00 : 남  면   5944 ----------


 ---------- 2012-07-28 13:00:00 : 남산면   5945 ----------


 ---------- 2012-07-28 13:00:00 : 신사우동   5946 ----------


 ---------- 2012-07-28 13:00:00 : 북산면   5949 ----------


 ---------- 2012-07-28 14:00:00 : 소양동   5950 ----------


 ---------- 2012-07-28 14:00:00 : 동산면   5951 ----------


 ---------- 2012-07-28 15:00:00 : 석사동   5952 ----------


 ---------- 2012-07-28 16:00:00 : 후평1동   5953 ----------


 ---------- 2012-07-28 17:00:00 : 신동면   5954 ----------


 ---------- 2012-07-28 17:00:00 : 서  면   5955 ----------


 ---------- 2012-07-29 08:00:00 : 후평1동   5956 ----------


 ---------- 2012-07-29 10:00:00 : 석사동   5957 ----------


 ---------- 2012-07-29 10:00:00 : 사북면   5958 ----------


 ---------- 2012-07-29 10:00:00 : 교  동   5959 ----------


 ---------- 2012-07-29 11:00:00 : 강남동   5961 ----------


 ---------- 2012-07-29 11:00:00 : 남  면   5962 ----------


 ---------- 2012-07-29 11:00:00 : 신사우동   5963 ----------


 ---------- 2012-07-29 13:00:00 : 사북면   5964 ----------


 ---------- 2012-07-29 13:00:00 : 동산면   5965 ----------


 ---------- 2012-07-29 14:00:00 : 퇴계동   5966 ----------


 ---------- 2012-07-29 15:00:00 : 신사우동   5967 ----------


 ---------- 2012-07-29 16:00:00 : 후평1동   5968 ----------


 ---------- 2012-07-29 19:00:00 : 후평1동   5969 ----------


 ---------- 2012-07-29 20:00:00 : 신사우동   5970 ----------


 ---------- 2012-07-30 08:00:00 : 서  면   5972 ----------


 ---------- 2012-07-30 09:00:00 : 사북면   5973 ----------


 ---------- 2012-07-30 09:00:00 : 동내면   5974 ----------


 ---------- 2012-07-30 09:00:00 : 소양동   5975 ----------


 ---------- 2012-07-30 09:00:00 : 퇴계동   5976 ----------


 ---------- 2012-07-30 09:00:00 : 동산면   5977 ----------


 ---------- 2012-07-30 10:00:00 : 석사동   5978 ----------


 ---------- 2012-07-30 10:00:00 : 사북면   5979 ----------


 ---------- 2012-07-30 10:00:00 : 동  면   5980 ----------


 ---------- 2012-07-30 10:00:00 : 후평1동   5981 ----------


 ---------- 2012-07-30 11:00:00 : 석사동   5982 ----------


 ---------- 2012-07-30 11:00:00 : 신동면   5983 ----------


 ---------- 2012-07-30 12:00:00 : 효자1동   5984 ----------


 ---------- 2012-07-30 12:00:00 : 조운동   5985 ----------


 ---------- 2012-07-30 13:00:00 : 서  면   5986 ----------


 ---------- 2012-07-30 13:00:00 : 남  면   5987 ----------


 ---------- 2012-07-30 13:00:00 : 후평1동   5988 ----------


 ---------- 2012-07-30 14:00:00 : 서  면   5989 ----------


 ---------- 2012-07-30 14:00:00 : 남산면   5990 ----------


 ---------- 2012-07-30 14:00:00 : 퇴계동   5991 ----------


 ---------- 2012-07-30 15:00:00 : 남산면   5992 ----------


 ---------- 2012-07-30 15:00:00 : 동  면   5993 ----------


 ---------- 2012-07-30 16:00:00 : 남  면   5994 ----------


 ---------- 2012-07-30 18:00:00 : 사북면   5995 ----------


 ---------- 2012-07-30 20:00:00 : 조운동   5996 ----------


 ---------- 2012-07-30 23:00:00 : 퇴계동   5998 ----------


 ---------- 2012-07-31 01:00:00 : 동  면   5999 ----------


 ---------- 2012-07-31 02:00:00 : 석사동   6000 ----------


 ---------- 2012-07-31 08:00:00 : 서  면   6001 ----------


 ---------- 2012-07-31 09:00:00 : 사북면   6002 ----------


 ---------- 2012-07-31 09:00:00 : 남산면   6003 ----------


 ---------- 2012-07-31 09:00:00 : 동  면   6004 ----------

 ---------- 2012-07-31 10:00:00 : 서  면   6005 ----------


 ---------- 2012-07-31 10:00:00 : 사북면   6006 ----------


 ---------- 2012-07-31 10:00:00 : 근화동   6007 ----------


 ---------- 2012-07-31 10:00:00 : 신사우동   6008 ----------


 ---------- 2012-07-31 10:00:00 : 동  면   6010 ----------


 ---------- 2012-07-31 10:00:00 : 후평1동   6011 ----------


 ---------- 2012-07-31 11:00:00 : 남산면   6012 ----------


 ---------- 2012-07-31 12:00:00 : 효자1동   6013 ----------


 ---------- 2012-07-31 12:00:00 : 신사우동   6014 ----------


 ---------- 2012-07-31 12:00:00 : 퇴계동   6016 ----------


 ---------- 2012-07-31 13:00:00 : 동내면   6017 ----------


 ---------- 2012-07-31 14:00:00 : 사북면   6018 ----------


 ---------- 2012-07-31 14:00:00 : 남산면   6019 ----------


 ---------- 2012-07-31 14:00:00 : 근화동   6020 ----------


 ---------- 2012-07-31 14:00:00 : 신사우동   6021 ----------


 ---------- 2012-07-31 15:00:00 : 동내면   6022 ----------


 ---------- 2012-07-31 15:00:00 : 효자1동   6023 ----------


 ---------- 2012-07-31 15:00:00 : 교  동   6024 ----------


 ---------- 2012-07-31 16:00:00 : 서  면   6025 ----------


 ---------- 2012-07-31 18:00:00 : 신동면   6026 ----------


 ---------- 2012-08-01 02:00:00 : 효자1동   6027 ----------


 ---------- 2012-08-01 09:00:00 : 석사동   6028 ----------


 ---------- 2012-08-01 09:00:00 : 사북면   6029 ----------


 ---------- 2012-08-01 09:00:00 : 동내면   6030 ----------


 ---------- 2012-08-01 09:00:00 : 신북읍   6031 ----------


 ---------- 2012-08-01 10:00:00 : 서  면   6032 ----------


 ---------- 2012-08-01 10:00:00 : 동  면   6033 ----------


 ---------- 2012-08-01 11:00:00 : 동내면   6035 ----------


 ---------- 2012-08-01 11:00:00 : 신사우동   6036 ----------


 ---------- 2012-08-01 12:00:00 : 남산면   6037 ----------


 ---------- 2012-08-01 12:00:00 : 동산면   6038 ----------


 ---------- 2012-08-01 14:00:00 : 강남동   6039 ----------


 ---------- 2012-08-01 14:00:00 : 남산면   6040 ----------


 ---------- 2012-08-01 14:00:00 : 후평1동   6042 ----------


 ---------- 2012-08-01 15:00:00 : 소양동   6043 ----------


 ---------- 2012-08-01 15:00:00 : 동  면   6045 ----------


 ---------- 2012-08-01 15:00:00 : 후평1동   6046 ----------


 ---------- 2012-08-01 15:00:00 : 조운동   6047 ----------


 ---------- 2012-08-01 16:00:00 : 석사동   6048 ----------


 ---------- 2012-08-01 16:00:00 : 서  면   6050 ----------


 ---------- 2012-08-01 18:00:00 : 동산면   6051 ----------


 ---------- 2012-08-01 21:00:00 : 신북읍   6052 ----------


 ---------- 2012-08-02 00:00:00 : 강남동   6054 ----------


 ---------- 2012-08-02 01:00:00 : 석사동   6055 ----------


 ---------- 2012-08-02 09:00:00 : 남산면   6057 ----------


 ---------- 2012-08-02 09:00:00 : 신사우동   6058 ----------


 ---------- 2012-08-02 09:00:00 : 약사명동   6059 ----------


 ---------- 2012-08-02 09:00:00 : 동산면   6060 ----------


 ---------- 2012-08-02 10:00:00 : 동  면   6061 ----------


 ---------- 2012-08-02 11:00:00 : 효자1동   6062 ----------


 ---------- 2012-08-02 11:00:00 : 후평1동   6063 ----------


 ---------- 2012-08-02 13:00:00 : 사북면   6064 ----------


 ---------- 2012-08-02 13:00:00 : 신사우동   6066 ----------


 ---------- 2012-08-02 13:00:00 : 소양동   6067 ----------


 ---------- 2012-08-02 14:00:00 : 사북면   6068 ----------


 ---------- 2012-08-02 14:00:00 : 남산면   6069 ----------


 ---------- 2012-08-02 14:00:00 : 근화동   6070 ----------


 ---------- 2012-08-02 15:00:00 : 효자1동   6071 ----------


 ---------- 2012-08-02 15:00:00 : 남산면   6072 ----------


 ---------- 2012-08-02 16:00:00 : 석사동   6073 ----------


 ---------- 2012-08-02 16:00:00 : 퇴계동   6074 ----------


 ---------- 2012-08-02 17:00:00 : 남산면   6075 ----------


 ---------- 2012-08-02 17:00:00 : 후평1동   6076 ----------


 ---------- 2012-08-02 17:00:00 : 퇴계동   6077 ----------


 ---------- 2012-08-02 18:00:00 : 동  면   6078 ----------


 ---------- 2012-08-03 01:00:00 : 동내면   6079 ----------


 ---------- 2012-08-03 07:00:00 : 신사우동   6080 ----------


 ---------- 2012-08-03 08:00:00 : 석사동   6081 ----------


 ---------- 2012-08-03 08:00:00 : 소양동   6082 ----------


 ---------- 2012-08-03 09:00:00 : 석사동   6084 ----------


 ---------- 2012-08-03 09:00:00 : 사북면   6085 ----------


 ---------- 2012-08-03 09:00:00 : 동내면   6086 ----------


 ---------- 2012-08-03 09:00:00 : 남산면   6087 ----------


 ---------- 2012-08-03 09:00:00 : 신사우동   6088 ----------


 ---------- 2012-08-03 09:00:00 : 북산면   6089 ----------


 ---------- 2012-08-03 10:00:00 : 남산면   6090 ----------


 ---------- 2012-08-03 10:00:00 : 동  면   6091 ----------


 ---------- 2012-08-03 11:00:00 : 동내면   6092 ----------


 ---------- 2012-08-03 13:00:00 : 남산면   6094 ----------


 ---------- 2012-08-03 13:00:00 : 신사우동   6095 ----------


 ---------- 2012-08-03 13:00:00 : 소양동   6096 ----------


 ---------- 2012-08-03 13:00:00 : 동산면   6097 ----------


 ---------- 2012-08-03 14:00:00 : 강남동   6098 ----------


 ---------- 2012-08-03 16:00:00 : 효자1동   6099 ----------


 ---------- 2012-08-03 16:00:00 : 후평1동   6101 ----------


 ---------- 2012-08-03 16:00:00 : 동산면   6102 ----------


 ---------- 2012-08-03 17:00:00 : 서  면   6103 ----------


 ---------- 2012-08-03 18:00:00 : 신북읍   6104 ----------


 ---------- 2012-08-03 19:00:00 : 동  면   6105 ----------


 ---------- 2012-08-03 23:00:00 : 퇴계동   6106 ----------


 ---------- 2012-08-04 04:00:00 : 남산면   6107 ----------


 ---------- 2012-08-04 08:00:00 : 소양동   6108 ----------


 ---------- 2012-08-04 09:00:00 : 강남동   6109 ----------


 ---------- 2012-08-04 09:00:00 : 근화동   6110 ----------


 ---------- 2012-08-04 10:00:00 : 석사동   6111 ----------


 ---------- 2012-08-04 10:00:00 : 서  면   6112 ----------


 ---------- 2012-08-04 10:00:00 : 남산면   6113 ----------


 ---------- 2012-08-04 10:00:00 : 북산면   6115 ----------


 ---------- 2012-08-04 10:00:00 : 동산면   6116 ----------


 ---------- 2012-08-04 13:00:00 : 신동면   6117 ----------


 ---------- 2012-08-04 13:00:00 : 남산면   6118 ----------


 ---------- 2012-08-04 13:00:00 : 신북읍   6119 ----------


 ---------- 2012-08-04 13:00:00 : 약사명동   6120 ----------


 ---------- 2012-08-04 15:00:00 : 강남동   6121 ----------


 ---------- 2012-08-04 15:00:00 : 남산면   6124 ----------


 ---------- 2012-08-04 15:00:00 : 후평1동   6125 ----------


 ---------- 2012-08-04 18:00:00 : 동내면   6126 ----------


 ---------- 2012-08-04 19:00:00 : 남산면   6127 ----------


 ---------- 2012-08-04 23:00:00 : 신동면   6128 ----------


 ---------- 2012-08-05 01:00:00 : 석사동   6129 ----------


 ---------- 2012-08-05 07:00:00 : 석사동   6130 ----------


 ---------- 2012-08-05 09:00:00 : 서  면   6131 ----------


 ---------- 2012-08-05 10:00:00 : 강남동   6132 ----------


 ---------- 2012-08-05 10:00:00 : 사북면   6133 ----------


 ---------- 2012-08-05 10:00:00 : 동  면   6134 ----------


 ---------- 2012-08-05 10:00:00 : 퇴계동   6135 ----------


 ---------- 2012-08-05 12:00:00 : 신북읍   6136 ----------


 ---------- 2012-08-05 13:00:00 : 서  면   6137 ----------


 ---------- 2012-08-05 13:00:00 : 사북면   6138 ----------


 ---------- 2012-08-05 13:00:00 : 동내면   6139 ----------


 ---------- 2012-08-05 13:00:00 : 퇴계동   6140 ----------


 ---------- 2012-08-05 14:00:00 : 석사동   6141 ----------


 ---------- 2012-08-05 14:00:00 : 동산면   6142 ----------


 ---------- 2012-08-05 15:00:00 : 교  동   6143 ----------


 ---------- 2012-08-05 16:00:00 : 서  면   6144 ----------


 ---------- 2012-08-06 09:00:00 : 석사동   6145 ----------


 ---------- 2012-08-06 09:00:00 : 강남동   6146 ----------


 ---------- 2012-08-06 09:00:00 : 효자1동   6147 ----------


 ---------- 2012-08-06 09:00:00 : 남산면   6149 ----------


 ---------- 2012-08-06 10:00:00 : 석사동   6150 ----------


 ---------- 2012-08-06 10:00:00 : 사북면   6151 ----------


 ---------- 2012-08-06 10:00:00 : 동산면   6152 ----------


 ---------- 2012-08-06 11:00:00 : 남산면   6153 ----------


 ---------- 2012-08-06 11:00:00 : 조운동   6154 ----------


 ---------- 2012-08-06 13:00:00 : 신동면   6155 ----------


 ---------- 2012-08-06 13:00:00 : 사북면   6156 ----------


 ---------- 2012-08-06 13:00:00 : 신북읍   6157 ----------


 ---------- 2012-08-06 13:00:00 : 동  면   6159 ----------


 ---------- 2012-08-06 14:00:00 : 석사동   6160 ----------


 ---------- 2012-08-06 14:00:00 : 사북면   6161 ----------

 ---------- 2012-08-06 14:00:00 : 동내면   6162 ----------


 ---------- 2012-08-06 14:00:00 : 남산면   6163 ----------


 ---------- 2012-08-06 14:00:00 : 동  면   6164 ----------


 ---------- 2012-08-06 14:00:00 : 후평1동   6165 ----------


 ---------- 2012-08-06 15:00:00 : 남  면   6166 ----------


 ---------- 2012-08-06 15:00:00 : 동산면   6167 ----------


 ---------- 2012-08-06 16:00:00 : 남산면   6168 ----------


 ---------- 2012-08-06 17:00:00 : 강남동   6169 ----------


 ---------- 2012-08-06 17:00:00 : 효자1동   6170 ----------


 ---------- 2012-08-06 17:00:00 : 남산면   6171 ----------


 ---------- 2012-08-06 17:00:00 : 동  면   6172 ----------


 ---------- 2012-08-06 18:00:00 : 동  면   6173 ----------


 ---------- 2012-08-06 18:00:00 : 후평1동   6174 ----------


 ---------- 2012-08-06 21:00:00 : 근화동   6175 ----------


 ---------- 2012-08-06 21:00:00 : 퇴계동   6177 ----------


 ---------- 2012-08-07 09:00:00 : 남  면   6178 ----------


 ---------- 2012-08-07 09:00:00 : 사북면   6179 ----------


 ---------- 2012-08-07 09:00:00 : 동내면   6181 ----------


 ---------- 2012-08-07 10:00:00 : 서  면   6182 ----------


 ---------- 2012-08-07 10:00:00 : 사북면   6183 ----------


 ---------- 2012-08-07 10:00:00 : 효자1동   6184 ----------


 ---------- 2012-08-07 10:00:00 : 남산면   6185 ----------


 ---------- 2012-08-07 10:00:00 : 퇴계동   6186 ----------


 ---------- 2012-08-07 12:00:00 : 서  면   6187 ----------


 ---------- 2012-08-07 13:00:00 : 강남동   6189 ----------


 ---------- 2012-08-07 13:00:00 : 서  면   6190 ----------


 ---------- 2012-08-07 13:00:00 : 동내면   6191 ----------


 ---------- 2012-08-07 13:00:00 : 근화동   6193 ----------


 ---------- 2012-08-07 13:00:00 : 후평1동   6194 ----------


 ---------- 2012-08-07 13:00:00 : 퇴계동   6195 ----------


 ---------- 2012-08-07 14:00:00 : 동내면   6196 ----------


 ---------- 2012-08-07 14:00:00 : 신북읍   6197 ----------


 ---------- 2012-08-07 14:00:00 : 동산면   6198 ----------


 ---------- 2012-08-07 15:00:00 : 석사동   6199 ----------


 ---------- 2012-08-07 15:00:00 : 신북읍   6200 ----------


 ---------- 2012-08-07 16:00:00 : 조운동   6201 ----------


 ---------- 2012-08-07 17:00:00 : 동  면   6202 ----------


 ---------- 2012-08-07 17:00:00 : 후평1동   6203 ----------


 ---------- 2012-08-07 18:00:00 : 소양동   6204 ----------


 ---------- 2012-08-07 18:00:00 : 동  면   6205 ----------


 ---------- 2012-08-07 18:00:00 : 조운동   6206 ----------


 ---------- 2012-08-07 19:00:00 : 동  면   6207 ----------


 ---------- 2012-08-07 20:00:00 : 후평1동   6208 ----------


 ---------- 2012-08-07 21:00:00 : 효자1동   6209 ----------


 ---------- 2012-08-08 02:00:00 : 신북읍   6210 ----------


 ---------- 2012-08-08 07:00:00 : 석사동   6211 ----------


 ---------- 2012-08-08 09:00:00 : 석사동   6213 ----------


 ---------- 2012-08-08 09:00:00 : 서  면   6214 ----------


 ---------- 2012-08-08 09:00:00 : 동내면   6215 ----------


 ---------- 2012-08-08 09:00:00 : 효자1동   6216 ----------


 ---------- 2012-08-08 09:00:00 : 소양동   6217 ----------


 ---------- 2012-08-08 09:00:00 : 동  면   6218 ----------


 ---------- 2012-08-08 09:00:00 : 후평1동   6219 ----------


 ---------- 2012-08-08 10:00:00 : 남산면   6220 ----------


 ---------- 2012-08-08 10:00:00 : 동  면   6221 ----------


 ---------- 2012-08-08 10:00:00 : 후평1동   6222 ----------


 ---------- 2012-08-08 10:00:00 : 퇴계동   6224 ----------


 ---------- 2012-08-08 13:00:00 : 강남동   6225 ----------


 ---------- 2012-08-08 13:00:00 : 효자1동   6226 ----------


 ---------- 2012-08-08 13:00:00 : 남산면   6227 ----------


 ---------- 2012-08-08 13:00:00 : 동  면   6229 ----------


 ---------- 2012-08-08 14:00:00 : 신동면   6230 ----------


 ---------- 2012-08-08 15:00:00 : 동산면   6231 ----------


 ---------- 2012-08-08 16:00:00 : 신사우동   6232 ----------


 ---------- 2012-08-08 17:00:00 : 퇴계동   6233 ----------


 ---------- 2012-08-08 18:00:00 : 동내면   6234 ----------


 ---------- 2012-08-09 02:00:00 : 근화동   6236 ----------


 ---------- 2012-08-09 05:00:00 : 후평1동   6237 ----------


 ---------- 2012-08-09 06:00:00 : 근화동   6238 ----------


 ---------- 2012-08-09 09:00:00 : 신북읍   6239 ----------


 ---------- 2012-08-09 09:00:00 : 교  동   6240 ----------


 ---------- 2012-08-09 10:00:00 : 서  면   6241 ----------


 ---------- 2012-08-09 11:00:00 : 교  동   6242 ----------


 ---------- 2012-08-09 13:00:00 : 신동면   6243 ----------


 ---------- 2012-08-09 13:00:00 : 남산면   6246 ----------


 ---------- 2012-08-09 14:00:00 : 사북면   6247 ----------


 ---------- 2012-08-09 14:00:00 : 효자1동   6248 ----------


 ---------- 2012-08-09 14:00:00 : 소양동   6249 ----------


 ---------- 2012-08-09 15:00:00 : 동내면   6250 ----------


 ---------- 2012-08-09 16:00:00 : 강남동   6251 ----------


 ---------- 2012-08-09 16:00:00 : 서  면   6252 ----------


 ---------- 2012-08-09 17:00:00 : 후평1동   6253 ----------


 ---------- 2012-08-09 18:00:00 : 사북면   6255 ----------


 ---------- 2012-08-09 18:00:00 : 남산면   6256 ----------


 ---------- 2012-08-09 20:00:00 : 후평1동   6257 ----------


 ---------- 2012-08-10 08:00:00 : 신동면   6258 ----------


 ---------- 2012-08-10 09:00:00 : 서  면   6259 ----------


 ---------- 2012-08-10 09:00:00 : 소양동   6260 ----------


 ---------- 2012-08-10 10:00:00 : 신사우동   6261 ----------


 ---------- 2012-08-10 11:00:00 : 남  면   6262 ----------


 ---------- 2012-08-10 13:00:00 : 서  면   6263 ----------


 ---------- 2012-08-10 13:00:00 : 퇴계동   6264 ----------


 ---------- 2012-08-10 13:00:00 : 북산면   6265 ----------


 ---------- 2012-08-10 14:00:00 : 신동면   6266 ----------


 ---------- 2012-08-10 14:00:00 : 서  면   6267 ----------


 ---------- 2012-08-10 14:00:00 : 효자1동   6268 ----------


 ---------- 2012-08-10 16:00:00 : 조운동   6269 ----------


 ---------- 2012-08-10 18:00:00 : 퇴계동   6270 ----------


 ---------- 2012-08-10 19:00:00 : 남산면   6271 ----------


 ---------- 2012-08-10 19:00:00 : 후평1동   6272 ----------


 ---------- 2012-08-10 20:00:00 : 동  면   6273 ----------


 ---------- 2012-08-10 22:00:00 : 퇴계동   6274 ----------


 ---------- 2012-08-11 06:00:00 : 근화동   6275 ----------


 ---------- 2012-08-11 08:00:00 : 서  면   6276 ----------


 ---------- 2012-08-11 08:00:00 : 신사우동   6277 ----------


 ---------- 2012-08-11 09:00:00 : 신동면   6278 ----------


 ---------- 2012-08-11 09:00:00 : 약사명동   6279 ----------


 ---------- 2012-08-11 10:00:00 : 석사동   6280 ----------


 ---------- 2012-08-11 10:00:00 : 신북읍   6281 ----------


 ---------- 2012-08-11 11:00:00 : 동내면   6282 ----------


 ---------- 2012-08-11 11:00:00 : 퇴계동   6283 ----------


 ---------- 2012-08-11 12:00:00 : 신동면   6284 ----------


 ---------- 2012-08-11 13:00:00 : 근화동   6285 ----------


 ---------- 2012-08-11 14:00:00 : 신동면   6286 ----------


 ---------- 2012-08-11 14:00:00 : 남산면   6287 ----------


 ---------- 2012-08-11 16:00:00 : 신동면   6288 ----------


 ---------- 2012-08-11 16:00:00 : 강남동   6289 ----------


 ---------- 2012-08-11 16:00:00 : 남산면   6290 ----------


 ---------- 2012-08-11 18:00:00 : 동  면   6291 ----------


 ---------- 2012-08-11 18:00:00 : 퇴계동   6292 ----------


 ---------- 2012-08-12 08:00:00 : 신동면   6293 ----------


 ---------- 2012-08-12 09:00:00 : 석사동   6294 ----------


 ---------- 2012-08-12 09:00:00 : 서  면   6295 ----------


 ---------- 2012-08-12 10:00:00 : 신동면   6296 ----------


 ---------- 2012-08-12 11:00:00 : 남  면   6298 ----------


 ---------- 2012-08-12 11:00:00 : 남산면   6299 ----------


 ---------- 2012-08-12 12:00:00 : 석사동   6300 ----------


 ---------- 2012-08-12 12:00:00 : 서  면   6301 ----------


 ---------- 2012-08-12 13:00:00 : 근화동   6302 ----------


 ---------- 2012-08-12 13:00:00 : 퇴계동   6303 ----------


 ---------- 2012-08-12 15:00:00 : 석사동   6304 ----------


 ---------- 2012-08-12 20:00:00 : 근화동   6307 ----------


 ---------- 2012-08-12 22:00:00 : 남산면   6308 ----------


 ---------- 2012-08-13 09:00:00 : 석사동   6310 ----------


 ---------- 2012-08-13 09:00:00 : 남산면   6311 ----------


 ---------- 2012-08-13 09:00:00 : 후평1동   6312 ----------


 ---------- 2012-08-13 11:00:00 : 석사동   6313 ----------


 ---------- 2012-08-13 13:00:00 : 신사우동   6314 ----------


 ---------- 2012-08-13 13:00:00 : 동  면   6315 ----------

 ---------- 2012-08-13 14:00:00 : 후평1동   6316 ----------


 ---------- 2012-08-13 14:00:00 : 퇴계동   6317 ----------


 ---------- 2012-08-13 15:00:00 : 신동면   6318 ----------


 ---------- 2012-08-13 15:00:00 : 퇴계동   6319 ----------


 ---------- 2012-08-13 16:00:00 : 서  면   6320 ----------


 ---------- 2012-08-13 17:00:00 : 약사명동   6321 ----------


 ---------- 2012-08-13 18:00:00 : 강남동   6322 ----------


 ---------- 2012-08-13 18:00:00 : 후평1동   6324 ----------


 ---------- 2012-08-14 11:00:00 : 후평1동   6325 ----------


 ---------- 2012-08-14 12:00:00 : 석사동   6326 ----------


 ---------- 2012-08-14 12:00:00 : 동산면   6327 ----------


 ---------- 2012-08-14 13:00:00 : 남산면   6328 ----------


 ---------- 2012-08-14 13:00:00 : 신사우동   6329 ----------


 ---------- 2012-08-14 13:00:00 : 신북읍   6330 ----------


 ---------- 2012-08-14 13:00:00 : 퇴계동   6331 ----------


 ---------- 2012-08-14 14:00:00 : 남산면   6332 ----------


 ---------- 2012-08-14 15:00:00 : 신사우동   6334 ----------


 ---------- 2012-08-14 16:00:00 : 퇴계동   6335 ----------


 ---------- 2012-08-14 17:00:00 : 사북면   6336 ----------


 ---------- 2012-08-14 18:00:00 : 석사동   6337 ----------


 ---------- 2012-08-14 21:00:00 : 강남동   6338 ----------


 ---------- 2012-08-14 23:00:00 : 근화동   6339 ----------


 ---------- 2012-08-15 10:00:00 : 남산면   6340 ----------


 ---------- 2012-08-15 11:00:00 : 동  면   6341 ----------


 ---------- 2012-08-15 12:00:00 : 신사우동   6342 ----------


 ---------- 2012-08-15 13:00:00 : 남산면   6347 ----------


 ---------- 2012-08-15 19:00:00 : 약사명동   6348 ----------


 ---------- 2012-08-15 19:00:00 : 후평1동   6349 ----------


 ---------- 2012-08-15 22:00:00 : 서  면   6350 ----------


 ---------- 2012-08-16 09:00:00 : 서  면   6351 ----------


 ---------- 2012-08-16 09:00:00 : 동내면   6353 ----------


 ---------- 2012-08-16 09:00:00 : 후평1동   6354 ----------


 ---------- 2012-08-16 10:00:00 : 사북면   6355 ----------


 ---------- 2012-08-16 12:00:00 : 교  동   6356 ----------


 ---------- 2012-08-16 13:00:00 : 강남동   6357 ----------


 ---------- 2012-08-16 13:00:00 : 동내면   6358 ----------


 ---------- 2012-08-16 13:00:00 : 퇴계동   6359 ----------


 ---------- 2012-08-16 14:00:00 : 후평1동   6360 ----------


 ---------- 2012-08-16 15:00:00 : 후평1동   6361 ----------


 ---------- 2012-08-16 15:00:00 : 퇴계동   6362 ----------


 ---------- 2012-08-16 16:00:00 : 서  면   6363 ----------


 ---------- 2012-08-16 16:00:00 : 동  면   6364 ----------


 ---------- 2012-08-16 16:00:00 : 조운동   6365 ----------


 ---------- 2012-08-16 18:00:00 : 강남동   6366 ----------


 ---------- 2012-08-16 19:00:00 : 강남동   6368 ----------


 ---------- 2012-08-17 02:00:00 : 동산면   6369 ----------


 ---------- 2012-08-17 06:00:00 : 동산면   6370 ----------


 ---------- 2012-08-17 09:00:00 : 석사동   6372 ----------


 ---------- 2012-08-17 09:00:00 : 동  면   6373 ----------


 ---------- 2012-08-17 10:00:00 : 근화동   6374 ----------


 ---------- 2012-08-17 10:00:00 : 북산면   6375 ----------


 ---------- 2012-08-17 12:00:00 : 강남동   6376 ----------


 ---------- 2012-08-17 12:00:00 : 남산면   6377 ----------


 ---------- 2012-08-17 13:00:00 : 남  면   6378 ----------


 ---------- 2012-08-17 14:00:00 : 근화동   6379 ----------


 ---------- 2012-08-17 15:00:00 : 신동면   6380 ----------


 ---------- 2012-08-17 15:00:00 : 사북면   6381 ----------


 ---------- 2012-08-17 15:00:00 : 동내면   6382 ----------


 ---------- 2012-08-17 15:00:00 : 남산면   6383 ----------


 ---------- 2012-08-17 15:00:00 : 후평1동   6384 ----------


 ---------- 2012-08-17 16:00:00 : 석사동   6385 ----------


 ---------- 2012-08-17 16:00:00 : 동내면   6386 ----------


 ---------- 2012-08-17 16:00:00 : 후평1동   6388 ----------


 ---------- 2012-08-17 19:00:00 : 소양동   6389 ----------


 ---------- 2012-08-17 23:00:00 : 퇴계동   6390 ----------


 ---------- 2012-08-18 08:00:00 : 석사동   6391 ----------


 ---------- 2012-08-18 08:00:00 : 효자1동   6392 ----------


 ---------- 2012-08-18 09:00:00 : 신동면   6393 ----------


 ---------- 2012-08-18 09:00:00 : 강남동   6394 ----------


 ---------- 2012-08-18 09:00:00 : 남  면   6395 ----------


 ---------- 2012-08-18 10:00:00 : 강남동   6396 ----------


 ---------- 2012-08-18 10:00:00 : 사북면   6397 ----------


 ---------- 2012-08-18 10:00:00 : 효자1동   6398 ----------


 ---------- 2012-08-18 11:00:00 : 강남동   6399 ----------


 ---------- 2012-08-18 11:00:00 : 효자1동   6400 ----------


 ---------- 2012-08-18 12:00:00 : 서  면   6401 ----------


 ---------- 2012-08-18 12:00:00 : 신사우동   6402 ----------


 ---------- 2012-08-18 14:00:00 : 사북면   6404 ----------


 ---------- 2012-08-18 14:00:00 : 신사우동   6405 ----------


 ---------- 2012-08-18 16:00:00 : 소양동   6406 ----------


 ---------- 2012-08-18 17:00:00 : 효자1동   6407 ----------


 ---------- 2012-08-18 20:00:00 : 근화동   6409 ----------


 ---------- 2012-08-19 06:00:00 : 동산면   6410 ----------


 ---------- 2012-08-19 07:00:00 : 동산면   6411 ----------


 ---------- 2012-08-19 09:00:00 : 동내면   6412 ----------


 ---------- 2012-08-19 09:00:00 : 신사우동   6413 ----------


 ---------- 2012-08-19 12:00:00 : 신사우동   6414 ----------


 ---------- 2012-08-19 13:00:00 : 근화동   6415 ----------


 ---------- 2012-08-19 13:00:00 : 신북읍   6416 ----------


 ---------- 2012-08-19 13:00:00 : 약사명동   6417 ----------


 ---------- 2012-08-19 14:00:00 : 교  동   6418 ----------


 ---------- 2012-08-19 16:00:00 : 신동면   6419 ----------


 ---------- 2012-08-19 17:00:00 : 석사동   6420 ----------


 ---------- 2012-08-19 23:00:00 : 퇴계동   6421 ----------


 ---------- 2012-08-20 10:00:00 : 남산면   6422 ----------


 ---------- 2012-08-20 13:00:00 : 근화동   6423 ----------


 ---------- 2012-08-20 14:00:00 : 강남동   6424 ----------


 ---------- 2012-08-20 14:00:00 : 서  면   6425 ----------


 ---------- 2012-08-20 15:00:00 : 석사동   6426 ----------


 ---------- 2012-08-20 17:00:00 : 신사우동   6427 ----------


 ---------- 2012-08-20 20:00:00 : 후평1동   6428 ----------


 ---------- 2012-08-20 22:00:00 : 사북면   6429 ----------


 ---------- 2012-08-21 05:00:00 : 신사우동   6430 ----------


 ---------- 2012-08-21 09:00:00 : 동산면   6431 ----------


 ---------- 2012-08-21 10:00:00 : 석사동   6432 ----------


 ---------- 2012-08-21 12:00:00 : 신북읍   6433 ----------


 ---------- 2012-08-21 13:00:00 : 강남동   6434 ----------


 ---------- 2012-08-21 13:00:00 : 소양동   6436 ----------


 ---------- 2012-08-21 13:00:00 : 퇴계동   6438 ----------


 ---------- 2012-08-21 15:00:00 : 동내면   6439 ----------


 ---------- 2012-08-21 16:00:00 : 남산면   6442 ----------


 ---------- 2012-08-21 17:00:00 : 동  면   6443 ----------


 ---------- 2012-08-22 08:00:00 : 근화동   6444 ----------


 ---------- 2012-08-22 09:00:00 : 신동면   6445 ----------


 ---------- 2012-08-22 09:00:00 : 동  면   6446 ----------


 ---------- 2012-08-22 12:00:00 : 석사동   6447 ----------


 ---------- 2012-08-22 12:00:00 : 동  면   6448 ----------


 ---------- 2012-08-22 14:00:00 : 동산면   6449 ----------


 ---------- 2012-08-22 15:00:00 : 동내면   6450 ----------


 ---------- 2012-08-22 16:00:00 : 석사동   6451 ----------


 ---------- 2012-08-22 16:00:00 : 서  면   6452 ----------


 ---------- 2012-08-22 16:00:00 : 후평1동   6453 ----------


 ---------- 2012-08-22 16:00:00 : 동산면   6454 ----------


 ---------- 2012-08-22 20:00:00 : 남산면   6455 ----------


 ---------- 2012-08-23 09:00:00 : 사북면   6459 ----------


 ---------- 2012-08-23 10:00:00 : 남산면   6460 ----------


 ---------- 2012-08-23 10:00:00 : 신북읍   6461 ----------


 ---------- 2012-08-23 11:00:00 : 석사동   6462 ----------


 ---------- 2012-08-23 12:00:00 : 동  면   6463 ----------


 ---------- 2012-08-23 13:00:00 : 효자1동   6464 ----------


 ---------- 2012-08-23 13:00:00 : 북산면   6465 ----------


 ---------- 2012-08-23 14:00:00 : 효자1동   6466 ----------


 ---------- 2012-08-23 14:00:00 : 동  면   6467 ----------


 ---------- 2012-08-23 14:00:00 : 퇴계동   6469 ----------


 ---------- 2012-08-23 14:00:00 : 북산면   6470 ----------


 ---------- 2012-08-23 15:00:00 : 신사우동   6471 ----------


 ---------- 2012-08-23 16:00:00 : 남산면   6472 ----------


 ---------- 2012-08-23 16:00:00 : 소양동   6473 ----------


 ---------- 2012-08-23 20:00:00 : 후평1동   6474 ----------

 ---------- 2012-08-24 00:00:00 : 퇴계동   6475 ----------


 ---------- 2012-08-24 02:00:00 : 동  면   6477 ----------


 ---------- 2012-08-24 07:00:00 : 석사동   6478 ----------


 ---------- 2012-08-24 08:00:00 : 남산면   6479 ----------


 ---------- 2012-08-24 09:00:00 : 서  면   6480 ----------


 ---------- 2012-08-24 09:00:00 : 약사명동   6482 ----------


 ---------- 2012-08-24 09:00:00 : 동산면   6483 ----------


 ---------- 2012-08-24 10:00:00 : 남산면   6484 ----------


 ---------- 2012-08-24 11:00:00 : 사북면   6485 ----------


 ---------- 2012-08-24 11:00:00 : 후평1동   6486 ----------


 ---------- 2012-08-24 12:00:00 : 효자1동   6487 ----------


 ---------- 2012-08-24 12:00:00 : 근화동   6488 ----------


 ---------- 2012-08-24 13:00:00 : 효자1동   6489 ----------


 ---------- 2012-08-24 13:00:00 : 남산면   6490 ----------


 ---------- 2012-08-24 13:00:00 : 퇴계동   6491 ----------


 ---------- 2012-08-24 13:00:00 : 교  동   6493 ----------


 ---------- 2012-08-24 14:00:00 : 근화동   6494 ----------


 ---------- 2012-08-24 14:00:00 : 후평1동   6495 ----------


 ---------- 2012-08-24 15:00:00 : 강남동   6496 ----------


 ---------- 2012-08-24 15:00:00 : 신북읍   6497 ----------


 ---------- 2012-08-24 16:00:00 : 신사우동   6498 ----------


 ---------- 2012-08-24 16:00:00 : 후평1동   6499 ----------


 ---------- 2012-08-24 17:00:00 : 강남동   6500 ----------


 ---------- 2012-08-24 19:00:00 : 후평1동   6502 ----------


 ---------- 2012-08-25 07:00:00 : 남  면   6503 ----------


 ---------- 2012-08-25 11:00:00 : 석사동   6504 ----------


 ---------- 2012-08-25 13:00:00 : 석사동   6505 ----------


 ---------- 2012-08-25 13:00:00 : 사북면   6506 ----------


 ---------- 2012-08-25 13:00:00 : 퇴계동   6507 ----------


 ---------- 2012-08-25 14:00:00 : 서  면   6508 ----------


 ---------- 2012-08-25 14:00:00 : 남산면   6509 ----------


 ---------- 2012-08-25 15:00:00 : 강남동   6510 ----------


 ---------- 2012-08-25 16:00:00 : 강남동   6511 ----------


 ---------- 2012-08-25 16:00:00 : 남산면   6512 ----------


 ---------- 2012-08-25 16:00:00 : 후평1동   6513 ----------


 ---------- 2012-08-25 16:00:00 : 퇴계동   6514 ----------


 ---------- 2012-08-25 17:00:00 : 동산면   6516 ----------


 ---------- 2012-08-26 08:00:00 : 신동면   6517 ----------


 ---------- 2012-08-26 09:00:00 : 남산면   6518 ----------


 ---------- 2012-08-26 09:00:00 : 신북읍   6519 ----------


 ---------- 2012-08-26 11:00:00 : 북산면   6520 ----------


 ---------- 2012-08-26 13:00:00 : 신동면   6521 ----------


 ---------- 2012-08-26 13:00:00 : 강남동   6523 ----------


 ---------- 2012-08-26 14:00:00 : 강남동   6524 ----------


 ---------- 2012-08-26 14:00:00 : 퇴계동   6525 ----------


 ---------- 2012-08-26 17:00:00 : 강남동   6526 ----------


 ---------- 2012-08-26 21:00:00 : 서  면   6528 ----------


 ---------- 2012-08-27 04:00:00 : 석사동   6529 ----------


 ---------- 2012-08-27 06:00:00 : 퇴계동   6530 ----------


 ---------- 2012-08-27 09:00:00 : 효자1동   6531 ----------


 ---------- 2012-08-27 09:00:00 : 동산면   6532 ----------


 ---------- 2012-08-27 10:00:00 : 동내면   6534 ----------


 ---------- 2012-08-27 10:00:00 : 후평1동   6536 ----------


 ---------- 2012-08-27 11:00:00 : 신동면   6537 ----------


 ---------- 2012-08-27 11:00:00 : 조운동   6539 ----------


 ---------- 2012-08-27 13:00:00 : 사북면   6540 ----------


 ---------- 2012-08-27 13:00:00 : 남산면   6541 ----------


 ---------- 2012-08-27 13:00:00 : 퇴계동   6542 ----------


 ---------- 2012-08-27 14:00:00 : 신사우동   6544 ----------


 ---------- 2012-08-27 15:00:00 : 동내면   6545 ----------


 ---------- 2012-08-27 16:00:00 : 강남동   6546 ----------


 ---------- 2012-08-27 16:00:00 : 효자1동   6547 ----------


 ---------- 2012-08-27 17:00:00 : 근화동   6549 ----------


 ---------- 2012-08-27 17:00:00 : 동  면   6550 ----------


 ---------- 2012-08-27 18:00:00 : 신사우동   6552 ----------


 ---------- 2012-08-27 22:00:00 : 후평1동   6553 ----------


 ---------- 2012-08-28 09:00:00 : 신북읍   6554 ----------


 ---------- 2012-08-28 10:00:00 : 동내면   6556 ----------


 ---------- 2012-08-28 11:00:00 : 퇴계동   6557 ----------


 ---------- 2012-08-28 12:00:00 : 동내면   6558 ----------


 ---------- 2012-08-28 12:00:00 : 효자1동   6559 ----------


 ---------- 2012-08-28 12:00:00 : 조운동   6560 ----------


 ---------- 2012-08-28 13:00:00 : 동  면   6561 ----------


 ---------- 2012-08-28 13:00:00 : 동산면   6563 ----------


 ---------- 2012-08-28 14:00:00 : 약사명동   6564 ----------


 ---------- 2012-08-28 15:00:00 : 효자1동   6565 ----------


 ---------- 2012-08-28 16:00:00 : 석사동   6567 ----------


 ---------- 2012-08-28 16:00:00 : 동  면   6568 ----------


 ---------- 2012-08-28 16:00:00 : 후평1동   6572 ----------


 ---------- 2012-08-28 16:00:00 : 조운동   6573 ----------


 ---------- 2012-08-28 16:00:00 : 교  동   6574 ----------


 ---------- 2012-08-28 17:00:00 : 효자1동   6575 ----------


 ---------- 2012-08-28 17:00:00 : 신사우동   6576 ----------


 ---------- 2012-08-28 18:00:00 : 석사동   6577 ----------


 ---------- 2012-08-28 18:00:00 : 약사명동   6578 ----------


 ---------- 2012-08-28 20:00:00 : 서  면   6579 ----------


 ---------- 2012-08-28 21:00:00 : 석사동   6580 ----------


 ---------- 2012-08-28 21:00:00 : 효자1동   6581 ----------


 ---------- 2012-08-28 21:00:00 : 후평1동   6582 ----------


 ---------- 2012-08-28 21:00:00 : 조운동   6583 ----------


 ---------- 2012-08-28 22:00:00 : 석사동   6587 ----------


 ---------- 2012-08-28 22:00:00 : 서  면   6588 ----------


 ---------- 2012-08-28 22:00:00 : 후평1동   6590 ----------


 ---------- 2012-08-28 23:00:00 : 석사동   6592 ----------


 ---------- 2012-08-28 23:00:00 : 신동면   6593 ----------


 ---------- 2012-08-28 23:00:00 : 효자1동   6596 ----------


 ---------- 2012-08-28 23:00:00 : 약사명동   6597 ----------


 ---------- 2012-08-28 23:00:00 : 후평1동   6600 ----------


 ---------- 2012-08-28 23:00:00 : 퇴계동   6601 ----------


 ---------- 2012-08-29 09:00:00 : 남  면   6603 ----------


 ---------- 2012-08-29 09:00:00 : 신사우동   6605 ----------


 ---------- 2012-08-29 09:00:00 : 퇴계동   6606 ----------


 ---------- 2012-08-29 10:00:00 : 남산면   6608 ----------


 ---------- 2012-08-29 10:00:00 : 소양동   6609 ----------


 ---------- 2012-08-29 11:00:00 : 신동면   6610 ----------


 ---------- 2012-08-29 11:00:00 : 남산면   6611 ----------


 ---------- 2012-08-29 11:00:00 : 신사우동   6612 ----------


 ---------- 2012-08-29 11:00:00 : 퇴계동   6613 ----------


 ---------- 2012-08-29 12:00:00 : 동내면   6615 ----------


 ---------- 2012-08-29 12:00:00 : 후평1동   6616 ----------


 ---------- 2012-08-29 13:00:00 : 석사동   6617 ----------


 ---------- 2012-08-29 13:00:00 : 신동면   6619 ----------


 ---------- 2012-08-29 13:00:00 : 남산면   6620 ----------


 ---------- 2012-08-29 14:00:00 : 신사우동   6622 ----------


 ---------- 2012-08-29 17:00:00 : 남산면   6623 ----------


 ---------- 2012-08-29 21:00:00 : 효자1동   6624 ----------


 ---------- 2012-08-29 21:00:00 : 퇴계동   6626 ----------


 ---------- 2012-08-29 23:00:00 : 석사동   6627 ----------


 ---------- 2012-08-29 23:00:00 : 남산면   6628 ----------


 ---------- 2012-08-30 01:00:00 : 효자1동   6629 ----------


 ---------- 2012-08-30 06:00:00 : 퇴계동   6631 ----------


 ---------- 2012-08-30 10:00:00 : 신사우동   6632 ----------


 ---------- 2012-08-30 14:00:00 : 교  동   6633 ----------


 ---------- 2012-08-30 23:00:00 : 효자1동   6634 ----------


 ---------- 2012-08-31 10:00:00 : 동내면   6635 ----------


 ---------- 2012-08-31 10:00:00 : 남산면   6636 ----------


 ---------- 2012-08-31 11:00:00 : 북산면   6637 ----------


 ---------- 2012-08-31 12:00:00 : 서  면   6638 ----------


 ---------- 2012-08-31 12:00:00 : 신사우동   6639 ----------


 ---------- 2012-08-31 13:00:00 : 강남동   6640 ----------


 ---------- 2012-08-31 13:00:00 : 근화동   6641 ----------


 ---------- 2012-08-31 14:00:00 : 퇴계동   6642 ----------


 ---------- 2012-08-31 15:00:00 : 강남동   6643 ----------


 ---------- 2012-08-31 15:00:00 : 서  면   6644 ----------


 ---------- 2012-08-31 15:00:00 : 신사우동   6645 ----------


 ---------- 2012-08-31 16:00:00 : 동내면   6646 ----------


 ---------- 2012-08-31 16:00:00 : 근화동   6647 ----------


 ---------- 2012-08-31 17:00:00 : 남산면   6649 ----------


 ---------- 2012-08-31 17:00:00 : 신사우동   6650 ----------


 ---------- 2012-08-31 17:00:00 : 소양동   6651 ----------

 ---------- 2012-08-31 21:00:00 : 후평1동   6652 ----------


 ---------- 2012-08-31 23:00:00 : 석사동   6653 ----------


 ---------- 2012-08-31 23:00:00 : 신사우동   6654 ----------


 ---------- 2012-09-01 01:00:00 : 석사동   6655 ----------


 ---------- 2012-09-01 07:00:00 : 근화동   6657 ----------


 ---------- 2012-09-01 09:00:00 : 서  면   6658 ----------


 ---------- 2012-09-01 10:00:00 : 강남동   6659 ----------


 ---------- 2012-09-01 12:00:00 : 퇴계동   6660 ----------


 ---------- 2012-09-01 13:00:00 : 석사동   6661 ----------


 ---------- 2012-09-01 13:00:00 : 남산면   6662 ----------


 ---------- 2012-09-01 13:00:00 : 소양동   6663 ----------


 ---------- 2012-09-01 14:00:00 : 동내면   6664 ----------


 ---------- 2012-09-01 14:00:00 : 남산면   6666 ----------


 ---------- 2012-09-01 15:00:00 : 동  면   6667 ----------


 ---------- 2012-09-01 16:00:00 : 사북면   6668 ----------


 ---------- 2012-09-01 18:00:00 : 동내면   6670 ----------


 ---------- 2012-09-02 00:00:00 : 교  동   6671 ----------


 ---------- 2012-09-02 03:00:00 : 근화동   6672 ----------


 ---------- 2012-09-02 08:00:00 : 석사동   6673 ----------


 ---------- 2012-09-02 09:00:00 : 사북면   6674 ----------


 ---------- 2012-09-02 10:00:00 : 석사동   6675 ----------


 ---------- 2012-09-02 10:00:00 : 후평1동   6676 ----------


 ---------- 2012-09-02 12:00:00 : 북산면   6679 ----------


 ---------- 2012-09-02 13:00:00 : 북산면   6683 ----------


 ---------- 2012-09-02 16:00:00 : 강남동   6684 ----------


 ---------- 2012-09-02 16:00:00 : 남산면   6686 ----------


 ---------- 2012-09-02 16:00:00 : 동  면   6687 ----------


 ---------- 2012-09-02 18:00:00 : 근화동   6688 ----------


 ---------- 2012-09-02 19:00:00 : 남  면   6689 ----------


 ---------- 2012-09-02 23:00:00 : 약사명동   6690 ----------


 ---------- 2012-09-03 09:00:00 : 동내면   6691 ----------


 ---------- 2012-09-03 09:00:00 : 동산면   6692 ----------


 ---------- 2012-09-03 10:00:00 : 남산면   6693 ----------


 ---------- 2012-09-03 11:00:00 : 석사동   6694 ----------


 ---------- 2012-09-03 13:00:00 : 강남동   6695 ----------


 ---------- 2012-09-03 13:00:00 : 효자1동   6696 ----------


 ---------- 2012-09-03 14:00:00 : 약사명동   6697 ----------


 ---------- 2012-09-03 15:00:00 : 강남동   6698 ----------


 ---------- 2012-09-03 18:00:00 : 신사우동   6699 ----------


 ---------- 2012-09-03 19:00:00 : 신동면   6700 ----------


 ---------- 2012-09-03 19:00:00 : 사북면   6701 ----------


 ---------- 2012-09-03 19:00:00 : 후평1동   6702 ----------


 ---------- 2012-09-03 23:00:00 : 약사명동   6703 ----------


 ---------- 2012-09-04 04:00:00 : 효자1동   6704 ----------


 ---------- 2012-09-04 09:00:00 : 동내면   6705 ----------


 ---------- 2012-09-04 10:00:00 : 신동면   6707 ----------


 ---------- 2012-09-04 13:00:00 : 동내면   6708 ----------


 ---------- 2012-09-04 14:00:00 : 동  면   6709 ----------


 ---------- 2012-09-04 15:00:00 : 효자1동   6710 ----------


 ---------- 2012-09-04 15:00:00 : 후평1동   6711 ----------


 ---------- 2012-09-04 16:00:00 : 동내면   6712 ----------


 ---------- 2012-09-05 01:00:00 : 동내면   6714 ----------


 ---------- 2012-09-05 09:00:00 : 효자1동   6715 ----------


 ---------- 2012-09-05 09:00:00 : 신북읍   6716 ----------


 ---------- 2012-09-05 10:00:00 : 효자1동   6717 ----------


 ---------- 2012-09-05 11:00:00 : 근화동   6718 ----------


 ---------- 2012-09-05 13:00:00 : 강남동   6719 ----------


 ---------- 2012-09-05 14:00:00 : 석사동   6721 ----------


 ---------- 2012-09-05 14:00:00 : 효자1동   6722 ----------


 ---------- 2012-09-05 15:00:00 : 신사우동   6723 ----------


 ---------- 2012-09-05 16:00:00 : 후평1동   6724 ----------


 ---------- 2012-09-05 17:00:00 : 신사우동   6725 ----------


 ---------- 2012-09-06 06:00:00 : 퇴계동   6726 ----------


 ---------- 2012-09-06 08:00:00 : 효자1동   6727 ----------


 ---------- 2012-09-06 09:00:00 : 석사동   6729 ----------


 ---------- 2012-09-06 09:00:00 : 효자1동   6730 ----------


 ---------- 2012-09-06 10:00:00 : 석사동   6731 ----------


 ---------- 2012-09-06 10:00:00 : 강남동   6732 ----------


 ---------- 2012-09-06 10:00:00 : 신사우동   6733 ----------


 ---------- 2012-09-06 11:00:00 : 강남동   6734 ----------


 ---------- 2012-09-06 12:00:00 : 동  면   6735 ----------


 ---------- 2012-09-06 13:00:00 : 남  면   6737 ----------


 ---------- 2012-09-06 13:00:00 : 신북읍   6738 ----------


 ---------- 2012-09-06 13:00:00 : 북산면   6740 ----------


 ---------- 2012-09-06 13:00:00 : 동산면   6741 ----------


 ---------- 2012-09-06 14:00:00 : 효자1동   6742 ----------


 ---------- 2012-09-06 14:00:00 : 동  면   6743 ----------


 ---------- 2012-09-06 14:00:00 : 퇴계동   6745 ----------


 ---------- 2012-09-06 15:00:00 : 동내면   6746 ----------


 ---------- 2012-09-06 16:00:00 : 근화동   6748 ----------


 ---------- 2012-09-06 17:00:00 : 효자1동   6749 ----------


 ---------- 2012-09-06 18:00:00 : 효자1동   6750 ----------


 ---------- 2012-09-06 18:00:00 : 동산면   6752 ----------


 ---------- 2012-09-06 22:00:00 : 석사동   6754 ----------


 ---------- 2012-09-06 23:00:00 : 석사동   6755 ----------


 ---------- 2012-09-07 10:00:00 : 신사우동   6756 ----------


 ---------- 2012-09-07 11:00:00 : 소양동   6757 ----------


 ---------- 2012-09-07 12:00:00 : 남  면   6759 ----------


 ---------- 2012-09-07 12:00:00 : 동내면   6760 ----------


 ---------- 2012-09-07 12:00:00 : 동  면   6761 ----------


 ---------- 2012-09-07 13:00:00 : 남산면   6762 ----------


 ---------- 2012-09-07 13:00:00 : 근화동   6764 ----------


 ---------- 2012-09-07 13:00:00 : 동  면   6765 ----------


 ---------- 2012-09-07 14:00:00 : 북산면   6767 ----------


 ---------- 2012-09-07 15:00:00 : 남산면   6768 ----------


 ---------- 2012-09-07 17:00:00 : 강남동   6770 ----------


 ---------- 2012-09-07 17:00:00 : 사북면   6771 ----------


 ---------- 2012-09-07 18:00:00 : 동  면   6772 ----------


 ---------- 2012-09-07 19:00:00 : 퇴계동   6773 ----------


 ---------- 2012-09-08 00:00:00 : 퇴계동   6774 ----------


 ---------- 2012-09-08 00:00:00 : 조운동   6775 ----------


 ---------- 2012-09-08 04:00:00 : 석사동   6777 ----------


 ---------- 2012-09-08 09:00:00 : 후평1동   6778 ----------


 ---------- 2012-09-08 10:00:00 : 북산면   6779 ----------


 ---------- 2012-09-08 16:00:00 : 석사동   6780 ----------


 ---------- 2012-09-08 19:00:00 : 조운동   6781 ----------


 ---------- 2012-09-08 21:00:00 : 석사동   6783 ----------


 ---------- 2012-09-09 09:00:00 : 강남동   6784 ----------


 ---------- 2012-09-09 13:00:00 : 신북읍   6785 ----------


 ---------- 2012-09-09 15:00:00 : 남  면   6793 ----------


 ---------- 2012-09-09 16:00:00 : 동내면   6794 ----------


 ---------- 2012-09-10 02:00:00 : 효자1동   6795 ----------


 ---------- 2012-09-10 09:00:00 : 남  면   6796 ----------


 ---------- 2012-09-10 09:00:00 : 신북읍   6797 ----------


 ---------- 2012-09-10 10:00:00 : 서  면   6798 ----------


 ---------- 2012-09-10 12:00:00 : 석사동   6800 ----------


 ---------- 2012-09-10 13:00:00 : 남산면   6802 ----------


 ---------- 2012-09-10 14:00:00 : 동산면   6803 ----------


 ---------- 2012-09-11 03:00:00 : 효자1동   6804 ----------


 ---------- 2012-09-11 10:00:00 : 서  면   6805 ----------


 ---------- 2012-09-11 15:00:00 : 약사명동   6806 ----------


 ---------- 2012-09-11 21:00:00 : 강남동   6807 ----------


 ---------- 2012-09-12 12:00:00 : 교  동   6808 ----------


 ---------- 2012-09-12 15:00:00 : 동  면   6809 ----------


 ---------- 2012-09-12 16:00:00 : 동내면   6810 ----------


 ---------- 2012-09-12 16:00:00 : 남산면   6811 ----------


 ---------- 2012-09-12 16:00:00 : 신북읍   6812 ----------


 ---------- 2012-09-13 07:00:00 : 남산면   6813 ----------


 ---------- 2012-09-13 10:00:00 : 강남동   6814 ----------


 ---------- 2012-09-13 13:00:00 : 동내면   6815 ----------


 ---------- 2012-09-13 15:00:00 : 후평1동   6816 ----------


 ---------- 2012-09-13 15:00:00 : 동산면   6817 ----------


 ---------- 2012-09-13 19:00:00 : 남산면   6818 ----------


 ---------- 2012-09-13 20:00:00 : 석사동   6819 ----------


 ---------- 2012-09-13 21:00:00 : 신북읍   6821 ----------


 ---------- 2012-09-13 22:00:00 : 석사동   6823 ----------


 ---------- 2012-09-13 22:00:00 : 남산면   6824 ----------


 ---------- 2012-09-13 22:00:00 : 신사우동   6825 ----------


 ---------- 2012-09-14 08:00:00 : 서  면   6826 ----------

 ---------- 2012-09-14 09:00:00 : 서  면   6828 ----------


 ---------- 2012-09-14 10:00:00 : 사북면   6829 ----------


 ---------- 2012-09-14 10:00:00 : 남산면   6830 ----------


 ---------- 2012-09-14 13:00:00 : 강남동   6832 ----------


 ---------- 2012-09-14 13:00:00 : 서  면   6833 ----------


 ---------- 2012-09-14 14:00:00 : 신북읍   6834 ----------


 ---------- 2012-09-14 15:00:00 : 동  면   6836 ----------


 ---------- 2012-09-14 20:00:00 : 퇴계동   6837 ----------


 ---------- 2012-09-15 07:00:00 : 효자1동   6838 ----------


 ---------- 2012-09-15 09:00:00 : 동내면   6839 ----------


 ---------- 2012-09-15 09:00:00 : 신북읍   6840 ----------


 ---------- 2012-09-15 09:00:00 : 소양동   6841 ----------


 ---------- 2012-09-15 10:00:00 : 후평1동   6842 ----------


 ---------- 2012-09-15 15:00:00 : 서  면   6843 ----------


 ---------- 2012-09-15 16:00:00 : 신북읍   6845 ----------


 ---------- 2012-09-15 17:00:00 : 석사동   6846 ----------


 ---------- 2012-09-15 21:00:00 : 남산면   6850 ----------


 ---------- 2012-09-16 08:00:00 : 사북면   6851 ----------


 ---------- 2012-09-16 09:00:00 : 동산면   6853 ----------


 ---------- 2012-09-16 12:00:00 : 신동면   6854 ----------


 ---------- 2012-09-16 12:00:00 : 서  면   6855 ----------


 ---------- 2012-09-16 12:00:00 : 동산면   6857 ----------


 ---------- 2012-09-16 14:00:00 : 동  면   6858 ----------


 ---------- 2012-09-16 19:00:00 : 효자1동   6859 ----------


 ---------- 2012-09-16 19:00:00 : 신사우동   6860 ----------


 ---------- 2012-09-17 00:00:00 : 북산면   6861 ----------


 ---------- 2012-09-17 10:00:00 : 남산면   6862 ----------


 ---------- 2012-09-17 13:00:00 : 소양동   6863 ----------


 ---------- 2012-09-17 15:00:00 : 신북읍   6865 ----------


 ---------- 2012-09-17 16:00:00 : 북산면   6867 ----------


 ---------- 2012-09-18 06:00:00 : 근화동   6870 ----------


 ---------- 2012-09-18 07:00:00 : 신북읍   6871 ----------


 ---------- 2012-09-18 08:00:00 : 신북읍   6872 ----------


 ---------- 2012-09-18 09:00:00 : 신북읍   6873 ----------


 ---------- 2012-09-18 13:00:00 : 후평1동   6874 ----------


 ---------- 2012-09-18 14:00:00 : 신북읍   6875 ----------


 ---------- 2012-09-18 14:00:00 : 퇴계동   6877 ----------


 ---------- 2012-09-18 16:00:00 : 신북읍   6878 ----------


 ---------- 2012-09-18 21:00:00 : 강남동   6880 ----------


 ---------- 2012-09-18 21:00:00 : 후평1동   6881 ----------


 ---------- 2012-09-19 05:00:00 : 신북읍   6882 ----------


 ---------- 2012-09-19 06:00:00 : 근화동   6884 ----------


 ---------- 2012-09-19 06:00:00 : 신북읍   6885 ----------


 ---------- 2012-09-19 09:00:00 : 신동면   6886 ----------


 ---------- 2012-09-19 09:00:00 : 사북면   6887 ----------


 ---------- 2012-09-19 10:00:00 : 신북읍   6888 ----------


 ---------- 2012-09-19 11:00:00 : 동  면   6889 ----------


 ---------- 2012-09-19 16:00:00 : 퇴계동   6890 ----------


 ---------- 2012-09-19 17:00:00 : 효자1동   6893 ----------


 ---------- 2012-09-20 08:00:00 : 남산면   6895 ----------


 ---------- 2012-09-20 13:00:00 : 강남동   6896 ----------


 ---------- 2012-09-20 16:00:00 : 남산면   6897 ----------


 ---------- 2012-09-20 17:00:00 : 남산면   6898 ----------


 ---------- 2012-09-20 17:00:00 : 후평1동   6899 ----------


 ---------- 2012-09-20 22:00:00 : 서  면   6902 ----------


 ---------- 2012-09-20 23:00:00 : 후평1동   6903 ----------


 ---------- 2012-09-21 15:00:00 : 서  면   6904 ----------


 ---------- 2012-09-21 15:00:00 : 남산면   6906 ----------


 ---------- 2012-09-21 20:00:00 : 서  면   6907 ----------


 ---------- 2012-09-21 23:00:00 : 신사우동   6908 ----------


 ---------- 2012-09-22 12:00:00 : 효자1동   6910 ----------


 ---------- 2012-09-22 13:00:00 : 후평1동   6911 ----------


 ---------- 2012-09-22 15:00:00 : 사북면   6913 ----------


 ---------- 2012-09-22 15:00:00 : 남산면   6914 ----------


 ---------- 2012-09-22 15:00:00 : 퇴계동   6915 ----------


 ---------- 2012-09-22 16:00:00 : 남산면   6916 ----------


 ---------- 2012-09-22 16:00:00 : 동  면   6917 ----------


 ---------- 2012-09-22 17:00:00 : 석사동   6918 ----------


 ---------- 2012-09-22 23:00:00 : 석사동   6919 ----------


 ---------- 2012-09-23 06:00:00 : 후평1동   6920 ----------


 ---------- 2012-09-23 09:00:00 : 후평1동   6921 ----------


 ---------- 2012-09-23 13:00:00 : 소양동   6923 ----------


 ---------- 2012-09-23 13:00:00 : 퇴계동   6924 ----------


 ---------- 2012-09-23 14:00:00 : 신동면   6928 ----------


 ---------- 2012-09-23 14:00:00 : 신사우동   6929 ----------


 ---------- 2012-09-23 15:00:00 : 신동면   6930 ----------


 ---------- 2012-09-24 02:00:00 : 효자1동   6931 ----------


 ---------- 2012-09-24 04:00:00 : 조운동   6933 ----------


 ---------- 2012-09-24 09:00:00 : 남산면   6935 ----------


 ---------- 2012-09-24 09:00:00 : 신북읍   6936 ----------


 ---------- 2012-09-24 10:00:00 : 서  면   6937 ----------


 ---------- 2012-09-24 11:00:00 : 남  면   6938 ----------


 ---------- 2012-09-24 12:00:00 : 후평1동   6939 ----------


 ---------- 2012-09-24 14:00:00 : 신사우동   6940 ----------


 ---------- 2012-09-24 15:00:00 : 약사명동   6941 ----------


 ---------- 2012-09-24 17:00:00 : 강남동   6943 ----------


 ---------- 2012-09-24 18:00:00 : 석사동   6944 ----------


 ---------- 2012-09-25 00:00:00 : 신동면   6945 ----------


 ---------- 2012-09-25 01:00:00 : 근화동   6946 ----------


 ---------- 2012-09-25 10:00:00 : 효자1동   6947 ----------


 ---------- 2012-09-25 13:00:00 : 약사명동   6948 ----------


 ---------- 2012-09-25 14:00:00 : 효자1동   6949 ----------


 ---------- 2012-09-26 02:00:00 : 동내면   6950 ----------


 ---------- 2012-09-26 09:00:00 : 동내면   6951 ----------


 ---------- 2012-09-26 10:00:00 : 후평1동   6952 ----------


 ---------- 2012-09-26 11:00:00 : 서  면   6954 ----------


 ---------- 2012-09-26 12:00:00 : 서  면   6955 ----------


 ---------- 2012-09-26 13:00:00 : 퇴계동   6956 ----------


 ---------- 2012-09-26 17:00:00 : 근화동   6957 ----------


 ---------- 2012-09-27 05:00:00 : 효자1동   6958 ----------


 ---------- 2012-09-27 09:00:00 : 북산면   6959 ----------


 ---------- 2012-09-27 15:00:00 : 남산면   6960 ----------


 ---------- 2012-09-27 15:00:00 : 신사우동   6961 ----------


 ---------- 2012-09-27 16:00:00 : 동산면   6962 ----------


 ---------- 2012-09-27 18:00:00 : 조운동   6964 ----------


 ---------- 2012-09-28 09:00:00 : 퇴계동   6965 ----------


 ---------- 2012-09-28 10:00:00 : 후평1동   6966 ----------


 ---------- 2012-09-28 12:00:00 : 남산면   6968 ----------


 ---------- 2012-09-28 13:00:00 : 후평1동   6970 ----------


 ---------- 2012-09-28 15:00:00 : 약사명동   6972 ----------


 ---------- 2012-09-28 18:00:00 : 동산면   6975 ----------


 ---------- 2012-09-28 21:00:00 : 조운동   6977 ----------


 ---------- 2012-09-29 05:00:00 : 효자1동   6978 ----------


 ---------- 2012-09-29 08:00:00 : 사북면   6979 ----------


 ---------- 2012-09-29 12:00:00 : 효자1동   6980 ----------


 ---------- 2012-09-29 19:00:00 : 신사우동   6981 ----------


 ---------- 2012-09-30 00:00:00 : 남산면   6982 ----------


 ---------- 2012-09-30 10:00:00 : 남산면   6983 ----------


 ---------- 2012-09-30 12:00:00 : 신북읍   6984 ----------


 ---------- 2012-09-30 13:00:00 : 동  면   6985 ----------


 ---------- 2012-09-30 23:00:00 : 퇴계동   6986 ----------


 ---------- 2012-10-01 07:00:00 : 약사명동   6987 ----------


 ---------- 2012-10-01 09:00:00 : 동  면   6988 ----------


 ---------- 2012-10-01 11:00:00 : 강남동   6990 ----------


 ---------- 2012-10-01 11:00:00 : 퇴계동   6991 ----------


 ---------- 2012-10-01 11:00:00 : 북산면   6993 ----------


 ---------- 2012-10-01 13:00:00 : 효자1동   6994 ----------


 ---------- 2012-10-01 17:00:00 : 후평1동   6995 ----------


 ---------- 2012-10-01 18:00:00 : 석사동   6997 ----------


 ---------- 2012-10-01 18:00:00 : 후평1동   6998 ----------


 ---------- 2012-10-01 19:00:00 : 후평1동   7000 ----------


 ---------- 2012-10-01 22:00:00 : 신동면   7001 ----------


 ---------- 2012-10-01 22:00:00 : 효자1동   7002 ----------


 ---------- 2012-10-01 23:00:00 : 퇴계동   7004 ----------


 ---------- 2012-10-02 01:00:00 : 효자1동   7005 ----------


 ---------- 2012-10-02 05:00:00 : 약사명동   7006 ----------


 ---------- 2012-10-02 08:00:00 : 후평1동   7007 ----------


 ---------- 2012-10-02 10:00:00 : 효자1동   7008 ----------

 ---------- 2012-10-02 12:00:00 : 신사우동   7009 ----------


 ---------- 2012-10-02 13:00:00 : 서  면   7010 ----------


 ---------- 2012-10-02 13:00:00 : 동내면   7011 ----------


 ---------- 2012-10-02 13:00:00 : 남산면   7013 ----------


 ---------- 2012-10-02 15:00:00 : 남산면   7014 ----------


 ---------- 2012-10-02 15:00:00 : 신사우동   7015 ----------


 ---------- 2012-10-02 17:00:00 : 효자1동   7016 ----------


 ---------- 2012-10-02 18:00:00 : 사북면   7017 ----------


 ---------- 2012-10-03 10:00:00 : 강남동   7018 ----------


 ---------- 2012-10-03 10:00:00 : 남산면   7019 ----------


 ---------- 2012-10-03 12:00:00 : 신동면   7022 ----------


 ---------- 2012-10-03 13:00:00 : 서  면   7023 ----------


 ---------- 2012-10-03 13:00:00 : 동내면   7024 ----------


 ---------- 2012-10-03 15:00:00 : 동  면   7025 ----------


 ---------- 2012-10-04 07:00:00 : 신사우동   7026 ----------


 ---------- 2012-10-04 11:00:00 : 북산면   7027 ----------


 ---------- 2012-10-04 12:00:00 : 근화동   7028 ----------


 ---------- 2012-10-04 13:00:00 : 강남동   7030 ----------


 ---------- 2012-10-04 13:00:00 : 서  면   7031 ----------


 ---------- 2012-10-04 13:00:00 : 동  면   7032 ----------


 ---------- 2012-10-04 23:00:00 : 석사동   7033 ----------


 ---------- 2012-10-05 07:00:00 : 강남동   7034 ----------


 ---------- 2012-10-05 15:00:00 : 소양동   7035 ----------


 ---------- 2012-10-05 20:00:00 : 효자1동   7036 ----------


 ---------- 2012-10-06 01:00:00 : 석사동   7038 ----------


 ---------- 2012-10-06 01:00:00 : 근화동   7039 ----------


 ---------- 2012-10-06 06:00:00 : 석사동   7040 ----------


 ---------- 2012-10-06 06:00:00 : 퇴계동   7042 ----------


 ---------- 2012-10-06 10:00:00 : 석사동   7043 ----------


 ---------- 2012-10-06 10:00:00 : 서  면   7044 ----------


 ---------- 2012-10-06 12:00:00 : 사북면   7045 ----------


 ---------- 2012-10-06 13:00:00 : 남산면   7046 ----------


 ---------- 2012-10-06 14:00:00 : 서  면   7047 ----------


 ---------- 2012-10-06 15:00:00 : 동내면   7048 ----------


 ---------- 2012-10-06 16:00:00 : 남산면   7049 ----------


 ---------- 2012-10-06 16:00:00 : 약사명동   7051 ----------


 ---------- 2012-10-06 19:00:00 : 동내면   7053 ----------


 ---------- 2012-10-06 21:00:00 : 신사우동   7054 ----------


 ---------- 2012-10-07 06:00:00 : 남산면   7055 ----------


 ---------- 2012-10-07 07:00:00 : 효자1동   7056 ----------


 ---------- 2012-10-07 11:00:00 : 동내면   7057 ----------


 ---------- 2012-10-07 12:00:00 : 석사동   7058 ----------


 ---------- 2012-10-07 12:00:00 : 후평1동   7059 ----------


 ---------- 2012-10-07 13:00:00 : 강남동   7060 ----------


 ---------- 2012-10-07 14:00:00 : 석사동   7061 ----------


 ---------- 2012-10-07 14:00:00 : 강남동   7062 ----------


 ---------- 2012-10-07 14:00:00 : 신사우동   7063 ----------


 ---------- 2012-10-07 14:00:00 : 신북읍   7064 ----------


 ---------- 2012-10-07 14:00:00 : 후평1동   7065 ----------


 ---------- 2012-10-07 16:00:00 : 신북읍   7066 ----------


 ---------- 2012-10-08 09:00:00 : 소양동   7067 ----------


 ---------- 2012-10-08 09:00:00 : 동  면   7068 ----------


 ---------- 2012-10-08 13:00:00 : 강남동   7069 ----------


 ---------- 2012-10-08 14:00:00 : 효자1동   7070 ----------


 ---------- 2012-10-08 14:00:00 : 근화동   7071 ----------


 ---------- 2012-10-08 16:00:00 : 서  면   7072 ----------


 ---------- 2012-10-08 17:00:00 : 신사우동   7074 ----------


 ---------- 2012-10-08 21:00:00 : 후평1동   7075 ----------


 ---------- 2012-10-08 22:00:00 : 효자1동   7076 ----------


 ---------- 2012-10-09 11:00:00 : 동  면   7077 ----------


 ---------- 2012-10-09 12:00:00 : 퇴계동   7078 ----------


 ---------- 2012-10-09 13:00:00 : 서  면   7079 ----------


 ---------- 2012-10-09 14:00:00 : 효자1동   7080 ----------


 ---------- 2012-10-09 15:00:00 : 신북읍   7081 ----------


 ---------- 2012-10-10 12:00:00 : 서  면   7082 ----------


 ---------- 2012-10-10 14:00:00 : 남산면   7083 ----------


 ---------- 2012-10-10 23:00:00 : 퇴계동   7084 ----------


 ---------- 2012-10-11 03:00:00 : 효자1동   7085 ----------


 ---------- 2012-10-11 05:00:00 : 동내면   7086 ----------


 ---------- 2012-10-11 09:00:00 : 남  면   7087 ----------


 ---------- 2012-10-11 11:00:00 : 강남동   7088 ----------


 ---------- 2012-10-11 14:00:00 : 효자1동   7090 ----------


 ---------- 2012-10-11 19:00:00 : 약사명동   7092 ----------


 ---------- 2012-10-11 23:00:00 : 신동면   7094 ----------


 ---------- 2012-10-12 00:00:00 : 석사동   7097 ----------


 ---------- 2012-10-12 04:00:00 : 후평1동   7099 ----------


 ---------- 2012-10-12 08:00:00 : 후평1동   7100 ----------


 ---------- 2012-10-12 15:00:00 : 신동면   7101 ----------


 ---------- 2012-10-12 15:00:00 : 근화동   7103 ----------


 ---------- 2012-10-12 20:00:00 : 효자1동   7105 ----------


 ---------- 2012-10-13 07:00:00 : 근화동   7107 ----------


 ---------- 2012-10-13 11:00:00 : 사북면   7108 ----------


 ---------- 2012-10-13 12:00:00 : 서  면   7109 ----------


 ---------- 2012-10-14 00:00:00 : 후평1동   7110 ----------


 ---------- 2012-10-14 03:00:00 : 후평1동   7111 ----------


 ---------- 2012-10-14 10:00:00 : 북산면   7112 ----------


 ---------- 2012-10-14 11:00:00 : 동내면   7114 ----------


 ---------- 2012-10-14 11:00:00 : 북산면   7115 ----------


 ---------- 2012-10-14 12:00:00 : 동내면   7116 ----------


 ---------- 2012-10-14 12:00:00 : 북산면   7117 ----------


 ---------- 2012-10-14 13:00:00 : 신북읍   7118 ----------


 ---------- 2012-10-14 14:00:00 : 사북면   7119 ----------


 ---------- 2012-10-14 14:00:00 : 근화동   7120 ----------


 ---------- 2012-10-14 15:00:00 : 사북면   7121 ----------


 ---------- 2012-10-15 06:00:00 : 동내면   7122 ----------


 ---------- 2012-10-15 11:00:00 : 후평1동   7123 ----------


 ---------- 2012-10-15 13:00:00 : 신동면   7124 ----------


 ---------- 2012-10-15 13:00:00 : 근화동   7125 ----------


 ---------- 2012-10-15 14:00:00 : 강남동   7127 ----------


 ---------- 2012-10-15 23:00:00 : 신사우동   7128 ----------


 ---------- 2012-10-16 12:00:00 : 동  면   7129 ----------


 ---------- 2012-10-16 13:00:00 : 동내면   7130 ----------


 ---------- 2012-10-16 14:00:00 : 남  면   7131 ----------


 ---------- 2012-10-16 14:00:00 : 동  면   7132 ----------


 ---------- 2012-10-16 14:00:00 : 동산면   7133 ----------


 ---------- 2012-10-16 16:00:00 : 효자1동   7134 ----------


 ---------- 2012-10-17 03:00:00 : 효자1동   7136 ----------


 ---------- 2012-10-17 06:00:00 : 교  동   7137 ----------


 ---------- 2012-10-17 07:00:00 : 서  면   7138 ----------


 ---------- 2012-10-17 14:00:00 : 석사동   7139 ----------


 ---------- 2012-10-17 20:00:00 : 퇴계동   7141 ----------


 ---------- 2012-10-18 00:00:00 : 동  면   7142 ----------


 ---------- 2012-10-18 02:00:00 : 퇴계동   7143 ----------


 ---------- 2012-10-18 04:00:00 : 약사명동   7145 ----------


 ---------- 2012-10-18 09:00:00 : 석사동   7146 ----------


 ---------- 2012-10-18 15:00:00 : 퇴계동   7147 ----------


 ---------- 2012-10-19 02:00:00 : 효자1동   7148 ----------


 ---------- 2012-10-19 08:00:00 : 후평1동   7149 ----------


 ---------- 2012-10-19 19:00:00 : 신사우동   7150 ----------


 ---------- 2012-10-20 00:00:00 : 조운동   7152 ----------


 ---------- 2012-10-20 04:00:00 : 석사동   7154 ----------


 ---------- 2012-10-20 05:00:00 : 동내면   7155 ----------


 ---------- 2012-10-20 13:00:00 : 서  면   7158 ----------


 ---------- 2012-10-20 16:00:00 : 약사명동   7160 ----------


 ---------- 2012-10-20 17:00:00 : 후평1동   7161 ----------


 ---------- 2012-10-21 03:00:00 : 동산면   7162 ----------


 ---------- 2012-10-21 10:00:00 : 남  면   7163 ----------


 ---------- 2012-10-21 11:00:00 : 동  면   7164 ----------


 ---------- 2012-10-21 12:00:00 : 약사명동   7165 ----------


 ---------- 2012-10-21 12:00:00 : 동  면   7166 ----------


 ---------- 2012-10-21 13:00:00 : 서  면   7168 ----------


 ---------- 2012-10-21 13:00:00 : 근화동   7169 ----------


 ---------- 2012-10-21 15:00:00 : 서  면   7170 ----------


 ---------- 2012-10-21 19:00:00 : 퇴계동   7171 ----------


 ---------- 2012-10-22 22:00:00 : 석사동   7172 ----------


 ---------- 2012-10-22 23:00:00 : 서  면   7173 ----------


 ---------- 2012-10-23 10:00:00 : 퇴계동   7174 ----------


 ---------- 2012-10-23 12:00:00 : 효자1동   7175 ----------

 ---------- 2012-10-23 15:00:00 : 효자1동   7176 ----------


 ---------- 2012-10-24 13:00:00 : 남  면   7177 ----------


 ---------- 2012-10-24 23:00:00 : 후평1동   7178 ----------


 ---------- 2012-10-25 01:00:00 : 효자1동   7179 ----------


 ---------- 2012-10-25 02:00:00 : 석사동   7181 ----------


 ---------- 2012-10-25 06:00:00 : 소양동   7183 ----------


 ---------- 2012-10-25 07:00:00 : 소양동   7184 ----------


 ---------- 2012-10-25 10:00:00 : 근화동   7185 ----------


 ---------- 2012-10-26 06:00:00 : 소양동   7187 ----------


 ---------- 2012-10-26 17:00:00 : 효자1동   7188 ----------


 ---------- 2012-10-26 21:00:00 : 퇴계동   7189 ----------


 ---------- 2012-10-28 10:00:00 : 강남동   7191 ----------


 ---------- 2012-10-28 11:00:00 : 후평1동   7193 ----------


 ---------- 2012-10-28 17:00:00 : 신사우동   7194 ----------


 ---------- 2012-10-28 21:00:00 : 조운동   7195 ----------


 ---------- 2012-10-29 08:00:00 : 동내면   7197 ----------


 ---------- 2012-10-29 09:00:00 : 퇴계동   7198 ----------


 ---------- 2012-10-29 10:00:00 : 석사동   7200 ----------


 ---------- 2012-10-29 12:00:00 : 신동면   7201 ----------


 ---------- 2012-10-29 15:00:00 : 서  면   7203 ----------


 ---------- 2012-10-29 18:00:00 : 근화동   7204 ----------


 ---------- 2012-10-29 21:00:00 : 강남동   7206 ----------


 ---------- 2012-10-30 00:00:00 : 약사명동   7207 ----------


 ---------- 2012-10-30 08:00:00 : 남  면   7208 ----------


 ---------- 2012-10-30 09:00:00 : 효자1동   7209 ----------


 ---------- 2012-10-30 11:00:00 : 사북면   7211 ----------


 ---------- 2012-10-31 07:00:00 : 신동면   7212 ----------


 ---------- 2012-10-31 16:00:00 : 근화동   7213 ----------


 ---------- 2012-10-31 17:00:00 : 소양동   7214 ----------


 ---------- 2012-11-01 07:00:00 : 약사명동   7215 ----------


 ---------- 2012-11-01 11:00:00 : 서  면   7216 ----------


 ---------- 2012-11-01 13:00:00 : 석사동   7218 ----------


 ---------- 2012-11-01 13:00:00 : 남산면   7221 ----------


 ---------- 2012-11-02 02:00:00 : 동  면   7222 ----------


 ---------- 2012-11-02 14:00:00 : 효자1동   7223 ----------


 ---------- 2012-11-02 18:00:00 : 퇴계동   7224 ----------


 ---------- 2012-11-03 01:00:00 : 퇴계동   7225 ----------


 ---------- 2012-11-03 17:00:00 : 석사동   7227 ----------


 ---------- 2012-11-03 19:00:00 : 남산면   7228 ----------


 ---------- 2012-11-03 22:00:00 : 동내면   7230 ----------


 ---------- 2012-11-04 11:00:00 : 서  면   7231 ----------


 ---------- 2012-11-04 16:00:00 : 동내면   7233 ----------


 ---------- 2012-11-04 17:00:00 : 서  면   7235 ----------


 ---------- 2012-11-06 15:00:00 : 근화동   7237 ----------


 ---------- 2012-11-06 18:00:00 : 퇴계동   7238 ----------


 ---------- 2012-11-07 15:00:00 : 남산면   7241 ----------


 ---------- 2012-11-08 10:00:00 : 석사동   7243 ----------


 ---------- 2012-11-08 16:00:00 : 서  면   7246 ----------


 ---------- 2012-11-08 16:00:00 : 효자1동   7247 ----------


 ---------- 2012-11-08 17:00:00 : 퇴계동   7249 ----------


 ---------- 2012-11-09 11:00:00 : 신사우동   7250 ----------


 ---------- 2012-11-09 17:00:00 : 석사동   7251 ----------


 ---------- 2012-11-09 23:00:00 : 석사동   7254 ----------


 ---------- 2012-11-10 00:00:00 : 퇴계동   7255 ----------


 ---------- 2012-11-10 04:00:00 : 효자1동   7259 ----------


 ---------- 2012-11-10 05:00:00 : 조운동   7264 ----------


 ---------- 2012-11-10 10:00:00 : 서  면   7265 ----------


 ---------- 2012-11-10 11:00:00 : 석사동   7266 ----------


 ---------- 2012-11-11 01:00:00 : 효자1동   7267 ----------


 ---------- 2012-11-11 01:00:00 : 남산면   7268 ----------


 ---------- 2012-11-11 06:00:00 : 후평1동   7270 ----------


 ---------- 2012-11-11 07:00:00 : 동산면   7272 ----------


 ---------- 2012-11-11 09:00:00 : 동산면   7273 ----------


 ---------- 2012-11-11 10:00:00 : 남산면   7276 ----------


 ---------- 2012-11-11 20:00:00 : 퇴계동   7277 ----------


 ---------- 2012-11-11 22:00:00 : 퇴계동   7278 ----------


 ---------- 2012-11-11 23:00:00 : 석사동   7279 ----------


 ---------- 2012-11-12 12:00:00 : 남산면   7281 ----------


 ---------- 2012-11-12 14:00:00 : 신사우동   7282 ----------


 ---------- 2012-11-12 16:00:00 : 석사동   7283 ----------


 ---------- 2012-11-13 16:00:00 : 신동면   7284 ----------


 ---------- 2012-11-13 16:00:00 : 동  면   7285 ----------


 ---------- 2012-11-14 04:00:00 : 교  동   7286 ----------


 ---------- 2012-11-14 08:00:00 : 조운동   7289 ----------


 ---------- 2012-11-14 15:00:00 : 신북읍   7290 ----------


 ---------- 2012-11-15 09:00:00 : 신사우동   7291 ----------


 ---------- 2012-11-15 18:00:00 : 강남동   7293 ----------


 ---------- 2012-11-15 18:00:00 : 동  면   7294 ----------


 ---------- 2012-11-16 15:00:00 : 신북읍   7296 ----------


 ---------- 2012-11-16 21:00:00 : 동  면   7297 ----------


 ---------- 2012-11-17 00:00:00 : 효자1동   7299 ----------


 ---------- 2012-11-17 03:00:00 : 석사동   7300 ----------


 ---------- 2012-11-17 03:00:00 : 효자1동   7301 ----------


 ---------- 2012-11-17 04:00:00 : 효자1동   7302 ----------


 ---------- 2012-11-17 09:00:00 : 소양동   7303 ----------


 ---------- 2012-11-17 11:00:00 : 교  동   7305 ----------


 ---------- 2012-11-18 12:00:00 : 신동면   7306 ----------


 ---------- 2012-11-18 13:00:00 : 신동면   7307 ----------


 ---------- 2012-11-18 22:00:00 : 조운동   7309 ----------


 ---------- 2012-11-19 10:00:00 : 신동면   7310 ----------


 ---------- 2012-11-19 11:00:00 : 남산면   7313 ----------


 ---------- 2012-11-19 11:00:00 : 후평1동   7314 ----------


 ---------- 2012-11-19 12:00:00 : 효자1동   7316 ----------


 ---------- 2012-11-19 15:00:00 : 석사동   7318 ----------


 ---------- 2012-11-19 16:00:00 : 후평1동   7319 ----------


 ---------- 2012-11-20 08:00:00 : 근화동   7321 ----------


 ---------- 2012-11-21 03:00:00 : 신사우동   7322 ----------


 ---------- 2012-11-21 06:00:00 : 신사우동   7324 ----------


 ---------- 2012-11-21 10:00:00 : 후평1동   7326 ----------


 ---------- 2012-11-21 14:00:00 : 동산면   7327 ----------


 ---------- 2012-11-22 05:00:00 : 강남동   7328 ----------


 ---------- 2012-11-22 16:00:00 : 석사동   7329 ----------


 ---------- 2012-11-22 16:00:00 : 효자1동   7330 ----------


 ---------- 2012-11-22 20:00:00 : 약사명동   7331 ----------


 ---------- 2012-11-22 23:00:00 : 조운동   7333 ----------


 ---------- 2012-11-23 11:00:00 : 소양동   7334 ----------


 ---------- 2012-11-24 00:00:00 : 후평1동   7337 ----------


 ---------- 2012-11-24 06:00:00 : 서  면   7339 ----------


 ---------- 2012-11-24 08:00:00 : 효자1동   7340 ----------


 ---------- 2012-11-24 15:00:00 : 동내면   7342 ----------


 ---------- 2012-11-24 19:00:00 : 동내면   7344 ----------


 ---------- 2012-11-25 14:00:00 : 북산면   7345 ----------


 ---------- 2012-11-25 19:00:00 : 효자1동   7347 ----------


 ---------- 2012-11-25 19:00:00 : 신사우동   7349 ----------


 ---------- 2012-11-26 08:00:00 : 남  면   7352 ----------


 ---------- 2012-11-26 12:00:00 : 강남동   7353 ----------


 ---------- 2012-11-26 19:00:00 : 후평1동   7354 ----------


 ---------- 2012-11-27 10:00:00 : 동내면   7356 ----------


 ---------- 2012-11-27 13:00:00 : 석사동   7358 ----------


 ---------- 2012-11-27 15:00:00 : 남  면   7360 ----------


 ---------- 2012-11-27 15:00:00 : 신북읍   7361 ----------


 ---------- 2012-11-28 05:00:00 : 동  면   7362 ----------


 ---------- 2012-11-28 08:00:00 : 서  면   7365 ----------


 ---------- 2012-11-28 16:00:00 : 석사동   7367 ----------


 ---------- 2012-11-28 19:00:00 : 후평1동   7368 ----------


 ---------- 2012-11-28 19:00:00 : 퇴계동   7370 ----------


 ---------- 2012-11-28 22:00:00 : 석사동   7372 ----------


 ---------- 2012-11-29 01:00:00 : 소양동   7373 ----------


 ---------- 2012-11-29 07:00:00 : 동내면   7375 ----------


 ---------- 2012-11-30 05:00:00 : 퇴계동   7377 ----------


 ---------- 2012-11-30 17:00:00 : 약사명동   7378 ----------


 ---------- 2012-12-01 13:00:00 : 교  동   7379 ----------


 ---------- 2012-12-01 21:00:00 : 신사우동   7380 ----------


 ---------- 2012-12-02 09:00:00 : 사북면   7382 ----------


 ---------- 2012-12-02 09:00:00 : 후평1동   7383 ----------


 ---------- 2012-12-02 12:00:00 : 동산면   7385 ----------


 ---------- 2012-12-02 14:00:00 : 효자1동   7386 ----------


 ---------- 2012-12-02 15:00:00 : 서  면   7388 ----------

 ---------- 2012-12-02 16:00:00 : 서  면   7389 ----------


 ---------- 2012-12-02 19:00:00 : 조운동   7390 ----------


 ---------- 2012-12-02 23:00:00 : 석사동   7391 ----------


 ---------- 2012-12-03 14:00:00 : 서  면   7393 ----------


 ---------- 2012-12-03 18:00:00 : 동  면   7394 ----------


 ---------- 2012-12-04 12:00:00 : 북산면   7395 ----------


 ---------- 2012-12-04 21:00:00 : 후평1동   7396 ----------


 ---------- 2012-12-04 23:00:00 : 남산면   7398 ----------


 ---------- 2012-12-05 01:00:00 : 신동면   7399 ----------


 ---------- 2012-12-05 08:00:00 : 후평1동   7400 ----------


 ---------- 2012-12-05 14:00:00 : 조운동   7401 ----------


 ---------- 2012-12-05 21:00:00 : 퇴계동   7402 ----------


 ---------- 2012-12-06 00:00:00 : 신사우동   7403 ----------


 ---------- 2012-12-06 02:00:00 : 동  면   7404 ----------


 ---------- 2012-12-06 15:00:00 : 신동면   7406 ----------


 ---------- 2012-12-06 17:00:00 : 소양동   7407 ----------


 ---------- 2012-12-06 20:00:00 : 소양동   7408 ----------


 ---------- 2012-12-07 08:00:00 : 강남동   7411 ----------


 ---------- 2012-12-07 10:00:00 : 석사동   7412 ----------


 ---------- 2012-12-07 17:00:00 : 신동면   7413 ----------


 ---------- 2012-12-07 17:00:00 : 근화동   7414 ----------


 ---------- 2012-12-07 17:00:00 : 약사명동   7415 ----------


 ---------- 2012-12-08 06:00:00 : 후평1동   7416 ----------


 ---------- 2012-12-09 00:00:00 : 신사우동   7417 ----------


 ---------- 2012-12-09 10:00:00 : 동내면   7418 ----------


 ---------- 2012-12-09 12:00:00 : 신동면   7420 ----------


 ---------- 2012-12-09 13:00:00 : 신동면   7421 ----------


 ---------- 2012-12-09 16:00:00 : 소양동   7422 ----------


 ---------- 2012-12-09 17:00:00 : 효자1동   7424 ----------


 ---------- 2012-12-09 22:00:00 : 퇴계동   7426 ----------


 ---------- 2012-12-09 23:00:00 : 동내면   7427 ----------


 ---------- 2012-12-10 08:00:00 : 동  면   7429 ----------


 ---------- 2012-12-10 08:00:00 : 퇴계동   7431 ----------


 ---------- 2012-12-10 11:00:00 : 후평1동   7434 ----------


 ---------- 2012-12-10 12:00:00 : 북산면   7435 ----------


 ---------- 2012-12-10 13:00:00 : 효자1동   7436 ----------


 ---------- 2012-12-11 07:00:00 : 석사동   7437 ----------


 ---------- 2012-12-11 14:00:00 : 효자1동   7438 ----------


 ---------- 2012-12-11 17:00:00 : 근화동   7439 ----------


 ---------- 2012-12-12 14:00:00 : 효자1동   7440 ----------


 ---------- 2012-12-12 19:00:00 : 효자1동   7441 ----------


 ---------- 2012-12-13 07:00:00 : 후평1동   7442 ----------


 ---------- 2012-12-13 10:00:00 : 후평1동   7443 ----------


 ---------- 2012-12-14 09:00:00 : 신사우동   7444 ----------


 ---------- 2012-12-14 17:00:00 : 동산면   7447 ----------


 ---------- 2012-12-15 02:00:00 : 석사동   7448 ----------


 ---------- 2012-12-15 03:00:00 : 신사우동   7449 ----------


 ---------- 2012-12-15 12:00:00 : 동내면   7450 ----------


 ---------- 2012-12-15 16:00:00 : 퇴계동   7451 ----------


 ---------- 2012-12-16 07:00:00 : 강남동   7452 ----------


 ---------- 2012-12-16 09:00:00 : 북산면   7453 ----------


 ---------- 2012-12-16 10:00:00 : 퇴계동   7454 ----------


 ---------- 2012-12-16 11:00:00 : 사북면   7455 ----------


 ---------- 2012-12-16 14:00:00 : 사북면   7456 ----------


 ---------- 2012-12-16 21:00:00 : 강남동   7458 ----------


 ---------- 2012-12-17 01:00:00 : 효자1동   7460 ----------


 ---------- 2012-12-17 06:00:00 : 신사우동   7461 ----------


 ---------- 2012-12-17 21:00:00 : 석사동   7463 ----------


 ---------- 2012-12-18 03:00:00 : 강남동   7464 ----------


 ---------- 2012-12-18 07:00:00 : 효자1동   7465 ----------


 ---------- 2012-12-18 11:00:00 : 남산면   7466 ----------


 ---------- 2012-12-18 17:00:00 : 효자1동   7467 ----------


 ---------- 2012-12-18 18:00:00 : 강남동   7468 ----------


 ---------- 2012-12-19 11:00:00 : 후평1동   7470 ----------


 ---------- 2012-12-19 13:00:00 : 남산면   7472 ----------


 ---------- 2012-12-19 14:00:00 : 남산면   7473 ----------


 ---------- 2012-12-19 17:00:00 : 석사동   7474 ----------


 ---------- 2012-12-19 20:00:00 : 효자1동   7475 ----------


 ---------- 2012-12-20 00:00:00 : 남산면   7476 ----------


 ---------- 2012-12-20 09:00:00 : 조운동   7478 ----------


 ---------- 2012-12-20 14:00:00 : 동내면   7479 ----------


 ---------- 2012-12-20 17:00:00 : 효자1동   7480 ----------


 ---------- 2012-12-21 00:00:00 : 효자1동   7481 ----------


 ---------- 2012-12-21 10:00:00 : 남산면   7482 ----------


 ---------- 2012-12-22 01:00:00 : 교  동   7483 ----------


 ---------- 2012-12-22 02:00:00 : 근화동   7484 ----------


 ---------- 2012-12-22 17:00:00 : 근화동   7486 ----------


 ---------- 2012-12-22 21:00:00 : 퇴계동   7487 ----------


 ---------- 2012-12-23 04:00:00 : 효자1동   7488 ----------


 ---------- 2012-12-23 04:00:00 : 근화동   7489 ----------


 ---------- 2012-12-23 15:00:00 : 소양동   7490 ----------


 ---------- 2012-12-23 23:00:00 : 남산면   7491 ----------


 ---------- 2012-12-24 21:00:00 : 동내면   7492 ----------


 ---------- 2012-12-25 09:00:00 : 신북읍   7494 ----------


 ---------- 2012-12-26 10:00:00 : 효자1동   7495 ----------


 ---------- 2012-12-26 12:00:00 : 효자1동   7496 ----------


 ---------- 2012-12-26 14:00:00 : 석사동   7498 ----------


 ---------- 2012-12-26 15:00:00 : 소양동   7499 ----------


 ---------- 2012-12-26 15:00:00 : 퇴계동   7500 ----------


 ---------- 2012-12-26 18:00:00 : 효자1동   7501 ----------


 ---------- 2012-12-27 03:00:00 : 남산면   7502 ----------


 ---------- 2012-12-27 11:00:00 : 후평1동   7503 ----------


 ---------- 2012-12-27 19:00:00 : 근화동   7504 ----------


 ---------- 2012-12-28 02:00:00 : 강남동   7506 ----------


 ---------- 2012-12-29 03:00:00 : 효자1동   7507 ----------


 ---------- 2012-12-29 07:00:00 : 신북읍   7508 ----------


 ---------- 2012-12-29 10:00:00 : 후평1동   7509 ----------


 ---------- 2012-12-29 14:00:00 : 효자1동   7510 ----------


 ---------- 2012-12-29 19:00:00 : 동내면   7512 ----------


 ---------- 2012-12-30 08:00:00 : 효자1동   7513 ----------


 ---------- 2012-12-30 17:00:00 : 북산면   7514 ----------


 ---------- 2012-12-30 18:00:00 : 동내면   7516 ----------


 ---------- 2012-12-31 11:00:00 : 신동면   7517 ----------


 ---------- 2012-12-31 15:00:00 : 소양동   7518 ----------


 ---------- 2012-12-31 15:00:00 : 후평1동   7519 ----------


 ---------- 2012-12-31 16:00:00 : 퇴계동   7520 ----------


 ---------- 2012-12-31 21:00:00 : 효자1동   7521 ----------


 ---------- 2012-12-31 23:00:00 : 효자1동   7522 ----------


 ---------- 2013-01-01 09:00:00 : 퇴계동   7524 ----------


 ---------- 2013-01-01 10:00:00 : 신동면   7525 ----------


 ---------- 2013-01-01 11:00:00 : 퇴계동   7527 ----------


 ---------- 2013-01-01 12:00:00 : 효자1동   7528 ----------


 ---------- 2013-01-01 16:00:00 : 소양동   7530 ----------


 ---------- 2013-01-02 15:00:00 : 석사동   7532 ----------


 ---------- 2013-01-02 20:00:00 : 효자1동   7534 ----------


 ---------- 2013-01-02 21:00:00 : 강남동   7535 ----------


 ---------- 2013-01-04 00:00:00 : 석사동   7536 ----------


 ---------- 2013-01-04 01:00:00 : 동내면   7538 ----------


 ---------- 2013-01-04 04:00:00 : 후평1동   7539 ----------


 ---------- 2013-01-04 07:00:00 : 강남동   7540 ----------


 ---------- 2013-01-04 08:00:00 : 신북읍   7541 ----------


 ---------- 2013-01-04 11:00:00 : 효자1동   7543 ----------


 ---------- 2013-01-04 12:00:00 : 신북읍   7544 ----------


 ---------- 2013-01-04 13:00:00 : 근화동   7545 ----------


 ---------- 2013-01-04 16:00:00 : 신북읍   7547 ----------


 ---------- 2013-01-04 16:00:00 : 퇴계동   7550 ----------


 ---------- 2013-01-04 19:00:00 : 후평1동   7551 ----------


 ---------- 2013-01-05 11:00:00 : 퇴계동   7552 ----------


 ---------- 2013-01-05 17:00:00 : 강남동   7554 ----------


 ---------- 2013-01-05 18:00:00 : 후평1동   7555 ----------


 ---------- 2013-01-06 03:00:00 : 후평1동   7556 ----------


 ---------- 2013-01-06 14:00:00 : 후평1동   7558 ----------


 ---------- 2013-01-06 15:00:00 : 퇴계동   7560 ----------


 ---------- 2013-01-07 00:00:00 : 후평1동   7561 ----------


 ---------- 2013-01-07 11:00:00 : 강남동   7562 ----------


 ---------- 2013-01-07 14:00:00 : 교  동   7563 ----------


 ---------- 2013-01-07 21:00:00 : 퇴계동   7564 ----------


 ---------- 2013-01-08 08:00:00 : 소양동   7566 ----------

 ---------- 2013-01-08 12:00:00 : 근화동   7568 ----------


 ---------- 2013-01-08 13:00:00 : 퇴계동   7569 ----------


 ---------- 2013-01-08 18:00:00 : 강남동   7570 ----------


 ---------- 2013-01-08 19:00:00 : 강남동   7571 ----------


 ---------- 2013-01-08 20:00:00 : 후평1동   7572 ----------


 ---------- 2013-01-08 21:00:00 : 석사동   7573 ----------


 ---------- 2013-01-08 22:00:00 : 석사동   7574 ----------


 ---------- 2013-01-08 23:00:00 : 석사동   7575 ----------


 ---------- 2013-01-09 09:00:00 : 소양동   7576 ----------


 ---------- 2013-01-09 10:00:00 : 석사동   7577 ----------


 ---------- 2013-01-09 19:00:00 : 효자1동   7579 ----------


 ---------- 2013-01-09 22:00:00 : 남산면   7583 ----------


 ---------- 2013-01-10 03:00:00 : 효자1동   7585 ----------


 ---------- 2013-01-10 08:00:00 : 신북읍   7586 ----------


 ---------- 2013-01-10 20:00:00 : 강남동   7587 ----------


 ---------- 2013-01-11 00:00:00 : 근화동   7588 ----------


 ---------- 2013-01-11 06:00:00 : 효자1동   7590 ----------


 ---------- 2013-01-11 09:00:00 : 후평1동   7591 ----------


 ---------- 2013-01-11 12:00:00 : 효자1동   7592 ----------


 ---------- 2013-01-11 18:00:00 : 신사우동   7593 ----------


 ---------- 2013-01-11 20:00:00 : 석사동   7594 ----------


 ---------- 2013-01-12 00:00:00 : 동내면   7597 ----------


 ---------- 2013-01-12 12:00:00 : 근화동   7599 ----------


 ---------- 2013-01-12 13:00:00 : 교  동   7600 ----------


 ---------- 2013-01-12 18:00:00 : 남산면   7603 ----------


 ---------- 2013-01-13 08:00:00 : 퇴계동   7604 ----------


 ---------- 2013-01-13 20:00:00 : 후평1동   7605 ----------


 ---------- 2013-01-14 08:00:00 : 후평1동   7606 ----------


 ---------- 2013-01-14 10:00:00 : 동산면   7608 ----------


 ---------- 2013-01-14 17:00:00 : 신동면   7609 ----------


 ---------- 2013-01-14 18:00:00 : 동내면   7611 ----------


 ---------- 2013-01-14 19:00:00 : 남산면   7613 ----------


 ---------- 2013-01-14 23:00:00 : 근화동   7614 ----------


 ---------- 2013-01-15 01:00:00 : 효자1동   7615 ----------


 ---------- 2013-01-15 10:00:00 : 사북면   7617 ----------


 ---------- 2013-01-15 20:00:00 : 후평1동   7618 ----------


 ---------- 2013-01-16 00:00:00 : 강남동   7619 ----------


 ---------- 2013-01-16 00:00:00 : 퇴계동   7620 ----------


 ---------- 2013-01-17 09:00:00 : 동  면   7621 ----------


 ---------- 2013-01-17 19:00:00 : 남산면   7624 ----------


 ---------- 2013-01-18 14:00:00 : 소양동   7625 ----------


 ---------- 2013-01-18 15:00:00 : 강남동   7626 ----------


 ---------- 2013-01-18 16:00:00 : 서  면   7630 ----------


 ---------- 2013-01-19 11:00:00 : 소양동   7632 ----------


 ---------- 2013-01-19 12:00:00 : 신북읍   7633 ----------


 ---------- 2013-01-19 17:00:00 : 남산면   7634 ----------


 ---------- 2013-01-19 19:00:00 : 후평1동   7635 ----------


 ---------- 2013-01-20 15:00:00 : 효자1동   7637 ----------


 ---------- 2013-01-20 19:00:00 : 조운동   7639 ----------


 ---------- 2013-01-20 21:00:00 : 후평1동   7640 ----------


 ---------- 2013-01-21 01:00:00 : 약사명동   7641 ----------


 ---------- 2013-01-21 08:00:00 : 사북면   7643 ----------


 ---------- 2013-01-21 09:00:00 : 동내면   7644 ----------


 ---------- 2013-01-21 10:00:00 : 동  면   7646 ----------


 ---------- 2013-01-21 11:00:00 : 석사동   7648 ----------


 ---------- 2013-01-21 11:00:00 : 효자1동   7650 ----------


 ---------- 2013-01-21 14:00:00 : 동  면   7651 ----------


 ---------- 2013-01-21 15:00:00 : 신북읍   7653 ----------


 ---------- 2013-01-21 19:00:00 : 소양동   7654 ----------


 ---------- 2013-01-21 19:00:00 : 후평1동   7656 ----------


 ---------- 2013-01-22 07:00:00 : 효자1동   7657 ----------


 ---------- 2013-01-22 08:00:00 : 신사우동   7659 ----------


 ---------- 2013-01-22 12:00:00 : 강남동   7660 ----------


 ---------- 2013-01-22 13:00:00 : 신사우동   7661 ----------


 ---------- 2013-01-22 19:00:00 : 동  면   7662 ----------


 ---------- 2013-01-22 20:00:00 : 석사동   7664 ----------


 ---------- 2013-01-23 03:00:00 : 동산면   7665 ----------


 ---------- 2013-01-23 09:00:00 : 신사우동   7666 ----------


 ---------- 2013-01-23 14:00:00 : 신사우동   7667 ----------


 ---------- 2013-01-23 22:00:00 : 동산면   7668 ----------


 ---------- 2013-01-24 04:00:00 : 동내면   7669 ----------


 ---------- 2013-01-25 10:00:00 : 퇴계동   7672 ----------


 ---------- 2013-01-25 11:00:00 : 소양동   7673 ----------


 ---------- 2013-01-25 17:00:00 : 석사동   7674 ----------


 ---------- 2013-01-26 04:00:00 : 후평1동   7675 ----------


 ---------- 2013-01-26 09:00:00 : 남산면   7677 ----------


 ---------- 2013-01-26 14:00:00 : 동  면   7678 ----------


 ---------- 2013-01-26 16:00:00 : 남산면   7679 ----------


 ---------- 2013-01-26 21:00:00 : 남산면   7680 ----------


 ---------- 2013-01-27 06:00:00 : 효자1동   7682 ----------


 ---------- 2013-01-27 10:00:00 : 퇴계동   7683 ----------


 ---------- 2013-01-27 15:00:00 : 효자1동   7684 ----------


 ---------- 2013-01-27 21:00:00 : 효자1동   7686 ----------


 ---------- 2013-01-27 23:00:00 : 후평1동   7687 ----------


 ---------- 2013-01-28 14:00:00 : 효자1동   7688 ----------


 ---------- 2013-01-29 09:00:00 : 신북읍   7689 ----------


 ---------- 2013-01-29 12:00:00 : 동내면   7690 ----------


 ---------- 2013-01-29 16:00:00 : 효자1동   7691 ----------


 ---------- 2013-01-29 23:00:00 : 동  면   7692 ----------


 ---------- 2013-01-30 08:00:00 : 후평1동   7693 ----------


 ---------- 2013-01-30 09:00:00 : 동  면   7695 ----------


 ---------- 2013-01-30 13:00:00 : 신사우동   7696 ----------


 ---------- 2013-01-30 15:00:00 : 신사우동   7697 ----------


 ---------- 2013-01-30 16:00:00 : 후평1동   7699 ----------


 ---------- 2013-01-30 17:00:00 : 약사명동   7700 ----------


 ---------- 2013-01-30 17:00:00 : 동산면   7703 ----------


 ---------- 2013-01-31 00:00:00 : 서  면   7704 ----------


 ---------- 2013-01-31 10:00:00 : 동  면   7705 ----------


 ---------- 2013-01-31 13:00:00 : 신사우동   7706 ----------


 ---------- 2013-01-31 16:00:00 : 북산면   7707 ----------


 ---------- 2013-01-31 22:00:00 : 석사동   7708 ----------


 ---------- 2013-02-01 12:00:00 : 소양동   7710 ----------


 ---------- 2013-02-01 13:00:00 : 후평1동   7712 ----------


 ---------- 2013-02-01 16:00:00 : 석사동   7714 ----------


 ---------- 2013-02-01 19:00:00 : 동내면   7716 ----------


 ---------- 2013-02-02 00:00:00 : 강남동   7717 ----------


 ---------- 2013-02-02 00:00:00 : 근화동   7719 ----------


 ---------- 2013-02-02 02:00:00 : 신사우동   7721 ----------


 ---------- 2013-02-02 03:00:00 : 남산면   7722 ----------


 ---------- 2013-02-02 06:00:00 : 동내면   7724 ----------


 ---------- 2013-02-02 06:00:00 : 효자1동   7725 ----------


 ---------- 2013-02-02 07:00:00 : 신동면   7726 ----------


 ---------- 2013-02-02 07:00:00 : 신사우동   7728 ----------


 ---------- 2013-02-02 07:00:00 : 신북읍   7730 ----------


 ---------- 2013-02-02 08:00:00 : 강남동   7732 ----------


 ---------- 2013-02-02 08:00:00 : 동내면   7734 ----------


 ---------- 2013-02-02 09:00:00 : 신사우동   7735 ----------


 ---------- 2013-02-02 10:00:00 : 신북읍   7736 ----------


 ---------- 2013-02-02 12:00:00 : 남산면   7737 ----------


 ---------- 2013-02-02 18:00:00 : 조운동   7738 ----------


 ---------- 2013-02-02 19:00:00 : 효자1동   7739 ----------


 ---------- 2013-02-03 06:00:00 : 강남동   7741 ----------


 ---------- 2013-02-03 13:00:00 : 서  면   7742 ----------


 ---------- 2013-02-05 01:00:00 : 후평1동   7744 ----------


 ---------- 2013-02-05 08:00:00 : 동내면   7746 ----------


 ---------- 2013-02-05 09:00:00 : 남산면   7747 ----------


 ---------- 2013-02-05 11:00:00 : 효자1동   7748 ----------


 ---------- 2013-02-05 14:00:00 : 석사동   7749 ----------


 ---------- 2013-02-05 15:00:00 : 신사우동   7751 ----------


 ---------- 2013-02-05 16:00:00 : 신사우동   7752 ----------


 ---------- 2013-02-06 11:00:00 : 동내면   7754 ----------


 ---------- 2013-02-06 17:00:00 : 약사명동   7755 ----------


 ---------- 2013-02-06 19:00:00 : 석사동   7756 ----------


 ---------- 2013-02-07 00:00:00 : 석사동   7758 ----------


 ---------- 2013-02-07 09:00:00 : 후평1동   7759 ----------


 ---------- 2013-02-07 21:00:00 : 효자1동   7760 ----------


 ---------- 2013-02-08 00:00:00 : 동내면   7761 ----------


 ---------- 2013-02-09 00:00:00 : 후평1동   7762 ----------

 ---------- 2013-02-09 15:00:00 : 강남동   7763 ----------


 ---------- 2013-02-09 17:00:00 : 효자1동   7764 ----------


 ---------- 2013-02-10 01:00:00 : 석사동   7765 ----------


 ---------- 2013-02-10 06:00:00 : 강남동   7766 ----------


 ---------- 2013-02-10 08:00:00 : 동산면   7768 ----------


 ---------- 2013-02-10 12:00:00 : 강남동   7769 ----------


 ---------- 2013-02-10 12:00:00 : 퇴계동   7770 ----------


 ---------- 2013-02-10 14:00:00 : 강남동   7771 ----------


 ---------- 2013-02-10 16:00:00 : 서  면   7773 ----------


 ---------- 2013-02-10 21:00:00 : 후평1동   7774 ----------


 ---------- 2013-02-11 12:00:00 : 강남동   7775 ----------


 ---------- 2013-02-11 12:00:00 : 후평1동   7777 ----------


 ---------- 2013-02-11 13:00:00 : 사북면   7779 ----------


 ---------- 2013-02-11 13:00:00 : 남산면   7780 ----------


 ---------- 2013-02-11 14:00:00 : 후평1동   7782 ----------


 ---------- 2013-02-11 15:00:00 : 서  면   7784 ----------


 ---------- 2013-02-11 15:00:00 : 남  면   7785 ----------


 ---------- 2013-02-11 15:00:00 : 북산면   7787 ----------


 ---------- 2013-02-11 20:00:00 : 신사우동   7788 ----------


 ---------- 2013-02-11 23:00:00 : 동  면   7789 ----------


 ---------- 2013-02-13 02:00:00 : 후평1동   7790 ----------


 ---------- 2013-02-13 07:00:00 : 후평1동   7791 ----------


 ---------- 2013-02-13 09:00:00 : 효자1동   7792 ----------


 ---------- 2013-02-13 11:00:00 : 동  면   7793 ----------


 ---------- 2013-02-13 16:00:00 : 강남동   7794 ----------


 ---------- 2013-02-14 23:00:00 : 남산면   7795 ----------


 ---------- 2013-02-15 10:00:00 : 소양동   7796 ----------


 ---------- 2013-02-16 01:00:00 : 후평1동   7797 ----------


 ---------- 2013-02-16 09:00:00 : 교  동   7799 ----------


 ---------- 2013-02-16 22:00:00 : 효자1동   7800 ----------


 ---------- 2013-02-17 13:00:00 : 퇴계동   7801 ----------


 ---------- 2013-02-17 14:00:00 : 효자1동   7803 ----------


 ---------- 2013-02-18 07:00:00 : 소양동   7804 ----------


 ---------- 2013-02-18 10:00:00 : 강남동   7806 ----------


 ---------- 2013-02-18 12:00:00 : 신북읍   7807 ----------


 ---------- 2013-02-18 13:00:00 : 후평1동   7808 ----------


 ---------- 2013-02-18 21:00:00 : 신북읍   7809 ----------


 ---------- 2013-02-19 08:00:00 : 효자1동   7810 ----------


 ---------- 2013-02-19 17:00:00 : 효자1동   7811 ----------


 ---------- 2013-02-19 22:00:00 : 신북읍   7813 ----------


 ---------- 2013-02-20 06:00:00 : 조운동   7814 ----------


 ---------- 2013-02-20 07:00:00 : 근화동   7815 ----------


 ---------- 2013-02-20 08:00:00 : 강남동   7816 ----------


 ---------- 2013-02-20 14:00:00 : 서  면   7818 ----------


 ---------- 2013-02-21 15:00:00 : 신동면   7820 ----------


 ---------- 2013-02-21 15:00:00 : 동산면   7821 ----------


 ---------- 2013-02-22 01:00:00 : 석사동   7823 ----------


 ---------- 2013-02-22 19:00:00 : 후평1동   7824 ----------


 ---------- 2013-02-23 01:00:00 : 효자1동   7825 ----------


 ---------- 2013-02-23 11:00:00 : 효자1동   7828 ----------


 ---------- 2013-02-23 14:00:00 : 남산면   7830 ----------


 ---------- 2013-02-23 14:00:00 : 교  동   7831 ----------


 ---------- 2013-02-23 15:00:00 : 조운동   7832 ----------


 ---------- 2013-02-24 21:00:00 : 신북읍   7833 ----------


 ---------- 2013-02-25 08:00:00 : 동산면   7835 ----------


 ---------- 2013-02-25 09:00:00 : 근화동   7836 ----------


 ---------- 2013-02-25 13:00:00 : 강남동   7837 ----------


 ---------- 2013-02-25 15:00:00 : 약사명동   7838 ----------


 ---------- 2013-02-26 03:00:00 : 석사동   7840 ----------


 ---------- 2013-02-26 21:00:00 : 퇴계동   7842 ----------


 ---------- 2013-02-27 10:00:00 : 신사우동   7843 ----------


 ---------- 2013-02-27 14:00:00 : 석사동   7844 ----------


 ---------- 2013-02-27 16:00:00 : 동내면   7845 ----------


 ---------- 2013-02-28 02:00:00 : 효자1동   7846 ----------


 ---------- 2013-02-28 12:00:00 : 서  면   7847 ----------


 ---------- 2013-02-28 20:00:00 : 동내면   7848 ----------


 ---------- 2013-03-01 01:00:00 : 석사동   7849 ----------


 ---------- 2013-03-01 09:00:00 : 후평1동   7851 ----------


 ---------- 2013-03-01 10:00:00 : 효자1동   7852 ----------


 ---------- 2013-03-01 12:00:00 : 후평1동   7854 ----------


 ---------- 2013-03-01 14:00:00 : 동  면   7855 ----------


 ---------- 2013-03-02 13:00:00 : 북산면   7856 ----------


 ---------- 2013-03-02 17:00:00 : 신동면   7858 ----------


 ---------- 2013-03-02 17:00:00 : 남  면   7860 ----------


 ---------- 2013-03-02 18:00:00 : 서  면   7861 ----------


 ---------- 2013-03-03 07:00:00 : 후평1동   7862 ----------


 ---------- 2013-03-03 19:00:00 : 효자1동   7863 ----------


 ---------- 2013-03-03 20:00:00 : 강남동   7865 ----------


 ---------- 2013-03-04 02:00:00 : 강남동   7866 ----------


 ---------- 2013-03-04 17:00:00 : 효자1동   7867 ----------


 ---------- 2013-03-04 22:00:00 : 석사동   7868 ----------


 ---------- 2013-03-05 13:00:00 : 동내면   7869 ----------


 ---------- 2013-03-06 10:00:00 : 소양동   7870 ----------


 ---------- 2013-03-06 15:00:00 : 신북읍   7871 ----------


 ---------- 2013-03-07 00:00:00 : 신사우동   7872 ----------


 ---------- 2013-03-07 01:00:00 : 신사우동   7874 ----------


 ---------- 2013-03-07 03:00:00 : 효자1동   7875 ----------


 ---------- 2013-03-07 06:00:00 : 동내면   7876 ----------


 ---------- 2013-03-07 13:00:00 : 근화동   7877 ----------


 ---------- 2013-03-08 14:00:00 : 동내면   7878 ----------


 ---------- 2013-03-08 16:00:00 : 효자1동   7879 ----------


 ---------- 2013-03-08 18:00:00 : 남산면   7880 ----------


 ---------- 2013-03-09 07:00:00 : 동산면   7881 ----------


 ---------- 2013-03-09 14:00:00 : 소양동   7882 ----------


 ---------- 2013-03-09 17:00:00 : 후평1동   7883 ----------


 ---------- 2013-03-09 19:00:00 : 신북읍   7885 ----------


 ---------- 2013-03-09 19:00:00 : 교  동   7886 ----------


 ---------- 2013-03-09 20:00:00 : 근화동   7887 ----------


 ---------- 2013-03-09 21:00:00 : 근화동   7888 ----------


 ---------- 2013-03-09 22:00:00 : 남산면   7890 ----------


 ---------- 2013-03-09 22:00:00 : 약사명동   7892 ----------


 ---------- 2013-03-10 03:00:00 : 신사우동   7893 ----------


 ---------- 2013-03-10 14:00:00 : 후평1동   7894 ----------


 ---------- 2013-03-10 21:00:00 : 근화동   7895 ----------


 ---------- 2013-03-11 00:00:00 : 효자1동   7896 ----------


 ---------- 2013-03-11 07:00:00 : 동내면   7897 ----------


 ---------- 2013-03-11 08:00:00 : 강남동   7898 ----------


 ---------- 2013-03-11 20:00:00 : 강남동   7900 ----------


 ---------- 2013-03-12 07:00:00 : 신사우동   7901 ----------


 ---------- 2013-03-12 16:00:00 : 신동면   7903 ----------


 ---------- 2013-03-12 17:00:00 : 신동면   7904 ----------


 ---------- 2013-03-13 08:00:00 : 석사동   7905 ----------


 ---------- 2013-03-13 09:00:00 : 석사동   7907 ----------


 ---------- 2013-03-14 03:00:00 : 신사우동   7908 ----------


 ---------- 2013-03-14 09:00:00 : 석사동   7910 ----------


 ---------- 2013-03-14 13:00:00 : 소양동   7912 ----------


 ---------- 2013-03-14 14:00:00 : 서  면   7915 ----------


 ---------- 2013-03-14 21:00:00 : 후평1동   7916 ----------


 ---------- 2013-03-15 14:00:00 : 근화동   7918 ----------


 ---------- 2013-03-15 21:00:00 : 후평1동   7919 ----------


 ---------- 2013-03-16 11:00:00 : 효자1동   7920 ----------


 ---------- 2013-03-16 14:00:00 : 남산면   7922 ----------


 ---------- 2013-03-16 18:00:00 : 남산면   7924 ----------


 ---------- 2013-03-16 18:00:00 : 후평1동   7926 ----------


 ---------- 2013-03-18 04:00:00 : 남  면   7927 ----------


 ---------- 2013-03-18 08:00:00 : 후평1동   7928 ----------


 ---------- 2013-03-18 12:00:00 : 남산면   7929 ----------


 ---------- 2013-03-18 20:00:00 : 강남동   7931 ----------


 ---------- 2013-03-19 12:00:00 : 강남동   7933 ----------


 ---------- 2013-03-19 18:00:00 : 석사동   7935 ----------


 ---------- 2013-03-19 20:00:00 : 남산면   7936 ----------


 ---------- 2013-03-20 02:00:00 : 강남동   7937 ----------


 ---------- 2013-03-20 09:00:00 : 후평1동   7938 ----------


 ---------- 2013-03-20 20:00:00 : 후평1동   7939 ----------


 ---------- 2013-03-21 08:00:00 : 동  면   7940 ----------


 ---------- 2013-03-21 19:00:00 : 강남동   7941 ----------


 ---------- 2013-03-21 19:00:00 : 남산면   7943 ----------


 ---------- 2013-03-21 21:00:00 : 강남동   7944 ----------

 ---------- 2013-03-22 04:00:00 : 사북면   7946 ----------


 ---------- 2013-03-22 14:00:00 : 후평1동   7947 ----------


 ---------- 2013-03-23 00:00:00 : 서  면   7949 ----------


 ---------- 2013-03-23 12:00:00 : 효자1동   7950 ----------


 ---------- 2013-03-23 23:00:00 : 효자1동   7952 ----------


 ---------- 2013-03-24 09:00:00 : 남산면   7953 ----------


 ---------- 2013-03-24 11:00:00 : 석사동   7955 ----------


 ---------- 2013-03-24 12:00:00 : 후평1동   7956 ----------


 ---------- 2013-03-24 13:00:00 : 남산면   7957 ----------


 ---------- 2013-03-24 21:00:00 : 동산면   7958 ----------


 ---------- 2013-03-25 06:00:00 : 석사동   7960 ----------


 ---------- 2013-03-25 09:00:00 : 강남동   7961 ----------


 ---------- 2013-03-25 11:00:00 : 효자1동   7962 ----------


 ---------- 2013-03-25 18:00:00 : 효자1동   7964 ----------


 ---------- 2013-03-25 21:00:00 : 신북읍   7965 ----------


 ---------- 2013-03-26 08:00:00 : 동  면   7966 ----------


 ---------- 2013-03-27 04:00:00 : 효자1동   7967 ----------


 ---------- 2013-03-27 06:00:00 : 효자1동   7968 ----------


 ---------- 2013-03-27 15:00:00 : 사북면   7970 ----------


 ---------- 2013-03-27 16:00:00 : 신사우동   7971 ----------


 ---------- 2013-03-27 17:00:00 : 후평1동   7972 ----------


 ---------- 2013-03-27 18:00:00 : 후평1동   7973 ----------


 ---------- 2013-03-27 19:00:00 : 효자1동   7974 ----------


 ---------- 2013-03-28 01:00:00 : 동내면   7976 ----------


 ---------- 2013-03-28 14:00:00 : 동산면   7978 ----------


 ---------- 2013-03-28 15:00:00 : 효자1동   7979 ----------


 ---------- 2013-03-28 15:00:00 : 신사우동   7980 ----------


 ---------- 2013-03-28 22:00:00 : 퇴계동   7981 ----------


 ---------- 2013-03-29 01:00:00 : 조운동   7982 ----------


 ---------- 2013-03-29 08:00:00 : 동  면   7983 ----------


 ---------- 2013-03-29 12:00:00 : 신사우동   7984 ----------


 ---------- 2013-03-29 12:00:00 : 신북읍   7985 ----------


 ---------- 2013-03-30 00:00:00 : 동내면   7987 ----------


 ---------- 2013-03-30 05:00:00 : 남산면   7988 ----------


 ---------- 2013-03-30 09:00:00 : 동  면   7989 ----------


 ---------- 2013-03-30 11:00:00 : 후평1동   7990 ----------


 ---------- 2013-03-30 15:00:00 : 후평1동   7991 ----------


 ---------- 2013-03-30 20:00:00 : 신사우동   7993 ----------


 ---------- 2013-03-30 20:00:00 : 동  면   7994 ----------


 ---------- 2013-03-30 21:00:00 : 남산면   7996 ----------


 ---------- 2013-03-31 09:00:00 : 석사동   7997 ----------


 ---------- 2013-03-31 14:00:00 : 효자1동   7998 ----------


 ---------- 2013-03-31 15:00:00 : 효자1동   7999 ----------


 ---------- 2013-03-31 16:00:00 : 교  동   8000 ----------


 ---------- 2013-03-31 22:00:00 : 신북읍   8001 ----------


 ---------- 2013-04-01 08:00:00 : 조운동   8002 ----------


 ---------- 2013-04-01 13:00:00 : 신동면   8003 ----------


 ---------- 2013-04-01 13:00:00 : 효자1동   8004 ----------


 ---------- 2013-04-01 17:00:00 : 석사동   8007 ----------


 ---------- 2013-04-01 17:00:00 : 퇴계동   8009 ----------


 ---------- 2013-04-02 00:00:00 : 효자1동   8011 ----------


 ---------- 2013-04-02 02:00:00 : 강남동   8012 ----------


 ---------- 2013-04-02 02:00:00 : 신사우동   8013 ----------


 ---------- 2013-04-02 09:00:00 : 서  면   8014 ----------


 ---------- 2013-04-02 16:00:00 : 남산면   8015 ----------


 ---------- 2013-04-02 16:00:00 : 후평1동   8016 ----------


 ---------- 2013-04-02 23:00:00 : 퇴계동   8017 ----------


 ---------- 2013-04-03 03:00:00 : 석사동   8018 ----------


 ---------- 2013-04-04 17:00:00 : 교  동   8019 ----------


 ---------- 2013-04-04 20:00:00 : 동내면   8020 ----------


 ---------- 2013-04-04 20:00:00 : 동  면   8021 ----------


 ---------- 2013-04-05 00:00:00 : 신사우동   8022 ----------


 ---------- 2013-04-05 05:00:00 : 효자1동   8023 ----------


 ---------- 2013-04-05 20:00:00 : 퇴계동   8025 ----------


 ---------- 2013-04-06 21:00:00 : 강남동   8026 ----------


 ---------- 2013-04-07 15:00:00 : 남산면   8029 ----------


 ---------- 2013-04-07 15:00:00 : 동  면   8032 ----------


 ---------- 2013-04-07 18:00:00 : 신동면   8033 ----------


 ---------- 2013-04-07 18:00:00 : 동  면   8034 ----------


 ---------- 2013-04-07 19:00:00 : 석사동   8036 ----------


 ---------- 2013-04-09 01:00:00 : 남산면   8037 ----------


 ---------- 2013-04-09 08:00:00 : 석사동   8040 ----------


 ---------- 2013-04-09 23:00:00 : 소양동   8041 ----------


 ---------- 2013-04-10 07:00:00 : 후평1동   8043 ----------


 ---------- 2013-04-10 08:00:00 : 석사동   8044 ----------


 ---------- 2013-04-10 14:00:00 : 석사동   8046 ----------


 ---------- 2013-04-10 16:00:00 : 동내면   8047 ----------


 ---------- 2013-04-11 10:00:00 : 강남동   8048 ----------


 ---------- 2013-04-11 21:00:00 : 신북읍   8049 ----------


 ---------- 2013-04-12 07:00:00 : 강남동   8051 ----------


 ---------- 2013-04-12 09:00:00 : 신북읍   8052 ----------


 ---------- 2013-04-12 12:00:00 : 남산면   8053 ----------


 ---------- 2013-04-12 14:00:00 : 강남동   8054 ----------


 ---------- 2013-04-12 14:00:00 : 동산면   8055 ----------


 ---------- 2013-04-12 19:00:00 : 동  면   8057 ----------


 ---------- 2013-04-13 06:00:00 : 신북읍   8058 ----------


 ---------- 2013-04-13 10:00:00 : 강남동   8060 ----------


 ---------- 2013-04-13 11:00:00 : 후평1동   8061 ----------


 ---------- 2013-04-13 13:00:00 : 서  면   8063 ----------


 ---------- 2013-04-13 13:00:00 : 근화동   8064 ----------


 ---------- 2013-04-14 00:00:00 : 퇴계동   8066 ----------


 ---------- 2013-04-14 13:00:00 : 북산면   8070 ----------


 ---------- 2013-04-14 20:00:00 : 강남동   8072 ----------


 ---------- 2013-04-14 20:00:00 : 북산면   8073 ----------


 ---------- 2013-04-14 20:00:00 : 조운동   8074 ----------


 ---------- 2013-04-15 16:00:00 : 후평1동   8075 ----------


 ---------- 2013-04-15 22:00:00 : 사북면   8077 ----------


 ---------- 2013-04-15 23:00:00 : 소양동   8079 ----------


 ---------- 2013-04-16 03:00:00 : 강남동   8080 ----------


 ---------- 2013-04-16 06:00:00 : 신사우동   8082 ----------


 ---------- 2013-04-16 09:00:00 : 동  면   8083 ----------


 ---------- 2013-04-17 16:00:00 : 근화동   8084 ----------


 ---------- 2013-04-18 07:00:00 : 후평1동   8085 ----------


 ---------- 2013-04-18 11:00:00 : 석사동   8086 ----------


 ---------- 2013-04-18 17:00:00 : 신사우동   8087 ----------


 ---------- 2013-04-18 21:00:00 : 퇴계동   8088 ----------


 ---------- 2013-04-19 05:00:00 : 신북읍   8089 ----------


 ---------- 2013-04-19 09:00:00 : 서  면   8090 ----------


 ---------- 2013-04-19 14:00:00 : 신북읍   8091 ----------


 ---------- 2013-04-19 16:00:00 : 동  면   8092 ----------


 ---------- 2013-04-19 18:00:00 : 서  면   8093 ----------


 ---------- 2013-04-20 09:00:00 : 강남동   8094 ----------


 ---------- 2013-04-20 11:00:00 : 소양동   8095 ----------


 ---------- 2013-04-20 18:00:00 : 북산면   8096 ----------


 ---------- 2013-04-20 19:00:00 : 동산면   8097 ----------


 ---------- 2013-04-21 08:00:00 : 서  면   8098 ----------


 ---------- 2013-04-21 12:00:00 : 북산면   8101 ----------


 ---------- 2013-04-21 13:00:00 : 북산면   8102 ----------


 ---------- 2013-04-21 20:00:00 : 교  동   8103 ----------


 ---------- 2013-04-21 21:00:00 : 동  면   8104 ----------


 ---------- 2013-04-21 23:00:00 : 효자1동   8105 ----------


 ---------- 2013-04-22 10:00:00 : 조운동   8106 ----------


 ---------- 2013-04-22 16:00:00 : 동  면   8107 ----------


 ---------- 2013-04-22 20:00:00 : 석사동   8108 ----------


 ---------- 2013-04-23 08:00:00 : 후평1동   8109 ----------


 ---------- 2013-04-23 10:00:00 : 근화동   8111 ----------


 ---------- 2013-04-23 16:00:00 : 북산면   8113 ----------


 ---------- 2013-04-23 18:00:00 : 남산면   8114 ----------


 ---------- 2013-04-23 22:00:00 : 남산면   8115 ----------


 ---------- 2013-04-24 03:00:00 : 동내면   8116 ----------


 ---------- 2013-04-24 08:00:00 : 후평1동   8117 ----------


 ---------- 2013-04-24 13:00:00 : 석사동   8118 ----------


 ---------- 2013-04-24 23:00:00 : 동산면   8119 ----------


 ---------- 2013-04-25 07:00:00 : 석사동   8121 ----------


 ---------- 2013-04-25 18:00:00 : 효자1동   8122 ----------


 ---------- 2013-04-25 18:00:00 : 동  면   8123 ----------


 ---------- 2013-04-26 11:00:00 : 석사동   8125 ----------


 ---------- 2013-04-26 17:00:00 : 남산면   8126 ----------

 ---------- 2013-04-27 00:00:00 : 신북읍   8127 ----------


 ---------- 2013-04-27 15:00:00 : 신동면   8128 ----------


 ---------- 2013-04-28 13:00:00 : 북산면   8131 ----------


 ---------- 2013-04-28 17:00:00 : 남산면   8132 ----------


 ---------- 2013-04-29 01:00:00 : 석사동   8133 ----------


 ---------- 2013-04-29 08:00:00 : 효자1동   8135 ----------


 ---------- 2013-04-29 17:00:00 : 효자1동   8136 ----------


 ---------- 2013-04-29 17:00:00 : 남산면   8137 ----------


 ---------- 2013-04-29 19:00:00 : 후평1동   8139 ----------


 ---------- 2013-04-30 12:00:00 : 서  면   8140 ----------


 ---------- 2013-04-30 13:00:00 : 동  면   8141 ----------


 ---------- 2013-04-30 16:00:00 : 신사우동   8143 ----------


 ---------- 2013-05-01 15:00:00 : 동  면   8144 ----------


 ---------- 2013-05-01 22:00:00 : 신사우동   8145 ----------


 ---------- 2013-05-02 03:00:00 : 동  면   8146 ----------


 ---------- 2013-05-02 08:00:00 : 동  면   8147 ----------


 ---------- 2013-05-02 10:00:00 : 동  면   8148 ----------


 ---------- 2013-05-02 20:00:00 : 석사동   8150 ----------


 ---------- 2013-05-03 12:00:00 : 후평1동   8152 ----------


 ---------- 2013-05-03 16:00:00 : 남산면   8155 ----------


 ---------- 2013-05-03 20:00:00 : 강남동   8156 ----------


 ---------- 2013-05-04 07:00:00 : 신사우동   8157 ----------


 ---------- 2013-05-04 09:00:00 : 남  면   8158 ----------


 ---------- 2013-05-04 11:00:00 : 소양동   8159 ----------


 ---------- 2013-05-04 23:00:00 : 근화동   8161 ----------


 ---------- 2013-05-05 00:00:00 : 동산면   8163 ----------


 ---------- 2013-05-05 01:00:00 : 후평1동   8164 ----------


 ---------- 2013-05-05 02:00:00 : 신사우동   8165 ----------


 ---------- 2013-05-05 03:00:00 : 강남동   8166 ----------


 ---------- 2013-05-05 05:00:00 : 소양동   8167 ----------


 ---------- 2013-05-05 06:00:00 : 동내면   8168 ----------


 ---------- 2013-05-05 16:00:00 : 남산면   8169 ----------


 ---------- 2013-05-06 13:00:00 : 퇴계동   8171 ----------


 ---------- 2013-05-06 14:00:00 : 동  면   8172 ----------


 ---------- 2013-05-06 18:00:00 : 근화동   8173 ----------


 ---------- 2013-05-07 14:00:00 : 강남동   8174 ----------


 ---------- 2013-05-07 17:00:00 : 석사동   8176 ----------


 ---------- 2013-05-07 17:00:00 : 후평1동   8178 ----------


 ---------- 2013-05-07 18:00:00 : 신사우동   8179 ----------


 ---------- 2013-05-07 22:00:00 : 교  동   8180 ----------


 ---------- 2013-05-07 23:00:00 : 후평1동   8181 ----------


 ---------- 2013-05-08 17:00:00 : 후평1동   8182 ----------


 ---------- 2013-05-09 13:00:00 : 강남동   8183 ----------


 ---------- 2013-05-09 15:00:00 : 남산면   8184 ----------


 ---------- 2013-05-10 11:00:00 : 소양동   8185 ----------


 ---------- 2013-05-10 16:00:00 : 석사동   8186 ----------


 ---------- 2013-05-10 16:00:00 : 강남동   8187 ----------


 ---------- 2013-05-11 01:00:00 : 후평1동   8188 ----------


 ---------- 2013-05-11 03:00:00 : 석사동   8190 ----------


 ---------- 2013-05-11 13:00:00 : 석사동   8192 ----------


 ---------- 2013-05-11 23:00:00 : 동내면   8193 ----------


 ---------- 2013-05-12 08:00:00 : 동  면   8195 ----------


 ---------- 2013-05-12 11:00:00 : 남산면   8199 ----------


 ---------- 2013-05-12 12:00:00 : 근화동   8200 ----------


 ---------- 2013-05-12 17:00:00 : 서  면   8202 ----------


 ---------- 2013-05-14 08:00:00 : 신사우동   8204 ----------


 ---------- 2013-05-14 11:00:00 : 퇴계동   8205 ----------


 ---------- 2013-05-14 12:00:00 : 남산면   8206 ----------


 ---------- 2013-05-14 12:00:00 : 소양동   8207 ----------


 ---------- 2013-05-14 16:00:00 : 후평1동   8208 ----------


 ---------- 2013-05-14 17:00:00 : 서  면   8209 ----------


 ---------- 2013-05-14 18:00:00 : 후평1동   8210 ----------


 ---------- 2013-05-14 20:00:00 : 근화동   8211 ----------


 ---------- 2013-05-15 00:00:00 : 효자1동   8212 ----------


 ---------- 2013-05-15 03:00:00 : 퇴계동   8213 ----------


 ---------- 2013-05-15 07:00:00 : 후평1동   8215 ----------


 ---------- 2013-05-15 11:00:00 : 효자1동   8217 ----------


 ---------- 2013-05-15 18:00:00 : 효자1동   8219 ----------


 ---------- 2013-05-15 21:00:00 : 강남동   8221 ----------


 ---------- 2013-05-16 07:00:00 : 근화동   8222 ----------


 ---------- 2013-05-16 17:00:00 : 동내면   8223 ----------


 ---------- 2013-05-17 16:00:00 : 신사우동   8224 ----------


 ---------- 2013-05-17 16:00:00 : 소양동   8225 ----------


 ---------- 2013-05-17 20:00:00 : 효자1동   8227 ----------


 ---------- 2013-05-17 22:00:00 : 서  면   8228 ----------


 ---------- 2013-05-18 13:00:00 : 동산면   8229 ----------


 ---------- 2013-05-18 18:00:00 : 동내면   8230 ----------


 ---------- 2013-05-18 21:00:00 : 동산면   8232 ----------


 ---------- 2013-05-19 00:00:00 : 근화동   8233 ----------


 ---------- 2013-05-19 01:00:00 : 효자1동   8234 ----------


 ---------- 2013-05-19 13:00:00 : 신북읍   8237 ----------


 ---------- 2013-05-19 17:00:00 : 퇴계동   8238 ----------


 ---------- 2013-05-20 11:00:00 : 근화동   8240 ----------


 ---------- 2013-05-20 15:00:00 : 서  면   8243 ----------


 ---------- 2013-05-20 18:00:00 : 후평1동   8244 ----------


 ---------- 2013-05-21 00:00:00 : 효자1동   8245 ----------


 ---------- 2013-05-21 09:00:00 : 신사우동   8246 ----------


 ---------- 2013-05-21 17:00:00 : 남  면   8247 ----------


 ---------- 2013-05-21 17:00:00 : 근화동   8248 ----------


 ---------- 2013-05-21 21:00:00 : 후평1동   8250 ----------


 ---------- 2013-05-21 23:00:00 : 동  면   8252 ----------


 ---------- 2013-05-22 18:00:00 : 퇴계동   8253 ----------


 ---------- 2013-05-23 01:00:00 : 효자1동   8254 ----------


 ---------- 2013-05-23 09:00:00 : 소양동   8255 ----------


 ---------- 2013-05-23 13:00:00 : 동산면   8256 ----------


 ---------- 2013-05-23 16:00:00 : 효자1동   8257 ----------


 ---------- 2013-05-23 19:00:00 : 석사동   8258 ----------


 ---------- 2013-05-24 01:00:00 : 교  동   8259 ----------


 ---------- 2013-05-24 08:00:00 : 남  면   8260 ----------


 ---------- 2013-05-25 01:00:00 : 석사동   8261 ----------


 ---------- 2013-05-25 06:00:00 : 사북면   8262 ----------


 ---------- 2013-05-25 12:00:00 : 효자1동   8263 ----------


 ---------- 2013-05-25 13:00:00 : 석사동   8264 ----------


 ---------- 2013-05-25 13:00:00 : 강남동   8265 ----------


 ---------- 2013-05-26 03:00:00 : 남산면   8266 ----------


 ---------- 2013-05-26 10:00:00 : 서  면   8268 ----------


 ---------- 2013-05-26 12:00:00 : 서  면   8270 ----------


 ---------- 2013-05-26 13:00:00 : 소양동   8271 ----------


 ---------- 2013-05-26 15:00:00 : 신북읍   8272 ----------


 ---------- 2013-05-26 16:00:00 : 효자1동   8273 ----------


 ---------- 2013-05-26 20:00:00 : 동산면   8278 ----------


 ---------- 2013-05-26 21:00:00 : 퇴계동   8279 ----------


 ---------- 2013-05-27 02:00:00 : 퇴계동   8280 ----------


 ---------- 2013-05-27 08:00:00 : 신동면   8283 ----------


 ---------- 2013-05-27 09:00:00 : 후평1동   8284 ----------


 ---------- 2013-05-27 12:00:00 : 동  면   8285 ----------


 ---------- 2013-05-27 15:00:00 : 남산면   8286 ----------


 ---------- 2013-05-27 16:00:00 : 후평1동   8288 ----------


 ---------- 2013-05-27 20:00:00 : 후평1동   8289 ----------


 ---------- 2013-05-27 23:00:00 : 동산면   8290 ----------


 ---------- 2013-05-28 04:00:00 : 동내면   8291 ----------


 ---------- 2013-05-28 18:00:00 : 신동면   8293 ----------


 ---------- 2013-05-28 23:00:00 : 후평1동   8294 ----------


 ---------- 2013-05-29 09:00:00 : 교  동   8295 ----------


 ---------- 2013-05-29 13:00:00 : 근화동   8296 ----------


 ---------- 2013-05-29 13:00:00 : 소양동   8297 ----------


 ---------- 2013-05-29 15:00:00 : 서  면   8299 ----------


 ---------- 2013-05-29 16:00:00 : 동산면   8301 ----------


 ---------- 2013-05-30 00:00:00 : 약사명동   8302 ----------


 ---------- 2013-05-30 01:00:00 : 근화동   8304 ----------


 ---------- 2013-05-30 11:00:00 : 석사동   8305 ----------


 ---------- 2013-05-30 14:00:00 : 퇴계동   8306 ----------


 ---------- 2013-05-30 15:00:00 : 효자1동   8308 ----------


 ---------- 2013-05-30 18:00:00 : 강남동   8309 ----------


 ---------- 2013-05-31 08:00:00 : 약사명동   8310 ----------


 ---------- 2013-06-01 03:00:00 : 약사명동   8311 ----------


 ---------- 2013-06-01 14:00:00 : 동  면   8312 ----------


 ---------- 2013-06-01 16:00:00 : 서  면   8315 ----------

 ---------- 2013-06-01 17:00:00 : 신북읍   8316 ----------


 ---------- 2013-06-02 10:00:00 : 동내면   8318 ----------


 ---------- 2013-06-02 14:00:00 : 소양동   8319 ----------


 ---------- 2013-06-02 20:00:00 : 신사우동   8321 ----------


 ---------- 2013-06-02 21:00:00 : 서  면   8324 ----------


 ---------- 2013-06-03 01:00:00 : 후평1동   8325 ----------


 ---------- 2013-06-03 04:00:00 : 교  동   8326 ----------


 ---------- 2013-06-03 13:00:00 : 효자1동   8327 ----------


 ---------- 2013-06-05 09:00:00 : 강남동   8328 ----------


 ---------- 2013-06-05 11:00:00 : 근화동   8329 ----------


 ---------- 2013-06-05 13:00:00 : 북산면   8330 ----------


 ---------- 2013-06-05 15:00:00 : 남산면   8331 ----------


 ---------- 2013-06-06 04:00:00 : 후평1동   8332 ----------


 ---------- 2013-06-06 08:00:00 : 석사동   8333 ----------


 ---------- 2013-06-06 08:00:00 : 교  동   8335 ----------


 ---------- 2013-06-06 14:00:00 : 신동면   8336 ----------


 ---------- 2013-06-06 21:00:00 : 신동면   8337 ----------


 ---------- 2013-06-07 09:00:00 : 석사동   8338 ----------


 ---------- 2013-06-07 09:00:00 : 후평1동   8339 ----------


 ---------- 2013-06-07 15:00:00 : 동  면   8340 ----------


 ---------- 2013-06-07 22:00:00 : 소양동   8341 ----------


 ---------- 2013-06-08 02:00:00 : 동내면   8342 ----------


 ---------- 2013-06-08 02:00:00 : 남산면   8343 ----------


 ---------- 2013-06-08 09:00:00 : 신사우동   8344 ----------


 ---------- 2013-06-08 09:00:00 : 동  면   8345 ----------


 ---------- 2013-06-08 11:00:00 : 후평1동   8346 ----------


 ---------- 2013-06-08 15:00:00 : 신사우동   8347 ----------


 ---------- 2013-06-08 19:00:00 : 북산면   8348 ----------


 ---------- 2013-06-09 11:00:00 : 신동면   8349 ----------


 ---------- 2013-06-09 13:00:00 : 북산면   8353 ----------


 ---------- 2013-06-09 19:00:00 : 후평1동   8354 ----------


 ---------- 2013-06-10 00:00:00 : 신북읍   8355 ----------


 ---------- 2013-06-10 05:00:00 : 퇴계동   8356 ----------


 ---------- 2013-06-10 14:00:00 : 사북면   8357 ----------


 ---------- 2013-06-10 23:00:00 : 후평1동   8358 ----------


 ---------- 2013-06-11 10:00:00 : 강남동   8359 ----------


 ---------- 2013-06-11 10:00:00 : 소양동   8360 ----------


 ---------- 2013-06-11 12:00:00 : 석사동   8361 ----------


 ---------- 2013-06-11 13:00:00 : 퇴계동   8362 ----------


 ---------- 2013-06-12 08:00:00 : 남  면   8363 ----------


 ---------- 2013-06-13 10:00:00 : 퇴계동   8364 ----------


 ---------- 2013-06-13 13:00:00 : 후평1동   8365 ----------


 ---------- 2013-06-13 17:00:00 : 남산면   8367 ----------


 ---------- 2013-06-13 18:00:00 : 북산면   8368 ----------


 ---------- 2013-06-13 20:00:00 : 석사동   8370 ----------


 ---------- 2013-06-14 00:00:00 : 근화동   8372 ----------


 ---------- 2013-06-14 01:00:00 : 후평1동   8373 ----------


 ---------- 2013-06-14 07:00:00 : 남  면   8374 ----------


 ---------- 2013-06-14 12:00:00 : 동내면   8375 ----------


 ---------- 2013-06-14 12:00:00 : 후평1동   8377 ----------


 ---------- 2013-06-14 13:00:00 : 남산면   8378 ----------


 ---------- 2013-06-14 14:00:00 : 효자1동   8379 ----------


 ---------- 2013-06-14 14:00:00 : 조운동   8380 ----------


 ---------- 2013-06-14 15:00:00 : 효자1동   8381 ----------


 ---------- 2013-06-14 20:00:00 : 근화동   8382 ----------


 ---------- 2013-06-15 00:00:00 : 신북읍   8383 ----------


 ---------- 2013-06-15 01:00:00 : 후평1동   8385 ----------


 ---------- 2013-06-15 02:00:00 : 효자1동   8386 ----------


 ---------- 2013-06-15 05:00:00 : 동내면   8389 ----------


 ---------- 2013-06-15 06:00:00 : 동산면   8390 ----------


 ---------- 2013-06-15 07:00:00 : 효자1동   8391 ----------


 ---------- 2013-06-15 08:00:00 : 신사우동   8394 ----------


 ---------- 2013-06-15 15:00:00 : 소양동   8395 ----------


 ---------- 2013-06-16 10:00:00 : 신사우동   8396 ----------


 ---------- 2013-06-16 15:00:00 : 남  면   8397 ----------


 ---------- 2013-06-16 16:00:00 : 신동면   8399 ----------


 ---------- 2013-06-17 16:00:00 : 남산면   8400 ----------


 ---------- 2013-06-17 20:00:00 : 효자1동   8401 ----------


 ---------- 2013-06-17 23:00:00 : 근화동   8403 ----------


 ---------- 2013-06-18 05:00:00 : 강남동   8404 ----------


 ---------- 2013-06-18 10:00:00 : 후평1동   8405 ----------


 ---------- 2013-06-18 12:00:00 : 석사동   8406 ----------


 ---------- 2013-06-18 12:00:00 : 효자1동   8407 ----------


 ---------- 2013-06-18 13:00:00 : 석사동   8408 ----------


 ---------- 2013-06-18 14:00:00 : 강남동   8409 ----------


 ---------- 2013-06-18 14:00:00 : 남산면   8410 ----------


 ---------- 2013-06-19 09:00:00 : 효자1동   8411 ----------


 ---------- 2013-06-19 12:00:00 : 석사동   8412 ----------


 ---------- 2013-06-19 15:00:00 : 강남동   8413 ----------


 ---------- 2013-06-19 15:00:00 : 신북읍   8414 ----------


 ---------- 2013-06-19 19:00:00 : 교  동   8415 ----------


 ---------- 2013-06-19 21:00:00 : 효자1동   8416 ----------


 ---------- 2013-06-19 23:00:00 : 효자1동   8417 ----------


 ---------- 2013-06-20 01:00:00 : 효자1동   8419 ----------


 ---------- 2013-06-20 09:00:00 : 서  면   8420 ----------


 ---------- 2013-06-20 15:00:00 : 소양동   8421 ----------


 ---------- 2013-06-20 16:00:00 : 교  동   8422 ----------


 ---------- 2013-06-20 18:00:00 : 후평1동   8423 ----------


 ---------- 2013-06-20 22:00:00 : 효자1동   8424 ----------


 ---------- 2013-06-21 10:00:00 : 서  면   8425 ----------


 ---------- 2013-06-21 10:00:00 : 효자1동   8426 ----------


 ---------- 2013-06-21 13:00:00 : 신사우동   8427 ----------


 ---------- 2013-06-21 17:00:00 : 신사우동   8428 ----------


 ---------- 2013-06-22 00:00:00 : 효자1동   8429 ----------


 ---------- 2013-06-22 09:00:00 : 남산면   8430 ----------


 ---------- 2013-06-22 14:00:00 : 남산면   8431 ----------


 ---------- 2013-06-22 16:00:00 : 남산면   8434 ----------


 ---------- 2013-06-22 20:00:00 : 신북읍   8436 ----------


 ---------- 2013-06-22 21:00:00 : 약사명동   8438 ----------


 ---------- 2013-06-22 22:00:00 : 후평1동   8439 ----------


 ---------- 2013-06-23 01:00:00 : 신사우동   8440 ----------


 ---------- 2013-06-23 04:00:00 : 신북읍   8442 ----------


 ---------- 2013-06-23 05:00:00 : 남산면   8443 ----------


 ---------- 2013-06-23 13:00:00 : 동내면   8444 ----------


 ---------- 2013-06-23 14:00:00 : 효자1동   8445 ----------


 ---------- 2013-06-23 17:00:00 : 후평1동   8446 ----------


 ---------- 2013-06-23 23:00:00 : 석사동   8447 ----------


 ---------- 2013-06-24 10:00:00 : 석사동   8449 ----------


 ---------- 2013-06-24 10:00:00 : 효자1동   8450 ----------


 ---------- 2013-06-24 16:00:00 : 석사동   8451 ----------


 ---------- 2013-06-25 10:00:00 : 퇴계동   8452 ----------


 ---------- 2013-06-25 12:00:00 : 신동면   8453 ----------


 ---------- 2013-06-25 14:00:00 : 석사동   8454 ----------


 ---------- 2013-06-25 16:00:00 : 효자1동   8455 ----------


 ---------- 2013-06-25 20:00:00 : 후평1동   8456 ----------


 ---------- 2013-06-25 21:00:00 : 후평1동   8457 ----------


 ---------- 2013-06-25 22:00:00 : 후평1동   8459 ----------


 ---------- 2013-06-26 01:00:00 : 후평1동   8460 ----------


 ---------- 2013-06-26 09:00:00 : 소양동   8461 ----------


 ---------- 2013-06-26 13:00:00 : 신북읍   8462 ----------


 ---------- 2013-06-26 17:00:00 : 퇴계동   8463 ----------


 ---------- 2013-06-26 20:00:00 : 강남동   8464 ----------


 ---------- 2013-06-26 20:00:00 : 효자1동   8465 ----------


 ---------- 2013-06-26 20:00:00 : 동산면   8467 ----------


 ---------- 2013-06-27 02:00:00 : 후평1동   8468 ----------


 ---------- 2013-06-27 17:00:00 : 남산면   8469 ----------


 ---------- 2013-06-27 20:00:00 : 서  면   8471 ----------


 ---------- 2013-06-28 00:00:00 : 남  면   8472 ----------


 ---------- 2013-06-28 09:00:00 : 효자1동   8474 ----------


 ---------- 2013-06-28 19:00:00 : 신사우동   8475 ----------


 ---------- 2013-06-29 08:00:00 : 근화동   8476 ----------


 ---------- 2013-06-29 08:00:00 : 후평1동   8478 ----------


 ---------- 2013-06-29 09:00:00 : 동산면   8479 ----------


 ---------- 2013-06-29 10:00:00 : 신동면   8480 ----------


 ---------- 2013-06-29 12:00:00 : 퇴계동   8481 ----------


 ---------- 2013-06-30 05:00:00 : 조운동   8482 ----------


 ---------- 2013-06-30 11:00:00 : 석사동   8483 ----------


 ---------- 2013-06-30 12:00:00 : 신동면   8484 ----------

 ---------- 2013-06-30 13:00:00 : 신북읍   8487 ----------


 ---------- 2013-06-30 13:00:00 : 동  면   8488 ----------


 ---------- 2013-06-30 14:00:00 : 효자1동   8489 ----------


 ---------- 2013-06-30 16:00:00 : 동내면   8491 ----------


 ---------- 2013-07-01 08:00:00 : 효자1동   8492 ----------


 ---------- 2013-07-01 11:00:00 : 남산면   8493 ----------


 ---------- 2013-07-01 13:00:00 : 남산면   8494 ----------


 ---------- 2013-07-01 14:00:00 : 석사동   8495 ----------


 ---------- 2013-07-01 20:00:00 : 석사동   8498 ----------


 ---------- 2013-07-01 22:00:00 : 교  동   8499 ----------


 ---------- 2013-07-02 13:00:00 : 퇴계동   8500 ----------


 ---------- 2013-07-02 14:00:00 : 후평1동   8501 ----------


 ---------- 2013-07-02 19:00:00 : 신사우동   8502 ----------


 ---------- 2013-07-03 07:00:00 : 동내면   8503 ----------


 ---------- 2013-07-03 07:00:00 : 신북읍   8504 ----------


 ---------- 2013-07-03 08:00:00 : 남산면   8505 ----------


 ---------- 2013-07-03 10:00:00 : 동내면   8506 ----------


 ---------- 2013-07-03 14:00:00 : 석사동   8507 ----------


 ---------- 2013-07-03 14:00:00 : 퇴계동   8508 ----------


 ---------- 2013-07-03 18:00:00 : 북산면   8509 ----------


 ---------- 2013-07-03 21:00:00 : 석사동   8511 ----------


 ---------- 2013-07-03 22:00:00 : 근화동   8514 ----------


 ---------- 2013-07-03 22:00:00 : 동  면   8515 ----------


 ---------- 2013-07-04 11:00:00 : 석사동   8516 ----------


 ---------- 2013-07-04 11:00:00 : 신동면   8517 ----------


 ---------- 2013-07-04 16:00:00 : 퇴계동   8520 ----------


 ---------- 2013-07-05 00:00:00 : 남산면   8523 ----------


 ---------- 2013-07-05 11:00:00 : 석사동   8525 ----------


 ---------- 2013-07-05 12:00:00 : 효자1동   8526 ----------


 ---------- 2013-07-05 14:00:00 : 동내면   8527 ----------


 ---------- 2013-07-05 16:00:00 : 남산면   8530 ----------


 ---------- 2013-07-05 17:00:00 : 소양동   8531 ----------


 ---------- 2013-07-05 19:00:00 : 소양동   8532 ----------


 ---------- 2013-07-05 22:00:00 : 신북읍   8533 ----------


 ---------- 2013-07-06 01:00:00 : 신사우동   8535 ----------


 ---------- 2013-07-06 08:00:00 : 남산면   8536 ----------


 ---------- 2013-07-06 10:00:00 : 석사동   8537 ----------


 ---------- 2013-07-06 10:00:00 : 서  면   8538 ----------


 ---------- 2013-07-06 11:00:00 : 남  면   8539 ----------


 ---------- 2013-07-06 13:00:00 : 후평1동   8540 ----------


 ---------- 2013-07-06 14:00:00 : 강남동   8541 ----------


 ---------- 2013-07-06 14:00:00 : 퇴계동   8542 ----------


 ---------- 2013-07-06 15:00:00 : 신동면   8544 ----------


 ---------- 2013-07-06 16:00:00 : 남  면   8545 ----------


 ---------- 2013-07-07 13:00:00 : 강남동   8546 ----------


 ---------- 2013-07-07 15:00:00 : 신동면   8547 ----------


 ---------- 2013-07-07 16:00:00 : 신사우동   8548 ----------


 ---------- 2013-07-07 20:00:00 : 퇴계동   8549 ----------


 ---------- 2013-07-08 11:00:00 : 남  면   8551 ----------


 ---------- 2013-07-08 14:00:00 : 남  면   8554 ----------


 ---------- 2013-07-08 16:00:00 : 퇴계동   8556 ----------


 ---------- 2013-07-08 20:00:00 : 석사동   8558 ----------


 ---------- 2013-07-09 00:00:00 : 동  면   8560 ----------


 ---------- 2013-07-09 06:00:00 : 소양동   8561 ----------


 ---------- 2013-07-09 09:00:00 : 동내면   8562 ----------


 ---------- 2013-07-09 10:00:00 : 후평1동   8563 ----------


 ---------- 2013-07-09 14:00:00 : 근화동   8564 ----------


 ---------- 2013-07-09 19:00:00 : 석사동   8565 ----------


 ---------- 2013-07-09 19:00:00 : 신사우동   8566 ----------


 ---------- 2013-07-09 23:00:00 : 퇴계동   8568 ----------


 ---------- 2013-07-10 00:00:00 : 효자1동   8569 ----------


 ---------- 2013-07-10 08:00:00 : 후평1동   8570 ----------


 ---------- 2013-07-10 11:00:00 : 동  면   8571 ----------


 ---------- 2013-07-10 12:00:00 : 소양동   8572 ----------


 ---------- 2013-07-10 19:00:00 : 북산면   8574 ----------


 ---------- 2013-07-11 09:00:00 : 약사명동   8576 ----------


 ---------- 2013-07-11 18:00:00 : 퇴계동   8578 ----------


 ---------- 2013-07-12 05:00:00 : 북산면   8579 ----------


 ---------- 2013-07-12 06:00:00 : 서  면   8581 ----------


 ---------- 2013-07-12 09:00:00 : 효자1동   8582 ----------


 ---------- 2013-07-12 10:00:00 : 석사동   8583 ----------


 ---------- 2013-07-12 10:00:00 : 효자1동   8584 ----------


 ---------- 2013-07-12 16:00:00 : 소양동   8585 ----------


 ---------- 2013-07-12 20:00:00 : 석사동   8587 ----------


 ---------- 2013-07-13 06:00:00 : 동내면   8588 ----------


 ---------- 2013-07-13 06:00:00 : 교  동   8590 ----------


 ---------- 2013-07-13 10:00:00 : 효자1동   8591 ----------


 ---------- 2013-07-13 13:00:00 : 퇴계동   8592 ----------


 ---------- 2013-07-13 17:00:00 : 근화동   8593 ----------


 ---------- 2013-07-13 19:00:00 : 신동면   8594 ----------


 ---------- 2013-07-13 20:00:00 : 석사동   8595 ----------


 ---------- 2013-07-14 07:00:00 : 석사동   8596 ----------


 ---------- 2013-07-14 08:00:00 : 신북읍   8597 ----------


 ---------- 2013-07-14 08:00:00 : 후평1동   8598 ----------


 ---------- 2013-07-14 08:00:00 : 퇴계동   8600 ----------


 ---------- 2013-07-14 09:00:00 : 신동면   8601 ----------


 ---------- 2013-07-14 09:00:00 : 강남동   8602 ----------


 ---------- 2013-07-14 09:00:00 : 남산면   8605 ----------


 ---------- 2013-07-14 09:00:00 : 근화동   8606 ----------


 ---------- 2013-07-14 09:00:00 : 소양동   8607 ----------


 ---------- 2013-07-14 09:00:00 : 퇴계동   8608 ----------


 ---------- 2013-07-14 10:00:00 : 동내면   8609 ----------


 ---------- 2013-07-14 10:00:00 : 남산면   8612 ----------


 ---------- 2013-07-14 10:00:00 : 신사우동   8613 ----------


 ---------- 2013-07-14 11:00:00 : 효자1동   8614 ----------


 ---------- 2013-07-14 13:00:00 : 근화동   8615 ----------


 ---------- 2013-07-14 14:00:00 : 동  면   8616 ----------


 ---------- 2013-07-14 15:00:00 : 남산면   8619 ----------


 ---------- 2013-07-14 19:00:00 : 남산면   8622 ----------


 ---------- 2013-07-14 20:00:00 : 신사우동   8623 ----------


 ---------- 2013-07-14 21:00:00 : 조운동   8625 ----------


 ---------- 2013-07-14 22:00:00 : 동내면   8627 ----------


 ---------- 2013-07-14 23:00:00 : 퇴계동   8628 ----------


 ---------- 2013-07-15 04:00:00 : 남산면   8629 ----------


 ---------- 2013-07-15 08:00:00 : 조운동   8630 ----------


 ---------- 2013-07-15 09:00:00 : 서  면   8632 ----------


 ---------- 2013-07-15 11:00:00 : 강남동   8633 ----------


 ---------- 2013-07-15 15:00:00 : 조운동   8634 ----------


 ---------- 2013-07-15 16:00:00 : 서  면   8635 ----------


 ---------- 2013-07-15 20:00:00 : 효자1동   8636 ----------


 ---------- 2013-07-15 22:00:00 : 석사동   8637 ----------


 ---------- 2013-07-15 23:00:00 : 후평1동   8638 ----------


 ---------- 2013-07-16 00:00:00 : 효자1동   8639 ----------


 ---------- 2013-07-16 05:00:00 : 후평1동   8640 ----------


 ---------- 2013-07-16 13:00:00 : 약사명동   8641 ----------


 ---------- 2013-07-16 15:00:00 : 신사우동   8642 ----------


 ---------- 2013-07-16 19:00:00 : 남산면   8645 ----------


 ---------- 2013-07-17 16:00:00 : 석사동   8647 ----------


 ---------- 2013-07-17 16:00:00 : 신북읍   8648 ----------


 ---------- 2013-07-17 16:00:00 : 조운동   8649 ----------


 ---------- 2013-07-18 12:00:00 : 교  동   8650 ----------


 ---------- 2013-07-18 14:00:00 : 효자1동   8651 ----------


 ---------- 2013-07-18 22:00:00 : 동내면   8652 ----------


 ---------- 2013-07-19 08:00:00 : 신사우동   8653 ----------


 ---------- 2013-07-19 10:00:00 : 동내면   8654 ----------


 ---------- 2013-07-19 10:00:00 : 동  면   8655 ----------


 ---------- 2013-07-19 12:00:00 : 남산면   8656 ----------


 ---------- 2013-07-19 15:00:00 : 조운동   8657 ----------


 ---------- 2013-07-19 18:00:00 : 서  면   8659 ----------


 ---------- 2013-07-20 03:00:00 : 석사동   8660 ----------


 ---------- 2013-07-20 09:00:00 : 효자1동   8661 ----------


 ---------- 2013-07-20 12:00:00 : 후평1동   8662 ----------


 ---------- 2013-07-20 13:00:00 : 남산면   8663 ----------


 ---------- 2013-07-20 13:00:00 : 후평1동   8664 ----------


 ---------- 2013-07-20 15:00:00 : 효자1동   8665 ----------


 ---------- 2013-07-20 16:00:00 : 퇴계동   8667 ----------


 ---------- 2013-07-20 21:00:00 : 남산면   8668 ----------


 ---------- 2013-07-20 21:00:00 : 동산면   8670 ----------


 ---------- 2013-07-21 05:00:00 : 동  면   8672 ----------

 ---------- 2013-07-21 10:00:00 : 후평1동   8673 ----------


 ---------- 2013-07-21 13:00:00 : 석사동   8674 ----------


 ---------- 2013-07-21 13:00:00 : 동내면   8675 ----------


 ---------- 2013-07-21 13:00:00 : 동  면   8676 ----------


 ---------- 2013-07-21 15:00:00 : 석사동   8677 ----------


 ---------- 2013-07-21 15:00:00 : 동내면   8678 ----------


 ---------- 2013-07-22 08:00:00 : 신사우동   8679 ----------


 ---------- 2013-07-22 09:00:00 : 남  면   8680 ----------


 ---------- 2013-07-22 10:00:00 : 근화동   8681 ----------


 ---------- 2013-07-22 13:00:00 : 동내면   8682 ----------


 ---------- 2013-07-22 13:00:00 : 효자1동   8683 ----------


 ---------- 2013-07-22 16:00:00 : 효자1동   8684 ----------


 ---------- 2013-07-22 16:00:00 : 근화동   8685 ----------


 ---------- 2013-07-22 19:00:00 : 석사동   8687 ----------


 ---------- 2013-07-23 01:00:00 : 동내면   8689 ----------


 ---------- 2013-07-23 11:00:00 : 동내면   8690 ----------


 ---------- 2013-07-23 15:00:00 : 신사우동   8692 ----------


 ---------- 2013-07-23 16:00:00 : 퇴계동   8693 ----------


 ---------- 2013-07-23 23:00:00 : 신북읍   8694 ----------


 ---------- 2013-07-23 23:00:00 : 동  면   8695 ----------


 ---------- 2013-07-24 06:00:00 : 후평1동   8696 ----------


 ---------- 2013-07-24 09:00:00 : 효자1동   8697 ----------


 ---------- 2013-07-24 09:00:00 : 소양동   8698 ----------


 ---------- 2013-07-24 12:00:00 : 동  면   8700 ----------


 ---------- 2013-07-24 12:00:00 : 동산면   8701 ----------


 ---------- 2013-07-24 13:00:00 : 신동면   8702 ----------


 ---------- 2013-07-24 14:00:00 : 신북읍   8703 ----------


 ---------- 2013-07-24 17:00:00 : 동내면   8704 ----------


 ---------- 2013-07-24 17:00:00 : 효자1동   8705 ----------


 ---------- 2013-07-25 07:00:00 : 강남동   8707 ----------


 ---------- 2013-07-25 09:00:00 : 신북읍   8708 ----------


 ---------- 2013-07-25 10:00:00 : 효자1동   8709 ----------


 ---------- 2013-07-25 12:00:00 : 동산면   8711 ----------


 ---------- 2013-07-25 16:00:00 : 신동면   8712 ----------


 ---------- 2013-07-25 17:00:00 : 석사동   8713 ----------


 ---------- 2013-07-25 22:00:00 : 근화동   8715 ----------


 ---------- 2013-07-26 00:00:00 : 약사명동   8716 ----------


 ---------- 2013-07-26 09:00:00 : 서  면   8717 ----------


 ---------- 2013-07-26 09:00:00 : 신북읍   8718 ----------


 ---------- 2013-07-26 11:00:00 : 동내면   8719 ----------


 ---------- 2013-07-26 13:00:00 : 동내면   8720 ----------


 ---------- 2013-07-26 14:00:00 : 소양동   8721 ----------


 ---------- 2013-07-26 15:00:00 : 후평1동   8722 ----------


 ---------- 2013-07-26 17:00:00 : 강남동   8725 ----------


 ---------- 2013-07-26 18:00:00 : 신동면   8726 ----------


 ---------- 2013-07-26 18:00:00 : 서  면   8728 ----------


 ---------- 2013-07-27 00:00:00 : 신사우동   8729 ----------


 ---------- 2013-07-27 02:00:00 : 조운동   8730 ----------


 ---------- 2013-07-27 06:00:00 : 소양동   8731 ----------


 ---------- 2013-07-27 08:00:00 : 남산면   8732 ----------


 ---------- 2013-07-27 09:00:00 : 석사동   8733 ----------


 ---------- 2013-07-27 10:00:00 : 퇴계동   8734 ----------


 ---------- 2013-07-27 12:00:00 : 석사동   8736 ----------


 ---------- 2013-07-27 17:00:00 : 석사동   8737 ----------


 ---------- 2013-07-28 02:00:00 : 석사동   8738 ----------


 ---------- 2013-07-29 05:00:00 : 석사동   8740 ----------


 ---------- 2013-07-29 08:00:00 : 동산면   8741 ----------


 ---------- 2013-07-29 10:00:00 : 석사동   8742 ----------


 ---------- 2013-07-29 10:00:00 : 조운동   8743 ----------


 ---------- 2013-07-29 11:00:00 : 동내면   8744 ----------


 ---------- 2013-07-29 12:00:00 : 교  동   8745 ----------


 ---------- 2013-07-29 15:00:00 : 석사동   8746 ----------


 ---------- 2013-07-29 16:00:00 : 약사명동   8747 ----------


 ---------- 2013-07-29 17:00:00 : 석사동   8749 ----------


 ---------- 2013-07-30 07:00:00 : 후평1동   8750 ----------


 ---------- 2013-07-30 08:00:00 : 퇴계동   8751 ----------


 ---------- 2013-07-30 10:00:00 : 강남동   8752 ----------


 ---------- 2013-07-30 12:00:00 : 소양동   8753 ----------


 ---------- 2013-07-30 12:00:00 : 교  동   8754 ----------


 ---------- 2013-07-30 13:00:00 : 후평1동   8755 ----------


 ---------- 2013-07-30 14:00:00 : 신북읍   8756 ----------


 ---------- 2013-07-30 18:00:00 : 남  면   8757 ----------


 ---------- 2013-07-30 18:00:00 : 동내면   8758 ----------


 ---------- 2013-07-31 04:00:00 : 남산면   8759 ----------


 ---------- 2013-07-31 07:00:00 : 효자1동   8760 ----------


 ---------- 2013-07-31 09:00:00 : 강남동   8761 ----------


 ---------- 2013-07-31 13:00:00 : 강남동   8762 ----------


 ---------- 2013-07-31 13:00:00 : 효자1동   8763 ----------


 ---------- 2013-07-31 13:00:00 : 후평1동   8764 ----------


 ---------- 2013-07-31 15:00:00 : 효자1동   8765 ----------


 ---------- 2013-07-31 16:00:00 : 석사동   8766 ----------


 ---------- 2013-07-31 17:00:00 : 강남동   8767 ----------


 ---------- 2013-07-31 18:00:00 : 남산면   8768 ----------


 ---------- 2013-08-01 06:00:00 : 석사동   8769 ----------


 ---------- 2013-08-01 09:00:00 : 석사동   8770 ----------


 ---------- 2013-08-01 10:00:00 : 남산면   8772 ----------


 ---------- 2013-08-01 11:00:00 : 동내면   8773 ----------


 ---------- 2013-08-01 16:00:00 : 석사동   8774 ----------


 ---------- 2013-08-01 23:00:00 : 후평1동   8776 ----------


 ---------- 2013-08-02 09:00:00 : 동  면   8777 ----------


 ---------- 2013-08-02 17:00:00 : 후평1동   8778 ----------


 ---------- 2013-08-02 18:00:00 : 퇴계동   8779 ----------


 ---------- 2013-08-02 19:00:00 : 사북면   8780 ----------


 ---------- 2013-08-02 19:00:00 : 동산면   8782 ----------


 ---------- 2013-08-02 21:00:00 : 석사동   8783 ----------


 ---------- 2013-08-02 22:00:00 : 소양동   8785 ----------


 ---------- 2013-08-03 03:00:00 : 후평1동   8787 ----------


 ---------- 2013-08-03 05:00:00 : 석사동   8788 ----------


 ---------- 2013-08-03 11:00:00 : 후평1동   8789 ----------


 ---------- 2013-08-03 15:00:00 : 석사동   8790 ----------


 ---------- 2013-08-03 19:00:00 : 동산면   8791 ----------


 ---------- 2013-08-04 01:00:00 : 후평1동   8792 ----------


 ---------- 2013-08-04 09:00:00 : 사북면   8793 ----------


 ---------- 2013-08-04 09:00:00 : 신사우동   8794 ----------


 ---------- 2013-08-04 11:00:00 : 석사동   8795 ----------


 ---------- 2013-08-04 15:00:00 : 신사우동   8796 ----------


 ---------- 2013-08-04 16:00:00 : 동내면   8797 ----------


 ---------- 2013-08-04 16:00:00 : 신북읍   8799 ----------


 ---------- 2013-08-04 17:00:00 : 후평1동   8800 ----------


 ---------- 2013-08-04 18:00:00 : 동  면   8802 ----------


 ---------- 2013-08-04 20:00:00 : 근화동   8803 ----------


 ---------- 2013-08-04 23:00:00 : 신사우동   8804 ----------


 ---------- 2013-08-05 01:00:00 : 동내면   8805 ----------


 ---------- 2013-08-05 04:00:00 : 사북면   8806 ----------


 ---------- 2013-08-05 06:00:00 : 신북읍   8807 ----------


 ---------- 2013-08-05 08:00:00 : 강남동   8808 ----------


 ---------- 2013-08-05 09:00:00 : 석사동   8809 ----------


 ---------- 2013-08-05 10:00:00 : 퇴계동   8810 ----------


 ---------- 2013-08-05 11:00:00 : 근화동   8811 ----------


 ---------- 2013-08-05 15:00:00 : 석사동   8812 ----------


 ---------- 2013-08-05 15:00:00 : 서  면   8813 ----------


 ---------- 2013-08-05 19:00:00 : 퇴계동   8814 ----------


 ---------- 2013-08-05 22:00:00 : 서  면   8815 ----------


 ---------- 2013-08-06 06:00:00 : 퇴계동   8816 ----------


 ---------- 2013-08-06 07:00:00 : 석사동   8817 ----------


 ---------- 2013-08-06 09:00:00 : 동내면   8818 ----------


 ---------- 2013-08-06 10:00:00 : 후평1동   8819 ----------


 ---------- 2013-08-06 14:00:00 : 신사우동   8820 ----------


 ---------- 2013-08-06 15:00:00 : 강남동   8821 ----------


 ---------- 2013-08-07 09:00:00 : 효자1동   8823 ----------


 ---------- 2013-08-07 10:00:00 : 퇴계동   8824 ----------


 ---------- 2013-08-07 11:00:00 : 퇴계동   8825 ----------


 ---------- 2013-08-07 12:00:00 : 석사동   8826 ----------


 ---------- 2013-08-07 12:00:00 : 남산면   8827 ----------


 ---------- 2013-08-07 13:00:00 : 동내면   8828 ----------


 ---------- 2013-08-07 13:00:00 : 동  면   8829 ----------


 ---------- 2013-08-07 17:00:00 : 퇴계동   8831 ----------


 ---------- 2013-08-07 20:00:00 : 동내면   8833 ----------


 ---------- 2013-08-07 21:00:00 : 석사동   8834 ----------

 ---------- 2013-08-08 02:00:00 : 효자1동   8835 ----------


 ---------- 2013-08-08 08:00:00 : 효자1동   8837 ----------


 ---------- 2013-08-08 09:00:00 : 후평1동   8838 ----------


 ---------- 2013-08-08 10:00:00 : 석사동   8839 ----------


 ---------- 2013-08-08 11:00:00 : 동  면   8840 ----------


 ---------- 2013-08-08 11:00:00 : 퇴계동   8841 ----------


 ---------- 2013-08-08 12:00:00 : 퇴계동   8842 ----------


 ---------- 2013-08-08 13:00:00 : 강남동   8843 ----------


 ---------- 2013-08-08 15:00:00 : 효자1동   8844 ----------


 ---------- 2013-08-08 15:00:00 : 동  면   8845 ----------


 ---------- 2013-08-08 15:00:00 : 퇴계동   8846 ----------


 ---------- 2013-08-08 22:00:00 : 남산면   8850 ----------


 ---------- 2013-08-09 07:00:00 : 석사동   8852 ----------


 ---------- 2013-08-09 09:00:00 : 후평1동   8853 ----------


 ---------- 2013-08-09 09:00:00 : 동산면   8854 ----------


 ---------- 2013-08-09 10:00:00 : 퇴계동   8855 ----------


 ---------- 2013-08-09 13:00:00 : 서  면   8856 ----------


 ---------- 2013-08-09 14:00:00 : 석사동   8857 ----------


 ---------- 2013-08-09 16:00:00 : 근화동   8858 ----------


 ---------- 2013-08-09 17:00:00 : 근화동   8859 ----------


 ---------- 2013-08-09 21:00:00 : 후평1동   8860 ----------


 ---------- 2013-08-10 02:00:00 : 서  면   8861 ----------


 ---------- 2013-08-10 06:00:00 : 신사우동   8863 ----------


 ---------- 2013-08-10 08:00:00 : 퇴계동   8864 ----------


 ---------- 2013-08-10 09:00:00 : 강남동   8865 ----------


 ---------- 2013-08-10 09:00:00 : 서  면   8866 ----------


 ---------- 2013-08-10 09:00:00 : 퇴계동   8867 ----------


 ---------- 2013-08-10 10:00:00 : 효자1동   8870 ----------


 ---------- 2013-08-10 10:00:00 : 남산면   8871 ----------


 ---------- 2013-08-10 16:00:00 : 동내면   8872 ----------


 ---------- 2013-08-10 16:00:00 : 후평1동   8873 ----------


 ---------- 2013-08-11 02:00:00 : 석사동   8874 ----------


 ---------- 2013-08-11 14:00:00 : 남산면   8877 ----------


 ---------- 2013-08-11 14:00:00 : 신사우동   8878 ----------


 ---------- 2013-08-11 17:00:00 : 사북면   8879 ----------


 ---------- 2013-08-11 23:00:00 : 강남동   8881 ----------


 ---------- 2013-08-12 03:00:00 : 후평1동   8882 ----------


 ---------- 2013-08-12 04:00:00 : 강남동   8885 ----------


 ---------- 2013-08-12 06:00:00 : 북산면   8886 ----------


 ---------- 2013-08-12 09:00:00 : 사북면   8887 ----------


 ---------- 2013-08-12 09:00:00 : 퇴계동   8888 ----------


 ---------- 2013-08-12 11:00:00 : 신사우동   8889 ----------


 ---------- 2013-08-12 11:00:00 : 퇴계동   8890 ----------


 ---------- 2013-08-12 12:00:00 : 신사우동   8892 ----------


 ---------- 2013-08-12 17:00:00 : 후평1동   8893 ----------


 ---------- 2013-08-12 21:00:00 : 신북읍   8895 ----------


 ---------- 2013-08-13 07:00:00 : 사북면   8896 ----------


 ---------- 2013-08-13 09:00:00 : 석사동   8897 ----------


 ---------- 2013-08-13 10:00:00 : 동내면   8898 ----------


 ---------- 2013-08-13 12:00:00 : 신사우동   8900 ----------


 ---------- 2013-08-13 14:00:00 : 퇴계동   8901 ----------


 ---------- 2013-08-13 18:00:00 : 퇴계동   8902 ----------


 ---------- 2013-08-14 06:00:00 : 효자1동   8903 ----------


 ---------- 2013-08-14 06:00:00 : 퇴계동   8904 ----------


 ---------- 2013-08-14 09:00:00 : 강남동   8905 ----------


 ---------- 2013-08-14 10:00:00 : 남산면   8906 ----------


 ---------- 2013-08-14 14:00:00 : 후평1동   8907 ----------


 ---------- 2013-08-14 15:00:00 : 효자1동   8908 ----------


 ---------- 2013-08-14 15:00:00 : 소양동   8909 ----------


 ---------- 2013-08-14 17:00:00 : 동산면   8910 ----------


 ---------- 2013-08-14 19:00:00 : 남산면   8911 ----------


 ---------- 2013-08-15 07:00:00 : 근화동   8912 ----------


 ---------- 2013-08-15 08:00:00 : 효자1동   8913 ----------


 ---------- 2013-08-15 09:00:00 : 후평1동   8914 ----------


 ---------- 2013-08-15 10:00:00 : 석사동   8915 ----------


 ---------- 2013-08-15 11:00:00 : 후평1동   8916 ----------


 ---------- 2013-08-15 14:00:00 : 약사명동   8918 ----------


 ---------- 2013-08-15 14:00:00 : 후평1동   8919 ----------


 ---------- 2013-08-15 15:00:00 : 남  면   8921 ----------


 ---------- 2013-08-15 16:00:00 : 동내면   8922 ----------


 ---------- 2013-08-15 17:00:00 : 후평1동   8925 ----------


 ---------- 2013-08-16 00:00:00 : 퇴계동   8926 ----------


 ---------- 2013-08-16 09:00:00 : 소양동   8927 ----------


 ---------- 2013-08-16 10:00:00 : 퇴계동   8928 ----------


 ---------- 2013-08-16 14:00:00 : 석사동   8929 ----------


 ---------- 2013-08-16 15:00:00 : 신동면   8931 ----------


 ---------- 2013-08-16 17:00:00 : 신사우동   8932 ----------


 ---------- 2013-08-16 18:00:00 : 신북읍   8933 ----------


 ---------- 2013-08-16 19:00:00 : 후평1동   8934 ----------


 ---------- 2013-08-16 21:00:00 : 후평1동   8936 ----------


 ---------- 2013-08-17 00:00:00 : 신사우동   8937 ----------


 ---------- 2013-08-17 01:00:00 : 석사동   8938 ----------


 ---------- 2013-08-17 10:00:00 : 근화동   8939 ----------


 ---------- 2013-08-17 11:00:00 : 효자1동   8940 ----------


 ---------- 2013-08-17 12:00:00 : 신북읍   8941 ----------


 ---------- 2013-08-17 12:00:00 : 북산면   8943 ----------


 ---------- 2013-08-17 12:00:00 : 동산면   8944 ----------


 ---------- 2013-08-17 13:00:00 : 신사우동   8945 ----------


 ---------- 2013-08-17 13:00:00 : 북산면   8951 ----------


 ---------- 2013-08-17 14:00:00 : 동내면   8952 ----------


 ---------- 2013-08-17 17:00:00 : 동내면   8953 ----------


 ---------- 2013-08-17 17:00:00 : 근화동   8955 ----------


 ---------- 2013-08-17 19:00:00 : 서  면   8956 ----------


 ---------- 2013-08-17 19:00:00 : 동내면   8957 ----------


 ---------- 2013-08-17 19:00:00 : 북산면   8958 ----------


 ---------- 2013-08-18 09:00:00 : 석사동   8959 ----------


 ---------- 2013-08-18 09:00:00 : 후평1동   8960 ----------


 ---------- 2013-08-18 11:00:00 : 신사우동   8961 ----------


 ---------- 2013-08-18 12:00:00 : 서  면   8962 ----------


 ---------- 2013-08-18 16:00:00 : 소양동   8963 ----------


 ---------- 2013-08-18 16:00:00 : 동  면   8964 ----------


 ---------- 2013-08-19 00:00:00 : 석사동   8965 ----------


 ---------- 2013-08-19 09:00:00 : 신사우동   8966 ----------


 ---------- 2013-08-19 09:00:00 : 퇴계동   8967 ----------


 ---------- 2013-08-19 10:00:00 : 서  면   8968 ----------


 ---------- 2013-08-19 10:00:00 : 신사우동   8969 ----------


 ---------- 2013-08-19 12:00:00 : 사북면   8973 ----------


 ---------- 2013-08-19 13:00:00 : 근화동   8974 ----------


 ---------- 2013-08-19 13:00:00 : 소양동   8975 ----------


 ---------- 2013-08-19 14:00:00 : 강남동   8976 ----------


 ---------- 2013-08-19 16:00:00 : 신사우동   8977 ----------


 ---------- 2013-08-19 18:00:00 : 신사우동   8978 ----------


 ---------- 2013-08-19 19:00:00 : 효자1동   8979 ----------


 ---------- 2013-08-19 22:00:00 : 효자1동   8980 ----------


 ---------- 2013-08-20 02:00:00 : 사북면   8982 ----------


 ---------- 2013-08-20 12:00:00 : 조운동   8983 ----------


 ---------- 2013-08-20 13:00:00 : 동내면   8984 ----------


 ---------- 2013-08-20 16:00:00 : 신사우동   8985 ----------


 ---------- 2013-08-21 06:00:00 : 신동면   8986 ----------


 ---------- 2013-08-21 08:00:00 : 소양동   8987 ----------


 ---------- 2013-08-21 09:00:00 : 사북면   8988 ----------


 ---------- 2013-08-21 09:00:00 : 소양동   8989 ----------


 ---------- 2013-08-21 15:00:00 : 동내면   8991 ----------


 ---------- 2013-08-21 16:00:00 : 강남동   8992 ----------


 ---------- 2013-08-21 16:00:00 : 신북읍   8993 ----------


 ---------- 2013-08-21 17:00:00 : 석사동   8994 ----------


 ---------- 2013-08-21 18:00:00 : 약사명동   8996 ----------


 ---------- 2013-08-21 19:00:00 : 소양동   8997 ----------


 ---------- 2013-08-22 02:00:00 : 퇴계동   8999 ----------


 ---------- 2013-08-22 09:00:00 : 동  면   9000 ----------


 ---------- 2013-08-22 10:00:00 : 서  면   9003 ----------


 ---------- 2013-08-22 11:00:00 : 서  면   9004 ----------


 ---------- 2013-08-22 11:00:00 : 후평1동   9005 ----------


 ---------- 2013-08-22 12:00:00 : 효자1동   9006 ----------


 ---------- 2013-08-22 13:00:00 : 남  면   9008 ----------


 ---------- 2013-08-22 14:00:00 : 효자1동   9009 ----------


 ---------- 2013-08-22 15:00:00 : 강남동   9012 ----------


 ---------- 2013-08-22 17:00:00 : 석사동   9013 ----------


 ---------- 2013-08-22 17:00:00 : 효자1동   9014 ----------

 ---------- 2013-08-22 20:00:00 : 신사우동   9015 ----------


 ---------- 2013-08-23 05:00:00 : 남산면   9016 ----------


 ---------- 2013-08-23 07:00:00 : 석사동   9017 ----------


 ---------- 2013-08-23 07:00:00 : 강남동   9019 ----------


 ---------- 2013-08-23 09:00:00 : 후평1동   9020 ----------


 ---------- 2013-08-23 10:00:00 : 남  면   9022 ----------


 ---------- 2013-08-23 10:00:00 : 남산면   9023 ----------


 ---------- 2013-08-23 11:00:00 : 강남동   9024 ----------


 ---------- 2013-08-23 11:00:00 : 퇴계동   9025 ----------


 ---------- 2013-08-23 16:00:00 : 강남동   9026 ----------


 ---------- 2013-08-24 00:00:00 : 소양동   9027 ----------


 ---------- 2013-08-24 06:00:00 : 강남동   9028 ----------


 ---------- 2013-08-24 08:00:00 : 동내면   9029 ----------


 ---------- 2013-08-24 10:00:00 : 남산면   9030 ----------


 ---------- 2013-08-24 11:00:00 : 후평1동   9033 ----------


 ---------- 2013-08-24 12:00:00 : 후평1동   9034 ----------


 ---------- 2013-08-24 13:00:00 : 서  면   9036 ----------


 ---------- 2013-08-24 14:00:00 : 신사우동   9037 ----------


 ---------- 2013-08-25 01:00:00 : 효자1동   9040 ----------


 ---------- 2013-08-25 02:00:00 : 석사동   9041 ----------


 ---------- 2013-08-25 02:00:00 : 근화동   9045 ----------


 ---------- 2013-08-25 05:00:00 : 동  면   9046 ----------


 ---------- 2013-08-25 05:00:00 : 후평1동   9047 ----------


 ---------- 2013-08-25 09:00:00 : 석사동   9048 ----------


 ---------- 2013-08-25 09:00:00 : 동내면   9049 ----------


 ---------- 2013-08-25 09:00:00 : 소양동   9050 ----------


 ---------- 2013-08-25 09:00:00 : 퇴계동   9051 ----------


 ---------- 2013-08-25 16:00:00 : 교  동   9052 ----------


 ---------- 2013-08-25 21:00:00 : 사북면   9053 ----------


 ---------- 2013-08-26 09:00:00 : 동  면   9054 ----------


 ---------- 2013-08-26 12:00:00 : 남산면   9055 ----------


 ---------- 2013-08-26 15:00:00 : 후평1동   9056 ----------


 ---------- 2013-08-26 15:00:00 : 퇴계동   9057 ----------


 ---------- 2013-08-26 18:00:00 : 석사동   9058 ----------


 ---------- 2013-08-27 03:00:00 : 효자1동   9059 ----------


 ---------- 2013-08-27 08:00:00 : 강남동   9060 ----------


 ---------- 2013-08-27 10:00:00 : 효자1동   9061 ----------


 ---------- 2013-08-27 10:00:00 : 동  면   9064 ----------


 ---------- 2013-08-27 13:00:00 : 신북읍   9065 ----------


 ---------- 2013-08-27 14:00:00 : 후평1동   9067 ----------


 ---------- 2013-08-27 20:00:00 : 석사동   9068 ----------


 ---------- 2013-08-27 21:00:00 : 퇴계동   9069 ----------


 ---------- 2013-08-27 22:00:00 : 후평1동   9070 ----------


 ---------- 2013-08-27 22:00:00 : 퇴계동   9071 ----------


 ---------- 2013-08-28 08:00:00 : 사북면   9072 ----------


 ---------- 2013-08-28 09:00:00 : 신사우동   9073 ----------


 ---------- 2013-08-28 09:00:00 : 후평1동   9074 ----------


 ---------- 2013-08-28 10:00:00 : 소양동   9075 ----------


 ---------- 2013-08-28 12:00:00 : 신사우동   9077 ----------


 ---------- 2013-08-28 20:00:00 : 신사우동   9079 ----------


 ---------- 2013-08-29 15:00:00 : 서  면   9081 ----------


 ---------- 2013-08-29 20:00:00 : 석사동   9082 ----------


 ---------- 2013-08-29 21:00:00 : 후평1동   9083 ----------


 ---------- 2013-08-30 00:00:00 : 효자1동   9084 ----------


 ---------- 2013-08-30 04:00:00 : 효자1동   9085 ----------


 ---------- 2013-08-30 07:00:00 : 퇴계동   9086 ----------


 ---------- 2013-08-30 10:00:00 : 석사동   9087 ----------


 ---------- 2013-08-30 10:00:00 : 남산면   9088 ----------


 ---------- 2013-08-30 10:00:00 : 약사명동   9089 ----------


 ---------- 2013-08-30 10:00:00 : 동  면   9090 ----------


 ---------- 2013-08-30 11:00:00 : 신사우동   9091 ----------


 ---------- 2013-08-30 19:00:00 : 퇴계동   9092 ----------


 ---------- 2013-08-30 22:00:00 : 효자1동   9093 ----------


 ---------- 2013-08-31 00:00:00 : 후평1동   9096 ----------


 ---------- 2013-08-31 09:00:00 : 후평1동   9097 ----------


 ---------- 2013-08-31 13:00:00 : 동내면   9098 ----------


 ---------- 2013-08-31 13:00:00 : 남산면   9099 ----------


 ---------- 2013-08-31 15:00:00 : 동내면   9100 ----------


 ---------- 2013-08-31 16:00:00 : 후평1동   9101 ----------


 ---------- 2013-08-31 17:00:00 : 근화동   9102 ----------


 ---------- 2013-08-31 18:00:00 : 후평1동   9103 ----------


 ---------- 2013-08-31 19:00:00 : 퇴계동   9104 ----------


 ---------- 2013-09-01 00:00:00 : 신동면   9105 ----------


 ---------- 2013-09-01 04:00:00 : 북산면   9106 ----------


 ---------- 2013-09-01 06:00:00 : 남산면   9107 ----------


 ---------- 2013-09-01 10:00:00 : 신북읍   9108 ----------


 ---------- 2013-09-01 12:00:00 : 퇴계동   9109 ----------


 ---------- 2013-09-01 12:00:00 : 동산면   9110 ----------


 ---------- 2013-09-01 13:00:00 : 석사동   9111 ----------


 ---------- 2013-09-01 15:00:00 : 동내면   9112 ----------


 ---------- 2013-09-01 15:00:00 : 후평1동   9113 ----------


 ---------- 2013-09-01 16:00:00 : 근화동   9114 ----------


 ---------- 2013-09-01 16:00:00 : 후평1동   9115 ----------


 ---------- 2013-09-01 20:00:00 : 효자1동   9116 ----------


 ---------- 2013-09-01 22:00:00 : 교  동   9117 ----------


 ---------- 2013-09-02 09:00:00 : 신북읍   9118 ----------


 ---------- 2013-09-02 11:00:00 : 석사동   9119 ----------


 ---------- 2013-09-02 11:00:00 : 동  면   9120 ----------


 ---------- 2013-09-02 12:00:00 : 효자1동   9121 ----------


 ---------- 2013-09-02 13:00:00 : 근화동   9122 ----------


 ---------- 2013-09-02 14:00:00 : 후평1동   9123 ----------


 ---------- 2013-09-02 16:00:00 : 신동면   9124 ----------


 ---------- 2013-09-02 16:00:00 : 남  면   9125 ----------


 ---------- 2013-09-02 17:00:00 : 남산면   9126 ----------


 ---------- 2013-09-02 19:00:00 : 동내면   9127 ----------


 ---------- 2013-09-03 07:00:00 : 퇴계동   9128 ----------


 ---------- 2013-09-03 09:00:00 : 남산면   9129 ----------


 ---------- 2013-09-03 09:00:00 : 신사우동   9131 ----------


 ---------- 2013-09-03 10:00:00 : 남산면   9132 ----------


 ---------- 2013-09-03 10:00:00 : 후평1동   9133 ----------


 ---------- 2013-09-03 15:00:00 : 효자1동   9134 ----------


 ---------- 2013-09-03 19:00:00 : 효자1동   9135 ----------


 ---------- 2013-09-03 19:00:00 : 후평1동   9137 ----------


 ---------- 2013-09-04 09:00:00 : 동내면   9138 ----------


 ---------- 2013-09-04 13:00:00 : 강남동   9139 ----------


 ---------- 2013-09-04 13:00:00 : 소양동   9140 ----------


 ---------- 2013-09-04 14:00:00 : 신북읍   9141 ----------


 ---------- 2013-09-04 16:00:00 : 퇴계동   9142 ----------


 ---------- 2013-09-04 17:00:00 : 강남동   9143 ----------


 ---------- 2013-09-05 06:00:00 : 남산면   9144 ----------


 ---------- 2013-09-05 11:00:00 : 사북면   9146 ----------


 ---------- 2013-09-05 13:00:00 : 후평1동   9147 ----------


 ---------- 2013-09-05 14:00:00 : 소양동   9148 ----------


 ---------- 2013-09-05 14:00:00 : 퇴계동   9149 ----------


 ---------- 2013-09-05 16:00:00 : 석사동   9150 ----------


 ---------- 2013-09-05 17:00:00 : 동산면   9151 ----------


 ---------- 2013-09-05 19:00:00 : 신사우동   9152 ----------


 ---------- 2013-09-06 09:00:00 : 소양동   9153 ----------


 ---------- 2013-09-06 09:00:00 : 동  면   9155 ----------


 ---------- 2013-09-06 11:00:00 : 석사동   9156 ----------


 ---------- 2013-09-06 12:00:00 : 석사동   9158 ----------


 ---------- 2013-09-06 13:00:00 : 서  면   9159 ----------


 ---------- 2013-09-06 13:00:00 : 근화동   9160 ----------


 ---------- 2013-09-06 13:00:00 : 후평1동   9161 ----------


 ---------- 2013-09-06 14:00:00 : 신사우동   9162 ----------


 ---------- 2013-09-06 14:00:00 : 북산면   9163 ----------


 ---------- 2013-09-06 16:00:00 : 효자1동   9164 ----------


 ---------- 2013-09-06 16:00:00 : 신북읍   9165 ----------


 ---------- 2013-09-07 08:00:00 : 신사우동   9166 ----------


 ---------- 2013-09-07 10:00:00 : 근화동   9168 ----------


 ---------- 2013-09-07 11:00:00 : 서  면   9170 ----------


 ---------- 2013-09-07 12:00:00 : 신북읍   9171 ----------


 ---------- 2013-09-07 13:00:00 : 석사동   9173 ----------


 ---------- 2013-09-07 14:00:00 : 동내면   9174 ----------


 ---------- 2013-09-07 16:00:00 : 강남동   9175 ----------


 ---------- 2013-09-07 17:00:00 : 강남동   9176 ----------


 ---------- 2013-09-08 00:00:00 : 소양동   9177 ----------


 ---------- 2013-09-08 08:00:00 : 후평1동   9178 ----------

 ---------- 2013-09-08 10:00:00 : 근화동   9179 ----------


 ---------- 2013-09-08 10:00:00 : 신사우동   9180 ----------


 ---------- 2013-09-08 11:00:00 : 동내면   9181 ----------


 ---------- 2013-09-08 12:00:00 : 소양동   9182 ----------


 ---------- 2013-09-08 12:00:00 : 퇴계동   9183 ----------


 ---------- 2013-09-08 13:00:00 : 퇴계동   9184 ----------


 ---------- 2013-09-08 16:00:00 : 사북면   9186 ----------


 ---------- 2013-09-08 18:00:00 : 퇴계동   9188 ----------


 ---------- 2013-09-08 22:00:00 : 서  면   9189 ----------


 ---------- 2013-09-09 00:00:00 : 근화동   9190 ----------


 ---------- 2013-09-09 01:00:00 : 남  면   9191 ----------


 ---------- 2013-09-09 02:00:00 : 석사동   9192 ----------


 ---------- 2013-09-09 10:00:00 : 효자1동   9193 ----------


 ---------- 2013-09-09 10:00:00 : 동  면   9194 ----------


 ---------- 2013-09-09 12:00:00 : 동  면   9195 ----------


 ---------- 2013-09-09 14:00:00 : 동  면   9196 ----------


 ---------- 2013-09-09 16:00:00 : 남산면   9197 ----------


 ---------- 2013-09-09 18:00:00 : 신사우동   9198 ----------


 ---------- 2013-09-09 18:00:00 : 동  면   9199 ----------


 ---------- 2013-09-10 11:00:00 : 후평1동   9201 ----------


 ---------- 2013-09-10 12:00:00 : 동  면   9202 ----------


 ---------- 2013-09-10 14:00:00 : 조운동   9203 ----------


 ---------- 2013-09-10 15:00:00 : 신사우동   9204 ----------


 ---------- 2013-09-10 19:00:00 : 서  면   9206 ----------


 ---------- 2013-09-11 00:00:00 : 퇴계동   9207 ----------


 ---------- 2013-09-11 03:00:00 : 동내면   9208 ----------


 ---------- 2013-09-11 08:00:00 : 동  면   9209 ----------


 ---------- 2013-09-11 13:00:00 : 신동면   9210 ----------


 ---------- 2013-09-11 13:00:00 : 사북면   9211 ----------


 ---------- 2013-09-11 18:00:00 : 사북면   9212 ----------


 ---------- 2013-09-12 05:00:00 : 약사명동   9213 ----------


 ---------- 2013-09-12 07:00:00 : 소양동   9214 ----------


 ---------- 2013-09-12 10:00:00 : 동내면   9215 ----------


 ---------- 2013-09-12 10:00:00 : 퇴계동   9216 ----------


 ---------- 2013-09-12 11:00:00 : 후평1동   9218 ----------


 ---------- 2013-09-12 12:00:00 : 석사동   9219 ----------


 ---------- 2013-09-12 12:00:00 : 남산면   9220 ----------


 ---------- 2013-09-12 14:00:00 : 동  면   9221 ----------


 ---------- 2013-09-12 14:00:00 : 후평1동   9223 ----------


 ---------- 2013-09-12 15:00:00 : 사북면   9226 ----------


 ---------- 2013-09-12 15:00:00 : 후평1동   9227 ----------


 ---------- 2013-09-12 18:00:00 : 신사우동   9228 ----------


 ---------- 2013-09-12 21:00:00 : 강남동   9229 ----------


 ---------- 2013-09-12 23:00:00 : 서  면   9230 ----------


 ---------- 2013-09-12 23:00:00 : 효자1동   9231 ----------


 ---------- 2013-09-13 06:00:00 : 서  면   9234 ----------


 ---------- 2013-09-13 08:00:00 : 효자1동   9235 ----------


 ---------- 2013-09-13 10:00:00 : 강남동   9237 ----------


 ---------- 2013-09-13 14:00:00 : 근화동   9238 ----------


 ---------- 2013-09-13 14:00:00 : 약사명동   9239 ----------


 ---------- 2013-09-13 15:00:00 : 신사우동   9240 ----------


 ---------- 2013-09-13 18:00:00 : 후평1동   9241 ----------


 ---------- 2013-09-13 19:00:00 : 후평1동   9242 ----------


 ---------- 2013-09-13 21:00:00 : 근화동   9243 ----------


 ---------- 2013-09-14 06:00:00 : 신사우동   9244 ----------


 ---------- 2013-09-14 13:00:00 : 신북읍   9245 ----------


 ---------- 2013-09-14 14:00:00 : 석사동   9246 ----------


 ---------- 2013-09-14 15:00:00 : 후평1동   9247 ----------


 ---------- 2013-09-14 16:00:00 : 근화동   9248 ----------


 ---------- 2013-09-14 23:00:00 : 동  면   9249 ----------


 ---------- 2013-09-15 10:00:00 : 남  면   9250 ----------


 ---------- 2013-09-15 12:00:00 : 강남동   9251 ----------


 ---------- 2013-09-15 12:00:00 : 서  면   9254 ----------


 ---------- 2013-09-15 13:00:00 : 서  면   9256 ----------


 ---------- 2013-09-15 13:00:00 : 동  면   9257 ----------


 ---------- 2013-09-15 14:00:00 : 서  면   9258 ----------


 ---------- 2013-09-15 14:00:00 : 동산면   9259 ----------


 ---------- 2013-09-15 17:00:00 : 남산면   9261 ----------


 ---------- 2013-09-15 18:00:00 : 퇴계동   9262 ----------


 ---------- 2013-09-15 20:00:00 : 효자1동   9263 ----------


 ---------- 2013-09-15 22:00:00 : 후평1동   9266 ----------


 ---------- 2013-09-16 08:00:00 : 석사동   9268 ----------


 ---------- 2013-09-16 10:00:00 : 소양동   9269 ----------


 ---------- 2013-09-16 10:00:00 : 동  면   9270 ----------


 ---------- 2013-09-16 11:00:00 : 후평1동   9272 ----------


 ---------- 2013-09-16 12:00:00 : 후평1동   9273 ----------


 ---------- 2013-09-16 13:00:00 : 동  면   9274 ----------


 ---------- 2013-09-16 13:00:00 : 후평1동   9275 ----------


 ---------- 2013-09-16 15:00:00 : 후평1동   9277 ----------


 ---------- 2013-09-16 16:00:00 : 동내면   9279 ----------


 ---------- 2013-09-16 22:00:00 : 소양동   9280 ----------


 ---------- 2013-09-17 10:00:00 : 후평1동   9281 ----------


 ---------- 2013-09-17 13:00:00 : 동내면   9282 ----------


 ---------- 2013-09-17 18:00:00 : 강남동   9284 ----------


 ---------- 2013-09-17 18:00:00 : 동  면   9286 ----------


 ---------- 2013-09-17 19:00:00 : 서  면   9287 ----------


 ---------- 2013-09-17 20:00:00 : 동  면   9289 ----------


 ---------- 2013-09-18 07:00:00 : 서  면   9290 ----------


 ---------- 2013-09-18 09:00:00 : 동  면   9291 ----------


 ---------- 2013-09-18 09:00:00 : 퇴계동   9292 ----------


 ---------- 2013-09-18 10:00:00 : 신동면   9293 ----------


 ---------- 2013-09-18 10:00:00 : 사북면   9294 ----------


 ---------- 2013-09-18 10:00:00 : 효자1동   9295 ----------


 ---------- 2013-09-18 10:00:00 : 조운동   9296 ----------


 ---------- 2013-09-18 13:00:00 : 신사우동   9297 ----------


 ---------- 2013-09-18 14:00:00 : 신동면   9298 ----------


 ---------- 2013-09-18 15:00:00 : 사북면   9299 ----------


 ---------- 2013-09-18 15:00:00 : 후평1동   9300 ----------


 ---------- 2013-09-18 16:00:00 : 남산면   9301 ----------


 ---------- 2013-09-18 16:00:00 : 동산면   9302 ----------


 ---------- 2013-09-18 18:00:00 : 후평1동   9304 ----------


 ---------- 2013-09-19 08:00:00 : 남  면   9305 ----------


 ---------- 2013-09-19 09:00:00 : 효자1동   9306 ----------


 ---------- 2013-09-19 10:00:00 : 후평1동   9307 ----------


 ---------- 2013-09-19 11:00:00 : 남산면   9308 ----------


 ---------- 2013-09-19 11:00:00 : 퇴계동   9309 ----------


 ---------- 2013-09-19 14:00:00 : 후평1동   9310 ----------


 ---------- 2013-09-19 15:00:00 : 동내면   9311 ----------


 ---------- 2013-09-19 15:00:00 : 신사우동   9313 ----------


 ---------- 2013-09-19 19:00:00 : 효자1동   9315 ----------


 ---------- 2013-09-19 19:00:00 : 신사우동   9316 ----------


 ---------- 2013-09-20 09:00:00 : 후평1동   9317 ----------


 ---------- 2013-09-20 12:00:00 : 강남동   9318 ----------


 ---------- 2013-09-20 16:00:00 : 근화동   9319 ----------


 ---------- 2013-09-20 20:00:00 : 서  면   9320 ----------


 ---------- 2013-09-20 20:00:00 : 신북읍   9321 ----------


 ---------- 2013-09-20 22:00:00 : 신사우동   9323 ----------


 ---------- 2013-09-21 07:00:00 : 강남동   9324 ----------


 ---------- 2013-09-21 09:00:00 : 동내면   9325 ----------


 ---------- 2013-09-21 10:00:00 : 동내면   9326 ----------


 ---------- 2013-09-21 13:00:00 : 서  면   9329 ----------


 ---------- 2013-09-21 16:00:00 : 남산면   9331 ----------


 ---------- 2013-09-21 19:00:00 : 퇴계동   9332 ----------


 ---------- 2013-09-22 15:00:00 : 동  면   9333 ----------


 ---------- 2013-09-22 17:00:00 : 동  면   9336 ----------


 ---------- 2013-09-22 18:00:00 : 퇴계동   9338 ----------


 ---------- 2013-09-22 21:00:00 : 조운동   9339 ----------


 ---------- 2013-09-23 04:00:00 : 효자1동   9340 ----------


 ---------- 2013-09-23 10:00:00 : 서  면   9341 ----------


 ---------- 2013-09-23 11:00:00 : 동내면   9342 ----------


 ---------- 2013-09-23 13:00:00 : 남산면   9343 ----------


 ---------- 2013-09-23 13:00:00 : 소양동   9344 ----------


 ---------- 2013-09-23 13:00:00 : 약사명동   9346 ----------


 ---------- 2013-09-23 14:00:00 : 서  면   9347 ----------


 ---------- 2013-09-23 19:00:00 : 소양동   9348 ----------


 ---------- 2013-09-24 03:00:00 : 효자1동   9349 ----------


 ---------- 2013-09-24 06:00:00 : 효자1동   9350 ----------


 ---------- 2013-09-24 07:00:00 : 소양동   9351 ----------


 ---------- 2013-09-24 08:00:00 : 석사동   9352 ----------

 ---------- 2013-09-24 13:00:00 : 동  면   9353 ----------


 ---------- 2013-09-24 15:00:00 : 후평1동   9354 ----------


 ---------- 2013-09-24 17:00:00 : 서  면   9355 ----------


 ---------- 2013-09-24 21:00:00 : 후평1동   9356 ----------


 ---------- 2013-09-25 09:00:00 : 신북읍   9357 ----------


 ---------- 2013-09-25 12:00:00 : 남산면   9358 ----------


 ---------- 2013-09-25 12:00:00 : 신북읍   9359 ----------


 ---------- 2013-09-25 14:00:00 : 남산면   9360 ----------


 ---------- 2013-09-25 14:00:00 : 조운동   9361 ----------


 ---------- 2013-09-26 11:00:00 : 교  동   9362 ----------


 ---------- 2013-09-26 12:00:00 : 남산면   9363 ----------


 ---------- 2013-09-26 14:00:00 : 효자1동   9365 ----------


 ---------- 2013-09-26 16:00:00 : 동내면   9366 ----------


 ---------- 2013-09-26 21:00:00 : 강남동   9368 ----------


 ---------- 2013-09-27 01:00:00 : 퇴계동   9370 ----------


 ---------- 2013-09-27 09:00:00 : 약사명동   9372 ----------


 ---------- 2013-09-27 14:00:00 : 퇴계동   9373 ----------


 ---------- 2013-09-27 21:00:00 : 신사우동   9374 ----------


 ---------- 2013-09-28 02:00:00 : 석사동   9375 ----------


 ---------- 2013-09-28 15:00:00 : 북산면   9376 ----------


 ---------- 2013-09-28 18:00:00 : 서  면   9378 ----------


 ---------- 2013-09-29 15:00:00 : 신북읍   9380 ----------


 ---------- 2013-09-29 23:00:00 : 퇴계동   9381 ----------


 ---------- 2013-09-30 01:00:00 : 강남동   9382 ----------


 ---------- 2013-09-30 11:00:00 : 신동면   9383 ----------


 ---------- 2013-09-30 16:00:00 : 소양동   9384 ----------


 ---------- 2013-10-01 12:00:00 : 후평1동   9385 ----------


 ---------- 2013-10-01 12:00:00 : 동산면   9386 ----------


 ---------- 2013-10-01 13:00:00 : 남산면   9387 ----------


 ---------- 2013-10-01 15:00:00 : 신북읍   9389 ----------


 ---------- 2013-10-01 15:00:00 : 동  면   9390 ----------


 ---------- 2013-10-01 16:00:00 : 퇴계동   9391 ----------


 ---------- 2013-10-01 23:00:00 : 효자1동   9392 ----------


 ---------- 2013-10-02 00:00:00 : 신사우동   9394 ----------


 ---------- 2013-10-02 01:00:00 : 동내면   9395 ----------


 ---------- 2013-10-02 01:00:00 : 신사우동   9396 ----------


 ---------- 2013-10-02 10:00:00 : 북산면   9397 ----------


 ---------- 2013-10-02 12:00:00 : 근화동   9399 ----------


 ---------- 2013-10-02 14:00:00 : 석사동   9400 ----------


 ---------- 2013-10-02 15:00:00 : 근화동   9401 ----------


 ---------- 2013-10-02 17:00:00 : 동내면   9402 ----------


 ---------- 2013-10-03 08:00:00 : 강남동   9406 ----------


 ---------- 2013-10-03 08:00:00 : 조운동   9408 ----------


 ---------- 2013-10-03 13:00:00 : 신북읍   9409 ----------


 ---------- 2013-10-03 14:00:00 : 동내면   9410 ----------


 ---------- 2013-10-03 14:00:00 : 후평1동   9411 ----------


 ---------- 2013-10-03 16:00:00 : 퇴계동   9412 ----------


 ---------- 2013-10-03 17:00:00 : 석사동   9413 ----------


 ---------- 2013-10-04 02:00:00 : 동  면   9414 ----------


 ---------- 2013-10-04 05:00:00 : 효자1동   9415 ----------


 ---------- 2013-10-04 08:00:00 : 석사동   9417 ----------


 ---------- 2013-10-04 10:00:00 : 신북읍   9418 ----------


 ---------- 2013-10-04 11:00:00 : 신북읍   9419 ----------


 ---------- 2013-10-04 11:00:00 : 동  면   9420 ----------


 ---------- 2013-10-04 12:00:00 : 석사동   9421 ----------


 ---------- 2013-10-04 14:00:00 : 남산면   9422 ----------


 ---------- 2013-10-04 17:00:00 : 후평1동   9424 ----------


 ---------- 2013-10-04 18:00:00 : 근화동   9425 ----------


 ---------- 2013-10-04 21:00:00 : 근화동   9427 ----------


 ---------- 2013-10-04 23:00:00 : 석사동   9428 ----------


 ---------- 2013-10-05 04:00:00 : 약사명동   9430 ----------


 ---------- 2013-10-05 09:00:00 : 서  면   9432 ----------


 ---------- 2013-10-05 09:00:00 : 신사우동   9433 ----------


 ---------- 2013-10-05 10:00:00 : 강남동   9436 ----------


 ---------- 2013-10-05 10:00:00 : 동  면   9437 ----------


 ---------- 2013-10-05 12:00:00 : 강남동   9438 ----------


 ---------- 2013-10-05 13:00:00 : 남산면   9440 ----------


 ---------- 2013-10-05 14:00:00 : 석사동   9441 ----------


 ---------- 2013-10-05 14:00:00 : 남산면   9443 ----------


 ---------- 2013-10-05 14:00:00 : 신북읍   9444 ----------


 ---------- 2013-10-05 15:00:00 : 석사동   9445 ----------


 ---------- 2013-10-05 15:00:00 : 소양동   9446 ----------


 ---------- 2013-10-05 20:00:00 : 사북면   9447 ----------


 ---------- 2013-10-05 21:00:00 : 북산면   9448 ----------


 ---------- 2013-10-06 07:00:00 : 신북읍   9449 ----------


 ---------- 2013-10-06 09:00:00 : 퇴계동   9450 ----------


 ---------- 2013-10-06 13:00:00 : 신동면   9451 ----------


 ---------- 2013-10-06 14:00:00 : 퇴계동   9452 ----------


 ---------- 2013-10-06 15:00:00 : 신사우동   9453 ----------


 ---------- 2013-10-06 19:00:00 : 효자1동   9454 ----------


 ---------- 2013-10-06 19:00:00 : 남산면   9455 ----------


 ---------- 2013-10-07 04:00:00 : 석사동   9456 ----------


 ---------- 2013-10-07 10:00:00 : 후평1동   9458 ----------


 ---------- 2013-10-07 11:00:00 : 서  면   9459 ----------


 ---------- 2013-10-07 11:00:00 : 동내면   9460 ----------


 ---------- 2013-10-07 14:00:00 : 동내면   9461 ----------


 ---------- 2013-10-07 16:00:00 : 동산면   9462 ----------


 ---------- 2013-10-07 20:00:00 : 퇴계동   9464 ----------


 ---------- 2013-10-07 21:00:00 : 동내면   9465 ----------


 ---------- 2013-10-07 21:00:00 : 남산면   9466 ----------


 ---------- 2013-10-08 03:00:00 : 신북읍   9467 ----------


 ---------- 2013-10-08 12:00:00 : 후평1동   9468 ----------


 ---------- 2013-10-08 13:00:00 : 효자1동   9469 ----------


 ---------- 2013-10-09 07:00:00 : 근화동   9470 ----------


 ---------- 2013-10-09 09:00:00 : 동  면   9471 ----------


 ---------- 2013-10-09 12:00:00 : 사북면   9474 ----------


 ---------- 2013-10-09 13:00:00 : 동산면   9475 ----------


 ---------- 2013-10-09 15:00:00 : 강남동   9476 ----------


 ---------- 2013-10-09 16:00:00 : 신동면   9479 ----------


 ---------- 2013-10-09 17:00:00 : 서  면   9482 ----------


 ---------- 2013-10-09 20:00:00 : 후평1동   9484 ----------


 ---------- 2013-10-10 00:00:00 : 남산면   9485 ----------


 ---------- 2013-10-10 01:00:00 : 효자1동   9486 ----------


 ---------- 2013-10-10 06:00:00 : 석사동   9488 ----------


 ---------- 2013-10-10 12:00:00 : 퇴계동   9489 ----------


 ---------- 2013-10-10 12:00:00 : 교  동   9490 ----------


 ---------- 2013-10-10 13:00:00 : 서  면   9491 ----------


 ---------- 2013-10-10 14:00:00 : 강남동   9492 ----------


 ---------- 2013-10-10 14:00:00 : 남  면   9493 ----------


 ---------- 2013-10-10 14:00:00 : 후평1동   9494 ----------


 ---------- 2013-10-10 18:00:00 : 남산면   9495 ----------


 ---------- 2013-10-10 21:00:00 : 약사명동   9497 ----------


 ---------- 2013-10-11 06:00:00 : 후평1동   9498 ----------


 ---------- 2013-10-11 10:00:00 : 신북읍   9499 ----------


 ---------- 2013-10-11 11:00:00 : 동내면   9500 ----------


 ---------- 2013-10-11 13:00:00 : 강남동   9501 ----------


 ---------- 2013-10-11 18:00:00 : 동  면   9504 ----------


 ---------- 2013-10-12 07:00:00 : 동  면   9505 ----------


 ---------- 2013-10-12 08:00:00 : 동산면   9507 ----------


 ---------- 2013-10-12 10:00:00 : 남산면   9508 ----------


 ---------- 2013-10-12 10:00:00 : 신북읍   9510 ----------


 ---------- 2013-10-12 13:00:00 : 신동면   9511 ----------


 ---------- 2013-10-12 15:00:00 : 동내면   9512 ----------


 ---------- 2013-10-12 17:00:00 : 사북면   9513 ----------


 ---------- 2013-10-12 20:00:00 : 남산면   9514 ----------


 ---------- 2013-10-12 20:00:00 : 퇴계동   9515 ----------


 ---------- 2013-10-12 21:00:00 : 신북읍   9516 ----------


 ---------- 2013-10-13 10:00:00 : 사북면   9517 ----------


 ---------- 2013-10-13 13:00:00 : 사북면   9518 ----------


 ---------- 2013-10-14 09:00:00 : 사북면   9519 ----------


 ---------- 2013-10-14 09:00:00 : 동산면   9520 ----------


 ---------- 2013-10-14 11:00:00 : 퇴계동   9521 ----------


 ---------- 2013-10-14 13:00:00 : 석사동   9522 ----------


 ---------- 2013-10-14 15:00:00 : 남  면   9525 ----------


 ---------- 2013-10-15 07:00:00 : 퇴계동   9526 ----------


 ---------- 2013-10-15 08:00:00 : 동산면   9527 ----------


 ---------- 2013-10-15 09:00:00 : 신동면   9528 ----------


 ---------- 2013-10-15 11:00:00 : 퇴계동   9529 ----------


 ---------- 2013-10-15 14:00:00 : 사북면   9530 ----------

 ---------- 2013-10-15 18:00:00 : 효자1동   9531 ----------


 ---------- 2013-10-16 01:00:00 : 석사동   9533 ----------


 ---------- 2013-10-16 09:00:00 : 사북면   9534 ----------


 ---------- 2013-10-16 16:00:00 : 조운동   9535 ----------


 ---------- 2013-10-16 19:00:00 : 신동면   9536 ----------


 ---------- 2013-10-17 05:00:00 : 석사동   9538 ----------


 ---------- 2013-10-17 09:00:00 : 사북면   9539 ----------


 ---------- 2013-10-17 10:00:00 : 동  면   9540 ----------


 ---------- 2013-10-17 16:00:00 : 효자1동   9541 ----------


 ---------- 2013-10-17 16:00:00 : 신북읍   9542 ----------


 ---------- 2013-10-17 20:00:00 : 신사우동   9543 ----------


 ---------- 2013-10-17 21:00:00 : 석사동   9545 ----------


 ---------- 2013-10-18 09:00:00 : 신북읍   9546 ----------


 ---------- 2013-10-18 09:00:00 : 북산면   9547 ----------


 ---------- 2013-10-18 12:00:00 : 퇴계동   9548 ----------


 ---------- 2013-10-18 14:00:00 : 신북읍   9549 ----------


 ---------- 2013-10-18 22:00:00 : 조운동   9550 ----------


 ---------- 2013-10-19 05:00:00 : 석사동   9551 ----------


 ---------- 2013-10-19 07:00:00 : 후평1동   9553 ----------


 ---------- 2013-10-19 08:00:00 : 후평1동   9554 ----------


 ---------- 2013-10-19 12:00:00 : 석사동   9555 ----------


 ---------- 2013-10-19 13:00:00 : 동내면   9556 ----------


 ---------- 2013-10-19 15:00:00 : 신사우동   9557 ----------


 ---------- 2013-10-19 18:00:00 : 남산면   9558 ----------


 ---------- 2013-10-20 10:00:00 : 남산면   9561 ----------


 ---------- 2013-10-20 13:00:00 : 서  면   9562 ----------


 ---------- 2013-10-20 13:00:00 : 후평1동   9563 ----------


 ---------- 2013-10-20 16:00:00 : 효자1동   9564 ----------


 ---------- 2013-10-20 18:00:00 : 퇴계동   9565 ----------


 ---------- 2013-10-21 10:00:00 : 사북면   9566 ----------


 ---------- 2013-10-21 11:00:00 : 신북읍   9567 ----------


 ---------- 2013-10-21 12:00:00 : 약사명동   9568 ----------


 ---------- 2013-10-21 13:00:00 : 서  면   9569 ----------


 ---------- 2013-10-21 13:00:00 : 효자1동   9570 ----------


 ---------- 2013-10-21 15:00:00 : 남산면   9571 ----------


 ---------- 2013-10-21 15:00:00 : 후평1동   9573 ----------


 ---------- 2013-10-21 16:00:00 : 퇴계동   9575 ----------


 ---------- 2013-10-22 10:00:00 : 효자1동   9576 ----------


 ---------- 2013-10-22 12:00:00 : 서  면   9577 ----------


 ---------- 2013-10-22 15:00:00 : 석사동   9578 ----------


 ---------- 2013-10-22 15:00:00 : 동내면   9580 ----------


 ---------- 2013-10-23 11:00:00 : 후평1동   9581 ----------


 ---------- 2013-10-23 13:00:00 : 소양동   9584 ----------


 ---------- 2013-10-23 17:00:00 : 신북읍   9587 ----------


 ---------- 2013-10-23 21:00:00 : 근화동   9589 ----------


 ---------- 2013-10-23 21:00:00 : 퇴계동   9590 ----------


 ---------- 2013-10-24 01:00:00 : 소양동   9591 ----------


 ---------- 2013-10-24 07:00:00 : 후평1동   9592 ----------


 ---------- 2013-10-24 16:00:00 : 서  면   9594 ----------


 ---------- 2013-10-25 08:00:00 : 신사우동   9595 ----------


 ---------- 2013-10-25 09:00:00 : 남산면   9596 ----------


 ---------- 2013-10-25 15:00:00 : 후평1동   9597 ----------


 ---------- 2013-10-25 17:00:00 : 동내면   9598 ----------


 ---------- 2013-10-25 23:00:00 : 약사명동   9600 ----------


 ---------- 2013-10-26 03:00:00 : 효자1동   9601 ----------


 ---------- 2013-10-26 17:00:00 : 사북면   9603 ----------


 ---------- 2013-10-26 19:00:00 : 남산면   9605 ----------


 ---------- 2013-10-26 21:00:00 : 남산면   9607 ----------


 ---------- 2013-10-27 01:00:00 : 석사동   9609 ----------


 ---------- 2013-10-27 10:00:00 : 남산면   9610 ----------


 ---------- 2013-10-27 16:00:00 : 남산면   9611 ----------


 ---------- 2013-10-27 23:00:00 : 신사우동   9612 ----------


 ---------- 2013-10-27 23:00:00 : 동  면   9613 ----------


 ---------- 2013-10-28 08:00:00 : 후평1동   9614 ----------


 ---------- 2013-10-28 10:00:00 : 강남동   9615 ----------


 ---------- 2013-10-28 13:00:00 : 남  면   9617 ----------


 ---------- 2013-10-28 13:00:00 : 남산면   9618 ----------


 ---------- 2013-10-28 16:00:00 : 후평1동   9619 ----------


 ---------- 2013-10-28 18:00:00 : 효자1동   9620 ----------


 ---------- 2013-10-28 19:00:00 : 서  면   9621 ----------


 ---------- 2013-10-28 20:00:00 : 퇴계동   9622 ----------


 ---------- 2013-10-29 00:00:00 : 후평1동   9624 ----------


 ---------- 2013-10-29 03:00:00 : 효자1동   9625 ----------


 ---------- 2013-10-29 10:00:00 : 신사우동   9626 ----------


 ---------- 2013-10-29 19:00:00 : 석사동   9628 ----------


 ---------- 2013-10-30 01:00:00 : 소양동   9630 ----------


 ---------- 2013-10-30 01:00:00 : 퇴계동   9631 ----------


 ---------- 2013-10-30 02:00:00 : 동  면   9632 ----------


 ---------- 2013-10-30 06:00:00 : 동내면   9634 ----------


 ---------- 2013-10-30 14:00:00 : 동  면   9637 ----------


 ---------- 2013-10-30 19:00:00 : 퇴계동   9639 ----------


 ---------- 2013-10-31 11:00:00 : 동  면   9640 ----------


 ---------- 2013-10-31 20:00:00 : 신동면   9641 ----------


 ---------- 2013-10-31 20:00:00 : 강남동   9643 ----------


 ---------- 2013-10-31 23:00:00 : 효자1동   9644 ----------


 ---------- 2013-11-01 10:00:00 : 강남동   9645 ----------


 ---------- 2013-11-01 12:00:00 : 동  면   9646 ----------


 ---------- 2013-11-01 13:00:00 : 후평1동   9647 ----------


 ---------- 2013-11-01 16:00:00 : 후평1동   9648 ----------


 ---------- 2013-11-01 17:00:00 : 조운동   9650 ----------


 ---------- 2013-11-01 18:00:00 : 근화동   9651 ----------


 ---------- 2013-11-01 18:00:00 : 신사우동   9652 ----------


 ---------- 2013-11-01 21:00:00 : 동  면   9654 ----------


 ---------- 2013-11-02 08:00:00 : 근화동   9655 ----------


 ---------- 2013-11-02 11:00:00 : 효자1동   9656 ----------


 ---------- 2013-11-02 13:00:00 : 사북면   9658 ----------


 ---------- 2013-11-02 14:00:00 : 동산면   9661 ----------


 ---------- 2013-11-02 16:00:00 : 북산면   9663 ----------


 ---------- 2013-11-02 20:00:00 : 퇴계동   9664 ----------


 ---------- 2013-11-03 00:00:00 : 남산면   9667 ----------


 ---------- 2013-11-03 01:00:00 : 석사동   9669 ----------


 ---------- 2013-11-03 08:00:00 : 동  면   9671 ----------


 ---------- 2013-11-03 10:00:00 : 사북면   9672 ----------


 ---------- 2013-11-03 11:00:00 : 효자1동   9673 ----------


 ---------- 2013-11-03 13:00:00 : 신사우동   9674 ----------


 ---------- 2013-11-04 07:00:00 : 남  면   9675 ----------


 ---------- 2013-11-04 13:00:00 : 사북면   9676 ----------


 ---------- 2013-11-04 18:00:00 : 효자1동   9677 ----------


 ---------- 2013-11-04 20:00:00 : 효자1동   9678 ----------


 ---------- 2013-11-05 00:00:00 : 교  동   9679 ----------


 ---------- 2013-11-05 01:00:00 : 후평1동   9680 ----------


 ---------- 2013-11-05 07:00:00 : 효자1동   9681 ----------


 ---------- 2013-11-05 12:00:00 : 퇴계동   9682 ----------


 ---------- 2013-11-05 14:00:00 : 퇴계동   9683 ----------


 ---------- 2013-11-05 15:00:00 : 강남동   9684 ----------


 ---------- 2013-11-05 15:00:00 : 서  면   9685 ----------


 ---------- 2013-11-05 19:00:00 : 석사동   9687 ----------


 ---------- 2013-11-05 20:00:00 : 후평1동   9688 ----------


 ---------- 2013-11-05 21:00:00 : 후평1동   9689 ----------


 ---------- 2013-11-06 00:00:00 : 후평1동   9690 ----------


 ---------- 2013-11-06 04:00:00 : 퇴계동   9691 ----------


 ---------- 2013-11-06 11:00:00 : 신북읍   9692 ----------


 ---------- 2013-11-06 12:00:00 : 사북면   9694 ----------


 ---------- 2013-11-06 13:00:00 : 사북면   9695 ----------


 ---------- 2013-11-07 16:00:00 : 사북면   9696 ----------


 ---------- 2013-11-07 18:00:00 : 효자1동   9697 ----------


 ---------- 2013-11-07 20:00:00 : 약사명동   9698 ----------


 ---------- 2013-11-07 21:00:00 : 동  면   9700 ----------


 ---------- 2013-11-08 11:00:00 : 남산면   9702 ----------


 ---------- 2013-11-08 11:00:00 : 약사명동   9703 ----------


 ---------- 2013-11-08 14:00:00 : 남산면   9704 ----------


 ---------- 2013-11-08 17:00:00 : 약사명동   9705 ----------


 ---------- 2013-11-08 20:00:00 : 석사동   9706 ----------


 ---------- 2013-11-09 01:00:00 : 신사우동   9707 ----------


 ---------- 2013-11-09 10:00:00 : 소양동   9709 ----------


 ---------- 2013-11-09 13:00:00 : 동내면   9711 ----------


 ---------- 2013-11-09 14:00:00 : 동내면   9715 ----------


 ---------- 2013-11-09 17:00:00 : 퇴계동   9717 ----------

 ---------- 2013-11-09 19:00:00 : 퇴계동   9719 ----------


 ---------- 2013-11-09 22:00:00 : 퇴계동   9720 ----------


 ---------- 2013-11-10 04:00:00 : 효자1동   9721 ----------


 ---------- 2013-11-10 11:00:00 : 남산면   9722 ----------


 ---------- 2013-11-10 12:00:00 : 효자1동   9723 ----------


 ---------- 2013-11-10 14:00:00 : 신북읍   9724 ----------


 ---------- 2013-11-11 01:00:00 : 효자1동   9725 ----------


 ---------- 2013-11-11 07:00:00 : 동  면   9726 ----------


 ---------- 2013-11-11 08:00:00 : 후평1동   9728 ----------


 ---------- 2013-11-11 18:00:00 : 조운동   9729 ----------


 ---------- 2013-11-11 20:00:00 : 조운동   9730 ----------


 ---------- 2013-11-11 23:00:00 : 신동면   9731 ----------


 ---------- 2013-11-12 01:00:00 : 후평1동   9732 ----------


 ---------- 2013-11-12 11:00:00 : 사북면   9734 ----------


 ---------- 2013-11-12 16:00:00 : 후평1동   9735 ----------


 ---------- 2013-11-12 19:00:00 : 교  동   9736 ----------


 ---------- 2013-11-12 22:00:00 : 신사우동   9737 ----------


 ---------- 2013-11-13 04:00:00 : 강남동   9738 ----------


 ---------- 2013-11-13 14:00:00 : 효자1동   9739 ----------


 ---------- 2013-11-13 16:00:00 : 신동면   9741 ----------


 ---------- 2013-11-13 17:00:00 : 근화동   9742 ----------


 ---------- 2013-11-13 18:00:00 : 후평1동   9743 ----------


 ---------- 2013-11-14 14:00:00 : 효자1동   9744 ----------


 ---------- 2013-11-14 16:00:00 : 남  면   9745 ----------


 ---------- 2013-11-16 06:00:00 : 근화동   9747 ----------


 ---------- 2013-11-16 10:00:00 : 동산면   9749 ----------


 ---------- 2013-11-16 14:00:00 : 동산면   9751 ----------


 ---------- 2013-11-16 16:00:00 : 석사동   9752 ----------


 ---------- 2013-11-16 17:00:00 : 남산면   9753 ----------


 ---------- 2013-11-17 05:00:00 : 신사우동   9754 ----------


 ---------- 2013-11-17 08:00:00 : 석사동   9757 ----------


 ---------- 2013-11-17 19:00:00 : 후평1동   9758 ----------


 ---------- 2013-11-17 20:00:00 : 신북읍   9759 ----------


 ---------- 2013-11-17 22:00:00 : 효자1동   9760 ----------


 ---------- 2013-11-18 13:00:00 : 후평1동   9761 ----------


 ---------- 2013-11-18 15:00:00 : 강남동   9762 ----------


 ---------- 2013-11-18 18:00:00 : 신사우동   9763 ----------


 ---------- 2013-11-19 10:00:00 : 동산면   9764 ----------


 ---------- 2013-11-19 11:00:00 : 신북읍   9765 ----------


 ---------- 2013-11-19 18:00:00 : 강남동   9767 ----------


 ---------- 2013-11-19 20:00:00 : 강남동   9768 ----------


 ---------- 2013-11-19 22:00:00 : 석사동   9770 ----------


 ---------- 2013-11-20 10:00:00 : 강남동   9772 ----------


 ---------- 2013-11-20 12:00:00 : 소양동   9773 ----------


 ---------- 2013-11-20 17:00:00 : 근화동   9774 ----------


 ---------- 2013-11-20 18:00:00 : 신북읍   9775 ----------


 ---------- 2013-11-21 14:00:00 : 신사우동   9776 ----------


 ---------- 2013-11-21 17:00:00 : 신북읍   9778 ----------


 ---------- 2013-11-21 22:00:00 : 교  동   9779 ----------


 ---------- 2013-11-23 02:00:00 : 효자1동   9780 ----------


 ---------- 2013-11-23 07:00:00 : 동산면   9782 ----------


 ---------- 2013-11-23 11:00:00 : 효자1동   9784 ----------


 ---------- 2013-11-23 16:00:00 : 석사동   9785 ----------


 ---------- 2013-11-23 23:00:00 : 동내면   9786 ----------


 ---------- 2013-11-24 13:00:00 : 조운동   9787 ----------


 ---------- 2013-11-24 14:00:00 : 신북읍   9788 ----------


 ---------- 2013-11-24 14:00:00 : 후평1동   9789 ----------


 ---------- 2013-11-25 08:00:00 : 석사동   9790 ----------


 ---------- 2013-11-25 09:00:00 : 신사우동   9791 ----------


 ---------- 2013-11-25 12:00:00 : 동  면   9792 ----------


 ---------- 2013-11-25 16:00:00 : 소양동   9794 ----------


 ---------- 2013-11-25 17:00:00 : 북산면   9795 ----------


 ---------- 2013-11-25 19:00:00 : 후평1동   9797 ----------


 ---------- 2013-11-25 22:00:00 : 강남동   9799 ----------


 ---------- 2013-11-26 17:00:00 : 후평1동   9801 ----------


 ---------- 2013-11-27 01:00:00 : 석사동   9802 ----------


 ---------- 2013-11-27 01:00:00 : 퇴계동   9803 ----------


 ---------- 2013-11-27 14:00:00 : 남  면   9804 ----------


 ---------- 2013-11-27 16:00:00 : 동산면   9807 ----------


 ---------- 2013-11-27 20:00:00 : 강남동   9808 ----------


 ---------- 2013-11-28 10:00:00 : 근화동   9809 ----------


 ---------- 2013-11-29 01:00:00 : 후평1동   9811 ----------


 ---------- 2013-11-29 17:00:00 : 퇴계동   9812 ----------


 ---------- 2013-11-30 04:00:00 : 석사동   9813 ----------


 ---------- 2013-11-30 05:00:00 : 남산면   9814 ----------


 ---------- 2013-11-30 10:00:00 : 후평1동   9815 ----------


 ---------- 2013-11-30 16:00:00 : 후평1동   9816 ----------


 ---------- 2013-11-30 17:00:00 : 후평1동   9817 ----------


 ---------- 2013-11-30 23:00:00 : 후평1동   9818 ----------


 ---------- 2013-12-01 01:00:00 : 효자1동   9819 ----------


 ---------- 2013-12-01 11:00:00 : 근화동   9820 ----------


 ---------- 2013-12-01 12:00:00 : 신북읍   9821 ----------


 ---------- 2013-12-01 14:00:00 : 후평1동   9822 ----------


 ---------- 2013-12-02 15:00:00 : 신북읍   9824 ----------


 ---------- 2013-12-02 18:00:00 : 동내면   9825 ----------


 ---------- 2013-12-02 20:00:00 : 동  면   9826 ----------


 ---------- 2013-12-03 07:00:00 : 후평1동   9828 ----------


 ---------- 2013-12-03 08:00:00 : 동산면   9831 ----------


 ---------- 2013-12-03 13:00:00 : 효자1동   9832 ----------


 ---------- 2013-12-03 15:00:00 : 퇴계동   9835 ----------


 ---------- 2013-12-03 19:00:00 : 신북읍   9836 ----------


 ---------- 2013-12-04 01:00:00 : 동내면   9837 ----------


 ---------- 2013-12-04 01:00:00 : 후평1동   9838 ----------


 ---------- 2013-12-04 12:00:00 : 근화동   9839 ----------


 ---------- 2013-12-04 13:00:00 : 동  면   9840 ----------


 ---------- 2013-12-04 19:00:00 : 약사명동   9841 ----------


 ---------- 2013-12-05 02:00:00 : 후평1동   9842 ----------


 ---------- 2013-12-05 12:00:00 : 신동면   9843 ----------


 ---------- 2013-12-05 12:00:00 : 효자1동   9844 ----------


 ---------- 2013-12-06 12:00:00 : 신사우동   9845 ----------


 ---------- 2013-12-06 23:00:00 : 후평1동   9846 ----------


 ---------- 2013-12-07 01:00:00 : 근화동   9847 ----------


 ---------- 2013-12-07 13:00:00 : 신북읍   9848 ----------


 ---------- 2013-12-07 15:00:00 : 퇴계동   9849 ----------


 ---------- 2013-12-07 19:00:00 : 퇴계동   9850 ----------


 ---------- 2013-12-07 23:00:00 : 강남동   9852 ----------


 ---------- 2013-12-07 23:00:00 : 남산면   9853 ----------


 ---------- 2013-12-08 03:00:00 : 약사명동   9854 ----------


 ---------- 2013-12-08 09:00:00 : 후평1동   9855 ----------


 ---------- 2013-12-08 11:00:00 : 신북읍   9856 ----------


 ---------- 2013-12-08 14:00:00 : 효자1동   9857 ----------


 ---------- 2013-12-08 16:00:00 : 후평1동   9858 ----------


 ---------- 2013-12-09 03:00:00 : 서  면   9859 ----------


 ---------- 2013-12-09 03:00:00 : 신사우동   9861 ----------


 ---------- 2013-12-09 06:00:00 : 소양동   9862 ----------


 ---------- 2013-12-09 15:00:00 : 후평1동   9865 ----------


 ---------- 2013-12-09 19:00:00 : 퇴계동   9866 ----------


 ---------- 2013-12-10 08:00:00 : 후평1동   9867 ----------


 ---------- 2013-12-10 13:00:00 : 조운동   9869 ----------


 ---------- 2013-12-10 21:00:00 : 퇴계동   9870 ----------


 ---------- 2013-12-10 23:00:00 : 서  면   9871 ----------


 ---------- 2013-12-11 03:00:00 : 석사동   9872 ----------


 ---------- 2013-12-11 06:00:00 : 동  면   9874 ----------


 ---------- 2013-12-11 09:00:00 : 후평1동   9875 ----------


 ---------- 2013-12-11 17:00:00 : 신북읍   9878 ----------


 ---------- 2013-12-11 20:00:00 : 신사우동   9879 ----------


 ---------- 2013-12-12 01:00:00 : 동내면   9880 ----------


 ---------- 2013-12-12 04:00:00 : 근화동   9881 ----------


 ---------- 2013-12-12 09:00:00 : 남산면   9882 ----------


 ---------- 2013-12-12 11:00:00 : 조운동   9884 ----------


 ---------- 2013-12-12 15:00:00 : 강남동   9885 ----------


 ---------- 2013-12-12 16:00:00 : 남산면   9886 ----------


 ---------- 2013-12-12 20:00:00 : 소양동   9887 ----------


 ---------- 2013-12-13 03:00:00 : 조운동   9888 ----------


 ---------- 2013-12-13 06:00:00 : 사북면   9889 ----------


 ---------- 2013-12-13 11:00:00 : 남산면   9890 ----------


 ---------- 2013-12-13 15:00:00 : 신동면   9891 ----------


 ---------- 2013-12-13 16:00:00 : 후평1동   9892 ----------

 ---------- 2013-12-13 17:00:00 : 남산면   9893 ----------


 ---------- 2013-12-14 02:00:00 : 퇴계동   9895 ----------


 ---------- 2013-12-14 10:00:00 : 퇴계동   9898 ----------


 ---------- 2013-12-14 12:00:00 : 남  면   9901 ----------


 ---------- 2013-12-14 20:00:00 : 강남동   9903 ----------


 ---------- 2013-12-14 21:00:00 : 강남동   9904 ----------


 ---------- 2013-12-15 03:00:00 : 효자1동   9905 ----------


 ---------- 2013-12-16 00:00:00 : 신북읍   9906 ----------


 ---------- 2013-12-16 08:00:00 : 퇴계동   9907 ----------


 ---------- 2013-12-16 12:00:00 : 후평1동   9908 ----------


 ---------- 2013-12-16 13:00:00 : 남산면   9909 ----------


 ---------- 2013-12-16 21:00:00 : 석사동   9910 ----------


 ---------- 2013-12-17 12:00:00 : 신북읍   9911 ----------


 ---------- 2013-12-17 14:00:00 : 강남동   9913 ----------


 ---------- 2013-12-17 16:00:00 : 신사우동   9915 ----------


 ---------- 2013-12-17 19:00:00 : 석사동   9917 ----------


 ---------- 2013-12-17 19:00:00 : 소양동   9918 ----------


 ---------- 2013-12-17 21:00:00 : 남산면   9919 ----------


 ---------- 2013-12-18 05:00:00 : 신북읍   9921 ----------


 ---------- 2013-12-18 08:00:00 : 효자1동   9923 ----------


 ---------- 2013-12-18 10:00:00 : 석사동   9924 ----------


 ---------- 2013-12-18 13:00:00 : 석사동   9925 ----------


 ---------- 2013-12-18 17:00:00 : 후평1동   9927 ----------


 ---------- 2013-12-18 18:00:00 : 신사우동   9929 ----------


 ---------- 2013-12-18 23:00:00 : 약사명동   9931 ----------


 ---------- 2013-12-19 07:00:00 : 효자1동   9932 ----------


 ---------- 2013-12-19 14:00:00 : 퇴계동   9933 ----------


 ---------- 2013-12-19 21:00:00 : 조운동   9934 ----------


 ---------- 2013-12-20 00:00:00 : 석사동   9936 ----------


 ---------- 2013-12-20 06:00:00 : 후평1동   9937 ----------


 ---------- 2013-12-20 10:00:00 : 소양동   9938 ----------


 ---------- 2013-12-20 12:00:00 : 효자1동   9939 ----------


 ---------- 2013-12-20 16:00:00 : 동산면   9940 ----------


 ---------- 2013-12-20 17:00:00 : 동내면   9943 ----------


 ---------- 2013-12-21 04:00:00 : 후평1동   9945 ----------


 ---------- 2013-12-22 13:00:00 : 후평1동   9946 ----------


 ---------- 2013-12-22 16:00:00 : 동  면   9947 ----------


 ---------- 2013-12-22 22:00:00 : 소양동   9948 ----------


 ---------- 2013-12-23 03:00:00 : 신북읍   9949 ----------


 ---------- 2013-12-23 12:00:00 : 신동면   9950 ----------


 ---------- 2013-12-23 14:00:00 : 조운동   9951 ----------


 ---------- 2013-12-23 18:00:00 : 후평1동   9952 ----------


 ---------- 2013-12-24 01:00:00 : 퇴계동   9955 ----------


 ---------- 2013-12-24 02:00:00 : 신사우동   9956 ----------


 ---------- 2013-12-24 04:00:00 : 효자1동   9957 ----------


 ---------- 2013-12-25 11:00:00 : 석사동   9958 ----------


 ---------- 2013-12-25 11:00:00 : 후평1동   9959 ----------


 ---------- 2013-12-25 22:00:00 : 후평1동   9961 ----------


 ---------- 2013-12-26 01:00:00 : 약사명동   9963 ----------


 ---------- 2013-12-26 09:00:00 : 동산면   9965 ----------


 ---------- 2013-12-26 12:00:00 : 후평1동   9967 ----------


 ---------- 2013-12-26 14:00:00 : 석사동   9968 ----------


 ---------- 2013-12-26 15:00:00 : 동내면   9969 ----------


 ---------- 2013-12-26 21:00:00 : 퇴계동   9971 ----------


 ---------- 2013-12-26 23:00:00 : 석사동   9972 ----------


 ---------- 2013-12-27 21:00:00 : 후평1동   9973 ----------


 ---------- 2013-12-27 23:00:00 : 신사우동   9974 ----------


 ---------- 2013-12-28 11:00:00 : 신북읍   9975 ----------


 ---------- 2013-12-28 13:00:00 : 근화동   9976 ----------


 ---------- 2013-12-28 15:00:00 : 강남동   9977 ----------


 ---------- 2013-12-28 19:00:00 : 동  면   9979 ----------


 ---------- 2013-12-29 00:00:00 : 남산면   9980 ----------


 ---------- 2013-12-29 05:00:00 : 동  면   9981 ----------


 ---------- 2013-12-29 07:00:00 : 동내면   9983 ----------


 ---------- 2013-12-29 11:00:00 : 남  면   9984 ----------


 ---------- 2013-12-29 14:00:00 : 효자1동   9985 ----------


 ---------- 2013-12-29 16:00:00 : 동내면   9986 ----------


 ---------- 2013-12-29 18:00:00 : 신사우동   9987 ----------


 ---------- 2013-12-29 20:00:00 : 강남동   9988 ----------


 ---------- 2013-12-30 02:00:00 : 효자1동   9989 ----------


 ---------- 2013-12-30 02:00:00 : 근화동   9990 ----------


 ---------- 2013-12-30 02:00:00 : 신사우동   9991 ----------


 ---------- 2013-12-30 08:00:00 : 남산면   9992 ----------


 ---------- 2013-12-30 15:00:00 : 강남동   9993 ----------


 ---------- 2013-12-30 15:00:00 : 남산면   9994 ----------


 ---------- 2013-12-30 23:00:00 : 동내면   9996 ----------


 ---------- 2013-12-31 02:00:00 : 퇴계동   9997 ----------


 ---------- 2013-12-31 08:00:00 : 약사명동   9998 ----------


 ---------- 2014-01-01 10:00:00 : 동내면   9999 ----------


 ---------- 2014-01-01 10:00:00 : 퇴계동   10000 ----------


 ---------- 2014-01-01 14:00:00 : 소양동   10003 ----------


 ---------- 2014-01-01 17:00:00 : 약사명동   10004 ----------


 ---------- 2014-01-01 17:00:00 : 퇴계동   10005 ----------


 ---------- 2014-01-01 18:00:00 : 퇴계동   10006 ----------


 ---------- 2014-01-01 19:00:00 : 퇴계동   10007 ----------


 ---------- 2014-01-01 22:00:00 : 강남동   10008 ----------


 ---------- 2014-01-01 23:00:00 : 후평1동   10010 ----------


 ---------- 2014-01-02 00:00:00 : 근화동   10011 ----------


 ---------- 2014-01-02 01:00:00 : 퇴계동   10013 ----------


 ---------- 2014-01-02 11:00:00 : 서  면   10016 ----------


 ---------- 2014-01-02 15:00:00 : 후평1동   10018 ----------


 ---------- 2014-01-03 03:00:00 : 석사동   10019 ----------


 ---------- 2014-01-03 10:00:00 : 약사명동   10020 ----------


 ---------- 2014-01-03 14:00:00 : 동내면   10022 ----------


 ---------- 2014-01-03 16:00:00 : 소양동   10024 ----------


 ---------- 2014-01-03 23:00:00 : 동내면   10026 ----------


 ---------- 2014-01-04 09:00:00 : 소양동   10027 ----------


 ---------- 2014-01-04 11:00:00 : 신북읍   10028 ----------


 ---------- 2014-01-04 14:00:00 : 서  면   10032 ----------


 ---------- 2014-01-04 14:00:00 : 사북면   10033 ----------


 ---------- 2014-01-04 18:00:00 : 남산면   10037 ----------


 ---------- 2014-01-04 23:00:00 : 동내면   10038 ----------


 ---------- 2014-01-05 12:00:00 : 동내면   10040 ----------


 ---------- 2014-01-06 03:00:00 : 동내면   10042 ----------


 ---------- 2014-01-06 08:00:00 : 소양동   10044 ----------


 ---------- 2014-01-06 11:00:00 : 석사동   10045 ----------


 ---------- 2014-01-06 12:00:00 : 후평1동   10046 ----------


 ---------- 2014-01-06 14:00:00 : 강남동   10047 ----------


 ---------- 2014-01-06 16:00:00 : 약사명동   10048 ----------


 ---------- 2014-01-06 17:00:00 : 근화동   10049 ----------


 ---------- 2014-01-06 21:00:00 : 근화동   10050 ----------


 ---------- 2014-01-07 15:00:00 : 효자1동   10051 ----------


 ---------- 2014-01-07 18:00:00 : 석사동   10052 ----------


 ---------- 2014-01-07 21:00:00 : 후평1동   10053 ----------


 ---------- 2014-01-08 08:00:00 : 퇴계동   10057 ----------


 ---------- 2014-01-08 09:00:00 : 근화동   10060 ----------


 ---------- 2014-01-08 12:00:00 : 남산면   10063 ----------


 ---------- 2014-01-08 13:00:00 : 남산면   10064 ----------


 ---------- 2014-01-08 14:00:00 : 후평1동   10065 ----------


 ---------- 2014-01-08 21:00:00 : 석사동   10066 ----------


 ---------- 2014-01-08 22:00:00 : 근화동   10068 ----------


 ---------- 2014-01-08 23:00:00 : 효자1동   10069 ----------


 ---------- 2014-01-09 00:00:00 : 후평1동   10070 ----------


 ---------- 2014-01-09 10:00:00 : 후평1동   10071 ----------


 ---------- 2014-01-09 20:00:00 : 신사우동   10072 ----------


 ---------- 2014-01-09 20:00:00 : 신북읍   10073 ----------


 ---------- 2014-01-10 10:00:00 : 동  면   10074 ----------


 ---------- 2014-01-10 19:00:00 : 효자1동   10075 ----------


 ---------- 2014-01-11 00:00:00 : 석사동   10076 ----------


 ---------- 2014-01-11 01:00:00 : 동산면   10078 ----------


 ---------- 2014-01-11 07:00:00 : 남산면   10081 ----------


 ---------- 2014-01-11 17:00:00 : 신동면   10082 ----------


 ---------- 2014-01-11 18:00:00 : 석사동   10083 ----------


 ---------- 2014-01-12 08:00:00 : 조운동   10085 ----------


 ---------- 2014-01-12 15:00:00 : 후평1동   10086 ----------


 ---------- 2014-01-12 17:00:00 : 서  면   10087 ----------


 ---------- 2014-01-13 08:00:00 : 신동면   10088 ----------


 ---------- 2014-01-13 17:00:00 : 석사동   10089 ----------

 ---------- 2014-01-13 19:00:00 : 후평1동   10090 ----------


 ---------- 2014-01-13 19:00:00 : 퇴계동   10091 ----------


 ---------- 2014-01-13 20:00:00 : 강남동   10092 ----------


 ---------- 2014-01-13 20:00:00 : 신사우동   10093 ----------


 ---------- 2014-01-14 22:00:00 : 퇴계동   10095 ----------


 ---------- 2014-01-15 10:00:00 : 동내면   10096 ----------


 ---------- 2014-01-15 21:00:00 : 신사우동   10098 ----------


 ---------- 2014-01-16 05:00:00 : 남산면   10099 ----------


 ---------- 2014-01-16 13:00:00 : 강남동   10100 ----------


 ---------- 2014-01-16 17:00:00 : 퇴계동   10102 ----------


 ---------- 2014-01-16 20:00:00 : 후평1동   10103 ----------


 ---------- 2014-01-17 18:00:00 : 신동면   10104 ----------


 ---------- 2014-01-17 19:00:00 : 신동면   10106 ----------


 ---------- 2014-01-17 23:00:00 : 퇴계동   10107 ----------


 ---------- 2014-01-18 23:00:00 : 퇴계동   10108 ----------


 ---------- 2014-01-19 01:00:00 : 후평1동   10110 ----------


 ---------- 2014-01-19 03:00:00 : 후평1동   10111 ----------


 ---------- 2014-01-19 11:00:00 : 후평1동   10112 ----------


 ---------- 2014-01-19 16:00:00 : 소양동   10114 ----------


 ---------- 2014-01-19 22:00:00 : 효자1동   10115 ----------


 ---------- 2014-01-20 08:00:00 : 효자1동   10116 ----------


 ---------- 2014-01-20 18:00:00 : 후평1동   10117 ----------


 ---------- 2014-01-20 23:00:00 : 근화동   10118 ----------


 ---------- 2014-01-21 05:00:00 : 석사동   10120 ----------


 ---------- 2014-01-21 11:00:00 : 남산면   10122 ----------


 ---------- 2014-01-21 12:00:00 : 후평1동   10124 ----------


 ---------- 2014-01-21 17:00:00 : 사북면   10127 ----------


 ---------- 2014-01-21 18:00:00 : 퇴계동   10129 ----------


 ---------- 2014-01-21 20:00:00 : 퇴계동   10131 ----------


 ---------- 2014-01-22 08:00:00 : 효자1동   10132 ----------


 ---------- 2014-01-22 13:00:00 : 후평1동   10133 ----------


 ---------- 2014-01-22 19:00:00 : 약사명동   10135 ----------


 ---------- 2014-01-22 21:00:00 : 후평1동   10137 ----------


 ---------- 2014-01-23 00:00:00 : 석사동   10139 ----------


 ---------- 2014-01-23 09:00:00 : 후평1동   10140 ----------


 ---------- 2014-01-23 16:00:00 : 조운동   10142 ----------


 ---------- 2014-01-23 23:00:00 : 효자1동   10143 ----------


 ---------- 2014-01-24 01:00:00 : 신사우동   10144 ----------


 ---------- 2014-01-24 02:00:00 : 퇴계동   10145 ----------


 ---------- 2014-01-24 03:00:00 : 석사동   10148 ----------


 ---------- 2014-01-24 09:00:00 : 후평1동   10149 ----------


 ---------- 2014-01-24 16:00:00 : 북산면   10150 ----------


 ---------- 2014-01-24 18:00:00 : 소양동   10151 ----------


 ---------- 2014-01-25 15:00:00 : 석사동   10152 ----------


 ---------- 2014-01-25 15:00:00 : 동  면   10154 ----------


 ---------- 2014-01-26 00:00:00 : 동내면   10156 ----------


 ---------- 2014-01-26 01:00:00 : 신동면   10158 ----------


 ---------- 2014-01-26 10:00:00 : 남산면   10160 ----------


 ---------- 2014-01-26 15:00:00 : 북산면   10163 ----------


 ---------- 2014-01-26 16:00:00 : 동내면   10165 ----------


 ---------- 2014-01-27 16:00:00 : 강남동   10166 ----------


 ---------- 2014-01-27 19:00:00 : 동  면   10168 ----------


 ---------- 2014-01-28 08:00:00 : 효자1동   10169 ----------


 ---------- 2014-01-28 08:00:00 : 남산면   10171 ----------


 ---------- 2014-01-28 12:00:00 : 신북읍   10173 ----------


 ---------- 2014-01-28 19:00:00 : 석사동   10175 ----------


 ---------- 2014-01-28 19:00:00 : 동  면   10176 ----------


 ---------- 2014-01-28 19:00:00 : 교  동   10177 ----------


 ---------- 2014-01-29 15:00:00 : 약사명동   10178 ----------


 ---------- 2014-01-30 08:00:00 : 남산면   10181 ----------


 ---------- 2014-01-30 12:00:00 : 소양동   10182 ----------


 ---------- 2014-01-30 13:00:00 : 근화동   10184 ----------


 ---------- 2014-01-31 00:00:00 : 신사우동   10186 ----------


 ---------- 2014-01-31 00:00:00 : 후평1동   10187 ----------


 ---------- 2014-01-31 10:00:00 : 동  면   10188 ----------


 ---------- 2014-01-31 13:00:00 : 소양동   10189 ----------


 ---------- 2014-01-31 17:00:00 : 후평1동   10190 ----------


 ---------- 2014-01-31 19:00:00 : 후평1동   10192 ----------


 ---------- 2014-01-31 23:00:00 : 남산면   10193 ----------


 ---------- 2014-02-01 11:00:00 : 서  면   10194 ----------


 ---------- 2014-02-01 13:00:00 : 남산면   10197 ----------


 ---------- 2014-02-01 14:00:00 : 사북면   10198 ----------


 ---------- 2014-02-01 17:00:00 : 서  면   10199 ----------


 ---------- 2014-02-01 17:00:00 : 효자1동   10200 ----------


 ---------- 2014-02-01 18:00:00 : 효자1동   10201 ----------


 ---------- 2014-02-01 18:00:00 : 교  동   10202 ----------


 ---------- 2014-02-02 12:00:00 : 동  면   10203 ----------


 ---------- 2014-02-02 15:00:00 : 석사동   10204 ----------


 ---------- 2014-02-02 15:00:00 : 동산면   10205 ----------


 ---------- 2014-02-02 19:00:00 : 후평1동   10207 ----------


 ---------- 2014-02-02 21:00:00 : 동내면   10208 ----------


 ---------- 2014-02-03 02:00:00 : 후평1동   10210 ----------


 ---------- 2014-02-03 04:00:00 : 석사동   10211 ----------


 ---------- 2014-02-03 07:00:00 : 후평1동   10212 ----------


 ---------- 2014-02-03 10:00:00 : 효자1동   10213 ----------


 ---------- 2014-02-03 18:00:00 : 후평1동   10214 ----------


 ---------- 2014-02-03 20:00:00 : 후평1동   10215 ----------


 ---------- 2014-02-04 02:00:00 : 석사동   10217 ----------


 ---------- 2014-02-04 03:00:00 : 퇴계동   10218 ----------


 ---------- 2014-02-04 13:00:00 : 신동면   10219 ----------


 ---------- 2014-02-04 14:00:00 : 사북면   10220 ----------


 ---------- 2014-02-04 16:00:00 : 석사동   10222 ----------


 ---------- 2014-02-04 16:00:00 : 신동면   10223 ----------


 ---------- 2014-02-04 20:00:00 : 석사동   10224 ----------


 ---------- 2014-02-04 22:00:00 : 후평1동   10225 ----------


 ---------- 2014-02-05 00:00:00 : 신동면   10226 ----------


 ---------- 2014-02-05 02:00:00 : 효자1동   10227 ----------


 ---------- 2014-02-05 02:00:00 : 후평1동   10228 ----------


 ---------- 2014-02-05 10:00:00 : 신사우동   10229 ----------


 ---------- 2014-02-05 14:00:00 : 강남동   10230 ----------


 ---------- 2014-02-06 00:00:00 : 근화동   10231 ----------


 ---------- 2014-02-06 01:00:00 : 후평1동   10232 ----------


 ---------- 2014-02-06 02:00:00 : 강남동   10233 ----------


 ---------- 2014-02-06 14:00:00 : 서  면   10234 ----------


 ---------- 2014-02-06 20:00:00 : 석사동   10235 ----------


 ---------- 2014-02-06 23:00:00 : 신사우동   10237 ----------


 ---------- 2014-02-07 10:00:00 : 강남동   10238 ----------


 ---------- 2014-02-07 12:00:00 : 동내면   10239 ----------


 ---------- 2014-02-07 12:00:00 : 북산면   10242 ----------


 ---------- 2014-02-08 01:00:00 : 석사동   10243 ----------


 ---------- 2014-02-08 10:00:00 : 후평1동   10244 ----------


 ---------- 2014-02-08 12:00:00 : 남산면   10245 ----------


 ---------- 2014-02-08 16:00:00 : 강남동   10246 ----------


 ---------- 2014-02-08 22:00:00 : 남산면   10248 ----------


 ---------- 2014-02-09 08:00:00 : 동  면   10249 ----------


 ---------- 2014-02-09 13:00:00 : 남산면   10252 ----------


 ---------- 2014-02-09 14:00:00 : 효자1동   10253 ----------


 ---------- 2014-02-09 16:00:00 : 신동면   10254 ----------


 ---------- 2014-02-09 18:00:00 : 강남동   10255 ----------


 ---------- 2014-02-10 11:00:00 : 효자1동   10256 ----------


 ---------- 2014-02-10 13:00:00 : 효자1동   10258 ----------


 ---------- 2014-02-11 13:00:00 : 퇴계동   10259 ----------


 ---------- 2014-02-11 14:00:00 : 강남동   10260 ----------


 ---------- 2014-02-11 21:00:00 : 효자1동   10261 ----------


 ---------- 2014-02-11 23:00:00 : 석사동   10264 ----------


 ---------- 2014-02-12 09:00:00 : 근화동   10266 ----------


 ---------- 2014-02-12 10:00:00 : 동산면   10267 ----------


 ---------- 2014-02-13 00:00:00 : 신북읍   10268 ----------


 ---------- 2014-02-13 05:00:00 : 신북읍   10269 ----------


 ---------- 2014-02-13 16:00:00 : 동  면   10272 ----------


 ---------- 2014-02-14 09:00:00 : 동  면   10274 ----------


 ---------- 2014-02-14 19:00:00 : 동  면   10276 ----------


 ---------- 2014-02-15 09:00:00 : 석사동   10277 ----------


 ---------- 2014-02-15 11:00:00 : 신동면   10279 ----------


 ---------- 2014-02-15 11:00:00 : 후평1동   10280 ----------


 ---------- 2014-02-15 14:00:00 : 서  면   10282 ----------

 ---------- 2014-02-16 14:00:00 : 북산면   10285 ----------


 ---------- 2014-02-16 19:00:00 : 석사동   10287 ----------


 ---------- 2014-02-17 15:00:00 : 퇴계동   10289 ----------


 ---------- 2014-02-17 16:00:00 : 강남동   10290 ----------


 ---------- 2014-02-17 17:00:00 : 석사동   10291 ----------


 ---------- 2014-02-19 13:00:00 : 남산면   10293 ----------


 ---------- 2014-02-19 17:00:00 : 퇴계동   10294 ----------


 ---------- 2014-02-19 18:00:00 : 후평1동   10295 ----------


 ---------- 2014-02-19 21:00:00 : 강남동   10296 ----------


 ---------- 2014-02-20 13:00:00 : 후평1동   10297 ----------


 ---------- 2014-02-20 19:00:00 : 후평1동   10298 ----------


 ---------- 2014-02-20 23:00:00 : 신사우동   10300 ----------


 ---------- 2014-02-21 14:00:00 : 남산면   10302 ----------


 ---------- 2014-02-21 19:00:00 : 신북읍   10304 ----------


 ---------- 2014-02-21 22:00:00 : 신동면   10305 ----------


 ---------- 2014-02-22 04:00:00 : 동내면   10306 ----------


 ---------- 2014-02-22 05:00:00 : 동내면   10307 ----------


 ---------- 2014-02-22 06:00:00 : 동  면   10309 ----------


 ---------- 2014-02-22 17:00:00 : 석사동   10310 ----------


 ---------- 2014-02-22 17:00:00 : 남산면   10312 ----------


 ---------- 2014-02-23 03:00:00 : 후평1동   10313 ----------


 ---------- 2014-02-23 04:00:00 : 석사동   10314 ----------


 ---------- 2014-02-23 13:00:00 : 석사동   10315 ----------


 ---------- 2014-02-23 22:00:00 : 석사동   10317 ----------


 ---------- 2014-02-24 12:00:00 : 석사동   10318 ----------


 ---------- 2014-02-24 13:00:00 : 동  면   10319 ----------


 ---------- 2014-02-24 15:00:00 : 후평1동   10320 ----------


 ---------- 2014-02-24 17:00:00 : 북산면   10322 ----------


 ---------- 2014-02-25 15:00:00 : 효자1동   10323 ----------


 ---------- 2014-02-25 16:00:00 : 후평1동   10324 ----------


 ---------- 2014-02-25 19:00:00 : 남산면   10326 ----------


 ---------- 2014-02-25 20:00:00 : 강남동   10327 ----------


 ---------- 2014-02-26 07:00:00 : 강남동   10328 ----------


 ---------- 2014-02-26 14:00:00 : 신북읍   10329 ----------


 ---------- 2014-02-26 21:00:00 : 서  면   10330 ----------


 ---------- 2014-02-27 15:00:00 : 동  면   10331 ----------


 ---------- 2014-02-28 12:00:00 : 동  면   10333 ----------


 ---------- 2014-02-28 15:00:00 : 신사우동   10334 ----------


 ---------- 2014-02-28 23:00:00 : 강남동   10337 ----------


 ---------- 2014-03-01 05:00:00 : 효자1동   10338 ----------


 ---------- 2014-03-01 11:00:00 : 근화동   10339 ----------


 ---------- 2014-03-01 12:00:00 : 퇴계동   10340 ----------


 ---------- 2014-03-02 00:00:00 : 후평1동   10341 ----------


 ---------- 2014-03-02 10:00:00 : 사북면   10342 ----------


 ---------- 2014-03-02 12:00:00 : 서  면   10346 ----------


 ---------- 2014-03-02 12:00:00 : 후평1동   10348 ----------


 ---------- 2014-03-02 13:00:00 : 서  면   10349 ----------


 ---------- 2014-03-02 13:00:00 : 북산면   10353 ----------


 ---------- 2014-03-03 11:00:00 : 근화동   10355 ----------


 ---------- 2014-03-03 14:00:00 : 신북읍   10356 ----------


 ---------- 2014-03-03 16:00:00 : 후평1동   10357 ----------


 ---------- 2014-03-03 18:00:00 : 퇴계동   10358 ----------


 ---------- 2014-03-03 21:00:00 : 신북읍   10359 ----------


 ---------- 2014-03-04 15:00:00 : 석사동   10361 ----------


 ---------- 2014-03-04 17:00:00 : 퇴계동   10363 ----------


 ---------- 2014-03-05 01:00:00 : 효자1동   10364 ----------


 ---------- 2014-03-05 09:00:00 : 남산면   10365 ----------


 ---------- 2014-03-05 10:00:00 : 효자1동   10367 ----------


 ---------- 2014-03-05 11:00:00 : 남산면   10368 ----------


 ---------- 2014-03-05 15:00:00 : 남  면   10369 ----------


 ---------- 2014-03-06 01:00:00 : 퇴계동   10370 ----------


 ---------- 2014-03-06 07:00:00 : 석사동   10371 ----------


 ---------- 2014-03-06 10:00:00 : 사북면   10372 ----------


 ---------- 2014-03-06 10:00:00 : 남산면   10373 ----------


 ---------- 2014-03-06 13:00:00 : 효자1동   10374 ----------


 ---------- 2014-03-06 18:00:00 : 남  면   10375 ----------


 ---------- 2014-03-06 23:00:00 : 석사동   10377 ----------


 ---------- 2014-03-08 19:00:00 : 강남동   10378 ----------


 ---------- 2014-03-08 22:00:00 : 강남동   10380 ----------


 ---------- 2014-03-09 09:00:00 : 석사동   10381 ----------


 ---------- 2014-03-09 09:00:00 : 근화동   10382 ----------


 ---------- 2014-03-09 15:00:00 : 서  면   10383 ----------


 ---------- 2014-03-09 15:00:00 : 근화동   10386 ----------


 ---------- 2014-03-09 17:00:00 : 신북읍   10387 ----------


 ---------- 2014-03-09 19:00:00 : 강남동   10388 ----------


 ---------- 2014-03-09 22:00:00 : 퇴계동   10389 ----------


 ---------- 2014-03-10 12:00:00 : 북산면   10391 ----------


 ---------- 2014-03-10 14:00:00 : 북산면   10393 ----------


 ---------- 2014-03-10 16:00:00 : 효자1동   10394 ----------


 ---------- 2014-03-10 18:00:00 : 소양동   10395 ----------


 ---------- 2014-03-10 21:00:00 : 약사명동   10396 ----------


 ---------- 2014-03-11 16:00:00 : 후평1동   10398 ----------


 ---------- 2014-03-12 08:00:00 : 근화동   10399 ----------


 ---------- 2014-03-12 09:00:00 : 소양동   10400 ----------


 ---------- 2014-03-12 09:00:00 : 후평1동   10401 ----------


 ---------- 2014-03-12 10:00:00 : 소양동   10402 ----------


 ---------- 2014-03-12 17:00:00 : 신북읍   10403 ----------


 ---------- 2014-03-12 22:00:00 : 사북면   10405 ----------


 ---------- 2014-03-12 23:00:00 : 퇴계동   10409 ----------


 ---------- 2014-03-13 09:00:00 : 사북면   10410 ----------


 ---------- 2014-03-13 13:00:00 : 서  면   10411 ----------


 ---------- 2014-03-13 17:00:00 : 신동면   10412 ----------


 ---------- 2014-03-13 17:00:00 : 약사명동   10413 ----------


 ---------- 2014-03-13 17:00:00 : 동  면   10414 ----------


 ---------- 2014-03-13 22:00:00 : 근화동   10416 ----------


 ---------- 2014-03-14 11:00:00 : 석사동   10418 ----------


 ---------- 2014-03-14 17:00:00 : 동내면   10419 ----------


 ---------- 2014-03-14 23:00:00 : 동내면   10422 ----------


 ---------- 2014-03-15 03:00:00 : 동산면   10423 ----------


 ---------- 2014-03-15 14:00:00 : 신북읍   10424 ----------


 ---------- 2014-03-15 16:00:00 : 사북면   10425 ----------


 ---------- 2014-03-15 18:00:00 : 신동면   10426 ----------


 ---------- 2014-03-16 22:00:00 : 석사동   10427 ----------


 ---------- 2014-03-18 00:00:00 : 석사동   10428 ----------


 ---------- 2014-03-18 04:00:00 : 소양동   10429 ----------


 ---------- 2014-03-18 08:00:00 : 동  면   10430 ----------


 ---------- 2014-03-18 11:00:00 : 후평1동   10431 ----------


 ---------- 2014-03-18 15:00:00 : 강남동   10432 ----------


 ---------- 2014-03-18 19:00:00 : 후평1동   10433 ----------


 ---------- 2014-03-18 22:00:00 : 후평1동   10434 ----------


 ---------- 2014-03-19 09:00:00 : 동  면   10435 ----------


 ---------- 2014-03-19 10:00:00 : 후평1동   10436 ----------


 ---------- 2014-03-19 10:00:00 : 퇴계동   10437 ----------


 ---------- 2014-03-19 12:00:00 : 동  면   10438 ----------


 ---------- 2014-03-19 15:00:00 : 동  면   10439 ----------


 ---------- 2014-03-19 16:00:00 : 교  동   10440 ----------


 ---------- 2014-03-19 19:00:00 : 교  동   10442 ----------


 ---------- 2014-03-20 09:00:00 : 동  면   10443 ----------


 ---------- 2014-03-20 11:00:00 : 교  동   10444 ----------


 ---------- 2014-03-20 19:00:00 : 석사동   10445 ----------


 ---------- 2014-03-20 20:00:00 : 동내면   10446 ----------


 ---------- 2014-03-20 22:00:00 : 후평1동   10447 ----------


 ---------- 2014-03-21 02:00:00 : 효자1동   10448 ----------


 ---------- 2014-03-21 13:00:00 : 후평1동   10449 ----------


 ---------- 2014-03-21 23:00:00 : 동  면   10450 ----------


 ---------- 2014-03-22 07:00:00 : 석사동   10451 ----------


 ---------- 2014-03-22 14:00:00 : 동산면   10452 ----------


 ---------- 2014-03-23 10:00:00 : 남  면   10455 ----------


 ---------- 2014-03-23 11:00:00 : 후평1동   10456 ----------


 ---------- 2014-03-23 13:00:00 : 효자1동   10457 ----------


 ---------- 2014-03-23 16:00:00 : 약사명동   10460 ----------


 ---------- 2014-03-23 19:00:00 : 남산면   10465 ----------


 ---------- 2014-03-24 13:00:00 : 효자1동   10466 ----------


 ---------- 2014-03-24 16:00:00 : 근화동   10467 ----------


 ---------- 2014-03-24 18:00:00 : 남산면   10469 ----------


 ---------- 2014-03-24 19:00:00 : 퇴계동   10470 ----------

 ---------- 2014-03-24 20:00:00 : 후평1동   10471 ----------


 ---------- 2014-03-25 00:00:00 : 효자1동   10472 ----------


 ---------- 2014-03-25 10:00:00 : 북산면   10473 ----------


 ---------- 2014-03-25 12:00:00 : 동산면   10476 ----------


 ---------- 2014-03-26 05:00:00 : 후평1동   10477 ----------


 ---------- 2014-03-26 11:00:00 : 후평1동   10478 ----------


 ---------- 2014-03-26 14:00:00 : 후평1동   10479 ----------


 ---------- 2014-03-26 15:00:00 : 후평1동   10480 ----------


 ---------- 2014-03-26 16:00:00 : 소양동   10481 ----------


 ---------- 2014-03-27 08:00:00 : 소양동   10482 ----------


 ---------- 2014-03-27 10:00:00 : 신사우동   10484 ----------


 ---------- 2014-03-27 14:00:00 : 동  면   10485 ----------


 ---------- 2014-03-28 01:00:00 : 효자1동   10486 ----------


 ---------- 2014-03-28 09:00:00 : 동산면   10488 ----------


 ---------- 2014-03-28 14:00:00 : 강남동   10489 ----------


 ---------- 2014-03-28 22:00:00 : 근화동   10490 ----------


 ---------- 2014-03-29 13:00:00 : 퇴계동   10491 ----------


 ---------- 2014-03-30 14:00:00 : 신사우동   10492 ----------


 ---------- 2014-03-30 19:00:00 : 신북읍   10493 ----------


 ---------- 2014-04-01 12:00:00 : 남산면   10495 ----------


 ---------- 2014-04-01 19:00:00 : 신사우동   10496 ----------


 ---------- 2014-04-01 23:00:00 : 동  면   10497 ----------


 ---------- 2014-04-01 23:00:00 : 후평1동   10498 ----------


 ---------- 2014-04-02 06:00:00 : 강남동   10500 ----------


 ---------- 2014-04-02 07:00:00 : 동내면   10501 ----------


 ---------- 2014-04-02 16:00:00 : 동내면   10502 ----------


 ---------- 2014-04-02 18:00:00 : 후평1동   10503 ----------


 ---------- 2014-04-04 07:00:00 : 강남동   10504 ----------


 ---------- 2014-04-04 09:00:00 : 사북면   10506 ----------


 ---------- 2014-04-04 11:00:00 : 퇴계동   10508 ----------


 ---------- 2014-04-04 14:00:00 : 퇴계동   10510 ----------


 ---------- 2014-04-05 00:00:00 : 효자1동   10511 ----------


 ---------- 2014-04-05 02:00:00 : 효자1동   10513 ----------


 ---------- 2014-04-05 09:00:00 : 강남동   10514 ----------


 ---------- 2014-04-05 12:00:00 : 후평1동   10516 ----------


 ---------- 2014-04-05 18:00:00 : 근화동   10518 ----------


 ---------- 2014-04-05 18:00:00 : 동  면   10520 ----------


 ---------- 2014-04-06 15:00:00 : 퇴계동   10522 ----------


 ---------- 2014-04-06 19:00:00 : 동산면   10524 ----------


 ---------- 2014-04-06 21:00:00 : 석사동   10525 ----------


 ---------- 2014-04-06 21:00:00 : 강남동   10526 ----------


 ---------- 2014-04-07 00:00:00 : 후평1동   10527 ----------


 ---------- 2014-04-07 15:00:00 : 동  면   10529 ----------


 ---------- 2014-04-08 00:00:00 : 석사동   10530 ----------


 ---------- 2014-04-08 01:00:00 : 후평1동   10531 ----------


 ---------- 2014-04-08 04:00:00 : 효자1동   10533 ----------


 ---------- 2014-04-08 13:00:00 : 효자1동   10534 ----------


 ---------- 2014-04-08 13:00:00 : 동  면   10535 ----------


 ---------- 2014-04-08 14:00:00 : 효자1동   10537 ----------


 ---------- 2014-04-08 15:00:00 : 석사동   10538 ----------


 ---------- 2014-04-08 17:00:00 : 동  면   10539 ----------


 ---------- 2014-04-08 18:00:00 : 동  면   10540 ----------


 ---------- 2014-04-09 09:00:00 : 석사동   10542 ----------


 ---------- 2014-04-09 16:00:00 : 동내면   10543 ----------


 ---------- 2014-04-09 23:00:00 : 신사우동   10544 ----------


 ---------- 2014-04-10 14:00:00 : 신사우동   10545 ----------


 ---------- 2014-04-11 10:00:00 : 신사우동   10547 ----------


 ---------- 2014-04-11 13:00:00 : 후평1동   10549 ----------


 ---------- 2014-04-11 13:00:00 : 동산면   10551 ----------


 ---------- 2014-04-11 14:00:00 : 동  면   10552 ----------


 ---------- 2014-04-11 14:00:00 : 동산면   10554 ----------


 ---------- 2014-04-11 22:00:00 : 동  면   10555 ----------


 ---------- 2014-04-12 06:00:00 : 신북읍   10556 ----------


 ---------- 2014-04-12 09:00:00 : 후평1동   10557 ----------


 ---------- 2014-04-12 15:00:00 : 후평1동   10558 ----------


 ---------- 2014-04-12 16:00:00 : 효자1동   10559 ----------


 ---------- 2014-04-12 17:00:00 : 동  면   10560 ----------


 ---------- 2014-04-13 00:00:00 : 근화동   10562 ----------


 ---------- 2014-04-13 02:00:00 : 소양동   10564 ----------


 ---------- 2014-04-13 13:00:00 : 효자1동   10565 ----------


 ---------- 2014-04-13 14:00:00 : 후평1동   10566 ----------


 ---------- 2014-04-13 16:00:00 : 동내면   10568 ----------


 ---------- 2014-04-13 18:00:00 : 소양동   10570 ----------


 ---------- 2014-04-14 07:00:00 : 동  면   10571 ----------


 ---------- 2014-04-14 09:00:00 : 소양동   10573 ----------


 ---------- 2014-04-14 12:00:00 : 서  면   10577 ----------


 ---------- 2014-04-14 15:00:00 : 소양동   10579 ----------


 ---------- 2014-04-14 20:00:00 : 동내면   10580 ----------


 ---------- 2014-04-14 21:00:00 : 석사동   10581 ----------


 ---------- 2014-04-14 21:00:00 : 동내면   10582 ----------


 ---------- 2014-04-15 03:00:00 : 석사동   10583 ----------


 ---------- 2014-04-15 03:00:00 : 퇴계동   10584 ----------


 ---------- 2014-04-15 14:00:00 : 석사동   10585 ----------


 ---------- 2014-04-15 14:00:00 : 남산면   10586 ----------


 ---------- 2014-04-15 15:00:00 : 효자1동   10588 ----------


 ---------- 2014-04-15 18:00:00 : 서  면   10590 ----------


 ---------- 2014-04-15 19:00:00 : 남산면   10592 ----------


 ---------- 2014-04-16 01:00:00 : 후평1동   10593 ----------


 ---------- 2014-04-16 10:00:00 : 소양동   10594 ----------


 ---------- 2014-04-16 12:00:00 : 퇴계동   10595 ----------


 ---------- 2014-04-16 15:00:00 : 조운동   10596 ----------


 ---------- 2014-04-16 17:00:00 : 효자1동   10597 ----------


 ---------- 2014-04-16 19:00:00 : 소양동   10598 ----------


 ---------- 2014-04-16 22:00:00 : 효자1동   10599 ----------


 ---------- 2014-04-16 22:00:00 : 퇴계동   10600 ----------


 ---------- 2014-04-17 01:00:00 : 퇴계동   10601 ----------


 ---------- 2014-04-17 08:00:00 : 동내면   10602 ----------


 ---------- 2014-04-17 17:00:00 : 남산면   10603 ----------


 ---------- 2014-04-18 15:00:00 : 동내면   10604 ----------


 ---------- 2014-04-18 18:00:00 : 사북면   10605 ----------


 ---------- 2014-04-18 21:00:00 : 근화동   10606 ----------


 ---------- 2014-04-19 14:00:00 : 후평1동   10607 ----------


 ---------- 2014-04-19 17:00:00 : 남산면   10609 ----------


 ---------- 2014-04-19 23:00:00 : 퇴계동   10611 ----------


 ---------- 2014-04-20 11:00:00 : 사북면   10613 ----------


 ---------- 2014-04-20 12:00:00 : 사북면   10614 ----------


 ---------- 2014-04-20 13:00:00 : 사북면   10615 ----------


 ---------- 2014-04-20 15:00:00 : 동  면   10616 ----------


 ---------- 2014-04-20 22:00:00 : 소양동   10617 ----------


 ---------- 2014-04-21 02:00:00 : 석사동   10618 ----------


 ---------- 2014-04-21 07:00:00 : 조운동   10619 ----------


 ---------- 2014-04-21 17:00:00 : 동  면   10621 ----------


 ---------- 2014-04-21 20:00:00 : 동산면   10622 ----------


 ---------- 2014-04-21 23:00:00 : 후평1동   10623 ----------


 ---------- 2014-04-22 00:00:00 : 신사우동   10624 ----------


 ---------- 2014-04-22 01:00:00 : 조운동   10625 ----------


 ---------- 2014-04-22 06:00:00 : 강남동   10627 ----------


 ---------- 2014-04-22 08:00:00 : 석사동   10628 ----------


 ---------- 2014-04-22 14:00:00 : 남산면   10630 ----------


 ---------- 2014-04-22 16:00:00 : 신사우동   10631 ----------


 ---------- 2014-04-22 18:00:00 : 석사동   10632 ----------


 ---------- 2014-04-23 00:00:00 : 근화동   10633 ----------


 ---------- 2014-04-23 10:00:00 : 서  면   10634 ----------


 ---------- 2014-04-23 13:00:00 : 퇴계동   10635 ----------


 ---------- 2014-04-23 18:00:00 : 동  면   10638 ----------


 ---------- 2014-04-23 22:00:00 : 후평1동   10639 ----------


 ---------- 2014-04-24 03:00:00 : 후평1동   10640 ----------


 ---------- 2014-04-24 09:00:00 : 퇴계동   10641 ----------


 ---------- 2014-04-24 12:00:00 : 강남동   10642 ----------


 ---------- 2014-04-24 14:00:00 : 신동면   10645 ----------


 ---------- 2014-04-24 15:00:00 : 동산면   10646 ----------


 ---------- 2014-04-24 18:00:00 : 후평1동   10647 ----------


 ---------- 2014-04-24 20:00:00 : 후평1동   10648 ----------


 ---------- 2014-04-24 22:00:00 : 석사동   10649 ----------


 ---------- 2014-04-24 23:00:00 : 석사동   10650 ----------


 ---------- 2014-04-25 09:00:00 : 강남동   10651 ----------

 ---------- 2014-04-25 11:00:00 : 효자1동   10652 ----------


 ---------- 2014-04-25 13:00:00 : 동  면   10653 ----------


 ---------- 2014-04-25 15:00:00 : 동  면   10654 ----------


 ---------- 2014-04-26 10:00:00 : 석사동   10655 ----------


 ---------- 2014-04-26 11:00:00 : 후평1동   10657 ----------


 ---------- 2014-04-26 13:00:00 : 강남동   10658 ----------


 ---------- 2014-04-26 13:00:00 : 후평1동   10659 ----------


 ---------- 2014-04-26 15:00:00 : 약사명동   10660 ----------


 ---------- 2014-04-26 16:00:00 : 동내면   10661 ----------


 ---------- 2014-04-26 19:00:00 : 후평1동   10663 ----------


 ---------- 2014-04-27 07:00:00 : 신동면   10664 ----------


 ---------- 2014-04-27 13:00:00 : 효자1동   10666 ----------


 ---------- 2014-04-27 15:00:00 : 퇴계동   10667 ----------


 ---------- 2014-04-27 22:00:00 : 후평1동   10668 ----------


 ---------- 2014-04-28 03:00:00 : 석사동   10669 ----------


 ---------- 2014-04-28 03:00:00 : 남  면   10672 ----------


 ---------- 2014-04-28 08:00:00 : 석사동   10673 ----------


 ---------- 2014-04-28 16:00:00 : 강남동   10674 ----------


 ---------- 2014-04-28 17:00:00 : 신동면   10677 ----------


 ---------- 2014-04-28 22:00:00 : 약사명동   10678 ----------


 ---------- 2014-04-29 11:00:00 : 근화동   10680 ----------


 ---------- 2014-04-29 14:00:00 : 신북읍   10682 ----------


 ---------- 2014-04-29 19:00:00 : 교  동   10683 ----------


 ---------- 2014-04-29 21:00:00 : 석사동   10684 ----------


 ---------- 2014-04-30 02:00:00 : 사북면   10685 ----------


 ---------- 2014-04-30 06:00:00 : 신북읍   10686 ----------


 ---------- 2014-04-30 09:00:00 : 신북읍   10687 ----------


 ---------- 2014-04-30 14:00:00 : 강남동   10688 ----------


 ---------- 2014-04-30 18:00:00 : 조운동   10689 ----------


 ---------- 2014-05-01 00:00:00 : 동  면   10690 ----------


 ---------- 2014-05-01 01:00:00 : 강남동   10691 ----------


 ---------- 2014-05-01 02:00:00 : 서  면   10693 ----------


 ---------- 2014-05-01 05:00:00 : 동내면   10694 ----------


 ---------- 2014-05-01 09:00:00 : 신북읍   10695 ----------


 ---------- 2014-05-01 12:00:00 : 북산면   10698 ----------


 ---------- 2014-05-01 14:00:00 : 신북읍   10699 ----------


 ---------- 2014-05-01 14:00:00 : 북산면   10700 ----------


 ---------- 2014-05-02 12:00:00 : 효자1동   10701 ----------


 ---------- 2014-05-02 16:00:00 : 후평1동   10702 ----------


 ---------- 2014-05-03 05:00:00 : 퇴계동   10703 ----------


 ---------- 2014-05-03 07:00:00 : 석사동   10704 ----------


 ---------- 2014-05-03 08:00:00 : 신북읍   10705 ----------


 ---------- 2014-05-03 12:00:00 : 동  면   10706 ----------


 ---------- 2014-05-03 12:00:00 : 후평1동   10707 ----------


 ---------- 2014-05-03 14:00:00 : 신북읍   10708 ----------


 ---------- 2014-05-03 17:00:00 : 효자1동   10709 ----------


 ---------- 2014-05-03 17:00:00 : 동  면   10710 ----------


 ---------- 2014-05-03 18:00:00 : 효자1동   10711 ----------


 ---------- 2014-05-04 09:00:00 : 신북읍   10712 ----------


 ---------- 2014-05-04 13:00:00 : 남산면   10715 ----------


 ---------- 2014-05-04 13:00:00 : 동  면   10716 ----------


 ---------- 2014-05-04 14:00:00 : 신북읍   10717 ----------


 ---------- 2014-05-04 17:00:00 : 남산면   10718 ----------


 ---------- 2014-05-05 00:00:00 : 남산면   10719 ----------


 ---------- 2014-05-05 19:00:00 : 남산면   10721 ----------


 ---------- 2014-05-05 22:00:00 : 약사명동   10722 ----------


 ---------- 2014-05-06 11:00:00 : 후평1동   10723 ----------


 ---------- 2014-05-06 20:00:00 : 강남동   10727 ----------


 ---------- 2014-05-07 12:00:00 : 북산면   10729 ----------


 ---------- 2014-05-07 13:00:00 : 퇴계동   10730 ----------


 ---------- 2014-05-07 16:00:00 : 강남동   10732 ----------


 ---------- 2014-05-08 10:00:00 : 퇴계동   10734 ----------


 ---------- 2014-05-08 19:00:00 : 후평1동   10735 ----------


 ---------- 2014-05-09 02:00:00 : 후평1동   10736 ----------


 ---------- 2014-05-09 11:00:00 : 신사우동   10738 ----------


 ---------- 2014-05-10 00:00:00 : 교  동   10739 ----------


 ---------- 2014-05-10 09:00:00 : 퇴계동   10741 ----------


 ---------- 2014-05-10 13:00:00 : 석사동   10743 ----------


 ---------- 2014-05-10 14:00:00 : 동산면   10745 ----------


 ---------- 2014-05-10 15:00:00 : 동내면   10746 ----------


 ---------- 2014-05-10 15:00:00 : 신북읍   10747 ----------


 ---------- 2014-05-10 17:00:00 : 교  동   10748 ----------


 ---------- 2014-05-10 20:00:00 : 신사우동   10750 ----------


 ---------- 2014-05-10 21:00:00 : 퇴계동   10752 ----------


 ---------- 2014-05-11 12:00:00 : 신북읍   10753 ----------


 ---------- 2014-05-11 14:00:00 : 퇴계동   10755 ----------


 ---------- 2014-05-11 17:00:00 : 약사명동   10757 ----------


 ---------- 2014-05-11 21:00:00 : 조운동   10758 ----------


 ---------- 2014-05-12 01:00:00 : 석사동   10760 ----------


 ---------- 2014-05-12 07:00:00 : 신사우동   10761 ----------


 ---------- 2014-05-12 14:00:00 : 소양동   10762 ----------


 ---------- 2014-05-13 13:00:00 : 소양동   10763 ----------


 ---------- 2014-05-13 15:00:00 : 석사동   10765 ----------


 ---------- 2014-05-14 09:00:00 : 동내면   10766 ----------


 ---------- 2014-05-15 04:00:00 : 강남동   10767 ----------


 ---------- 2014-05-15 08:00:00 : 동내면   10768 ----------


 ---------- 2014-05-15 09:00:00 : 신북읍   10769 ----------


 ---------- 2014-05-15 10:00:00 : 후평1동   10770 ----------


 ---------- 2014-05-15 11:00:00 : 효자1동   10771 ----------


 ---------- 2014-05-15 12:00:00 : 북산면   10773 ----------


 ---------- 2014-05-15 16:00:00 : 퇴계동   10774 ----------


 ---------- 2014-05-15 18:00:00 : 효자1동   10775 ----------


 ---------- 2014-05-15 19:00:00 : 동내면   10776 ----------


 ---------- 2014-05-15 20:00:00 : 효자1동   10777 ----------


 ---------- 2014-05-15 21:00:00 : 강남동   10778 ----------


 ---------- 2014-05-15 21:00:00 : 효자1동   10779 ----------


 ---------- 2014-05-16 05:00:00 : 소양동   10780 ----------


 ---------- 2014-05-16 08:00:00 : 소양동   10781 ----------


 ---------- 2014-05-16 10:00:00 : 신북읍   10782 ----------


 ---------- 2014-05-16 12:00:00 : 약사명동   10783 ----------


 ---------- 2014-05-16 17:00:00 : 신북읍   10784 ----------


 ---------- 2014-05-16 18:00:00 : 신북읍   10786 ----------


 ---------- 2014-05-17 03:00:00 : 후평1동   10787 ----------


 ---------- 2014-05-17 05:00:00 : 효자1동   10788 ----------


 ---------- 2014-05-17 05:00:00 : 후평1동   10789 ----------


 ---------- 2014-05-17 06:00:00 : 퇴계동   10790 ----------


 ---------- 2014-05-17 11:00:00 : 신사우동   10793 ----------


 ---------- 2014-05-17 12:00:00 : 후평1동   10794 ----------


 ---------- 2014-05-17 14:00:00 : 석사동   10796 ----------


 ---------- 2014-05-17 14:00:00 : 약사명동   10797 ----------


 ---------- 2014-05-17 15:00:00 : 신동면   10798 ----------


 ---------- 2014-05-17 15:00:00 : 남산면   10800 ----------


 ---------- 2014-05-17 15:00:00 : 근화동   10801 ----------


 ---------- 2014-05-17 19:00:00 : 북산면   10802 ----------


 ---------- 2014-05-17 20:00:00 : 북산면   10803 ----------


 ---------- 2014-05-18 15:00:00 : 동내면   10804 ----------


 ---------- 2014-05-18 17:00:00 : 효자1동   10805 ----------


 ---------- 2014-05-19 06:00:00 : 효자1동   10806 ----------


 ---------- 2014-05-19 08:00:00 : 신사우동   10807 ----------


 ---------- 2014-05-19 09:00:00 : 강남동   10808 ----------


 ---------- 2014-05-19 11:00:00 : 소양동   10809 ----------


 ---------- 2014-05-19 12:00:00 : 동  면   10810 ----------


 ---------- 2014-05-19 20:00:00 : 동  면   10811 ----------


 ---------- 2014-05-19 22:00:00 : 약사명동   10812 ----------


 ---------- 2014-05-19 23:00:00 : 소양동   10813 ----------


 ---------- 2014-05-20 13:00:00 : 약사명동   10814 ----------


 ---------- 2014-05-20 15:00:00 : 소양동   10816 ----------


 ---------- 2014-05-20 20:00:00 : 후평1동   10817 ----------


 ---------- 2014-05-20 22:00:00 : 동  면   10818 ----------


 ---------- 2014-05-20 22:00:00 : 퇴계동   10819 ----------


 ---------- 2014-05-21 12:00:00 : 동내면   10820 ----------


 ---------- 2014-05-21 14:00:00 : 교  동   10821 ----------


 ---------- 2014-05-21 18:00:00 : 강남동   10822 ----------


 ---------- 2014-05-22 00:00:00 : 퇴계동   10823 ----------


 ---------- 2014-05-22 09:00:00 : 서  면   10824 ----------


 ---------- 2014-05-22 20:00:00 : 석사동   10825 ----------

 ---------- 2014-05-22 20:00:00 : 후평1동   10826 ----------


 ---------- 2014-05-22 23:00:00 : 효자1동   10827 ----------


 ---------- 2014-05-23 06:00:00 : 사북면   10828 ----------


 ---------- 2014-05-23 10:00:00 : 석사동   10829 ----------


 ---------- 2014-05-23 11:00:00 : 후평1동   10830 ----------


 ---------- 2014-05-23 11:00:00 : 퇴계동   10831 ----------


 ---------- 2014-05-23 13:00:00 : 신동면   10832 ----------


 ---------- 2014-05-23 16:00:00 : 신사우동   10833 ----------


 ---------- 2014-05-23 21:00:00 : 조운동   10835 ----------


 ---------- 2014-05-24 01:00:00 : 효자1동   10836 ----------


 ---------- 2014-05-24 02:00:00 : 효자1동   10837 ----------


 ---------- 2014-05-24 09:00:00 : 동내면   10838 ----------


 ---------- 2014-05-24 14:00:00 : 북산면   10840 ----------


 ---------- 2014-05-24 16:00:00 : 후평1동   10841 ----------


 ---------- 2014-05-24 19:00:00 : 석사동   10842 ----------


 ---------- 2014-05-24 21:00:00 : 석사동   10844 ----------


 ---------- 2014-05-25 00:00:00 : 후평1동   10846 ----------


 ---------- 2014-05-25 05:00:00 : 석사동   10847 ----------


 ---------- 2014-05-25 05:00:00 : 신동면   10848 ----------


 ---------- 2014-05-25 07:00:00 : 조운동   10850 ----------


 ---------- 2014-05-25 13:00:00 : 남산면   10852 ----------


 ---------- 2014-05-25 16:00:00 : 석사동   10853 ----------


 ---------- 2014-05-26 18:00:00 : 동  면   10855 ----------


 ---------- 2014-05-26 19:00:00 : 소양동   10856 ----------


 ---------- 2014-05-27 01:00:00 : 사북면   10857 ----------


 ---------- 2014-05-27 07:00:00 : 약사명동   10858 ----------


 ---------- 2014-05-27 11:00:00 : 석사동   10859 ----------


 ---------- 2014-05-27 11:00:00 : 약사명동   10860 ----------


 ---------- 2014-05-28 12:00:00 : 석사동   10861 ----------


 ---------- 2014-05-28 12:00:00 : 신북읍   10862 ----------


 ---------- 2014-05-28 17:00:00 : 석사동   10863 ----------


 ---------- 2014-05-28 19:00:00 : 동내면   10864 ----------


 ---------- 2014-05-28 22:00:00 : 석사동   10867 ----------


 ---------- 2014-05-28 23:00:00 : 소양동   10868 ----------


 ---------- 2014-05-29 17:00:00 : 효자1동   10869 ----------


 ---------- 2014-05-30 01:00:00 : 석사동   10870 ----------


 ---------- 2014-05-30 01:00:00 : 강남동   10871 ----------


 ---------- 2014-05-30 01:00:00 : 퇴계동   10873 ----------


 ---------- 2014-05-30 18:00:00 : 석사동   10874 ----------


 ---------- 2014-05-30 23:00:00 : 동내면   10876 ----------


 ---------- 2014-05-31 03:00:00 : 남산면   10877 ----------


 ---------- 2014-05-31 15:00:00 : 남산면   10879 ----------


 ---------- 2014-05-31 17:00:00 : 후평1동   10880 ----------


 ---------- 2014-05-31 17:00:00 : 퇴계동   10881 ----------


 ---------- 2014-05-31 20:00:00 : 강남동   10882 ----------


 ---------- 2014-05-31 22:00:00 : 동내면   10884 ----------


 ---------- 2014-06-01 00:00:00 : 남산면   10885 ----------


 ---------- 2014-06-01 14:00:00 : 신동면   10886 ----------


 ---------- 2014-06-01 14:00:00 : 남  면   10888 ----------


 ---------- 2014-06-01 16:00:00 : 후평1동   10889 ----------


 ---------- 2014-06-01 17:00:00 : 동내면   10892 ----------


 ---------- 2014-06-01 17:00:00 : 소양동   10895 ----------


 ---------- 2014-06-01 22:00:00 : 석사동   10896 ----------


 ---------- 2014-06-02 09:00:00 : 근화동   10899 ----------


 ---------- 2014-06-02 12:00:00 : 근화동   10900 ----------


 ---------- 2014-06-02 18:00:00 : 신사우동   10902 ----------


 ---------- 2014-06-02 19:00:00 : 효자1동   10904 ----------


 ---------- 2014-06-02 22:00:00 : 동내면   10906 ----------


 ---------- 2014-06-03 11:00:00 : 동산면   10907 ----------


 ---------- 2014-06-03 12:00:00 : 석사동   10908 ----------


 ---------- 2014-06-03 13:00:00 : 강남동   10909 ----------


 ---------- 2014-06-03 16:00:00 : 퇴계동   10910 ----------


 ---------- 2014-06-03 20:00:00 : 후평1동   10912 ----------


 ---------- 2014-06-04 03:00:00 : 근화동   10913 ----------


 ---------- 2014-06-04 09:00:00 : 강남동   10914 ----------


 ---------- 2014-06-04 09:00:00 : 동  면   10915 ----------


 ---------- 2014-06-04 10:00:00 : 동내면   10916 ----------


 ---------- 2014-06-04 10:00:00 : 남산면   10917 ----------


 ---------- 2014-06-04 10:00:00 : 후평1동   10919 ----------


 ---------- 2014-06-04 10:00:00 : 퇴계동   10920 ----------


 ---------- 2014-06-04 12:00:00 : 소양동   10921 ----------


 ---------- 2014-06-04 18:00:00 : 교  동   10922 ----------


 ---------- 2014-06-04 21:00:00 : 동  면   10923 ----------


 ---------- 2014-06-04 21:00:00 : 퇴계동   10924 ----------


 ---------- 2014-06-04 22:00:00 : 근화동   10925 ----------


 ---------- 2014-06-05 09:00:00 : 동산면   10926 ----------


 ---------- 2014-06-05 14:00:00 : 소양동   10927 ----------


 ---------- 2014-06-05 14:00:00 : 동  면   10928 ----------


 ---------- 2014-06-05 16:00:00 : 퇴계동   10929 ----------


 ---------- 2014-06-05 18:00:00 : 동  면   10931 ----------


 ---------- 2014-06-06 08:00:00 : 서  면   10932 ----------


 ---------- 2014-06-06 10:00:00 : 후평1동   10933 ----------


 ---------- 2014-06-06 11:00:00 : 동내면   10935 ----------


 ---------- 2014-06-06 11:00:00 : 후평1동   10936 ----------


 ---------- 2014-06-06 13:00:00 : 남산면   10937 ----------


 ---------- 2014-06-06 14:00:00 : 신사우동   10938 ----------


 ---------- 2014-06-06 17:00:00 : 동  면   10939 ----------


 ---------- 2014-06-06 18:00:00 : 남산면   10940 ----------


 ---------- 2014-06-06 18:00:00 : 동  면   10941 ----------


 ---------- 2014-06-06 20:00:00 : 서  면   10943 ----------


 ---------- 2014-06-06 20:00:00 : 후평1동   10944 ----------


 ---------- 2014-06-07 00:00:00 : 신사우동   10945 ----------


 ---------- 2014-06-07 01:00:00 : 강남동   10946 ----------


 ---------- 2014-06-07 12:00:00 : 석사동   10948 ----------


 ---------- 2014-06-07 14:00:00 : 석사동   10949 ----------


 ---------- 2014-06-07 15:00:00 : 석사동   10950 ----------


 ---------- 2014-06-08 02:00:00 : 강남동   10951 ----------


 ---------- 2014-06-08 12:00:00 : 사북면   10952 ----------


 ---------- 2014-06-08 14:00:00 : 사북면   10953 ----------


 ---------- 2014-06-08 17:00:00 : 동  면   10954 ----------


 ---------- 2014-06-08 21:00:00 : 근화동   10955 ----------


 ---------- 2014-06-09 07:00:00 : 퇴계동   10956 ----------


 ---------- 2014-06-09 12:00:00 : 동  면   10957 ----------


 ---------- 2014-06-09 13:00:00 : 소양동   10958 ----------


 ---------- 2014-06-09 14:00:00 : 남산면   10959 ----------


 ---------- 2014-06-09 17:00:00 : 북산면   10961 ----------


 ---------- 2014-06-09 18:00:00 : 석사동   10962 ----------


 ---------- 2014-06-10 02:00:00 : 퇴계동   10963 ----------


 ---------- 2014-06-10 09:00:00 : 강남동   10964 ----------


 ---------- 2014-06-10 11:00:00 : 강남동   10965 ----------


 ---------- 2014-06-10 11:00:00 : 남산면   10966 ----------


 ---------- 2014-06-10 13:00:00 : 교  동   10967 ----------


 ---------- 2014-06-10 14:00:00 : 강남동   10968 ----------


 ---------- 2014-06-10 15:00:00 : 근화동   10969 ----------


 ---------- 2014-06-10 16:00:00 : 신사우동   10970 ----------


 ---------- 2014-06-10 19:00:00 : 석사동   10971 ----------


 ---------- 2014-06-10 19:00:00 : 근화동   10973 ----------


 ---------- 2014-06-10 23:00:00 : 교  동   10975 ----------


 ---------- 2014-06-11 08:00:00 : 강남동   10976 ----------


 ---------- 2014-06-11 13:00:00 : 석사동   10978 ----------


 ---------- 2014-06-11 14:00:00 : 석사동   10979 ----------


 ---------- 2014-06-11 15:00:00 : 신동면   10980 ----------


 ---------- 2014-06-11 20:00:00 : 강남동   10981 ----------


 ---------- 2014-06-11 23:00:00 : 소양동   10982 ----------


 ---------- 2014-06-12 01:00:00 : 동  면   10983 ----------


 ---------- 2014-06-12 01:00:00 : 후평1동   10984 ----------


 ---------- 2014-06-12 08:00:00 : 신사우동   10985 ----------


 ---------- 2014-06-12 10:00:00 : 근화동   10986 ----------


 ---------- 2014-06-12 14:00:00 : 석사동   10987 ----------


 ---------- 2014-06-12 15:00:00 : 퇴계동   10988 ----------


 ---------- 2014-06-12 16:00:00 : 동내면   10989 ----------


 ---------- 2014-06-12 21:00:00 : 신북읍   10990 ----------


 ---------- 2014-06-13 02:00:00 : 퇴계동   10991 ----------


 ---------- 2014-06-13 09:00:00 : 후평1동   10992 ----------


 ---------- 2014-06-13 15:00:00 : 서  면   10993 ----------


 ---------- 2014-06-13 16:00:00 : 퇴계동   10995 ----------

 ---------- 2014-06-13 20:00:00 : 후평1동   10996 ----------


 ---------- 2014-06-14 01:00:00 : 후평1동   10997 ----------


 ---------- 2014-06-14 10:00:00 : 석사동   10998 ----------


 ---------- 2014-06-14 11:00:00 : 후평1동   11000 ----------


 ---------- 2014-06-14 13:00:00 : 북산면   11003 ----------


 ---------- 2014-06-14 14:00:00 : 사북면   11004 ----------


 ---------- 2014-06-14 14:00:00 : 남산면   11007 ----------


 ---------- 2014-06-14 17:00:00 : 약사명동   11008 ----------


 ---------- 2014-06-14 19:00:00 : 동내면   11010 ----------


 ---------- 2014-06-15 00:00:00 : 동산면   11013 ----------


 ---------- 2014-06-15 13:00:00 : 동내면   11014 ----------


 ---------- 2014-06-15 13:00:00 : 남산면   11015 ----------


 ---------- 2014-06-15 13:00:00 : 근화동   11017 ----------


 ---------- 2014-06-15 13:00:00 : 신북읍   11018 ----------


 ---------- 2014-06-15 14:00:00 : 남산면   11019 ----------


 ---------- 2014-06-15 15:00:00 : 신사우동   11020 ----------


 ---------- 2014-06-15 16:00:00 : 동내면   11021 ----------


 ---------- 2014-06-15 16:00:00 : 퇴계동   11022 ----------


 ---------- 2014-06-15 18:00:00 : 강남동   11023 ----------


 ---------- 2014-06-15 18:00:00 : 서  면   11024 ----------


 ---------- 2014-06-15 20:00:00 : 근화동   11025 ----------


 ---------- 2014-06-15 20:00:00 : 약사명동   11026 ----------


 ---------- 2014-06-16 00:00:00 : 신동면   11030 ----------


 ---------- 2014-06-16 10:00:00 : 소양동   11031 ----------


 ---------- 2014-06-16 18:00:00 : 동내면   11032 ----------


 ---------- 2014-06-17 03:00:00 : 근화동   11034 ----------


 ---------- 2014-06-17 10:00:00 : 석사동   11035 ----------


 ---------- 2014-06-17 12:00:00 : 신동면   11036 ----------


 ---------- 2014-06-17 14:00:00 : 강남동   11037 ----------


 ---------- 2014-06-17 22:00:00 : 후평1동   11038 ----------


 ---------- 2014-06-18 08:00:00 : 남산면   11039 ----------


 ---------- 2014-06-18 09:00:00 : 강남동   11041 ----------


 ---------- 2014-06-18 10:00:00 : 후평1동   11042 ----------


 ---------- 2014-06-18 11:00:00 : 강남동   11043 ----------


 ---------- 2014-06-18 14:00:00 : 소양동   11044 ----------


 ---------- 2014-06-18 14:00:00 : 후평1동   11045 ----------


 ---------- 2014-06-18 16:00:00 : 동내면   11046 ----------


 ---------- 2014-06-18 19:00:00 : 후평1동   11047 ----------


 ---------- 2014-06-18 20:00:00 : 효자1동   11048 ----------


 ---------- 2014-06-19 02:00:00 : 신사우동   11050 ----------


 ---------- 2014-06-19 04:00:00 : 석사동   11051 ----------


 ---------- 2014-06-19 04:00:00 : 퇴계동   11052 ----------


 ---------- 2014-06-19 09:00:00 : 남산면   11054 ----------


 ---------- 2014-06-19 10:00:00 : 동산면   11055 ----------


 ---------- 2014-06-19 14:00:00 : 신사우동   11056 ----------


 ---------- 2014-06-19 15:00:00 : 남산면   11057 ----------


 ---------- 2014-06-19 15:00:00 : 후평1동   11058 ----------


 ---------- 2014-06-19 16:00:00 : 서  면   11060 ----------


 ---------- 2014-06-19 23:00:00 : 효자1동   11061 ----------


 ---------- 2014-06-20 00:00:00 : 신사우동   11062 ----------


 ---------- 2014-06-20 07:00:00 : 동산면   11063 ----------


 ---------- 2014-06-20 13:00:00 : 신사우동   11064 ----------


 ---------- 2014-06-20 13:00:00 : 후평1동   11066 ----------


 ---------- 2014-06-20 14:00:00 : 신북읍   11067 ----------


 ---------- 2014-06-20 17:00:00 : 신동면   11068 ----------


 ---------- 2014-06-20 17:00:00 : 동내면   11070 ----------


 ---------- 2014-06-20 20:00:00 : 신동면   11071 ----------


 ---------- 2014-06-20 21:00:00 : 신동면   11072 ----------


 ---------- 2014-06-20 22:00:00 : 신북읍   11073 ----------


 ---------- 2014-06-21 05:00:00 : 동산면   11075 ----------


 ---------- 2014-06-21 08:00:00 : 석사동   11076 ----------


 ---------- 2014-06-21 12:00:00 : 효자1동   11077 ----------


 ---------- 2014-06-21 12:00:00 : 남산면   11080 ----------


 ---------- 2014-06-21 13:00:00 : 서  면   11083 ----------


 ---------- 2014-06-21 13:00:00 : 동산면   11084 ----------


 ---------- 2014-06-21 14:00:00 : 서  면   11085 ----------


 ---------- 2014-06-21 15:00:00 : 퇴계동   11086 ----------


 ---------- 2014-06-21 16:00:00 : 퇴계동   11087 ----------


 ---------- 2014-06-21 17:00:00 : 후평1동   11088 ----------


 ---------- 2014-06-22 14:00:00 : 강남동   11089 ----------


 ---------- 2014-06-22 14:00:00 : 교  동   11090 ----------


 ---------- 2014-06-23 09:00:00 : 강남동   11091 ----------


 ---------- 2014-06-23 10:00:00 : 신동면   11092 ----------


 ---------- 2014-06-23 12:00:00 : 신동면   11093 ----------


 ---------- 2014-06-23 14:00:00 : 교  동   11095 ----------


 ---------- 2014-06-23 16:00:00 : 동  면   11096 ----------


 ---------- 2014-06-23 17:00:00 : 신북읍   11097 ----------


 ---------- 2014-06-23 22:00:00 : 후평1동   11099 ----------


 ---------- 2014-06-23 23:00:00 : 석사동   11100 ----------


 ---------- 2014-06-23 23:00:00 : 약사명동   11101 ----------


 ---------- 2014-06-24 07:00:00 : 석사동   11102 ----------


 ---------- 2014-06-24 10:00:00 : 퇴계동   11103 ----------


 ---------- 2014-06-24 14:00:00 : 남산면   11104 ----------


 ---------- 2014-06-24 15:00:00 : 후평1동   11105 ----------


 ---------- 2014-06-24 18:00:00 : 퇴계동   11106 ----------


 ---------- 2014-06-24 19:00:00 : 퇴계동   11107 ----------


 ---------- 2014-06-25 06:00:00 : 신사우동   11108 ----------


 ---------- 2014-06-25 08:00:00 : 신사우동   11110 ----------


 ---------- 2014-06-25 12:00:00 : 신동면   11111 ----------


 ---------- 2014-06-25 19:00:00 : 남산면   11112 ----------


 ---------- 2014-06-25 20:00:00 : 후평1동   11113 ----------


 ---------- 2014-06-26 01:00:00 : 교  동   11114 ----------


 ---------- 2014-06-26 03:00:00 : 동내면   11115 ----------


 ---------- 2014-06-26 05:00:00 : 신북읍   11117 ----------


 ---------- 2014-06-26 08:00:00 : 후평1동   11118 ----------


 ---------- 2014-06-26 08:00:00 : 교  동   11120 ----------


 ---------- 2014-06-26 09:00:00 : 남산면   11122 ----------


 ---------- 2014-06-26 13:00:00 : 신동면   11123 ----------


 ---------- 2014-06-26 14:00:00 : 약사명동   11125 ----------


 ---------- 2014-06-26 15:00:00 : 동  면   11126 ----------


 ---------- 2014-06-26 16:00:00 : 남  면   11128 ----------


 ---------- 2014-06-27 02:00:00 : 후평1동   11129 ----------


 ---------- 2014-06-27 08:00:00 : 남산면   11130 ----------


 ---------- 2014-06-27 09:00:00 : 효자1동   11131 ----------


 ---------- 2014-06-27 09:00:00 : 동산면   11132 ----------


 ---------- 2014-06-27 11:00:00 : 신사우동   11133 ----------


 ---------- 2014-06-27 12:00:00 : 서  면   11134 ----------


 ---------- 2014-06-27 12:00:00 : 소양동   11137 ----------


 ---------- 2014-06-27 14:00:00 : 서  면   11138 ----------


 ---------- 2014-06-27 14:00:00 : 소양동   11140 ----------


 ---------- 2014-06-27 15:00:00 : 남  면   11141 ----------


 ---------- 2014-06-27 16:00:00 : 동산면   11142 ----------


 ---------- 2014-06-27 17:00:00 : 후평1동   11144 ----------


 ---------- 2014-06-27 19:00:00 : 남산면   11145 ----------


 ---------- 2014-06-27 19:00:00 : 약사명동   11147 ----------


 ---------- 2014-06-28 06:00:00 : 퇴계동   11148 ----------


 ---------- 2014-06-28 09:00:00 : 신동면   11149 ----------


 ---------- 2014-06-28 10:00:00 : 효자1동   11150 ----------


 ---------- 2014-06-28 13:00:00 : 남산면   11151 ----------


 ---------- 2014-06-28 14:00:00 : 신동면   11152 ----------


 ---------- 2014-06-28 16:00:00 : 근화동   11153 ----------


 ---------- 2014-06-28 17:00:00 : 동  면   11155 ----------


 ---------- 2014-06-28 20:00:00 : 소양동   11157 ----------


 ---------- 2014-06-28 20:00:00 : 퇴계동   11159 ----------


 ---------- 2014-06-29 00:00:00 : 서  면   11160 ----------


 ---------- 2014-06-29 08:00:00 : 동  면   11161 ----------


 ---------- 2014-06-29 09:00:00 : 후평1동   11162 ----------


 ---------- 2014-06-29 11:00:00 : 사북면   11163 ----------


 ---------- 2014-06-29 12:00:00 : 사북면   11164 ----------


 ---------- 2014-06-29 12:00:00 : 동내면   11165 ----------


 ---------- 2014-06-29 14:00:00 : 동내면   11166 ----------


 ---------- 2014-06-29 14:00:00 : 남산면   11168 ----------


 ---------- 2014-06-29 17:00:00 : 서  면   11171 ----------


 ---------- 2014-06-29 17:00:00 : 후평1동   11172 ----------


 ---------- 2014-06-29 22:00:00 : 석사동   11173 ----------


 ---------- 2014-06-30 01:00:00 : 강남동   11174 ----------

 ---------- 2014-06-30 01:00:00 : 약사명동   11175 ----------


 ---------- 2014-06-30 07:00:00 : 강남동   11176 ----------


 ---------- 2014-06-30 10:00:00 : 동내면   11177 ----------


 ---------- 2014-06-30 11:00:00 : 근화동   11178 ----------


 ---------- 2014-06-30 11:00:00 : 조운동   11179 ----------


 ---------- 2014-06-30 12:00:00 : 남산면   11180 ----------


 ---------- 2014-06-30 13:00:00 : 신동면   11181 ----------


 ---------- 2014-06-30 14:00:00 : 남산면   11182 ----------


 ---------- 2014-06-30 15:00:00 : 동내면   11183 ----------


 ---------- 2014-06-30 16:00:00 : 조운동   11185 ----------


 ---------- 2014-06-30 17:00:00 : 신북읍   11186 ----------


 ---------- 2014-06-30 17:00:00 : 소양동   11187 ----------


 ---------- 2014-06-30 17:00:00 : 북산면   11188 ----------


 ---------- 2014-06-30 18:00:00 : 석사동   11189 ----------


 ---------- 2014-06-30 20:00:00 : 남산면   11190 ----------


 ---------- 2014-06-30 21:00:00 : 후평1동   11191 ----------


 ---------- 2014-07-01 10:00:00 : 강남동   11192 ----------


 ---------- 2014-07-01 12:00:00 : 사북면   11193 ----------


 ---------- 2014-07-01 13:00:00 : 남산면   11194 ----------


 ---------- 2014-07-01 14:00:00 : 강남동   11195 ----------


 ---------- 2014-07-01 17:00:00 : 남산면   11196 ----------


 ---------- 2014-07-01 18:00:00 : 강남동   11199 ----------


 ---------- 2014-07-01 18:00:00 : 남  면   11200 ----------


 ---------- 2014-07-02 07:00:00 : 후평1동   11201 ----------


 ---------- 2014-07-02 09:00:00 : 남산면   11202 ----------


 ---------- 2014-07-02 10:00:00 : 동산면   11203 ----------


 ---------- 2014-07-02 11:00:00 : 소양동   11204 ----------


 ---------- 2014-07-02 12:00:00 : 신북읍   11205 ----------


 ---------- 2014-07-02 14:00:00 : 석사동   11206 ----------


 ---------- 2014-07-02 14:00:00 : 동내면   11207 ----------


 ---------- 2014-07-02 14:00:00 : 신사우동   11208 ----------


 ---------- 2014-07-02 14:00:00 : 신북읍   11209 ----------


 ---------- 2014-07-02 17:00:00 : 석사동   11211 ----------


 ---------- 2014-07-02 17:00:00 : 남산면   11212 ----------


 ---------- 2014-07-02 18:00:00 : 북산면   11213 ----------


 ---------- 2014-07-03 08:00:00 : 서  면   11214 ----------


 ---------- 2014-07-03 11:00:00 : 효자1동   11216 ----------


 ---------- 2014-07-03 14:00:00 : 강남동   11217 ----------


 ---------- 2014-07-03 15:00:00 : 석사동   11220 ----------


 ---------- 2014-07-03 18:00:00 : 후평1동   11222 ----------


 ---------- 2014-07-03 20:00:00 : 효자1동   11223 ----------


 ---------- 2014-07-04 01:00:00 : 소양동   11224 ----------


 ---------- 2014-07-04 06:00:00 : 동  면   11225 ----------


 ---------- 2014-07-04 08:00:00 : 남산면   11226 ----------


 ---------- 2014-07-04 09:00:00 : 효자1동   11227 ----------


 ---------- 2014-07-04 10:00:00 : 강남동   11228 ----------


 ---------- 2014-07-04 11:00:00 : 신북읍   11229 ----------


 ---------- 2014-07-04 15:00:00 : 남산면   11230 ----------


 ---------- 2014-07-04 18:00:00 : 남산면   11231 ----------


 ---------- 2014-07-04 19:00:00 : 강남동   11233 ----------


 ---------- 2014-07-05 00:00:00 : 신동면   11234 ----------


 ---------- 2014-07-05 12:00:00 : 남산면   11235 ----------


 ---------- 2014-07-05 14:00:00 : 동  면   11236 ----------


 ---------- 2014-07-05 15:00:00 : 후평1동   11237 ----------


 ---------- 2014-07-05 16:00:00 : 석사동   11238 ----------


 ---------- 2014-07-05 17:00:00 : 서  면   11239 ----------


 ---------- 2014-07-05 18:00:00 : 신동면   11240 ----------


 ---------- 2014-07-05 19:00:00 : 석사동   11242 ----------


 ---------- 2014-07-05 20:00:00 : 신사우동   11243 ----------


 ---------- 2014-07-05 20:00:00 : 퇴계동   11244 ----------


 ---------- 2014-07-06 09:00:00 : 남산면   11245 ----------


 ---------- 2014-07-06 10:00:00 : 퇴계동   11246 ----------


 ---------- 2014-07-06 13:00:00 : 퇴계동   11247 ----------


 ---------- 2014-07-06 15:00:00 : 효자1동   11249 ----------


 ---------- 2014-07-06 15:00:00 : 남산면   11251 ----------


 ---------- 2014-07-06 15:00:00 : 교  동   11252 ----------


 ---------- 2014-07-06 16:00:00 : 신동면   11254 ----------


 ---------- 2014-07-06 16:00:00 : 남산면   11256 ----------


 ---------- 2014-07-06 17:00:00 : 효자1동   11258 ----------


 ---------- 2014-07-06 18:00:00 : 동내면   11259 ----------


 ---------- 2014-07-06 23:00:00 : 후평1동   11260 ----------


 ---------- 2014-07-07 00:00:00 : 강남동   11261 ----------


 ---------- 2014-07-07 00:00:00 : 근화동   11262 ----------


 ---------- 2014-07-07 09:00:00 : 효자1동   11263 ----------


 ---------- 2014-07-07 09:00:00 : 신북읍   11264 ----------


 ---------- 2014-07-07 12:00:00 : 효자1동   11265 ----------


 ---------- 2014-07-07 16:00:00 : 남  면   11266 ----------


 ---------- 2014-07-07 17:00:00 : 동  면   11267 ----------


 ---------- 2014-07-07 17:00:00 : 조운동   11268 ----------


 ---------- 2014-07-08 09:00:00 : 사북면   11269 ----------


 ---------- 2014-07-08 09:00:00 : 남산면   11270 ----------


 ---------- 2014-07-08 10:00:00 : 석사동   11271 ----------


 ---------- 2014-07-08 10:00:00 : 남산면   11272 ----------


 ---------- 2014-07-08 12:00:00 : 사북면   11273 ----------


 ---------- 2014-07-08 13:00:00 : 서  면   11274 ----------


 ---------- 2014-07-08 15:00:00 : 소양동   11275 ----------


 ---------- 2014-07-08 16:00:00 : 동내면   11276 ----------


 ---------- 2014-07-08 16:00:00 : 후평1동   11277 ----------


 ---------- 2014-07-08 17:00:00 : 남산면   11278 ----------


 ---------- 2014-07-08 20:00:00 : 강남동   11279 ----------


 ---------- 2014-07-09 08:00:00 : 사북면   11280 ----------


 ---------- 2014-07-09 09:00:00 : 사북면   11281 ----------


 ---------- 2014-07-09 12:00:00 : 서  면   11282 ----------


 ---------- 2014-07-09 12:00:00 : 남산면   11283 ----------


 ---------- 2014-07-09 14:00:00 : 신북읍   11284 ----------


 ---------- 2014-07-09 15:00:00 : 석사동   11285 ----------


 ---------- 2014-07-09 17:00:00 : 석사동   11286 ----------


 ---------- 2014-07-09 18:00:00 : 효자1동   11287 ----------


 ---------- 2014-07-10 08:00:00 : 남  면   11288 ----------


 ---------- 2014-07-10 08:00:00 : 사북면   11289 ----------


 ---------- 2014-07-10 08:00:00 : 동내면   11290 ----------


 ---------- 2014-07-10 09:00:00 : 서  면   11291 ----------


 ---------- 2014-07-10 09:00:00 : 동내면   11292 ----------


 ---------- 2014-07-10 09:00:00 : 후평1동   11293 ----------


 ---------- 2014-07-10 09:00:00 : 동산면   11294 ----------


 ---------- 2014-07-10 10:00:00 : 서  면   11295 ----------


 ---------- 2014-07-10 10:00:00 : 동내면   11297 ----------


 ---------- 2014-07-10 10:00:00 : 동  면   11298 ----------


 ---------- 2014-07-10 11:00:00 : 신동면   11299 ----------


 ---------- 2014-07-10 11:00:00 : 후평1동   11300 ----------


 ---------- 2014-07-10 11:00:00 : 퇴계동   11301 ----------


 ---------- 2014-07-10 12:00:00 : 강남동   11302 ----------


 ---------- 2014-07-10 12:00:00 : 소양동   11303 ----------


 ---------- 2014-07-10 12:00:00 : 퇴계동   11304 ----------


 ---------- 2014-07-10 14:00:00 : 남산면   11305 ----------


 ---------- 2014-07-10 15:00:00 : 사북면   11306 ----------


 ---------- 2014-07-10 15:00:00 : 퇴계동   11307 ----------


 ---------- 2014-07-10 16:00:00 : 석사동   11308 ----------


 ---------- 2014-07-10 16:00:00 : 남산면   11310 ----------


 ---------- 2014-07-10 18:00:00 : 신동면   11311 ----------


 ---------- 2014-07-11 09:00:00 : 신북읍   11312 ----------


 ---------- 2014-07-11 09:00:00 : 동  면   11313 ----------


 ---------- 2014-07-11 10:00:00 : 근화동   11314 ----------


 ---------- 2014-07-11 10:00:00 : 신사우동   11316 ----------


 ---------- 2014-07-11 12:00:00 : 동  면   11317 ----------


 ---------- 2014-07-11 13:00:00 : 사북면   11319 ----------


 ---------- 2014-07-11 13:00:00 : 동내면   11320 ----------


 ---------- 2014-07-11 13:00:00 : 남산면   11321 ----------


 ---------- 2014-07-11 14:00:00 : 사북면   11322 ----------


 ---------- 2014-07-11 14:00:00 : 동내면   11323 ----------


 ---------- 2014-07-11 21:00:00 : 석사동   11324 ----------


 ---------- 2014-07-12 01:00:00 : 신사우동   11325 ----------


 ---------- 2014-07-12 06:00:00 : 퇴계동   11326 ----------


 ---------- 2014-07-12 07:00:00 : 소양동   11328 ----------


 ---------- 2014-07-12 08:00:00 : 동  면   11329 ----------


 ---------- 2014-07-12 09:00:00 : 서  면   11331 ----------

 ---------- 2014-07-12 09:00:00 : 소양동   11333 ----------


 ---------- 2014-07-12 11:00:00 : 서  면   11334 ----------


 ---------- 2014-07-12 12:00:00 : 동내면   11335 ----------


 ---------- 2014-07-12 12:00:00 : 동  면   11336 ----------


 ---------- 2014-07-12 14:00:00 : 서  면   11337 ----------


 ---------- 2014-07-12 14:00:00 : 남산면   11338 ----------


 ---------- 2014-07-12 14:00:00 : 퇴계동   11340 ----------


 ---------- 2014-07-12 15:00:00 : 소양동   11341 ----------


 ---------- 2014-07-12 16:00:00 : 동  면   11342 ----------


 ---------- 2014-07-12 18:00:00 : 후평1동   11343 ----------


 ---------- 2014-07-12 20:00:00 : 퇴계동   11344 ----------


 ---------- 2014-07-12 21:00:00 : 효자1동   11345 ----------


 ---------- 2014-07-12 23:00:00 : 근화동   11346 ----------


 ---------- 2014-07-13 01:00:00 : 후평1동   11347 ----------


 ---------- 2014-07-13 08:00:00 : 강남동   11348 ----------


 ---------- 2014-07-13 09:00:00 : 강남동   11349 ----------


 ---------- 2014-07-13 09:00:00 : 근화동   11350 ----------


 ---------- 2014-07-13 09:00:00 : 신북읍   11351 ----------


 ---------- 2014-07-13 10:00:00 : 사북면   11352 ----------


 ---------- 2014-07-13 11:00:00 : 남  면   11353 ----------


 ---------- 2014-07-13 11:00:00 : 소양동   11354 ----------


 ---------- 2014-07-13 11:00:00 : 후평1동   11355 ----------


 ---------- 2014-07-13 12:00:00 : 사북면   11356 ----------


 ---------- 2014-07-13 12:00:00 : 소양동   11357 ----------


 ---------- 2014-07-13 13:00:00 : 석사동   11358 ----------


 ---------- 2014-07-13 14:00:00 : 동내면   11360 ----------


 ---------- 2014-07-13 16:00:00 : 남산면   11361 ----------


 ---------- 2014-07-13 18:00:00 : 석사동   11363 ----------


 ---------- 2014-07-13 19:00:00 : 남산면   11364 ----------


 ---------- 2014-07-13 22:00:00 : 석사동   11365 ----------


 ---------- 2014-07-13 22:00:00 : 퇴계동   11366 ----------


 ---------- 2014-07-14 04:00:00 : 신사우동   11368 ----------


 ---------- 2014-07-14 09:00:00 : 남산면   11369 ----------


 ---------- 2014-07-14 09:00:00 : 퇴계동   11370 ----------


 ---------- 2014-07-14 10:00:00 : 석사동   11371 ----------


 ---------- 2014-07-14 10:00:00 : 동내면   11372 ----------


 ---------- 2014-07-14 10:00:00 : 신북읍   11373 ----------


 ---------- 2014-07-14 11:00:00 : 신사우동   11374 ----------


 ---------- 2014-07-14 12:00:00 : 교  동   11375 ----------


 ---------- 2014-07-14 13:00:00 : 석사동   11376 ----------


 ---------- 2014-07-14 13:00:00 : 남  면   11377 ----------


 ---------- 2014-07-14 13:00:00 : 사북면   11379 ----------


 ---------- 2014-07-14 13:00:00 : 신북읍   11380 ----------


 ---------- 2014-07-14 14:00:00 : 동  면   11383 ----------


 ---------- 2014-07-14 14:00:00 : 퇴계동   11385 ----------


 ---------- 2014-07-14 15:00:00 : 석사동   11386 ----------


 ---------- 2014-07-14 15:00:00 : 서  면   11387 ----------


 ---------- 2014-07-14 15:00:00 : 남산면   11390 ----------


 ---------- 2014-07-14 15:00:00 : 신북읍   11391 ----------


 ---------- 2014-07-14 16:00:00 : 남산면   11392 ----------


 ---------- 2014-07-14 17:00:00 : 신동면   11393 ----------


 ---------- 2014-07-14 17:00:00 : 퇴계동   11394 ----------


 ---------- 2014-07-14 18:00:00 : 사북면   11395 ----------


 ---------- 2014-07-14 19:00:00 : 약사명동   11396 ----------


 ---------- 2014-07-14 22:00:00 : 신북읍   11398 ----------


 ---------- 2014-07-14 22:00:00 : 후평1동   11399 ----------


 ---------- 2014-07-14 23:00:00 : 동  면   11401 ----------


 ---------- 2014-07-15 08:00:00 : 사북면   11402 ----------


 ---------- 2014-07-15 08:00:00 : 남산면   11404 ----------


 ---------- 2014-07-15 08:00:00 : 약사명동   11405 ----------


 ---------- 2014-07-15 08:00:00 : 퇴계동   11406 ----------


 ---------- 2014-07-15 09:00:00 : 강남동   11407 ----------


 ---------- 2014-07-15 09:00:00 : 서  면   11408 ----------


 ---------- 2014-07-15 09:00:00 : 후평1동   11409 ----------


 ---------- 2014-07-15 10:00:00 : 서  면   11410 ----------


 ---------- 2014-07-15 10:00:00 : 소양동   11411 ----------


 ---------- 2014-07-15 12:00:00 : 강남동   11412 ----------


 ---------- 2014-07-15 13:00:00 : 후평1동   11413 ----------


 ---------- 2014-07-15 16:00:00 : 퇴계동   11414 ----------


 ---------- 2014-07-15 19:00:00 : 신북읍   11415 ----------


 ---------- 2014-07-15 23:00:00 : 강남동   11416 ----------


 ---------- 2014-07-16 01:00:00 : 퇴계동   11417 ----------


 ---------- 2014-07-16 08:00:00 : 남  면   11418 ----------


 ---------- 2014-07-16 08:00:00 : 후평1동   11419 ----------


 ---------- 2014-07-16 09:00:00 : 신북읍   11423 ----------


 ---------- 2014-07-16 09:00:00 : 후평1동   11425 ----------


 ---------- 2014-07-16 10:00:00 : 신북읍   11426 ----------


 ---------- 2014-07-16 10:00:00 : 북산면   11427 ----------


 ---------- 2014-07-16 10:00:00 : 동산면   11428 ----------


 ---------- 2014-07-16 12:00:00 : 남산면   11429 ----------


 ---------- 2014-07-16 12:00:00 : 북산면   11430 ----------


 ---------- 2014-07-16 13:00:00 : 신북읍   11431 ----------


 ---------- 2014-07-16 14:00:00 : 서  면   11432 ----------


 ---------- 2014-07-16 14:00:00 : 남산면   11433 ----------


 ---------- 2014-07-16 14:00:00 : 동  면   11434 ----------


 ---------- 2014-07-16 16:00:00 : 서  면   11435 ----------


 ---------- 2014-07-16 16:00:00 : 남산면   11436 ----------


 ---------- 2014-07-16 17:00:00 : 신동면   11438 ----------


 ---------- 2014-07-16 17:00:00 : 약사명동   11439 ----------


 ---------- 2014-07-16 18:00:00 : 후평1동   11440 ----------


 ---------- 2014-07-16 20:00:00 : 후평1동   11442 ----------


 ---------- 2014-07-16 21:00:00 : 동  면   11443 ----------


 ---------- 2014-07-17 08:00:00 : 근화동   11444 ----------


 ---------- 2014-07-17 09:00:00 : 동  면   11445 ----------


 ---------- 2014-07-17 10:00:00 : 신북읍   11446 ----------


 ---------- 2014-07-17 10:00:00 : 후평1동   11447 ----------


 ---------- 2014-07-17 11:00:00 : 신사우동   11448 ----------


 ---------- 2014-07-17 11:00:00 : 교  동   11449 ----------


 ---------- 2014-07-17 14:00:00 : 강남동   11450 ----------


 ---------- 2014-07-17 15:00:00 : 서  면   11451 ----------


 ---------- 2014-07-17 16:00:00 : 근화동   11452 ----------


 ---------- 2014-07-17 20:00:00 : 후평1동   11454 ----------


 ---------- 2014-07-18 09:00:00 : 남산면   11455 ----------


 ---------- 2014-07-18 09:00:00 : 동  면   11456 ----------


 ---------- 2014-07-18 09:00:00 : 퇴계동   11458 ----------


 ---------- 2014-07-18 10:00:00 : 강남동   11459 ----------


 ---------- 2014-07-18 10:00:00 : 동내면   11460 ----------


 ---------- 2014-07-18 10:00:00 : 북산면   11461 ----------


 ---------- 2014-07-18 12:00:00 : 사북면   11462 ----------


 ---------- 2014-07-18 12:00:00 : 북산면   11463 ----------


 ---------- 2014-07-18 13:00:00 : 남산면   11464 ----------


 ---------- 2014-07-18 14:00:00 : 북산면   11465 ----------


 ---------- 2014-07-18 14:00:00 : 동산면   11466 ----------


 ---------- 2014-07-18 15:00:00 : 서  면   11467 ----------


 ---------- 2014-07-18 16:00:00 : 서  면   11469 ----------


 ---------- 2014-07-18 17:00:00 : 동내면   11470 ----------


 ---------- 2014-07-18 19:00:00 : 신사우동   11471 ----------


 ---------- 2014-07-18 22:00:00 : 석사동   11472 ----------


 ---------- 2014-07-18 23:00:00 : 신동면   11473 ----------


 ---------- 2014-07-19 08:00:00 : 동산면   11474 ----------


 ---------- 2014-07-19 09:00:00 : 남산면   11475 ----------


 ---------- 2014-07-19 09:00:00 : 동  면   11476 ----------


 ---------- 2014-07-19 10:00:00 : 신동면   11478 ----------


 ---------- 2014-07-19 10:00:00 : 서  면   11479 ----------


 ---------- 2014-07-19 11:00:00 : 강남동   11481 ----------


 ---------- 2014-07-19 11:00:00 : 신사우동   11482 ----------


 ---------- 2014-07-19 13:00:00 : 근화동   11484 ----------


 ---------- 2014-07-19 14:00:00 : 사북면   11485 ----------


 ---------- 2014-07-19 14:00:00 : 남산면   11486 ----------


 ---------- 2014-07-19 15:00:00 : 퇴계동   11487 ----------


 ---------- 2014-07-19 16:00:00 : 석사동   11488 ----------


 ---------- 2014-07-19 16:00:00 : 신동면   11489 ----------


 ---------- 2014-07-19 16:00:00 : 서  면   11490 ----------


 ---------- 2014-07-19 17:00:00 : 동산면   11491 ----------


 ---------- 2014-07-19 18:00:00 : 신동면   11492 ----------


 ---------- 2014-07-19 18:00:00 : 근화동   11493 ----------

 ---------- 2014-07-19 19:00:00 : 효자1동   11495 ----------


 ---------- 2014-07-20 08:00:00 : 남  면   11496 ----------


 ---------- 2014-07-20 08:00:00 : 동내면   11497 ----------


 ---------- 2014-07-20 08:00:00 : 후평1동   11498 ----------


 ---------- 2014-07-20 10:00:00 : 강남동   11499 ----------


 ---------- 2014-07-20 11:00:00 : 동내면   11500 ----------


 ---------- 2014-07-20 11:00:00 : 북산면   11501 ----------


 ---------- 2014-07-20 12:00:00 : 근화동   11502 ----------


 ---------- 2014-07-20 12:00:00 : 신사우동   11503 ----------


 ---------- 2014-07-20 14:00:00 : 신북읍   11504 ----------


 ---------- 2014-07-20 15:00:00 : 남  면   11505 ----------


 ---------- 2014-07-20 16:00:00 : 석사동   11506 ----------


 ---------- 2014-07-20 16:00:00 : 신동면   11508 ----------


 ---------- 2014-07-20 17:00:00 : 석사동   11510 ----------


 ---------- 2014-07-20 21:00:00 : 석사동   11511 ----------


 ---------- 2014-07-21 07:00:00 : 동산면   11514 ----------


 ---------- 2014-07-21 08:00:00 : 소양동   11515 ----------


 ---------- 2014-07-21 09:00:00 : 강남동   11516 ----------


 ---------- 2014-07-21 09:00:00 : 동산면   11517 ----------


 ---------- 2014-07-21 10:00:00 : 서  면   11518 ----------


 ---------- 2014-07-21 10:00:00 : 남산면   11519 ----------


 ---------- 2014-07-21 10:00:00 : 교  동   11520 ----------


 ---------- 2014-07-21 11:00:00 : 서  면   11521 ----------


 ---------- 2014-07-21 12:00:00 : 신북읍   11522 ----------


 ---------- 2014-07-21 13:00:00 : 남산면   11523 ----------


 ---------- 2014-07-21 13:00:00 : 동  면   11524 ----------


 ---------- 2014-07-21 14:00:00 : 동내면   11525 ----------


 ---------- 2014-07-21 14:00:00 : 효자1동   11526 ----------


 ---------- 2014-07-21 16:00:00 : 사북면   11527 ----------


 ---------- 2014-07-21 20:00:00 : 근화동   11528 ----------


 ---------- 2014-07-21 21:00:00 : 퇴계동   11530 ----------


 ---------- 2014-07-21 23:00:00 : 석사동   11533 ----------


 ---------- 2014-07-21 23:00:00 : 강남동   11534 ----------


 ---------- 2014-07-21 23:00:00 : 약사명동   11535 ----------


 ---------- 2014-07-22 09:00:00 : 서  면   11536 ----------


 ---------- 2014-07-22 09:00:00 : 남  면   11537 ----------


 ---------- 2014-07-22 09:00:00 : 퇴계동   11538 ----------


 ---------- 2014-07-22 10:00:00 : 동  면   11539 ----------


 ---------- 2014-07-22 11:00:00 : 신동면   11540 ----------


 ---------- 2014-07-22 11:00:00 : 동내면   11541 ----------


 ---------- 2014-07-22 11:00:00 : 남산면   11542 ----------


 ---------- 2014-07-22 12:00:00 : 서  면   11543 ----------


 ---------- 2014-07-22 12:00:00 : 동내면   11544 ----------


 ---------- 2014-07-22 13:00:00 : 강남동   11545 ----------


 ---------- 2014-07-22 14:00:00 : 북산면   11546 ----------


 ---------- 2014-07-22 15:00:00 : 효자1동   11547 ----------


 ---------- 2014-07-22 15:00:00 : 퇴계동   11549 ----------


 ---------- 2014-07-22 16:00:00 : 동내면   11550 ----------


 ---------- 2014-07-22 18:00:00 : 동내면   11551 ----------


 ---------- 2014-07-23 07:00:00 : 근화동   11552 ----------


 ---------- 2014-07-23 08:00:00 : 퇴계동   11553 ----------


 ---------- 2014-07-23 09:00:00 : 후평1동   11554 ----------


 ---------- 2014-07-23 10:00:00 : 북산면   11555 ----------


 ---------- 2014-07-23 11:00:00 : 신동면   11556 ----------


 ---------- 2014-07-23 11:00:00 : 동내면   11557 ----------


 ---------- 2014-07-23 11:00:00 : 신사우동   11558 ----------


 ---------- 2014-07-23 12:00:00 : 퇴계동   11559 ----------


 ---------- 2014-07-23 13:00:00 : 신사우동   11560 ----------


 ---------- 2014-07-23 14:00:00 : 남산면   11561 ----------


 ---------- 2014-07-23 15:00:00 : 신동면   11562 ----------


 ---------- 2014-07-23 15:00:00 : 효자1동   11563 ----------


 ---------- 2014-07-23 16:00:00 : 후평1동   11564 ----------


 ---------- 2014-07-23 21:00:00 : 퇴계동   11566 ----------


 ---------- 2014-07-24 02:00:00 : 후평1동   11567 ----------


 ---------- 2014-07-24 07:00:00 : 퇴계동   11569 ----------


 ---------- 2014-07-24 08:00:00 : 후평1동   11570 ----------


 ---------- 2014-07-24 09:00:00 : 남산면   11571 ----------


 ---------- 2014-07-24 14:00:00 : 사북면   11572 ----------


 ---------- 2014-07-24 14:00:00 : 조운동   11573 ----------


 ---------- 2014-07-24 15:00:00 : 신동면   11574 ----------


 ---------- 2014-07-24 16:00:00 : 서  면   11575 ----------


 ---------- 2014-07-24 16:00:00 : 남  면   11576 ----------


 ---------- 2014-07-24 17:00:00 : 동내면   11577 ----------


 ---------- 2014-07-24 18:00:00 : 근화동   11578 ----------


 ---------- 2014-07-24 19:00:00 : 강남동   11579 ----------


 ---------- 2014-07-24 21:00:00 : 동  면   11581 ----------


 ---------- 2014-07-24 21:00:00 : 퇴계동   11582 ----------


 ---------- 2014-07-24 22:00:00 : 석사동   11583 ----------


 ---------- 2014-07-25 01:00:00 : 근화동   11585 ----------


 ---------- 2014-07-25 03:00:00 : 효자1동   11588 ----------


 ---------- 2014-07-25 05:00:00 : 신사우동   11590 ----------


 ---------- 2014-07-25 08:00:00 : 남산면   11591 ----------


 ---------- 2014-07-25 08:00:00 : 약사명동   11592 ----------


 ---------- 2014-07-25 09:00:00 : 신동면   11593 ----------


 ---------- 2014-07-25 10:00:00 : 서  면   11594 ----------


 ---------- 2014-07-25 10:00:00 : 동  면   11595 ----------


 ---------- 2014-07-25 11:00:00 : 후평1동   11596 ----------


 ---------- 2014-07-25 12:00:00 : 약사명동   11597 ----------


 ---------- 2014-07-25 12:00:00 : 퇴계동   11598 ----------


 ---------- 2014-07-25 15:00:00 : 남산면   11599 ----------


 ---------- 2014-07-25 16:00:00 : 동  면   11600 ----------


 ---------- 2014-07-25 17:00:00 : 동  면   11601 ----------


 ---------- 2014-07-25 18:00:00 : 퇴계동   11602 ----------


 ---------- 2014-07-25 19:00:00 : 동  면   11604 ----------


 ---------- 2014-07-26 09:00:00 : 석사동   11605 ----------


 ---------- 2014-07-26 09:00:00 : 남산면   11606 ----------


 ---------- 2014-07-26 10:00:00 : 신동면   11607 ----------


 ---------- 2014-07-26 10:00:00 : 서  면   11608 ----------


 ---------- 2014-07-26 10:00:00 : 사북면   11609 ----------


 ---------- 2014-07-26 11:00:00 : 강남동   11610 ----------


 ---------- 2014-07-26 11:00:00 : 퇴계동   11611 ----------


 ---------- 2014-07-26 11:00:00 : 동산면   11612 ----------


 ---------- 2014-07-26 12:00:00 : 동산면   11613 ----------


 ---------- 2014-07-26 13:00:00 : 소양동   11614 ----------


 ---------- 2014-07-26 15:00:00 : 남산면   11615 ----------


 ---------- 2014-07-26 18:00:00 : 동내면   11616 ----------


 ---------- 2014-07-26 20:00:00 : 효자1동   11617 ----------


 ---------- 2014-07-26 22:00:00 : 퇴계동   11618 ----------


 ---------- 2014-07-27 00:00:00 : 남산면   11619 ----------


 ---------- 2014-07-27 01:00:00 : 효자1동   11620 ----------


 ---------- 2014-07-27 08:00:00 : 신동면   11621 ----------


 ---------- 2014-07-27 09:00:00 : 남  면   11622 ----------


 ---------- 2014-07-27 10:00:00 : 동산면   11623 ----------


 ---------- 2014-07-27 11:00:00 : 효자1동   11625 ----------


 ---------- 2014-07-27 13:00:00 : 남산면   11626 ----------


 ---------- 2014-07-27 13:00:00 : 신북읍   11627 ----------


 ---------- 2014-07-27 15:00:00 : 북산면   11629 ----------


 ---------- 2014-07-27 16:00:00 : 사북면   11630 ----------


 ---------- 2014-07-27 16:00:00 : 남산면   11631 ----------


 ---------- 2014-07-27 17:00:00 : 남  면   11634 ----------


 ---------- 2014-07-27 17:00:00 : 남산면   11635 ----------


 ---------- 2014-07-27 17:00:00 : 신사우동   11637 ----------


 ---------- 2014-07-27 18:00:00 : 북산면   11638 ----------


 ---------- 2014-07-27 20:00:00 : 석사동   11639 ----------


 ---------- 2014-07-27 20:00:00 : 신사우동   11640 ----------


 ---------- 2014-07-27 22:00:00 : 후평1동   11642 ----------


 ---------- 2014-07-28 03:00:00 : 신사우동   11643 ----------


 ---------- 2014-07-28 06:00:00 : 남산면   11644 ----------


 ---------- 2014-07-28 08:00:00 : 사북면   11645 ----------


 ---------- 2014-07-28 09:00:00 : 퇴계동   11646 ----------


 ---------- 2014-07-28 10:00:00 : 강남동   11647 ----------


 ---------- 2014-07-28 10:00:00 : 동내면   11648 ----------


 ---------- 2014-07-28 11:00:00 : 동  면   11649 ----------


 ---------- 2014-07-28 13:00:00 : 남산면   11650 ----------


 ---------- 2014-07-28 13:00:00 : 동  면   11651 ----------


 ---------- 2014-07-28 14:00:00 : 사북면   11652 ----------


 ---------- 2014-07-28 14:00:00 : 신사우동   11653 ----------

 ---------- 2014-07-28 14:00:00 : 동  면   11655 ----------


 ---------- 2014-07-28 14:00:00 : 퇴계동   11657 ----------


 ---------- 2014-07-28 15:00:00 : 동내면   11658 ----------


 ---------- 2014-07-28 15:00:00 : 후평1동   11659 ----------


 ---------- 2014-07-28 15:00:00 : 교  동   11660 ----------


 ---------- 2014-07-28 16:00:00 : 남  면   11661 ----------


 ---------- 2014-07-28 16:00:00 : 소양동   11662 ----------


 ---------- 2014-07-28 17:00:00 : 퇴계동   11663 ----------


 ---------- 2014-07-28 17:00:00 : 동산면   11664 ----------


 ---------- 2014-07-28 18:00:00 : 석사동   11665 ----------


 ---------- 2014-07-28 18:00:00 : 후평1동   11666 ----------


 ---------- 2014-07-28 19:00:00 : 석사동   11667 ----------


 ---------- 2014-07-28 21:00:00 : 후평1동   11668 ----------


 ---------- 2014-07-28 21:00:00 : 퇴계동   11669 ----------


 ---------- 2014-07-28 23:00:00 : 퇴계동   11670 ----------


 ---------- 2014-07-29 08:00:00 : 석사동   11671 ----------


 ---------- 2014-07-29 08:00:00 : 조운동   11672 ----------


 ---------- 2014-07-29 09:00:00 : 서  면   11673 ----------


 ---------- 2014-07-29 09:00:00 : 사북면   11674 ----------


 ---------- 2014-07-29 09:00:00 : 동내면   11675 ----------


 ---------- 2014-07-29 09:00:00 : 남산면   11677 ----------


 ---------- 2014-07-29 09:00:00 : 퇴계동   11678 ----------


 ---------- 2014-07-29 09:00:00 : 교  동   11679 ----------


 ---------- 2014-07-29 12:00:00 : 퇴계동   11680 ----------


 ---------- 2014-07-29 13:00:00 : 효자1동   11681 ----------


 ---------- 2014-07-29 13:00:00 : 신사우동   11682 ----------


 ---------- 2014-07-29 13:00:00 : 동산면   11683 ----------


 ---------- 2014-07-29 14:00:00 : 후평1동   11684 ----------


 ---------- 2014-07-29 16:00:00 : 후평1동   11685 ----------


 ---------- 2014-07-29 19:00:00 : 강남동   11686 ----------


 ---------- 2014-07-29 22:00:00 : 신사우동   11687 ----------


 ---------- 2014-07-29 23:00:00 : 조운동   11689 ----------


 ---------- 2014-07-30 08:00:00 : 동내면   11690 ----------


 ---------- 2014-07-30 09:00:00 : 강남동   11691 ----------


 ---------- 2014-07-30 09:00:00 : 동  면   11692 ----------


 ---------- 2014-07-30 09:00:00 : 퇴계동   11693 ----------


 ---------- 2014-07-30 10:00:00 : 강남동   11694 ----------


 ---------- 2014-07-30 11:00:00 : 효자1동   11695 ----------


 ---------- 2014-07-30 12:00:00 : 퇴계동   11696 ----------


 ---------- 2014-07-30 12:00:00 : 동산면   11697 ----------


 ---------- 2014-07-30 13:00:00 : 남산면   11698 ----------


 ---------- 2014-07-30 14:00:00 : 동  면   11700 ----------


 ---------- 2014-07-30 16:00:00 : 강남동   11701 ----------


 ---------- 2014-07-30 16:00:00 : 동  면   11703 ----------


 ---------- 2014-07-30 17:00:00 : 신북읍   11704 ----------


 ---------- 2014-07-30 17:00:00 : 소양동   11705 ----------


 ---------- 2014-07-31 00:00:00 : 동내면   11706 ----------


 ---------- 2014-07-31 06:00:00 : 강남동   11707 ----------


 ---------- 2014-07-31 09:00:00 : 동내면   11708 ----------


 ---------- 2014-07-31 09:00:00 : 남산면   11709 ----------


 ---------- 2014-07-31 09:00:00 : 퇴계동   11710 ----------


 ---------- 2014-07-31 10:00:00 : 남  면   11711 ----------


 ---------- 2014-07-31 10:00:00 : 동내면   11712 ----------


 ---------- 2014-07-31 10:00:00 : 후평1동   11713 ----------


 ---------- 2014-07-31 11:00:00 : 석사동   11714 ----------


 ---------- 2014-07-31 11:00:00 : 남산면   11716 ----------


 ---------- 2014-07-31 11:00:00 : 신북읍   11717 ----------


 ---------- 2014-07-31 11:00:00 : 후평1동   11718 ----------


 ---------- 2014-07-31 13:00:00 : 남산면   11719 ----------


 ---------- 2014-07-31 13:00:00 : 북산면   11720 ----------


 ---------- 2014-07-31 14:00:00 : 남  면   11721 ----------


 ---------- 2014-07-31 14:00:00 : 남산면   11723 ----------


 ---------- 2014-07-31 14:00:00 : 북산면   11725 ----------


 ---------- 2014-07-31 15:00:00 : 동내면   11726 ----------


 ---------- 2014-07-31 17:00:00 : 동  면   11727 ----------


 ---------- 2014-08-01 00:00:00 : 후평1동   11728 ----------


 ---------- 2014-08-01 09:00:00 : 서  면   11729 ----------


 ---------- 2014-08-01 10:00:00 : 동  면   11730 ----------


 ---------- 2014-08-01 11:00:00 : 강남동   11731 ----------


 ---------- 2014-08-01 11:00:00 : 동산면   11732 ----------


 ---------- 2014-08-01 11:00:00 : 교  동   11733 ----------


 ---------- 2014-08-01 13:00:00 : 남산면   11734 ----------


 ---------- 2014-08-01 13:00:00 : 신북읍   11735 ----------


 ---------- 2014-08-01 13:00:00 : 후평1동   11736 ----------


 ---------- 2014-08-01 14:00:00 : 서  면   11737 ----------


 ---------- 2014-08-01 15:00:00 : 신사우동   11738 ----------


 ---------- 2014-08-01 16:00:00 : 북산면   11739 ----------


 ---------- 2014-08-01 19:00:00 : 동내면   11740 ----------


 ---------- 2014-08-01 22:00:00 : 근화동   11741 ----------


 ---------- 2014-08-02 01:00:00 : 석사동   11742 ----------


 ---------- 2014-08-02 04:00:00 : 동내면   11745 ----------


 ---------- 2014-08-02 06:00:00 : 동  면   11748 ----------


 ---------- 2014-08-02 08:00:00 : 남산면   11749 ----------


 ---------- 2014-08-02 08:00:00 : 근화동   11750 ----------


 ---------- 2014-08-02 09:00:00 : 서  면   11751 ----------


 ---------- 2014-08-02 10:00:00 : 사북면   11752 ----------


 ---------- 2014-08-02 11:00:00 : 석사동   11753 ----------


 ---------- 2014-08-02 14:00:00 : 남  면   11754 ----------


 ---------- 2014-08-02 16:00:00 : 서  면   11755 ----------


 ---------- 2014-08-02 17:00:00 : 교  동   11756 ----------


 ---------- 2014-08-03 02:00:00 : 효자1동   11757 ----------


 ---------- 2014-08-03 08:00:00 : 신사우동   11758 ----------


 ---------- 2014-08-03 09:00:00 : 효자1동   11759 ----------


 ---------- 2014-08-03 12:00:00 : 남  면   11760 ----------


 ---------- 2014-08-03 12:00:00 : 북산면   11761 ----------


 ---------- 2014-08-03 13:00:00 : 동내면   11762 ----------


 ---------- 2014-08-03 13:00:00 : 남산면   11763 ----------


 ---------- 2014-08-03 15:00:00 : 남산면   11764 ----------


 ---------- 2014-08-03 16:00:00 : 남산면   11765 ----------


 ---------- 2014-08-03 17:00:00 : 동내면   11766 ----------


 ---------- 2014-08-04 07:00:00 : 후평1동   11767 ----------


 ---------- 2014-08-04 09:00:00 : 서  면   11769 ----------


 ---------- 2014-08-04 09:00:00 : 남산면   11770 ----------


 ---------- 2014-08-04 09:00:00 : 신사우동   11771 ----------


 ---------- 2014-08-04 10:00:00 : 소양동   11772 ----------


 ---------- 2014-08-04 11:00:00 : 강남동   11773 ----------


 ---------- 2014-08-04 12:00:00 : 신사우동   11775 ----------


 ---------- 2014-08-04 13:00:00 : 서  면   11776 ----------


 ---------- 2014-08-04 13:00:00 : 사북면   11778 ----------


 ---------- 2014-08-04 14:00:00 : 신북읍   11779 ----------


 ---------- 2014-08-04 14:00:00 : 퇴계동   11780 ----------


 ---------- 2014-08-04 15:00:00 : 서  면   11781 ----------


 ---------- 2014-08-04 15:00:00 : 남산면   11782 ----------


 ---------- 2014-08-04 18:00:00 : 석사동   11783 ----------


 ---------- 2014-08-04 18:00:00 : 후평1동   11784 ----------


 ---------- 2014-08-04 19:00:00 : 동  면   11785 ----------


 ---------- 2014-08-04 21:00:00 : 동  면   11786 ----------


 ---------- 2014-08-05 10:00:00 : 동내면   11787 ----------


 ---------- 2014-08-05 10:00:00 : 남산면   11788 ----------


 ---------- 2014-08-05 13:00:00 : 남산면   11789 ----------


 ---------- 2014-08-05 13:00:00 : 소양동   11790 ----------


 ---------- 2014-08-05 13:00:00 : 동산면   11791 ----------


 ---------- 2014-08-05 14:00:00 : 동  면   11792 ----------


 ---------- 2014-08-05 15:00:00 : 석사동   11794 ----------


 ---------- 2014-08-05 15:00:00 : 강남동   11795 ----------


 ---------- 2014-08-05 16:00:00 : 신사우동   11797 ----------


 ---------- 2014-08-05 18:00:00 : 후평1동   11798 ----------


 ---------- 2014-08-06 08:00:00 : 남  면   11799 ----------


 ---------- 2014-08-06 08:00:00 : 신북읍   11800 ----------


 ---------- 2014-08-06 09:00:00 : 서  면   11801 ----------


 ---------- 2014-08-06 09:00:00 : 남  면   11802 ----------


 ---------- 2014-08-06 10:00:00 : 퇴계동   11803 ----------


 ---------- 2014-08-06 11:00:00 : 강남동   11804 ----------


 ---------- 2014-08-06 13:00:00 : 후평1동   11805 ----------


 ---------- 2014-08-06 13:00:00 : 퇴계동   11808 ----------


 ---------- 2014-08-06 14:00:00 : 서  면   11810 ----------

 ---------- 2014-08-06 14:00:00 : 동  면   11811 ----------


 ---------- 2014-08-06 15:00:00 : 남산면   11812 ----------


 ---------- 2014-08-06 15:00:00 : 후평1동   11813 ----------


 ---------- 2014-08-06 16:00:00 : 동내면   11814 ----------


 ---------- 2014-08-06 16:00:00 : 남산면   11815 ----------


 ---------- 2014-08-07 09:00:00 : 남산면   11816 ----------


 ---------- 2014-08-07 09:00:00 : 동  면   11817 ----------


 ---------- 2014-08-07 09:00:00 : 교  동   11818 ----------


 ---------- 2014-08-07 10:00:00 : 강남동   11819 ----------


 ---------- 2014-08-07 10:00:00 : 신사우동   11821 ----------


 ---------- 2014-08-07 10:00:00 : 신북읍   11822 ----------


 ---------- 2014-08-07 10:00:00 : 소양동   11823 ----------


 ---------- 2014-08-07 13:00:00 : 남산면   11825 ----------


 ---------- 2014-08-07 13:00:00 : 북산면   11826 ----------


 ---------- 2014-08-07 14:00:00 : 강남동   11828 ----------


 ---------- 2014-08-07 18:00:00 : 퇴계동   11829 ----------


 ---------- 2014-08-07 22:00:00 : 소양동   11830 ----------


 ---------- 2014-08-08 00:00:00 : 동내면   11831 ----------


 ---------- 2014-08-08 08:00:00 : 신북읍   11832 ----------


 ---------- 2014-08-08 08:00:00 : 동  면   11833 ----------


 ---------- 2014-08-08 08:00:00 : 후평1동   11835 ----------


 ---------- 2014-08-08 09:00:00 : 남산면   11837 ----------


 ---------- 2014-08-08 10:00:00 : 동  면   11840 ----------


 ---------- 2014-08-08 10:00:00 : 퇴계동   11841 ----------


 ---------- 2014-08-08 10:00:00 : 동산면   11842 ----------


 ---------- 2014-08-08 12:00:00 : 남산면   11843 ----------


 ---------- 2014-08-08 13:00:00 : 서  면   11844 ----------


 ---------- 2014-08-08 13:00:00 : 동내면   11847 ----------


 ---------- 2014-08-08 13:00:00 : 효자1동   11848 ----------


 ---------- 2014-08-08 14:00:00 : 신동면   11850 ----------


 ---------- 2014-08-08 15:00:00 : 남산면   11851 ----------


 ---------- 2014-08-08 16:00:00 : 남  면   11852 ----------


 ---------- 2014-08-08 16:00:00 : 동산면   11853 ----------


 ---------- 2014-08-08 17:00:00 : 퇴계동   11856 ----------


 ---------- 2014-08-08 18:00:00 : 강남동   11857 ----------


 ---------- 2014-08-08 18:00:00 : 퇴계동   11858 ----------


 ---------- 2014-08-08 19:00:00 : 강남동   11860 ----------


 ---------- 2014-08-08 19:00:00 : 신북읍   11861 ----------


 ---------- 2014-08-09 09:00:00 : 남산면   11862 ----------


 ---------- 2014-08-09 09:00:00 : 동  면   11863 ----------


 ---------- 2014-08-09 10:00:00 : 신동면   11864 ----------


 ---------- 2014-08-09 11:00:00 : 신사우동   11865 ----------


 ---------- 2014-08-09 12:00:00 : 동  면   11866 ----------


 ---------- 2014-08-09 13:00:00 : 신사우동   11867 ----------


 ---------- 2014-08-09 14:00:00 : 서  면   11868 ----------


 ---------- 2014-08-09 14:00:00 : 후평1동   11869 ----------


 ---------- 2014-08-09 15:00:00 : 동  면   11870 ----------


 ---------- 2014-08-09 17:00:00 : 석사동   11871 ----------


 ---------- 2014-08-09 17:00:00 : 동  면   11872 ----------


 ---------- 2014-08-09 17:00:00 : 북산면   11873 ----------


 ---------- 2014-08-09 19:00:00 : 강남동   11875 ----------


 ---------- 2014-08-10 08:00:00 : 소양동   11876 ----------


 ---------- 2014-08-10 09:00:00 : 신사우동   11877 ----------


 ---------- 2014-08-10 10:00:00 : 후평1동   11878 ----------


 ---------- 2014-08-10 12:00:00 : 서  면   11879 ----------


 ---------- 2014-08-10 12:00:00 : 동내면   11880 ----------


 ---------- 2014-08-10 12:00:00 : 교  동   11881 ----------


 ---------- 2014-08-10 13:00:00 : 퇴계동   11882 ----------


 ---------- 2014-08-10 14:00:00 : 서  면   11883 ----------


 ---------- 2014-08-10 14:00:00 : 동  면   11884 ----------


 ---------- 2014-08-10 16:00:00 : 신동면   11885 ----------


 ---------- 2014-08-10 16:00:00 : 동내면   11886 ----------


 ---------- 2014-08-10 17:00:00 : 신동면   11887 ----------


 ---------- 2014-08-10 20:00:00 : 소양동   11888 ----------


 ---------- 2014-08-11 03:00:00 : 신북읍   11889 ----------


 ---------- 2014-08-11 06:00:00 : 서  면   11890 ----------


 ---------- 2014-08-11 07:00:00 : 퇴계동   11891 ----------


 ---------- 2014-08-11 08:00:00 : 석사동   11892 ----------


 ---------- 2014-08-11 08:00:00 : 강남동   11893 ----------


 ---------- 2014-08-11 09:00:00 : 남산면   11894 ----------


 ---------- 2014-08-11 10:00:00 : 신동면   11895 ----------


 ---------- 2014-08-11 10:00:00 : 남산면   11896 ----------


 ---------- 2014-08-11 13:00:00 : 석사동   11897 ----------


 ---------- 2014-08-11 13:00:00 : 서  면   11898 ----------


 ---------- 2014-08-11 14:00:00 : 효자1동   11899 ----------


 ---------- 2014-08-11 14:00:00 : 근화동   11900 ----------


 ---------- 2014-08-11 14:00:00 : 신사우동   11901 ----------


 ---------- 2014-08-11 15:00:00 : 효자1동   11902 ----------


 ---------- 2014-08-11 16:00:00 : 동내면   11903 ----------


 ---------- 2014-08-12 02:00:00 : 후평1동   11906 ----------


 ---------- 2014-08-12 03:00:00 : 퇴계동   11908 ----------


 ---------- 2014-08-12 07:00:00 : 퇴계동   11909 ----------


 ---------- 2014-08-12 08:00:00 : 신동면   11910 ----------


 ---------- 2014-08-12 09:00:00 : 남산면   11911 ----------


 ---------- 2014-08-12 09:00:00 : 신북읍   11912 ----------


 ---------- 2014-08-12 10:00:00 : 신동면   11913 ----------


 ---------- 2014-08-12 10:00:00 : 남산면   11914 ----------


 ---------- 2014-08-12 10:00:00 : 소양동   11915 ----------


 ---------- 2014-08-12 10:00:00 : 북산면   11918 ----------


 ---------- 2014-08-12 12:00:00 : 북산면   11919 ----------


 ---------- 2014-08-12 13:00:00 : 남산면   11920 ----------


 ---------- 2014-08-12 13:00:00 : 근화동   11921 ----------


 ---------- 2014-08-12 14:00:00 : 신북읍   11922 ----------


 ---------- 2014-08-12 15:00:00 : 남산면   11923 ----------


 ---------- 2014-08-12 17:00:00 : 강남동   11924 ----------


 ---------- 2014-08-12 18:00:00 : 신북읍   11925 ----------


 ---------- 2014-08-12 22:00:00 : 동내면   11926 ----------


 ---------- 2014-08-13 01:00:00 : 석사동   11927 ----------


 ---------- 2014-08-13 06:00:00 : 서  면   11929 ----------


 ---------- 2014-08-13 08:00:00 : 사북면   11930 ----------


 ---------- 2014-08-13 09:00:00 : 강남동   11931 ----------


 ---------- 2014-08-13 09:00:00 : 남산면   11932 ----------


 ---------- 2014-08-13 10:00:00 : 북산면   11933 ----------


 ---------- 2014-08-13 12:00:00 : 남산면   11934 ----------


 ---------- 2014-08-13 12:00:00 : 후평1동   11935 ----------


 ---------- 2014-08-13 13:00:00 : 석사동   11936 ----------


 ---------- 2014-08-13 13:00:00 : 신북읍   11937 ----------


 ---------- 2014-08-13 13:00:00 : 동  면   11938 ----------


 ---------- 2014-08-13 13:00:00 : 퇴계동   11939 ----------


 ---------- 2014-08-13 14:00:00 : 서  면   11940 ----------


 ---------- 2014-08-13 15:00:00 : 신동면   11941 ----------


 ---------- 2014-08-13 15:00:00 : 남산면   11942 ----------


 ---------- 2014-08-13 16:00:00 : 신사우동   11943 ----------


 ---------- 2014-08-13 16:00:00 : 후평1동   11944 ----------


 ---------- 2014-08-13 22:00:00 : 신사우동   11945 ----------


 ---------- 2014-08-14 08:00:00 : 북산면   11946 ----------


 ---------- 2014-08-14 09:00:00 : 효자1동   11947 ----------


 ---------- 2014-08-14 09:00:00 : 후평1동   11948 ----------


 ---------- 2014-08-14 10:00:00 : 석사동   11949 ----------


 ---------- 2014-08-14 10:00:00 : 강남동   11950 ----------


 ---------- 2014-08-14 10:00:00 : 퇴계동   11951 ----------


 ---------- 2014-08-14 12:00:00 : 남  면   11952 ----------


 ---------- 2014-08-14 12:00:00 : 후평1동   11953 ----------


 ---------- 2014-08-14 14:00:00 : 동  면   11955 ----------


 ---------- 2014-08-14 15:00:00 : 사북면   11956 ----------


 ---------- 2014-08-14 15:00:00 : 동  면   11957 ----------


 ---------- 2014-08-14 16:00:00 : 후평1동   11958 ----------


 ---------- 2014-08-14 19:00:00 : 강남동   11959 ----------


 ---------- 2014-08-14 19:00:00 : 동내면   11960 ----------


 ---------- 2014-08-15 06:00:00 : 효자1동   11962 ----------


 ---------- 2014-08-15 06:00:00 : 북산면   11964 ----------


 ---------- 2014-08-15 08:00:00 : 신동면   11965 ----------


 ---------- 2014-08-15 08:00:00 : 강남동   11966 ----------


 ---------- 2014-08-15 09:00:00 : 남산면   11967 ----------


 ---------- 2014-08-15 09:00:00 : 동  면   11968 ----------


 ---------- 2014-08-15 11:00:00 : 신동면   11969 ----------

 ---------- 2014-08-15 12:00:00 : 후평1동   11970 ----------


 ---------- 2014-08-15 13:00:00 : 서  면   11971 ----------


 ---------- 2014-08-15 14:00:00 : 강남동   11972 ----------


 ---------- 2014-08-15 14:00:00 : 동  면   11973 ----------


 ---------- 2014-08-15 16:00:00 : 서  면   11974 ----------


 ---------- 2014-08-15 17:00:00 : 서  면   11975 ----------


 ---------- 2014-08-15 17:00:00 : 후평1동   11976 ----------


 ---------- 2014-08-15 17:00:00 : 북산면   11977 ----------


 ---------- 2014-08-15 18:00:00 : 소양동   11981 ----------


 ---------- 2014-08-15 20:00:00 : 동  면   11982 ----------


 ---------- 2014-08-16 02:00:00 : 효자1동   11983 ----------


 ---------- 2014-08-16 08:00:00 : 남  면   11984 ----------


 ---------- 2014-08-16 09:00:00 : 석사동   11985 ----------


 ---------- 2014-08-16 10:00:00 : 석사동   11986 ----------


 ---------- 2014-08-16 10:00:00 : 동내면   11987 ----------


 ---------- 2014-08-16 10:00:00 : 남산면   11988 ----------


 ---------- 2014-08-16 12:00:00 : 석사동   11989 ----------


 ---------- 2014-08-16 12:00:00 : 남산면   11990 ----------


 ---------- 2014-08-16 12:00:00 : 소양동   11992 ----------


 ---------- 2014-08-16 13:00:00 : 효자1동   11993 ----------


 ---------- 2014-08-16 13:00:00 : 남산면   11994 ----------


 ---------- 2014-08-16 16:00:00 : 퇴계동   11995 ----------


 ---------- 2014-08-16 17:00:00 : 근화동   11996 ----------


 ---------- 2014-08-16 18:00:00 : 강남동   11997 ----------


 ---------- 2014-08-16 23:00:00 : 남  면   11998 ----------


 ---------- 2014-08-17 03:00:00 : 신북읍   11999 ----------


 ---------- 2014-08-17 09:00:00 : 남산면   12000 ----------


 ---------- 2014-08-17 09:00:00 : 신사우동   12001 ----------


 ---------- 2014-08-17 10:00:00 : 사북면   12002 ----------


 ---------- 2014-08-17 10:00:00 : 남산면   12003 ----------


 ---------- 2014-08-17 11:00:00 : 남산면   12005 ----------


 ---------- 2014-08-17 12:00:00 : 강남동   12006 ----------


 ---------- 2014-08-17 14:00:00 : 남산면   12008 ----------


 ---------- 2014-08-17 15:00:00 : 소양동   12009 ----------


 ---------- 2014-08-17 16:00:00 : 남산면   12010 ----------


 ---------- 2014-08-17 16:00:00 : 신사우동   12011 ----------


 ---------- 2014-08-17 16:00:00 : 후평1동   12012 ----------


 ---------- 2014-08-17 18:00:00 : 석사동   12013 ----------


 ---------- 2014-08-17 20:00:00 : 동  면   12014 ----------


 ---------- 2014-08-17 23:00:00 : 신사우동   12015 ----------


 ---------- 2014-08-18 01:00:00 : 신북읍   12017 ----------


 ---------- 2014-08-18 08:00:00 : 신동면   12018 ----------


 ---------- 2014-08-18 09:00:00 : 남  면   12019 ----------


 ---------- 2014-08-18 10:00:00 : 동  면   12020 ----------


 ---------- 2014-08-18 14:00:00 : 동  면   12021 ----------


 ---------- 2014-08-18 22:00:00 : 신사우동   12023 ----------


 ---------- 2014-08-19 00:00:00 : 동산면   12024 ----------


 ---------- 2014-08-19 09:00:00 : 동내면   12025 ----------


 ---------- 2014-08-19 09:00:00 : 남산면   12027 ----------


 ---------- 2014-08-19 10:00:00 : 동내면   12028 ----------


 ---------- 2014-08-19 14:00:00 : 신북읍   12029 ----------


 ---------- 2014-08-19 16:00:00 : 사북면   12030 ----------


 ---------- 2014-08-19 19:00:00 : 근화동   12031 ----------


 ---------- 2014-08-20 09:00:00 : 동내면   12032 ----------


 ---------- 2014-08-20 09:00:00 : 남산면   12034 ----------


 ---------- 2014-08-20 09:00:00 : 소양동   12035 ----------


 ---------- 2014-08-20 10:00:00 : 효자1동   12037 ----------


 ---------- 2014-08-20 10:00:00 : 소양동   12038 ----------


 ---------- 2014-08-20 12:00:00 : 퇴계동   12039 ----------


 ---------- 2014-08-20 13:00:00 : 후평1동   12040 ----------


 ---------- 2014-08-20 13:00:00 : 북산면   12041 ----------


 ---------- 2014-08-20 14:00:00 : 강남동   12042 ----------


 ---------- 2014-08-20 14:00:00 : 후평1동   12043 ----------


 ---------- 2014-08-20 14:00:00 : 북산면   12044 ----------


 ---------- 2014-08-20 14:00:00 : 동산면   12045 ----------


 ---------- 2014-08-20 17:00:00 : 신사우동   12046 ----------


 ---------- 2014-08-20 17:00:00 : 북산면   12047 ----------


 ---------- 2014-08-21 01:00:00 : 근화동   12048 ----------


 ---------- 2014-08-21 10:00:00 : 강남동   12049 ----------


 ---------- 2014-08-21 10:00:00 : 남산면   12050 ----------


 ---------- 2014-08-21 11:00:00 : 약사명동   12051 ----------


 ---------- 2014-08-21 17:00:00 : 동산면   12052 ----------


 ---------- 2014-08-22 09:00:00 : 석사동   12053 ----------


 ---------- 2014-08-22 09:00:00 : 신사우동   12054 ----------


 ---------- 2014-08-22 10:00:00 : 동산면   12055 ----------


 ---------- 2014-08-22 10:00:00 : 교  동   12056 ----------


 ---------- 2014-08-22 13:00:00 : 북산면   12057 ----------


 ---------- 2014-08-22 15:00:00 : 신북읍   12058 ----------


 ---------- 2014-08-22 18:00:00 : 후평1동   12059 ----------


 ---------- 2014-08-22 22:00:00 : 후평1동   12061 ----------


 ---------- 2014-08-23 00:00:00 : 소양동   12062 ----------


 ---------- 2014-08-23 08:00:00 : 서  면   12063 ----------


 ---------- 2014-08-23 09:00:00 : 신동면   12065 ----------


 ---------- 2014-08-23 11:00:00 : 동  면   12066 ----------


 ---------- 2014-08-23 12:00:00 : 근화동   12067 ----------


 ---------- 2014-08-23 13:00:00 : 신동면   12068 ----------


 ---------- 2014-08-23 13:00:00 : 남산면   12069 ----------


 ---------- 2014-08-23 14:00:00 : 강남동   12070 ----------


 ---------- 2014-08-23 15:00:00 : 서  면   12071 ----------


 ---------- 2014-08-23 16:00:00 : 신북읍   12072 ----------


 ---------- 2014-08-23 16:00:00 : 소양동   12073 ----------


 ---------- 2014-08-23 16:00:00 : 후평1동   12075 ----------


 ---------- 2014-08-23 17:00:00 : 효자1동   12076 ----------


 ---------- 2014-08-23 17:00:00 : 남산면   12077 ----------


 ---------- 2014-08-23 17:00:00 : 근화동   12078 ----------


 ---------- 2014-08-23 18:00:00 : 강남동   12079 ----------


 ---------- 2014-08-23 20:00:00 : 석사동   12080 ----------


 ---------- 2014-08-24 09:00:00 : 서  면   12081 ----------


 ---------- 2014-08-24 09:00:00 : 교  동   12082 ----------


 ---------- 2014-08-24 10:00:00 : 강남동   12083 ----------


 ---------- 2014-08-24 10:00:00 : 북산면   12084 ----------


 ---------- 2014-08-24 12:00:00 : 석사동   12085 ----------


 ---------- 2014-08-24 12:00:00 : 남산면   12086 ----------


 ---------- 2014-08-24 14:00:00 : 강남동   12087 ----------


 ---------- 2014-08-24 15:00:00 : 신동면   12088 ----------


 ---------- 2014-08-24 17:00:00 : 동내면   12089 ----------


 ---------- 2014-08-24 21:00:00 : 퇴계동   12091 ----------


 ---------- 2014-08-25 07:00:00 : 후평1동   12092 ----------


 ---------- 2014-08-25 09:00:00 : 석사동   12093 ----------


 ---------- 2014-08-25 09:00:00 : 남  면   12094 ----------


 ---------- 2014-08-25 09:00:00 : 후평1동   12095 ----------


 ---------- 2014-08-25 10:00:00 : 서  면   12096 ----------


 ---------- 2014-08-25 15:00:00 : 근화동   12098 ----------


 ---------- 2014-08-25 16:00:00 : 신북읍   12099 ----------


 ---------- 2014-08-25 17:00:00 : 신동면   12100 ----------


 ---------- 2014-08-25 17:00:00 : 신북읍   12102 ----------


 ---------- 2014-08-25 17:00:00 : 후평1동   12104 ----------


 ---------- 2014-08-25 22:00:00 : 신북읍   12105 ----------


 ---------- 2014-08-26 08:00:00 : 서  면   12106 ----------


 ---------- 2014-08-26 09:00:00 : 동내면   12107 ----------


 ---------- 2014-08-26 09:00:00 : 남산면   12108 ----------


 ---------- 2014-08-26 10:00:00 : 신북읍   12109 ----------


 ---------- 2014-08-26 10:00:00 : 후평1동   12110 ----------


 ---------- 2014-08-26 10:00:00 : 퇴계동   12111 ----------


 ---------- 2014-08-26 13:00:00 : 남산면   12112 ----------


 ---------- 2014-08-26 13:00:00 : 동  면   12113 ----------


 ---------- 2014-08-26 15:00:00 : 동  면   12114 ----------


 ---------- 2014-08-26 16:00:00 : 후평1동   12116 ----------


 ---------- 2014-08-26 17:00:00 : 신사우동   12117 ----------


 ---------- 2014-08-26 22:00:00 : 퇴계동   12118 ----------


 ---------- 2014-08-27 09:00:00 : 사북면   12119 ----------


 ---------- 2014-08-27 09:00:00 : 동  면   12120 ----------


 ---------- 2014-08-27 10:00:00 : 근화동   12121 ----------


 ---------- 2014-08-27 10:00:00 : 신사우동   12122 ----------


 ---------- 2014-08-27 11:00:00 : 근화동   12123 ----------


 ---------- 2014-08-27 13:00:00 : 강남동   12124 ----------

 ---------- 2014-08-27 13:00:00 : 소양동   12125 ----------


 ---------- 2014-08-27 13:00:00 : 퇴계동   12126 ----------


 ---------- 2014-08-27 14:00:00 : 후평1동   12127 ----------


 ---------- 2014-08-27 15:00:00 : 남산면   12128 ----------


 ---------- 2014-08-27 16:00:00 : 조운동   12129 ----------


 ---------- 2014-08-27 17:00:00 : 후평1동   12130 ----------


 ---------- 2014-08-27 17:00:00 : 조운동   12131 ----------


 ---------- 2014-08-27 22:00:00 : 퇴계동   12133 ----------


 ---------- 2014-08-27 23:00:00 : 효자1동   12134 ----------


 ---------- 2014-08-28 09:00:00 : 강남동   12135 ----------


 ---------- 2014-08-28 10:00:00 : 강남동   12136 ----------


 ---------- 2014-08-28 13:00:00 : 신동면   12139 ----------


 ---------- 2014-08-28 13:00:00 : 남  면   12140 ----------


 ---------- 2014-08-28 13:00:00 : 후평1동   12141 ----------


 ---------- 2014-08-28 13:00:00 : 퇴계동   12142 ----------


 ---------- 2014-08-28 14:00:00 : 소양동   12143 ----------


 ---------- 2014-08-28 16:00:00 : 근화동   12145 ----------


 ---------- 2014-08-28 18:00:00 : 소양동   12146 ----------


 ---------- 2014-08-28 19:00:00 : 후평1동   12147 ----------


 ---------- 2014-08-28 20:00:00 : 동산면   12148 ----------


 ---------- 2014-08-28 21:00:00 : 약사명동   12149 ----------


 ---------- 2014-08-29 00:00:00 : 퇴계동   12150 ----------


 ---------- 2014-08-29 07:00:00 : 신동면   12151 ----------


 ---------- 2014-08-29 07:00:00 : 서  면   12152 ----------


 ---------- 2014-08-29 09:00:00 : 강남동   12153 ----------


 ---------- 2014-08-29 13:00:00 : 강남동   12154 ----------


 ---------- 2014-08-29 13:00:00 : 신북읍   12155 ----------


 ---------- 2014-08-29 14:00:00 : 북산면   12157 ----------


 ---------- 2014-08-29 15:00:00 : 북산면   12158 ----------


 ---------- 2014-08-29 16:00:00 : 효자1동   12159 ----------


 ---------- 2014-08-29 17:00:00 : 조운동   12160 ----------


 ---------- 2014-08-29 18:00:00 : 석사동   12161 ----------


 ---------- 2014-08-29 22:00:00 : 효자1동   12162 ----------


 ---------- 2014-08-29 22:00:00 : 약사명동   12163 ----------


 ---------- 2014-08-30 08:00:00 : 강남동   12164 ----------


 ---------- 2014-08-30 09:00:00 : 신동면   12165 ----------


 ---------- 2014-08-30 09:00:00 : 서  면   12166 ----------


 ---------- 2014-08-30 11:00:00 : 신동면   12167 ----------


 ---------- 2014-08-30 13:00:00 : 강남동   12168 ----------


 ---------- 2014-08-30 14:00:00 : 사북면   12171 ----------


 ---------- 2014-08-30 14:00:00 : 동내면   12172 ----------


 ---------- 2014-08-30 15:00:00 : 효자1동   12174 ----------


 ---------- 2014-08-30 16:00:00 : 근화동   12175 ----------


 ---------- 2014-08-30 17:00:00 : 효자1동   12177 ----------


 ---------- 2014-08-30 17:00:00 : 후평1동   12178 ----------


 ---------- 2014-08-30 20:00:00 : 신동면   12179 ----------


 ---------- 2014-08-30 22:00:00 : 석사동   12180 ----------


 ---------- 2014-08-31 01:00:00 : 후평1동   12182 ----------


 ---------- 2014-08-31 01:00:00 : 퇴계동   12183 ----------


 ---------- 2014-08-31 08:00:00 : 석사동   12184 ----------


 ---------- 2014-08-31 09:00:00 : 신북읍   12185 ----------


 ---------- 2014-08-31 10:00:00 : 석사동   12186 ----------


 ---------- 2014-08-31 11:00:00 : 강남동   12187 ----------


 ---------- 2014-08-31 12:00:00 : 석사동   12188 ----------


 ---------- 2014-08-31 14:00:00 : 석사동   12189 ----------


 ---------- 2014-08-31 15:00:00 : 석사동   12190 ----------


 ---------- 2014-08-31 17:00:00 : 남산면   12191 ----------


 ---------- 2014-08-31 21:00:00 : 서  면   12192 ----------


 ---------- 2014-09-01 07:00:00 : 강남동   12193 ----------


 ---------- 2014-09-01 08:00:00 : 신동면   12194 ----------


 ---------- 2014-09-01 09:00:00 : 효자1동   12195 ----------


 ---------- 2014-09-01 10:00:00 : 동내면   12197 ----------


 ---------- 2014-09-01 11:00:00 : 강남동   12198 ----------


 ---------- 2014-09-01 11:00:00 : 서  면   12199 ----------


 ---------- 2014-09-01 11:00:00 : 남산면   12200 ----------


 ---------- 2014-09-01 13:00:00 : 신사우동   12201 ----------


 ---------- 2014-09-01 13:00:00 : 조운동   12202 ----------


 ---------- 2014-09-01 14:00:00 : 소양동   12203 ----------


 ---------- 2014-09-01 16:00:00 : 소양동   12204 ----------


 ---------- 2014-09-01 16:00:00 : 동  면   12205 ----------


 ---------- 2014-09-01 17:00:00 : 동  면   12206 ----------


 ---------- 2014-09-01 17:00:00 : 퇴계동   12207 ----------


 ---------- 2014-09-02 07:00:00 : 신사우동   12209 ----------


 ---------- 2014-09-02 08:00:00 : 강남동   12210 ----------


 ---------- 2014-09-02 08:00:00 : 사북면   12211 ----------


 ---------- 2014-09-02 09:00:00 : 동  면   12212 ----------


 ---------- 2014-09-02 10:00:00 : 남  면   12214 ----------


 ---------- 2014-09-02 11:00:00 : 동내면   12216 ----------


 ---------- 2014-09-02 11:00:00 : 후평1동   12217 ----------


 ---------- 2014-09-02 12:00:00 : 동내면   12218 ----------


 ---------- 2014-09-02 12:00:00 : 남산면   12219 ----------


 ---------- 2014-09-02 12:00:00 : 약사명동   12220 ----------


 ---------- 2014-09-02 13:00:00 : 동산면   12221 ----------


 ---------- 2014-09-02 14:00:00 : 후평1동   12222 ----------


 ---------- 2014-09-02 15:00:00 : 남산면   12224 ----------


 ---------- 2014-09-02 17:00:00 : 퇴계동   12225 ----------


 ---------- 2014-09-02 18:00:00 : 서  면   12226 ----------


 ---------- 2014-09-02 19:00:00 : 약사명동   12227 ----------


 ---------- 2014-09-02 23:00:00 : 효자1동   12228 ----------


 ---------- 2014-09-03 07:00:00 : 서  면   12229 ----------


 ---------- 2014-09-03 08:00:00 : 근화동   12230 ----------


 ---------- 2014-09-03 14:00:00 : 서  면   12231 ----------


 ---------- 2014-09-03 18:00:00 : 서  면   12232 ----------


 ---------- 2014-09-03 23:00:00 : 근화동   12233 ----------


 ---------- 2014-09-04 07:00:00 : 신북읍   12235 ----------


 ---------- 2014-09-04 08:00:00 : 신동면   12237 ----------


 ---------- 2014-09-04 08:00:00 : 퇴계동   12239 ----------


 ---------- 2014-09-04 09:00:00 : 효자1동   12240 ----------


 ---------- 2014-09-04 09:00:00 : 동  면   12241 ----------


 ---------- 2014-09-04 13:00:00 : 동내면   12242 ----------


 ---------- 2014-09-04 13:00:00 : 효자1동   12243 ----------


 ---------- 2014-09-04 14:00:00 : 신북읍   12244 ----------


 ---------- 2014-09-04 15:00:00 : 신사우동   12245 ----------


 ---------- 2014-09-04 16:00:00 : 남산면   12246 ----------


 ---------- 2014-09-04 16:00:00 : 동  면   12247 ----------


 ---------- 2014-09-04 17:00:00 : 강남동   12249 ----------


 ---------- 2014-09-04 17:00:00 : 퇴계동   12250 ----------


 ---------- 2014-09-04 19:00:00 : 약사명동   12251 ----------


 ---------- 2014-09-04 23:00:00 : 효자1동   12252 ----------


 ---------- 2014-09-05 08:00:00 : 신사우동   12253 ----------


 ---------- 2014-09-05 10:00:00 : 남산면   12254 ----------


 ---------- 2014-09-05 13:00:00 : 서  면   12255 ----------


 ---------- 2014-09-05 15:00:00 : 강남동   12256 ----------


 ---------- 2014-09-05 15:00:00 : 동내면   12257 ----------


 ---------- 2014-09-05 18:00:00 : 동내면   12258 ----------


 ---------- 2014-09-05 18:00:00 : 동산면   12259 ----------


 ---------- 2014-09-05 19:00:00 : 후평1동   12260 ----------


 ---------- 2014-09-05 22:00:00 : 강남동   12261 ----------


 ---------- 2014-09-06 10:00:00 : 신사우동   12262 ----------


 ---------- 2014-09-06 12:00:00 : 남산면   12263 ----------


 ---------- 2014-09-06 14:00:00 : 남산면   12264 ----------


 ---------- 2014-09-06 14:00:00 : 신북읍   12265 ----------


 ---------- 2014-09-06 15:00:00 : 신북읍   12266 ----------


 ---------- 2014-09-06 17:00:00 : 후평1동   12267 ----------


 ---------- 2014-09-07 09:00:00 : 퇴계동   12268 ----------


 ---------- 2014-09-07 10:00:00 : 남산면   12269 ----------


 ---------- 2014-09-07 13:00:00 : 남산면   12270 ----------


 ---------- 2014-09-07 15:00:00 : 강남동   12271 ----------


 ---------- 2014-09-07 15:00:00 : 신사우동   12273 ----------


 ---------- 2014-09-07 15:00:00 : 신북읍   12274 ----------


 ---------- 2014-09-07 15:00:00 : 동  면   12275 ----------


 ---------- 2014-09-07 16:00:00 : 사북면   12276 ----------


 ---------- 2014-09-07 16:00:00 : 북산면   12278 ----------


 ---------- 2014-09-07 17:00:00 : 남산면   12279 ----------


 ---------- 2014-09-07 18:00:00 : 동  면   12280 ----------


 ---------- 2014-09-07 19:00:00 : 동  면   12281 ----------

 ---------- 2014-09-08 00:00:00 : 동산면   12283 ----------


 ---------- 2014-09-08 06:00:00 : 동  면   12286 ----------


 ---------- 2014-09-08 07:00:00 : 동  면   12287 ----------


 ---------- 2014-09-08 09:00:00 : 신동면   12288 ----------


 ---------- 2014-09-08 09:00:00 : 서  면   12289 ----------


 ---------- 2014-09-08 11:00:00 : 서  면   12290 ----------


 ---------- 2014-09-08 11:00:00 : 사북면   12292 ----------


 ---------- 2014-09-08 12:00:00 : 신동면   12293 ----------


 ---------- 2014-09-08 12:00:00 : 서  면   12294 ----------


 ---------- 2014-09-08 13:00:00 : 사북면   12295 ----------


 ---------- 2014-09-08 14:00:00 : 신북읍   12296 ----------


 ---------- 2014-09-08 15:00:00 : 남산면   12297 ----------


 ---------- 2014-09-08 15:00:00 : 동  면   12298 ----------


 ---------- 2014-09-08 17:00:00 : 신북읍   12299 ----------


 ---------- 2014-09-08 23:00:00 : 근화동   12301 ----------


 ---------- 2014-09-09 09:00:00 : 서  면   12302 ----------


 ---------- 2014-09-09 09:00:00 : 동내면   12303 ----------


 ---------- 2014-09-09 09:00:00 : 동  면   12305 ----------


 ---------- 2014-09-09 15:00:00 : 남산면   12306 ----------


 ---------- 2014-09-09 15:00:00 : 소양동   12309 ----------


 ---------- 2014-09-09 16:00:00 : 서  면   12310 ----------


 ---------- 2014-09-09 18:00:00 : 동  면   12312 ----------


 ---------- 2014-09-09 19:00:00 : 신동면   12314 ----------


 ---------- 2014-09-10 09:00:00 : 소양동   12316 ----------


 ---------- 2014-09-10 09:00:00 : 동산면   12317 ----------


 ---------- 2014-09-10 10:00:00 : 효자1동   12318 ----------


 ---------- 2014-09-10 16:00:00 : 신북읍   12319 ----------


 ---------- 2014-09-10 21:00:00 : 후평1동   12320 ----------


 ---------- 2014-09-11 09:00:00 : 효자1동   12321 ----------


 ---------- 2014-09-11 10:00:00 : 효자1동   12323 ----------


 ---------- 2014-09-11 11:00:00 : 남  면   12324 ----------


 ---------- 2014-09-11 12:00:00 : 동내면   12325 ----------


 ---------- 2014-09-11 12:00:00 : 퇴계동   12326 ----------


 ---------- 2014-09-11 15:00:00 : 소양동   12327 ----------


 ---------- 2014-09-11 20:00:00 : 서  면   12328 ----------


 ---------- 2014-09-11 21:00:00 : 후평1동   12330 ----------


 ---------- 2014-09-12 08:00:00 : 퇴계동   12331 ----------


 ---------- 2014-09-12 09:00:00 : 석사동   12332 ----------


 ---------- 2014-09-12 09:00:00 : 신동면   12333 ----------


 ---------- 2014-09-12 10:00:00 : 신사우동   12334 ----------


 ---------- 2014-09-12 10:00:00 : 동  면   12335 ----------


 ---------- 2014-09-12 11:00:00 : 서  면   12336 ----------


 ---------- 2014-09-12 12:00:00 : 신동면   12338 ----------


 ---------- 2014-09-12 13:00:00 : 퇴계동   12339 ----------


 ---------- 2014-09-12 14:00:00 : 남산면   12340 ----------


 ---------- 2014-09-12 14:00:00 : 후평1동   12342 ----------


 ---------- 2014-09-12 15:00:00 : 신북읍   12344 ----------


 ---------- 2014-09-12 16:00:00 : 교  동   12345 ----------


 ---------- 2014-09-12 17:00:00 : 후평1동   12346 ----------


 ---------- 2014-09-12 18:00:00 : 동산면   12347 ----------


 ---------- 2014-09-12 19:00:00 : 근화동   12348 ----------


 ---------- 2014-09-13 10:00:00 : 서  면   12349 ----------


 ---------- 2014-09-13 12:00:00 : 남산면   12350 ----------


 ---------- 2014-09-13 14:00:00 : 서  면   12353 ----------


 ---------- 2014-09-13 15:00:00 : 근화동   12354 ----------


 ---------- 2014-09-13 15:00:00 : 신사우동   12355 ----------


 ---------- 2014-09-13 18:00:00 : 신동면   12356 ----------


 ---------- 2014-09-13 21:00:00 : 퇴계동   12357 ----------


 ---------- 2014-09-14 00:00:00 : 후평1동   12358 ----------


 ---------- 2014-09-14 09:00:00 : 동  면   12359 ----------


 ---------- 2014-09-14 10:00:00 : 강남동   12360 ----------


 ---------- 2014-09-14 10:00:00 : 서  면   12361 ----------


 ---------- 2014-09-14 14:00:00 : 동내면   12364 ----------


 ---------- 2014-09-14 14:00:00 : 북산면   12365 ----------


 ---------- 2014-09-14 16:00:00 : 석사동   12366 ----------


 ---------- 2014-09-14 16:00:00 : 소양동   12367 ----------


 ---------- 2014-09-14 16:00:00 : 퇴계동   12368 ----------


 ---------- 2014-09-14 19:00:00 : 동내면   12370 ----------


 ---------- 2014-09-15 09:00:00 : 신동면   12371 ----------


 ---------- 2014-09-15 09:00:00 : 신사우동   12372 ----------


 ---------- 2014-09-15 10:00:00 : 약사명동   12373 ----------


 ---------- 2014-09-15 11:00:00 : 강남동   12374 ----------


 ---------- 2014-09-15 11:00:00 : 동내면   12375 ----------


 ---------- 2014-09-15 12:00:00 : 남산면   12376 ----------


 ---------- 2014-09-15 14:00:00 : 신북읍   12377 ----------


 ---------- 2014-09-15 14:00:00 : 퇴계동   12378 ----------


 ---------- 2014-09-15 15:00:00 : 후평1동   12379 ----------


 ---------- 2014-09-15 16:00:00 : 강남동   12380 ----------


 ---------- 2014-09-15 19:00:00 : 후평1동   12381 ----------


 ---------- 2014-09-15 21:00:00 : 동  면   12382 ----------


 ---------- 2014-09-15 23:00:00 : 후평1동   12383 ----------


 ---------- 2014-09-16 09:00:00 : 동내면   12386 ----------


 ---------- 2014-09-16 09:00:00 : 남산면   12387 ----------


 ---------- 2014-09-16 10:00:00 : 서  면   12388 ----------


 ---------- 2014-09-16 11:00:00 : 신사우동   12390 ----------


 ---------- 2014-09-16 13:00:00 : 남산면   12391 ----------


 ---------- 2014-09-16 20:00:00 : 소양동   12392 ----------


 ---------- 2014-09-17 09:00:00 : 신북읍   12393 ----------


 ---------- 2014-09-17 13:00:00 : 후평1동   12394 ----------


 ---------- 2014-09-17 14:00:00 : 퇴계동   12395 ----------


 ---------- 2014-09-17 20:00:00 : 퇴계동   12396 ----------


 ---------- 2014-09-17 23:00:00 : 강남동   12397 ----------


 ---------- 2014-09-18 07:00:00 : 근화동   12398 ----------


 ---------- 2014-09-18 07:00:00 : 신사우동   12399 ----------


 ---------- 2014-09-18 10:00:00 : 근화동   12400 ----------


 ---------- 2014-09-18 10:00:00 : 동산면   12401 ----------


 ---------- 2014-09-18 12:00:00 : 신사우동   12402 ----------


 ---------- 2014-09-18 15:00:00 : 소양동   12403 ----------


 ---------- 2014-09-18 16:00:00 : 동  면   12404 ----------


 ---------- 2014-09-18 23:00:00 : 근화동   12405 ----------


 ---------- 2014-09-19 07:00:00 : 소양동   12406 ----------


 ---------- 2014-09-19 09:00:00 : 퇴계동   12407 ----------


 ---------- 2014-09-19 16:00:00 : 동내면   12408 ----------


 ---------- 2014-09-19 17:00:00 : 서  면   12409 ----------


 ---------- 2014-09-19 18:00:00 : 신사우동   12410 ----------


 ---------- 2014-09-19 19:00:00 : 효자1동   12411 ----------


 ---------- 2014-09-19 23:00:00 : 효자1동   12412 ----------


 ---------- 2014-09-20 01:00:00 : 퇴계동   12414 ----------


 ---------- 2014-09-20 05:00:00 : 동산면   12417 ----------


 ---------- 2014-09-20 09:00:00 : 석사동   12418 ----------


 ---------- 2014-09-20 09:00:00 : 서  면   12419 ----------


 ---------- 2014-09-20 09:00:00 : 동내면   12420 ----------


 ---------- 2014-09-20 09:00:00 : 효자1동   12421 ----------


 ---------- 2014-09-20 10:00:00 : 소양동   12422 ----------


 ---------- 2014-09-20 12:00:00 : 서  면   12423 ----------


 ---------- 2014-09-20 14:00:00 : 사북면   12424 ----------


 ---------- 2014-09-21 01:00:00 : 약사명동   12425 ----------


 ---------- 2014-09-21 02:00:00 : 교  동   12426 ----------


 ---------- 2014-09-21 09:00:00 : 후평1동   12427 ----------


 ---------- 2014-09-21 12:00:00 : 강남동   12428 ----------


 ---------- 2014-09-21 15:00:00 : 남  면   12429 ----------


 ---------- 2014-09-21 15:00:00 : 신북읍   12430 ----------


 ---------- 2014-09-21 18:00:00 : 신북읍   12431 ----------


 ---------- 2014-09-21 19:00:00 : 퇴계동   12432 ----------


 ---------- 2014-09-22 08:00:00 : 강남동   12433 ----------


 ---------- 2014-09-22 11:00:00 : 남산면   12434 ----------


 ---------- 2014-09-22 12:00:00 : 후평1동   12435 ----------


 ---------- 2014-09-22 13:00:00 : 신사우동   12436 ----------


 ---------- 2014-09-22 13:00:00 : 동  면   12437 ----------


 ---------- 2014-09-22 14:00:00 : 근화동   12438 ----------


 ---------- 2014-09-22 16:00:00 : 서  면   12439 ----------


 ---------- 2014-09-22 16:00:00 : 사북면   12440 ----------


 ---------- 2014-09-23 07:00:00 : 효자1동   12441 ----------


 ---------- 2014-09-23 08:00:00 : 후평1동   12442 ----------


 ---------- 2014-09-23 09:00:00 : 사북면   12443 ----------


 ---------- 2014-09-23 09:00:00 : 동내면   12444 ----------


 ---------- 2014-09-23 09:00:00 : 소양동   12445 ----------

 ---------- 2014-09-23 09:00:00 : 퇴계동   12446 ----------


 ---------- 2014-09-23 10:00:00 : 신사우동   12447 ----------


 ---------- 2014-09-23 13:00:00 : 석사동   12448 ----------


 ---------- 2014-09-23 13:00:00 : 효자1동   12449 ----------


 ---------- 2014-09-23 13:00:00 : 소양동   12450 ----------


 ---------- 2014-09-23 13:00:00 : 퇴계동   12452 ----------


 ---------- 2014-09-23 14:00:00 : 서  면   12453 ----------


 ---------- 2014-09-23 14:00:00 : 효자1동   12454 ----------


 ---------- 2014-09-23 16:00:00 : 퇴계동   12456 ----------


 ---------- 2014-09-23 17:00:00 : 효자1동   12457 ----------


 ---------- 2014-09-23 23:00:00 : 석사동   12459 ----------


 ---------- 2014-09-24 02:00:00 : 효자1동   12460 ----------


 ---------- 2014-09-24 09:00:00 : 신동면   12462 ----------


 ---------- 2014-09-24 10:00:00 : 강남동   12463 ----------


 ---------- 2014-09-24 16:00:00 : 후평1동   12464 ----------


 ---------- 2014-09-24 19:00:00 : 소양동   12466 ----------


 ---------- 2014-09-24 22:00:00 : 효자1동   12467 ----------


 ---------- 2014-09-25 12:00:00 : 퇴계동   12468 ----------


 ---------- 2014-09-25 14:00:00 : 남산면   12470 ----------


 ---------- 2014-09-25 15:00:00 : 남산면   12471 ----------


 ---------- 2014-09-25 17:00:00 : 서  면   12472 ----------


 ---------- 2014-09-26 08:00:00 : 후평1동   12474 ----------


 ---------- 2014-09-26 13:00:00 : 신사우동   12477 ----------


 ---------- 2014-09-26 14:00:00 : 신사우동   12478 ----------


 ---------- 2014-09-26 14:00:00 : 후평1동   12480 ----------


 ---------- 2014-09-26 16:00:00 : 동  면   12482 ----------


 ---------- 2014-09-27 12:00:00 : 강남동   12484 ----------


 ---------- 2014-09-27 15:00:00 : 서  면   12486 ----------


 ---------- 2014-09-27 15:00:00 : 근화동   12489 ----------


 ---------- 2014-09-27 18:00:00 : 강남동   12492 ----------


 ---------- 2014-09-27 18:00:00 : 후평1동   12494 ----------


 ---------- 2014-09-28 01:00:00 : 퇴계동   12496 ----------


 ---------- 2014-09-28 15:00:00 : 남산면   12497 ----------


 ---------- 2014-09-28 16:00:00 : 신북읍   12499 ----------


 ---------- 2014-09-28 17:00:00 : 서  면   12501 ----------


 ---------- 2014-09-28 17:00:00 : 신북읍   12503 ----------


 ---------- 2014-09-28 17:00:00 : 후평1동   12505 ----------


 ---------- 2014-09-28 18:00:00 : 신북읍   12506 ----------


 ---------- 2014-09-28 19:00:00 : 후평1동   12507 ----------


 ---------- 2014-09-29 09:00:00 : 동산면   12509 ----------


 ---------- 2014-09-29 19:00:00 : 신동면   12511 ----------


 ---------- 2014-09-29 19:00:00 : 소양동   12512 ----------


 ---------- 2014-09-30 09:00:00 : 남산면   12513 ----------


 ---------- 2014-09-30 09:00:00 : 신사우동   12515 ----------


 ---------- 2014-09-30 12:00:00 : 서  면   12516 ----------


 ---------- 2014-09-30 14:00:00 : 근화동   12517 ----------


 ---------- 2014-09-30 15:00:00 : 퇴계동   12518 ----------


 ---------- 2014-10-01 06:00:00 : 효자1동   12519 ----------


 ---------- 2014-10-01 08:00:00 : 퇴계동   12520 ----------


 ---------- 2014-10-01 11:00:00 : 석사동   12524 ----------


 ---------- 2014-10-01 13:00:00 : 퇴계동   12525 ----------


 ---------- 2014-10-01 18:00:00 : 후평1동   12526 ----------


 ---------- 2014-10-02 01:00:00 : 후평1동   12527 ----------


 ---------- 2014-10-02 07:00:00 : 동  면   12528 ----------


 ---------- 2014-10-02 11:00:00 : 남산면   12529 ----------


 ---------- 2014-10-02 22:00:00 : 석사동   12530 ----------


 ---------- 2014-10-03 07:00:00 : 석사동   12531 ----------


 ---------- 2014-10-03 09:00:00 : 남산면   12532 ----------


 ---------- 2014-10-03 10:00:00 : 강남동   12533 ----------


 ---------- 2014-10-03 13:00:00 : 석사동   12534 ----------


 ---------- 2014-10-03 14:00:00 : 강남동   12535 ----------


 ---------- 2014-10-03 16:00:00 : 동내면   12536 ----------


 ---------- 2014-10-03 18:00:00 : 남산면   12537 ----------


 ---------- 2014-10-04 02:00:00 : 소양동   12538 ----------


 ---------- 2014-10-04 08:00:00 : 퇴계동   12540 ----------


 ---------- 2014-10-04 11:00:00 : 강남동   12542 ----------


 ---------- 2014-10-04 12:00:00 : 서  면   12543 ----------


 ---------- 2014-10-04 12:00:00 : 남산면   12545 ----------


 ---------- 2014-10-04 13:00:00 : 강남동   12546 ----------


 ---------- 2014-10-04 19:00:00 : 효자1동   12547 ----------


 ---------- 2014-10-04 23:00:00 : 후평1동   12549 ----------


 ---------- 2014-10-05 00:00:00 : 효자1동   12552 ----------


 ---------- 2014-10-05 06:00:00 : 신사우동   12554 ----------


 ---------- 2014-10-05 08:00:00 : 동  면   12555 ----------


 ---------- 2014-10-05 09:00:00 : 강남동   12556 ----------


 ---------- 2014-10-05 11:00:00 : 동  면   12557 ----------


 ---------- 2014-10-05 11:00:00 : 동산면   12558 ----------


 ---------- 2014-10-06 04:00:00 : 남산면   12559 ----------


 ---------- 2014-10-06 08:00:00 : 효자1동   12560 ----------


 ---------- 2014-10-06 10:00:00 : 동  면   12561 ----------


 ---------- 2014-10-06 12:00:00 : 동  면   12562 ----------


 ---------- 2014-10-07 01:00:00 : 후평1동   12564 ----------


 ---------- 2014-10-07 08:00:00 : 신북읍   12565 ----------


 ---------- 2014-10-07 09:00:00 : 석사동   12571 ----------


 ---------- 2014-10-07 10:00:00 : 남산면   12572 ----------


 ---------- 2014-10-07 11:00:00 : 남산면   12573 ----------


 ---------- 2014-10-07 12:00:00 : 강남동   12575 ----------


 ---------- 2014-10-07 14:00:00 : 효자1동   12576 ----------


 ---------- 2014-10-07 14:00:00 : 남산면   12577 ----------


 ---------- 2014-10-07 23:00:00 : 효자1동   12578 ----------


 ---------- 2014-10-08 16:00:00 : 효자1동   12579 ----------


 ---------- 2014-10-08 20:00:00 : 후평1동   12582 ----------


 ---------- 2014-10-08 21:00:00 : 소양동   12583 ----------


 ---------- 2014-10-09 13:00:00 : 남산면   12584 ----------


 ---------- 2014-10-09 13:00:00 : 동  면   12586 ----------


 ---------- 2014-10-09 14:00:00 : 강남동   12588 ----------


 ---------- 2014-10-09 14:00:00 : 서  면   12591 ----------


 ---------- 2014-10-09 14:00:00 : 사북면   12592 ----------


 ---------- 2014-10-09 14:00:00 : 조운동   12593 ----------


 ---------- 2014-10-09 15:00:00 : 동내면   12594 ----------


 ---------- 2014-10-09 15:00:00 : 근화동   12596 ----------


 ---------- 2014-10-10 09:00:00 : 강남동   12597 ----------


 ---------- 2014-10-10 09:00:00 : 동  면   12598 ----------


 ---------- 2014-10-10 09:00:00 : 후평1동   12599 ----------


 ---------- 2014-10-10 11:00:00 : 서  면   12600 ----------


 ---------- 2014-10-10 12:00:00 : 서  면   12603 ----------


 ---------- 2014-10-10 13:00:00 : 동  면   12605 ----------


 ---------- 2014-10-10 14:00:00 : 강남동   12606 ----------


 ---------- 2014-10-10 17:00:00 : 동내면   12607 ----------


 ---------- 2014-10-10 18:00:00 : 퇴계동   12608 ----------


 ---------- 2014-10-11 01:00:00 : 조운동   12609 ----------


 ---------- 2014-10-11 06:00:00 : 동  면   12610 ----------


 ---------- 2014-10-11 09:00:00 : 석사동   12612 ----------


 ---------- 2014-10-11 10:00:00 : 동내면   12613 ----------


 ---------- 2014-10-11 10:00:00 : 신사우동   12614 ----------


 ---------- 2014-10-11 10:00:00 : 퇴계동   12616 ----------


 ---------- 2014-10-11 11:00:00 : 동내면   12617 ----------


 ---------- 2014-10-11 13:00:00 : 남산면   12618 ----------


 ---------- 2014-10-11 13:00:00 : 근화동   12619 ----------


 ---------- 2014-10-11 13:00:00 : 동  면   12620 ----------


 ---------- 2014-10-11 14:00:00 : 신사우동   12622 ----------


 ---------- 2014-10-11 15:00:00 : 서  면   12623 ----------


 ---------- 2014-10-11 20:00:00 : 퇴계동   12624 ----------


 ---------- 2014-10-11 22:00:00 : 퇴계동   12625 ----------


 ---------- 2014-10-12 08:00:00 : 소양동   12626 ----------


 ---------- 2014-10-12 09:00:00 : 약사명동   12627 ----------


 ---------- 2014-10-12 09:00:00 : 후평1동   12629 ----------


 ---------- 2014-10-12 11:00:00 : 동내면   12630 ----------


 ---------- 2014-10-12 11:00:00 : 소양동   12631 ----------


 ---------- 2014-10-12 12:00:00 : 서  면   12632 ----------


 ---------- 2014-10-12 13:00:00 : 강남동   12633 ----------


 ---------- 2014-10-12 13:00:00 : 동산면   12634 ----------


 ---------- 2014-10-12 14:00:00 : 신사우동   12635 ----------


 ---------- 2014-10-12 16:00:00 : 석사동   12637 ----------


 ---------- 2014-10-12 16:00:00 : 동내면   12638 ----------


 ---------- 2014-10-12 19:00:00 : 서  면   12640 ----------

 ---------- 2014-10-12 21:00:00 : 퇴계동   12641 ----------


 ---------- 2014-10-13 01:00:00 : 후평1동   12642 ----------


 ---------- 2014-10-13 11:00:00 : 소양동   12643 ----------


 ---------- 2014-10-13 11:00:00 : 동  면   12644 ----------


 ---------- 2014-10-13 12:00:00 : 강남동   12645 ----------


 ---------- 2014-10-13 13:00:00 : 퇴계동   12647 ----------


 ---------- 2014-10-13 16:00:00 : 후평1동   12648 ----------


 ---------- 2014-10-13 18:00:00 : 근화동   12649 ----------


 ---------- 2014-10-13 20:00:00 : 강남동   12650 ----------


 ---------- 2014-10-14 09:00:00 : 퇴계동   12651 ----------


 ---------- 2014-10-14 15:00:00 : 동내면   12652 ----------


 ---------- 2014-10-14 18:00:00 : 서  면   12653 ----------


 ---------- 2014-10-15 13:00:00 : 석사동   12654 ----------


 ---------- 2014-10-15 16:00:00 : 동산면   12655 ----------


 ---------- 2014-10-15 17:00:00 : 소양동   12656 ----------


 ---------- 2014-10-15 23:00:00 : 근화동   12657 ----------


 ---------- 2014-10-16 16:00:00 : 서  면   12659 ----------


 ---------- 2014-10-16 16:00:00 : 동내면   12660 ----------


 ---------- 2014-10-16 21:00:00 : 동내면   12661 ----------


 ---------- 2014-10-16 23:00:00 : 서  면   12662 ----------


 ---------- 2014-10-17 02:00:00 : 남산면   12664 ----------


 ---------- 2014-10-17 13:00:00 : 신북읍   12665 ----------


 ---------- 2014-10-17 14:00:00 : 후평1동   12666 ----------


 ---------- 2014-10-17 19:00:00 : 동내면   12671 ----------


 ---------- 2014-10-18 09:00:00 : 서  면   12672 ----------


 ---------- 2014-10-18 10:00:00 : 신북읍   12675 ----------


 ---------- 2014-10-18 11:00:00 : 남산면   12676 ----------


 ---------- 2014-10-18 12:00:00 : 석사동   12677 ----------


 ---------- 2014-10-18 12:00:00 : 동내면   12678 ----------


 ---------- 2014-10-18 15:00:00 : 서  면   12679 ----------


 ---------- 2014-10-18 16:00:00 : 소양동   12680 ----------


 ---------- 2014-10-18 18:00:00 : 사북면   12682 ----------


 ---------- 2014-10-19 00:00:00 : 후평1동   12684 ----------


 ---------- 2014-10-19 03:00:00 : 후평1동   12686 ----------


 ---------- 2014-10-19 11:00:00 : 강남동   12687 ----------


 ---------- 2014-10-19 12:00:00 : 남산면   12689 ----------


 ---------- 2014-10-19 15:00:00 : 서  면   12690 ----------


 ---------- 2014-10-19 15:00:00 : 효자1동   12691 ----------


 ---------- 2014-10-19 15:00:00 : 동  면   12692 ----------


 ---------- 2014-10-19 17:00:00 : 조운동   12693 ----------


 ---------- 2014-10-19 18:00:00 : 동산면   12694 ----------


 ---------- 2014-10-19 22:00:00 : 후평1동   12696 ----------


 ---------- 2014-10-20 04:00:00 : 신사우동   12697 ----------


 ---------- 2014-10-20 11:00:00 : 후평1동   12698 ----------


 ---------- 2014-10-20 14:00:00 : 동내면   12699 ----------


 ---------- 2014-10-20 14:00:00 : 신사우동   12701 ----------


 ---------- 2014-10-20 17:00:00 : 동내면   12702 ----------


 ---------- 2014-10-20 17:00:00 : 동산면   12703 ----------


 ---------- 2014-10-20 18:00:00 : 효자1동   12704 ----------


 ---------- 2014-10-21 10:00:00 : 효자1동   12705 ----------


 ---------- 2014-10-21 18:00:00 : 동내면   12707 ----------


 ---------- 2014-10-21 22:00:00 : 강남동   12708 ----------


 ---------- 2014-10-22 05:00:00 : 퇴계동   12709 ----------


 ---------- 2014-10-22 14:00:00 : 북산면   12711 ----------


 ---------- 2014-10-22 15:00:00 : 강남동   12712 ----------


 ---------- 2014-10-22 16:00:00 : 동  면   12713 ----------


 ---------- 2014-10-22 21:00:00 : 남산면   12715 ----------


 ---------- 2014-10-23 13:00:00 : 효자1동   12716 ----------


 ---------- 2014-10-23 13:00:00 : 조운동   12717 ----------


 ---------- 2014-10-23 14:00:00 : 효자1동   12719 ----------


 ---------- 2014-10-23 23:00:00 : 서  면   12720 ----------


 ---------- 2014-10-24 01:00:00 : 효자1동   12721 ----------


 ---------- 2014-10-24 12:00:00 : 동내면   12722 ----------


 ---------- 2014-10-24 17:00:00 : 북산면   12726 ----------


 ---------- 2014-10-24 21:00:00 : 후평1동   12728 ----------


 ---------- 2014-10-25 06:00:00 : 퇴계동   12729 ----------


 ---------- 2014-10-25 09:00:00 : 효자1동   12733 ----------


 ---------- 2014-10-25 13:00:00 : 강남동   12734 ----------


 ---------- 2014-10-25 13:00:00 : 퇴계동   12735 ----------


 ---------- 2014-10-25 14:00:00 : 동내면   12736 ----------


 ---------- 2014-10-25 15:00:00 : 퇴계동   12737 ----------


 ---------- 2014-10-25 19:00:00 : 효자1동   12738 ----------


 ---------- 2014-10-25 19:00:00 : 후평1동   12739 ----------


 ---------- 2014-10-26 00:00:00 : 사북면   12741 ----------


 ---------- 2014-10-26 02:00:00 : 효자1동   12742 ----------


 ---------- 2014-10-26 02:00:00 : 신북읍   12743 ----------


 ---------- 2014-10-26 04:00:00 : 신북읍   12744 ----------


 ---------- 2014-10-26 07:00:00 : 서  면   12746 ----------


 ---------- 2014-10-26 10:00:00 : 신북읍   12747 ----------


 ---------- 2014-10-26 11:00:00 : 퇴계동   12749 ----------


 ---------- 2014-10-26 12:00:00 : 소양동   12750 ----------


 ---------- 2014-10-26 15:00:00 : 남산면   12751 ----------


 ---------- 2014-10-26 16:00:00 : 남산면   12752 ----------


 ---------- 2014-10-26 20:00:00 : 동내면   12753 ----------


 ---------- 2014-10-27 09:00:00 : 서  면   12754 ----------


 ---------- 2014-10-27 09:00:00 : 효자1동   12755 ----------


 ---------- 2014-10-27 10:00:00 : 후평1동   12756 ----------


 ---------- 2014-10-27 11:00:00 : 석사동   12757 ----------


 ---------- 2014-10-27 12:00:00 : 효자1동   12758 ----------


 ---------- 2014-10-27 13:00:00 : 신북읍   12759 ----------


 ---------- 2014-10-27 13:00:00 : 동산면   12760 ----------


 ---------- 2014-10-27 17:00:00 : 동내면   12761 ----------


 ---------- 2014-10-27 19:00:00 : 동내면   12762 ----------


 ---------- 2014-10-27 21:00:00 : 소양동   12763 ----------


 ---------- 2014-10-27 22:00:00 : 석사동   12765 ----------


 ---------- 2014-10-28 08:00:00 : 퇴계동   12766 ----------


 ---------- 2014-10-28 11:00:00 : 퇴계동   12768 ----------


 ---------- 2014-10-28 18:00:00 : 근화동   12769 ----------


 ---------- 2014-10-28 22:00:00 : 강남동   12770 ----------


 ---------- 2014-10-28 23:00:00 : 남산면   12771 ----------


 ---------- 2014-10-29 01:00:00 : 석사동   12772 ----------


 ---------- 2014-10-29 03:00:00 : 석사동   12773 ----------


 ---------- 2014-10-29 08:00:00 : 근화동   12774 ----------


 ---------- 2014-10-29 10:00:00 : 효자1동   12775 ----------


 ---------- 2014-10-29 11:00:00 : 사북면   12777 ----------


 ---------- 2014-10-29 16:00:00 : 퇴계동   12778 ----------


 ---------- 2014-10-29 18:00:00 : 효자1동   12779 ----------


 ---------- 2014-10-30 07:00:00 : 효자1동   12780 ----------


 ---------- 2014-10-30 19:00:00 : 후평1동   12781 ----------


 ---------- 2014-10-30 20:00:00 : 강남동   12782 ----------


 ---------- 2014-10-30 20:00:00 : 효자1동   12783 ----------


 ---------- 2014-10-31 01:00:00 : 조운동   12784 ----------


 ---------- 2014-10-31 10:00:00 : 신동면   12785 ----------


 ---------- 2014-10-31 12:00:00 : 신사우동   12786 ----------


 ---------- 2014-10-31 13:00:00 : 동내면   12787 ----------


 ---------- 2014-10-31 13:00:00 : 신사우동   12789 ----------


 ---------- 2014-10-31 20:00:00 : 후평1동   12790 ----------


 ---------- 2014-11-01 00:00:00 : 석사동   12792 ----------


 ---------- 2014-11-01 07:00:00 : 서  면   12793 ----------


 ---------- 2014-11-01 15:00:00 : 신사우동   12794 ----------


 ---------- 2014-11-02 14:00:00 : 서  면   12795 ----------


 ---------- 2014-11-02 17:00:00 : 동산면   12796 ----------


 ---------- 2014-11-03 09:00:00 : 효자1동   12797 ----------


 ---------- 2014-11-03 16:00:00 : 서  면   12798 ----------


 ---------- 2014-11-03 20:00:00 : 신북읍   12799 ----------


 ---------- 2014-11-04 00:00:00 : 약사명동   12800 ----------


 ---------- 2014-11-04 05:00:00 : 사북면   12801 ----------


 ---------- 2014-11-04 08:00:00 : 신사우동   12803 ----------


 ---------- 2014-11-04 09:00:00 : 신북읍   12804 ----------


 ---------- 2014-11-04 12:00:00 : 소양동   12805 ----------


 ---------- 2014-11-04 15:00:00 : 동  면   12806 ----------


 ---------- 2014-11-05 03:00:00 : 강남동   12807 ----------


 ---------- 2014-11-05 03:00:00 : 소양동   12808 ----------


 ---------- 2014-11-05 11:00:00 : 후평1동   12809 ----------


 ---------- 2014-11-05 11:00:00 : 퇴계동   12810 ----------


 ---------- 2014-11-05 12:00:00 : 후평1동   12811 ----------

 ---------- 2014-11-05 15:00:00 : 서  면   12812 ----------


 ---------- 2014-11-05 18:00:00 : 신사우동   12815 ----------


 ---------- 2014-11-05 20:00:00 : 동  면   12816 ----------


 ---------- 2014-11-06 00:00:00 : 신북읍   12817 ----------


 ---------- 2014-11-06 01:00:00 : 후평1동   12819 ----------


 ---------- 2014-11-06 11:00:00 : 퇴계동   12821 ----------


 ---------- 2014-11-06 15:00:00 : 근화동   12822 ----------


 ---------- 2014-11-07 00:00:00 : 후평1동   12823 ----------


 ---------- 2014-11-07 08:00:00 : 신사우동   12824 ----------


 ---------- 2014-11-07 09:00:00 : 신북읍   12825 ----------


 ---------- 2014-11-07 18:00:00 : 후평1동   12826 ----------


 ---------- 2014-11-08 06:00:00 : 신동면   12827 ----------


 ---------- 2014-11-08 16:00:00 : 강남동   12828 ----------


 ---------- 2014-11-08 19:00:00 : 소양동   12830 ----------


 ---------- 2014-11-08 20:00:00 : 석사동   12831 ----------


 ---------- 2014-11-08 20:00:00 : 효자1동   12832 ----------


 ---------- 2014-11-09 05:00:00 : 신북읍   12834 ----------


 ---------- 2014-11-09 05:00:00 : 동산면   12836 ----------


 ---------- 2014-11-09 06:00:00 : 석사동   12837 ----------


 ---------- 2014-11-09 10:00:00 : 북산면   12839 ----------


 ---------- 2014-11-09 11:00:00 : 서  면   12840 ----------


 ---------- 2014-11-09 14:00:00 : 남  면   12841 ----------


 ---------- 2014-11-10 01:00:00 : 남산면   12842 ----------


 ---------- 2014-11-10 04:00:00 : 남산면   12844 ----------


 ---------- 2014-11-10 13:00:00 : 신북읍   12846 ----------


 ---------- 2014-11-10 14:00:00 : 동내면   12847 ----------


 ---------- 2014-11-10 14:00:00 : 신사우동   12848 ----------


 ---------- 2014-11-10 15:00:00 : 신북읍   12849 ----------


 ---------- 2014-11-10 17:00:00 : 강남동   12850 ----------


 ---------- 2014-11-11 09:00:00 : 신동면   12851 ----------


 ---------- 2014-11-11 13:00:00 : 서  면   12852 ----------


 ---------- 2014-11-11 13:00:00 : 효자1동   12853 ----------


 ---------- 2014-11-11 20:00:00 : 약사명동   12856 ----------


 ---------- 2014-11-12 12:00:00 : 후평1동   12858 ----------


 ---------- 2014-11-12 19:00:00 : 서  면   12859 ----------


 ---------- 2014-11-12 19:00:00 : 남산면   12860 ----------


 ---------- 2014-11-12 20:00:00 : 퇴계동   12862 ----------


 ---------- 2014-11-13 00:00:00 : 효자1동   12863 ----------


 ---------- 2014-11-13 06:00:00 : 동내면   12864 ----------


 ---------- 2014-11-13 09:00:00 : 후평1동   12865 ----------


 ---------- 2014-11-13 12:00:00 : 석사동   12866 ----------


 ---------- 2014-11-13 12:00:00 : 남산면   12867 ----------


 ---------- 2014-11-13 13:00:00 : 남산면   12868 ----------


 ---------- 2014-11-13 18:00:00 : 남산면   12869 ----------


 ---------- 2014-11-14 00:00:00 : 석사동   12870 ----------


 ---------- 2014-11-14 00:00:00 : 효자1동   12871 ----------


 ---------- 2014-11-14 02:00:00 : 소양동   12872 ----------


 ---------- 2014-11-14 02:00:00 : 후평1동   12873 ----------


 ---------- 2014-11-14 03:00:00 : 신북읍   12874 ----------


 ---------- 2014-11-14 12:00:00 : 퇴계동   12876 ----------


 ---------- 2014-11-14 12:00:00 : 북산면   12878 ----------


 ---------- 2014-11-14 15:00:00 : 석사동   12880 ----------


 ---------- 2014-11-14 16:00:00 : 효자1동   12882 ----------


 ---------- 2014-11-15 11:00:00 : 동  면   12883 ----------


 ---------- 2014-11-15 13:00:00 : 소양동   12884 ----------


 ---------- 2014-11-15 13:00:00 : 후평1동   12886 ----------


 ---------- 2014-11-15 14:00:00 : 강남동   12888 ----------


 ---------- 2014-11-15 15:00:00 : 서  면   12890 ----------


 ---------- 2014-11-15 16:00:00 : 효자1동   12891 ----------


 ---------- 2014-11-16 00:00:00 : 후평1동   12893 ----------


 ---------- 2014-11-16 11:00:00 : 석사동   12895 ----------


 ---------- 2014-11-16 15:00:00 : 강남동   12896 ----------


 ---------- 2014-11-16 19:00:00 : 동  면   12899 ----------


 ---------- 2014-11-17 11:00:00 : 근화동   12902 ----------


 ---------- 2014-11-17 17:00:00 : 소양동   12903 ----------


 ---------- 2014-11-17 22:00:00 : 효자1동   12904 ----------


 ---------- 2014-11-18 08:00:00 : 후평1동   12905 ----------


 ---------- 2014-11-18 23:00:00 : 후평1동   12906 ----------


 ---------- 2014-11-19 08:00:00 : 후평1동   12907 ----------


 ---------- 2014-11-19 09:00:00 : 석사동   12909 ----------


 ---------- 2014-11-19 11:00:00 : 남산면   12911 ----------


 ---------- 2014-11-19 15:00:00 : 석사동   12912 ----------


 ---------- 2014-11-19 15:00:00 : 동내면   12913 ----------


 ---------- 2014-11-19 17:00:00 : 소양동   12914 ----------


 ---------- 2014-11-19 18:00:00 : 서  면   12915 ----------


 ---------- 2014-11-19 21:00:00 : 강남동   12916 ----------


 ---------- 2014-11-20 08:00:00 : 신동면   12917 ----------


 ---------- 2014-11-20 09:00:00 : 효자1동   12918 ----------


 ---------- 2014-11-20 16:00:00 : 사북면   12921 ----------


 ---------- 2014-11-20 17:00:00 : 신북읍   12922 ----------


 ---------- 2014-11-21 03:00:00 : 퇴계동   12923 ----------


 ---------- 2014-11-21 10:00:00 : 석사동   12924 ----------


 ---------- 2014-11-21 17:00:00 : 신북읍   12925 ----------


 ---------- 2014-11-21 17:00:00 : 소양동   12926 ----------


 ---------- 2014-11-21 17:00:00 : 동  면   12928 ----------


 ---------- 2014-11-21 21:00:00 : 신동면   12929 ----------


 ---------- 2014-11-22 02:00:00 : 효자1동   12930 ----------


 ---------- 2014-11-22 11:00:00 : 근화동   12931 ----------


 ---------- 2014-11-23 08:00:00 : 동  면   12933 ----------


 ---------- 2014-11-23 08:00:00 : 퇴계동   12934 ----------


 ---------- 2014-11-23 16:00:00 : 신동면   12935 ----------


 ---------- 2014-11-23 16:00:00 : 신사우동   12936 ----------


 ---------- 2014-11-23 17:00:00 : 서  면   12938 ----------


 ---------- 2014-11-23 17:00:00 : 남산면   12939 ----------


 ---------- 2014-11-23 20:00:00 : 서  면   12940 ----------


 ---------- 2014-11-24 08:00:00 : 약사명동   12941 ----------


 ---------- 2014-11-24 18:00:00 : 석사동   12943 ----------


 ---------- 2014-11-24 19:00:00 : 서  면   12944 ----------


 ---------- 2014-11-25 15:00:00 : 조운동   12945 ----------


 ---------- 2014-11-25 18:00:00 : 석사동   12946 ----------


 ---------- 2014-11-25 19:00:00 : 근화동   12947 ----------


 ---------- 2014-11-25 20:00:00 : 근화동   12948 ----------


 ---------- 2014-11-26 06:00:00 : 석사동   12950 ----------


 ---------- 2014-11-26 09:00:00 : 퇴계동   12952 ----------


 ---------- 2014-11-26 23:00:00 : 석사동   12954 ----------


 ---------- 2014-11-27 02:00:00 : 효자1동   12955 ----------


 ---------- 2014-11-27 21:00:00 : 석사동   12956 ----------


 ---------- 2014-11-28 13:00:00 : 조운동   12957 ----------


 ---------- 2014-11-28 20:00:00 : 동  면   12960 ----------


 ---------- 2014-11-28 23:00:00 : 신동면   12963 ----------


 ---------- 2014-11-29 15:00:00 : 석사동   12966 ----------


 ---------- 2014-11-29 21:00:00 : 퇴계동   12967 ----------


 ---------- 2014-11-30 09:00:00 : 서  면   12969 ----------


 ---------- 2014-12-01 00:00:00 : 효자1동   12971 ----------


 ---------- 2014-12-01 13:00:00 : 동내면   12972 ----------


 ---------- 2014-12-01 13:00:00 : 신사우동   12973 ----------


 ---------- 2014-12-01 14:00:00 : 사북면   12974 ----------


 ---------- 2014-12-02 06:00:00 : 효자1동   12975 ----------


 ---------- 2014-12-02 09:00:00 : 강남동   12976 ----------


 ---------- 2014-12-02 11:00:00 : 신사우동   12978 ----------


 ---------- 2014-12-02 16:00:00 : 후평1동   12979 ----------


 ---------- 2014-12-02 18:00:00 : 강남동   12980 ----------


 ---------- 2014-12-02 23:00:00 : 후평1동   12981 ----------


 ---------- 2014-12-03 08:00:00 : 약사명동   12982 ----------


 ---------- 2014-12-03 09:00:00 : 소양동   12985 ----------


 ---------- 2014-12-03 14:00:00 : 동산면   12986 ----------


 ---------- 2014-12-04 17:00:00 : 동내면   12988 ----------


 ---------- 2014-12-04 18:00:00 : 퇴계동   12989 ----------


 ---------- 2014-12-04 19:00:00 : 후평1동   12991 ----------


 ---------- 2014-12-05 13:00:00 : 효자1동   12992 ----------


 ---------- 2014-12-06 01:00:00 : 퇴계동   12993 ----------


 ---------- 2014-12-06 01:00:00 : 북산면   12994 ----------


 ---------- 2014-12-06 07:00:00 : 석사동   12995 ----------


 ---------- 2014-12-06 07:00:00 : 효자1동   12996 ----------


 ---------- 2014-12-06 08:00:00 : 북산면   12998 ----------


 ---------- 2014-12-06 12:00:00 : 효자1동   12999 ----------

 ---------- 2014-12-07 10:00:00 : 강남동   13001 ----------


 ---------- 2014-12-07 10:00:00 : 근화동   13002 ----------


 ---------- 2014-12-07 13:00:00 : 퇴계동   13003 ----------


 ---------- 2014-12-08 01:00:00 : 소양동   13004 ----------


 ---------- 2014-12-08 11:00:00 : 서  면   13005 ----------


 ---------- 2014-12-08 20:00:00 : 후평1동   13007 ----------


 ---------- 2014-12-08 23:00:00 : 퇴계동   13008 ----------


 ---------- 2014-12-09 00:00:00 : 효자1동   13009 ----------


 ---------- 2014-12-09 01:00:00 : 후평1동   13010 ----------


 ---------- 2014-12-09 02:00:00 : 강남동   13011 ----------


 ---------- 2014-12-09 04:00:00 : 후평1동   13012 ----------


 ---------- 2014-12-09 10:00:00 : 석사동   13013 ----------


 ---------- 2014-12-09 17:00:00 : 약사명동   13014 ----------


 ---------- 2014-12-10 09:00:00 : 효자1동   13015 ----------


 ---------- 2014-12-10 09:00:00 : 후평1동   13017 ----------


 ---------- 2014-12-10 14:00:00 : 북산면   13018 ----------


 ---------- 2014-12-11 07:00:00 : 후평1동   13020 ----------


 ---------- 2014-12-11 08:00:00 : 남산면   13022 ----------


 ---------- 2014-12-11 10:00:00 : 강남동   13023 ----------


 ---------- 2014-12-11 15:00:00 : 퇴계동   13024 ----------


 ---------- 2014-12-11 16:00:00 : 효자1동   13026 ----------


 ---------- 2014-12-11 16:00:00 : 후평1동   13027 ----------


 ---------- 2014-12-11 18:00:00 : 효자1동   13028 ----------


 ---------- 2014-12-11 21:00:00 : 석사동   13030 ----------


 ---------- 2014-12-12 13:00:00 : 퇴계동   13031 ----------


 ---------- 2014-12-12 16:00:00 : 근화동   13032 ----------


 ---------- 2014-12-12 17:00:00 : 퇴계동   13033 ----------


 ---------- 2014-12-12 20:00:00 : 교  동   13034 ----------


 ---------- 2014-12-13 10:00:00 : 남산면   13035 ----------


 ---------- 2014-12-13 14:00:00 : 조운동   13036 ----------


 ---------- 2014-12-13 18:00:00 : 동  면   13037 ----------


 ---------- 2014-12-14 00:00:00 : 후평1동   13038 ----------


 ---------- 2014-12-14 09:00:00 : 약사명동   13039 ----------


 ---------- 2014-12-14 11:00:00 : 근화동   13041 ----------


 ---------- 2014-12-14 20:00:00 : 강남동   13042 ----------


 ---------- 2014-12-15 02:00:00 : 퇴계동   13043 ----------


 ---------- 2014-12-15 12:00:00 : 서  면   13044 ----------


 ---------- 2014-12-15 16:00:00 : 동산면   13045 ----------


 ---------- 2014-12-15 18:00:00 : 신북읍   13047 ----------


 ---------- 2014-12-15 22:00:00 : 남산면   13049 ----------


 ---------- 2014-12-16 10:00:00 : 서  면   13051 ----------


 ---------- 2014-12-16 17:00:00 : 교  동   13052 ----------


 ---------- 2014-12-17 00:00:00 : 서  면   13053 ----------


 ---------- 2014-12-17 00:00:00 : 신사우동   13055 ----------


 ---------- 2014-12-17 11:00:00 : 퇴계동   13056 ----------


 ---------- 2014-12-17 17:00:00 : 동  면   13057 ----------


 ---------- 2014-12-18 07:00:00 : 석사동   13059 ----------


 ---------- 2014-12-18 10:00:00 : 퇴계동   13060 ----------


 ---------- 2014-12-18 13:00:00 : 후평1동   13061 ----------


 ---------- 2014-12-18 20:00:00 : 후평1동   13062 ----------


 ---------- 2014-12-18 22:00:00 : 효자1동   13063 ----------


 ---------- 2014-12-18 22:00:00 : 소양동   13064 ----------


 ---------- 2014-12-19 02:00:00 : 퇴계동   13065 ----------


 ---------- 2014-12-19 08:00:00 : 후평1동   13067 ----------


 ---------- 2014-12-19 13:00:00 : 후평1동   13068 ----------


 ---------- 2014-12-19 17:00:00 : 교  동   13069 ----------


 ---------- 2014-12-19 19:00:00 : 효자1동   13070 ----------


 ---------- 2014-12-19 22:00:00 : 석사동   13071 ----------


 ---------- 2014-12-19 23:00:00 : 효자1동   13072 ----------


 ---------- 2014-12-20 02:00:00 : 효자1동   13074 ----------


 ---------- 2014-12-20 08:00:00 : 석사동   13075 ----------


 ---------- 2014-12-20 14:00:00 : 소양동   13076 ----------


 ---------- 2014-12-20 14:00:00 : 약사명동   13077 ----------


 ---------- 2014-12-20 22:00:00 : 석사동   13078 ----------


 ---------- 2014-12-21 03:00:00 : 소양동   13079 ----------


 ---------- 2014-12-21 13:00:00 : 남산면   13080 ----------


 ---------- 2014-12-21 15:00:00 : 후평1동   13081 ----------


 ---------- 2014-12-21 20:00:00 : 동  면   13082 ----------


 ---------- 2014-12-21 22:00:00 : 효자1동   13084 ----------


 ---------- 2014-12-21 22:00:00 : 후평1동   13085 ----------


 ---------- 2014-12-22 11:00:00 : 남산면   13088 ----------


 ---------- 2014-12-22 14:00:00 : 후평1동   13089 ----------


 ---------- 2014-12-22 17:00:00 : 석사동   13090 ----------


 ---------- 2014-12-22 20:00:00 : 동내면   13091 ----------


 ---------- 2014-12-23 17:00:00 : 강남동   13092 ----------


 ---------- 2014-12-23 17:00:00 : 퇴계동   13093 ----------


 ---------- 2014-12-23 23:00:00 : 소양동   13094 ----------


 ---------- 2014-12-24 09:00:00 : 효자1동   13095 ----------


 ---------- 2014-12-24 23:00:00 : 신동면   13096 ----------


 ---------- 2014-12-24 23:00:00 : 강남동   13097 ----------


 ---------- 2014-12-25 00:00:00 : 강남동   13098 ----------


 ---------- 2014-12-25 02:00:00 : 후평1동   13099 ----------


 ---------- 2014-12-25 06:00:00 : 신동면   13100 ----------


 ---------- 2014-12-25 12:00:00 : 남산면   13102 ----------


 ---------- 2014-12-25 18:00:00 : 후평1동   13103 ----------


 ---------- 2014-12-26 13:00:00 : 동내면   13104 ----------


 ---------- 2014-12-26 14:00:00 : 동  면   13105 ----------


 ---------- 2014-12-26 14:00:00 : 후평1동   13107 ----------


 ---------- 2014-12-26 15:00:00 : 후평1동   13109 ----------


 ---------- 2014-12-26 17:00:00 : 동내면   13110 ----------


 ---------- 2014-12-26 17:00:00 : 교  동   13111 ----------


 ---------- 2014-12-27 05:00:00 : 근화동   13112 ----------


 ---------- 2014-12-27 20:00:00 : 퇴계동   13114 ----------


 ---------- 2014-12-27 23:00:00 : 사북면   13116 ----------


 ---------- 2014-12-28 04:00:00 : 효자1동   13117 ----------


 ---------- 2014-12-28 10:00:00 : 퇴계동   13118 ----------


 ---------- 2014-12-28 13:00:00 : 신사우동   13119 ----------


 ---------- 2014-12-28 14:00:00 : 신사우동   13120 ----------


 ---------- 2014-12-28 18:00:00 : 퇴계동   13121 ----------


 ---------- 2014-12-29 00:00:00 : 석사동   13123 ----------


 ---------- 2014-12-29 10:00:00 : 후평1동   13124 ----------


 ---------- 2014-12-29 12:00:00 : 동산면   13126 ----------


 ---------- 2014-12-29 20:00:00 : 신사우동   13128 ----------


 ---------- 2014-12-29 20:00:00 : 퇴계동   13130 ----------


 ---------- 2014-12-30 07:00:00 : 석사동   13131 ----------


 ---------- 2014-12-30 13:00:00 : 동  면   13132 ----------


 ---------- 2014-12-30 14:00:00 : 서  면   13135 ----------


 ---------- 2014-12-31 01:00:00 : 후평1동   13136 ----------


 ---------- 2014-12-31 12:00:00 : 석사동   13137 ----------


 ---------- 2014-12-31 23:00:00 : 후평1동   13138 ----------


 ---------- 2015-01-01 09:00:00 : 효자1동   13139 ----------


 ---------- 2015-01-01 13:00:00 : 석사동   13140 ----------


 ---------- 2015-01-01 17:00:00 : 후평1동   13141 ----------


 ---------- 2015-01-01 18:00:00 : 석사동   13142 ----------


 ---------- 2015-01-02 10:00:00 : 석사동   13143 ----------


 ---------- 2015-01-02 10:00:00 : 후평1동   13144 ----------


 ---------- 2015-01-02 17:00:00 : 석사동   13145 ----------


 ---------- 2015-01-02 18:00:00 : 석사동   13146 ----------


 ---------- 2015-01-02 23:00:00 : 교  동   13147 ----------


 ---------- 2015-01-03 03:00:00 : 후평1동   13148 ----------


 ---------- 2015-01-03 11:00:00 : 사북면   13149 ----------


 ---------- 2015-01-03 17:00:00 : 신북읍   13150 ----------


 ---------- 2015-01-03 18:00:00 : 신북읍   13151 ----------


 ---------- 2015-01-03 22:00:00 : 퇴계동   13152 ----------


 ---------- 2015-01-04 13:00:00 : 동  면   13153 ----------


 ---------- 2015-01-04 15:00:00 : 북산면   13155 ----------


 ---------- 2015-01-04 20:00:00 : 퇴계동   13156 ----------


 ---------- 2015-01-04 21:00:00 : 근화동   13157 ----------


 ---------- 2015-01-04 22:00:00 : 강남동   13159 ----------


 ---------- 2015-01-06 00:00:00 : 강남동   13160 ----------


 ---------- 2015-01-06 03:00:00 : 동내면   13161 ----------


 ---------- 2015-01-06 09:00:00 : 남산면   13163 ----------


 ---------- 2015-01-06 09:00:00 : 동  면   13165 ----------


 ---------- 2015-01-06 10:00:00 : 신동면   13166 ----------


 ---------- 2015-01-06 12:00:00 : 석사동   13167 ----------


 ---------- 2015-01-06 13:00:00 : 소양동   13168 ----------

 ---------- 2015-01-06 16:00:00 : 근화동   13170 ----------


 ---------- 2015-01-06 22:00:00 : 약사명동   13171 ----------


 ---------- 2015-01-07 08:00:00 : 퇴계동   13172 ----------


 ---------- 2015-01-07 15:00:00 : 근화동   13173 ----------


 ---------- 2015-01-07 18:00:00 : 퇴계동   13175 ----------


 ---------- 2015-01-07 22:00:00 : 동  면   13176 ----------


 ---------- 2015-01-08 03:00:00 : 소양동   13177 ----------


 ---------- 2015-01-10 14:00:00 : 소양동   13178 ----------


 ---------- 2015-01-10 15:00:00 : 남산면   13179 ----------


 ---------- 2015-01-11 00:00:00 : 후평1동   13180 ----------


 ---------- 2015-01-11 01:00:00 : 남  면   13183 ----------


 ---------- 2015-01-11 14:00:00 : 동내면   13185 ----------


 ---------- 2015-01-11 16:00:00 : 동내면   13187 ----------


 ---------- 2015-01-11 16:00:00 : 동  면   13190 ----------


 ---------- 2015-01-11 18:00:00 : 후평1동   13192 ----------


 ---------- 2015-01-12 15:00:00 : 석사동   13193 ----------


 ---------- 2015-01-12 15:00:00 : 사북면   13196 ----------


 ---------- 2015-01-12 16:00:00 : 동  면   13197 ----------


 ---------- 2015-01-13 00:00:00 : 신사우동   13198 ----------


 ---------- 2015-01-13 10:00:00 : 소양동   13199 ----------


 ---------- 2015-01-13 19:00:00 : 신동면   13200 ----------


 ---------- 2015-01-14 01:00:00 : 석사동   13202 ----------


 ---------- 2015-01-14 10:00:00 : 후평1동   13203 ----------


 ---------- 2015-01-14 13:00:00 : 조운동   13204 ----------


 ---------- 2015-01-14 18:00:00 : 동  면   13205 ----------


 ---------- 2015-01-14 19:00:00 : 근화동   13206 ----------


 ---------- 2015-01-14 20:00:00 : 효자1동   13207 ----------


 ---------- 2015-01-16 09:00:00 : 신사우동   13208 ----------


 ---------- 2015-01-16 09:00:00 : 퇴계동   13209 ----------


 ---------- 2015-01-16 10:00:00 : 약사명동   13211 ----------


 ---------- 2015-01-16 11:00:00 : 사북면   13212 ----------


 ---------- 2015-01-16 11:00:00 : 신사우동   13214 ----------


 ---------- 2015-01-17 11:00:00 : 신북읍   13215 ----------


 ---------- 2015-01-17 12:00:00 : 서  면   13217 ----------


 ---------- 2015-01-17 13:00:00 : 서  면   13218 ----------


 ---------- 2015-01-17 14:00:00 : 서  면   13219 ----------


 ---------- 2015-01-17 19:00:00 : 신북읍   13222 ----------


 ---------- 2015-01-18 02:00:00 : 동산면   13224 ----------


 ---------- 2015-01-18 06:00:00 : 동산면   13226 ----------


 ---------- 2015-01-18 10:00:00 : 근화동   13227 ----------


 ---------- 2015-01-18 10:00:00 : 후평1동   13228 ----------


 ---------- 2015-01-18 15:00:00 : 사북면   13229 ----------


 ---------- 2015-01-18 19:00:00 : 소양동   13230 ----------


 ---------- 2015-01-18 22:00:00 : 동  면   13231 ----------


 ---------- 2015-01-19 13:00:00 : 신북읍   13232 ----------


 ---------- 2015-01-19 17:00:00 : 근화동   13233 ----------


 ---------- 2015-01-19 20:00:00 : 강남동   13234 ----------


 ---------- 2015-01-20 00:00:00 : 효자1동   13235 ----------


 ---------- 2015-01-20 09:00:00 : 후평1동   13236 ----------


 ---------- 2015-01-20 16:00:00 : 남산면   13237 ----------


 ---------- 2015-01-21 09:00:00 : 후평1동   13239 ----------


 ---------- 2015-01-21 11:00:00 : 신북읍   13242 ----------


 ---------- 2015-01-22 11:00:00 : 후평1동   13243 ----------


 ---------- 2015-01-22 12:00:00 : 동내면   13245 ----------


 ---------- 2015-01-22 17:00:00 : 남산면   13246 ----------


 ---------- 2015-01-23 04:00:00 : 근화동   13247 ----------


 ---------- 2015-01-23 18:00:00 : 사북면   13249 ----------


 ---------- 2015-01-23 20:00:00 : 동  면   13251 ----------


 ---------- 2015-01-24 00:00:00 : 신북읍   13253 ----------


 ---------- 2015-01-24 05:00:00 : 효자1동   13255 ----------


 ---------- 2015-01-24 17:00:00 : 후평1동   13257 ----------


 ---------- 2015-01-24 18:00:00 : 석사동   13258 ----------


 ---------- 2015-01-24 19:00:00 : 후평1동   13259 ----------


 ---------- 2015-01-25 07:00:00 : 남  면   13260 ----------


 ---------- 2015-01-25 10:00:00 : 퇴계동   13261 ----------


 ---------- 2015-01-25 13:00:00 : 사북면   13262 ----------


 ---------- 2015-01-25 18:00:00 : 근화동   13263 ----------


 ---------- 2015-01-26 08:00:00 : 조운동   13264 ----------


 ---------- 2015-01-26 14:00:00 : 신사우동   13265 ----------


 ---------- 2015-01-27 02:00:00 : 동  면   13267 ----------


 ---------- 2015-01-27 18:00:00 : 소양동   13269 ----------


 ---------- 2015-01-27 18:00:00 : 퇴계동   13271 ----------


 ---------- 2015-01-28 22:00:00 : 효자1동   13273 ----------


 ---------- 2015-01-28 23:00:00 : 후평1동   13274 ----------


 ---------- 2015-01-29 00:00:00 : 석사동   13275 ----------


 ---------- 2015-01-29 11:00:00 : 동산면   13276 ----------


 ---------- 2015-01-29 16:00:00 : 석사동   13277 ----------


 ---------- 2015-01-29 20:00:00 : 후평1동   13279 ----------


 ---------- 2015-01-30 11:00:00 : 후평1동   13280 ----------


 ---------- 2015-01-30 18:00:00 : 사북면   13281 ----------


 ---------- 2015-01-31 09:00:00 : 효자1동   13282 ----------


 ---------- 2015-01-31 12:00:00 : 남산면   13283 ----------


 ---------- 2015-01-31 13:00:00 : 동  면   13285 ----------


 ---------- 2015-01-31 14:00:00 : 남산면   13286 ----------


 ---------- 2015-01-31 15:00:00 : 동  면   13287 ----------


 ---------- 2015-01-31 16:00:00 : 동  면   13288 ----------


 ---------- 2015-01-31 18:00:00 : 강남동   13289 ----------


 ---------- 2015-02-01 03:00:00 : 퇴계동   13290 ----------


 ---------- 2015-02-01 04:00:00 : 근화동   13291 ----------


 ---------- 2015-02-01 13:00:00 : 서  면   13294 ----------


 ---------- 2015-02-01 13:00:00 : 동  면   13295 ----------


 ---------- 2015-02-01 15:00:00 : 남산면   13296 ----------


 ---------- 2015-02-01 15:00:00 : 동  면   13297 ----------


 ---------- 2015-02-01 16:00:00 : 남산면   13298 ----------


 ---------- 2015-02-02 04:00:00 : 후평1동   13299 ----------


 ---------- 2015-02-02 07:00:00 : 서  면   13302 ----------


 ---------- 2015-02-02 09:00:00 : 석사동   13303 ----------


 ---------- 2015-02-03 12:00:00 : 신동면   13304 ----------


 ---------- 2015-02-03 15:00:00 : 신북읍   13305 ----------


 ---------- 2015-02-04 11:00:00 : 후평1동   13306 ----------


 ---------- 2015-02-04 11:00:00 : 동산면   13308 ----------


 ---------- 2015-02-04 12:00:00 : 후평1동   13310 ----------


 ---------- 2015-02-04 16:00:00 : 남산면   13311 ----------


 ---------- 2015-02-04 23:00:00 : 사북면   13312 ----------


 ---------- 2015-02-05 02:00:00 : 후평1동   13313 ----------


 ---------- 2015-02-05 13:00:00 : 신사우동   13315 ----------


 ---------- 2015-02-05 19:00:00 : 신북읍   13316 ----------


 ---------- 2015-02-06 03:00:00 : 근화동   13317 ----------


 ---------- 2015-02-06 18:00:00 : 강남동   13318 ----------


 ---------- 2015-02-08 01:00:00 : 석사동   13319 ----------


 ---------- 2015-02-08 06:00:00 : 북산면   13322 ----------


 ---------- 2015-02-08 17:00:00 : 후평1동   13323 ----------


 ---------- 2015-02-08 18:00:00 : 후평1동   13324 ----------


 ---------- 2015-02-09 12:00:00 : 근화동   13325 ----------


 ---------- 2015-02-09 12:00:00 : 소양동   13326 ----------


 ---------- 2015-02-09 16:00:00 : 남산면   13327 ----------


 ---------- 2015-02-10 10:00:00 : 신사우동   13329 ----------


 ---------- 2015-02-10 15:00:00 : 효자1동   13331 ----------


 ---------- 2015-02-10 16:00:00 : 북산면   13332 ----------


 ---------- 2015-02-10 20:00:00 : 석사동   13333 ----------


 ---------- 2015-02-11 15:00:00 : 사북면   13336 ----------


 ---------- 2015-02-11 18:00:00 : 근화동   13338 ----------


 ---------- 2015-02-12 03:00:00 : 신사우동   13339 ----------


 ---------- 2015-02-12 09:00:00 : 석사동   13341 ----------


 ---------- 2015-02-12 13:00:00 : 석사동   13343 ----------


 ---------- 2015-02-13 05:00:00 : 퇴계동   13344 ----------


 ---------- 2015-02-13 21:00:00 : 동  면   13345 ----------


 ---------- 2015-02-13 21:00:00 : 후평1동   13347 ----------


 ---------- 2015-02-13 23:00:00 : 강남동   13349 ----------


 ---------- 2015-02-13 23:00:00 : 동  면   13350 ----------


 ---------- 2015-02-14 00:00:00 : 근화동   13352 ----------


 ---------- 2015-02-14 00:00:00 : 후평1동   13354 ----------


 ---------- 2015-02-14 12:00:00 : 근화동   13355 ----------


 ---------- 2015-02-14 15:00:00 : 신동면   13356 ----------


 ---------- 2015-02-14 16:00:00 : 후평1동   13357 ----------


 ---------- 2015-02-14 19:00:00 : 효자1동   13358 ----------

 ---------- 2015-02-15 02:00:00 : 동  면   13359 ----------


 ---------- 2015-02-15 05:00:00 : 석사동   13360 ----------


 ---------- 2015-02-15 10:00:00 : 석사동   13361 ----------


 ---------- 2015-02-15 13:00:00 : 조운동   13362 ----------


 ---------- 2015-02-15 15:00:00 : 후평1동   13363 ----------


 ---------- 2015-02-15 19:00:00 : 신사우동   13365 ----------


 ---------- 2015-02-15 23:00:00 : 후평1동   13366 ----------


 ---------- 2015-02-16 11:00:00 : 근화동   13367 ----------


 ---------- 2015-02-16 12:00:00 : 신동면   13368 ----------


 ---------- 2015-02-16 14:00:00 : 효자1동   13369 ----------


 ---------- 2015-02-16 19:00:00 : 동  면   13371 ----------


 ---------- 2015-02-17 16:00:00 : 석사동   13372 ----------


 ---------- 2015-02-18 20:00:00 : 효자1동   13373 ----------


 ---------- 2015-02-18 21:00:00 : 신북읍   13375 ----------


 ---------- 2015-02-18 22:00:00 : 동산면   13377 ----------


 ---------- 2015-02-18 23:00:00 : 석사동   13379 ----------


 ---------- 2015-02-19 10:00:00 : 후평1동   13380 ----------


 ---------- 2015-02-19 18:00:00 : 동내면   13381 ----------


 ---------- 2015-02-20 00:00:00 : 효자1동   13383 ----------


 ---------- 2015-02-20 02:00:00 : 남산면   13384 ----------


 ---------- 2015-02-20 12:00:00 : 신사우동   13385 ----------


 ---------- 2015-02-20 19:00:00 : 퇴계동   13387 ----------


 ---------- 2015-02-21 11:00:00 : 동내면   13388 ----------


 ---------- 2015-02-21 18:00:00 : 서  면   13389 ----------


 ---------- 2015-02-21 23:00:00 : 석사동   13391 ----------


 ---------- 2015-02-22 17:00:00 : 근화동   13393 ----------


 ---------- 2015-02-22 21:00:00 : 신북읍   13394 ----------


 ---------- 2015-02-23 09:00:00 : 강남동   13396 ----------


 ---------- 2015-02-23 10:00:00 : 사북면   13397 ----------


 ---------- 2015-02-23 11:00:00 : 동  면   13398 ----------


 ---------- 2015-02-23 22:00:00 : 퇴계동   13399 ----------


 ---------- 2015-02-23 23:00:00 : 퇴계동   13400 ----------


 ---------- 2015-02-24 01:00:00 : 동  면   13401 ----------


 ---------- 2015-02-24 05:00:00 : 동  면   13402 ----------


 ---------- 2015-02-24 14:00:00 : 퇴계동   13403 ----------


 ---------- 2015-02-24 15:00:00 : 교  동   13405 ----------


 ---------- 2015-02-24 23:00:00 : 석사동   13407 ----------


 ---------- 2015-02-24 23:00:00 : 후평1동   13408 ----------


 ---------- 2015-02-25 07:00:00 : 남산면   13409 ----------


 ---------- 2015-02-27 00:00:00 : 퇴계동   13410 ----------


 ---------- 2015-02-27 09:00:00 : 후평1동   13411 ----------


 ---------- 2015-02-27 18:00:00 : 신사우동   13412 ----------


 ---------- 2015-02-27 18:00:00 : 동산면   13413 ----------


 ---------- 2015-02-28 13:00:00 : 신사우동   13415 ----------


 ---------- 2015-02-28 15:00:00 : 신동면   13417 ----------


 ---------- 2015-03-01 06:00:00 : 후평1동   13419 ----------


 ---------- 2015-03-01 13:00:00 : 서  면   13420 ----------


 ---------- 2015-03-01 21:00:00 : 약사명동   13421 ----------


 ---------- 2015-03-01 22:00:00 : 퇴계동   13422 ----------


 ---------- 2015-03-02 09:00:00 : 남  면   13423 ----------


 ---------- 2015-03-02 14:00:00 : 사북면   13425 ----------


 ---------- 2015-03-02 21:00:00 : 동  면   13426 ----------


 ---------- 2015-03-03 08:00:00 : 후평1동   13427 ----------


 ---------- 2015-03-03 11:00:00 : 근화동   13428 ----------


 ---------- 2015-03-03 18:00:00 : 신사우동   13429 ----------


 ---------- 2015-03-03 21:00:00 : 후평1동   13430 ----------


 ---------- 2015-03-04 10:00:00 : 석사동   13431 ----------


 ---------- 2015-03-04 10:00:00 : 조운동   13432 ----------


 ---------- 2015-03-04 11:00:00 : 석사동   13433 ----------


 ---------- 2015-03-04 17:00:00 : 후평1동   13435 ----------


 ---------- 2015-03-04 22:00:00 : 퇴계동   13438 ----------


 ---------- 2015-03-05 03:00:00 : 약사명동   13440 ----------


 ---------- 2015-03-05 11:00:00 : 동  면   13441 ----------


 ---------- 2015-03-05 14:00:00 : 석사동   13443 ----------


 ---------- 2015-03-05 15:00:00 : 동  면   13444 ----------


 ---------- 2015-03-05 19:00:00 : 후평1동   13445 ----------


 ---------- 2015-03-06 10:00:00 : 동내면   13446 ----------


 ---------- 2015-03-06 11:00:00 : 신동면   13447 ----------


 ---------- 2015-03-06 14:00:00 : 근화동   13448 ----------


 ---------- 2015-03-06 16:00:00 : 효자1동   13449 ----------


 ---------- 2015-03-06 18:00:00 : 소양동   13452 ----------


 ---------- 2015-03-06 19:00:00 : 신북읍   13454 ----------


 ---------- 2015-03-07 06:00:00 : 후평1동   13455 ----------


 ---------- 2015-03-07 17:00:00 : 약사명동   13456 ----------


 ---------- 2015-03-07 18:00:00 : 신북읍   13458 ----------


 ---------- 2015-03-07 21:00:00 : 퇴계동   13459 ----------


 ---------- 2015-03-08 10:00:00 : 효자1동   13460 ----------


 ---------- 2015-03-09 14:00:00 : 신북읍   13461 ----------


 ---------- 2015-03-09 14:00:00 : 동  면   13462 ----------


 ---------- 2015-03-09 18:00:00 : 소양동   13463 ----------


 ---------- 2015-03-10 08:00:00 : 석사동   13464 ----------


 ---------- 2015-03-10 11:00:00 : 석사동   13465 ----------


 ---------- 2015-03-10 16:00:00 : 교  동   13466 ----------


 ---------- 2015-03-10 22:00:00 : 석사동   13468 ----------


 ---------- 2015-03-11 14:00:00 : 근화동   13469 ----------


 ---------- 2015-03-12 06:00:00 : 효자1동   13471 ----------


 ---------- 2015-03-12 08:00:00 : 신동면   13473 ----------


 ---------- 2015-03-12 09:00:00 : 근화동   13474 ----------


 ---------- 2015-03-12 11:00:00 : 서  면   13475 ----------


 ---------- 2015-03-12 17:00:00 : 소양동   13476 ----------


 ---------- 2015-03-12 21:00:00 : 효자1동   13477 ----------


 ---------- 2015-03-13 08:00:00 : 사북면   13479 ----------


 ---------- 2015-03-13 17:00:00 : 효자1동   13480 ----------


 ---------- 2015-03-13 18:00:00 : 효자1동   13482 ----------


 ---------- 2015-03-13 19:00:00 : 소양동   13483 ----------


 ---------- 2015-03-14 01:00:00 : 남산면   13484 ----------


 ---------- 2015-03-14 04:00:00 : 동  면   13486 ----------


 ---------- 2015-03-14 10:00:00 : 신북읍   13487 ----------


 ---------- 2015-03-14 16:00:00 : 소양동   13488 ----------


 ---------- 2015-03-15 01:00:00 : 효자1동   13489 ----------


 ---------- 2015-03-15 07:00:00 : 동산면   13490 ----------


 ---------- 2015-03-15 09:00:00 : 소양동   13491 ----------


 ---------- 2015-03-15 15:00:00 : 근화동   13492 ----------


 ---------- 2015-03-15 15:00:00 : 북산면   13496 ----------


 ---------- 2015-03-15 16:00:00 : 동  면   13497 ----------


 ---------- 2015-03-15 16:00:00 : 후평1동   13499 ----------


 ---------- 2015-03-15 19:00:00 : 퇴계동   13501 ----------


 ---------- 2015-03-15 20:00:00 : 동  면   13503 ----------


 ---------- 2015-03-15 21:00:00 : 강남동   13505 ----------


 ---------- 2015-03-16 00:00:00 : 신사우동   13507 ----------


 ---------- 2015-03-16 08:00:00 : 석사동   13509 ----------


 ---------- 2015-03-16 12:00:00 : 소양동   13510 ----------


 ---------- 2015-03-16 16:00:00 : 서  면   13511 ----------


 ---------- 2015-03-16 20:00:00 : 동내면   13512 ----------


 ---------- 2015-03-16 20:00:00 : 동산면   13513 ----------


 ---------- 2015-03-16 22:00:00 : 후평1동   13514 ----------


 ---------- 2015-03-17 14:00:00 : 효자1동   13515 ----------


 ---------- 2015-03-17 16:00:00 : 효자1동   13516 ----------


 ---------- 2015-03-18 01:00:00 : 동내면   13517 ----------


 ---------- 2015-03-18 01:00:00 : 효자1동   13520 ----------


 ---------- 2015-03-18 11:00:00 : 근화동   13523 ----------


 ---------- 2015-03-18 13:00:00 : 후평1동   13524 ----------


 ---------- 2015-03-18 20:00:00 : 퇴계동   13525 ----------


 ---------- 2015-03-19 07:00:00 : 석사동   13527 ----------


 ---------- 2015-03-19 09:00:00 : 석사동   13529 ----------


 ---------- 2015-03-19 09:00:00 : 효자1동   13530 ----------


 ---------- 2015-03-19 12:00:00 : 서  면   13532 ----------


 ---------- 2015-03-19 14:00:00 : 서  면   13533 ----------


 ---------- 2015-03-19 17:00:00 : 석사동   13536 ----------


 ---------- 2015-03-20 01:00:00 : 후평1동   13537 ----------


 ---------- 2015-03-20 07:00:00 : 후평1동   13538 ----------


 ---------- 2015-03-20 09:00:00 : 신북읍   13539 ----------


 ---------- 2015-03-20 13:00:00 : 남산면   13541 ----------


 ---------- 2015-03-20 17:00:00 : 후평1동   13542 ----------


 ---------- 2015-03-20 22:00:00 : 효자1동   13543 ----------


 ---------- 2015-03-20 23:00:00 : 신사우동   13545 ----------

 ---------- 2015-03-21 10:00:00 : 강남동   13547 ----------


 ---------- 2015-03-21 15:00:00 : 후평1동   13548 ----------


 ---------- 2015-03-21 17:00:00 : 후평1동   13549 ----------


 ---------- 2015-03-21 19:00:00 : 신사우동   13550 ----------


 ---------- 2015-03-22 00:00:00 : 서  면   13553 ----------


 ---------- 2015-03-22 11:00:00 : 효자1동   13554 ----------


 ---------- 2015-03-22 15:00:00 : 동내면   13555 ----------


 ---------- 2015-03-22 16:00:00 : 강남동   13556 ----------


 ---------- 2015-03-22 19:00:00 : 강남동   13557 ----------


 ---------- 2015-03-23 01:00:00 : 효자1동   13558 ----------


 ---------- 2015-03-23 05:00:00 : 강남동   13559 ----------


 ---------- 2015-03-23 08:00:00 : 신동면   13560 ----------


 ---------- 2015-03-23 11:00:00 : 사북면   13563 ----------


 ---------- 2015-03-23 15:00:00 : 신북읍   13564 ----------


 ---------- 2015-03-24 06:00:00 : 석사동   13565 ----------


 ---------- 2015-03-24 09:00:00 : 후평1동   13566 ----------


 ---------- 2015-03-24 10:00:00 : 후평1동   13567 ----------


 ---------- 2015-03-24 10:00:00 : 북산면   13569 ----------


 ---------- 2015-03-24 16:00:00 : 신북읍   13570 ----------


 ---------- 2015-03-24 19:00:00 : 효자1동   13571 ----------


 ---------- 2015-03-25 00:00:00 : 후평1동   13572 ----------


 ---------- 2015-03-25 06:00:00 : 남산면   13573 ----------


 ---------- 2015-03-25 13:00:00 : 소양동   13574 ----------


 ---------- 2015-03-25 19:00:00 : 신북읍   13576 ----------


 ---------- 2015-03-25 20:00:00 : 석사동   13577 ----------


 ---------- 2015-03-26 01:00:00 : 동  면   13579 ----------


 ---------- 2015-03-26 02:00:00 : 조운동   13580 ----------


 ---------- 2015-03-26 04:00:00 : 후평1동   13581 ----------


 ---------- 2015-03-26 08:00:00 : 석사동   13582 ----------


 ---------- 2015-03-27 10:00:00 : 석사동   13584 ----------


 ---------- 2015-03-27 12:00:00 : 신북읍   13585 ----------


 ---------- 2015-03-27 14:00:00 : 후평1동   13586 ----------


 ---------- 2015-03-27 15:00:00 : 신사우동   13588 ----------


 ---------- 2015-03-27 23:00:00 : 석사동   13590 ----------


 ---------- 2015-03-27 23:00:00 : 신사우동   13591 ----------


 ---------- 2015-03-27 23:00:00 : 동산면   13592 ----------


 ---------- 2015-03-28 01:00:00 : 강남동   13593 ----------


 ---------- 2015-03-28 05:00:00 : 석사동   13595 ----------


 ---------- 2015-03-28 08:00:00 : 석사동   13597 ----------


 ---------- 2015-03-28 12:00:00 : 동내면   13598 ----------


 ---------- 2015-03-28 15:00:00 : 효자1동   13599 ----------


 ---------- 2015-03-28 21:00:00 : 약사명동   13600 ----------


 ---------- 2015-03-28 22:00:00 : 소양동   13601 ----------


 ---------- 2015-03-29 02:00:00 : 근화동   13602 ----------


 ---------- 2015-03-29 11:00:00 : 서  면   13604 ----------


 ---------- 2015-03-29 23:00:00 : 서  면   13605 ----------


 ---------- 2015-03-30 06:00:00 : 동  면   13607 ----------


 ---------- 2015-03-30 12:00:00 : 소양동   13608 ----------


 ---------- 2015-03-30 15:00:00 : 서  면   13609 ----------


 ---------- 2015-03-30 17:00:00 : 신북읍   13610 ----------


 ---------- 2015-03-30 17:00:00 : 조운동   13611 ----------


 ---------- 2015-03-30 20:00:00 : 근화동   13612 ----------


 ---------- 2015-03-31 00:00:00 : 석사동   13614 ----------


 ---------- 2015-03-31 06:00:00 : 후평1동   13615 ----------


 ---------- 2015-03-31 12:00:00 : 후평1동   13616 ----------


 ---------- 2015-03-31 13:00:00 : 효자1동   13617 ----------


 ---------- 2015-03-31 13:00:00 : 남산면   13619 ----------


 ---------- 2015-03-31 13:00:00 : 북산면   13621 ----------


 ---------- 2015-03-31 14:00:00 : 북산면   13622 ----------


 ---------- 2015-03-31 16:00:00 : 근화동   13623 ----------


 ---------- 2015-03-31 23:00:00 : 퇴계동   13624 ----------


 ---------- 2015-04-01 05:00:00 : 신북읍   13625 ----------


 ---------- 2015-04-01 12:00:00 : 퇴계동   13626 ----------


 ---------- 2015-04-01 15:00:00 : 후평1동   13627 ----------


 ---------- 2015-04-01 21:00:00 : 석사동   13629 ----------


 ---------- 2015-04-01 22:00:00 : 남산면   13630 ----------


 ---------- 2015-04-02 14:00:00 : 강남동   13631 ----------


 ---------- 2015-04-02 23:00:00 : 퇴계동   13632 ----------


 ---------- 2015-04-03 08:00:00 : 근화동   13633 ----------


 ---------- 2015-04-03 09:00:00 : 신사우동   13634 ----------


 ---------- 2015-04-03 14:00:00 : 신북읍   13635 ----------


 ---------- 2015-04-03 15:00:00 : 서  면   13636 ----------


 ---------- 2015-04-03 16:00:00 : 사북면   13637 ----------


 ---------- 2015-04-03 19:00:00 : 동내면   13639 ----------


 ---------- 2015-04-03 21:00:00 : 석사동   13641 ----------


 ---------- 2015-04-03 22:00:00 : 동산면   13645 ----------


 ---------- 2015-04-04 09:00:00 : 강남동   13647 ----------


 ---------- 2015-04-04 10:00:00 : 근화동   13649 ----------


 ---------- 2015-04-04 14:00:00 : 약사명동   13651 ----------


 ---------- 2015-04-05 12:00:00 : 동  면   13653 ----------


 ---------- 2015-04-05 21:00:00 : 근화동   13654 ----------


 ---------- 2015-04-05 23:00:00 : 퇴계동   13655 ----------


 ---------- 2015-04-06 00:00:00 : 신북읍   13657 ----------


 ---------- 2015-04-06 11:00:00 : 석사동   13658 ----------


 ---------- 2015-04-06 12:00:00 : 소양동   13659 ----------


 ---------- 2015-04-06 15:00:00 : 동내면   13660 ----------


 ---------- 2015-04-06 15:00:00 : 신북읍   13661 ----------


 ---------- 2015-04-07 13:00:00 : 남산면   13663 ----------


 ---------- 2015-04-07 16:00:00 : 효자1동   13665 ----------


 ---------- 2015-04-07 20:00:00 : 소양동   13666 ----------


 ---------- 2015-04-07 21:00:00 : 후평1동   13667 ----------


 ---------- 2015-04-08 01:00:00 : 신동면   13668 ----------


 ---------- 2015-04-08 05:00:00 : 후평1동   13669 ----------


 ---------- 2015-04-08 09:00:00 : 강남동   13671 ----------


 ---------- 2015-04-08 09:00:00 : 근화동   13672 ----------


 ---------- 2015-04-08 15:00:00 : 동내면   13673 ----------


 ---------- 2015-04-08 17:00:00 : 소양동   13674 ----------


 ---------- 2015-04-08 23:00:00 : 효자1동   13675 ----------


 ---------- 2015-04-09 01:00:00 : 석사동   13676 ----------


 ---------- 2015-04-09 09:00:00 : 약사명동   13677 ----------


 ---------- 2015-04-09 11:00:00 : 서  면   13679 ----------


 ---------- 2015-04-09 16:00:00 : 동  면   13680 ----------


 ---------- 2015-04-09 18:00:00 : 퇴계동   13681 ----------


 ---------- 2015-04-09 19:00:00 : 후평1동   13682 ----------


 ---------- 2015-04-09 23:00:00 : 남산면   13683 ----------


 ---------- 2015-04-10 06:00:00 : 동  면   13684 ----------


 ---------- 2015-04-10 07:00:00 : 소양동   13686 ----------


 ---------- 2015-04-10 15:00:00 : 북산면   13687 ----------


 ---------- 2015-04-11 01:00:00 : 강남동   13688 ----------


 ---------- 2015-04-11 02:00:00 : 강남동   13690 ----------


 ---------- 2015-04-11 09:00:00 : 동내면   13692 ----------


 ---------- 2015-04-11 10:00:00 : 신사우동   13693 ----------


 ---------- 2015-04-11 11:00:00 : 서  면   13694 ----------


 ---------- 2015-04-11 11:00:00 : 신사우동   13695 ----------


 ---------- 2015-04-11 11:00:00 : 소양동   13696 ----------


 ---------- 2015-04-11 13:00:00 : 남  면   13697 ----------


 ---------- 2015-04-11 13:00:00 : 동내면   13698 ----------


 ---------- 2015-04-11 14:00:00 : 근화동   13699 ----------


 ---------- 2015-04-11 21:00:00 : 후평1동   13700 ----------


 ---------- 2015-04-11 22:00:00 : 근화동   13701 ----------


 ---------- 2015-04-12 05:00:00 : 효자1동   13703 ----------


 ---------- 2015-04-12 06:00:00 : 동내면   13705 ----------


 ---------- 2015-04-12 11:00:00 : 신사우동   13706 ----------


 ---------- 2015-04-12 11:00:00 : 동산면   13707 ----------


 ---------- 2015-04-12 15:00:00 : 서  면   13708 ----------


 ---------- 2015-04-12 20:00:00 : 석사동   13709 ----------


 ---------- 2015-04-12 21:00:00 : 동내면   13710 ----------


 ---------- 2015-04-13 10:00:00 : 후평1동   13711 ----------


 ---------- 2015-04-13 15:00:00 : 서  면   13712 ----------


 ---------- 2015-04-14 01:00:00 : 강남동   13714 ----------


 ---------- 2015-04-14 16:00:00 : 강남동   13715 ----------


 ---------- 2015-04-14 18:00:00 : 석사동   13716 ----------


 ---------- 2015-04-14 22:00:00 : 강남동   13717 ----------


 ---------- 2015-04-15 07:00:00 : 동산면   13718 ----------


 ---------- 2015-04-15 14:00:00 : 신사우동   13721 ----------


 ---------- 2015-04-15 14:00:00 : 교  동   13722 ----------

 ---------- 2015-04-15 16:00:00 : 서  면   13725 ----------


 ---------- 2015-04-15 18:00:00 : 후평1동   13726 ----------


 ---------- 2015-04-15 19:00:00 : 사북면   13728 ----------


 ---------- 2015-04-15 19:00:00 : 퇴계동   13729 ----------


 ---------- 2015-04-16 02:00:00 : 효자1동   13730 ----------


 ---------- 2015-04-16 06:00:00 : 북산면   13732 ----------


 ---------- 2015-04-16 09:00:00 : 퇴계동   13734 ----------


 ---------- 2015-04-16 14:00:00 : 약사명동   13736 ----------


 ---------- 2015-04-16 20:00:00 : 석사동   13737 ----------


 ---------- 2015-04-16 23:00:00 : 신사우동   13738 ----------


 ---------- 2015-04-17 10:00:00 : 근화동   13739 ----------


 ---------- 2015-04-17 21:00:00 : 동  면   13740 ----------


 ---------- 2015-04-18 01:00:00 : 퇴계동   13741 ----------


 ---------- 2015-04-18 02:00:00 : 동내면   13742 ----------


 ---------- 2015-04-18 03:00:00 : 퇴계동   13743 ----------


 ---------- 2015-04-18 04:00:00 : 근화동   13744 ----------


 ---------- 2015-04-18 06:00:00 : 동  면   13745 ----------


 ---------- 2015-04-18 10:00:00 : 사북면   13746 ----------


 ---------- 2015-04-18 19:00:00 : 근화동   13747 ----------


 ---------- 2015-04-18 20:00:00 : 효자1동   13748 ----------


 ---------- 2015-04-18 21:00:00 : 동산면   13749 ----------


 ---------- 2015-04-19 00:00:00 : 후평1동   13750 ----------


 ---------- 2015-04-19 10:00:00 : 효자1동   13751 ----------


 ---------- 2015-04-19 12:00:00 : 근화동   13753 ----------


 ---------- 2015-04-19 17:00:00 : 교  동   13754 ----------


 ---------- 2015-04-19 21:00:00 : 효자1동   13755 ----------


 ---------- 2015-04-20 15:00:00 : 퇴계동   13756 ----------


 ---------- 2015-04-20 23:00:00 : 후평1동   13757 ----------


 ---------- 2015-04-21 01:00:00 : 소양동   13758 ----------


 ---------- 2015-04-21 07:00:00 : 효자1동   13759 ----------


 ---------- 2015-04-21 13:00:00 : 석사동   13760 ----------


 ---------- 2015-04-21 18:00:00 : 석사동   13761 ----------


 ---------- 2015-04-21 18:00:00 : 남  면   13762 ----------


 ---------- 2015-04-21 20:00:00 : 후평1동   13763 ----------


 ---------- 2015-04-21 21:00:00 : 석사동   13764 ----------


 ---------- 2015-04-21 21:00:00 : 효자1동   13766 ----------


 ---------- 2015-04-21 22:00:00 : 석사동   13767 ----------


 ---------- 2015-04-21 22:00:00 : 신사우동   13768 ----------


 ---------- 2015-04-22 03:00:00 : 신동면   13769 ----------


 ---------- 2015-04-22 09:00:00 : 석사동   13770 ----------


 ---------- 2015-04-22 14:00:00 : 강남동   13771 ----------


 ---------- 2015-04-22 22:00:00 : 효자1동   13772 ----------


 ---------- 2015-04-23 09:00:00 : 퇴계동   13773 ----------


 ---------- 2015-04-23 10:00:00 : 강남동   13774 ----------


 ---------- 2015-04-23 11:00:00 : 사북면   13775 ----------


 ---------- 2015-04-23 17:00:00 : 퇴계동   13776 ----------


 ---------- 2015-04-23 21:00:00 : 신사우동   13777 ----------


 ---------- 2015-04-23 21:00:00 : 신북읍   13778 ----------


 ---------- 2015-04-24 09:00:00 : 강남동   13779 ----------


 ---------- 2015-04-24 14:00:00 : 동  면   13780 ----------


 ---------- 2015-04-24 17:00:00 : 석사동   13781 ----------


 ---------- 2015-04-25 09:00:00 : 동  면   13782 ----------


 ---------- 2015-04-25 15:00:00 : 사북면   13784 ----------


 ---------- 2015-04-25 16:00:00 : 남  면   13785 ----------


 ---------- 2015-04-25 18:00:00 : 남산면   13786 ----------


 ---------- 2015-04-25 21:00:00 : 석사동   13788 ----------


 ---------- 2015-04-25 21:00:00 : 퇴계동   13789 ----------


 ---------- 2015-04-26 02:00:00 : 남산면   13790 ----------


 ---------- 2015-04-26 14:00:00 : 조운동   13791 ----------


 ---------- 2015-04-26 21:00:00 : 후평1동   13792 ----------


 ---------- 2015-04-27 12:00:00 : 강남동   13794 ----------


 ---------- 2015-04-27 18:00:00 : 신사우동   13795 ----------


 ---------- 2015-04-27 19:00:00 : 신사우동   13796 ----------


 ---------- 2015-04-27 20:00:00 : 신사우동   13797 ----------


 ---------- 2015-04-27 22:00:00 : 동  면   13798 ----------


 ---------- 2015-04-28 22:00:00 : 후평1동   13799 ----------


 ---------- 2015-04-29 00:00:00 : 석사동   13800 ----------


 ---------- 2015-04-30 10:00:00 : 효자1동   13802 ----------


 ---------- 2015-04-30 16:00:00 : 강남동   13803 ----------


 ---------- 2015-04-30 21:00:00 : 신동면   13804 ----------


 ---------- 2015-04-30 21:00:00 : 동내면   13806 ----------


 ---------- 2015-04-30 22:00:00 : 소양동   13807 ----------


 ---------- 2015-05-01 02:00:00 : 신동면   13809 ----------


 ---------- 2015-05-01 02:00:00 : 동  면   13810 ----------


 ---------- 2015-05-01 05:00:00 : 동산면   13811 ----------


 ---------- 2015-05-01 12:00:00 : 서  면   13813 ----------


 ---------- 2015-05-01 18:00:00 : 후평1동   13814 ----------


 ---------- 2015-05-02 02:00:00 : 신사우동   13815 ----------


 ---------- 2015-05-02 03:00:00 : 효자1동   13816 ----------


 ---------- 2015-05-02 10:00:00 : 석사동   13817 ----------


 ---------- 2015-05-02 15:00:00 : 강남동   13818 ----------


 ---------- 2015-05-02 15:00:00 : 동  면   13819 ----------


 ---------- 2015-05-03 05:00:00 : 후평1동   13820 ----------


 ---------- 2015-05-03 08:00:00 : 동내면   13821 ----------


 ---------- 2015-05-03 09:00:00 : 근화동   13822 ----------


 ---------- 2015-05-03 09:00:00 : 동  면   13823 ----------


 ---------- 2015-05-03 15:00:00 : 효자1동   13824 ----------


 ---------- 2015-05-03 15:00:00 : 퇴계동   13825 ----------


 ---------- 2015-05-03 18:00:00 : 후평1동   13826 ----------


 ---------- 2015-05-03 20:00:00 : 석사동   13827 ----------


 ---------- 2015-05-04 00:00:00 : 남산면   13829 ----------


 ---------- 2015-05-04 09:00:00 : 신사우동   13831 ----------


 ---------- 2015-05-04 13:00:00 : 후평1동   13832 ----------


 ---------- 2015-05-04 15:00:00 : 동  면   13834 ----------


 ---------- 2015-05-04 22:00:00 : 동  면   13835 ----------


 ---------- 2015-05-05 02:00:00 : 후평1동   13836 ----------


 ---------- 2015-05-05 04:00:00 : 효자1동   13837 ----------


 ---------- 2015-05-05 06:00:00 : 석사동   13838 ----------


 ---------- 2015-05-05 08:00:00 : 신사우동   13839 ----------


 ---------- 2015-05-05 13:00:00 : 소양동   13840 ----------


 ---------- 2015-05-05 15:00:00 : 퇴계동   13841 ----------


 ---------- 2015-05-06 00:00:00 : 퇴계동   13842 ----------


 ---------- 2015-05-06 01:00:00 : 근화동   13843 ----------


 ---------- 2015-05-06 09:00:00 : 퇴계동   13844 ----------


 ---------- 2015-05-06 10:00:00 : 퇴계동   13845 ----------


 ---------- 2015-05-06 11:00:00 : 신동면   13846 ----------


 ---------- 2015-05-06 15:00:00 : 후평1동   13847 ----------


 ---------- 2015-05-06 15:00:00 : 퇴계동   13849 ----------


 ---------- 2015-05-06 17:00:00 : 퇴계동   13850 ----------


 ---------- 2015-05-07 00:00:00 : 석사동   13851 ----------


 ---------- 2015-05-07 00:00:00 : 교  동   13852 ----------


 ---------- 2015-05-07 01:00:00 : 효자1동   13853 ----------


 ---------- 2015-05-07 13:00:00 : 퇴계동   13854 ----------


 ---------- 2015-05-07 15:00:00 : 후평1동   13855 ----------


 ---------- 2015-05-08 09:00:00 : 서  면   13856 ----------


 ---------- 2015-05-08 12:00:00 : 퇴계동   13857 ----------


 ---------- 2015-05-08 14:00:00 : 동산면   13858 ----------


 ---------- 2015-05-08 20:00:00 : 동내면   13860 ----------


 ---------- 2015-05-08 23:00:00 : 남산면   13862 ----------


 ---------- 2015-05-09 02:00:00 : 퇴계동   13863 ----------


 ---------- 2015-05-09 09:00:00 : 신동면   13865 ----------


 ---------- 2015-05-09 14:00:00 : 남산면   13866 ----------


 ---------- 2015-05-09 16:00:00 : 강남동   13867 ----------


 ---------- 2015-05-09 17:00:00 : 후평1동   13868 ----------


 ---------- 2015-05-09 20:00:00 : 강남동   13869 ----------


 ---------- 2015-05-09 21:00:00 : 사북면   13871 ----------


 ---------- 2015-05-10 08:00:00 : 조운동   13872 ----------


 ---------- 2015-05-10 12:00:00 : 북산면   13873 ----------


 ---------- 2015-05-10 13:00:00 : 북산면   13876 ----------


 ---------- 2015-05-10 16:00:00 : 동  면   13877 ----------


 ---------- 2015-05-10 19:00:00 : 동내면   13878 ----------


 ---------- 2015-05-11 12:00:00 : 후평1동   13879 ----------


 ---------- 2015-05-11 15:00:00 : 효자1동   13880 ----------


 ---------- 2015-05-11 15:00:00 : 약사명동   13881 ----------


 ---------- 2015-05-11 19:00:00 : 후평1동   13882 ----------


 ---------- 2015-05-11 19:00:00 : 퇴계동   13883 ----------

 ---------- 2015-05-11 21:00:00 : 남  면   13885 ----------


 ---------- 2015-05-11 23:00:00 : 퇴계동   13886 ----------


 ---------- 2015-05-12 04:00:00 : 신북읍   13887 ----------


 ---------- 2015-05-12 09:00:00 : 동  면   13888 ----------


 ---------- 2015-05-12 14:00:00 : 효자1동   13889 ----------


 ---------- 2015-05-12 17:00:00 : 석사동   13890 ----------


 ---------- 2015-05-12 18:00:00 : 동내면   13891 ----------


 ---------- 2015-05-13 02:00:00 : 근화동   13892 ----------


 ---------- 2015-05-13 09:00:00 : 조운동   13893 ----------


 ---------- 2015-05-13 11:00:00 : 신사우동   13894 ----------


 ---------- 2015-05-13 16:00:00 : 근화동   13895 ----------


 ---------- 2015-05-14 02:00:00 : 석사동   13896 ----------


 ---------- 2015-05-14 14:00:00 : 근화동   13897 ----------


 ---------- 2015-05-14 19:00:00 : 강남동   13898 ----------


 ---------- 2015-05-14 20:00:00 : 신북읍   13899 ----------


 ---------- 2015-05-15 04:00:00 : 퇴계동   13901 ----------


 ---------- 2015-05-15 12:00:00 : 석사동   13902 ----------


 ---------- 2015-05-15 12:00:00 : 동내면   13903 ----------


 ---------- 2015-05-15 14:00:00 : 서  면   13905 ----------


 ---------- 2015-05-15 14:00:00 : 동산면   13908 ----------


 ---------- 2015-05-15 15:00:00 : 소양동   13909 ----------


 ---------- 2015-05-15 16:00:00 : 동내면   13911 ----------


 ---------- 2015-05-15 16:00:00 : 동  면   13913 ----------


 ---------- 2015-05-15 21:00:00 : 후평1동   13914 ----------


 ---------- 2015-05-16 02:00:00 : 석사동   13915 ----------


 ---------- 2015-05-16 08:00:00 : 남산면   13916 ----------


 ---------- 2015-05-16 10:00:00 : 북산면   13917 ----------


 ---------- 2015-05-16 16:00:00 : 신사우동   13918 ----------


 ---------- 2015-05-17 03:00:00 : 후평1동   13919 ----------


 ---------- 2015-05-17 12:00:00 : 동내면   13920 ----------


 ---------- 2015-05-17 14:00:00 : 남산면   13921 ----------


 ---------- 2015-05-17 21:00:00 : 후평1동   13922 ----------


 ---------- 2015-05-18 10:00:00 : 동내면   13923 ----------


 ---------- 2015-05-18 14:00:00 : 후평1동   13924 ----------


 ---------- 2015-05-18 17:00:00 : 석사동   13925 ----------


 ---------- 2015-05-18 21:00:00 : 퇴계동   13926 ----------


 ---------- 2015-05-20 04:00:00 : 석사동   13928 ----------


 ---------- 2015-05-20 07:00:00 : 강남동   13929 ----------


 ---------- 2015-05-20 21:00:00 : 서  면   13930 ----------


 ---------- 2015-05-21 06:00:00 : 석사동   13931 ----------


 ---------- 2015-05-21 06:00:00 : 사북면   13932 ----------


 ---------- 2015-05-21 08:00:00 : 석사동   13933 ----------


 ---------- 2015-05-21 09:00:00 : 퇴계동   13934 ----------


 ---------- 2015-05-21 10:00:00 : 석사동   13935 ----------


 ---------- 2015-05-21 14:00:00 : 석사동   13936 ----------


 ---------- 2015-05-21 22:00:00 : 강남동   13937 ----------


 ---------- 2015-05-22 03:00:00 : 후평1동   13938 ----------


 ---------- 2015-05-22 06:00:00 : 남산면   13939 ----------


 ---------- 2015-05-22 09:00:00 : 퇴계동   13940 ----------


 ---------- 2015-05-22 10:00:00 : 남산면   13942 ----------


 ---------- 2015-05-22 13:00:00 : 서  면   13944 ----------


 ---------- 2015-05-22 17:00:00 : 동내면   13945 ----------


 ---------- 2015-05-22 17:00:00 : 효자1동   13947 ----------


 ---------- 2015-05-23 09:00:00 : 남산면   13948 ----------


 ---------- 2015-05-23 09:00:00 : 동  면   13949 ----------


 ---------- 2015-05-23 10:00:00 : 남산면   13952 ----------


 ---------- 2015-05-23 11:00:00 : 효자1동   13953 ----------


 ---------- 2015-05-23 13:00:00 : 남산면   13954 ----------


 ---------- 2015-05-23 18:00:00 : 신사우동   13955 ----------


 ---------- 2015-05-24 11:00:00 : 남산면   13956 ----------


 ---------- 2015-05-24 12:00:00 : 남산면   13957 ----------


 ---------- 2015-05-24 14:00:00 : 서  면   13958 ----------


 ---------- 2015-05-24 22:00:00 : 강남동   13959 ----------


 ---------- 2015-05-24 23:00:00 : 후평1동   13960 ----------


 ---------- 2015-05-25 05:00:00 : 동내면   13961 ----------


 ---------- 2015-05-25 06:00:00 : 동  면   13962 ----------


 ---------- 2015-05-25 14:00:00 : 남산면   13963 ----------


 ---------- 2015-05-25 16:00:00 : 신동면   13964 ----------


 ---------- 2015-05-26 02:00:00 : 효자1동   13965 ----------


 ---------- 2015-05-26 08:00:00 : 효자1동   13966 ----------


 ---------- 2015-05-26 09:00:00 : 서  면   13967 ----------


 ---------- 2015-05-26 12:00:00 : 신북읍   13968 ----------


 ---------- 2015-05-26 14:00:00 : 동  면   13969 ----------


 ---------- 2015-05-26 15:00:00 : 강남동   13970 ----------


 ---------- 2015-05-26 20:00:00 : 퇴계동   13971 ----------


 ---------- 2015-05-26 21:00:00 : 석사동   13972 ----------


 ---------- 2015-05-27 06:00:00 : 북산면   13973 ----------


 ---------- 2015-05-27 10:00:00 : 신사우동   13974 ----------


 ---------- 2015-05-27 16:00:00 : 동내면   13975 ----------


 ---------- 2015-05-27 19:00:00 : 퇴계동   13976 ----------


 ---------- 2015-05-27 20:00:00 : 효자1동   13977 ----------


 ---------- 2015-05-27 22:00:00 : 후평1동   13978 ----------


 ---------- 2015-05-28 08:00:00 : 석사동   13979 ----------


 ---------- 2015-05-28 13:00:00 : 소양동   13980 ----------


 ---------- 2015-05-28 13:00:00 : 퇴계동   13981 ----------


 ---------- 2015-05-28 14:00:00 : 석사동   13983 ----------


 ---------- 2015-05-29 10:00:00 : 소양동   13984 ----------


 ---------- 2015-05-29 10:00:00 : 교  동   13985 ----------


 ---------- 2015-05-29 15:00:00 : 석사동   13987 ----------


 ---------- 2015-05-29 19:00:00 : 퇴계동   13988 ----------


 ---------- 2015-05-29 22:00:00 : 석사동   13989 ----------


 ---------- 2015-05-30 00:00:00 : 소양동   13990 ----------


 ---------- 2015-05-30 01:00:00 : 서  면   13991 ----------


 ---------- 2015-05-30 13:00:00 : 석사동   13992 ----------


 ---------- 2015-05-30 13:00:00 : 조운동   13993 ----------


 ---------- 2015-05-30 16:00:00 : 약사명동   13994 ----------


 ---------- 2015-05-31 02:00:00 : 신북읍   13995 ----------


 ---------- 2015-05-31 05:00:00 : 후평1동   13996 ----------


 ---------- 2015-05-31 06:00:00 : 동  면   13998 ----------


 ---------- 2015-05-31 15:00:00 : 강남동   14000 ----------


 ---------- 2015-05-31 23:00:00 : 후평1동   14001 ----------


 ---------- 2015-06-01 04:00:00 : 효자1동   14002 ----------


 ---------- 2015-06-01 11:00:00 : 후평1동   14003 ----------


 ---------- 2015-06-01 12:00:00 : 퇴계동   14004 ----------


 ---------- 2015-06-01 14:00:00 : 교  동   14005 ----------


 ---------- 2015-06-01 18:00:00 : 석사동   14006 ----------


 ---------- 2015-06-01 19:00:00 : 석사동   14007 ----------


 ---------- 2015-06-01 21:00:00 : 퇴계동   14008 ----------


 ---------- 2015-06-02 09:00:00 : 효자1동   14009 ----------


 ---------- 2015-06-02 16:00:00 : 효자1동   14010 ----------


 ---------- 2015-06-02 20:00:00 : 석사동   14011 ----------


 ---------- 2015-06-03 07:00:00 : 근화동   14012 ----------


 ---------- 2015-06-03 09:00:00 : 신북읍   14013 ----------


 ---------- 2015-06-03 13:00:00 : 남산면   14015 ----------


 ---------- 2015-06-03 16:00:00 : 후평1동   14016 ----------


 ---------- 2015-06-03 21:00:00 : 남산면   14018 ----------


 ---------- 2015-06-04 10:00:00 : 동내면   14019 ----------


 ---------- 2015-06-04 12:00:00 : 신사우동   14020 ----------


 ---------- 2015-06-04 16:00:00 : 조운동   14021 ----------


 ---------- 2015-06-04 23:00:00 : 효자1동   14022 ----------


 ---------- 2015-06-05 07:00:00 : 동내면   14024 ----------


 ---------- 2015-06-05 09:00:00 : 후평1동   14025 ----------


 ---------- 2015-06-05 15:00:00 : 후평1동   14026 ----------


 ---------- 2015-06-05 18:00:00 : 근화동   14027 ----------


 ---------- 2015-06-05 19:00:00 : 후평1동   14028 ----------


 ---------- 2015-06-06 01:00:00 : 효자1동   14029 ----------


 ---------- 2015-06-06 11:00:00 : 퇴계동   14031 ----------


 ---------- 2015-06-06 12:00:00 : 석사동   14032 ----------


 ---------- 2015-06-06 12:00:00 : 동내면   14033 ----------


 ---------- 2015-06-06 14:00:00 : 효자1동   14034 ----------


 ---------- 2015-06-06 17:00:00 : 동내면   14036 ----------


 ---------- 2015-06-06 17:00:00 : 신북읍   14038 ----------


 ---------- 2015-06-06 18:00:00 : 서  면   14039 ----------


 ---------- 2015-06-07 10:00:00 : 석사동   14040 ----------


 ---------- 2015-06-07 11:00:00 : 강남동   14041 ----------


 ---------- 2015-06-07 17:00:00 : 효자1동   14042 ----------

 ---------- 2015-06-07 20:00:00 : 강남동   14043 ----------


 ---------- 2015-06-08 19:00:00 : 동  면   14044 ----------


 ---------- 2015-06-08 23:00:00 : 효자1동   14045 ----------


 ---------- 2015-06-09 09:00:00 : 퇴계동   14046 ----------


 ---------- 2015-06-09 10:00:00 : 효자1동   14047 ----------


 ---------- 2015-06-09 12:00:00 : 효자1동   14048 ----------


 ---------- 2015-06-09 18:00:00 : 동내면   14049 ----------


 ---------- 2015-06-09 19:00:00 : 후평1동   14050 ----------


 ---------- 2015-06-09 20:00:00 : 동  면   14051 ----------


 ---------- 2015-06-10 06:00:00 : 후평1동   14052 ----------


 ---------- 2015-06-10 10:00:00 : 북산면   14053 ----------


 ---------- 2015-06-10 11:00:00 : 남산면   14054 ----------


 ---------- 2015-06-10 14:00:00 : 동내면   14055 ----------


 ---------- 2015-06-10 17:00:00 : 동  면   14056 ----------


 ---------- 2015-06-10 21:00:00 : 석사동   14057 ----------


 ---------- 2015-06-10 21:00:00 : 서  면   14058 ----------


 ---------- 2015-06-10 22:00:00 : 서  면   14059 ----------


 ---------- 2015-06-11 10:00:00 : 북산면   14060 ----------


 ---------- 2015-06-11 12:00:00 : 신사우동   14061 ----------


 ---------- 2015-06-11 17:00:00 : 동  면   14062 ----------


 ---------- 2015-06-11 18:00:00 : 신동면   14063 ----------


 ---------- 2015-06-11 18:00:00 : 남산면   14065 ----------


 ---------- 2015-06-12 10:00:00 : 남산면   14067 ----------


 ---------- 2015-06-12 20:00:00 : 약사명동   14069 ----------


 ---------- 2015-06-12 23:00:00 : 효자1동   14070 ----------


 ---------- 2015-06-13 00:00:00 : 후평1동   14071 ----------


 ---------- 2015-06-13 13:00:00 : 석사동   14072 ----------


 ---------- 2015-06-13 16:00:00 : 근화동   14073 ----------


 ---------- 2015-06-13 16:00:00 : 동  면   14074 ----------


 ---------- 2015-06-13 17:00:00 : 동  면   14075 ----------


 ---------- 2015-06-14 05:00:00 : 동내면   14076 ----------


 ---------- 2015-06-14 08:00:00 : 동산면   14078 ----------


 ---------- 2015-06-14 11:00:00 : 북산면   14080 ----------


 ---------- 2015-06-14 15:00:00 : 신사우동   14082 ----------


 ---------- 2015-06-14 17:00:00 : 효자1동   14083 ----------


 ---------- 2015-06-14 21:00:00 : 근화동   14085 ----------


 ---------- 2015-06-15 04:00:00 : 강남동   14086 ----------


 ---------- 2015-06-15 11:00:00 : 소양동   14087 ----------


 ---------- 2015-06-15 13:00:00 : 소양동   14088 ----------


 ---------- 2015-06-15 20:00:00 : 동산면   14089 ----------


 ---------- 2015-06-15 21:00:00 : 퇴계동   14090 ----------


 ---------- 2015-06-16 09:00:00 : 남산면   14091 ----------


 ---------- 2015-06-16 13:00:00 : 동  면   14092 ----------


 ---------- 2015-06-16 16:00:00 : 효자1동   14093 ----------


 ---------- 2015-06-17 08:00:00 : 남산면   14094 ----------


 ---------- 2015-06-17 09:00:00 : 석사동   14095 ----------


 ---------- 2015-06-17 15:00:00 : 북산면   14096 ----------


 ---------- 2015-06-17 17:00:00 : 사북면   14097 ----------


 ---------- 2015-06-17 18:00:00 : 퇴계동   14098 ----------


 ---------- 2015-06-18 05:00:00 : 효자1동   14100 ----------


 ---------- 2015-06-18 06:00:00 : 교  동   14101 ----------


 ---------- 2015-06-18 13:00:00 : 신사우동   14102 ----------


 ---------- 2015-06-18 18:00:00 : 강남동   14103 ----------


 ---------- 2015-06-18 22:00:00 : 후평1동   14105 ----------


 ---------- 2015-06-19 06:00:00 : 신북읍   14106 ----------


 ---------- 2015-06-19 07:00:00 : 사북면   14107 ----------


 ---------- 2015-06-19 07:00:00 : 동내면   14108 ----------


 ---------- 2015-06-19 14:00:00 : 퇴계동   14111 ----------


 ---------- 2015-06-19 20:00:00 : 석사동   14112 ----------


 ---------- 2015-06-19 21:00:00 : 신북읍   14114 ----------


 ---------- 2015-06-20 07:00:00 : 서  면   14115 ----------


 ---------- 2015-06-20 09:00:00 : 석사동   14116 ----------


 ---------- 2015-06-20 10:00:00 : 서  면   14118 ----------


 ---------- 2015-06-20 11:00:00 : 동내면   14119 ----------


 ---------- 2015-06-20 12:00:00 : 동내면   14120 ----------


 ---------- 2015-06-20 13:00:00 : 퇴계동   14121 ----------


 ---------- 2015-06-20 16:00:00 : 사북면   14122 ----------


 ---------- 2015-06-20 18:00:00 : 신동면   14123 ----------


 ---------- 2015-06-20 18:00:00 : 후평1동   14124 ----------


 ---------- 2015-06-20 19:00:00 : 동  면   14125 ----------


 ---------- 2015-06-20 22:00:00 : 신북읍   14127 ----------


 ---------- 2015-06-21 11:00:00 : 강남동   14128 ----------


 ---------- 2015-06-21 20:00:00 : 퇴계동   14130 ----------


 ---------- 2015-06-21 23:00:00 : 조운동   14131 ----------


 ---------- 2015-06-22 00:00:00 : 석사동   14132 ----------


 ---------- 2015-06-22 09:00:00 : 후평1동   14133 ----------


 ---------- 2015-06-22 13:00:00 : 서  면   14134 ----------


 ---------- 2015-06-22 14:00:00 : 석사동   14135 ----------


 ---------- 2015-06-22 16:00:00 : 남산면   14136 ----------


 ---------- 2015-06-22 17:00:00 : 후평1동   14137 ----------


 ---------- 2015-06-23 02:00:00 : 신북읍   14138 ----------


 ---------- 2015-06-23 06:00:00 : 퇴계동   14139 ----------


 ---------- 2015-06-23 09:00:00 : 신사우동   14141 ----------


 ---------- 2015-06-23 10:00:00 : 서  면   14142 ----------


 ---------- 2015-06-23 11:00:00 : 석사동   14143 ----------


 ---------- 2015-06-23 12:00:00 : 신동면   14145 ----------


 ---------- 2015-06-23 17:00:00 : 남산면   14146 ----------


 ---------- 2015-06-23 17:00:00 : 후평1동   14148 ----------


 ---------- 2015-06-24 02:00:00 : 동  면   14149 ----------


 ---------- 2015-06-24 06:00:00 : 조운동   14150 ----------


 ---------- 2015-06-24 09:00:00 : 신동면   14151 ----------


 ---------- 2015-06-24 10:00:00 : 동내면   14152 ----------


 ---------- 2015-06-24 13:00:00 : 서  면   14153 ----------


 ---------- 2015-06-24 15:00:00 : 서  면   14154 ----------


 ---------- 2015-06-24 15:00:00 : 남  면   14155 ----------


 ---------- 2015-06-24 15:00:00 : 신북읍   14157 ----------


 ---------- 2015-06-24 16:00:00 : 북산면   14158 ----------


 ---------- 2015-06-24 17:00:00 : 석사동   14159 ----------


 ---------- 2015-06-24 19:00:00 : 효자1동   14160 ----------


 ---------- 2015-06-24 19:00:00 : 북산면   14161 ----------


 ---------- 2015-06-24 19:00:00 : 교  동   14162 ----------


 ---------- 2015-06-24 20:00:00 : 북산면   14164 ----------


 ---------- 2015-06-25 01:00:00 : 약사명동   14165 ----------


 ---------- 2015-06-25 03:00:00 : 신사우동   14166 ----------


 ---------- 2015-06-25 07:00:00 : 서  면   14167 ----------


 ---------- 2015-06-25 10:00:00 : 북산면   14169 ----------


 ---------- 2015-06-25 14:00:00 : 남  면   14170 ----------


 ---------- 2015-06-25 22:00:00 : 근화동   14171 ----------


 ---------- 2015-06-25 23:00:00 : 동  면   14172 ----------


 ---------- 2015-06-26 01:00:00 : 석사동   14173 ----------


 ---------- 2015-06-26 12:00:00 : 퇴계동   14174 ----------


 ---------- 2015-06-26 13:00:00 : 동내면   14175 ----------


 ---------- 2015-06-26 17:00:00 : 동내면   14176 ----------


 ---------- 2015-06-26 19:00:00 : 후평1동   14177 ----------


 ---------- 2015-06-26 20:00:00 : 퇴계동   14178 ----------


 ---------- 2015-06-27 02:00:00 : 석사동   14179 ----------


 ---------- 2015-06-27 10:00:00 : 신동면   14180 ----------


 ---------- 2015-06-27 20:00:00 : 효자1동   14181 ----------


 ---------- 2015-06-28 02:00:00 : 석사동   14182 ----------


 ---------- 2015-06-28 07:00:00 : 효자1동   14183 ----------


 ---------- 2015-06-28 11:00:00 : 동내면   14184 ----------


 ---------- 2015-06-28 12:00:00 : 동내면   14185 ----------


 ---------- 2015-06-28 13:00:00 : 강남동   14186 ----------


 ---------- 2015-06-28 14:00:00 : 동  면   14188 ----------


 ---------- 2015-06-28 15:00:00 : 소양동   14189 ----------


 ---------- 2015-06-28 16:00:00 : 동  면   14190 ----------


 ---------- 2015-06-29 07:00:00 : 동내면   14191 ----------


 ---------- 2015-06-29 15:00:00 : 남  면   14192 ----------


 ---------- 2015-06-29 16:00:00 : 신사우동   14193 ----------


 ---------- 2015-06-30 10:00:00 : 근화동   14194 ----------


 ---------- 2015-06-30 11:00:00 : 석사동   14195 ----------


 ---------- 2015-06-30 14:00:00 : 교  동   14196 ----------


 ---------- 2015-06-30 15:00:00 : 북산면   14198 ----------


 ---------- 2015-06-30 16:00:00 : 후평1동   14199 ----------


 ---------- 2015-06-30 17:00:00 : 남산면   14201 ----------


 ---------- 2015-06-30 20:00:00 : 효자1동   14202 ----------

 ---------- 2015-06-30 21:00:00 : 동내면   14203 ----------


 ---------- 2015-06-30 21:00:00 : 북산면   14205 ----------


 ---------- 2015-07-01 07:00:00 : 동내면   14206 ----------


 ---------- 2015-07-01 08:00:00 : 강남동   14207 ----------


 ---------- 2015-07-01 09:00:00 : 효자1동   14208 ----------


 ---------- 2015-07-01 09:00:00 : 약사명동   14209 ----------


 ---------- 2015-07-01 10:00:00 : 강남동   14210 ----------


 ---------- 2015-07-01 10:00:00 : 남산면   14211 ----------


 ---------- 2015-07-01 11:00:00 : 퇴계동   14212 ----------


 ---------- 2015-07-01 12:00:00 : 남산면   14213 ----------


 ---------- 2015-07-01 12:00:00 : 동  면   14214 ----------


 ---------- 2015-07-01 13:00:00 : 석사동   14215 ----------


 ---------- 2015-07-01 14:00:00 : 동  면   14216 ----------


 ---------- 2015-07-01 15:00:00 : 석사동   14217 ----------


 ---------- 2015-07-01 17:00:00 : 남산면   14218 ----------


 ---------- 2015-07-01 21:00:00 : 후평1동   14219 ----------


 ---------- 2015-07-02 00:00:00 : 석사동   14220 ----------


 ---------- 2015-07-02 07:00:00 : 효자1동   14221 ----------


 ---------- 2015-07-02 09:00:00 : 효자1동   14223 ----------


 ---------- 2015-07-02 11:00:00 : 신북읍   14224 ----------


 ---------- 2015-07-02 13:00:00 : 사북면   14225 ----------


 ---------- 2015-07-02 16:00:00 : 동  면   14226 ----------


 ---------- 2015-07-02 17:00:00 : 석사동   14227 ----------


 ---------- 2015-07-02 17:00:00 : 효자1동   14228 ----------


 ---------- 2015-07-02 22:00:00 : 석사동   14229 ----------


 ---------- 2015-07-03 09:00:00 : 동  면   14230 ----------


 ---------- 2015-07-03 10:00:00 : 사북면   14231 ----------


 ---------- 2015-07-03 11:00:00 : 근화동   14232 ----------


 ---------- 2015-07-03 12:00:00 : 신동면   14234 ----------


 ---------- 2015-07-03 17:00:00 : 신동면   14236 ----------


 ---------- 2015-07-03 17:00:00 : 퇴계동   14238 ----------


 ---------- 2015-07-04 05:00:00 : 동  면   14239 ----------


 ---------- 2015-07-04 08:00:00 : 남산면   14240 ----------


 ---------- 2015-07-04 10:00:00 : 퇴계동   14241 ----------


 ---------- 2015-07-04 11:00:00 : 강남동   14242 ----------


 ---------- 2015-07-04 13:00:00 : 소양동   14243 ----------


 ---------- 2015-07-04 14:00:00 : 신동면   14244 ----------


 ---------- 2015-07-04 16:00:00 : 서  면   14245 ----------


 ---------- 2015-07-04 16:00:00 : 동산면   14246 ----------


 ---------- 2015-07-04 17:00:00 : 남산면   14247 ----------


 ---------- 2015-07-04 20:00:00 : 석사동   14248 ----------


 ---------- 2015-07-05 09:00:00 : 서  면   14249 ----------


 ---------- 2015-07-05 10:00:00 : 사북면   14251 ----------


 ---------- 2015-07-05 10:00:00 : 신사우동   14252 ----------


 ---------- 2015-07-05 12:00:00 : 남산면   14253 ----------


 ---------- 2015-07-05 14:00:00 : 강남동   14254 ----------


 ---------- 2015-07-05 14:00:00 : 북산면   14255 ----------


 ---------- 2015-07-05 23:00:00 : 동내면   14256 ----------


 ---------- 2015-07-06 08:00:00 : 서  면   14257 ----------


 ---------- 2015-07-06 08:00:00 : 퇴계동   14260 ----------


 ---------- 2015-07-06 09:00:00 : 신동면   14261 ----------


 ---------- 2015-07-06 09:00:00 : 사북면   14262 ----------


 ---------- 2015-07-06 09:00:00 : 퇴계동   14263 ----------


 ---------- 2015-07-06 11:00:00 : 남산면   14264 ----------


 ---------- 2015-07-06 12:00:00 : 효자1동   14265 ----------


 ---------- 2015-07-06 13:00:00 : 강남동   14266 ----------


 ---------- 2015-07-06 13:00:00 : 퇴계동   14267 ----------


 ---------- 2015-07-06 14:00:00 : 사북면   14269 ----------


 ---------- 2015-07-06 14:00:00 : 신사우동   14270 ----------


 ---------- 2015-07-06 15:00:00 : 석사동   14271 ----------


 ---------- 2015-07-06 19:00:00 : 사북면   14272 ----------


 ---------- 2015-07-07 07:00:00 : 남산면   14273 ----------


 ---------- 2015-07-07 10:00:00 : 사북면   14274 ----------


 ---------- 2015-07-07 10:00:00 : 퇴계동   14276 ----------


 ---------- 2015-07-07 12:00:00 : 남산면   14277 ----------


 ---------- 2015-07-07 12:00:00 : 신사우동   14278 ----------


 ---------- 2015-07-07 14:00:00 : 신북읍   14279 ----------


 ---------- 2015-07-07 14:00:00 : 후평1동   14280 ----------


 ---------- 2015-07-07 14:00:00 : 퇴계동   14281 ----------


 ---------- 2015-07-07 16:00:00 : 남산면   14282 ----------


 ---------- 2015-07-07 17:00:00 : 사북면   14283 ----------


 ---------- 2015-07-07 18:00:00 : 근화동   14284 ----------


 ---------- 2015-07-07 18:00:00 : 동  면   14285 ----------


 ---------- 2015-07-08 02:00:00 : 약사명동   14287 ----------


 ---------- 2015-07-08 15:00:00 : 남산면   14288 ----------


 ---------- 2015-07-08 20:00:00 : 소양동   14290 ----------


 ---------- 2015-07-08 22:00:00 : 석사동   14291 ----------


 ---------- 2015-07-09 09:00:00 : 근화동   14292 ----------


 ---------- 2015-07-09 10:00:00 : 서  면   14293 ----------


 ---------- 2015-07-09 11:00:00 : 동  면   14294 ----------


 ---------- 2015-07-09 13:00:00 : 남산면   14295 ----------


 ---------- 2015-07-09 14:00:00 : 퇴계동   14296 ----------


 ---------- 2015-07-09 17:00:00 : 퇴계동   14297 ----------


 ---------- 2015-07-09 20:00:00 : 북산면   14299 ----------


 ---------- 2015-07-10 01:00:00 : 신사우동   14300 ----------


 ---------- 2015-07-10 09:00:00 : 석사동   14302 ----------


 ---------- 2015-07-10 09:00:00 : 남산면   14303 ----------


 ---------- 2015-07-10 09:00:00 : 신사우동   14304 ----------


 ---------- 2015-07-10 10:00:00 : 동내면   14305 ----------


 ---------- 2015-07-10 11:00:00 : 강남동   14307 ----------


 ---------- 2015-07-10 11:00:00 : 남  면   14309 ----------


 ---------- 2015-07-10 12:00:00 : 강남동   14311 ----------


 ---------- 2015-07-10 12:00:00 : 약사명동   14312 ----------


 ---------- 2015-07-10 13:00:00 : 동  면   14313 ----------


 ---------- 2015-07-10 15:00:00 : 서  면   14314 ----------


 ---------- 2015-07-10 15:00:00 : 근화동   14315 ----------


 ---------- 2015-07-10 17:00:00 : 사북면   14316 ----------


 ---------- 2015-07-10 17:00:00 : 퇴계동   14317 ----------


 ---------- 2015-07-10 18:00:00 : 강남동   14318 ----------


 ---------- 2015-07-10 18:00:00 : 신사우동   14321 ----------


 ---------- 2015-07-11 02:00:00 : 강남동   14322 ----------


 ---------- 2015-07-11 04:00:00 : 남산면   14323 ----------


 ---------- 2015-07-11 09:00:00 : 사북면   14324 ----------


 ---------- 2015-07-11 10:00:00 : 사북면   14325 ----------


 ---------- 2015-07-11 11:00:00 : 강남동   14326 ----------


 ---------- 2015-07-11 11:00:00 : 서  면   14327 ----------


 ---------- 2015-07-11 13:00:00 : 남산면   14328 ----------


 ---------- 2015-07-11 15:00:00 : 남산면   14330 ----------


 ---------- 2015-07-12 02:00:00 : 근화동   14331 ----------


 ---------- 2015-07-12 02:00:00 : 동  면   14332 ----------


 ---------- 2015-07-12 09:00:00 : 근화동   14333 ----------


 ---------- 2015-07-12 16:00:00 : 석사동   14334 ----------


 ---------- 2015-07-12 18:00:00 : 효자1동   14336 ----------


 ---------- 2015-07-13 01:00:00 : 강남동   14337 ----------


 ---------- 2015-07-13 06:00:00 : 퇴계동   14338 ----------


 ---------- 2015-07-13 08:00:00 : 사북면   14339 ----------


 ---------- 2015-07-13 10:00:00 : 남산면   14340 ----------


 ---------- 2015-07-13 11:00:00 : 강남동   14341 ----------


 ---------- 2015-07-13 12:00:00 : 석사동   14342 ----------


 ---------- 2015-07-13 16:00:00 : 남  면   14343 ----------


 ---------- 2015-07-13 17:00:00 : 동  면   14344 ----------


 ---------- 2015-07-14 08:00:00 : 남산면   14345 ----------


 ---------- 2015-07-14 10:00:00 : 서  면   14346 ----------


 ---------- 2015-07-14 10:00:00 : 소양동   14347 ----------


 ---------- 2015-07-14 11:00:00 : 서  면   14348 ----------


 ---------- 2015-07-14 12:00:00 : 서  면   14349 ----------


 ---------- 2015-07-14 13:00:00 : 동  면   14350 ----------


 ---------- 2015-07-14 17:00:00 : 강남동   14351 ----------


 ---------- 2015-07-14 18:00:00 : 소양동   14352 ----------


 ---------- 2015-07-14 19:00:00 : 소양동   14353 ----------


 ---------- 2015-07-15 09:00:00 : 남  면   14354 ----------


 ---------- 2015-07-15 10:00:00 : 강남동   14355 ----------


 ---------- 2015-07-15 11:00:00 : 근화동   14356 ----------


 ---------- 2015-07-15 14:00:00 : 남산면   14357 ----------


 ---------- 2015-07-15 15:00:00 : 서  면   14358 ----------


 ---------- 2015-07-15 16:00:00 : 신북읍   14359 ----------

 ---------- 2015-07-15 20:00:00 : 석사동   14360 ----------


 ---------- 2015-07-16 02:00:00 : 소양동   14362 ----------


 ---------- 2015-07-16 05:00:00 : 강남동   14363 ----------


 ---------- 2015-07-16 09:00:00 : 강남동   14364 ----------


 ---------- 2015-07-16 10:00:00 : 서  면   14365 ----------


 ---------- 2015-07-16 10:00:00 : 남  면   14366 ----------


 ---------- 2015-07-16 11:00:00 : 남  면   14367 ----------


 ---------- 2015-07-16 12:00:00 : 서  면   14368 ----------


 ---------- 2015-07-16 12:00:00 : 남산면   14369 ----------


 ---------- 2015-07-16 12:00:00 : 신사우동   14370 ----------


 ---------- 2015-07-16 17:00:00 : 서  면   14371 ----------


 ---------- 2015-07-16 17:00:00 : 동  면   14372 ----------


 ---------- 2015-07-16 18:00:00 : 후평1동   14373 ----------


 ---------- 2015-07-16 19:00:00 : 동산면   14374 ----------


 ---------- 2015-07-16 20:00:00 : 근화동   14375 ----------


 ---------- 2015-07-17 01:00:00 : 후평1동   14376 ----------


 ---------- 2015-07-17 08:00:00 : 서  면   14377 ----------


 ---------- 2015-07-17 09:00:00 : 신북읍   14378 ----------


 ---------- 2015-07-17 09:00:00 : 동  면   14379 ----------


 ---------- 2015-07-17 10:00:00 : 서  면   14380 ----------


 ---------- 2015-07-17 10:00:00 : 소양동   14381 ----------


 ---------- 2015-07-17 11:00:00 : 사북면   14382 ----------


 ---------- 2015-07-17 12:00:00 : 사북면   14383 ----------


 ---------- 2015-07-17 13:00:00 : 효자1동   14384 ----------


 ---------- 2015-07-17 13:00:00 : 남산면   14386 ----------


 ---------- 2015-07-17 14:00:00 : 남산면   14387 ----------


 ---------- 2015-07-17 17:00:00 : 남산면   14388 ----------


 ---------- 2015-07-17 18:00:00 : 사북면   14389 ----------


 ---------- 2015-07-17 18:00:00 : 효자1동   14390 ----------


 ---------- 2015-07-18 05:00:00 : 동내면   14391 ----------


 ---------- 2015-07-18 07:00:00 : 동내면   14392 ----------


 ---------- 2015-07-18 09:00:00 : 사북면   14393 ----------


 ---------- 2015-07-18 10:00:00 : 동  면   14394 ----------


 ---------- 2015-07-18 11:00:00 : 동내면   14395 ----------


 ---------- 2015-07-18 12:00:00 : 신동면   14396 ----------


 ---------- 2015-07-18 12:00:00 : 사북면   14397 ----------


 ---------- 2015-07-18 12:00:00 : 동내면   14399 ----------


 ---------- 2015-07-18 13:00:00 : 서  면   14400 ----------


 ---------- 2015-07-18 14:00:00 : 동내면   14402 ----------


 ---------- 2015-07-18 14:00:00 : 남산면   14403 ----------


 ---------- 2015-07-18 15:00:00 : 사북면   14404 ----------


 ---------- 2015-07-18 15:00:00 : 동산면   14405 ----------


 ---------- 2015-07-18 16:00:00 : 약사명동   14406 ----------


 ---------- 2015-07-19 09:00:00 : 서  면   14407 ----------


 ---------- 2015-07-19 10:00:00 : 사북면   14408 ----------


 ---------- 2015-07-19 11:00:00 : 퇴계동   14409 ----------


 ---------- 2015-07-19 12:00:00 : 석사동   14410 ----------


 ---------- 2015-07-19 13:00:00 : 동  면   14411 ----------


 ---------- 2015-07-19 17:00:00 : 동  면   14412 ----------


 ---------- 2015-07-19 20:00:00 : 효자1동   14413 ----------


 ---------- 2015-07-19 21:00:00 : 사북면   14414 ----------


 ---------- 2015-07-19 21:00:00 : 후평1동   14416 ----------


 ---------- 2015-07-19 22:00:00 : 후평1동   14417 ----------


 ---------- 2015-07-20 08:00:00 : 서  면   14418 ----------


 ---------- 2015-07-20 09:00:00 : 서  면   14419 ----------


 ---------- 2015-07-20 09:00:00 : 동  면   14421 ----------


 ---------- 2015-07-20 10:00:00 : 서  면   14423 ----------


 ---------- 2015-07-20 11:00:00 : 석사동   14424 ----------


 ---------- 2015-07-20 11:00:00 : 강남동   14425 ----------


 ---------- 2015-07-20 11:00:00 : 효자1동   14426 ----------


 ---------- 2015-07-20 14:00:00 : 석사동   14427 ----------


 ---------- 2015-07-20 15:00:00 : 효자1동   14428 ----------


 ---------- 2015-07-20 15:00:00 : 남산면   14429 ----------


 ---------- 2015-07-20 15:00:00 : 신북읍   14430 ----------


 ---------- 2015-07-20 15:00:00 : 후평1동   14431 ----------


 ---------- 2015-07-20 15:00:00 : 퇴계동   14433 ----------


 ---------- 2015-07-20 16:00:00 : 동  면   14434 ----------


 ---------- 2015-07-20 22:00:00 : 후평1동   14435 ----------


 ---------- 2015-07-21 00:00:00 : 효자1동   14436 ----------


 ---------- 2015-07-21 06:00:00 : 동  면   14437 ----------


 ---------- 2015-07-21 08:00:00 : 후평1동   14438 ----------


 ---------- 2015-07-21 09:00:00 : 남  면   14439 ----------


 ---------- 2015-07-21 09:00:00 : 동  면   14440 ----------


 ---------- 2015-07-21 10:00:00 : 동산면   14441 ----------


 ---------- 2015-07-21 11:00:00 : 서  면   14442 ----------


 ---------- 2015-07-21 13:00:00 : 신동면   14443 ----------


 ---------- 2015-07-21 13:00:00 : 근화동   14444 ----------


 ---------- 2015-07-21 13:00:00 : 신북읍   14445 ----------


 ---------- 2015-07-21 16:00:00 : 남  면   14446 ----------


 ---------- 2015-07-21 16:00:00 : 효자1동   14447 ----------


 ---------- 2015-07-21 17:00:00 : 신북읍   14448 ----------


 ---------- 2015-07-21 20:00:00 : 남산면   14449 ----------


 ---------- 2015-07-22 06:00:00 : 동  면   14450 ----------


 ---------- 2015-07-22 08:00:00 : 후평1동   14451 ----------


 ---------- 2015-07-22 10:00:00 : 사북면   14452 ----------


 ---------- 2015-07-22 10:00:00 : 남산면   14453 ----------


 ---------- 2015-07-22 12:00:00 : 신사우동   14454 ----------


 ---------- 2015-07-22 13:00:00 : 소양동   14455 ----------


 ---------- 2015-07-22 13:00:00 : 동  면   14456 ----------


 ---------- 2015-07-22 15:00:00 : 서  면   14457 ----------


 ---------- 2015-07-22 16:00:00 : 서  면   14458 ----------


 ---------- 2015-07-22 18:00:00 : 퇴계동   14459 ----------


 ---------- 2015-07-22 22:00:00 : 동  면   14460 ----------


 ---------- 2015-07-23 08:00:00 : 효자1동   14461 ----------


 ---------- 2015-07-23 09:00:00 : 남산면   14462 ----------


 ---------- 2015-07-23 09:00:00 : 북산면   14463 ----------


 ---------- 2015-07-23 10:00:00 : 북산면   14464 ----------


 ---------- 2015-07-23 11:00:00 : 남산면   14465 ----------


 ---------- 2015-07-23 13:00:00 : 소양동   14466 ----------


 ---------- 2015-07-23 13:00:00 : 퇴계동   14467 ----------


 ---------- 2015-07-23 14:00:00 : 신동면   14468 ----------


 ---------- 2015-07-23 14:00:00 : 남산면   14469 ----------


 ---------- 2015-07-23 15:00:00 : 서  면   14470 ----------


 ---------- 2015-07-23 16:00:00 : 서  면   14471 ----------


 ---------- 2015-07-23 16:00:00 : 신북읍   14472 ----------


 ---------- 2015-07-23 17:00:00 : 동  면   14473 ----------


 ---------- 2015-07-23 19:00:00 : 후평1동   14475 ----------


 ---------- 2015-07-24 02:00:00 : 석사동   14476 ----------


 ---------- 2015-07-24 08:00:00 : 효자1동   14477 ----------


 ---------- 2015-07-24 09:00:00 : 사북면   14478 ----------


 ---------- 2015-07-24 11:00:00 : 동내면   14479 ----------


 ---------- 2015-07-24 11:00:00 : 효자1동   14480 ----------


 ---------- 2015-07-24 12:00:00 : 서  면   14481 ----------


 ---------- 2015-07-24 12:00:00 : 남산면   14482 ----------


 ---------- 2015-07-24 12:00:00 : 동산면   14483 ----------


 ---------- 2015-07-24 14:00:00 : 남산면   14484 ----------


 ---------- 2015-07-24 14:00:00 : 소양동   14486 ----------


 ---------- 2015-07-24 15:00:00 : 교  동   14487 ----------


 ---------- 2015-07-24 16:00:00 : 후평1동   14488 ----------


 ---------- 2015-07-24 19:00:00 : 동내면   14489 ----------


 ---------- 2015-07-24 22:00:00 : 사북면   14490 ----------


 ---------- 2015-07-25 05:00:00 : 남  면   14492 ----------


 ---------- 2015-07-25 06:00:00 : 남  면   14493 ----------


 ---------- 2015-07-25 09:00:00 : 소양동   14494 ----------


 ---------- 2015-07-25 09:00:00 : 북산면   14495 ----------


 ---------- 2015-07-25 10:00:00 : 효자1동   14496 ----------


 ---------- 2015-07-25 11:00:00 : 석사동   14499 ----------


 ---------- 2015-07-25 12:00:00 : 남산면   14500 ----------


 ---------- 2015-07-25 13:00:00 : 신사우동   14501 ----------


 ---------- 2015-07-25 16:00:00 : 동  면   14502 ----------


 ---------- 2015-07-25 17:00:00 : 남산면   14504 ----------


 ---------- 2015-07-26 00:00:00 : 퇴계동   14505 ----------


 ---------- 2015-07-26 09:00:00 : 동내면   14506 ----------


 ---------- 2015-07-26 09:00:00 : 남산면   14507 ----------


 ---------- 2015-07-26 09:00:00 : 북산면   14508 ----------


 ---------- 2015-07-26 10:00:00 : 사북면   14509 ----------

 ---------- 2015-07-26 10:00:00 : 퇴계동   14510 ----------


 ---------- 2015-07-26 10:00:00 : 동산면   14511 ----------


 ---------- 2015-07-26 12:00:00 : 사북면   14512 ----------


 ---------- 2015-07-26 13:00:00 : 남산면   14513 ----------


 ---------- 2015-07-26 13:00:00 : 약사명동   14514 ----------


 ---------- 2015-07-26 15:00:00 : 소양동   14515 ----------


 ---------- 2015-07-26 15:00:00 : 동  면   14516 ----------


 ---------- 2015-07-26 16:00:00 : 신동면   14517 ----------


 ---------- 2015-07-26 16:00:00 : 강남동   14518 ----------


 ---------- 2015-07-26 17:00:00 : 남산면   14519 ----------


 ---------- 2015-07-26 19:00:00 : 퇴계동   14520 ----------


 ---------- 2015-07-26 20:00:00 : 효자1동   14521 ----------


 ---------- 2015-07-27 02:00:00 : 동내면   14522 ----------


 ---------- 2015-07-27 07:00:00 : 근화동   14523 ----------


 ---------- 2015-07-27 07:00:00 : 동  면   14524 ----------


 ---------- 2015-07-27 08:00:00 : 동내면   14525 ----------


 ---------- 2015-07-27 08:00:00 : 조운동   14526 ----------


 ---------- 2015-07-27 11:00:00 : 강남동   14527 ----------


 ---------- 2015-07-27 11:00:00 : 신사우동   14528 ----------


 ---------- 2015-07-27 11:00:00 : 소양동   14529 ----------


 ---------- 2015-07-27 12:00:00 : 동내면   14530 ----------


 ---------- 2015-07-27 12:00:00 : 남산면   14531 ----------


 ---------- 2015-07-27 13:00:00 : 강남동   14532 ----------


 ---------- 2015-07-27 13:00:00 : 동  면   14533 ----------


 ---------- 2015-07-27 13:00:00 : 동산면   14534 ----------


 ---------- 2015-07-27 15:00:00 : 효자1동   14535 ----------


 ---------- 2015-07-27 15:00:00 : 남산면   14536 ----------


 ---------- 2015-07-27 17:00:00 : 동산면   14537 ----------


 ---------- 2015-07-27 18:00:00 : 동  면   14538 ----------


 ---------- 2015-07-27 20:00:00 : 강남동   14539 ----------


 ---------- 2015-07-27 20:00:00 : 남산면   14540 ----------


 ---------- 2015-07-28 08:00:00 : 강남동   14541 ----------


 ---------- 2015-07-28 08:00:00 : 동내면   14542 ----------


 ---------- 2015-07-28 08:00:00 : 동  면   14543 ----------


 ---------- 2015-07-28 09:00:00 : 동내면   14544 ----------


 ---------- 2015-07-28 09:00:00 : 동  면   14545 ----------


 ---------- 2015-07-28 10:00:00 : 서  면   14546 ----------


 ---------- 2015-07-28 11:00:00 : 동  면   14547 ----------


 ---------- 2015-07-28 11:00:00 : 후평1동   14548 ----------


 ---------- 2015-07-28 12:00:00 : 석사동   14550 ----------


 ---------- 2015-07-28 12:00:00 : 서  면   14551 ----------


 ---------- 2015-07-28 12:00:00 : 교  동   14552 ----------


 ---------- 2015-07-28 13:00:00 : 서  면   14553 ----------


 ---------- 2015-07-28 14:00:00 : 석사동   14554 ----------


 ---------- 2015-07-28 14:00:00 : 신북읍   14555 ----------


 ---------- 2015-07-28 14:00:00 : 동  면   14556 ----------


 ---------- 2015-07-28 15:00:00 : 남  면   14557 ----------


 ---------- 2015-07-28 15:00:00 : 퇴계동   14558 ----------


 ---------- 2015-07-28 18:00:00 : 북산면   14559 ----------


 ---------- 2015-07-29 10:00:00 : 강남동   14560 ----------


 ---------- 2015-07-29 11:00:00 : 퇴계동   14561 ----------


 ---------- 2015-07-29 13:00:00 : 서  면   14562 ----------


 ---------- 2015-07-29 13:00:00 : 동  면   14563 ----------


 ---------- 2015-07-29 14:00:00 : 퇴계동   14564 ----------


 ---------- 2015-07-29 14:00:00 : 북산면   14565 ----------


 ---------- 2015-07-29 15:00:00 : 동내면   14566 ----------


 ---------- 2015-07-29 15:00:00 : 신사우동   14569 ----------


 ---------- 2015-07-30 00:00:00 : 후평1동   14571 ----------


 ---------- 2015-07-30 01:00:00 : 소양동   14572 ----------


 ---------- 2015-07-30 09:00:00 : 강남동   14573 ----------


 ---------- 2015-07-30 09:00:00 : 서  면   14575 ----------


 ---------- 2015-07-30 09:00:00 : 남  면   14576 ----------


 ---------- 2015-07-30 09:00:00 : 사북면   14577 ----------


 ---------- 2015-07-30 09:00:00 : 동내면   14578 ----------


 ---------- 2015-07-30 09:00:00 : 효자1동   14580 ----------


 ---------- 2015-07-30 10:00:00 : 동내면   14581 ----------


 ---------- 2015-07-30 10:00:00 : 동산면   14582 ----------


 ---------- 2015-07-30 13:00:00 : 강남동   14583 ----------


 ---------- 2015-07-30 14:00:00 : 사북면   14584 ----------


 ---------- 2015-07-30 18:00:00 : 남산면   14585 ----------


 ---------- 2015-07-30 20:00:00 : 서  면   14587 ----------


 ---------- 2015-07-31 09:00:00 : 강남동   14588 ----------


 ---------- 2015-07-31 09:00:00 : 서  면   14589 ----------


 ---------- 2015-07-31 09:00:00 : 남  면   14590 ----------


 ---------- 2015-07-31 11:00:00 : 사북면   14591 ----------


 ---------- 2015-07-31 11:00:00 : 신북읍   14592 ----------


 ---------- 2015-07-31 11:00:00 : 약사명동   14593 ----------


 ---------- 2015-07-31 12:00:00 : 남산면   14594 ----------


 ---------- 2015-07-31 12:00:00 : 동  면   14595 ----------


 ---------- 2015-07-31 12:00:00 : 퇴계동   14596 ----------


 ---------- 2015-07-31 13:00:00 : 신동면   14597 ----------


 ---------- 2015-07-31 13:00:00 : 남산면   14598 ----------


 ---------- 2015-07-31 13:00:00 : 동  면   14599 ----------


 ---------- 2015-07-31 13:00:00 : 동산면   14600 ----------


 ---------- 2015-07-31 14:00:00 : 서  면   14601 ----------


 ---------- 2015-07-31 14:00:00 : 신북읍   14602 ----------


 ---------- 2015-07-31 15:00:00 : 퇴계동   14604 ----------


 ---------- 2015-07-31 22:00:00 : 효자1동   14605 ----------


 ---------- 2015-08-01 06:00:00 : 효자1동   14606 ----------


 ---------- 2015-08-01 07:00:00 : 사북면   14607 ----------


 ---------- 2015-08-01 08:00:00 : 석사동   14608 ----------


 ---------- 2015-08-01 08:00:00 : 동내면   14609 ----------


 ---------- 2015-08-01 09:00:00 : 신동면   14610 ----------


 ---------- 2015-08-01 09:00:00 : 강남동   14612 ----------


 ---------- 2015-08-01 09:00:00 : 북산면   14613 ----------


 ---------- 2015-08-01 09:00:00 : 동산면   14614 ----------


 ---------- 2015-08-01 10:00:00 : 남산면   14615 ----------


 ---------- 2015-08-01 11:00:00 : 동내면   14616 ----------


 ---------- 2015-08-01 11:00:00 : 동  면   14617 ----------


 ---------- 2015-08-01 11:00:00 : 북산면   14618 ----------


 ---------- 2015-08-01 13:00:00 : 석사동   14619 ----------


 ---------- 2015-08-01 13:00:00 : 사북면   14620 ----------


 ---------- 2015-08-01 13:00:00 : 동내면   14621 ----------


 ---------- 2015-08-01 13:00:00 : 남산면   14622 ----------


 ---------- 2015-08-01 14:00:00 : 동내면   14623 ----------


 ---------- 2015-08-01 15:00:00 : 사북면   14624 ----------


 ---------- 2015-08-01 15:00:00 : 신사우동   14625 ----------


 ---------- 2015-08-01 16:00:00 : 신사우동   14626 ----------


 ---------- 2015-08-01 17:00:00 : 서  면   14627 ----------


 ---------- 2015-08-01 17:00:00 : 남산면   14628 ----------


 ---------- 2015-08-01 17:00:00 : 신사우동   14629 ----------


 ---------- 2015-08-01 18:00:00 : 남산면   14630 ----------


 ---------- 2015-08-01 19:00:00 : 신동면   14631 ----------


 ---------- 2015-08-01 19:00:00 : 동내면   14632 ----------


 ---------- 2015-08-01 21:00:00 : 석사동   14633 ----------


 ---------- 2015-08-01 23:00:00 : 후평1동   14634 ----------


 ---------- 2015-08-02 00:00:00 : 소양동   14635 ----------


 ---------- 2015-08-02 00:00:00 : 퇴계동   14637 ----------


 ---------- 2015-08-02 07:00:00 : 신사우동   14638 ----------


 ---------- 2015-08-02 08:00:00 : 석사동   14639 ----------


 ---------- 2015-08-02 08:00:00 : 신동면   14640 ----------


 ---------- 2015-08-02 08:00:00 : 남  면   14641 ----------


 ---------- 2015-08-02 09:00:00 : 북산면   14642 ----------


 ---------- 2015-08-02 10:00:00 : 북산면   14643 ----------


 ---------- 2015-08-02 11:00:00 : 동내면   14644 ----------


 ---------- 2015-08-02 11:00:00 : 남산면   14645 ----------


 ---------- 2015-08-02 13:00:00 : 신동면   14646 ----------


 ---------- 2015-08-02 13:00:00 : 동  면   14647 ----------


 ---------- 2015-08-02 13:00:00 : 후평1동   14648 ----------


 ---------- 2015-08-02 15:00:00 : 남산면   14649 ----------


 ---------- 2015-08-02 16:00:00 : 남  면   14650 ----------


 ---------- 2015-08-03 09:00:00 : 강남동   14651 ----------


 ---------- 2015-08-03 09:00:00 : 사북면   14653 ----------


 ---------- 2015-08-03 09:00:00 : 효자1동   14655 ----------


 ---------- 2015-08-03 09:00:00 : 근화동   14656 ----------


 ---------- 2015-08-03 09:00:00 : 퇴계동   14658 ----------


 ---------- 2015-08-03 10:00:00 : 사북면   14659 ----------

 ---------- 2015-08-03 11:00:00 : 남  면   14660 ----------


 ---------- 2015-08-03 11:00:00 : 동  면   14661 ----------


 ---------- 2015-08-03 12:00:00 : 신동면   14662 ----------


 ---------- 2015-08-03 13:00:00 : 신동면   14663 ----------


 ---------- 2015-08-03 14:00:00 : 강남동   14664 ----------


 ---------- 2015-08-03 14:00:00 : 남산면   14665 ----------


 ---------- 2015-08-03 15:00:00 : 사북면   14666 ----------


 ---------- 2015-08-03 18:00:00 : 후평1동   14667 ----------


 ---------- 2015-08-03 18:00:00 : 퇴계동   14668 ----------


 ---------- 2015-08-03 19:00:00 : 효자1동   14669 ----------


 ---------- 2015-08-03 22:00:00 : 소양동   14670 ----------


 ---------- 2015-08-04 07:00:00 : 동내면   14671 ----------


 ---------- 2015-08-04 07:00:00 : 신사우동   14672 ----------


 ---------- 2015-08-04 08:00:00 : 신동면   14673 ----------


 ---------- 2015-08-04 08:00:00 : 서  면   14675 ----------


 ---------- 2015-08-04 08:00:00 : 남  면   14676 ----------


 ---------- 2015-08-04 09:00:00 : 동내면   14677 ----------


 ---------- 2015-08-04 10:00:00 : 동  면   14678 ----------


 ---------- 2015-08-04 11:00:00 : 소양동   14679 ----------


 ---------- 2015-08-04 12:00:00 : 신동면   14680 ----------


 ---------- 2015-08-04 12:00:00 : 서  면   14681 ----------


 ---------- 2015-08-04 13:00:00 : 강남동   14682 ----------


 ---------- 2015-08-04 14:00:00 : 동  면   14684 ----------


 ---------- 2015-08-04 15:00:00 : 동내면   14685 ----------


 ---------- 2015-08-04 15:00:00 : 신사우동   14686 ----------


 ---------- 2015-08-04 16:00:00 : 강남동   14687 ----------


 ---------- 2015-08-04 16:00:00 : 남산면   14688 ----------


 ---------- 2015-08-04 20:00:00 : 남산면   14689 ----------


 ---------- 2015-08-05 09:00:00 : 강남동   14690 ----------


 ---------- 2015-08-05 09:00:00 : 서  면   14691 ----------


 ---------- 2015-08-05 09:00:00 : 신북읍   14692 ----------


 ---------- 2015-08-05 09:00:00 : 퇴계동   14693 ----------


 ---------- 2015-08-05 10:00:00 : 강남동   14694 ----------


 ---------- 2015-08-05 10:00:00 : 남산면   14695 ----------


 ---------- 2015-08-05 10:00:00 : 후평1동   14696 ----------


 ---------- 2015-08-05 11:00:00 : 효자1동   14697 ----------


 ---------- 2015-08-05 12:00:00 : 남산면   14698 ----------


 ---------- 2015-08-05 12:00:00 : 동  면   14699 ----------


 ---------- 2015-08-05 13:00:00 : 서  면   14700 ----------


 ---------- 2015-08-05 13:00:00 : 남산면   14702 ----------


 ---------- 2015-08-05 14:00:00 : 동내면   14703 ----------


 ---------- 2015-08-05 14:00:00 : 남산면   14704 ----------


 ---------- 2015-08-05 14:00:00 : 근화동   14705 ----------


 ---------- 2015-08-05 14:00:00 : 동  면   14706 ----------


 ---------- 2015-08-05 16:00:00 : 남  면   14707 ----------


 ---------- 2015-08-05 16:00:00 : 신북읍   14708 ----------


 ---------- 2015-08-05 21:00:00 : 남산면   14710 ----------


 ---------- 2015-08-06 09:00:00 : 서  면   14711 ----------


 ---------- 2015-08-06 09:00:00 : 남산면   14712 ----------


 ---------- 2015-08-06 10:00:00 : 남  면   14713 ----------


 ---------- 2015-08-06 11:00:00 : 남  면   14714 ----------


 ---------- 2015-08-06 12:00:00 : 서  면   14715 ----------


 ---------- 2015-08-06 13:00:00 : 석사동   14716 ----------


 ---------- 2015-08-06 13:00:00 : 신동면   14717 ----------


 ---------- 2015-08-06 13:00:00 : 서  면   14718 ----------


 ---------- 2015-08-06 13:00:00 : 남산면   14719 ----------


 ---------- 2015-08-06 13:00:00 : 신북읍   14720 ----------


 ---------- 2015-08-06 14:00:00 : 동  면   14721 ----------


 ---------- 2015-08-06 14:00:00 : 퇴계동   14722 ----------


 ---------- 2015-08-06 15:00:00 : 남산면   14724 ----------


 ---------- 2015-08-06 15:00:00 : 신사우동   14725 ----------


 ---------- 2015-08-06 15:00:00 : 동  면   14726 ----------


 ---------- 2015-08-06 17:00:00 : 동  면   14729 ----------


 ---------- 2015-08-06 18:00:00 : 남  면   14730 ----------


 ---------- 2015-08-06 19:00:00 : 효자1동   14731 ----------


 ---------- 2015-08-06 21:00:00 : 남산면   14732 ----------


 ---------- 2015-08-07 07:00:00 : 근화동   14733 ----------


 ---------- 2015-08-07 08:00:00 : 효자1동   14734 ----------


 ---------- 2015-08-07 09:00:00 : 강남동   14735 ----------


 ---------- 2015-08-07 09:00:00 : 퇴계동   14736 ----------


 ---------- 2015-08-07 09:00:00 : 동산면   14737 ----------


 ---------- 2015-08-07 10:00:00 : 강남동   14738 ----------


 ---------- 2015-08-07 10:00:00 : 사북면   14739 ----------


 ---------- 2015-08-07 10:00:00 : 효자1동   14740 ----------


 ---------- 2015-08-07 11:00:00 : 동내면   14741 ----------


 ---------- 2015-08-07 12:00:00 : 남산면   14742 ----------


 ---------- 2015-08-07 12:00:00 : 동  면   14743 ----------


 ---------- 2015-08-07 14:00:00 : 사북면   14744 ----------


 ---------- 2015-08-07 15:00:00 : 남산면   14745 ----------


 ---------- 2015-08-07 16:00:00 : 남산면   14746 ----------


 ---------- 2015-08-07 16:00:00 : 동산면   14747 ----------


 ---------- 2015-08-08 07:00:00 : 동내면   14748 ----------


 ---------- 2015-08-08 08:00:00 : 석사동   14749 ----------


 ---------- 2015-08-08 08:00:00 : 남산면   14750 ----------


 ---------- 2015-08-08 08:00:00 : 신북읍   14751 ----------


 ---------- 2015-08-08 09:00:00 : 서  면   14752 ----------


 ---------- 2015-08-08 09:00:00 : 사북면   14753 ----------


 ---------- 2015-08-08 10:00:00 : 강남동   14754 ----------


 ---------- 2015-08-08 11:00:00 : 신북읍   14757 ----------


 ---------- 2015-08-08 12:00:00 : 근화동   14758 ----------


 ---------- 2015-08-08 13:00:00 : 퇴계동   14759 ----------


 ---------- 2015-08-08 15:00:00 : 신동면   14760 ----------


 ---------- 2015-08-08 18:00:00 : 신동면   14761 ----------


 ---------- 2015-08-08 18:00:00 : 동  면   14762 ----------


 ---------- 2015-08-09 00:00:00 : 석사동   14763 ----------


 ---------- 2015-08-09 09:00:00 : 사북면   14765 ----------


 ---------- 2015-08-09 10:00:00 : 사북면   14766 ----------


 ---------- 2015-08-09 11:00:00 : 동내면   14767 ----------


 ---------- 2015-08-09 11:00:00 : 소양동   14768 ----------


 ---------- 2015-08-09 12:00:00 : 남산면   14769 ----------


 ---------- 2015-08-09 15:00:00 : 강남동   14770 ----------


 ---------- 2015-08-09 15:00:00 : 약사명동   14771 ----------


 ---------- 2015-08-09 15:00:00 : 후평1동   14772 ----------


 ---------- 2015-08-09 17:00:00 : 신동면   14773 ----------


 ---------- 2015-08-09 18:00:00 : 석사동   14774 ----------


 ---------- 2015-08-09 23:00:00 : 조운동   14775 ----------


 ---------- 2015-08-10 05:00:00 : 퇴계동   14776 ----------


 ---------- 2015-08-10 07:00:00 : 강남동   14777 ----------


 ---------- 2015-08-10 07:00:00 : 퇴계동   14778 ----------


 ---------- 2015-08-10 09:00:00 : 남산면   14781 ----------


 ---------- 2015-08-10 10:00:00 : 강남동   14782 ----------


 ---------- 2015-08-10 10:00:00 : 남산면   14783 ----------


 ---------- 2015-08-10 10:00:00 : 동  면   14784 ----------


 ---------- 2015-08-10 11:00:00 : 서  면   14785 ----------


 ---------- 2015-08-10 11:00:00 : 동내면   14788 ----------


 ---------- 2015-08-10 12:00:00 : 서  면   14789 ----------


 ---------- 2015-08-10 12:00:00 : 남산면   14790 ----------


 ---------- 2015-08-10 13:00:00 : 서  면   14791 ----------


 ---------- 2015-08-10 13:00:00 : 남산면   14792 ----------


 ---------- 2015-08-10 14:00:00 : 후평1동   14793 ----------


 ---------- 2015-08-10 15:00:00 : 신동면   14794 ----------


 ---------- 2015-08-10 15:00:00 : 강남동   14795 ----------


 ---------- 2015-08-10 15:00:00 : 남  면   14796 ----------


 ---------- 2015-08-10 16:00:00 : 서  면   14797 ----------


 ---------- 2015-08-10 16:00:00 : 동  면   14798 ----------


 ---------- 2015-08-10 17:00:00 : 신사우동   14800 ----------


 ---------- 2015-08-10 17:00:00 : 동  면   14801 ----------


 ---------- 2015-08-10 17:00:00 : 교  동   14802 ----------


 ---------- 2015-08-10 18:00:00 : 근화동   14803 ----------


 ---------- 2015-08-10 20:00:00 : 서  면   14805 ----------


 ---------- 2015-08-10 21:00:00 : 효자1동   14806 ----------


 ---------- 2015-08-11 06:00:00 : 동산면   14807 ----------


 ---------- 2015-08-11 08:00:00 : 신북읍   14808 ----------


 ---------- 2015-08-11 09:00:00 : 사북면   14809 ----------


 ---------- 2015-08-11 09:00:00 : 신북읍   14810 ----------


 ---------- 2015-08-11 10:00:00 : 남산면   14811 ----------

 ---------- 2015-08-11 11:00:00 : 근화동   14812 ----------


 ---------- 2015-08-11 11:00:00 : 북산면   14813 ----------


 ---------- 2015-08-11 12:00:00 : 근화동   14814 ----------


 ---------- 2015-08-11 12:00:00 : 신북읍   14815 ----------


 ---------- 2015-08-11 13:00:00 : 동  면   14816 ----------


 ---------- 2015-08-11 14:00:00 : 남산면   14817 ----------


 ---------- 2015-08-11 14:00:00 : 소양동   14819 ----------


 ---------- 2015-08-11 15:00:00 : 강남동   14821 ----------


 ---------- 2015-08-11 15:00:00 : 약사명동   14822 ----------


 ---------- 2015-08-11 16:00:00 : 석사동   14823 ----------


 ---------- 2015-08-11 16:00:00 : 사북면   14824 ----------


 ---------- 2015-08-11 17:00:00 : 동  면   14825 ----------


 ---------- 2015-08-12 08:00:00 : 석사동   14827 ----------


 ---------- 2015-08-12 08:00:00 : 남산면   14828 ----------


 ---------- 2015-08-12 08:00:00 : 근화동   14829 ----------


 ---------- 2015-08-12 09:00:00 : 사북면   14830 ----------


 ---------- 2015-08-12 10:00:00 : 남  면   14831 ----------


 ---------- 2015-08-12 10:00:00 : 남산면   14832 ----------


 ---------- 2015-08-12 10:00:00 : 동  면   14833 ----------


 ---------- 2015-08-12 11:00:00 : 퇴계동   14834 ----------


 ---------- 2015-08-12 11:00:00 : 동산면   14835 ----------


 ---------- 2015-08-12 13:00:00 : 남산면   14836 ----------


 ---------- 2015-08-12 14:00:00 : 강남동   14837 ----------


 ---------- 2015-08-12 14:00:00 : 남산면   14838 ----------


 ---------- 2015-08-12 14:00:00 : 퇴계동   14839 ----------


 ---------- 2015-08-12 16:00:00 : 동내면   14840 ----------


 ---------- 2015-08-12 16:00:00 : 신사우동   14841 ----------


 ---------- 2015-08-12 18:00:00 : 동내면   14842 ----------


 ---------- 2015-08-12 18:00:00 : 교  동   14843 ----------


 ---------- 2015-08-12 20:00:00 : 후평1동   14844 ----------


 ---------- 2015-08-13 08:00:00 : 퇴계동   14845 ----------


 ---------- 2015-08-13 09:00:00 : 석사동   14846 ----------


 ---------- 2015-08-13 09:00:00 : 동내면   14847 ----------


 ---------- 2015-08-13 09:00:00 : 근화동   14848 ----------


 ---------- 2015-08-13 10:00:00 : 동내면   14849 ----------


 ---------- 2015-08-13 10:00:00 : 소양동   14850 ----------


 ---------- 2015-08-13 13:00:00 : 남산면   14851 ----------


 ---------- 2015-08-13 17:00:00 : 북산면   14852 ----------


 ---------- 2015-08-13 21:00:00 : 후평1동   14853 ----------


 ---------- 2015-08-14 02:00:00 : 석사동   14854 ----------


 ---------- 2015-08-14 08:00:00 : 소양동   14855 ----------


 ---------- 2015-08-14 09:00:00 : 서  면   14856 ----------


 ---------- 2015-08-14 09:00:00 : 동내면   14857 ----------


 ---------- 2015-08-14 09:00:00 : 남산면   14858 ----------


 ---------- 2015-08-14 10:00:00 : 교  동   14859 ----------


 ---------- 2015-08-14 11:00:00 : 신동면   14860 ----------


 ---------- 2015-08-14 11:00:00 : 강남동   14861 ----------


 ---------- 2015-08-14 11:00:00 : 퇴계동   14863 ----------


 ---------- 2015-08-14 12:00:00 : 동내면   14864 ----------


 ---------- 2015-08-14 13:00:00 : 사북면   14865 ----------


 ---------- 2015-08-14 13:00:00 : 남산면   14866 ----------


 ---------- 2015-08-14 15:00:00 : 교  동   14867 ----------


 ---------- 2015-08-14 16:00:00 : 남  면   14868 ----------


 ---------- 2015-08-14 16:00:00 : 사북면   14869 ----------


 ---------- 2015-08-14 16:00:00 : 신북읍   14870 ----------


 ---------- 2015-08-14 17:00:00 : 효자1동   14871 ----------


 ---------- 2015-08-14 19:00:00 : 동내면   14872 ----------


 ---------- 2015-08-14 19:00:00 : 남산면   14873 ----------


 ---------- 2015-08-14 20:00:00 : 석사동   14874 ----------


 ---------- 2015-08-15 07:00:00 : 서  면   14875 ----------


 ---------- 2015-08-15 08:00:00 : 서  면   14876 ----------


 ---------- 2015-08-15 08:00:00 : 북산면   14877 ----------


 ---------- 2015-08-15 09:00:00 : 강남동   14878 ----------


 ---------- 2015-08-15 09:00:00 : 사북면   14879 ----------


 ---------- 2015-08-15 09:00:00 : 동내면   14880 ----------


 ---------- 2015-08-15 09:00:00 : 남산면   14881 ----------


 ---------- 2015-08-15 10:00:00 : 서  면   14882 ----------


 ---------- 2015-08-15 10:00:00 : 남  면   14884 ----------


 ---------- 2015-08-15 11:00:00 : 근화동   14885 ----------


 ---------- 2015-08-15 11:00:00 : 신북읍   14886 ----------


 ---------- 2015-08-15 12:00:00 : 효자1동   14887 ----------


 ---------- 2015-08-15 12:00:00 : 북산면   14888 ----------


 ---------- 2015-08-15 13:00:00 : 석사동   14889 ----------


 ---------- 2015-08-15 13:00:00 : 남산면   14890 ----------


 ---------- 2015-08-15 13:00:00 : 북산면   14891 ----------


 ---------- 2015-08-15 15:00:00 : 석사동   14892 ----------


 ---------- 2015-08-15 17:00:00 : 동  면   14893 ----------


 ---------- 2015-08-15 22:00:00 : 퇴계동   14894 ----------


 ---------- 2015-08-15 23:00:00 : 퇴계동   14895 ----------


 ---------- 2015-08-16 07:00:00 : 신동면   14896 ----------


 ---------- 2015-08-16 11:00:00 : 후평1동   14897 ----------


 ---------- 2015-08-16 12:00:00 : 사북면   14898 ----------


 ---------- 2015-08-16 14:00:00 : 남산면   14899 ----------


 ---------- 2015-08-16 15:00:00 : 북산면   14900 ----------


 ---------- 2015-08-16 16:00:00 : 신북읍   14901 ----------


 ---------- 2015-08-16 22:00:00 : 동내면   14902 ----------


 ---------- 2015-08-17 06:00:00 : 동내면   14903 ----------


 ---------- 2015-08-17 07:00:00 : 동내면   14904 ----------


 ---------- 2015-08-17 07:00:00 : 후평1동   14905 ----------


 ---------- 2015-08-17 09:00:00 : 사북면   14906 ----------


 ---------- 2015-08-17 09:00:00 : 후평1동   14907 ----------


 ---------- 2015-08-17 10:00:00 : 동  면   14909 ----------


 ---------- 2015-08-17 11:00:00 : 사북면   14910 ----------


 ---------- 2015-08-17 12:00:00 : 신북읍   14911 ----------


 ---------- 2015-08-17 16:00:00 : 남산면   14912 ----------


 ---------- 2015-08-17 16:00:00 : 약사명동   14913 ----------


 ---------- 2015-08-17 16:00:00 : 북산면   14914 ----------


 ---------- 2015-08-17 17:00:00 : 강남동   14915 ----------


 ---------- 2015-08-17 17:00:00 : 효자1동   14916 ----------


 ---------- 2015-08-17 17:00:00 : 신사우동   14917 ----------


 ---------- 2015-08-17 18:00:00 : 퇴계동   14918 ----------


 ---------- 2015-08-17 19:00:00 : 교  동   14919 ----------


 ---------- 2015-08-18 07:00:00 : 서  면   14920 ----------


 ---------- 2015-08-18 09:00:00 : 신동면   14921 ----------


 ---------- 2015-08-18 09:00:00 : 서  면   14922 ----------


 ---------- 2015-08-18 09:00:00 : 남산면   14923 ----------


 ---------- 2015-08-18 09:00:00 : 동  면   14924 ----------


 ---------- 2015-08-18 10:00:00 : 남  면   14925 ----------


 ---------- 2015-08-18 11:00:00 : 후평1동   14926 ----------


 ---------- 2015-08-18 11:00:00 : 퇴계동   14927 ----------


 ---------- 2015-08-18 12:00:00 : 약사명동   14928 ----------


 ---------- 2015-08-18 14:00:00 : 서  면   14929 ----------


 ---------- 2015-08-18 14:00:00 : 북산면   14930 ----------


 ---------- 2015-08-18 15:00:00 : 근화동   14931 ----------


 ---------- 2015-08-18 16:00:00 : 동내면   14932 ----------


 ---------- 2015-08-18 18:00:00 : 동내면   14933 ----------


 ---------- 2015-08-19 00:00:00 : 효자1동   14934 ----------


 ---------- 2015-08-19 00:00:00 : 퇴계동   14935 ----------


 ---------- 2015-08-19 03:00:00 : 근화동   14936 ----------


 ---------- 2015-08-19 03:00:00 : 퇴계동   14937 ----------


 ---------- 2015-08-19 05:00:00 : 석사동   14938 ----------


 ---------- 2015-08-19 09:00:00 : 사북면   14939 ----------


 ---------- 2015-08-19 09:00:00 : 소양동   14940 ----------


 ---------- 2015-08-19 10:00:00 : 남  면   14941 ----------


 ---------- 2015-08-19 10:00:00 : 동  면   14942 ----------


 ---------- 2015-08-19 10:00:00 : 후평1동   14943 ----------


 ---------- 2015-08-19 11:00:00 : 신북읍   14944 ----------


 ---------- 2015-08-19 12:00:00 : 강남동   14945 ----------


 ---------- 2015-08-19 12:00:00 : 신북읍   14947 ----------


 ---------- 2015-08-19 14:00:00 : 동내면   14948 ----------


 ---------- 2015-08-19 14:00:00 : 신사우동   14949 ----------


 ---------- 2015-08-19 18:00:00 : 남산면   14950 ----------


 ---------- 2015-08-20 08:00:00 : 서  면   14951 ----------


 ---------- 2015-08-20 09:00:00 : 서  면   14953 ----------


 ---------- 2015-08-20 10:00:00 : 강남동   14954 ----------


 ---------- 2015-08-20 10:00:00 : 신북읍   14955 ----------

 ---------- 2015-08-20 11:00:00 : 효자1동   14956 ----------


 ---------- 2015-08-20 11:00:00 : 동  면   14957 ----------


 ---------- 2015-08-20 11:00:00 : 퇴계동   14958 ----------


 ---------- 2015-08-20 13:00:00 : 남산면   14959 ----------


 ---------- 2015-08-20 14:00:00 : 강남동   14960 ----------


 ---------- 2015-08-20 15:00:00 : 동산면   14961 ----------


 ---------- 2015-08-20 16:00:00 : 신동면   14962 ----------


 ---------- 2015-08-20 21:00:00 : 남산면   14963 ----------


 ---------- 2015-08-20 22:00:00 : 약사명동   14964 ----------


 ---------- 2015-08-21 09:00:00 : 동내면   14965 ----------


 ---------- 2015-08-21 09:00:00 : 교  동   14966 ----------


 ---------- 2015-08-21 10:00:00 : 신북읍   14967 ----------


 ---------- 2015-08-21 10:00:00 : 동  면   14968 ----------


 ---------- 2015-08-21 11:00:00 : 강남동   14969 ----------


 ---------- 2015-08-21 12:00:00 : 강남동   14970 ----------


 ---------- 2015-08-21 13:00:00 : 신사우동   14971 ----------


 ---------- 2015-08-21 13:00:00 : 동  면   14972 ----------


 ---------- 2015-08-21 14:00:00 : 남산면   14973 ----------


 ---------- 2015-08-21 14:00:00 : 근화동   14974 ----------


 ---------- 2015-08-21 15:00:00 : 후평1동   14975 ----------


 ---------- 2015-08-21 16:00:00 : 신사우동   14976 ----------


 ---------- 2015-08-21 16:00:00 : 후평1동   14977 ----------


 ---------- 2015-08-21 18:00:00 : 신북읍   14978 ----------


 ---------- 2015-08-21 18:00:00 : 동  면   14979 ----------


 ---------- 2015-08-21 23:00:00 : 서  면   14980 ----------


 ---------- 2015-08-22 08:00:00 : 강남동   14982 ----------


 ---------- 2015-08-22 09:00:00 : 남산면   14983 ----------


 ---------- 2015-08-22 10:00:00 : 후평1동   14984 ----------


 ---------- 2015-08-22 11:00:00 : 남산면   14985 ----------


 ---------- 2015-08-22 12:00:00 : 신북읍   14986 ----------


 ---------- 2015-08-22 15:00:00 : 효자1동   14987 ----------


 ---------- 2015-08-22 17:00:00 : 소양동   14988 ----------


 ---------- 2015-08-22 19:00:00 : 퇴계동   14989 ----------


 ---------- 2015-08-22 20:00:00 : 동  면   14990 ----------


 ---------- 2015-08-23 08:00:00 : 서  면   14991 ----------


 ---------- 2015-08-23 09:00:00 : 효자1동   14992 ----------


 ---------- 2015-08-23 09:00:00 : 신북읍   14993 ----------


 ---------- 2015-08-23 10:00:00 : 동내면   14994 ----------


 ---------- 2015-08-23 12:00:00 : 사북면   14995 ----------


 ---------- 2015-08-23 14:00:00 : 강남동   14996 ----------


 ---------- 2015-08-23 15:00:00 : 동내면   14997 ----------


 ---------- 2015-08-23 15:00:00 : 신북읍   14999 ----------


 ---------- 2015-08-23 16:00:00 : 소양동   15000 ----------


 ---------- 2015-08-23 19:00:00 : 강남동   15001 ----------


 ---------- 2015-08-23 22:00:00 : 후평1동   15002 ----------


 ---------- 2015-08-24 09:00:00 : 사북면   15003 ----------


 ---------- 2015-08-24 10:00:00 : 후평1동   15004 ----------


 ---------- 2015-08-24 10:00:00 : 동산면   15005 ----------


 ---------- 2015-08-24 11:00:00 : 사북면   15006 ----------


 ---------- 2015-08-24 12:00:00 : 강남동   15007 ----------


 ---------- 2015-08-24 13:00:00 : 신동면   15009 ----------


 ---------- 2015-08-24 13:00:00 : 약사명동   15010 ----------


 ---------- 2015-08-24 13:00:00 : 동산면   15011 ----------


 ---------- 2015-08-24 14:00:00 : 퇴계동   15012 ----------


 ---------- 2015-08-24 15:00:00 : 사북면   15014 ----------


 ---------- 2015-08-24 15:00:00 : 신북읍   15015 ----------


 ---------- 2015-08-24 20:00:00 : 남산면   15017 ----------


 ---------- 2015-08-24 23:00:00 : 근화동   15018 ----------


 ---------- 2015-08-25 06:00:00 : 남  면   15019 ----------


 ---------- 2015-08-25 06:00:00 : 신북읍   15020 ----------


 ---------- 2015-08-25 09:00:00 : 동  면   15022 ----------


 ---------- 2015-08-25 10:00:00 : 동  면   15023 ----------


 ---------- 2015-08-25 13:00:00 : 석사동   15024 ----------


 ---------- 2015-08-25 18:00:00 : 신북읍   15025 ----------


 ---------- 2015-08-26 00:00:00 : 석사동   15026 ----------


 ---------- 2015-08-26 09:00:00 : 후평1동   15027 ----------


 ---------- 2015-08-26 10:00:00 : 남산면   15028 ----------


 ---------- 2015-08-26 12:00:00 : 동  면   15029 ----------


 ---------- 2015-08-26 15:00:00 : 동  면   15030 ----------


 ---------- 2015-08-26 16:00:00 : 효자1동   15031 ----------


 ---------- 2015-08-26 16:00:00 : 약사명동   15032 ----------


 ---------- 2015-08-26 16:00:00 : 동  면   15034 ----------


 ---------- 2015-08-26 16:00:00 : 후평1동   15035 ----------


 ---------- 2015-08-26 18:00:00 : 효자1동   15036 ----------


 ---------- 2015-08-26 19:00:00 : 동  면   15038 ----------


 ---------- 2015-08-27 00:00:00 : 근화동   15039 ----------


 ---------- 2015-08-27 09:00:00 : 동내면   15040 ----------


 ---------- 2015-08-27 09:00:00 : 남산면   15041 ----------


 ---------- 2015-08-27 10:00:00 : 사북면   15042 ----------


 ---------- 2015-08-27 10:00:00 : 신북읍   15043 ----------


 ---------- 2015-08-27 10:00:00 : 퇴계동   15044 ----------


 ---------- 2015-08-27 11:00:00 : 강남동   15045 ----------


 ---------- 2015-08-27 11:00:00 : 북산면   15046 ----------


 ---------- 2015-08-27 12:00:00 : 약사명동   15047 ----------


 ---------- 2015-08-27 15:00:00 : 서  면   15048 ----------


 ---------- 2015-08-27 15:00:00 : 효자1동   15049 ----------


 ---------- 2015-08-27 15:00:00 : 후평1동   15050 ----------


 ---------- 2015-08-27 16:00:00 : 사북면   15051 ----------


 ---------- 2015-08-27 17:00:00 : 동내면   15052 ----------


 ---------- 2015-08-28 06:00:00 : 동내면   15053 ----------


 ---------- 2015-08-28 08:00:00 : 신북읍   15054 ----------


 ---------- 2015-08-28 09:00:00 : 신사우동   15055 ----------


 ---------- 2015-08-28 11:00:00 : 동  면   15056 ----------


 ---------- 2015-08-28 13:00:00 : 서  면   15058 ----------


 ---------- 2015-08-28 14:00:00 : 서  면   15059 ----------


 ---------- 2015-08-28 14:00:00 : 남산면   15060 ----------


 ---------- 2015-08-28 14:00:00 : 근화동   15061 ----------


 ---------- 2015-08-28 15:00:00 : 강남동   15062 ----------


 ---------- 2015-08-28 15:00:00 : 동  면   15063 ----------


 ---------- 2015-08-28 15:00:00 : 교  동   15064 ----------


 ---------- 2015-08-29 01:00:00 : 강남동   15065 ----------


 ---------- 2015-08-29 03:00:00 : 신사우동   15066 ----------


 ---------- 2015-08-29 06:00:00 : 효자1동   15067 ----------


 ---------- 2015-08-29 08:00:00 : 남산면   15068 ----------


 ---------- 2015-08-29 09:00:00 : 소양동   15069 ----------


 ---------- 2015-08-29 09:00:00 : 동  면   15070 ----------


 ---------- 2015-08-29 10:00:00 : 서  면   15071 ----------


 ---------- 2015-08-29 10:00:00 : 남산면   15072 ----------


 ---------- 2015-08-29 10:00:00 : 퇴계동   15073 ----------


 ---------- 2015-08-29 11:00:00 : 강남동   15074 ----------


 ---------- 2015-08-29 13:00:00 : 퇴계동   15075 ----------


 ---------- 2015-08-29 14:00:00 : 서  면   15076 ----------


 ---------- 2015-08-29 14:00:00 : 동내면   15077 ----------


 ---------- 2015-08-29 14:00:00 : 남산면   15078 ----------


 ---------- 2015-08-29 15:00:00 : 강남동   15079 ----------


 ---------- 2015-08-30 11:00:00 : 강남동   15081 ----------


 ---------- 2015-08-30 13:00:00 : 신사우동   15082 ----------


 ---------- 2015-08-30 15:00:00 : 약사명동   15083 ----------


 ---------- 2015-08-30 18:00:00 : 강남동   15084 ----------


 ---------- 2015-08-30 23:00:00 : 신사우동   15085 ----------


 ---------- 2015-08-30 23:00:00 : 후평1동   15086 ----------


 ---------- 2015-08-31 08:00:00 : 남산면   15087 ----------


 ---------- 2015-08-31 08:00:00 : 신사우동   15088 ----------


 ---------- 2015-08-31 09:00:00 : 강남동   15089 ----------


 ---------- 2015-08-31 09:00:00 : 신북읍   15090 ----------


 ---------- 2015-08-31 10:00:00 : 퇴계동   15091 ----------


 ---------- 2015-08-31 12:00:00 : 남산면   15092 ----------


 ---------- 2015-08-31 12:00:00 : 동산면   15094 ----------


 ---------- 2015-08-31 13:00:00 : 강남동   15095 ----------


 ---------- 2015-08-31 13:00:00 : 퇴계동   15097 ----------


 ---------- 2015-08-31 15:00:00 : 사북면   15098 ----------


 ---------- 2015-08-31 16:00:00 : 동  면   15099 ----------


 ---------- 2015-08-31 17:00:00 : 석사동   15102 ----------


 ---------- 2015-08-31 17:00:00 : 퇴계동   15103 ----------


 ---------- 2015-08-31 18:00:00 : 동내면   15104 ----------


 ---------- 2015-08-31 23:00:00 : 소양동   15105 ----------

 ---------- 2015-09-01 09:00:00 : 근화동   15106 ----------


 ---------- 2015-09-01 10:00:00 : 신북읍   15107 ----------


 ---------- 2015-09-01 10:00:00 : 동  면   15108 ----------


 ---------- 2015-09-01 13:00:00 : 신북읍   15109 ----------


 ---------- 2015-09-01 14:00:00 : 동  면   15110 ----------


 ---------- 2015-09-01 15:00:00 : 동  면   15111 ----------


 ---------- 2015-09-01 16:00:00 : 근화동   15112 ----------


 ---------- 2015-09-01 17:00:00 : 효자1동   15113 ----------


 ---------- 2015-09-01 18:00:00 : 동  면   15114 ----------


 ---------- 2015-09-01 20:00:00 : 효자1동   15115 ----------


 ---------- 2015-09-02 08:00:00 : 석사동   15116 ----------


 ---------- 2015-09-02 09:00:00 : 신동면   15117 ----------


 ---------- 2015-09-02 09:00:00 : 동  면   15119 ----------


 ---------- 2015-09-02 09:00:00 : 후평1동   15121 ----------


 ---------- 2015-09-02 10:00:00 : 후평1동   15122 ----------


 ---------- 2015-09-02 11:00:00 : 사북면   15123 ----------


 ---------- 2015-09-02 13:00:00 : 퇴계동   15124 ----------


 ---------- 2015-09-02 15:00:00 : 강남동   15125 ----------


 ---------- 2015-09-02 16:00:00 : 퇴계동   15126 ----------


 ---------- 2015-09-02 18:00:00 : 남산면   15127 ----------


 ---------- 2015-09-02 18:00:00 : 퇴계동   15128 ----------


 ---------- 2015-09-03 06:00:00 : 신동면   15129 ----------


 ---------- 2015-09-03 08:00:00 : 퇴계동   15130 ----------


 ---------- 2015-09-03 09:00:00 : 신사우동   15131 ----------


 ---------- 2015-09-03 10:00:00 : 퇴계동   15132 ----------


 ---------- 2015-09-03 11:00:00 : 효자1동   15133 ----------


 ---------- 2015-09-03 15:00:00 : 석사동   15134 ----------


 ---------- 2015-09-03 16:00:00 : 강남동   15135 ----------


 ---------- 2015-09-03 17:00:00 : 서  면   15136 ----------


 ---------- 2015-09-03 21:00:00 : 소양동   15139 ----------


 ---------- 2015-09-03 23:00:00 : 석사동   15140 ----------


 ---------- 2015-09-04 07:00:00 : 석사동   15141 ----------


 ---------- 2015-09-04 08:00:00 : 신사우동   15142 ----------


 ---------- 2015-09-04 09:00:00 : 조운동   15143 ----------


 ---------- 2015-09-04 10:00:00 : 남산면   15144 ----------


 ---------- 2015-09-04 11:00:00 : 근화동   15145 ----------


 ---------- 2015-09-04 11:00:00 : 소양동   15147 ----------


 ---------- 2015-09-04 11:00:00 : 후평1동   15148 ----------


 ---------- 2015-09-04 11:00:00 : 동산면   15149 ----------


 ---------- 2015-09-04 12:00:00 : 신동면   15151 ----------


 ---------- 2015-09-04 13:00:00 : 서  면   15152 ----------


 ---------- 2015-09-04 14:00:00 : 효자1동   15153 ----------


 ---------- 2015-09-04 19:00:00 : 석사동   15155 ----------


 ---------- 2015-09-04 22:00:00 : 동  면   15156 ----------


 ---------- 2015-09-04 23:00:00 : 강남동   15157 ----------


 ---------- 2015-09-05 04:00:00 : 후평1동   15158 ----------


 ---------- 2015-09-05 07:00:00 : 신사우동   15159 ----------


 ---------- 2015-09-05 08:00:00 : 사북면   15160 ----------


 ---------- 2015-09-05 08:00:00 : 퇴계동   15161 ----------


 ---------- 2015-09-05 10:00:00 : 동  면   15163 ----------


 ---------- 2015-09-05 11:00:00 : 소양동   15164 ----------


 ---------- 2015-09-05 16:00:00 : 사북면   15165 ----------


 ---------- 2015-09-05 16:00:00 : 동  면   15166 ----------


 ---------- 2015-09-05 17:00:00 : 후평1동   15167 ----------


 ---------- 2015-09-06 01:00:00 : 신사우동   15168 ----------


 ---------- 2015-09-06 08:00:00 : 서  면   15169 ----------


 ---------- 2015-09-06 09:00:00 : 서  면   15171 ----------


 ---------- 2015-09-06 09:00:00 : 동내면   15172 ----------


 ---------- 2015-09-06 09:00:00 : 효자1동   15173 ----------


 ---------- 2015-09-06 09:00:00 : 남산면   15174 ----------


 ---------- 2015-09-06 09:00:00 : 신사우동   15175 ----------


 ---------- 2015-09-06 09:00:00 : 신북읍   15176 ----------


 ---------- 2015-09-06 10:00:00 : 남  면   15177 ----------


 ---------- 2015-09-06 10:00:00 : 북산면   15178 ----------


 ---------- 2015-09-06 11:00:00 : 남  면   15179 ----------


 ---------- 2015-09-06 13:00:00 : 서  면   15180 ----------


 ---------- 2015-09-06 14:00:00 : 북산면   15182 ----------


 ---------- 2015-09-06 14:00:00 : 동산면   15184 ----------


 ---------- 2015-09-06 15:00:00 : 북산면   15185 ----------


 ---------- 2015-09-06 16:00:00 : 동  면   15186 ----------


 ---------- 2015-09-06 18:00:00 : 교  동   15187 ----------


 ---------- 2015-09-07 01:00:00 : 후평1동   15188 ----------


 ---------- 2015-09-07 08:00:00 : 사북면   15189 ----------


 ---------- 2015-09-07 08:00:00 : 동  면   15190 ----------


 ---------- 2015-09-07 09:00:00 : 강남동   15191 ----------


 ---------- 2015-09-07 09:00:00 : 서  면   15192 ----------


 ---------- 2015-09-07 11:00:00 : 근화동   15193 ----------


 ---------- 2015-09-07 12:00:00 : 효자1동   15194 ----------


 ---------- 2015-09-07 12:00:00 : 남산면   15195 ----------


 ---------- 2015-09-07 12:00:00 : 동산면   15196 ----------


 ---------- 2015-09-07 13:00:00 : 남산면   15197 ----------


 ---------- 2015-09-07 14:00:00 : 신동면   15199 ----------


 ---------- 2015-09-07 16:00:00 : 동  면   15200 ----------


 ---------- 2015-09-07 16:00:00 : 퇴계동   15201 ----------


 ---------- 2015-09-07 17:00:00 : 동  면   15202 ----------


 ---------- 2015-09-07 17:00:00 : 후평1동   15203 ----------


 ---------- 2015-09-07 18:00:00 : 석사동   15204 ----------


 ---------- 2015-09-07 18:00:00 : 신사우동   15205 ----------


 ---------- 2015-09-07 22:00:00 : 후평1동   15206 ----------


 ---------- 2015-09-08 09:00:00 : 남산면   15207 ----------


 ---------- 2015-09-08 09:00:00 : 북산면   15208 ----------


 ---------- 2015-09-08 09:00:00 : 동산면   15209 ----------


 ---------- 2015-09-08 12:00:00 : 남산면   15210 ----------


 ---------- 2015-09-08 15:00:00 : 신북읍   15211 ----------


 ---------- 2015-09-08 17:00:00 : 퇴계동   15212 ----------


 ---------- 2015-09-09 01:00:00 : 신사우동   15213 ----------


 ---------- 2015-09-09 08:00:00 : 후평1동   15214 ----------


 ---------- 2015-09-09 09:00:00 : 강남동   15217 ----------


 ---------- 2015-09-09 11:00:00 : 후평1동   15218 ----------


 ---------- 2015-09-09 11:00:00 : 퇴계동   15220 ----------


 ---------- 2015-09-09 13:00:00 : 남산면   15221 ----------


 ---------- 2015-09-09 14:00:00 : 남산면   15222 ----------


 ---------- 2015-09-09 23:00:00 : 신사우동   15223 ----------


 ---------- 2015-09-10 07:00:00 : 퇴계동   15224 ----------


 ---------- 2015-09-10 09:00:00 : 신북읍   15225 ----------


 ---------- 2015-09-10 10:00:00 : 동내면   15226 ----------


 ---------- 2015-09-10 10:00:00 : 효자1동   15227 ----------


 ---------- 2015-09-10 10:00:00 : 남산면   15228 ----------


 ---------- 2015-09-10 12:00:00 : 동  면   15229 ----------


 ---------- 2015-09-10 13:00:00 : 남  면   15230 ----------


 ---------- 2015-09-10 13:00:00 : 남산면   15231 ----------


 ---------- 2015-09-10 14:00:00 : 남  면   15232 ----------


 ---------- 2015-09-10 14:00:00 : 동산면   15233 ----------


 ---------- 2015-09-10 15:00:00 : 강남동   15234 ----------


 ---------- 2015-09-10 15:00:00 : 서  면   15237 ----------


 ---------- 2015-09-10 18:00:00 : 조운동   15238 ----------


 ---------- 2015-09-10 23:00:00 : 후평1동   15239 ----------


 ---------- 2015-09-11 07:00:00 : 퇴계동   15240 ----------


 ---------- 2015-09-11 08:00:00 : 약사명동   15241 ----------


 ---------- 2015-09-11 09:00:00 : 동  면   15243 ----------


 ---------- 2015-09-11 10:00:00 : 신동면   15244 ----------


 ---------- 2015-09-11 10:00:00 : 동  면   15245 ----------


 ---------- 2015-09-11 11:00:00 : 동내면   15246 ----------


 ---------- 2015-09-11 13:00:00 : 신북읍   15247 ----------


 ---------- 2015-09-11 15:00:00 : 사북면   15248 ----------


 ---------- 2015-09-11 15:00:00 : 동  면   15249 ----------


 ---------- 2015-09-11 15:00:00 : 퇴계동   15250 ----------


 ---------- 2015-09-11 16:00:00 : 동  면   15251 ----------


 ---------- 2015-09-11 16:00:00 : 퇴계동   15253 ----------


 ---------- 2015-09-11 23:00:00 : 퇴계동   15254 ----------


 ---------- 2015-09-12 08:00:00 : 남  면   15255 ----------


 ---------- 2015-09-12 09:00:00 : 신동면   15256 ----------


 ---------- 2015-09-12 09:00:00 : 신북읍   15257 ----------


 ---------- 2015-09-12 09:00:00 : 동산면   15258 ----------


 ---------- 2015-09-12 10:00:00 : 신사우동   15260 ----------


 ---------- 2015-09-12 11:00:00 : 신사우동   15261 ----------

 ---------- 2015-09-12 13:00:00 : 신사우동   15262 ----------


 ---------- 2015-09-12 13:00:00 : 신북읍   15263 ----------


 ---------- 2015-09-12 17:00:00 : 후평1동   15264 ----------


 ---------- 2015-09-12 20:00:00 : 교  동   15265 ----------


 ---------- 2015-09-12 23:00:00 : 효자1동   15266 ----------


 ---------- 2015-09-13 01:00:00 : 석사동   15267 ----------


 ---------- 2015-09-13 03:00:00 : 효자1동   15268 ----------


 ---------- 2015-09-13 08:00:00 : 근화동   15269 ----------


 ---------- 2015-09-13 09:00:00 : 동내면   15270 ----------


 ---------- 2015-09-13 09:00:00 : 북산면   15271 ----------


 ---------- 2015-09-13 11:00:00 : 서  면   15272 ----------


 ---------- 2015-09-13 12:00:00 : 신북읍   15273 ----------


 ---------- 2015-09-13 13:00:00 : 서  면   15274 ----------


 ---------- 2015-09-13 13:00:00 : 동  면   15275 ----------


 ---------- 2015-09-13 16:00:00 : 동  면   15276 ----------


 ---------- 2015-09-13 21:00:00 : 석사동   15277 ----------


 ---------- 2015-09-14 08:00:00 : 신북읍   15278 ----------


 ---------- 2015-09-14 09:00:00 : 신사우동   15279 ----------


 ---------- 2015-09-14 09:00:00 : 동  면   15280 ----------


 ---------- 2015-09-14 10:00:00 : 석사동   15281 ----------


 ---------- 2015-09-14 10:00:00 : 강남동   15282 ----------


 ---------- 2015-09-14 10:00:00 : 서  면   15283 ----------


 ---------- 2015-09-14 10:00:00 : 소양동   15284 ----------


 ---------- 2015-09-14 10:00:00 : 동  면   15285 ----------


 ---------- 2015-09-14 13:00:00 : 남산면   15286 ----------


 ---------- 2015-09-14 14:00:00 : 동내면   15287 ----------


 ---------- 2015-09-14 14:00:00 : 신북읍   15288 ----------


 ---------- 2015-09-14 15:00:00 : 사북면   15290 ----------


 ---------- 2015-09-14 18:00:00 : 조운동   15292 ----------


 ---------- 2015-09-15 05:00:00 : 효자1동   15293 ----------


 ---------- 2015-09-15 05:00:00 : 후평1동   15295 ----------


 ---------- 2015-09-15 09:00:00 : 신동면   15296 ----------


 ---------- 2015-09-15 09:00:00 : 퇴계동   15297 ----------


 ---------- 2015-09-15 10:00:00 : 후평1동   15298 ----------


 ---------- 2015-09-15 11:00:00 : 북산면   15299 ----------


 ---------- 2015-09-15 12:00:00 : 서  면   15301 ----------


 ---------- 2015-09-15 13:00:00 : 소양동   15302 ----------


 ---------- 2015-09-15 14:00:00 : 서  면   15303 ----------


 ---------- 2015-09-15 15:00:00 : 신북읍   15304 ----------


 ---------- 2015-09-15 17:00:00 : 신북읍   15305 ----------


 ---------- 2015-09-15 18:00:00 : 퇴계동   15306 ----------


 ---------- 2015-09-15 18:00:00 : 북산면   15307 ----------


 ---------- 2015-09-15 19:00:00 : 석사동   15308 ----------


 ---------- 2015-09-16 08:00:00 : 사북면   15309 ----------


 ---------- 2015-09-16 08:00:00 : 동  면   15310 ----------


 ---------- 2015-09-16 09:00:00 : 서  면   15311 ----------


 ---------- 2015-09-16 09:00:00 : 남산면   15312 ----------


 ---------- 2015-09-16 09:00:00 : 동  면   15313 ----------


 ---------- 2015-09-16 09:00:00 : 후평1동   15314 ----------


 ---------- 2015-09-16 11:00:00 : 신사우동   15315 ----------


 ---------- 2015-09-16 13:00:00 : 신북읍   15316 ----------


 ---------- 2015-09-16 13:00:00 : 소양동   15317 ----------


 ---------- 2015-09-16 15:00:00 : 효자1동   15318 ----------


 ---------- 2015-09-16 16:00:00 : 약사명동   15319 ----------


 ---------- 2015-09-16 17:00:00 : 효자1동   15320 ----------


 ---------- 2015-09-16 20:00:00 : 동  면   15321 ----------


 ---------- 2015-09-17 03:00:00 : 퇴계동   15322 ----------


 ---------- 2015-09-17 09:00:00 : 석사동   15323 ----------


 ---------- 2015-09-17 10:00:00 : 남산면   15324 ----------


 ---------- 2015-09-17 11:00:00 : 효자1동   15325 ----------


 ---------- 2015-09-17 12:00:00 : 동내면   15326 ----------


 ---------- 2015-09-17 13:00:00 : 동산면   15327 ----------


 ---------- 2015-09-17 14:00:00 : 남산면   15329 ----------


 ---------- 2015-09-17 14:00:00 : 후평1동   15330 ----------


 ---------- 2015-09-17 15:00:00 : 남산면   15331 ----------


 ---------- 2015-09-17 15:00:00 : 동  면   15332 ----------


 ---------- 2015-09-17 16:00:00 : 동내면   15333 ----------


 ---------- 2015-09-17 18:00:00 : 서  면   15334 ----------


 ---------- 2015-09-17 21:00:00 : 석사동   15335 ----------


 ---------- 2015-09-18 07:00:00 : 신동면   15336 ----------


 ---------- 2015-09-18 09:00:00 : 신동면   15337 ----------


 ---------- 2015-09-18 10:00:00 : 교  동   15338 ----------


 ---------- 2015-09-18 12:00:00 : 남산면   15339 ----------


 ---------- 2015-09-18 12:00:00 : 신북읍   15340 ----------


 ---------- 2015-09-18 13:00:00 : 서  면   15341 ----------


 ---------- 2015-09-18 14:00:00 : 서  면   15342 ----------


 ---------- 2015-09-18 15:00:00 : 신사우동   15343 ----------


 ---------- 2015-09-18 16:00:00 : 신북읍   15344 ----------


 ---------- 2015-09-18 17:00:00 : 강남동   15345 ----------


 ---------- 2015-09-18 19:00:00 : 효자1동   15347 ----------


 ---------- 2015-09-18 20:00:00 : 후평1동   15348 ----------


 ---------- 2015-09-19 03:00:00 : 조운동   15349 ----------


 ---------- 2015-09-19 07:00:00 : 신북읍   15351 ----------


 ---------- 2015-09-19 09:00:00 : 소양동   15352 ----------


 ---------- 2015-09-19 09:00:00 : 동  면   15353 ----------


 ---------- 2015-09-19 10:00:00 : 서  면   15354 ----------


 ---------- 2015-09-19 11:00:00 : 남산면   15355 ----------


 ---------- 2015-09-19 13:00:00 : 남산면   15356 ----------


 ---------- 2015-09-19 14:00:00 : 신사우동   15357 ----------


 ---------- 2015-09-19 16:00:00 : 퇴계동   15358 ----------


 ---------- 2015-09-19 19:00:00 : 소양동   15359 ----------


 ---------- 2015-09-20 08:00:00 : 신사우동   15360 ----------


 ---------- 2015-09-20 10:00:00 : 동내면   15361 ----------


 ---------- 2015-09-20 12:00:00 : 근화동   15363 ----------


 ---------- 2015-09-20 17:00:00 : 동  면   15364 ----------


 ---------- 2015-09-20 17:00:00 : 후평1동   15365 ----------


 ---------- 2015-09-20 21:00:00 : 석사동   15366 ----------


 ---------- 2015-09-20 23:00:00 : 강남동   15368 ----------


 ---------- 2015-09-21 09:00:00 : 신동면   15369 ----------


 ---------- 2015-09-21 10:00:00 : 동  면   15370 ----------


 ---------- 2015-09-21 11:00:00 : 남산면   15371 ----------


 ---------- 2015-09-21 13:00:00 : 소양동   15372 ----------


 ---------- 2015-09-21 20:00:00 : 신사우동   15373 ----------


 ---------- 2015-09-21 22:00:00 : 퇴계동   15374 ----------


 ---------- 2015-09-22 07:00:00 : 효자1동   15375 ----------


 ---------- 2015-09-22 08:00:00 : 서  면   15377 ----------


 ---------- 2015-09-22 09:00:00 : 서  면   15378 ----------


 ---------- 2015-09-22 09:00:00 : 신사우동   15379 ----------


 ---------- 2015-09-22 09:00:00 : 동  면   15380 ----------


 ---------- 2015-09-22 10:00:00 : 신동면   15381 ----------


 ---------- 2015-09-22 11:00:00 : 남  면   15382 ----------


 ---------- 2015-09-22 11:00:00 : 효자1동   15383 ----------


 ---------- 2015-09-22 12:00:00 : 서  면   15384 ----------


 ---------- 2015-09-22 16:00:00 : 석사동   15385 ----------


 ---------- 2015-09-22 20:00:00 : 퇴계동   15386 ----------


 ---------- 2015-09-22 22:00:00 : 효자1동   15387 ----------


 ---------- 2015-09-23 01:00:00 : 석사동   15388 ----------


 ---------- 2015-09-23 09:00:00 : 남  면   15389 ----------


 ---------- 2015-09-23 09:00:00 : 사북면   15390 ----------


 ---------- 2015-09-23 11:00:00 : 신사우동   15391 ----------


 ---------- 2015-09-23 11:00:00 : 북산면   15392 ----------


 ---------- 2015-09-23 12:00:00 : 북산면   15394 ----------


 ---------- 2015-09-23 13:00:00 : 북산면   15395 ----------


 ---------- 2015-09-23 14:00:00 : 신사우동   15396 ----------


 ---------- 2015-09-23 15:00:00 : 사북면   15397 ----------


 ---------- 2015-09-23 15:00:00 : 소양동   15398 ----------


 ---------- 2015-09-23 20:00:00 : 근화동   15399 ----------


 ---------- 2015-09-23 21:00:00 : 동내면   15401 ----------


 ---------- 2015-09-23 22:00:00 : 동내면   15402 ----------


 ---------- 2015-09-24 09:00:00 : 효자1동   15403 ----------


 ---------- 2015-09-24 09:00:00 : 동  면   15404 ----------


 ---------- 2015-09-24 11:00:00 : 신사우동   15405 ----------


 ---------- 2015-09-24 13:00:00 : 강남동   15406 ----------


 ---------- 2015-09-24 14:00:00 : 강남동   15407 ----------


 ---------- 2015-09-24 14:00:00 : 남  면   15408 ----------


 ---------- 2015-09-24 17:00:00 : 신사우동   15409 ----------

 ---------- 2015-09-24 18:00:00 : 북산면   15412 ----------


 ---------- 2015-09-24 19:00:00 : 석사동   15413 ----------


 ---------- 2015-09-25 09:00:00 : 동내면   15414 ----------


 ---------- 2015-09-25 09:00:00 : 효자1동   15415 ----------


 ---------- 2015-09-25 09:00:00 : 소양동   15416 ----------


 ---------- 2015-09-25 11:00:00 : 동내면   15417 ----------


 ---------- 2015-09-25 11:00:00 : 동  면   15418 ----------


 ---------- 2015-09-25 13:00:00 : 퇴계동   15419 ----------


 ---------- 2015-09-25 14:00:00 : 소양동   15420 ----------


 ---------- 2015-09-25 14:00:00 : 퇴계동   15421 ----------


 ---------- 2015-09-25 17:00:00 : 퇴계동   15422 ----------


 ---------- 2015-09-25 18:00:00 : 동내면   15423 ----------


 ---------- 2015-09-26 09:00:00 : 약사명동   15425 ----------


 ---------- 2015-09-26 10:00:00 : 남산면   15426 ----------


 ---------- 2015-09-26 10:00:00 : 후평1동   15427 ----------


 ---------- 2015-09-26 11:00:00 : 후평1동   15428 ----------


 ---------- 2015-09-26 21:00:00 : 남산면   15430 ----------


 ---------- 2015-09-27 09:00:00 : 석사동   15431 ----------


 ---------- 2015-09-27 10:00:00 : 근화동   15432 ----------


 ---------- 2015-09-27 11:00:00 : 사북면   15433 ----------


 ---------- 2015-09-27 12:00:00 : 신동면   15434 ----------


 ---------- 2015-09-27 14:00:00 : 사북면   15435 ----------


 ---------- 2015-09-27 19:00:00 : 신동면   15436 ----------


 ---------- 2015-09-27 22:00:00 : 강남동   15437 ----------


 ---------- 2015-09-28 09:00:00 : 동내면   15438 ----------


 ---------- 2015-09-28 09:00:00 : 동  면   15439 ----------


 ---------- 2015-09-28 10:00:00 : 신동면   15440 ----------


 ---------- 2015-09-28 10:00:00 : 동  면   15441 ----------


 ---------- 2015-09-28 12:00:00 : 남  면   15442 ----------


 ---------- 2015-09-28 14:00:00 : 남산면   15444 ----------


 ---------- 2015-09-28 15:00:00 : 강남동   15445 ----------


 ---------- 2015-09-28 16:00:00 : 효자1동   15446 ----------


 ---------- 2015-09-28 18:00:00 : 신북읍   15447 ----------


 ---------- 2015-09-28 18:00:00 : 북산면   15448 ----------


 ---------- 2015-09-28 22:00:00 : 후평1동   15449 ----------


 ---------- 2015-09-28 23:00:00 : 서  면   15451 ----------


 ---------- 2015-09-29 02:00:00 : 효자1동   15452 ----------


 ---------- 2015-09-29 06:00:00 : 근화동   15453 ----------


 ---------- 2015-09-29 10:00:00 : 신북읍   15454 ----------


 ---------- 2015-09-29 12:00:00 : 남산면   15455 ----------


 ---------- 2015-09-29 15:00:00 : 남  면   15457 ----------


 ---------- 2015-09-29 15:00:00 : 사북면   15458 ----------


 ---------- 2015-09-29 15:00:00 : 효자1동   15459 ----------


 ---------- 2015-09-29 16:00:00 : 북산면   15460 ----------


 ---------- 2015-09-29 18:00:00 : 후평1동   15461 ----------


 ---------- 2015-09-29 18:00:00 : 퇴계동   15462 ----------


 ---------- 2015-09-29 21:00:00 : 석사동   15463 ----------


 ---------- 2015-09-29 22:00:00 : 퇴계동   15464 ----------


 ---------- 2015-09-30 00:00:00 : 동  면   15465 ----------


 ---------- 2015-09-30 05:00:00 : 효자1동   15466 ----------


 ---------- 2015-09-30 09:00:00 : 동내면   15467 ----------


 ---------- 2015-09-30 11:00:00 : 조운동   15468 ----------


 ---------- 2015-09-30 12:00:00 : 석사동   15469 ----------


 ---------- 2015-09-30 14:00:00 : 석사동   15470 ----------


 ---------- 2015-10-01 00:00:00 : 약사명동   15471 ----------


 ---------- 2015-10-01 08:00:00 : 퇴계동   15472 ----------


 ---------- 2015-10-01 09:00:00 : 남산면   15473 ----------


 ---------- 2015-10-01 09:00:00 : 신사우동   15474 ----------


 ---------- 2015-10-01 14:00:00 : 동내면   15476 ----------


 ---------- 2015-10-01 18:00:00 : 교  동   15477 ----------


 ---------- 2015-10-02 02:00:00 : 교  동   15478 ----------


 ---------- 2015-10-02 09:00:00 : 사북면   15479 ----------


 ---------- 2015-10-02 09:00:00 : 신북읍   15480 ----------


 ---------- 2015-10-02 13:00:00 : 동내면   15481 ----------


 ---------- 2015-10-02 14:00:00 : 효자1동   15482 ----------


 ---------- 2015-10-02 14:00:00 : 소양동   15483 ----------


 ---------- 2015-10-02 15:00:00 : 석사동   15484 ----------


 ---------- 2015-10-02 23:00:00 : 퇴계동   15486 ----------


 ---------- 2015-10-03 00:00:00 : 남산면   15488 ----------


 ---------- 2015-10-03 01:00:00 : 신사우동   15489 ----------


 ---------- 2015-10-03 08:00:00 : 후평1동   15490 ----------


 ---------- 2015-10-03 12:00:00 : 서  면   15491 ----------


 ---------- 2015-10-03 12:00:00 : 사북면   15492 ----------


 ---------- 2015-10-03 12:00:00 : 약사명동   15493 ----------


 ---------- 2015-10-03 13:00:00 : 북산면   15494 ----------


 ---------- 2015-10-03 14:00:00 : 남산면   15495 ----------


 ---------- 2015-10-03 14:00:00 : 동  면   15496 ----------


 ---------- 2015-10-03 15:00:00 : 동내면   15498 ----------


 ---------- 2015-10-03 15:00:00 : 효자1동   15499 ----------


 ---------- 2015-10-03 15:00:00 : 퇴계동   15500 ----------


 ---------- 2015-10-03 15:00:00 : 북산면   15501 ----------


 ---------- 2015-10-04 13:00:00 : 북산면   15505 ----------


 ---------- 2015-10-04 14:00:00 : 동산면   15506 ----------


 ---------- 2015-10-04 22:00:00 : 석사동   15507 ----------


 ---------- 2015-10-05 06:00:00 : 후평1동   15508 ----------


 ---------- 2015-10-05 08:00:00 : 소양동   15509 ----------


 ---------- 2015-10-05 09:00:00 : 남산면   15510 ----------


 ---------- 2015-10-05 11:00:00 : 신동면   15511 ----------


 ---------- 2015-10-05 11:00:00 : 후평1동   15512 ----------


 ---------- 2015-10-05 12:00:00 : 소양동   15513 ----------


 ---------- 2015-10-05 12:00:00 : 후평1동   15514 ----------


 ---------- 2015-10-05 14:00:00 : 서  면   15515 ----------


 ---------- 2015-10-05 14:00:00 : 남산면   15516 ----------


 ---------- 2015-10-05 14:00:00 : 동  면   15517 ----------


 ---------- 2015-10-05 16:00:00 : 동내면   15518 ----------


 ---------- 2015-10-06 01:00:00 : 석사동   15519 ----------


 ---------- 2015-10-06 02:00:00 : 후평1동   15520 ----------


 ---------- 2015-10-06 06:00:00 : 강남동   15521 ----------


 ---------- 2015-10-06 06:00:00 : 퇴계동   15522 ----------


 ---------- 2015-10-06 10:00:00 : 동  면   15523 ----------


 ---------- 2015-10-06 14:00:00 : 동내면   15524 ----------


 ---------- 2015-10-06 14:00:00 : 남산면   15525 ----------


 ---------- 2015-10-06 16:00:00 : 동내면   15526 ----------


 ---------- 2015-10-06 16:00:00 : 효자1동   15527 ----------


 ---------- 2015-10-06 17:00:00 : 사북면   15529 ----------


 ---------- 2015-10-06 18:00:00 : 효자1동   15530 ----------


 ---------- 2015-10-06 21:00:00 : 석사동   15532 ----------


 ---------- 2015-10-07 06:00:00 : 남산면   15534 ----------


 ---------- 2015-10-07 08:00:00 : 남산면   15535 ----------


 ---------- 2015-10-07 12:00:00 : 남산면   15536 ----------


 ---------- 2015-10-07 12:00:00 : 신북읍   15537 ----------


 ---------- 2015-10-07 12:00:00 : 소양동   15538 ----------


 ---------- 2015-10-07 13:00:00 : 강남동   15539 ----------


 ---------- 2015-10-07 13:00:00 : 서  면   15541 ----------


 ---------- 2015-10-07 14:00:00 : 강남동   15542 ----------


 ---------- 2015-10-07 14:00:00 : 남산면   15543 ----------


 ---------- 2015-10-07 14:00:00 : 동산면   15544 ----------


 ---------- 2015-10-07 15:00:00 : 남  면   15546 ----------


 ---------- 2015-10-07 17:00:00 : 강남동   15547 ----------


 ---------- 2015-10-07 18:00:00 : 사북면   15548 ----------


 ---------- 2015-10-08 09:00:00 : 사북면   15549 ----------


 ---------- 2015-10-08 11:00:00 : 신동면   15550 ----------


 ---------- 2015-10-08 11:00:00 : 근화동   15551 ----------


 ---------- 2015-10-08 13:00:00 : 사북면   15552 ----------


 ---------- 2015-10-08 13:00:00 : 동내면   15553 ----------


 ---------- 2015-10-08 13:00:00 : 신북읍   15554 ----------


 ---------- 2015-10-08 14:00:00 : 남산면   15555 ----------


 ---------- 2015-10-08 14:00:00 : 동  면   15556 ----------


 ---------- 2015-10-08 14:00:00 : 후평1동   15557 ----------


 ---------- 2015-10-08 16:00:00 : 동  면   15558 ----------


 ---------- 2015-10-08 21:00:00 : 후평1동   15559 ----------


 ---------- 2015-10-09 09:00:00 : 동내면   15560 ----------


 ---------- 2015-10-09 11:00:00 : 남산면   15563 ----------


 ---------- 2015-10-09 13:00:00 : 동산면   15564 ----------


 ---------- 2015-10-09 14:00:00 : 후평1동   15565 ----------


 ---------- 2015-10-09 18:00:00 : 후평1동   15566 ----------


 ---------- 2015-10-09 19:00:00 : 신동면   15567 ----------

 ---------- 2015-10-10 01:00:00 : 동  면   15568 ----------


 ---------- 2015-10-10 09:00:00 : 남산면   15570 ----------


 ---------- 2015-10-10 12:00:00 : 신사우동   15571 ----------


 ---------- 2015-10-10 16:00:00 : 남  면   15572 ----------


 ---------- 2015-10-11 10:00:00 : 석사동   15573 ----------


 ---------- 2015-10-11 10:00:00 : 신사우동   15575 ----------


 ---------- 2015-10-11 15:00:00 : 신동면   15576 ----------


 ---------- 2015-10-11 19:00:00 : 서  면   15578 ----------


 ---------- 2015-10-11 19:00:00 : 신사우동   15580 ----------


 ---------- 2015-10-11 21:00:00 : 동  면   15581 ----------


 ---------- 2015-10-11 23:00:00 : 동내면   15582 ----------


 ---------- 2015-10-12 07:00:00 : 강남동   15583 ----------


 ---------- 2015-10-12 20:00:00 : 남  면   15584 ----------


 ---------- 2015-10-13 03:00:00 : 조운동   15585 ----------


 ---------- 2015-10-13 08:00:00 : 남산면   15586 ----------


 ---------- 2015-10-13 08:00:00 : 후평1동   15587 ----------


 ---------- 2015-10-13 10:00:00 : 신북읍   15589 ----------


 ---------- 2015-10-13 15:00:00 : 강남동   15590 ----------


 ---------- 2015-10-13 18:00:00 : 석사동   15592 ----------


 ---------- 2015-10-14 11:00:00 : 근화동   15593 ----------


 ---------- 2015-10-14 12:00:00 : 석사동   15594 ----------


 ---------- 2015-10-14 12:00:00 : 소양동   15595 ----------


 ---------- 2015-10-14 15:00:00 : 약사명동   15596 ----------


 ---------- 2015-10-14 17:00:00 : 석사동   15597 ----------


 ---------- 2015-10-15 07:00:00 : 석사동   15598 ----------


 ---------- 2015-10-15 08:00:00 : 신사우동   15600 ----------


 ---------- 2015-10-15 09:00:00 : 북산면   15601 ----------


 ---------- 2015-10-15 10:00:00 : 동  면   15602 ----------


 ---------- 2015-10-15 11:00:00 : 후평1동   15603 ----------


 ---------- 2015-10-15 12:00:00 : 남산면   15604 ----------


 ---------- 2015-10-15 16:00:00 : 서  면   15605 ----------


 ---------- 2015-10-15 20:00:00 : 약사명동   15606 ----------


 ---------- 2015-10-16 08:00:00 : 동  면   15607 ----------


 ---------- 2015-10-16 10:00:00 : 근화동   15608 ----------


 ---------- 2015-10-16 16:00:00 : 동내면   15609 ----------


 ---------- 2015-10-16 19:00:00 : 동내면   15610 ----------


 ---------- 2015-10-17 00:00:00 : 근화동   15611 ----------


 ---------- 2015-10-17 01:00:00 : 사북면   15613 ----------


 ---------- 2015-10-17 08:00:00 : 사북면   15614 ----------


 ---------- 2015-10-17 11:00:00 : 퇴계동   15615 ----------


 ---------- 2015-10-17 12:00:00 : 강남동   15617 ----------


 ---------- 2015-10-17 13:00:00 : 남산면   15619 ----------


 ---------- 2015-10-17 18:00:00 : 후평1동   15620 ----------


 ---------- 2015-10-17 19:00:00 : 남산면   15622 ----------


 ---------- 2015-10-17 19:00:00 : 신사우동   15624 ----------


 ---------- 2015-10-18 00:00:00 : 남산면   15626 ----------


 ---------- 2015-10-18 05:00:00 : 석사동   15627 ----------


 ---------- 2015-10-18 09:00:00 : 후평1동   15628 ----------


 ---------- 2015-10-18 10:00:00 : 후평1동   15629 ----------


 ---------- 2015-10-18 14:00:00 : 신사우동   15630 ----------


 ---------- 2015-10-18 14:00:00 : 북산면   15632 ----------


 ---------- 2015-10-18 16:00:00 : 북산면   15633 ----------


 ---------- 2015-10-18 17:00:00 : 효자1동   15634 ----------


 ---------- 2015-10-19 08:00:00 : 강남동   15635 ----------


 ---------- 2015-10-19 13:00:00 : 신사우동   15636 ----------


 ---------- 2015-10-19 13:00:00 : 동  면   15638 ----------


 ---------- 2015-10-19 14:00:00 : 후평1동   15639 ----------


 ---------- 2015-10-19 18:00:00 : 동  면   15640 ----------


 ---------- 2015-10-19 20:00:00 : 석사동   15641 ----------


 ---------- 2015-10-20 04:00:00 : 후평1동   15642 ----------


 ---------- 2015-10-20 11:00:00 : 서  면   15643 ----------


 ---------- 2015-10-20 13:00:00 : 신사우동   15645 ----------


 ---------- 2015-10-20 13:00:00 : 신북읍   15646 ----------


 ---------- 2015-10-20 16:00:00 : 동  면   15647 ----------


 ---------- 2015-10-20 17:00:00 : 동  면   15648 ----------


 ---------- 2015-10-20 18:00:00 : 남산면   15649 ----------


 ---------- 2015-10-21 02:00:00 : 후평1동   15650 ----------


 ---------- 2015-10-21 03:00:00 : 동내면   15651 ----------


 ---------- 2015-10-21 07:00:00 : 북산면   15652 ----------


 ---------- 2015-10-21 08:00:00 : 북산면   15653 ----------


 ---------- 2015-10-21 10:00:00 : 동내면   15656 ----------


 ---------- 2015-10-21 11:00:00 : 서  면   15658 ----------


 ---------- 2015-10-21 11:00:00 : 후평1동   15659 ----------


 ---------- 2015-10-21 13:00:00 : 서  면   15660 ----------


 ---------- 2015-10-21 14:00:00 : 남  면   15661 ----------


 ---------- 2015-10-21 15:00:00 : 남산면   15664 ----------


 ---------- 2015-10-21 16:00:00 : 강남동   15666 ----------


 ---------- 2015-10-21 22:00:00 : 신사우동   15667 ----------


 ---------- 2015-10-22 02:00:00 : 근화동   15668 ----------


 ---------- 2015-10-22 03:00:00 : 근화동   15669 ----------


 ---------- 2015-10-22 09:00:00 : 석사동   15670 ----------


 ---------- 2015-10-22 12:00:00 : 강남동   15672 ----------


 ---------- 2015-10-22 13:00:00 : 동내면   15673 ----------


 ---------- 2015-10-22 13:00:00 : 신사우동   15674 ----------


 ---------- 2015-10-22 16:00:00 : 효자1동   15675 ----------


 ---------- 2015-10-22 23:00:00 : 퇴계동   15676 ----------


 ---------- 2015-10-23 09:00:00 : 남  면   15677 ----------


 ---------- 2015-10-23 11:00:00 : 강남동   15678 ----------


 ---------- 2015-10-23 12:00:00 : 효자1동   15680 ----------


 ---------- 2015-10-23 12:00:00 : 신북읍   15682 ----------


 ---------- 2015-10-23 17:00:00 : 후평1동   15683 ----------


 ---------- 2015-10-23 18:00:00 : 서  면   15684 ----------


 ---------- 2015-10-23 23:00:00 : 후평1동   15685 ----------


 ---------- 2015-10-24 09:00:00 : 신북읍   15686 ----------


 ---------- 2015-10-24 11:00:00 : 남산면   15687 ----------


 ---------- 2015-10-24 12:00:00 : 서  면   15688 ----------


 ---------- 2015-10-24 12:00:00 : 남산면   15689 ----------


 ---------- 2015-10-24 16:00:00 : 근화동   15690 ----------


 ---------- 2015-10-25 08:00:00 : 근화동   15691 ----------


 ---------- 2015-10-25 09:00:00 : 서  면   15693 ----------


 ---------- 2015-10-25 14:00:00 : 동내면   15694 ----------


 ---------- 2015-10-25 15:00:00 : 신사우동   15695 ----------


 ---------- 2015-10-25 15:00:00 : 조운동   15696 ----------


 ---------- 2015-10-25 18:00:00 : 신사우동   15697 ----------


 ---------- 2015-10-25 18:00:00 : 동  면   15698 ----------


 ---------- 2015-10-25 19:00:00 : 석사동   15699 ----------


 ---------- 2015-10-25 19:00:00 : 교  동   15700 ----------


 ---------- 2015-10-26 03:00:00 : 동  면   15701 ----------


 ---------- 2015-10-26 03:00:00 : 퇴계동   15702 ----------


 ---------- 2015-10-26 04:00:00 : 석사동   15703 ----------


 ---------- 2015-10-26 11:00:00 : 석사동   15704 ----------


 ---------- 2015-10-26 12:00:00 : 동  면   15705 ----------


 ---------- 2015-10-26 14:00:00 : 조운동   15706 ----------


 ---------- 2015-10-26 15:00:00 : 남산면   15707 ----------


 ---------- 2015-10-26 15:00:00 : 신사우동   15708 ----------


 ---------- 2015-10-26 17:00:00 : 신사우동   15709 ----------


 ---------- 2015-10-26 18:00:00 : 동  면   15711 ----------


 ---------- 2015-10-26 21:00:00 : 동내면   15712 ----------


 ---------- 2015-10-26 21:00:00 : 신사우동   15713 ----------


 ---------- 2015-10-26 23:00:00 : 후평1동   15714 ----------


 ---------- 2015-10-27 08:00:00 : 소양동   15715 ----------


 ---------- 2015-10-27 09:00:00 : 효자1동   15716 ----------


 ---------- 2015-10-27 14:00:00 : 동산면   15718 ----------


 ---------- 2015-10-27 15:00:00 : 강남동   15720 ----------


 ---------- 2015-10-27 15:00:00 : 효자1동   15721 ----------


 ---------- 2015-10-27 15:00:00 : 퇴계동   15722 ----------


 ---------- 2015-10-27 16:00:00 : 동내면   15724 ----------


 ---------- 2015-10-27 21:00:00 : 신사우동   15725 ----------


 ---------- 2015-10-28 02:00:00 : 후평1동   15726 ----------


 ---------- 2015-10-28 08:00:00 : 동산면   15727 ----------


 ---------- 2015-10-28 09:00:00 : 퇴계동   15728 ----------


 ---------- 2015-10-28 17:00:00 : 석사동   15729 ----------


 ---------- 2015-10-28 18:00:00 : 효자1동   15730 ----------


 ---------- 2015-10-29 01:00:00 : 신북읍   15731 ----------


 ---------- 2015-10-29 09:00:00 : 석사동   15732 ----------


 ---------- 2015-10-29 09:00:00 : 동  면   15733 ----------

 ---------- 2015-10-29 13:00:00 : 후평1동   15734 ----------


 ---------- 2015-10-29 21:00:00 : 후평1동   15735 ----------


 ---------- 2015-10-30 00:00:00 : 효자1동   15736 ----------


 ---------- 2015-10-30 07:00:00 : 남산면   15737 ----------


 ---------- 2015-10-30 08:00:00 : 후평1동   15738 ----------


 ---------- 2015-10-30 10:00:00 : 남산면   15739 ----------


 ---------- 2015-10-30 22:00:00 : 후평1동   15740 ----------


 ---------- 2015-10-31 09:00:00 : 동  면   15741 ----------


 ---------- 2015-10-31 11:00:00 : 석사동   15742 ----------


 ---------- 2015-10-31 13:00:00 : 후평1동   15743 ----------


 ---------- 2015-10-31 14:00:00 : 동산면   15744 ----------


 ---------- 2015-10-31 15:00:00 : 서  면   15745 ----------


 ---------- 2015-11-01 01:00:00 : 효자1동   15746 ----------


 ---------- 2015-11-01 02:00:00 : 후평1동   15747 ----------


 ---------- 2015-11-01 04:00:00 : 후평1동   15748 ----------


 ---------- 2015-11-01 10:00:00 : 효자1동   15749 ----------


 ---------- 2015-11-01 11:00:00 : 신사우동   15750 ----------


 ---------- 2015-11-01 14:00:00 : 신사우동   15751 ----------


 ---------- 2015-11-01 14:00:00 : 후평1동   15752 ----------


 ---------- 2015-11-01 15:00:00 : 퇴계동   15753 ----------


 ---------- 2015-11-01 23:00:00 : 퇴계동   15754 ----------


 ---------- 2015-11-02 03:00:00 : 후평1동   15755 ----------


 ---------- 2015-11-02 12:00:00 : 후평1동   15756 ----------


 ---------- 2015-11-02 13:00:00 : 교  동   15757 ----------


 ---------- 2015-11-02 14:00:00 : 남산면   15758 ----------


 ---------- 2015-11-02 16:00:00 : 후평1동   15759 ----------


 ---------- 2015-11-02 16:00:00 : 동산면   15760 ----------


 ---------- 2015-11-02 19:00:00 : 강남동   15761 ----------


 ---------- 2015-11-02 19:00:00 : 소양동   15762 ----------


 ---------- 2015-11-03 00:00:00 : 근화동   15763 ----------


 ---------- 2015-11-03 10:00:00 : 동  면   15765 ----------


 ---------- 2015-11-03 19:00:00 : 신동면   15766 ----------


 ---------- 2015-11-04 12:00:00 : 사북면   15767 ----------


 ---------- 2015-11-04 13:00:00 : 석사동   15768 ----------


 ---------- 2015-11-05 08:00:00 : 교  동   15769 ----------


 ---------- 2015-11-05 14:00:00 : 교  동   15770 ----------


 ---------- 2015-11-05 18:00:00 : 신사우동   15771 ----------


 ---------- 2015-11-05 20:00:00 : 강남동   15772 ----------


 ---------- 2015-11-05 23:00:00 : 퇴계동   15773 ----------


 ---------- 2015-11-06 11:00:00 : 석사동   15774 ----------


 ---------- 2015-11-06 16:00:00 : 남산면   15776 ----------


 ---------- 2015-11-06 17:00:00 : 후평1동   15777 ----------


 ---------- 2015-11-06 20:00:00 : 신사우동   15778 ----------


 ---------- 2015-11-07 09:00:00 : 소양동   15779 ----------


 ---------- 2015-11-07 17:00:00 : 동  면   15780 ----------


 ---------- 2015-11-08 04:00:00 : 남산면   15781 ----------


 ---------- 2015-11-08 09:00:00 : 후평1동   15782 ----------


 ---------- 2015-11-08 12:00:00 : 석사동   15783 ----------


 ---------- 2015-11-08 13:00:00 : 후평1동   15784 ----------


 ---------- 2015-11-08 15:00:00 : 신사우동   15785 ----------


 ---------- 2015-11-08 15:00:00 : 동  면   15786 ----------


 ---------- 2015-11-08 16:00:00 : 동  면   15787 ----------


 ---------- 2015-11-08 18:00:00 : 남산면   15788 ----------


 ---------- 2015-11-09 08:00:00 : 남  면   15789 ----------


 ---------- 2015-11-09 10:00:00 : 동  면   15790 ----------


 ---------- 2015-11-09 15:00:00 : 동산면   15792 ----------


 ---------- 2015-11-09 18:00:00 : 퇴계동   15793 ----------


 ---------- 2015-11-10 09:00:00 : 동산면   15794 ----------


 ---------- 2015-11-10 10:00:00 : 동  면   15795 ----------


 ---------- 2015-11-10 11:00:00 : 신사우동   15796 ----------


 ---------- 2015-11-10 14:00:00 : 효자1동   15797 ----------


 ---------- 2015-11-10 22:00:00 : 후평1동   15798 ----------


 ---------- 2015-11-11 01:00:00 : 후평1동   15799 ----------


 ---------- 2015-11-11 07:00:00 : 퇴계동   15800 ----------


 ---------- 2015-11-11 15:00:00 : 신북읍   15801 ----------


 ---------- 2015-11-11 22:00:00 : 석사동   15802 ----------


 ---------- 2015-11-11 23:00:00 : 강남동   15803 ----------


 ---------- 2015-11-12 11:00:00 : 동  면   15804 ----------


 ---------- 2015-11-12 11:00:00 : 조운동   15806 ----------


 ---------- 2015-11-13 11:00:00 : 퇴계동   15807 ----------


 ---------- 2015-11-14 14:00:00 : 동내면   15808 ----------


 ---------- 2015-11-14 20:00:00 : 조운동   15809 ----------


 ---------- 2015-11-14 22:00:00 : 퇴계동   15811 ----------


 ---------- 2015-11-15 02:00:00 : 근화동   15812 ----------


 ---------- 2015-11-15 09:00:00 : 강남동   15813 ----------


 ---------- 2015-11-15 10:00:00 : 동  면   15814 ----------


 ---------- 2015-11-15 13:00:00 : 석사동   15815 ----------


 ---------- 2015-11-15 14:00:00 : 강남동   15816 ----------


 ---------- 2015-11-15 22:00:00 : 석사동   15817 ----------


 ---------- 2015-11-16 07:00:00 : 동내면   15818 ----------


 ---------- 2015-11-16 09:00:00 : 효자1동   15819 ----------


 ---------- 2015-11-16 15:00:00 : 동  면   15820 ----------


 ---------- 2015-11-16 16:00:00 : 동  면   15821 ----------


 ---------- 2015-11-16 18:00:00 : 동  면   15822 ----------


 ---------- 2015-11-16 20:00:00 : 효자1동   15823 ----------


 ---------- 2015-11-17 13:00:00 : 남산면   15824 ----------


 ---------- 2015-11-18 01:00:00 : 남산면   15826 ----------


 ---------- 2015-11-18 08:00:00 : 후평1동   15827 ----------


 ---------- 2015-11-18 19:00:00 : 소양동   15828 ----------


 ---------- 2015-11-19 02:00:00 : 동내면   15829 ----------


 ---------- 2015-11-19 07:00:00 : 후평1동   15830 ----------


 ---------- 2015-11-19 22:00:00 : 석사동   15831 ----------


 ---------- 2015-11-19 22:00:00 : 효자1동   15832 ----------


 ---------- 2015-11-19 23:00:00 : 석사동   15833 ----------


 ---------- 2015-11-19 23:00:00 : 동  면   15834 ----------


 ---------- 2015-11-20 00:00:00 : 동내면   15836 ----------


 ---------- 2015-11-20 09:00:00 : 남산면   15837 ----------


 ---------- 2015-11-20 10:00:00 : 동  면   15838 ----------


 ---------- 2015-11-20 10:00:00 : 퇴계동   15839 ----------


 ---------- 2015-11-20 18:00:00 : 북산면   15840 ----------


 ---------- 2015-11-20 23:00:00 : 효자1동   15841 ----------


 ---------- 2015-11-21 05:00:00 : 석사동   15842 ----------


 ---------- 2015-11-21 08:00:00 : 신동면   15843 ----------


 ---------- 2015-11-21 16:00:00 : 신북읍   15844 ----------


 ---------- 2015-11-21 16:00:00 : 후평1동   15845 ----------


 ---------- 2015-11-21 16:00:00 : 퇴계동   15846 ----------


 ---------- 2015-11-21 17:00:00 : 동  면   15847 ----------


 ---------- 2015-11-21 21:00:00 : 강남동   15848 ----------


 ---------- 2015-11-22 00:00:00 : 동  면   15849 ----------


 ---------- 2015-11-22 06:00:00 : 소양동   15850 ----------


 ---------- 2015-11-22 13:00:00 : 석사동   15851 ----------


 ---------- 2015-11-22 13:00:00 : 남산면   15853 ----------


 ---------- 2015-11-22 16:00:00 : 서  면   15855 ----------


 ---------- 2015-11-22 16:00:00 : 동산면   15856 ----------


 ---------- 2015-11-22 21:00:00 : 퇴계동   15857 ----------


 ---------- 2015-11-23 07:00:00 : 강남동   15858 ----------


 ---------- 2015-11-23 10:00:00 : 동내면   15859 ----------


 ---------- 2015-11-23 11:00:00 : 신북읍   15860 ----------


 ---------- 2015-11-23 12:00:00 : 사북면   15862 ----------


 ---------- 2015-11-23 18:00:00 : 석사동   15863 ----------


 ---------- 2015-11-23 21:00:00 : 석사동   15864 ----------


 ---------- 2015-11-24 05:00:00 : 신북읍   15865 ----------


 ---------- 2015-11-24 15:00:00 : 효자1동   15866 ----------


 ---------- 2015-11-24 15:00:00 : 퇴계동   15867 ----------


 ---------- 2015-11-25 08:00:00 : 석사동   15868 ----------


 ---------- 2015-11-25 09:00:00 : 약사명동   15869 ----------


 ---------- 2015-11-25 15:00:00 : 후평1동   15870 ----------


 ---------- 2015-11-25 16:00:00 : 후평1동   15871 ----------


 ---------- 2015-11-25 17:00:00 : 동  면   15872 ----------


 ---------- 2015-11-25 20:00:00 : 동  면   15873 ----------


 ---------- 2015-11-25 21:00:00 : 석사동   15874 ----------


 ---------- 2015-11-26 00:00:00 : 퇴계동   15875 ----------


 ---------- 2015-11-26 04:00:00 : 신동면   15876 ----------


 ---------- 2015-11-26 19:00:00 : 동  면   15877 ----------


 ---------- 2015-11-26 21:00:00 : 석사동   15878 ----------


 ---------- 2015-11-27 09:00:00 : 석사동   15879 ----------

 ---------- 2015-11-27 14:00:00 : 신사우동   15881 ----------


 ---------- 2015-11-27 17:00:00 : 강남동   15882 ----------


 ---------- 2015-11-27 19:00:00 : 효자1동   15883 ----------


 ---------- 2015-11-27 21:00:00 : 소양동   15884 ----------


 ---------- 2015-11-28 01:00:00 : 강남동   15885 ----------


 ---------- 2015-11-28 08:00:00 : 신북읍   15887 ----------


 ---------- 2015-11-28 10:00:00 : 사북면   15889 ----------


 ---------- 2015-11-28 18:00:00 : 동내면   15890 ----------


 ---------- 2015-11-28 21:00:00 : 퇴계동   15891 ----------


 ---------- 2015-11-29 10:00:00 : 후평1동   15892 ----------


 ---------- 2015-11-29 14:00:00 : 강남동   15893 ----------


 ---------- 2015-11-29 18:00:00 : 석사동   15894 ----------


 ---------- 2015-11-30 07:00:00 : 신동면   15895 ----------


 ---------- 2015-11-30 12:00:00 : 근화동   15896 ----------


 ---------- 2015-11-30 13:00:00 : 동산면   15897 ----------


 ---------- 2015-11-30 17:00:00 : 서  면   15898 ----------


 ---------- 2015-11-30 20:00:00 : 효자1동   15899 ----------


 ---------- 2015-12-01 00:00:00 : 후평1동   15900 ----------


 ---------- 2015-12-01 09:00:00 : 후평1동   15901 ----------


 ---------- 2015-12-01 10:00:00 : 후평1동   15902 ----------


 ---------- 2015-12-01 19:00:00 : 신동면   15903 ----------


 ---------- 2015-12-01 23:00:00 : 소양동   15904 ----------


 ---------- 2015-12-02 00:00:00 : 신사우동   15905 ----------


 ---------- 2015-12-02 10:00:00 : 소양동   15906 ----------


 ---------- 2015-12-02 15:00:00 : 교  동   15907 ----------


 ---------- 2015-12-03 00:00:00 : 효자1동   15909 ----------


 ---------- 2015-12-03 01:00:00 : 석사동   15911 ----------


 ---------- 2015-12-03 13:00:00 : 사북면   15913 ----------


 ---------- 2015-12-03 17:00:00 : 동산면   15914 ----------


 ---------- 2015-12-03 21:00:00 : 퇴계동   15915 ----------


 ---------- 2015-12-05 23:00:00 : 석사동   15916 ----------


 ---------- 2015-12-06 13:00:00 : 남산면   15918 ----------


 ---------- 2015-12-07 11:00:00 : 후평1동   15919 ----------


 ---------- 2015-12-07 23:00:00 : 근화동   15920 ----------


 ---------- 2015-12-08 00:00:00 : 동  면   15921 ----------


 ---------- 2015-12-08 02:00:00 : 근화동   15922 ----------


 ---------- 2015-12-08 10:00:00 : 남산면   15924 ----------


 ---------- 2015-12-08 11:00:00 : 서  면   15926 ----------


 ---------- 2015-12-08 16:00:00 : 동  면   15928 ----------


 ---------- 2015-12-08 20:00:00 : 후평1동   15930 ----------


 ---------- 2015-12-09 16:00:00 : 퇴계동   15931 ----------


 ---------- 2015-12-10 08:00:00 : 동내면   15933 ----------


 ---------- 2015-12-10 08:00:00 : 근화동   15934 ----------


 ---------- 2015-12-10 17:00:00 : 후평1동   15935 ----------


 ---------- 2015-12-11 07:00:00 : 동산면   15937 ----------


 ---------- 2015-12-11 10:00:00 : 신동면   15939 ----------


 ---------- 2015-12-11 18:00:00 : 동내면   15940 ----------


 ---------- 2015-12-11 19:00:00 : 동내면   15941 ----------


 ---------- 2015-12-12 02:00:00 : 조운동   15942 ----------


 ---------- 2015-12-12 13:00:00 : 남산면   15944 ----------


 ---------- 2015-12-12 18:00:00 : 동내면   15946 ----------


 ---------- 2015-12-13 00:00:00 : 약사명동   15947 ----------


 ---------- 2015-12-13 02:00:00 : 효자1동   15948 ----------


 ---------- 2015-12-13 03:00:00 : 북산면   15949 ----------


 ---------- 2015-12-13 17:00:00 : 효자1동   15950 ----------


 ---------- 2015-12-13 19:00:00 : 조운동   15951 ----------


 ---------- 2015-12-14 17:00:00 : 서  면   15953 ----------


 ---------- 2015-12-14 17:00:00 : 효자1동   15954 ----------


 ---------- 2015-12-14 20:00:00 : 소양동   15955 ----------


 ---------- 2015-12-14 21:00:00 : 후평1동   15956 ----------


 ---------- 2015-12-15 09:00:00 : 남  면   15957 ----------


 ---------- 2015-12-15 18:00:00 : 석사동   15958 ----------


 ---------- 2015-12-15 20:00:00 : 신사우동   15959 ----------


 ---------- 2015-12-16 02:00:00 : 석사동   15960 ----------


 ---------- 2015-12-16 04:00:00 : 효자1동   15961 ----------


 ---------- 2015-12-16 08:00:00 : 신동면   15962 ----------


 ---------- 2015-12-16 14:00:00 : 신사우동   15963 ----------


 ---------- 2015-12-16 15:00:00 : 후평1동   15964 ----------


 ---------- 2015-12-16 20:00:00 : 퇴계동   15965 ----------


 ---------- 2015-12-16 23:00:00 : 소양동   15966 ----------


 ---------- 2015-12-17 09:00:00 : 후평1동   15967 ----------


 ---------- 2015-12-17 10:00:00 : 근화동   15968 ----------


 ---------- 2015-12-17 22:00:00 : 퇴계동   15969 ----------


 ---------- 2015-12-18 12:00:00 : 석사동   15970 ----------


 ---------- 2015-12-18 13:00:00 : 후평1동   15971 ----------


 ---------- 2015-12-18 14:00:00 : 동내면   15974 ----------


 ---------- 2015-12-18 17:00:00 : 후평1동   15975 ----------


 ---------- 2015-12-18 22:00:00 : 후평1동   15976 ----------


 ---------- 2015-12-19 05:00:00 : 신사우동   15977 ----------


 ---------- 2015-12-19 15:00:00 : 신사우동   15978 ----------


 ---------- 2015-12-19 17:00:00 : 동내면   15979 ----------


 ---------- 2015-12-20 12:00:00 : 석사동   15980 ----------


 ---------- 2015-12-20 17:00:00 : 신북읍   15983 ----------


 ---------- 2015-12-20 18:00:00 : 강남동   15984 ----------


 ---------- 2015-12-20 21:00:00 : 석사동   15985 ----------


 ---------- 2015-12-21 09:00:00 : 동산면   15987 ----------


 ---------- 2015-12-21 10:00:00 : 사북면   15989 ----------


 ---------- 2015-12-21 14:00:00 : 동내면   15990 ----------


 ---------- 2015-12-22 17:00:00 : 석사동   15992 ----------


 ---------- 2015-12-23 18:00:00 : 효자1동   15993 ----------


 ---------- 2015-12-25 06:00:00 : 신동면   15995 ----------


 ---------- 2015-12-25 06:00:00 : 강남동   15996 ----------


 ---------- 2015-12-25 17:00:00 : 석사동   15997 ----------


 ---------- 2015-12-25 22:00:00 : 퇴계동   15998 ----------


 ---------- 2015-12-26 13:00:00 : 퇴계동   15999 ----------


 ---------- 2015-12-26 16:00:00 : 동  면   16001 ----------


 ---------- 2015-12-26 19:00:00 : 신북읍   16003 ----------


 ---------- 2015-12-27 08:00:00 : 근화동   16004 ----------


 ---------- 2015-12-27 14:00:00 : 남산면   16005 ----------


 ---------- 2015-12-27 18:00:00 : 신동면   16007 ----------


 ---------- 2015-12-27 23:00:00 : 후평1동   16008 ----------


 ---------- 2015-12-28 01:00:00 : 교  동   16009 ----------


 ---------- 2015-12-28 10:00:00 : 강남동   16010 ----------


 ---------- 2015-12-28 15:00:00 : 신동면   16011 ----------


 ---------- 2015-12-29 14:00:00 : 신북읍   16012 ----------


 ---------- 2015-12-29 19:00:00 : 후평1동   16013 ----------


 ---------- 2015-12-29 20:00:00 : 소양동   16014 ----------


 ---------- 2015-12-30 00:00:00 : 약사명동   16015 ----------


 ---------- 2015-12-30 02:00:00 : 석사동   16016 ----------


 ---------- 2015-12-30 08:00:00 : 석사동   16017 ----------


 ---------- 2015-12-30 13:00:00 : 신사우동   16018 ----------


 ---------- 2015-12-30 15:00:00 : 석사동   16019 ----------


 ---------- 2015-12-30 23:00:00 : 후평1동   16020 ----------


 ---------- 2015-12-31 01:00:00 : 후평1동   16021 ----------


 ---------- 2015-12-31 04:00:00 : 효자1동   16022 ----------


 ---------- 2015-12-31 08:00:00 : 신동면   16023 ----------


 ---------- 2015-12-31 23:00:00 : 후평1동   16024 ----------


 ---------- 2016-01-01 01:00:00 : 퇴계동   16025 ----------


 ---------- 2016-01-01 03:00:00 : 신사우동   16026 ----------


 ---------- 2016-01-01 18:00:00 : 후평1동   16027 ----------


 ---------- 2016-01-01 19:00:00 : 남  면   16028 ----------


 ---------- 2016-01-02 02:00:00 : 효자1동   16029 ----------


 ---------- 2016-01-02 13:00:00 : 남산면   16031 ----------


 ---------- 2016-01-02 15:00:00 : 강남동   16032 ----------


 ---------- 2016-01-02 15:00:00 : 신북읍   16033 ----------


 ---------- 2016-01-02 17:00:00 : 동  면   16034 ----------


 ---------- 2016-01-02 20:00:00 : 남산면   16035 ----------


 ---------- 2016-01-02 21:00:00 : 근화동   16036 ----------


 ---------- 2016-01-03 17:00:00 : 신사우동   16037 ----------


 ---------- 2016-01-04 08:00:00 : 약사명동   16038 ----------


 ---------- 2016-01-04 19:00:00 : 근화동   16039 ----------


 ---------- 2016-01-06 08:00:00 : 퇴계동   16040 ----------


 ---------- 2016-01-06 12:00:00 : 남산면   16043 ----------


 ---------- 2016-01-06 22:00:00 : 후평1동   16044 ----------


 ---------- 2016-01-07 08:00:00 : 서  면   16048 ----------


 ---------- 2016-01-07 19:00:00 : 효자1동   16049 ----------


 ---------- 2016-01-07 19:00:00 : 퇴계동   16050 ----------

 ---------- 2016-01-07 23:00:00 : 후평1동   16051 ----------


 ---------- 2016-01-08 03:00:00 : 효자1동   16052 ----------


 ---------- 2016-01-09 13:00:00 : 신사우동   16054 ----------


 ---------- 2016-01-09 15:00:00 : 신사우동   16055 ----------


 ---------- 2016-01-09 18:00:00 : 근화동   16056 ----------


 ---------- 2016-01-10 15:00:00 : 후평1동   16057 ----------


 ---------- 2016-01-10 22:00:00 : 동  면   16059 ----------


 ---------- 2016-01-11 07:00:00 : 석사동   16060 ----------


 ---------- 2016-01-11 08:00:00 : 퇴계동   16062 ----------


 ---------- 2016-01-11 15:00:00 : 강남동   16063 ----------


 ---------- 2016-01-11 22:00:00 : 동산면   16066 ----------


 ---------- 2016-01-11 23:00:00 : 동산면   16067 ----------


 ---------- 2016-01-12 06:00:00 : 서  면   16068 ----------


 ---------- 2016-01-12 07:00:00 : 동산면   16069 ----------


 ---------- 2016-01-12 16:00:00 : 석사동   16070 ----------


 ---------- 2016-01-12 21:00:00 : 남산면   16071 ----------


 ---------- 2016-01-12 22:00:00 : 남  면   16073 ----------


 ---------- 2016-01-13 08:00:00 : 동  면   16074 ----------


 ---------- 2016-01-13 11:00:00 : 동내면   16075 ----------


 ---------- 2016-01-13 14:00:00 : 서  면   16076 ----------


 ---------- 2016-01-14 03:00:00 : 후평1동   16077 ----------


 ---------- 2016-01-15 00:00:00 : 퇴계동   16078 ----------


 ---------- 2016-01-15 03:00:00 : 후평1동   16079 ----------


 ---------- 2016-01-15 10:00:00 : 근화동   16080 ----------


 ---------- 2016-01-15 18:00:00 : 신북읍   16081 ----------


 ---------- 2016-01-15 22:00:00 : 근화동   16082 ----------


 ---------- 2016-01-16 09:00:00 : 퇴계동   16083 ----------


 ---------- 2016-01-16 17:00:00 : 석사동   16084 ----------


 ---------- 2016-01-16 18:00:00 : 남  면   16086 ----------


 ---------- 2016-01-17 00:00:00 : 석사동   16087 ----------


 ---------- 2016-01-17 07:00:00 : 남  면   16089 ----------


 ---------- 2016-01-17 13:00:00 : 신북읍   16091 ----------


 ---------- 2016-01-18 05:00:00 : 동  면   16093 ----------


 ---------- 2016-01-18 12:00:00 : 후평1동   16094 ----------


 ---------- 2016-01-18 14:00:00 : 후평1동   16095 ----------


 ---------- 2016-01-19 06:00:00 : 소양동   16096 ----------


 ---------- 2016-01-19 08:00:00 : 석사동   16097 ----------


 ---------- 2016-01-19 18:00:00 : 신동면   16098 ----------


 ---------- 2016-01-20 04:00:00 : 소양동   16099 ----------


 ---------- 2016-01-20 13:00:00 : 후평1동   16100 ----------


 ---------- 2016-01-20 20:00:00 : 신사우동   16101 ----------


 ---------- 2016-01-21 09:00:00 : 사북면   16102 ----------


 ---------- 2016-01-21 11:00:00 : 서  면   16103 ----------


 ---------- 2016-01-21 20:00:00 : 강남동   16104 ----------


 ---------- 2016-01-22 06:00:00 : 신북읍   16105 ----------


 ---------- 2016-01-22 23:00:00 : 석사동   16106 ----------


 ---------- 2016-01-23 02:00:00 : 퇴계동   16107 ----------


 ---------- 2016-01-23 20:00:00 : 신동면   16108 ----------


 ---------- 2016-01-24 03:00:00 : 사북면   16110 ----------


 ---------- 2016-01-24 03:00:00 : 동내면   16112 ----------


 ---------- 2016-01-24 07:00:00 : 사북면   16113 ----------


 ---------- 2016-01-24 09:00:00 : 효자1동   16114 ----------


 ---------- 2016-01-24 11:00:00 : 약사명동   16115 ----------


 ---------- 2016-01-25 12:00:00 : 효자1동   16116 ----------


 ---------- 2016-01-25 13:00:00 : 효자1동   16117 ----------


 ---------- 2016-01-25 14:00:00 : 약사명동   16118 ----------


 ---------- 2016-01-25 17:00:00 : 석사동   16119 ----------


 ---------- 2016-01-25 18:00:00 : 효자1동   16120 ----------


 ---------- 2016-01-25 18:00:00 : 신북읍   16121 ----------


 ---------- 2016-01-25 20:00:00 : 강남동   16122 ----------


 ---------- 2016-01-25 21:00:00 : 신사우동   16123 ----------


 ---------- 2016-01-25 23:00:00 : 신사우동   16126 ----------


 ---------- 2016-01-26 01:00:00 : 서  면   16128 ----------


 ---------- 2016-01-26 03:00:00 : 사북면   16129 ----------


 ---------- 2016-01-26 03:00:00 : 동내면   16130 ----------


 ---------- 2016-01-26 08:00:00 : 후평1동   16131 ----------


 ---------- 2016-01-26 09:00:00 : 약사명동   16132 ----------


 ---------- 2016-01-26 10:00:00 : 사북면   16133 ----------


 ---------- 2016-01-26 12:00:00 : 후평1동   16134 ----------


 ---------- 2016-01-26 16:00:00 : 북산면   16135 ----------


 ---------- 2016-01-26 21:00:00 : 소양동   16136 ----------


 ---------- 2016-01-26 22:00:00 : 소양동   16137 ----------


 ---------- 2016-01-27 00:00:00 : 후평1동   16138 ----------


 ---------- 2016-01-27 10:00:00 : 북산면   16139 ----------


 ---------- 2016-01-27 12:00:00 : 후평1동   16140 ----------


 ---------- 2016-01-27 14:00:00 : 후평1동   16142 ----------


 ---------- 2016-01-28 19:00:00 : 석사동   16143 ----------


 ---------- 2016-01-28 20:00:00 : 석사동   16144 ----------


 ---------- 2016-01-28 20:00:00 : 퇴계동   16145 ----------


 ---------- 2016-01-29 00:00:00 : 후평1동   16146 ----------


 ---------- 2016-01-29 06:00:00 : 효자1동   16147 ----------


 ---------- 2016-01-29 11:00:00 : 소양동   16148 ----------


 ---------- 2016-01-29 15:00:00 : 후평1동   16149 ----------


 ---------- 2016-01-29 23:00:00 : 후평1동   16150 ----------


 ---------- 2016-01-30 02:00:00 : 사북면   16153 ----------


 ---------- 2016-01-30 03:00:00 : 후평1동   16154 ----------


 ---------- 2016-01-30 07:00:00 : 효자1동   16155 ----------


 ---------- 2016-01-30 12:00:00 : 신사우동   16157 ----------


 ---------- 2016-01-30 13:00:00 : 석사동   16158 ----------


 ---------- 2016-01-30 14:00:00 : 후평1동   16159 ----------


 ---------- 2016-01-30 17:00:00 : 사북면   16160 ----------


 ---------- 2016-01-30 18:00:00 : 효자1동   16161 ----------


 ---------- 2016-01-30 21:00:00 : 교  동   16162 ----------


 ---------- 2016-01-31 02:00:00 : 강남동   16163 ----------


 ---------- 2016-01-31 07:00:00 : 후평1동   16165 ----------


 ---------- 2016-01-31 10:00:00 : 동내면   16166 ----------


 ---------- 2016-01-31 11:00:00 : 신북읍   16167 ----------


 ---------- 2016-01-31 12:00:00 : 후평1동   16168 ----------


 ---------- 2016-01-31 13:00:00 : 동내면   16169 ----------


 ---------- 2016-01-31 14:00:00 : 신북읍   16171 ----------


 ---------- 2016-01-31 18:00:00 : 후평1동   16172 ----------


 ---------- 2016-01-31 18:00:00 : 퇴계동   16173 ----------


 ---------- 2016-02-01 07:00:00 : 동  면   16175 ----------


 ---------- 2016-02-01 09:00:00 : 동  면   16176 ----------


 ---------- 2016-02-01 11:00:00 : 후평1동   16177 ----------


 ---------- 2016-02-01 12:00:00 : 신사우동   16178 ----------


 ---------- 2016-02-01 16:00:00 : 퇴계동   16179 ----------


 ---------- 2016-02-01 17:00:00 : 남  면   16180 ----------


 ---------- 2016-02-01 18:00:00 : 효자1동   16181 ----------


 ---------- 2016-02-01 18:00:00 : 근화동   16182 ----------


 ---------- 2016-02-01 20:00:00 : 후평1동   16183 ----------


 ---------- 2016-02-02 10:00:00 : 퇴계동   16184 ----------


 ---------- 2016-02-02 13:00:00 : 강남동   16185 ----------


 ---------- 2016-02-02 14:00:00 : 신북읍   16186 ----------


 ---------- 2016-02-02 15:00:00 : 강남동   16187 ----------


 ---------- 2016-02-02 17:00:00 : 동  면   16188 ----------


 ---------- 2016-02-02 21:00:00 : 석사동   16189 ----------


 ---------- 2016-02-03 00:00:00 : 석사동   16190 ----------


 ---------- 2016-02-03 05:00:00 : 후평1동   16191 ----------


 ---------- 2016-02-03 10:00:00 : 후평1동   16192 ----------


 ---------- 2016-02-03 13:00:00 : 효자1동   16193 ----------


 ---------- 2016-02-03 13:00:00 : 남산면   16194 ----------


 ---------- 2016-02-03 22:00:00 : 후평1동   16195 ----------


 ---------- 2016-02-04 10:00:00 : 강남동   16196 ----------


 ---------- 2016-02-04 11:00:00 : 강남동   16197 ----------


 ---------- 2016-02-04 16:00:00 : 후평1동   16198 ----------


 ---------- 2016-02-04 18:00:00 : 교  동   16199 ----------


 ---------- 2016-02-05 12:00:00 : 서  면   16200 ----------


 ---------- 2016-02-05 14:00:00 : 후평1동   16201 ----------


 ---------- 2016-02-05 18:00:00 : 후평1동   16202 ----------


 ---------- 2016-02-06 23:00:00 : 후평1동   16203 ----------


 ---------- 2016-02-07 00:00:00 : 퇴계동   16204 ----------


 ---------- 2016-02-07 15:00:00 : 남산면   16205 ----------


 ---------- 2016-02-07 15:00:00 : 퇴계동   16206 ----------


 ---------- 2016-02-08 00:00:00 : 신동면   16207 ----------


 ---------- 2016-02-08 02:00:00 : 근화동   16208 ----------

 ---------- 2016-02-08 09:00:00 : 사북면   16209 ----------


 ---------- 2016-02-08 14:00:00 : 신사우동   16210 ----------


 ---------- 2016-02-08 16:00:00 : 남  면   16212 ----------


 ---------- 2016-02-08 21:00:00 : 효자1동   16213 ----------


 ---------- 2016-02-09 00:00:00 : 신사우동   16214 ----------


 ---------- 2016-02-09 10:00:00 : 후평1동   16215 ----------


 ---------- 2016-02-09 12:00:00 : 동  면   16216 ----------


 ---------- 2016-02-10 05:00:00 : 퇴계동   16217 ----------


 ---------- 2016-02-10 13:00:00 : 북산면   16219 ----------


 ---------- 2016-02-11 03:00:00 : 근화동   16220 ----------


 ---------- 2016-02-11 09:00:00 : 퇴계동   16221 ----------


 ---------- 2016-02-11 13:00:00 : 동내면   16222 ----------


 ---------- 2016-02-11 13:00:00 : 남산면   16223 ----------


 ---------- 2016-02-11 17:00:00 : 신사우동   16224 ----------


 ---------- 2016-02-12 14:00:00 : 신사우동   16226 ----------


 ---------- 2016-02-12 16:00:00 : 근화동   16227 ----------


 ---------- 2016-02-13 17:00:00 : 신사우동   16228 ----------


 ---------- 2016-02-14 11:00:00 : 서  면   16229 ----------


 ---------- 2016-02-14 13:00:00 : 동내면   16230 ----------


 ---------- 2016-02-14 16:00:00 : 동  면   16231 ----------


 ---------- 2016-02-14 18:00:00 : 약사명동   16232 ----------


 ---------- 2016-02-14 23:00:00 : 강남동   16233 ----------


 ---------- 2016-02-14 23:00:00 : 효자1동   16234 ----------


 ---------- 2016-02-15 08:00:00 : 신북읍   16235 ----------


 ---------- 2016-02-15 10:00:00 : 신사우동   16236 ----------


 ---------- 2016-02-15 10:00:00 : 신북읍   16240 ----------


 ---------- 2016-02-15 15:00:00 : 석사동   16241 ----------


 ---------- 2016-02-15 17:00:00 : 효자1동   16242 ----------


 ---------- 2016-02-16 20:00:00 : 서  면   16243 ----------


 ---------- 2016-02-17 00:00:00 : 효자1동   16245 ----------


 ---------- 2016-02-17 04:00:00 : 교  동   16246 ----------


 ---------- 2016-02-17 09:00:00 : 강남동   16247 ----------


 ---------- 2016-02-17 10:00:00 : 신동면   16248 ----------


 ---------- 2016-02-17 13:00:00 : 퇴계동   16249 ----------


 ---------- 2016-02-17 23:00:00 : 석사동   16250 ----------


 ---------- 2016-02-18 00:00:00 : 석사동   16251 ----------


 ---------- 2016-02-18 07:00:00 : 후평1동   16252 ----------


 ---------- 2016-02-18 19:00:00 : 석사동   16253 ----------


 ---------- 2016-02-19 13:00:00 : 남산면   16254 ----------


 ---------- 2016-02-19 14:00:00 : 동내면   16255 ----------


 ---------- 2016-02-19 17:00:00 : 근화동   16256 ----------


 ---------- 2016-02-19 20:00:00 : 강남동   16257 ----------


 ---------- 2016-02-20 00:00:00 : 석사동   16258 ----------


 ---------- 2016-02-20 10:00:00 : 후평1동   16259 ----------


 ---------- 2016-02-20 13:00:00 : 서  면   16261 ----------


 ---------- 2016-02-20 16:00:00 : 신북읍   16262 ----------


 ---------- 2016-02-20 20:00:00 : 남산면   16263 ----------


 ---------- 2016-02-20 23:00:00 : 동산면   16264 ----------


 ---------- 2016-02-21 12:00:00 : 퇴계동   16265 ----------


 ---------- 2016-02-21 15:00:00 : 효자1동   16266 ----------


 ---------- 2016-02-21 16:00:00 : 신사우동   16267 ----------


 ---------- 2016-02-22 01:00:00 : 강남동   16269 ----------


 ---------- 2016-02-22 04:00:00 : 후평1동   16270 ----------


 ---------- 2016-02-22 06:00:00 : 후평1동   16271 ----------


 ---------- 2016-02-22 08:00:00 : 후평1동   16273 ----------


 ---------- 2016-02-22 10:00:00 : 동내면   16275 ----------


 ---------- 2016-02-22 20:00:00 : 신사우동   16276 ----------


 ---------- 2016-02-23 06:00:00 : 신사우동   16277 ----------


 ---------- 2016-02-23 08:00:00 : 석사동   16278 ----------


 ---------- 2016-02-23 19:00:00 : 효자1동   16279 ----------


 ---------- 2016-02-23 20:00:00 : 효자1동   16280 ----------


 ---------- 2016-02-24 03:00:00 : 석사동   16281 ----------


 ---------- 2016-02-24 11:00:00 : 서  면   16282 ----------


 ---------- 2016-02-24 21:00:00 : 동내면   16283 ----------


 ---------- 2016-02-25 10:00:00 : 퇴계동   16284 ----------


 ---------- 2016-02-25 15:00:00 : 신동면   16285 ----------


 ---------- 2016-02-25 21:00:00 : 남산면   16286 ----------


 ---------- 2016-02-26 15:00:00 : 남산면   16287 ----------


 ---------- 2016-02-26 19:00:00 : 동내면   16288 ----------


 ---------- 2016-02-26 22:00:00 : 석사동   16289 ----------


 ---------- 2016-02-27 08:00:00 : 신북읍   16290 ----------


 ---------- 2016-02-27 09:00:00 : 남산면   16291 ----------


 ---------- 2016-02-27 12:00:00 : 강남동   16292 ----------


 ---------- 2016-02-27 13:00:00 : 남산면   16293 ----------


 ---------- 2016-02-27 14:00:00 : 동내면   16294 ----------


 ---------- 2016-02-27 14:00:00 : 동  면   16295 ----------


 ---------- 2016-02-27 23:00:00 : 남  면   16296 ----------


 ---------- 2016-02-28 00:00:00 : 후평1동   16297 ----------


 ---------- 2016-02-28 06:00:00 : 근화동   16298 ----------


 ---------- 2016-02-28 06:00:00 : 동산면   16299 ----------


 ---------- 2016-02-28 14:00:00 : 서  면   16300 ----------


 ---------- 2016-02-28 14:00:00 : 남산면   16301 ----------


 ---------- 2016-02-28 14:00:00 : 동  면   16302 ----------


 ---------- 2016-02-28 17:00:00 : 소양동   16303 ----------


 ---------- 2016-02-29 00:00:00 : 석사동   16304 ----------


 ---------- 2016-02-29 12:00:00 : 남산면   16306 ----------


 ---------- 2016-02-29 13:00:00 : 후평1동   16307 ----------


 ---------- 2016-02-29 14:00:00 : 서  면   16308 ----------


 ---------- 2016-02-29 15:00:00 : 퇴계동   16309 ----------


 ---------- 2016-02-29 17:00:00 : 후평1동   16311 ----------


 ---------- 2016-02-29 22:00:00 : 후평1동   16312 ----------


 ---------- 2016-03-01 09:00:00 : 퇴계동   16313 ----------


 ---------- 2016-03-01 11:00:00 : 강남동   16314 ----------


 ---------- 2016-03-01 11:00:00 : 서  면   16316 ----------


 ---------- 2016-03-01 11:00:00 : 후평1동   16317 ----------


 ---------- 2016-03-01 11:00:00 : 조운동   16318 ----------


 ---------- 2016-03-01 13:00:00 : 동  면   16319 ----------


 ---------- 2016-03-01 22:00:00 : 석사동   16320 ----------


 ---------- 2016-03-02 00:00:00 : 약사명동   16321 ----------


 ---------- 2016-03-02 12:00:00 : 동내면   16322 ----------


 ---------- 2016-03-02 12:00:00 : 교  동   16323 ----------


 ---------- 2016-03-03 01:00:00 : 효자1동   16324 ----------


 ---------- 2016-03-03 06:00:00 : 근화동   16326 ----------


 ---------- 2016-03-03 10:00:00 : 서  면   16328 ----------


 ---------- 2016-03-03 11:00:00 : 서  면   16330 ----------


 ---------- 2016-03-03 11:00:00 : 교  동   16331 ----------


 ---------- 2016-03-03 16:00:00 : 석사동   16332 ----------


 ---------- 2016-03-03 18:00:00 : 동  면   16334 ----------


 ---------- 2016-03-03 23:00:00 : 조운동   16335 ----------


 ---------- 2016-03-04 04:00:00 : 동내면   16336 ----------


 ---------- 2016-03-04 08:00:00 : 근화동   16338 ----------


 ---------- 2016-03-05 20:00:00 : 신북읍   16339 ----------


 ---------- 2016-03-06 04:00:00 : 후평1동   16340 ----------


 ---------- 2016-03-06 07:00:00 : 후평1동   16341 ----------


 ---------- 2016-03-06 10:00:00 : 근화동   16342 ----------


 ---------- 2016-03-07 04:00:00 : 후평1동   16343 ----------


 ---------- 2016-03-07 09:00:00 : 동내면   16344 ----------


 ---------- 2016-03-07 13:00:00 : 후평1동   16345 ----------


 ---------- 2016-03-07 14:00:00 : 사북면   16347 ----------


 ---------- 2016-03-07 17:00:00 : 동산면   16348 ----------


 ---------- 2016-03-07 19:00:00 : 신동면   16349 ----------


 ---------- 2016-03-07 21:00:00 : 동산면   16350 ----------


 ---------- 2016-03-07 22:00:00 : 효자1동   16351 ----------


 ---------- 2016-03-07 23:00:00 : 퇴계동   16352 ----------


 ---------- 2016-03-08 06:00:00 : 효자1동   16353 ----------


 ---------- 2016-03-08 11:00:00 : 후평1동   16354 ----------


 ---------- 2016-03-08 16:00:00 : 효자1동   16355 ----------


 ---------- 2016-03-10 08:00:00 : 강남동   16356 ----------


 ---------- 2016-03-10 11:00:00 : 소양동   16357 ----------


 ---------- 2016-03-10 12:00:00 : 북산면   16358 ----------


 ---------- 2016-03-10 17:00:00 : 후평1동   16359 ----------


 ---------- 2016-03-10 18:00:00 : 서  면   16360 ----------


 ---------- 2016-03-10 22:00:00 : 남산면   16361 ----------


 ---------- 2016-03-10 23:00:00 : 효자1동   16362 ----------


 ---------- 2016-03-12 03:00:00 : 효자1동   16363 ----------


 ---------- 2016-03-12 04:00:00 : 퇴계동   16365 ----------

 ---------- 2016-03-12 15:00:00 : 동내면   16366 ----------


 ---------- 2016-03-13 00:00:00 : 강남동   16367 ----------


 ---------- 2016-03-13 01:00:00 : 효자1동   16368 ----------


 ---------- 2016-03-13 14:00:00 : 동내면   16369 ----------


 ---------- 2016-03-14 14:00:00 : 서  면   16370 ----------


 ---------- 2016-03-14 18:00:00 : 동내면   16371 ----------


 ---------- 2016-03-15 02:00:00 : 근화동   16372 ----------


 ---------- 2016-03-15 05:00:00 : 동  면   16373 ----------


 ---------- 2016-03-15 11:00:00 : 신사우동   16374 ----------


 ---------- 2016-03-15 14:00:00 : 남산면   16375 ----------


 ---------- 2016-03-16 03:00:00 : 근화동   16376 ----------


 ---------- 2016-03-16 10:00:00 : 서  면   16377 ----------


 ---------- 2016-03-16 11:00:00 : 석사동   16378 ----------


 ---------- 2016-03-16 11:00:00 : 동내면   16379 ----------


 ---------- 2016-03-16 12:00:00 : 동내면   16380 ----------


 ---------- 2016-03-16 17:00:00 : 동  면   16381 ----------


 ---------- 2016-03-16 21:00:00 : 신북읍   16382 ----------


 ---------- 2016-03-16 22:00:00 : 퇴계동   16384 ----------


 ---------- 2016-03-17 17:00:00 : 후평1동   16385 ----------


 ---------- 2016-03-17 21:00:00 : 동  면   16386 ----------


 ---------- 2016-03-18 07:00:00 : 후평1동   16387 ----------


 ---------- 2016-03-18 17:00:00 : 조운동   16388 ----------


 ---------- 2016-03-18 18:00:00 : 근화동   16389 ----------


 ---------- 2016-03-18 19:00:00 : 퇴계동   16390 ----------


 ---------- 2016-03-19 02:00:00 : 동산면   16391 ----------


 ---------- 2016-03-19 03:00:00 : 석사동   16392 ----------


 ---------- 2016-03-19 08:00:00 : 효자1동   16393 ----------


 ---------- 2016-03-19 12:00:00 : 동내면   16394 ----------


 ---------- 2016-03-19 13:00:00 : 동  면   16395 ----------


 ---------- 2016-03-19 14:00:00 : 근화동   16396 ----------


 ---------- 2016-03-19 15:00:00 : 북산면   16397 ----------


 ---------- 2016-03-19 16:00:00 : 남산면   16398 ----------


 ---------- 2016-03-19 16:00:00 : 근화동   16399 ----------


 ---------- 2016-03-19 20:00:00 : 동산면   16401 ----------


 ---------- 2016-03-20 19:00:00 : 서  면   16402 ----------


 ---------- 2016-03-20 20:00:00 : 신북읍   16403 ----------


 ---------- 2016-03-20 22:00:00 : 약사명동   16404 ----------


 ---------- 2016-03-20 23:00:00 : 후평1동   16405 ----------


 ---------- 2016-03-21 05:00:00 : 석사동   16406 ----------


 ---------- 2016-03-21 09:00:00 : 동  면   16407 ----------


 ---------- 2016-03-21 11:00:00 : 강남동   16408 ----------


 ---------- 2016-03-21 14:00:00 : 사북면   16410 ----------


 ---------- 2016-03-21 23:00:00 : 사북면   16411 ----------


 ---------- 2016-03-22 09:00:00 : 남산면   16413 ----------


 ---------- 2016-03-22 10:00:00 : 효자1동   16414 ----------


 ---------- 2016-03-22 17:00:00 : 남산면   16415 ----------


 ---------- 2016-03-22 20:00:00 : 신북읍   16416 ----------


 ---------- 2016-03-22 20:00:00 : 동  면   16417 ----------


 ---------- 2016-03-22 20:00:00 : 조운동   16418 ----------


 ---------- 2016-03-22 21:00:00 : 강남동   16419 ----------


 ---------- 2016-03-23 10:00:00 : 석사동   16420 ----------


 ---------- 2016-03-23 15:00:00 : 퇴계동   16421 ----------


 ---------- 2016-03-23 21:00:00 : 효자1동   16422 ----------


 ---------- 2016-03-23 22:00:00 : 동  면   16423 ----------


 ---------- 2016-03-24 01:00:00 : 효자1동   16424 ----------


 ---------- 2016-03-24 19:00:00 : 석사동   16425 ----------


 ---------- 2016-03-25 10:00:00 : 효자1동   16426 ----------


 ---------- 2016-03-25 11:00:00 : 강남동   16427 ----------


 ---------- 2016-03-25 17:00:00 : 동  면   16428 ----------


 ---------- 2016-03-25 18:00:00 : 신사우동   16431 ----------


 ---------- 2016-03-25 19:00:00 : 효자1동   16432 ----------


 ---------- 2016-03-26 12:00:00 : 신사우동   16433 ----------


 ---------- 2016-03-26 22:00:00 : 신사우동   16434 ----------


 ---------- 2016-03-27 00:00:00 : 효자1동   16435 ----------


 ---------- 2016-03-27 02:00:00 : 후평1동   16436 ----------


 ---------- 2016-03-27 10:00:00 : 서  면   16438 ----------


 ---------- 2016-03-27 10:00:00 : 신북읍   16439 ----------


 ---------- 2016-03-27 11:00:00 : 후평1동   16440 ----------


 ---------- 2016-03-27 14:00:00 : 강남동   16441 ----------


 ---------- 2016-03-27 14:00:00 : 신사우동   16444 ----------


 ---------- 2016-03-27 23:00:00 : 석사동   16445 ----------


 ---------- 2016-03-28 14:00:00 : 후평1동   16446 ----------


 ---------- 2016-03-28 17:00:00 : 근화동   16447 ----------


 ---------- 2016-03-28 21:00:00 : 동  면   16448 ----------


 ---------- 2016-03-29 03:00:00 : 석사동   16449 ----------


 ---------- 2016-03-29 09:00:00 : 강남동   16450 ----------


 ---------- 2016-03-29 13:00:00 : 남산면   16451 ----------


 ---------- 2016-03-29 14:00:00 : 퇴계동   16452 ----------


 ---------- 2016-03-29 15:00:00 : 근화동   16454 ----------


 ---------- 2016-03-30 00:00:00 : 후평1동   16455 ----------


 ---------- 2016-03-30 07:00:00 : 강남동   16456 ----------


 ---------- 2016-03-30 10:00:00 : 조운동   16457 ----------


 ---------- 2016-03-30 11:00:00 : 동내면   16458 ----------


 ---------- 2016-03-30 15:00:00 : 석사동   16459 ----------


 ---------- 2016-03-30 19:00:00 : 석사동   16460 ----------


 ---------- 2016-03-31 09:00:00 : 동  면   16461 ----------


 ---------- 2016-03-31 11:00:00 : 퇴계동   16462 ----------


 ---------- 2016-03-31 16:00:00 : 퇴계동   16463 ----------


 ---------- 2016-04-01 10:00:00 : 신사우동   16464 ----------


 ---------- 2016-04-01 10:00:00 : 신북읍   16465 ----------


 ---------- 2016-04-01 10:00:00 : 퇴계동   16466 ----------


 ---------- 2016-04-01 12:00:00 : 신동면   16467 ----------


 ---------- 2016-04-01 13:00:00 : 강남동   16468 ----------


 ---------- 2016-04-01 16:00:00 : 효자1동   16469 ----------


 ---------- 2016-04-01 21:00:00 : 약사명동   16470 ----------


 ---------- 2016-04-02 07:00:00 : 신사우동   16471 ----------


 ---------- 2016-04-02 11:00:00 : 근화동   16472 ----------


 ---------- 2016-04-02 12:00:00 : 서  면   16475 ----------


 ---------- 2016-04-02 12:00:00 : 소양동   16476 ----------


 ---------- 2016-04-02 13:00:00 : 서  면   16477 ----------


 ---------- 2016-04-02 13:00:00 : 사북면   16478 ----------


 ---------- 2016-04-03 00:00:00 : 후평1동   16479 ----------


 ---------- 2016-04-03 10:00:00 : 남산면   16480 ----------


 ---------- 2016-04-03 15:00:00 : 남  면   16482 ----------


 ---------- 2016-04-03 19:00:00 : 후평1동   16483 ----------


 ---------- 2016-04-03 20:00:00 : 후평1동   16484 ----------


 ---------- 2016-04-04 07:00:00 : 강남동   16485 ----------


 ---------- 2016-04-05 08:00:00 : 퇴계동   16487 ----------


 ---------- 2016-04-05 09:00:00 : 신북읍   16489 ----------


 ---------- 2016-04-05 12:00:00 : 사북면   16491 ----------


 ---------- 2016-04-05 14:00:00 : 교  동   16492 ----------


 ---------- 2016-04-05 21:00:00 : 신사우동   16493 ----------


 ---------- 2016-04-05 22:00:00 : 효자1동   16494 ----------


 ---------- 2016-04-06 13:00:00 : 효자1동   16495 ----------


 ---------- 2016-04-06 13:00:00 : 남산면   16496 ----------


 ---------- 2016-04-06 16:00:00 : 동산면   16498 ----------


 ---------- 2016-04-06 22:00:00 : 석사동   16499 ----------


 ---------- 2016-04-07 00:00:00 : 신사우동   16500 ----------


 ---------- 2016-04-07 09:00:00 : 신사우동   16502 ----------


 ---------- 2016-04-07 12:00:00 : 퇴계동   16503 ----------


 ---------- 2016-04-07 18:00:00 : 서  면   16506 ----------


 ---------- 2016-04-08 11:00:00 : 신북읍   16507 ----------


 ---------- 2016-04-08 13:00:00 : 퇴계동   16508 ----------


 ---------- 2016-04-08 15:00:00 : 효자1동   16509 ----------


 ---------- 2016-04-08 16:00:00 : 효자1동   16510 ----------


 ---------- 2016-04-09 00:00:00 : 석사동   16511 ----------


 ---------- 2016-04-09 08:00:00 : 신사우동   16512 ----------


 ---------- 2016-04-09 10:00:00 : 서  면   16514 ----------


 ---------- 2016-04-09 13:00:00 : 동  면   16516 ----------


 ---------- 2016-04-09 20:00:00 : 신북읍   16517 ----------


 ---------- 2016-04-10 13:00:00 : 북산면   16519 ----------


 ---------- 2016-04-10 15:00:00 : 강남동   16520 ----------


 ---------- 2016-04-10 18:00:00 : 소양동   16521 ----------


 ---------- 2016-04-11 00:00:00 : 후평1동   16522 ----------


 ---------- 2016-04-11 04:00:00 : 효자1동   16523 ----------


 ---------- 2016-04-11 05:00:00 : 근화동   16524 ----------

 ---------- 2016-04-11 08:00:00 : 신북읍   16525 ----------


 ---------- 2016-04-11 08:00:00 : 교  동   16528 ----------


 ---------- 2016-04-11 09:00:00 : 후평1동   16529 ----------


 ---------- 2016-04-11 10:00:00 : 근화동   16530 ----------


 ---------- 2016-04-11 11:00:00 : 북산면   16531 ----------


 ---------- 2016-04-11 18:00:00 : 후평1동   16532 ----------


 ---------- 2016-04-12 10:00:00 : 석사동   16533 ----------


 ---------- 2016-04-12 16:00:00 : 신동면   16534 ----------


 ---------- 2016-04-13 01:00:00 : 강남동   16535 ----------


 ---------- 2016-04-13 18:00:00 : 강남동   16536 ----------


 ---------- 2016-04-14 01:00:00 : 효자1동   16537 ----------


 ---------- 2016-04-14 12:00:00 : 신북읍   16538 ----------


 ---------- 2016-04-14 15:00:00 : 근화동   16541 ----------


 ---------- 2016-04-14 16:00:00 : 후평1동   16542 ----------


 ---------- 2016-04-15 09:00:00 : 근화동   16545 ----------


 ---------- 2016-04-16 01:00:00 : 근화동   16547 ----------


 ---------- 2016-04-16 01:00:00 : 후평1동   16548 ----------


 ---------- 2016-04-16 07:00:00 : 남산면   16549 ----------


 ---------- 2016-04-16 10:00:00 : 동내면   16550 ----------


 ---------- 2016-04-16 15:00:00 : 퇴계동   16551 ----------


 ---------- 2016-04-16 21:00:00 : 퇴계동   16552 ----------


 ---------- 2016-04-17 00:00:00 : 효자1동   16553 ----------


 ---------- 2016-04-17 10:00:00 : 효자1동   16554 ----------


 ---------- 2016-04-17 12:00:00 : 강남동   16555 ----------


 ---------- 2016-04-17 14:00:00 : 강남동   16556 ----------


 ---------- 2016-04-17 18:00:00 : 강남동   16557 ----------


 ---------- 2016-04-17 20:00:00 : 약사명동   16558 ----------


 ---------- 2016-04-18 01:00:00 : 석사동   16559 ----------


 ---------- 2016-04-18 14:00:00 : 동산면   16560 ----------


 ---------- 2016-04-18 17:00:00 : 강남동   16562 ----------


 ---------- 2016-04-18 20:00:00 : 강남동   16563 ----------


 ---------- 2016-04-19 00:00:00 : 후평1동   16564 ----------


 ---------- 2016-04-19 03:00:00 : 석사동   16565 ----------


 ---------- 2016-04-19 10:00:00 : 소양동   16566 ----------


 ---------- 2016-04-19 13:00:00 : 신사우동   16567 ----------


 ---------- 2016-04-19 17:00:00 : 퇴계동   16568 ----------


 ---------- 2016-04-19 18:00:00 : 남산면   16569 ----------


 ---------- 2016-04-19 18:00:00 : 신북읍   16570 ----------


 ---------- 2016-04-19 19:00:00 : 퇴계동   16572 ----------


 ---------- 2016-04-19 23:00:00 : 강남동   16573 ----------


 ---------- 2016-04-20 06:00:00 : 후평1동   16574 ----------


 ---------- 2016-04-20 08:00:00 : 신사우동   16575 ----------


 ---------- 2016-04-20 11:00:00 : 교  동   16577 ----------


 ---------- 2016-04-20 14:00:00 : 신사우동   16578 ----------


 ---------- 2016-04-20 15:00:00 : 강남동   16579 ----------


 ---------- 2016-04-20 19:00:00 : 퇴계동   16580 ----------


 ---------- 2016-04-20 20:00:00 : 후평1동   16581 ----------


 ---------- 2016-04-21 01:00:00 : 효자1동   16582 ----------


 ---------- 2016-04-21 07:00:00 : 신사우동   16584 ----------


 ---------- 2016-04-21 09:00:00 : 석사동   16585 ----------


 ---------- 2016-04-21 10:00:00 : 동  면   16586 ----------


 ---------- 2016-04-21 15:00:00 : 신북읍   16587 ----------


 ---------- 2016-04-21 17:00:00 : 후평1동   16588 ----------


 ---------- 2016-04-21 19:00:00 : 서  면   16590 ----------


 ---------- 2016-04-21 21:00:00 : 퇴계동   16591 ----------


 ---------- 2016-04-22 01:00:00 : 강남동   16592 ----------


 ---------- 2016-04-22 04:00:00 : 퇴계동   16593 ----------


 ---------- 2016-04-22 09:00:00 : 후평1동   16594 ----------


 ---------- 2016-04-22 15:00:00 : 소양동   16596 ----------


 ---------- 2016-04-22 19:00:00 : 약사명동   16597 ----------


 ---------- 2016-04-22 20:00:00 : 동내면   16598 ----------


 ---------- 2016-04-23 11:00:00 : 동내면   16599 ----------


 ---------- 2016-04-23 12:00:00 : 서  면   16600 ----------


 ---------- 2016-04-23 12:00:00 : 후평1동   16601 ----------


 ---------- 2016-04-23 13:00:00 : 효자1동   16602 ----------


 ---------- 2016-04-23 16:00:00 : 신동면   16603 ----------


 ---------- 2016-04-23 19:00:00 : 동산면   16604 ----------


 ---------- 2016-04-24 09:00:00 : 퇴계동   16605 ----------


 ---------- 2016-04-24 13:00:00 : 서  면   16606 ----------


 ---------- 2016-04-24 13:00:00 : 남  면   16608 ----------


 ---------- 2016-04-24 18:00:00 : 동내면   16610 ----------


 ---------- 2016-04-24 18:00:00 : 남산면   16611 ----------


 ---------- 2016-04-24 21:00:00 : 동내면   16612 ----------


 ---------- 2016-04-25 01:00:00 : 강남동   16613 ----------


 ---------- 2016-04-25 09:00:00 : 남산면   16614 ----------


 ---------- 2016-04-25 17:00:00 : 북산면   16616 ----------


 ---------- 2016-04-26 01:00:00 : 신사우동   16617 ----------


 ---------- 2016-04-26 06:00:00 : 근화동   16618 ----------


 ---------- 2016-04-26 07:00:00 : 근화동   16619 ----------


 ---------- 2016-04-26 14:00:00 : 후평1동   16620 ----------


 ---------- 2016-04-26 15:00:00 : 효자1동   16621 ----------


 ---------- 2016-04-26 15:00:00 : 후평1동   16622 ----------


 ---------- 2016-04-27 10:00:00 : 신동면   16624 ----------


 ---------- 2016-04-27 12:00:00 : 근화동   16625 ----------


 ---------- 2016-04-27 15:00:00 : 남산면   16626 ----------


 ---------- 2016-04-27 15:00:00 : 후평1동   16627 ----------


 ---------- 2016-04-27 18:00:00 : 남산면   16628 ----------


 ---------- 2016-04-27 22:00:00 : 후평1동   16629 ----------


 ---------- 2016-04-27 23:00:00 : 석사동   16630 ----------


 ---------- 2016-04-28 00:00:00 : 신사우동   16632 ----------


 ---------- 2016-04-28 19:00:00 : 효자1동   16633 ----------


 ---------- 2016-04-28 22:00:00 : 소양동   16634 ----------


 ---------- 2016-04-29 01:00:00 : 동  면   16635 ----------


 ---------- 2016-04-29 02:00:00 : 효자1동   16636 ----------


 ---------- 2016-04-29 10:00:00 : 남산면   16637 ----------


 ---------- 2016-04-29 11:00:00 : 후평1동   16638 ----------


 ---------- 2016-04-29 14:00:00 : 서  면   16639 ----------


 ---------- 2016-04-30 05:00:00 : 석사동   16640 ----------


 ---------- 2016-04-30 05:00:00 : 후평1동   16642 ----------


 ---------- 2016-04-30 06:00:00 : 석사동   16643 ----------


 ---------- 2016-04-30 10:00:00 : 약사명동   16644 ----------


 ---------- 2016-04-30 11:00:00 : 약사명동   16645 ----------


 ---------- 2016-04-30 15:00:00 : 강남동   16647 ----------


 ---------- 2016-04-30 18:00:00 : 석사동   16648 ----------


 ---------- 2016-04-30 18:00:00 : 신북읍   16649 ----------


 ---------- 2016-04-30 19:00:00 : 후평1동   16650 ----------


 ---------- 2016-04-30 19:00:00 : 퇴계동   16651 ----------


 ---------- 2016-04-30 21:00:00 : 퇴계동   16652 ----------


 ---------- 2016-05-01 10:00:00 : 북산면   16657 ----------


 ---------- 2016-05-01 12:00:00 : 동내면   16658 ----------


 ---------- 2016-05-01 12:00:00 : 신사우동   16662 ----------


 ---------- 2016-05-01 14:00:00 : 신사우동   16663 ----------


 ---------- 2016-05-01 16:00:00 : 후평1동   16664 ----------


 ---------- 2016-05-01 17:00:00 : 효자1동   16666 ----------


 ---------- 2016-05-01 17:00:00 : 동  면   16667 ----------


 ---------- 2016-05-01 21:00:00 : 퇴계동   16668 ----------


 ---------- 2016-05-02 02:00:00 : 조운동   16669 ----------


 ---------- 2016-05-02 05:00:00 : 신사우동   16670 ----------


 ---------- 2016-05-02 05:00:00 : 동  면   16671 ----------


 ---------- 2016-05-02 05:00:00 : 후평1동   16673 ----------


 ---------- 2016-05-02 10:00:00 : 석사동   16674 ----------


 ---------- 2016-05-02 11:00:00 : 남산면   16676 ----------


 ---------- 2016-05-02 12:00:00 : 남산면   16677 ----------


 ---------- 2016-05-02 14:00:00 : 동산면   16678 ----------


 ---------- 2016-05-02 21:00:00 : 근화동   16679 ----------


 ---------- 2016-05-03 07:00:00 : 남산면   16681 ----------


 ---------- 2016-05-03 08:00:00 : 효자1동   16682 ----------


 ---------- 2016-05-03 14:00:00 : 남산면   16683 ----------


 ---------- 2016-05-03 17:00:00 : 석사동   16684 ----------


 ---------- 2016-05-03 18:00:00 : 서  면   16686 ----------


 ---------- 2016-05-03 19:00:00 : 소양동   16688 ----------


 ---------- 2016-05-03 19:00:00 : 후평1동   16689 ----------


 ---------- 2016-05-03 20:00:00 : 약사명동   16692 ----------


 ---------- 2016-05-04 03:00:00 : 신동면   16694 ----------


 ---------- 2016-05-04 05:00:00 : 신동면   16695 ----------


 ---------- 2016-05-04 06:00:00 : 신북읍   16696 ----------


 ---------- 2016-05-04 06:00:00 : 북산면   16697 ----------

 ---------- 2016-05-04 08:00:00 : 신사우동   16698 ----------


 ---------- 2016-05-04 10:00:00 : 동내면   16702 ----------


 ---------- 2016-05-04 11:00:00 : 효자1동   16703 ----------


 ---------- 2016-05-04 11:00:00 : 동  면   16704 ----------


 ---------- 2016-05-04 12:00:00 : 서  면   16705 ----------


 ---------- 2016-05-04 12:00:00 : 근화동   16706 ----------


 ---------- 2016-05-04 13:00:00 : 근화동   16707 ----------


 ---------- 2016-05-04 14:00:00 : 근화동   16708 ----------


 ---------- 2016-05-04 14:00:00 : 약사명동   16709 ----------


 ---------- 2016-05-04 14:00:00 : 후평1동   16710 ----------


 ---------- 2016-05-04 15:00:00 : 서  면   16711 ----------


 ---------- 2016-05-04 15:00:00 : 동내면   16712 ----------


 ---------- 2016-05-04 16:00:00 : 근화동   16713 ----------


 ---------- 2016-05-04 17:00:00 : 근화동   16714 ----------


 ---------- 2016-05-04 19:00:00 : 석사동   16715 ----------


 ---------- 2016-05-05 08:00:00 : 동  면   16716 ----------


 ---------- 2016-05-05 09:00:00 : 퇴계동   16717 ----------


 ---------- 2016-05-05 13:00:00 : 남산면   16718 ----------


 ---------- 2016-05-05 15:00:00 : 신동면   16719 ----------


 ---------- 2016-05-05 16:00:00 : 퇴계동   16720 ----------


 ---------- 2016-05-05 17:00:00 : 후평1동   16721 ----------


 ---------- 2016-05-05 18:00:00 : 신사우동   16722 ----------


 ---------- 2016-05-05 21:00:00 : 석사동   16723 ----------


 ---------- 2016-05-06 03:00:00 : 퇴계동   16724 ----------


 ---------- 2016-05-06 12:00:00 : 석사동   16725 ----------


 ---------- 2016-05-06 22:00:00 : 동내면   16726 ----------


 ---------- 2016-05-06 23:00:00 : 후평1동   16727 ----------


 ---------- 2016-05-07 14:00:00 : 후평1동   16728 ----------


 ---------- 2016-05-08 06:00:00 : 동내면   16730 ----------


 ---------- 2016-05-08 09:00:00 : 후평1동   16731 ----------


 ---------- 2016-05-09 06:00:00 : 동  면   16732 ----------


 ---------- 2016-05-09 17:00:00 : 남산면   16733 ----------


 ---------- 2016-05-10 10:00:00 : 동산면   16735 ----------


 ---------- 2016-05-10 12:00:00 : 남산면   16736 ----------


 ---------- 2016-05-10 12:00:00 : 교  동   16737 ----------


 ---------- 2016-05-10 14:00:00 : 효자1동   16738 ----------


 ---------- 2016-05-10 18:00:00 : 후평1동   16739 ----------


 ---------- 2016-05-10 19:00:00 : 효자1동   16740 ----------


 ---------- 2016-05-10 21:00:00 : 동내면   16742 ----------


 ---------- 2016-05-10 21:00:00 : 퇴계동   16743 ----------


 ---------- 2016-05-11 13:00:00 : 남산면   16744 ----------


 ---------- 2016-05-12 02:00:00 : 효자1동   16745 ----------


 ---------- 2016-05-12 14:00:00 : 남산면   16746 ----------


 ---------- 2016-05-12 17:00:00 : 후평1동   16747 ----------


 ---------- 2016-05-12 20:00:00 : 후평1동   16748 ----------


 ---------- 2016-05-12 22:00:00 : 동내면   16749 ----------


 ---------- 2016-05-12 22:00:00 : 퇴계동   16750 ----------


 ---------- 2016-05-13 00:00:00 : 근화동   16751 ----------


 ---------- 2016-05-13 01:00:00 : 효자1동   16753 ----------


 ---------- 2016-05-13 06:00:00 : 소양동   16754 ----------


 ---------- 2016-05-13 07:00:00 : 동  면   16755 ----------


 ---------- 2016-05-13 17:00:00 : 효자1동   16756 ----------


 ---------- 2016-05-13 17:00:00 : 후평1동   16757 ----------


 ---------- 2016-05-13 23:00:00 : 동내면   16758 ----------


 ---------- 2016-05-14 12:00:00 : 후평1동   16759 ----------


 ---------- 2016-05-14 16:00:00 : 동  면   16760 ----------


 ---------- 2016-05-14 17:00:00 : 후평1동   16761 ----------


 ---------- 2016-05-15 00:00:00 : 동내면   16762 ----------


 ---------- 2016-05-15 05:00:00 : 동  면   16763 ----------


 ---------- 2016-05-15 07:00:00 : 강남동   16764 ----------


 ---------- 2016-05-15 08:00:00 : 소양동   16765 ----------


 ---------- 2016-05-15 10:00:00 : 약사명동   16766 ----------


 ---------- 2016-05-15 11:00:00 : 후평1동   16767 ----------


 ---------- 2016-05-15 13:00:00 : 효자1동   16768 ----------


 ---------- 2016-05-15 14:00:00 : 효자1동   16769 ----------


 ---------- 2016-05-15 17:00:00 : 서  면   16770 ----------


 ---------- 2016-05-15 17:00:00 : 효자1동   16771 ----------


 ---------- 2016-05-15 19:00:00 : 남산면   16772 ----------


 ---------- 2016-05-16 12:00:00 : 소양동   16773 ----------


 ---------- 2016-05-16 15:00:00 : 퇴계동   16774 ----------


 ---------- 2016-05-17 00:00:00 : 동  면   16776 ----------


 ---------- 2016-05-17 06:00:00 : 근화동   16777 ----------


 ---------- 2016-05-17 08:00:00 : 소양동   16778 ----------


 ---------- 2016-05-17 11:00:00 : 동내면   16779 ----------


 ---------- 2016-05-17 11:00:00 : 퇴계동   16780 ----------


 ---------- 2016-05-17 13:00:00 : 근화동   16781 ----------


 ---------- 2016-05-17 15:00:00 : 효자1동   16782 ----------


 ---------- 2016-05-17 22:00:00 : 퇴계동   16783 ----------


 ---------- 2016-05-18 05:00:00 : 효자1동   16784 ----------


 ---------- 2016-05-18 14:00:00 : 남  면   16785 ----------


 ---------- 2016-05-18 17:00:00 : 효자1동   16786 ----------


 ---------- 2016-05-18 22:00:00 : 석사동   16787 ----------


 ---------- 2016-05-19 03:00:00 : 남산면   16788 ----------


 ---------- 2016-05-19 04:00:00 : 후평1동   16789 ----------


 ---------- 2016-05-19 08:00:00 : 신사우동   16790 ----------


 ---------- 2016-05-19 09:00:00 : 소양동   16791 ----------


 ---------- 2016-05-19 09:00:00 : 후평1동   16793 ----------


 ---------- 2016-05-19 14:00:00 : 효자1동   16794 ----------


 ---------- 2016-05-19 14:00:00 : 근화동   16795 ----------


 ---------- 2016-05-19 14:00:00 : 후평1동   16796 ----------


 ---------- 2016-05-19 16:00:00 : 퇴계동   16797 ----------


 ---------- 2016-05-19 18:00:00 : 남산면   16799 ----------


 ---------- 2016-05-19 18:00:00 : 후평1동   16800 ----------


 ---------- 2016-05-19 21:00:00 : 효자1동   16801 ----------


 ---------- 2016-05-20 00:00:00 : 석사동   16802 ----------


 ---------- 2016-05-20 11:00:00 : 후평1동   16803 ----------


 ---------- 2016-05-20 13:00:00 : 효자1동   16804 ----------


 ---------- 2016-05-20 14:00:00 : 후평1동   16805 ----------


 ---------- 2016-05-20 16:00:00 : 동  면   16806 ----------


 ---------- 2016-05-20 17:00:00 : 동산면   16807 ----------


 ---------- 2016-05-20 23:00:00 : 후평1동   16808 ----------


 ---------- 2016-05-21 01:00:00 : 석사동   16809 ----------


 ---------- 2016-05-21 08:00:00 : 강남동   16810 ----------


 ---------- 2016-05-21 12:00:00 : 강남동   16811 ----------


 ---------- 2016-05-21 13:00:00 : 신사우동   16812 ----------


 ---------- 2016-05-21 14:00:00 : 퇴계동   16813 ----------


 ---------- 2016-05-21 16:00:00 : 약사명동   16814 ----------


 ---------- 2016-05-21 18:00:00 : 서  면   16816 ----------


 ---------- 2016-05-21 18:00:00 : 후평1동   16817 ----------


 ---------- 2016-05-21 21:00:00 : 석사동   16818 ----------


 ---------- 2016-05-21 23:00:00 : 석사동   16819 ----------


 ---------- 2016-05-21 23:00:00 : 강남동   16820 ----------


 ---------- 2016-05-22 00:00:00 : 효자1동   16821 ----------


 ---------- 2016-05-22 06:00:00 : 동  면   16822 ----------


 ---------- 2016-05-22 07:00:00 : 석사동   16823 ----------


 ---------- 2016-05-22 08:00:00 : 신사우동   16824 ----------


 ---------- 2016-05-22 09:00:00 : 조운동   16825 ----------


 ---------- 2016-05-22 12:00:00 : 서  면   16827 ----------


 ---------- 2016-05-22 13:00:00 : 북산면   16830 ----------


 ---------- 2016-05-22 14:00:00 : 교  동   16831 ----------


 ---------- 2016-05-22 19:00:00 : 효자1동   16832 ----------


 ---------- 2016-05-22 21:00:00 : 신북읍   16833 ----------


 ---------- 2016-05-23 09:00:00 : 서  면   16834 ----------


 ---------- 2016-05-23 09:00:00 : 후평1동   16835 ----------


 ---------- 2016-05-23 09:00:00 : 북산면   16836 ----------


 ---------- 2016-05-24 00:00:00 : 퇴계동   16837 ----------


 ---------- 2016-05-24 08:00:00 : 퇴계동   16838 ----------


 ---------- 2016-05-24 11:00:00 : 퇴계동   16839 ----------


 ---------- 2016-05-24 13:00:00 : 강남동   16840 ----------


 ---------- 2016-05-24 14:00:00 : 효자1동   16841 ----------


 ---------- 2016-05-24 14:00:00 : 후평1동   16842 ----------


 ---------- 2016-05-24 16:00:00 : 동  면   16843 ----------


 ---------- 2016-05-24 22:00:00 : 석사동   16844 ----------


 ---------- 2016-05-25 09:00:00 : 남산면   16845 ----------


 ---------- 2016-05-25 18:00:00 : 후평1동   16846 ----------


 ---------- 2016-05-26 14:00:00 : 후평1동   16848 ----------

 ---------- 2016-05-27 10:00:00 : 동  면   16849 ----------


 ---------- 2016-05-27 18:00:00 : 남산면   16851 ----------


 ---------- 2016-05-27 20:00:00 : 남산면   16853 ----------


 ---------- 2016-05-27 20:00:00 : 신사우동   16854 ----------


 ---------- 2016-05-27 21:00:00 : 효자1동   16855 ----------


 ---------- 2016-05-28 02:00:00 : 교  동   16856 ----------


 ---------- 2016-05-28 05:00:00 : 석사동   16857 ----------


 ---------- 2016-05-28 11:00:00 : 신사우동   16859 ----------


 ---------- 2016-05-28 13:00:00 : 강남동   16860 ----------


 ---------- 2016-05-28 13:00:00 : 북산면   16861 ----------


 ---------- 2016-05-28 17:00:00 : 강남동   16862 ----------


 ---------- 2016-05-28 17:00:00 : 퇴계동   16863 ----------


 ---------- 2016-05-29 08:00:00 : 신북읍   16865 ----------


 ---------- 2016-05-29 15:00:00 : 서  면   16866 ----------


 ---------- 2016-05-29 19:00:00 : 신사우동   16867 ----------


 ---------- 2016-05-29 22:00:00 : 사북면   16868 ----------


 ---------- 2016-05-30 07:00:00 : 소양동   16869 ----------


 ---------- 2016-05-30 10:00:00 : 소양동   16870 ----------


 ---------- 2016-05-30 11:00:00 : 남  면   16871 ----------


 ---------- 2016-05-30 15:00:00 : 신북읍   16872 ----------


 ---------- 2016-05-30 18:00:00 : 효자1동   16873 ----------


 ---------- 2016-05-30 20:00:00 : 후평1동   16874 ----------


 ---------- 2016-05-31 01:00:00 : 석사동   16875 ----------


 ---------- 2016-05-31 04:00:00 : 후평1동   16876 ----------


 ---------- 2016-05-31 05:00:00 : 동내면   16877 ----------


 ---------- 2016-05-31 06:00:00 : 신북읍   16879 ----------


 ---------- 2016-05-31 23:00:00 : 약사명동   16880 ----------


 ---------- 2016-05-31 23:00:00 : 후평1동   16881 ----------


 ---------- 2016-06-01 12:00:00 : 소양동   16883 ----------


 ---------- 2016-06-02 06:00:00 : 신북읍   16884 ----------


 ---------- 2016-06-02 07:00:00 : 근화동   16885 ----------


 ---------- 2016-06-02 08:00:00 : 남  면   16887 ----------


 ---------- 2016-06-02 11:00:00 : 퇴계동   16888 ----------


 ---------- 2016-06-02 12:00:00 : 강남동   16889 ----------


 ---------- 2016-06-02 15:00:00 : 효자1동   16890 ----------


 ---------- 2016-06-02 23:00:00 : 근화동   16891 ----------


 ---------- 2016-06-03 09:00:00 : 동내면   16892 ----------


 ---------- 2016-06-03 14:00:00 : 석사동   16893 ----------


 ---------- 2016-06-03 20:00:00 : 남산면   16895 ----------


 ---------- 2016-06-03 21:00:00 : 효자1동   16896 ----------


 ---------- 2016-06-03 22:00:00 : 효자1동   16897 ----------


 ---------- 2016-06-04 00:00:00 : 강남동   16898 ----------


 ---------- 2016-06-04 12:00:00 : 강남동   16899 ----------


 ---------- 2016-06-04 13:00:00 : 신사우동   16900 ----------


 ---------- 2016-06-04 16:00:00 : 북산면   16901 ----------


 ---------- 2016-06-05 14:00:00 : 북산면   16904 ----------


 ---------- 2016-06-05 16:00:00 : 북산면   16905 ----------


 ---------- 2016-06-05 19:00:00 : 신북읍   16906 ----------


 ---------- 2016-06-05 20:00:00 : 남산면   16907 ----------


 ---------- 2016-06-06 09:00:00 : 후평1동   16908 ----------


 ---------- 2016-06-06 12:00:00 : 남산면   16909 ----------


 ---------- 2016-06-06 14:00:00 : 퇴계동   16911 ----------


 ---------- 2016-06-07 02:00:00 : 동내면   16913 ----------


 ---------- 2016-06-07 09:00:00 : 후평1동   16914 ----------


 ---------- 2016-06-07 11:00:00 : 남산면   16915 ----------


 ---------- 2016-06-07 17:00:00 : 석사동   16916 ----------


 ---------- 2016-06-07 19:00:00 : 조운동   16917 ----------


 ---------- 2016-06-07 20:00:00 : 효자1동   16918 ----------


 ---------- 2016-06-07 21:00:00 : 약사명동   16919 ----------


 ---------- 2016-06-08 09:00:00 : 동내면   16920 ----------


 ---------- 2016-06-08 11:00:00 : 강남동   16921 ----------


 ---------- 2016-06-08 11:00:00 : 동내면   16922 ----------


 ---------- 2016-06-08 12:00:00 : 효자1동   16923 ----------


 ---------- 2016-06-08 16:00:00 : 후평1동   16924 ----------


 ---------- 2016-06-08 19:00:00 : 석사동   16925 ----------


 ---------- 2016-06-09 01:00:00 : 근화동   16926 ----------


 ---------- 2016-06-09 09:00:00 : 석사동   16927 ----------


 ---------- 2016-06-09 11:00:00 : 동산면   16928 ----------


 ---------- 2016-06-09 13:00:00 : 신북읍   16929 ----------


 ---------- 2016-06-09 17:00:00 : 석사동   16930 ----------


 ---------- 2016-06-09 20:00:00 : 후평1동   16931 ----------


 ---------- 2016-06-09 22:00:00 : 동  면   16933 ----------


 ---------- 2016-06-10 06:00:00 : 강남동   16934 ----------


 ---------- 2016-06-10 14:00:00 : 동  면   16935 ----------


 ---------- 2016-06-10 17:00:00 : 강남동   16936 ----------


 ---------- 2016-06-11 02:00:00 : 효자1동   16937 ----------


 ---------- 2016-06-11 13:00:00 : 후평1동   16938 ----------


 ---------- 2016-06-11 16:00:00 : 사북면   16939 ----------


 ---------- 2016-06-11 17:00:00 : 석사동   16940 ----------


 ---------- 2016-06-11 21:00:00 : 석사동   16941 ----------


 ---------- 2016-06-12 09:00:00 : 효자1동   16942 ----------


 ---------- 2016-06-12 13:00:00 : 서  면   16943 ----------


 ---------- 2016-06-12 16:00:00 : 효자1동   16944 ----------


 ---------- 2016-06-12 16:00:00 : 후평1동   16945 ----------


 ---------- 2016-06-12 21:00:00 : 동  면   16946 ----------


 ---------- 2016-06-13 15:00:00 : 소양동   16947 ----------


 ---------- 2016-06-13 16:00:00 : 효자1동   16948 ----------


 ---------- 2016-06-13 16:00:00 : 북산면   16949 ----------


 ---------- 2016-06-13 16:00:00 : 조운동   16951 ----------


 ---------- 2016-06-13 18:00:00 : 근화동   16952 ----------


 ---------- 2016-06-13 22:00:00 : 효자1동   16953 ----------


 ---------- 2016-06-14 01:00:00 : 후평1동   16954 ----------


 ---------- 2016-06-14 09:00:00 : 남산면   16955 ----------


 ---------- 2016-06-14 10:00:00 : 남산면   16956 ----------


 ---------- 2016-06-14 11:00:00 : 후평1동   16957 ----------


 ---------- 2016-06-14 15:00:00 : 석사동   16958 ----------


 ---------- 2016-06-14 16:00:00 : 퇴계동   16960 ----------


 ---------- 2016-06-14 18:00:00 : 신사우동   16961 ----------


 ---------- 2016-06-15 08:00:00 : 소양동   16962 ----------


 ---------- 2016-06-15 14:00:00 : 남산면   16963 ----------


 ---------- 2016-06-15 16:00:00 : 퇴계동   16965 ----------


 ---------- 2016-06-15 17:00:00 : 서  면   16966 ----------


 ---------- 2016-06-15 20:00:00 : 석사동   16967 ----------


 ---------- 2016-06-16 07:00:00 : 동내면   16968 ----------


 ---------- 2016-06-16 09:00:00 : 석사동   16969 ----------


 ---------- 2016-06-16 09:00:00 : 남산면   16970 ----------


 ---------- 2016-06-16 12:00:00 : 강남동   16971 ----------


 ---------- 2016-06-16 13:00:00 : 강남동   16972 ----------


 ---------- 2016-06-16 13:00:00 : 소양동   16973 ----------


 ---------- 2016-06-16 16:00:00 : 서  면   16975 ----------


 ---------- 2016-06-17 00:00:00 : 효자1동   16976 ----------


 ---------- 2016-06-17 02:00:00 : 동내면   16977 ----------


 ---------- 2016-06-17 11:00:00 : 후평1동   16978 ----------


 ---------- 2016-06-17 13:00:00 : 신사우동   16979 ----------


 ---------- 2016-06-17 14:00:00 : 근화동   16980 ----------


 ---------- 2016-06-17 14:00:00 : 신사우동   16981 ----------


 ---------- 2016-06-17 17:00:00 : 효자1동   16982 ----------


 ---------- 2016-06-18 00:00:00 : 석사동   16983 ----------


 ---------- 2016-06-18 02:00:00 : 석사동   16984 ----------


 ---------- 2016-06-18 10:00:00 : 남산면   16985 ----------


 ---------- 2016-06-18 13:00:00 : 남산면   16986 ----------


 ---------- 2016-06-18 13:00:00 : 동  면   16987 ----------


 ---------- 2016-06-18 15:00:00 : 근화동   16988 ----------


 ---------- 2016-06-18 20:00:00 : 석사동   16989 ----------


 ---------- 2016-06-18 23:00:00 : 후평1동   16990 ----------


 ---------- 2016-06-19 01:00:00 : 효자1동   16991 ----------


 ---------- 2016-06-19 03:00:00 : 후평1동   16992 ----------


 ---------- 2016-06-19 08:00:00 : 남산면   16993 ----------


 ---------- 2016-06-19 08:00:00 : 신북읍   16994 ----------


 ---------- 2016-06-19 11:00:00 : 강남동   16995 ----------


 ---------- 2016-06-19 11:00:00 : 사북면   16996 ----------


 ---------- 2016-06-19 12:00:00 : 남산면   16997 ----------


 ---------- 2016-06-19 16:00:00 : 남  면   16999 ----------


 ---------- 2016-06-19 19:00:00 : 남산면   17000 ----------


 ---------- 2016-06-19 19:00:00 : 후평1동   17001 ----------


 ---------- 2016-06-19 21:00:00 : 교  동   17002 ----------

 ---------- 2016-06-20 13:00:00 : 강남동   17003 ----------


 ---------- 2016-06-20 13:00:00 : 남산면   17004 ----------


 ---------- 2016-06-20 14:00:00 : 남산면   17005 ----------


 ---------- 2016-06-20 17:00:00 : 퇴계동   17006 ----------


 ---------- 2016-06-20 17:00:00 : 동산면   17007 ----------


 ---------- 2016-06-20 20:00:00 : 신사우동   17008 ----------


 ---------- 2016-06-21 09:00:00 : 소양동   17009 ----------


 ---------- 2016-06-21 11:00:00 : 소양동   17010 ----------


 ---------- 2016-06-21 16:00:00 : 서  면   17011 ----------


 ---------- 2016-06-21 17:00:00 : 효자1동   17012 ----------


 ---------- 2016-06-21 21:00:00 : 소양동   17013 ----------


 ---------- 2016-06-21 22:00:00 : 서  면   17014 ----------


 ---------- 2016-06-22 01:00:00 : 효자1동   17015 ----------


 ---------- 2016-06-22 10:00:00 : 퇴계동   17017 ----------


 ---------- 2016-06-22 11:00:00 : 석사동   17018 ----------


 ---------- 2016-06-22 15:00:00 : 동  면   17019 ----------


 ---------- 2016-06-22 16:00:00 : 석사동   17021 ----------


 ---------- 2016-06-22 16:00:00 : 효자1동   17022 ----------


 ---------- 2016-06-22 17:00:00 : 퇴계동   17023 ----------


 ---------- 2016-06-22 19:00:00 : 서  면   17024 ----------


 ---------- 2016-06-22 19:00:00 : 효자1동   17025 ----------


 ---------- 2016-06-23 13:00:00 : 석사동   17026 ----------


 ---------- 2016-06-23 13:00:00 : 효자1동   17027 ----------


 ---------- 2016-06-23 16:00:00 : 석사동   17028 ----------


 ---------- 2016-06-23 18:00:00 : 동  면   17029 ----------


 ---------- 2016-06-24 14:00:00 : 강남동   17030 ----------


 ---------- 2016-06-24 17:00:00 : 남산면   17031 ----------


 ---------- 2016-06-24 19:00:00 : 효자1동   17033 ----------


 ---------- 2016-06-24 19:00:00 : 남산면   17034 ----------


 ---------- 2016-06-24 20:00:00 : 후평1동   17035 ----------


 ---------- 2016-06-24 22:00:00 : 교  동   17036 ----------


 ---------- 2016-06-25 09:00:00 : 소양동   17037 ----------


 ---------- 2016-06-25 10:00:00 : 근화동   17038 ----------


 ---------- 2016-06-25 12:00:00 : 강남동   17039 ----------


 ---------- 2016-06-25 15:00:00 : 신북읍   17040 ----------


 ---------- 2016-06-25 20:00:00 : 근화동   17041 ----------


 ---------- 2016-06-26 08:00:00 : 서  면   17042 ----------


 ---------- 2016-06-26 08:00:00 : 약사명동   17043 ----------


 ---------- 2016-06-26 10:00:00 : 동  면   17044 ----------


 ---------- 2016-06-26 11:00:00 : 동내면   17045 ----------


 ---------- 2016-06-26 11:00:00 : 신사우동   17046 ----------


 ---------- 2016-06-26 12:00:00 : 강남동   17047 ----------


 ---------- 2016-06-26 13:00:00 : 조운동   17048 ----------


 ---------- 2016-06-26 18:00:00 : 동내면   17049 ----------


 ---------- 2016-06-26 19:00:00 : 동내면   17050 ----------


 ---------- 2016-06-26 19:00:00 : 효자1동   17051 ----------


 ---------- 2016-06-26 22:00:00 : 조운동   17052 ----------


 ---------- 2016-06-26 23:00:00 : 남산면   17054 ----------


 ---------- 2016-06-27 00:00:00 : 퇴계동   17056 ----------


 ---------- 2016-06-27 02:00:00 : 동내면   17057 ----------


 ---------- 2016-06-27 08:00:00 : 신북읍   17058 ----------


 ---------- 2016-06-27 09:00:00 : 석사동   17059 ----------


 ---------- 2016-06-27 09:00:00 : 근화동   17060 ----------


 ---------- 2016-06-27 10:00:00 : 근화동   17061 ----------


 ---------- 2016-06-27 10:00:00 : 동산면   17062 ----------


 ---------- 2016-06-27 11:00:00 : 강남동   17063 ----------


 ---------- 2016-06-27 13:00:00 : 남산면   17064 ----------


 ---------- 2016-06-27 17:00:00 : 서  면   17065 ----------


 ---------- 2016-06-28 09:00:00 : 남산면   17066 ----------


 ---------- 2016-06-28 09:00:00 : 동  면   17067 ----------


 ---------- 2016-06-28 10:00:00 : 남산면   17068 ----------


 ---------- 2016-06-28 11:00:00 : 동내면   17069 ----------


 ---------- 2016-06-28 11:00:00 : 퇴계동   17070 ----------


 ---------- 2016-06-28 15:00:00 : 동내면   17071 ----------


 ---------- 2016-06-28 16:00:00 : 남산면   17072 ----------


 ---------- 2016-06-28 20:00:00 : 조운동   17073 ----------


 ---------- 2016-06-29 09:00:00 : 효자1동   17074 ----------


 ---------- 2016-06-29 10:00:00 : 효자1동   17075 ----------


 ---------- 2016-06-29 10:00:00 : 소양동   17076 ----------


 ---------- 2016-06-29 12:00:00 : 남산면   17077 ----------


 ---------- 2016-06-29 15:00:00 : 서  면   17078 ----------


 ---------- 2016-06-29 16:00:00 : 사북면   17079 ----------


 ---------- 2016-06-29 18:00:00 : 남산면   17080 ----------


 ---------- 2016-06-29 20:00:00 : 남산면   17081 ----------


 ---------- 2016-06-30 00:00:00 : 퇴계동   17082 ----------


 ---------- 2016-06-30 08:00:00 : 석사동   17083 ----------


 ---------- 2016-06-30 08:00:00 : 서  면   17085 ----------


 ---------- 2016-06-30 08:00:00 : 소양동   17086 ----------


 ---------- 2016-06-30 12:00:00 : 석사동   17087 ----------


 ---------- 2016-06-30 14:00:00 : 남  면   17088 ----------


 ---------- 2016-06-30 15:00:00 : 남산면   17089 ----------


 ---------- 2016-06-30 17:00:00 : 석사동   17090 ----------


 ---------- 2016-07-01 01:00:00 : 효자1동   17091 ----------


 ---------- 2016-07-01 07:00:00 : 효자1동   17092 ----------


 ---------- 2016-07-01 07:00:00 : 남산면   17093 ----------


 ---------- 2016-07-01 09:00:00 : 남산면   17094 ----------


 ---------- 2016-07-01 09:00:00 : 동  면   17095 ----------


 ---------- 2016-07-01 09:00:00 : 퇴계동   17096 ----------


 ---------- 2016-07-01 10:00:00 : 사북면   17097 ----------


 ---------- 2016-07-01 12:00:00 : 남산면   17098 ----------


 ---------- 2016-07-01 15:00:00 : 석사동   17099 ----------


 ---------- 2016-07-01 15:00:00 : 남  면   17100 ----------


 ---------- 2016-07-01 15:00:00 : 동산면   17101 ----------


 ---------- 2016-07-01 23:00:00 : 석사동   17103 ----------


 ---------- 2016-07-01 23:00:00 : 퇴계동   17106 ----------


 ---------- 2016-07-02 03:00:00 : 조운동   17107 ----------


 ---------- 2016-07-02 08:00:00 : 신북읍   17108 ----------


 ---------- 2016-07-02 09:00:00 : 신북읍   17109 ----------


 ---------- 2016-07-02 10:00:00 : 북산면   17110 ----------


 ---------- 2016-07-02 14:00:00 : 퇴계동   17111 ----------


 ---------- 2016-07-02 18:00:00 : 동산면   17112 ----------


 ---------- 2016-07-02 22:00:00 : 동내면   17113 ----------


 ---------- 2016-07-02 22:00:00 : 퇴계동   17114 ----------


 ---------- 2016-07-03 10:00:00 : 동  면   17115 ----------


 ---------- 2016-07-03 13:00:00 : 석사동   17116 ----------


 ---------- 2016-07-03 14:00:00 : 신북읍   17117 ----------


 ---------- 2016-07-04 02:00:00 : 동  면   17118 ----------


 ---------- 2016-07-04 10:00:00 : 신동면   17120 ----------


 ---------- 2016-07-04 11:00:00 : 석사동   17121 ----------


 ---------- 2016-07-04 11:00:00 : 근화동   17122 ----------


 ---------- 2016-07-04 12:00:00 : 동  면   17123 ----------


 ---------- 2016-07-04 15:00:00 : 석사동   17124 ----------


 ---------- 2016-07-04 15:00:00 : 강남동   17125 ----------


 ---------- 2016-07-04 16:00:00 : 조운동   17126 ----------


 ---------- 2016-07-04 17:00:00 : 후평1동   17127 ----------


 ---------- 2016-07-05 03:00:00 : 석사동   17128 ----------


 ---------- 2016-07-05 07:00:00 : 신사우동   17131 ----------


 ---------- 2016-07-05 09:00:00 : 서  면   17132 ----------


 ---------- 2016-07-05 10:00:00 : 남산면   17133 ----------


 ---------- 2016-07-05 11:00:00 : 석사동   17134 ----------


 ---------- 2016-07-05 11:00:00 : 남산면   17138 ----------


 ---------- 2016-07-05 11:00:00 : 후평1동   17139 ----------


 ---------- 2016-07-05 11:00:00 : 조운동   17140 ----------


 ---------- 2016-07-05 12:00:00 : 동내면   17141 ----------


 ---------- 2016-07-05 12:00:00 : 남산면   17143 ----------


 ---------- 2016-07-05 12:00:00 : 북산면   17144 ----------


 ---------- 2016-07-05 13:00:00 : 효자1동   17145 ----------


 ---------- 2016-07-05 14:00:00 : 강남동   17146 ----------


 ---------- 2016-07-05 14:00:00 : 남산면   17147 ----------


 ---------- 2016-07-05 14:00:00 : 신북읍   17148 ----------


 ---------- 2016-07-05 14:00:00 : 후평1동   17149 ----------


 ---------- 2016-07-05 15:00:00 : 석사동   17151 ----------


 ---------- 2016-07-05 15:00:00 : 남산면   17152 ----------


 ---------- 2016-07-05 16:00:00 : 석사동   17153 ----------


 ---------- 2016-07-05 18:00:00 : 신동면   17154 ----------


 ---------- 2016-07-05 18:00:00 : 후평1동   17155 ----------


 ---------- 2016-07-05 19:00:00 : 강남동   17156 ----------

 ---------- 2016-07-05 19:00:00 : 신사우동   17157 ----------


 ---------- 2016-07-05 20:00:00 : 신동면   17158 ----------


 ---------- 2016-07-05 20:00:00 : 교  동   17159 ----------


 ---------- 2016-07-06 00:00:00 : 후평1동   17160 ----------


 ---------- 2016-07-06 07:00:00 : 소양동   17161 ----------


 ---------- 2016-07-06 09:00:00 : 약사명동   17162 ----------


 ---------- 2016-07-06 09:00:00 : 퇴계동   17163 ----------


 ---------- 2016-07-06 11:00:00 : 퇴계동   17164 ----------


 ---------- 2016-07-06 14:00:00 : 석사동   17165 ----------


 ---------- 2016-07-06 14:00:00 : 동  면   17166 ----------


 ---------- 2016-07-06 17:00:00 : 동내면   17167 ----------


 ---------- 2016-07-06 17:00:00 : 조운동   17168 ----------


 ---------- 2016-07-06 18:00:00 : 남산면   17169 ----------


 ---------- 2016-07-06 19:00:00 : 조운동   17170 ----------


 ---------- 2016-07-06 20:00:00 : 퇴계동   17171 ----------


 ---------- 2016-07-06 23:00:00 : 효자1동   17172 ----------


 ---------- 2016-07-07 00:00:00 : 동  면   17174 ----------


 ---------- 2016-07-07 02:00:00 : 조운동   17175 ----------


 ---------- 2016-07-07 07:00:00 : 후평1동   17176 ----------


 ---------- 2016-07-07 09:00:00 : 남산면   17177 ----------


 ---------- 2016-07-07 10:00:00 : 근화동   17178 ----------


 ---------- 2016-07-07 10:00:00 : 후평1동   17179 ----------


 ---------- 2016-07-07 12:00:00 : 동내면   17180 ----------


 ---------- 2016-07-07 14:00:00 : 석사동   17181 ----------


 ---------- 2016-07-07 14:00:00 : 효자1동   17182 ----------


 ---------- 2016-07-07 18:00:00 : 효자1동   17183 ----------


 ---------- 2016-07-07 18:00:00 : 신사우동   17184 ----------


 ---------- 2016-07-07 22:00:00 : 근화동   17185 ----------


 ---------- 2016-07-08 00:00:00 : 신북읍   17186 ----------


 ---------- 2016-07-08 00:00:00 : 후평1동   17187 ----------


 ---------- 2016-07-08 09:00:00 : 서  면   17188 ----------


 ---------- 2016-07-08 09:00:00 : 동  면   17189 ----------


 ---------- 2016-07-08 11:00:00 : 동  면   17190 ----------


 ---------- 2016-07-08 12:00:00 : 동  면   17191 ----------


 ---------- 2016-07-08 13:00:00 : 동  면   17192 ----------


 ---------- 2016-07-08 14:00:00 : 서  면   17193 ----------


 ---------- 2016-07-08 17:00:00 : 근화동   17195 ----------


 ---------- 2016-07-09 09:00:00 : 소양동   17196 ----------


 ---------- 2016-07-09 10:00:00 : 효자1동   17198 ----------


 ---------- 2016-07-09 10:00:00 : 신북읍   17199 ----------


 ---------- 2016-07-09 11:00:00 : 신사우동   17200 ----------


 ---------- 2016-07-09 12:00:00 : 신사우동   17201 ----------


 ---------- 2016-07-09 12:00:00 : 동산면   17202 ----------


 ---------- 2016-07-09 14:00:00 : 강남동   17203 ----------


 ---------- 2016-07-09 15:00:00 : 북산면   17204 ----------


 ---------- 2016-07-09 23:00:00 : 조운동   17205 ----------


 ---------- 2016-07-10 03:00:00 : 효자1동   17206 ----------


 ---------- 2016-07-10 08:00:00 : 서  면   17207 ----------


 ---------- 2016-07-10 10:00:00 : 후평1동   17208 ----------


 ---------- 2016-07-10 11:00:00 : 남  면   17209 ----------


 ---------- 2016-07-10 13:00:00 : 남산면   17210 ----------


 ---------- 2016-07-10 15:00:00 : 신북읍   17211 ----------


 ---------- 2016-07-10 16:00:00 : 강남동   17212 ----------


 ---------- 2016-07-11 06:00:00 : 동  면   17213 ----------


 ---------- 2016-07-11 08:00:00 : 남산면   17214 ----------


 ---------- 2016-07-11 09:00:00 : 석사동   17215 ----------


 ---------- 2016-07-11 09:00:00 : 신사우동   17216 ----------


 ---------- 2016-07-11 14:00:00 : 동내면   17217 ----------


 ---------- 2016-07-11 19:00:00 : 석사동   17218 ----------


 ---------- 2016-07-11 19:00:00 : 퇴계동   17219 ----------


 ---------- 2016-07-12 02:00:00 : 소양동   17220 ----------


 ---------- 2016-07-12 09:00:00 : 강남동   17221 ----------


 ---------- 2016-07-12 09:00:00 : 북산면   17222 ----------


 ---------- 2016-07-12 10:00:00 : 동  면   17223 ----------


 ---------- 2016-07-12 11:00:00 : 퇴계동   17224 ----------


 ---------- 2016-07-12 12:00:00 : 신사우동   17225 ----------


 ---------- 2016-07-12 13:00:00 : 신사우동   17226 ----------


 ---------- 2016-07-12 14:00:00 : 근화동   17227 ----------


 ---------- 2016-07-12 15:00:00 : 석사동   17229 ----------


 ---------- 2016-07-12 18:00:00 : 후평1동   17230 ----------


 ---------- 2016-07-12 21:00:00 : 동내면   17232 ----------


 ---------- 2016-07-13 03:00:00 : 후평1동   17233 ----------


 ---------- 2016-07-13 09:00:00 : 강남동   17234 ----------


 ---------- 2016-07-13 09:00:00 : 동  면   17236 ----------


 ---------- 2016-07-13 10:00:00 : 강남동   17237 ----------


 ---------- 2016-07-13 10:00:00 : 서  면   17238 ----------


 ---------- 2016-07-13 12:00:00 : 남산면   17239 ----------


 ---------- 2016-07-13 17:00:00 : 근화동   17241 ----------


 ---------- 2016-07-13 19:00:00 : 교  동   17242 ----------


 ---------- 2016-07-13 20:00:00 : 소양동   17243 ----------


 ---------- 2016-07-13 21:00:00 : 효자1동   17244 ----------


 ---------- 2016-07-13 23:00:00 : 동내면   17245 ----------


 ---------- 2016-07-14 00:00:00 : 교  동   17246 ----------


 ---------- 2016-07-14 08:00:00 : 남산면   17247 ----------


 ---------- 2016-07-14 08:00:00 : 근화동   17249 ----------


 ---------- 2016-07-14 11:00:00 : 효자1동   17250 ----------


 ---------- 2016-07-14 13:00:00 : 효자1동   17251 ----------


 ---------- 2016-07-14 14:00:00 : 석사동   17252 ----------


 ---------- 2016-07-14 14:00:00 : 동내면   17254 ----------


 ---------- 2016-07-14 14:00:00 : 효자1동   17255 ----------


 ---------- 2016-07-14 15:00:00 : 남산면   17256 ----------


 ---------- 2016-07-14 17:00:00 : 신북읍   17257 ----------


 ---------- 2016-07-14 17:00:00 : 동  면   17259 ----------


 ---------- 2016-07-14 18:00:00 : 신사우동   17260 ----------


 ---------- 2016-07-14 18:00:00 : 교  동   17261 ----------


 ---------- 2016-07-15 09:00:00 : 석사동   17262 ----------


 ---------- 2016-07-15 09:00:00 : 신북읍   17263 ----------


 ---------- 2016-07-15 10:00:00 : 동내면   17264 ----------


 ---------- 2016-07-15 11:00:00 : 퇴계동   17265 ----------


 ---------- 2016-07-15 13:00:00 : 석사동   17266 ----------


 ---------- 2016-07-15 13:00:00 : 근화동   17267 ----------


 ---------- 2016-07-15 15:00:00 : 남산면   17268 ----------


 ---------- 2016-07-15 16:00:00 : 신동면   17269 ----------


 ---------- 2016-07-15 16:00:00 : 남산면   17270 ----------


 ---------- 2016-07-15 17:00:00 : 동내면   17271 ----------


 ---------- 2016-07-16 04:00:00 : 강남동   17272 ----------


 ---------- 2016-07-16 11:00:00 : 석사동   17273 ----------


 ---------- 2016-07-16 12:00:00 : 서  면   17274 ----------


 ---------- 2016-07-16 15:00:00 : 석사동   17275 ----------


 ---------- 2016-07-16 15:00:00 : 동  면   17276 ----------


 ---------- 2016-07-16 17:00:00 : 석사동   17277 ----------


 ---------- 2016-07-17 00:00:00 : 효자1동   17278 ----------


 ---------- 2016-07-17 00:00:00 : 퇴계동   17279 ----------


 ---------- 2016-07-17 01:00:00 : 소양동   17280 ----------


 ---------- 2016-07-17 09:00:00 : 후평1동   17281 ----------


 ---------- 2016-07-17 10:00:00 : 퇴계동   17282 ----------


 ---------- 2016-07-17 12:00:00 : 효자1동   17283 ----------


 ---------- 2016-07-17 13:00:00 : 동내면   17285 ----------


 ---------- 2016-07-17 13:00:00 : 남산면   17287 ----------


 ---------- 2016-07-17 13:00:00 : 소양동   17288 ----------


 ---------- 2016-07-17 14:00:00 : 동내면   17289 ----------


 ---------- 2016-07-17 14:00:00 : 신사우동   17290 ----------


 ---------- 2016-07-17 14:00:00 : 신북읍   17294 ----------


 ---------- 2016-07-17 16:00:00 : 남  면   17297 ----------


 ---------- 2016-07-17 16:00:00 : 남산면   17298 ----------


 ---------- 2016-07-17 17:00:00 : 효자1동   17299 ----------


 ---------- 2016-07-17 19:00:00 : 석사동   17300 ----------


 ---------- 2016-07-17 19:00:00 : 신사우동   17302 ----------


 ---------- 2016-07-17 21:00:00 : 동내면   17305 ----------


 ---------- 2016-07-18 00:00:00 : 퇴계동   17306 ----------


 ---------- 2016-07-18 09:00:00 : 퇴계동   17307 ----------


 ---------- 2016-07-18 10:00:00 : 석사동   17308 ----------


 ---------- 2016-07-18 10:00:00 : 동내면   17309 ----------


 ---------- 2016-07-18 11:00:00 : 신사우동   17310 ----------


 ---------- 2016-07-18 13:00:00 : 동내면   17311 ----------


 ---------- 2016-07-18 15:00:00 : 석사동   17312 ----------


 ---------- 2016-07-18 15:00:00 : 남  면   17313 ----------

 ---------- 2016-07-18 15:00:00 : 후평1동   17315 ----------


 ---------- 2016-07-18 15:00:00 : 동산면   17316 ----------


 ---------- 2016-07-18 17:00:00 : 서  면   17317 ----------


 ---------- 2016-07-18 17:00:00 : 퇴계동   17318 ----------


 ---------- 2016-07-18 18:00:00 : 퇴계동   17320 ----------


 ---------- 2016-07-19 04:00:00 : 동내면   17321 ----------


 ---------- 2016-07-19 09:00:00 : 동내면   17322 ----------


 ---------- 2016-07-19 09:00:00 : 남산면   17324 ----------


 ---------- 2016-07-19 09:00:00 : 북산면   17326 ----------


 ---------- 2016-07-19 10:00:00 : 석사동   17327 ----------


 ---------- 2016-07-19 10:00:00 : 효자1동   17328 ----------


 ---------- 2016-07-19 11:00:00 : 사북면   17329 ----------


 ---------- 2016-07-19 11:00:00 : 효자1동   17330 ----------


 ---------- 2016-07-19 12:00:00 : 강남동   17331 ----------


 ---------- 2016-07-19 12:00:00 : 근화동   17332 ----------


 ---------- 2016-07-19 12:00:00 : 북산면   17333 ----------


 ---------- 2016-07-19 13:00:00 : 동내면   17334 ----------


 ---------- 2016-07-19 13:00:00 : 신사우동   17335 ----------


 ---------- 2016-07-19 13:00:00 : 신북읍   17336 ----------


 ---------- 2016-07-19 13:00:00 : 동산면   17337 ----------


 ---------- 2016-07-19 14:00:00 : 서  면   17338 ----------


 ---------- 2016-07-19 15:00:00 : 강남동   17339 ----------


 ---------- 2016-07-19 16:00:00 : 신북읍   17340 ----------


 ---------- 2016-07-19 20:00:00 : 효자1동   17341 ----------


 ---------- 2016-07-19 23:00:00 : 후평1동   17342 ----------


 ---------- 2016-07-20 02:00:00 : 신사우동   17344 ----------


 ---------- 2016-07-20 06:00:00 : 소양동   17345 ----------


 ---------- 2016-07-20 09:00:00 : 석사동   17346 ----------


 ---------- 2016-07-20 09:00:00 : 신사우동   17347 ----------


 ---------- 2016-07-20 09:00:00 : 교  동   17350 ----------


 ---------- 2016-07-20 10:00:00 : 동  면   17351 ----------


 ---------- 2016-07-20 12:00:00 : 석사동   17352 ----------


 ---------- 2016-07-20 13:00:00 : 퇴계동   17353 ----------


 ---------- 2016-07-20 14:00:00 : 강남동   17354 ----------


 ---------- 2016-07-20 15:00:00 : 사북면   17355 ----------


 ---------- 2016-07-20 15:00:00 : 남산면   17356 ----------


 ---------- 2016-07-20 15:00:00 : 후평1동   17358 ----------


 ---------- 2016-07-20 18:00:00 : 남산면   17359 ----------


 ---------- 2016-07-20 18:00:00 : 동  면   17361 ----------


 ---------- 2016-07-20 23:00:00 : 효자1동   17362 ----------


 ---------- 2016-07-21 09:00:00 : 신동면   17363 ----------


 ---------- 2016-07-21 09:00:00 : 근화동   17364 ----------


 ---------- 2016-07-21 10:00:00 : 동  면   17365 ----------


 ---------- 2016-07-21 11:00:00 : 남산면   17366 ----------


 ---------- 2016-07-21 15:00:00 : 효자1동   17367 ----------


 ---------- 2016-07-21 17:00:00 : 동  면   17368 ----------


 ---------- 2016-07-21 23:00:00 : 효자1동   17369 ----------


 ---------- 2016-07-22 00:00:00 : 석사동   17370 ----------


 ---------- 2016-07-22 09:00:00 : 신동면   17371 ----------


 ---------- 2016-07-22 10:00:00 : 퇴계동   17372 ----------


 ---------- 2016-07-22 15:00:00 : 강남동   17375 ----------


 ---------- 2016-07-22 16:00:00 : 동내면   17376 ----------


 ---------- 2016-07-22 16:00:00 : 소양동   17377 ----------


 ---------- 2016-07-22 17:00:00 : 효자1동   17378 ----------


 ---------- 2016-07-22 22:00:00 : 근화동   17379 ----------


 ---------- 2016-07-23 08:00:00 : 퇴계동   17380 ----------


 ---------- 2016-07-23 09:00:00 : 동내면   17381 ----------


 ---------- 2016-07-23 09:00:00 : 후평1동   17382 ----------


 ---------- 2016-07-23 10:00:00 : 동산면   17383 ----------


 ---------- 2016-07-23 13:00:00 : 사북면   17385 ----------


 ---------- 2016-07-23 14:00:00 : 서  면   17386 ----------


 ---------- 2016-07-23 16:00:00 : 약사명동   17387 ----------


 ---------- 2016-07-23 16:00:00 : 조운동   17388 ----------


 ---------- 2016-07-23 16:00:00 : 동산면   17389 ----------


 ---------- 2016-07-23 18:00:00 : 동내면   17390 ----------


 ---------- 2016-07-23 18:00:00 : 조운동   17391 ----------


 ---------- 2016-07-23 19:00:00 : 동내면   17392 ----------


 ---------- 2016-07-23 21:00:00 : 강남동   17393 ----------


 ---------- 2016-07-23 22:00:00 : 후평1동   17394 ----------


 ---------- 2016-07-23 22:00:00 : 조운동   17395 ----------


 ---------- 2016-07-24 01:00:00 : 효자1동   17396 ----------


 ---------- 2016-07-24 09:00:00 : 신동면   17398 ----------


 ---------- 2016-07-24 09:00:00 : 북산면   17399 ----------


 ---------- 2016-07-24 13:00:00 : 석사동   17400 ----------


 ---------- 2016-07-24 15:00:00 : 남산면   17401 ----------


 ---------- 2016-07-24 17:00:00 : 교  동   17402 ----------


 ---------- 2016-07-24 18:00:00 : 석사동   17403 ----------


 ---------- 2016-07-24 20:00:00 : 서  면   17404 ----------


 ---------- 2016-07-25 00:00:00 : 신사우동   17405 ----------


 ---------- 2016-07-25 09:00:00 : 소양동   17406 ----------


 ---------- 2016-07-25 10:00:00 : 후평1동   17408 ----------


 ---------- 2016-07-25 11:00:00 : 동내면   17409 ----------


 ---------- 2016-07-25 11:00:00 : 동  면   17410 ----------


 ---------- 2016-07-25 13:00:00 : 신북읍   17411 ----------


 ---------- 2016-07-25 14:00:00 : 소양동   17412 ----------


 ---------- 2016-07-25 15:00:00 : 약사명동   17413 ----------


 ---------- 2016-07-25 18:00:00 : 후평1동   17414 ----------


 ---------- 2016-07-26 01:00:00 : 근화동   17415 ----------


 ---------- 2016-07-26 09:00:00 : 서  면   17416 ----------


 ---------- 2016-07-26 10:00:00 : 석사동   17417 ----------


 ---------- 2016-07-26 10:00:00 : 신동면   17418 ----------


 ---------- 2016-07-26 13:00:00 : 퇴계동   17419 ----------


 ---------- 2016-07-26 15:00:00 : 동내면   17420 ----------


 ---------- 2016-07-26 15:00:00 : 퇴계동   17421 ----------


 ---------- 2016-07-26 16:00:00 : 서  면   17422 ----------


 ---------- 2016-07-26 16:00:00 : 효자1동   17423 ----------


 ---------- 2016-07-26 17:00:00 : 동  면   17424 ----------


 ---------- 2016-07-26 19:00:00 : 강남동   17425 ----------


 ---------- 2016-07-27 02:00:00 : 퇴계동   17426 ----------


 ---------- 2016-07-27 07:00:00 : 석사동   17427 ----------


 ---------- 2016-07-27 09:00:00 : 남산면   17428 ----------


 ---------- 2016-07-27 11:00:00 : 북산면   17429 ----------


 ---------- 2016-07-27 15:00:00 : 강남동   17430 ----------


 ---------- 2016-07-27 16:00:00 : 남산면   17431 ----------


 ---------- 2016-07-27 22:00:00 : 근화동   17433 ----------


 ---------- 2016-07-27 23:00:00 : 남산면   17435 ----------


 ---------- 2016-07-28 00:00:00 : 근화동   17436 ----------


 ---------- 2016-07-28 01:00:00 : 근화동   17437 ----------


 ---------- 2016-07-28 06:00:00 : 강남동   17438 ----------


 ---------- 2016-07-28 07:00:00 : 남산면   17440 ----------


 ---------- 2016-07-28 07:00:00 : 교  동   17441 ----------


 ---------- 2016-07-28 08:00:00 : 남산면   17443 ----------


 ---------- 2016-07-28 09:00:00 : 사북면   17444 ----------


 ---------- 2016-07-28 10:00:00 : 남산면   17445 ----------


 ---------- 2016-07-28 10:00:00 : 후평1동   17446 ----------


 ---------- 2016-07-28 11:00:00 : 동  면   17448 ----------


 ---------- 2016-07-28 12:00:00 : 동  면   17449 ----------


 ---------- 2016-07-28 13:00:00 : 동  면   17450 ----------


 ---------- 2016-07-28 14:00:00 : 남산면   17451 ----------


 ---------- 2016-07-28 14:00:00 : 동  면   17452 ----------


 ---------- 2016-07-28 15:00:00 : 동내면   17454 ----------


 ---------- 2016-07-28 17:00:00 : 동내면   17455 ----------


 ---------- 2016-07-28 18:00:00 : 석사동   17456 ----------


 ---------- 2016-07-29 02:00:00 : 효자1동   17457 ----------


 ---------- 2016-07-29 06:00:00 : 강남동   17458 ----------


 ---------- 2016-07-29 10:00:00 : 동  면   17459 ----------


 ---------- 2016-07-29 11:00:00 : 신사우동   17460 ----------


 ---------- 2016-07-29 12:00:00 : 서  면   17461 ----------


 ---------- 2016-07-29 12:00:00 : 후평1동   17462 ----------


 ---------- 2016-07-29 12:00:00 : 퇴계동   17463 ----------


 ---------- 2016-07-29 13:00:00 : 강남동   17464 ----------


 ---------- 2016-07-29 13:00:00 : 동내면   17465 ----------


 ---------- 2016-07-29 13:00:00 : 효자1동   17466 ----------


 ---------- 2016-07-29 13:00:00 : 남산면   17467 ----------


 ---------- 2016-07-29 13:00:00 : 동산면   17468 ----------


 ---------- 2016-07-29 14:00:00 : 동  면   17470 ----------

 ---------- 2016-07-29 15:00:00 : 동내면   17471 ----------


 ---------- 2016-07-29 16:00:00 : 근화동   17472 ----------


 ---------- 2016-07-29 23:00:00 : 석사동   17473 ----------


 ---------- 2016-07-29 23:00:00 : 효자1동   17474 ----------


 ---------- 2016-07-29 23:00:00 : 신사우동   17477 ----------


 ---------- 2016-07-30 00:00:00 : 약사명동   17478 ----------


 ---------- 2016-07-30 08:00:00 : 석사동   17479 ----------


 ---------- 2016-07-30 08:00:00 : 신북읍   17480 ----------


 ---------- 2016-07-30 09:00:00 : 동내면   17481 ----------


 ---------- 2016-07-30 09:00:00 : 신사우동   17482 ----------


 ---------- 2016-07-30 10:00:00 : 석사동   17483 ----------


 ---------- 2016-07-30 10:00:00 : 신사우동   17484 ----------


 ---------- 2016-07-30 12:00:00 : 동산면   17485 ----------


 ---------- 2016-07-30 15:00:00 : 퇴계동   17486 ----------


 ---------- 2016-07-30 16:00:00 : 효자1동   17487 ----------


 ---------- 2016-07-30 16:00:00 : 남산면   17488 ----------


 ---------- 2016-07-30 17:00:00 : 신동면   17489 ----------


 ---------- 2016-07-30 18:00:00 : 강남동   17490 ----------


 ---------- 2016-07-30 21:00:00 : 신북읍   17491 ----------


 ---------- 2016-07-31 03:00:00 : 남산면   17494 ----------


 ---------- 2016-07-31 04:00:00 : 효자1동   17495 ----------


 ---------- 2016-07-31 06:00:00 : 사북면   17496 ----------


 ---------- 2016-07-31 09:00:00 : 남산면   17497 ----------


 ---------- 2016-07-31 11:00:00 : 신북읍   17498 ----------


 ---------- 2016-07-31 11:00:00 : 퇴계동   17499 ----------


 ---------- 2016-07-31 12:00:00 : 석사동   17500 ----------


 ---------- 2016-07-31 12:00:00 : 효자1동   17501 ----------


 ---------- 2016-07-31 12:00:00 : 신사우동   17502 ----------


 ---------- 2016-07-31 14:00:00 : 동내면   17503 ----------


 ---------- 2016-07-31 15:00:00 : 석사동   17504 ----------


 ---------- 2016-07-31 15:00:00 : 근화동   17505 ----------


 ---------- 2016-07-31 16:00:00 : 소양동   17507 ----------


 ---------- 2016-08-01 07:00:00 : 신북읍   17508 ----------


 ---------- 2016-08-01 09:00:00 : 퇴계동   17509 ----------


 ---------- 2016-08-01 10:00:00 : 강남동   17510 ----------


 ---------- 2016-08-01 10:00:00 : 동내면   17511 ----------


 ---------- 2016-08-01 10:00:00 : 남산면   17512 ----------


 ---------- 2016-08-01 10:00:00 : 신사우동   17513 ----------


 ---------- 2016-08-01 10:00:00 : 조운동   17514 ----------


 ---------- 2016-08-01 12:00:00 : 신동면   17515 ----------


 ---------- 2016-08-01 12:00:00 : 강남동   17516 ----------


 ---------- 2016-08-01 12:00:00 : 조운동   17517 ----------


 ---------- 2016-08-01 15:00:00 : 신동면   17518 ----------


 ---------- 2016-08-01 16:00:00 : 근화동   17520 ----------


 ---------- 2016-08-01 17:00:00 : 남  면   17522 ----------


 ---------- 2016-08-01 17:00:00 : 효자1동   17524 ----------


 ---------- 2016-08-01 17:00:00 : 퇴계동   17525 ----------


 ---------- 2016-08-01 18:00:00 : 강남동   17526 ----------


 ---------- 2016-08-01 18:00:00 : 서  면   17527 ----------


 ---------- 2016-08-01 18:00:00 : 근화동   17532 ----------


 ---------- 2016-08-01 18:00:00 : 신북읍   17533 ----------


 ---------- 2016-08-01 18:00:00 : 후평1동   17534 ----------


 ---------- 2016-08-01 18:00:00 : 조운동   17535 ----------


 ---------- 2016-08-01 19:00:00 : 강남동   17537 ----------


 ---------- 2016-08-01 19:00:00 : 근화동   17539 ----------


 ---------- 2016-08-01 20:00:00 : 강남동   17540 ----------


 ---------- 2016-08-02 05:00:00 : 석사동   17541 ----------


 ---------- 2016-08-02 05:00:00 : 서  면   17542 ----------


 ---------- 2016-08-02 07:00:00 : 남산면   17543 ----------


 ---------- 2016-08-02 08:00:00 : 북산면   17544 ----------


 ---------- 2016-08-02 08:00:00 : 조운동   17545 ----------


 ---------- 2016-08-02 09:00:00 : 동내면   17546 ----------


 ---------- 2016-08-02 09:00:00 : 후평1동   17547 ----------


 ---------- 2016-08-02 10:00:00 : 신북읍   17548 ----------


 ---------- 2016-08-02 10:00:00 : 동  면   17549 ----------


 ---------- 2016-08-02 11:00:00 : 동  면   17550 ----------


 ---------- 2016-08-02 13:00:00 : 신북읍   17551 ----------


 ---------- 2016-08-02 18:00:00 : 효자1동   17554 ----------


 ---------- 2016-08-02 18:00:00 : 소양동   17555 ----------


 ---------- 2016-08-03 05:00:00 : 퇴계동   17556 ----------


 ---------- 2016-08-03 09:00:00 : 석사동   17557 ----------


 ---------- 2016-08-03 09:00:00 : 강남동   17558 ----------


 ---------- 2016-08-03 10:00:00 : 남  면   17559 ----------


 ---------- 2016-08-03 11:00:00 : 강남동   17560 ----------


 ---------- 2016-08-03 12:00:00 : 서  면   17561 ----------


 ---------- 2016-08-03 13:00:00 : 동  면   17563 ----------


 ---------- 2016-08-03 14:00:00 : 동  면   17564 ----------


 ---------- 2016-08-03 14:00:00 : 북산면   17566 ----------


 ---------- 2016-08-03 14:00:00 : 동산면   17567 ----------


 ---------- 2016-08-03 15:00:00 : 남  면   17568 ----------


 ---------- 2016-08-03 16:00:00 : 남산면   17569 ----------


 ---------- 2016-08-03 17:00:00 : 석사동   17570 ----------


 ---------- 2016-08-03 18:00:00 : 동내면   17571 ----------


 ---------- 2016-08-03 18:00:00 : 남산면   17572 ----------


 ---------- 2016-08-03 19:00:00 : 동산면   17573 ----------


 ---------- 2016-08-03 21:00:00 : 석사동   17574 ----------


 ---------- 2016-08-03 21:00:00 : 조운동   17575 ----------


 ---------- 2016-08-03 23:00:00 : 퇴계동   17576 ----------


 ---------- 2016-08-04 08:00:00 : 후평1동   17577 ----------


 ---------- 2016-08-04 09:00:00 : 후평1동   17578 ----------


 ---------- 2016-08-04 10:00:00 : 북산면   17579 ----------


 ---------- 2016-08-04 11:00:00 : 석사동   17580 ----------


 ---------- 2016-08-04 11:00:00 : 동내면   17581 ----------


 ---------- 2016-08-04 11:00:00 : 동  면   17582 ----------


 ---------- 2016-08-04 12:00:00 : 석사동   17583 ----------


 ---------- 2016-08-04 12:00:00 : 강남동   17584 ----------


 ---------- 2016-08-04 12:00:00 : 근화동   17586 ----------


 ---------- 2016-08-04 13:00:00 : 남  면   17588 ----------


 ---------- 2016-08-04 14:00:00 : 석사동   17589 ----------


 ---------- 2016-08-04 14:00:00 : 남  면   17590 ----------


 ---------- 2016-08-04 14:00:00 : 신북읍   17591 ----------


 ---------- 2016-08-04 14:00:00 : 후평1동   17592 ----------


 ---------- 2016-08-04 14:00:00 : 동산면   17593 ----------


 ---------- 2016-08-04 15:00:00 : 효자1동   17594 ----------


 ---------- 2016-08-04 15:00:00 : 퇴계동   17595 ----------


 ---------- 2016-08-04 18:00:00 : 후평1동   17596 ----------


 ---------- 2016-08-04 19:00:00 : 서  면   17597 ----------


 ---------- 2016-08-04 19:00:00 : 효자1동   17598 ----------


 ---------- 2016-08-05 01:00:00 : 퇴계동   17599 ----------


 ---------- 2016-08-05 07:00:00 : 효자1동   17600 ----------


 ---------- 2016-08-05 08:00:00 : 효자1동   17601 ----------


 ---------- 2016-08-05 09:00:00 : 동산면   17602 ----------


 ---------- 2016-08-05 10:00:00 : 근화동   17603 ----------


 ---------- 2016-08-05 10:00:00 : 동  면   17605 ----------


 ---------- 2016-08-05 11:00:00 : 강남동   17606 ----------


 ---------- 2016-08-05 11:00:00 : 신북읍   17607 ----------


 ---------- 2016-08-05 12:00:00 : 남산면   17608 ----------


 ---------- 2016-08-05 12:00:00 : 동산면   17609 ----------


 ---------- 2016-08-05 13:00:00 : 동내면   17610 ----------


 ---------- 2016-08-05 14:00:00 : 동  면   17611 ----------


 ---------- 2016-08-05 14:00:00 : 교  동   17612 ----------


 ---------- 2016-08-05 15:00:00 : 서  면   17613 ----------


 ---------- 2016-08-05 17:00:00 : 서  면   17614 ----------


 ---------- 2016-08-05 18:00:00 : 석사동   17615 ----------


 ---------- 2016-08-05 18:00:00 : 동  면   17616 ----------


 ---------- 2016-08-05 18:00:00 : 퇴계동   17617 ----------


 ---------- 2016-08-05 22:00:00 : 후평1동   17618 ----------


 ---------- 2016-08-06 03:00:00 : 후평1동   17619 ----------


 ---------- 2016-08-06 08:00:00 : 서  면   17620 ----------


 ---------- 2016-08-06 08:00:00 : 근화동   17621 ----------


 ---------- 2016-08-06 08:00:00 : 신사우동   17622 ----------


 ---------- 2016-08-06 09:00:00 : 후평1동   17623 ----------


 ---------- 2016-08-06 10:00:00 : 퇴계동   17624 ----------


 ---------- 2016-08-06 11:00:00 : 소양동   17625 ----------


 ---------- 2016-08-06 12:00:00 : 석사동   17626 ----------


 ---------- 2016-08-06 13:00:00 : 남산면   17627 ----------

 ---------- 2016-08-06 14:00:00 : 효자1동   17628 ----------


 ---------- 2016-08-06 15:00:00 : 근화동   17629 ----------


 ---------- 2016-08-06 17:00:00 : 신동면   17630 ----------


 ---------- 2016-08-06 17:00:00 : 강남동   17631 ----------


 ---------- 2016-08-06 19:00:00 : 후평1동   17632 ----------


 ---------- 2016-08-06 20:00:00 : 신동면   17633 ----------


 ---------- 2016-08-07 03:00:00 : 강남동   17636 ----------


 ---------- 2016-08-07 09:00:00 : 석사동   17637 ----------


 ---------- 2016-08-07 09:00:00 : 근화동   17638 ----------


 ---------- 2016-08-07 11:00:00 : 후평1동   17639 ----------


 ---------- 2016-08-07 12:00:00 : 석사동   17640 ----------


 ---------- 2016-08-07 13:00:00 : 동  면   17641 ----------


 ---------- 2016-08-07 16:00:00 : 강남동   17642 ----------


 ---------- 2016-08-07 17:00:00 : 석사동   17644 ----------


 ---------- 2016-08-07 18:00:00 : 석사동   17645 ----------


 ---------- 2016-08-07 18:00:00 : 동  면   17646 ----------


 ---------- 2016-08-07 19:00:00 : 강남동   17647 ----------


 ---------- 2016-08-08 00:00:00 : 강남동   17648 ----------


 ---------- 2016-08-08 00:00:00 : 남산면   17649 ----------


 ---------- 2016-08-08 04:00:00 : 남산면   17650 ----------


 ---------- 2016-08-08 07:00:00 : 효자1동   17651 ----------


 ---------- 2016-08-08 09:00:00 : 근화동   17652 ----------


 ---------- 2016-08-08 09:00:00 : 후평1동   17654 ----------


 ---------- 2016-08-08 10:00:00 : 석사동   17655 ----------


 ---------- 2016-08-08 11:00:00 : 신북읍   17656 ----------


 ---------- 2016-08-08 12:00:00 : 사북면   17657 ----------


 ---------- 2016-08-08 12:00:00 : 신북읍   17658 ----------


 ---------- 2016-08-08 12:00:00 : 퇴계동   17659 ----------


 ---------- 2016-08-08 13:00:00 : 신동면   17660 ----------


 ---------- 2016-08-08 13:00:00 : 강남동   17661 ----------


 ---------- 2016-08-08 13:00:00 : 서  면   17662 ----------


 ---------- 2016-08-08 13:00:00 : 사북면   17663 ----------


 ---------- 2016-08-08 13:00:00 : 동  면   17664 ----------


 ---------- 2016-08-08 13:00:00 : 퇴계동   17665 ----------


 ---------- 2016-08-08 14:00:00 : 동산면   17666 ----------


 ---------- 2016-08-08 17:00:00 : 석사동   17667 ----------


 ---------- 2016-08-08 17:00:00 : 효자1동   17668 ----------


 ---------- 2016-08-08 18:00:00 : 석사동   17669 ----------


 ---------- 2016-08-08 19:00:00 : 후평1동   17670 ----------


 ---------- 2016-08-08 21:00:00 : 동내면   17671 ----------


 ---------- 2016-08-08 21:00:00 : 퇴계동   17672 ----------


 ---------- 2016-08-08 23:00:00 : 석사동   17673 ----------


 ---------- 2016-08-09 06:00:00 : 동내면   17674 ----------


 ---------- 2016-08-09 09:00:00 : 동내면   17675 ----------


 ---------- 2016-08-09 09:00:00 : 동산면   17676 ----------


 ---------- 2016-08-09 10:00:00 : 강남동   17677 ----------


 ---------- 2016-08-09 11:00:00 : 신사우동   17678 ----------


 ---------- 2016-08-09 13:00:00 : 동내면   17681 ----------


 ---------- 2016-08-09 15:00:00 : 석사동   17684 ----------


 ---------- 2016-08-09 15:00:00 : 신북읍   17685 ----------


 ---------- 2016-08-09 15:00:00 : 소양동   17686 ----------


 ---------- 2016-08-09 15:00:00 : 동  면   17687 ----------


 ---------- 2016-08-09 16:00:00 : 퇴계동   17688 ----------


 ---------- 2016-08-09 17:00:00 : 강남동   17689 ----------


 ---------- 2016-08-09 18:00:00 : 후평1동   17690 ----------


 ---------- 2016-08-09 18:00:00 : 교  동   17691 ----------


 ---------- 2016-08-09 19:00:00 : 남산면   17692 ----------


 ---------- 2016-08-09 19:00:00 : 후평1동   17693 ----------


 ---------- 2016-08-10 08:00:00 : 석사동   17695 ----------


 ---------- 2016-08-10 08:00:00 : 후평1동   17696 ----------


 ---------- 2016-08-10 09:00:00 : 석사동   17697 ----------


 ---------- 2016-08-10 11:00:00 : 약사명동   17698 ----------


 ---------- 2016-08-10 11:00:00 : 후평1동   17699 ----------


 ---------- 2016-08-10 12:00:00 : 남산면   17701 ----------


 ---------- 2016-08-10 12:00:00 : 약사명동   17703 ----------


 ---------- 2016-08-10 12:00:00 : 퇴계동   17704 ----------


 ---------- 2016-08-10 15:00:00 : 사북면   17705 ----------


 ---------- 2016-08-10 18:00:00 : 동내면   17706 ----------


 ---------- 2016-08-10 23:00:00 : 효자1동   17707 ----------


 ---------- 2016-08-10 23:00:00 : 신북읍   17708 ----------


 ---------- 2016-08-11 02:00:00 : 석사동   17709 ----------


 ---------- 2016-08-11 08:00:00 : 신동면   17710 ----------


 ---------- 2016-08-11 08:00:00 : 신사우동   17711 ----------


 ---------- 2016-08-11 08:00:00 : 신북읍   17712 ----------


 ---------- 2016-08-11 09:00:00 : 남  면   17713 ----------


 ---------- 2016-08-11 09:00:00 : 퇴계동   17714 ----------


 ---------- 2016-08-11 10:00:00 : 퇴계동   17715 ----------


 ---------- 2016-08-11 12:00:00 : 강남동   17716 ----------


 ---------- 2016-08-11 12:00:00 : 동  면   17717 ----------


 ---------- 2016-08-11 16:00:00 : 후평1동   17718 ----------


 ---------- 2016-08-11 17:00:00 : 남산면   17719 ----------


 ---------- 2016-08-11 17:00:00 : 동  면   17720 ----------


 ---------- 2016-08-11 19:00:00 : 석사동   17721 ----------


 ---------- 2016-08-11 20:00:00 : 퇴계동   17722 ----------


 ---------- 2016-08-11 23:00:00 : 교  동   17723 ----------


 ---------- 2016-08-12 00:00:00 : 신사우동   17724 ----------


 ---------- 2016-08-12 04:00:00 : 남산면   17726 ----------


 ---------- 2016-08-12 05:00:00 : 남산면   17727 ----------


 ---------- 2016-08-12 08:00:00 : 남산면   17730 ----------


 ---------- 2016-08-12 08:00:00 : 동  면   17731 ----------


 ---------- 2016-08-12 09:00:00 : 동  면   17732 ----------


 ---------- 2016-08-12 09:00:00 : 퇴계동   17733 ----------


 ---------- 2016-08-12 11:00:00 : 동  면   17735 ----------


 ---------- 2016-08-12 12:00:00 : 강남동   17736 ----------


 ---------- 2016-08-12 12:00:00 : 동  면   17737 ----------


 ---------- 2016-08-12 14:00:00 : 동  면   17738 ----------


 ---------- 2016-08-12 15:00:00 : 석사동   17739 ----------


 ---------- 2016-08-12 18:00:00 : 서  면   17740 ----------


 ---------- 2016-08-12 19:00:00 : 신북읍   17741 ----------


 ---------- 2016-08-13 01:00:00 : 동내면   17742 ----------


 ---------- 2016-08-13 04:00:00 : 강남동   17743 ----------


 ---------- 2016-08-13 08:00:00 : 신북읍   17744 ----------


 ---------- 2016-08-13 08:00:00 : 동  면   17745 ----------


 ---------- 2016-08-13 09:00:00 : 북산면   17746 ----------


 ---------- 2016-08-13 10:00:00 : 동내면   17747 ----------


 ---------- 2016-08-13 10:00:00 : 신북읍   17748 ----------


 ---------- 2016-08-13 10:00:00 : 소양동   17749 ----------


 ---------- 2016-08-13 11:00:00 : 후평1동   17750 ----------


 ---------- 2016-08-13 13:00:00 : 신동면   17751 ----------


 ---------- 2016-08-13 13:00:00 : 강남동   17752 ----------


 ---------- 2016-08-13 13:00:00 : 효자1동   17753 ----------


 ---------- 2016-08-13 14:00:00 : 석사동   17754 ----------


 ---------- 2016-08-13 14:00:00 : 동내면   17755 ----------


 ---------- 2016-08-13 15:00:00 : 남  면   17757 ----------


 ---------- 2016-08-13 15:00:00 : 신북읍   17758 ----------


 ---------- 2016-08-13 16:00:00 : 동내면   17759 ----------


 ---------- 2016-08-13 18:00:00 : 효자1동   17760 ----------


 ---------- 2016-08-13 18:00:00 : 남산면   17761 ----------


 ---------- 2016-08-13 19:00:00 : 동내면   17762 ----------


 ---------- 2016-08-14 04:00:00 : 서  면   17763 ----------


 ---------- 2016-08-14 05:00:00 : 강남동   17764 ----------


 ---------- 2016-08-14 09:00:00 : 동내면   17765 ----------


 ---------- 2016-08-14 10:00:00 : 동내면   17766 ----------


 ---------- 2016-08-14 13:00:00 : 신사우동   17767 ----------


 ---------- 2016-08-14 14:00:00 : 강남동   17768 ----------


 ---------- 2016-08-14 14:00:00 : 동산면   17769 ----------


 ---------- 2016-08-14 15:00:00 : 효자1동   17770 ----------


 ---------- 2016-08-14 16:00:00 : 효자1동   17771 ----------


 ---------- 2016-08-14 16:00:00 : 동산면   17772 ----------


 ---------- 2016-08-14 17:00:00 : 퇴계동   17773 ----------


 ---------- 2016-08-14 18:00:00 : 신북읍   17774 ----------


 ---------- 2016-08-14 22:00:00 : 강남동   17775 ----------


 ---------- 2016-08-15 01:00:00 : 강남동   17776 ----------


 ---------- 2016-08-15 09:00:00 : 석사동   17777 ----------


 ---------- 2016-08-15 09:00:00 : 동내면   17779 ----------


 ---------- 2016-08-15 11:00:00 : 동  면   17780 ----------


 ---------- 2016-08-15 11:00:00 : 퇴계동   17781 ----------


 ---------- 2016-08-15 12:00:00 : 신동면   17782 ----------

 ---------- 2016-08-15 12:00:00 : 사북면   17783 ----------


 ---------- 2016-08-15 14:00:00 : 강남동   17784 ----------


 ---------- 2016-08-15 14:00:00 : 동  면   17785 ----------


 ---------- 2016-08-15 15:00:00 : 신동면   17786 ----------


 ---------- 2016-08-15 15:00:00 : 동내면   17787 ----------


 ---------- 2016-08-15 15:00:00 : 동  면   17788 ----------


 ---------- 2016-08-15 16:00:00 : 서  면   17789 ----------


 ---------- 2016-08-15 17:00:00 : 효자1동   17790 ----------


 ---------- 2016-08-15 18:00:00 : 강남동   17791 ----------


 ---------- 2016-08-15 18:00:00 : 남산면   17792 ----------


 ---------- 2016-08-15 18:00:00 : 동  면   17794 ----------


 ---------- 2016-08-16 01:00:00 : 신사우동   17796 ----------


 ---------- 2016-08-16 07:00:00 : 신사우동   17797 ----------


 ---------- 2016-08-16 10:00:00 : 후평1동   17798 ----------


 ---------- 2016-08-16 11:00:00 : 석사동   17799 ----------


 ---------- 2016-08-16 12:00:00 : 석사동   17800 ----------


 ---------- 2016-08-16 12:00:00 : 효자1동   17801 ----------


 ---------- 2016-08-16 12:00:00 : 후평1동   17802 ----------


 ---------- 2016-08-16 13:00:00 : 사북면   17803 ----------


 ---------- 2016-08-16 13:00:00 : 소양동   17804 ----------


 ---------- 2016-08-16 16:00:00 : 석사동   17805 ----------


 ---------- 2016-08-16 16:00:00 : 퇴계동   17806 ----------


 ---------- 2016-08-16 17:00:00 : 석사동   17807 ----------


 ---------- 2016-08-16 18:00:00 : 사북면   17808 ----------


 ---------- 2016-08-17 07:00:00 : 효자1동   17809 ----------


 ---------- 2016-08-17 09:00:00 : 후평1동   17810 ----------


 ---------- 2016-08-17 10:00:00 : 동내면   17811 ----------


 ---------- 2016-08-17 11:00:00 : 석사동   17812 ----------


 ---------- 2016-08-17 11:00:00 : 서  면   17814 ----------


 ---------- 2016-08-17 11:00:00 : 남산면   17815 ----------


 ---------- 2016-08-17 13:00:00 : 후평1동   17816 ----------


 ---------- 2016-08-17 13:00:00 : 퇴계동   17817 ----------


 ---------- 2016-08-17 14:00:00 : 소양동   17818 ----------


 ---------- 2016-08-17 15:00:00 : 동  면   17819 ----------


 ---------- 2016-08-17 19:00:00 : 석사동   17820 ----------


 ---------- 2016-08-17 19:00:00 : 퇴계동   17821 ----------


 ---------- 2016-08-17 22:00:00 : 신사우동   17822 ----------


 ---------- 2016-08-17 23:00:00 : 서  면   17823 ----------


 ---------- 2016-08-18 09:00:00 : 남산면   17824 ----------


 ---------- 2016-08-18 09:00:00 : 소양동   17825 ----------


 ---------- 2016-08-18 09:00:00 : 퇴계동   17827 ----------


 ---------- 2016-08-18 09:00:00 : 교  동   17828 ----------


 ---------- 2016-08-18 10:00:00 : 퇴계동   17829 ----------


 ---------- 2016-08-18 11:00:00 : 효자1동   17830 ----------


 ---------- 2016-08-18 13:00:00 : 강남동   17831 ----------


 ---------- 2016-08-18 14:00:00 : 사북면   17832 ----------


 ---------- 2016-08-18 14:00:00 : 남산면   17833 ----------


 ---------- 2016-08-18 15:00:00 : 후평1동   17834 ----------


 ---------- 2016-08-18 17:00:00 : 근화동   17835 ----------


 ---------- 2016-08-18 18:00:00 : 퇴계동   17836 ----------


 ---------- 2016-08-18 18:00:00 : 동산면   17837 ----------


 ---------- 2016-08-18 22:00:00 : 후평1동   17838 ----------


 ---------- 2016-08-19 05:00:00 : 동내면   17839 ----------


 ---------- 2016-08-19 07:00:00 : 석사동   17840 ----------


 ---------- 2016-08-19 09:00:00 : 석사동   17841 ----------


 ---------- 2016-08-19 09:00:00 : 퇴계동   17842 ----------


 ---------- 2016-08-19 10:00:00 : 후평1동   17843 ----------


 ---------- 2016-08-19 12:00:00 : 강남동   17844 ----------


 ---------- 2016-08-19 12:00:00 : 동  면   17845 ----------


 ---------- 2016-08-19 13:00:00 : 석사동   17846 ----------


 ---------- 2016-08-19 15:00:00 : 석사동   17847 ----------


 ---------- 2016-08-19 15:00:00 : 서  면   17848 ----------


 ---------- 2016-08-19 15:00:00 : 동  면   17849 ----------


 ---------- 2016-08-19 16:00:00 : 석사동   17850 ----------


 ---------- 2016-08-19 17:00:00 : 효자1동   17851 ----------


 ---------- 2016-08-19 17:00:00 : 후평1동   17852 ----------


 ---------- 2016-08-20 01:00:00 : 후평1동   17853 ----------


 ---------- 2016-08-20 07:00:00 : 남산면   17854 ----------


 ---------- 2016-08-20 08:00:00 : 남산면   17855 ----------


 ---------- 2016-08-20 09:00:00 : 효자1동   17856 ----------


 ---------- 2016-08-20 10:00:00 : 강남동   17857 ----------


 ---------- 2016-08-20 11:00:00 : 효자1동   17858 ----------


 ---------- 2016-08-20 11:00:00 : 소양동   17859 ----------


 ---------- 2016-08-20 11:00:00 : 교  동   17860 ----------


 ---------- 2016-08-20 12:00:00 : 서  면   17861 ----------


 ---------- 2016-08-20 14:00:00 : 약사명동   17862 ----------


 ---------- 2016-08-20 16:00:00 : 강남동   17863 ----------


 ---------- 2016-08-20 18:00:00 : 근화동   17864 ----------


 ---------- 2016-08-20 22:00:00 : 동  면   17865 ----------


 ---------- 2016-08-21 04:00:00 : 신동면   17866 ----------


 ---------- 2016-08-21 07:00:00 : 남산면   17868 ----------


 ---------- 2016-08-21 10:00:00 : 퇴계동   17870 ----------


 ---------- 2016-08-21 14:00:00 : 후평1동   17871 ----------


 ---------- 2016-08-21 15:00:00 : 남산면   17872 ----------


 ---------- 2016-08-21 18:00:00 : 효자1동   17873 ----------


 ---------- 2016-08-21 19:00:00 : 남산면   17874 ----------


 ---------- 2016-08-22 08:00:00 : 소양동   17875 ----------


 ---------- 2016-08-22 09:00:00 : 동  면   17876 ----------


 ---------- 2016-08-22 10:00:00 : 강남동   17877 ----------


 ---------- 2016-08-22 10:00:00 : 서  면   17879 ----------


 ---------- 2016-08-22 10:00:00 : 동내면   17880 ----------


 ---------- 2016-08-22 10:00:00 : 효자1동   17883 ----------


 ---------- 2016-08-22 10:00:00 : 남산면   17884 ----------


 ---------- 2016-08-22 11:00:00 : 동내면   17885 ----------


 ---------- 2016-08-22 12:00:00 : 신북읍   17886 ----------


 ---------- 2016-08-22 13:00:00 : 석사동   17887 ----------


 ---------- 2016-08-22 13:00:00 : 강남동   17888 ----------


 ---------- 2016-08-22 14:00:00 : 동내면   17890 ----------


 ---------- 2016-08-22 14:00:00 : 후평1동   17891 ----------


 ---------- 2016-08-22 15:00:00 : 동내면   17892 ----------


 ---------- 2016-08-22 15:00:00 : 신북읍   17893 ----------


 ---------- 2016-08-22 18:00:00 : 소양동   17894 ----------


 ---------- 2016-08-22 19:00:00 : 신사우동   17895 ----------


 ---------- 2016-08-22 21:00:00 : 후평1동   17896 ----------


 ---------- 2016-08-23 03:00:00 : 효자1동   17897 ----------


 ---------- 2016-08-23 03:00:00 : 근화동   17898 ----------


 ---------- 2016-08-23 07:00:00 : 효자1동   17900 ----------


 ---------- 2016-08-23 10:00:00 : 동산면   17901 ----------


 ---------- 2016-08-23 11:00:00 : 후평1동   17902 ----------


 ---------- 2016-08-23 12:00:00 : 서  면   17903 ----------


 ---------- 2016-08-23 12:00:00 : 남  면   17904 ----------


 ---------- 2016-08-23 13:00:00 : 강남동   17905 ----------


 ---------- 2016-08-23 13:00:00 : 효자1동   17906 ----------


 ---------- 2016-08-23 14:00:00 : 남산면   17907 ----------


 ---------- 2016-08-23 14:00:00 : 동  면   17908 ----------


 ---------- 2016-08-23 16:00:00 : 서  면   17909 ----------


 ---------- 2016-08-23 17:00:00 : 남산면   17910 ----------


 ---------- 2016-08-23 17:00:00 : 신사우동   17911 ----------


 ---------- 2016-08-23 18:00:00 : 신동면   17912 ----------


 ---------- 2016-08-23 18:00:00 : 동  면   17913 ----------


 ---------- 2016-08-24 03:00:00 : 석사동   17914 ----------


 ---------- 2016-08-24 08:00:00 : 남산면   17915 ----------


 ---------- 2016-08-24 08:00:00 : 동  면   17916 ----------


 ---------- 2016-08-24 09:00:00 : 근화동   17917 ----------


 ---------- 2016-08-24 09:00:00 : 약사명동   17918 ----------


 ---------- 2016-08-24 09:00:00 : 후평1동   17919 ----------


 ---------- 2016-08-24 09:00:00 : 퇴계동   17920 ----------


 ---------- 2016-08-24 12:00:00 : 동  면   17922 ----------


 ---------- 2016-08-24 13:00:00 : 신동면   17923 ----------


 ---------- 2016-08-24 13:00:00 : 서  면   17924 ----------


 ---------- 2016-08-24 14:00:00 : 석사동   17925 ----------


 ---------- 2016-08-24 15:00:00 : 효자1동   17926 ----------


 ---------- 2016-08-24 15:00:00 : 남산면   17927 ----------


 ---------- 2016-08-24 15:00:00 : 소양동   17928 ----------


 ---------- 2016-08-24 15:00:00 : 동  면   17930 ----------


 ---------- 2016-08-24 16:00:00 : 신동면   17931 ----------

 ---------- 2016-08-25 04:00:00 : 근화동   17932 ----------


 ---------- 2016-08-25 07:00:00 : 효자1동   17933 ----------


 ---------- 2016-08-25 08:00:00 : 남산면   17934 ----------


 ---------- 2016-08-25 09:00:00 : 신동면   17935 ----------


 ---------- 2016-08-25 10:00:00 : 남산면   17936 ----------


 ---------- 2016-08-25 10:00:00 : 후평1동   17937 ----------


 ---------- 2016-08-25 11:00:00 : 효자1동   17938 ----------


 ---------- 2016-08-25 11:00:00 : 동  면   17939 ----------


 ---------- 2016-08-25 12:00:00 : 남산면   17940 ----------


 ---------- 2016-08-25 12:00:00 : 퇴계동   17941 ----------


 ---------- 2016-08-25 13:00:00 : 동  면   17942 ----------


 ---------- 2016-08-25 14:00:00 : 동  면   17943 ----------


 ---------- 2016-08-25 14:00:00 : 후평1동   17944 ----------


 ---------- 2016-08-25 14:00:00 : 북산면   17945 ----------


 ---------- 2016-08-25 18:00:00 : 석사동   17946 ----------


 ---------- 2016-08-26 00:00:00 : 후평1동   17947 ----------


 ---------- 2016-08-26 09:00:00 : 동내면   17948 ----------


 ---------- 2016-08-26 10:00:00 : 후평1동   17949 ----------


 ---------- 2016-08-26 13:00:00 : 후평1동   17950 ----------


 ---------- 2016-08-26 14:00:00 : 강남동   17951 ----------


 ---------- 2016-08-26 14:00:00 : 퇴계동   17952 ----------


 ---------- 2016-08-26 16:00:00 : 동산면   17953 ----------


 ---------- 2016-08-26 18:00:00 : 소양동   17954 ----------


 ---------- 2016-08-26 18:00:00 : 후평1동   17955 ----------


 ---------- 2016-08-26 23:00:00 : 효자1동   17956 ----------


 ---------- 2016-08-27 00:00:00 : 후평1동   17957 ----------


 ---------- 2016-08-27 04:00:00 : 효자1동   17958 ----------


 ---------- 2016-08-27 09:00:00 : 강남동   17959 ----------


 ---------- 2016-08-27 11:00:00 : 신동면   17960 ----------


 ---------- 2016-08-27 11:00:00 : 서  면   17961 ----------


 ---------- 2016-08-27 11:00:00 : 퇴계동   17962 ----------


 ---------- 2016-08-27 14:00:00 : 신동면   17963 ----------


 ---------- 2016-08-27 17:00:00 : 서  면   17964 ----------


 ---------- 2016-08-27 18:00:00 : 석사동   17965 ----------


 ---------- 2016-08-27 19:00:00 : 신사우동   17966 ----------


 ---------- 2016-08-27 21:00:00 : 신사우동   17967 ----------


 ---------- 2016-08-28 09:00:00 : 동  면   17968 ----------


 ---------- 2016-08-28 09:00:00 : 후평1동   17969 ----------


 ---------- 2016-08-28 13:00:00 : 신동면   17970 ----------


 ---------- 2016-08-28 15:00:00 : 강남동   17971 ----------


 ---------- 2016-08-28 16:00:00 : 동  면   17972 ----------


 ---------- 2016-08-28 18:00:00 : 조운동   17973 ----------


 ---------- 2016-08-29 00:00:00 : 소양동   17974 ----------


 ---------- 2016-08-29 00:00:00 : 후평1동   17975 ----------


 ---------- 2016-08-29 03:00:00 : 효자1동   17976 ----------


 ---------- 2016-08-29 09:00:00 : 강남동   17977 ----------


 ---------- 2016-08-29 09:00:00 : 동내면   17978 ----------


 ---------- 2016-08-29 10:00:00 : 동  면   17979 ----------


 ---------- 2016-08-29 11:00:00 : 석사동   17980 ----------


 ---------- 2016-08-29 12:00:00 : 서  면   17981 ----------


 ---------- 2016-08-29 12:00:00 : 퇴계동   17982 ----------


 ---------- 2016-08-29 14:00:00 : 효자1동   17983 ----------


 ---------- 2016-08-29 14:00:00 : 동산면   17984 ----------


 ---------- 2016-08-29 16:00:00 : 동  면   17985 ----------


 ---------- 2016-08-29 23:00:00 : 조운동   17986 ----------


 ---------- 2016-08-30 07:00:00 : 동  면   17987 ----------


 ---------- 2016-08-30 08:00:00 : 석사동   17988 ----------


 ---------- 2016-08-30 09:00:00 : 서  면   17989 ----------


 ---------- 2016-08-30 10:00:00 : 남산면   17990 ----------


 ---------- 2016-08-30 12:00:00 : 후평1동   17991 ----------


 ---------- 2016-08-30 14:00:00 : 신동면   17992 ----------


 ---------- 2016-08-30 14:00:00 : 남산면   17993 ----------


 ---------- 2016-08-30 14:00:00 : 동산면   17994 ----------


 ---------- 2016-08-30 14:00:00 : 교  동   17995 ----------


 ---------- 2016-08-30 16:00:00 : 동  면   17996 ----------


 ---------- 2016-08-30 17:00:00 : 교  동   17997 ----------


 ---------- 2016-08-30 21:00:00 : 소양동   17998 ----------


 ---------- 2016-08-31 03:00:00 : 후평1동   17999 ----------


 ---------- 2016-08-31 03:00:00 : 퇴계동   18000 ----------


 ---------- 2016-08-31 04:00:00 : 남산면   18001 ----------


 ---------- 2016-08-31 08:00:00 : 효자1동   18002 ----------


 ---------- 2016-08-31 09:00:00 : 남  면   18003 ----------


 ---------- 2016-08-31 12:00:00 : 신북읍   18004 ----------


 ---------- 2016-08-31 14:00:00 : 퇴계동   18005 ----------


 ---------- 2016-08-31 15:00:00 : 동내면   18006 ----------


 ---------- 2016-08-31 21:00:00 : 석사동   18007 ----------


 ---------- 2016-09-01 00:00:00 : 퇴계동   18009 ----------


 ---------- 2016-09-01 02:00:00 : 석사동   18010 ----------


 ---------- 2016-09-01 08:00:00 : 서  면   18011 ----------


 ---------- 2016-09-01 08:00:00 : 사북면   18012 ----------


 ---------- 2016-09-01 10:00:00 : 동  면   18013 ----------


 ---------- 2016-09-01 13:00:00 : 동  면   18014 ----------


 ---------- 2016-09-01 13:00:00 : 퇴계동   18015 ----------


 ---------- 2016-09-01 15:00:00 : 동내면   18017 ----------


 ---------- 2016-09-01 15:00:00 : 동  면   18018 ----------


 ---------- 2016-09-01 15:00:00 : 후평1동   18019 ----------


 ---------- 2016-09-01 16:00:00 : 효자1동   18020 ----------


 ---------- 2016-09-01 22:00:00 : 석사동   18021 ----------


 ---------- 2016-09-02 08:00:00 : 후평1동   18022 ----------


 ---------- 2016-09-02 09:00:00 : 신동면   18023 ----------


 ---------- 2016-09-02 09:00:00 : 효자1동   18024 ----------


 ---------- 2016-09-02 09:00:00 : 신북읍   18026 ----------


 ---------- 2016-09-02 10:00:00 : 신동면   18027 ----------


 ---------- 2016-09-02 10:00:00 : 서  면   18028 ----------


 ---------- 2016-09-02 10:00:00 : 동  면   18029 ----------


 ---------- 2016-09-02 10:00:00 : 북산면   18030 ----------


 ---------- 2016-09-02 11:00:00 : 서  면   18031 ----------


 ---------- 2016-09-02 11:00:00 : 효자1동   18032 ----------


 ---------- 2016-09-02 12:00:00 : 신북읍   18033 ----------


 ---------- 2016-09-02 15:00:00 : 효자1동   18034 ----------


 ---------- 2016-09-02 16:00:00 : 동내면   18035 ----------


 ---------- 2016-09-02 16:00:00 : 교  동   18036 ----------


 ---------- 2016-09-02 17:00:00 : 신북읍   18037 ----------


 ---------- 2016-09-02 18:00:00 : 강남동   18038 ----------


 ---------- 2016-09-02 18:00:00 : 신사우동   18039 ----------


 ---------- 2016-09-02 21:00:00 : 근화동   18040 ----------


 ---------- 2016-09-02 21:00:00 : 후평1동   18041 ----------


 ---------- 2016-09-03 08:00:00 : 동내면   18042 ----------


 ---------- 2016-09-03 09:00:00 : 서  면   18043 ----------


 ---------- 2016-09-03 10:00:00 : 신동면   18045 ----------


 ---------- 2016-09-03 11:00:00 : 남산면   18047 ----------


 ---------- 2016-09-03 13:00:00 : 동내면   18048 ----------


 ---------- 2016-09-03 14:00:00 : 남산면   18049 ----------


 ---------- 2016-09-03 15:00:00 : 효자1동   18052 ----------


 ---------- 2016-09-03 16:00:00 : 강남동   18053 ----------


 ---------- 2016-09-03 17:00:00 : 퇴계동   18054 ----------


 ---------- 2016-09-03 21:00:00 : 퇴계동   18055 ----------


 ---------- 2016-09-04 01:00:00 : 퇴계동   18056 ----------


 ---------- 2016-09-04 08:00:00 : 신사우동   18057 ----------


 ---------- 2016-09-04 09:00:00 : 퇴계동   18058 ----------


 ---------- 2016-09-04 11:00:00 : 신북읍   18059 ----------


 ---------- 2016-09-04 14:00:00 : 효자1동   18060 ----------


 ---------- 2016-09-04 15:00:00 : 신사우동   18061 ----------


 ---------- 2016-09-04 15:00:00 : 북산면   18062 ----------


 ---------- 2016-09-04 16:00:00 : 신동면   18063 ----------


 ---------- 2016-09-04 18:00:00 : 퇴계동   18064 ----------


 ---------- 2016-09-04 19:00:00 : 북산면   18065 ----------


 ---------- 2016-09-05 08:00:00 : 동내면   18067 ----------


 ---------- 2016-09-05 09:00:00 : 강남동   18068 ----------


 ---------- 2016-09-05 09:00:00 : 퇴계동   18069 ----------


 ---------- 2016-09-05 10:00:00 : 사북면   18070 ----------


 ---------- 2016-09-05 12:00:00 : 강남동   18071 ----------


 ---------- 2016-09-05 13:00:00 : 서  면   18072 ----------


 ---------- 2016-09-05 13:00:00 : 후평1동   18073 ----------


 ---------- 2016-09-05 14:00:00 : 동  면   18074 ----------


 ---------- 2016-09-05 14:00:00 : 교  동   18075 ----------

 ---------- 2016-09-05 16:00:00 : 신동면   18077 ----------


 ---------- 2016-09-05 16:00:00 : 동내면   18078 ----------


 ---------- 2016-09-05 16:00:00 : 후평1동   18079 ----------


 ---------- 2016-09-05 18:00:00 : 효자1동   18080 ----------


 ---------- 2016-09-05 19:00:00 : 동  면   18081 ----------


 ---------- 2016-09-05 21:00:00 : 남산면   18083 ----------


 ---------- 2016-09-06 09:00:00 : 신동면   18084 ----------


 ---------- 2016-09-06 11:00:00 : 동  면   18085 ----------


 ---------- 2016-09-06 13:00:00 : 남산면   18086 ----------


 ---------- 2016-09-06 17:00:00 : 후평1동   18087 ----------


 ---------- 2016-09-06 18:00:00 : 동  면   18088 ----------


 ---------- 2016-09-07 00:00:00 : 서  면   18089 ----------


 ---------- 2016-09-07 06:00:00 : 후평1동   18090 ----------


 ---------- 2016-09-07 10:00:00 : 동내면   18091 ----------


 ---------- 2016-09-07 11:00:00 : 신동면   18092 ----------


 ---------- 2016-09-07 13:00:00 : 후평1동   18093 ----------


 ---------- 2016-09-07 14:00:00 : 동  면   18094 ----------


 ---------- 2016-09-07 15:00:00 : 석사동   18095 ----------


 ---------- 2016-09-07 15:00:00 : 동내면   18096 ----------


 ---------- 2016-09-07 16:00:00 : 강남동   18097 ----------


 ---------- 2016-09-07 16:00:00 : 동내면   18098 ----------


 ---------- 2016-09-07 16:00:00 : 효자1동   18100 ----------


 ---------- 2016-09-07 17:00:00 : 동내면   18101 ----------


 ---------- 2016-09-07 19:00:00 : 근화동   18102 ----------


 ---------- 2016-09-08 09:00:00 : 동산면   18103 ----------


 ---------- 2016-09-08 10:00:00 : 석사동   18104 ----------


 ---------- 2016-09-08 11:00:00 : 동  면   18105 ----------


 ---------- 2016-09-08 13:00:00 : 신동면   18106 ----------


 ---------- 2016-09-08 13:00:00 : 퇴계동   18107 ----------


 ---------- 2016-09-08 15:00:00 : 서  면   18108 ----------


 ---------- 2016-09-08 16:00:00 : 신동면   18109 ----------


 ---------- 2016-09-08 17:00:00 : 서  면   18111 ----------


 ---------- 2016-09-08 22:00:00 : 효자1동   18112 ----------


 ---------- 2016-09-09 01:00:00 : 후평1동   18113 ----------


 ---------- 2016-09-09 08:00:00 : 강남동   18114 ----------


 ---------- 2016-09-09 10:00:00 : 동내면   18115 ----------


 ---------- 2016-09-09 12:00:00 : 후평1동   18116 ----------


 ---------- 2016-09-09 13:00:00 : 석사동   18117 ----------


 ---------- 2016-09-09 13:00:00 : 후평1동   18118 ----------


 ---------- 2016-09-09 14:00:00 : 남산면   18119 ----------


 ---------- 2016-09-09 14:00:00 : 신북읍   18120 ----------


 ---------- 2016-09-09 14:00:00 : 후평1동   18121 ----------


 ---------- 2016-09-09 15:00:00 : 동  면   18122 ----------


 ---------- 2016-09-09 16:00:00 : 동내면   18123 ----------


 ---------- 2016-09-09 16:00:00 : 동  면   18124 ----------


 ---------- 2016-09-09 17:00:00 : 서  면   18125 ----------


 ---------- 2016-09-09 21:00:00 : 퇴계동   18126 ----------


 ---------- 2016-09-10 08:00:00 : 신북읍   18127 ----------


 ---------- 2016-09-10 08:00:00 : 퇴계동   18128 ----------


 ---------- 2016-09-10 09:00:00 : 남  면   18129 ----------


 ---------- 2016-09-10 10:00:00 : 효자1동   18130 ----------


 ---------- 2016-09-10 10:00:00 : 동산면   18131 ----------


 ---------- 2016-09-10 11:00:00 : 남산면   18133 ----------


 ---------- 2016-09-10 12:00:00 : 동산면   18135 ----------


 ---------- 2016-09-10 13:00:00 : 퇴계동   18136 ----------


 ---------- 2016-09-10 15:00:00 : 석사동   18137 ----------


 ---------- 2016-09-10 18:00:00 : 효자1동   18138 ----------


 ---------- 2016-09-10 22:00:00 : 강남동   18139 ----------


 ---------- 2016-09-11 06:00:00 : 효자1동   18140 ----------


 ---------- 2016-09-11 10:00:00 : 신사우동   18141 ----------


 ---------- 2016-09-11 14:00:00 : 서  면   18142 ----------


 ---------- 2016-09-11 15:00:00 : 후평1동   18143 ----------


 ---------- 2016-09-11 15:00:00 : 퇴계동   18144 ----------


 ---------- 2016-09-11 16:00:00 : 서  면   18145 ----------


 ---------- 2016-09-11 16:00:00 : 동  면   18146 ----------


 ---------- 2016-09-12 12:00:00 : 신북읍   18147 ----------


 ---------- 2016-09-12 14:00:00 : 신사우동   18148 ----------


 ---------- 2016-09-12 15:00:00 : 동  면   18149 ----------


 ---------- 2016-09-12 16:00:00 : 후평1동   18150 ----------


 ---------- 2016-09-12 19:00:00 : 신사우동   18151 ----------


 ---------- 2016-09-12 20:00:00 : 소양동   18153 ----------


 ---------- 2016-09-12 23:00:00 : 동  면   18154 ----------


 ---------- 2016-09-13 01:00:00 : 동  면   18155 ----------


 ---------- 2016-09-13 02:00:00 : 후평1동   18156 ----------


 ---------- 2016-09-13 02:00:00 : 교  동   18157 ----------


 ---------- 2016-09-13 04:00:00 : 효자1동   18158 ----------


 ---------- 2016-09-13 10:00:00 : 서  면   18160 ----------


 ---------- 2016-09-13 11:00:00 : 퇴계동   18161 ----------


 ---------- 2016-09-13 13:00:00 : 소양동   18163 ----------


 ---------- 2016-09-13 14:00:00 : 교  동   18164 ----------


 ---------- 2016-09-13 15:00:00 : 퇴계동   18166 ----------


 ---------- 2016-09-13 16:00:00 : 사북면   18167 ----------


 ---------- 2016-09-13 18:00:00 : 석사동   18168 ----------


 ---------- 2016-09-13 22:00:00 : 효자1동   18169 ----------


 ---------- 2016-09-14 01:00:00 : 소양동   18170 ----------


 ---------- 2016-09-14 03:00:00 : 후평1동   18171 ----------


 ---------- 2016-09-14 09:00:00 : 남산면   18172 ----------


 ---------- 2016-09-14 09:00:00 : 후평1동   18173 ----------


 ---------- 2016-09-14 11:00:00 : 약사명동   18174 ----------


 ---------- 2016-09-14 12:00:00 : 남산면   18175 ----------


 ---------- 2016-09-14 12:00:00 : 근화동   18176 ----------


 ---------- 2016-09-14 13:00:00 : 효자1동   18177 ----------


 ---------- 2016-09-14 13:00:00 : 소양동   18178 ----------


 ---------- 2016-09-14 15:00:00 : 조운동   18179 ----------


 ---------- 2016-09-14 16:00:00 : 석사동   18180 ----------


 ---------- 2016-09-14 16:00:00 : 교  동   18181 ----------


 ---------- 2016-09-14 17:00:00 : 신북읍   18182 ----------


 ---------- 2016-09-14 17:00:00 : 동산면   18184 ----------


 ---------- 2016-09-14 18:00:00 : 북산면   18185 ----------


 ---------- 2016-09-14 22:00:00 : 동  면   18188 ----------


 ---------- 2016-09-15 07:00:00 : 석사동   18189 ----------


 ---------- 2016-09-15 08:00:00 : 퇴계동   18190 ----------


 ---------- 2016-09-15 09:00:00 : 신북읍   18191 ----------


 ---------- 2016-09-15 09:00:00 : 후평1동   18192 ----------


 ---------- 2016-09-15 10:00:00 : 신사우동   18193 ----------


 ---------- 2016-09-15 11:00:00 : 근화동   18194 ----------


 ---------- 2016-09-15 12:00:00 : 신동면   18195 ----------


 ---------- 2016-09-15 12:00:00 : 남  면   18198 ----------


 ---------- 2016-09-15 13:00:00 : 신동면   18199 ----------


 ---------- 2016-09-15 13:00:00 : 사북면   18200 ----------


 ---------- 2016-09-15 14:00:00 : 근화동   18201 ----------


 ---------- 2016-09-15 18:00:00 : 약사명동   18202 ----------


 ---------- 2016-09-15 19:00:00 : 효자1동   18203 ----------


 ---------- 2016-09-15 22:00:00 : 효자1동   18204 ----------


 ---------- 2016-09-16 05:00:00 : 북산면   18205 ----------


 ---------- 2016-09-16 09:00:00 : 후평1동   18206 ----------


 ---------- 2016-09-16 10:00:00 : 석사동   18207 ----------


 ---------- 2016-09-16 11:00:00 : 남  면   18208 ----------


 ---------- 2016-09-16 12:00:00 : 사북면   18209 ----------


 ---------- 2016-09-16 12:00:00 : 효자1동   18210 ----------


 ---------- 2016-09-16 13:00:00 : 신사우동   18211 ----------


 ---------- 2016-09-16 15:00:00 : 후평1동   18212 ----------


 ---------- 2016-09-16 16:00:00 : 약사명동   18214 ----------


 ---------- 2016-09-16 17:00:00 : 신사우동   18215 ----------


 ---------- 2016-09-16 21:00:00 : 교  동   18216 ----------


 ---------- 2016-09-17 01:00:00 : 강남동   18217 ----------


 ---------- 2016-09-17 13:00:00 : 서  면   18218 ----------


 ---------- 2016-09-17 14:00:00 : 신동면   18219 ----------


 ---------- 2016-09-17 15:00:00 : 사북면   18220 ----------


 ---------- 2016-09-17 15:00:00 : 신북읍   18221 ----------


 ---------- 2016-09-17 16:00:00 : 신북읍   18222 ----------


 ---------- 2016-09-17 20:00:00 : 신사우동   18223 ----------


 ---------- 2016-09-18 04:00:00 : 퇴계동   18224 ----------


 ---------- 2016-09-18 08:00:00 : 동  면   18225 ----------


 ---------- 2016-09-18 13:00:00 : 퇴계동   18227 ----------


 ---------- 2016-09-18 17:00:00 : 효자1동   18228 ----------

 ---------- 2016-09-19 00:00:00 : 효자1동   18229 ----------


 ---------- 2016-09-19 10:00:00 : 후평1동   18230 ----------


 ---------- 2016-09-19 11:00:00 : 근화동   18231 ----------


 ---------- 2016-09-19 13:00:00 : 동내면   18232 ----------


 ---------- 2016-09-19 14:00:00 : 사북면   18233 ----------


 ---------- 2016-09-19 14:00:00 : 남산면   18234 ----------


 ---------- 2016-09-19 16:00:00 : 서  면   18235 ----------


 ---------- 2016-09-19 16:00:00 : 남산면   18236 ----------


 ---------- 2016-09-19 16:00:00 : 동  면   18237 ----------


 ---------- 2016-09-19 17:00:00 : 남산면   18238 ----------


 ---------- 2016-09-19 21:00:00 : 소양동   18239 ----------


 ---------- 2016-09-20 06:00:00 : 후평1동   18240 ----------


 ---------- 2016-09-20 08:00:00 : 퇴계동   18241 ----------


 ---------- 2016-09-20 09:00:00 : 남산면   18242 ----------


 ---------- 2016-09-20 10:00:00 : 신사우동   18243 ----------


 ---------- 2016-09-20 10:00:00 : 소양동   18244 ----------


 ---------- 2016-09-20 12:00:00 : 동산면   18245 ----------


 ---------- 2016-09-20 13:00:00 : 석사동   18246 ----------


 ---------- 2016-09-20 13:00:00 : 사북면   18247 ----------


 ---------- 2016-09-20 14:00:00 : 신사우동   18248 ----------


 ---------- 2016-09-20 17:00:00 : 퇴계동   18249 ----------


 ---------- 2016-09-20 18:00:00 : 석사동   18250 ----------


 ---------- 2016-09-20 18:00:00 : 남산면   18251 ----------


 ---------- 2016-09-20 23:00:00 : 석사동   18252 ----------


 ---------- 2016-09-21 04:00:00 : 남  면   18256 ----------


 ---------- 2016-09-21 08:00:00 : 석사동   18257 ----------


 ---------- 2016-09-21 10:00:00 : 남산면   18258 ----------


 ---------- 2016-09-21 11:00:00 : 근화동   18259 ----------


 ---------- 2016-09-21 13:00:00 : 효자1동   18260 ----------


 ---------- 2016-09-21 13:00:00 : 근화동   18261 ----------


 ---------- 2016-09-21 14:00:00 : 사북면   18263 ----------


 ---------- 2016-09-21 15:00:00 : 퇴계동   18264 ----------


 ---------- 2016-09-21 16:00:00 : 동  면   18265 ----------


 ---------- 2016-09-21 16:00:00 : 퇴계동   18266 ----------


 ---------- 2016-09-22 06:00:00 : 신사우동   18267 ----------


 ---------- 2016-09-22 08:00:00 : 서  면   18268 ----------


 ---------- 2016-09-22 09:00:00 : 서  면   18269 ----------


 ---------- 2016-09-22 10:00:00 : 효자1동   18270 ----------


 ---------- 2016-09-22 10:00:00 : 동  면   18271 ----------


 ---------- 2016-09-22 10:00:00 : 동산면   18272 ----------


 ---------- 2016-09-22 12:00:00 : 북산면   18275 ----------


 ---------- 2016-09-22 13:00:00 : 사북면   18276 ----------


 ---------- 2016-09-22 14:00:00 : 동내면   18277 ----------


 ---------- 2016-09-22 14:00:00 : 동산면   18279 ----------


 ---------- 2016-09-22 15:00:00 : 신북읍   18280 ----------


 ---------- 2016-09-22 16:00:00 : 동  면   18281 ----------


 ---------- 2016-09-22 16:00:00 : 후평1동   18282 ----------


 ---------- 2016-09-22 22:00:00 : 퇴계동   18283 ----------


 ---------- 2016-09-23 04:00:00 : 남산면   18284 ----------


 ---------- 2016-09-23 06:00:00 : 동산면   18285 ----------


 ---------- 2016-09-23 07:00:00 : 퇴계동   18286 ----------


 ---------- 2016-09-23 10:00:00 : 사북면   18287 ----------


 ---------- 2016-09-23 11:00:00 : 신사우동   18289 ----------


 ---------- 2016-09-23 12:00:00 : 남산면   18290 ----------


 ---------- 2016-09-23 14:00:00 : 동  면   18291 ----------


 ---------- 2016-09-23 15:00:00 : 석사동   18292 ----------


 ---------- 2016-09-23 18:00:00 : 석사동   18295 ----------


 ---------- 2016-09-23 21:00:00 : 후평1동   18296 ----------


 ---------- 2016-09-23 23:00:00 : 조운동   18297 ----------


 ---------- 2016-09-24 10:00:00 : 강남동   18298 ----------


 ---------- 2016-09-24 10:00:00 : 동내면   18299 ----------


 ---------- 2016-09-24 15:00:00 : 서  면   18300 ----------


 ---------- 2016-09-24 17:00:00 : 동산면   18301 ----------


 ---------- 2016-09-25 02:00:00 : 남산면   18302 ----------


 ---------- 2016-09-25 07:00:00 : 서  면   18304 ----------


 ---------- 2016-09-25 10:00:00 : 사북면   18307 ----------


 ---------- 2016-09-25 13:00:00 : 동내면   18308 ----------


 ---------- 2016-09-25 15:00:00 : 신동면   18309 ----------


 ---------- 2016-09-25 16:00:00 : 동내면   18310 ----------


 ---------- 2016-09-25 16:00:00 : 효자1동   18311 ----------


 ---------- 2016-09-25 17:00:00 : 강남동   18312 ----------


 ---------- 2016-09-25 17:00:00 : 남산면   18313 ----------


 ---------- 2016-09-25 19:00:00 : 사북면   18315 ----------


 ---------- 2016-09-25 22:00:00 : 후평1동   18316 ----------


 ---------- 2016-09-26 09:00:00 : 효자1동   18317 ----------


 ---------- 2016-09-26 10:00:00 : 강남동   18318 ----------


 ---------- 2016-09-26 11:00:00 : 동내면   18319 ----------


 ---------- 2016-09-26 14:00:00 : 약사명동   18320 ----------


 ---------- 2016-09-26 14:00:00 : 퇴계동   18321 ----------


 ---------- 2016-09-26 15:00:00 : 동  면   18322 ----------


 ---------- 2016-09-26 16:00:00 : 석사동   18323 ----------


 ---------- 2016-09-26 16:00:00 : 동  면   18324 ----------


 ---------- 2016-09-26 17:00:00 : 신북읍   18326 ----------


 ---------- 2016-09-26 23:00:00 : 석사동   18327 ----------


 ---------- 2016-09-27 03:00:00 : 석사동   18328 ----------


 ---------- 2016-09-27 09:00:00 : 강남동   18329 ----------


 ---------- 2016-09-27 10:00:00 : 근화동   18330 ----------


 ---------- 2016-09-27 13:00:00 : 서  면   18331 ----------


 ---------- 2016-09-27 14:00:00 : 서  면   18333 ----------


 ---------- 2016-09-28 04:00:00 : 석사동   18334 ----------


 ---------- 2016-09-28 07:00:00 : 효자1동   18335 ----------


 ---------- 2016-09-28 07:00:00 : 후평1동   18336 ----------


 ---------- 2016-09-28 09:00:00 : 남산면   18337 ----------


 ---------- 2016-09-28 11:00:00 : 북산면   18338 ----------


 ---------- 2016-09-28 16:00:00 : 신동면   18339 ----------


 ---------- 2016-09-28 16:00:00 : 효자1동   18340 ----------


 ---------- 2016-09-28 17:00:00 : 석사동   18341 ----------


 ---------- 2016-09-28 17:00:00 : 동내면   18342 ----------


 ---------- 2016-09-29 03:00:00 : 후평1동   18343 ----------


 ---------- 2016-09-29 09:00:00 : 신북읍   18344 ----------


 ---------- 2016-09-29 09:00:00 : 동  면   18345 ----------


 ---------- 2016-09-29 10:00:00 : 동내면   18346 ----------


 ---------- 2016-09-29 13:00:00 : 신동면   18347 ----------


 ---------- 2016-09-29 15:00:00 : 석사동   18349 ----------


 ---------- 2016-09-29 16:00:00 : 석사동   18350 ----------


 ---------- 2016-09-30 01:00:00 : 신북읍   18351 ----------


 ---------- 2016-09-30 09:00:00 : 남산면   18352 ----------


 ---------- 2016-09-30 13:00:00 : 동  면   18353 ----------


 ---------- 2016-09-30 14:00:00 : 퇴계동   18354 ----------


 ---------- 2016-09-30 16:00:00 : 후평1동   18355 ----------


 ---------- 2016-09-30 19:00:00 : 강남동   18356 ----------


 ---------- 2016-10-01 00:00:00 : 근화동   18357 ----------


 ---------- 2016-10-01 06:00:00 : 동  면   18358 ----------


 ---------- 2016-10-01 07:00:00 : 신사우동   18359 ----------


 ---------- 2016-10-01 08:00:00 : 남  면   18360 ----------


 ---------- 2016-10-01 09:00:00 : 동내면   18361 ----------


 ---------- 2016-10-01 09:00:00 : 신북읍   18362 ----------


 ---------- 2016-10-01 10:00:00 : 동  면   18364 ----------


 ---------- 2016-10-01 12:00:00 : 소양동   18365 ----------


 ---------- 2016-10-01 12:00:00 : 동  면   18366 ----------


 ---------- 2016-10-01 16:00:00 : 남  면   18367 ----------


 ---------- 2016-10-02 00:00:00 : 후평1동   18368 ----------


 ---------- 2016-10-02 00:00:00 : 조운동   18369 ----------


 ---------- 2016-10-02 01:00:00 : 사북면   18370 ----------


 ---------- 2016-10-02 09:00:00 : 동내면   18371 ----------


 ---------- 2016-10-02 10:00:00 : 신사우동   18372 ----------


 ---------- 2016-10-02 16:00:00 : 근화동   18373 ----------


 ---------- 2016-10-02 19:00:00 : 강남동   18374 ----------


 ---------- 2016-10-03 03:00:00 : 퇴계동   18375 ----------


 ---------- 2016-10-03 13:00:00 : 서  면   18376 ----------


 ---------- 2016-10-03 14:00:00 : 남산면   18377 ----------


 ---------- 2016-10-03 17:00:00 : 남산면   18378 ----------


 ---------- 2016-10-03 19:00:00 : 후평1동   18379 ----------


 ---------- 2016-10-04 08:00:00 : 신사우동   18380 ----------


 ---------- 2016-10-04 09:00:00 : 남산면   18381 ----------


 ---------- 2016-10-04 11:00:00 : 후평1동   18382 ----------

 ---------- 2016-10-04 12:00:00 : 남산면   18383 ----------


 ---------- 2016-10-04 13:00:00 : 신동면   18384 ----------


 ---------- 2016-10-04 13:00:00 : 조운동   18385 ----------


 ---------- 2016-10-04 14:00:00 : 석사동   18386 ----------


 ---------- 2016-10-04 14:00:00 : 신북읍   18387 ----------


 ---------- 2016-10-04 18:00:00 : 신동면   18388 ----------


 ---------- 2016-10-05 01:00:00 : 효자1동   18389 ----------


 ---------- 2016-10-05 09:00:00 : 신사우동   18390 ----------


 ---------- 2016-10-05 10:00:00 : 퇴계동   18391 ----------


 ---------- 2016-10-05 11:00:00 : 서  면   18392 ----------


 ---------- 2016-10-05 12:00:00 : 효자1동   18393 ----------


 ---------- 2016-10-05 12:00:00 : 후평1동   18394 ----------


 ---------- 2016-10-05 16:00:00 : 동내면   18395 ----------


 ---------- 2016-10-06 02:00:00 : 석사동   18396 ----------


 ---------- 2016-10-06 02:00:00 : 근화동   18397 ----------


 ---------- 2016-10-06 10:00:00 : 강남동   18398 ----------


 ---------- 2016-10-06 13:00:00 : 효자1동   18399 ----------


 ---------- 2016-10-06 16:00:00 : 서  면   18400 ----------


 ---------- 2016-10-06 17:00:00 : 효자1동   18401 ----------


 ---------- 2016-10-06 19:00:00 : 후평1동   18402 ----------


 ---------- 2016-10-07 00:00:00 : 신사우동   18403 ----------


 ---------- 2016-10-07 02:00:00 : 석사동   18404 ----------


 ---------- 2016-10-07 07:00:00 : 남산면   18405 ----------


 ---------- 2016-10-07 08:00:00 : 남  면   18406 ----------


 ---------- 2016-10-07 08:00:00 : 동내면   18407 ----------


 ---------- 2016-10-07 08:00:00 : 남산면   18408 ----------


 ---------- 2016-10-07 11:00:00 : 신사우동   18409 ----------


 ---------- 2016-10-07 13:00:00 : 서  면   18410 ----------


 ---------- 2016-10-07 13:00:00 : 근화동   18411 ----------


 ---------- 2016-10-07 14:00:00 : 신북읍   18412 ----------


 ---------- 2016-10-07 16:00:00 : 강남동   18413 ----------


 ---------- 2016-10-07 17:00:00 : 퇴계동   18414 ----------


 ---------- 2016-10-08 06:00:00 : 남  면   18415 ----------


 ---------- 2016-10-08 08:00:00 : 효자1동   18416 ----------


 ---------- 2016-10-08 17:00:00 : 석사동   18417 ----------


 ---------- 2016-10-08 19:00:00 : 북산면   18419 ----------


 ---------- 2016-10-08 21:00:00 : 동내면   18420 ----------


 ---------- 2016-10-08 22:00:00 : 퇴계동   18421 ----------


 ---------- 2016-10-09 07:00:00 : 효자1동   18422 ----------


 ---------- 2016-10-09 09:00:00 : 신동면   18423 ----------


 ---------- 2016-10-09 11:00:00 : 동  면   18424 ----------


 ---------- 2016-10-09 13:00:00 : 사북면   18425 ----------


 ---------- 2016-10-09 13:00:00 : 효자1동   18426 ----------


 ---------- 2016-10-09 15:00:00 : 동내면   18428 ----------


 ---------- 2016-10-09 16:00:00 : 사북면   18429 ----------


 ---------- 2016-10-09 17:00:00 : 동내면   18430 ----------


 ---------- 2016-10-09 21:00:00 : 동  면   18431 ----------


 ---------- 2016-10-10 03:00:00 : 신사우동   18432 ----------


 ---------- 2016-10-10 07:00:00 : 효자1동   18433 ----------


 ---------- 2016-10-10 08:00:00 : 남산면   18434 ----------


 ---------- 2016-10-10 09:00:00 : 남산면   18435 ----------


 ---------- 2016-10-10 09:00:00 : 동  면   18436 ----------


 ---------- 2016-10-10 10:00:00 : 동  면   18437 ----------


 ---------- 2016-10-10 11:00:00 : 북산면   18438 ----------


 ---------- 2016-10-10 17:00:00 : 동내면   18439 ----------


 ---------- 2016-10-10 20:00:00 : 후평1동   18440 ----------


 ---------- 2016-10-11 13:00:00 : 신사우동   18441 ----------


 ---------- 2016-10-11 16:00:00 : 신북읍   18442 ----------


 ---------- 2016-10-11 17:00:00 : 후평1동   18443 ----------


 ---------- 2016-10-11 18:00:00 : 강남동   18444 ----------


 ---------- 2016-10-11 19:00:00 : 동  면   18446 ----------


 ---------- 2016-10-12 09:00:00 : 효자1동   18448 ----------


 ---------- 2016-10-12 10:00:00 : 신북읍   18449 ----------


 ---------- 2016-10-12 13:00:00 : 후평1동   18450 ----------


 ---------- 2016-10-12 14:00:00 : 신북읍   18451 ----------


 ---------- 2016-10-12 15:00:00 : 신동면   18452 ----------


 ---------- 2016-10-12 15:00:00 : 동  면   18453 ----------


 ---------- 2016-10-13 09:00:00 : 남  면   18454 ----------


 ---------- 2016-10-13 09:00:00 : 동산면   18455 ----------


 ---------- 2016-10-13 13:00:00 : 동  면   18456 ----------


 ---------- 2016-10-13 16:00:00 : 동내면   18457 ----------


 ---------- 2016-10-13 16:00:00 : 남산면   18458 ----------


 ---------- 2016-10-13 19:00:00 : 강남동   18459 ----------


 ---------- 2016-10-13 21:00:00 : 동  면   18460 ----------


 ---------- 2016-10-14 09:00:00 : 약사명동   18461 ----------


 ---------- 2016-10-14 20:00:00 : 퇴계동   18462 ----------


 ---------- 2016-10-14 21:00:00 : 석사동   18463 ----------


 ---------- 2016-10-15 00:00:00 : 동  면   18464 ----------


 ---------- 2016-10-15 11:00:00 : 약사명동   18465 ----------


 ---------- 2016-10-15 12:00:00 : 서  면   18466 ----------


 ---------- 2016-10-15 15:00:00 : 신북읍   18467 ----------


 ---------- 2016-10-15 16:00:00 : 동산면   18468 ----------


 ---------- 2016-10-15 17:00:00 : 동산면   18469 ----------


 ---------- 2016-10-15 20:00:00 : 동산면   18470 ----------


 ---------- 2016-10-16 00:00:00 : 후평1동   18471 ----------


 ---------- 2016-10-16 04:00:00 : 남산면   18473 ----------


 ---------- 2016-10-16 15:00:00 : 신북읍   18474 ----------


 ---------- 2016-10-16 15:00:00 : 동  면   18475 ----------


 ---------- 2016-10-16 17:00:00 : 동  면   18476 ----------


 ---------- 2016-10-16 21:00:00 : 석사동   18477 ----------


 ---------- 2016-10-17 00:00:00 : 조운동   18478 ----------


 ---------- 2016-10-17 09:00:00 : 약사명동   18479 ----------


 ---------- 2016-10-17 12:00:00 : 동산면   18480 ----------


 ---------- 2016-10-17 13:00:00 : 동내면   18481 ----------


 ---------- 2016-10-17 15:00:00 : 동  면   18482 ----------


 ---------- 2016-10-17 17:00:00 : 사북면   18483 ----------


 ---------- 2016-10-17 22:00:00 : 퇴계동   18484 ----------


 ---------- 2016-10-18 08:00:00 : 동내면   18485 ----------


 ---------- 2016-10-18 11:00:00 : 동  면   18486 ----------


 ---------- 2016-10-18 12:00:00 : 강남동   18487 ----------


 ---------- 2016-10-18 12:00:00 : 동  면   18488 ----------


 ---------- 2016-10-18 13:00:00 : 남  면   18489 ----------


 ---------- 2016-10-18 14:00:00 : 남  면   18490 ----------


 ---------- 2016-10-18 14:00:00 : 후평1동   18491 ----------


 ---------- 2016-10-18 16:00:00 : 서  면   18492 ----------


 ---------- 2016-10-18 18:00:00 : 후평1동   18493 ----------


 ---------- 2016-10-18 21:00:00 : 석사동   18494 ----------


 ---------- 2016-10-18 21:00:00 : 동  면   18495 ----------


 ---------- 2016-10-18 21:00:00 : 후평1동   18496 ----------


 ---------- 2016-10-19 09:00:00 : 사북면   18497 ----------


 ---------- 2016-10-19 12:00:00 : 퇴계동   18498 ----------


 ---------- 2016-10-19 13:00:00 : 동  면   18499 ----------


 ---------- 2016-10-19 15:00:00 : 동내면   18500 ----------


 ---------- 2016-10-19 19:00:00 : 동  면   18501 ----------


 ---------- 2016-10-19 21:00:00 : 약사명동   18502 ----------


 ---------- 2016-10-20 06:00:00 : 북산면   18503 ----------


 ---------- 2016-10-20 07:00:00 : 조운동   18504 ----------


 ---------- 2016-10-20 13:00:00 : 약사명동   18505 ----------


 ---------- 2016-10-20 14:00:00 : 소양동   18506 ----------


 ---------- 2016-10-20 14:00:00 : 퇴계동   18507 ----------


 ---------- 2016-10-20 15:00:00 : 석사동   18508 ----------


 ---------- 2016-10-20 16:00:00 : 강남동   18509 ----------


 ---------- 2016-10-20 19:00:00 : 석사동   18510 ----------


 ---------- 2016-10-21 10:00:00 : 신북읍   18511 ----------


 ---------- 2016-10-21 10:00:00 : 소양동   18512 ----------


 ---------- 2016-10-21 12:00:00 : 서  면   18513 ----------


 ---------- 2016-10-21 13:00:00 : 신사우동   18514 ----------


 ---------- 2016-10-21 15:00:00 : 석사동   18515 ----------


 ---------- 2016-10-21 15:00:00 : 신북읍   18516 ----------


 ---------- 2016-10-21 15:00:00 : 후평1동   18517 ----------


 ---------- 2016-10-21 15:00:00 : 퇴계동   18518 ----------


 ---------- 2016-10-21 17:00:00 : 신북읍   18520 ----------


 ---------- 2016-10-21 19:00:00 : 서  면   18521 ----------


 ---------- 2016-10-22 01:00:00 : 석사동   18522 ----------


 ---------- 2016-10-22 01:00:00 : 소양동   18523 ----------


 ---------- 2016-10-22 04:00:00 : 신북읍   18524 ----------

 ---------- 2016-10-22 12:00:00 : 소양동   18525 ----------


 ---------- 2016-10-22 14:00:00 : 남  면   18526 ----------


 ---------- 2016-10-23 09:00:00 : 동  면   18527 ----------


 ---------- 2016-10-23 10:00:00 : 후평1동   18528 ----------


 ---------- 2016-10-23 13:00:00 : 효자1동   18529 ----------


 ---------- 2016-10-23 14:00:00 : 조운동   18530 ----------


 ---------- 2016-10-24 05:00:00 : 후평1동   18531 ----------


 ---------- 2016-10-24 09:00:00 : 사북면   18532 ----------


 ---------- 2016-10-24 09:00:00 : 신북읍   18533 ----------


 ---------- 2016-10-24 18:00:00 : 약사명동   18534 ----------


 ---------- 2016-10-25 02:00:00 : 근화동   18535 ----------


 ---------- 2016-10-25 04:00:00 : 조운동   18536 ----------


 ---------- 2016-10-25 09:00:00 : 퇴계동   18538 ----------


 ---------- 2016-10-25 13:00:00 : 강남동   18539 ----------


 ---------- 2016-10-25 16:00:00 : 남산면   18540 ----------


 ---------- 2016-10-25 20:00:00 : 후평1동   18541 ----------


 ---------- 2016-10-26 01:00:00 : 남산면   18543 ----------


 ---------- 2016-10-26 07:00:00 : 신북읍   18545 ----------


 ---------- 2016-10-26 10:00:00 : 효자1동   18546 ----------


 ---------- 2016-10-26 14:00:00 : 석사동   18547 ----------


 ---------- 2016-10-26 22:00:00 : 동  면   18548 ----------


 ---------- 2016-10-27 03:00:00 : 퇴계동   18549 ----------


 ---------- 2016-10-27 06:00:00 : 효자1동   18550 ----------


 ---------- 2016-10-27 13:00:00 : 서  면   18551 ----------


 ---------- 2016-10-27 17:00:00 : 효자1동   18552 ----------


 ---------- 2016-10-27 18:00:00 : 교  동   18553 ----------


 ---------- 2016-10-27 21:00:00 : 후평1동   18554 ----------


 ---------- 2016-10-27 22:00:00 : 효자1동   18555 ----------


 ---------- 2016-10-28 12:00:00 : 퇴계동   18556 ----------


 ---------- 2016-10-29 06:00:00 : 동  면   18557 ----------


 ---------- 2016-10-29 09:00:00 : 신북읍   18558 ----------


 ---------- 2016-10-29 16:00:00 : 강남동   18559 ----------


 ---------- 2016-10-29 16:00:00 : 동  면   18560 ----------


 ---------- 2016-10-29 18:00:00 : 서  면   18561 ----------


 ---------- 2016-10-30 09:00:00 : 강남동   18562 ----------


 ---------- 2016-10-30 12:00:00 : 신북읍   18564 ----------


 ---------- 2016-10-30 16:00:00 : 동내면   18565 ----------


 ---------- 2016-10-30 18:00:00 : 서  면   18567 ----------


 ---------- 2016-10-30 19:00:00 : 석사동   18568 ----------


 ---------- 2016-10-31 00:00:00 : 효자1동   18569 ----------


 ---------- 2016-10-31 04:00:00 : 약사명동   18570 ----------


 ---------- 2016-10-31 09:00:00 : 동  면   18571 ----------


 ---------- 2016-10-31 10:00:00 : 남  면   18572 ----------


 ---------- 2016-10-31 10:00:00 : 동  면   18573 ----------


 ---------- 2016-10-31 19:00:00 : 효자1동   18574 ----------


 ---------- 2016-10-31 22:00:00 : 석사동   18575 ----------


 ---------- 2016-11-01 10:00:00 : 후평1동   18576 ----------


 ---------- 2016-11-01 12:00:00 : 동내면   18577 ----------


 ---------- 2016-11-01 13:00:00 : 신동면   18578 ----------


 ---------- 2016-11-01 15:00:00 : 석사동   18579 ----------


 ---------- 2016-11-01 15:00:00 : 소양동   18581 ----------


 ---------- 2016-11-01 16:00:00 : 석사동   18583 ----------


 ---------- 2016-11-01 18:00:00 : 근화동   18584 ----------


 ---------- 2016-11-01 19:00:00 : 후평1동   18585 ----------


 ---------- 2016-11-01 23:00:00 : 소양동   18586 ----------


 ---------- 2016-11-02 02:00:00 : 후평1동   18587 ----------


 ---------- 2016-11-02 03:00:00 : 효자1동   18588 ----------


 ---------- 2016-11-02 08:00:00 : 퇴계동   18589 ----------


 ---------- 2016-11-02 14:00:00 : 약사명동   18590 ----------


 ---------- 2016-11-02 14:00:00 : 동  면   18591 ----------


 ---------- 2016-11-02 18:00:00 : 동내면   18592 ----------


 ---------- 2016-11-03 00:00:00 : 동  면   18594 ----------


 ---------- 2016-11-03 07:00:00 : 동  면   18595 ----------


 ---------- 2016-11-03 14:00:00 : 강남동   18596 ----------


 ---------- 2016-11-03 16:00:00 : 동  면   18597 ----------


 ---------- 2016-11-04 05:00:00 : 서  면   18598 ----------


 ---------- 2016-11-04 08:00:00 : 교  동   18599 ----------


 ---------- 2016-11-04 19:00:00 : 퇴계동   18600 ----------


 ---------- 2016-11-04 20:00:00 : 동내면   18601 ----------


 ---------- 2016-11-05 07:00:00 : 석사동   18603 ----------


 ---------- 2016-11-05 07:00:00 : 남산면   18605 ----------


 ---------- 2016-11-05 14:00:00 : 남산면   18606 ----------


 ---------- 2016-11-05 19:00:00 : 강남동   18607 ----------


 ---------- 2016-11-06 00:00:00 : 후평1동   18608 ----------


 ---------- 2016-11-06 01:00:00 : 신사우동   18609 ----------


 ---------- 2016-11-06 08:00:00 : 동산면   18610 ----------


 ---------- 2016-11-06 09:00:00 : 후평1동   18611 ----------


 ---------- 2016-11-06 13:00:00 : 동  면   18612 ----------


 ---------- 2016-11-06 13:00:00 : 후평1동   18613 ----------


 ---------- 2016-11-06 14:00:00 : 동내면   18614 ----------


 ---------- 2016-11-07 07:00:00 : 사북면   18615 ----------


 ---------- 2016-11-07 13:00:00 : 강남동   18616 ----------


 ---------- 2016-11-07 13:00:00 : 동내면   18617 ----------


 ---------- 2016-11-07 18:00:00 : 퇴계동   18618 ----------


 ---------- 2016-11-08 01:00:00 : 후평1동   18619 ----------


 ---------- 2016-11-08 09:00:00 : 신북읍   18620 ----------


 ---------- 2016-11-08 10:00:00 : 근화동   18621 ----------


 ---------- 2016-11-08 12:00:00 : 남  면   18622 ----------


 ---------- 2016-11-08 12:00:00 : 후평1동   18624 ----------


 ---------- 2016-11-08 16:00:00 : 소양동   18625 ----------


 ---------- 2016-11-08 16:00:00 : 동산면   18626 ----------


 ---------- 2016-11-08 17:00:00 : 퇴계동   18627 ----------


 ---------- 2016-11-09 08:00:00 : 신사우동   18628 ----------


 ---------- 2016-11-09 09:00:00 : 후평1동   18629 ----------


 ---------- 2016-11-09 14:00:00 : 후평1동   18630 ----------


 ---------- 2016-11-09 19:00:00 : 남  면   18631 ----------


 ---------- 2016-11-09 20:00:00 : 신북읍   18632 ----------


 ---------- 2016-11-09 21:00:00 : 후평1동   18633 ----------


 ---------- 2016-11-10 12:00:00 : 소양동   18634 ----------


 ---------- 2016-11-10 20:00:00 : 근화동   18635 ----------


 ---------- 2016-11-11 08:00:00 : 교  동   18636 ----------


 ---------- 2016-11-11 09:00:00 : 남  면   18637 ----------


 ---------- 2016-11-11 10:00:00 : 효자1동   18640 ----------


 ---------- 2016-11-11 10:00:00 : 근화동   18641 ----------


 ---------- 2016-11-11 12:00:00 : 사북면   18642 ----------


 ---------- 2016-11-11 19:00:00 : 신사우동   18643 ----------


 ---------- 2016-11-11 19:00:00 : 후평1동   18644 ----------


 ---------- 2016-11-11 22:00:00 : 신사우동   18645 ----------


 ---------- 2016-11-12 14:00:00 : 서  면   18646 ----------


 ---------- 2016-11-12 23:00:00 : 퇴계동   18647 ----------


 ---------- 2016-11-13 04:00:00 : 효자1동   18648 ----------


 ---------- 2016-11-13 17:00:00 : 석사동   18649 ----------


 ---------- 2016-11-14 02:00:00 : 퇴계동   18650 ----------


 ---------- 2016-11-14 15:00:00 : 남산면   18652 ----------


 ---------- 2016-11-14 19:00:00 : 남  면   18653 ----------


 ---------- 2016-11-15 09:00:00 : 동내면   18654 ----------


 ---------- 2016-11-15 13:00:00 : 서  면   18655 ----------


 ---------- 2016-11-15 14:00:00 : 후평1동   18656 ----------


 ---------- 2016-11-15 15:00:00 : 효자1동   18657 ----------


 ---------- 2016-11-15 16:00:00 : 효자1동   18658 ----------


 ---------- 2016-11-15 17:00:00 : 신동면   18659 ----------


 ---------- 2016-11-16 08:00:00 : 신사우동   18660 ----------


 ---------- 2016-11-16 09:00:00 : 남산면   18661 ----------


 ---------- 2016-11-16 17:00:00 : 효자1동   18662 ----------


 ---------- 2016-11-16 19:00:00 : 조운동   18663 ----------


 ---------- 2016-11-16 21:00:00 : 동내면   18664 ----------


 ---------- 2016-11-17 10:00:00 : 동  면   18665 ----------


 ---------- 2016-11-17 13:00:00 : 석사동   18666 ----------


 ---------- 2016-11-17 16:00:00 : 퇴계동   18667 ----------


 ---------- 2016-11-18 12:00:00 : 신사우동   18668 ----------


 ---------- 2016-11-18 17:00:00 : 효자1동   18669 ----------


 ---------- 2016-11-19 01:00:00 : 후평1동   18670 ----------


 ---------- 2016-11-19 10:00:00 : 신동면   18671 ----------


 ---------- 2016-11-19 10:00:00 : 북산면   18672 ----------


 ---------- 2016-11-19 14:00:00 : 신동면   18673 ----------


 ---------- 2016-11-19 15:00:00 : 서  면   18674 ----------

 ---------- 2016-11-19 18:00:00 : 서  면   18675 ----------


 ---------- 2016-11-19 18:00:00 : 동  면   18676 ----------


 ---------- 2016-11-19 18:00:00 : 조운동   18677 ----------


 ---------- 2016-11-19 21:00:00 : 후평1동   18678 ----------


 ---------- 2016-11-19 22:00:00 : 동내면   18679 ----------


 ---------- 2016-11-19 22:00:00 : 효자1동   18680 ----------


 ---------- 2016-11-20 12:00:00 : 근화동   18681 ----------


 ---------- 2016-11-20 13:00:00 : 남산면   18682 ----------


 ---------- 2016-11-20 13:00:00 : 동  면   18683 ----------


 ---------- 2016-11-20 17:00:00 : 강남동   18684 ----------


 ---------- 2016-11-20 17:00:00 : 약사명동   18685 ----------


 ---------- 2016-11-20 17:00:00 : 퇴계동   18686 ----------


 ---------- 2016-11-20 18:00:00 : 근화동   18687 ----------


 ---------- 2016-11-21 10:00:00 : 석사동   18688 ----------


 ---------- 2016-11-21 12:00:00 : 후평1동   18689 ----------


 ---------- 2016-11-21 14:00:00 : 후평1동   18690 ----------


 ---------- 2016-11-21 14:00:00 : 퇴계동   18691 ----------


 ---------- 2016-11-21 16:00:00 : 신동면   18692 ----------


 ---------- 2016-11-21 17:00:00 : 퇴계동   18693 ----------


 ---------- 2016-11-21 17:00:00 : 북산면   18694 ----------


 ---------- 2016-11-21 19:00:00 : 동  면   18695 ----------


 ---------- 2016-11-21 22:00:00 : 퇴계동   18696 ----------


 ---------- 2016-11-22 05:00:00 : 조운동   18697 ----------


 ---------- 2016-11-22 10:00:00 : 퇴계동   18698 ----------


 ---------- 2016-11-23 13:00:00 : 신동면   18699 ----------


 ---------- 2016-11-23 13:00:00 : 동내면   18701 ----------


 ---------- 2016-11-23 15:00:00 : 신동면   18702 ----------


 ---------- 2016-11-23 17:00:00 : 조운동   18703 ----------


 ---------- 2016-11-24 01:00:00 : 조운동   18704 ----------


 ---------- 2016-11-24 02:00:00 : 효자1동   18706 ----------


 ---------- 2016-11-24 07:00:00 : 효자1동   18707 ----------


 ---------- 2016-11-24 12:00:00 : 동내면   18708 ----------


 ---------- 2016-11-24 15:00:00 : 신사우동   18709 ----------


 ---------- 2016-11-24 22:00:00 : 동  면   18710 ----------


 ---------- 2016-11-25 14:00:00 : 후평1동   18711 ----------


 ---------- 2016-11-25 16:00:00 : 효자1동   18712 ----------


 ---------- 2016-11-26 04:00:00 : 동내면   18713 ----------


 ---------- 2016-11-26 09:00:00 : 서  면   18714 ----------


 ---------- 2016-11-26 10:00:00 : 동  면   18715 ----------


 ---------- 2016-11-26 12:00:00 : 석사동   18716 ----------


 ---------- 2016-11-26 12:00:00 : 후평1동   18717 ----------


 ---------- 2016-11-26 13:00:00 : 신동면   18718 ----------


 ---------- 2016-11-26 15:00:00 : 석사동   18719 ----------


 ---------- 2016-11-26 16:00:00 : 신동면   18720 ----------


 ---------- 2016-11-26 16:00:00 : 신북읍   18721 ----------


 ---------- 2016-11-26 18:00:00 : 소양동   18722 ----------


 ---------- 2016-11-26 20:00:00 : 동내면   18723 ----------


 ---------- 2016-11-26 20:00:00 : 퇴계동   18724 ----------


 ---------- 2016-11-26 21:00:00 : 석사동   18725 ----------


 ---------- 2016-11-26 22:00:00 : 석사동   18726 ----------


 ---------- 2016-11-27 11:00:00 : 사북면   18727 ----------


 ---------- 2016-11-27 13:00:00 : 석사동   18728 ----------


 ---------- 2016-11-27 20:00:00 : 후평1동   18730 ----------


 ---------- 2016-11-28 00:00:00 : 신사우동   18732 ----------


 ---------- 2016-11-28 06:00:00 : 신사우동   18733 ----------


 ---------- 2016-11-28 15:00:00 : 퇴계동   18734 ----------


 ---------- 2016-11-28 20:00:00 : 소양동   18735 ----------


 ---------- 2016-11-28 21:00:00 : 퇴계동   18736 ----------


 ---------- 2016-11-29 11:00:00 : 동내면   18737 ----------


 ---------- 2016-11-29 20:00:00 : 석사동   18738 ----------


 ---------- 2016-11-29 22:00:00 : 퇴계동   18739 ----------


 ---------- 2016-11-30 01:00:00 : 동내면   18740 ----------


 ---------- 2016-11-30 08:00:00 : 남  면   18742 ----------


 ---------- 2016-11-30 09:00:00 : 근화동   18743 ----------


 ---------- 2016-11-30 10:00:00 : 근화동   18744 ----------


 ---------- 2016-11-30 11:00:00 : 약사명동   18745 ----------


 ---------- 2016-11-30 12:00:00 : 효자1동   18746 ----------


 ---------- 2016-11-30 16:00:00 : 신동면   18747 ----------


 ---------- 2016-11-30 17:00:00 : 강남동   18748 ----------


 ---------- 2016-11-30 21:00:00 : 퇴계동   18749 ----------


 ---------- 2016-11-30 22:00:00 : 후평1동   18750 ----------


 ---------- 2016-12-01 10:00:00 : 조운동   18751 ----------


 ---------- 2016-12-01 12:00:00 : 근화동   18752 ----------


 ---------- 2016-12-01 15:00:00 : 퇴계동   18753 ----------


 ---------- 2016-12-01 17:00:00 : 사북면   18754 ----------


 ---------- 2016-12-01 17:00:00 : 조운동   18755 ----------


 ---------- 2016-12-01 23:00:00 : 석사동   18756 ----------


 ---------- 2016-12-02 16:00:00 : 퇴계동   18757 ----------


 ---------- 2016-12-02 19:00:00 : 서  면   18758 ----------


 ---------- 2016-12-03 05:00:00 : 퇴계동   18759 ----------


 ---------- 2016-12-03 08:00:00 : 동  면   18760 ----------


 ---------- 2016-12-03 09:00:00 : 사북면   18761 ----------


 ---------- 2016-12-03 09:00:00 : 동내면   18762 ----------


 ---------- 2016-12-03 09:00:00 : 근화동   18763 ----------


 ---------- 2016-12-03 17:00:00 : 신북읍   18764 ----------


 ---------- 2016-12-03 23:00:00 : 석사동   18765 ----------


 ---------- 2016-12-04 01:00:00 : 동  면   18766 ----------


 ---------- 2016-12-04 09:00:00 : 서  면   18767 ----------


 ---------- 2016-12-05 09:00:00 : 동산면   18768 ----------


 ---------- 2016-12-05 11:00:00 : 후평1동   18769 ----------


 ---------- 2016-12-05 11:00:00 : 퇴계동   18770 ----------


 ---------- 2016-12-05 14:00:00 : 효자1동   18771 ----------


 ---------- 2016-12-06 19:00:00 : 동산면   18772 ----------


 ---------- 2016-12-06 20:00:00 : 동산면   18774 ----------


 ---------- 2016-12-07 16:00:00 : 동내면   18775 ----------


 ---------- 2016-12-07 18:00:00 : 후평1동   18776 ----------


 ---------- 2016-12-07 19:00:00 : 동내면   18777 ----------


 ---------- 2016-12-08 13:00:00 : 후평1동   18778 ----------


 ---------- 2016-12-09 12:00:00 : 사북면   18779 ----------


 ---------- 2016-12-09 15:00:00 : 남산면   18780 ----------


 ---------- 2016-12-09 16:00:00 : 강남동   18781 ----------


 ---------- 2016-12-09 18:00:00 : 동  면   18782 ----------


 ---------- 2016-12-10 01:00:00 : 퇴계동   18783 ----------


 ---------- 2016-12-10 04:00:00 : 후평1동   18784 ----------


 ---------- 2016-12-10 08:00:00 : 소양동   18785 ----------


 ---------- 2016-12-11 08:00:00 : 서  면   18787 ----------


 ---------- 2016-12-11 08:00:00 : 동내면   18788 ----------


 ---------- 2016-12-11 13:00:00 : 퇴계동   18789 ----------


 ---------- 2016-12-11 14:00:00 : 후평1동   18790 ----------


 ---------- 2016-12-11 19:00:00 : 퇴계동   18791 ----------


 ---------- 2016-12-11 20:00:00 : 동  면   18792 ----------


 ---------- 2016-12-11 20:00:00 : 후평1동   18793 ----------


 ---------- 2016-12-11 22:00:00 : 퇴계동   18794 ----------


 ---------- 2016-12-12 09:00:00 : 신북읍   18795 ----------


 ---------- 2016-12-12 16:00:00 : 신북읍   18796 ----------


 ---------- 2016-12-12 17:00:00 : 석사동   18797 ----------


 ---------- 2016-12-12 20:00:00 : 소양동   18798 ----------


 ---------- 2016-12-13 00:00:00 : 효자1동   18800 ----------


 ---------- 2016-12-13 11:00:00 : 조운동   18801 ----------


 ---------- 2016-12-13 12:00:00 : 신북읍   18804 ----------


 ---------- 2016-12-13 15:00:00 : 효자1동   18805 ----------


 ---------- 2016-12-14 11:00:00 : 석사동   18806 ----------


 ---------- 2016-12-14 11:00:00 : 강남동   18807 ----------


 ---------- 2016-12-14 14:00:00 : 신동면   18808 ----------


 ---------- 2016-12-14 19:00:00 : 후평1동   18809 ----------


 ---------- 2016-12-15 03:00:00 : 효자1동   18810 ----------


 ---------- 2016-12-15 07:00:00 : 신북읍   18811 ----------


 ---------- 2016-12-15 12:00:00 : 후평1동   18812 ----------


 ---------- 2016-12-15 13:00:00 : 후평1동   18813 ----------


 ---------- 2016-12-15 18:00:00 : 남  면   18814 ----------


 ---------- 2016-12-16 00:00:00 : 후평1동   18815 ----------


 ---------- 2016-12-16 00:00:00 : 교  동   18816 ----------


 ---------- 2016-12-16 09:00:00 : 효자1동   18817 ----------


 ---------- 2016-12-16 10:00:00 : 동산면   18818 ----------


 ---------- 2016-12-16 11:00:00 : 동내면   18819 ----------


 ---------- 2016-12-17 01:00:00 : 동  면   18820 ----------

 ---------- 2016-12-17 08:00:00 : 신동면   18821 ----------


 ---------- 2016-12-17 14:00:00 : 신동면   18822 ----------


 ---------- 2016-12-17 14:00:00 : 동내면   18823 ----------


 ---------- 2016-12-17 18:00:00 : 동산면   18824 ----------


 ---------- 2016-12-17 21:00:00 : 후평1동   18825 ----------


 ---------- 2016-12-17 23:00:00 : 후평1동   18826 ----------


 ---------- 2016-12-18 09:00:00 : 남산면   18827 ----------


 ---------- 2016-12-18 16:00:00 : 남산면   18828 ----------


 ---------- 2016-12-18 22:00:00 : 후평1동   18829 ----------


 ---------- 2016-12-19 01:00:00 : 근화동   18830 ----------


 ---------- 2016-12-19 11:00:00 : 남  면   18831 ----------


 ---------- 2016-12-19 14:00:00 : 동내면   18832 ----------


 ---------- 2016-12-19 20:00:00 : 후평1동   18833 ----------


 ---------- 2016-12-19 23:00:00 : 동내면   18834 ----------


 ---------- 2016-12-20 07:00:00 : 동내면   18836 ----------


 ---------- 2016-12-20 15:00:00 : 동내면   18837 ----------


 ---------- 2016-12-20 16:00:00 : 사북면   18838 ----------


 ---------- 2016-12-20 18:00:00 : 퇴계동   18839 ----------


 ---------- 2016-12-21 02:00:00 : 석사동   18840 ----------


 ---------- 2016-12-21 08:00:00 : 후평1동   18841 ----------


 ---------- 2016-12-21 08:00:00 : 퇴계동   18842 ----------


 ---------- 2016-12-21 15:00:00 : 동  면   18843 ----------


 ---------- 2016-12-21 18:00:00 : 퇴계동   18845 ----------


 ---------- 2016-12-21 21:00:00 : 효자1동   18846 ----------


 ---------- 2016-12-22 06:00:00 : 후평1동   18847 ----------


 ---------- 2016-12-22 07:00:00 : 후평1동   18848 ----------


 ---------- 2016-12-22 11:00:00 : 석사동   18849 ----------


 ---------- 2016-12-22 12:00:00 : 동산면   18850 ----------


 ---------- 2016-12-23 11:00:00 : 동  면   18851 ----------


 ---------- 2016-12-23 16:00:00 : 후평1동   18852 ----------


 ---------- 2016-12-23 20:00:00 : 서  면   18854 ----------


 ---------- 2016-12-23 21:00:00 : 강남동   18855 ----------


 ---------- 2016-12-23 22:00:00 : 효자1동   18857 ----------


 ---------- 2016-12-23 23:00:00 : 동  면   18858 ----------


 ---------- 2016-12-24 07:00:00 : 퇴계동   18859 ----------


 ---------- 2016-12-24 15:00:00 : 동  면   18860 ----------


 ---------- 2016-12-25 01:00:00 : 남산면   18861 ----------


 ---------- 2016-12-25 03:00:00 : 신사우동   18862 ----------


 ---------- 2016-12-25 14:00:00 : 서  면   18863 ----------


 ---------- 2016-12-25 14:00:00 : 신북읍   18864 ----------


 ---------- 2016-12-25 14:00:00 : 후평1동   18865 ----------


 ---------- 2016-12-25 15:00:00 : 서  면   18866 ----------


 ---------- 2016-12-25 18:00:00 : 퇴계동   18867 ----------


 ---------- 2016-12-25 19:00:00 : 동산면   18868 ----------


 ---------- 2016-12-25 21:00:00 : 신북읍   18869 ----------


 ---------- 2016-12-26 06:00:00 : 효자1동   18870 ----------


 ---------- 2016-12-26 10:00:00 : 신사우동   18873 ----------


 ---------- 2016-12-26 17:00:00 : 남산면   18874 ----------


 ---------- 2016-12-27 02:00:00 : 효자1동   18875 ----------


 ---------- 2016-12-27 09:00:00 : 후평1동   18876 ----------


 ---------- 2016-12-28 11:00:00 : 후평1동   18877 ----------


 ---------- 2016-12-28 17:00:00 : 교  동   18878 ----------


 ---------- 2016-12-29 01:00:00 : 신사우동   18879 ----------


 ---------- 2016-12-29 15:00:00 : 동  면   18880 ----------


 ---------- 2016-12-29 21:00:00 : 효자1동   18882 ----------


 ---------- 2016-12-30 00:00:00 : 소양동   18883 ----------


 ---------- 2016-12-30 10:00:00 : 동내면   18884 ----------


 ---------- 2016-12-30 10:00:00 : 동  면   18885 ----------


 ---------- 2016-12-30 23:00:00 : 강남동   18886 ----------


 ---------- 2016-12-30 23:00:00 : 효자1동   18888 ----------


 ---------- 2016-12-31 00:00:00 : 신북읍   18889 ----------


 ---------- 2016-12-31 02:00:00 : 조운동   18890 ----------


 ---------- 2016-12-31 16:00:00 : 남  면   18891 ----------


 ---------- 2016-12-31 16:00:00 : 동  면   18892 ----------


 ---------- 2016-12-31 18:00:00 : 신사우동   18893 ----------


 ---------- 2017-01-01 09:00:00 : 근화동   18894 ----------


 ---------- 2017-01-01 15:00:00 : 신북읍   18896 ----------


 ---------- 2017-01-01 16:00:00 : 서  면   18898 ----------


 ---------- 2017-01-01 21:00:00 : 동내면   18899 ----------


 ---------- 2017-01-02 14:00:00 : 동내면   18900 ----------


 ---------- 2017-01-02 14:00:00 : 남산면   18901 ----------


 ---------- 2017-01-02 18:00:00 : 사북면   18902 ----------


 ---------- 2017-01-03 03:00:00 : 강남동   18903 ----------


 ---------- 2017-01-03 12:00:00 : 후평1동   18904 ----------


 ---------- 2017-01-03 15:00:00 : 동산면   18905 ----------


 ---------- 2017-01-03 20:00:00 : 조운동   18906 ----------


 ---------- 2017-01-04 11:00:00 : 신북읍   18907 ----------


 ---------- 2017-01-04 22:00:00 : 신북읍   18911 ----------


 ---------- 2017-01-05 18:00:00 : 석사동   18912 ----------


 ---------- 2017-01-06 07:00:00 : 신사우동   18913 ----------


 ---------- 2017-01-06 12:00:00 : 조운동   18914 ----------


 ---------- 2017-01-06 21:00:00 : 조운동   18915 ----------


 ---------- 2017-01-06 23:00:00 : 소양동   18916 ----------


 ---------- 2017-01-07 05:00:00 : 신사우동   18918 ----------


 ---------- 2017-01-07 14:00:00 : 남산면   18919 ----------


 ---------- 2017-01-07 17:00:00 : 효자1동   18921 ----------


 ---------- 2017-01-07 18:00:00 : 석사동   18922 ----------


 ---------- 2017-01-07 22:00:00 : 퇴계동   18923 ----------


 ---------- 2017-01-08 00:00:00 : 교  동   18924 ----------


 ---------- 2017-01-08 10:00:00 : 효자1동   18925 ----------


 ---------- 2017-01-08 11:00:00 : 강남동   18926 ----------


 ---------- 2017-01-08 15:00:00 : 석사동   18927 ----------


 ---------- 2017-01-08 15:00:00 : 후평1동   18929 ----------


 ---------- 2017-01-08 16:00:00 : 사북면   18930 ----------


 ---------- 2017-01-08 22:00:00 : 퇴계동   18931 ----------


 ---------- 2017-01-09 08:00:00 : 소양동   18932 ----------


 ---------- 2017-01-09 08:00:00 : 조운동   18935 ----------


 ---------- 2017-01-09 17:00:00 : 동  면   18936 ----------


 ---------- 2017-01-10 10:00:00 : 동내면   18937 ----------


 ---------- 2017-01-10 14:00:00 : 서  면   18938 ----------


 ---------- 2017-01-10 15:00:00 : 효자1동   18939 ----------


 ---------- 2017-01-11 10:00:00 : 남  면   18940 ----------


 ---------- 2017-01-11 13:00:00 : 신북읍   18941 ----------


 ---------- 2017-01-11 13:00:00 : 조운동   18942 ----------


 ---------- 2017-01-11 16:00:00 : 동  면   18943 ----------


 ---------- 2017-01-12 14:00:00 : 후평1동   18944 ----------


 ---------- 2017-01-12 16:00:00 : 퇴계동   18945 ----------


 ---------- 2017-01-12 23:00:00 : 효자1동   18946 ----------


 ---------- 2017-01-13 14:00:00 : 신북읍   18948 ----------


 ---------- 2017-01-13 14:00:00 : 퇴계동   18949 ----------


 ---------- 2017-01-13 19:00:00 : 신동면   18950 ----------


 ---------- 2017-01-13 19:00:00 : 동산면   18951 ----------


 ---------- 2017-01-13 23:00:00 : 석사동   18952 ----------


 ---------- 2017-01-14 12:00:00 : 사북면   18953 ----------


 ---------- 2017-01-14 13:00:00 : 퇴계동   18956 ----------


 ---------- 2017-01-14 23:00:00 : 남산면   18957 ----------


 ---------- 2017-01-15 05:00:00 : 퇴계동   18958 ----------


 ---------- 2017-01-15 12:00:00 : 강남동   18959 ----------


 ---------- 2017-01-15 15:00:00 : 서  면   18962 ----------


 ---------- 2017-01-15 15:00:00 : 동산면   18963 ----------


 ---------- 2017-01-15 19:00:00 : 강남동   18964 ----------


 ---------- 2017-01-15 21:00:00 : 퇴계동   18965 ----------


 ---------- 2017-01-16 11:00:00 : 퇴계동   18967 ----------


 ---------- 2017-01-16 15:00:00 : 후평1동   18968 ----------


 ---------- 2017-01-17 01:00:00 : 약사명동   18969 ----------


 ---------- 2017-01-17 08:00:00 : 강남동   18970 ----------


 ---------- 2017-01-17 09:00:00 : 효자1동   18971 ----------


 ---------- 2017-01-17 14:00:00 : 신사우동   18972 ----------


 ---------- 2017-01-17 15:00:00 : 퇴계동   18973 ----------


 ---------- 2017-01-17 18:00:00 : 신북읍   18974 ----------


 ---------- 2017-01-17 19:00:00 : 효자1동   18975 ----------


 ---------- 2017-01-18 00:00:00 : 효자1동   18976 ----------


 ---------- 2017-01-18 04:00:00 : 효자1동   18978 ----------


 ---------- 2017-01-18 08:00:00 : 소양동   18979 ----------


 ---------- 2017-01-18 09:00:00 : 강남동   18980 ----------


 ---------- 2017-01-18 22:00:00 : 신사우동   18981 ----------


 ---------- 2017-01-18 22:00:00 : 퇴계동   18982 ----------

 ---------- 2017-01-19 10:00:00 : 사북면   18983 ----------


 ---------- 2017-01-19 15:00:00 : 신북읍   18984 ----------


 ---------- 2017-01-19 15:00:00 : 북산면   18985 ----------


 ---------- 2017-01-19 18:00:00 : 동  면   18986 ----------


 ---------- 2017-01-19 19:00:00 : 석사동   18987 ----------


 ---------- 2017-01-20 07:00:00 : 서  면   18988 ----------


 ---------- 2017-01-20 08:00:00 : 신동면   18989 ----------


 ---------- 2017-01-20 09:00:00 : 소양동   18990 ----------


 ---------- 2017-01-20 12:00:00 : 퇴계동   18991 ----------


 ---------- 2017-01-20 13:00:00 : 동내면   18992 ----------


 ---------- 2017-01-20 13:00:00 : 후평1동   18993 ----------


 ---------- 2017-01-20 17:00:00 : 효자1동   18994 ----------


 ---------- 2017-01-21 09:00:00 : 동산면   18995 ----------


 ---------- 2017-01-21 13:00:00 : 사북면   18996 ----------


 ---------- 2017-01-21 14:00:00 : 신동면   18997 ----------


 ---------- 2017-01-21 18:00:00 : 신북읍   18999 ----------


 ---------- 2017-01-21 20:00:00 : 남  면   19000 ----------


 ---------- 2017-01-22 10:00:00 : 서  면   19001 ----------


 ---------- 2017-01-22 10:00:00 : 효자1동   19002 ----------


 ---------- 2017-01-22 14:00:00 : 남산면   19003 ----------


 ---------- 2017-01-22 17:00:00 : 근화동   19004 ----------


 ---------- 2017-01-22 22:00:00 : 동산면   19005 ----------


 ---------- 2017-01-23 02:00:00 : 교  동   19006 ----------


 ---------- 2017-01-23 05:00:00 : 석사동   19007 ----------


 ---------- 2017-01-23 10:00:00 : 신사우동   19008 ----------


 ---------- 2017-01-23 12:00:00 : 남  면   19009 ----------


 ---------- 2017-01-23 12:00:00 : 남산면   19011 ----------


 ---------- 2017-01-23 12:00:00 : 소양동   19012 ----------


 ---------- 2017-01-23 14:00:00 : 효자1동   19013 ----------


 ---------- 2017-01-23 15:00:00 : 조운동   19014 ----------


 ---------- 2017-01-24 00:00:00 : 효자1동   19016 ----------


 ---------- 2017-01-24 02:00:00 : 강남동   19017 ----------


 ---------- 2017-01-24 08:00:00 : 강남동   19018 ----------


 ---------- 2017-01-24 12:00:00 : 서  면   19019 ----------


 ---------- 2017-01-24 13:00:00 : 동  면   19020 ----------


 ---------- 2017-01-24 23:00:00 : 후평1동   19021 ----------


 ---------- 2017-01-25 06:00:00 : 남  면   19023 ----------


 ---------- 2017-01-25 08:00:00 : 약사명동   19024 ----------


 ---------- 2017-01-25 09:00:00 : 동산면   19025 ----------


 ---------- 2017-01-25 13:00:00 : 신동면   19027 ----------


 ---------- 2017-01-25 16:00:00 : 동산면   19029 ----------


 ---------- 2017-01-25 22:00:00 : 동내면   19031 ----------


 ---------- 2017-01-25 23:00:00 : 신북읍   19034 ----------


 ---------- 2017-01-26 01:00:00 : 남산면   19035 ----------


 ---------- 2017-01-26 08:00:00 : 퇴계동   19036 ----------


 ---------- 2017-01-26 15:00:00 : 신북읍   19037 ----------


 ---------- 2017-01-26 18:00:00 : 후평1동   19038 ----------


 ---------- 2017-01-27 00:00:00 : 강남동   19039 ----------


 ---------- 2017-01-27 00:00:00 : 근화동   19040 ----------


 ---------- 2017-01-27 00:00:00 : 소양동   19041 ----------


 ---------- 2017-01-27 08:00:00 : 신북읍   19042 ----------


 ---------- 2017-01-27 12:00:00 : 남  면   19043 ----------


 ---------- 2017-01-27 14:00:00 : 신동면   19044 ----------


 ---------- 2017-01-27 17:00:00 : 석사동   19047 ----------


 ---------- 2017-01-28 08:00:00 : 효자1동   19048 ----------


 ---------- 2017-01-28 11:00:00 : 서  면   19050 ----------


 ---------- 2017-01-28 11:00:00 : 동  면   19051 ----------


 ---------- 2017-01-28 12:00:00 : 소양동   19052 ----------


 ---------- 2017-01-28 21:00:00 : 동  면   19053 ----------


 ---------- 2017-01-28 23:00:00 : 석사동   19054 ----------


 ---------- 2017-01-29 03:00:00 : 효자1동   19055 ----------


 ---------- 2017-01-29 10:00:00 : 근화동   19056 ----------


 ---------- 2017-01-29 15:00:00 : 동내면   19057 ----------


 ---------- 2017-01-29 15:00:00 : 효자1동   19058 ----------


 ---------- 2017-01-29 17:00:00 : 사북면   19060 ----------


 ---------- 2017-01-29 17:00:00 : 후평1동   19061 ----------


 ---------- 2017-01-29 20:00:00 : 사북면   19062 ----------


 ---------- 2017-01-29 20:00:00 : 효자1동   19065 ----------


 ---------- 2017-01-31 08:00:00 : 동내면   19066 ----------


 ---------- 2017-01-31 16:00:00 : 동산면   19067 ----------


 ---------- 2017-01-31 23:00:00 : 퇴계동   19068 ----------


 ---------- 2017-02-01 00:00:00 : 근화동   19070 ----------


 ---------- 2017-02-01 00:00:00 : 후평1동   19071 ----------


 ---------- 2017-02-01 00:00:00 : 퇴계동   19073 ----------


 ---------- 2017-02-01 03:00:00 : 퇴계동   19074 ----------


 ---------- 2017-02-01 11:00:00 : 효자1동   19075 ----------


 ---------- 2017-02-01 12:00:00 : 동내면   19076 ----------


 ---------- 2017-02-01 13:00:00 : 약사명동   19077 ----------


 ---------- 2017-02-01 14:00:00 : 소양동   19078 ----------


 ---------- 2017-02-01 17:00:00 : 교  동   19079 ----------


 ---------- 2017-02-01 20:00:00 : 조운동   19080 ----------


 ---------- 2017-02-02 02:00:00 : 퇴계동   19081 ----------


 ---------- 2017-02-02 07:00:00 : 후평1동   19082 ----------


 ---------- 2017-02-02 09:00:00 : 신사우동   19083 ----------


 ---------- 2017-02-02 14:00:00 : 신북읍   19084 ----------


 ---------- 2017-02-02 15:00:00 : 석사동   19085 ----------


 ---------- 2017-02-02 17:00:00 : 동산면   19086 ----------


 ---------- 2017-02-03 00:00:00 : 신사우동   19087 ----------


 ---------- 2017-02-03 00:00:00 : 신북읍   19088 ----------


 ---------- 2017-02-03 02:00:00 : 교  동   19089 ----------


 ---------- 2017-02-03 15:00:00 : 석사동   19090 ----------


 ---------- 2017-02-03 17:00:00 : 퇴계동   19091 ----------


 ---------- 2017-02-03 18:00:00 : 후평1동   19092 ----------


 ---------- 2017-02-04 09:00:00 : 효자1동   19093 ----------


 ---------- 2017-02-04 10:00:00 : 퇴계동   19094 ----------


 ---------- 2017-02-04 19:00:00 : 후평1동   19095 ----------


 ---------- 2017-02-04 20:00:00 : 근화동   19096 ----------


 ---------- 2017-02-05 01:00:00 : 강남동   19097 ----------


 ---------- 2017-02-05 01:00:00 : 효자1동   19100 ----------


 ---------- 2017-02-05 01:00:00 : 퇴계동   19101 ----------


 ---------- 2017-02-05 11:00:00 : 근화동   19102 ----------


 ---------- 2017-02-05 12:00:00 : 남  면   19104 ----------


 ---------- 2017-02-06 00:00:00 : 퇴계동   19105 ----------


 ---------- 2017-02-06 08:00:00 : 근화동   19107 ----------


 ---------- 2017-02-06 10:00:00 : 사북면   19108 ----------


 ---------- 2017-02-06 10:00:00 : 퇴계동   19109 ----------


 ---------- 2017-02-06 11:00:00 : 후평1동   19110 ----------


 ---------- 2017-02-06 15:00:00 : 동  면   19111 ----------


 ---------- 2017-02-06 20:00:00 : 후평1동   19112 ----------


 ---------- 2017-02-06 23:00:00 : 조운동   19113 ----------


 ---------- 2017-02-07 00:00:00 : 석사동   19114 ----------


 ---------- 2017-02-07 03:00:00 : 후평1동   19115 ----------


 ---------- 2017-02-07 08:00:00 : 동내면   19116 ----------


 ---------- 2017-02-07 11:00:00 : 동  면   19118 ----------


 ---------- 2017-02-07 13:00:00 : 동  면   19119 ----------


 ---------- 2017-02-07 21:00:00 : 사북면   19121 ----------


 ---------- 2017-02-07 23:00:00 : 교  동   19122 ----------


 ---------- 2017-02-08 09:00:00 : 동내면   19123 ----------


 ---------- 2017-02-08 12:00:00 : 남산면   19125 ----------


 ---------- 2017-02-08 13:00:00 : 남산면   19126 ----------


 ---------- 2017-02-09 10:00:00 : 근화동   19127 ----------


 ---------- 2017-02-09 11:00:00 : 신동면   19128 ----------


 ---------- 2017-02-09 13:00:00 : 조운동   19129 ----------


 ---------- 2017-02-09 14:00:00 : 석사동   19130 ----------


 ---------- 2017-02-09 16:00:00 : 후평1동   19132 ----------


 ---------- 2017-02-09 21:00:00 : 효자1동   19133 ----------


 ---------- 2017-02-10 12:00:00 : 후평1동   19134 ----------


 ---------- 2017-02-10 18:00:00 : 남산면   19136 ----------


 ---------- 2017-02-11 20:00:00 : 소양동   19137 ----------


 ---------- 2017-02-11 21:00:00 : 후평1동   19138 ----------


 ---------- 2017-02-12 06:00:00 : 퇴계동   19139 ----------


 ---------- 2017-02-12 09:00:00 : 동  면   19140 ----------


 ---------- 2017-02-12 09:00:00 : 퇴계동   19141 ----------


 ---------- 2017-02-12 10:00:00 : 동산면   19142 ----------


 ---------- 2017-02-12 11:00:00 : 남산면   19143 ----------


 ---------- 2017-02-12 16:00:00 : 강남동   19144 ----------

 ---------- 2017-02-12 22:00:00 : 석사동   19145 ----------


 ---------- 2017-02-13 02:00:00 : 약사명동   19146 ----------


 ---------- 2017-02-13 03:00:00 : 신북읍   19147 ----------


 ---------- 2017-02-13 08:00:00 : 약사명동   19148 ----------


 ---------- 2017-02-13 11:00:00 : 동  면   19149 ----------


 ---------- 2017-02-13 21:00:00 : 남산면   19151 ----------


 ---------- 2017-02-13 23:00:00 : 효자1동   19152 ----------


 ---------- 2017-02-13 23:00:00 : 후평1동   19153 ----------


 ---------- 2017-02-14 01:00:00 : 강남동   19154 ----------


 ---------- 2017-02-14 10:00:00 : 조운동   19155 ----------


 ---------- 2017-02-14 14:00:00 : 강남동   19156 ----------


 ---------- 2017-02-14 15:00:00 : 동내면   19157 ----------


 ---------- 2017-02-14 16:00:00 : 남산면   19158 ----------


 ---------- 2017-02-14 17:00:00 : 소양동   19160 ----------


 ---------- 2017-02-14 19:00:00 : 석사동   19161 ----------


 ---------- 2017-02-15 01:00:00 : 소양동   19162 ----------


 ---------- 2017-02-15 08:00:00 : 동내면   19164 ----------


 ---------- 2017-02-15 13:00:00 : 신북읍   19165 ----------


 ---------- 2017-02-15 15:00:00 : 조운동   19166 ----------


 ---------- 2017-02-15 19:00:00 : 동  면   19167 ----------


 ---------- 2017-02-16 07:00:00 : 동  면   19168 ----------


 ---------- 2017-02-16 14:00:00 : 효자1동   19169 ----------


 ---------- 2017-02-17 00:00:00 : 남산면   19170 ----------


 ---------- 2017-02-17 00:00:00 : 신북읍   19171 ----------


 ---------- 2017-02-17 10:00:00 : 석사동   19172 ----------


 ---------- 2017-02-17 11:00:00 : 동내면   19173 ----------


 ---------- 2017-02-17 11:00:00 : 교  동   19174 ----------


 ---------- 2017-02-17 13:00:00 : 서  면   19175 ----------


 ---------- 2017-02-17 16:00:00 : 남  면   19176 ----------


 ---------- 2017-02-17 17:00:00 : 동산면   19177 ----------


 ---------- 2017-02-17 19:00:00 : 퇴계동   19178 ----------


 ---------- 2017-02-17 23:00:00 : 강남동   19179 ----------


 ---------- 2017-02-18 10:00:00 : 효자1동   19180 ----------


 ---------- 2017-02-18 10:00:00 : 약사명동   19181 ----------


 ---------- 2017-02-18 10:00:00 : 퇴계동   19182 ----------


 ---------- 2017-02-18 13:00:00 : 신동면   19183 ----------


 ---------- 2017-02-18 14:00:00 : 근화동   19184 ----------


 ---------- 2017-02-18 16:00:00 : 교  동   19185 ----------


 ---------- 2017-02-18 18:00:00 : 효자1동   19186 ----------


 ---------- 2017-02-18 18:00:00 : 후평1동   19187 ----------


 ---------- 2017-02-19 09:00:00 : 석사동   19188 ----------


 ---------- 2017-02-19 10:00:00 : 효자1동   19189 ----------


 ---------- 2017-02-19 15:00:00 : 북산면   19191 ----------


 ---------- 2017-02-19 16:00:00 : 북산면   19192 ----------


 ---------- 2017-02-20 06:00:00 : 신동면   19193 ----------


 ---------- 2017-02-20 08:00:00 : 서  면   19194 ----------


 ---------- 2017-02-20 14:00:00 : 남산면   19195 ----------


 ---------- 2017-02-20 16:00:00 : 남  면   19196 ----------


 ---------- 2017-02-20 17:00:00 : 남  면   19197 ----------


 ---------- 2017-02-20 17:00:00 : 동내면   19198 ----------


 ---------- 2017-02-21 12:00:00 : 남산면   19200 ----------


 ---------- 2017-02-21 15:00:00 : 조운동   19201 ----------


 ---------- 2017-02-21 18:00:00 : 후평1동   19202 ----------


 ---------- 2017-02-22 05:00:00 : 효자1동   19203 ----------


 ---------- 2017-02-22 10:00:00 : 강남동   19204 ----------


 ---------- 2017-02-22 13:00:00 : 후평1동   19205 ----------


 ---------- 2017-02-22 15:00:00 : 효자1동   19206 ----------


 ---------- 2017-02-22 16:00:00 : 동산면   19207 ----------


 ---------- 2017-02-22 17:00:00 : 조운동   19208 ----------


 ---------- 2017-02-22 19:00:00 : 소양동   19209 ----------


 ---------- 2017-02-22 21:00:00 : 동내면   19210 ----------


 ---------- 2017-02-23 09:00:00 : 소양동   19212 ----------


 ---------- 2017-02-23 10:00:00 : 퇴계동   19213 ----------


 ---------- 2017-02-23 16:00:00 : 교  동   19214 ----------


 ---------- 2017-02-23 19:00:00 : 효자1동   19215 ----------


 ---------- 2017-02-23 22:00:00 : 효자1동   19216 ----------


 ---------- 2017-02-24 02:00:00 : 석사동   19217 ----------


 ---------- 2017-02-24 03:00:00 : 강남동   19219 ----------


 ---------- 2017-02-24 03:00:00 : 약사명동   19220 ----------


 ---------- 2017-02-24 11:00:00 : 사북면   19221 ----------


 ---------- 2017-02-24 11:00:00 : 신북읍   19222 ----------


 ---------- 2017-02-24 14:00:00 : 동내면   19223 ----------


 ---------- 2017-02-24 15:00:00 : 동내면   19224 ----------


 ---------- 2017-02-24 16:00:00 : 교  동   19225 ----------


 ---------- 2017-02-24 23:00:00 : 신사우동   19226 ----------


 ---------- 2017-02-25 10:00:00 : 서  면   19227 ----------


 ---------- 2017-02-25 11:00:00 : 효자1동   19228 ----------


 ---------- 2017-02-25 11:00:00 : 퇴계동   19229 ----------


 ---------- 2017-02-25 14:00:00 : 석사동   19230 ----------


 ---------- 2017-02-26 10:00:00 : 남  면   19231 ----------


 ---------- 2017-02-26 12:00:00 : 남  면   19233 ----------


 ---------- 2017-02-26 16:00:00 : 신북읍   19236 ----------


 ---------- 2017-02-27 06:00:00 : 신북읍   19237 ----------


 ---------- 2017-02-27 10:00:00 : 약사명동   19239 ----------


 ---------- 2017-02-27 14:00:00 : 퇴계동   19240 ----------


 ---------- 2017-02-27 17:00:00 : 동산면   19241 ----------


 ---------- 2017-02-27 18:00:00 : 후평1동   19242 ----------


 ---------- 2017-02-27 19:00:00 : 강남동   19243 ----------


 ---------- 2017-02-27 20:00:00 : 동내면   19244 ----------


 ---------- 2017-02-28 09:00:00 : 소양동   19245 ----------


 ---------- 2017-02-28 13:00:00 : 신사우동   19246 ----------


 ---------- 2017-03-01 12:00:00 : 서  면   19248 ----------


 ---------- 2017-03-01 21:00:00 : 후평1동   19249 ----------


 ---------- 2017-03-01 22:00:00 : 강남동   19250 ----------


 ---------- 2017-03-02 07:00:00 : 동산면   19251 ----------


 ---------- 2017-03-02 18:00:00 : 소양동   19252 ----------


 ---------- 2017-03-03 06:00:00 : 근화동   19253 ----------


 ---------- 2017-03-03 07:00:00 : 강남동   19254 ----------


 ---------- 2017-03-03 08:00:00 : 퇴계동   19255 ----------


 ---------- 2017-03-03 13:00:00 : 동내면   19256 ----------


 ---------- 2017-03-03 16:00:00 : 소양동   19257 ----------


 ---------- 2017-03-04 00:00:00 : 조운동   19258 ----------


 ---------- 2017-03-04 07:00:00 : 후평1동   19259 ----------


 ---------- 2017-03-04 11:00:00 : 강남동   19260 ----------


 ---------- 2017-03-04 11:00:00 : 후평1동   19261 ----------


 ---------- 2017-03-04 14:00:00 : 남산면   19263 ----------


 ---------- 2017-03-04 14:00:00 : 신북읍   19265 ----------


 ---------- 2017-03-04 20:00:00 : 효자1동   19266 ----------


 ---------- 2017-03-05 07:00:00 : 북산면   19268 ----------


 ---------- 2017-03-05 09:00:00 : 효자1동   19270 ----------


 ---------- 2017-03-05 11:00:00 : 근화동   19271 ----------


 ---------- 2017-03-05 13:00:00 : 퇴계동   19272 ----------


 ---------- 2017-03-05 23:00:00 : 신사우동   19273 ----------


 ---------- 2017-03-06 09:00:00 : 동  면   19274 ----------


 ---------- 2017-03-06 10:00:00 : 교  동   19275 ----------


 ---------- 2017-03-06 14:00:00 : 남산면   19277 ----------


 ---------- 2017-03-06 15:00:00 : 동내면   19278 ----------


 ---------- 2017-03-06 16:00:00 : 남산면   19279 ----------


 ---------- 2017-03-06 20:00:00 : 강남동   19281 ----------


 ---------- 2017-03-06 22:00:00 : 교  동   19282 ----------


 ---------- 2017-03-07 00:00:00 : 효자1동   19283 ----------


 ---------- 2017-03-07 08:00:00 : 후평1동   19284 ----------


 ---------- 2017-03-07 13:00:00 : 근화동   19285 ----------


 ---------- 2017-03-07 15:00:00 : 소양동   19286 ----------


 ---------- 2017-03-08 01:00:00 : 퇴계동   19287 ----------


 ---------- 2017-03-08 14:00:00 : 남산면   19288 ----------


 ---------- 2017-03-08 19:00:00 : 근화동   19289 ----------


 ---------- 2017-03-08 21:00:00 : 효자1동   19290 ----------


 ---------- 2017-03-09 09:00:00 : 동내면   19291 ----------


 ---------- 2017-03-09 14:00:00 : 동내면   19292 ----------


 ---------- 2017-03-09 19:00:00 : 석사동   19293 ----------


 ---------- 2017-03-09 19:00:00 : 소양동   19294 ----------


 ---------- 2017-03-10 02:00:00 : 효자1동   19295 ----------


 ---------- 2017-03-10 05:00:00 : 후평1동   19296 ----------


 ---------- 2017-03-10 09:00:00 : 근화동   19297 ----------


 ---------- 2017-03-10 12:00:00 : 남산면   19299 ----------

 ---------- 2017-03-10 14:00:00 : 동내면   19300 ----------


 ---------- 2017-03-10 15:00:00 : 남산면   19301 ----------


 ---------- 2017-03-11 09:00:00 : 근화동   19302 ----------


 ---------- 2017-03-11 14:00:00 : 신사우동   19303 ----------


 ---------- 2017-03-11 15:00:00 : 사북면   19304 ----------


 ---------- 2017-03-12 00:00:00 : 후평1동   19305 ----------


 ---------- 2017-03-12 04:00:00 : 남  면   19306 ----------


 ---------- 2017-03-12 07:00:00 : 후평1동   19307 ----------


 ---------- 2017-03-12 12:00:00 : 후평1동   19308 ----------


 ---------- 2017-03-12 13:00:00 : 후평1동   19309 ----------


 ---------- 2017-03-12 15:00:00 : 후평1동   19310 ----------


 ---------- 2017-03-12 17:00:00 : 사북면   19311 ----------


 ---------- 2017-03-12 18:00:00 : 효자1동   19312 ----------


 ---------- 2017-03-12 20:00:00 : 동  면   19313 ----------


 ---------- 2017-03-13 15:00:00 : 동산면   19314 ----------


 ---------- 2017-03-13 16:00:00 : 퇴계동   19315 ----------


 ---------- 2017-03-13 23:00:00 : 효자1동   19316 ----------


 ---------- 2017-03-14 05:00:00 : 소양동   19317 ----------


 ---------- 2017-03-14 08:00:00 : 동내면   19318 ----------


 ---------- 2017-03-14 12:00:00 : 후평1동   19319 ----------


 ---------- 2017-03-14 14:00:00 : 남  면   19320 ----------


 ---------- 2017-03-14 18:00:00 : 동  면   19321 ----------


 ---------- 2017-03-15 01:00:00 : 효자1동   19322 ----------


 ---------- 2017-03-15 09:00:00 : 사북면   19323 ----------


 ---------- 2017-03-15 09:00:00 : 남산면   19324 ----------


 ---------- 2017-03-15 18:00:00 : 효자1동   19325 ----------


 ---------- 2017-03-16 02:00:00 : 강남동   19326 ----------


 ---------- 2017-03-16 02:00:00 : 조운동   19327 ----------


 ---------- 2017-03-16 03:00:00 : 후평1동   19328 ----------


 ---------- 2017-03-16 09:00:00 : 동내면   19329 ----------


 ---------- 2017-03-16 14:00:00 : 동내면   19330 ----------


 ---------- 2017-03-16 15:00:00 : 석사동   19332 ----------


 ---------- 2017-03-16 20:00:00 : 동내면   19333 ----------


 ---------- 2017-03-16 21:00:00 : 후평1동   19334 ----------


 ---------- 2017-03-17 08:00:00 : 퇴계동   19335 ----------


 ---------- 2017-03-17 15:00:00 : 동  면   19336 ----------


 ---------- 2017-03-17 15:00:00 : 퇴계동   19337 ----------


 ---------- 2017-03-18 02:00:00 : 석사동   19338 ----------


 ---------- 2017-03-18 16:00:00 : 효자1동   19339 ----------


 ---------- 2017-03-18 17:00:00 : 근화동   19341 ----------


 ---------- 2017-03-18 20:00:00 : 신북읍   19342 ----------


 ---------- 2017-03-18 23:00:00 : 석사동   19343 ----------


 ---------- 2017-03-19 00:00:00 : 동  면   19344 ----------


 ---------- 2017-03-19 10:00:00 : 후평1동   19345 ----------


 ---------- 2017-03-19 13:00:00 : 신북읍   19346 ----------


 ---------- 2017-03-19 19:00:00 : 서  면   19347 ----------


 ---------- 2017-03-20 11:00:00 : 효자1동   19348 ----------


 ---------- 2017-03-20 13:00:00 : 동내면   19349 ----------


 ---------- 2017-03-20 14:00:00 : 동산면   19350 ----------


 ---------- 2017-03-20 15:00:00 : 남  면   19351 ----------


 ---------- 2017-03-20 21:00:00 : 석사동   19353 ----------


 ---------- 2017-03-20 23:00:00 : 퇴계동   19354 ----------


 ---------- 2017-03-21 09:00:00 : 남산면   19355 ----------


 ---------- 2017-03-21 11:00:00 : 신사우동   19356 ----------


 ---------- 2017-03-21 20:00:00 : 남산면   19359 ----------


 ---------- 2017-03-22 10:00:00 : 신사우동   19360 ----------


 ---------- 2017-03-22 19:00:00 : 신사우동   19361 ----------


 ---------- 2017-03-22 22:00:00 : 동  면   19362 ----------


 ---------- 2017-03-23 09:00:00 : 동내면   19363 ----------


 ---------- 2017-03-23 14:00:00 : 동내면   19364 ----------


 ---------- 2017-03-23 16:00:00 : 서  면   19365 ----------


 ---------- 2017-03-24 07:00:00 : 신북읍   19366 ----------


 ---------- 2017-03-24 09:00:00 : 동내면   19367 ----------


 ---------- 2017-03-24 16:00:00 : 퇴계동   19368 ----------


 ---------- 2017-03-24 23:00:00 : 서  면   19370 ----------


 ---------- 2017-03-25 03:00:00 : 후평1동   19371 ----------


 ---------- 2017-03-25 10:00:00 : 남산면   19372 ----------


 ---------- 2017-03-25 14:00:00 : 동내면   19373 ----------


 ---------- 2017-03-26 09:00:00 : 남  면   19374 ----------


 ---------- 2017-03-26 10:00:00 : 조운동   19375 ----------


 ---------- 2017-03-26 15:00:00 : 북산면   19377 ----------


 ---------- 2017-03-27 04:00:00 : 신북읍   19378 ----------


 ---------- 2017-03-27 07:00:00 : 효자1동   19379 ----------


 ---------- 2017-03-27 09:00:00 : 동산면   19380 ----------


 ---------- 2017-03-27 23:00:00 : 동  면   19381 ----------


 ---------- 2017-03-28 14:00:00 : 교  동   19382 ----------


 ---------- 2017-03-29 00:00:00 : 효자1동   19384 ----------


 ---------- 2017-03-29 11:00:00 : 후평1동   19385 ----------


 ---------- 2017-03-29 12:00:00 : 효자1동   19386 ----------


 ---------- 2017-03-29 12:00:00 : 신사우동   19387 ----------


 ---------- 2017-03-29 16:00:00 : 석사동   19388 ----------


 ---------- 2017-03-29 18:00:00 : 근화동   19389 ----------


 ---------- 2017-03-30 16:00:00 : 강남동   19390 ----------


 ---------- 2017-03-31 04:00:00 : 후평1동   19391 ----------


 ---------- 2017-03-31 08:00:00 : 석사동   19392 ----------


 ---------- 2017-03-31 14:00:00 : 남산면   19393 ----------


 ---------- 2017-04-01 05:00:00 : 후평1동   19395 ----------


 ---------- 2017-04-01 08:00:00 : 후평1동   19396 ----------


 ---------- 2017-04-01 15:00:00 : 남  면   19398 ----------


 ---------- 2017-04-01 18:00:00 : 효자1동   19399 ----------


 ---------- 2017-04-02 16:00:00 : 석사동   19401 ----------


 ---------- 2017-04-02 16:00:00 : 효자1동   19402 ----------


 ---------- 2017-04-02 17:00:00 : 동내면   19403 ----------


 ---------- 2017-04-03 09:00:00 : 효자1동   19404 ----------


 ---------- 2017-04-03 12:00:00 : 후평1동   19405 ----------


 ---------- 2017-04-03 20:00:00 : 후평1동   19406 ----------


 ---------- 2017-04-04 07:00:00 : 퇴계동   19407 ----------


 ---------- 2017-04-04 12:00:00 : 동산면   19408 ----------


 ---------- 2017-04-04 16:00:00 : 후평1동   19409 ----------


 ---------- 2017-04-04 21:00:00 : 후평1동   19410 ----------


 ---------- 2017-04-05 09:00:00 : 석사동   19411 ----------


 ---------- 2017-04-05 17:00:00 : 동  면   19412 ----------


 ---------- 2017-04-05 18:00:00 : 후평1동   19413 ----------


 ---------- 2017-04-05 22:00:00 : 후평1동   19414 ----------


 ---------- 2017-04-06 09:00:00 : 남산면   19416 ----------


 ---------- 2017-04-06 10:00:00 : 동산면   19417 ----------


 ---------- 2017-04-06 13:00:00 : 소양동   19418 ----------


 ---------- 2017-04-06 21:00:00 : 후평1동   19419 ----------


 ---------- 2017-04-07 00:00:00 : 후평1동   19420 ----------


 ---------- 2017-04-07 08:00:00 : 효자1동   19421 ----------


 ---------- 2017-04-07 21:00:00 : 후평1동   19422 ----------


 ---------- 2017-04-08 02:00:00 : 퇴계동   19423 ----------


 ---------- 2017-04-09 12:00:00 : 퇴계동   19424 ----------


 ---------- 2017-04-09 16:00:00 : 동  면   19425 ----------


 ---------- 2017-04-10 09:00:00 : 후평1동   19427 ----------


 ---------- 2017-04-10 10:00:00 : 서  면   19428 ----------


 ---------- 2017-04-10 11:00:00 : 조운동   19429 ----------


 ---------- 2017-04-10 12:00:00 : 석사동   19430 ----------


 ---------- 2017-04-10 14:00:00 : 신동면   19431 ----------


 ---------- 2017-04-10 15:00:00 : 석사동   19433 ----------


 ---------- 2017-04-10 15:00:00 : 신동면   19434 ----------


 ---------- 2017-04-10 16:00:00 : 석사동   19437 ----------


 ---------- 2017-04-10 20:00:00 : 근화동   19438 ----------


 ---------- 2017-04-11 04:00:00 : 효자1동   19439 ----------


 ---------- 2017-04-11 07:00:00 : 동내면   19440 ----------


 ---------- 2017-04-11 08:00:00 : 신사우동   19441 ----------


 ---------- 2017-04-11 09:00:00 : 서  면   19442 ----------


 ---------- 2017-04-11 17:00:00 : 동내면   19443 ----------


 ---------- 2017-04-11 22:00:00 : 석사동   19444 ----------


 ---------- 2017-04-11 23:00:00 : 퇴계동   19445 ----------


 ---------- 2017-04-12 09:00:00 : 동내면   19446 ----------


 ---------- 2017-04-12 10:00:00 : 동  면   19447 ----------


 ---------- 2017-04-12 14:00:00 : 석사동   19448 ----------


 ---------- 2017-04-12 23:00:00 : 소양동   19449 ----------


 ---------- 2017-04-13 10:00:00 : 동내면   19450 ----------


 ---------- 2017-04-13 14:00:00 : 신북읍   19451 ----------

 ---------- 2017-04-13 18:00:00 : 조운동   19452 ----------


 ---------- 2017-04-13 21:00:00 : 신사우동   19453 ----------


 ---------- 2017-04-13 22:00:00 : 근화동   19454 ----------


 ---------- 2017-04-13 22:00:00 : 신북읍   19455 ----------


 ---------- 2017-04-14 07:00:00 : 동산면   19456 ----------


 ---------- 2017-04-14 14:00:00 : 강남동   19457 ----------


 ---------- 2017-04-14 14:00:00 : 효자1동   19458 ----------


 ---------- 2017-04-14 14:00:00 : 퇴계동   19459 ----------


 ---------- 2017-04-14 15:00:00 : 사북면   19460 ----------


 ---------- 2017-04-14 20:00:00 : 신북읍   19461 ----------


 ---------- 2017-04-15 15:00:00 : 동내면   19462 ----------


 ---------- 2017-04-15 16:00:00 : 퇴계동   19463 ----------


 ---------- 2017-04-15 17:00:00 : 후평1동   19464 ----------


 ---------- 2017-04-15 23:00:00 : 석사동   19465 ----------


 ---------- 2017-04-16 00:00:00 : 후평1동   19466 ----------


 ---------- 2017-04-16 07:00:00 : 서  면   19467 ----------


 ---------- 2017-04-16 10:00:00 : 근화동   19468 ----------


 ---------- 2017-04-16 13:00:00 : 약사명동   19469 ----------


 ---------- 2017-04-16 14:00:00 : 신동면   19470 ----------


 ---------- 2017-04-16 15:00:00 : 퇴계동   19471 ----------


 ---------- 2017-04-16 19:00:00 : 근화동   19473 ----------


 ---------- 2017-04-17 00:00:00 : 동내면   19474 ----------


 ---------- 2017-04-17 02:00:00 : 후평1동   19475 ----------


 ---------- 2017-04-17 08:00:00 : 동내면   19476 ----------


 ---------- 2017-04-17 09:00:00 : 동  면   19477 ----------


 ---------- 2017-04-17 10:00:00 : 석사동   19479 ----------


 ---------- 2017-04-17 15:00:00 : 동내면   19480 ----------


 ---------- 2017-04-17 17:00:00 : 동내면   19481 ----------


 ---------- 2017-04-17 18:00:00 : 동  면   19482 ----------


 ---------- 2017-04-18 06:00:00 : 후평1동   19483 ----------


 ---------- 2017-04-18 10:00:00 : 동내면   19484 ----------


 ---------- 2017-04-18 11:00:00 : 동산면   19485 ----------


 ---------- 2017-04-18 17:00:00 : 동산면   19487 ----------


 ---------- 2017-04-18 18:00:00 : 후평1동   19488 ----------


 ---------- 2017-04-18 19:00:00 : 동산면   19489 ----------


 ---------- 2017-04-18 23:00:00 : 석사동   19490 ----------


 ---------- 2017-04-18 23:00:00 : 강남동   19491 ----------


 ---------- 2017-04-19 18:00:00 : 동  면   19492 ----------


 ---------- 2017-04-19 20:00:00 : 사북면   19493 ----------


 ---------- 2017-04-19 22:00:00 : 후평1동   19494 ----------


 ---------- 2017-04-20 12:00:00 : 강남동   19495 ----------


 ---------- 2017-04-20 13:00:00 : 후평1동   19496 ----------


 ---------- 2017-04-20 13:00:00 : 퇴계동   19497 ----------


 ---------- 2017-04-20 23:00:00 : 후평1동   19498 ----------


 ---------- 2017-04-21 12:00:00 : 남산면   19501 ----------


 ---------- 2017-04-21 14:00:00 : 남산면   19503 ----------


 ---------- 2017-04-21 19:00:00 : 퇴계동   19504 ----------


 ---------- 2017-04-22 00:00:00 : 동  면   19505 ----------


 ---------- 2017-04-22 11:00:00 : 퇴계동   19506 ----------


 ---------- 2017-04-22 12:00:00 : 근화동   19507 ----------


 ---------- 2017-04-22 15:00:00 : 동내면   19508 ----------


 ---------- 2017-04-22 18:00:00 : 효자1동   19509 ----------


 ---------- 2017-04-22 23:00:00 : 남산면   19510 ----------


 ---------- 2017-04-23 10:00:00 : 신북읍   19511 ----------


 ---------- 2017-04-23 13:00:00 : 동내면   19513 ----------


 ---------- 2017-04-24 08:00:00 : 조운동   19514 ----------


 ---------- 2017-04-24 10:00:00 : 신사우동   19515 ----------


 ---------- 2017-04-24 20:00:00 : 신사우동   19516 ----------


 ---------- 2017-04-24 23:00:00 : 동내면   19518 ----------


 ---------- 2017-04-24 23:00:00 : 후평1동   19519 ----------


 ---------- 2017-04-25 12:00:00 : 동산면   19520 ----------


 ---------- 2017-04-25 14:00:00 : 남산면   19521 ----------


 ---------- 2017-04-25 17:00:00 : 후평1동   19522 ----------


 ---------- 2017-04-25 18:00:00 : 퇴계동   19523 ----------


 ---------- 2017-04-26 00:00:00 : 사북면   19524 ----------


 ---------- 2017-04-26 01:00:00 : 후평1동   19525 ----------


 ---------- 2017-04-26 06:00:00 : 강남동   19526 ----------


 ---------- 2017-04-26 10:00:00 : 동내면   19527 ----------


 ---------- 2017-04-26 10:00:00 : 근화동   19528 ----------


 ---------- 2017-04-26 11:00:00 : 퇴계동   19529 ----------


 ---------- 2017-04-26 14:00:00 : 퇴계동   19530 ----------


 ---------- 2017-04-26 18:00:00 : 후평1동   19531 ----------


 ---------- 2017-04-27 08:00:00 : 남산면   19532 ----------


 ---------- 2017-04-27 11:00:00 : 후평1동   19533 ----------


 ---------- 2017-04-27 14:00:00 : 신사우동   19534 ----------


 ---------- 2017-04-28 12:00:00 : 남산면   19535 ----------


 ---------- 2017-04-28 13:00:00 : 동내면   19536 ----------


 ---------- 2017-04-28 20:00:00 : 사북면   19537 ----------


 ---------- 2017-04-28 21:00:00 : 근화동   19538 ----------


 ---------- 2017-04-28 23:00:00 : 후평1동   19539 ----------


 ---------- 2017-04-29 03:00:00 : 후평1동   19540 ----------


 ---------- 2017-04-29 08:00:00 : 신사우동   19541 ----------


 ---------- 2017-04-29 09:00:00 : 퇴계동   19542 ----------


 ---------- 2017-04-29 12:00:00 : 북산면   19544 ----------


 ---------- 2017-04-29 14:00:00 : 북산면   19545 ----------


 ---------- 2017-04-29 15:00:00 : 북산면   19546 ----------


 ---------- 2017-04-29 20:00:00 : 효자1동   19547 ----------


 ---------- 2017-04-30 10:00:00 : 강남동   19548 ----------


 ---------- 2017-04-30 14:00:00 : 효자1동   19549 ----------


 ---------- 2017-04-30 15:00:00 : 근화동   19550 ----------


 ---------- 2017-04-30 18:00:00 : 소양동   19551 ----------


 ---------- 2017-04-30 22:00:00 : 효자1동   19552 ----------


 ---------- 2017-05-01 01:00:00 : 퇴계동   19553 ----------


 ---------- 2017-05-01 11:00:00 : 신북읍   19554 ----------


 ---------- 2017-05-01 16:00:00 : 후평1동   19555 ----------


 ---------- 2017-05-01 16:00:00 : 조운동   19556 ----------


 ---------- 2017-05-01 22:00:00 : 동  면   19557 ----------


 ---------- 2017-05-01 23:00:00 : 효자1동   19558 ----------


 ---------- 2017-05-02 09:00:00 : 남산면   19559 ----------


 ---------- 2017-05-02 12:00:00 : 남산면   19560 ----------


 ---------- 2017-05-02 15:00:00 : 조운동   19561 ----------


 ---------- 2017-05-02 18:00:00 : 서  면   19562 ----------


 ---------- 2017-05-02 19:00:00 : 강남동   19564 ----------


 ---------- 2017-05-02 19:00:00 : 동내면   19565 ----------


 ---------- 2017-05-03 08:00:00 : 후평1동   19566 ----------


 ---------- 2017-05-03 09:00:00 : 남산면   19567 ----------


 ---------- 2017-05-03 09:00:00 : 신사우동   19568 ----------


 ---------- 2017-05-03 13:00:00 : 신동면   19569 ----------


 ---------- 2017-05-03 14:00:00 : 남  면   19571 ----------


 ---------- 2017-05-03 16:00:00 : 서  면   19572 ----------


 ---------- 2017-05-03 16:00:00 : 북산면   19573 ----------


 ---------- 2017-05-03 18:00:00 : 동  면   19574 ----------


 ---------- 2017-05-03 19:00:00 : 효자1동   19576 ----------


 ---------- 2017-05-03 19:00:00 : 퇴계동   19577 ----------


 ---------- 2017-05-03 22:00:00 : 신북읍   19579 ----------


 ---------- 2017-05-04 08:00:00 : 효자1동   19580 ----------


 ---------- 2017-05-04 12:00:00 : 퇴계동   19581 ----------


 ---------- 2017-05-04 13:00:00 : 신북읍   19582 ----------


 ---------- 2017-05-04 14:00:00 : 동내면   19584 ----------


 ---------- 2017-05-04 19:00:00 : 동  면   19585 ----------


 ---------- 2017-05-04 22:00:00 : 소양동   19586 ----------


 ---------- 2017-05-05 01:00:00 : 석사동   19587 ----------


 ---------- 2017-05-05 14:00:00 : 신사우동   19588 ----------


 ---------- 2017-05-05 16:00:00 : 서  면   19589 ----------


 ---------- 2017-05-05 17:00:00 : 사북면   19590 ----------


 ---------- 2017-05-05 21:00:00 : 북산면   19591 ----------


 ---------- 2017-05-06 01:00:00 : 강남동   19593 ----------


 ---------- 2017-05-06 09:00:00 : 강남동   19594 ----------


 ---------- 2017-05-06 12:00:00 : 근화동   19595 ----------


 ---------- 2017-05-06 12:00:00 : 교  동   19596 ----------


 ---------- 2017-05-06 13:00:00 : 강남동   19597 ----------


 ---------- 2017-05-06 14:00:00 : 북산면   19598 ----------


 ---------- 2017-05-06 16:00:00 : 동  면   19599 ----------


 ---------- 2017-05-06 21:00:00 : 석사동   19600 ----------


 ---------- 2017-05-07 06:00:00 : 신북읍   19601 ----------


 ---------- 2017-05-07 07:00:00 : 효자1동   19602 ----------

 ---------- 2017-05-07 10:00:00 : 신사우동   19603 ----------


 ---------- 2017-05-07 13:00:00 : 동내면   19604 ----------


 ---------- 2017-05-07 16:00:00 : 교  동   19606 ----------


 ---------- 2017-05-07 18:00:00 : 후평1동   19607 ----------


 ---------- 2017-05-07 19:00:00 : 석사동   19608 ----------


 ---------- 2017-05-08 06:00:00 : 강남동   19609 ----------


 ---------- 2017-05-08 09:00:00 : 강남동   19610 ----------


 ---------- 2017-05-08 10:00:00 : 서  면   19611 ----------


 ---------- 2017-05-08 11:00:00 : 신북읍   19612 ----------


 ---------- 2017-05-08 18:00:00 : 남산면   19613 ----------


 ---------- 2017-05-08 19:00:00 : 조운동   19614 ----------


 ---------- 2017-05-08 23:00:00 : 석사동   19615 ----------


 ---------- 2017-05-09 13:00:00 : 후평1동   19616 ----------


 ---------- 2017-05-09 14:00:00 : 후평1동   19617 ----------


 ---------- 2017-05-09 16:00:00 : 동산면   19618 ----------


 ---------- 2017-05-09 23:00:00 : 동  면   19619 ----------


 ---------- 2017-05-10 09:00:00 : 효자1동   19620 ----------


 ---------- 2017-05-10 13:00:00 : 효자1동   19621 ----------


 ---------- 2017-05-10 14:00:00 : 서  면   19622 ----------


 ---------- 2017-05-10 16:00:00 : 퇴계동   19623 ----------


 ---------- 2017-05-10 17:00:00 : 소양동   19624 ----------


 ---------- 2017-05-10 18:00:00 : 석사동   19625 ----------


 ---------- 2017-05-10 19:00:00 : 동산면   19627 ----------


 ---------- 2017-05-10 20:00:00 : 강남동   19628 ----------


 ---------- 2017-05-11 00:00:00 : 후평1동   19629 ----------


 ---------- 2017-05-11 10:00:00 : 신북읍   19630 ----------


 ---------- 2017-05-11 15:00:00 : 신사우동   19631 ----------


 ---------- 2017-05-11 17:00:00 : 신동면   19632 ----------


 ---------- 2017-05-11 20:00:00 : 동  면   19633 ----------


 ---------- 2017-05-11 22:00:00 : 석사동   19634 ----------


 ---------- 2017-05-12 15:00:00 : 퇴계동   19635 ----------


 ---------- 2017-05-12 16:00:00 : 퇴계동   19636 ----------


 ---------- 2017-05-12 18:00:00 : 석사동   19637 ----------


 ---------- 2017-05-13 04:00:00 : 신사우동   19638 ----------


 ---------- 2017-05-13 07:00:00 : 동  면   19639 ----------


 ---------- 2017-05-13 09:00:00 : 남  면   19641 ----------


 ---------- 2017-05-13 14:00:00 : 동내면   19643 ----------


 ---------- 2017-05-13 15:00:00 : 동내면   19644 ----------


 ---------- 2017-05-13 15:00:00 : 약사명동   19646 ----------


 ---------- 2017-05-13 16:00:00 : 효자1동   19647 ----------


 ---------- 2017-05-13 16:00:00 : 신북읍   19648 ----------


 ---------- 2017-05-13 19:00:00 : 퇴계동   19649 ----------


 ---------- 2017-05-14 11:00:00 : 효자1동   19650 ----------


 ---------- 2017-05-14 12:00:00 : 퇴계동   19651 ----------


 ---------- 2017-05-14 13:00:00 : 후평1동   19652 ----------


 ---------- 2017-05-14 14:00:00 : 북산면   19654 ----------


 ---------- 2017-05-14 17:00:00 : 동내면   19655 ----------


 ---------- 2017-05-14 18:00:00 : 석사동   19656 ----------


 ---------- 2017-05-15 04:00:00 : 효자1동   19657 ----------


 ---------- 2017-05-15 12:00:00 : 신동면   19658 ----------


 ---------- 2017-05-15 15:00:00 : 후평1동   19659 ----------


 ---------- 2017-05-15 16:00:00 : 퇴계동   19660 ----------


 ---------- 2017-05-15 17:00:00 : 후평1동   19661 ----------


 ---------- 2017-05-15 18:00:00 : 동내면   19662 ----------


 ---------- 2017-05-15 18:00:00 : 퇴계동   19663 ----------


 ---------- 2017-05-15 21:00:00 : 근화동   19664 ----------


 ---------- 2017-05-15 21:00:00 : 후평1동   19665 ----------


 ---------- 2017-05-16 10:00:00 : 후평1동   19666 ----------


 ---------- 2017-05-16 11:00:00 : 효자1동   19667 ----------


 ---------- 2017-05-16 11:00:00 : 근화동   19670 ----------


 ---------- 2017-05-16 11:00:00 : 후평1동   19671 ----------


 ---------- 2017-05-16 12:00:00 : 서  면   19672 ----------


 ---------- 2017-05-16 15:00:00 : 후평1동   19673 ----------


 ---------- 2017-05-16 20:00:00 : 남산면   19674 ----------


 ---------- 2017-05-16 23:00:00 : 서  면   19676 ----------


 ---------- 2017-05-16 23:00:00 : 신사우동   19677 ----------


 ---------- 2017-05-17 11:00:00 : 동  면   19678 ----------


 ---------- 2017-05-17 15:00:00 : 효자1동   19679 ----------


 ---------- 2017-05-17 23:00:00 : 후평1동   19680 ----------


 ---------- 2017-05-18 08:00:00 : 남산면   19681 ----------


 ---------- 2017-05-18 08:00:00 : 퇴계동   19682 ----------


 ---------- 2017-05-18 09:00:00 : 동  면   19683 ----------


 ---------- 2017-05-18 09:00:00 : 후평1동   19684 ----------


 ---------- 2017-05-18 10:00:00 : 후평1동   19685 ----------


 ---------- 2017-05-18 11:00:00 : 교  동   19686 ----------


 ---------- 2017-05-18 13:00:00 : 효자1동   19688 ----------


 ---------- 2017-05-18 13:00:00 : 근화동   19689 ----------


 ---------- 2017-05-18 14:00:00 : 소양동   19690 ----------


 ---------- 2017-05-19 15:00:00 : 근화동   19691 ----------


 ---------- 2017-05-19 18:00:00 : 강남동   19692 ----------


 ---------- 2017-05-19 18:00:00 : 퇴계동   19693 ----------


 ---------- 2017-05-19 23:00:00 : 석사동   19694 ----------


 ---------- 2017-05-20 01:00:00 : 후평1동   19695 ----------


 ---------- 2017-05-20 02:00:00 : 강남동   19696 ----------


 ---------- 2017-05-20 09:00:00 : 석사동   19697 ----------


 ---------- 2017-05-20 12:00:00 : 서  면   19698 ----------


 ---------- 2017-05-20 18:00:00 : 조운동   19699 ----------


 ---------- 2017-05-20 20:00:00 : 사북면   19700 ----------


 ---------- 2017-05-21 10:00:00 : 퇴계동   19702 ----------


 ---------- 2017-05-21 11:00:00 : 북산면   19703 ----------


 ---------- 2017-05-21 14:00:00 : 남산면   19704 ----------


 ---------- 2017-05-21 18:00:00 : 퇴계동   19705 ----------


 ---------- 2017-05-22 00:00:00 : 근화동   19706 ----------


 ---------- 2017-05-22 09:00:00 : 근화동   19707 ----------


 ---------- 2017-05-22 10:00:00 : 후평1동   19708 ----------


 ---------- 2017-05-22 13:00:00 : 효자1동   19709 ----------


 ---------- 2017-05-22 15:00:00 : 동  면   19710 ----------


 ---------- 2017-05-22 19:00:00 : 석사동   19711 ----------


 ---------- 2017-05-22 23:00:00 : 석사동   19712 ----------


 ---------- 2017-05-23 09:00:00 : 소양동   19713 ----------


 ---------- 2017-05-23 09:00:00 : 동  면   19714 ----------


 ---------- 2017-05-23 10:00:00 : 신동면   19715 ----------


 ---------- 2017-05-23 12:00:00 : 남산면   19716 ----------


 ---------- 2017-05-23 12:00:00 : 후평1동   19717 ----------


 ---------- 2017-05-23 14:00:00 : 효자1동   19718 ----------


 ---------- 2017-05-23 20:00:00 : 신동면   19719 ----------


 ---------- 2017-05-23 22:00:00 : 효자1동   19720 ----------


 ---------- 2017-05-23 23:00:00 : 근화동   19721 ----------


 ---------- 2017-05-24 00:00:00 : 퇴계동   19722 ----------


 ---------- 2017-05-24 13:00:00 : 서  면   19723 ----------


 ---------- 2017-05-24 14:00:00 : 남산면   19724 ----------


 ---------- 2017-05-24 14:00:00 : 근화동   19725 ----------


 ---------- 2017-05-24 15:00:00 : 남산면   19726 ----------


 ---------- 2017-05-24 16:00:00 : 석사동   19729 ----------


 ---------- 2017-05-24 21:00:00 : 석사동   19730 ----------


 ---------- 2017-05-24 22:00:00 : 효자1동   19731 ----------


 ---------- 2017-05-25 00:00:00 : 퇴계동   19732 ----------


 ---------- 2017-05-25 08:00:00 : 서  면   19733 ----------


 ---------- 2017-05-25 15:00:00 : 동내면   19734 ----------


 ---------- 2017-05-25 16:00:00 : 강남동   19735 ----------


 ---------- 2017-05-25 23:00:00 : 후평1동   19736 ----------


 ---------- 2017-05-26 09:00:00 : 서  면   19737 ----------


 ---------- 2017-05-26 10:00:00 : 효자1동   19738 ----------


 ---------- 2017-05-26 10:00:00 : 동  면   19739 ----------


 ---------- 2017-05-26 10:00:00 : 퇴계동   19740 ----------


 ---------- 2017-05-26 11:00:00 : 신사우동   19741 ----------


 ---------- 2017-05-26 23:00:00 : 효자1동   19742 ----------


 ---------- 2017-05-27 00:00:00 : 석사동   19743 ----------


 ---------- 2017-05-27 14:00:00 : 서  면   19744 ----------


 ---------- 2017-05-27 14:00:00 : 사북면   19745 ----------


 ---------- 2017-05-27 15:00:00 : 신동면   19746 ----------


 ---------- 2017-05-27 18:00:00 : 신동면   19747 ----------


 ---------- 2017-05-27 22:00:00 : 효자1동   19748 ----------


 ---------- 2017-05-28 03:00:00 : 석사동   19749 ----------


 ---------- 2017-05-28 11:00:00 : 동  면   19750 ----------


 ---------- 2017-05-28 18:00:00 : 강남동   19751 ----------

 ---------- 2017-05-29 08:00:00 : 신사우동   19752 ----------


 ---------- 2017-05-29 08:00:00 : 후평1동   19753 ----------


 ---------- 2017-05-29 11:00:00 : 소양동   19754 ----------


 ---------- 2017-05-29 13:00:00 : 동산면   19755 ----------


 ---------- 2017-05-29 15:00:00 : 신북읍   19756 ----------


 ---------- 2017-05-30 09:00:00 : 사북면   19757 ----------


 ---------- 2017-05-30 10:00:00 : 신사우동   19758 ----------


 ---------- 2017-05-30 16:00:00 : 효자1동   19759 ----------


 ---------- 2017-05-30 18:00:00 : 후평1동   19760 ----------


 ---------- 2017-05-30 20:00:00 : 강남동   19761 ----------


 ---------- 2017-05-30 22:00:00 : 효자1동   19762 ----------


 ---------- 2017-05-30 23:00:00 : 효자1동   19763 ----------


 ---------- 2017-05-31 02:00:00 : 효자1동   19766 ----------


 ---------- 2017-05-31 14:00:00 : 동산면   19767 ----------


 ---------- 2017-05-31 15:00:00 : 동  면   19768 ----------


 ---------- 2017-05-31 16:00:00 : 동산면   19769 ----------


 ---------- 2017-05-31 21:00:00 : 효자1동   19770 ----------


 ---------- 2017-05-31 22:00:00 : 후평1동   19771 ----------


 ---------- 2017-05-31 23:00:00 : 퇴계동   19772 ----------


 ---------- 2017-06-01 06:00:00 : 동  면   19773 ----------


 ---------- 2017-06-01 12:00:00 : 강남동   19774 ----------


 ---------- 2017-06-01 14:00:00 : 동내면   19775 ----------


 ---------- 2017-06-01 14:00:00 : 남산면   19776 ----------


 ---------- 2017-06-01 14:00:00 : 후평1동   19777 ----------


 ---------- 2017-06-01 20:00:00 : 소양동   19778 ----------


 ---------- 2017-06-02 02:00:00 : 강남동   19779 ----------


 ---------- 2017-06-02 05:00:00 : 동내면   19780 ----------


 ---------- 2017-06-02 07:00:00 : 효자1동   19781 ----------


 ---------- 2017-06-02 10:00:00 : 동  면   19782 ----------


 ---------- 2017-06-02 18:00:00 : 동내면   19783 ----------


 ---------- 2017-06-03 00:00:00 : 동  면   19784 ----------


 ---------- 2017-06-03 03:00:00 : 신사우동   19785 ----------


 ---------- 2017-06-03 06:00:00 : 신북읍   19786 ----------


 ---------- 2017-06-03 09:00:00 : 남산면   19787 ----------


 ---------- 2017-06-03 09:00:00 : 신북읍   19789 ----------


 ---------- 2017-06-03 10:00:00 : 소양동   19790 ----------


 ---------- 2017-06-03 12:00:00 : 약사명동   19791 ----------


 ---------- 2017-06-03 14:00:00 : 북산면   19793 ----------


 ---------- 2017-06-03 15:00:00 : 효자1동   19794 ----------


 ---------- 2017-06-03 17:00:00 : 신북읍   19795 ----------


 ---------- 2017-06-03 18:00:00 : 소양동   19796 ----------


 ---------- 2017-06-03 20:00:00 : 석사동   19797 ----------


 ---------- 2017-06-04 11:00:00 : 후평1동   19798 ----------


 ---------- 2017-06-04 19:00:00 : 효자1동   19799 ----------


 ---------- 2017-06-04 20:00:00 : 석사동   19800 ----------


 ---------- 2017-06-04 20:00:00 : 근화동   19801 ----------


 ---------- 2017-06-04 23:00:00 : 효자1동   19802 ----------


 ---------- 2017-06-05 00:00:00 : 후평1동   19803 ----------


 ---------- 2017-06-05 07:00:00 : 신사우동   19804 ----------


 ---------- 2017-06-05 07:00:00 : 후평1동   19805 ----------


 ---------- 2017-06-05 10:00:00 : 효자1동   19806 ----------


 ---------- 2017-06-05 12:00:00 : 신북읍   19807 ----------


 ---------- 2017-06-05 12:00:00 : 소양동   19808 ----------


 ---------- 2017-06-05 12:00:00 : 후평1동   19809 ----------


 ---------- 2017-06-05 13:00:00 : 후평1동   19810 ----------


 ---------- 2017-06-05 13:00:00 : 동산면   19811 ----------


 ---------- 2017-06-05 18:00:00 : 후평1동   19812 ----------


 ---------- 2017-06-05 20:00:00 : 석사동   19813 ----------


 ---------- 2017-06-05 23:00:00 : 남산면   19814 ----------


 ---------- 2017-06-06 00:00:00 : 신사우동   19815 ----------


 ---------- 2017-06-06 09:00:00 : 동내면   19816 ----------


 ---------- 2017-06-06 09:00:00 : 신북읍   19818 ----------


 ---------- 2017-06-06 15:00:00 : 신사우동   19819 ----------


 ---------- 2017-06-07 09:00:00 : 소양동   19820 ----------


 ---------- 2017-06-07 09:00:00 : 동산면   19821 ----------


 ---------- 2017-06-07 14:00:00 : 동산면   19822 ----------


 ---------- 2017-06-07 15:00:00 : 조운동   19823 ----------


 ---------- 2017-06-07 17:00:00 : 효자1동   19824 ----------


 ---------- 2017-06-07 17:00:00 : 후평1동   19825 ----------


 ---------- 2017-06-07 19:00:00 : 석사동   19826 ----------


 ---------- 2017-06-07 21:00:00 : 동내면   19827 ----------


 ---------- 2017-06-07 23:00:00 : 후평1동   19828 ----------


 ---------- 2017-06-08 10:00:00 : 석사동   19829 ----------


 ---------- 2017-06-08 13:00:00 : 신동면   19830 ----------


 ---------- 2017-06-08 14:00:00 : 후평1동   19831 ----------


 ---------- 2017-06-08 14:00:00 : 동산면   19832 ----------


 ---------- 2017-06-08 15:00:00 : 석사동   19833 ----------


 ---------- 2017-06-08 17:00:00 : 신사우동   19834 ----------


 ---------- 2017-06-08 17:00:00 : 퇴계동   19836 ----------


 ---------- 2017-06-08 22:00:00 : 효자1동   19837 ----------


 ---------- 2017-06-09 09:00:00 : 후평1동   19838 ----------


 ---------- 2017-06-09 10:00:00 : 석사동   19839 ----------


 ---------- 2017-06-09 11:00:00 : 남산면   19840 ----------


 ---------- 2017-06-09 13:00:00 : 서  면   19841 ----------


 ---------- 2017-06-09 14:00:00 : 후평1동   19842 ----------


 ---------- 2017-06-09 16:00:00 : 효자1동   19843 ----------


 ---------- 2017-06-09 18:00:00 : 남산면   19845 ----------


 ---------- 2017-06-10 08:00:00 : 후평1동   19847 ----------


 ---------- 2017-06-10 13:00:00 : 서  면   19848 ----------


 ---------- 2017-06-10 14:00:00 : 신동면   19850 ----------


 ---------- 2017-06-10 14:00:00 : 효자1동   19851 ----------


 ---------- 2017-06-10 23:00:00 : 신사우동   19852 ----------


 ---------- 2017-06-11 05:00:00 : 동내면   19853 ----------


 ---------- 2017-06-11 06:00:00 : 신사우동   19854 ----------


 ---------- 2017-06-11 09:00:00 : 강남동   19855 ----------


 ---------- 2017-06-11 10:00:00 : 조운동   19856 ----------


 ---------- 2017-06-11 12:00:00 : 강남동   19857 ----------


 ---------- 2017-06-11 12:00:00 : 남  면   19858 ----------


 ---------- 2017-06-11 15:00:00 : 근화동   19859 ----------


 ---------- 2017-06-11 17:00:00 : 동산면   19860 ----------


 ---------- 2017-06-11 18:00:00 : 후평1동   19861 ----------


 ---------- 2017-06-11 21:00:00 : 신사우동   19862 ----------


 ---------- 2017-06-12 08:00:00 : 근화동   19863 ----------


 ---------- 2017-06-12 09:00:00 : 석사동   19864 ----------


 ---------- 2017-06-12 09:00:00 : 퇴계동   19865 ----------


 ---------- 2017-06-12 12:00:00 : 신사우동   19866 ----------


 ---------- 2017-06-12 12:00:00 : 후평1동   19867 ----------


 ---------- 2017-06-12 15:00:00 : 석사동   19868 ----------


 ---------- 2017-06-12 17:00:00 : 동산면   19870 ----------


 ---------- 2017-06-13 01:00:00 : 동내면   19871 ----------


 ---------- 2017-06-13 01:00:00 : 신사우동   19873 ----------


 ---------- 2017-06-13 06:00:00 : 효자1동   19875 ----------


 ---------- 2017-06-13 09:00:00 : 남산면   19876 ----------


 ---------- 2017-06-13 10:00:00 : 퇴계동   19877 ----------


 ---------- 2017-06-13 11:00:00 : 서  면   19878 ----------


 ---------- 2017-06-13 12:00:00 : 효자1동   19879 ----------


 ---------- 2017-06-13 15:00:00 : 동산면   19880 ----------


 ---------- 2017-06-13 23:00:00 : 신사우동   19881 ----------


 ---------- 2017-06-14 08:00:00 : 효자1동   19882 ----------


 ---------- 2017-06-14 09:00:00 : 근화동   19883 ----------


 ---------- 2017-06-14 12:00:00 : 조운동   19884 ----------


 ---------- 2017-06-14 14:00:00 : 신동면   19885 ----------


 ---------- 2017-06-14 14:00:00 : 근화동   19886 ----------


 ---------- 2017-06-14 20:00:00 : 강남동   19887 ----------


 ---------- 2017-06-14 21:00:00 : 약사명동   19888 ----------


 ---------- 2017-06-15 09:00:00 : 동내면   19889 ----------


 ---------- 2017-06-15 10:00:00 : 근화동   19890 ----------


 ---------- 2017-06-15 15:00:00 : 동산면   19891 ----------


 ---------- 2017-06-15 17:00:00 : 강남동   19892 ----------


 ---------- 2017-06-15 18:00:00 : 석사동   19893 ----------


 ---------- 2017-06-15 18:00:00 : 동  면   19894 ----------


 ---------- 2017-06-15 18:00:00 : 후평1동   19895 ----------


 ---------- 2017-06-15 20:00:00 : 후평1동   19896 ----------


 ---------- 2017-06-16 08:00:00 : 석사동   19897 ----------


 ---------- 2017-06-16 09:00:00 : 동내면   19898 ----------


 ---------- 2017-06-16 18:00:00 : 서  면   19900 ----------

 ---------- 2017-06-17 00:00:00 : 퇴계동   19901 ----------


 ---------- 2017-06-17 07:00:00 : 후평1동   19902 ----------


 ---------- 2017-06-17 09:00:00 : 동산면   19903 ----------


 ---------- 2017-06-17 10:00:00 : 강남동   19904 ----------


 ---------- 2017-06-17 10:00:00 : 동내면   19905 ----------


 ---------- 2017-06-17 12:00:00 : 신동면   19906 ----------


 ---------- 2017-06-17 16:00:00 : 동산면   19907 ----------


 ---------- 2017-06-17 19:00:00 : 북산면   19908 ----------


 ---------- 2017-06-17 23:00:00 : 퇴계동   19909 ----------


 ---------- 2017-06-18 01:00:00 : 북산면   19910 ----------


 ---------- 2017-06-18 02:00:00 : 남산면   19911 ----------


 ---------- 2017-06-18 08:00:00 : 동내면   19912 ----------


 ---------- 2017-06-18 10:00:00 : 근화동   19913 ----------


 ---------- 2017-06-18 11:00:00 : 남산면   19914 ----------


 ---------- 2017-06-18 15:00:00 : 동  면   19915 ----------


 ---------- 2017-06-18 16:00:00 : 동산면   19916 ----------


 ---------- 2017-06-18 17:00:00 : 동산면   19917 ----------


 ---------- 2017-06-18 18:00:00 : 신동면   19918 ----------


 ---------- 2017-06-18 18:00:00 : 신북읍   19919 ----------


 ---------- 2017-06-18 19:00:00 : 소양동   19920 ----------


 ---------- 2017-06-18 20:00:00 : 효자1동   19921 ----------


 ---------- 2017-06-18 21:00:00 : 효자1동   19923 ----------


 ---------- 2017-06-19 04:00:00 : 후평1동   19924 ----------


 ---------- 2017-06-19 06:00:00 : 근화동   19925 ----------


 ---------- 2017-06-19 07:00:00 : 동내면   19927 ----------


 ---------- 2017-06-19 11:00:00 : 후평1동   19928 ----------


 ---------- 2017-06-19 12:00:00 : 신북읍   19929 ----------


 ---------- 2017-06-19 13:00:00 : 효자1동   19930 ----------


 ---------- 2017-06-19 14:00:00 : 석사동   19931 ----------


 ---------- 2017-06-19 14:00:00 : 신동면   19932 ----------


 ---------- 2017-06-19 14:00:00 : 사북면   19933 ----------


 ---------- 2017-06-19 14:00:00 : 효자1동   19934 ----------


 ---------- 2017-06-19 14:00:00 : 신북읍   19935 ----------


 ---------- 2017-06-19 16:00:00 : 신사우동   19936 ----------


 ---------- 2017-06-19 16:00:00 : 동산면   19937 ----------


 ---------- 2017-06-19 18:00:00 : 교  동   19938 ----------


 ---------- 2017-06-19 19:00:00 : 석사동   19939 ----------


 ---------- 2017-06-19 20:00:00 : 퇴계동   19940 ----------


 ---------- 2017-06-20 09:00:00 : 동내면   19942 ----------


 ---------- 2017-06-20 14:00:00 : 남산면   19943 ----------


 ---------- 2017-06-20 15:00:00 : 동  면   19944 ----------


 ---------- 2017-06-20 16:00:00 : 효자1동   19945 ----------


 ---------- 2017-06-20 17:00:00 : 동내면   19946 ----------


 ---------- 2017-06-20 18:00:00 : 남산면   19947 ----------


 ---------- 2017-06-20 18:00:00 : 동산면   19948 ----------


 ---------- 2017-06-20 19:00:00 : 후평1동   19949 ----------


 ---------- 2017-06-20 20:00:00 : 퇴계동   19950 ----------


 ---------- 2017-06-20 22:00:00 : 서  면   19951 ----------


 ---------- 2017-06-21 01:00:00 : 후평1동   19952 ----------


 ---------- 2017-06-21 03:00:00 : 강남동   19953 ----------


 ---------- 2017-06-21 08:00:00 : 남산면   19954 ----------


 ---------- 2017-06-21 08:00:00 : 동  면   19955 ----------


 ---------- 2017-06-21 09:00:00 : 동  면   19956 ----------


 ---------- 2017-06-21 10:00:00 : 석사동   19957 ----------


 ---------- 2017-06-21 10:00:00 : 사북면   19958 ----------


 ---------- 2017-06-21 11:00:00 : 강남동   19959 ----------


 ---------- 2017-06-21 14:00:00 : 동산면   19960 ----------


 ---------- 2017-06-21 15:00:00 : 사북면   19961 ----------


 ---------- 2017-06-21 15:00:00 : 동  면   19962 ----------


 ---------- 2017-06-21 15:00:00 : 동산면   19963 ----------


 ---------- 2017-06-21 19:00:00 : 퇴계동   19964 ----------


 ---------- 2017-06-21 20:00:00 : 동내면   19965 ----------


 ---------- 2017-06-22 01:00:00 : 퇴계동   19966 ----------


 ---------- 2017-06-22 09:00:00 : 신북읍   19967 ----------


 ---------- 2017-06-22 11:00:00 : 서  면   19968 ----------


 ---------- 2017-06-22 11:00:00 : 동산면   19969 ----------


 ---------- 2017-06-22 12:00:00 : 서  면   19972 ----------


 ---------- 2017-06-22 15:00:00 : 조운동   19973 ----------


 ---------- 2017-06-22 16:00:00 : 사북면   19975 ----------


 ---------- 2017-06-22 16:00:00 : 동산면   19976 ----------


 ---------- 2017-06-22 17:00:00 : 남산면   19977 ----------


 ---------- 2017-06-22 17:00:00 : 동  면   19978 ----------


 ---------- 2017-06-22 18:00:00 : 석사동   19979 ----------


 ---------- 2017-06-22 18:00:00 : 근화동   19980 ----------


 ---------- 2017-06-22 19:00:00 : 퇴계동   19981 ----------


 ---------- 2017-06-22 20:00:00 : 효자1동   19982 ----------


 ---------- 2017-06-22 23:00:00 : 퇴계동   19983 ----------


 ---------- 2017-06-23 00:00:00 : 소양동   19984 ----------


 ---------- 2017-06-23 00:00:00 : 동  면   19985 ----------


 ---------- 2017-06-23 01:00:00 : 효자1동   19986 ----------


 ---------- 2017-06-23 08:00:00 : 석사동   19987 ----------


 ---------- 2017-06-23 08:00:00 : 약사명동   19988 ----------


 ---------- 2017-06-23 09:00:00 : 석사동   19989 ----------


 ---------- 2017-06-23 09:00:00 : 후평1동   19990 ----------


 ---------- 2017-06-23 10:00:00 : 동산면   19991 ----------


 ---------- 2017-06-23 14:00:00 : 강남동   19992 ----------


 ---------- 2017-06-23 16:00:00 : 사북면   19993 ----------


 ---------- 2017-06-23 16:00:00 : 동  면   19994 ----------


 ---------- 2017-06-23 18:00:00 : 석사동   19995 ----------


 ---------- 2017-06-23 19:00:00 : 동산면   19996 ----------


 ---------- 2017-06-23 21:00:00 : 석사동   19997 ----------


 ---------- 2017-06-23 23:00:00 : 강남동   19998 ----------


 ---------- 2017-06-24 02:00:00 : 약사명동   19999 ----------


 ---------- 2017-06-24 06:00:00 : 서  면   20000 ----------


 ---------- 2017-06-24 06:00:00 : 후평1동   20001 ----------


 ---------- 2017-06-24 07:00:00 : 약사명동   20002 ----------


 ---------- 2017-06-24 08:00:00 : 서  면   20003 ----------


 ---------- 2017-06-24 09:00:00 : 동산면   20004 ----------


 ---------- 2017-06-24 10:00:00 : 신사우동   20005 ----------


 ---------- 2017-06-24 11:00:00 : 신사우동   20006 ----------


 ---------- 2017-06-24 11:00:00 : 후평1동   20007 ----------


 ---------- 2017-06-24 13:00:00 : 서  면   20008 ----------


 ---------- 2017-06-24 14:00:00 : 후평1동   20009 ----------


 ---------- 2017-06-24 15:00:00 : 강남동   20010 ----------


 ---------- 2017-06-24 16:00:00 : 남산면   20011 ----------


 ---------- 2017-06-24 16:00:00 : 북산면   20014 ----------


 ---------- 2017-06-24 16:00:00 : 동산면   20015 ----------


 ---------- 2017-06-24 18:00:00 : 남산면   20016 ----------


 ---------- 2017-06-24 18:00:00 : 약사명동   20017 ----------


 ---------- 2017-06-24 18:00:00 : 동  면   20018 ----------


 ---------- 2017-06-25 00:00:00 : 사북면   20019 ----------


 ---------- 2017-06-25 08:00:00 : 석사동   20021 ----------


 ---------- 2017-06-25 08:00:00 : 남산면   20022 ----------


 ---------- 2017-06-25 09:00:00 : 동내면   20024 ----------


 ---------- 2017-06-25 10:00:00 : 남산면   20025 ----------


 ---------- 2017-06-25 11:00:00 : 동  면   20026 ----------


 ---------- 2017-06-25 12:00:00 : 강남동   20027 ----------


 ---------- 2017-06-25 14:00:00 : 서  면   20028 ----------


 ---------- 2017-06-25 17:00:00 : 석사동   20029 ----------


 ---------- 2017-06-25 17:00:00 : 남산면   20030 ----------


 ---------- 2017-06-25 20:00:00 : 효자1동   20031 ----------


 ---------- 2017-06-26 04:00:00 : 효자1동   20032 ----------


 ---------- 2017-06-26 08:00:00 : 강남동   20033 ----------


 ---------- 2017-06-26 08:00:00 : 후평1동   20034 ----------


 ---------- 2017-06-26 10:00:00 : 신북읍   20035 ----------


 ---------- 2017-06-26 10:00:00 : 퇴계동   20036 ----------


 ---------- 2017-06-26 11:00:00 : 강남동   20037 ----------


 ---------- 2017-06-26 11:00:00 : 동내면   20038 ----------


 ---------- 2017-06-26 12:00:00 : 동내면   20039 ----------


 ---------- 2017-06-26 13:00:00 : 효자1동   20040 ----------


 ---------- 2017-06-26 13:00:00 : 소양동   20041 ----------


 ---------- 2017-06-26 15:00:00 : 동산면   20042 ----------


 ---------- 2017-06-26 20:00:00 : 석사동   20043 ----------


 ---------- 2017-06-26 20:00:00 : 후평1동   20044 ----------


 ---------- 2017-06-27 10:00:00 : 동  면   20046 ----------


 ---------- 2017-06-27 11:00:00 : 동내면   20047 ----------

 ---------- 2017-06-27 12:00:00 : 석사동   20048 ----------


 ---------- 2017-06-27 13:00:00 : 석사동   20049 ----------


 ---------- 2017-06-27 13:00:00 : 퇴계동   20050 ----------


 ---------- 2017-06-27 14:00:00 : 동  면   20051 ----------


 ---------- 2017-06-27 15:00:00 : 석사동   20052 ----------


 ---------- 2017-06-27 16:00:00 : 근화동   20053 ----------


 ---------- 2017-06-27 16:00:00 : 동산면   20054 ----------


 ---------- 2017-06-27 17:00:00 : 동  면   20055 ----------


 ---------- 2017-06-27 19:00:00 : 약사명동   20056 ----------


 ---------- 2017-06-27 19:00:00 : 후평1동   20057 ----------


 ---------- 2017-06-27 21:00:00 : 동산면   20058 ----------


 ---------- 2017-06-28 04:00:00 : 동  면   20060 ----------


 ---------- 2017-06-28 08:00:00 : 동내면   20061 ----------


 ---------- 2017-06-28 08:00:00 : 남산면   20062 ----------


 ---------- 2017-06-28 14:00:00 : 약사명동   20063 ----------


 ---------- 2017-06-28 16:00:00 : 동산면   20064 ----------


 ---------- 2017-06-28 18:00:00 : 서  면   20065 ----------


 ---------- 2017-06-28 18:00:00 : 조운동   20066 ----------


 ---------- 2017-06-28 19:00:00 : 퇴계동   20067 ----------


 ---------- 2017-06-28 23:00:00 : 강남동   20068 ----------


 ---------- 2017-06-28 23:00:00 : 근화동   20069 ----------


 ---------- 2017-06-29 06:00:00 : 후평1동   20070 ----------


 ---------- 2017-06-29 07:00:00 : 퇴계동   20071 ----------


 ---------- 2017-06-29 09:00:00 : 남산면   20072 ----------


 ---------- 2017-06-29 09:00:00 : 퇴계동   20073 ----------


 ---------- 2017-06-29 12:00:00 : 후평1동   20075 ----------


 ---------- 2017-06-29 14:00:00 : 남산면   20076 ----------


 ---------- 2017-06-29 15:00:00 : 남산면   20077 ----------


 ---------- 2017-06-29 15:00:00 : 신북읍   20078 ----------


 ---------- 2017-06-29 16:00:00 : 동내면   20079 ----------


 ---------- 2017-06-29 16:00:00 : 동산면   20080 ----------


 ---------- 2017-06-29 17:00:00 : 석사동   20081 ----------


 ---------- 2017-06-29 19:00:00 : 강남동   20082 ----------


 ---------- 2017-06-29 21:00:00 : 효자1동   20083 ----------


 ---------- 2017-06-29 23:00:00 : 동  면   20084 ----------


 ---------- 2017-06-30 05:00:00 : 북산면   20085 ----------


 ---------- 2017-06-30 07:00:00 : 남산면   20086 ----------


 ---------- 2017-06-30 09:00:00 : 서  면   20087 ----------


 ---------- 2017-06-30 09:00:00 : 남산면   20088 ----------


 ---------- 2017-06-30 09:00:00 : 신사우동   20089 ----------


 ---------- 2017-06-30 10:00:00 : 근화동   20090 ----------


 ---------- 2017-06-30 10:00:00 : 후평1동   20091 ----------


 ---------- 2017-06-30 11:00:00 : 효자1동   20092 ----------


 ---------- 2017-06-30 12:00:00 : 남산면   20093 ----------


 ---------- 2017-06-30 13:00:00 : 강남동   20094 ----------


 ---------- 2017-06-30 13:00:00 : 남산면   20095 ----------


 ---------- 2017-06-30 15:00:00 : 효자1동   20096 ----------


 ---------- 2017-06-30 16:00:00 : 근화동   20097 ----------


 ---------- 2017-06-30 18:00:00 : 후평1동   20098 ----------


 ---------- 2017-06-30 19:00:00 : 후평1동   20099 ----------


 ---------- 2017-06-30 20:00:00 : 남산면   20101 ----------


 ---------- 2017-07-01 08:00:00 : 남산면   20102 ----------


 ---------- 2017-07-01 08:00:00 : 후평1동   20103 ----------


 ---------- 2017-07-01 09:00:00 : 신동면   20104 ----------


 ---------- 2017-07-01 09:00:00 : 동내면   20105 ----------


 ---------- 2017-07-01 09:00:00 : 소양동   20106 ----------


 ---------- 2017-07-01 10:00:00 : 효자1동   20107 ----------


 ---------- 2017-07-01 10:00:00 : 신북읍   20108 ----------


 ---------- 2017-07-01 11:00:00 : 신북읍   20109 ----------


 ---------- 2017-07-01 12:00:00 : 남산면   20110 ----------


 ---------- 2017-07-01 13:00:00 : 동산면   20111 ----------


 ---------- 2017-07-01 17:00:00 : 신사우동   20112 ----------


 ---------- 2017-07-01 17:00:00 : 동산면   20113 ----------


 ---------- 2017-07-01 18:00:00 : 후평1동   20114 ----------


 ---------- 2017-07-01 20:00:00 : 근화동   20115 ----------


 ---------- 2017-07-01 20:00:00 : 후평1동   20116 ----------


 ---------- 2017-07-01 21:00:00 : 후평1동   20117 ----------


 ---------- 2017-07-01 22:00:00 : 퇴계동   20118 ----------


 ---------- 2017-07-02 07:00:00 : 서  면   20119 ----------


 ---------- 2017-07-02 08:00:00 : 동내면   20120 ----------


 ---------- 2017-07-02 11:00:00 : 동  면   20121 ----------


 ---------- 2017-07-02 12:00:00 : 동  면   20122 ----------


 ---------- 2017-07-02 13:00:00 : 동산면   20123 ----------


 ---------- 2017-07-02 15:00:00 : 강남동   20124 ----------


 ---------- 2017-07-02 15:00:00 : 후평1동   20126 ----------


 ---------- 2017-07-02 16:00:00 : 강남동   20128 ----------


 ---------- 2017-07-02 17:00:00 : 사북면   20130 ----------


 ---------- 2017-07-02 18:00:00 : 퇴계동   20131 ----------


 ---------- 2017-07-02 19:00:00 : 후평1동   20132 ----------


 ---------- 2017-07-02 21:00:00 : 석사동   20133 ----------


 ---------- 2017-07-02 21:00:00 : 근화동   20134 ----------


 ---------- 2017-07-02 22:00:00 : 퇴계동   20135 ----------


 ---------- 2017-07-03 02:00:00 : 근화동   20137 ----------


 ---------- 2017-07-03 09:00:00 : 석사동   20138 ----------


 ---------- 2017-07-03 09:00:00 : 효자1동   20139 ----------


 ---------- 2017-07-03 10:00:00 : 동  면   20140 ----------


 ---------- 2017-07-03 12:00:00 : 후평1동   20141 ----------


 ---------- 2017-07-03 13:00:00 : 강남동   20142 ----------


 ---------- 2017-07-03 13:00:00 : 동  면   20143 ----------


 ---------- 2017-07-03 13:00:00 : 퇴계동   20144 ----------


 ---------- 2017-07-03 15:00:00 : 강남동   20146 ----------


 ---------- 2017-07-03 15:00:00 : 동내면   20147 ----------


 ---------- 2017-07-03 15:00:00 : 남산면   20148 ----------


 ---------- 2017-07-03 16:00:00 : 강남동   20149 ----------


 ---------- 2017-07-03 16:00:00 : 남산면   20150 ----------


 ---------- 2017-07-03 18:00:00 : 후평1동   20151 ----------


 ---------- 2017-07-03 20:00:00 : 강남동   20152 ----------


 ---------- 2017-07-03 21:00:00 : 동내면   20156 ----------


 ---------- 2017-07-03 21:00:00 : 효자1동   20157 ----------


 ---------- 2017-07-03 22:00:00 : 강남동   20158 ----------


 ---------- 2017-07-03 22:00:00 : 효자1동   20159 ----------


 ---------- 2017-07-04 08:00:00 : 강남동   20160 ----------


 ---------- 2017-07-04 08:00:00 : 후평1동   20161 ----------


 ---------- 2017-07-04 09:00:00 : 동산면   20162 ----------


 ---------- 2017-07-04 10:00:00 : 남산면   20163 ----------


 ---------- 2017-07-04 12:00:00 : 동내면   20164 ----------


 ---------- 2017-07-04 13:00:00 : 동  면   20165 ----------


 ---------- 2017-07-04 15:00:00 : 동내면   20166 ----------


 ---------- 2017-07-04 16:00:00 : 동  면   20167 ----------


 ---------- 2017-07-04 17:00:00 : 남  면   20168 ----------


 ---------- 2017-07-04 18:00:00 : 남산면   20169 ----------


 ---------- 2017-07-04 19:00:00 : 동내면   20170 ----------


 ---------- 2017-07-05 07:00:00 : 서  면   20171 ----------


 ---------- 2017-07-05 09:00:00 : 소양동   20172 ----------


 ---------- 2017-07-05 14:00:00 : 동산면   20173 ----------


 ---------- 2017-07-05 16:00:00 : 강남동   20174 ----------


 ---------- 2017-07-05 20:00:00 : 신북읍   20175 ----------


 ---------- 2017-07-06 01:00:00 : 동  면   20176 ----------


 ---------- 2017-07-06 06:00:00 : 신동면   20177 ----------


 ---------- 2017-07-06 07:00:00 : 효자1동   20178 ----------


 ---------- 2017-07-06 09:00:00 : 석사동   20179 ----------


 ---------- 2017-07-06 09:00:00 : 동  면   20180 ----------


 ---------- 2017-07-06 10:00:00 : 남산면   20181 ----------


 ---------- 2017-07-06 10:00:00 : 동  면   20182 ----------


 ---------- 2017-07-06 14:00:00 : 남산면   20183 ----------


 ---------- 2017-07-06 14:00:00 : 북산면   20184 ----------


 ---------- 2017-07-06 15:00:00 : 서  면   20185 ----------


 ---------- 2017-07-06 15:00:00 : 후평1동   20186 ----------


 ---------- 2017-07-06 15:00:00 : 퇴계동   20187 ----------


 ---------- 2017-07-06 17:00:00 : 효자1동   20188 ----------


 ---------- 2017-07-06 17:00:00 : 남산면   20189 ----------


 ---------- 2017-07-06 18:00:00 : 북산면   20190 ----------


 ---------- 2017-07-06 19:00:00 : 효자1동   20191 ----------


 ---------- 2017-07-06 22:00:00 : 강남동   20193 ----------


 ---------- 2017-07-06 23:00:00 : 퇴계동   20194 ----------


 ---------- 2017-07-07 00:00:00 : 신북읍   20195 ----------

 ---------- 2017-07-07 07:00:00 : 남산면   20197 ----------


 ---------- 2017-07-07 08:00:00 : 퇴계동   20198 ----------


 ---------- 2017-07-07 09:00:00 : 동내면   20199 ----------


 ---------- 2017-07-07 09:00:00 : 남산면   20200 ----------


 ---------- 2017-07-07 09:00:00 : 소양동   20201 ----------


 ---------- 2017-07-07 12:00:00 : 남  면   20202 ----------


 ---------- 2017-07-07 14:00:00 : 강남동   20203 ----------


 ---------- 2017-07-07 14:00:00 : 효자1동   20204 ----------


 ---------- 2017-07-07 14:00:00 : 남산면   20205 ----------


 ---------- 2017-07-07 15:00:00 : 강남동   20206 ----------


 ---------- 2017-07-07 15:00:00 : 동  면   20207 ----------


 ---------- 2017-07-07 16:00:00 : 강남동   20208 ----------


 ---------- 2017-07-07 17:00:00 : 강남동   20209 ----------


 ---------- 2017-07-07 18:00:00 : 남  면   20211 ----------


 ---------- 2017-07-07 20:00:00 : 근화동   20212 ----------


 ---------- 2017-07-07 21:00:00 : 소양동   20213 ----------


 ---------- 2017-07-08 00:00:00 : 신사우동   20214 ----------


 ---------- 2017-07-08 03:00:00 : 퇴계동   20216 ----------


 ---------- 2017-07-08 04:00:00 : 효자1동   20217 ----------


 ---------- 2017-07-08 05:00:00 : 퇴계동   20218 ----------


 ---------- 2017-07-08 07:00:00 : 서  면   20219 ----------


 ---------- 2017-07-08 08:00:00 : 신동면   20220 ----------


 ---------- 2017-07-08 08:00:00 : 남산면   20222 ----------


 ---------- 2017-07-08 09:00:00 : 서  면   20223 ----------


 ---------- 2017-07-08 09:00:00 : 동산면   20224 ----------


 ---------- 2017-07-08 10:00:00 : 동산면   20225 ----------


 ---------- 2017-07-08 12:00:00 : 남산면   20226 ----------


 ---------- 2017-07-08 12:00:00 : 후평1동   20227 ----------


 ---------- 2017-07-08 13:00:00 : 석사동   20228 ----------


 ---------- 2017-07-08 13:00:00 : 신동면   20229 ----------


 ---------- 2017-07-08 14:00:00 : 서  면   20230 ----------


 ---------- 2017-07-08 15:00:00 : 서  면   20231 ----------


 ---------- 2017-07-08 15:00:00 : 효자1동   20232 ----------


 ---------- 2017-07-08 15:00:00 : 동  면   20233 ----------


 ---------- 2017-07-08 16:00:00 : 약사명동   20234 ----------


 ---------- 2017-07-08 19:00:00 : 남산면   20235 ----------


 ---------- 2017-07-08 19:00:00 : 약사명동   20236 ----------


 ---------- 2017-07-08 20:00:00 : 조운동   20237 ----------


 ---------- 2017-07-09 01:00:00 : 후평1동   20238 ----------


 ---------- 2017-07-09 08:00:00 : 신북읍   20240 ----------


 ---------- 2017-07-09 09:00:00 : 후평1동   20241 ----------


 ---------- 2017-07-09 09:00:00 : 퇴계동   20242 ----------


 ---------- 2017-07-09 10:00:00 : 후평1동   20243 ----------


 ---------- 2017-07-09 11:00:00 : 사북면   20245 ----------


 ---------- 2017-07-09 11:00:00 : 후평1동   20246 ----------


 ---------- 2017-07-09 12:00:00 : 서  면   20247 ----------


 ---------- 2017-07-09 16:00:00 : 남산면   20248 ----------


 ---------- 2017-07-09 16:00:00 : 퇴계동   20249 ----------


 ---------- 2017-07-09 18:00:00 : 동  면   20251 ----------


 ---------- 2017-07-09 19:00:00 : 동  면   20252 ----------


 ---------- 2017-07-09 21:00:00 : 남  면   20253 ----------


 ---------- 2017-07-09 22:00:00 : 조운동   20254 ----------


 ---------- 2017-07-10 00:00:00 : 효자1동   20255 ----------


 ---------- 2017-07-10 08:00:00 : 강남동   20256 ----------


 ---------- 2017-07-10 09:00:00 : 효자1동   20257 ----------


 ---------- 2017-07-10 09:00:00 : 동산면   20258 ----------


 ---------- 2017-07-10 13:00:00 : 서  면   20259 ----------


 ---------- 2017-07-10 15:00:00 : 동  면   20260 ----------


 ---------- 2017-07-10 16:00:00 : 남산면   20261 ----------


 ---------- 2017-07-10 17:00:00 : 신동면   20262 ----------


 ---------- 2017-07-10 18:00:00 : 신동면   20263 ----------


 ---------- 2017-07-10 20:00:00 : 강남동   20264 ----------


 ---------- 2017-07-10 21:00:00 : 효자1동   20265 ----------


 ---------- 2017-07-10 22:00:00 : 신사우동   20266 ----------


 ---------- 2017-07-10 23:00:00 : 석사동   20267 ----------


 ---------- 2017-07-11 00:00:00 : 남산면   20268 ----------


 ---------- 2017-07-11 01:00:00 : 남  면   20269 ----------


 ---------- 2017-07-11 02:00:00 : 효자1동   20270 ----------


 ---------- 2017-07-11 10:00:00 : 서  면   20271 ----------


 ---------- 2017-07-11 11:00:00 : 남산면   20272 ----------


 ---------- 2017-07-11 11:00:00 : 소양동   20273 ----------


 ---------- 2017-07-11 11:00:00 : 동  면   20274 ----------


 ---------- 2017-07-11 11:00:00 : 퇴계동   20275 ----------


 ---------- 2017-07-11 13:00:00 : 후평1동   20276 ----------


 ---------- 2017-07-11 14:00:00 : 남  면   20278 ----------


 ---------- 2017-07-11 15:00:00 : 남산면   20279 ----------


 ---------- 2017-07-11 15:00:00 : 동  면   20280 ----------


 ---------- 2017-07-11 17:00:00 : 신북읍   20281 ----------


 ---------- 2017-07-11 18:00:00 : 서  면   20282 ----------


 ---------- 2017-07-11 19:00:00 : 후평1동   20284 ----------


 ---------- 2017-07-12 04:00:00 : 조운동   20285 ----------


 ---------- 2017-07-12 05:00:00 : 석사동   20286 ----------


 ---------- 2017-07-12 08:00:00 : 석사동   20287 ----------


 ---------- 2017-07-12 08:00:00 : 강남동   20288 ----------


 ---------- 2017-07-12 09:00:00 : 석사동   20289 ----------


 ---------- 2017-07-12 09:00:00 : 신북읍   20290 ----------


 ---------- 2017-07-12 09:00:00 : 동  면   20291 ----------


 ---------- 2017-07-12 10:00:00 : 사북면   20292 ----------


 ---------- 2017-07-12 10:00:00 : 남산면   20293 ----------


 ---------- 2017-07-12 10:00:00 : 신북읍   20294 ----------


 ---------- 2017-07-12 10:00:00 : 동산면   20295 ----------


 ---------- 2017-07-12 11:00:00 : 석사동   20296 ----------


 ---------- 2017-07-12 12:00:00 : 강남동   20297 ----------


 ---------- 2017-07-12 14:00:00 : 강남동   20298 ----------


 ---------- 2017-07-12 14:00:00 : 동  면   20299 ----------


 ---------- 2017-07-12 15:00:00 : 남산면   20300 ----------


 ---------- 2017-07-12 16:00:00 : 동  면   20301 ----------


 ---------- 2017-07-12 17:00:00 : 효자1동   20302 ----------


 ---------- 2017-07-12 18:00:00 : 신사우동   20303 ----------


 ---------- 2017-07-12 22:00:00 : 신사우동   20304 ----------


 ---------- 2017-07-13 08:00:00 : 후평1동   20305 ----------


 ---------- 2017-07-13 09:00:00 : 석사동   20306 ----------


 ---------- 2017-07-13 09:00:00 : 신동면   20307 ----------


 ---------- 2017-07-13 09:00:00 : 사북면   20308 ----------


 ---------- 2017-07-13 09:00:00 : 신사우동   20309 ----------


 ---------- 2017-07-13 09:00:00 : 북산면   20311 ----------


 ---------- 2017-07-13 10:00:00 : 강남동   20312 ----------


 ---------- 2017-07-13 10:00:00 : 남산면   20314 ----------


 ---------- 2017-07-13 10:00:00 : 퇴계동   20315 ----------


 ---------- 2017-07-13 11:00:00 : 남산면   20316 ----------


 ---------- 2017-07-13 11:00:00 : 신북읍   20317 ----------


 ---------- 2017-07-13 12:00:00 : 남산면   20318 ----------


 ---------- 2017-07-13 13:00:00 : 사북면   20319 ----------


 ---------- 2017-07-13 13:00:00 : 동내면   20320 ----------


 ---------- 2017-07-13 13:00:00 : 동  면   20321 ----------


 ---------- 2017-07-13 15:00:00 : 약사명동   20322 ----------


 ---------- 2017-07-13 15:00:00 : 후평1동   20324 ----------


 ---------- 2017-07-13 16:00:00 : 효자1동   20325 ----------


 ---------- 2017-07-13 17:00:00 : 효자1동   20326 ----------


 ---------- 2017-07-13 18:00:00 : 퇴계동   20327 ----------


 ---------- 2017-07-13 19:00:00 : 신북읍   20328 ----------


 ---------- 2017-07-13 20:00:00 : 석사동   20329 ----------


 ---------- 2017-07-13 22:00:00 : 석사동   20330 ----------


 ---------- 2017-07-13 23:00:00 : 퇴계동   20331 ----------


 ---------- 2017-07-14 03:00:00 : 동  면   20332 ----------


 ---------- 2017-07-14 09:00:00 : 서  면   20333 ----------


 ---------- 2017-07-14 09:00:00 : 사북면   20334 ----------


 ---------- 2017-07-14 09:00:00 : 효자1동   20335 ----------


 ---------- 2017-07-14 09:00:00 : 동산면   20336 ----------


 ---------- 2017-07-14 10:00:00 : 효자1동   20337 ----------


 ---------- 2017-07-14 10:00:00 : 남산면   20338 ----------


 ---------- 2017-07-14 10:00:00 : 동  면   20339 ----------


 ---------- 2017-07-14 11:00:00 : 효자1동   20340 ----------


 ---------- 2017-07-14 12:00:00 : 후평1동   20341 ----------


 ---------- 2017-07-14 13:00:00 : 효자1동   20343 ----------


 ---------- 2017-07-14 14:00:00 : 석사동   20344 ----------

 ---------- 2017-07-14 14:00:00 : 신북읍   20345 ----------


 ---------- 2017-07-14 15:00:00 : 신사우동   20346 ----------


 ---------- 2017-07-14 16:00:00 : 후평1동   20348 ----------


 ---------- 2017-07-14 17:00:00 : 남산면   20349 ----------


 ---------- 2017-07-14 18:00:00 : 후평1동   20350 ----------


 ---------- 2017-07-14 19:00:00 : 동  면   20351 ----------


 ---------- 2017-07-14 22:00:00 : 근화동   20352 ----------


 ---------- 2017-07-15 01:00:00 : 후평1동   20353 ----------


 ---------- 2017-07-15 02:00:00 : 북산면   20354 ----------


 ---------- 2017-07-15 06:00:00 : 신북읍   20355 ----------


 ---------- 2017-07-15 07:00:00 : 퇴계동   20356 ----------


 ---------- 2017-07-15 09:00:00 : 동내면   20357 ----------


 ---------- 2017-07-15 09:00:00 : 후평1동   20358 ----------


 ---------- 2017-07-15 10:00:00 : 약사명동   20359 ----------


 ---------- 2017-07-15 10:00:00 : 북산면   20360 ----------


 ---------- 2017-07-15 11:00:00 : 서  면   20361 ----------


 ---------- 2017-07-15 12:00:00 : 신동면   20362 ----------


 ---------- 2017-07-15 12:00:00 : 사북면   20363 ----------


 ---------- 2017-07-15 12:00:00 : 동  면   20364 ----------


 ---------- 2017-07-15 13:00:00 : 석사동   20365 ----------


 ---------- 2017-07-15 13:00:00 : 신사우동   20366 ----------


 ---------- 2017-07-15 13:00:00 : 동  면   20367 ----------


 ---------- 2017-07-15 14:00:00 : 남산면   20368 ----------


 ---------- 2017-07-15 14:00:00 : 근화동   20370 ----------


 ---------- 2017-07-15 14:00:00 : 동  면   20371 ----------


 ---------- 2017-07-15 15:00:00 : 동산면   20372 ----------


 ---------- 2017-07-15 17:00:00 : 동내면   20373 ----------


 ---------- 2017-07-15 18:00:00 : 동  면   20374 ----------


 ---------- 2017-07-15 20:00:00 : 후평1동   20375 ----------


 ---------- 2017-07-16 04:00:00 : 조운동   20376 ----------


 ---------- 2017-07-16 09:00:00 : 사북면   20377 ----------


 ---------- 2017-07-16 11:00:00 : 퇴계동   20378 ----------


 ---------- 2017-07-16 12:00:00 : 신동면   20379 ----------


 ---------- 2017-07-16 12:00:00 : 남  면   20380 ----------


 ---------- 2017-07-16 12:00:00 : 동  면   20381 ----------


 ---------- 2017-07-16 13:00:00 : 석사동   20382 ----------


 ---------- 2017-07-16 13:00:00 : 사북면   20383 ----------


 ---------- 2017-07-16 14:00:00 : 효자1동   20384 ----------


 ---------- 2017-07-16 15:00:00 : 강남동   20385 ----------


 ---------- 2017-07-16 16:00:00 : 남산면   20386 ----------


 ---------- 2017-07-16 16:00:00 : 동  면   20387 ----------


 ---------- 2017-07-16 18:00:00 : 소양동   20388 ----------


 ---------- 2017-07-17 00:00:00 : 퇴계동   20389 ----------


 ---------- 2017-07-17 08:00:00 : 동  면   20390 ----------


 ---------- 2017-07-17 09:00:00 : 강남동   20391 ----------


 ---------- 2017-07-17 10:00:00 : 강남동   20392 ----------


 ---------- 2017-07-17 10:00:00 : 서  면   20393 ----------


 ---------- 2017-07-17 10:00:00 : 사북면   20394 ----------


 ---------- 2017-07-17 10:00:00 : 동  면   20395 ----------


 ---------- 2017-07-17 10:00:00 : 동산면   20396 ----------


 ---------- 2017-07-17 12:00:00 : 남산면   20397 ----------


 ---------- 2017-07-17 13:00:00 : 신동면   20398 ----------


 ---------- 2017-07-17 13:00:00 : 남산면   20400 ----------


 ---------- 2017-07-17 13:00:00 : 동  면   20401 ----------


 ---------- 2017-07-17 13:00:00 : 조운동   20402 ----------


 ---------- 2017-07-17 15:00:00 : 동  면   20404 ----------


 ---------- 2017-07-17 15:00:00 : 후평1동   20405 ----------


 ---------- 2017-07-17 16:00:00 : 신사우동   20406 ----------


 ---------- 2017-07-17 17:00:00 : 서  면   20407 ----------


 ---------- 2017-07-17 17:00:00 : 남산면   20408 ----------


 ---------- 2017-07-17 17:00:00 : 동  면   20409 ----------


 ---------- 2017-07-17 21:00:00 : 석사동   20410 ----------


 ---------- 2017-07-18 08:00:00 : 서  면   20411 ----------


 ---------- 2017-07-18 09:00:00 : 강남동   20412 ----------


 ---------- 2017-07-18 10:00:00 : 강남동   20413 ----------


 ---------- 2017-07-18 11:00:00 : 신동면   20414 ----------


 ---------- 2017-07-18 11:00:00 : 서  면   20415 ----------


 ---------- 2017-07-18 11:00:00 : 후평1동   20416 ----------


 ---------- 2017-07-18 13:00:00 : 사북면   20417 ----------


 ---------- 2017-07-18 13:00:00 : 동내면   20418 ----------


 ---------- 2017-07-18 14:00:00 : 강남동   20420 ----------


 ---------- 2017-07-18 14:00:00 : 퇴계동   20421 ----------


 ---------- 2017-07-18 14:00:00 : 북산면   20422 ----------


 ---------- 2017-07-18 15:00:00 : 신동면   20424 ----------


 ---------- 2017-07-18 15:00:00 : 강남동   20425 ----------


 ---------- 2017-07-18 15:00:00 : 남산면   20426 ----------


 ---------- 2017-07-18 16:00:00 : 동  면   20428 ----------


 ---------- 2017-07-18 17:00:00 : 강남동   20429 ----------


 ---------- 2017-07-18 18:00:00 : 신동면   20430 ----------


 ---------- 2017-07-18 18:00:00 : 동  면   20431 ----------


 ---------- 2017-07-18 19:00:00 : 퇴계동   20432 ----------


 ---------- 2017-07-18 22:00:00 : 퇴계동   20434 ----------


 ---------- 2017-07-19 06:00:00 : 퇴계동   20435 ----------


 ---------- 2017-07-19 08:00:00 : 서  면   20436 ----------


 ---------- 2017-07-19 09:00:00 : 남산면   20437 ----------


 ---------- 2017-07-19 09:00:00 : 동  면   20438 ----------


 ---------- 2017-07-19 10:00:00 : 강남동   20439 ----------


 ---------- 2017-07-19 10:00:00 : 서  면   20441 ----------


 ---------- 2017-07-19 10:00:00 : 동  면   20442 ----------


 ---------- 2017-07-19 11:00:00 : 서  면   20443 ----------


 ---------- 2017-07-19 12:00:00 : 석사동   20444 ----------


 ---------- 2017-07-19 12:00:00 : 강남동   20445 ----------


 ---------- 2017-07-19 12:00:00 : 동  면   20446 ----------


 ---------- 2017-07-19 12:00:00 : 후평1동   20447 ----------


 ---------- 2017-07-19 13:00:00 : 남  면   20448 ----------


 ---------- 2017-07-19 13:00:00 : 동산면   20449 ----------


 ---------- 2017-07-19 14:00:00 : 동  면   20450 ----------


 ---------- 2017-07-19 15:00:00 : 남산면   20451 ----------


 ---------- 2017-07-19 16:00:00 : 사북면   20452 ----------


 ---------- 2017-07-19 16:00:00 : 동  면   20453 ----------


 ---------- 2017-07-19 18:00:00 : 퇴계동   20454 ----------


 ---------- 2017-07-19 20:00:00 : 신사우동   20455 ----------


 ---------- 2017-07-20 01:00:00 : 근화동   20456 ----------


 ---------- 2017-07-20 06:00:00 : 강남동   20457 ----------


 ---------- 2017-07-20 08:00:00 : 후평1동   20458 ----------


 ---------- 2017-07-20 09:00:00 : 효자1동   20459 ----------


 ---------- 2017-07-20 09:00:00 : 남산면   20460 ----------


 ---------- 2017-07-20 11:00:00 : 석사동   20461 ----------


 ---------- 2017-07-20 11:00:00 : 남산면   20462 ----------


 ---------- 2017-07-20 13:00:00 : 강남동   20463 ----------


 ---------- 2017-07-20 14:00:00 : 남산면   20464 ----------


 ---------- 2017-07-20 14:00:00 : 동산면   20465 ----------


 ---------- 2017-07-20 14:00:00 : 교  동   20466 ----------


 ---------- 2017-07-20 15:00:00 : 서  면   20467 ----------


 ---------- 2017-07-20 15:00:00 : 후평1동   20468 ----------


 ---------- 2017-07-20 16:00:00 : 동내면   20469 ----------


 ---------- 2017-07-20 17:00:00 : 동  면   20470 ----------


 ---------- 2017-07-20 19:00:00 : 강남동   20471 ----------


 ---------- 2017-07-20 19:00:00 : 후평1동   20472 ----------


 ---------- 2017-07-21 08:00:00 : 신동면   20473 ----------


 ---------- 2017-07-21 09:00:00 : 동내면   20474 ----------


 ---------- 2017-07-21 09:00:00 : 동  면   20475 ----------


 ---------- 2017-07-21 10:00:00 : 서  면   20476 ----------


 ---------- 2017-07-21 10:00:00 : 남  면   20478 ----------


 ---------- 2017-07-21 10:00:00 : 동내면   20479 ----------


 ---------- 2017-07-21 10:00:00 : 동  면   20480 ----------


 ---------- 2017-07-21 10:00:00 : 퇴계동   20481 ----------


 ---------- 2017-07-21 11:00:00 : 석사동   20482 ----------


 ---------- 2017-07-21 12:00:00 : 서  면   20483 ----------


 ---------- 2017-07-21 12:00:00 : 동내면   20484 ----------


 ---------- 2017-07-21 12:00:00 : 남산면   20485 ----------


 ---------- 2017-07-21 12:00:00 : 북산면   20486 ----------


 ---------- 2017-07-21 13:00:00 : 신동면   20487 ----------


 ---------- 2017-07-21 13:00:00 : 동내면   20488 ----------


 ---------- 2017-07-21 13:00:00 : 남산면   20489 ----------


 ---------- 2017-07-21 14:00:00 : 동내면   20490 ----------


 ---------- 2017-07-21 14:00:00 : 남산면   20491 ----------

 ---------- 2017-07-21 14:00:00 : 퇴계동   20492 ----------


 ---------- 2017-07-21 15:00:00 : 남  면   20493 ----------


 ---------- 2017-07-21 16:00:00 : 퇴계동   20494 ----------


 ---------- 2017-07-21 16:00:00 : 교  동   20495 ----------


 ---------- 2017-07-21 18:00:00 : 동내면   20496 ----------


 ---------- 2017-07-21 21:00:00 : 약사명동   20497 ----------


 ---------- 2017-07-21 21:00:00 : 퇴계동   20499 ----------


 ---------- 2017-07-22 07:00:00 : 후평1동   20500 ----------


 ---------- 2017-07-22 08:00:00 : 동  면   20501 ----------


 ---------- 2017-07-22 09:00:00 : 사북면   20502 ----------


 ---------- 2017-07-22 09:00:00 : 남산면   20503 ----------


 ---------- 2017-07-22 09:00:00 : 후평1동   20505 ----------


 ---------- 2017-07-22 10:00:00 : 남산면   20506 ----------


 ---------- 2017-07-22 10:00:00 : 동  면   20507 ----------


 ---------- 2017-07-22 12:00:00 : 서  면   20508 ----------


 ---------- 2017-07-22 13:00:00 : 신동면   20509 ----------


 ---------- 2017-07-22 13:00:00 : 강남동   20510 ----------


 ---------- 2017-07-22 15:00:00 : 신동면   20511 ----------


 ---------- 2017-07-22 15:00:00 : 동산면   20512 ----------


 ---------- 2017-07-22 16:00:00 : 동산면   20513 ----------


 ---------- 2017-07-22 17:00:00 : 동  면   20514 ----------


 ---------- 2017-07-22 18:00:00 : 남  면   20515 ----------


 ---------- 2017-07-22 18:00:00 : 동  면   20516 ----------


 ---------- 2017-07-22 19:00:00 : 근화동   20517 ----------


 ---------- 2017-07-22 22:00:00 : 후평1동   20520 ----------


 ---------- 2017-07-23 01:00:00 : 서  면   20522 ----------


 ---------- 2017-07-23 07:00:00 : 동  면   20523 ----------


 ---------- 2017-07-23 10:00:00 : 남  면   20524 ----------


 ---------- 2017-07-23 12:00:00 : 소양동   20525 ----------


 ---------- 2017-07-23 13:00:00 : 신동면   20526 ----------


 ---------- 2017-07-23 14:00:00 : 동내면   20527 ----------


 ---------- 2017-07-23 15:00:00 : 강남동   20528 ----------


 ---------- 2017-07-23 16:00:00 : 강남동   20529 ----------


 ---------- 2017-07-23 18:00:00 : 석사동   20530 ----------


 ---------- 2017-07-23 22:00:00 : 신사우동   20531 ----------


 ---------- 2017-07-24 00:00:00 : 효자1동   20532 ----------


 ---------- 2017-07-24 08:00:00 : 퇴계동   20533 ----------


 ---------- 2017-07-24 09:00:00 : 후평1동   20534 ----------


 ---------- 2017-07-24 09:00:00 : 퇴계동   20535 ----------


 ---------- 2017-07-24 10:00:00 : 신동면   20537 ----------


 ---------- 2017-07-24 10:00:00 : 퇴계동   20538 ----------


 ---------- 2017-07-24 10:00:00 : 교  동   20539 ----------


 ---------- 2017-07-24 11:00:00 : 석사동   20540 ----------


 ---------- 2017-07-24 11:00:00 : 신동면   20541 ----------


 ---------- 2017-07-24 11:00:00 : 동  면   20542 ----------


 ---------- 2017-07-24 13:00:00 : 서  면   20543 ----------


 ---------- 2017-07-24 13:00:00 : 남산면   20544 ----------


 ---------- 2017-07-24 13:00:00 : 동산면   20545 ----------


 ---------- 2017-07-24 15:00:00 : 후평1동   20546 ----------


 ---------- 2017-07-24 16:00:00 : 효자1동   20547 ----------


 ---------- 2017-07-24 17:00:00 : 후평1동   20548 ----------


 ---------- 2017-07-24 18:00:00 : 서  면   20549 ----------


 ---------- 2017-07-24 18:00:00 : 신사우동   20550 ----------


 ---------- 2017-07-24 22:00:00 : 후평1동   20551 ----------


 ---------- 2017-07-25 00:00:00 : 후평1동   20552 ----------


 ---------- 2017-07-25 05:00:00 : 효자1동   20553 ----------


 ---------- 2017-07-25 07:00:00 : 신동면   20554 ----------


 ---------- 2017-07-25 08:00:00 : 동내면   20555 ----------


 ---------- 2017-07-25 08:00:00 : 남산면   20556 ----------


 ---------- 2017-07-25 09:00:00 : 신동면   20557 ----------


 ---------- 2017-07-25 09:00:00 : 동내면   20559 ----------


 ---------- 2017-07-25 09:00:00 : 동  면   20560 ----------


 ---------- 2017-07-25 10:00:00 : 서  면   20561 ----------


 ---------- 2017-07-25 11:00:00 : 남  면   20562 ----------


 ---------- 2017-07-25 11:00:00 : 동내면   20563 ----------


 ---------- 2017-07-25 11:00:00 : 효자1동   20564 ----------


 ---------- 2017-07-25 12:00:00 : 강남동   20565 ----------


 ---------- 2017-07-25 12:00:00 : 동내면   20566 ----------


 ---------- 2017-07-25 13:00:00 : 남산면   20567 ----------


 ---------- 2017-07-25 14:00:00 : 효자1동   20568 ----------


 ---------- 2017-07-25 14:00:00 : 남산면   20569 ----------


 ---------- 2017-07-25 15:00:00 : 신동면   20570 ----------


 ---------- 2017-07-25 15:00:00 : 소양동   20571 ----------


 ---------- 2017-07-25 15:00:00 : 동  면   20572 ----------


 ---------- 2017-07-25 16:00:00 : 남산면   20573 ----------


 ---------- 2017-07-25 16:00:00 : 후평1동   20575 ----------


 ---------- 2017-07-25 18:00:00 : 남산면   20576 ----------


 ---------- 2017-07-26 02:00:00 : 신사우동   20577 ----------


 ---------- 2017-07-26 05:00:00 : 동  면   20578 ----------


 ---------- 2017-07-26 08:00:00 : 후평1동   20579 ----------


 ---------- 2017-07-26 09:00:00 : 남산면   20581 ----------


 ---------- 2017-07-26 09:00:00 : 동  면   20582 ----------


 ---------- 2017-07-26 10:00:00 : 강남동   20583 ----------


 ---------- 2017-07-26 10:00:00 : 효자1동   20584 ----------


 ---------- 2017-07-26 10:00:00 : 남산면   20585 ----------


 ---------- 2017-07-26 10:00:00 : 퇴계동   20586 ----------


 ---------- 2017-07-26 11:00:00 : 동  면   20587 ----------


 ---------- 2017-07-26 11:00:00 : 후평1동   20588 ----------


 ---------- 2017-07-26 13:00:00 : 석사동   20589 ----------


 ---------- 2017-07-26 14:00:00 : 석사동   20590 ----------


 ---------- 2017-07-26 14:00:00 : 동  면   20591 ----------


 ---------- 2017-07-26 16:00:00 : 강남동   20592 ----------


 ---------- 2017-07-26 16:00:00 : 남산면   20593 ----------


 ---------- 2017-07-26 17:00:00 : 사북면   20594 ----------


 ---------- 2017-07-26 18:00:00 : 남산면   20596 ----------


 ---------- 2017-07-26 18:00:00 : 신사우동   20597 ----------


 ---------- 2017-07-26 18:00:00 : 후평1동   20598 ----------


 ---------- 2017-07-26 19:00:00 : 후평1동   20599 ----------


 ---------- 2017-07-26 21:00:00 : 효자1동   20600 ----------


 ---------- 2017-07-27 07:00:00 : 강남동   20601 ----------


 ---------- 2017-07-27 07:00:00 : 동  면   20602 ----------


 ---------- 2017-07-27 07:00:00 : 동산면   20603 ----------


 ---------- 2017-07-27 08:00:00 : 서  면   20604 ----------


 ---------- 2017-07-27 08:00:00 : 남산면   20605 ----------


 ---------- 2017-07-27 08:00:00 : 퇴계동   20606 ----------


 ---------- 2017-07-27 09:00:00 : 효자1동   20607 ----------


 ---------- 2017-07-27 09:00:00 : 남산면   20609 ----------


 ---------- 2017-07-27 09:00:00 : 신북읍   20610 ----------


 ---------- 2017-07-27 09:00:00 : 후평1동   20611 ----------


 ---------- 2017-07-27 09:00:00 : 동산면   20612 ----------


 ---------- 2017-07-27 10:00:00 : 석사동   20613 ----------


 ---------- 2017-07-27 10:00:00 : 남  면   20614 ----------


 ---------- 2017-07-27 10:00:00 : 신북읍   20615 ----------


 ---------- 2017-07-27 11:00:00 : 남  면   20616 ----------


 ---------- 2017-07-27 11:00:00 : 동내면   20618 ----------


 ---------- 2017-07-27 11:00:00 : 소양동   20619 ----------


 ---------- 2017-07-27 12:00:00 : 신사우동   20620 ----------


 ---------- 2017-07-27 12:00:00 : 동  면   20622 ----------


 ---------- 2017-07-27 13:00:00 : 교  동   20623 ----------


 ---------- 2017-07-27 14:00:00 : 강남동   20624 ----------


 ---------- 2017-07-27 15:00:00 : 사북면   20625 ----------


 ---------- 2017-07-27 15:00:00 : 동  면   20626 ----------


 ---------- 2017-07-27 16:00:00 : 사북면   20627 ----------


 ---------- 2017-07-27 16:00:00 : 퇴계동   20628 ----------


 ---------- 2017-07-27 17:00:00 : 신동면   20629 ----------


 ---------- 2017-07-27 18:00:00 : 강남동   20630 ----------


 ---------- 2017-07-27 18:00:00 : 후평1동   20631 ----------


 ---------- 2017-07-27 19:00:00 : 서  면   20632 ----------


 ---------- 2017-07-27 19:00:00 : 신사우동   20633 ----------


 ---------- 2017-07-27 23:00:00 : 동내면   20634 ----------


 ---------- 2017-07-28 06:00:00 : 동  면   20635 ----------


 ---------- 2017-07-28 09:00:00 : 석사동   20636 ----------


 ---------- 2017-07-28 09:00:00 : 서  면   20637 ----------


 ---------- 2017-07-28 09:00:00 : 소양동   20638 ----------


 ---------- 2017-07-28 10:00:00 : 근화동   20639 ----------


 ---------- 2017-07-28 11:00:00 : 신동면   20640 ----------

 ---------- 2017-07-28 11:00:00 : 퇴계동   20641 ----------


 ---------- 2017-07-28 12:00:00 : 퇴계동   20642 ----------


 ---------- 2017-07-28 13:00:00 : 동  면   20643 ----------


 ---------- 2017-07-28 13:00:00 : 퇴계동   20644 ----------


 ---------- 2017-07-28 14:00:00 : 동내면   20645 ----------


 ---------- 2017-07-28 14:00:00 : 신북읍   20646 ----------


 ---------- 2017-07-28 14:00:00 : 후평1동   20649 ----------


 ---------- 2017-07-28 15:00:00 : 석사동   20650 ----------


 ---------- 2017-07-28 15:00:00 : 후평1동   20651 ----------


 ---------- 2017-07-28 15:00:00 : 퇴계동   20652 ----------


 ---------- 2017-07-28 20:00:00 : 소양동   20653 ----------


 ---------- 2017-07-28 21:00:00 : 효자1동   20654 ----------


 ---------- 2017-07-29 00:00:00 : 효자1동   20655 ----------


 ---------- 2017-07-29 04:00:00 : 근화동   20656 ----------


 ---------- 2017-07-29 07:00:00 : 남산면   20657 ----------


 ---------- 2017-07-29 08:00:00 : 북산면   20659 ----------


 ---------- 2017-07-29 09:00:00 : 후평1동   20660 ----------


 ---------- 2017-07-29 09:00:00 : 동산면   20661 ----------


 ---------- 2017-07-29 10:00:00 : 남산면   20662 ----------


 ---------- 2017-07-29 10:00:00 : 신사우동   20663 ----------


 ---------- 2017-07-29 11:00:00 : 사북면   20664 ----------


 ---------- 2017-07-29 12:00:00 : 석사동   20665 ----------


 ---------- 2017-07-29 12:00:00 : 사북면   20666 ----------


 ---------- 2017-07-29 12:00:00 : 동내면   20667 ----------


 ---------- 2017-07-29 12:00:00 : 신사우동   20668 ----------


 ---------- 2017-07-29 12:00:00 : 동  면   20669 ----------


 ---------- 2017-07-29 12:00:00 : 동산면   20670 ----------


 ---------- 2017-07-29 14:00:00 : 남  면   20671 ----------


 ---------- 2017-07-29 14:00:00 : 남산면   20672 ----------


 ---------- 2017-07-29 15:00:00 : 동산면   20673 ----------


 ---------- 2017-07-29 16:00:00 : 신동면   20674 ----------


 ---------- 2017-07-29 16:00:00 : 강남동   20675 ----------


 ---------- 2017-07-29 16:00:00 : 동  면   20676 ----------


 ---------- 2017-07-29 17:00:00 : 서  면   20677 ----------


 ---------- 2017-07-29 18:00:00 : 석사동   20678 ----------


 ---------- 2017-07-29 18:00:00 : 동내면   20679 ----------


 ---------- 2017-07-29 18:00:00 : 조운동   20681 ----------


 ---------- 2017-07-29 19:00:00 : 동  면   20682 ----------


 ---------- 2017-07-29 19:00:00 : 후평1동   20683 ----------


 ---------- 2017-07-29 21:00:00 : 남산면   20684 ----------


 ---------- 2017-07-30 00:00:00 : 석사동   20685 ----------


 ---------- 2017-07-30 00:00:00 : 남산면   20686 ----------


 ---------- 2017-07-30 04:00:00 : 퇴계동   20687 ----------


 ---------- 2017-07-30 07:00:00 : 동내면   20688 ----------


 ---------- 2017-07-30 07:00:00 : 동  면   20689 ----------


 ---------- 2017-07-30 08:00:00 : 신사우동   20690 ----------


 ---------- 2017-07-30 09:00:00 : 동내면   20691 ----------


 ---------- 2017-07-30 09:00:00 : 신북읍   20692 ----------


 ---------- 2017-07-30 10:00:00 : 동산면   20693 ----------


 ---------- 2017-07-30 11:00:00 : 후평1동   20694 ----------


 ---------- 2017-07-30 11:00:00 : 북산면   20695 ----------


 ---------- 2017-07-30 12:00:00 : 후평1동   20696 ----------


 ---------- 2017-07-30 13:00:00 : 동  면   20697 ----------


 ---------- 2017-07-30 13:00:00 : 후평1동   20698 ----------


 ---------- 2017-07-30 14:00:00 : 남  면   20699 ----------


 ---------- 2017-07-30 14:00:00 : 동내면   20700 ----------


 ---------- 2017-07-30 14:00:00 : 근화동   20701 ----------


 ---------- 2017-07-30 15:00:00 : 서  면   20702 ----------


 ---------- 2017-07-30 15:00:00 : 신북읍   20705 ----------


 ---------- 2017-07-30 16:00:00 : 남산면   20706 ----------


 ---------- 2017-07-30 16:00:00 : 동  면   20707 ----------


 ---------- 2017-07-30 17:00:00 : 남산면   20708 ----------


 ---------- 2017-07-30 17:00:00 : 동  면   20709 ----------


 ---------- 2017-07-30 17:00:00 : 북산면   20710 ----------


 ---------- 2017-07-30 18:00:00 : 강남동   20711 ----------


 ---------- 2017-07-30 18:00:00 : 남산면   20712 ----------


 ---------- 2017-07-30 18:00:00 : 신사우동   20713 ----------


 ---------- 2017-07-30 18:00:00 : 후평1동   20715 ----------


 ---------- 2017-07-30 20:00:00 : 동  면   20716 ----------


 ---------- 2017-07-31 00:00:00 : 석사동   20717 ----------


 ---------- 2017-07-31 00:00:00 : 강남동   20718 ----------


 ---------- 2017-07-31 00:00:00 : 남산면   20719 ----------


 ---------- 2017-07-31 01:00:00 : 퇴계동   20721 ----------


 ---------- 2017-07-31 05:00:00 : 동내면   20722 ----------


 ---------- 2017-07-31 07:00:00 : 후평1동   20723 ----------


 ---------- 2017-07-31 08:00:00 : 강남동   20724 ----------


 ---------- 2017-07-31 09:00:00 : 강남동   20725 ----------


 ---------- 2017-07-31 09:00:00 : 서  면   20726 ----------


 ---------- 2017-07-31 09:00:00 : 신사우동   20727 ----------


 ---------- 2017-07-31 09:00:00 : 신북읍   20728 ----------


 ---------- 2017-07-31 11:00:00 : 서  면   20729 ----------


 ---------- 2017-07-31 11:00:00 : 근화동   20730 ----------


 ---------- 2017-07-31 12:00:00 : 효자1동   20731 ----------


 ---------- 2017-07-31 13:00:00 : 강남동   20732 ----------


 ---------- 2017-07-31 13:00:00 : 동  면   20733 ----------


 ---------- 2017-07-31 14:00:00 : 남  면   20736 ----------


 ---------- 2017-07-31 14:00:00 : 동내면   20739 ----------


 ---------- 2017-07-31 15:00:00 : 강남동   20740 ----------


 ---------- 2017-07-31 15:00:00 : 남산면   20741 ----------


 ---------- 2017-07-31 16:00:00 : 사북면   20742 ----------


 ---------- 2017-07-31 16:00:00 : 남산면   20743 ----------


 ---------- 2017-07-31 18:00:00 : 남산면   20744 ----------


 ---------- 2017-08-01 08:00:00 : 동  면   20745 ----------


 ---------- 2017-08-01 09:00:00 : 강남동   20746 ----------


 ---------- 2017-08-01 09:00:00 : 신북읍   20747 ----------


 ---------- 2017-08-01 09:00:00 : 후평1동   20748 ----------


 ---------- 2017-08-01 10:00:00 : 신동면   20749 ----------


 ---------- 2017-08-01 10:00:00 : 신사우동   20750 ----------


 ---------- 2017-08-01 10:00:00 : 소양동   20751 ----------


 ---------- 2017-08-01 10:00:00 : 동  면   20752 ----------


 ---------- 2017-08-01 11:00:00 : 사북면   20754 ----------


 ---------- 2017-08-01 11:00:00 : 남산면   20755 ----------


 ---------- 2017-08-01 12:00:00 : 강남동   20756 ----------


 ---------- 2017-08-01 13:00:00 : 강남동   20757 ----------


 ---------- 2017-08-01 13:00:00 : 동내면   20758 ----------


 ---------- 2017-08-01 13:00:00 : 신북읍   20759 ----------


 ---------- 2017-08-01 13:00:00 : 북산면   20760 ----------


 ---------- 2017-08-01 14:00:00 : 신동면   20761 ----------


 ---------- 2017-08-01 15:00:00 : 효자1동   20762 ----------


 ---------- 2017-08-01 15:00:00 : 후평1동   20763 ----------


 ---------- 2017-08-01 19:00:00 : 신북읍   20764 ----------


 ---------- 2017-08-01 20:00:00 : 남산면   20765 ----------


 ---------- 2017-08-01 21:00:00 : 서  면   20766 ----------


 ---------- 2017-08-01 21:00:00 : 남산면   20768 ----------


 ---------- 2017-08-02 08:00:00 : 후평1동   20769 ----------


 ---------- 2017-08-02 09:00:00 : 남  면   20770 ----------


 ---------- 2017-08-02 09:00:00 : 후평1동   20771 ----------


 ---------- 2017-08-02 10:00:00 : 신동면   20772 ----------


 ---------- 2017-08-02 10:00:00 : 강남동   20773 ----------


 ---------- 2017-08-02 10:00:00 : 동내면   20774 ----------


 ---------- 2017-08-02 10:00:00 : 남산면   20775 ----------


 ---------- 2017-08-02 10:00:00 : 신사우동   20776 ----------


 ---------- 2017-08-02 10:00:00 : 동  면   20778 ----------


 ---------- 2017-08-02 11:00:00 : 신사우동   20779 ----------


 ---------- 2017-08-02 12:00:00 : 서  면   20780 ----------


 ---------- 2017-08-02 13:00:00 : 석사동   20781 ----------


 ---------- 2017-08-02 13:00:00 : 서  면   20782 ----------


 ---------- 2017-08-02 13:00:00 : 남  면   20784 ----------


 ---------- 2017-08-02 13:00:00 : 동내면   20785 ----------


 ---------- 2017-08-02 13:00:00 : 남산면   20786 ----------


 ---------- 2017-08-02 13:00:00 : 퇴계동   20787 ----------


 ---------- 2017-08-02 14:00:00 : 효자1동   20788 ----------


 ---------- 2017-08-02 14:00:00 : 남산면   20790 ----------


 ---------- 2017-08-02 15:00:00 : 남  면   20791 ----------


 ---------- 2017-08-02 16:00:00 : 신동면   20792 ----------


 ---------- 2017-08-02 16:00:00 : 남  면   20793 ----------

 ---------- 2017-08-02 16:00:00 : 신사우동   20794 ----------


 ---------- 2017-08-02 17:00:00 : 동내면   20796 ----------


 ---------- 2017-08-02 18:00:00 : 동내면   20797 ----------


 ---------- 2017-08-02 18:00:00 : 남산면   20798 ----------


 ---------- 2017-08-02 18:00:00 : 소양동   20799 ----------


 ---------- 2017-08-02 18:00:00 : 동  면   20800 ----------


 ---------- 2017-08-02 19:00:00 : 남산면   20801 ----------


 ---------- 2017-08-02 22:00:00 : 퇴계동   20802 ----------


 ---------- 2017-08-03 08:00:00 : 사북면   20803 ----------


 ---------- 2017-08-03 08:00:00 : 남산면   20804 ----------


 ---------- 2017-08-03 09:00:00 : 사북면   20805 ----------


 ---------- 2017-08-03 09:00:00 : 동내면   20806 ----------


 ---------- 2017-08-03 09:00:00 : 남산면   20807 ----------


 ---------- 2017-08-03 09:00:00 : 신북읍   20808 ----------


 ---------- 2017-08-03 10:00:00 : 사북면   20810 ----------


 ---------- 2017-08-03 10:00:00 : 동내면   20811 ----------


 ---------- 2017-08-03 10:00:00 : 퇴계동   20813 ----------


 ---------- 2017-08-03 10:00:00 : 북산면   20814 ----------


 ---------- 2017-08-03 11:00:00 : 퇴계동   20815 ----------


 ---------- 2017-08-03 12:00:00 : 사북면   20816 ----------


 ---------- 2017-08-03 14:00:00 : 서  면   20817 ----------


 ---------- 2017-08-03 15:00:00 : 남산면   20818 ----------


 ---------- 2017-08-03 17:00:00 : 사북면   20820 ----------


 ---------- 2017-08-03 17:00:00 : 동내면   20821 ----------


 ---------- 2017-08-03 17:00:00 : 북산면   20822 ----------


 ---------- 2017-08-03 18:00:00 : 소양동   20823 ----------


 ---------- 2017-08-03 19:00:00 : 신북읍   20826 ----------


 ---------- 2017-08-03 21:00:00 : 강남동   20827 ----------


 ---------- 2017-08-03 22:00:00 : 신사우동   20829 ----------


 ---------- 2017-08-03 22:00:00 : 신북읍   20831 ----------


 ---------- 2017-08-03 23:00:00 : 약사명동   20832 ----------


 ---------- 2017-08-04 00:00:00 : 효자1동   20834 ----------


 ---------- 2017-08-04 01:00:00 : 효자1동   20835 ----------


 ---------- 2017-08-04 02:00:00 : 신북읍   20839 ----------


 ---------- 2017-08-04 07:00:00 : 강남동   20840 ----------


 ---------- 2017-08-04 08:00:00 : 후평1동   20841 ----------


 ---------- 2017-08-04 09:00:00 : 사북면   20842 ----------


 ---------- 2017-08-04 09:00:00 : 남산면   20843 ----------


 ---------- 2017-08-04 09:00:00 : 신사우동   20844 ----------


 ---------- 2017-08-04 09:00:00 : 소양동   20846 ----------


 ---------- 2017-08-04 10:00:00 : 신동면   20848 ----------


 ---------- 2017-08-04 10:00:00 : 남산면   20849 ----------


 ---------- 2017-08-04 10:00:00 : 신북읍   20850 ----------


 ---------- 2017-08-04 11:00:00 : 효자1동   20851 ----------


 ---------- 2017-08-04 11:00:00 : 남산면   20852 ----------


 ---------- 2017-08-04 12:00:00 : 신동면   20855 ----------


 ---------- 2017-08-04 12:00:00 : 남산면   20858 ----------


 ---------- 2017-08-04 12:00:00 : 후평1동   20859 ----------


 ---------- 2017-08-04 13:00:00 : 신북읍   20860 ----------


 ---------- 2017-08-04 14:00:00 : 강남동   20861 ----------


 ---------- 2017-08-04 14:00:00 : 서  면   20862 ----------


 ---------- 2017-08-04 14:00:00 : 남산면   20863 ----------


 ---------- 2017-08-04 14:00:00 : 동산면   20864 ----------


 ---------- 2017-08-04 15:00:00 : 후평1동   20865 ----------


 ---------- 2017-08-04 16:00:00 : 석사동   20866 ----------


 ---------- 2017-08-04 16:00:00 : 동산면   20867 ----------


 ---------- 2017-08-04 17:00:00 : 석사동   20868 ----------


 ---------- 2017-08-04 17:00:00 : 동내면   20869 ----------


 ---------- 2017-08-04 17:00:00 : 후평1동   20871 ----------


 ---------- 2017-08-04 18:00:00 : 사북면   20872 ----------


 ---------- 2017-08-04 18:00:00 : 동  면   20873 ----------


 ---------- 2017-08-04 22:00:00 : 신사우동   20874 ----------


 ---------- 2017-08-04 23:00:00 : 후평1동   20875 ----------


 ---------- 2017-08-05 06:00:00 : 신북읍   20876 ----------


 ---------- 2017-08-05 08:00:00 : 신사우동   20877 ----------


 ---------- 2017-08-05 09:00:00 : 신동면   20878 ----------


 ---------- 2017-08-05 09:00:00 : 남  면   20880 ----------


 ---------- 2017-08-05 10:00:00 : 신동면   20881 ----------


 ---------- 2017-08-05 10:00:00 : 남산면   20882 ----------


 ---------- 2017-08-05 10:00:00 : 후평1동   20883 ----------


 ---------- 2017-08-05 11:00:00 : 남산면   20884 ----------


 ---------- 2017-08-05 11:00:00 : 소양동   20885 ----------


 ---------- 2017-08-05 12:00:00 : 신사우동   20887 ----------


 ---------- 2017-08-05 12:00:00 : 후평1동   20888 ----------


 ---------- 2017-08-05 12:00:00 : 동산면   20889 ----------


 ---------- 2017-08-05 13:00:00 : 강남동   20890 ----------


 ---------- 2017-08-05 13:00:00 : 남  면   20891 ----------


 ---------- 2017-08-05 13:00:00 : 사북면   20892 ----------


 ---------- 2017-08-05 13:00:00 : 퇴계동   20893 ----------


 ---------- 2017-08-05 14:00:00 : 동내면   20894 ----------


 ---------- 2017-08-05 14:00:00 : 남산면   20896 ----------


 ---------- 2017-08-05 15:00:00 : 퇴계동   20897 ----------


 ---------- 2017-08-05 16:00:00 : 남  면   20898 ----------


 ---------- 2017-08-05 16:00:00 : 동산면   20899 ----------


 ---------- 2017-08-05 18:00:00 : 동내면   20900 ----------


 ---------- 2017-08-05 19:00:00 : 동  면   20901 ----------


 ---------- 2017-08-05 21:00:00 : 사북면   20902 ----------


 ---------- 2017-08-05 23:00:00 : 석사동   20907 ----------


 ---------- 2017-08-06 06:00:00 : 약사명동   20908 ----------


 ---------- 2017-08-06 06:00:00 : 교  동   20909 ----------


 ---------- 2017-08-06 08:00:00 : 동내면   20910 ----------


 ---------- 2017-08-06 10:00:00 : 남산면   20911 ----------


 ---------- 2017-08-06 12:00:00 : 석사동   20912 ----------


 ---------- 2017-08-06 12:00:00 : 신동면   20913 ----------


 ---------- 2017-08-06 13:00:00 : 서  면   20914 ----------


 ---------- 2017-08-06 13:00:00 : 신사우동   20915 ----------


 ---------- 2017-08-06 14:00:00 : 동산면   20916 ----------


 ---------- 2017-08-06 16:00:00 : 석사동   20917 ----------


 ---------- 2017-08-06 16:00:00 : 신동면   20919 ----------


 ---------- 2017-08-06 17:00:00 : 신사우동   20920 ----------


 ---------- 2017-08-06 18:00:00 : 소양동   20921 ----------


 ---------- 2017-08-06 20:00:00 : 강남동   20922 ----------


 ---------- 2017-08-07 07:00:00 : 석사동   20923 ----------


 ---------- 2017-08-07 07:00:00 : 서  면   20924 ----------


 ---------- 2017-08-07 08:00:00 : 동내면   20925 ----------


 ---------- 2017-08-07 08:00:00 : 후평1동   20926 ----------


 ---------- 2017-08-07 09:00:00 : 석사동   20927 ----------


 ---------- 2017-08-07 09:00:00 : 신동면   20929 ----------


 ---------- 2017-08-07 09:00:00 : 효자1동   20930 ----------


 ---------- 2017-08-07 09:00:00 : 북산면   20931 ----------


 ---------- 2017-08-07 10:00:00 : 석사동   20932 ----------


 ---------- 2017-08-07 10:00:00 : 신동면   20934 ----------


 ---------- 2017-08-07 10:00:00 : 남산면   20936 ----------


 ---------- 2017-08-07 10:00:00 : 신사우동   20937 ----------


 ---------- 2017-08-07 10:00:00 : 동  면   20938 ----------


 ---------- 2017-08-07 11:00:00 : 강남동   20939 ----------


 ---------- 2017-08-07 11:00:00 : 서  면   20940 ----------


 ---------- 2017-08-07 11:00:00 : 동내면   20941 ----------


 ---------- 2017-08-07 11:00:00 : 후평1동   20942 ----------


 ---------- 2017-08-07 12:00:00 : 남산면   20943 ----------


 ---------- 2017-08-07 12:00:00 : 후평1동   20945 ----------


 ---------- 2017-08-07 13:00:00 : 사북면   20946 ----------


 ---------- 2017-08-07 13:00:00 : 동  면   20947 ----------


 ---------- 2017-08-07 14:00:00 : 동  면   20948 ----------


 ---------- 2017-08-07 15:00:00 : 강남동   20949 ----------


 ---------- 2017-08-07 15:00:00 : 북산면   20951 ----------


 ---------- 2017-08-07 16:00:00 : 동  면   20952 ----------


 ---------- 2017-08-07 16:00:00 : 북산면   20953 ----------


 ---------- 2017-08-07 17:00:00 : 신사우동   20954 ----------


 ---------- 2017-08-07 18:00:00 : 석사동   20955 ----------


 ---------- 2017-08-07 18:00:00 : 신북읍   20956 ----------


 ---------- 2017-08-07 19:00:00 : 남산면   20957 ----------


 ---------- 2017-08-07 22:00:00 : 후평1동   20958 ----------


 ---------- 2017-08-08 08:00:00 : 강남동   20959 ----------


 ---------- 2017-08-08 08:00:00 : 서  면   20961 ----------


 ---------- 2017-08-08 08:00:00 : 동내면   20963 ----------

 ---------- 2017-08-08 09:00:00 : 강남동   20964 ----------


 ---------- 2017-08-08 09:00:00 : 서  면   20966 ----------


 ---------- 2017-08-08 09:00:00 : 동  면   20967 ----------


 ---------- 2017-08-08 09:00:00 : 후평1동   20968 ----------


 ---------- 2017-08-08 09:00:00 : 동산면   20969 ----------


 ---------- 2017-08-08 10:00:00 : 서  면   20971 ----------


 ---------- 2017-08-08 10:00:00 : 동  면   20972 ----------


 ---------- 2017-08-08 11:00:00 : 석사동   20973 ----------


 ---------- 2017-08-08 11:00:00 : 강남동   20974 ----------


 ---------- 2017-08-08 11:00:00 : 신사우동   20975 ----------


 ---------- 2017-08-08 12:00:00 : 퇴계동   20976 ----------


 ---------- 2017-08-08 13:00:00 : 석사동   20977 ----------


 ---------- 2017-08-08 13:00:00 : 사북면   20978 ----------


 ---------- 2017-08-08 13:00:00 : 동내면   20979 ----------


 ---------- 2017-08-08 13:00:00 : 신북읍   20980 ----------


 ---------- 2017-08-08 13:00:00 : 북산면   20981 ----------


 ---------- 2017-08-08 14:00:00 : 서  면   20982 ----------


 ---------- 2017-08-08 14:00:00 : 동내면   20983 ----------


 ---------- 2017-08-08 14:00:00 : 동  면   20984 ----------


 ---------- 2017-08-08 15:00:00 : 동내면   20986 ----------


 ---------- 2017-08-08 15:00:00 : 신북읍   20987 ----------


 ---------- 2017-08-08 15:00:00 : 동  면   20989 ----------


 ---------- 2017-08-08 16:00:00 : 강남동   20990 ----------


 ---------- 2017-08-08 16:00:00 : 효자1동   20991 ----------


 ---------- 2017-08-08 17:00:00 : 동내면   20992 ----------


 ---------- 2017-08-08 17:00:00 : 후평1동   20993 ----------


 ---------- 2017-08-08 18:00:00 : 동  면   20994 ----------


 ---------- 2017-08-08 21:00:00 : 남산면   20995 ----------


 ---------- 2017-08-08 22:00:00 : 퇴계동   20996 ----------


 ---------- 2017-08-09 08:00:00 : 신북읍   20997 ----------


 ---------- 2017-08-09 09:00:00 : 강남동   20998 ----------


 ---------- 2017-08-09 09:00:00 : 서  면   20999 ----------


 ---------- 2017-08-09 09:00:00 : 사북면   21000 ----------


 ---------- 2017-08-09 09:00:00 : 동산면   21001 ----------


 ---------- 2017-08-09 10:00:00 : 석사동   21002 ----------


 ---------- 2017-08-09 10:00:00 : 신동면   21003 ----------


 ---------- 2017-08-09 10:00:00 : 강남동   21004 ----------


 ---------- 2017-08-09 11:00:00 : 강남동   21005 ----------


 ---------- 2017-08-09 11:00:00 : 동산면   21010 ----------


 ---------- 2017-08-09 12:00:00 : 동  면   21011 ----------


 ---------- 2017-08-09 13:00:00 : 석사동   21012 ----------


 ---------- 2017-08-09 13:00:00 : 신사우동   21013 ----------


 ---------- 2017-08-09 13:00:00 : 동  면   21015 ----------


 ---------- 2017-08-09 14:00:00 : 석사동   21016 ----------


 ---------- 2017-08-09 14:00:00 : 서  면   21017 ----------


 ---------- 2017-08-09 14:00:00 : 남산면   21019 ----------


 ---------- 2017-08-09 15:00:00 : 신동면   21020 ----------


 ---------- 2017-08-09 15:00:00 : 서  면   21021 ----------


 ---------- 2017-08-09 15:00:00 : 신사우동   21022 ----------


 ---------- 2017-08-09 15:00:00 : 동  면   21023 ----------


 ---------- 2017-08-09 16:00:00 : 강남동   21024 ----------


 ---------- 2017-08-09 17:00:00 : 강남동   21025 ----------


 ---------- 2017-08-09 17:00:00 : 동  면   21029 ----------


 ---------- 2017-08-09 18:00:00 : 동내면   21030 ----------


 ---------- 2017-08-09 19:00:00 : 동  면   21032 ----------


 ---------- 2017-08-09 21:00:00 : 동내면   21033 ----------


 ---------- 2017-08-10 08:00:00 : 사북면   21034 ----------


 ---------- 2017-08-10 09:00:00 : 신동면   21035 ----------


 ---------- 2017-08-10 09:00:00 : 서  면   21036 ----------


 ---------- 2017-08-10 09:00:00 : 신북읍   21038 ----------


 ---------- 2017-08-10 10:00:00 : 북산면   21039 ----------


 ---------- 2017-08-10 11:00:00 : 퇴계동   21040 ----------


 ---------- 2017-08-10 12:00:00 : 강남동   21041 ----------


 ---------- 2017-08-10 13:00:00 : 강남동   21042 ----------


 ---------- 2017-08-10 13:00:00 : 신사우동   21043 ----------


 ---------- 2017-08-10 14:00:00 : 남산면   21044 ----------


 ---------- 2017-08-10 16:00:00 : 동내면   21045 ----------


 ---------- 2017-08-10 16:00:00 : 신북읍   21046 ----------


 ---------- 2017-08-10 22:00:00 : 석사동   21047 ----------


 ---------- 2017-08-11 00:00:00 : 신동면   21048 ----------


 ---------- 2017-08-11 08:00:00 : 효자1동   21049 ----------


 ---------- 2017-08-11 08:00:00 : 신사우동   21050 ----------


 ---------- 2017-08-11 09:00:00 : 신동면   21051 ----------


 ---------- 2017-08-11 09:00:00 : 사북면   21052 ----------


 ---------- 2017-08-11 09:00:00 : 신북읍   21053 ----------


 ---------- 2017-08-11 09:00:00 : 후평1동   21054 ----------


 ---------- 2017-08-11 10:00:00 : 신북읍   21056 ----------


 ---------- 2017-08-11 10:00:00 : 퇴계동   21057 ----------


 ---------- 2017-08-11 11:00:00 : 남  면   21058 ----------


 ---------- 2017-08-11 12:00:00 : 남  면   21059 ----------


 ---------- 2017-08-11 12:00:00 : 사북면   21060 ----------


 ---------- 2017-08-11 12:00:00 : 동내면   21061 ----------


 ---------- 2017-08-11 13:00:00 : 남산면   21062 ----------


 ---------- 2017-08-11 13:00:00 : 동산면   21063 ----------


 ---------- 2017-08-11 14:00:00 : 신사우동   21067 ----------


 ---------- 2017-08-11 15:00:00 : 남산면   21069 ----------


 ---------- 2017-08-11 16:00:00 : 강남동   21070 ----------


 ---------- 2017-08-11 18:00:00 : 석사동   21071 ----------


 ---------- 2017-08-11 18:00:00 : 신북읍   21072 ----------


 ---------- 2017-08-11 19:00:00 : 석사동   21074 ----------


 ---------- 2017-08-11 21:00:00 : 강남동   21075 ----------


 ---------- 2017-08-11 22:00:00 : 신사우동   21076 ----------


 ---------- 2017-08-12 03:00:00 : 후평1동   21077 ----------


 ---------- 2017-08-12 05:00:00 : 후평1동   21078 ----------


 ---------- 2017-08-12 08:00:00 : 동내면   21079 ----------


 ---------- 2017-08-12 09:00:00 : 동  면   21080 ----------


 ---------- 2017-08-12 10:00:00 : 동  면   21081 ----------


 ---------- 2017-08-12 11:00:00 : 효자1동   21082 ----------


 ---------- 2017-08-12 12:00:00 : 강남동   21083 ----------


 ---------- 2017-08-12 13:00:00 : 남산면   21084 ----------


 ---------- 2017-08-12 15:00:00 : 석사동   21085 ----------


 ---------- 2017-08-12 15:00:00 : 남산면   21086 ----------


 ---------- 2017-08-12 16:00:00 : 남산면   21087 ----------


 ---------- 2017-08-12 17:00:00 : 동  면   21088 ----------


 ---------- 2017-08-12 17:00:00 : 퇴계동   21089 ----------


 ---------- 2017-08-12 18:00:00 : 신북읍   21090 ----------


 ---------- 2017-08-12 19:00:00 : 동  면   21091 ----------


 ---------- 2017-08-12 21:00:00 : 강남동   21092 ----------


 ---------- 2017-08-12 21:00:00 : 서  면   21093 ----------


 ---------- 2017-08-13 00:00:00 : 신북읍   21094 ----------


 ---------- 2017-08-13 04:00:00 : 효자1동   21095 ----------


 ---------- 2017-08-13 07:00:00 : 동  면   21096 ----------


 ---------- 2017-08-13 08:00:00 : 신북읍   21097 ----------


 ---------- 2017-08-13 09:00:00 : 남산면   21098 ----------


 ---------- 2017-08-13 09:00:00 : 신북읍   21099 ----------


 ---------- 2017-08-13 09:00:00 : 퇴계동   21100 ----------


 ---------- 2017-08-13 12:00:00 : 서  면   21101 ----------


 ---------- 2017-08-13 12:00:00 : 남산면   21102 ----------


 ---------- 2017-08-13 12:00:00 : 동  면   21103 ----------


 ---------- 2017-08-13 13:00:00 : 신사우동   21104 ----------


 ---------- 2017-08-13 14:00:00 : 북산면   21105 ----------


 ---------- 2017-08-13 15:00:00 : 신동면   21106 ----------


 ---------- 2017-08-13 15:00:00 : 사북면   21107 ----------


 ---------- 2017-08-13 15:00:00 : 조운동   21108 ----------


 ---------- 2017-08-13 16:00:00 : 강남동   21109 ----------


 ---------- 2017-08-13 17:00:00 : 강남동   21110 ----------


 ---------- 2017-08-13 17:00:00 : 남  면   21111 ----------


 ---------- 2017-08-13 18:00:00 : 서  면   21112 ----------


 ---------- 2017-08-13 19:00:00 : 효자1동   21113 ----------


 ---------- 2017-08-13 21:00:00 : 후평1동   21114 ----------


 ---------- 2017-08-14 07:00:00 : 효자1동   21116 ----------


 ---------- 2017-08-14 08:00:00 : 동내면   21117 ----------


 ---------- 2017-08-14 09:00:00 : 석사동   21118 ----------


 ---------- 2017-08-14 09:00:00 : 강남동   21119 ----------


 ---------- 2017-08-14 09:00:00 : 동내면   21120 ----------


 ---------- 2017-08-14 09:00:00 : 후평1동   21121 ----------


 ---------- 2017-08-14 09:00:00 : 북산면   21122 ----------

 ---------- 2017-08-14 10:00:00 : 효자1동   21123 ----------


 ---------- 2017-08-14 10:00:00 : 신북읍   21125 ----------


 ---------- 2017-08-14 10:00:00 : 퇴계동   21126 ----------


 ---------- 2017-08-14 10:00:00 : 교  동   21127 ----------


 ---------- 2017-08-14 11:00:00 : 강남동   21128 ----------


 ---------- 2017-08-14 11:00:00 : 소양동   21130 ----------


 ---------- 2017-08-14 12:00:00 : 서  면   21131 ----------


 ---------- 2017-08-14 12:00:00 : 소양동   21132 ----------


 ---------- 2017-08-14 13:00:00 : 석사동   21133 ----------


 ---------- 2017-08-14 13:00:00 : 강남동   21134 ----------


 ---------- 2017-08-14 13:00:00 : 효자1동   21135 ----------


 ---------- 2017-08-14 14:00:00 : 신동면   21136 ----------


 ---------- 2017-08-14 14:00:00 : 서  면   21137 ----------


 ---------- 2017-08-14 14:00:00 : 동  면   21138 ----------


 ---------- 2017-08-14 15:00:00 : 석사동   21139 ----------


 ---------- 2017-08-14 15:00:00 : 서  면   21140 ----------


 ---------- 2017-08-14 15:00:00 : 사북면   21141 ----------


 ---------- 2017-08-14 16:00:00 : 강남동   21142 ----------


 ---------- 2017-08-15 06:00:00 : 강남동   21143 ----------


 ---------- 2017-08-15 07:00:00 : 동내면   21144 ----------


 ---------- 2017-08-15 09:00:00 : 동내면   21145 ----------


 ---------- 2017-08-15 09:00:00 : 남산면   21146 ----------


 ---------- 2017-08-15 11:00:00 : 석사동   21147 ----------


 ---------- 2017-08-15 11:00:00 : 퇴계동   21148 ----------


 ---------- 2017-08-15 12:00:00 : 강남동   21149 ----------


 ---------- 2017-08-15 12:00:00 : 약사명동   21150 ----------


 ---------- 2017-08-15 13:00:00 : 교  동   21151 ----------


 ---------- 2017-08-15 14:00:00 : 신북읍   21152 ----------


 ---------- 2017-08-15 22:00:00 : 신북읍   21155 ----------


 ---------- 2017-08-16 08:00:00 : 후평1동   21156 ----------


 ---------- 2017-08-16 09:00:00 : 석사동   21157 ----------


 ---------- 2017-08-16 09:00:00 : 후평1동   21158 ----------


 ---------- 2017-08-16 09:00:00 : 퇴계동   21159 ----------


 ---------- 2017-08-16 09:00:00 : 북산면   21160 ----------


 ---------- 2017-08-16 10:00:00 : 퇴계동   21161 ----------


 ---------- 2017-08-16 10:00:00 : 조운동   21162 ----------


 ---------- 2017-08-16 11:00:00 : 강남동   21163 ----------


 ---------- 2017-08-16 11:00:00 : 동  면   21165 ----------


 ---------- 2017-08-16 13:00:00 : 동  면   21166 ----------


 ---------- 2017-08-16 14:00:00 : 신동면   21167 ----------


 ---------- 2017-08-16 15:00:00 : 동  면   21168 ----------


 ---------- 2017-08-16 15:00:00 : 후평1동   21169 ----------


 ---------- 2017-08-16 16:00:00 : 소양동   21170 ----------


 ---------- 2017-08-16 17:00:00 : 동  면   21171 ----------


 ---------- 2017-08-16 19:00:00 : 동내면   21173 ----------


 ---------- 2017-08-16 21:00:00 : 석사동   21174 ----------


 ---------- 2017-08-16 21:00:00 : 서  면   21175 ----------


 ---------- 2017-08-16 21:00:00 : 소양동   21177 ----------


 ---------- 2017-08-16 22:00:00 : 동  면   21178 ----------


 ---------- 2017-08-16 23:00:00 : 신사우동   21179 ----------


 ---------- 2017-08-17 06:00:00 : 근화동   21180 ----------


 ---------- 2017-08-17 08:00:00 : 사북면   21181 ----------


 ---------- 2017-08-17 09:00:00 : 석사동   21182 ----------


 ---------- 2017-08-17 10:00:00 : 강남동   21183 ----------


 ---------- 2017-08-17 11:00:00 : 동내면   21184 ----------


 ---------- 2017-08-17 11:00:00 : 동  면   21185 ----------


 ---------- 2017-08-17 13:00:00 : 동내면   21186 ----------


 ---------- 2017-08-17 14:00:00 : 후평1동   21187 ----------


 ---------- 2017-08-17 14:00:00 : 조운동   21188 ----------


 ---------- 2017-08-17 15:00:00 : 남  면   21189 ----------


 ---------- 2017-08-17 15:00:00 : 후평1동   21190 ----------


 ---------- 2017-08-17 16:00:00 : 동내면   21191 ----------


 ---------- 2017-08-17 16:00:00 : 신사우동   21192 ----------


 ---------- 2017-08-17 17:00:00 : 석사동   21193 ----------


 ---------- 2017-08-17 18:00:00 : 신북읍   21194 ----------


 ---------- 2017-08-17 18:00:00 : 후평1동   21195 ----------


 ---------- 2017-08-18 00:00:00 : 효자1동   21196 ----------


 ---------- 2017-08-18 01:00:00 : 석사동   21197 ----------


 ---------- 2017-08-18 08:00:00 : 동내면   21198 ----------


 ---------- 2017-08-18 09:00:00 : 효자1동   21199 ----------


 ---------- 2017-08-18 10:00:00 : 신사우동   21200 ----------


 ---------- 2017-08-18 11:00:00 : 강남동   21201 ----------


 ---------- 2017-08-18 12:00:00 : 신사우동   21202 ----------


 ---------- 2017-08-18 12:00:00 : 동산면   21203 ----------


 ---------- 2017-08-18 13:00:00 : 후평1동   21204 ----------


 ---------- 2017-08-18 14:00:00 : 동  면   21205 ----------


 ---------- 2017-08-18 14:00:00 : 후평1동   21206 ----------


 ---------- 2017-08-18 15:00:00 : 사북면   21207 ----------


 ---------- 2017-08-18 15:00:00 : 동  면   21208 ----------


 ---------- 2017-08-18 18:00:00 : 퇴계동   21209 ----------


 ---------- 2017-08-18 18:00:00 : 동산면   21210 ----------


 ---------- 2017-08-18 20:00:00 : 효자1동   21211 ----------


 ---------- 2017-08-19 06:00:00 : 교  동   21212 ----------


 ---------- 2017-08-19 10:00:00 : 강남동   21213 ----------


 ---------- 2017-08-19 10:00:00 : 남산면   21214 ----------


 ---------- 2017-08-19 11:00:00 : 퇴계동   21215 ----------


 ---------- 2017-08-19 12:00:00 : 사북면   21216 ----------


 ---------- 2017-08-19 12:00:00 : 약사명동   21217 ----------


 ---------- 2017-08-19 13:00:00 : 서  면   21218 ----------


 ---------- 2017-08-19 13:00:00 : 신사우동   21219 ----------


 ---------- 2017-08-19 14:00:00 : 동산면   21221 ----------


 ---------- 2017-08-19 15:00:00 : 서  면   21222 ----------


 ---------- 2017-08-19 15:00:00 : 동  면   21223 ----------


 ---------- 2017-08-19 16:00:00 : 남산면   21224 ----------


 ---------- 2017-08-19 16:00:00 : 신사우동   21225 ----------


 ---------- 2017-08-19 18:00:00 : 남산면   21227 ----------


 ---------- 2017-08-19 20:00:00 : 남  면   21228 ----------


 ---------- 2017-08-20 00:00:00 : 후평1동   21229 ----------


 ---------- 2017-08-20 08:00:00 : 효자1동   21231 ----------


 ---------- 2017-08-20 09:00:00 : 교  동   21232 ----------


 ---------- 2017-08-20 10:00:00 : 동산면   21233 ----------


 ---------- 2017-08-20 13:00:00 : 동  면   21234 ----------


 ---------- 2017-08-20 15:00:00 : 퇴계동   21235 ----------


 ---------- 2017-08-20 16:00:00 : 근화동   21236 ----------


 ---------- 2017-08-20 16:00:00 : 신북읍   21237 ----------


 ---------- 2017-08-21 08:00:00 : 남산면   21239 ----------


 ---------- 2017-08-21 09:00:00 : 근화동   21240 ----------


 ---------- 2017-08-21 09:00:00 : 퇴계동   21241 ----------


 ---------- 2017-08-21 10:00:00 : 남산면   21243 ----------


 ---------- 2017-08-21 11:00:00 : 후평1동   21244 ----------


 ---------- 2017-08-21 12:00:00 : 석사동   21245 ----------


 ---------- 2017-08-21 12:00:00 : 동내면   21246 ----------


 ---------- 2017-08-21 13:00:00 : 효자1동   21247 ----------


 ---------- 2017-08-21 14:00:00 : 효자1동   21248 ----------


 ---------- 2017-08-21 15:00:00 : 신북읍   21249 ----------


 ---------- 2017-08-21 16:00:00 : 석사동   21250 ----------


 ---------- 2017-08-21 19:00:00 : 석사동   21251 ----------


 ---------- 2017-08-21 19:00:00 : 남산면   21252 ----------


 ---------- 2017-08-21 21:00:00 : 석사동   21253 ----------


 ---------- 2017-08-22 09:00:00 : 사북면   21254 ----------


 ---------- 2017-08-22 09:00:00 : 퇴계동   21255 ----------


 ---------- 2017-08-22 10:00:00 : 남산면   21256 ----------


 ---------- 2017-08-22 10:00:00 : 신사우동   21257 ----------


 ---------- 2017-08-22 10:00:00 : 신북읍   21259 ----------


 ---------- 2017-08-22 11:00:00 : 후평1동   21260 ----------


 ---------- 2017-08-22 12:00:00 : 근화동   21261 ----------


 ---------- 2017-08-22 13:00:00 : 효자1동   21262 ----------


 ---------- 2017-08-22 13:00:00 : 후평1동   21264 ----------


 ---------- 2017-08-22 14:00:00 : 석사동   21265 ----------


 ---------- 2017-08-22 14:00:00 : 신사우동   21266 ----------


 ---------- 2017-08-22 16:00:00 : 남산면   21267 ----------


 ---------- 2017-08-22 16:00:00 : 신북읍   21268 ----------


 ---------- 2017-08-22 16:00:00 : 후평1동   21270 ----------


 ---------- 2017-08-22 17:00:00 : 남  면   21271 ----------


 ---------- 2017-08-22 18:00:00 : 신사우동   21272 ----------


 ---------- 2017-08-22 20:00:00 : 신북읍   21273 ----------

 ---------- 2017-08-23 02:00:00 : 효자1동   21275 ----------


 ---------- 2017-08-23 08:00:00 : 신사우동   21276 ----------


 ---------- 2017-08-23 08:00:00 : 후평1동   21277 ----------


 ---------- 2017-08-23 09:00:00 : 근화동   21278 ----------


 ---------- 2017-08-23 11:00:00 : 석사동   21279 ----------


 ---------- 2017-08-23 12:00:00 : 신사우동   21280 ----------


 ---------- 2017-08-23 14:00:00 : 석사동   21281 ----------


 ---------- 2017-08-23 14:00:00 : 강남동   21283 ----------


 ---------- 2017-08-23 14:00:00 : 동내면   21284 ----------


 ---------- 2017-08-23 15:00:00 : 서  면   21285 ----------


 ---------- 2017-08-23 15:00:00 : 근화동   21286 ----------


 ---------- 2017-08-23 18:00:00 : 강남동   21287 ----------


 ---------- 2017-08-23 18:00:00 : 동  면   21288 ----------


 ---------- 2017-08-24 09:00:00 : 석사동   21289 ----------


 ---------- 2017-08-24 09:00:00 : 강남동   21290 ----------


 ---------- 2017-08-24 10:00:00 : 동내면   21291 ----------


 ---------- 2017-08-24 10:00:00 : 근화동   21292 ----------


 ---------- 2017-08-24 10:00:00 : 신북읍   21294 ----------


 ---------- 2017-08-24 13:00:00 : 서  면   21295 ----------


 ---------- 2017-08-24 13:00:00 : 동  면   21296 ----------


 ---------- 2017-08-24 14:00:00 : 근화동   21297 ----------


 ---------- 2017-08-24 14:00:00 : 신사우동   21298 ----------


 ---------- 2017-08-24 14:00:00 : 소양동   21299 ----------


 ---------- 2017-08-24 17:00:00 : 강남동   21300 ----------


 ---------- 2017-08-24 17:00:00 : 퇴계동   21301 ----------


 ---------- 2017-08-24 18:00:00 : 동  면   21302 ----------


 ---------- 2017-08-24 21:00:00 : 동  면   21303 ----------


 ---------- 2017-08-24 23:00:00 : 후평1동   21304 ----------


 ---------- 2017-08-25 03:00:00 : 효자1동   21305 ----------


 ---------- 2017-08-25 05:00:00 : 남산면   21306 ----------


 ---------- 2017-08-25 07:00:00 : 근화동   21308 ----------


 ---------- 2017-08-25 08:00:00 : 효자1동   21309 ----------


 ---------- 2017-08-25 09:00:00 : 남산면   21310 ----------


 ---------- 2017-08-25 09:00:00 : 동  면   21312 ----------


 ---------- 2017-08-25 10:00:00 : 강남동   21313 ----------


 ---------- 2017-08-25 10:00:00 : 남산면   21314 ----------


 ---------- 2017-08-25 11:00:00 : 석사동   21315 ----------


 ---------- 2017-08-25 14:00:00 : 석사동   21316 ----------


 ---------- 2017-08-25 14:00:00 : 강남동   21317 ----------


 ---------- 2017-08-25 15:00:00 : 신북읍   21318 ----------


 ---------- 2017-08-25 16:00:00 : 석사동   21319 ----------


 ---------- 2017-08-25 17:00:00 : 신북읍   21321 ----------


 ---------- 2017-08-25 17:00:00 : 퇴계동   21322 ----------


 ---------- 2017-08-25 18:00:00 : 석사동   21323 ----------


 ---------- 2017-08-25 18:00:00 : 효자1동   21324 ----------


 ---------- 2017-08-25 18:00:00 : 퇴계동   21325 ----------


 ---------- 2017-08-25 18:00:00 : 조운동   21326 ----------


 ---------- 2017-08-25 19:00:00 : 신사우동   21327 ----------


 ---------- 2017-08-26 10:00:00 : 동산면   21328 ----------


 ---------- 2017-08-26 11:00:00 : 신북읍   21329 ----------


 ---------- 2017-08-26 13:00:00 : 동내면   21330 ----------


 ---------- 2017-08-26 13:00:00 : 남산면   21331 ----------


 ---------- 2017-08-26 14:00:00 : 남산면   21332 ----------


 ---------- 2017-08-26 15:00:00 : 동내면   21333 ----------


 ---------- 2017-08-26 16:00:00 : 신사우동   21334 ----------


 ---------- 2017-08-26 16:00:00 : 신북읍   21335 ----------


 ---------- 2017-08-26 16:00:00 : 후평1동   21336 ----------


 ---------- 2017-08-26 17:00:00 : 신동면   21337 ----------


 ---------- 2017-08-26 17:00:00 : 강남동   21339 ----------


 ---------- 2017-08-26 17:00:00 : 동내면   21340 ----------


 ---------- 2017-08-26 18:00:00 : 서  면   21341 ----------


 ---------- 2017-08-26 19:00:00 : 근화동   21342 ----------


 ---------- 2017-08-26 20:00:00 : 근화동   21343 ----------


 ---------- 2017-08-27 08:00:00 : 강남동   21344 ----------


 ---------- 2017-08-27 08:00:00 : 근화동   21345 ----------


 ---------- 2017-08-27 08:00:00 : 신사우동   21346 ----------


 ---------- 2017-08-27 09:00:00 : 신동면   21347 ----------


 ---------- 2017-08-27 09:00:00 : 동  면   21348 ----------


 ---------- 2017-08-27 09:00:00 : 후평1동   21349 ----------


 ---------- 2017-08-27 10:00:00 : 석사동   21350 ----------


 ---------- 2017-08-27 10:00:00 : 동  면   21351 ----------


 ---------- 2017-08-27 13:00:00 : 서  면   21353 ----------


 ---------- 2017-08-27 14:00:00 : 동내면   21354 ----------


 ---------- 2017-08-27 14:00:00 : 북산면   21355 ----------


 ---------- 2017-08-27 15:00:00 : 서  면   21356 ----------


 ---------- 2017-08-27 15:00:00 : 조운동   21357 ----------


 ---------- 2017-08-27 17:00:00 : 남  면   21359 ----------


 ---------- 2017-08-27 17:00:00 : 근화동   21360 ----------


 ---------- 2017-08-27 17:00:00 : 퇴계동   21361 ----------


 ---------- 2017-08-27 18:00:00 : 석사동   21362 ----------


 ---------- 2017-08-27 18:00:00 : 신북읍   21363 ----------


 ---------- 2017-08-27 19:00:00 : 효자1동   21364 ----------


 ---------- 2017-08-27 20:00:00 : 신사우동   21366 ----------


 ---------- 2017-08-27 22:00:00 : 남산면   21367 ----------


 ---------- 2017-08-28 09:00:00 : 석사동   21368 ----------


 ---------- 2017-08-28 09:00:00 : 강남동   21369 ----------


 ---------- 2017-08-28 09:00:00 : 서  면   21370 ----------


 ---------- 2017-08-28 09:00:00 : 근화동   21371 ----------


 ---------- 2017-08-28 14:00:00 : 남산면   21372 ----------


 ---------- 2017-08-28 15:00:00 : 효자1동   21373 ----------


 ---------- 2017-08-28 15:00:00 : 퇴계동   21374 ----------


 ---------- 2017-08-28 18:00:00 : 신북읍   21375 ----------


 ---------- 2017-08-29 09:00:00 : 석사동   21376 ----------


 ---------- 2017-08-29 09:00:00 : 강남동   21377 ----------


 ---------- 2017-08-29 10:00:00 : 북산면   21378 ----------


 ---------- 2017-08-29 11:00:00 : 석사동   21379 ----------


 ---------- 2017-08-29 11:00:00 : 근화동   21380 ----------


 ---------- 2017-08-29 12:00:00 : 효자1동   21381 ----------


 ---------- 2017-08-29 12:00:00 : 근화동   21383 ----------


 ---------- 2017-08-29 13:00:00 : 효자1동   21384 ----------


 ---------- 2017-08-29 13:00:00 : 후평1동   21385 ----------


 ---------- 2017-08-29 13:00:00 : 동산면   21386 ----------


 ---------- 2017-08-29 14:00:00 : 남  면   21387 ----------


 ---------- 2017-08-29 15:00:00 : 석사동   21388 ----------


 ---------- 2017-08-29 15:00:00 : 남  면   21389 ----------


 ---------- 2017-08-29 15:00:00 : 남산면   21390 ----------


 ---------- 2017-08-29 15:00:00 : 신북읍   21391 ----------


 ---------- 2017-08-29 16:00:00 : 석사동   21393 ----------


 ---------- 2017-08-29 16:00:00 : 효자1동   21394 ----------


 ---------- 2017-08-29 20:00:00 : 강남동   21397 ----------


 ---------- 2017-08-29 20:00:00 : 동  면   21399 ----------


 ---------- 2017-08-30 00:00:00 : 신사우동   21400 ----------


 ---------- 2017-08-30 08:00:00 : 후평1동   21401 ----------


 ---------- 2017-08-30 09:00:00 : 약사명동   21402 ----------


 ---------- 2017-08-30 10:00:00 : 동내면   21403 ----------


 ---------- 2017-08-30 14:00:00 : 남산면   21404 ----------


 ---------- 2017-08-30 14:00:00 : 신사우동   21405 ----------


 ---------- 2017-08-30 14:00:00 : 동  면   21406 ----------


 ---------- 2017-08-30 14:00:00 : 퇴계동   21408 ----------


 ---------- 2017-08-30 15:00:00 : 강남동   21409 ----------


 ---------- 2017-08-30 16:00:00 : 석사동   21410 ----------


 ---------- 2017-08-30 17:00:00 : 석사동   21411 ----------


 ---------- 2017-08-30 17:00:00 : 효자1동   21412 ----------


 ---------- 2017-08-30 17:00:00 : 신북읍   21413 ----------


 ---------- 2017-08-30 17:00:00 : 동산면   21414 ----------


 ---------- 2017-08-30 20:00:00 : 근화동   21415 ----------


 ---------- 2017-08-31 00:00:00 : 후평1동   21416 ----------


 ---------- 2017-08-31 01:00:00 : 소양동   21417 ----------


 ---------- 2017-08-31 05:00:00 : 후평1동   21418 ----------


 ---------- 2017-08-31 09:00:00 : 강남동   21419 ----------


 ---------- 2017-08-31 10:00:00 : 동내면   21420 ----------


 ---------- 2017-08-31 10:00:00 : 남산면   21422 ----------


 ---------- 2017-08-31 13:00:00 : 동  면   21423 ----------


 ---------- 2017-08-31 13:00:00 : 퇴계동   21424 ----------


 ---------- 2017-08-31 14:00:00 : 효자1동   21425 ----------


 ---------- 2017-08-31 16:00:00 : 동  면   21426 ----------

 ---------- 2017-08-31 17:00:00 : 소양동   21427 ----------


 ---------- 2017-08-31 18:00:00 : 신북읍   21428 ----------


 ---------- 2017-09-01 09:00:00 : 후평1동   21429 ----------


 ---------- 2017-09-01 10:00:00 : 효자1동   21430 ----------


 ---------- 2017-09-01 10:00:00 : 신사우동   21431 ----------


 ---------- 2017-09-01 11:00:00 : 서  면   21432 ----------


 ---------- 2017-09-01 12:00:00 : 신동면   21433 ----------


 ---------- 2017-09-01 13:00:00 : 강남동   21434 ----------


 ---------- 2017-09-01 13:00:00 : 동  면   21435 ----------


 ---------- 2017-09-01 15:00:00 : 후평1동   21436 ----------


 ---------- 2017-09-01 16:00:00 : 신사우동   21437 ----------


 ---------- 2017-09-01 17:00:00 : 석사동   21438 ----------


 ---------- 2017-09-01 17:00:00 : 신동면   21439 ----------


 ---------- 2017-09-01 17:00:00 : 신북읍   21440 ----------


 ---------- 2017-09-01 18:00:00 : 동내면   21441 ----------


 ---------- 2017-09-01 23:00:00 : 신북읍   21442 ----------


 ---------- 2017-09-02 08:00:00 : 신북읍   21443 ----------


 ---------- 2017-09-02 08:00:00 : 교  동   21444 ----------


 ---------- 2017-09-02 09:00:00 : 신동면   21445 ----------


 ---------- 2017-09-02 09:00:00 : 강남동   21446 ----------


 ---------- 2017-09-02 09:00:00 : 남산면   21447 ----------


 ---------- 2017-09-02 09:00:00 : 동  면   21448 ----------


 ---------- 2017-09-02 09:00:00 : 교  동   21449 ----------


 ---------- 2017-09-02 10:00:00 : 소양동   21450 ----------


 ---------- 2017-09-02 10:00:00 : 퇴계동   21451 ----------


 ---------- 2017-09-02 10:00:00 : 북산면   21452 ----------


 ---------- 2017-09-02 11:00:00 : 사북면   21453 ----------


 ---------- 2017-09-02 11:00:00 : 동내면   21454 ----------


 ---------- 2017-09-02 11:00:00 : 동  면   21455 ----------


 ---------- 2017-09-02 11:00:00 : 퇴계동   21456 ----------


 ---------- 2017-09-02 12:00:00 : 근화동   21457 ----------


 ---------- 2017-09-02 13:00:00 : 남산면   21458 ----------


 ---------- 2017-09-02 14:00:00 : 동  면   21459 ----------


 ---------- 2017-09-02 15:00:00 : 신북읍   21460 ----------


 ---------- 2017-09-02 17:00:00 : 근화동   21461 ----------


 ---------- 2017-09-02 18:00:00 : 석사동   21462 ----------


 ---------- 2017-09-02 18:00:00 : 근화동   21463 ----------


 ---------- 2017-09-02 19:00:00 : 효자1동   21464 ----------


 ---------- 2017-09-03 01:00:00 : 강남동   21465 ----------


 ---------- 2017-09-03 03:00:00 : 후평1동   21466 ----------


 ---------- 2017-09-03 09:00:00 : 남산면   21467 ----------


 ---------- 2017-09-03 09:00:00 : 신북읍   21468 ----------


 ---------- 2017-09-03 11:00:00 : 남산면   21469 ----------


 ---------- 2017-09-03 11:00:00 : 신사우동   21470 ----------


 ---------- 2017-09-03 13:00:00 : 신북읍   21471 ----------


 ---------- 2017-09-03 14:00:00 : 사북면   21472 ----------


 ---------- 2017-09-03 15:00:00 : 신동면   21473 ----------


 ---------- 2017-09-03 15:00:00 : 강남동   21474 ----------


 ---------- 2017-09-03 15:00:00 : 남  면   21475 ----------


 ---------- 2017-09-03 15:00:00 : 동산면   21476 ----------


 ---------- 2017-09-03 16:00:00 : 신동면   21477 ----------


 ---------- 2017-09-03 16:00:00 : 강남동   21478 ----------


 ---------- 2017-09-03 17:00:00 : 강남동   21479 ----------


 ---------- 2017-09-03 17:00:00 : 퇴계동   21480 ----------


 ---------- 2017-09-04 08:00:00 : 사북면   21481 ----------


 ---------- 2017-09-04 08:00:00 : 동내면   21482 ----------


 ---------- 2017-09-04 08:00:00 : 효자1동   21483 ----------


 ---------- 2017-09-04 09:00:00 : 효자1동   21484 ----------


 ---------- 2017-09-04 09:00:00 : 신북읍   21485 ----------


 ---------- 2017-09-04 09:00:00 : 약사명동   21486 ----------


 ---------- 2017-09-04 09:00:00 : 후평1동   21487 ----------


 ---------- 2017-09-04 10:00:00 : 신사우동   21488 ----------


 ---------- 2017-09-04 10:00:00 : 후평1동   21489 ----------


 ---------- 2017-09-04 11:00:00 : 동내면   21491 ----------


 ---------- 2017-09-04 12:00:00 : 신북읍   21492 ----------


 ---------- 2017-09-04 13:00:00 : 동내면   21493 ----------


 ---------- 2017-09-04 15:00:00 : 신사우동   21494 ----------


 ---------- 2017-09-04 15:00:00 : 약사명동   21495 ----------


 ---------- 2017-09-04 16:00:00 : 동내면   21496 ----------


 ---------- 2017-09-04 16:00:00 : 소양동   21497 ----------


 ---------- 2017-09-04 19:00:00 : 동  면   21498 ----------


 ---------- 2017-09-04 21:00:00 : 강남동   21499 ----------


 ---------- 2017-09-04 23:00:00 : 소양동   21500 ----------


 ---------- 2017-09-05 00:00:00 : 소양동   21501 ----------


 ---------- 2017-09-05 08:00:00 : 효자1동   21503 ----------


 ---------- 2017-09-05 09:00:00 : 석사동   21504 ----------


 ---------- 2017-09-05 09:00:00 : 서  면   21505 ----------


 ---------- 2017-09-05 09:00:00 : 북산면   21506 ----------


 ---------- 2017-09-05 10:00:00 : 신사우동   21507 ----------


 ---------- 2017-09-05 11:00:00 : 동산면   21509 ----------


 ---------- 2017-09-05 12:00:00 : 동내면   21510 ----------


 ---------- 2017-09-05 12:00:00 : 동  면   21511 ----------


 ---------- 2017-09-05 12:00:00 : 후평1동   21512 ----------


 ---------- 2017-09-05 13:00:00 : 신북읍   21514 ----------


 ---------- 2017-09-05 13:00:00 : 동  면   21515 ----------


 ---------- 2017-09-05 13:00:00 : 후평1동   21516 ----------


 ---------- 2017-09-05 14:00:00 : 서  면   21517 ----------


 ---------- 2017-09-05 14:00:00 : 남산면   21518 ----------


 ---------- 2017-09-05 15:00:00 : 동  면   21519 ----------


 ---------- 2017-09-05 16:00:00 : 신동면   21520 ----------


 ---------- 2017-09-05 16:00:00 : 남산면   21521 ----------


 ---------- 2017-09-05 17:00:00 : 강남동   21522 ----------


 ---------- 2017-09-05 17:00:00 : 후평1동   21523 ----------


 ---------- 2017-09-05 18:00:00 : 석사동   21524 ----------


 ---------- 2017-09-05 19:00:00 : 남산면   21525 ----------


 ---------- 2017-09-05 20:00:00 : 퇴계동   21526 ----------


 ---------- 2017-09-06 09:00:00 : 신북읍   21527 ----------


 ---------- 2017-09-06 10:00:00 : 신동면   21528 ----------


 ---------- 2017-09-06 10:00:00 : 강남동   21529 ----------


 ---------- 2017-09-06 10:00:00 : 동내면   21530 ----------


 ---------- 2017-09-06 10:00:00 : 북산면   21533 ----------


 ---------- 2017-09-06 10:00:00 : 동산면   21535 ----------


 ---------- 2017-09-06 11:00:00 : 남산면   21536 ----------


 ---------- 2017-09-06 12:00:00 : 퇴계동   21537 ----------


 ---------- 2017-09-06 13:00:00 : 서  면   21538 ----------


 ---------- 2017-09-06 13:00:00 : 사북면   21539 ----------


 ---------- 2017-09-06 13:00:00 : 북산면   21540 ----------


 ---------- 2017-09-06 13:00:00 : 동산면   21541 ----------


 ---------- 2017-09-06 14:00:00 : 동  면   21543 ----------


 ---------- 2017-09-06 14:00:00 : 북산면   21544 ----------


 ---------- 2017-09-06 15:00:00 : 신동면   21545 ----------


 ---------- 2017-09-06 16:00:00 : 신북읍   21546 ----------


 ---------- 2017-09-06 19:00:00 : 퇴계동   21549 ----------


 ---------- 2017-09-07 09:00:00 : 동내면   21550 ----------


 ---------- 2017-09-07 09:00:00 : 동  면   21551 ----------


 ---------- 2017-09-07 10:00:00 : 석사동   21552 ----------


 ---------- 2017-09-07 11:00:00 : 강남동   21553 ----------


 ---------- 2017-09-07 11:00:00 : 서  면   21554 ----------


 ---------- 2017-09-07 12:00:00 : 신북읍   21555 ----------


 ---------- 2017-09-07 13:00:00 : 석사동   21556 ----------


 ---------- 2017-09-07 13:00:00 : 강남동   21557 ----------


 ---------- 2017-09-07 13:00:00 : 효자1동   21559 ----------


 ---------- 2017-09-07 14:00:00 : 후평1동   21560 ----------


 ---------- 2017-09-07 15:00:00 : 소양동   21561 ----------


 ---------- 2017-09-07 16:00:00 : 근화동   21562 ----------


 ---------- 2017-09-07 16:00:00 : 퇴계동   21563 ----------


 ---------- 2017-09-07 18:00:00 : 효자1동   21564 ----------


 ---------- 2017-09-07 19:00:00 : 강남동   21565 ----------


 ---------- 2017-09-08 03:00:00 : 후평1동   21566 ----------


 ---------- 2017-09-08 04:00:00 : 근화동   21567 ----------


 ---------- 2017-09-08 07:00:00 : 퇴계동   21568 ----------


 ---------- 2017-09-08 08:00:00 : 효자1동   21569 ----------


 ---------- 2017-09-08 09:00:00 : 남산면   21570 ----------


 ---------- 2017-09-08 09:00:00 : 신북읍   21571 ----------


 ---------- 2017-09-08 09:00:00 : 소양동   21572 ----------


 ---------- 2017-09-08 09:00:00 : 동  면   21573 ----------

 ---------- 2017-09-08 10:00:00 : 퇴계동   21574 ----------


 ---------- 2017-09-08 11:00:00 : 신사우동   21575 ----------


 ---------- 2017-09-08 11:00:00 : 동  면   21576 ----------


 ---------- 2017-09-08 12:00:00 : 석사동   21577 ----------


 ---------- 2017-09-08 13:00:00 : 퇴계동   21578 ----------


 ---------- 2017-09-08 14:00:00 : 동내면   21579 ----------


 ---------- 2017-09-08 16:00:00 : 강남동   21580 ----------


 ---------- 2017-09-08 17:00:00 : 석사동   21581 ----------


 ---------- 2017-09-08 17:00:00 : 퇴계동   21582 ----------


 ---------- 2017-09-08 18:00:00 : 남산면   21583 ----------


 ---------- 2017-09-08 19:00:00 : 신사우동   21584 ----------


 ---------- 2017-09-08 21:00:00 : 사북면   21585 ----------


 ---------- 2017-09-08 23:00:00 : 근화동   21586 ----------


 ---------- 2017-09-09 09:00:00 : 동  면   21587 ----------


 ---------- 2017-09-09 09:00:00 : 동산면   21588 ----------


 ---------- 2017-09-09 10:00:00 : 석사동   21589 ----------


 ---------- 2017-09-09 12:00:00 : 서  면   21590 ----------


 ---------- 2017-09-09 12:00:00 : 동내면   21591 ----------


 ---------- 2017-09-09 13:00:00 : 신북읍   21592 ----------


 ---------- 2017-09-09 14:00:00 : 소양동   21593 ----------


 ---------- 2017-09-09 15:00:00 : 남  면   21595 ----------


 ---------- 2017-09-09 15:00:00 : 후평1동   21596 ----------


 ---------- 2017-09-09 15:00:00 : 북산면   21597 ----------


 ---------- 2017-09-10 09:00:00 : 서  면   21598 ----------


 ---------- 2017-09-10 10:00:00 : 신동면   21600 ----------


 ---------- 2017-09-10 11:00:00 : 북산면   21602 ----------


 ---------- 2017-09-10 12:00:00 : 근화동   21603 ----------


 ---------- 2017-09-10 12:00:00 : 북산면   21604 ----------


 ---------- 2017-09-10 12:00:00 : 동산면   21606 ----------


 ---------- 2017-09-10 14:00:00 : 동내면   21607 ----------


 ---------- 2017-09-10 15:00:00 : 동  면   21608 ----------


 ---------- 2017-09-10 16:00:00 : 동내면   21609 ----------


 ---------- 2017-09-10 16:00:00 : 신사우동   21611 ----------


 ---------- 2017-09-10 17:00:00 : 남산면   21612 ----------


 ---------- 2017-09-10 22:00:00 : 신사우동   21613 ----------


 ---------- 2017-09-11 01:00:00 : 신사우동   21615 ----------


 ---------- 2017-09-11 03:00:00 : 퇴계동   21616 ----------


 ---------- 2017-09-11 10:00:00 : 강남동   21617 ----------


 ---------- 2017-09-11 10:00:00 : 동내면   21618 ----------


 ---------- 2017-09-11 11:00:00 : 서  면   21619 ----------


 ---------- 2017-09-11 13:00:00 : 퇴계동   21620 ----------


 ---------- 2017-09-11 14:00:00 : 효자1동   21621 ----------


 ---------- 2017-09-11 14:00:00 : 신사우동   21622 ----------


 ---------- 2017-09-11 14:00:00 : 동  면   21625 ----------


 ---------- 2017-09-11 15:00:00 : 동  면   21626 ----------


 ---------- 2017-09-11 15:00:00 : 퇴계동   21627 ----------


 ---------- 2017-09-11 16:00:00 : 북산면   21628 ----------


 ---------- 2017-09-12 01:00:00 : 후평1동   21629 ----------


 ---------- 2017-09-12 02:00:00 : 동  면   21630 ----------


 ---------- 2017-09-12 10:00:00 : 동  면   21631 ----------


 ---------- 2017-09-12 11:00:00 : 후평1동   21632 ----------


 ---------- 2017-09-12 13:00:00 : 동산면   21633 ----------


 ---------- 2017-09-12 14:00:00 : 남  면   21635 ----------


 ---------- 2017-09-12 15:00:00 : 신사우동   21636 ----------


 ---------- 2017-09-12 15:00:00 : 동  면   21637 ----------


 ---------- 2017-09-12 16:00:00 : 동내면   21638 ----------


 ---------- 2017-09-12 18:00:00 : 강남동   21639 ----------


 ---------- 2017-09-12 19:00:00 : 퇴계동   21640 ----------


 ---------- 2017-09-12 20:00:00 : 사북면   21643 ----------


 ---------- 2017-09-13 00:00:00 : 퇴계동   21644 ----------


 ---------- 2017-09-13 07:00:00 : 사북면   21646 ----------


 ---------- 2017-09-13 07:00:00 : 효자1동   21648 ----------


 ---------- 2017-09-13 08:00:00 : 효자1동   21650 ----------


 ---------- 2017-09-13 08:00:00 : 남산면   21651 ----------


 ---------- 2017-09-13 08:00:00 : 신사우동   21652 ----------


 ---------- 2017-09-13 13:00:00 : 신동면   21653 ----------


 ---------- 2017-09-13 14:00:00 : 남산면   21654 ----------


 ---------- 2017-09-13 15:00:00 : 남산면   21656 ----------


 ---------- 2017-09-13 15:00:00 : 신북읍   21657 ----------


 ---------- 2017-09-13 18:00:00 : 동내면   21658 ----------


 ---------- 2017-09-14 04:00:00 : 후평1동   21659 ----------


 ---------- 2017-09-14 09:00:00 : 신사우동   21660 ----------


 ---------- 2017-09-14 10:00:00 : 신동면   21661 ----------


 ---------- 2017-09-14 10:00:00 : 동  면   21662 ----------


 ---------- 2017-09-14 13:00:00 : 석사동   21663 ----------


 ---------- 2017-09-14 13:00:00 : 효자1동   21664 ----------


 ---------- 2017-09-14 13:00:00 : 교  동   21665 ----------


 ---------- 2017-09-14 15:00:00 : 동  면   21666 ----------


 ---------- 2017-09-14 18:00:00 : 교  동   21668 ----------


 ---------- 2017-09-14 19:00:00 : 효자1동   21669 ----------


 ---------- 2017-09-14 19:00:00 : 신사우동   21670 ----------


 ---------- 2017-09-14 20:00:00 : 신사우동   21671 ----------


 ---------- 2017-09-14 20:00:00 : 약사명동   21672 ----------


 ---------- 2017-09-14 21:00:00 : 근화동   21673 ----------


 ---------- 2017-09-14 22:00:00 : 후평1동   21674 ----------


 ---------- 2017-09-15 00:00:00 : 석사동   21675 ----------


 ---------- 2017-09-15 01:00:00 : 후평1동   21676 ----------


 ---------- 2017-09-15 02:00:00 : 후평1동   21677 ----------


 ---------- 2017-09-15 09:00:00 : 신북읍   21678 ----------


 ---------- 2017-09-15 10:00:00 : 석사동   21679 ----------


 ---------- 2017-09-15 10:00:00 : 남산면   21680 ----------


 ---------- 2017-09-15 10:00:00 : 동  면   21681 ----------


 ---------- 2017-09-15 12:00:00 : 강남동   21682 ----------


 ---------- 2017-09-15 13:00:00 : 동내면   21683 ----------


 ---------- 2017-09-15 14:00:00 : 서  면   21684 ----------


 ---------- 2017-09-15 14:00:00 : 퇴계동   21685 ----------


 ---------- 2017-09-15 14:00:00 : 조운동   21686 ----------


 ---------- 2017-09-15 15:00:00 : 북산면   21688 ----------


 ---------- 2017-09-15 16:00:00 : 사북면   21689 ----------


 ---------- 2017-09-15 19:00:00 : 북산면   21690 ----------


 ---------- 2017-09-15 23:00:00 : 강남동   21691 ----------


 ---------- 2017-09-16 01:00:00 : 효자1동   21692 ----------


 ---------- 2017-09-16 08:00:00 : 신북읍   21693 ----------


 ---------- 2017-09-16 09:00:00 : 신동면   21694 ----------


 ---------- 2017-09-16 10:00:00 : 효자1동   21695 ----------


 ---------- 2017-09-16 10:00:00 : 동산면   21696 ----------


 ---------- 2017-09-16 11:00:00 : 남  면   21697 ----------


 ---------- 2017-09-16 13:00:00 : 사북면   21698 ----------


 ---------- 2017-09-16 15:00:00 : 서  면   21699 ----------


 ---------- 2017-09-16 15:00:00 : 조운동   21700 ----------


 ---------- 2017-09-16 16:00:00 : 동내면   21701 ----------


 ---------- 2017-09-16 17:00:00 : 남산면   21703 ----------


 ---------- 2017-09-16 18:00:00 : 석사동   21704 ----------


 ---------- 2017-09-16 18:00:00 : 약사명동   21705 ----------


 ---------- 2017-09-16 19:00:00 : 신동면   21706 ----------


 ---------- 2017-09-16 20:00:00 : 석사동   21708 ----------


 ---------- 2017-09-16 21:00:00 : 강남동   21709 ----------


 ---------- 2017-09-16 22:00:00 : 퇴계동   21710 ----------


 ---------- 2017-09-17 05:00:00 : 석사동   21711 ----------


 ---------- 2017-09-17 07:00:00 : 강남동   21712 ----------


 ---------- 2017-09-17 07:00:00 : 동  면   21714 ----------


 ---------- 2017-09-17 10:00:00 : 남  면   21715 ----------


 ---------- 2017-09-17 10:00:00 : 동산면   21716 ----------


 ---------- 2017-09-17 11:00:00 : 서  면   21718 ----------


 ---------- 2017-09-17 12:00:00 : 동  면   21719 ----------


 ---------- 2017-09-17 12:00:00 : 북산면   21720 ----------


 ---------- 2017-09-17 13:00:00 : 석사동   21721 ----------


 ---------- 2017-09-17 13:00:00 : 강남동   21722 ----------


 ---------- 2017-09-17 14:00:00 : 신북읍   21723 ----------


 ---------- 2017-09-17 14:00:00 : 후평1동   21724 ----------


 ---------- 2017-09-17 14:00:00 : 북산면   21725 ----------


 ---------- 2017-09-17 17:00:00 : 남  면   21726 ----------


 ---------- 2017-09-17 18:00:00 : 남  면   21728 ----------


 ---------- 2017-09-17 18:00:00 : 남산면   21729 ----------


 ---------- 2017-09-17 18:00:00 : 북산면   21730 ----------


 ---------- 2017-09-18 01:00:00 : 동내면   21731 ----------

 ---------- 2017-09-18 08:00:00 : 근화동   21732 ----------


 ---------- 2017-09-18 08:00:00 : 신북읍   21733 ----------


 ---------- 2017-09-18 09:00:00 : 강남동   21734 ----------


 ---------- 2017-09-18 09:00:00 : 신사우동   21735 ----------


 ---------- 2017-09-18 09:00:00 : 동산면   21736 ----------


 ---------- 2017-09-18 10:00:00 : 후평1동   21737 ----------


 ---------- 2017-09-18 11:00:00 : 남  면   21739 ----------


 ---------- 2017-09-18 11:00:00 : 퇴계동   21740 ----------


 ---------- 2017-09-18 12:00:00 : 남산면   21741 ----------


 ---------- 2017-09-18 13:00:00 : 강남동   21743 ----------


 ---------- 2017-09-18 13:00:00 : 서  면   21744 ----------


 ---------- 2017-09-18 13:00:00 : 약사명동   21745 ----------


 ---------- 2017-09-18 13:00:00 : 동산면   21746 ----------


 ---------- 2017-09-18 14:00:00 : 동  면   21748 ----------


 ---------- 2017-09-18 14:00:00 : 퇴계동   21749 ----------


 ---------- 2017-09-18 15:00:00 : 서  면   21750 ----------


 ---------- 2017-09-18 16:00:00 : 효자1동   21751 ----------


 ---------- 2017-09-18 17:00:00 : 신북읍   21752 ----------


 ---------- 2017-09-18 18:00:00 : 효자1동   21753 ----------


 ---------- 2017-09-18 20:00:00 : 서  면   21754 ----------


 ---------- 2017-09-18 20:00:00 : 후평1동   21755 ----------


 ---------- 2017-09-19 04:00:00 : 퇴계동   21756 ----------


 ---------- 2017-09-19 09:00:00 : 신북읍   21757 ----------


 ---------- 2017-09-19 09:00:00 : 후평1동   21758 ----------


 ---------- 2017-09-19 10:00:00 : 동내면   21759 ----------


 ---------- 2017-09-19 10:00:00 : 동  면   21762 ----------


 ---------- 2017-09-19 12:00:00 : 동내면   21763 ----------


 ---------- 2017-09-19 13:00:00 : 효자1동   21765 ----------


 ---------- 2017-09-19 14:00:00 : 석사동   21766 ----------


 ---------- 2017-09-19 14:00:00 : 사북면   21767 ----------


 ---------- 2017-09-19 17:00:00 : 강남동   21768 ----------


 ---------- 2017-09-19 17:00:00 : 동내면   21769 ----------


 ---------- 2017-09-20 06:00:00 : 신동면   21770 ----------


 ---------- 2017-09-20 08:00:00 : 석사동   21771 ----------


 ---------- 2017-09-20 11:00:00 : 남산면   21772 ----------


 ---------- 2017-09-20 14:00:00 : 소양동   21773 ----------


 ---------- 2017-09-20 16:00:00 : 효자1동   21774 ----------


 ---------- 2017-09-20 18:00:00 : 신사우동   21775 ----------


 ---------- 2017-09-20 19:00:00 : 동내면   21777 ----------


 ---------- 2017-09-20 19:00:00 : 교  동   21779 ----------


 ---------- 2017-09-20 21:00:00 : 신사우동   21780 ----------


 ---------- 2017-09-21 06:00:00 : 동  면   21781 ----------


 ---------- 2017-09-21 09:00:00 : 서  면   21782 ----------


 ---------- 2017-09-21 11:00:00 : 석사동   21783 ----------


 ---------- 2017-09-21 11:00:00 : 동산면   21785 ----------


 ---------- 2017-09-21 12:00:00 : 신동면   21786 ----------


 ---------- 2017-09-21 12:00:00 : 신사우동   21787 ----------


 ---------- 2017-09-21 12:00:00 : 북산면   21788 ----------


 ---------- 2017-09-21 14:00:00 : 퇴계동   21789 ----------


 ---------- 2017-09-21 17:00:00 : 강남동   21790 ----------


 ---------- 2017-09-21 20:00:00 : 동  면   21791 ----------


 ---------- 2017-09-22 01:00:00 : 효자1동   21792 ----------


 ---------- 2017-09-22 03:00:00 : 석사동   21793 ----------


 ---------- 2017-09-22 08:00:00 : 사북면   21794 ----------


 ---------- 2017-09-22 10:00:00 : 서  면   21796 ----------


 ---------- 2017-09-22 10:00:00 : 동내면   21797 ----------


 ---------- 2017-09-22 12:00:00 : 북산면   21798 ----------


 ---------- 2017-09-22 12:00:00 : 동산면   21800 ----------


 ---------- 2017-09-22 13:00:00 : 사북면   21801 ----------


 ---------- 2017-09-22 13:00:00 : 동내면   21802 ----------


 ---------- 2017-09-22 13:00:00 : 남산면   21803 ----------


 ---------- 2017-09-22 13:00:00 : 신사우동   21804 ----------


 ---------- 2017-09-22 14:00:00 : 동내면   21805 ----------


 ---------- 2017-09-22 14:00:00 : 동산면   21807 ----------


 ---------- 2017-09-22 16:00:00 : 동  면   21808 ----------


 ---------- 2017-09-22 22:00:00 : 효자1동   21809 ----------


 ---------- 2017-09-23 00:00:00 : 효자1동   21810 ----------


 ---------- 2017-09-23 14:00:00 : 석사동   21811 ----------


 ---------- 2017-09-23 14:00:00 : 동  면   21812 ----------


 ---------- 2017-09-23 15:00:00 : 석사동   21813 ----------


 ---------- 2017-09-23 17:00:00 : 동내면   21814 ----------


 ---------- 2017-09-23 17:00:00 : 동산면   21815 ----------


 ---------- 2017-09-23 18:00:00 : 후평1동   21816 ----------


 ---------- 2017-09-23 20:00:00 : 남  면   21817 ----------


 ---------- 2017-09-24 06:00:00 : 강남동   21818 ----------


 ---------- 2017-09-24 08:00:00 : 효자1동   21819 ----------


 ---------- 2017-09-24 08:00:00 : 신북읍   21820 ----------


 ---------- 2017-09-24 09:00:00 : 신동면   21821 ----------


 ---------- 2017-09-24 09:00:00 : 남산면   21822 ----------


 ---------- 2017-09-24 09:00:00 : 신북읍   21823 ----------


 ---------- 2017-09-24 13:00:00 : 북산면   21824 ----------


 ---------- 2017-09-24 15:00:00 : 남산면   21825 ----------


 ---------- 2017-09-24 15:00:00 : 신북읍   21826 ----------


 ---------- 2017-09-24 16:00:00 : 석사동   21827 ----------


 ---------- 2017-09-24 17:00:00 : 교  동   21828 ----------


 ---------- 2017-09-24 18:00:00 : 신동면   21829 ----------


 ---------- 2017-09-24 18:00:00 : 남산면   21831 ----------


 ---------- 2017-09-24 20:00:00 : 효자1동   21832 ----------


 ---------- 2017-09-25 09:00:00 : 동내면   21833 ----------


 ---------- 2017-09-25 10:00:00 : 효자1동   21834 ----------


 ---------- 2017-09-25 10:00:00 : 신북읍   21835 ----------


 ---------- 2017-09-25 10:00:00 : 소양동   21836 ----------


 ---------- 2017-09-25 11:00:00 : 강남동   21837 ----------


 ---------- 2017-09-25 14:00:00 : 석사동   21838 ----------


 ---------- 2017-09-25 14:00:00 : 퇴계동   21839 ----------


 ---------- 2017-09-25 15:00:00 : 후평1동   21840 ----------


 ---------- 2017-09-25 16:00:00 : 소양동   21841 ----------


 ---------- 2017-09-25 16:00:00 : 조운동   21842 ----------


 ---------- 2017-09-25 17:00:00 : 근화동   21843 ----------


 ---------- 2017-09-25 19:00:00 : 동내면   21845 ----------


 ---------- 2017-09-25 22:00:00 : 후평1동   21846 ----------


 ---------- 2017-09-26 01:00:00 : 동  면   21847 ----------


 ---------- 2017-09-26 02:00:00 : 동  면   21848 ----------


 ---------- 2017-09-26 10:00:00 : 강남동   21849 ----------


 ---------- 2017-09-26 10:00:00 : 남산면   21850 ----------


 ---------- 2017-09-26 13:00:00 : 신사우동   21851 ----------


 ---------- 2017-09-26 13:00:00 : 동  면   21852 ----------


 ---------- 2017-09-26 14:00:00 : 효자1동   21853 ----------


 ---------- 2017-09-26 15:00:00 : 신북읍   21854 ----------


 ---------- 2017-09-26 16:00:00 : 근화동   21855 ----------


 ---------- 2017-09-27 10:00:00 : 신사우동   21856 ----------


 ---------- 2017-09-27 10:00:00 : 동  면   21857 ----------


 ---------- 2017-09-27 11:00:00 : 강남동   21858 ----------


 ---------- 2017-09-27 12:00:00 : 강남동   21859 ----------


 ---------- 2017-09-27 13:00:00 : 신사우동   21860 ----------


 ---------- 2017-09-27 15:00:00 : 동  면   21861 ----------


 ---------- 2017-09-27 23:00:00 : 서  면   21862 ----------


 ---------- 2017-09-28 04:00:00 : 교  동   21863 ----------


 ---------- 2017-09-28 07:00:00 : 신북읍   21864 ----------


 ---------- 2017-09-28 10:00:00 : 강남동   21865 ----------


 ---------- 2017-09-28 14:00:00 : 신동면   21866 ----------


 ---------- 2017-09-28 14:00:00 : 동  면   21867 ----------


 ---------- 2017-09-28 15:00:00 : 동  면   21869 ----------


 ---------- 2017-09-28 16:00:00 : 강남동   21870 ----------


 ---------- 2017-09-28 16:00:00 : 퇴계동   21871 ----------


 ---------- 2017-09-28 17:00:00 : 서  면   21872 ----------


 ---------- 2017-09-28 18:00:00 : 동  면   21874 ----------


 ---------- 2017-09-28 19:00:00 : 남  면   21876 ----------


 ---------- 2017-09-28 21:00:00 : 효자1동   21878 ----------


 ---------- 2017-09-28 22:00:00 : 동내면   21880 ----------


 ---------- 2017-09-29 06:00:00 : 근화동   21881 ----------


 ---------- 2017-09-29 09:00:00 : 동내면   21882 ----------


 ---------- 2017-09-29 09:00:00 : 효자1동   21883 ----------


 ---------- 2017-09-29 09:00:00 : 후평1동   21884 ----------


 ---------- 2017-09-29 09:00:00 : 퇴계동   21885 ----------


 ---------- 2017-09-29 09:00:00 : 교  동   21886 ----------

 ---------- 2017-09-29 12:00:00 : 동내면   21887 ----------


 ---------- 2017-09-30 01:00:00 : 소양동   21890 ----------


 ---------- 2017-09-30 08:00:00 : 동  면   21891 ----------


 ---------- 2017-09-30 10:00:00 : 신동면   21892 ----------


 ---------- 2017-09-30 12:00:00 : 남  면   21893 ----------


 ---------- 2017-09-30 13:00:00 : 동내면   21894 ----------


 ---------- 2017-09-30 14:00:00 : 강남동   21895 ----------


 ---------- 2017-09-30 15:00:00 : 남산면   21896 ----------


 ---------- 2017-09-30 15:00:00 : 동  면   21897 ----------


 ---------- 2017-09-30 17:00:00 : 강남동   21898 ----------


 ---------- 2017-09-30 22:00:00 : 석사동   21900 ----------


 ---------- 2017-10-01 02:00:00 : 신사우동   21901 ----------


 ---------- 2017-10-01 04:00:00 : 동내면   21904 ----------


 ---------- 2017-10-01 07:00:00 : 강남동   21905 ----------


 ---------- 2017-10-01 08:00:00 : 강남동   21906 ----------


 ---------- 2017-10-01 08:00:00 : 효자1동   21907 ----------


 ---------- 2017-10-01 09:00:00 : 남산면   21908 ----------


 ---------- 2017-10-01 11:00:00 : 사북면   21909 ----------


 ---------- 2017-10-01 11:00:00 : 신사우동   21910 ----------


 ---------- 2017-10-01 12:00:00 : 퇴계동   21911 ----------


 ---------- 2017-10-01 13:00:00 : 신사우동   21912 ----------


 ---------- 2017-10-01 15:00:00 : 서  면   21913 ----------


 ---------- 2017-10-01 16:00:00 : 동산면   21915 ----------


 ---------- 2017-10-01 21:00:00 : 석사동   21916 ----------


 ---------- 2017-10-02 03:00:00 : 후평1동   21917 ----------


 ---------- 2017-10-02 06:00:00 : 서  면   21919 ----------


 ---------- 2017-10-02 09:00:00 : 근화동   21920 ----------


 ---------- 2017-10-02 09:00:00 : 신북읍   21921 ----------


 ---------- 2017-10-02 09:00:00 : 후평1동   21922 ----------


 ---------- 2017-10-02 10:00:00 : 신북읍   21923 ----------


 ---------- 2017-10-02 14:00:00 : 서  면   21924 ----------


 ---------- 2017-10-02 14:00:00 : 남산면   21926 ----------


 ---------- 2017-10-02 16:00:00 : 강남동   21927 ----------


 ---------- 2017-10-02 16:00:00 : 동  면   21928 ----------


 ---------- 2017-10-02 16:00:00 : 조운동   21929 ----------


 ---------- 2017-10-02 17:00:00 : 남산면   21931 ----------


 ---------- 2017-10-02 18:00:00 : 신사우동   21932 ----------


 ---------- 2017-10-02 18:00:00 : 후평1동   21933 ----------


 ---------- 2017-10-03 07:00:00 : 신사우동   21934 ----------


 ---------- 2017-10-03 08:00:00 : 동  면   21935 ----------


 ---------- 2017-10-03 10:00:00 : 강남동   21936 ----------


 ---------- 2017-10-03 11:00:00 : 사북면   21937 ----------


 ---------- 2017-10-03 22:00:00 : 신북읍   21939 ----------


 ---------- 2017-10-04 01:00:00 : 퇴계동   21940 ----------


 ---------- 2017-10-04 06:00:00 : 퇴계동   21941 ----------


 ---------- 2017-10-04 07:00:00 : 후평1동   21942 ----------


 ---------- 2017-10-04 09:00:00 : 신동면   21943 ----------


 ---------- 2017-10-04 10:00:00 : 남산면   21945 ----------


 ---------- 2017-10-04 11:00:00 : 후평1동   21946 ----------


 ---------- 2017-10-04 16:00:00 : 신사우동   21948 ----------


 ---------- 2017-10-04 17:00:00 : 남  면   21949 ----------


 ---------- 2017-10-04 18:00:00 : 동내면   21950 ----------


 ---------- 2017-10-05 01:00:00 : 동  면   21951 ----------


 ---------- 2017-10-05 08:00:00 : 남산면   21952 ----------


 ---------- 2017-10-05 10:00:00 : 신동면   21955 ----------


 ---------- 2017-10-05 10:00:00 : 동  면   21956 ----------


 ---------- 2017-10-05 11:00:00 : 효자1동   21957 ----------


 ---------- 2017-10-05 11:00:00 : 동산면   21958 ----------


 ---------- 2017-10-05 12:00:00 : 남산면   21959 ----------


 ---------- 2017-10-06 10:00:00 : 동  면   21960 ----------


 ---------- 2017-10-06 12:00:00 : 동  면   21961 ----------


 ---------- 2017-10-06 13:00:00 : 남산면   21962 ----------


 ---------- 2017-10-06 14:00:00 : 석사동   21963 ----------


 ---------- 2017-10-06 20:00:00 : 효자1동   21964 ----------


 ---------- 2017-10-07 11:00:00 : 강남동   21965 ----------


 ---------- 2017-10-07 11:00:00 : 신사우동   21966 ----------


 ---------- 2017-10-07 12:00:00 : 서  면   21967 ----------


 ---------- 2017-10-07 12:00:00 : 남산면   21969 ----------


 ---------- 2017-10-07 12:00:00 : 동산면   21970 ----------


 ---------- 2017-10-07 13:00:00 : 서  면   21971 ----------


 ---------- 2017-10-07 13:00:00 : 남산면   21972 ----------


 ---------- 2017-10-07 14:00:00 : 사북면   21973 ----------


 ---------- 2017-10-07 14:00:00 : 남산면   21976 ----------


 ---------- 2017-10-07 14:00:00 : 북산면   21977 ----------


 ---------- 2017-10-07 15:00:00 : 남산면   21978 ----------


 ---------- 2017-10-07 16:00:00 : 서  면   21979 ----------


 ---------- 2017-10-07 18:00:00 : 후평1동   21980 ----------


 ---------- 2017-10-08 09:00:00 : 석사동   21981 ----------


 ---------- 2017-10-08 12:00:00 : 강남동   21982 ----------


 ---------- 2017-10-08 12:00:00 : 효자1동   21983 ----------


 ---------- 2017-10-08 12:00:00 : 남산면   21984 ----------


 ---------- 2017-10-08 15:00:00 : 남산면   21985 ----------


 ---------- 2017-10-08 17:00:00 : 석사동   21986 ----------


 ---------- 2017-10-08 18:00:00 : 신동면   21987 ----------


 ---------- 2017-10-09 08:00:00 : 교  동   21988 ----------


 ---------- 2017-10-09 09:00:00 : 서  면   21991 ----------


 ---------- 2017-10-09 10:00:00 : 동산면   21992 ----------


 ---------- 2017-10-09 12:00:00 : 신동면   21993 ----------


 ---------- 2017-10-09 12:00:00 : 퇴계동   21994 ----------


 ---------- 2017-10-09 13:00:00 : 퇴계동   21995 ----------


 ---------- 2017-10-09 14:00:00 : 신북읍   21996 ----------


 ---------- 2017-10-09 16:00:00 : 강남동   21997 ----------


 ---------- 2017-10-09 21:00:00 : 동  면   21999 ----------


 ---------- 2017-10-10 09:00:00 : 신사우동   22000 ----------


 ---------- 2017-10-10 13:00:00 : 효자1동   22001 ----------


 ---------- 2017-10-10 13:00:00 : 신북읍   22002 ----------


 ---------- 2017-10-10 13:00:00 : 약사명동   22003 ----------


 ---------- 2017-10-10 14:00:00 : 동  면   22004 ----------


 ---------- 2017-10-10 14:00:00 : 후평1동   22005 ----------


 ---------- 2017-10-10 18:00:00 : 동내면   22006 ----------


 ---------- 2017-10-11 07:00:00 : 북산면   22007 ----------


 ---------- 2017-10-11 14:00:00 : 후평1동   22008 ----------


 ---------- 2017-10-11 15:00:00 : 퇴계동   22009 ----------


 ---------- 2017-10-11 19:00:00 : 석사동   22010 ----------


 ---------- 2017-10-12 09:00:00 : 신사우동   22011 ----------


 ---------- 2017-10-12 10:00:00 : 효자1동   22012 ----------


 ---------- 2017-10-12 13:00:00 : 신북읍   22015 ----------


 ---------- 2017-10-12 16:00:00 : 후평1동   22016 ----------


 ---------- 2017-10-13 03:00:00 : 강남동   22017 ----------


 ---------- 2017-10-13 10:00:00 : 동  면   22018 ----------


 ---------- 2017-10-13 11:00:00 : 서  면   22019 ----------


 ---------- 2017-10-13 13:00:00 : 효자1동   22020 ----------


 ---------- 2017-10-13 15:00:00 : 후평1동   22021 ----------


 ---------- 2017-10-13 16:00:00 : 근화동   22022 ----------


 ---------- 2017-10-13 23:00:00 : 남산면   22023 ----------


 ---------- 2017-10-14 01:00:00 : 퇴계동   22024 ----------


 ---------- 2017-10-14 09:00:00 : 신북읍   22025 ----------


 ---------- 2017-10-14 11:00:00 : 효자1동   22026 ----------


 ---------- 2017-10-14 12:00:00 : 석사동   22027 ----------


 ---------- 2017-10-14 12:00:00 : 동산면   22028 ----------


 ---------- 2017-10-14 16:00:00 : 신사우동   22029 ----------


 ---------- 2017-10-14 23:00:00 : 신사우동   22030 ----------


 ---------- 2017-10-15 11:00:00 : 신동면   22031 ----------


 ---------- 2017-10-15 11:00:00 : 동  면   22032 ----------


 ---------- 2017-10-15 13:00:00 : 남산면   22033 ----------


 ---------- 2017-10-15 13:00:00 : 동  면   22034 ----------


 ---------- 2017-10-15 14:00:00 : 남산면   22035 ----------


 ---------- 2017-10-15 15:00:00 : 석사동   22036 ----------


 ---------- 2017-10-15 17:00:00 : 후평1동   22037 ----------


 ---------- 2017-10-15 18:00:00 : 효자1동   22038 ----------


 ---------- 2017-10-15 19:00:00 : 소양동   22040 ----------


 ---------- 2017-10-15 23:00:00 : 동  면   22041 ----------


 ---------- 2017-10-16 00:00:00 : 동  면   22042 ----------


 ---------- 2017-10-16 09:00:00 : 남산면   22044 ----------


 ---------- 2017-10-16 12:00:00 : 교  동   22045 ----------


 ---------- 2017-10-16 13:00:00 : 강남동   22046 ----------

 ---------- 2017-10-16 14:00:00 : 퇴계동   22047 ----------


 ---------- 2017-10-16 14:00:00 : 교  동   22048 ----------


 ---------- 2017-10-16 16:00:00 : 동내면   22049 ----------


 ---------- 2017-10-16 16:00:00 : 남산면   22050 ----------


 ---------- 2017-10-16 18:00:00 : 동  면   22051 ----------


 ---------- 2017-10-16 19:00:00 : 석사동   22055 ----------


 ---------- 2017-10-16 19:00:00 : 동  면   22056 ----------


 ---------- 2017-10-17 04:00:00 : 효자1동   22057 ----------


 ---------- 2017-10-17 08:00:00 : 효자1동   22058 ----------


 ---------- 2017-10-17 09:00:00 : 후평1동   22059 ----------


 ---------- 2017-10-17 10:00:00 : 남산면   22060 ----------


 ---------- 2017-10-17 15:00:00 : 동  면   22061 ----------


 ---------- 2017-10-17 18:00:00 : 석사동   22062 ----------


 ---------- 2017-10-17 21:00:00 : 석사동   22063 ----------


 ---------- 2017-10-17 21:00:00 : 효자1동   22064 ----------


 ---------- 2017-10-18 06:00:00 : 효자1동   22065 ----------


 ---------- 2017-10-18 11:00:00 : 동산면   22066 ----------


 ---------- 2017-10-18 12:00:00 : 서  면   22067 ----------


 ---------- 2017-10-18 13:00:00 : 교  동   22068 ----------


 ---------- 2017-10-18 15:00:00 : 석사동   22069 ----------


 ---------- 2017-10-18 15:00:00 : 남산면   22070 ----------


 ---------- 2017-10-18 18:00:00 : 동  면   22071 ----------


 ---------- 2017-10-18 19:00:00 : 소양동   22072 ----------


 ---------- 2017-10-19 04:00:00 : 석사동   22073 ----------


 ---------- 2017-10-19 11:00:00 : 신북읍   22074 ----------


 ---------- 2017-10-19 12:00:00 : 강남동   22075 ----------


 ---------- 2017-10-19 14:00:00 : 강남동   22076 ----------


 ---------- 2017-10-19 15:00:00 : 강남동   22077 ----------


 ---------- 2017-10-19 16:00:00 : 서  면   22078 ----------


 ---------- 2017-10-20 12:00:00 : 남산면   22079 ----------


 ---------- 2017-10-20 14:00:00 : 퇴계동   22080 ----------


 ---------- 2017-10-20 15:00:00 : 교  동   22082 ----------


 ---------- 2017-10-20 16:00:00 : 동  면   22083 ----------


 ---------- 2017-10-20 18:00:00 : 동내면   22084 ----------


 ---------- 2017-10-20 20:00:00 : 후평1동   22085 ----------


 ---------- 2017-10-20 21:00:00 : 동  면   22086 ----------


 ---------- 2017-10-20 23:00:00 : 석사동   22087 ----------


 ---------- 2017-10-21 09:00:00 : 사북면   22088 ----------


 ---------- 2017-10-21 10:00:00 : 강남동   22090 ----------


 ---------- 2017-10-21 19:00:00 : 사북면   22091 ----------


 ---------- 2017-10-21 21:00:00 : 후평1동   22092 ----------


 ---------- 2017-10-22 07:00:00 : 동  면   22093 ----------


 ---------- 2017-10-22 09:00:00 : 서  면   22094 ----------


 ---------- 2017-10-22 10:00:00 : 사북면   22095 ----------


 ---------- 2017-10-22 10:00:00 : 신사우동   22096 ----------


 ---------- 2017-10-22 11:00:00 : 강남동   22097 ----------


 ---------- 2017-10-22 11:00:00 : 후평1동   22098 ----------


 ---------- 2017-10-22 14:00:00 : 석사동   22099 ----------


 ---------- 2017-10-22 14:00:00 : 동  면   22100 ----------


 ---------- 2017-10-22 15:00:00 : 후평1동   22101 ----------


 ---------- 2017-10-22 16:00:00 : 효자1동   22102 ----------


 ---------- 2017-10-22 16:00:00 : 후평1동   22103 ----------


 ---------- 2017-10-22 18:00:00 : 사북면   22104 ----------


 ---------- 2017-10-22 21:00:00 : 퇴계동   22106 ----------


 ---------- 2017-10-22 22:00:00 : 후평1동   22107 ----------


 ---------- 2017-10-23 08:00:00 : 소양동   22108 ----------


 ---------- 2017-10-23 09:00:00 : 석사동   22110 ----------


 ---------- 2017-10-23 10:00:00 : 퇴계동   22111 ----------


 ---------- 2017-10-23 12:00:00 : 효자1동   22112 ----------


 ---------- 2017-10-23 12:00:00 : 남산면   22113 ----------


 ---------- 2017-10-23 14:00:00 : 동  면   22114 ----------


 ---------- 2017-10-23 16:00:00 : 신동면   22115 ----------


 ---------- 2017-10-23 19:00:00 : 강남동   22116 ----------


 ---------- 2017-10-23 20:00:00 : 석사동   22117 ----------


 ---------- 2017-10-24 11:00:00 : 서  면   22118 ----------


 ---------- 2017-10-24 13:00:00 : 동  면   22120 ----------


 ---------- 2017-10-24 14:00:00 : 서  면   22121 ----------


 ---------- 2017-10-24 17:00:00 : 신사우동   22122 ----------


 ---------- 2017-10-24 18:00:00 : 약사명동   22123 ----------


 ---------- 2017-10-24 18:00:00 : 퇴계동   22124 ----------


 ---------- 2017-10-25 11:00:00 : 효자1동   22125 ----------


 ---------- 2017-10-25 12:00:00 : 조운동   22126 ----------


 ---------- 2017-10-25 14:00:00 : 동산면   22127 ----------


 ---------- 2017-10-25 20:00:00 : 동  면   22128 ----------


 ---------- 2017-10-26 09:00:00 : 후평1동   22129 ----------


 ---------- 2017-10-26 13:00:00 : 신북읍   22130 ----------


 ---------- 2017-10-26 19:00:00 : 근화동   22131 ----------


 ---------- 2017-10-26 20:00:00 : 근화동   22132 ----------


 ---------- 2017-10-26 22:00:00 : 후평1동   22133 ----------


 ---------- 2017-10-27 01:00:00 : 신사우동   22134 ----------


 ---------- 2017-10-27 04:00:00 : 신사우동   22135 ----------


 ---------- 2017-10-27 07:00:00 : 퇴계동   22136 ----------


 ---------- 2017-10-27 09:00:00 : 동  면   22137 ----------


 ---------- 2017-10-27 11:00:00 : 동내면   22138 ----------


 ---------- 2017-10-27 12:00:00 : 남산면   22139 ----------


 ---------- 2017-10-27 17:00:00 : 신사우동   22141 ----------


 ---------- 2017-10-27 17:00:00 : 퇴계동   22142 ----------


 ---------- 2017-10-27 18:00:00 : 신북읍   22143 ----------


 ---------- 2017-10-27 23:00:00 : 후평1동   22144 ----------


 ---------- 2017-10-28 05:00:00 : 신사우동   22145 ----------


 ---------- 2017-10-28 08:00:00 : 신동면   22146 ----------


 ---------- 2017-10-28 09:00:00 : 후평1동   22147 ----------


 ---------- 2017-10-28 10:00:00 : 남  면   22148 ----------


 ---------- 2017-10-28 12:00:00 : 남산면   22149 ----------


 ---------- 2017-10-28 12:00:00 : 퇴계동   22150 ----------


 ---------- 2017-10-28 13:00:00 : 남산면   22151 ----------


 ---------- 2017-10-28 13:00:00 : 후평1동   22152 ----------


 ---------- 2017-10-28 16:00:00 : 북산면   22153 ----------


 ---------- 2017-10-28 18:00:00 : 동  면   22155 ----------


 ---------- 2017-10-28 18:00:00 : 후평1동   22156 ----------


 ---------- 2017-10-29 02:00:00 : 후평1동   22157 ----------


 ---------- 2017-10-29 10:00:00 : 신북읍   22158 ----------


 ---------- 2017-10-29 11:00:00 : 사북면   22159 ----------


 ---------- 2017-10-29 11:00:00 : 남산면   22160 ----------


 ---------- 2017-10-29 17:00:00 : 북산면   22161 ----------


 ---------- 2017-10-29 18:00:00 : 근화동   22162 ----------


 ---------- 2017-10-29 19:00:00 : 서  면   22163 ----------


 ---------- 2017-10-30 00:00:00 : 신사우동   22164 ----------


 ---------- 2017-10-30 07:00:00 : 사북면   22165 ----------


 ---------- 2017-10-30 09:00:00 : 동내면   22166 ----------


 ---------- 2017-10-30 11:00:00 : 신북읍   22167 ----------


 ---------- 2017-10-30 19:00:00 : 강남동   22168 ----------


 ---------- 2017-10-30 21:00:00 : 강남동   22170 ----------


 ---------- 2017-10-30 22:00:00 : 남산면   22171 ----------


 ---------- 2017-10-31 00:00:00 : 퇴계동   22173 ----------


 ---------- 2017-10-31 07:00:00 : 후평1동   22174 ----------


 ---------- 2017-10-31 10:00:00 : 후평1동   22175 ----------


 ---------- 2017-10-31 13:00:00 : 약사명동   22176 ----------


 ---------- 2017-10-31 16:00:00 : 동내면   22177 ----------


 ---------- 2017-10-31 17:00:00 : 석사동   22178 ----------


 ---------- 2017-10-31 21:00:00 : 신북읍   22179 ----------


 ---------- 2017-11-01 02:00:00 : 근화동   22180 ----------


 ---------- 2017-11-01 03:00:00 : 강남동   22181 ----------


 ---------- 2017-11-01 12:00:00 : 퇴계동   22182 ----------


 ---------- 2017-11-01 15:00:00 : 강남동   22184 ----------


 ---------- 2017-11-01 20:00:00 : 조운동   22185 ----------


 ---------- 2017-11-02 08:00:00 : 동내면   22186 ----------


 ---------- 2017-11-02 08:00:00 : 효자1동   22187 ----------


 ---------- 2017-11-02 11:00:00 : 약사명동   22189 ----------


 ---------- 2017-11-02 13:00:00 : 효자1동   22190 ----------


 ---------- 2017-11-02 13:00:00 : 교  동   22191 ----------


 ---------- 2017-11-02 15:00:00 : 신사우동   22192 ----------


 ---------- 2017-11-02 22:00:00 : 강남동   22194 ----------


 ---------- 2017-11-03 03:00:00 : 후평1동   22195 ----------


 ---------- 2017-11-03 13:00:00 : 후평1동   22196 ----------


 ---------- 2017-11-03 16:00:00 : 남산면   22197 ----------

 ---------- 2017-11-03 19:00:00 : 조운동   22198 ----------


 ---------- 2017-11-04 02:00:00 : 효자1동   22199 ----------


 ---------- 2017-11-04 05:00:00 : 퇴계동   22200 ----------


 ---------- 2017-11-04 09:00:00 : 소양동   22201 ----------


 ---------- 2017-11-04 11:00:00 : 신사우동   22202 ----------


 ---------- 2017-11-04 12:00:00 : 조운동   22203 ----------


 ---------- 2017-11-04 16:00:00 : 동내면   22205 ----------


 ---------- 2017-11-04 18:00:00 : 남산면   22208 ----------


 ---------- 2017-11-04 20:00:00 : 강남동   22209 ----------


 ---------- 2017-11-05 07:00:00 : 동내면   22211 ----------


 ---------- 2017-11-05 10:00:00 : 신북읍   22212 ----------


 ---------- 2017-11-05 12:00:00 : 서  면   22213 ----------


 ---------- 2017-11-05 20:00:00 : 효자1동   22214 ----------


 ---------- 2017-11-05 23:00:00 : 효자1동   22215 ----------


 ---------- 2017-11-06 10:00:00 : 신동면   22216 ----------


 ---------- 2017-11-06 13:00:00 : 후평1동   22217 ----------


 ---------- 2017-11-06 18:00:00 : 서  면   22218 ----------


 ---------- 2017-11-06 19:00:00 : 신사우동   22219 ----------


 ---------- 2017-11-07 00:00:00 : 퇴계동   22220 ----------


 ---------- 2017-11-07 01:00:00 : 석사동   22221 ----------


 ---------- 2017-11-07 12:00:00 : 후평1동   22222 ----------


 ---------- 2017-11-07 16:00:00 : 석사동   22223 ----------


 ---------- 2017-11-07 23:00:00 : 후평1동   22224 ----------


 ---------- 2017-11-08 02:00:00 : 석사동   22225 ----------


 ---------- 2017-11-08 03:00:00 : 석사동   22226 ----------


 ---------- 2017-11-08 06:00:00 : 남산면   22227 ----------


 ---------- 2017-11-08 10:00:00 : 퇴계동   22228 ----------


 ---------- 2017-11-08 13:00:00 : 동내면   22230 ----------


 ---------- 2017-11-08 14:00:00 : 후평1동   22231 ----------


 ---------- 2017-11-08 15:00:00 : 석사동   22232 ----------


 ---------- 2017-11-08 19:00:00 : 석사동   22233 ----------


 ---------- 2017-11-08 19:00:00 : 후평1동   22234 ----------


 ---------- 2017-11-09 07:00:00 : 후평1동   22235 ----------


 ---------- 2017-11-09 09:00:00 : 석사동   22236 ----------


 ---------- 2017-11-09 12:00:00 : 남산면   22237 ----------


 ---------- 2017-11-10 07:00:00 : 퇴계동   22238 ----------


 ---------- 2017-11-10 10:00:00 : 동내면   22239 ----------


 ---------- 2017-11-10 14:00:00 : 남  면   22240 ----------


 ---------- 2017-11-11 12:00:00 : 신북읍   22241 ----------


 ---------- 2017-11-11 16:00:00 : 서  면   22242 ----------


 ---------- 2017-11-11 17:00:00 : 후평1동   22243 ----------


 ---------- 2017-11-12 03:00:00 : 후평1동   22244 ----------


 ---------- 2017-11-12 10:00:00 : 강남동   22245 ----------


 ---------- 2017-11-12 14:00:00 : 석사동   22246 ----------


 ---------- 2017-11-12 16:00:00 : 남산면   22248 ----------


 ---------- 2017-11-12 21:00:00 : 근화동   22249 ----------


 ---------- 2017-11-13 07:00:00 : 석사동   22250 ----------


 ---------- 2017-11-13 09:00:00 : 사북면   22251 ----------


 ---------- 2017-11-14 07:00:00 : 효자1동   22252 ----------


 ---------- 2017-11-14 16:00:00 : 신북읍   22253 ----------


 ---------- 2017-11-15 13:00:00 : 신북읍   22254 ----------


 ---------- 2017-11-15 15:00:00 : 후평1동   22256 ----------


 ---------- 2017-11-15 18:00:00 : 효자1동   22257 ----------


 ---------- 2017-11-15 20:00:00 : 동내면   22258 ----------


 ---------- 2017-11-15 21:00:00 : 강남동   22259 ----------


 ---------- 2017-11-16 01:00:00 : 근화동   22260 ----------


 ---------- 2017-11-16 02:00:00 : 효자1동   22261 ----------


 ---------- 2017-11-16 08:00:00 : 효자1동   22262 ----------


 ---------- 2017-11-16 10:00:00 : 강남동   22263 ----------


 ---------- 2017-11-16 10:00:00 : 남산면   22264 ----------


 ---------- 2017-11-16 11:00:00 : 효자1동   22265 ----------


 ---------- 2017-11-16 12:00:00 : 강남동   22266 ----------


 ---------- 2017-11-16 12:00:00 : 남  면   22268 ----------


 ---------- 2017-11-16 12:00:00 : 동  면   22269 ----------


 ---------- 2017-11-16 13:00:00 : 강남동   22270 ----------


 ---------- 2017-11-16 15:00:00 : 강남동   22271 ----------


 ---------- 2017-11-16 17:00:00 : 신북읍   22272 ----------


 ---------- 2017-11-16 21:00:00 : 후평1동   22273 ----------


 ---------- 2017-11-17 14:00:00 : 신사우동   22274 ----------


 ---------- 2017-11-17 16:00:00 : 후평1동   22275 ----------


 ---------- 2017-11-17 20:00:00 : 동  면   22276 ----------


 ---------- 2017-11-17 23:00:00 : 조운동   22277 ----------


 ---------- 2017-11-18 10:00:00 : 남산면   22280 ----------


 ---------- 2017-11-18 12:00:00 : 서  면   22281 ----------


 ---------- 2017-11-18 13:00:00 : 석사동   22282 ----------


 ---------- 2017-11-18 13:00:00 : 사북면   22283 ----------


 ---------- 2017-11-18 13:00:00 : 동  면   22284 ----------


 ---------- 2017-11-19 10:00:00 : 후평1동   22285 ----------


 ---------- 2017-11-19 13:00:00 : 석사동   22286 ----------


 ---------- 2017-11-19 14:00:00 : 동내면   22287 ----------


 ---------- 2017-11-19 14:00:00 : 신사우동   22288 ----------


 ---------- 2017-11-19 17:00:00 : 효자1동   22289 ----------


 ---------- 2017-11-19 18:00:00 : 후평1동   22290 ----------


 ---------- 2017-11-19 23:00:00 : 퇴계동   22291 ----------


 ---------- 2017-11-20 08:00:00 : 근화동   22292 ----------


 ---------- 2017-11-20 08:00:00 : 동산면   22293 ----------


 ---------- 2017-11-20 09:00:00 : 남산면   22294 ----------


 ---------- 2017-11-20 13:00:00 : 동산면   22296 ----------


 ---------- 2017-11-20 14:00:00 : 동산면   22297 ----------


 ---------- 2017-11-20 16:00:00 : 교  동   22298 ----------


 ---------- 2017-11-20 19:00:00 : 조운동   22299 ----------


 ---------- 2017-11-21 09:00:00 : 남산면   22300 ----------


 ---------- 2017-11-21 10:00:00 : 조운동   22302 ----------


 ---------- 2017-11-21 11:00:00 : 동내면   22303 ----------


 ---------- 2017-11-21 13:00:00 : 석사동   22304 ----------


 ---------- 2017-11-21 18:00:00 : 근화동   22305 ----------


 ---------- 2017-11-21 21:00:00 : 석사동   22306 ----------


 ---------- 2017-11-22 09:00:00 : 남산면   22307 ----------


 ---------- 2017-11-22 09:00:00 : 퇴계동   22308 ----------


 ---------- 2017-11-22 10:00:00 : 신사우동   22309 ----------


 ---------- 2017-11-23 09:00:00 : 남산면   22310 ----------


 ---------- 2017-11-23 10:00:00 : 신사우동   22311 ----------


 ---------- 2017-11-23 10:00:00 : 후평1동   22312 ----------


 ---------- 2017-11-23 12:00:00 : 신동면   22313 ----------


 ---------- 2017-11-23 16:00:00 : 퇴계동   22315 ----------


 ---------- 2017-11-23 22:00:00 : 남산면   22316 ----------


 ---------- 2017-11-24 09:00:00 : 남산면   22317 ----------


 ---------- 2017-11-24 16:00:00 : 강남동   22318 ----------


 ---------- 2017-11-24 19:00:00 : 동내면   22319 ----------


 ---------- 2017-11-24 22:00:00 : 사북면   22320 ----------


 ---------- 2017-11-24 22:00:00 : 퇴계동   22321 ----------


 ---------- 2017-11-25 00:00:00 : 퇴계동   22322 ----------


 ---------- 2017-11-25 07:00:00 : 신북읍   22323 ----------


 ---------- 2017-11-25 11:00:00 : 동  면   22324 ----------


 ---------- 2017-11-25 16:00:00 : 석사동   22325 ----------


 ---------- 2017-11-25 18:00:00 : 동내면   22326 ----------


 ---------- 2017-11-25 18:00:00 : 남산면   22327 ----------


 ---------- 2017-11-25 23:00:00 : 효자1동   22328 ----------


 ---------- 2017-11-26 12:00:00 : 석사동   22329 ----------


 ---------- 2017-11-26 12:00:00 : 효자1동   22330 ----------


 ---------- 2017-11-26 14:00:00 : 근화동   22331 ----------


 ---------- 2017-11-26 14:00:00 : 북산면   22332 ----------


 ---------- 2017-11-26 22:00:00 : 효자1동   22333 ----------


 ---------- 2017-11-27 05:00:00 : 석사동   22334 ----------


 ---------- 2017-11-27 09:00:00 : 서  면   22335 ----------


 ---------- 2017-11-27 09:00:00 : 퇴계동   22336 ----------


 ---------- 2017-11-27 16:00:00 : 강남동   22337 ----------


 ---------- 2017-11-27 18:00:00 : 동  면   22338 ----------


 ---------- 2017-11-27 21:00:00 : 퇴계동   22339 ----------


 ---------- 2017-11-28 12:00:00 : 퇴계동   22340 ----------


 ---------- 2017-11-28 15:00:00 : 동내면   22341 ----------


 ---------- 2017-11-29 15:00:00 : 석사동   22342 ----------


 ---------- 2017-11-29 15:00:00 : 남  면   22343 ----------


 ---------- 2017-11-29 17:00:00 : 강남동   22344 ----------


 ---------- 2017-11-30 13:00:00 : 북산면   22347 ----------


 ---------- 2017-11-30 15:00:00 : 후평1동   22348 ----------

 ---------- 2017-12-01 09:00:00 : 퇴계동   22349 ----------


 ---------- 2017-12-01 19:00:00 : 동내면   22350 ----------


 ---------- 2017-12-01 21:00:00 : 석사동   22351 ----------


 ---------- 2017-12-01 21:00:00 : 동  면   22352 ----------


 ---------- 2017-12-02 01:00:00 : 신사우동   22354 ----------


 ---------- 2017-12-02 15:00:00 : 약사명동   22355 ----------


 ---------- 2017-12-02 17:00:00 : 강남동   22356 ----------


 ---------- 2017-12-03 05:00:00 : 후평1동   22357 ----------


 ---------- 2017-12-03 11:00:00 : 동  면   22358 ----------


 ---------- 2017-12-03 17:00:00 : 신사우동   22360 ----------


 ---------- 2017-12-04 09:00:00 : 동내면   22361 ----------


 ---------- 2017-12-04 15:00:00 : 신동면   22362 ----------


 ---------- 2017-12-04 15:00:00 : 강남동   22364 ----------


 ---------- 2017-12-04 17:00:00 : 동내면   22365 ----------


 ---------- 2017-12-05 14:00:00 : 석사동   22366 ----------


 ---------- 2017-12-05 22:00:00 : 석사동   22367 ----------


 ---------- 2017-12-06 10:00:00 : 남  면   22368 ----------


 ---------- 2017-12-06 12:00:00 : 신사우동   22369 ----------


 ---------- 2017-12-06 17:00:00 : 서  면   22370 ----------


 ---------- 2017-12-06 17:00:00 : 퇴계동   22371 ----------


 ---------- 2017-12-06 18:00:00 : 퇴계동   22372 ----------


 ---------- 2017-12-07 08:00:00 : 소양동   22373 ----------


 ---------- 2017-12-07 10:00:00 : 효자1동   22374 ----------


 ---------- 2017-12-07 13:00:00 : 퇴계동   22375 ----------


 ---------- 2017-12-07 13:00:00 : 북산면   22377 ----------


 ---------- 2017-12-08 07:00:00 : 동내면   22378 ----------


 ---------- 2017-12-08 12:00:00 : 신동면   22379 ----------


 ---------- 2017-12-08 12:00:00 : 서  면   22380 ----------


 ---------- 2017-12-08 13:00:00 : 후평1동   22381 ----------


 ---------- 2017-12-08 18:00:00 : 남산면   22383 ----------


 ---------- 2017-12-09 02:00:00 : 신사우동   22384 ----------


 ---------- 2017-12-09 05:00:00 : 소양동   22385 ----------


 ---------- 2017-12-09 12:00:00 : 신사우동   22387 ----------


 ---------- 2017-12-09 13:00:00 : 남산면   22388 ----------


 ---------- 2017-12-09 16:00:00 : 효자1동   22389 ----------


 ---------- 2017-12-09 19:00:00 : 북산면   22390 ----------


 ---------- 2017-12-09 21:00:00 : 동  면   22391 ----------


 ---------- 2017-12-10 10:00:00 : 소양동   22392 ----------


 ---------- 2017-12-10 10:00:00 : 약사명동   22393 ----------


 ---------- 2017-12-10 19:00:00 : 약사명동   22394 ----------


 ---------- 2017-12-11 12:00:00 : 동내면   22395 ----------


 ---------- 2017-12-11 13:00:00 : 후평1동   22396 ----------


 ---------- 2017-12-11 15:00:00 : 사북면   22397 ----------


 ---------- 2017-12-12 03:00:00 : 교  동   22398 ----------


 ---------- 2017-12-12 08:00:00 : 동  면   22399 ----------


 ---------- 2017-12-12 18:00:00 : 신사우동   22400 ----------


 ---------- 2017-12-12 22:00:00 : 석사동   22401 ----------


 ---------- 2017-12-13 05:00:00 : 교  동   22402 ----------


 ---------- 2017-12-13 07:00:00 : 신사우동   22403 ----------


 ---------- 2017-12-13 10:00:00 : 동내면   22404 ----------


 ---------- 2017-12-13 13:00:00 : 신동면   22405 ----------


 ---------- 2017-12-13 15:00:00 : 퇴계동   22406 ----------


 ---------- 2017-12-13 17:00:00 : 동내면   22408 ----------


 ---------- 2017-12-13 17:00:00 : 효자1동   22410 ----------


 ---------- 2017-12-13 19:00:00 : 효자1동   22411 ----------


 ---------- 2017-12-13 21:00:00 : 석사동   22412 ----------


 ---------- 2017-12-13 23:00:00 : 효자1동   22413 ----------


 ---------- 2017-12-14 01:00:00 : 사북면   22414 ----------


 ---------- 2017-12-14 14:00:00 : 신동면   22415 ----------


 ---------- 2017-12-14 14:00:00 : 동내면   22416 ----------


 ---------- 2017-12-14 16:00:00 : 강남동   22417 ----------


 ---------- 2017-12-14 16:00:00 : 효자1동   22418 ----------


 ---------- 2017-12-15 03:00:00 : 약사명동   22419 ----------


 ---------- 2017-12-15 08:00:00 : 사북면   22420 ----------


 ---------- 2017-12-15 08:00:00 : 효자1동   22421 ----------


 ---------- 2017-12-15 20:00:00 : 효자1동   22422 ----------


 ---------- 2017-12-15 21:00:00 : 석사동   22423 ----------


 ---------- 2017-12-15 22:00:00 : 남산면   22424 ----------


 ---------- 2017-12-15 23:00:00 : 신북읍   22427 ----------


 ---------- 2017-12-16 01:00:00 : 남  면   22429 ----------


 ---------- 2017-12-16 02:00:00 : 후평1동   22430 ----------


 ---------- 2017-12-16 16:00:00 : 후평1동   22431 ----------


 ---------- 2017-12-16 17:00:00 : 퇴계동   22432 ----------


 ---------- 2017-12-16 21:00:00 : 약사명동   22433 ----------


 ---------- 2017-12-16 21:00:00 : 후평1동   22434 ----------


 ---------- 2017-12-17 00:00:00 : 남  면   22436 ----------


 ---------- 2017-12-17 00:00:00 : 동  면   22437 ----------


 ---------- 2017-12-17 09:00:00 : 효자1동   22438 ----------


 ---------- 2017-12-17 12:00:00 : 소양동   22439 ----------


 ---------- 2017-12-17 12:00:00 : 약사명동   22440 ----------


 ---------- 2017-12-17 13:00:00 : 후평1동   22442 ----------


 ---------- 2017-12-17 15:00:00 : 강남동   22443 ----------


 ---------- 2017-12-18 14:00:00 : 약사명동   22444 ----------


 ---------- 2017-12-18 15:00:00 : 동산면   22445 ----------


 ---------- 2017-12-18 17:00:00 : 동  면   22446 ----------


 ---------- 2017-12-19 01:00:00 : 사북면   22447 ----------


 ---------- 2017-12-19 08:00:00 : 동내면   22448 ----------


 ---------- 2017-12-19 13:00:00 : 퇴계동   22449 ----------


 ---------- 2017-12-19 15:00:00 : 효자1동   22450 ----------


 ---------- 2017-12-19 15:00:00 : 동  면   22451 ----------


 ---------- 2017-12-19 17:00:00 : 사북면   22452 ----------


 ---------- 2017-12-20 00:00:00 : 동  면   22453 ----------


 ---------- 2017-12-20 12:00:00 : 소양동   22454 ----------


 ---------- 2017-12-20 13:00:00 : 석사동   22455 ----------


 ---------- 2017-12-20 17:00:00 : 효자1동   22456 ----------


 ---------- 2017-12-20 19:00:00 : 퇴계동   22457 ----------


 ---------- 2017-12-20 20:00:00 : 신동면   22458 ----------


 ---------- 2017-12-20 23:00:00 : 신동면   22460 ----------


 ---------- 2017-12-21 00:00:00 : 동산면   22462 ----------


 ---------- 2017-12-21 08:00:00 : 근화동   22463 ----------


 ---------- 2017-12-21 10:00:00 : 남산면   22464 ----------


 ---------- 2017-12-21 10:00:00 : 신사우동   22465 ----------


 ---------- 2017-12-21 11:00:00 : 교  동   22466 ----------


 ---------- 2017-12-21 12:00:00 : 신사우동   22467 ----------


 ---------- 2017-12-21 14:00:00 : 후평1동   22468 ----------


 ---------- 2017-12-21 18:00:00 : 동산면   22470 ----------


 ---------- 2017-12-21 21:00:00 : 효자1동   22471 ----------


 ---------- 2017-12-22 02:00:00 : 소양동   22472 ----------


 ---------- 2017-12-22 02:00:00 : 퇴계동   22474 ----------


 ---------- 2017-12-22 08:00:00 : 동산면   22475 ----------


 ---------- 2017-12-22 09:00:00 : 약사명동   22476 ----------


 ---------- 2017-12-22 14:00:00 : 신사우동   22477 ----------


 ---------- 2017-12-22 14:00:00 : 신북읍   22478 ----------


 ---------- 2017-12-22 16:00:00 : 신북읍   22479 ----------


 ---------- 2017-12-22 20:00:00 : 석사동   22480 ----------


 ---------- 2017-12-23 02:00:00 : 석사동   22481 ----------


 ---------- 2017-12-23 02:00:00 : 효자1동   22484 ----------


 ---------- 2017-12-24 00:00:00 : 효자1동   22485 ----------


 ---------- 2017-12-24 08:00:00 : 근화동   22486 ----------


 ---------- 2017-12-24 10:00:00 : 효자1동   22487 ----------


 ---------- 2017-12-24 18:00:00 : 조운동   22488 ----------


 ---------- 2017-12-24 23:00:00 : 동  면   22489 ----------


 ---------- 2017-12-25 02:00:00 : 퇴계동   22490 ----------


 ---------- 2017-12-25 05:00:00 : 신북읍   22491 ----------


 ---------- 2017-12-25 07:00:00 : 동내면   22492 ----------


 ---------- 2017-12-25 19:00:00 : 신사우동   22493 ----------


 ---------- 2017-12-25 19:00:00 : 조운동   22494 ----------


 ---------- 2017-12-25 20:00:00 : 조운동   22495 ----------


 ---------- 2017-12-26 03:00:00 : 소양동   22496 ----------


 ---------- 2017-12-26 08:00:00 : 사북면   22497 ----------


 ---------- 2017-12-26 10:00:00 : 효자1동   22498 ----------


 ---------- 2017-12-26 15:00:00 : 동내면   22499 ----------


 ---------- 2017-12-26 19:00:00 : 동내면   22500 ----------


 ---------- 2017-12-26 19:00:00 : 후평1동   22501 ----------


 ---------- 2017-12-27 00:00:00 : 후평1동   22502 ----------


 ---------- 2017-12-27 08:00:00 : 신사우동   22503 ----------

 ---------- 2017-12-27 10:00:00 : 후평1동   22504 ----------


 ---------- 2017-12-27 11:00:00 : 석사동   22505 ----------


 ---------- 2017-12-27 18:00:00 : 신동면   22506 ----------


 ---------- 2017-12-27 20:00:00 : 효자1동   22507 ----------


 ---------- 2017-12-27 22:00:00 : 신동면   22508 ----------


 ---------- 2017-12-28 08:00:00 : 근화동   22509 ----------


 ---------- 2017-12-28 10:00:00 : 효자1동   22510 ----------


 ---------- 2017-12-28 11:00:00 : 동내면   22511 ----------


 ---------- 2017-12-28 11:00:00 : 동  면   22512 ----------


 ---------- 2017-12-28 14:00:00 : 신동면   22513 ----------


 ---------- 2017-12-28 14:00:00 : 강남동   22514 ----------


 ---------- 2017-12-28 14:00:00 : 동  면   22515 ----------


 ---------- 2017-12-28 15:00:00 : 퇴계동   22516 ----------


 ---------- 2017-12-28 18:00:00 : 퇴계동   22517 ----------


 ---------- 2017-12-28 19:00:00 : 석사동   22518 ----------


 ---------- 2017-12-28 20:00:00 : 남산면   22519 ----------


 ---------- 2017-12-29 09:00:00 : 남산면   22520 ----------


 ---------- 2017-12-29 09:00:00 : 신사우동   22521 ----------


 ---------- 2017-12-29 14:00:00 : 퇴계동   22522 ----------


 ---------- 2017-12-29 19:00:00 : 동  면   22523 ----------


 ---------- 2017-12-29 21:00:00 : 석사동   22524 ----------


 ---------- 2017-12-30 01:00:00 : 남산면   22525 ----------


 ---------- 2017-12-30 08:00:00 : 후평1동   22526 ----------


 ---------- 2017-12-30 10:00:00 : 석사동   22528 ----------


 ---------- 2017-12-30 10:00:00 : 신사우동   22529 ----------


 ---------- 2017-12-31 12:00:00 : 동  면   22530 ----------


 ---------- 2017-12-31 15:00:00 : 신북읍   22531 ----------


 ---------- 2018-01-01 10:00:00 : 남  면   22533 ----------


 ---------- 2018-01-01 10:00:00 : 동  면   22534 ----------


 ---------- 2018-01-01 15:00:00 : 강남동   22535 ----------


 ---------- 2018-01-01 15:00:00 : 동  면   22536 ----------


 ---------- 2018-01-01 16:00:00 : 소양동   22537 ----------


 ---------- 2018-01-01 19:00:00 : 효자1동   22538 ----------


 ---------- 2018-01-02 09:00:00 : 근화동   22539 ----------


 ---------- 2018-01-02 09:00:00 : 약사명동   22540 ----------


 ---------- 2018-01-02 13:00:00 : 근화동   22541 ----------


 ---------- 2018-01-02 13:00:00 : 동  면   22542 ----------


 ---------- 2018-01-02 18:00:00 : 후평1동   22543 ----------


 ---------- 2018-01-02 23:00:00 : 남산면   22544 ----------


 ---------- 2018-01-03 09:00:00 : 교  동   22545 ----------


 ---------- 2018-01-03 12:00:00 : 남산면   22547 ----------


 ---------- 2018-01-03 15:00:00 : 후평1동   22548 ----------


 ---------- 2018-01-03 17:00:00 : 퇴계동   22549 ----------


 ---------- 2018-01-03 22:00:00 : 후평1동   22550 ----------


 ---------- 2018-01-04 01:00:00 : 신사우동   22551 ----------


 ---------- 2018-01-04 02:00:00 : 소양동   22552 ----------


 ---------- 2018-01-04 04:00:00 : 석사동   22553 ----------


 ---------- 2018-01-04 04:00:00 : 효자1동   22554 ----------


 ---------- 2018-01-04 15:00:00 : 남산면   22555 ----------


 ---------- 2018-01-04 15:00:00 : 소양동   22557 ----------


 ---------- 2018-01-04 17:00:00 : 강남동   22558 ----------


 ---------- 2018-01-04 19:00:00 : 근화동   22559 ----------


 ---------- 2018-01-04 23:00:00 : 약사명동   22560 ----------


 ---------- 2018-01-05 03:00:00 : 후평1동   22561 ----------


 ---------- 2018-01-05 03:00:00 : 퇴계동   22563 ----------


 ---------- 2018-01-05 09:00:00 : 서  면   22564 ----------


 ---------- 2018-01-05 13:00:00 : 퇴계동   22565 ----------


 ---------- 2018-01-05 15:00:00 : 석사동   22566 ----------


 ---------- 2018-01-06 13:00:00 : 석사동   22568 ----------


 ---------- 2018-01-06 23:00:00 : 동  면   22569 ----------


 ---------- 2018-01-07 11:00:00 : 동  면   22570 ----------


 ---------- 2018-01-07 12:00:00 : 동내면   22571 ----------


 ---------- 2018-01-07 13:00:00 : 남산면   22572 ----------


 ---------- 2018-01-07 18:00:00 : 강남동   22573 ----------


 ---------- 2018-01-07 18:00:00 : 조운동   22574 ----------


 ---------- 2018-01-07 21:00:00 : 사북면   22575 ----------


 ---------- 2018-01-08 04:00:00 : 효자1동   22576 ----------


 ---------- 2018-01-08 05:00:00 : 신북읍   22577 ----------


 ---------- 2018-01-08 13:00:00 : 소양동   22578 ----------


 ---------- 2018-01-08 14:00:00 : 효자1동   22579 ----------


 ---------- 2018-01-09 02:00:00 : 효자1동   22580 ----------


 ---------- 2018-01-09 04:00:00 : 신사우동   22581 ----------


 ---------- 2018-01-09 10:00:00 : 강남동   22582 ----------


 ---------- 2018-01-09 15:00:00 : 강남동   22583 ----------


 ---------- 2018-01-09 15:00:00 : 근화동   22584 ----------


 ---------- 2018-01-09 16:00:00 : 동산면   22585 ----------


 ---------- 2018-01-09 18:00:00 : 남  면   22587 ----------


 ---------- 2018-01-10 00:00:00 : 퇴계동   22588 ----------


 ---------- 2018-01-10 16:00:00 : 퇴계동   22589 ----------


 ---------- 2018-01-10 22:00:00 : 신동면   22591 ----------


 ---------- 2018-01-11 00:00:00 : 효자1동   22592 ----------


 ---------- 2018-01-11 02:00:00 : 석사동   22593 ----------


 ---------- 2018-01-11 14:00:00 : 신동면   22594 ----------


 ---------- 2018-01-11 21:00:00 : 남산면   22595 ----------


 ---------- 2018-01-11 22:00:00 : 남산면   22596 ----------


 ---------- 2018-01-12 06:00:00 : 신사우동   22597 ----------


 ---------- 2018-01-12 13:00:00 : 사북면   22598 ----------


 ---------- 2018-01-12 13:00:00 : 조운동   22599 ----------


 ---------- 2018-01-13 11:00:00 : 석사동   22600 ----------


 ---------- 2018-01-13 17:00:00 : 신사우동   22601 ----------


 ---------- 2018-01-13 19:00:00 : 북산면   22602 ----------


 ---------- 2018-01-13 21:00:00 : 동내면   22603 ----------


 ---------- 2018-01-13 22:00:00 : 동내면   22604 ----------


 ---------- 2018-01-13 23:00:00 : 신사우동   22605 ----------


 ---------- 2018-01-14 09:00:00 : 석사동   22606 ----------


 ---------- 2018-01-14 14:00:00 : 강남동   22607 ----------


 ---------- 2018-01-14 17:00:00 : 강남동   22608 ----------


 ---------- 2018-01-14 18:00:00 : 신사우동   22609 ----------


 ---------- 2018-01-15 09:00:00 : 신사우동   22610 ----------


 ---------- 2018-01-15 11:00:00 : 퇴계동   22611 ----------


 ---------- 2018-01-15 12:00:00 : 서  면   22612 ----------


 ---------- 2018-01-15 12:00:00 : 동  면   22613 ----------


 ---------- 2018-01-15 13:00:00 : 동내면   22614 ----------


 ---------- 2018-01-15 14:00:00 : 퇴계동   22615 ----------


 ---------- 2018-01-15 18:00:00 : 남산면   22616 ----------


 ---------- 2018-01-15 21:00:00 : 후평1동   22617 ----------


 ---------- 2018-01-16 02:00:00 : 효자1동   22618 ----------


 ---------- 2018-01-16 04:00:00 : 조운동   22619 ----------


 ---------- 2018-01-16 12:00:00 : 석사동   22620 ----------


 ---------- 2018-01-16 15:00:00 : 서  면   22621 ----------


 ---------- 2018-01-16 16:00:00 : 서  면   22622 ----------


 ---------- 2018-01-16 18:00:00 : 후평1동   22623 ----------


 ---------- 2018-01-16 18:00:00 : 조운동   22624 ----------


 ---------- 2018-01-16 22:00:00 : 후평1동   22626 ----------


 ---------- 2018-01-17 10:00:00 : 퇴계동   22627 ----------


 ---------- 2018-01-17 12:00:00 : 신사우동   22628 ----------


 ---------- 2018-01-17 14:00:00 : 효자1동   22629 ----------


 ---------- 2018-01-17 19:00:00 : 퇴계동   22630 ----------


 ---------- 2018-01-18 03:00:00 : 석사동   22631 ----------


 ---------- 2018-01-18 09:00:00 : 교  동   22632 ----------


 ---------- 2018-01-18 10:00:00 : 동  면   22633 ----------


 ---------- 2018-01-18 15:00:00 : 동내면   22634 ----------


 ---------- 2018-01-18 15:00:00 : 신사우동   22636 ----------


 ---------- 2018-01-19 14:00:00 : 서  면   22637 ----------


 ---------- 2018-01-19 15:00:00 : 서  면   22638 ----------


 ---------- 2018-01-19 15:00:00 : 남산면   22639 ----------


 ---------- 2018-01-20 01:00:00 : 신사우동   22640 ----------


 ---------- 2018-01-20 12:00:00 : 효자1동   22641 ----------


 ---------- 2018-01-20 14:00:00 : 사북면   22643 ----------


 ---------- 2018-01-20 15:00:00 : 강남동   22645 ----------


 ---------- 2018-01-20 16:00:00 : 약사명동   22646 ----------


 ---------- 2018-01-20 17:00:00 : 효자1동   22647 ----------


 ---------- 2018-01-20 21:00:00 : 석사동   22648 ----------


 ---------- 2018-01-21 09:00:00 : 퇴계동   22649 ----------


 ---------- 2018-01-21 19:00:00 : 사북면   22650 ----------


 ---------- 2018-01-21 23:00:00 : 석사동   22651 ----------

 ---------- 2018-01-21 23:00:00 : 후평1동   22652 ----------


 ---------- 2018-01-22 02:00:00 : 효자1동   22653 ----------


 ---------- 2018-01-22 06:00:00 : 효자1동   22654 ----------


 ---------- 2018-01-22 09:00:00 : 퇴계동   22655 ----------


 ---------- 2018-01-22 10:00:00 : 신북읍   22656 ----------


 ---------- 2018-01-22 12:00:00 : 약사명동   22657 ----------


 ---------- 2018-01-22 12:00:00 : 후평1동   22658 ----------


 ---------- 2018-01-22 20:00:00 : 사북면   22659 ----------


 ---------- 2018-01-23 01:00:00 : 신동면   22661 ----------


 ---------- 2018-01-23 02:00:00 : 석사동   22662 ----------


 ---------- 2018-01-23 02:00:00 : 신북읍   22663 ----------


 ---------- 2018-01-23 11:00:00 : 동내면   22665 ----------


 ---------- 2018-01-23 14:00:00 : 강남동   22666 ----------


 ---------- 2018-01-23 17:00:00 : 동산면   22667 ----------


 ---------- 2018-01-23 23:00:00 : 퇴계동   22668 ----------


 ---------- 2018-01-24 08:00:00 : 후평1동   22669 ----------


 ---------- 2018-01-25 08:00:00 : 강남동   22673 ----------


 ---------- 2018-01-25 08:00:00 : 남산면   22675 ----------


 ---------- 2018-01-25 08:00:00 : 신사우동   22676 ----------


 ---------- 2018-01-25 10:00:00 : 서  면   22677 ----------


 ---------- 2018-01-25 10:00:00 : 동  면   22678 ----------


 ---------- 2018-01-25 13:00:00 : 동내면   22679 ----------


 ---------- 2018-01-25 16:00:00 : 신동면   22680 ----------


 ---------- 2018-01-25 16:00:00 : 신사우동   22681 ----------


 ---------- 2018-01-25 16:00:00 : 후평1동   22682 ----------


 ---------- 2018-01-25 22:00:00 : 효자1동   22684 ----------


 ---------- 2018-01-25 23:00:00 : 동내면   22685 ----------


 ---------- 2018-01-25 23:00:00 : 후평1동   22686 ----------


 ---------- 2018-01-26 02:00:00 : 효자1동   22687 ----------


 ---------- 2018-01-26 10:00:00 : 석사동   22688 ----------


 ---------- 2018-01-26 14:00:00 : 동  면   22689 ----------


 ---------- 2018-01-26 15:00:00 : 강남동   22690 ----------


 ---------- 2018-01-26 16:00:00 : 후평1동   22691 ----------


 ---------- 2018-01-26 21:00:00 : 근화동   22692 ----------


 ---------- 2018-01-27 00:00:00 : 신사우동   22693 ----------


 ---------- 2018-01-27 09:00:00 : 남산면   22694 ----------


 ---------- 2018-01-27 10:00:00 : 동내면   22695 ----------


 ---------- 2018-01-27 13:00:00 : 동  면   22697 ----------


 ---------- 2018-01-27 15:00:00 : 석사동   22698 ----------


 ---------- 2018-01-27 19:00:00 : 후평1동   22699 ----------


 ---------- 2018-01-27 21:00:00 : 후평1동   22701 ----------


 ---------- 2018-01-28 04:00:00 : 효자1동   22702 ----------


 ---------- 2018-01-28 10:00:00 : 근화동   22703 ----------


 ---------- 2018-01-28 11:00:00 : 강남동   22704 ----------


 ---------- 2018-01-28 12:00:00 : 효자1동   22705 ----------


 ---------- 2018-01-28 13:00:00 : 효자1동   22706 ----------


 ---------- 2018-01-28 17:00:00 : 동  면   22707 ----------


 ---------- 2018-01-29 10:00:00 : 후평1동   22708 ----------


 ---------- 2018-01-29 13:00:00 : 신동면   22709 ----------


 ---------- 2018-01-29 13:00:00 : 약사명동   22710 ----------


 ---------- 2018-01-29 14:00:00 : 석사동   22711 ----------


 ---------- 2018-01-30 03:00:00 : 남산면   22712 ----------


 ---------- 2018-01-30 09:00:00 : 후평1동   22713 ----------


 ---------- 2018-01-30 12:00:00 : 신사우동   22714 ----------


 ---------- 2018-01-30 13:00:00 : 동  면   22715 ----------


 ---------- 2018-01-30 13:00:00 : 북산면   22716 ----------


 ---------- 2018-01-30 17:00:00 : 동내면   22717 ----------


 ---------- 2018-01-30 19:00:00 : 효자1동   22718 ----------


 ---------- 2018-01-31 00:00:00 : 동내면   22719 ----------


 ---------- 2018-01-31 01:00:00 : 동내면   22720 ----------


 ---------- 2018-01-31 10:00:00 : 남  면   22721 ----------


 ---------- 2018-01-31 10:00:00 : 동내면   22722 ----------


 ---------- 2018-01-31 13:00:00 : 서  면   22723 ----------


 ---------- 2018-01-31 14:00:00 : 후평1동   22724 ----------


 ---------- 2018-01-31 16:00:00 : 후평1동   22726 ----------


 ---------- 2018-01-31 17:00:00 : 퇴계동   22727 ----------


 ---------- 2018-01-31 18:00:00 : 효자1동   22728 ----------


 ---------- 2018-01-31 23:00:00 : 북산면   22729 ----------


 ---------- 2018-02-01 09:00:00 : 동내면   22730 ----------


 ---------- 2018-02-01 10:00:00 : 석사동   22731 ----------


 ---------- 2018-02-01 14:00:00 : 근화동   22732 ----------


 ---------- 2018-02-01 17:00:00 : 석사동   22734 ----------


 ---------- 2018-02-02 07:00:00 : 약사명동   22735 ----------


 ---------- 2018-02-02 08:00:00 : 효자1동   22736 ----------


 ---------- 2018-02-02 11:00:00 : 동산면   22737 ----------


 ---------- 2018-02-02 13:00:00 : 서  면   22738 ----------


 ---------- 2018-02-02 14:00:00 : 신사우동   22739 ----------


 ---------- 2018-02-02 19:00:00 : 남  면   22740 ----------


 ---------- 2018-02-02 20:00:00 : 퇴계동   22741 ----------


 ---------- 2018-02-02 22:00:00 : 석사동   22744 ----------


 ---------- 2018-02-03 05:00:00 : 동  면   22745 ----------


 ---------- 2018-02-03 12:00:00 : 퇴계동   22746 ----------


 ---------- 2018-02-03 13:00:00 : 서  면   22747 ----------


 ---------- 2018-02-03 15:00:00 : 동내면   22748 ----------


 ---------- 2018-02-03 16:00:00 : 남  면   22749 ----------


 ---------- 2018-02-03 18:00:00 : 조운동   22750 ----------


 ---------- 2018-02-03 20:00:00 : 남산면   22754 ----------


 ---------- 2018-02-04 00:00:00 : 후평1동   22755 ----------


 ---------- 2018-02-04 12:00:00 : 신사우동   22756 ----------


 ---------- 2018-02-04 14:00:00 : 신동면   22757 ----------


 ---------- 2018-02-04 17:00:00 : 동  면   22758 ----------


 ---------- 2018-02-04 20:00:00 : 석사동   22759 ----------


 ---------- 2018-02-04 20:00:00 : 사북면   22760 ----------


 ---------- 2018-02-04 21:00:00 : 동내면   22761 ----------


 ---------- 2018-02-05 01:00:00 : 동  면   22762 ----------


 ---------- 2018-02-05 12:00:00 : 근화동   22763 ----------


 ---------- 2018-02-05 13:00:00 : 신사우동   22764 ----------


 ---------- 2018-02-05 16:00:00 : 퇴계동   22765 ----------


 ---------- 2018-02-05 23:00:00 : 퇴계동   22766 ----------


 ---------- 2018-02-06 00:00:00 : 동내면   22767 ----------


 ---------- 2018-02-06 01:00:00 : 남산면   22768 ----------


 ---------- 2018-02-06 06:00:00 : 퇴계동   22769 ----------


 ---------- 2018-02-06 13:00:00 : 퇴계동   22770 ----------


 ---------- 2018-02-06 15:00:00 : 사북면   22772 ----------


 ---------- 2018-02-06 18:00:00 : 동  면   22773 ----------


 ---------- 2018-02-07 13:00:00 : 남산면   22774 ----------


 ---------- 2018-02-07 13:00:00 : 후평1동   22775 ----------


 ---------- 2018-02-07 15:00:00 : 동내면   22776 ----------


 ---------- 2018-02-07 16:00:00 : 동  면   22777 ----------


 ---------- 2018-02-07 21:00:00 : 소양동   22778 ----------


 ---------- 2018-02-07 22:00:00 : 퇴계동   22779 ----------


 ---------- 2018-02-08 00:00:00 : 동  면   22782 ----------


 ---------- 2018-02-08 00:00:00 : 퇴계동   22783 ----------


 ---------- 2018-02-08 01:00:00 : 동  면   22784 ----------


 ---------- 2018-02-08 09:00:00 : 서  면   22785 ----------


 ---------- 2018-02-08 09:00:00 : 남산면   22786 ----------


 ---------- 2018-02-08 11:00:00 : 신사우동   22787 ----------


 ---------- 2018-02-08 12:00:00 : 신사우동   22788 ----------


 ---------- 2018-02-08 13:00:00 : 사북면   22789 ----------


 ---------- 2018-02-08 13:00:00 : 퇴계동   22790 ----------


 ---------- 2018-02-08 15:00:00 : 효자1동   22791 ----------


 ---------- 2018-02-08 15:00:00 : 남산면   22792 ----------


 ---------- 2018-02-08 16:00:00 : 서  면   22793 ----------


 ---------- 2018-02-08 23:00:00 : 동  면   22794 ----------


 ---------- 2018-02-09 07:00:00 : 동산면   22795 ----------


 ---------- 2018-02-09 08:00:00 : 퇴계동   22797 ----------


 ---------- 2018-02-09 10:00:00 : 근화동   22799 ----------


 ---------- 2018-02-09 10:00:00 : 약사명동   22800 ----------


 ---------- 2018-02-09 11:00:00 : 남산면   22801 ----------


 ---------- 2018-02-09 12:00:00 : 강남동   22802 ----------


 ---------- 2018-02-09 13:00:00 : 남산면   22803 ----------


 ---------- 2018-02-09 13:00:00 : 신북읍   22804 ----------


 ---------- 2018-02-09 14:00:00 : 신사우동   22806 ----------


 ---------- 2018-02-09 17:00:00 : 신사우동   22807 ----------


 ---------- 2018-02-09 22:00:00 : 강남동   22808 ----------


 ---------- 2018-02-09 22:00:00 : 신사우동   22809 ----------

 ---------- 2018-02-09 23:00:00 : 서  면   22810 ----------


 ---------- 2018-02-10 14:00:00 : 후평1동   22811 ----------


 ---------- 2018-02-10 14:00:00 : 퇴계동   22813 ----------


 ---------- 2018-02-10 16:00:00 : 남산면   22814 ----------


 ---------- 2018-02-10 19:00:00 : 퇴계동   22815 ----------


 ---------- 2018-02-11 03:00:00 : 남산면   22816 ----------


 ---------- 2018-02-11 14:00:00 : 후평1동   22817 ----------


 ---------- 2018-02-11 14:00:00 : 퇴계동   22818 ----------


 ---------- 2018-02-11 17:00:00 : 강남동   22819 ----------


 ---------- 2018-02-11 18:00:00 : 서  면   22820 ----------


 ---------- 2018-02-11 19:00:00 : 남산면   22821 ----------


 ---------- 2018-02-11 21:00:00 : 강남동   22822 ----------


 ---------- 2018-02-12 11:00:00 : 남산면   22823 ----------


 ---------- 2018-02-12 14:00:00 : 후평1동   22824 ----------


 ---------- 2018-02-12 15:00:00 : 신북읍   22825 ----------


 ---------- 2018-02-12 15:00:00 : 동산면   22826 ----------


 ---------- 2018-02-12 16:00:00 : 소양동   22827 ----------


 ---------- 2018-02-12 16:00:00 : 퇴계동   22829 ----------


 ---------- 2018-02-12 17:00:00 : 서  면   22830 ----------


 ---------- 2018-02-12 17:00:00 : 신사우동   22831 ----------


 ---------- 2018-02-13 14:00:00 : 서  면   22832 ----------


 ---------- 2018-02-13 15:00:00 : 퇴계동   22833 ----------


 ---------- 2018-02-14 06:00:00 : 신북읍   22834 ----------


 ---------- 2018-02-14 10:00:00 : 서  면   22835 ----------


 ---------- 2018-02-14 10:00:00 : 근화동   22836 ----------


 ---------- 2018-02-14 11:00:00 : 동산면   22838 ----------


 ---------- 2018-02-14 13:00:00 : 석사동   22839 ----------


 ---------- 2018-02-14 14:00:00 : 남  면   22840 ----------


 ---------- 2018-02-14 18:00:00 : 석사동   22841 ----------


 ---------- 2018-02-14 22:00:00 : 신사우동   22842 ----------


 ---------- 2018-02-15 01:00:00 : 신북읍   22843 ----------


 ---------- 2018-02-15 10:00:00 : 남산면   22844 ----------


 ---------- 2018-02-15 11:00:00 : 서  면   22845 ----------


 ---------- 2018-02-15 14:00:00 : 신사우동   22846 ----------


 ---------- 2018-02-15 17:00:00 : 강남동   22847 ----------


 ---------- 2018-02-15 20:00:00 : 조운동   22848 ----------


 ---------- 2018-02-16 11:00:00 : 남산면   22849 ----------


 ---------- 2018-02-16 13:00:00 : 신동면   22850 ----------


 ---------- 2018-02-16 14:00:00 : 동내면   22851 ----------


 ---------- 2018-02-16 17:00:00 : 효자1동   22852 ----------


 ---------- 2018-02-16 21:00:00 : 퇴계동   22853 ----------


 ---------- 2018-02-17 00:00:00 : 후평1동   22854 ----------


 ---------- 2018-02-17 12:00:00 : 신사우동   22855 ----------


 ---------- 2018-02-17 12:00:00 : 후평1동   22856 ----------


 ---------- 2018-02-17 13:00:00 : 동내면   22857 ----------


 ---------- 2018-02-17 14:00:00 : 신동면   22858 ----------


 ---------- 2018-02-17 14:00:00 : 후평1동   22859 ----------


 ---------- 2018-02-17 16:00:00 : 퇴계동   22860 ----------


 ---------- 2018-02-17 19:00:00 : 신사우동   22861 ----------


 ---------- 2018-02-17 21:00:00 : 효자1동   22862 ----------


 ---------- 2018-02-18 09:00:00 : 동  면   22863 ----------


 ---------- 2018-02-18 17:00:00 : 소양동   22864 ----------


 ---------- 2018-02-19 10:00:00 : 서  면   22865 ----------


 ---------- 2018-02-19 13:00:00 : 퇴계동   22866 ----------


 ---------- 2018-02-19 14:00:00 : 동내면   22867 ----------


 ---------- 2018-02-19 14:00:00 : 효자1동   22868 ----------


 ---------- 2018-02-19 15:00:00 : 서  면   22869 ----------


 ---------- 2018-02-19 18:00:00 : 후평1동   22871 ----------


 ---------- 2018-02-19 18:00:00 : 퇴계동   22872 ----------


 ---------- 2018-02-19 21:00:00 : 신북읍   22873 ----------


 ---------- 2018-02-20 09:00:00 : 남산면   22874 ----------


 ---------- 2018-02-20 10:00:00 : 신북읍   22875 ----------


 ---------- 2018-02-20 10:00:00 : 후평1동   22876 ----------


 ---------- 2018-02-20 13:00:00 : 서  면   22877 ----------


 ---------- 2018-02-20 20:00:00 : 동내면   22879 ----------


 ---------- 2018-02-20 22:00:00 : 강남동   22880 ----------


 ---------- 2018-02-20 22:00:00 : 후평1동   22881 ----------


 ---------- 2018-02-21 01:00:00 : 신사우동   22882 ----------


 ---------- 2018-02-21 08:00:00 : 조운동   22883 ----------


 ---------- 2018-02-21 13:00:00 : 북산면   22884 ----------


 ---------- 2018-02-21 16:00:00 : 남산면   22886 ----------


 ---------- 2018-02-22 05:00:00 : 신북읍   22887 ----------


 ---------- 2018-02-22 10:00:00 : 퇴계동   22888 ----------


 ---------- 2018-02-22 20:00:00 : 소양동   22890 ----------


 ---------- 2018-02-23 14:00:00 : 신사우동   22891 ----------


 ---------- 2018-02-23 15:00:00 : 강남동   22893 ----------


 ---------- 2018-02-23 17:00:00 : 서  면   22895 ----------


 ---------- 2018-02-23 18:00:00 : 신북읍   22896 ----------


 ---------- 2018-02-24 04:00:00 : 후평1동   22897 ----------


 ---------- 2018-02-24 09:00:00 : 근화동   22898 ----------


 ---------- 2018-02-24 11:00:00 : 동내면   22899 ----------


 ---------- 2018-02-24 14:00:00 : 근화동   22900 ----------


 ---------- 2018-02-24 15:00:00 : 동내면   22901 ----------


 ---------- 2018-02-24 16:00:00 : 근화동   22902 ----------


 ---------- 2018-02-24 17:00:00 : 동  면   22903 ----------


 ---------- 2018-02-24 20:00:00 : 석사동   22905 ----------


 ---------- 2018-02-24 22:00:00 : 근화동   22906 ----------


 ---------- 2018-02-25 00:00:00 : 교  동   22908 ----------


 ---------- 2018-02-25 09:00:00 : 퇴계동   22909 ----------


 ---------- 2018-02-25 10:00:00 : 효자1동   22910 ----------


 ---------- 2018-02-25 12:00:00 : 서  면   22913 ----------


 ---------- 2018-02-25 13:00:00 : 서  면   22914 ----------


 ---------- 2018-02-25 18:00:00 : 약사명동   22915 ----------


 ---------- 2018-02-26 08:00:00 : 후평1동   22916 ----------


 ---------- 2018-02-26 09:00:00 : 남산면   22917 ----------


 ---------- 2018-02-26 12:00:00 : 조운동   22918 ----------


 ---------- 2018-02-26 20:00:00 : 동내면   22919 ----------


 ---------- 2018-02-26 21:00:00 : 강남동   22920 ----------


 ---------- 2018-02-27 07:00:00 : 신동면   22921 ----------


 ---------- 2018-02-27 09:00:00 : 약사명동   22922 ----------


 ---------- 2018-02-27 11:00:00 : 소양동   22923 ----------


 ---------- 2018-02-27 14:00:00 : 동내면   22924 ----------


 ---------- 2018-02-27 21:00:00 : 강남동   22925 ----------


 ---------- 2018-02-28 09:00:00 : 후평1동   22926 ----------


 ---------- 2018-02-28 10:00:00 : 후평1동   22927 ----------


 ---------- 2018-02-28 11:00:00 : 후평1동   22928 ----------


 ---------- 2018-02-28 13:00:00 : 동  면   22929 ----------


 ---------- 2018-02-28 14:00:00 : 효자1동   22931 ----------


 ---------- 2018-02-28 14:00:00 : 신북읍   22932 ----------


 ---------- 2018-02-28 15:00:00 : 후평1동   22934 ----------


 ---------- 2018-02-28 17:00:00 : 동내면   22936 ----------


 ---------- 2018-02-28 18:00:00 : 후평1동   22937 ----------


 ---------- 2018-02-28 19:00:00 : 북산면   22938 ----------


 ---------- 2018-03-01 05:00:00 : 근화동   22939 ----------


 ---------- 2018-03-01 13:00:00 : 동내면   22940 ----------


 ---------- 2018-03-01 15:00:00 : 후평1동   22941 ----------


 ---------- 2018-03-01 15:00:00 : 북산면   22942 ----------


 ---------- 2018-03-01 16:00:00 : 북산면   22943 ----------


 ---------- 2018-03-01 17:00:00 : 조운동   22945 ----------


 ---------- 2018-03-01 21:00:00 : 효자1동   22946 ----------


 ---------- 2018-03-02 15:00:00 : 후평1동   22947 ----------


 ---------- 2018-03-02 16:00:00 : 남  면   22950 ----------


 ---------- 2018-03-02 18:00:00 : 효자1동   22951 ----------


 ---------- 2018-03-02 19:00:00 : 후평1동   22952 ----------


 ---------- 2018-03-02 20:00:00 : 후평1동   22954 ----------


 ---------- 2018-03-03 02:00:00 : 남산면   22955 ----------


 ---------- 2018-03-03 09:00:00 : 동내면   22956 ----------


 ---------- 2018-03-03 16:00:00 : 사북면   22957 ----------


 ---------- 2018-03-03 23:00:00 : 강남동   22958 ----------


 ---------- 2018-03-04 03:00:00 : 효자1동   22959 ----------


 ---------- 2018-03-05 10:00:00 : 소양동   22960 ----------


 ---------- 2018-03-05 11:00:00 : 남산면   22961 ----------


 ---------- 2018-03-05 12:00:00 : 퇴계동   22962 ----------


 ---------- 2018-03-05 13:00:00 : 석사동   22963 ----------


 ---------- 2018-03-05 16:00:00 : 후평1동   22964 ----------


 ---------- 2018-03-06 13:00:00 : 남산면   22965 ----------

 ---------- 2018-03-06 17:00:00 : 교  동   22966 ----------


 ---------- 2018-03-06 18:00:00 : 효자1동   22967 ----------


 ---------- 2018-03-07 01:00:00 : 서  면   22970 ----------


 ---------- 2018-03-07 06:00:00 : 신북읍   22973 ----------


 ---------- 2018-03-07 07:00:00 : 신북읍   22974 ----------


 ---------- 2018-03-07 11:00:00 : 석사동   22975 ----------


 ---------- 2018-03-07 11:00:00 : 신사우동   22976 ----------


 ---------- 2018-03-07 14:00:00 : 효자1동   22977 ----------


 ---------- 2018-03-07 16:00:00 : 동  면   22978 ----------


 ---------- 2018-03-07 16:00:00 : 동산면   22979 ----------


 ---------- 2018-03-09 09:00:00 : 서  면   22981 ----------


 ---------- 2018-03-09 15:00:00 : 동내면   22982 ----------


 ---------- 2018-03-09 23:00:00 : 석사동   22984 ----------


 ---------- 2018-03-10 08:00:00 : 동내면   22985 ----------


 ---------- 2018-03-10 11:00:00 : 조운동   22986 ----------


 ---------- 2018-03-10 12:00:00 : 강남동   22988 ----------


 ---------- 2018-03-10 17:00:00 : 효자1동   22989 ----------


 ---------- 2018-03-10 18:00:00 : 신동면   22990 ----------


 ---------- 2018-03-10 20:00:00 : 남산면   22993 ----------


 ---------- 2018-03-11 06:00:00 : 석사동   22994 ----------


 ---------- 2018-03-11 14:00:00 : 신사우동   22995 ----------


 ---------- 2018-03-11 17:00:00 : 신북읍   22996 ----------


 ---------- 2018-03-11 20:00:00 : 신사우동   22997 ----------


 ---------- 2018-03-12 08:00:00 : 후평1동   22998 ----------


 ---------- 2018-03-12 17:00:00 : 동산면   22999 ----------


 ---------- 2018-03-12 19:00:00 : 동  면   23000 ----------


 ---------- 2018-03-13 07:00:00 : 동  면   23002 ----------


 ---------- 2018-03-13 09:00:00 : 동산면   23003 ----------


 ---------- 2018-03-13 10:00:00 : 신동면   23004 ----------


 ---------- 2018-03-13 16:00:00 : 소양동   23005 ----------


 ---------- 2018-03-14 00:00:00 : 석사동   23006 ----------


 ---------- 2018-03-14 02:00:00 : 석사동   23008 ----------


 ---------- 2018-03-14 07:00:00 : 석사동   23009 ----------


 ---------- 2018-03-15 00:00:00 : 신북읍   23010 ----------


 ---------- 2018-03-15 17:00:00 : 석사동   23011 ----------


 ---------- 2018-03-15 21:00:00 : 효자1동   23012 ----------


 ---------- 2018-03-15 21:00:00 : 후평1동   23013 ----------


 ---------- 2018-03-16 01:00:00 : 동내면   23015 ----------


 ---------- 2018-03-16 08:00:00 : 석사동   23016 ----------


 ---------- 2018-03-16 08:00:00 : 북산면   23019 ----------


 ---------- 2018-03-16 10:00:00 : 동내면   23020 ----------


 ---------- 2018-03-16 10:00:00 : 퇴계동   23021 ----------


 ---------- 2018-03-16 10:00:00 : 북산면   23022 ----------


 ---------- 2018-03-16 12:00:00 : 석사동   23023 ----------


 ---------- 2018-03-16 16:00:00 : 후평1동   23025 ----------


 ---------- 2018-03-16 17:00:00 : 퇴계동   23026 ----------


 ---------- 2018-03-17 09:00:00 : 사북면   23027 ----------


 ---------- 2018-03-17 10:00:00 : 후평1동   23028 ----------


 ---------- 2018-03-18 18:00:00 : 후평1동   23029 ----------


 ---------- 2018-03-19 08:00:00 : 효자1동   23030 ----------


 ---------- 2018-03-19 10:00:00 : 서  면   23031 ----------


 ---------- 2018-03-19 15:00:00 : 효자1동   23032 ----------


 ---------- 2018-03-19 17:00:00 : 소양동   23033 ----------


 ---------- 2018-03-19 23:00:00 : 신사우동   23034 ----------


 ---------- 2018-03-20 07:00:00 : 남  면   23036 ----------


 ---------- 2018-03-20 09:00:00 : 남산면   23037 ----------


 ---------- 2018-03-20 15:00:00 : 퇴계동   23038 ----------


 ---------- 2018-03-20 20:00:00 : 후평1동   23039 ----------


 ---------- 2018-03-21 20:00:00 : 서  면   23041 ----------


 ---------- 2018-03-22 13:00:00 : 남산면   23043 ----------


 ---------- 2018-03-22 13:00:00 : 근화동   23044 ----------


 ---------- 2018-03-22 13:00:00 : 신북읍   23045 ----------


 ---------- 2018-03-23 10:00:00 : 퇴계동   23046 ----------


 ---------- 2018-03-23 12:00:00 : 석사동   23047 ----------


 ---------- 2018-03-23 13:00:00 : 신북읍   23048 ----------


 ---------- 2018-03-23 14:00:00 : 강남동   23049 ----------


 ---------- 2018-03-24 11:00:00 : 남산면   23051 ----------


 ---------- 2018-03-24 21:00:00 : 퇴계동   23052 ----------


 ---------- 2018-03-25 01:00:00 : 강남동   23055 ----------


 ---------- 2018-03-25 02:00:00 : 후평1동   23057 ----------


 ---------- 2018-03-25 18:00:00 : 신사우동   23058 ----------


 ---------- 2018-03-25 20:00:00 : 후평1동   23059 ----------


 ---------- 2018-03-26 05:00:00 : 후평1동   23060 ----------


 ---------- 2018-03-26 10:00:00 : 후평1동   23061 ----------


 ---------- 2018-03-26 13:00:00 : 동내면   23062 ----------


 ---------- 2018-03-26 13:00:00 : 약사명동   23065 ----------


 ---------- 2018-03-26 19:00:00 : 신사우동   23066 ----------


 ---------- 2018-03-27 06:00:00 : 동내면   23067 ----------


 ---------- 2018-03-27 13:00:00 : 신북읍   23068 ----------


 ---------- 2018-03-27 14:00:00 : 남산면   23069 ----------


 ---------- 2018-03-28 04:00:00 : 석사동   23070 ----------


 ---------- 2018-03-28 06:00:00 : 신북읍   23072 ----------


 ---------- 2018-03-28 07:00:00 : 신북읍   23074 ----------


 ---------- 2018-03-28 15:00:00 : 사북면   23075 ----------


 ---------- 2018-03-28 20:00:00 : 근화동   23076 ----------


 ---------- 2018-03-28 21:00:00 : 근화동   23077 ----------


 ---------- 2018-03-29 13:00:00 : 신북읍   23078 ----------


 ---------- 2018-03-30 03:00:00 : 신사우동   23079 ----------


 ---------- 2018-03-30 08:00:00 : 동내면   23080 ----------


 ---------- 2018-03-30 16:00:00 : 동산면   23081 ----------


 ---------- 2018-03-30 17:00:00 : 강남동   23082 ----------


 ---------- 2018-03-30 18:00:00 : 북산면   23084 ----------


 ---------- 2018-03-30 19:00:00 : 신동면   23085 ----------


 ---------- 2018-03-30 22:00:00 : 효자1동   23086 ----------


 ---------- 2018-03-31 03:00:00 : 퇴계동   23087 ----------


 ---------- 2018-03-31 05:00:00 : 효자1동   23088 ----------


 ---------- 2018-03-31 06:00:00 : 동내면   23089 ----------


 ---------- 2018-03-31 10:00:00 : 서  면   23090 ----------


 ---------- 2018-03-31 15:00:00 : 사북면   23091 ----------


 ---------- 2018-03-31 17:00:00 : 근화동   23092 ----------


 ---------- 2018-03-31 20:00:00 : 후평1동   23093 ----------


 ---------- 2018-03-31 21:00:00 : 동  면   23094 ----------


 ---------- 2018-04-01 04:00:00 : 남산면   23096 ----------


 ---------- 2018-04-01 10:00:00 : 퇴계동   23098 ----------


 ---------- 2018-04-01 10:00:00 : 동산면   23099 ----------


 ---------- 2018-04-01 11:00:00 : 효자1동   23100 ----------


 ---------- 2018-04-01 11:00:00 : 신북읍   23103 ----------


 ---------- 2018-04-01 15:00:00 : 서  면   23104 ----------


 ---------- 2018-04-01 21:00:00 : 퇴계동   23105 ----------


 ---------- 2018-04-02 12:00:00 : 석사동   23107 ----------


 ---------- 2018-04-02 14:00:00 : 퇴계동   23108 ----------


 ---------- 2018-04-02 16:00:00 : 퇴계동   23109 ----------


 ---------- 2018-04-02 18:00:00 : 후평1동   23110 ----------


 ---------- 2018-04-03 04:00:00 : 후평1동   23111 ----------


 ---------- 2018-04-03 08:00:00 : 강남동   23112 ----------


 ---------- 2018-04-03 10:00:00 : 사북면   23113 ----------


 ---------- 2018-04-03 11:00:00 : 퇴계동   23114 ----------


 ---------- 2018-04-03 12:00:00 : 후평1동   23115 ----------


 ---------- 2018-04-03 13:00:00 : 동내면   23116 ----------


 ---------- 2018-04-03 15:00:00 : 후평1동   23117 ----------


 ---------- 2018-04-04 23:00:00 : 동  면   23119 ----------


 ---------- 2018-04-05 17:00:00 : 교  동   23120 ----------


 ---------- 2018-04-05 20:00:00 : 동내면   23121 ----------


 ---------- 2018-04-06 02:00:00 : 동내면   23122 ----------


 ---------- 2018-04-06 14:00:00 : 신동면   23123 ----------


 ---------- 2018-04-06 21:00:00 : 신사우동   23124 ----------


 ---------- 2018-04-06 21:00:00 : 퇴계동   23125 ----------


 ---------- 2018-04-06 22:00:00 : 소양동   23126 ----------


 ---------- 2018-04-07 03:00:00 : 소양동   23127 ----------


 ---------- 2018-04-07 07:00:00 : 남산면   23129 ----------


 ---------- 2018-04-07 12:00:00 : 남산면   23130 ----------


 ---------- 2018-04-07 14:00:00 : 신사우동   23131 ----------


 ---------- 2018-04-07 16:00:00 : 남산면   23132 ----------


 ---------- 2018-04-07 17:00:00 : 근화동   23133 ----------


 ---------- 2018-04-07 22:00:00 : 신사우동   23134 ----------


 ---------- 2018-04-08 08:00:00 : 동  면   23136 ----------

 ---------- 2018-04-08 09:00:00 : 사북면   23137 ----------


 ---------- 2018-04-08 09:00:00 : 신북읍   23138 ----------


 ---------- 2018-04-08 12:00:00 : 효자1동   23139 ----------


 ---------- 2018-04-08 15:00:00 : 서  면   23140 ----------


 ---------- 2018-04-08 16:00:00 : 신사우동   23141 ----------


 ---------- 2018-04-08 20:00:00 : 신북읍   23142 ----------


 ---------- 2018-04-08 22:00:00 : 동  면   23143 ----------


 ---------- 2018-04-09 05:00:00 : 효자1동   23144 ----------


 ---------- 2018-04-09 09:00:00 : 남산면   23146 ----------


 ---------- 2018-04-09 09:00:00 : 퇴계동   23147 ----------


 ---------- 2018-04-09 16:00:00 : 사북면   23148 ----------


 ---------- 2018-04-10 06:00:00 : 약사명동   23149 ----------


 ---------- 2018-04-10 10:00:00 : 퇴계동   23151 ----------


 ---------- 2018-04-10 12:00:00 : 서  면   23152 ----------


 ---------- 2018-04-10 13:00:00 : 신북읍   23153 ----------


 ---------- 2018-04-10 14:00:00 : 동  면   23154 ----------


 ---------- 2018-04-10 17:00:00 : 효자1동   23155 ----------


 ---------- 2018-04-10 17:00:00 : 동산면   23157 ----------


 ---------- 2018-04-10 19:00:00 : 석사동   23159 ----------


 ---------- 2018-04-11 04:00:00 : 퇴계동   23160 ----------


 ---------- 2018-04-11 17:00:00 : 동내면   23161 ----------


 ---------- 2018-04-11 20:00:00 : 효자1동   23162 ----------


 ---------- 2018-04-11 22:00:00 : 신북읍   23163 ----------


 ---------- 2018-04-12 05:00:00 : 약사명동   23164 ----------


 ---------- 2018-04-12 07:00:00 : 퇴계동   23165 ----------


 ---------- 2018-04-12 10:00:00 : 사북면   23166 ----------


 ---------- 2018-04-12 11:00:00 : 효자1동   23167 ----------


 ---------- 2018-04-12 12:00:00 : 서  면   23168 ----------


 ---------- 2018-04-12 14:00:00 : 남산면   23170 ----------


 ---------- 2018-04-13 05:00:00 : 남  면   23171 ----------


 ---------- 2018-04-13 06:00:00 : 동내면   23172 ----------


 ---------- 2018-04-13 12:00:00 : 동  면   23173 ----------


 ---------- 2018-04-13 13:00:00 : 동  면   23174 ----------


 ---------- 2018-04-13 19:00:00 : 효자1동   23175 ----------


 ---------- 2018-04-14 12:00:00 : 조운동   23176 ----------


 ---------- 2018-04-14 13:00:00 : 후평1동   23178 ----------


 ---------- 2018-04-15 00:00:00 : 신동면   23180 ----------


 ---------- 2018-04-15 11:00:00 : 동  면   23181 ----------


 ---------- 2018-04-15 13:00:00 : 퇴계동   23183 ----------


 ---------- 2018-04-15 21:00:00 : 동  면   23184 ----------


 ---------- 2018-04-16 07:00:00 : 동  면   23186 ----------


 ---------- 2018-04-16 11:00:00 : 동내면   23188 ----------


 ---------- 2018-04-16 11:00:00 : 동  면   23189 ----------


 ---------- 2018-04-16 13:00:00 : 근화동   23191 ----------


 ---------- 2018-04-16 14:00:00 : 조운동   23193 ----------


 ---------- 2018-04-16 17:00:00 : 조운동   23194 ----------


 ---------- 2018-04-16 23:00:00 : 강남동   23195 ----------


 ---------- 2018-04-17 00:00:00 : 석사동   23196 ----------


 ---------- 2018-04-17 00:00:00 : 남산면   23198 ----------


 ---------- 2018-04-17 06:00:00 : 남산면   23199 ----------


 ---------- 2018-04-17 07:00:00 : 후평1동   23200 ----------


 ---------- 2018-04-17 09:00:00 : 강남동   23201 ----------


 ---------- 2018-04-17 13:00:00 : 효자1동   23204 ----------


 ---------- 2018-04-17 17:00:00 : 신사우동   23205 ----------


 ---------- 2018-04-17 18:00:00 : 퇴계동   23206 ----------


 ---------- 2018-04-18 00:00:00 : 소양동   23207 ----------


 ---------- 2018-04-18 11:00:00 : 약사명동   23209 ----------


 ---------- 2018-04-18 13:00:00 : 효자1동   23210 ----------


 ---------- 2018-04-18 19:00:00 : 신북읍   23211 ----------


 ---------- 2018-04-18 21:00:00 : 퇴계동   23212 ----------


 ---------- 2018-04-19 02:00:00 : 석사동   23213 ----------


 ---------- 2018-04-19 06:00:00 : 신동면   23214 ----------


 ---------- 2018-04-19 12:00:00 : 근화동   23215 ----------


 ---------- 2018-04-19 13:00:00 : 퇴계동   23216 ----------


 ---------- 2018-04-19 18:00:00 : 동  면   23217 ----------


 ---------- 2018-04-19 19:00:00 : 근화동   23218 ----------


 ---------- 2018-04-19 20:00:00 : 퇴계동   23219 ----------


 ---------- 2018-04-19 23:00:00 : 신동면   23220 ----------


 ---------- 2018-04-20 11:00:00 : 동내면   23221 ----------


 ---------- 2018-04-20 11:00:00 : 신사우동   23224 ----------


 ---------- 2018-04-20 14:00:00 : 동내면   23225 ----------


 ---------- 2018-04-20 14:00:00 : 신북읍   23226 ----------


 ---------- 2018-04-20 21:00:00 : 신북읍   23227 ----------


 ---------- 2018-04-20 21:00:00 : 교  동   23228 ----------


 ---------- 2018-04-21 01:00:00 : 효자1동   23229 ----------


 ---------- 2018-04-21 09:00:00 : 서  면   23230 ----------


 ---------- 2018-04-21 10:00:00 : 효자1동   23231 ----------


 ---------- 2018-04-21 10:00:00 : 퇴계동   23232 ----------


 ---------- 2018-04-21 11:00:00 : 신사우동   23234 ----------


 ---------- 2018-04-21 11:00:00 : 신북읍   23235 ----------


 ---------- 2018-04-21 16:00:00 : 강남동   23236 ----------


 ---------- 2018-04-21 16:00:00 : 남  면   23237 ----------


 ---------- 2018-04-21 17:00:00 : 동  면   23238 ----------


 ---------- 2018-04-21 18:00:00 : 남  면   23240 ----------


 ---------- 2018-04-21 20:00:00 : 서  면   23241 ----------


 ---------- 2018-04-21 22:00:00 : 효자1동   23242 ----------


 ---------- 2018-04-21 23:00:00 : 남산면   23243 ----------


 ---------- 2018-04-22 09:00:00 : 동내면   23244 ----------


 ---------- 2018-04-22 12:00:00 : 북산면   23245 ----------


 ---------- 2018-04-22 17:00:00 : 서  면   23246 ----------


 ---------- 2018-04-22 18:00:00 : 강남동   23247 ----------


 ---------- 2018-04-23 08:00:00 : 동내면   23248 ----------


 ---------- 2018-04-23 09:00:00 : 석사동   23249 ----------


 ---------- 2018-04-23 11:00:00 : 후평1동   23250 ----------


 ---------- 2018-04-24 08:00:00 : 근화동   23252 ----------


 ---------- 2018-04-24 13:00:00 : 동산면   23253 ----------


 ---------- 2018-04-24 17:00:00 : 조운동   23254 ----------


 ---------- 2018-04-24 18:00:00 : 후평1동   23257 ----------


 ---------- 2018-04-25 11:00:00 : 신동면   23258 ----------


 ---------- 2018-04-25 13:00:00 : 서  면   23260 ----------


 ---------- 2018-04-25 14:00:00 : 서  면   23261 ----------


 ---------- 2018-04-25 15:00:00 : 강남동   23262 ----------


 ---------- 2018-04-25 16:00:00 : 서  면   23265 ----------


 ---------- 2018-04-25 16:00:00 : 소양동   23266 ----------


 ---------- 2018-04-25 19:00:00 : 동내면   23267 ----------


 ---------- 2018-04-25 22:00:00 : 동내면   23269 ----------


 ---------- 2018-04-26 01:00:00 : 퇴계동   23270 ----------


 ---------- 2018-04-26 05:00:00 : 근화동   23272 ----------


 ---------- 2018-04-26 09:00:00 : 사북면   23273 ----------


 ---------- 2018-04-26 14:00:00 : 서  면   23274 ----------


 ---------- 2018-04-27 11:00:00 : 신북읍   23275 ----------


 ---------- 2018-04-27 15:00:00 : 신사우동   23277 ----------


 ---------- 2018-04-27 17:00:00 : 서  면   23278 ----------


 ---------- 2018-04-27 17:00:00 : 동내면   23279 ----------


 ---------- 2018-04-27 17:00:00 : 근화동   23280 ----------


 ---------- 2018-04-27 23:00:00 : 소양동   23281 ----------


 ---------- 2018-04-28 08:00:00 : 신사우동   23282 ----------


 ---------- 2018-04-28 11:00:00 : 강남동   23284 ----------


 ---------- 2018-04-28 13:00:00 : 석사동   23286 ----------


 ---------- 2018-04-28 17:00:00 : 남  면   23289 ----------


 ---------- 2018-04-29 03:00:00 : 퇴계동   23291 ----------


 ---------- 2018-04-29 12:00:00 : 강남동   23292 ----------


 ---------- 2018-04-29 13:00:00 : 효자1동   23293 ----------


 ---------- 2018-04-29 14:00:00 : 조운동   23294 ----------


 ---------- 2018-04-29 19:00:00 : 동  면   23295 ----------


 ---------- 2018-04-30 10:00:00 : 후평1동   23296 ----------


 ---------- 2018-04-30 10:00:00 : 퇴계동   23298 ----------


 ---------- 2018-04-30 11:00:00 : 신동면   23299 ----------


 ---------- 2018-04-30 13:00:00 : 강남동   23300 ----------


 ---------- 2018-04-30 18:00:00 : 근화동   23301 ----------


 ---------- 2018-04-30 22:00:00 : 강남동   23303 ----------


 ---------- 2018-05-01 10:00:00 : 근화동   23305 ----------


 ---------- 2018-05-01 10:00:00 : 후평1동   23306 ----------


 ---------- 2018-05-01 16:00:00 : 퇴계동   23307 ----------


 ---------- 2018-05-01 17:00:00 : 후평1동   23308 ----------


 ---------- 2018-05-01 22:00:00 : 신사우동   23309 ----------

 ---------- 2018-05-01 23:00:00 : 사북면   23310 ----------


 ---------- 2018-05-02 01:00:00 : 남산면   23311 ----------


 ---------- 2018-05-02 04:00:00 : 후평1동   23312 ----------


 ---------- 2018-05-02 06:00:00 : 퇴계동   23315 ----------


 ---------- 2018-05-02 08:00:00 : 신사우동   23316 ----------


 ---------- 2018-05-02 17:00:00 : 동  면   23317 ----------


 ---------- 2018-05-03 09:00:00 : 소양동   23319 ----------


 ---------- 2018-05-03 10:00:00 : 후평1동   23320 ----------


 ---------- 2018-05-03 12:00:00 : 효자1동   23321 ----------


 ---------- 2018-05-03 15:00:00 : 북산면   23322 ----------


 ---------- 2018-05-03 18:00:00 : 동  면   23323 ----------


 ---------- 2018-05-04 00:00:00 : 서  면   23324 ----------


 ---------- 2018-05-04 02:00:00 : 퇴계동   23325 ----------


 ---------- 2018-05-04 10:00:00 : 강남동   23326 ----------


 ---------- 2018-05-04 10:00:00 : 서  면   23328 ----------


 ---------- 2018-05-04 14:00:00 : 신북읍   23329 ----------


 ---------- 2018-05-04 16:00:00 : 서  면   23330 ----------


 ---------- 2018-05-04 23:00:00 : 후평1동   23331 ----------


 ---------- 2018-05-05 08:00:00 : 근화동   23332 ----------


 ---------- 2018-05-05 14:00:00 : 퇴계동   23334 ----------


 ---------- 2018-05-05 15:00:00 : 남산면   23335 ----------


 ---------- 2018-05-05 16:00:00 : 후평1동   23336 ----------


 ---------- 2018-05-05 17:00:00 : 효자1동   23338 ----------


 ---------- 2018-05-05 19:00:00 : 효자1동   23340 ----------


 ---------- 2018-05-06 07:00:00 : 효자1동   23342 ----------


 ---------- 2018-05-06 08:00:00 : 효자1동   23345 ----------


 ---------- 2018-05-06 10:00:00 : 퇴계동   23346 ----------


 ---------- 2018-05-06 13:00:00 : 동  면   23347 ----------


 ---------- 2018-05-06 13:00:00 : 퇴계동   23348 ----------


 ---------- 2018-05-06 15:00:00 : 후평1동   23349 ----------


 ---------- 2018-05-06 17:00:00 : 퇴계동   23350 ----------


 ---------- 2018-05-06 18:00:00 : 석사동   23351 ----------


 ---------- 2018-05-07 00:00:00 : 후평1동   23352 ----------


 ---------- 2018-05-07 05:00:00 : 퇴계동   23354 ----------


 ---------- 2018-05-07 07:00:00 : 석사동   23356 ----------


 ---------- 2018-05-07 09:00:00 : 신북읍   23357 ----------


 ---------- 2018-05-07 10:00:00 : 남  면   23360 ----------


 ---------- 2018-05-07 12:00:00 : 퇴계동   23361 ----------


 ---------- 2018-05-08 03:00:00 : 신북읍   23362 ----------


 ---------- 2018-05-08 13:00:00 : 후평1동   23363 ----------


 ---------- 2018-05-08 14:00:00 : 석사동   23364 ----------


 ---------- 2018-05-09 09:00:00 : 동내면   23365 ----------


 ---------- 2018-05-09 14:00:00 : 후평1동   23366 ----------


 ---------- 2018-05-09 17:00:00 : 효자1동   23367 ----------


 ---------- 2018-05-09 19:00:00 : 후평1동   23368 ----------


 ---------- 2018-05-09 21:00:00 : 근화동   23370 ----------


 ---------- 2018-05-10 13:00:00 : 퇴계동   23371 ----------


 ---------- 2018-05-10 14:00:00 : 신북읍   23372 ----------


 ---------- 2018-05-10 17:00:00 : 신동면   23373 ----------


 ---------- 2018-05-11 09:00:00 : 남  면   23374 ----------


 ---------- 2018-05-11 10:00:00 : 퇴계동   23375 ----------


 ---------- 2018-05-11 16:00:00 : 퇴계동   23376 ----------


 ---------- 2018-05-11 17:00:00 : 동  면   23377 ----------


 ---------- 2018-05-11 19:00:00 : 동  면   23378 ----------


 ---------- 2018-05-11 21:00:00 : 석사동   23379 ----------


 ---------- 2018-05-11 22:00:00 : 후평1동   23380 ----------


 ---------- 2018-05-12 08:00:00 : 동내면   23381 ----------


 ---------- 2018-05-12 15:00:00 : 퇴계동   23382 ----------


 ---------- 2018-05-12 18:00:00 : 동  면   23383 ----------


 ---------- 2018-05-13 05:00:00 : 신사우동   23384 ----------


 ---------- 2018-05-13 13:00:00 : 신동면   23385 ----------


 ---------- 2018-05-13 13:00:00 : 신사우동   23386 ----------


 ---------- 2018-05-13 16:00:00 : 강남동   23388 ----------


 ---------- 2018-05-14 06:00:00 : 후평1동   23389 ----------


 ---------- 2018-05-14 09:00:00 : 남  면   23391 ----------


 ---------- 2018-05-14 10:00:00 : 퇴계동   23392 ----------


 ---------- 2018-05-14 11:00:00 : 효자1동   23394 ----------


 ---------- 2018-05-14 13:00:00 : 후평1동   23395 ----------


 ---------- 2018-05-14 20:00:00 : 북산면   23397 ----------


 ---------- 2018-05-15 10:00:00 : 동산면   23398 ----------


 ---------- 2018-05-15 16:00:00 : 신사우동   23399 ----------


 ---------- 2018-05-16 00:00:00 : 동  면   23401 ----------


 ---------- 2018-05-16 08:00:00 : 신사우동   23402 ----------


 ---------- 2018-05-16 08:00:00 : 신북읍   23403 ----------


 ---------- 2018-05-16 12:00:00 : 사북면   23404 ----------


 ---------- 2018-05-17 03:00:00 : 후평1동   23405 ----------


 ---------- 2018-05-17 04:00:00 : 강남동   23406 ----------


 ---------- 2018-05-17 04:00:00 : 퇴계동   23408 ----------


 ---------- 2018-05-17 08:00:00 : 약사명동   23409 ----------


 ---------- 2018-05-17 10:00:00 : 퇴계동   23410 ----------


 ---------- 2018-05-17 12:00:00 : 동내면   23411 ----------


 ---------- 2018-05-17 14:00:00 : 동  면   23412 ----------


 ---------- 2018-05-17 20:00:00 : 남산면   23414 ----------


 ---------- 2018-05-17 20:00:00 : 후평1동   23415 ----------


 ---------- 2018-05-17 20:00:00 : 퇴계동   23417 ----------


 ---------- 2018-05-18 09:00:00 : 근화동   23419 ----------


 ---------- 2018-05-18 10:00:00 : 근화동   23420 ----------


 ---------- 2018-05-18 11:00:00 : 후평1동   23421 ----------


 ---------- 2018-05-18 17:00:00 : 퇴계동   23422 ----------


 ---------- 2018-05-18 18:00:00 : 퇴계동   23423 ----------


 ---------- 2018-05-19 00:00:00 : 석사동   23424 ----------


 ---------- 2018-05-19 04:00:00 : 후평1동   23425 ----------


 ---------- 2018-05-19 11:00:00 : 신사우동   23426 ----------


 ---------- 2018-05-19 14:00:00 : 후평1동   23427 ----------


 ---------- 2018-05-19 17:00:00 : 석사동   23428 ----------


 ---------- 2018-05-19 18:00:00 : 근화동   23429 ----------


 ---------- 2018-05-20 03:00:00 : 강남동   23431 ----------


 ---------- 2018-05-20 15:00:00 : 동내면   23432 ----------


 ---------- 2018-05-20 18:00:00 : 약사명동   23434 ----------


 ---------- 2018-05-21 01:00:00 : 효자1동   23436 ----------


 ---------- 2018-05-21 07:00:00 : 석사동   23437 ----------


 ---------- 2018-05-21 08:00:00 : 효자1동   23439 ----------


 ---------- 2018-05-21 10:00:00 : 후평1동   23440 ----------


 ---------- 2018-05-21 14:00:00 : 남  면   23442 ----------


 ---------- 2018-05-21 15:00:00 : 남산면   23443 ----------


 ---------- 2018-05-21 20:00:00 : 퇴계동   23445 ----------


 ---------- 2018-05-22 00:00:00 : 동내면   23446 ----------


 ---------- 2018-05-22 03:00:00 : 근화동   23448 ----------


 ---------- 2018-05-22 09:00:00 : 신북읍   23449 ----------


 ---------- 2018-05-22 11:00:00 : 후평1동   23450 ----------


 ---------- 2018-05-22 17:00:00 : 소양동   23451 ----------


 ---------- 2018-05-22 20:00:00 : 후평1동   23452 ----------


 ---------- 2018-05-22 21:00:00 : 동  면   23453 ----------


 ---------- 2018-05-23 03:00:00 : 서  면   23455 ----------


 ---------- 2018-05-23 08:00:00 : 강남동   23456 ----------


 ---------- 2018-05-23 14:00:00 : 약사명동   23457 ----------


 ---------- 2018-05-23 18:00:00 : 사북면   23458 ----------


 ---------- 2018-05-23 18:00:00 : 북산면   23459 ----------


 ---------- 2018-05-23 19:00:00 : 후평1동   23460 ----------


 ---------- 2018-05-23 21:00:00 : 효자1동   23461 ----------


 ---------- 2018-05-23 21:00:00 : 신사우동   23462 ----------


 ---------- 2018-05-23 22:00:00 : 효자1동   23464 ----------


 ---------- 2018-05-23 23:00:00 : 강남동   23465 ----------


 ---------- 2018-05-23 23:00:00 : 후평1동   23466 ----------


 ---------- 2018-05-24 07:00:00 : 신북읍   23467 ----------


 ---------- 2018-05-24 09:00:00 : 후평1동   23468 ----------


 ---------- 2018-05-24 23:00:00 : 효자1동   23469 ----------


 ---------- 2018-05-25 07:00:00 : 약사명동   23470 ----------


 ---------- 2018-05-25 09:00:00 : 약사명동   23471 ----------


 ---------- 2018-05-25 18:00:00 : 사북면   23472 ----------


 ---------- 2018-05-25 19:00:00 : 퇴계동   23473 ----------


 ---------- 2018-05-26 00:00:00 : 후평1동   23474 ----------


 ---------- 2018-05-26 07:00:00 : 서  면   23475 ----------


 ---------- 2018-05-26 11:00:00 : 서  면   23477 ----------


 ---------- 2018-05-26 14:00:00 : 서  면   23478 ----------


 ---------- 2018-05-27 00:00:00 : 조운동   23480 ----------


 ---------- 2018-05-27 01:00:00 : 서  면   23481 ----------

 ---------- 2018-05-27 13:00:00 : 퇴계동   23482 ----------


 ---------- 2018-05-27 17:00:00 : 퇴계동   23484 ----------


 ---------- 2018-05-27 18:00:00 : 퇴계동   23485 ----------


 ---------- 2018-05-27 20:00:00 : 동  면   23486 ----------


 ---------- 2018-05-28 00:00:00 : 강남동   23488 ----------


 ---------- 2018-05-28 11:00:00 : 신사우동   23489 ----------


 ---------- 2018-05-28 11:00:00 : 교  동   23490 ----------


 ---------- 2018-05-28 12:00:00 : 소양동   23492 ----------


 ---------- 2018-05-28 15:00:00 : 북산면   23495 ----------


 ---------- 2018-05-28 16:00:00 : 효자1동   23500 ----------


 ---------- 2018-05-28 18:00:00 : 후평1동   23501 ----------


 ---------- 2018-05-28 20:00:00 : 서  면   23502 ----------


 ---------- 2018-05-28 20:00:00 : 효자1동   23504 ----------


 ---------- 2018-05-29 14:00:00 : 소양동   23505 ----------


 ---------- 2018-05-29 15:00:00 : 후평1동   23506 ----------


 ---------- 2018-05-30 00:00:00 : 동  면   23507 ----------


 ---------- 2018-05-30 06:00:00 : 서  면   23509 ----------


 ---------- 2018-05-30 10:00:00 : 석사동   23511 ----------


 ---------- 2018-05-30 10:00:00 : 남산면   23512 ----------


 ---------- 2018-05-30 12:00:00 : 신사우동   23513 ----------


 ---------- 2018-05-30 15:00:00 : 동  면   23514 ----------


 ---------- 2018-05-30 17:00:00 : 동산면   23515 ----------


 ---------- 2018-05-30 18:00:00 : 서  면   23517 ----------


 ---------- 2018-05-30 22:00:00 : 후평1동   23518 ----------


 ---------- 2018-05-31 08:00:00 : 강남동   23519 ----------


 ---------- 2018-05-31 10:00:00 : 약사명동   23521 ----------


 ---------- 2018-05-31 11:00:00 : 후평1동   23522 ----------


 ---------- 2018-05-31 13:00:00 : 근화동   23523 ----------


 ---------- 2018-05-31 18:00:00 : 서  면   23524 ----------


 ---------- 2018-06-01 03:00:00 : 동  면   23525 ----------


 ---------- 2018-06-01 07:00:00 : 약사명동   23527 ----------


 ---------- 2018-06-01 07:00:00 : 동  면   23528 ----------


 ---------- 2018-06-01 12:00:00 : 신사우동   23529 ----------


 ---------- 2018-06-01 13:00:00 : 서  면   23530 ----------


 ---------- 2018-06-01 14:00:00 : 사북면   23531 ----------


 ---------- 2018-06-01 19:00:00 : 신동면   23532 ----------


 ---------- 2018-06-01 19:00:00 : 사북면   23533 ----------


 ---------- 2018-06-01 20:00:00 : 소양동   23534 ----------


 ---------- 2018-06-02 10:00:00 : 동  면   23535 ----------


 ---------- 2018-06-02 11:00:00 : 약사명동   23537 ----------


 ---------- 2018-06-02 12:00:00 : 동  면   23538 ----------


 ---------- 2018-06-02 13:00:00 : 동  면   23539 ----------


 ---------- 2018-06-02 14:00:00 : 북산면   23540 ----------


 ---------- 2018-06-02 15:00:00 : 석사동   23541 ----------


 ---------- 2018-06-02 15:00:00 : 북산면   23542 ----------


 ---------- 2018-06-02 15:00:00 : 교  동   23543 ----------


 ---------- 2018-06-02 16:00:00 : 퇴계동   23544 ----------


 ---------- 2018-06-02 17:00:00 : 신동면   23545 ----------


 ---------- 2018-06-02 17:00:00 : 동  면   23546 ----------


 ---------- 2018-06-02 23:00:00 : 효자1동   23548 ----------


 ---------- 2018-06-02 23:00:00 : 동  면   23551 ----------


 ---------- 2018-06-03 07:00:00 : 남산면   23553 ----------


 ---------- 2018-06-03 10:00:00 : 북산면   23555 ----------


 ---------- 2018-06-03 16:00:00 : 동  면   23556 ----------


 ---------- 2018-06-03 18:00:00 : 후평1동   23557 ----------


 ---------- 2018-06-03 19:00:00 : 소양동   23559 ----------


 ---------- 2018-06-04 02:00:00 : 강남동   23560 ----------


 ---------- 2018-06-04 09:00:00 : 소양동   23561 ----------


 ---------- 2018-06-04 13:00:00 : 남산면   23562 ----------


 ---------- 2018-06-04 14:00:00 : 후평1동   23563 ----------


 ---------- 2018-06-04 15:00:00 : 교  동   23564 ----------


 ---------- 2018-06-04 17:00:00 : 석사동   23565 ----------


 ---------- 2018-06-04 19:00:00 : 신사우동   23567 ----------


 ---------- 2018-06-04 23:00:00 : 동  면   23568 ----------


 ---------- 2018-06-05 00:00:00 : 석사동   23570 ----------


 ---------- 2018-06-05 05:00:00 : 효자1동   23571 ----------


 ---------- 2018-06-05 12:00:00 : 퇴계동   23572 ----------


 ---------- 2018-06-05 17:00:00 : 석사동   23573 ----------


 ---------- 2018-06-05 20:00:00 : 동  면   23575 ----------


 ---------- 2018-06-05 20:00:00 : 교  동   23576 ----------


 ---------- 2018-06-05 21:00:00 : 후평1동   23577 ----------


 ---------- 2018-06-06 01:00:00 : 강남동   23578 ----------


 ---------- 2018-06-06 04:00:00 : 강남동   23579 ----------


 ---------- 2018-06-06 09:00:00 : 동  면   23580 ----------


 ---------- 2018-06-06 09:00:00 : 퇴계동   23581 ----------


 ---------- 2018-06-06 10:00:00 : 남산면   23582 ----------


 ---------- 2018-06-06 11:00:00 : 강남동   23583 ----------


 ---------- 2018-06-06 11:00:00 : 남산면   23584 ----------


 ---------- 2018-06-06 14:00:00 : 강남동   23585 ----------


 ---------- 2018-06-06 15:00:00 : 효자1동   23586 ----------


 ---------- 2018-06-06 17:00:00 : 효자1동   23587 ----------


 ---------- 2018-06-06 19:00:00 : 동내면   23588 ----------


 ---------- 2018-06-07 06:00:00 : 동내면   23589 ----------


 ---------- 2018-06-07 06:00:00 : 효자1동   23591 ----------


 ---------- 2018-06-07 08:00:00 : 남산면   23593 ----------


 ---------- 2018-06-07 09:00:00 : 신동면   23594 ----------


 ---------- 2018-06-07 12:00:00 : 남산면   23595 ----------


 ---------- 2018-06-07 13:00:00 : 서  면   23597 ----------


 ---------- 2018-06-07 15:00:00 : 퇴계동   23599 ----------


 ---------- 2018-06-08 06:00:00 : 서  면   23600 ----------


 ---------- 2018-06-09 01:00:00 : 교  동   23601 ----------


 ---------- 2018-06-09 15:00:00 : 사북면   23602 ----------


 ---------- 2018-06-10 03:00:00 : 남산면   23603 ----------


 ---------- 2018-06-10 09:00:00 : 약사명동   23604 ----------


 ---------- 2018-06-10 10:00:00 : 남산면   23607 ----------


 ---------- 2018-06-10 13:00:00 : 서  면   23608 ----------


 ---------- 2018-06-10 15:00:00 : 동  면   23609 ----------


 ---------- 2018-06-10 17:00:00 : 남산면   23612 ----------


 ---------- 2018-06-10 20:00:00 : 신사우동   23613 ----------


 ---------- 2018-06-10 20:00:00 : 퇴계동   23615 ----------


 ---------- 2018-06-11 05:00:00 : 서  면   23616 ----------


 ---------- 2018-06-11 08:00:00 : 근화동   23618 ----------


 ---------- 2018-06-11 11:00:00 : 효자1동   23619 ----------


 ---------- 2018-06-11 14:00:00 : 퇴계동   23620 ----------


 ---------- 2018-06-11 17:00:00 : 효자1동   23621 ----------


 ---------- 2018-06-11 18:00:00 : 석사동   23622 ----------


 ---------- 2018-06-11 21:00:00 : 신동면   23623 ----------


 ---------- 2018-06-11 21:00:00 : 사북면   23624 ----------


 ---------- 2018-06-11 22:00:00 : 효자1동   23625 ----------


 ---------- 2018-06-12 08:00:00 : 동  면   23626 ----------


 ---------- 2018-06-12 18:00:00 : 석사동   23627 ----------


 ---------- 2018-06-12 18:00:00 : 근화동   23628 ----------


 ---------- 2018-06-12 19:00:00 : 신사우동   23629 ----------


 ---------- 2018-06-12 23:00:00 : 동내면   23630 ----------


 ---------- 2018-06-13 09:00:00 : 퇴계동   23631 ----------


 ---------- 2018-06-13 10:00:00 : 근화동   23632 ----------


 ---------- 2018-06-13 12:00:00 : 동내면   23633 ----------


 ---------- 2018-06-13 13:00:00 : 남산면   23634 ----------


 ---------- 2018-06-13 15:00:00 : 신북읍   23635 ----------


 ---------- 2018-06-13 16:00:00 : 남  면   23636 ----------


 ---------- 2018-06-13 18:00:00 : 동내면   23637 ----------


 ---------- 2018-06-13 18:00:00 : 효자1동   23639 ----------


 ---------- 2018-06-13 21:00:00 : 남산면   23640 ----------


 ---------- 2018-06-13 22:00:00 : 효자1동   23642 ----------


 ---------- 2018-06-13 23:00:00 : 근화동   23643 ----------


 ---------- 2018-06-14 16:00:00 : 신사우동   23644 ----------


 ---------- 2018-06-14 17:00:00 : 남산면   23645 ----------


 ---------- 2018-06-14 17:00:00 : 소양동   23646 ----------


 ---------- 2018-06-14 19:00:00 : 소양동   23647 ----------


 ---------- 2018-06-14 20:00:00 : 강남동   23648 ----------


 ---------- 2018-06-14 22:00:00 : 남산면   23649 ----------


 ---------- 2018-06-14 23:00:00 : 근화동   23650 ----------


 ---------- 2018-06-15 06:00:00 : 퇴계동   23651 ----------


 ---------- 2018-06-15 16:00:00 : 남산면   23652 ----------


 ---------- 2018-06-15 17:00:00 : 후평1동   23653 ----------


 ---------- 2018-06-15 20:00:00 : 후평1동   23654 ----------

 ---------- 2018-06-15 21:00:00 : 효자1동   23655 ----------


 ---------- 2018-06-16 09:00:00 : 동산면   23656 ----------


 ---------- 2018-06-16 13:00:00 : 남산면   23659 ----------


 ---------- 2018-06-16 13:00:00 : 동  면   23660 ----------


 ---------- 2018-06-16 14:00:00 : 동  면   23661 ----------


 ---------- 2018-06-16 16:00:00 : 남산면   23663 ----------


 ---------- 2018-06-16 18:00:00 : 소양동   23664 ----------


 ---------- 2018-06-16 21:00:00 : 효자1동   23665 ----------


 ---------- 2018-06-16 22:00:00 : 강남동   23667 ----------


 ---------- 2018-06-17 00:00:00 : 신북읍   23668 ----------


 ---------- 2018-06-17 01:00:00 : 동  면   23669 ----------


 ---------- 2018-06-17 09:00:00 : 신북읍   23670 ----------


 ---------- 2018-06-17 10:00:00 : 소양동   23671 ----------


 ---------- 2018-06-17 11:00:00 : 효자1동   23672 ----------


 ---------- 2018-06-17 13:00:00 : 서  면   23673 ----------


 ---------- 2018-06-17 14:00:00 : 퇴계동   23674 ----------


 ---------- 2018-06-17 16:00:00 : 후평1동   23675 ----------


 ---------- 2018-06-17 22:00:00 : 강남동   23676 ----------


 ---------- 2018-06-18 10:00:00 : 근화동   23678 ----------


 ---------- 2018-06-18 12:00:00 : 남  면   23681 ----------


 ---------- 2018-06-18 13:00:00 : 동  면   23682 ----------


 ---------- 2018-06-18 15:00:00 : 동내면   23683 ----------


 ---------- 2018-06-18 15:00:00 : 퇴계동   23684 ----------


 ---------- 2018-06-18 16:00:00 : 강남동   23685 ----------


 ---------- 2018-06-19 06:00:00 : 서  면   23686 ----------


 ---------- 2018-06-19 07:00:00 : 서  면   23687 ----------


 ---------- 2018-06-19 09:00:00 : 신북읍   23688 ----------


 ---------- 2018-06-19 12:00:00 : 후평1동   23689 ----------


 ---------- 2018-06-19 13:00:00 : 신사우동   23690 ----------


 ---------- 2018-06-19 14:00:00 : 사북면   23691 ----------


 ---------- 2018-06-19 14:00:00 : 퇴계동   23692 ----------


 ---------- 2018-06-19 16:00:00 : 사북면   23693 ----------


 ---------- 2018-06-19 19:00:00 : 남  면   23694 ----------


 ---------- 2018-06-19 21:00:00 : 효자1동   23696 ----------


 ---------- 2018-06-19 23:00:00 : 효자1동   23697 ----------


 ---------- 2018-06-20 06:00:00 : 신동면   23699 ----------


 ---------- 2018-06-20 08:00:00 : 동  면   23700 ----------


 ---------- 2018-06-20 09:00:00 : 석사동   23701 ----------


 ---------- 2018-06-20 10:00:00 : 후평1동   23702 ----------


 ---------- 2018-06-20 11:00:00 : 신동면   23703 ----------


 ---------- 2018-06-20 15:00:00 : 신사우동   23704 ----------


 ---------- 2018-06-20 15:00:00 : 동  면   23705 ----------


 ---------- 2018-06-20 16:00:00 : 신사우동   23706 ----------


 ---------- 2018-06-20 16:00:00 : 소양동   23707 ----------


 ---------- 2018-06-20 23:00:00 : 조운동   23709 ----------


 ---------- 2018-06-21 09:00:00 : 근화동   23710 ----------


 ---------- 2018-06-21 09:00:00 : 후평1동   23711 ----------


 ---------- 2018-06-21 10:00:00 : 강남동   23712 ----------


 ---------- 2018-06-21 11:00:00 : 후평1동   23713 ----------


 ---------- 2018-06-21 13:00:00 : 남산면   23714 ----------


 ---------- 2018-06-21 13:00:00 : 소양동   23715 ----------


 ---------- 2018-06-21 13:00:00 : 후평1동   23717 ----------


 ---------- 2018-06-21 16:00:00 : 강남동   23718 ----------


 ---------- 2018-06-21 22:00:00 : 동산면   23719 ----------


 ---------- 2018-06-22 06:00:00 : 석사동   23720 ----------


 ---------- 2018-06-22 07:00:00 : 석사동   23721 ----------


 ---------- 2018-06-22 10:00:00 : 신북읍   23722 ----------


 ---------- 2018-06-22 10:00:00 : 약사명동   23723 ----------


 ---------- 2018-06-22 13:00:00 : 효자1동   23724 ----------


 ---------- 2018-06-22 13:00:00 : 동  면   23725 ----------


 ---------- 2018-06-22 17:00:00 : 서  면   23726 ----------


 ---------- 2018-06-22 18:00:00 : 동내면   23729 ----------


 ---------- 2018-06-22 18:00:00 : 효자1동   23731 ----------


 ---------- 2018-06-22 19:00:00 : 효자1동   23732 ----------


 ---------- 2018-06-22 21:00:00 : 동내면   23733 ----------


 ---------- 2018-06-22 21:00:00 : 신북읍   23735 ----------


 ---------- 2018-06-22 23:00:00 : 신사우동   23736 ----------


 ---------- 2018-06-22 23:00:00 : 신북읍   23737 ----------


 ---------- 2018-06-22 23:00:00 : 퇴계동   23738 ----------


 ---------- 2018-06-23 07:00:00 : 퇴계동   23739 ----------


 ---------- 2018-06-23 10:00:00 : 효자1동   23740 ----------


 ---------- 2018-06-23 11:00:00 : 동  면   23741 ----------


 ---------- 2018-06-23 13:00:00 : 서  면   23742 ----------


 ---------- 2018-06-23 15:00:00 : 신동면   23744 ----------


 ---------- 2018-06-23 16:00:00 : 강남동   23745 ----------


 ---------- 2018-06-23 17:00:00 : 석사동   23746 ----------


 ---------- 2018-06-23 19:00:00 : 근화동   23747 ----------


 ---------- 2018-06-24 07:00:00 : 퇴계동   23749 ----------


 ---------- 2018-06-24 09:00:00 : 석사동   23750 ----------


 ---------- 2018-06-24 10:00:00 : 신사우동   23751 ----------


 ---------- 2018-06-24 14:00:00 : 신북읍   23752 ----------


 ---------- 2018-06-24 15:00:00 : 서  면   23754 ----------


 ---------- 2018-06-24 19:00:00 : 동내면   23755 ----------


 ---------- 2018-06-24 20:00:00 : 효자1동   23756 ----------


 ---------- 2018-06-24 21:00:00 : 동내면   23757 ----------


 ---------- 2018-06-24 22:00:00 : 신사우동   23758 ----------


 ---------- 2018-06-24 23:00:00 : 남  면   23760 ----------


 ---------- 2018-06-25 02:00:00 : 석사동   23761 ----------


 ---------- 2018-06-25 10:00:00 : 석사동   23762 ----------


 ---------- 2018-06-25 10:00:00 : 동내면   23763 ----------


 ---------- 2018-06-25 16:00:00 : 교  동   23764 ----------


 ---------- 2018-06-25 20:00:00 : 소양동   23765 ----------


 ---------- 2018-06-25 21:00:00 : 효자1동   23766 ----------


 ---------- 2018-06-25 23:00:00 : 소양동   23767 ----------


 ---------- 2018-06-26 01:00:00 : 석사동   23768 ----------


 ---------- 2018-06-26 09:00:00 : 동산면   23769 ----------


 ---------- 2018-06-26 11:00:00 : 후평1동   23770 ----------


 ---------- 2018-06-26 20:00:00 : 북산면   23772 ----------


 ---------- 2018-06-26 21:00:00 : 신북읍   23773 ----------


 ---------- 2018-06-26 21:00:00 : 퇴계동   23774 ----------


 ---------- 2018-06-27 04:00:00 : 동내면   23775 ----------


 ---------- 2018-06-27 06:00:00 : 사북면   23776 ----------


 ---------- 2018-06-27 11:00:00 : 동내면   23777 ----------


 ---------- 2018-06-27 14:00:00 : 남  면   23778 ----------


 ---------- 2018-06-27 14:00:00 : 소양동   23779 ----------


 ---------- 2018-06-27 15:00:00 : 근화동   23780 ----------


 ---------- 2018-06-27 18:00:00 : 퇴계동   23781 ----------


 ---------- 2018-06-27 19:00:00 : 후평1동   23782 ----------


 ---------- 2018-06-27 21:00:00 : 효자1동   23784 ----------


 ---------- 2018-06-28 10:00:00 : 남산면   23785 ----------


 ---------- 2018-06-28 10:00:00 : 신사우동   23786 ----------


 ---------- 2018-06-28 10:00:00 : 소양동   23787 ----------


 ---------- 2018-06-28 11:00:00 : 강남동   23789 ----------


 ---------- 2018-06-28 14:00:00 : 강남동   23790 ----------


 ---------- 2018-06-28 15:00:00 : 강남동   23792 ----------


 ---------- 2018-06-28 15:00:00 : 남산면   23795 ----------


 ---------- 2018-06-28 15:00:00 : 후평1동   23796 ----------


 ---------- 2018-06-28 16:00:00 : 서  면   23797 ----------


 ---------- 2018-06-28 16:00:00 : 신사우동   23798 ----------


 ---------- 2018-06-28 17:00:00 : 신사우동   23799 ----------


 ---------- 2018-06-28 18:00:00 : 강남동   23801 ----------


 ---------- 2018-06-28 18:00:00 : 서  면   23802 ----------


 ---------- 2018-06-28 20:00:00 : 석사동   23804 ----------


 ---------- 2018-06-28 20:00:00 : 신북읍   23805 ----------


 ---------- 2018-06-28 21:00:00 : 서  면   23807 ----------


 ---------- 2018-06-28 22:00:00 : 남산면   23809 ----------


 ---------- 2018-06-29 01:00:00 : 북산면   23810 ----------


 ---------- 2018-06-29 02:00:00 : 북산면   23811 ----------


 ---------- 2018-06-29 03:00:00 : 퇴계동   23812 ----------


 ---------- 2018-06-29 04:00:00 : 신동면   23813 ----------


 ---------- 2018-06-29 04:00:00 : 남  면   23815 ----------


 ---------- 2018-06-29 05:00:00 : 서  면   23816 ----------


 ---------- 2018-06-29 07:00:00 : 동내면   23817 ----------


 ---------- 2018-06-29 09:00:00 : 근화동   23818 ----------


 ---------- 2018-06-29 18:00:00 : 동  면   23819 ----------


 ---------- 2018-06-29 21:00:00 : 강남동   23820 ----------

 ---------- 2018-06-30 02:00:00 : 효자1동   23821 ----------


 ---------- 2018-06-30 07:00:00 : 약사명동   23822 ----------


 ---------- 2018-06-30 07:00:00 : 퇴계동   23823 ----------


 ---------- 2018-06-30 08:00:00 : 석사동   23824 ----------


 ---------- 2018-06-30 09:00:00 : 동  면   23825 ----------


 ---------- 2018-06-30 09:00:00 : 후평1동   23826 ----------


 ---------- 2018-06-30 12:00:00 : 강남동   23828 ----------


 ---------- 2018-06-30 14:00:00 : 석사동   23829 ----------


 ---------- 2018-06-30 15:00:00 : 남  면   23832 ----------


 ---------- 2018-06-30 15:00:00 : 신북읍   23833 ----------


 ---------- 2018-06-30 18:00:00 : 효자1동   23834 ----------


 ---------- 2018-06-30 18:00:00 : 신사우동   23836 ----------


 ---------- 2018-06-30 23:00:00 : 남산면   23837 ----------


 ---------- 2018-07-01 01:00:00 : 동내면   23838 ----------


 ---------- 2018-07-01 07:00:00 : 동내면   23839 ----------


 ---------- 2018-07-01 08:00:00 : 신북읍   23840 ----------


 ---------- 2018-07-01 09:00:00 : 석사동   23841 ----------


 ---------- 2018-07-01 10:00:00 : 동내면   23842 ----------


 ---------- 2018-07-01 11:00:00 : 동내면   23843 ----------


 ---------- 2018-07-01 11:00:00 : 신북읍   23844 ----------


 ---------- 2018-07-01 11:00:00 : 동산면   23849 ----------


 ---------- 2018-07-01 15:00:00 : 신동면   23850 ----------


 ---------- 2018-07-01 17:00:00 : 남  면   23851 ----------


 ---------- 2018-07-01 21:00:00 : 퇴계동   23853 ----------


 ---------- 2018-07-02 05:00:00 : 동내면   23855 ----------


 ---------- 2018-07-02 07:00:00 : 동내면   23856 ----------


 ---------- 2018-07-02 08:00:00 : 신동면   23858 ----------


 ---------- 2018-07-02 09:00:00 : 동내면   23859 ----------


 ---------- 2018-07-02 10:00:00 : 근화동   23860 ----------


 ---------- 2018-07-02 12:00:00 : 신사우동   23861 ----------


 ---------- 2018-07-02 15:00:00 : 남산면   23863 ----------


 ---------- 2018-07-02 20:00:00 : 근화동   23865 ----------


 ---------- 2018-07-02 23:00:00 : 강남동   23867 ----------


 ---------- 2018-07-03 06:00:00 : 사북면   23868 ----------


 ---------- 2018-07-03 06:00:00 : 동내면   23869 ----------


 ---------- 2018-07-03 06:00:00 : 효자1동   23870 ----------


 ---------- 2018-07-03 08:00:00 : 동내면   23871 ----------


 ---------- 2018-07-03 08:00:00 : 후평1동   23872 ----------


 ---------- 2018-07-03 09:00:00 : 동내면   23873 ----------


 ---------- 2018-07-03 09:00:00 : 신북읍   23874 ----------


 ---------- 2018-07-03 10:00:00 : 효자1동   23876 ----------


 ---------- 2018-07-03 13:00:00 : 신동면   23877 ----------


 ---------- 2018-07-03 13:00:00 : 동내면   23878 ----------


 ---------- 2018-07-03 13:00:00 : 동산면   23879 ----------


 ---------- 2018-07-03 14:00:00 : 퇴계동   23880 ----------


 ---------- 2018-07-03 14:00:00 : 동산면   23881 ----------


 ---------- 2018-07-03 16:00:00 : 남산면   23882 ----------


 ---------- 2018-07-03 17:00:00 : 강남동   23883 ----------


 ---------- 2018-07-03 18:00:00 : 강남동   23884 ----------


 ---------- 2018-07-03 18:00:00 : 퇴계동   23885 ----------


 ---------- 2018-07-03 19:00:00 : 후평1동   23886 ----------


 ---------- 2018-07-03 20:00:00 : 신북읍   23887 ----------


 ---------- 2018-07-04 03:00:00 : 신북읍   23888 ----------


 ---------- 2018-07-04 06:00:00 : 동내면   23889 ----------


 ---------- 2018-07-04 07:00:00 : 석사동   23891 ----------


 ---------- 2018-07-04 08:00:00 : 사북면   23892 ----------


 ---------- 2018-07-04 08:00:00 : 동내면   23895 ----------


 ---------- 2018-07-04 09:00:00 : 효자1동   23896 ----------


 ---------- 2018-07-04 10:00:00 : 신북읍   23897 ----------


 ---------- 2018-07-04 10:00:00 : 퇴계동   23898 ----------


 ---------- 2018-07-04 11:00:00 : 효자1동   23900 ----------


 ---------- 2018-07-04 13:00:00 : 효자1동   23901 ----------


 ---------- 2018-07-04 14:00:00 : 동내면   23902 ----------


 ---------- 2018-07-04 15:00:00 : 신북읍   23903 ----------


 ---------- 2018-07-04 16:00:00 : 교  동   23904 ----------


 ---------- 2018-07-04 17:00:00 : 석사동   23905 ----------


 ---------- 2018-07-04 17:00:00 : 효자1동   23906 ----------


 ---------- 2018-07-04 17:00:00 : 동산면   23907 ----------


 ---------- 2018-07-04 23:00:00 : 후평1동   23908 ----------


 ---------- 2018-07-05 00:00:00 : 후평1동   23909 ----------


 ---------- 2018-07-05 06:00:00 : 신사우동   23910 ----------


 ---------- 2018-07-05 07:00:00 : 퇴계동   23911 ----------


 ---------- 2018-07-05 08:00:00 : 서  면   23912 ----------


 ---------- 2018-07-05 09:00:00 : 동내면   23913 ----------


 ---------- 2018-07-05 10:00:00 : 강남동   23914 ----------


 ---------- 2018-07-05 11:00:00 : 석사동   23915 ----------


 ---------- 2018-07-05 11:00:00 : 남산면   23916 ----------


 ---------- 2018-07-05 17:00:00 : 남산면   23917 ----------


 ---------- 2018-07-05 17:00:00 : 후평1동   23919 ----------


 ---------- 2018-07-05 18:00:00 : 후평1동   23920 ----------


 ---------- 2018-07-05 20:00:00 : 신사우동   23923 ----------


 ---------- 2018-07-05 20:00:00 : 후평1동   23924 ----------


 ---------- 2018-07-05 23:00:00 : 소양동   23926 ----------


 ---------- 2018-07-06 01:00:00 : 효자1동   23927 ----------


 ---------- 2018-07-06 08:00:00 : 동내면   23928 ----------


 ---------- 2018-07-06 08:00:00 : 동  면   23929 ----------


 ---------- 2018-07-06 09:00:00 : 서  면   23932 ----------


 ---------- 2018-07-06 09:00:00 : 동내면   23934 ----------


 ---------- 2018-07-06 12:00:00 : 동  면   23935 ----------


 ---------- 2018-07-06 19:00:00 : 근화동   23936 ----------


 ---------- 2018-07-06 22:00:00 : 후평1동   23937 ----------


 ---------- 2018-07-07 07:00:00 : 퇴계동   23938 ----------


 ---------- 2018-07-07 09:00:00 : 동내면   23939 ----------


 ---------- 2018-07-07 09:00:00 : 효자1동   23940 ----------


 ---------- 2018-07-07 09:00:00 : 근화동   23942 ----------


 ---------- 2018-07-07 10:00:00 : 강남동   23943 ----------


 ---------- 2018-07-07 10:00:00 : 사북면   23944 ----------


 ---------- 2018-07-07 11:00:00 : 석사동   23945 ----------


 ---------- 2018-07-07 12:00:00 : 남산면   23947 ----------


 ---------- 2018-07-07 13:00:00 : 강남동   23948 ----------


 ---------- 2018-07-07 13:00:00 : 서  면   23949 ----------


 ---------- 2018-07-07 14:00:00 : 강남동   23950 ----------


 ---------- 2018-07-07 16:00:00 : 서  면   23951 ----------


 ---------- 2018-07-07 18:00:00 : 남  면   23952 ----------


 ---------- 2018-07-07 18:00:00 : 남산면   23956 ----------


 ---------- 2018-07-07 18:00:00 : 신사우동   23957 ----------


 ---------- 2018-07-07 21:00:00 : 조운동   23958 ----------


 ---------- 2018-07-08 05:00:00 : 서  면   23959 ----------


 ---------- 2018-07-08 07:00:00 : 근화동   23961 ----------


 ---------- 2018-07-08 08:00:00 : 퇴계동   23962 ----------


 ---------- 2018-07-08 10:00:00 : 동내면   23963 ----------


 ---------- 2018-07-08 10:00:00 : 동  면   23964 ----------


 ---------- 2018-07-08 11:00:00 : 사북면   23965 ----------


 ---------- 2018-07-08 13:00:00 : 석사동   23966 ----------


 ---------- 2018-07-08 15:00:00 : 동내면   23967 ----------


 ---------- 2018-07-08 16:00:00 : 강남동   23968 ----------


 ---------- 2018-07-08 16:00:00 : 사북면   23969 ----------


 ---------- 2018-07-08 16:00:00 : 후평1동   23970 ----------


 ---------- 2018-07-08 17:00:00 : 강남동   23971 ----------


 ---------- 2018-07-08 19:00:00 : 신북읍   23972 ----------


 ---------- 2018-07-09 07:00:00 : 후평1동   23973 ----------


 ---------- 2018-07-09 08:00:00 : 후평1동   23974 ----------


 ---------- 2018-07-09 09:00:00 : 효자1동   23976 ----------


 ---------- 2018-07-09 09:00:00 : 후평1동   23977 ----------


 ---------- 2018-07-09 10:00:00 : 남산면   23978 ----------


 ---------- 2018-07-09 21:00:00 : 동내면   23981 ----------


 ---------- 2018-07-09 22:00:00 : 석사동   23982 ----------


 ---------- 2018-07-10 07:00:00 : 석사동   23985 ----------


 ---------- 2018-07-10 10:00:00 : 근화동   23986 ----------


 ---------- 2018-07-10 10:00:00 : 동  면   23987 ----------


 ---------- 2018-07-10 17:00:00 : 남산면   23988 ----------


 ---------- 2018-07-10 19:00:00 : 퇴계동   23989 ----------


 ---------- 2018-07-10 20:00:00 : 북산면   23990 ----------


 ---------- 2018-07-10 23:00:00 : 석사동   23991 ----------


 ---------- 2018-07-11 07:00:00 : 퇴계동   23992 ----------


 ---------- 2018-07-11 10:00:00 : 효자1동   23994 ----------

 ---------- 2018-07-11 12:00:00 : 근화동   23995 ----------


 ---------- 2018-07-11 13:00:00 : 석사동   23996 ----------


 ---------- 2018-07-11 16:00:00 : 동  면   23997 ----------


 ---------- 2018-07-11 18:00:00 : 퇴계동   23998 ----------


 ---------- 2018-07-11 21:00:00 : 효자1동   23999 ----------


 ---------- 2018-07-12 06:00:00 : 퇴계동   24000 ----------


 ---------- 2018-07-12 08:00:00 : 남산면   24001 ----------


 ---------- 2018-07-12 09:00:00 : 신동면   24002 ----------


 ---------- 2018-07-12 09:00:00 : 근화동   24003 ----------


 ---------- 2018-07-12 11:00:00 : 석사동   24004 ----------


 ---------- 2018-07-12 12:00:00 : 신북읍   24007 ----------


 ---------- 2018-07-12 13:00:00 : 남  면   24008 ----------


 ---------- 2018-07-12 17:00:00 : 신사우동   24009 ----------


 ---------- 2018-07-12 18:00:00 : 강남동   24010 ----------


 ---------- 2018-07-12 20:00:00 : 소양동   24011 ----------


 ---------- 2018-07-12 23:00:00 : 근화동   24012 ----------


 ---------- 2018-07-12 23:00:00 : 북산면   24013 ----------


 ---------- 2018-07-13 00:00:00 : 동내면   24015 ----------


 ---------- 2018-07-13 07:00:00 : 근화동   24016 ----------


 ---------- 2018-07-13 07:00:00 : 퇴계동   24017 ----------


 ---------- 2018-07-13 09:00:00 : 근화동   24018 ----------


 ---------- 2018-07-13 10:00:00 : 남산면   24019 ----------


 ---------- 2018-07-13 11:00:00 : 퇴계동   24020 ----------


 ---------- 2018-07-13 14:00:00 : 석사동   24021 ----------


 ---------- 2018-07-13 15:00:00 : 북산면   24022 ----------


 ---------- 2018-07-13 16:00:00 : 사북면   24023 ----------


 ---------- 2018-07-13 16:00:00 : 남산면   24024 ----------


 ---------- 2018-07-13 16:00:00 : 근화동   24025 ----------


 ---------- 2018-07-13 16:00:00 : 소양동   24026 ----------


 ---------- 2018-07-13 16:00:00 : 동  면   24027 ----------


 ---------- 2018-07-13 16:00:00 : 후평1동   24028 ----------


 ---------- 2018-07-13 17:00:00 : 남산면   24030 ----------


 ---------- 2018-07-13 19:00:00 : 효자1동   24031 ----------


 ---------- 2018-07-13 21:00:00 : 교  동   24032 ----------


 ---------- 2018-07-13 22:00:00 : 효자1동   24034 ----------


 ---------- 2018-07-13 22:00:00 : 후평1동   24035 ----------


 ---------- 2018-07-13 22:00:00 : 교  동   24036 ----------


 ---------- 2018-07-14 08:00:00 : 남  면   24037 ----------


 ---------- 2018-07-14 09:00:00 : 남  면   24039 ----------


 ---------- 2018-07-14 09:00:00 : 후평1동   24040 ----------


 ---------- 2018-07-14 10:00:00 : 후평1동   24041 ----------


 ---------- 2018-07-14 14:00:00 : 동산면   24043 ----------


 ---------- 2018-07-14 16:00:00 : 석사동   24044 ----------


 ---------- 2018-07-14 16:00:00 : 서  면   24045 ----------


 ---------- 2018-07-14 16:00:00 : 동  면   24046 ----------


 ---------- 2018-07-14 18:00:00 : 서  면   24047 ----------


 ---------- 2018-07-14 18:00:00 : 후평1동   24048 ----------


 ---------- 2018-07-14 19:00:00 : 효자1동   24049 ----------


 ---------- 2018-07-14 20:00:00 : 석사동   24050 ----------


 ---------- 2018-07-14 21:00:00 : 남산면   24052 ----------


 ---------- 2018-07-15 05:00:00 : 사북면   24053 ----------


 ---------- 2018-07-15 07:00:00 : 남산면   24054 ----------


 ---------- 2018-07-15 07:00:00 : 퇴계동   24055 ----------


 ---------- 2018-07-15 08:00:00 : 북산면   24056 ----------


 ---------- 2018-07-15 09:00:00 : 효자1동   24057 ----------


 ---------- 2018-07-15 09:00:00 : 남산면   24058 ----------


 ---------- 2018-07-15 10:00:00 : 남산면   24062 ----------


 ---------- 2018-07-15 14:00:00 : 동내면   24063 ----------


 ---------- 2018-07-15 14:00:00 : 신북읍   24064 ----------


 ---------- 2018-07-15 15:00:00 : 사북면   24065 ----------


 ---------- 2018-07-15 18:00:00 : 조운동   24066 ----------


 ---------- 2018-07-15 19:00:00 : 동산면   24067 ----------


 ---------- 2018-07-16 00:00:00 : 석사동   24068 ----------


 ---------- 2018-07-16 02:00:00 : 사북면   24070 ----------


 ---------- 2018-07-16 02:00:00 : 퇴계동   24071 ----------


 ---------- 2018-07-16 08:00:00 : 동  면   24072 ----------


 ---------- 2018-07-16 09:00:00 : 강남동   24074 ----------


 ---------- 2018-07-16 09:00:00 : 근화동   24075 ----------


 ---------- 2018-07-16 13:00:00 : 신동면   24076 ----------


 ---------- 2018-07-16 13:00:00 : 서  면   24077 ----------


 ---------- 2018-07-16 13:00:00 : 효자1동   24078 ----------


 ---------- 2018-07-16 13:00:00 : 근화동   24079 ----------


 ---------- 2018-07-16 14:00:00 : 동  면   24080 ----------


 ---------- 2018-07-16 15:00:00 : 신북읍   24081 ----------


 ---------- 2018-07-16 17:00:00 : 강남동   24082 ----------


 ---------- 2018-07-16 17:00:00 : 동  면   24084 ----------


 ---------- 2018-07-16 17:00:00 : 퇴계동   24085 ----------


 ---------- 2018-07-16 18:00:00 : 석사동   24086 ----------


 ---------- 2018-07-16 19:00:00 : 석사동   24087 ----------


 ---------- 2018-07-16 20:00:00 : 조운동   24089 ----------


 ---------- 2018-07-16 21:00:00 : 조운동   24091 ----------


 ---------- 2018-07-16 22:00:00 : 동  면   24092 ----------


 ---------- 2018-07-16 23:00:00 : 후평1동   24093 ----------


 ---------- 2018-07-17 06:00:00 : 동내면   24095 ----------


 ---------- 2018-07-17 09:00:00 : 동  면   24096 ----------


 ---------- 2018-07-17 12:00:00 : 효자1동   24097 ----------


 ---------- 2018-07-17 13:00:00 : 동내면   24098 ----------


 ---------- 2018-07-17 13:00:00 : 효자1동   24101 ----------


 ---------- 2018-07-17 13:00:00 : 동  면   24103 ----------


 ---------- 2018-07-17 14:00:00 : 소양동   24104 ----------


 ---------- 2018-07-17 14:00:00 : 후평1동   24105 ----------


 ---------- 2018-07-17 16:00:00 : 효자1동   24107 ----------


 ---------- 2018-07-17 19:00:00 : 남산면   24108 ----------


 ---------- 2018-07-17 19:00:00 : 동  면   24109 ----------


 ---------- 2018-07-17 22:00:00 : 강남동   24110 ----------


 ---------- 2018-07-18 07:00:00 : 동  면   24111 ----------


 ---------- 2018-07-18 07:00:00 : 동산면   24112 ----------


 ---------- 2018-07-18 09:00:00 : 신동면   24113 ----------


 ---------- 2018-07-18 09:00:00 : 신사우동   24114 ----------


 ---------- 2018-07-18 09:00:00 : 동  면   24115 ----------


 ---------- 2018-07-18 09:00:00 : 동산면   24116 ----------


 ---------- 2018-07-18 10:00:00 : 동  면   24117 ----------


 ---------- 2018-07-18 10:00:00 : 퇴계동   24118 ----------


 ---------- 2018-07-18 11:00:00 : 소양동   24119 ----------


 ---------- 2018-07-18 11:00:00 : 후평1동   24120 ----------


 ---------- 2018-07-18 12:00:00 : 동내면   24121 ----------


 ---------- 2018-07-18 12:00:00 : 후평1동   24122 ----------


 ---------- 2018-07-18 15:00:00 : 서  면   24124 ----------


 ---------- 2018-07-18 15:00:00 : 동  면   24125 ----------


 ---------- 2018-07-18 15:00:00 : 후평1동   24126 ----------


 ---------- 2018-07-18 16:00:00 : 후평1동   24127 ----------


 ---------- 2018-07-18 20:00:00 : 효자1동   24128 ----------


 ---------- 2018-07-18 20:00:00 : 동  면   24129 ----------


 ---------- 2018-07-18 23:00:00 : 효자1동   24130 ----------


 ---------- 2018-07-19 03:00:00 : 효자1동   24131 ----------


 ---------- 2018-07-19 06:00:00 : 교  동   24134 ----------


 ---------- 2018-07-19 07:00:00 : 남산면   24135 ----------


 ---------- 2018-07-19 08:00:00 : 남산면   24137 ----------


 ---------- 2018-07-19 08:00:00 : 신사우동   24138 ----------


 ---------- 2018-07-19 08:00:00 : 동  면   24139 ----------


 ---------- 2018-07-19 08:00:00 : 퇴계동   24140 ----------


 ---------- 2018-07-19 09:00:00 : 동내면   24141 ----------


 ---------- 2018-07-19 09:00:00 : 남산면   24142 ----------


 ---------- 2018-07-19 12:00:00 : 동  면   24143 ----------


 ---------- 2018-07-19 13:00:00 : 강남동   24144 ----------


 ---------- 2018-07-19 13:00:00 : 서  면   24145 ----------


 ---------- 2018-07-19 13:00:00 : 사북면   24146 ----------


 ---------- 2018-07-19 14:00:00 : 강남동   24147 ----------


 ---------- 2018-07-19 15:00:00 : 효자1동   24148 ----------


 ---------- 2018-07-19 16:00:00 : 석사동   24149 ----------


 ---------- 2018-07-19 16:00:00 : 동  면   24150 ----------


 ---------- 2018-07-19 17:00:00 : 신동면   24151 ----------


 ---------- 2018-07-19 18:00:00 : 서  면   24154 ----------


 ---------- 2018-07-19 18:00:00 : 신북읍   24155 ----------


 ---------- 2018-07-19 18:00:00 : 퇴계동   24156 ----------


 ---------- 2018-07-19 21:00:00 : 퇴계동   24157 ----------

 ---------- 2018-07-20 00:00:00 : 효자1동   24159 ----------


 ---------- 2018-07-20 06:00:00 : 석사동   24160 ----------


 ---------- 2018-07-20 06:00:00 : 신북읍   24162 ----------


 ---------- 2018-07-20 07:00:00 : 신사우동   24163 ----------


 ---------- 2018-07-20 08:00:00 : 강남동   24164 ----------


 ---------- 2018-07-20 08:00:00 : 남산면   24165 ----------


 ---------- 2018-07-20 08:00:00 : 북산면   24167 ----------


 ---------- 2018-07-20 09:00:00 : 효자1동   24168 ----------


 ---------- 2018-07-20 09:00:00 : 후평1동   24169 ----------


 ---------- 2018-07-20 11:00:00 : 동  면   24170 ----------


 ---------- 2018-07-20 12:00:00 : 석사동   24171 ----------


 ---------- 2018-07-20 12:00:00 : 퇴계동   24172 ----------


 ---------- 2018-07-20 13:00:00 : 후평1동   24174 ----------


 ---------- 2018-07-20 14:00:00 : 동내면   24175 ----------


 ---------- 2018-07-20 14:00:00 : 후평1동   24176 ----------


 ---------- 2018-07-20 16:00:00 : 동내면   24177 ----------


 ---------- 2018-07-20 17:00:00 : 사북면   24178 ----------


 ---------- 2018-07-20 17:00:00 : 동내면   24179 ----------


 ---------- 2018-07-20 18:00:00 : 동  면   24180 ----------


 ---------- 2018-07-20 19:00:00 : 강남동   24181 ----------


 ---------- 2018-07-20 23:00:00 : 강남동   24182 ----------


 ---------- 2018-07-21 00:00:00 : 강남동   24183 ----------


 ---------- 2018-07-21 06:00:00 : 신사우동   24185 ----------


 ---------- 2018-07-21 07:00:00 : 남산면   24186 ----------


 ---------- 2018-07-21 09:00:00 : 강남동   24187 ----------


 ---------- 2018-07-21 10:00:00 : 근화동   24188 ----------


 ---------- 2018-07-21 11:00:00 : 신동면   24189 ----------


 ---------- 2018-07-21 11:00:00 : 동  면   24190 ----------


 ---------- 2018-07-21 13:00:00 : 동  면   24191 ----------


 ---------- 2018-07-21 14:00:00 : 강남동   24192 ----------


 ---------- 2018-07-21 14:00:00 : 서  면   24194 ----------


 ---------- 2018-07-21 14:00:00 : 신북읍   24195 ----------


 ---------- 2018-07-21 14:00:00 : 동  면   24196 ----------


 ---------- 2018-07-21 15:00:00 : 서  면   24198 ----------


 ---------- 2018-07-21 15:00:00 : 동내면   24199 ----------


 ---------- 2018-07-21 15:00:00 : 동  면   24200 ----------


 ---------- 2018-07-21 15:00:00 : 퇴계동   24201 ----------


 ---------- 2018-07-21 16:00:00 : 강남동   24202 ----------


 ---------- 2018-07-21 18:00:00 : 강남동   24204 ----------


 ---------- 2018-07-21 18:00:00 : 남  면   24205 ----------


 ---------- 2018-07-21 19:00:00 : 사북면   24206 ----------


 ---------- 2018-07-21 20:00:00 : 동내면   24207 ----------


 ---------- 2018-07-21 22:00:00 : 남산면   24210 ----------


 ---------- 2018-07-22 00:00:00 : 사북면   24211 ----------


 ---------- 2018-07-22 00:00:00 : 후평1동   24212 ----------


 ---------- 2018-07-22 01:00:00 : 후평1동   24213 ----------


 ---------- 2018-07-22 05:00:00 : 강남동   24214 ----------


 ---------- 2018-07-22 09:00:00 : 서  면   24215 ----------


 ---------- 2018-07-22 09:00:00 : 사북면   24216 ----------


 ---------- 2018-07-22 11:00:00 : 동  면   24217 ----------


 ---------- 2018-07-22 13:00:00 : 근화동   24218 ----------


 ---------- 2018-07-22 14:00:00 : 사북면   24219 ----------


 ---------- 2018-07-22 14:00:00 : 효자1동   24220 ----------


 ---------- 2018-07-22 14:00:00 : 동  면   24221 ----------


 ---------- 2018-07-22 15:00:00 : 서  면   24223 ----------


 ---------- 2018-07-22 15:00:00 : 남  면   24224 ----------


 ---------- 2018-07-22 15:00:00 : 남산면   24225 ----------


 ---------- 2018-07-22 17:00:00 : 동  면   24226 ----------


 ---------- 2018-07-23 07:00:00 : 남산면   24227 ----------


 ---------- 2018-07-23 07:00:00 : 퇴계동   24228 ----------


 ---------- 2018-07-23 08:00:00 : 신사우동   24230 ----------


 ---------- 2018-07-23 08:00:00 : 후평1동   24231 ----------


 ---------- 2018-07-23 09:00:00 : 동내면   24233 ----------


 ---------- 2018-07-23 09:00:00 : 근화동   24234 ----------


 ---------- 2018-07-23 10:00:00 : 동내면   24235 ----------


 ---------- 2018-07-23 10:00:00 : 신북읍   24236 ----------


 ---------- 2018-07-23 10:00:00 : 퇴계동   24237 ----------


 ---------- 2018-07-23 11:00:00 : 신북읍   24238 ----------


 ---------- 2018-07-23 11:00:00 : 후평1동   24239 ----------


 ---------- 2018-07-23 12:00:00 : 강남동   24240 ----------


 ---------- 2018-07-23 12:00:00 : 동내면   24241 ----------


 ---------- 2018-07-23 12:00:00 : 퇴계동   24242 ----------


 ---------- 2018-07-23 13:00:00 : 남산면   24243 ----------


 ---------- 2018-07-23 13:00:00 : 동  면   24246 ----------


 ---------- 2018-07-23 14:00:00 : 동내면   24247 ----------


 ---------- 2018-07-23 14:00:00 : 신북읍   24248 ----------


 ---------- 2018-07-23 15:00:00 : 퇴계동   24249 ----------


 ---------- 2018-07-23 16:00:00 : 남  면   24250 ----------


 ---------- 2018-07-23 18:00:00 : 사북면   24251 ----------


 ---------- 2018-07-23 18:00:00 : 후평1동   24252 ----------


 ---------- 2018-07-23 18:00:00 : 동산면   24253 ----------


 ---------- 2018-07-23 19:00:00 : 동내면   24254 ----------


 ---------- 2018-07-24 06:00:00 : 서  면   24255 ----------


 ---------- 2018-07-24 07:00:00 : 동  면   24257 ----------


 ---------- 2018-07-24 08:00:00 : 남  면   24258 ----------


 ---------- 2018-07-24 08:00:00 : 소양동   24259 ----------


 ---------- 2018-07-24 09:00:00 : 신동면   24260 ----------


 ---------- 2018-07-24 09:00:00 : 서  면   24261 ----------


 ---------- 2018-07-24 09:00:00 : 남  면   24262 ----------


 ---------- 2018-07-24 10:00:00 : 신동면   24263 ----------


 ---------- 2018-07-24 10:00:00 : 사북면   24264 ----------


 ---------- 2018-07-24 10:00:00 : 동내면   24265 ----------


 ---------- 2018-07-24 11:00:00 : 남산면   24266 ----------


 ---------- 2018-07-24 12:00:00 : 근화동   24267 ----------


 ---------- 2018-07-24 12:00:00 : 후평1동   24268 ----------


 ---------- 2018-07-24 13:00:00 : 신사우동   24269 ----------


 ---------- 2018-07-24 14:00:00 : 석사동   24272 ----------


 ---------- 2018-07-24 15:00:00 : 근화동   24273 ----------


 ---------- 2018-07-24 16:00:00 : 남산면   24274 ----------


 ---------- 2018-07-24 16:00:00 : 동  면   24275 ----------


 ---------- 2018-07-24 16:00:00 : 후평1동   24276 ----------


 ---------- 2018-07-24 16:00:00 : 퇴계동   24278 ----------


 ---------- 2018-07-24 17:00:00 : 석사동   24280 ----------


 ---------- 2018-07-24 17:00:00 : 신북읍   24281 ----------


 ---------- 2018-07-24 18:00:00 : 남  면   24282 ----------


 ---------- 2018-07-24 18:00:00 : 소양동   24283 ----------


 ---------- 2018-07-24 18:00:00 : 후평1동   24284 ----------


 ---------- 2018-07-24 19:00:00 : 동  면   24285 ----------


 ---------- 2018-07-24 21:00:00 : 후평1동   24286 ----------


 ---------- 2018-07-24 22:00:00 : 신사우동   24288 ----------


 ---------- 2018-07-25 03:00:00 : 동내면   24289 ----------


 ---------- 2018-07-25 05:00:00 : 강남동   24292 ----------


 ---------- 2018-07-25 07:00:00 : 후평1동   24293 ----------


 ---------- 2018-07-25 09:00:00 : 강남동   24294 ----------


 ---------- 2018-07-25 09:00:00 : 효자1동   24295 ----------


 ---------- 2018-07-25 09:00:00 : 남산면   24296 ----------


 ---------- 2018-07-25 10:00:00 : 서  면   24297 ----------


 ---------- 2018-07-25 10:00:00 : 남산면   24298 ----------


 ---------- 2018-07-25 10:00:00 : 후평1동   24299 ----------


 ---------- 2018-07-25 10:00:00 : 퇴계동   24300 ----------


 ---------- 2018-07-25 11:00:00 : 서  면   24301 ----------


 ---------- 2018-07-25 11:00:00 : 사북면   24302 ----------


 ---------- 2018-07-25 12:00:00 : 신동면   24303 ----------


 ---------- 2018-07-25 12:00:00 : 강남동   24304 ----------


 ---------- 2018-07-25 12:00:00 : 근화동   24306 ----------


 ---------- 2018-07-25 12:00:00 : 후평1동   24307 ----------


 ---------- 2018-07-25 13:00:00 : 동  면   24308 ----------


 ---------- 2018-07-25 14:00:00 : 석사동   24310 ----------


 ---------- 2018-07-25 14:00:00 : 신동면   24311 ----------


 ---------- 2018-07-25 18:00:00 : 신동면   24312 ----------


 ---------- 2018-07-25 19:00:00 : 석사동   24313 ----------


 ---------- 2018-07-26 06:00:00 : 동산면   24315 ----------


 ---------- 2018-07-26 07:00:00 : 신북읍   24316 ----------


 ---------- 2018-07-26 07:00:00 : 동  면   24317 ----------


 ---------- 2018-07-26 09:00:00 : 사북면   24318 ----------


 ---------- 2018-07-26 09:00:00 : 신북읍   24319 ----------

 ---------- 2018-07-26 09:00:00 : 동  면   24320 ----------


 ---------- 2018-07-26 10:00:00 : 석사동   24321 ----------


 ---------- 2018-07-26 10:00:00 : 강남동   24323 ----------


 ---------- 2018-07-26 10:00:00 : 서  면   24324 ----------


 ---------- 2018-07-26 10:00:00 : 신북읍   24325 ----------


 ---------- 2018-07-26 11:00:00 : 사북면   24326 ----------


 ---------- 2018-07-26 13:00:00 : 근화동   24328 ----------


 ---------- 2018-07-26 13:00:00 : 후평1동   24329 ----------


 ---------- 2018-07-26 14:00:00 : 강남동   24332 ----------


 ---------- 2018-07-26 15:00:00 : 신동면   24333 ----------


 ---------- 2018-07-26 15:00:00 : 후평1동   24334 ----------


 ---------- 2018-07-26 16:00:00 : 동  면   24335 ----------


 ---------- 2018-07-26 17:00:00 : 신사우동   24337 ----------


 ---------- 2018-07-26 17:00:00 : 퇴계동   24338 ----------


 ---------- 2018-07-26 18:00:00 : 석사동   24339 ----------


 ---------- 2018-07-26 18:00:00 : 후평1동   24340 ----------


 ---------- 2018-07-26 18:00:00 : 북산면   24342 ----------


 ---------- 2018-07-27 00:00:00 : 동  면   24343 ----------


 ---------- 2018-07-27 08:00:00 : 후평1동   24344 ----------


 ---------- 2018-07-27 09:00:00 : 효자1동   24345 ----------


 ---------- 2018-07-27 09:00:00 : 후평1동   24346 ----------


 ---------- 2018-07-27 10:00:00 : 남산면   24347 ----------


 ---------- 2018-07-27 10:00:00 : 동  면   24348 ----------


 ---------- 2018-07-27 11:00:00 : 신북읍   24349 ----------


 ---------- 2018-07-27 12:00:00 : 동  면   24350 ----------


 ---------- 2018-07-27 13:00:00 : 강남동   24351 ----------


 ---------- 2018-07-27 14:00:00 : 서  면   24352 ----------


 ---------- 2018-07-27 14:00:00 : 동내면   24353 ----------


 ---------- 2018-07-27 17:00:00 : 남산면   24354 ----------


 ---------- 2018-07-27 18:00:00 : 서  면   24355 ----------


 ---------- 2018-07-27 18:00:00 : 근화동   24356 ----------


 ---------- 2018-07-27 18:00:00 : 후평1동   24357 ----------


 ---------- 2018-07-28 07:00:00 : 남산면   24358 ----------


 ---------- 2018-07-28 08:00:00 : 서  면   24361 ----------


 ---------- 2018-07-28 09:00:00 : 신사우동   24362 ----------


 ---------- 2018-07-28 09:00:00 : 소양동   24363 ----------


 ---------- 2018-07-28 10:00:00 : 근화동   24366 ----------


 ---------- 2018-07-28 10:00:00 : 후평1동   24367 ----------


 ---------- 2018-07-28 11:00:00 : 남산면   24368 ----------


 ---------- 2018-07-28 11:00:00 : 근화동   24369 ----------


 ---------- 2018-07-28 11:00:00 : 소양동   24372 ----------


 ---------- 2018-07-28 14:00:00 : 서  면   24375 ----------


 ---------- 2018-07-28 14:00:00 : 남산면   24376 ----------


 ---------- 2018-07-28 15:00:00 : 서  면   24378 ----------


 ---------- 2018-07-28 15:00:00 : 후평1동   24379 ----------


 ---------- 2018-07-28 19:00:00 : 동내면   24380 ----------


 ---------- 2018-07-28 20:00:00 : 석사동   24381 ----------


 ---------- 2018-07-28 23:00:00 : 남  면   24385 ----------


 ---------- 2018-07-29 01:00:00 : 남산면   24386 ----------


 ---------- 2018-07-29 04:00:00 : 신북읍   24387 ----------


 ---------- 2018-07-29 07:00:00 : 남산면   24388 ----------


 ---------- 2018-07-29 07:00:00 : 동  면   24389 ----------


 ---------- 2018-07-29 08:00:00 : 동  면   24390 ----------


 ---------- 2018-07-29 08:00:00 : 퇴계동   24391 ----------


 ---------- 2018-07-29 09:00:00 : 동내면   24392 ----------


 ---------- 2018-07-29 09:00:00 : 신사우동   24393 ----------


 ---------- 2018-07-29 09:00:00 : 신북읍   24394 ----------


 ---------- 2018-07-29 11:00:00 : 동내면   24395 ----------


 ---------- 2018-07-29 12:00:00 : 동  면   24396 ----------


 ---------- 2018-07-29 12:00:00 : 북산면   24397 ----------


 ---------- 2018-07-29 13:00:00 : 신북읍   24398 ----------


 ---------- 2018-07-29 17:00:00 : 석사동   24399 ----------


 ---------- 2018-07-29 17:00:00 : 강남동   24400 ----------


 ---------- 2018-07-29 17:00:00 : 동  면   24401 ----------


 ---------- 2018-07-29 18:00:00 : 강남동   24402 ----------


 ---------- 2018-07-29 19:00:00 : 퇴계동   24403 ----------


 ---------- 2018-07-29 22:00:00 : 남산면   24404 ----------


 ---------- 2018-07-30 06:00:00 : 근화동   24405 ----------


 ---------- 2018-07-30 07:00:00 : 동내면   24406 ----------


 ---------- 2018-07-30 08:00:00 : 동내면   24408 ----------


 ---------- 2018-07-30 08:00:00 : 후평1동   24410 ----------


 ---------- 2018-07-30 09:00:00 : 남산면   24411 ----------


 ---------- 2018-07-30 09:00:00 : 퇴계동   24412 ----------


 ---------- 2018-07-30 10:00:00 : 남  면   24413 ----------


 ---------- 2018-07-30 10:00:00 : 신사우동   24414 ----------


 ---------- 2018-07-30 11:00:00 : 강남동   24415 ----------


 ---------- 2018-07-30 11:00:00 : 남산면   24416 ----------


 ---------- 2018-07-30 12:00:00 : 남산면   24417 ----------


 ---------- 2018-07-30 15:00:00 : 남산면   24418 ----------


 ---------- 2018-07-30 17:00:00 : 신동면   24419 ----------


 ---------- 2018-07-30 17:00:00 : 남산면   24420 ----------


 ---------- 2018-07-30 17:00:00 : 신북읍   24421 ----------


 ---------- 2018-07-30 17:00:00 : 퇴계동   24422 ----------


 ---------- 2018-07-30 19:00:00 : 신북읍   24423 ----------


 ---------- 2018-07-30 20:00:00 : 신북읍   24424 ----------


 ---------- 2018-07-31 02:00:00 : 후평1동   24425 ----------


 ---------- 2018-07-31 06:00:00 : 퇴계동   24426 ----------


 ---------- 2018-07-31 07:00:00 : 동내면   24427 ----------


 ---------- 2018-07-31 09:00:00 : 동내면   24429 ----------


 ---------- 2018-07-31 13:00:00 : 강남동   24430 ----------


 ---------- 2018-07-31 13:00:00 : 남  면   24433 ----------


 ---------- 2018-07-31 13:00:00 : 동  면   24434 ----------


 ---------- 2018-07-31 14:00:00 : 강남동   24435 ----------


 ---------- 2018-07-31 14:00:00 : 사북면   24436 ----------


 ---------- 2018-07-31 14:00:00 : 북산면   24437 ----------


 ---------- 2018-07-31 15:00:00 : 후평1동   24438 ----------


 ---------- 2018-07-31 16:00:00 : 강남동   24440 ----------


 ---------- 2018-07-31 17:00:00 : 퇴계동   24441 ----------


 ---------- 2018-07-31 18:00:00 : 강남동   24442 ----------


 ---------- 2018-07-31 18:00:00 : 퇴계동   24443 ----------


 ---------- 2018-08-01 06:00:00 : 남  면   24444 ----------


 ---------- 2018-08-01 07:00:00 : 강남동   24445 ----------


 ---------- 2018-08-01 08:00:00 : 동내면   24446 ----------


 ---------- 2018-08-01 08:00:00 : 남산면   24448 ----------


 ---------- 2018-08-01 09:00:00 : 동  면   24450 ----------


 ---------- 2018-08-01 09:00:00 : 퇴계동   24451 ----------


 ---------- 2018-08-01 10:00:00 : 동내면   24452 ----------


 ---------- 2018-08-01 10:00:00 : 남산면   24453 ----------


 ---------- 2018-08-01 10:00:00 : 근화동   24454 ----------


 ---------- 2018-08-01 10:00:00 : 신북읍   24455 ----------


 ---------- 2018-08-01 11:00:00 : 남  면   24456 ----------


 ---------- 2018-08-01 11:00:00 : 근화동   24457 ----------


 ---------- 2018-08-01 11:00:00 : 신사우동   24458 ----------


 ---------- 2018-08-01 12:00:00 : 서  면   24459 ----------


 ---------- 2018-08-01 13:00:00 : 석사동   24460 ----------


 ---------- 2018-08-01 13:00:00 : 남산면   24461 ----------


 ---------- 2018-08-01 14:00:00 : 동  면   24462 ----------


 ---------- 2018-08-01 15:00:00 : 강남동   24464 ----------


 ---------- 2018-08-01 15:00:00 : 남  면   24465 ----------


 ---------- 2018-08-01 15:00:00 : 사북면   24466 ----------


 ---------- 2018-08-01 15:00:00 : 퇴계동   24468 ----------


 ---------- 2018-08-01 16:00:00 : 후평1동   24469 ----------


 ---------- 2018-08-01 16:00:00 : 퇴계동   24470 ----------


 ---------- 2018-08-01 17:00:00 : 석사동   24471 ----------


 ---------- 2018-08-01 17:00:00 : 서  면   24472 ----------


 ---------- 2018-08-01 17:00:00 : 효자1동   24473 ----------


 ---------- 2018-08-01 18:00:00 : 석사동   24476 ----------


 ---------- 2018-08-01 18:00:00 : 동내면   24477 ----------


 ---------- 2018-08-01 21:00:00 : 석사동   24478 ----------


 ---------- 2018-08-02 06:00:00 : 동내면   24479 ----------


 ---------- 2018-08-02 07:00:00 : 석사동   24480 ----------


 ---------- 2018-08-02 07:00:00 : 동내면   24482 ----------


 ---------- 2018-08-02 07:00:00 : 신사우동   24483 ----------


 ---------- 2018-08-02 07:00:00 : 퇴계동   24485 ----------


 ---------- 2018-08-02 08:00:00 : 후평1동   24486 ----------


 ---------- 2018-08-02 08:00:00 : 퇴계동   24487 ----------


 ---------- 2018-08-02 08:00:00 : 북산면   24488 ----------

 ---------- 2018-08-02 09:00:00 : 신사우동   24489 ----------


 ---------- 2018-08-02 10:00:00 : 강남동   24490 ----------


 ---------- 2018-08-02 10:00:00 : 신사우동   24491 ----------


 ---------- 2018-08-02 10:00:00 : 신북읍   24492 ----------


 ---------- 2018-08-02 11:00:00 : 강남동   24493 ----------


 ---------- 2018-08-02 11:00:00 : 사북면   24494 ----------


 ---------- 2018-08-02 11:00:00 : 동내면   24495 ----------


 ---------- 2018-08-02 11:00:00 : 근화동   24496 ----------


 ---------- 2018-08-02 12:00:00 : 신사우동   24497 ----------


 ---------- 2018-08-02 13:00:00 : 강남동   24498 ----------


 ---------- 2018-08-02 13:00:00 : 퇴계동   24499 ----------


 ---------- 2018-08-02 14:00:00 : 강남동   24500 ----------


 ---------- 2018-08-02 14:00:00 : 서  면   24501 ----------


 ---------- 2018-08-02 14:00:00 : 남산면   24502 ----------


 ---------- 2018-08-02 14:00:00 : 북산면   24503 ----------


 ---------- 2018-08-02 15:00:00 : 동  면   24504 ----------


 ---------- 2018-08-02 17:00:00 : 서  면   24505 ----------


 ---------- 2018-08-02 17:00:00 : 남  면   24509 ----------


 ---------- 2018-08-02 22:00:00 : 소양동   24510 ----------


 ---------- 2018-08-02 23:00:00 : 동  면   24511 ----------


 ---------- 2018-08-03 00:00:00 : 강남동   24512 ----------


 ---------- 2018-08-03 00:00:00 : 남산면   24514 ----------


 ---------- 2018-08-03 01:00:00 : 강남동   24515 ----------


 ---------- 2018-08-03 03:00:00 : 근화동   24516 ----------


 ---------- 2018-08-03 08:00:00 : 석사동   24517 ----------


 ---------- 2018-08-03 08:00:00 : 효자1동   24518 ----------


 ---------- 2018-08-03 08:00:00 : 근화동   24519 ----------


 ---------- 2018-08-03 08:00:00 : 신사우동   24521 ----------


 ---------- 2018-08-03 09:00:00 : 남  면   24522 ----------


 ---------- 2018-08-03 09:00:00 : 동내면   24523 ----------


 ---------- 2018-08-03 09:00:00 : 동  면   24524 ----------


 ---------- 2018-08-03 09:00:00 : 퇴계동   24525 ----------


 ---------- 2018-08-03 10:00:00 : 동내면   24526 ----------


 ---------- 2018-08-03 10:00:00 : 동  면   24527 ----------


 ---------- 2018-08-03 10:00:00 : 동산면   24528 ----------


 ---------- 2018-08-03 11:00:00 : 퇴계동   24529 ----------


 ---------- 2018-08-03 12:00:00 : 효자1동   24530 ----------


 ---------- 2018-08-03 13:00:00 : 동  면   24531 ----------


 ---------- 2018-08-03 14:00:00 : 서  면   24532 ----------


 ---------- 2018-08-03 15:00:00 : 강남동   24533 ----------


 ---------- 2018-08-03 16:00:00 : 남산면   24534 ----------


 ---------- 2018-08-03 16:00:00 : 후평1동   24535 ----------


 ---------- 2018-08-03 17:00:00 : 신북읍   24536 ----------


 ---------- 2018-08-03 18:00:00 : 남산면   24538 ----------


 ---------- 2018-08-03 18:00:00 : 동  면   24539 ----------


 ---------- 2018-08-04 01:00:00 : 근화동   24541 ----------


 ---------- 2018-08-04 02:00:00 : 효자1동   24542 ----------


 ---------- 2018-08-04 02:00:00 : 신사우동   24544 ----------


 ---------- 2018-08-04 04:00:00 : 동내면   24545 ----------


 ---------- 2018-08-04 07:00:00 : 동내면   24548 ----------


 ---------- 2018-08-04 07:00:00 : 후평1동   24549 ----------


 ---------- 2018-08-04 08:00:00 : 신북읍   24550 ----------


 ---------- 2018-08-04 09:00:00 : 사북면   24551 ----------


 ---------- 2018-08-04 10:00:00 : 동내면   24552 ----------


 ---------- 2018-08-04 10:00:00 : 남산면   24553 ----------


 ---------- 2018-08-04 10:00:00 : 동  면   24554 ----------


 ---------- 2018-08-04 10:00:00 : 동산면   24555 ----------


 ---------- 2018-08-04 11:00:00 : 서  면   24556 ----------


 ---------- 2018-08-04 14:00:00 : 신동면   24557 ----------


 ---------- 2018-08-04 14:00:00 : 신북읍   24558 ----------


 ---------- 2018-08-04 15:00:00 : 신사우동   24559 ----------


 ---------- 2018-08-04 15:00:00 : 동  면   24560 ----------


 ---------- 2018-08-04 16:00:00 : 서  면   24561 ----------


 ---------- 2018-08-04 19:00:00 : 남  면   24562 ----------


 ---------- 2018-08-05 07:00:00 : 동  면   24563 ----------


 ---------- 2018-08-05 09:00:00 : 남산면   24565 ----------


 ---------- 2018-08-05 09:00:00 : 동  면   24566 ----------


 ---------- 2018-08-05 11:00:00 : 남산면   24567 ----------


 ---------- 2018-08-05 13:00:00 : 사북면   24568 ----------


 ---------- 2018-08-05 14:00:00 : 사북면   24569 ----------


 ---------- 2018-08-05 15:00:00 : 효자1동   24570 ----------


 ---------- 2018-08-05 15:00:00 : 신사우동   24571 ----------


 ---------- 2018-08-05 15:00:00 : 후평1동   24572 ----------


 ---------- 2018-08-05 17:00:00 : 서  면   24573 ----------


 ---------- 2018-08-05 17:00:00 : 신북읍   24574 ----------


 ---------- 2018-08-05 17:00:00 : 동  면   24575 ----------


 ---------- 2018-08-05 17:00:00 : 동산면   24576 ----------


 ---------- 2018-08-05 18:00:00 : 효자1동   24577 ----------


 ---------- 2018-08-05 19:00:00 : 효자1동   24578 ----------


 ---------- 2018-08-05 20:00:00 : 신북읍   24579 ----------


 ---------- 2018-08-05 22:00:00 : 강남동   24581 ----------


 ---------- 2018-08-06 08:00:00 : 동내면   24582 ----------


 ---------- 2018-08-06 08:00:00 : 퇴계동   24583 ----------


 ---------- 2018-08-06 09:00:00 : 남산면   24584 ----------


 ---------- 2018-08-06 09:00:00 : 소양동   24585 ----------


 ---------- 2018-08-06 09:00:00 : 퇴계동   24586 ----------


 ---------- 2018-08-06 10:00:00 : 석사동   24587 ----------


 ---------- 2018-08-06 10:00:00 : 동내면   24588 ----------


 ---------- 2018-08-06 11:00:00 : 신사우동   24589 ----------


 ---------- 2018-08-06 12:00:00 : 서  면   24590 ----------


 ---------- 2018-08-06 12:00:00 : 동  면   24591 ----------


 ---------- 2018-08-06 13:00:00 : 석사동   24592 ----------


 ---------- 2018-08-06 13:00:00 : 동내면   24593 ----------


 ---------- 2018-08-06 13:00:00 : 신북읍   24594 ----------


 ---------- 2018-08-06 14:00:00 : 퇴계동   24595 ----------


 ---------- 2018-08-06 15:00:00 : 남  면   24596 ----------


 ---------- 2018-08-06 15:00:00 : 동  면   24597 ----------


 ---------- 2018-08-06 16:00:00 : 약사명동   24598 ----------


 ---------- 2018-08-06 16:00:00 : 동산면   24599 ----------


 ---------- 2018-08-06 17:00:00 : 남  면   24600 ----------


 ---------- 2018-08-06 17:00:00 : 동  면   24601 ----------


 ---------- 2018-08-07 06:00:00 : 동산면   24602 ----------


 ---------- 2018-08-07 08:00:00 : 동  면   24603 ----------


 ---------- 2018-08-07 08:00:00 : 후평1동   24605 ----------


 ---------- 2018-08-07 09:00:00 : 서  면   24606 ----------


 ---------- 2018-08-07 09:00:00 : 신북읍   24607 ----------


 ---------- 2018-08-07 10:00:00 : 근화동   24608 ----------


 ---------- 2018-08-07 10:00:00 : 신사우동   24610 ----------


 ---------- 2018-08-07 10:00:00 : 후평1동   24611 ----------


 ---------- 2018-08-07 11:00:00 : 효자1동   24612 ----------


 ---------- 2018-08-07 13:00:00 : 강남동   24613 ----------


 ---------- 2018-08-07 13:00:00 : 동내면   24614 ----------


 ---------- 2018-08-07 13:00:00 : 근화동   24615 ----------


 ---------- 2018-08-07 17:00:00 : 사북면   24616 ----------


 ---------- 2018-08-07 18:00:00 : 효자1동   24618 ----------


 ---------- 2018-08-07 19:00:00 : 동  면   24619 ----------


 ---------- 2018-08-07 19:00:00 : 북산면   24620 ----------


 ---------- 2018-08-07 22:00:00 : 강남동   24622 ----------


 ---------- 2018-08-08 03:00:00 : 후평1동   24623 ----------


 ---------- 2018-08-08 05:00:00 : 효자1동   24625 ----------


 ---------- 2018-08-08 08:00:00 : 강남동   24626 ----------


 ---------- 2018-08-08 10:00:00 : 강남동   24627 ----------


 ---------- 2018-08-08 10:00:00 : 서  면   24628 ----------


 ---------- 2018-08-08 10:00:00 : 후평1동   24629 ----------


 ---------- 2018-08-08 10:00:00 : 퇴계동   24630 ----------


 ---------- 2018-08-08 11:00:00 : 효자1동   24631 ----------


 ---------- 2018-08-08 11:00:00 : 신사우동   24632 ----------


 ---------- 2018-08-08 12:00:00 : 신사우동   24633 ----------


 ---------- 2018-08-08 12:00:00 : 동  면   24634 ----------


 ---------- 2018-08-08 14:00:00 : 동내면   24635 ----------


 ---------- 2018-08-08 14:00:00 : 신사우동   24638 ----------


 ---------- 2018-08-08 14:00:00 : 소양동   24639 ----------


 ---------- 2018-08-08 15:00:00 : 서  면   24640 ----------


 ---------- 2018-08-08 15:00:00 : 남산면   24641 ----------


 ---------- 2018-08-08 15:00:00 : 신사우동   24642 ----------


 ---------- 2018-08-08 16:00:00 : 강남동   24643 ----------

 ---------- 2018-08-08 16:00:00 : 후평1동   24644 ----------


 ---------- 2018-08-08 16:00:00 : 퇴계동   24645 ----------


 ---------- 2018-08-08 21:00:00 : 퇴계동   24647 ----------


 ---------- 2018-08-08 22:00:00 : 강남동   24649 ----------


 ---------- 2018-08-09 09:00:00 : 석사동   24650 ----------


 ---------- 2018-08-09 09:00:00 : 사북면   24651 ----------


 ---------- 2018-08-09 09:00:00 : 소양동   24652 ----------


 ---------- 2018-08-09 11:00:00 : 석사동   24653 ----------


 ---------- 2018-08-09 11:00:00 : 북산면   24654 ----------


 ---------- 2018-08-09 12:00:00 : 서  면   24655 ----------


 ---------- 2018-08-09 14:00:00 : 석사동   24657 ----------


 ---------- 2018-08-09 14:00:00 : 강남동   24658 ----------


 ---------- 2018-08-09 14:00:00 : 퇴계동   24659 ----------


 ---------- 2018-08-09 15:00:00 : 남산면   24661 ----------


 ---------- 2018-08-09 15:00:00 : 조운동   24662 ----------


 ---------- 2018-08-09 16:00:00 : 신북읍   24663 ----------


 ---------- 2018-08-09 17:00:00 : 동내면   24664 ----------


 ---------- 2018-08-09 17:00:00 : 신사우동   24665 ----------


 ---------- 2018-08-09 18:00:00 : 남  면   24666 ----------


 ---------- 2018-08-09 18:00:00 : 동내면   24668 ----------


 ---------- 2018-08-09 18:00:00 : 북산면   24669 ----------


 ---------- 2018-08-09 20:00:00 : 후평1동   24670 ----------


 ---------- 2018-08-09 21:00:00 : 석사동   24672 ----------


 ---------- 2018-08-10 01:00:00 : 강남동   24674 ----------


 ---------- 2018-08-10 02:00:00 : 동  면   24675 ----------


 ---------- 2018-08-10 08:00:00 : 서  면   24677 ----------


 ---------- 2018-08-10 08:00:00 : 소양동   24678 ----------


 ---------- 2018-08-10 10:00:00 : 석사동   24679 ----------


 ---------- 2018-08-10 10:00:00 : 신동면   24680 ----------


 ---------- 2018-08-10 10:00:00 : 효자1동   24681 ----------


 ---------- 2018-08-10 10:00:00 : 남산면   24682 ----------


 ---------- 2018-08-10 10:00:00 : 동  면   24683 ----------


 ---------- 2018-08-10 12:00:00 : 동  면   24685 ----------


 ---------- 2018-08-10 13:00:00 : 근화동   24686 ----------


 ---------- 2018-08-10 13:00:00 : 동  면   24687 ----------


 ---------- 2018-08-10 13:00:00 : 후평1동   24688 ----------


 ---------- 2018-08-10 14:00:00 : 신동면   24689 ----------


 ---------- 2018-08-10 14:00:00 : 신북읍   24690 ----------


 ---------- 2018-08-10 15:00:00 : 사북면   24691 ----------


 ---------- 2018-08-10 16:00:00 : 사북면   24693 ----------


 ---------- 2018-08-10 16:00:00 : 후평1동   24694 ----------


 ---------- 2018-08-10 16:00:00 : 퇴계동   24695 ----------


 ---------- 2018-08-10 17:00:00 : 동  면   24696 ----------


 ---------- 2018-08-10 18:00:00 : 강남동   24697 ----------


 ---------- 2018-08-10 18:00:00 : 남  면   24701 ----------


 ---------- 2018-08-10 18:00:00 : 남산면   24702 ----------


 ---------- 2018-08-10 19:00:00 : 강남동   24706 ----------


 ---------- 2018-08-10 19:00:00 : 서  면   24708 ----------


 ---------- 2018-08-10 19:00:00 : 소양동   24709 ----------


 ---------- 2018-08-10 19:00:00 : 동  면   24710 ----------


 ---------- 2018-08-11 06:00:00 : 소양동   24711 ----------


 ---------- 2018-08-11 07:00:00 : 남산면   24712 ----------


 ---------- 2018-08-11 09:00:00 : 동  면   24714 ----------


 ---------- 2018-08-11 11:00:00 : 남산면   24715 ----------


 ---------- 2018-08-11 11:00:00 : 소양동   24716 ----------


 ---------- 2018-08-11 12:00:00 : 소양동   24717 ----------


 ---------- 2018-08-11 12:00:00 : 후평1동   24718 ----------


 ---------- 2018-08-11 13:00:00 : 신동면   24719 ----------


 ---------- 2018-08-11 15:00:00 : 석사동   24720 ----------


 ---------- 2018-08-11 16:00:00 : 남  면   24721 ----------


 ---------- 2018-08-11 16:00:00 : 동내면   24722 ----------


 ---------- 2018-08-11 16:00:00 : 신북읍   24723 ----------


 ---------- 2018-08-11 17:00:00 : 사북면   24724 ----------


 ---------- 2018-08-11 18:00:00 : 강남동   24725 ----------


 ---------- 2018-08-11 20:00:00 : 신북읍   24726 ----------


 ---------- 2018-08-12 08:00:00 : 북산면   24727 ----------


 ---------- 2018-08-12 09:00:00 : 신북읍   24728 ----------


 ---------- 2018-08-12 09:00:00 : 소양동   24729 ----------


 ---------- 2018-08-12 09:00:00 : 후평1동   24730 ----------


 ---------- 2018-08-12 10:00:00 : 동산면   24731 ----------


 ---------- 2018-08-12 11:00:00 : 동  면   24732 ----------


 ---------- 2018-08-12 12:00:00 : 강남동   24733 ----------


 ---------- 2018-08-12 12:00:00 : 서  면   24734 ----------


 ---------- 2018-08-12 13:00:00 : 강남동   24735 ----------


 ---------- 2018-08-12 15:00:00 : 퇴계동   24736 ----------


 ---------- 2018-08-12 16:00:00 : 남산면   24737 ----------


 ---------- 2018-08-12 22:00:00 : 후평1동   24738 ----------


 ---------- 2018-08-13 06:00:00 : 후평1동   24739 ----------


 ---------- 2018-08-13 07:00:00 : 후평1동   24740 ----------


 ---------- 2018-08-13 08:00:00 : 석사동   24741 ----------


 ---------- 2018-08-13 08:00:00 : 신북읍   24742 ----------


 ---------- 2018-08-13 09:00:00 : 효자1동   24743 ----------


 ---------- 2018-08-13 09:00:00 : 남산면   24744 ----------


 ---------- 2018-08-13 09:00:00 : 동  면   24745 ----------


 ---------- 2018-08-13 12:00:00 : 동  면   24751 ----------


 ---------- 2018-08-13 13:00:00 : 석사동   24752 ----------


 ---------- 2018-08-13 13:00:00 : 효자1동   24753 ----------


 ---------- 2018-08-13 13:00:00 : 후평1동   24754 ----------


 ---------- 2018-08-13 13:00:00 : 퇴계동   24755 ----------


 ---------- 2018-08-13 14:00:00 : 효자1동   24757 ----------


 ---------- 2018-08-13 14:00:00 : 퇴계동   24758 ----------


 ---------- 2018-08-13 15:00:00 : 퇴계동   24759 ----------


 ---------- 2018-08-13 16:00:00 : 후평1동   24760 ----------


 ---------- 2018-08-13 17:00:00 : 동  면   24761 ----------


 ---------- 2018-08-14 07:00:00 : 강남동   24762 ----------


 ---------- 2018-08-14 07:00:00 : 퇴계동   24763 ----------


 ---------- 2018-08-14 08:00:00 : 신북읍   24764 ----------


 ---------- 2018-08-14 09:00:00 : 동내면   24765 ----------


 ---------- 2018-08-14 09:00:00 : 효자1동   24767 ----------


 ---------- 2018-08-14 09:00:00 : 후평1동   24768 ----------


 ---------- 2018-08-14 10:00:00 : 강남동   24769 ----------


 ---------- 2018-08-14 10:00:00 : 후평1동   24770 ----------


 ---------- 2018-08-14 10:00:00 : 동산면   24771 ----------


 ---------- 2018-08-14 12:00:00 : 석사동   24772 ----------


 ---------- 2018-08-14 13:00:00 : 서  면   24773 ----------


 ---------- 2018-08-14 13:00:00 : 퇴계동   24775 ----------


 ---------- 2018-08-14 15:00:00 : 남산면   24779 ----------


 ---------- 2018-08-14 17:00:00 : 후평1동   24780 ----------


 ---------- 2018-08-14 18:00:00 : 동  면   24781 ----------


 ---------- 2018-08-14 19:00:00 : 서  면   24783 ----------


 ---------- 2018-08-14 22:00:00 : 동  면   24784 ----------


 ---------- 2018-08-15 05:00:00 : 남  면   24785 ----------


 ---------- 2018-08-15 06:00:00 : 후평1동   24786 ----------


 ---------- 2018-08-15 08:00:00 : 서  면   24787 ----------


 ---------- 2018-08-15 08:00:00 : 신북읍   24788 ----------


 ---------- 2018-08-15 10:00:00 : 신북읍   24789 ----------


 ---------- 2018-08-15 11:00:00 : 서  면   24790 ----------


 ---------- 2018-08-15 11:00:00 : 동  면   24792 ----------


 ---------- 2018-08-15 12:00:00 : 남  면   24793 ----------


 ---------- 2018-08-15 14:00:00 : 석사동   24794 ----------


 ---------- 2018-08-15 15:00:00 : 신사우동   24795 ----------


 ---------- 2018-08-15 15:00:00 : 신북읍   24796 ----------


 ---------- 2018-08-15 15:00:00 : 동  면   24797 ----------


 ---------- 2018-08-15 16:00:00 : 신사우동   24798 ----------


 ---------- 2018-08-15 16:00:00 : 약사명동   24799 ----------


 ---------- 2018-08-15 18:00:00 : 신사우동   24800 ----------


 ---------- 2018-08-15 22:00:00 : 서  면   24801 ----------


 ---------- 2018-08-16 08:00:00 : 후평1동   24802 ----------


 ---------- 2018-08-16 09:00:00 : 남  면   24803 ----------


 ---------- 2018-08-16 09:00:00 : 사북면   24804 ----------


 ---------- 2018-08-16 09:00:00 : 동내면   24805 ----------


 ---------- 2018-08-16 09:00:00 : 근화동   24806 ----------


 ---------- 2018-08-16 10:00:00 : 석사동   24807 ----------


 ---------- 2018-08-16 10:00:00 : 동내면   24808 ----------


 ---------- 2018-08-16 10:00:00 : 퇴계동   24809 ----------


 ---------- 2018-08-16 11:00:00 : 퇴계동   24810 ----------

 ---------- 2018-08-16 14:00:00 : 서  면   24811 ----------


 ---------- 2018-08-16 14:00:00 : 퇴계동   24813 ----------


 ---------- 2018-08-16 15:00:00 : 동내면   24814 ----------


 ---------- 2018-08-16 16:00:00 : 신북읍   24815 ----------


 ---------- 2018-08-16 16:00:00 : 소양동   24816 ----------


 ---------- 2018-08-16 18:00:00 : 사북면   24817 ----------


 ---------- 2018-08-16 18:00:00 : 동내면   24818 ----------


 ---------- 2018-08-17 08:00:00 : 남  면   24819 ----------


 ---------- 2018-08-17 10:00:00 : 효자1동   24821 ----------


 ---------- 2018-08-17 10:00:00 : 남산면   24822 ----------


 ---------- 2018-08-17 10:00:00 : 신사우동   24823 ----------


 ---------- 2018-08-17 11:00:00 : 석사동   24824 ----------


 ---------- 2018-08-17 11:00:00 : 강남동   24825 ----------


 ---------- 2018-08-17 12:00:00 : 동  면   24826 ----------


 ---------- 2018-08-17 12:00:00 : 동산면   24827 ----------


 ---------- 2018-08-17 14:00:00 : 동  면   24828 ----------


 ---------- 2018-08-17 17:00:00 : 강남동   24830 ----------


 ---------- 2018-08-17 18:00:00 : 후평1동   24831 ----------


 ---------- 2018-08-18 09:00:00 : 강남동   24832 ----------


 ---------- 2018-08-18 10:00:00 : 동  면   24833 ----------


 ---------- 2018-08-18 10:00:00 : 퇴계동   24835 ----------


 ---------- 2018-08-18 11:00:00 : 남  면   24836 ----------


 ---------- 2018-08-18 12:00:00 : 남산면   24837 ----------


 ---------- 2018-08-18 12:00:00 : 신사우동   24838 ----------


 ---------- 2018-08-18 13:00:00 : 강남동   24839 ----------


 ---------- 2018-08-18 13:00:00 : 동내면   24840 ----------


 ---------- 2018-08-18 13:00:00 : 동  면   24841 ----------


 ---------- 2018-08-18 14:00:00 : 강남동   24842 ----------


 ---------- 2018-08-18 15:00:00 : 남산면   24847 ----------


 ---------- 2018-08-18 16:00:00 : 후평1동   24848 ----------


 ---------- 2018-08-18 17:00:00 : 퇴계동   24849 ----------


 ---------- 2018-08-19 08:00:00 : 강남동   24851 ----------


 ---------- 2018-08-19 09:00:00 : 동내면   24853 ----------


 ---------- 2018-08-19 09:00:00 : 신사우동   24854 ----------


 ---------- 2018-08-19 11:00:00 : 동산면   24855 ----------


 ---------- 2018-08-19 12:00:00 : 강남동   24856 ----------


 ---------- 2018-08-19 13:00:00 : 신북읍   24857 ----------


 ---------- 2018-08-19 15:00:00 : 남산면   24858 ----------


 ---------- 2018-08-19 15:00:00 : 후평1동   24860 ----------


 ---------- 2018-08-19 16:00:00 : 신북읍   24862 ----------


 ---------- 2018-08-19 17:00:00 : 신북읍   24864 ----------


 ---------- 2018-08-19 18:00:00 : 강남동   24865 ----------


 ---------- 2018-08-19 20:00:00 : 석사동   24866 ----------


 ---------- 2018-08-19 22:00:00 : 강남동   24867 ----------


 ---------- 2018-08-20 04:00:00 : 남산면   24871 ----------


 ---------- 2018-08-20 08:00:00 : 효자1동   24872 ----------


 ---------- 2018-08-20 08:00:00 : 후평1동   24873 ----------


 ---------- 2018-08-20 09:00:00 : 남  면   24874 ----------


 ---------- 2018-08-20 09:00:00 : 동내면   24875 ----------


 ---------- 2018-08-20 10:00:00 : 동내면   24876 ----------


 ---------- 2018-08-20 11:00:00 : 강남동   24877 ----------


 ---------- 2018-08-20 13:00:00 : 석사동   24879 ----------


 ---------- 2018-08-20 13:00:00 : 동산면   24880 ----------


 ---------- 2018-08-20 14:00:00 : 동  면   24881 ----------


 ---------- 2018-08-20 14:00:00 : 동산면   24882 ----------


 ---------- 2018-08-20 17:00:00 : 동  면   24883 ----------


 ---------- 2018-08-20 19:00:00 : 퇴계동   24884 ----------


 ---------- 2018-08-20 19:00:00 : 동산면   24885 ----------


 ---------- 2018-08-20 22:00:00 : 신사우동   24886 ----------


 ---------- 2018-08-21 02:00:00 : 석사동   24887 ----------


 ---------- 2018-08-21 07:00:00 : 효자1동   24889 ----------


 ---------- 2018-08-21 08:00:00 : 서  면   24890 ----------


 ---------- 2018-08-21 09:00:00 : 강남동   24891 ----------


 ---------- 2018-08-21 09:00:00 : 동  면   24892 ----------


 ---------- 2018-08-21 10:00:00 : 신북읍   24893 ----------


 ---------- 2018-08-21 11:00:00 : 퇴계동   24894 ----------


 ---------- 2018-08-21 13:00:00 : 석사동   24895 ----------


 ---------- 2018-08-21 13:00:00 : 강남동   24896 ----------


 ---------- 2018-08-21 13:00:00 : 남산면   24897 ----------


 ---------- 2018-08-21 15:00:00 : 소양동   24898 ----------


 ---------- 2018-08-21 15:00:00 : 동산면   24899 ----------


 ---------- 2018-08-21 18:00:00 : 신사우동   24900 ----------


 ---------- 2018-08-21 20:00:00 : 조운동   24902 ----------


 ---------- 2018-08-21 21:00:00 : 효자1동   24903 ----------


 ---------- 2018-08-21 23:00:00 : 효자1동   24905 ----------


 ---------- 2018-08-22 07:00:00 : 후평1동   24906 ----------


 ---------- 2018-08-22 09:00:00 : 신사우동   24907 ----------


 ---------- 2018-08-22 09:00:00 : 북산면   24908 ----------


 ---------- 2018-08-22 10:00:00 : 강남동   24909 ----------


 ---------- 2018-08-22 11:00:00 : 신북읍   24910 ----------


 ---------- 2018-08-22 11:00:00 : 후평1동   24911 ----------


 ---------- 2018-08-22 11:00:00 : 퇴계동   24912 ----------


 ---------- 2018-08-22 12:00:00 : 신사우동   24913 ----------


 ---------- 2018-08-22 13:00:00 : 신동면   24914 ----------


 ---------- 2018-08-22 13:00:00 : 신사우동   24915 ----------


 ---------- 2018-08-22 13:00:00 : 동  면   24916 ----------


 ---------- 2018-08-22 16:00:00 : 동내면   24918 ----------


 ---------- 2018-08-22 16:00:00 : 북산면   24919 ----------


 ---------- 2018-08-22 17:00:00 : 동내면   24920 ----------


 ---------- 2018-08-22 18:00:00 : 효자1동   24921 ----------


 ---------- 2018-08-22 18:00:00 : 퇴계동   24922 ----------


 ---------- 2018-08-22 19:00:00 : 후평1동   24923 ----------


 ---------- 2018-08-23 02:00:00 : 후평1동   24925 ----------


 ---------- 2018-08-23 08:00:00 : 효자1동   24926 ----------


 ---------- 2018-08-23 10:00:00 : 신북읍   24927 ----------


 ---------- 2018-08-23 11:00:00 : 동내면   24928 ----------


 ---------- 2018-08-23 12:00:00 : 서  면   24929 ----------


 ---------- 2018-08-23 15:00:00 : 동내면   24930 ----------


 ---------- 2018-08-23 17:00:00 : 서  면   24931 ----------


 ---------- 2018-08-23 17:00:00 : 근화동   24932 ----------


 ---------- 2018-08-24 06:00:00 : 퇴계동   24933 ----------


 ---------- 2018-08-24 11:00:00 : 사북면   24934 ----------


 ---------- 2018-08-24 11:00:00 : 효자1동   24935 ----------


 ---------- 2018-08-24 12:00:00 : 강남동   24936 ----------


 ---------- 2018-08-24 13:00:00 : 약사명동   24937 ----------


 ---------- 2018-08-24 16:00:00 : 신사우동   24938 ----------


 ---------- 2018-08-24 16:00:00 : 약사명동   24939 ----------


 ---------- 2018-08-24 17:00:00 : 남  면   24940 ----------


 ---------- 2018-08-24 17:00:00 : 약사명동   24941 ----------


 ---------- 2018-08-24 19:00:00 : 석사동   24942 ----------


 ---------- 2018-08-25 08:00:00 : 서  면   24943 ----------


 ---------- 2018-08-25 09:00:00 : 남  면   24944 ----------


 ---------- 2018-08-25 09:00:00 : 신사우동   24947 ----------


 ---------- 2018-08-25 09:00:00 : 소양동   24948 ----------


 ---------- 2018-08-25 11:00:00 : 근화동   24949 ----------


 ---------- 2018-08-25 11:00:00 : 신사우동   24950 ----------


 ---------- 2018-08-25 12:00:00 : 후평1동   24951 ----------


 ---------- 2018-08-25 13:00:00 : 후평1동   24952 ----------


 ---------- 2018-08-25 13:00:00 : 퇴계동   24953 ----------


 ---------- 2018-08-25 14:00:00 : 효자1동   24954 ----------


 ---------- 2018-08-25 15:00:00 : 강남동   24955 ----------


 ---------- 2018-08-25 15:00:00 : 동내면   24956 ----------


 ---------- 2018-08-25 15:00:00 : 후평1동   24957 ----------


 ---------- 2018-08-25 15:00:00 : 북산면   24959 ----------


 ---------- 2018-08-25 16:00:00 : 강남동   24960 ----------


 ---------- 2018-08-25 16:00:00 : 남  면   24961 ----------


 ---------- 2018-08-25 16:00:00 : 효자1동   24962 ----------


 ---------- 2018-08-25 16:00:00 : 동  면   24963 ----------


 ---------- 2018-08-25 17:00:00 : 신북읍   24964 ----------


 ---------- 2018-08-25 17:00:00 : 퇴계동   24965 ----------


 ---------- 2018-08-25 18:00:00 : 신동면   24967 ----------


 ---------- 2018-08-25 18:00:00 : 동  면   24968 ----------


 ---------- 2018-08-25 19:00:00 : 강남동   24969 ----------


 ---------- 2018-08-25 19:00:00 : 사북면   24970 ----------


 ---------- 2018-08-25 23:00:00 : 동내면   24971 ----------


 ---------- 2018-08-25 23:00:00 : 퇴계동   24972 ----------

 ---------- 2018-08-26 03:00:00 : 석사동   24973 ----------


 ---------- 2018-08-26 07:00:00 : 강남동   24974 ----------


 ---------- 2018-08-26 08:00:00 : 교  동   24975 ----------


 ---------- 2018-08-26 09:00:00 : 신북읍   24976 ----------


 ---------- 2018-08-26 11:00:00 : 후평1동   24977 ----------


 ---------- 2018-08-26 11:00:00 : 퇴계동   24978 ----------


 ---------- 2018-08-26 13:00:00 : 신사우동   24979 ----------


 ---------- 2018-08-26 15:00:00 : 동내면   24980 ----------


 ---------- 2018-08-26 17:00:00 : 강남동   24981 ----------


 ---------- 2018-08-26 17:00:00 : 동  면   24982 ----------


 ---------- 2018-08-27 07:00:00 : 동내면   24983 ----------


 ---------- 2018-08-27 10:00:00 : 퇴계동   24984 ----------


 ---------- 2018-08-27 13:00:00 : 석사동   24985 ----------


 ---------- 2018-08-27 14:00:00 : 남산면   24987 ----------


 ---------- 2018-08-27 15:00:00 : 동  면   24988 ----------


 ---------- 2018-08-27 17:00:00 : 사북면   24989 ----------


 ---------- 2018-08-27 19:00:00 : 근화동   24990 ----------


 ---------- 2018-08-27 20:00:00 : 신사우동   24991 ----------


 ---------- 2018-08-27 21:00:00 : 신사우동   24992 ----------


 ---------- 2018-08-28 01:00:00 : 신사우동   24993 ----------


 ---------- 2018-08-28 02:00:00 : 교  동   24995 ----------


 ---------- 2018-08-28 09:00:00 : 약사명동   24996 ----------


 ---------- 2018-08-28 10:00:00 : 석사동   24997 ----------


 ---------- 2018-08-28 10:00:00 : 후평1동   24998 ----------


 ---------- 2018-08-28 11:00:00 : 신사우동   25000 ----------


 ---------- 2018-08-28 15:00:00 : 석사동   25001 ----------


 ---------- 2018-08-28 20:00:00 : 서  면   25002 ----------


 ---------- 2018-08-28 20:00:00 : 동산면   25004 ----------


 ---------- 2018-08-28 21:00:00 : 서  면   25006 ----------


 ---------- 2018-08-28 21:00:00 : 동내면   25007 ----------


 ---------- 2018-08-28 23:00:00 : 동내면   25008 ----------


 ---------- 2018-08-29 01:00:00 : 퇴계동   25009 ----------


 ---------- 2018-08-29 03:00:00 : 강남동   25010 ----------


 ---------- 2018-08-29 03:00:00 : 소양동   25011 ----------


 ---------- 2018-08-29 07:00:00 : 석사동   25012 ----------


 ---------- 2018-08-29 08:00:00 : 근화동   25014 ----------


 ---------- 2018-08-29 09:00:00 : 남산면   25015 ----------


 ---------- 2018-08-29 09:00:00 : 동산면   25016 ----------


 ---------- 2018-08-29 10:00:00 : 동내면   25017 ----------


 ---------- 2018-08-29 12:00:00 : 후평1동   25018 ----------


 ---------- 2018-08-29 13:00:00 : 남산면   25025 ----------


 ---------- 2018-08-29 14:00:00 : 남산면   25026 ----------


 ---------- 2018-08-29 14:00:00 : 퇴계동   25027 ----------


 ---------- 2018-08-29 17:00:00 : 효자1동   25028 ----------


 ---------- 2018-08-29 17:00:00 : 남산면   25031 ----------


 ---------- 2018-08-29 17:00:00 : 조운동   25032 ----------


 ---------- 2018-08-29 18:00:00 : 신동면   25033 ----------


 ---------- 2018-08-29 18:00:00 : 근화동   25034 ----------


 ---------- 2018-08-30 03:00:00 : 동내면   25035 ----------


 ---------- 2018-08-30 08:00:00 : 남산면   25036 ----------


 ---------- 2018-08-30 09:00:00 : 석사동   25037 ----------


 ---------- 2018-08-30 09:00:00 : 서  면   25039 ----------


 ---------- 2018-08-30 09:00:00 : 소양동   25040 ----------


 ---------- 2018-08-30 10:00:00 : 동내면   25041 ----------


 ---------- 2018-08-30 10:00:00 : 동  면   25042 ----------


 ---------- 2018-08-30 14:00:00 : 동  면   25043 ----------


 ---------- 2018-08-30 15:00:00 : 강남동   25044 ----------


 ---------- 2018-08-31 00:00:00 : 퇴계동   25045 ----------


 ---------- 2018-08-31 09:00:00 : 남산면   25046 ----------


 ---------- 2018-08-31 10:00:00 : 효자1동   25047 ----------


 ---------- 2018-08-31 13:00:00 : 강남동   25048 ----------


 ---------- 2018-08-31 14:00:00 : 강남동   25049 ----------


 ---------- 2018-09-01 02:00:00 : 신사우동   25051 ----------


 ---------- 2018-09-01 07:00:00 : 남산면   25052 ----------


 ---------- 2018-09-01 07:00:00 : 퇴계동   25053 ----------


 ---------- 2018-09-01 08:00:00 : 사북면   25054 ----------


 ---------- 2018-09-01 09:00:00 : 서  면   25055 ----------


 ---------- 2018-09-01 09:00:00 : 동내면   25056 ----------


 ---------- 2018-09-01 09:00:00 : 신사우동   25057 ----------


 ---------- 2018-09-01 10:00:00 : 강남동   25058 ----------


 ---------- 2018-09-01 10:00:00 : 사북면   25059 ----------


 ---------- 2018-09-01 11:00:00 : 남산면   25060 ----------


 ---------- 2018-09-01 11:00:00 : 후평1동   25061 ----------


 ---------- 2018-09-01 12:00:00 : 석사동   25062 ----------


 ---------- 2018-09-01 12:00:00 : 동내면   25063 ----------


 ---------- 2018-09-01 13:00:00 : 신북읍   25064 ----------


 ---------- 2018-09-01 17:00:00 : 강남동   25067 ----------


 ---------- 2018-09-02 00:00:00 : 후평1동   25068 ----------


 ---------- 2018-09-02 02:00:00 : 석사동   25069 ----------


 ---------- 2018-09-02 07:00:00 : 석사동   25070 ----------


 ---------- 2018-09-02 09:00:00 : 강남동   25071 ----------


 ---------- 2018-09-02 09:00:00 : 신사우동   25072 ----------


 ---------- 2018-09-02 10:00:00 : 석사동   25073 ----------


 ---------- 2018-09-02 10:00:00 : 남  면   25074 ----------


 ---------- 2018-09-02 11:00:00 : 서  면   25075 ----------


 ---------- 2018-09-02 11:00:00 : 신사우동   25076 ----------


 ---------- 2018-09-02 11:00:00 : 소양동   25077 ----------


 ---------- 2018-09-02 13:00:00 : 강남동   25078 ----------


 ---------- 2018-09-02 13:00:00 : 동  면   25079 ----------


 ---------- 2018-09-02 15:00:00 : 서  면   25080 ----------


 ---------- 2018-09-02 16:00:00 : 강남동   25081 ----------


 ---------- 2018-09-02 16:00:00 : 근화동   25083 ----------


 ---------- 2018-09-02 17:00:00 : 근화동   25085 ----------


 ---------- 2018-09-02 17:00:00 : 소양동   25087 ----------


 ---------- 2018-09-02 18:00:00 : 남산면   25088 ----------


 ---------- 2018-09-02 22:00:00 : 북산면   25091 ----------


 ---------- 2018-09-03 01:00:00 : 효자1동   25092 ----------


 ---------- 2018-09-03 09:00:00 : 강남동   25093 ----------


 ---------- 2018-09-03 10:00:00 : 후평1동   25094 ----------


 ---------- 2018-09-03 10:00:00 : 퇴계동   25095 ----------


 ---------- 2018-09-03 11:00:00 : 석사동   25096 ----------


 ---------- 2018-09-03 11:00:00 : 남산면   25097 ----------


 ---------- 2018-09-03 12:00:00 : 남산면   25098 ----------


 ---------- 2018-09-03 13:00:00 : 후평1동   25099 ----------


 ---------- 2018-09-03 14:00:00 : 후평1동   25100 ----------


 ---------- 2018-09-03 15:00:00 : 신북읍   25101 ----------


 ---------- 2018-09-03 15:00:00 : 후평1동   25102 ----------


 ---------- 2018-09-03 16:00:00 : 강남동   25103 ----------


 ---------- 2018-09-03 17:00:00 : 남산면   25106 ----------


 ---------- 2018-09-04 03:00:00 : 후평1동   25107 ----------


 ---------- 2018-09-04 09:00:00 : 남산면   25108 ----------


 ---------- 2018-09-04 10:00:00 : 동산면   25109 ----------


 ---------- 2018-09-04 12:00:00 : 강남동   25110 ----------


 ---------- 2018-09-04 13:00:00 : 석사동   25111 ----------


 ---------- 2018-09-04 13:00:00 : 동내면   25112 ----------


 ---------- 2018-09-04 14:00:00 : 석사동   25113 ----------


 ---------- 2018-09-04 14:00:00 : 사북면   25114 ----------


 ---------- 2018-09-04 14:00:00 : 신사우동   25115 ----------


 ---------- 2018-09-04 15:00:00 : 남  면   25116 ----------


 ---------- 2018-09-04 15:00:00 : 남산면   25117 ----------


 ---------- 2018-09-04 18:00:00 : 동산면   25118 ----------


 ---------- 2018-09-05 07:00:00 : 퇴계동   25119 ----------


 ---------- 2018-09-05 08:00:00 : 신사우동   25120 ----------


 ---------- 2018-09-05 08:00:00 : 동  면   25121 ----------


 ---------- 2018-09-05 09:00:00 : 후평1동   25122 ----------


 ---------- 2018-09-05 10:00:00 : 강남동   25123 ----------


 ---------- 2018-09-05 11:00:00 : 강남동   25124 ----------


 ---------- 2018-09-05 11:00:00 : 동  면   25125 ----------


 ---------- 2018-09-05 12:00:00 : 남산면   25126 ----------


 ---------- 2018-09-05 12:00:00 : 퇴계동   25127 ----------


 ---------- 2018-09-05 13:00:00 : 강남동   25128 ----------


 ---------- 2018-09-05 14:00:00 : 교  동   25129 ----------


 ---------- 2018-09-05 15:00:00 : 신북읍   25132 ----------


 ---------- 2018-09-05 17:00:00 : 동내면   25133 ----------


 ---------- 2018-09-05 17:00:00 : 후평1동   25134 ----------


 ---------- 2018-09-05 20:00:00 : 강남동   25136 ----------

 ---------- 2018-09-06 09:00:00 : 근화동   25137 ----------


 ---------- 2018-09-06 09:00:00 : 동산면   25138 ----------


 ---------- 2018-09-06 10:00:00 : 강남동   25139 ----------


 ---------- 2018-09-06 11:00:00 : 퇴계동   25141 ----------


 ---------- 2018-09-06 13:00:00 : 석사동   25142 ----------


 ---------- 2018-09-06 14:00:00 : 동  면   25143 ----------


 ---------- 2018-09-06 15:00:00 : 효자1동   25144 ----------


 ---------- 2018-09-06 15:00:00 : 북산면   25145 ----------


 ---------- 2018-09-06 15:00:00 : 교  동   25146 ----------


 ---------- 2018-09-06 16:00:00 : 동내면   25147 ----------


 ---------- 2018-09-06 19:00:00 : 효자1동   25150 ----------


 ---------- 2018-09-07 09:00:00 : 서  면   25151 ----------


 ---------- 2018-09-07 09:00:00 : 신사우동   25152 ----------


 ---------- 2018-09-07 13:00:00 : 남산면   25153 ----------


 ---------- 2018-09-07 14:00:00 : 퇴계동   25154 ----------


 ---------- 2018-09-07 15:00:00 : 동내면   25155 ----------


 ---------- 2018-09-07 16:00:00 : 강남동   25156 ----------


 ---------- 2018-09-07 17:00:00 : 석사동   25157 ----------


 ---------- 2018-09-07 17:00:00 : 서  면   25158 ----------


 ---------- 2018-09-07 17:00:00 : 동  면   25159 ----------


 ---------- 2018-09-07 19:00:00 : 동내면   25160 ----------


 ---------- 2018-09-07 19:00:00 : 퇴계동   25161 ----------


 ---------- 2018-09-07 21:00:00 : 북산면   25162 ----------


 ---------- 2018-09-07 22:00:00 : 조운동   25163 ----------


 ---------- 2018-09-08 09:00:00 : 신동면   25165 ----------


 ---------- 2018-09-08 11:00:00 : 퇴계동   25166 ----------


 ---------- 2018-09-08 13:00:00 : 동내면   25167 ----------


 ---------- 2018-09-08 14:00:00 : 사북면   25168 ----------


 ---------- 2018-09-08 15:00:00 : 효자1동   25169 ----------


 ---------- 2018-09-08 16:00:00 : 강남동   25170 ----------


 ---------- 2018-09-08 18:00:00 : 신북읍   25171 ----------


 ---------- 2018-09-08 21:00:00 : 효자1동   25173 ----------


 ---------- 2018-09-08 21:00:00 : 퇴계동   25174 ----------


 ---------- 2018-09-09 06:00:00 : 강남동   25175 ----------


 ---------- 2018-09-09 09:00:00 : 신북읍   25176 ----------


 ---------- 2018-09-09 10:00:00 : 신동면   25177 ----------


 ---------- 2018-09-09 11:00:00 : 신사우동   25178 ----------


 ---------- 2018-09-09 13:00:00 : 근화동   25179 ----------


 ---------- 2018-09-09 14:00:00 : 동  면   25180 ----------


 ---------- 2018-09-09 15:00:00 : 동내면   25181 ----------


 ---------- 2018-09-09 16:00:00 : 근화동   25182 ----------


 ---------- 2018-09-09 16:00:00 : 동산면   25183 ----------


 ---------- 2018-09-09 17:00:00 : 석사동   25184 ----------


 ---------- 2018-09-09 21:00:00 : 동내면   25185 ----------


 ---------- 2018-09-10 09:00:00 : 석사동   25186 ----------


 ---------- 2018-09-10 09:00:00 : 약사명동   25187 ----------


 ---------- 2018-09-10 09:00:00 : 후평1동   25188 ----------


 ---------- 2018-09-10 12:00:00 : 강남동   25189 ----------


 ---------- 2018-09-10 12:00:00 : 신사우동   25190 ----------


 ---------- 2018-09-10 14:00:00 : 신북읍   25191 ----------


 ---------- 2018-09-10 15:00:00 : 동내면   25192 ----------


 ---------- 2018-09-10 15:00:00 : 신북읍   25193 ----------


 ---------- 2018-09-10 17:00:00 : 동내면   25194 ----------


 ---------- 2018-09-10 18:00:00 : 동  면   25195 ----------


 ---------- 2018-09-11 07:00:00 : 신사우동   25197 ----------


 ---------- 2018-09-11 08:00:00 : 동산면   25198 ----------


 ---------- 2018-09-11 09:00:00 : 동  면   25199 ----------


 ---------- 2018-09-11 10:00:00 : 강남동   25200 ----------


 ---------- 2018-09-11 10:00:00 : 남  면   25201 ----------


 ---------- 2018-09-11 11:00:00 : 남산면   25202 ----------


 ---------- 2018-09-11 11:00:00 : 후평1동   25203 ----------


 ---------- 2018-09-11 13:00:00 : 동  면   25204 ----------


 ---------- 2018-09-11 14:00:00 : 후평1동   25205 ----------


 ---------- 2018-09-11 16:00:00 : 남산면   25206 ----------


 ---------- 2018-09-11 16:00:00 : 후평1동   25207 ----------


 ---------- 2018-09-11 19:00:00 : 사북면   25208 ----------


 ---------- 2018-09-12 09:00:00 : 퇴계동   25209 ----------


 ---------- 2018-09-12 10:00:00 : 동내면   25210 ----------


 ---------- 2018-09-12 10:00:00 : 퇴계동   25211 ----------


 ---------- 2018-09-12 11:00:00 : 동내면   25212 ----------


 ---------- 2018-09-12 13:00:00 : 서  면   25214 ----------


 ---------- 2018-09-12 13:00:00 : 남산면   25215 ----------


 ---------- 2018-09-12 13:00:00 : 신사우동   25217 ----------


 ---------- 2018-09-12 18:00:00 : 신북읍   25218 ----------


 ---------- 2018-09-12 19:00:00 : 소양동   25219 ----------


 ---------- 2018-09-12 22:00:00 : 교  동   25221 ----------


 ---------- 2018-09-13 00:00:00 : 동내면   25223 ----------


 ---------- 2018-09-13 08:00:00 : 동내면   25224 ----------


 ---------- 2018-09-13 09:00:00 : 석사동   25225 ----------


 ---------- 2018-09-13 09:00:00 : 서  면   25226 ----------


 ---------- 2018-09-13 09:00:00 : 남산면   25227 ----------


 ---------- 2018-09-13 09:00:00 : 동  면   25228 ----------


 ---------- 2018-09-13 11:00:00 : 신사우동   25229 ----------


 ---------- 2018-09-13 12:00:00 : 신동면   25230 ----------


 ---------- 2018-09-13 14:00:00 : 퇴계동   25232 ----------


 ---------- 2018-09-13 16:00:00 : 강남동   25233 ----------


 ---------- 2018-09-13 21:00:00 : 사북면   25236 ----------


 ---------- 2018-09-14 08:00:00 : 서  면   25237 ----------


 ---------- 2018-09-14 09:00:00 : 신사우동   25238 ----------


 ---------- 2018-09-14 09:00:00 : 조운동   25239 ----------


 ---------- 2018-09-14 11:00:00 : 퇴계동   25241 ----------


 ---------- 2018-09-14 12:00:00 : 소양동   25242 ----------


 ---------- 2018-09-14 13:00:00 : 동  면   25243 ----------


 ---------- 2018-09-14 15:00:00 : 남산면   25244 ----------


 ---------- 2018-09-14 18:00:00 : 후평1동   25245 ----------


 ---------- 2018-09-14 19:00:00 : 후평1동   25246 ----------


 ---------- 2018-09-14 20:00:00 : 남산면   25247 ----------


 ---------- 2018-09-14 23:00:00 : 동내면   25249 ----------


 ---------- 2018-09-15 10:00:00 : 신사우동   25250 ----------


 ---------- 2018-09-15 11:00:00 : 동내면   25251 ----------


 ---------- 2018-09-15 11:00:00 : 동  면   25252 ----------


 ---------- 2018-09-15 12:00:00 : 신사우동   25253 ----------


 ---------- 2018-09-15 15:00:00 : 강남동   25254 ----------


 ---------- 2018-09-15 15:00:00 : 효자1동   25255 ----------


 ---------- 2018-09-15 19:00:00 : 효자1동   25257 ----------


 ---------- 2018-09-16 03:00:00 : 동내면   25259 ----------


 ---------- 2018-09-16 04:00:00 : 남산면   25260 ----------


 ---------- 2018-09-16 08:00:00 : 신사우동   25261 ----------


 ---------- 2018-09-16 09:00:00 : 서  면   25262 ----------


 ---------- 2018-09-16 09:00:00 : 남산면   25263 ----------


 ---------- 2018-09-16 10:00:00 : 동내면   25264 ----------


 ---------- 2018-09-16 12:00:00 : 효자1동   25265 ----------


 ---------- 2018-09-16 13:00:00 : 동내면   25266 ----------


 ---------- 2018-09-16 13:00:00 : 효자1동   25267 ----------


 ---------- 2018-09-16 14:00:00 : 신동면   25268 ----------


 ---------- 2018-09-16 14:00:00 : 북산면   25269 ----------


 ---------- 2018-09-16 16:00:00 : 신사우동   25270 ----------


 ---------- 2018-09-16 17:00:00 : 동산면   25271 ----------


 ---------- 2018-09-17 00:00:00 : 약사명동   25272 ----------


 ---------- 2018-09-17 07:00:00 : 강남동   25273 ----------


 ---------- 2018-09-17 09:00:00 : 강남동   25274 ----------


 ---------- 2018-09-17 09:00:00 : 남산면   25276 ----------


 ---------- 2018-09-17 09:00:00 : 동  면   25279 ----------


 ---------- 2018-09-17 10:00:00 : 강남동   25280 ----------


 ---------- 2018-09-17 14:00:00 : 신동면   25281 ----------


 ---------- 2018-09-17 14:00:00 : 신북읍   25282 ----------


 ---------- 2018-09-17 16:00:00 : 남산면   25283 ----------


 ---------- 2018-09-17 16:00:00 : 후평1동   25284 ----------


 ---------- 2018-09-17 16:00:00 : 퇴계동   25285 ----------


 ---------- 2018-09-17 17:00:00 : 강남동   25286 ----------


 ---------- 2018-09-17 18:00:00 : 석사동   25287 ----------


 ---------- 2018-09-17 19:00:00 : 퇴계동   25288 ----------


 ---------- 2018-09-18 03:00:00 : 후평1동   25289 ----------


 ---------- 2018-09-18 09:00:00 : 동  면   25290 ----------


 ---------- 2018-09-18 10:00:00 : 효자1동   25291 ----------


 ---------- 2018-09-18 11:00:00 : 남산면   25292 ----------

 ---------- 2018-09-18 14:00:00 : 신동면   25293 ----------


 ---------- 2018-09-18 14:00:00 : 서  면   25294 ----------


 ---------- 2018-09-18 14:00:00 : 후평1동   25295 ----------


 ---------- 2018-09-18 15:00:00 : 강남동   25296 ----------


 ---------- 2018-09-18 15:00:00 : 효자1동   25297 ----------


 ---------- 2018-09-18 16:00:00 : 후평1동   25298 ----------


 ---------- 2018-09-18 17:00:00 : 동내면   25299 ----------


 ---------- 2018-09-18 19:00:00 : 강남동   25300 ----------


 ---------- 2018-09-18 20:00:00 : 석사동   25301 ----------


 ---------- 2018-09-19 07:00:00 : 효자1동   25302 ----------


 ---------- 2018-09-19 09:00:00 : 서  면   25303 ----------


 ---------- 2018-09-19 10:00:00 : 서  면   25304 ----------


 ---------- 2018-09-19 10:00:00 : 남산면   25305 ----------


 ---------- 2018-09-19 10:00:00 : 신북읍   25306 ----------


 ---------- 2018-09-19 11:00:00 : 퇴계동   25307 ----------


 ---------- 2018-09-19 15:00:00 : 서  면   25310 ----------


 ---------- 2018-09-19 16:00:00 : 석사동   25311 ----------


 ---------- 2018-09-19 19:00:00 : 동  면   25312 ----------


 ---------- 2018-09-19 23:00:00 : 신사우동   25313 ----------


 ---------- 2018-09-20 07:00:00 : 효자1동   25315 ----------


 ---------- 2018-09-20 09:00:00 : 사북면   25317 ----------


 ---------- 2018-09-20 10:00:00 : 효자1동   25318 ----------


 ---------- 2018-09-20 13:00:00 : 근화동   25319 ----------


 ---------- 2018-09-20 16:00:00 : 동산면   25320 ----------


 ---------- 2018-09-20 18:00:00 : 동내면   25321 ----------


 ---------- 2018-09-20 18:00:00 : 후평1동   25322 ----------


 ---------- 2018-09-21 04:00:00 : 신사우동   25323 ----------


 ---------- 2018-09-21 06:00:00 : 동내면   25325 ----------


 ---------- 2018-09-21 08:00:00 : 퇴계동   25327 ----------


 ---------- 2018-09-21 09:00:00 : 남  면   25328 ----------


 ---------- 2018-09-21 16:00:00 : 동  면   25329 ----------


 ---------- 2018-09-21 16:00:00 : 후평1동   25330 ----------


 ---------- 2018-09-21 18:00:00 : 후평1동   25331 ----------


 ---------- 2018-09-21 20:00:00 : 신사우동   25332 ----------


 ---------- 2018-09-21 21:00:00 : 효자1동   25334 ----------


 ---------- 2018-09-22 01:00:00 : 약사명동   25335 ----------


 ---------- 2018-09-22 10:00:00 : 사북면   25336 ----------


 ---------- 2018-09-22 13:00:00 : 신북읍   25338 ----------


 ---------- 2018-09-22 14:00:00 : 퇴계동   25339 ----------


 ---------- 2018-09-22 15:00:00 : 신북읍   25341 ----------


 ---------- 2018-09-22 16:00:00 : 서  면   25342 ----------


 ---------- 2018-09-22 16:00:00 : 신북읍   25343 ----------


 ---------- 2018-09-22 16:00:00 : 조운동   25344 ----------


 ---------- 2018-09-22 19:00:00 : 효자1동   25347 ----------


 ---------- 2018-09-22 21:00:00 : 효자1동   25349 ----------


 ---------- 2018-09-22 22:00:00 : 동내면   25350 ----------


 ---------- 2018-09-22 23:00:00 : 조운동   25351 ----------


 ---------- 2018-09-23 04:00:00 : 석사동   25352 ----------


 ---------- 2018-09-23 08:00:00 : 신북읍   25353 ----------


 ---------- 2018-09-23 12:00:00 : 석사동   25354 ----------


 ---------- 2018-09-23 16:00:00 : 근화동   25355 ----------


 ---------- 2018-09-23 17:00:00 : 동내면   25356 ----------


 ---------- 2018-09-23 20:00:00 : 석사동   25357 ----------


 ---------- 2018-09-23 22:00:00 : 효자1동   25358 ----------


 ---------- 2018-09-24 02:00:00 : 후평1동   25359 ----------


 ---------- 2018-09-24 09:00:00 : 신북읍   25360 ----------


 ---------- 2018-09-24 10:00:00 : 남산면   25364 ----------


 ---------- 2018-09-24 12:00:00 : 강남동   25365 ----------


 ---------- 2018-09-24 12:00:00 : 동내면   25366 ----------


 ---------- 2018-09-24 13:00:00 : 강남동   25367 ----------


 ---------- 2018-09-24 15:00:00 : 남  면   25368 ----------


 ---------- 2018-09-24 16:00:00 : 남  면   25369 ----------


 ---------- 2018-09-24 16:00:00 : 후평1동   25370 ----------


 ---------- 2018-09-24 17:00:00 : 석사동   25372 ----------


 ---------- 2018-09-24 18:00:00 : 석사동   25373 ----------


 ---------- 2018-09-24 20:00:00 : 동내면   25374 ----------


 ---------- 2018-09-25 01:00:00 : 근화동   25375 ----------


 ---------- 2018-09-25 04:00:00 : 석사동   25376 ----------


 ---------- 2018-09-25 10:00:00 : 석사동   25378 ----------


 ---------- 2018-09-25 10:00:00 : 효자1동   25379 ----------


 ---------- 2018-09-25 16:00:00 : 석사동   25380 ----------


 ---------- 2018-09-25 17:00:00 : 동산면   25381 ----------


 ---------- 2018-09-25 20:00:00 : 동산면   25383 ----------


 ---------- 2018-09-26 00:00:00 : 후평1동   25384 ----------


 ---------- 2018-09-26 01:00:00 : 교  동   25385 ----------


 ---------- 2018-09-26 04:00:00 : 동내면   25386 ----------


 ---------- 2018-09-26 09:00:00 : 퇴계동   25388 ----------


 ---------- 2018-09-26 10:00:00 : 남  면   25389 ----------


 ---------- 2018-09-26 10:00:00 : 퇴계동   25390 ----------


 ---------- 2018-09-26 11:00:00 : 석사동   25391 ----------


 ---------- 2018-09-26 13:00:00 : 후평1동   25392 ----------


 ---------- 2018-09-26 14:00:00 : 남  면   25393 ----------


 ---------- 2018-09-26 15:00:00 : 남  면   25394 ----------


 ---------- 2018-09-26 17:00:00 : 사북면   25395 ----------


 ---------- 2018-09-26 19:00:00 : 남  면   25396 ----------


 ---------- 2018-09-26 19:00:00 : 후평1동   25397 ----------


 ---------- 2018-09-27 04:00:00 : 후평1동   25398 ----------


 ---------- 2018-09-27 09:00:00 : 신북읍   25399 ----------


 ---------- 2018-09-27 10:00:00 : 북산면   25400 ----------


 ---------- 2018-09-27 10:00:00 : 동산면   25401 ----------


 ---------- 2018-09-27 11:00:00 : 사북면   25402 ----------


 ---------- 2018-09-27 14:00:00 : 신사우동   25403 ----------


 ---------- 2018-09-27 17:00:00 : 강남동   25404 ----------


 ---------- 2018-09-27 19:00:00 : 효자1동   25405 ----------


 ---------- 2018-09-28 11:00:00 : 후평1동   25406 ----------


 ---------- 2018-09-28 13:00:00 : 동산면   25407 ----------


 ---------- 2018-09-28 14:00:00 : 신사우동   25408 ----------


 ---------- 2018-09-28 15:00:00 : 신북읍   25409 ----------


 ---------- 2018-09-28 15:00:00 : 동  면   25410 ----------


 ---------- 2018-09-28 16:00:00 : 강남동   25411 ----------


 ---------- 2018-09-28 18:00:00 : 동내면   25412 ----------


 ---------- 2018-09-28 22:00:00 : 효자1동   25413 ----------


 ---------- 2018-09-29 09:00:00 : 남  면   25414 ----------


 ---------- 2018-09-29 10:00:00 : 신사우동   25415 ----------


 ---------- 2018-09-29 11:00:00 : 동  면   25416 ----------


 ---------- 2018-09-29 12:00:00 : 사북면   25417 ----------


 ---------- 2018-09-29 12:00:00 : 북산면   25419 ----------


 ---------- 2018-09-29 13:00:00 : 동  면   25420 ----------


 ---------- 2018-09-29 13:00:00 : 퇴계동   25422 ----------


 ---------- 2018-09-29 13:00:00 : 북산면   25423 ----------


 ---------- 2018-09-29 13:00:00 : 교  동   25424 ----------


 ---------- 2018-09-29 14:00:00 : 사북면   25425 ----------


 ---------- 2018-09-29 15:00:00 : 남산면   25426 ----------


 ---------- 2018-09-29 16:00:00 : 동내면   25427 ----------


 ---------- 2018-09-29 16:00:00 : 신사우동   25428 ----------


 ---------- 2018-09-29 17:00:00 : 서  면   25429 ----------


 ---------- 2018-09-29 18:00:00 : 강남동   25430 ----------


 ---------- 2018-09-29 21:00:00 : 효자1동   25431 ----------


 ---------- 2018-09-29 23:00:00 : 교  동   25432 ----------


 ---------- 2018-09-30 08:00:00 : 남산면   25433 ----------


 ---------- 2018-09-30 09:00:00 : 북산면   25434 ----------


 ---------- 2018-09-30 12:00:00 : 퇴계동   25435 ----------


 ---------- 2018-09-30 13:00:00 : 신북읍   25436 ----------


 ---------- 2018-09-30 15:00:00 : 신북읍   25437 ----------


 ---------- 2018-09-30 17:00:00 : 동  면   25438 ----------


 ---------- 2018-09-30 20:00:00 : 강남동   25440 ----------


 ---------- 2018-09-30 23:00:00 : 강남동   25442 ----------


 ---------- 2018-09-30 23:00:00 : 효자1동   25444 ----------


 ---------- 2018-10-01 01:00:00 : 신사우동   25445 ----------


 ---------- 2018-10-01 08:00:00 : 남산면   25446 ----------


 ---------- 2018-10-01 10:00:00 : 남산면   25447 ----------


 ---------- 2018-10-01 13:00:00 : 강남동   25448 ----------


 ---------- 2018-10-01 13:00:00 : 사북면   25449 ----------


 ---------- 2018-10-01 13:00:00 : 남산면   25450 ----------


 ---------- 2018-10-01 15:00:00 : 북산면   25454 ----------


 ---------- 2018-10-01 16:00:00 : 북산면   25456 ----------

 ---------- 2018-10-01 18:00:00 : 동  면   25457 ----------


 ---------- 2018-10-01 19:00:00 : 소양동   25458 ----------


 ---------- 2018-10-02 00:00:00 : 동산면   25459 ----------


 ---------- 2018-10-02 01:00:00 : 신동면   25460 ----------


 ---------- 2018-10-02 07:00:00 : 남  면   25461 ----------


 ---------- 2018-10-02 07:00:00 : 근화동   25462 ----------


 ---------- 2018-10-02 09:00:00 : 근화동   25463 ----------


 ---------- 2018-10-02 09:00:00 : 교  동   25464 ----------


 ---------- 2018-10-02 10:00:00 : 효자1동   25465 ----------


 ---------- 2018-10-02 11:00:00 : 후평1동   25466 ----------


 ---------- 2018-10-02 12:00:00 : 남산면   25467 ----------


 ---------- 2018-10-02 14:00:00 : 서  면   25469 ----------


 ---------- 2018-10-03 07:00:00 : 후평1동   25470 ----------


 ---------- 2018-10-03 08:00:00 : 신동면   25473 ----------


 ---------- 2018-10-03 10:00:00 : 소양동   25474 ----------


 ---------- 2018-10-03 11:00:00 : 강남동   25476 ----------


 ---------- 2018-10-03 14:00:00 : 신사우동   25478 ----------


 ---------- 2018-10-03 15:00:00 : 동내면   25479 ----------


 ---------- 2018-10-03 17:00:00 : 남  면   25480 ----------


 ---------- 2018-10-03 20:00:00 : 동내면   25481 ----------


 ---------- 2018-10-03 20:00:00 : 효자1동   25482 ----------


 ---------- 2018-10-04 01:00:00 : 신동면   25483 ----------


 ---------- 2018-10-04 02:00:00 : 조운동   25484 ----------


 ---------- 2018-10-04 08:00:00 : 효자1동   25486 ----------


 ---------- 2018-10-04 08:00:00 : 동산면   25487 ----------


 ---------- 2018-10-04 09:00:00 : 남  면   25490 ----------


 ---------- 2018-10-04 10:00:00 : 남  면   25491 ----------


 ---------- 2018-10-04 10:00:00 : 후평1동   25492 ----------


 ---------- 2018-10-04 11:00:00 : 동  면   25493 ----------


 ---------- 2018-10-04 12:00:00 : 서  면   25497 ----------


 ---------- 2018-10-04 12:00:00 : 효자1동   25499 ----------


 ---------- 2018-10-04 13:00:00 : 남  면   25500 ----------


 ---------- 2018-10-04 13:00:00 : 후평1동   25501 ----------


 ---------- 2018-10-04 13:00:00 : 퇴계동   25502 ----------


 ---------- 2018-10-04 14:00:00 : 동내면   25503 ----------


 ---------- 2018-10-04 15:00:00 : 서  면   25504 ----------


 ---------- 2018-10-05 13:00:00 : 사북면   25505 ----------


 ---------- 2018-10-05 16:00:00 : 근화동   25507 ----------


 ---------- 2018-10-05 18:00:00 : 동  면   25508 ----------


 ---------- 2018-10-06 07:00:00 : 동  면   25509 ----------


 ---------- 2018-10-06 08:00:00 : 석사동   25512 ----------


 ---------- 2018-10-06 08:00:00 : 동산면   25513 ----------


 ---------- 2018-10-06 09:00:00 : 동산면   25517 ----------


 ---------- 2018-10-06 11:00:00 : 후평1동   25518 ----------


 ---------- 2018-10-06 18:00:00 : 남  면   25519 ----------


 ---------- 2018-10-07 02:00:00 : 소양동   25520 ----------


 ---------- 2018-10-07 06:00:00 : 석사동   25521 ----------


 ---------- 2018-10-07 08:00:00 : 동내면   25522 ----------


 ---------- 2018-10-07 08:00:00 : 신사우동   25523 ----------


 ---------- 2018-10-07 10:00:00 : 서  면   25524 ----------


 ---------- 2018-10-07 10:00:00 : 남산면   25526 ----------


 ---------- 2018-10-07 11:00:00 : 석사동   25527 ----------


 ---------- 2018-10-07 11:00:00 : 강남동   25528 ----------


 ---------- 2018-10-07 11:00:00 : 서  면   25530 ----------


 ---------- 2018-10-07 12:00:00 : 사북면   25531 ----------


 ---------- 2018-10-07 15:00:00 : 서  면   25532 ----------


 ---------- 2018-10-07 15:00:00 : 동  면   25533 ----------


 ---------- 2018-10-07 20:00:00 : 남  면   25534 ----------


 ---------- 2018-10-08 13:00:00 : 효자1동   25535 ----------


 ---------- 2018-10-08 15:00:00 : 효자1동   25536 ----------


 ---------- 2018-10-09 04:00:00 : 후평1동   25538 ----------


 ---------- 2018-10-09 09:00:00 : 근화동   25539 ----------


 ---------- 2018-10-09 10:00:00 : 신사우동   25540 ----------


 ---------- 2018-10-09 12:00:00 : 동내면   25541 ----------


 ---------- 2018-10-09 12:00:00 : 신사우동   25542 ----------


 ---------- 2018-10-09 17:00:00 : 동  면   25543 ----------


 ---------- 2018-10-10 01:00:00 : 신동면   25544 ----------


 ---------- 2018-10-10 05:00:00 : 석사동   25545 ----------


 ---------- 2018-10-10 08:00:00 : 동내면   25547 ----------


 ---------- 2018-10-10 13:00:00 : 후평1동   25548 ----------


 ---------- 2018-10-10 18:00:00 : 후평1동   25549 ----------


 ---------- 2018-10-10 20:00:00 : 후평1동   25550 ----------


 ---------- 2018-10-10 21:00:00 : 동내면   25551 ----------


 ---------- 2018-10-11 16:00:00 : 신사우동   25553 ----------


 ---------- 2018-10-11 17:00:00 : 조운동   25554 ----------


 ---------- 2018-10-12 08:00:00 : 석사동   25555 ----------


 ---------- 2018-10-12 12:00:00 : 남산면   25556 ----------


 ---------- 2018-10-12 13:00:00 : 퇴계동   25559 ----------


 ---------- 2018-10-12 17:00:00 : 근화동   25560 ----------


 ---------- 2018-10-12 17:00:00 : 후평1동   25561 ----------


 ---------- 2018-10-12 18:00:00 : 근화동   25562 ----------


 ---------- 2018-10-13 10:00:00 : 근화동   25564 ----------


 ---------- 2018-10-13 12:00:00 : 신북읍   25565 ----------


 ---------- 2018-10-13 13:00:00 : 동내면   25566 ----------


 ---------- 2018-10-13 14:00:00 : 효자1동   25567 ----------


 ---------- 2018-10-13 15:00:00 : 강남동   25569 ----------


 ---------- 2018-10-13 19:00:00 : 소양동   25571 ----------


 ---------- 2018-10-13 22:00:00 : 남  면   25573 ----------


 ---------- 2018-10-14 07:00:00 : 석사동   25574 ----------


 ---------- 2018-10-14 07:00:00 : 서  면   25576 ----------


 ---------- 2018-10-14 13:00:00 : 신사우동   25577 ----------


 ---------- 2018-10-14 14:00:00 : 서  면   25578 ----------


 ---------- 2018-10-14 14:00:00 : 남  면   25579 ----------


 ---------- 2018-10-15 08:00:00 : 신사우동   25580 ----------


 ---------- 2018-10-15 11:00:00 : 신동면   25583 ----------


 ---------- 2018-10-15 12:00:00 : 석사동   25584 ----------


 ---------- 2018-10-15 12:00:00 : 서  면   25585 ----------


 ---------- 2018-10-15 12:00:00 : 동내면   25586 ----------


 ---------- 2018-10-15 12:00:00 : 남산면   25588 ----------


 ---------- 2018-10-15 13:00:00 : 서  면   25589 ----------


 ---------- 2018-10-15 13:00:00 : 남산면   25590 ----------


 ---------- 2018-10-15 13:00:00 : 후평1동   25591 ----------


 ---------- 2018-10-15 14:00:00 : 사북면   25592 ----------


 ---------- 2018-10-15 15:00:00 : 강남동   25593 ----------


 ---------- 2018-10-15 16:00:00 : 남산면   25594 ----------


 ---------- 2018-10-15 23:00:00 : 후평1동   25595 ----------


 ---------- 2018-10-16 08:00:00 : 석사동   25596 ----------


 ---------- 2018-10-16 09:00:00 : 신동면   25598 ----------


 ---------- 2018-10-16 10:00:00 : 퇴계동   25599 ----------


 ---------- 2018-10-16 11:00:00 : 남  면   25600 ----------


 ---------- 2018-10-16 12:00:00 : 동내면   25601 ----------


 ---------- 2018-10-16 13:00:00 : 사북면   25602 ----------


 ---------- 2018-10-16 13:00:00 : 동내면   25603 ----------


 ---------- 2018-10-16 13:00:00 : 동  면   25605 ----------


 ---------- 2018-10-16 14:00:00 : 남산면   25606 ----------


 ---------- 2018-10-16 14:00:00 : 퇴계동   25608 ----------


 ---------- 2018-10-16 15:00:00 : 동  면   25609 ----------


 ---------- 2018-10-16 17:00:00 : 동  면   25610 ----------


 ---------- 2018-10-16 21:00:00 : 동  면   25611 ----------


 ---------- 2018-10-17 00:00:00 : 신동면   25612 ----------


 ---------- 2018-10-17 10:00:00 : 강남동   25613 ----------


 ---------- 2018-10-17 13:00:00 : 강남동   25614 ----------


 ---------- 2018-10-17 13:00:00 : 동내면   25615 ----------


 ---------- 2018-10-17 13:00:00 : 동  면   25616 ----------


 ---------- 2018-10-17 13:00:00 : 퇴계동   25618 ----------


 ---------- 2018-10-17 14:00:00 : 석사동   25619 ----------


 ---------- 2018-10-17 14:00:00 : 퇴계동   25620 ----------


 ---------- 2018-10-17 16:00:00 : 동  면   25621 ----------


 ---------- 2018-10-17 16:00:00 : 교  동   25622 ----------


 ---------- 2018-10-17 18:00:00 : 서  면   25623 ----------


 ---------- 2018-10-18 12:00:00 : 동  면   25624 ----------


 ---------- 2018-10-18 14:00:00 : 남산면   25626 ----------


 ---------- 2018-10-18 16:00:00 : 동내면   25627 ----------


 ---------- 2018-10-18 22:00:00 : 석사동   25628 ----------


 ---------- 2018-10-19 03:00:00 : 강남동   25629 ----------


 ---------- 2018-10-19 03:00:00 : 효자1동   25631 ----------

 ---------- 2018-10-19 09:00:00 : 근화동   25632 ----------


 ---------- 2018-10-19 10:00:00 : 후평1동   25633 ----------


 ---------- 2018-10-19 11:00:00 : 서  면   25634 ----------


 ---------- 2018-10-19 12:00:00 : 남산면   25637 ----------


 ---------- 2018-10-19 15:00:00 : 사북면   25638 ----------


 ---------- 2018-10-19 15:00:00 : 퇴계동   25639 ----------


 ---------- 2018-10-19 19:00:00 : 신사우동   25640 ----------


 ---------- 2018-10-20 05:00:00 : 효자1동   25641 ----------


 ---------- 2018-10-20 09:00:00 : 신북읍   25642 ----------


 ---------- 2018-10-20 09:00:00 : 후평1동   25643 ----------


 ---------- 2018-10-20 14:00:00 : 신사우동   25644 ----------


 ---------- 2018-10-20 16:00:00 : 석사동   25645 ----------


 ---------- 2018-10-20 16:00:00 : 퇴계동   25646 ----------


 ---------- 2018-10-20 18:00:00 : 신사우동   25647 ----------


 ---------- 2018-10-21 03:00:00 : 후평1동   25648 ----------


 ---------- 2018-10-21 08:00:00 : 효자1동   25650 ----------


 ---------- 2018-10-21 08:00:00 : 약사명동   25652 ----------


 ---------- 2018-10-21 08:00:00 : 조운동   25654 ----------


 ---------- 2018-10-21 10:00:00 : 조운동   25655 ----------


 ---------- 2018-10-21 11:00:00 : 서  면   25656 ----------


 ---------- 2018-10-21 12:00:00 : 석사동   25658 ----------


 ---------- 2018-10-21 12:00:00 : 서  면   25659 ----------


 ---------- 2018-10-21 13:00:00 : 조운동   25660 ----------


 ---------- 2018-10-21 23:00:00 : 동  면   25661 ----------


 ---------- 2018-10-22 02:00:00 : 퇴계동   25662 ----------


 ---------- 2018-10-22 08:00:00 : 효자1동   25663 ----------


 ---------- 2018-10-22 13:00:00 : 강남동   25664 ----------


 ---------- 2018-10-22 15:00:00 : 강남동   25665 ----------


 ---------- 2018-10-23 00:00:00 : 퇴계동   25666 ----------


 ---------- 2018-10-23 10:00:00 : 강남동   25667 ----------


 ---------- 2018-10-23 17:00:00 : 효자1동   25668 ----------


 ---------- 2018-10-23 20:00:00 : 석사동   25669 ----------


 ---------- 2018-10-24 07:00:00 : 신사우동   25670 ----------


 ---------- 2018-10-24 14:00:00 : 동내면   25671 ----------


 ---------- 2018-10-24 15:00:00 : 동내면   25672 ----------


 ---------- 2018-10-24 16:00:00 : 후평1동   25673 ----------


 ---------- 2018-10-24 17:00:00 : 후평1동   25674 ----------


 ---------- 2018-10-24 18:00:00 : 동  면   25675 ----------


 ---------- 2018-10-24 19:00:00 : 강남동   25676 ----------


 ---------- 2018-10-25 14:00:00 : 신사우동   25677 ----------


 ---------- 2018-10-25 14:00:00 : 조운동   25678 ----------


 ---------- 2018-10-25 16:00:00 : 남산면   25679 ----------


 ---------- 2018-10-25 17:00:00 : 남산면   25680 ----------


 ---------- 2018-10-25 19:00:00 : 동내면   25681 ----------


 ---------- 2018-10-26 12:00:00 : 신동면   25682 ----------


 ---------- 2018-10-26 22:00:00 : 퇴계동   25683 ----------


 ---------- 2018-10-27 04:00:00 : 효자1동   25685 ----------


 ---------- 2018-10-27 14:00:00 : 남  면   25688 ----------


 ---------- 2018-10-27 17:00:00 : 후평1동   25689 ----------


 ---------- 2018-10-27 19:00:00 : 신북읍   25690 ----------


 ---------- 2018-10-27 23:00:00 : 석사동   25691 ----------


 ---------- 2018-10-28 00:00:00 : 교  동   25692 ----------


 ---------- 2018-10-28 03:00:00 : 효자1동   25695 ----------


 ---------- 2018-10-28 18:00:00 : 신사우동   25696 ----------


 ---------- 2018-10-29 08:00:00 : 강남동   25697 ----------


 ---------- 2018-10-29 13:00:00 : 서  면   25698 ----------


 ---------- 2018-10-29 14:00:00 : 소양동   25700 ----------


 ---------- 2018-10-29 15:00:00 : 남산면   25702 ----------


 ---------- 2018-10-30 00:00:00 : 신사우동   25703 ----------


 ---------- 2018-10-30 06:00:00 : 후평1동   25704 ----------


 ---------- 2018-10-30 07:00:00 : 신동면   25705 ----------


 ---------- 2018-10-30 08:00:00 : 동  면   25706 ----------


 ---------- 2018-10-30 09:00:00 : 신사우동   25707 ----------


 ---------- 2018-10-30 13:00:00 : 서  면   25708 ----------


 ---------- 2018-10-30 15:00:00 : 소양동   25710 ----------


 ---------- 2018-10-30 17:00:00 : 동  면   25711 ----------


 ---------- 2018-10-31 07:00:00 : 효자1동   25714 ----------


 ---------- 2018-10-31 10:00:00 : 강남동   25715 ----------


 ---------- 2018-10-31 15:00:00 : 효자1동   25716 ----------


 ---------- 2018-10-31 16:00:00 : 신사우동   25717 ----------


 ---------- 2018-10-31 17:00:00 : 효자1동   25718 ----------


 ---------- 2018-10-31 18:00:00 : 석사동   25720 ----------


 ---------- 2018-11-01 09:00:00 : 강남동   25721 ----------


 ---------- 2018-11-01 15:00:00 : 동내면   25722 ----------


 ---------- 2018-11-01 18:00:00 : 동내면   25723 ----------


 ---------- 2018-11-01 23:00:00 : 후평1동   25724 ----------


 ---------- 2018-11-02 09:00:00 : 동내면   25725 ----------


 ---------- 2018-11-02 14:00:00 : 동내면   25726 ----------


 ---------- 2018-11-02 17:00:00 : 동내면   25729 ----------


 ---------- 2018-11-02 19:00:00 : 동내면   25731 ----------


 ---------- 2018-11-03 04:00:00 : 신북읍   25732 ----------


 ---------- 2018-11-03 06:00:00 : 신사우동   25733 ----------


 ---------- 2018-11-03 14:00:00 : 신사우동   25734 ----------


 ---------- 2018-11-03 16:00:00 : 석사동   25736 ----------


 ---------- 2018-11-03 17:00:00 : 근화동   25737 ----------


 ---------- 2018-11-03 22:00:00 : 석사동   25738 ----------


 ---------- 2018-11-04 14:00:00 : 신북읍   25739 ----------


 ---------- 2018-11-04 18:00:00 : 서  면   25741 ----------


 ---------- 2018-11-04 19:00:00 : 신동면   25743 ----------


 ---------- 2018-11-04 23:00:00 : 조운동   25744 ----------


 ---------- 2018-11-05 08:00:00 : 석사동   25745 ----------


 ---------- 2018-11-05 11:00:00 : 효자1동   25746 ----------


 ---------- 2018-11-05 11:00:00 : 남산면   25748 ----------


 ---------- 2018-11-05 12:00:00 : 남  면   25749 ----------


 ---------- 2018-11-05 13:00:00 : 동  면   25750 ----------


 ---------- 2018-11-05 14:00:00 : 동  면   25751 ----------


 ---------- 2018-11-05 15:00:00 : 후평1동   25752 ----------


 ---------- 2018-11-06 05:00:00 : 동  면   25753 ----------


 ---------- 2018-11-06 09:00:00 : 신사우동   25754 ----------


 ---------- 2018-11-06 13:00:00 : 동내면   25756 ----------


 ---------- 2018-11-06 17:00:00 : 신북읍   25757 ----------


 ---------- 2018-11-07 01:00:00 : 효자1동   25760 ----------


 ---------- 2018-11-07 02:00:00 : 퇴계동   25762 ----------


 ---------- 2018-11-07 16:00:00 : 신사우동   25763 ----------


 ---------- 2018-11-07 16:00:00 : 후평1동   25764 ----------


 ---------- 2018-11-07 19:00:00 : 후평1동   25765 ----------


 ---------- 2018-11-07 20:00:00 : 후평1동   25766 ----------


 ---------- 2018-11-08 05:00:00 : 동  면   25767 ----------


 ---------- 2018-11-08 14:00:00 : 석사동   25768 ----------


 ---------- 2018-11-09 07:00:00 : 근화동   25769 ----------


 ---------- 2018-11-09 14:00:00 : 후평1동   25770 ----------


 ---------- 2018-11-09 15:00:00 : 신동면   25771 ----------


 ---------- 2018-11-09 20:00:00 : 남산면   25772 ----------


 ---------- 2018-11-09 20:00:00 : 후평1동   25773 ----------


 ---------- 2018-11-10 08:00:00 : 약사명동   25774 ----------


 ---------- 2018-11-10 12:00:00 : 효자1동   25775 ----------


 ---------- 2018-11-10 14:00:00 : 신북읍   25776 ----------


 ---------- 2018-11-10 16:00:00 : 사북면   25777 ----------


 ---------- 2018-11-10 18:00:00 : 효자1동   25778 ----------


 ---------- 2018-11-10 20:00:00 : 근화동   25779 ----------


 ---------- 2018-11-10 21:00:00 : 석사동   25781 ----------


 ---------- 2018-11-10 22:00:00 : 신사우동   25782 ----------


 ---------- 2018-11-10 23:00:00 : 교  동   25784 ----------


 ---------- 2018-11-11 06:00:00 : 효자1동   25785 ----------


 ---------- 2018-11-11 17:00:00 : 사북면   25786 ----------


 ---------- 2018-11-11 19:00:00 : 효자1동   25788 ----------


 ---------- 2018-11-12 07:00:00 : 신사우동   25789 ----------


 ---------- 2018-11-12 08:00:00 : 동  면   25790 ----------


 ---------- 2018-11-12 12:00:00 : 서  면   25791 ----------


 ---------- 2018-11-12 15:00:00 : 퇴계동   25792 ----------


 ---------- 2018-11-12 16:00:00 : 소양동   25794 ----------


 ---------- 2018-11-12 17:00:00 : 후평1동   25795 ----------


 ---------- 2018-11-12 19:00:00 : 석사동   25796 ----------


 ---------- 2018-11-13 00:00:00 : 동내면   25797 ----------


 ---------- 2018-11-13 03:00:00 : 후평1동   25799 ----------


 ---------- 2018-11-13 09:00:00 : 동내면   25800 ----------

 ---------- 2018-11-13 11:00:00 : 근화동   25802 ----------


 ---------- 2018-11-13 13:00:00 : 효자1동   25803 ----------


 ---------- 2018-11-13 15:00:00 : 동  면   25804 ----------


 ---------- 2018-11-14 01:00:00 : 효자1동   25805 ----------


 ---------- 2018-11-14 07:00:00 : 약사명동   25806 ----------


 ---------- 2018-11-14 07:00:00 : 후평1동   25807 ----------


 ---------- 2018-11-14 14:00:00 : 서  면   25809 ----------


 ---------- 2018-11-14 14:00:00 : 근화동   25810 ----------


 ---------- 2018-11-14 15:00:00 : 신북읍   25811 ----------


 ---------- 2018-11-14 15:00:00 : 소양동   25812 ----------


 ---------- 2018-11-14 17:00:00 : 서  면   25813 ----------


 ---------- 2018-11-14 18:00:00 : 남산면   25815 ----------


 ---------- 2018-11-15 05:00:00 : 동내면   25816 ----------


 ---------- 2018-11-15 07:00:00 : 신동면   25818 ----------


 ---------- 2018-11-15 09:00:00 : 사북면   25819 ----------


 ---------- 2018-11-15 13:00:00 : 후평1동   25820 ----------


 ---------- 2018-11-15 15:00:00 : 북산면   25822 ----------


 ---------- 2018-11-15 17:00:00 : 신동면   25823 ----------


 ---------- 2018-11-16 05:00:00 : 효자1동   25824 ----------


 ---------- 2018-11-16 08:00:00 : 신사우동   25825 ----------


 ---------- 2018-11-16 10:00:00 : 남산면   25829 ----------


 ---------- 2018-11-16 14:00:00 : 동산면   25830 ----------


 ---------- 2018-11-16 17:00:00 : 후평1동   25831 ----------


 ---------- 2018-11-16 22:00:00 : 동산면   25832 ----------


 ---------- 2018-11-17 00:00:00 : 동내면   25833 ----------


 ---------- 2018-11-17 03:00:00 : 강남동   25835 ----------


 ---------- 2018-11-17 16:00:00 : 남  면   25836 ----------


 ---------- 2018-11-17 16:00:00 : 신사우동   25837 ----------


 ---------- 2018-11-17 17:00:00 : 강남동   25838 ----------


 ---------- 2018-11-18 10:00:00 : 후평1동   25839 ----------


 ---------- 2018-11-18 11:00:00 : 북산면   25840 ----------


 ---------- 2018-11-18 13:00:00 : 사북면   25841 ----------


 ---------- 2018-11-18 13:00:00 : 퇴계동   25842 ----------


 ---------- 2018-11-18 13:00:00 : 북산면   25843 ----------


 ---------- 2018-11-19 04:00:00 : 석사동   25844 ----------


 ---------- 2018-11-19 09:00:00 : 강남동   25845 ----------


 ---------- 2018-11-19 17:00:00 : 강남동   25846 ----------


 ---------- 2018-11-19 18:00:00 : 동  면   25847 ----------


 ---------- 2018-11-19 23:00:00 : 퇴계동   25849 ----------


 ---------- 2018-11-20 09:00:00 : 조운동   25850 ----------


 ---------- 2018-11-20 10:00:00 : 석사동   25852 ----------


 ---------- 2018-11-20 11:00:00 : 근화동   25854 ----------


 ---------- 2018-11-20 16:00:00 : 신사우동   25855 ----------


 ---------- 2018-11-20 20:00:00 : 신사우동   25856 ----------


 ---------- 2018-11-21 02:00:00 : 석사동   25857 ----------


 ---------- 2018-11-21 06:00:00 : 석사동   25858 ----------


 ---------- 2018-11-21 06:00:00 : 효자1동   25859 ----------


 ---------- 2018-11-21 07:00:00 : 후평1동   25860 ----------


 ---------- 2018-11-21 14:00:00 : 동  면   25861 ----------


 ---------- 2018-11-21 15:00:00 : 동  면   25862 ----------


 ---------- 2018-11-21 18:00:00 : 신북읍   25863 ----------


 ---------- 2018-11-21 21:00:00 : 강남동   25865 ----------


 ---------- 2018-11-21 22:00:00 : 효자1동   25866 ----------


 ---------- 2018-11-22 00:00:00 : 효자1동   25867 ----------


 ---------- 2018-11-22 09:00:00 : 신사우동   25868 ----------


 ---------- 2018-11-22 12:00:00 : 동내면   25869 ----------


 ---------- 2018-11-22 12:00:00 : 동산면   25870 ----------


 ---------- 2018-11-22 17:00:00 : 동  면   25871 ----------


 ---------- 2018-11-22 18:00:00 : 신북읍   25872 ----------


 ---------- 2018-11-22 18:00:00 : 소양동   25873 ----------


 ---------- 2018-11-22 21:00:00 : 퇴계동   25874 ----------


 ---------- 2018-11-22 23:00:00 : 효자1동   25875 ----------


 ---------- 2018-11-23 07:00:00 : 퇴계동   25876 ----------


 ---------- 2018-11-23 07:00:00 : 동산면   25878 ----------


 ---------- 2018-11-23 09:00:00 : 신동면   25879 ----------


 ---------- 2018-11-23 12:00:00 : 동산면   25880 ----------


 ---------- 2018-11-23 16:00:00 : 후평1동   25881 ----------


 ---------- 2018-11-23 20:00:00 : 서  면   25883 ----------


 ---------- 2018-11-23 21:00:00 : 신북읍   25886 ----------


 ---------- 2018-11-23 22:00:00 : 석사동   25887 ----------


 ---------- 2018-11-24 00:00:00 : 퇴계동   25888 ----------


 ---------- 2018-11-24 07:00:00 : 신북읍   25889 ----------


 ---------- 2018-11-24 10:00:00 : 신북읍   25890 ----------


 ---------- 2018-11-24 14:00:00 : 동내면   25891 ----------


 ---------- 2018-11-24 15:00:00 : 퇴계동   25893 ----------


 ---------- 2018-11-25 01:00:00 : 서  면   25894 ----------


 ---------- 2018-11-25 12:00:00 : 후평1동   25895 ----------


 ---------- 2018-11-25 13:00:00 : 효자1동   25896 ----------


 ---------- 2018-11-25 21:00:00 : 후평1동   25897 ----------


 ---------- 2018-11-26 04:00:00 : 석사동   25898 ----------


 ---------- 2018-11-26 07:00:00 : 신동면   25899 ----------


 ---------- 2018-11-26 11:00:00 : 조운동   25900 ----------


 ---------- 2018-11-26 13:00:00 : 남산면   25901 ----------


 ---------- 2018-11-26 15:00:00 : 석사동   25902 ----------


 ---------- 2018-11-26 16:00:00 : 후평1동   25904 ----------


 ---------- 2018-11-26 23:00:00 : 소양동   25905 ----------


 ---------- 2018-11-27 05:00:00 : 신북읍   25906 ----------


 ---------- 2018-11-27 09:00:00 : 동산면   25907 ----------


 ---------- 2018-11-27 18:00:00 : 약사명동   25909 ----------


 ---------- 2018-11-27 21:00:00 : 석사동   25910 ----------


 ---------- 2018-11-27 23:00:00 : 후평1동   25911 ----------


 ---------- 2018-11-28 11:00:00 : 후평1동   25912 ----------


 ---------- 2018-11-28 11:00:00 : 퇴계동   25913 ----------


 ---------- 2018-11-28 14:00:00 : 동산면   25914 ----------


 ---------- 2018-11-28 15:00:00 : 석사동   25915 ----------


 ---------- 2018-11-29 12:00:00 : 효자1동   25916 ----------


 ---------- 2018-11-29 12:00:00 : 신북읍   25917 ----------


 ---------- 2018-11-29 13:00:00 : 신동면   25918 ----------


 ---------- 2018-11-29 22:00:00 : 퇴계동   25920 ----------


 ---------- 2018-11-30 12:00:00 : 퇴계동   25921 ----------


 ---------- 2018-12-01 03:00:00 : 교  동   25922 ----------


 ---------- 2018-12-01 04:00:00 : 석사동   25923 ----------


 ---------- 2018-12-01 04:00:00 : 효자1동   25924 ----------


 ---------- 2018-12-01 08:00:00 : 동산면   25926 ----------


 ---------- 2018-12-01 11:00:00 : 강남동   25928 ----------


 ---------- 2018-12-01 14:00:00 : 강남동   25930 ----------


 ---------- 2018-12-01 15:00:00 : 소양동   25932 ----------


 ---------- 2018-12-01 16:00:00 : 서  면   25933 ----------


 ---------- 2018-12-01 18:00:00 : 신동면   25936 ----------


 ---------- 2018-12-01 18:00:00 : 조운동   25938 ----------


 ---------- 2018-12-01 19:00:00 : 서  면   25939 ----------


 ---------- 2018-12-01 20:00:00 : 소양동   25940 ----------


 ---------- 2018-12-01 20:00:00 : 동  면   25941 ----------


 ---------- 2018-12-01 21:00:00 : 신사우동   25942 ----------


 ---------- 2018-12-01 23:00:00 : 석사동   25944 ----------


 ---------- 2018-12-01 23:00:00 : 퇴계동   25945 ----------


 ---------- 2018-12-02 02:00:00 : 서  면   25946 ----------


 ---------- 2018-12-02 13:00:00 : 동산면   25947 ----------


 ---------- 2018-12-02 16:00:00 : 사북면   25948 ----------


 ---------- 2018-12-02 19:00:00 : 사북면   25949 ----------


 ---------- 2018-12-02 21:00:00 : 강남동   25950 ----------


 ---------- 2018-12-03 07:00:00 : 서  면   25952 ----------


 ---------- 2018-12-03 08:00:00 : 효자1동   25953 ----------


 ---------- 2018-12-03 10:00:00 : 후평1동   25954 ----------


 ---------- 2018-12-03 13:00:00 : 석사동   25957 ----------


 ---------- 2018-12-03 17:00:00 : 효자1동   25960 ----------


 ---------- 2018-12-03 19:00:00 : 강남동   25962 ----------


 ---------- 2018-12-03 21:00:00 : 후평1동   25963 ----------


 ---------- 2018-12-04 00:00:00 : 석사동   25964 ----------


 ---------- 2018-12-04 05:00:00 : 동내면   25967 ----------


 ---------- 2018-12-04 09:00:00 : 후평1동   25968 ----------


 ---------- 2018-12-04 11:00:00 : 서  면   25969 ----------


 ---------- 2018-12-04 16:00:00 : 후평1동   25971 ----------


 ---------- 2018-12-05 11:00:00 : 후평1동   25972 ----------


 ---------- 2018-12-05 20:00:00 : 소양동   25975 ----------


 ---------- 2018-12-05 20:00:00 : 후평1동   25977 ----------

 ---------- 2018-12-06 05:00:00 : 효자1동   25978 ----------


 ---------- 2018-12-06 11:00:00 : 강남동   25979 ----------


 ---------- 2018-12-06 11:00:00 : 근화동   25981 ----------


 ---------- 2018-12-06 11:00:00 : 퇴계동   25982 ----------


 ---------- 2018-12-06 13:00:00 : 신북읍   25983 ----------


 ---------- 2018-12-06 15:00:00 : 퇴계동   25985 ----------


 ---------- 2018-12-06 21:00:00 : 후평1동   25986 ----------


 ---------- 2018-12-06 21:00:00 : 퇴계동   25988 ----------


 ---------- 2018-12-06 22:00:00 : 강남동   25989 ----------


 ---------- 2018-12-07 04:00:00 : 효자1동   25990 ----------


 ---------- 2018-12-07 09:00:00 : 남  면   25992 ----------


 ---------- 2018-12-07 09:00:00 : 후평1동   25993 ----------


 ---------- 2018-12-07 13:00:00 : 동  면   25994 ----------


 ---------- 2018-12-07 16:00:00 : 동  면   25996 ----------


 ---------- 2018-12-07 17:00:00 : 후평1동   25997 ----------


 ---------- 2018-12-07 19:00:00 : 퇴계동   25998 ----------


 ---------- 2018-12-07 23:00:00 : 신사우동   25999 ----------


 ---------- 2018-12-08 16:00:00 : 동내면   26001 ----------


 ---------- 2018-12-08 17:00:00 : 서  면   26003 ----------


 ---------- 2018-12-08 20:00:00 : 후평1동   26004 ----------


 ---------- 2018-12-09 04:00:00 : 후평1동   26006 ----------


 ---------- 2018-12-09 14:00:00 : 퇴계동   26007 ----------


 ---------- 2018-12-09 21:00:00 : 효자1동   26008 ----------


 ---------- 2018-12-09 21:00:00 : 동  면   26010 ----------


 ---------- 2018-12-10 09:00:00 : 강남동   26011 ----------


 ---------- 2018-12-10 13:00:00 : 신북읍   26012 ----------


 ---------- 2018-12-10 18:00:00 : 서  면   26013 ----------


 ---------- 2018-12-10 23:00:00 : 동  면   26014 ----------


 ---------- 2018-12-11 01:00:00 : 교  동   26015 ----------


 ---------- 2018-12-11 11:00:00 : 근화동   26017 ----------


 ---------- 2018-12-11 15:00:00 : 조운동   26019 ----------


 ---------- 2018-12-11 16:00:00 : 신동면   26021 ----------


 ---------- 2018-12-11 17:00:00 : 북산면   26023 ----------


 ---------- 2018-12-12 07:00:00 : 퇴계동   26025 ----------


 ---------- 2018-12-12 08:00:00 : 약사명동   26026 ----------


 ---------- 2018-12-12 09:00:00 : 강남동   26028 ----------


 ---------- 2018-12-12 09:00:00 : 북산면   26029 ----------


 ---------- 2018-12-12 15:00:00 : 소양동   26031 ----------


 ---------- 2018-12-12 20:00:00 : 남산면   26033 ----------


 ---------- 2018-12-12 20:00:00 : 신사우동   26036 ----------


 ---------- 2018-12-13 00:00:00 : 퇴계동   26039 ----------


 ---------- 2018-12-13 03:00:00 : 석사동   26040 ----------


 ---------- 2018-12-13 04:00:00 : 효자1동   26041 ----------


 ---------- 2018-12-13 10:00:00 : 근화동   26044 ----------


 ---------- 2018-12-13 13:00:00 : 근화동   26045 ----------


 ---------- 2018-12-14 04:00:00 : 신사우동   26046 ----------


 ---------- 2018-12-14 13:00:00 : 동산면   26049 ----------


 ---------- 2018-12-14 15:00:00 : 효자1동   26050 ----------


 ---------- 2018-12-14 21:00:00 : 강남동   26051 ----------


 ---------- 2018-12-15 12:00:00 : 동내면   26052 ----------


 ---------- 2018-12-15 14:00:00 : 남산면   26053 ----------


 ---------- 2018-12-15 14:00:00 : 후평1동   26054 ----------


 ---------- 2018-12-15 16:00:00 : 조운동   26055 ----------


 ---------- 2018-12-15 19:00:00 : 효자1동   26056 ----------


 ---------- 2018-12-15 23:00:00 : 서  면   26057 ----------


 ---------- 2018-12-15 23:00:00 : 동내면   26059 ----------


 ---------- 2018-12-15 23:00:00 : 효자1동   26060 ----------


 ---------- 2018-12-16 00:00:00 : 강남동   26062 ----------


 ---------- 2018-12-16 12:00:00 : 동산면   26064 ----------


 ---------- 2018-12-16 16:00:00 : 강남동   26065 ----------


 ---------- 2018-12-16 16:00:00 : 근화동   26067 ----------


 ---------- 2018-12-16 16:00:00 : 후평1동   26068 ----------


 ---------- 2018-12-16 17:00:00 : 남산면   26070 ----------


 ---------- 2018-12-16 22:00:00 : 퇴계동   26073 ----------


 ---------- 2018-12-17 06:00:00 : 퇴계동   26075 ----------


 ---------- 2018-12-17 09:00:00 : 퇴계동   26076 ----------


 ---------- 2018-12-17 13:00:00 : 신동면   26077 ----------


 ---------- 2018-12-17 13:00:00 : 동  면   26078 ----------


 ---------- 2018-12-17 16:00:00 : 석사동   26079 ----------


 ---------- 2018-12-17 22:00:00 : 석사동   26081 ----------


 ---------- 2018-12-18 02:00:00 : 석사동   26082 ----------


 ---------- 2018-12-18 10:00:00 : 동  면   26083 ----------


 ---------- 2018-12-18 10:00:00 : 후평1동   26084 ----------


 ---------- 2018-12-18 11:00:00 : 동산면   26086 ----------


 ---------- 2018-12-18 12:00:00 : 약사명동   26087 ----------


 ---------- 2018-12-18 20:00:00 : 신사우동   26088 ----------


 ---------- 2018-12-19 17:00:00 : 후평1동   26089 ----------


 ---------- 2018-12-19 22:00:00 : 석사동   26090 ----------


 ---------- 2018-12-20 09:00:00 : 퇴계동   26091 ----------


 ---------- 2018-12-20 12:00:00 : 효자1동   26093 ----------


 ---------- 2018-12-20 13:00:00 : 동  면   26094 ----------


 ---------- 2018-12-20 14:00:00 : 동내면   26095 ----------


 ---------- 2018-12-21 10:00:00 : 강남동   26097 ----------


 ---------- 2018-12-21 16:00:00 : 동  면   26098 ----------


 ---------- 2018-12-21 18:00:00 : 동  면   26099 ----------


 ---------- 2018-12-21 20:00:00 : 동산면   26100 ----------


 ---------- 2018-12-22 12:00:00 : 효자1동   26101 ----------


 ---------- 2018-12-22 16:00:00 : 북산면   26102 ----------


 ---------- 2018-12-23 03:00:00 : 후평1동   26103 ----------


 ---------- 2018-12-23 07:00:00 : 신북읍   26104 ----------


 ---------- 2018-12-23 15:00:00 : 신사우동   26105 ----------


 ---------- 2018-12-23 19:00:00 : 강남동   26106 ----------


 ---------- 2018-12-24 04:00:00 : 후평1동   26107 ----------


 ---------- 2018-12-24 11:00:00 : 후평1동   26108 ----------


 ---------- 2018-12-24 16:00:00 : 남산면   26109 ----------


 ---------- 2018-12-24 19:00:00 : 남산면   26112 ----------


 ---------- 2018-12-24 22:00:00 : 석사동   26113 ----------


 ---------- 2018-12-25 08:00:00 : 효자1동   26114 ----------


 ---------- 2018-12-25 09:00:00 : 후평1동   26115 ----------


 ---------- 2018-12-25 15:00:00 : 후평1동   26116 ----------


 ---------- 2018-12-27 05:00:00 : 효자1동   26117 ----------


 ---------- 2018-12-27 08:00:00 : 동산면   26118 ----------


 ---------- 2018-12-27 11:00:00 : 소양동   26119 ----------


 ---------- 2018-12-27 14:00:00 : 효자1동   26120 ----------


 ---------- 2018-12-27 17:00:00 : 사북면   26121 ----------


 ---------- 2018-12-27 23:00:00 : 동  면   26122 ----------


 ---------- 2018-12-28 02:00:00 : 효자1동   26123 ----------


 ---------- 2018-12-28 11:00:00 : 동내면   26124 ----------


 ---------- 2018-12-28 17:00:00 : 후평1동   26125 ----------


 ---------- 2018-12-28 19:00:00 : 동내면   26128 ----------


 ---------- 2018-12-29 03:00:00 : 근화동   26129 ----------


 ---------- 2018-12-29 05:00:00 : 남산면   26131 ----------


 ---------- 2018-12-29 11:00:00 : 동내면   26132 ----------


 ---------- 2018-12-29 18:00:00 : 효자1동   26134 ----------


 ---------- 2018-12-30 00:00:00 : 동  면   26135 ----------


 ---------- 2018-12-30 13:00:00 : 석사동   26136 ----------


 ---------- 2018-12-30 14:00:00 : 석사동   26138 ----------


 ---------- 2018-12-30 15:00:00 : 석사동   26139 ----------


 ---------- 2018-12-30 16:00:00 : 신동면   26140 ----------


 ---------- 2018-12-30 19:00:00 : 석사동   26142 ----------


 ---------- 2018-12-31 07:00:00 : 남산면   26143 ----------


 ---------- 2018-12-31 15:00:00 : 후평1동   26144 ----------


 ---------- 2018-12-31 18:00:00 : 후평1동   26145 ----------


 ---------- 2018-12-31 23:00:00 : 남산면   26147 ----------


 ---------- 2019-01-01 10:00:00 : 동  면   26148 ----------


 ---------- 2019-01-01 12:00:00 : 퇴계동   26149 ----------


 ---------- 2019-01-01 14:00:00 : 동내면   26150 ----------


 ---------- 2019-01-01 20:00:00 : 후평1동   26152 ----------


 ---------- 2019-01-02 07:00:00 : 동내면   26153 ----------


 ---------- 2019-01-02 08:00:00 : 서  면   26156 ----------


 ---------- 2019-01-02 20:00:00 : 근화동   26158 ----------


 ---------- 2019-01-02 23:00:00 : 북산면   26160 ----------


 ---------- 2019-01-03 09:00:00 : 퇴계동   26162 ----------


 ---------- 2019-01-03 14:00:00 : 신동면   26163 ----------


 ---------- 2019-01-04 01:00:00 : 동내면   26165 ----------


 ---------- 2019-01-04 08:00:00 : 후평1동   26166 ----------

 ---------- 2019-01-04 11:00:00 : 효자1동   26167 ----------


 ---------- 2019-01-04 11:00:00 : 동산면   26168 ----------


 ---------- 2019-01-05 01:00:00 : 효자1동   26170 ----------


 ---------- 2019-01-05 03:00:00 : 소양동   26171 ----------


 ---------- 2019-01-05 06:00:00 : 신북읍   26173 ----------


 ---------- 2019-01-05 14:00:00 : 서  면   26176 ----------


 ---------- 2019-01-05 14:00:00 : 동내면   26177 ----------


 ---------- 2019-01-05 18:00:00 : 강남동   26180 ----------


 ---------- 2019-01-05 22:00:00 : 소양동   26181 ----------


 ---------- 2019-01-05 23:00:00 : 석사동   26183 ----------


 ---------- 2019-01-06 06:00:00 : 퇴계동   26184 ----------


 ---------- 2019-01-06 13:00:00 : 퇴계동   26186 ----------


 ---------- 2019-01-06 15:00:00 : 북산면   26188 ----------


 ---------- 2019-01-07 09:00:00 : 동  면   26190 ----------


 ---------- 2019-01-07 10:00:00 : 신북읍   26191 ----------


 ---------- 2019-01-07 17:00:00 : 효자1동   26192 ----------


 ---------- 2019-01-08 08:00:00 : 남산면   26194 ----------


 ---------- 2019-01-08 08:00:00 : 후평1동   26196 ----------


 ---------- 2019-01-08 15:00:00 : 동  면   26198 ----------


 ---------- 2019-01-08 16:00:00 : 효자1동   26199 ----------


 ---------- 2019-01-08 17:00:00 : 후평1동   26200 ----------


 ---------- 2019-01-08 18:00:00 : 약사명동   26201 ----------


 ---------- 2019-01-08 21:00:00 : 강남동   26202 ----------


 ---------- 2019-01-08 23:00:00 : 근화동   26203 ----------


 ---------- 2019-01-09 05:00:00 : 동내면   26204 ----------


 ---------- 2019-01-09 06:00:00 : 신북읍   26205 ----------


 ---------- 2019-01-09 14:00:00 : 효자1동   26206 ----------


 ---------- 2019-01-09 16:00:00 : 남산면   26207 ----------


 ---------- 2019-01-10 00:00:00 : 후평1동   26208 ----------


 ---------- 2019-01-10 01:00:00 : 약사명동   26210 ----------


 ---------- 2019-01-10 07:00:00 : 신사우동   26213 ----------


 ---------- 2019-01-10 10:00:00 : 후평1동   26215 ----------


 ---------- 2019-01-10 11:00:00 : 서  면   26218 ----------


 ---------- 2019-01-10 12:00:00 : 근화동   26219 ----------


 ---------- 2019-01-10 18:00:00 : 동산면   26220 ----------


 ---------- 2019-01-10 22:00:00 : 사북면   26221 ----------


 ---------- 2019-01-10 22:00:00 : 신사우동   26222 ----------


 ---------- 2019-01-11 00:00:00 : 후평1동   26224 ----------


 ---------- 2019-01-11 09:00:00 : 동  면   26226 ----------


 ---------- 2019-01-11 13:00:00 : 강남동   26228 ----------


 ---------- 2019-01-11 14:00:00 : 석사동   26229 ----------


 ---------- 2019-01-11 16:00:00 : 동산면   26230 ----------


 ---------- 2019-01-11 18:00:00 : 강남동   26232 ----------


 ---------- 2019-01-12 10:00:00 : 서  면   26233 ----------


 ---------- 2019-01-12 10:00:00 : 후평1동   26235 ----------


 ---------- 2019-01-12 11:00:00 : 남산면   26236 ----------


 ---------- 2019-01-12 14:00:00 : 소양동   26238 ----------


 ---------- 2019-01-12 15:00:00 : 남  면   26239 ----------


 ---------- 2019-01-12 18:00:00 : 동  면   26241 ----------


 ---------- 2019-01-13 12:00:00 : 사북면   26245 ----------


 ---------- 2019-01-13 15:00:00 : 효자1동   26247 ----------


 ---------- 2019-01-13 18:00:00 : 신북읍   26249 ----------


 ---------- 2019-01-14 09:00:00 : 후평1동   26250 ----------


 ---------- 2019-01-14 10:00:00 : 동내면   26251 ----------


 ---------- 2019-01-14 11:00:00 : 근화동   26252 ----------


 ---------- 2019-01-14 13:00:00 : 신북읍   26253 ----------


 ---------- 2019-01-14 14:00:00 : 신동면   26255 ----------


 ---------- 2019-01-14 15:00:00 : 약사명동   26256 ----------


 ---------- 2019-01-14 17:00:00 : 강남동   26258 ----------


 ---------- 2019-01-14 18:00:00 : 석사동   26259 ----------


 ---------- 2019-01-14 19:00:00 : 남산면   26260 ----------


 ---------- 2019-01-14 20:00:00 : 북산면   26261 ----------


 ---------- 2019-01-14 21:00:00 : 퇴계동   26262 ----------


 ---------- 2019-01-14 23:00:00 : 남산면   26264 ----------


 ---------- 2019-01-15 07:00:00 : 퇴계동   26265 ----------


 ---------- 2019-01-15 13:00:00 : 소양동   26267 ----------


 ---------- 2019-01-15 14:00:00 : 북산면   26268 ----------


 ---------- 2019-01-15 17:00:00 : 강남동   26269 ----------


 ---------- 2019-01-15 21:00:00 : 조운동   26270 ----------


 ---------- 2019-01-16 02:00:00 : 석사동   26271 ----------


 ---------- 2019-01-16 02:00:00 : 남  면   26272 ----------


 ---------- 2019-01-16 09:00:00 : 신동면   26275 ----------


 ---------- 2019-01-16 10:00:00 : 소양동   26277 ----------


 ---------- 2019-01-16 12:00:00 : 석사동   26279 ----------


 ---------- 2019-01-16 13:00:00 : 소양동   26281 ----------


 ---------- 2019-01-16 14:00:00 : 후평1동   26282 ----------


 ---------- 2019-01-16 15:00:00 : 신동면   26283 ----------


 ---------- 2019-01-17 08:00:00 : 남산면   26284 ----------


 ---------- 2019-01-17 11:00:00 : 근화동   26286 ----------


 ---------- 2019-01-17 16:00:00 : 소양동   26288 ----------


 ---------- 2019-01-17 19:00:00 : 근화동   26289 ----------


 ---------- 2019-01-17 23:00:00 : 조운동   26290 ----------


 ---------- 2019-01-18 06:00:00 : 신북읍   26291 ----------


 ---------- 2019-01-18 12:00:00 : 신북읍   26294 ----------


 ---------- 2019-01-18 13:00:00 : 신동면   26295 ----------


 ---------- 2019-01-18 15:00:00 : 동내면   26297 ----------


 ---------- 2019-01-18 16:00:00 : 신북읍   26298 ----------


 ---------- 2019-01-18 18:00:00 : 신동면   26299 ----------


 ---------- 2019-01-18 18:00:00 : 남산면   26301 ----------


 ---------- 2019-01-18 18:00:00 : 동  면   26303 ----------


 ---------- 2019-01-18 22:00:00 : 석사동   26304 ----------


 ---------- 2019-01-19 08:00:00 : 동내면   26305 ----------


 ---------- 2019-01-19 13:00:00 : 근화동   26306 ----------


 ---------- 2019-01-19 17:00:00 : 서  면   26307 ----------


 ---------- 2019-01-19 20:00:00 : 신사우동   26308 ----------


 ---------- 2019-01-20 12:00:00 : 서  면   26309 ----------


 ---------- 2019-01-20 16:00:00 : 동내면   26310 ----------


 ---------- 2019-01-20 18:00:00 : 효자1동   26312 ----------


 ---------- 2019-01-20 19:00:00 : 효자1동   26313 ----------


 ---------- 2019-01-20 22:00:00 : 근화동   26316 ----------


 ---------- 2019-01-21 00:00:00 : 동산면   26317 ----------


 ---------- 2019-01-21 08:00:00 : 석사동   26318 ----------


 ---------- 2019-01-22 01:00:00 : 서  면   26321 ----------


 ---------- 2019-01-22 10:00:00 : 석사동   26322 ----------


 ---------- 2019-01-22 16:00:00 : 동산면   26323 ----------


 ---------- 2019-01-22 20:00:00 : 신북읍   26324 ----------


 ---------- 2019-01-22 20:00:00 : 동  면   26326 ----------


 ---------- 2019-01-23 11:00:00 : 신사우동   26328 ----------


 ---------- 2019-01-23 13:00:00 : 동산면   26330 ----------


 ---------- 2019-01-23 15:00:00 : 남  면   26331 ----------


 ---------- 2019-01-23 16:00:00 : 석사동   26333 ----------


 ---------- 2019-01-24 01:00:00 : 사북면   26334 ----------


 ---------- 2019-01-24 06:00:00 : 남산면   26335 ----------


 ---------- 2019-01-24 13:00:00 : 남산면   26337 ----------


 ---------- 2019-01-24 14:00:00 : 석사동   26338 ----------


 ---------- 2019-01-24 15:00:00 : 석사동   26339 ----------


 ---------- 2019-01-24 16:00:00 : 동산면   26340 ----------


 ---------- 2019-01-24 20:00:00 : 약사명동   26341 ----------


 ---------- 2019-01-25 19:00:00 : 서  면   26342 ----------


 ---------- 2019-01-25 22:00:00 : 남산면   26343 ----------


 ---------- 2019-01-26 12:00:00 : 후평1동   26345 ----------


 ---------- 2019-01-26 14:00:00 : 후평1동   26346 ----------


 ---------- 2019-01-26 16:00:00 : 동산면   26347 ----------


 ---------- 2019-01-26 17:00:00 : 동내면   26348 ----------


 ---------- 2019-01-26 20:00:00 : 신동면   26350 ----------


 ---------- 2019-01-27 08:00:00 : 강남동   26351 ----------


 ---------- 2019-01-27 08:00:00 : 퇴계동   26353 ----------


 ---------- 2019-01-27 16:00:00 : 남  면   26355 ----------


 ---------- 2019-01-27 18:00:00 : 퇴계동   26357 ----------


 ---------- 2019-01-28 05:00:00 : 동  면   26358 ----------


 ---------- 2019-01-28 07:00:00 : 퇴계동   26359 ----------


 ---------- 2019-01-28 18:00:00 : 퇴계동   26360 ----------


 ---------- 2019-01-29 09:00:00 : 북산면   26361 ----------


 ---------- 2019-01-29 10:00:00 : 강남동   26363 ----------


 ---------- 2019-01-29 10:00:00 : 효자1동   26365 ----------


 ---------- 2019-01-29 16:00:00 : 남산면   26366 ----------

 ---------- 2019-01-29 17:00:00 : 동내면   26367 ----------


 ---------- 2019-01-29 17:00:00 : 효자1동   26369 ----------


 ---------- 2019-01-29 20:00:00 : 남산면   26370 ----------


 ---------- 2019-01-29 22:00:00 : 근화동   26371 ----------


 ---------- 2019-01-29 22:00:00 : 신북읍   26374 ----------


 ---------- 2019-01-30 04:00:00 : 북산면   26376 ----------


 ---------- 2019-01-30 13:00:00 : 신사우동   26377 ----------


 ---------- 2019-01-30 17:00:00 : 신사우동   26378 ----------


 ---------- 2019-01-30 19:00:00 : 후평1동   26380 ----------


 ---------- 2019-01-31 12:00:00 : 남산면   26381 ----------


 ---------- 2019-01-31 12:00:00 : 퇴계동   26383 ----------


 ---------- 2019-01-31 19:00:00 : 남산면   26386 ----------


 ---------- 2019-02-01 06:00:00 : 남  면   26387 ----------


 ---------- 2019-02-01 09:00:00 : 동내면   26388 ----------


 ---------- 2019-02-01 09:00:00 : 퇴계동   26390 ----------


 ---------- 2019-02-01 10:00:00 : 신동면   26391 ----------


 ---------- 2019-02-01 16:00:00 : 신북읍   26393 ----------


 ---------- 2019-02-01 18:00:00 : 효자1동   26395 ----------


 ---------- 2019-02-02 08:00:00 : 근화동   26397 ----------


 ---------- 2019-02-02 08:00:00 : 동  면   26398 ----------


 ---------- 2019-02-02 10:00:00 : 후평1동   26399 ----------


 ---------- 2019-02-02 14:00:00 : 동산면   26400 ----------


 ---------- 2019-02-02 17:00:00 : 신사우동   26401 ----------


 ---------- 2019-02-02 22:00:00 : 근화동   26402 ----------


 ---------- 2019-02-03 04:00:00 : 신사우동   26403 ----------


 ---------- 2019-02-03 05:00:00 : 남산면   26405 ----------


 ---------- 2019-02-03 11:00:00 : 강남동   26407 ----------


 ---------- 2019-02-03 13:00:00 : 서  면   26408 ----------


 ---------- 2019-02-03 17:00:00 : 효자1동   26410 ----------


 ---------- 2019-02-03 20:00:00 : 후평1동   26411 ----------


 ---------- 2019-02-03 22:00:00 : 석사동   26412 ----------


 ---------- 2019-02-04 02:00:00 : 근화동   26413 ----------


 ---------- 2019-02-04 13:00:00 : 석사동   26415 ----------


 ---------- 2019-02-04 13:00:00 : 동내면   26416 ----------


 ---------- 2019-02-04 14:00:00 : 후평1동   26417 ----------


 ---------- 2019-02-04 15:00:00 : 북산면   26418 ----------


 ---------- 2019-02-04 21:00:00 : 신북읍   26419 ----------


 ---------- 2019-02-04 21:00:00 : 퇴계동   26420 ----------


 ---------- 2019-02-05 08:00:00 : 신동면   26422 ----------


 ---------- 2019-02-05 08:00:00 : 신사우동   26425 ----------


 ---------- 2019-02-05 16:00:00 : 서  면   26427 ----------


 ---------- 2019-02-05 16:00:00 : 후평1동   26428 ----------


 ---------- 2019-02-05 21:00:00 : 동내면   26429 ----------


 ---------- 2019-02-06 15:00:00 : 석사동   26431 ----------


 ---------- 2019-02-06 15:00:00 : 퇴계동   26432 ----------


 ---------- 2019-02-06 21:00:00 : 석사동   26433 ----------


 ---------- 2019-02-07 08:00:00 : 사북면   26435 ----------


 ---------- 2019-02-07 11:00:00 : 소양동   26437 ----------


 ---------- 2019-02-07 14:00:00 : 후평1동   26438 ----------


 ---------- 2019-02-08 00:00:00 : 근화동   26439 ----------


 ---------- 2019-02-08 07:00:00 : 후평1동   26440 ----------


 ---------- 2019-02-08 11:00:00 : 동내면   26441 ----------


 ---------- 2019-02-08 12:00:00 : 남산면   26442 ----------


 ---------- 2019-02-08 20:00:00 : 퇴계동   26444 ----------


 ---------- 2019-02-09 10:00:00 : 강남동   26445 ----------


 ---------- 2019-02-09 17:00:00 : 신사우동   26447 ----------


 ---------- 2019-02-09 18:00:00 : 동  면   26449 ----------


 ---------- 2019-02-09 23:00:00 : 소양동   26450 ----------


 ---------- 2019-02-09 23:00:00 : 후평1동   26451 ----------


 ---------- 2019-02-10 03:00:00 : 석사동   26452 ----------


 ---------- 2019-02-10 11:00:00 : 후평1동   26453 ----------


 ---------- 2019-02-11 11:00:00 : 신동면   26454 ----------


 ---------- 2019-02-11 16:00:00 : 동  면   26455 ----------


 ---------- 2019-02-12 09:00:00 : 석사동   26456 ----------


 ---------- 2019-02-12 10:00:00 : 신사우동   26457 ----------


 ---------- 2019-02-12 12:00:00 : 소양동   26458 ----------


 ---------- 2019-02-13 00:00:00 : 후평1동   26459 ----------


 ---------- 2019-02-13 11:00:00 : 강남동   26460 ----------


 ---------- 2019-02-13 11:00:00 : 후평1동   26461 ----------


 ---------- 2019-02-13 16:00:00 : 강남동   26463 ----------


 ---------- 2019-02-13 18:00:00 : 신사우동   26464 ----------


 ---------- 2019-02-14 05:00:00 : 남산면   26465 ----------


 ---------- 2019-02-14 16:00:00 : 신사우동   26467 ----------


 ---------- 2019-02-15 03:00:00 : 남산면   26469 ----------


 ---------- 2019-02-15 03:00:00 : 교  동   26470 ----------


 ---------- 2019-02-15 06:00:00 : 남산면   26471 ----------


 ---------- 2019-02-15 09:00:00 : 후평1동   26472 ----------


 ---------- 2019-02-15 18:00:00 : 석사동   26474 ----------


 ---------- 2019-02-15 18:00:00 : 동  면   26476 ----------


 ---------- 2019-02-15 19:00:00 : 서  면   26477 ----------


 ---------- 2019-02-15 22:00:00 : 동  면   26479 ----------


 ---------- 2019-02-16 00:00:00 : 서  면   26480 ----------


 ---------- 2019-02-16 01:00:00 : 서  면   26481 ----------


 ---------- 2019-02-16 04:00:00 : 동내면   26482 ----------


 ---------- 2019-02-16 11:00:00 : 남산면   26483 ----------


 ---------- 2019-02-16 14:00:00 : 근화동   26484 ----------


 ---------- 2019-02-16 15:00:00 : 강남동   26485 ----------


 ---------- 2019-02-16 15:00:00 : 동내면   26489 ----------


 ---------- 2019-02-16 17:00:00 : 퇴계동   26492 ----------


 ---------- 2019-02-16 18:00:00 : 소양동   26494 ----------


 ---------- 2019-02-16 19:00:00 : 동내면   26495 ----------


 ---------- 2019-02-16 20:00:00 : 강남동   26496 ----------


 ---------- 2019-02-17 11:00:00 : 석사동   26497 ----------


 ---------- 2019-02-17 14:00:00 : 남산면   26499 ----------


 ---------- 2019-02-17 16:00:00 : 신북읍   26500 ----------


 ---------- 2019-02-17 17:00:00 : 동  면   26501 ----------


 ---------- 2019-02-18 09:00:00 : 퇴계동   26502 ----------


 ---------- 2019-02-18 09:00:00 : 동산면   26503 ----------


 ---------- 2019-02-18 14:00:00 : 석사동   26505 ----------


 ---------- 2019-02-18 15:00:00 : 신동면   26506 ----------


 ---------- 2019-02-18 18:00:00 : 효자1동   26507 ----------


 ---------- 2019-02-18 21:00:00 : 근화동   26508 ----------


 ---------- 2019-02-18 23:00:00 : 효자1동   26510 ----------


 ---------- 2019-02-19 07:00:00 : 소양동   26511 ----------


 ---------- 2019-02-19 10:00:00 : 사북면   26513 ----------


 ---------- 2019-02-19 21:00:00 : 강남동   26514 ----------


 ---------- 2019-02-20 18:00:00 : 근화동   26515 ----------


 ---------- 2019-02-20 20:00:00 : 신사우동   26516 ----------


 ---------- 2019-02-21 09:00:00 : 신동면   26517 ----------


 ---------- 2019-02-21 10:00:00 : 석사동   26518 ----------


 ---------- 2019-02-21 11:00:00 : 동내면   26519 ----------


 ---------- 2019-02-21 12:00:00 : 동내면   26520 ----------


 ---------- 2019-02-21 16:00:00 : 강남동   26521 ----------


 ---------- 2019-02-21 17:00:00 : 동  면   26522 ----------


 ---------- 2019-02-21 18:00:00 : 동내면   26524 ----------


 ---------- 2019-02-21 22:00:00 : 퇴계동   26525 ----------


 ---------- 2019-02-22 09:00:00 : 근화동   26526 ----------


 ---------- 2019-02-22 10:00:00 : 동내면   26528 ----------


 ---------- 2019-02-22 14:00:00 : 동내면   26529 ----------


 ---------- 2019-02-22 16:00:00 : 신북읍   26531 ----------


 ---------- 2019-02-22 18:00:00 : 후평1동   26532 ----------


 ---------- 2019-02-22 21:00:00 : 후평1동   26533 ----------


 ---------- 2019-02-23 01:00:00 : 조운동   26534 ----------


 ---------- 2019-02-23 08:00:00 : 강남동   26535 ----------


 ---------- 2019-02-23 10:00:00 : 동산면   26537 ----------


 ---------- 2019-02-23 14:00:00 : 서  면   26538 ----------


 ---------- 2019-02-23 19:00:00 : 서  면   26540 ----------


 ---------- 2019-02-23 22:00:00 : 퇴계동   26541 ----------


 ---------- 2019-02-24 06:00:00 : 신북읍   26542 ----------


 ---------- 2019-02-24 10:00:00 : 남산면   26543 ----------


 ---------- 2019-02-24 13:00:00 : 동  면   26544 ----------


 ---------- 2019-02-24 18:00:00 : 석사동   26545 ----------


 ---------- 2019-02-24 20:00:00 : 퇴계동   26547 ----------


 ---------- 2019-02-25 04:00:00 : 후평1동   26548 ----------


 ---------- 2019-02-26 11:00:00 : 근화동   26550 ----------


 ---------- 2019-02-26 14:00:00 : 서  면   26551 ----------

 ---------- 2019-02-26 18:00:00 : 동내면   26552 ----------


 ---------- 2019-02-26 19:00:00 : 후평1동   26553 ----------


 ---------- 2019-02-27 08:00:00 : 석사동   26554 ----------


 ---------- 2019-02-27 11:00:00 : 사북면   26555 ----------


 ---------- 2019-02-27 14:00:00 : 강남동   26557 ----------


 ---------- 2019-02-27 15:00:00 : 서  면   26558 ----------


 ---------- 2019-02-28 11:00:00 : 남  면   26559 ----------


 ---------- 2019-02-28 16:00:00 : 남산면   26560 ----------


 ---------- 2019-03-01 08:00:00 : 후평1동   26561 ----------


 ---------- 2019-03-01 10:00:00 : 근화동   26562 ----------


 ---------- 2019-03-01 11:00:00 : 동  면   26564 ----------


 ---------- 2019-03-01 15:00:00 : 후평1동   26566 ----------


 ---------- 2019-03-01 17:00:00 : 남산면   26567 ----------


 ---------- 2019-03-01 19:00:00 : 신동면   26569 ----------


 ---------- 2019-03-01 21:00:00 : 신사우동   26571 ----------


 ---------- 2019-03-01 21:00:00 : 신북읍   26573 ----------


 ---------- 2019-03-02 00:00:00 : 신북읍   26574 ----------


 ---------- 2019-03-02 10:00:00 : 석사동   26575 ----------


 ---------- 2019-03-02 10:00:00 : 동  면   26577 ----------


 ---------- 2019-03-02 11:00:00 : 동  면   26578 ----------


 ---------- 2019-03-02 13:00:00 : 강남동   26581 ----------


 ---------- 2019-03-02 14:00:00 : 남산면   26584 ----------


 ---------- 2019-03-02 18:00:00 : 북산면   26585 ----------


 ---------- 2019-03-02 20:00:00 : 동산면   26586 ----------


 ---------- 2019-03-03 11:00:00 : 신사우동   26587 ----------


 ---------- 2019-03-03 12:00:00 : 사북면   26589 ----------


 ---------- 2019-03-03 14:00:00 : 퇴계동   26590 ----------


 ---------- 2019-03-03 17:00:00 : 신북읍   26592 ----------


 ---------- 2019-03-04 00:00:00 : 강남동   26594 ----------


 ---------- 2019-03-04 07:00:00 : 강남동   26595 ----------


 ---------- 2019-03-04 10:00:00 : 강남동   26596 ----------


 ---------- 2019-03-04 12:00:00 : 퇴계동   26597 ----------


 ---------- 2019-03-04 13:00:00 : 강남동   26599 ----------


 ---------- 2019-03-04 13:00:00 : 근화동   26600 ----------


 ---------- 2019-03-04 14:00:00 : 소양동   26602 ----------


 ---------- 2019-03-04 15:00:00 : 석사동   26603 ----------


 ---------- 2019-03-04 16:00:00 : 서  면   26605 ----------


 ---------- 2019-03-04 17:00:00 : 신사우동   26606 ----------


 ---------- 2019-03-05 05:00:00 : 후평1동   26607 ----------


 ---------- 2019-03-05 18:00:00 : 후평1동   26608 ----------


 ---------- 2019-03-06 01:00:00 : 근화동   26609 ----------


 ---------- 2019-03-06 07:00:00 : 석사동   26610 ----------


 ---------- 2019-03-06 09:00:00 : 퇴계동   26612 ----------


 ---------- 2019-03-06 12:00:00 : 남산면   26613 ----------


 ---------- 2019-03-06 14:00:00 : 효자1동   26614 ----------


 ---------- 2019-03-06 15:00:00 : 신북읍   26615 ----------


 ---------- 2019-03-07 10:00:00 : 동  면   26619 ----------


 ---------- 2019-03-07 12:00:00 : 강남동   26621 ----------


 ---------- 2019-03-08 01:00:00 : 석사동   26623 ----------


 ---------- 2019-03-08 11:00:00 : 약사명동   26624 ----------


 ---------- 2019-03-08 15:00:00 : 퇴계동   26625 ----------


 ---------- 2019-03-08 21:00:00 : 강남동   26627 ----------


 ---------- 2019-03-08 22:00:00 : 후평1동   26628 ----------


 ---------- 2019-03-09 12:00:00 : 동내면   26629 ----------


 ---------- 2019-03-09 15:00:00 : 남산면   26631 ----------


 ---------- 2019-03-09 19:00:00 : 신사우동   26633 ----------


 ---------- 2019-03-09 21:00:00 : 약사명동   26634 ----------


 ---------- 2019-03-10 01:00:00 : 동  면   26637 ----------


 ---------- 2019-03-10 03:00:00 : 동산면   26640 ----------


 ---------- 2019-03-10 11:00:00 : 서  면   26644 ----------


 ---------- 2019-03-10 13:00:00 : 동내면   26645 ----------


 ---------- 2019-03-10 15:00:00 : 퇴계동   26646 ----------


 ---------- 2019-03-10 17:00:00 : 남  면   26647 ----------


 ---------- 2019-03-10 17:00:00 : 남산면   26648 ----------


 ---------- 2019-03-10 18:00:00 : 남산면   26651 ----------


 ---------- 2019-03-10 18:00:00 : 동산면   26656 ----------


 ---------- 2019-03-10 20:00:00 : 남산면   26657 ----------


 ---------- 2019-03-10 23:00:00 : 신북읍   26658 ----------


 ---------- 2019-03-11 02:00:00 : 근화동   26659 ----------


 ---------- 2019-03-11 06:00:00 : 동산면   26661 ----------


 ---------- 2019-03-11 09:00:00 : 동내면   26662 ----------


 ---------- 2019-03-11 10:00:00 : 신북읍   26663 ----------


 ---------- 2019-03-11 14:00:00 : 서  면   26664 ----------


 ---------- 2019-03-12 01:00:00 : 석사동   26665 ----------


 ---------- 2019-03-12 04:00:00 : 효자1동   26666 ----------


 ---------- 2019-03-12 15:00:00 : 동  면   26668 ----------


 ---------- 2019-03-13 06:00:00 : 강남동   26671 ----------


 ---------- 2019-03-13 12:00:00 : 후평1동   26672 ----------


 ---------- 2019-03-13 23:00:00 : 남산면   26673 ----------


 ---------- 2019-03-14 09:00:00 : 후평1동   26674 ----------


 ---------- 2019-03-14 10:00:00 : 신동면   26675 ----------


 ---------- 2019-03-14 16:00:00 : 석사동   26676 ----------


 ---------- 2019-03-14 20:00:00 : 강남동   26677 ----------


 ---------- 2019-03-14 21:00:00 : 석사동   26678 ----------


 ---------- 2019-03-14 23:00:00 : 석사동   26679 ----------


 ---------- 2019-03-15 09:00:00 : 강남동   26681 ----------


 ---------- 2019-03-15 10:00:00 : 석사동   26682 ----------


 ---------- 2019-03-15 10:00:00 : 효자1동   26683 ----------


 ---------- 2019-03-15 12:00:00 : 효자1동   26685 ----------


 ---------- 2019-03-15 15:00:00 : 소양동   26687 ----------


 ---------- 2019-03-15 16:00:00 : 후평1동   26688 ----------


 ---------- 2019-03-15 19:00:00 : 동산면   26689 ----------


 ---------- 2019-03-16 11:00:00 : 후평1동   26690 ----------


 ---------- 2019-03-16 11:00:00 : 북산면   26692 ----------


 ---------- 2019-03-16 13:00:00 : 서  면   26694 ----------


 ---------- 2019-03-16 17:00:00 : 강남동   26696 ----------


 ---------- 2019-03-16 20:00:00 : 남산면   26697 ----------


 ---------- 2019-03-17 03:00:00 : 석사동   26698 ----------


 ---------- 2019-03-17 04:00:00 : 동내면   26699 ----------


 ---------- 2019-03-17 12:00:00 : 사북면   26700 ----------


 ---------- 2019-03-17 13:00:00 : 석사동   26702 ----------


 ---------- 2019-03-17 15:00:00 : 남산면   26705 ----------


 ---------- 2019-03-17 18:00:00 : 후평1동   26707 ----------


 ---------- 2019-03-17 19:00:00 : 강남동   26709 ----------


 ---------- 2019-03-17 22:00:00 : 동  면   26710 ----------


 ---------- 2019-03-18 08:00:00 : 소양동   26711 ----------


 ---------- 2019-03-18 13:00:00 : 동내면   26712 ----------


 ---------- 2019-03-18 18:00:00 : 동내면   26714 ----------


 ---------- 2019-03-18 19:00:00 : 소양동   26717 ----------


 ---------- 2019-03-19 12:00:00 : 후평1동   26718 ----------


 ---------- 2019-03-19 13:00:00 : 교  동   26719 ----------


 ---------- 2019-03-19 14:00:00 : 신북읍   26720 ----------


 ---------- 2019-03-19 15:00:00 : 퇴계동   26721 ----------


 ---------- 2019-03-19 16:00:00 : 신북읍   26723 ----------


 ---------- 2019-03-19 20:00:00 : 동  면   26724 ----------


 ---------- 2019-03-20 12:00:00 : 후평1동   26725 ----------


 ---------- 2019-03-20 19:00:00 : 신동면   26726 ----------


 ---------- 2019-03-20 19:00:00 : 퇴계동   26727 ----------


 ---------- 2019-03-21 02:00:00 : 후평1동   26728 ----------


 ---------- 2019-03-21 06:00:00 : 남산면   26729 ----------


 ---------- 2019-03-21 06:00:00 : 소양동   26731 ----------


 ---------- 2019-03-21 07:00:00 : 남산면   26732 ----------


 ---------- 2019-03-21 20:00:00 : 퇴계동   26733 ----------


 ---------- 2019-03-22 05:00:00 : 석사동   26735 ----------


 ---------- 2019-03-22 13:00:00 : 서  면   26737 ----------


 ---------- 2019-03-22 16:00:00 : 소양동   26739 ----------


 ---------- 2019-03-22 21:00:00 : 효자1동   26741 ----------


 ---------- 2019-03-23 00:00:00 : 석사동   26742 ----------


 ---------- 2019-03-23 09:00:00 : 신북읍   26743 ----------


 ---------- 2019-03-23 12:00:00 : 서  면   26746 ----------


 ---------- 2019-03-23 15:00:00 : 신사우동   26748 ----------


 ---------- 2019-03-23 17:00:00 : 동  면   26749 ----------


 ---------- 2019-03-24 00:00:00 : 신사우동   26750 ----------


 ---------- 2019-03-24 11:00:00 : 강남동   26753 ----------


 ---------- 2019-03-24 11:00:00 : 후평1동   26755 ----------


 ---------- 2019-03-24 14:00:00 : 교  동   26756 ----------


 ---------- 2019-03-24 15:00:00 : 동내면   26757 ----------

 ---------- 2019-03-24 16:00:00 : 퇴계동   26759 ----------


 ---------- 2019-03-24 19:00:00 : 동산면   26760 ----------


 ---------- 2019-03-25 09:00:00 : 강남동   26761 ----------


 ---------- 2019-03-25 10:00:00 : 남  면   26764 ----------


 ---------- 2019-03-25 12:00:00 : 신사우동   26765 ----------


 ---------- 2019-03-25 15:00:00 : 동내면   26766 ----------


 ---------- 2019-03-25 21:00:00 : 근화동   26768 ----------


 ---------- 2019-03-26 07:00:00 : 효자1동   26769 ----------


 ---------- 2019-03-26 09:00:00 : 사북면   26770 ----------


 ---------- 2019-03-26 09:00:00 : 후평1동   26771 ----------


 ---------- 2019-03-26 14:00:00 : 퇴계동   26774 ----------


 ---------- 2019-03-26 15:00:00 : 후평1동   26776 ----------


 ---------- 2019-03-26 19:00:00 : 남산면   26778 ----------


 ---------- 2019-03-26 21:00:00 : 동내면   26779 ----------


 ---------- 2019-03-27 04:00:00 : 효자1동   26782 ----------


 ---------- 2019-03-27 11:00:00 : 후평1동   26784 ----------


 ---------- 2019-03-27 12:00:00 : 동산면   26786 ----------


 ---------- 2019-03-27 14:00:00 : 신동면   26788 ----------


 ---------- 2019-03-27 18:00:00 : 신북읍   26792 ----------


 ---------- 2019-03-28 00:00:00 : 효자1동   26794 ----------


 ---------- 2019-03-28 04:00:00 : 효자1동   26796 ----------


 ---------- 2019-03-28 19:00:00 : 석사동   26797 ----------


 ---------- 2019-03-29 10:00:00 : 석사동   26798 ----------


 ---------- 2019-03-30 14:00:00 : 신북읍   26799 ----------


 ---------- 2019-03-30 18:00:00 : 신사우동   26800 ----------


 ---------- 2019-03-30 22:00:00 : 후평1동   26802 ----------


 ---------- 2019-03-31 02:00:00 : 조운동   26804 ----------


 ---------- 2019-03-31 10:00:00 : 효자1동   26806 ----------


 ---------- 2019-03-31 13:00:00 : 강남동   26808 ----------


 ---------- 2019-03-31 13:00:00 : 동산면   26810 ----------


 ---------- 2019-03-31 16:00:00 : 신북읍   26811 ----------


 ---------- 2019-03-31 18:00:00 : 후평1동   26812 ----------


 ---------- 2019-03-31 19:00:00 : 북산면   26813 ----------


 ---------- 2019-04-01 09:00:00 : 동  면   26814 ----------


 ---------- 2019-04-01 14:00:00 : 효자1동   26816 ----------


 ---------- 2019-04-01 14:00:00 : 신북읍   26818 ----------


 ---------- 2019-04-01 15:00:00 : 석사동   26819 ----------


 ---------- 2019-04-01 16:00:00 : 강남동   26821 ----------


 ---------- 2019-04-01 19:00:00 : 강남동   26822 ----------


 ---------- 2019-04-01 23:00:00 : 조운동   26823 ----------


 ---------- 2019-04-02 05:00:00 : 퇴계동   26824 ----------


 ---------- 2019-04-02 10:00:00 : 석사동   26826 ----------


 ---------- 2019-04-02 11:00:00 : 동  면   26827 ----------


 ---------- 2019-04-02 12:00:00 : 동  면   26830 ----------


 ---------- 2019-04-02 19:00:00 : 조운동   26832 ----------


 ---------- 2019-04-02 21:00:00 : 신북읍   26835 ----------


 ---------- 2019-04-03 02:00:00 : 강남동   26837 ----------


 ---------- 2019-04-03 14:00:00 : 후평1동   26838 ----------


 ---------- 2019-04-03 18:00:00 : 후평1동   26839 ----------


 ---------- 2019-04-03 23:00:00 : 석사동   26841 ----------


 ---------- 2019-04-04 04:00:00 : 조운동   26842 ----------


 ---------- 2019-04-04 09:00:00 : 동산면   26844 ----------


 ---------- 2019-04-04 11:00:00 : 효자1동   26845 ----------


 ---------- 2019-04-04 11:00:00 : 신사우동   26846 ----------


 ---------- 2019-04-04 11:00:00 : 퇴계동   26847 ----------


 ---------- 2019-04-04 16:00:00 : 신동면   26848 ----------


 ---------- 2019-04-04 20:00:00 : 조운동   26850 ----------


 ---------- 2019-04-04 23:00:00 : 동  면   26853 ----------


 ---------- 2019-04-05 04:00:00 : 근화동   26854 ----------


 ---------- 2019-04-05 07:00:00 : 후평1동   26856 ----------


 ---------- 2019-04-05 16:00:00 : 동산면   26858 ----------


 ---------- 2019-04-05 21:00:00 : 약사명동   26859 ----------


 ---------- 2019-04-05 22:00:00 : 퇴계동   26860 ----------


 ---------- 2019-04-06 03:00:00 : 효자1동   26861 ----------


 ---------- 2019-04-06 13:00:00 : 석사동   26862 ----------


 ---------- 2019-04-06 13:00:00 : 동내면   26863 ----------


 ---------- 2019-04-06 21:00:00 : 후평1동   26864 ----------


 ---------- 2019-04-07 06:00:00 : 효자1동   26865 ----------


 ---------- 2019-04-07 08:00:00 : 석사동   26866 ----------


 ---------- 2019-04-07 08:00:00 : 후평1동   26867 ----------


 ---------- 2019-04-07 12:00:00 : 서  면   26869 ----------


 ---------- 2019-04-07 16:00:00 : 서  면   26870 ----------


 ---------- 2019-04-07 20:00:00 : 퇴계동   26872 ----------


 ---------- 2019-04-08 09:00:00 : 동  면   26873 ----------


 ---------- 2019-04-08 10:00:00 : 동산면   26874 ----------


 ---------- 2019-04-08 18:00:00 : 후평1동   26876 ----------


 ---------- 2019-04-08 19:00:00 : 동내면   26877 ----------


 ---------- 2019-04-09 03:00:00 : 신동면   26879 ----------


 ---------- 2019-04-09 06:00:00 : 신북읍   26880 ----------


 ---------- 2019-04-09 10:00:00 : 신사우동   26881 ----------


 ---------- 2019-04-09 15:00:00 : 신북읍   26882 ----------


 ---------- 2019-04-09 16:00:00 : 퇴계동   26883 ----------


 ---------- 2019-04-09 19:00:00 : 신사우동   26886 ----------


 ---------- 2019-04-09 19:00:00 : 후평1동   26888 ----------


 ---------- 2019-04-09 20:00:00 : 동내면   26889 ----------


 ---------- 2019-04-10 09:00:00 : 사북면   26891 ----------


 ---------- 2019-04-10 11:00:00 : 석사동   26893 ----------


 ---------- 2019-04-10 13:00:00 : 남산면   26894 ----------


 ---------- 2019-04-10 21:00:00 : 퇴계동   26895 ----------


 ---------- 2019-04-10 23:00:00 : 동내면   26897 ----------


 ---------- 2019-04-11 06:00:00 : 퇴계동   26899 ----------


 ---------- 2019-04-11 12:00:00 : 남산면   26900 ----------


 ---------- 2019-04-11 12:00:00 : 동  면   26901 ----------


 ---------- 2019-04-11 13:00:00 : 석사동   26902 ----------


 ---------- 2019-04-11 15:00:00 : 퇴계동   26904 ----------


 ---------- 2019-04-11 19:00:00 : 효자1동   26906 ----------


 ---------- 2019-04-11 21:00:00 : 강남동   26907 ----------


 ---------- 2019-04-12 11:00:00 : 퇴계동   26908 ----------


 ---------- 2019-04-12 13:00:00 : 효자1동   26909 ----------


 ---------- 2019-04-12 17:00:00 : 동내면   26911 ----------


 ---------- 2019-04-12 20:00:00 : 퇴계동   26912 ----------


 ---------- 2019-04-13 01:00:00 : 동산면   26914 ----------


 ---------- 2019-04-13 06:00:00 : 동내면   26916 ----------


 ---------- 2019-04-13 09:00:00 : 신동면   26918 ----------


 ---------- 2019-04-13 09:00:00 : 근화동   26919 ----------


 ---------- 2019-04-13 09:00:00 : 북산면   26920 ----------


 ---------- 2019-04-13 11:00:00 : 동내면   26921 ----------


 ---------- 2019-04-13 16:00:00 : 사북면   26922 ----------


 ---------- 2019-04-14 12:00:00 : 동산면   26923 ----------


 ---------- 2019-04-14 13:00:00 : 후평1동   26925 ----------


 ---------- 2019-04-14 13:00:00 : 북산면   26926 ----------


 ---------- 2019-04-14 14:00:00 : 남산면   26929 ----------


 ---------- 2019-04-14 14:00:00 : 퇴계동   26931 ----------


 ---------- 2019-04-14 17:00:00 : 퇴계동   26932 ----------


 ---------- 2019-04-15 01:00:00 : 동  면   26934 ----------


 ---------- 2019-04-15 07:00:00 : 신동면   26935 ----------


 ---------- 2019-04-15 10:00:00 : 신사우동   26939 ----------


 ---------- 2019-04-15 14:00:00 : 강남동   26940 ----------


 ---------- 2019-04-15 20:00:00 : 조운동   26942 ----------


 ---------- 2019-04-16 00:00:00 : 동산면   26944 ----------


 ---------- 2019-04-16 01:00:00 : 동산면   26945 ----------


 ---------- 2019-04-16 06:00:00 : 남산면   26946 ----------


 ---------- 2019-04-16 07:00:00 : 퇴계동   26947 ----------


 ---------- 2019-04-16 08:00:00 : 동  면   26949 ----------


 ---------- 2019-04-16 11:00:00 : 동  면   26950 ----------


 ---------- 2019-04-16 14:00:00 : 서  면   26953 ----------


 ---------- 2019-04-16 16:00:00 : 신북읍   26954 ----------


 ---------- 2019-04-16 23:00:00 : 동  면   26956 ----------


 ---------- 2019-04-17 07:00:00 : 동내면   26958 ----------


 ---------- 2019-04-17 08:00:00 : 강남동   26959 ----------


 ---------- 2019-04-17 09:00:00 : 남  면   26961 ----------


 ---------- 2019-04-17 14:00:00 : 석사동   26963 ----------


 ---------- 2019-04-17 19:00:00 : 신북읍   26965 ----------


 ---------- 2019-04-18 09:00:00 : 효자1동   26966 ----------


 ---------- 2019-04-18 14:00:00 : 신북읍   26968 ----------


 ---------- 2019-04-18 14:00:00 : 후평1동   26969 ----------

 ---------- 2019-04-18 17:00:00 : 남산면   26970 ----------


 ---------- 2019-04-18 19:00:00 : 퇴계동   26971 ----------


 ---------- 2019-04-18 22:00:00 : 동  면   26972 ----------


 ---------- 2019-04-19 09:00:00 : 효자1동   26973 ----------


 ---------- 2019-04-19 11:00:00 : 동내면   26976 ----------


 ---------- 2019-04-19 14:00:00 : 퇴계동   26977 ----------


 ---------- 2019-04-20 09:00:00 : 후평1동   26978 ----------


 ---------- 2019-04-20 10:00:00 : 약사명동   26979 ----------


 ---------- 2019-04-20 12:00:00 : 사북면   26980 ----------


 ---------- 2019-04-20 12:00:00 : 동  면   26981 ----------


 ---------- 2019-04-20 16:00:00 : 신동면   26982 ----------


 ---------- 2019-04-20 16:00:00 : 동내면   26983 ----------


 ---------- 2019-04-20 22:00:00 : 동내면   26985 ----------


 ---------- 2019-04-21 01:00:00 : 근화동   26986 ----------


 ---------- 2019-04-21 05:00:00 : 동  면   26987 ----------


 ---------- 2019-04-21 09:00:00 : 강남동   26990 ----------


 ---------- 2019-04-21 10:00:00 : 퇴계동   26991 ----------


 ---------- 2019-04-21 15:00:00 : 근화동   26994 ----------


 ---------- 2019-04-21 18:00:00 : 남산면   26995 ----------


 ---------- 2019-04-21 19:00:00 : 강남동   26997 ----------


 ---------- 2019-04-21 20:00:00 : 동산면   26998 ----------


 ---------- 2019-04-22 08:00:00 : 신사우동   26999 ----------


 ---------- 2019-04-22 09:00:00 : 신동면   27001 ----------


 ---------- 2019-04-22 10:00:00 : 후평1동   27002 ----------


 ---------- 2019-04-22 16:00:00 : 신사우동   27003 ----------


 ---------- 2019-04-22 17:00:00 : 후평1동   27005 ----------


 ---------- 2019-04-23 08:00:00 : 석사동   27007 ----------


 ---------- 2019-04-23 11:00:00 : 효자1동   27009 ----------


 ---------- 2019-04-23 13:00:00 : 동내면   27010 ----------


 ---------- 2019-04-23 13:00:00 : 효자1동   27011 ----------


 ---------- 2019-04-23 15:00:00 : 신북읍   27012 ----------


 ---------- 2019-04-23 22:00:00 : 효자1동   27013 ----------


 ---------- 2019-04-23 23:00:00 : 효자1동   27015 ----------


 ---------- 2019-04-24 08:00:00 : 신사우동   27017 ----------


 ---------- 2019-04-24 12:00:00 : 효자1동   27018 ----------


 ---------- 2019-04-24 13:00:00 : 석사동   27019 ----------


 ---------- 2019-04-24 13:00:00 : 근화동   27021 ----------


 ---------- 2019-04-24 14:00:00 : 동  면   27022 ----------


 ---------- 2019-04-24 16:00:00 : 퇴계동   27023 ----------


 ---------- 2019-04-25 10:00:00 : 효자1동   27026 ----------


 ---------- 2019-04-25 11:00:00 : 퇴계동   27028 ----------


 ---------- 2019-04-25 17:00:00 : 동산면   27029 ----------


 ---------- 2019-04-25 18:00:00 : 신사우동   27031 ----------


 ---------- 2019-04-25 19:00:00 : 소양동   27033 ----------


 ---------- 2019-04-25 21:00:00 : 신북읍   27036 ----------


 ---------- 2019-04-25 21:00:00 : 퇴계동   27037 ----------


 ---------- 2019-04-25 21:00:00 : 동산면   27040 ----------


 ---------- 2019-04-26 00:00:00 : 남  면   27043 ----------


 ---------- 2019-04-26 12:00:00 : 조운동   27045 ----------


 ---------- 2019-04-26 13:00:00 : 강남동   27047 ----------


 ---------- 2019-04-26 14:00:00 : 후평1동   27049 ----------


 ---------- 2019-04-26 15:00:00 : 신사우동   27050 ----------


 ---------- 2019-04-26 19:00:00 : 효자1동   27052 ----------


 ---------- 2019-04-26 19:00:00 : 후평1동   27054 ----------


 ---------- 2019-04-26 23:00:00 : 약사명동   27056 ----------


 ---------- 2019-04-27 07:00:00 : 퇴계동   27057 ----------


 ---------- 2019-04-27 16:00:00 : 북산면   27060 ----------


 ---------- 2019-04-27 17:00:00 : 석사동   27062 ----------


 ---------- 2019-04-27 18:00:00 : 서  면   27063 ----------


 ---------- 2019-04-27 18:00:00 : 동내면   27064 ----------


 ---------- 2019-04-27 18:00:00 : 북산면   27065 ----------


 ---------- 2019-04-28 05:00:00 : 사북면   27067 ----------


 ---------- 2019-04-28 06:00:00 : 동내면   27068 ----------


 ---------- 2019-04-28 08:00:00 : 석사동   27070 ----------


 ---------- 2019-04-28 09:00:00 : 남산면   27071 ----------


 ---------- 2019-04-28 14:00:00 : 조운동   27073 ----------


 ---------- 2019-04-28 15:00:00 : 서  면   27075 ----------


 ---------- 2019-04-29 04:00:00 : 소양동   27076 ----------


 ---------- 2019-04-29 10:00:00 : 신동면   27078 ----------


 ---------- 2019-04-29 14:00:00 : 남산면   27081 ----------


 ---------- 2019-04-29 15:00:00 : 신동면   27082 ----------


 ---------- 2019-04-29 17:00:00 : 서  면   27084 ----------


 ---------- 2019-04-29 19:00:00 : 후평1동   27085 ----------


 ---------- 2019-04-29 23:00:00 : 신사우동   27087 ----------


 ---------- 2019-04-30 00:00:00 : 동내면   27088 ----------


 ---------- 2019-04-30 07:00:00 : 강남동   27090 ----------


 ---------- 2019-04-30 08:00:00 : 강남동   27092 ----------


 ---------- 2019-04-30 10:00:00 : 조운동   27093 ----------


 ---------- 2019-04-30 11:00:00 : 남산면   27095 ----------


 ---------- 2019-04-30 17:00:00 : 효자1동   27096 ----------


 ---------- 2019-04-30 18:00:00 : 후평1동   27097 ----------


 ---------- 2019-04-30 19:00:00 : 퇴계동   27098 ----------


 ---------- 2019-05-01 08:00:00 : 석사동   27100 ----------


 ---------- 2019-05-01 09:00:00 : 서  면   27103 ----------


 ---------- 2019-05-01 09:00:00 : 효자1동   27104 ----------


 ---------- 2019-05-01 12:00:00 : 강남동   27106 ----------


 ---------- 2019-05-01 12:00:00 : 서  면   27107 ----------


 ---------- 2019-05-01 15:00:00 : 서  면   27108 ----------


 ---------- 2019-05-01 18:00:00 : 소양동   27110 ----------


 ---------- 2019-05-01 19:00:00 : 남산면   27111 ----------


 ---------- 2019-05-02 01:00:00 : 퇴계동   27112 ----------


 ---------- 2019-05-02 07:00:00 : 효자1동   27114 ----------


 ---------- 2019-05-02 08:00:00 : 후평1동   27115 ----------


 ---------- 2019-05-02 15:00:00 : 효자1동   27116 ----------


 ---------- 2019-05-02 15:00:00 : 신북읍   27118 ----------


 ---------- 2019-05-02 16:00:00 : 남산면   27120 ----------


 ---------- 2019-05-02 18:00:00 : 동내면   27121 ----------


 ---------- 2019-05-03 01:00:00 : 석사동   27123 ----------


 ---------- 2019-05-03 08:00:00 : 신동면   27125 ----------


 ---------- 2019-05-03 08:00:00 : 신사우동   27126 ----------


 ---------- 2019-05-03 10:00:00 : 신동면   27127 ----------


 ---------- 2019-05-03 13:00:00 : 남  면   27128 ----------


 ---------- 2019-05-03 16:00:00 : 서  면   27129 ----------


 ---------- 2019-05-03 21:00:00 : 퇴계동   27130 ----------


 ---------- 2019-05-03 22:00:00 : 강남동   27131 ----------


 ---------- 2019-05-04 11:00:00 : 동내면   27133 ----------


 ---------- 2019-05-04 11:00:00 : 후평1동   27134 ----------


 ---------- 2019-05-04 12:00:00 : 강남동   27135 ----------


 ---------- 2019-05-04 18:00:00 : 후평1동   27136 ----------


 ---------- 2019-05-04 18:00:00 : 퇴계동   27139 ----------


 ---------- 2019-05-04 23:00:00 : 석사동   27140 ----------


 ---------- 2019-05-05 03:00:00 : 강남동   27142 ----------


 ---------- 2019-05-05 08:00:00 : 동내면   27143 ----------


 ---------- 2019-05-05 08:00:00 : 후평1동   27144 ----------


 ---------- 2019-05-05 13:00:00 : 효자1동   27145 ----------


 ---------- 2019-05-05 15:00:00 : 북산면   27146 ----------


 ---------- 2019-05-05 16:00:00 : 강남동   27147 ----------


 ---------- 2019-05-05 16:00:00 : 동내면   27148 ----------


 ---------- 2019-05-05 18:00:00 : 석사동   27149 ----------


 ---------- 2019-05-05 19:00:00 : 동  면   27151 ----------


 ---------- 2019-05-05 23:00:00 : 동산면   27152 ----------


 ---------- 2019-05-06 02:00:00 : 신사우동   27153 ----------


 ---------- 2019-05-06 09:00:00 : 후평1동   27154 ----------


 ---------- 2019-05-06 13:00:00 : 북산면   27156 ----------


 ---------- 2019-05-06 15:00:00 : 강남동   27157 ----------


 ---------- 2019-05-06 15:00:00 : 신사우동   27158 ----------


 ---------- 2019-05-06 16:00:00 : 신사우동   27159 ----------


 ---------- 2019-05-06 17:00:00 : 강남동   27160 ----------


 ---------- 2019-05-06 19:00:00 : 근화동   27161 ----------


 ---------- 2019-05-06 21:00:00 : 동내면   27162 ----------


 ---------- 2019-05-07 00:00:00 : 퇴계동   27166 ----------


 ---------- 2019-05-07 01:00:00 : 교  동   27167 ----------


 ---------- 2019-05-07 07:00:00 : 신동면   27168 ----------


 ---------- 2019-05-07 10:00:00 : 신동면   27169 ----------


 ---------- 2019-05-07 11:00:00 : 동  면   27170 ----------


 ---------- 2019-05-07 11:00:00 : 후평1동   27171 ----------

 ---------- 2019-05-07 13:00:00 : 남산면   27172 ----------


 ---------- 2019-05-07 17:00:00 : 후평1동   27173 ----------


 ---------- 2019-05-07 19:00:00 : 신북읍   27175 ----------


 ---------- 2019-05-07 21:00:00 : 석사동   27177 ----------


 ---------- 2019-05-07 23:00:00 : 효자1동   27178 ----------


 ---------- 2019-05-07 23:00:00 : 퇴계동   27179 ----------


 ---------- 2019-05-08 11:00:00 : 서  면   27180 ----------


 ---------- 2019-05-09 09:00:00 : 사북면   27181 ----------


 ---------- 2019-05-09 14:00:00 : 강남동   27182 ----------


 ---------- 2019-05-10 10:00:00 : 약사명동   27183 ----------


 ---------- 2019-05-10 14:00:00 : 동산면   27184 ----------


 ---------- 2019-05-11 03:00:00 : 석사동   27185 ----------


 ---------- 2019-05-11 10:00:00 : 석사동   27186 ----------


 ---------- 2019-05-11 10:00:00 : 북산면   27187 ----------


 ---------- 2019-05-11 13:00:00 : 남산면   27189 ----------


 ---------- 2019-05-11 18:00:00 : 서  면   27191 ----------


 ---------- 2019-05-11 22:00:00 : 사북면   27193 ----------


 ---------- 2019-05-12 03:00:00 : 신사우동   27194 ----------


 ---------- 2019-05-12 05:00:00 : 사북면   27197 ----------


 ---------- 2019-05-12 06:00:00 : 사북면   27198 ----------


 ---------- 2019-05-12 08:00:00 : 사북면   27199 ----------


 ---------- 2019-05-12 11:00:00 : 강남동   27200 ----------


 ---------- 2019-05-12 11:00:00 : 동  면   27201 ----------


 ---------- 2019-05-12 12:00:00 : 사북면   27202 ----------


 ---------- 2019-05-12 13:00:00 : 북산면   27205 ----------


 ---------- 2019-05-12 17:00:00 : 강남동   27207 ----------


 ---------- 2019-05-12 17:00:00 : 동  면   27208 ----------


 ---------- 2019-05-12 20:00:00 : 동내면   27209 ----------


 ---------- 2019-05-13 06:00:00 : 사북면   27210 ----------


 ---------- 2019-05-13 08:00:00 : 사북면   27211 ----------


 ---------- 2019-05-13 08:00:00 : 남산면   27213 ----------


 ---------- 2019-05-13 09:00:00 : 사북면   27214 ----------


 ---------- 2019-05-13 10:00:00 : 석사동   27215 ----------


 ---------- 2019-05-13 16:00:00 : 서  면   27217 ----------


 ---------- 2019-05-14 06:00:00 : 강남동   27220 ----------


 ---------- 2019-05-14 07:00:00 : 사북면   27221 ----------


 ---------- 2019-05-14 08:00:00 : 사북면   27223 ----------


 ---------- 2019-05-14 12:00:00 : 동  면   27224 ----------


 ---------- 2019-05-14 12:00:00 : 후평1동   27225 ----------


 ---------- 2019-05-14 14:00:00 : 효자1동   27227 ----------


 ---------- 2019-05-14 17:00:00 : 근화동   27228 ----------


 ---------- 2019-05-14 18:00:00 : 근화동   27230 ----------


 ---------- 2019-05-14 19:00:00 : 석사동   27231 ----------


 ---------- 2019-05-14 19:00:00 : 동내면   27232 ----------


 ---------- 2019-05-15 05:00:00 : 사북면   27234 ----------


 ---------- 2019-05-15 07:00:00 : 사북면   27235 ----------


 ---------- 2019-05-15 13:00:00 : 후평1동   27236 ----------


 ---------- 2019-05-15 15:00:00 : 신북읍   27237 ----------


 ---------- 2019-05-15 15:00:00 : 동산면   27239 ----------


 ---------- 2019-05-15 18:00:00 : 동  면   27240 ----------


 ---------- 2019-05-16 02:00:00 : 석사동   27241 ----------


 ---------- 2019-05-16 07:00:00 : 사북면   27243 ----------


 ---------- 2019-05-16 08:00:00 : 사북면   27244 ----------


 ---------- 2019-05-16 12:00:00 : 소양동   27245 ----------


 ---------- 2019-05-16 15:00:00 : 사북면   27247 ----------


 ---------- 2019-05-16 16:00:00 : 사북면   27248 ----------


 ---------- 2019-05-16 20:00:00 : 효자1동   27249 ----------


 ---------- 2019-05-17 06:00:00 : 사북면   27250 ----------


 ---------- 2019-05-17 07:00:00 : 사북면   27251 ----------


 ---------- 2019-05-17 08:00:00 : 사북면   27252 ----------


 ---------- 2019-05-17 08:00:00 : 후평1동   27253 ----------


 ---------- 2019-05-17 10:00:00 : 후평1동   27255 ----------


 ---------- 2019-05-17 12:00:00 : 남  면   27256 ----------


 ---------- 2019-05-17 14:00:00 : 석사동   27257 ----------


 ---------- 2019-05-17 14:00:00 : 퇴계동   27258 ----------


 ---------- 2019-05-17 15:00:00 : 남산면   27259 ----------


 ---------- 2019-05-17 17:00:00 : 동내면   27260 ----------


 ---------- 2019-05-17 19:00:00 : 동내면   27261 ----------


 ---------- 2019-05-17 23:00:00 : 동  면   27263 ----------


 ---------- 2019-05-17 23:00:00 : 퇴계동   27264 ----------


 ---------- 2019-05-18 03:00:00 : 소양동   27265 ----------


 ---------- 2019-05-18 07:00:00 : 사북면   27266 ----------


 ---------- 2019-05-18 11:00:00 : 퇴계동   27268 ----------


 ---------- 2019-05-18 15:00:00 : 신동면   27269 ----------


 ---------- 2019-05-18 15:00:00 : 강남동   27270 ----------


 ---------- 2019-05-18 20:00:00 : 동내면   27271 ----------


 ---------- 2019-05-18 21:00:00 : 근화동   27274 ----------


 ---------- 2019-05-18 22:00:00 : 신사우동   27275 ----------


 ---------- 2019-05-19 03:00:00 : 효자1동   27276 ----------


 ---------- 2019-05-19 07:00:00 : 강남동   27277 ----------


 ---------- 2019-05-19 14:00:00 : 북산면   27278 ----------


 ---------- 2019-05-20 05:00:00 : 근화동   27280 ----------


 ---------- 2019-05-20 09:00:00 : 석사동   27281 ----------


 ---------- 2019-05-20 10:00:00 : 후평1동   27282 ----------


 ---------- 2019-05-20 12:00:00 : 사북면   27283 ----------


 ---------- 2019-05-20 12:00:00 : 퇴계동   27284 ----------


 ---------- 2019-05-20 15:00:00 : 후평1동   27285 ----------


 ---------- 2019-05-20 16:00:00 : 남산면   27287 ----------


 ---------- 2019-05-20 17:00:00 : 동내면   27288 ----------


 ---------- 2019-05-20 20:00:00 : 신북읍   27289 ----------


 ---------- 2019-05-21 06:00:00 : 동내면   27290 ----------


 ---------- 2019-05-21 18:00:00 : 신사우동   27291 ----------


 ---------- 2019-05-21 20:00:00 : 강남동   27292 ----------


 ---------- 2019-05-22 07:00:00 : 소양동   27294 ----------


 ---------- 2019-05-22 08:00:00 : 신북읍   27295 ----------


 ---------- 2019-05-22 11:00:00 : 강남동   27297 ----------


 ---------- 2019-05-22 12:00:00 : 동내면   27298 ----------


 ---------- 2019-05-22 17:00:00 : 사북면   27299 ----------


 ---------- 2019-05-22 18:00:00 : 후평1동   27301 ----------


 ---------- 2019-05-22 20:00:00 : 강남동   27302 ----------


 ---------- 2019-05-22 20:00:00 : 서  면   27303 ----------


 ---------- 2019-05-22 21:00:00 : 후평1동   27304 ----------


 ---------- 2019-05-23 05:00:00 : 후평1동   27305 ----------


 ---------- 2019-05-23 19:00:00 : 효자1동   27307 ----------


 ---------- 2019-05-23 19:00:00 : 근화동   27308 ----------


 ---------- 2019-05-23 22:00:00 : 후평1동   27310 ----------


 ---------- 2019-05-24 09:00:00 : 동  면   27312 ----------


 ---------- 2019-05-24 11:00:00 : 동  면   27313 ----------


 ---------- 2019-05-24 11:00:00 : 후평1동   27314 ----------


 ---------- 2019-05-24 12:00:00 : 남산면   27316 ----------


 ---------- 2019-05-24 14:00:00 : 서  면   27317 ----------


 ---------- 2019-05-24 15:00:00 : 동  면   27318 ----------


 ---------- 2019-05-24 18:00:00 : 신사우동   27319 ----------


 ---------- 2019-05-24 19:00:00 : 동내면   27322 ----------


 ---------- 2019-05-24 19:00:00 : 신북읍   27323 ----------


 ---------- 2019-05-24 21:00:00 : 소양동   27324 ----------


 ---------- 2019-05-25 09:00:00 : 퇴계동   27326 ----------


 ---------- 2019-05-25 14:00:00 : 동  면   27327 ----------


 ---------- 2019-05-25 16:00:00 : 근화동   27328 ----------


 ---------- 2019-05-25 18:00:00 : 강남동   27329 ----------


 ---------- 2019-05-25 18:00:00 : 신북읍   27330 ----------


 ---------- 2019-05-25 21:00:00 : 신사우동   27331 ----------


 ---------- 2019-05-26 04:00:00 : 효자1동   27332 ----------


 ---------- 2019-05-26 06:00:00 : 남  면   27334 ----------


 ---------- 2019-05-26 10:00:00 : 동  면   27335 ----------


 ---------- 2019-05-26 11:00:00 : 서  면   27337 ----------


 ---------- 2019-05-26 11:00:00 : 신북읍   27338 ----------


 ---------- 2019-05-26 16:00:00 : 동산면   27341 ----------


 ---------- 2019-05-26 22:00:00 : 석사동   27342 ----------


 ---------- 2019-05-26 23:00:00 : 약사명동   27343 ----------


 ---------- 2019-05-27 01:00:00 : 효자1동   27344 ----------


 ---------- 2019-05-27 04:00:00 : 효자1동   27345 ----------


 ---------- 2019-05-27 12:00:00 : 남산면   27347 ----------


 ---------- 2019-05-27 17:00:00 : 퇴계동   27349 ----------


 ---------- 2019-05-28 08:00:00 : 남산면   27350 ----------


 ---------- 2019-05-28 09:00:00 : 동산면   27351 ----------

 ---------- 2019-05-28 12:00:00 : 후평1동   27353 ----------


 ---------- 2019-05-28 15:00:00 : 후평1동   27354 ----------


 ---------- 2019-05-28 16:00:00 : 퇴계동   27355 ----------


 ---------- 2019-05-28 17:00:00 : 후평1동   27356 ----------


 ---------- 2019-05-28 17:00:00 : 교  동   27357 ----------


 ---------- 2019-05-28 19:00:00 : 동  면   27358 ----------


 ---------- 2019-05-28 20:00:00 : 후평1동   27359 ----------


 ---------- 2019-05-29 08:00:00 : 동내면   27361 ----------


 ---------- 2019-05-29 08:00:00 : 남산면   27363 ----------


 ---------- 2019-05-29 13:00:00 : 강남동   27365 ----------


 ---------- 2019-05-29 17:00:00 : 강남동   27366 ----------


 ---------- 2019-05-30 00:00:00 : 동내면   27367 ----------


 ---------- 2019-05-30 16:00:00 : 근화동   27368 ----------


 ---------- 2019-05-30 17:00:00 : 동산면   27370 ----------


 ---------- 2019-05-30 23:00:00 : 석사동   27372 ----------


 ---------- 2019-05-30 23:00:00 : 신북읍   27373 ----------


 ---------- 2019-05-31 01:00:00 : 남산면   27374 ----------


 ---------- 2019-05-31 10:00:00 : 신북읍   27375 ----------


 ---------- 2019-05-31 12:00:00 : 후평1동   27376 ----------


 ---------- 2019-05-31 13:00:00 : 석사동   27377 ----------


 ---------- 2019-05-31 17:00:00 : 근화동   27379 ----------


 ---------- 2019-05-31 18:00:00 : 석사동   27380 ----------


 ---------- 2019-05-31 20:00:00 : 신동면   27381 ----------


 ---------- 2019-06-01 09:00:00 : 강남동   27382 ----------


 ---------- 2019-06-01 09:00:00 : 후평1동   27383 ----------


 ---------- 2019-06-01 10:00:00 : 퇴계동   27385 ----------


 ---------- 2019-06-01 10:00:00 : 동산면   27386 ----------


 ---------- 2019-06-01 11:00:00 : 동산면   27387 ----------


 ---------- 2019-06-01 12:00:00 : 강남동   27388 ----------


 ---------- 2019-06-01 14:00:00 : 약사명동   27389 ----------


 ---------- 2019-06-01 20:00:00 : 근화동   27391 ----------


 ---------- 2019-06-02 01:00:00 : 동내면   27392 ----------


 ---------- 2019-06-02 07:00:00 : 서  면   27393 ----------


 ---------- 2019-06-02 07:00:00 : 남산면   27394 ----------


 ---------- 2019-06-02 13:00:00 : 북산면   27397 ----------


 ---------- 2019-06-02 15:00:00 : 동  면   27398 ----------


 ---------- 2019-06-02 21:00:00 : 효자1동   27400 ----------


 ---------- 2019-06-03 02:00:00 : 신사우동   27401 ----------


 ---------- 2019-06-03 11:00:00 : 효자1동   27403 ----------


 ---------- 2019-06-03 11:00:00 : 동  면   27405 ----------


 ---------- 2019-06-03 13:00:00 : 동  면   27406 ----------


 ---------- 2019-06-03 14:00:00 : 근화동   27407 ----------


 ---------- 2019-06-03 19:00:00 : 퇴계동   27408 ----------


 ---------- 2019-06-04 07:00:00 : 퇴계동   27409 ----------


 ---------- 2019-06-04 10:00:00 : 강남동   27411 ----------


 ---------- 2019-06-04 13:00:00 : 석사동   27412 ----------


 ---------- 2019-06-04 13:00:00 : 퇴계동   27414 ----------


 ---------- 2019-06-05 09:00:00 : 동내면   27415 ----------


 ---------- 2019-06-05 09:00:00 : 신사우동   27416 ----------


 ---------- 2019-06-05 10:00:00 : 약사명동   27417 ----------


 ---------- 2019-06-05 11:00:00 : 강남동   27418 ----------


 ---------- 2019-06-05 11:00:00 : 근화동   27419 ----------


 ---------- 2019-06-05 14:00:00 : 강남동   27420 ----------


 ---------- 2019-06-05 14:00:00 : 동  면   27421 ----------


 ---------- 2019-06-05 14:00:00 : 북산면   27423 ----------


 ---------- 2019-06-05 16:00:00 : 동내면   27424 ----------


 ---------- 2019-06-05 19:00:00 : 소양동   27425 ----------


 ---------- 2019-06-05 20:00:00 : 효자1동   27427 ----------


 ---------- 2019-06-05 20:00:00 : 동  면   27429 ----------


 ---------- 2019-06-05 21:00:00 : 효자1동   27430 ----------


 ---------- 2019-06-05 22:00:00 : 효자1동   27431 ----------


 ---------- 2019-06-05 23:00:00 : 석사동   27432 ----------


 ---------- 2019-06-06 04:00:00 : 효자1동   27433 ----------


 ---------- 2019-06-06 08:00:00 : 조운동   27434 ----------


 ---------- 2019-06-06 10:00:00 : 강남동   27435 ----------


 ---------- 2019-06-06 14:00:00 : 퇴계동   27436 ----------


 ---------- 2019-06-06 15:00:00 : 강남동   27437 ----------


 ---------- 2019-06-06 16:00:00 : 신동면   27439 ----------


 ---------- 2019-06-06 20:00:00 : 효자1동   27440 ----------


 ---------- 2019-06-07 04:00:00 : 소양동   27441 ----------


 ---------- 2019-06-07 05:00:00 : 강남동   27442 ----------


 ---------- 2019-06-07 10:00:00 : 효자1동   27443 ----------


 ---------- 2019-06-07 11:00:00 : 동산면   27445 ----------


 ---------- 2019-06-07 12:00:00 : 동산면   27446 ----------


 ---------- 2019-06-07 14:00:00 : 남  면   27449 ----------


 ---------- 2019-06-07 16:00:00 : 신사우동   27450 ----------


 ---------- 2019-06-07 17:00:00 : 동내면   27451 ----------


 ---------- 2019-06-07 17:00:00 : 동  면   27452 ----------


 ---------- 2019-06-07 18:00:00 : 석사동   27454 ----------


 ---------- 2019-06-07 20:00:00 : 서  면   27456 ----------


 ---------- 2019-06-07 23:00:00 : 효자1동   27457 ----------


 ---------- 2019-06-08 12:00:00 : 동  면   27458 ----------


 ---------- 2019-06-08 13:00:00 : 조운동   27459 ----------


 ---------- 2019-06-08 14:00:00 : 퇴계동   27460 ----------


 ---------- 2019-06-08 14:00:00 : 북산면   27462 ----------


 ---------- 2019-06-08 15:00:00 : 동산면   27463 ----------


 ---------- 2019-06-08 23:00:00 : 약사명동   27464 ----------


 ---------- 2019-06-09 10:00:00 : 신북읍   27465 ----------


 ---------- 2019-06-09 13:00:00 : 서  면   27467 ----------


 ---------- 2019-06-09 17:00:00 : 동내면   27468 ----------


 ---------- 2019-06-09 17:00:00 : 신북읍   27470 ----------


 ---------- 2019-06-09 23:00:00 : 동  면   27472 ----------


 ---------- 2019-06-10 11:00:00 : 퇴계동   27473 ----------


 ---------- 2019-06-10 14:00:00 : 사북면   27474 ----------


 ---------- 2019-06-10 17:00:00 : 소양동   27475 ----------


 ---------- 2019-06-10 18:00:00 : 동  면   27476 ----------


 ---------- 2019-06-10 18:00:00 : 후평1동   27477 ----------


 ---------- 2019-06-10 20:00:00 : 효자1동   27478 ----------


 ---------- 2019-06-10 22:00:00 : 퇴계동   27480 ----------


 ---------- 2019-06-11 08:00:00 : 강남동   27482 ----------


 ---------- 2019-06-11 08:00:00 : 남산면   27485 ----------


 ---------- 2019-06-11 09:00:00 : 동  면   27487 ----------


 ---------- 2019-06-11 10:00:00 : 신사우동   27488 ----------


 ---------- 2019-06-11 12:00:00 : 후평1동   27489 ----------


 ---------- 2019-06-11 13:00:00 : 근화동   27490 ----------


 ---------- 2019-06-11 23:00:00 : 석사동   27491 ----------


 ---------- 2019-06-12 07:00:00 : 약사명동   27493 ----------


 ---------- 2019-06-12 10:00:00 : 신북읍   27494 ----------


 ---------- 2019-06-12 10:00:00 : 소양동   27495 ----------


 ---------- 2019-06-12 10:00:00 : 동  면   27496 ----------


 ---------- 2019-06-12 11:00:00 : 동  면   27497 ----------


 ---------- 2019-06-12 11:00:00 : 동산면   27498 ----------


 ---------- 2019-06-12 17:00:00 : 석사동   27499 ----------


 ---------- 2019-06-12 17:00:00 : 효자1동   27500 ----------


 ---------- 2019-06-12 18:00:00 : 강남동   27501 ----------


 ---------- 2019-06-13 00:00:00 : 효자1동   27502 ----------


 ---------- 2019-06-13 09:00:00 : 동  면   27503 ----------


 ---------- 2019-06-13 13:00:00 : 퇴계동   27505 ----------


 ---------- 2019-06-13 16:00:00 : 남산면   27506 ----------


 ---------- 2019-06-13 18:00:00 : 서  면   27507 ----------


 ---------- 2019-06-14 11:00:00 : 후평1동   27509 ----------


 ---------- 2019-06-14 12:00:00 : 석사동   27510 ----------


 ---------- 2019-06-14 12:00:00 : 신북읍   27511 ----------


 ---------- 2019-06-14 20:00:00 : 남  면   27513 ----------


 ---------- 2019-06-14 21:00:00 : 북산면   27515 ----------


 ---------- 2019-06-15 01:00:00 : 후평1동   27516 ----------


 ---------- 2019-06-15 03:00:00 : 소양동   27517 ----------


 ---------- 2019-06-15 08:00:00 : 신사우동   27519 ----------


 ---------- 2019-06-15 10:00:00 : 강남동   27520 ----------


 ---------- 2019-06-15 14:00:00 : 신북읍   27521 ----------


 ---------- 2019-06-15 17:00:00 : 서  면   27522 ----------


 ---------- 2019-06-15 20:00:00 : 후평1동   27523 ----------


 ---------- 2019-06-15 21:00:00 : 후평1동   27524 ----------


 ---------- 2019-06-16 01:00:00 : 남산면   27525 ----------


 ---------- 2019-06-16 05:00:00 : 신동면   27526 ----------


 ---------- 2019-06-16 07:00:00 : 남산면   27527 ----------

 ---------- 2019-06-16 08:00:00 : 남산면   27529 ----------


 ---------- 2019-06-16 10:00:00 : 후평1동   27530 ----------


 ---------- 2019-06-16 11:00:00 : 남산면   27532 ----------


 ---------- 2019-06-16 13:00:00 : 남산면   27533 ----------


 ---------- 2019-06-16 14:00:00 : 효자1동   27535 ----------


 ---------- 2019-06-16 15:00:00 : 서  면   27537 ----------


 ---------- 2019-06-16 16:00:00 : 석사동   27539 ----------


 ---------- 2019-06-16 16:00:00 : 신사우동   27540 ----------


 ---------- 2019-06-16 20:00:00 : 후평1동   27541 ----------


 ---------- 2019-06-16 20:00:00 : 퇴계동   27542 ----------


 ---------- 2019-06-17 10:00:00 : 효자1동   27543 ----------


 ---------- 2019-06-17 10:00:00 : 동  면   27544 ----------


 ---------- 2019-06-17 10:00:00 : 조운동   27545 ----------


 ---------- 2019-06-17 13:00:00 : 서  면   27547 ----------


 ---------- 2019-06-17 13:00:00 : 남산면   27548 ----------


 ---------- 2019-06-17 13:00:00 : 퇴계동   27549 ----------


 ---------- 2019-06-17 14:00:00 : 남산면   27550 ----------


 ---------- 2019-06-17 21:00:00 : 석사동   27551 ----------


 ---------- 2019-06-18 05:00:00 : 석사동   27552 ----------


 ---------- 2019-06-18 09:00:00 : 동내면   27553 ----------


 ---------- 2019-06-18 16:00:00 : 동내면   27554 ----------


 ---------- 2019-06-18 18:00:00 : 근화동   27555 ----------


 ---------- 2019-06-18 18:00:00 : 후평1동   27556 ----------


 ---------- 2019-06-19 10:00:00 : 약사명동   27557 ----------


 ---------- 2019-06-19 13:00:00 : 북산면   27558 ----------


 ---------- 2019-06-19 14:00:00 : 효자1동   27559 ----------


 ---------- 2019-06-19 16:00:00 : 사북면   27560 ----------


 ---------- 2019-06-19 18:00:00 : 북산면   27561 ----------


 ---------- 2019-06-20 00:00:00 : 후평1동   27562 ----------


 ---------- 2019-06-20 01:00:00 : 석사동   27564 ----------


 ---------- 2019-06-20 16:00:00 : 효자1동   27565 ----------


 ---------- 2019-06-20 21:00:00 : 효자1동   27566 ----------


 ---------- 2019-06-20 22:00:00 : 신동면   27567 ----------


 ---------- 2019-06-20 22:00:00 : 퇴계동   27569 ----------


 ---------- 2019-06-21 07:00:00 : 신북읍   27571 ----------


 ---------- 2019-06-21 08:00:00 : 동산면   27572 ----------


 ---------- 2019-06-21 13:00:00 : 북산면   27573 ----------


 ---------- 2019-06-21 14:00:00 : 동산면   27575 ----------


 ---------- 2019-06-21 15:00:00 : 석사동   27576 ----------


 ---------- 2019-06-21 15:00:00 : 강남동   27578 ----------


 ---------- 2019-06-21 19:00:00 : 신사우동   27579 ----------


 ---------- 2019-06-22 06:00:00 : 신북읍   27580 ----------


 ---------- 2019-06-22 07:00:00 : 강남동   27581 ----------


 ---------- 2019-06-22 11:00:00 : 강남동   27582 ----------


 ---------- 2019-06-22 12:00:00 : 강남동   27583 ----------


 ---------- 2019-06-22 12:00:00 : 동산면   27584 ----------


 ---------- 2019-06-22 13:00:00 : 신사우동   27586 ----------


 ---------- 2019-06-22 17:00:00 : 북산면   27587 ----------


 ---------- 2019-06-22 23:00:00 : 효자1동   27588 ----------


 ---------- 2019-06-22 23:00:00 : 후평1동   27590 ----------


 ---------- 2019-06-23 08:00:00 : 신동면   27591 ----------


 ---------- 2019-06-23 11:00:00 : 동산면   27595 ----------


 ---------- 2019-06-23 15:00:00 : 석사동   27597 ----------


 ---------- 2019-06-23 16:00:00 : 신사우동   27598 ----------


 ---------- 2019-06-23 19:00:00 : 효자1동   27599 ----------


 ---------- 2019-06-24 00:00:00 : 석사동   27600 ----------


 ---------- 2019-06-24 06:00:00 : 후평1동   27601 ----------


 ---------- 2019-06-24 09:00:00 : 강남동   27602 ----------


 ---------- 2019-06-24 10:00:00 : 신북읍   27604 ----------


 ---------- 2019-06-24 12:00:00 : 사북면   27605 ----------


 ---------- 2019-06-24 13:00:00 : 동산면   27607 ----------


 ---------- 2019-06-24 14:00:00 : 석사동   27610 ----------


 ---------- 2019-06-24 14:00:00 : 강남동   27611 ----------


 ---------- 2019-06-24 15:00:00 : 석사동   27612 ----------


 ---------- 2019-06-24 16:00:00 : 후평1동   27613 ----------


 ---------- 2019-06-24 18:00:00 : 사북면   27614 ----------


 ---------- 2019-06-24 20:00:00 : 퇴계동   27616 ----------


 ---------- 2019-06-24 23:00:00 : 신사우동   27617 ----------


 ---------- 2019-06-25 09:00:00 : 신사우동   27618 ----------


 ---------- 2019-06-25 09:00:00 : 소양동   27619 ----------


 ---------- 2019-06-25 12:00:00 : 사북면   27620 ----------


 ---------- 2019-06-25 12:00:00 : 신사우동   27621 ----------


 ---------- 2019-06-25 14:00:00 : 신북읍   27623 ----------


 ---------- 2019-06-25 15:00:00 : 사북면   27624 ----------


 ---------- 2019-06-25 17:00:00 : 동내면   27625 ----------


 ---------- 2019-06-25 20:00:00 : 동내면   27627 ----------


 ---------- 2019-06-26 06:00:00 : 조운동   27628 ----------


 ---------- 2019-06-26 08:00:00 : 신사우동   27629 ----------


 ---------- 2019-06-26 09:00:00 : 남  면   27631 ----------


 ---------- 2019-06-26 09:00:00 : 근화동   27632 ----------


 ---------- 2019-06-26 13:00:00 : 서  면   27633 ----------


 ---------- 2019-06-26 14:00:00 : 남산면   27634 ----------


 ---------- 2019-06-26 18:00:00 : 사북면   27636 ----------


 ---------- 2019-06-26 18:00:00 : 신북읍   27637 ----------


 ---------- 2019-06-26 18:00:00 : 후평1동   27638 ----------


 ---------- 2019-06-26 19:00:00 : 동내면   27639 ----------


 ---------- 2019-06-26 22:00:00 : 효자1동   27641 ----------


 ---------- 2019-06-27 15:00:00 : 신북읍   27642 ----------


 ---------- 2019-06-27 16:00:00 : 교  동   27643 ----------


 ---------- 2019-06-27 17:00:00 : 강남동   27644 ----------


 ---------- 2019-06-27 18:00:00 : 남산면   27646 ----------


 ---------- 2019-06-27 19:00:00 : 퇴계동   27647 ----------


 ---------- 2019-06-28 07:00:00 : 석사동   27649 ----------


 ---------- 2019-06-28 08:00:00 : 퇴계동   27650 ----------


 ---------- 2019-06-28 10:00:00 : 사북면   27651 ----------


 ---------- 2019-06-28 10:00:00 : 동내면   27652 ----------


 ---------- 2019-06-28 14:00:00 : 석사동   27653 ----------


 ---------- 2019-06-28 15:00:00 : 신북읍   27654 ----------


 ---------- 2019-06-28 16:00:00 : 강남동   27655 ----------


 ---------- 2019-06-28 21:00:00 : 퇴계동   27656 ----------


 ---------- 2019-06-28 23:00:00 : 퇴계동   27657 ----------


 ---------- 2019-06-29 05:00:00 : 남  면   27659 ----------


 ---------- 2019-06-29 12:00:00 : 신사우동   27660 ----------


 ---------- 2019-06-29 14:00:00 : 동  면   27661 ----------


 ---------- 2019-06-29 16:00:00 : 서  면   27663 ----------


 ---------- 2019-06-29 20:00:00 : 신사우동   27664 ----------


 ---------- 2019-06-29 21:00:00 : 신북읍   27665 ----------


 ---------- 2019-06-29 22:00:00 : 동내면   27666 ----------


 ---------- 2019-06-29 23:00:00 : 동  면   27667 ----------


 ---------- 2019-06-30 09:00:00 : 후평1동   27668 ----------


 ---------- 2019-06-30 11:00:00 : 사북면   27669 ----------


 ---------- 2019-06-30 11:00:00 : 소양동   27671 ----------


 ---------- 2019-06-30 12:00:00 : 북산면   27674 ----------


 ---------- 2019-06-30 13:00:00 : 사북면   27676 ----------


 ---------- 2019-06-30 14:00:00 : 신사우동   27678 ----------


 ---------- 2019-06-30 16:00:00 : 사북면   27680 ----------


 ---------- 2019-06-30 18:00:00 : 서  면   27681 ----------


 ---------- 2019-06-30 19:00:00 : 남산면   27682 ----------


 ---------- 2019-07-01 10:00:00 : 북산면   27685 ----------


 ---------- 2019-07-01 16:00:00 : 서  면   27686 ----------


 ---------- 2019-07-01 22:00:00 : 강남동   27689 ----------


 ---------- 2019-07-01 23:00:00 : 신사우동   27690 ----------


 ---------- 2019-07-02 03:00:00 : 동  면   27691 ----------


 ---------- 2019-07-02 09:00:00 : 신북읍   27692 ----------


 ---------- 2019-07-02 09:00:00 : 동  면   27693 ----------


 ---------- 2019-07-02 10:00:00 : 남산면   27694 ----------


 ---------- 2019-07-02 13:00:00 : 남산면   27695 ----------


 ---------- 2019-07-02 15:00:00 : 동내면   27696 ----------


 ---------- 2019-07-02 15:00:00 : 후평1동   27697 ----------


 ---------- 2019-07-02 17:00:00 : 사북면   27698 ----------


 ---------- 2019-07-03 07:00:00 : 동산면   27701 ----------


 ---------- 2019-07-03 09:00:00 : 동내면   27702 ----------


 ---------- 2019-07-03 09:00:00 : 남산면   27703 ----------


 ---------- 2019-07-03 09:00:00 : 약사명동   27704 ----------


 ---------- 2019-07-03 10:00:00 : 신북읍   27706 ----------


 ---------- 2019-07-03 10:00:00 : 퇴계동   27708 ----------

 ---------- 2019-07-03 11:00:00 : 신북읍   27709 ----------


 ---------- 2019-07-03 11:00:00 : 동산면   27710 ----------


 ---------- 2019-07-03 12:00:00 : 퇴계동   27711 ----------


 ---------- 2019-07-03 13:00:00 : 신북읍   27712 ----------


 ---------- 2019-07-03 13:00:00 : 약사명동   27713 ----------


 ---------- 2019-07-03 13:00:00 : 조운동   27714 ----------


 ---------- 2019-07-03 14:00:00 : 약사명동   27715 ----------


 ---------- 2019-07-04 05:00:00 : 동내면   27717 ----------


 ---------- 2019-07-04 09:00:00 : 서  면   27718 ----------


 ---------- 2019-07-04 10:00:00 : 남산면   27719 ----------


 ---------- 2019-07-04 10:00:00 : 동  면   27720 ----------


 ---------- 2019-07-04 15:00:00 : 동  면   27721 ----------


 ---------- 2019-07-04 18:00:00 : 강남동   27722 ----------


 ---------- 2019-07-04 19:00:00 : 신사우동   27723 ----------


 ---------- 2019-07-04 21:00:00 : 퇴계동   27724 ----------


 ---------- 2019-07-05 05:00:00 : 신동면   27725 ----------


 ---------- 2019-07-05 09:00:00 : 후평1동   27726 ----------


 ---------- 2019-07-05 11:00:00 : 남  면   27727 ----------


 ---------- 2019-07-05 11:00:00 : 동내면   27728 ----------


 ---------- 2019-07-05 13:00:00 : 석사동   27730 ----------


 ---------- 2019-07-05 13:00:00 : 후평1동   27731 ----------


 ---------- 2019-07-05 16:00:00 : 강남동   27732 ----------


 ---------- 2019-07-05 16:00:00 : 남산면   27733 ----------


 ---------- 2019-07-05 17:00:00 : 신동면   27734 ----------


 ---------- 2019-07-05 19:00:00 : 석사동   27736 ----------


 ---------- 2019-07-05 19:00:00 : 신사우동   27737 ----------


 ---------- 2019-07-05 23:00:00 : 남산면   27738 ----------


 ---------- 2019-07-06 05:00:00 : 동산면   27740 ----------


 ---------- 2019-07-06 06:00:00 : 동  면   27742 ----------


 ---------- 2019-07-06 07:00:00 : 효자1동   27743 ----------


 ---------- 2019-07-06 07:00:00 : 소양동   27744 ----------


 ---------- 2019-07-06 09:00:00 : 강남동   27748 ----------


 ---------- 2019-07-06 09:00:00 : 남산면   27750 ----------


 ---------- 2019-07-06 10:00:00 : 남  면   27751 ----------


 ---------- 2019-07-06 10:00:00 : 동  면   27752 ----------


 ---------- 2019-07-06 10:00:00 : 후평1동   27753 ----------


 ---------- 2019-07-06 13:00:00 : 사북면   27754 ----------


 ---------- 2019-07-06 15:00:00 : 동  면   27755 ----------


 ---------- 2019-07-06 16:00:00 : 효자1동   27756 ----------


 ---------- 2019-07-06 17:00:00 : 신북읍   27757 ----------


 ---------- 2019-07-06 17:00:00 : 퇴계동   27758 ----------


 ---------- 2019-07-06 19:00:00 : 교  동   27759 ----------


 ---------- 2019-07-06 20:00:00 : 석사동   27760 ----------


 ---------- 2019-07-06 20:00:00 : 소양동   27761 ----------


 ---------- 2019-07-06 20:00:00 : 후평1동   27762 ----------


 ---------- 2019-07-06 22:00:00 : 강남동   27763 ----------


 ---------- 2019-07-06 22:00:00 : 남  면   27767 ----------


 ---------- 2019-07-07 02:00:00 : 강남동   27769 ----------


 ---------- 2019-07-07 08:00:00 : 신북읍   27770 ----------


 ---------- 2019-07-07 11:00:00 : 소양동   27771 ----------


 ---------- 2019-07-07 13:00:00 : 동내면   27773 ----------


 ---------- 2019-07-07 14:00:00 : 서  면   27775 ----------


 ---------- 2019-07-07 15:00:00 : 사북면   27776 ----------


 ---------- 2019-07-07 15:00:00 : 남산면   27778 ----------


 ---------- 2019-07-07 17:00:00 : 후평1동   27779 ----------


 ---------- 2019-07-07 18:00:00 : 퇴계동   27781 ----------


 ---------- 2019-07-07 20:00:00 : 강남동   27784 ----------


 ---------- 2019-07-07 20:00:00 : 후평1동   27785 ----------


 ---------- 2019-07-07 21:00:00 : 신북읍   27786 ----------


 ---------- 2019-07-07 22:00:00 : 동산면   27787 ----------


 ---------- 2019-07-08 03:00:00 : 효자1동   27789 ----------


 ---------- 2019-07-08 03:00:00 : 퇴계동   27790 ----------


 ---------- 2019-07-08 05:00:00 : 동내면   27791 ----------


 ---------- 2019-07-08 05:00:00 : 퇴계동   27792 ----------


 ---------- 2019-07-08 07:00:00 : 남산면   27793 ----------


 ---------- 2019-07-08 08:00:00 : 남산면   27794 ----------


 ---------- 2019-07-08 11:00:00 : 소양동   27795 ----------


 ---------- 2019-07-08 13:00:00 : 신사우동   27796 ----------


 ---------- 2019-07-08 15:00:00 : 후평1동   27797 ----------


 ---------- 2019-07-08 19:00:00 : 강남동   27798 ----------


 ---------- 2019-07-09 04:00:00 : 석사동   27799 ----------


 ---------- 2019-07-09 05:00:00 : 신사우동   27802 ----------


 ---------- 2019-07-09 05:00:00 : 동  면   27803 ----------


 ---------- 2019-07-09 06:00:00 : 퇴계동   27804 ----------


 ---------- 2019-07-09 08:00:00 : 조운동   27805 ----------


 ---------- 2019-07-09 09:00:00 : 강남동   27806 ----------


 ---------- 2019-07-09 09:00:00 : 효자1동   27808 ----------


 ---------- 2019-07-09 10:00:00 : 신동면   27809 ----------


 ---------- 2019-07-09 10:00:00 : 사북면   27810 ----------


 ---------- 2019-07-09 10:00:00 : 신사우동   27811 ----------


 ---------- 2019-07-09 11:00:00 : 퇴계동   27813 ----------


 ---------- 2019-07-09 14:00:00 : 후평1동   27814 ----------


 ---------- 2019-07-09 17:00:00 : 서  면   27815 ----------


 ---------- 2019-07-09 18:00:00 : 남산면   27816 ----------


 ---------- 2019-07-09 18:00:00 : 신북읍   27817 ----------


 ---------- 2019-07-09 18:00:00 : 북산면   27818 ----------


 ---------- 2019-07-09 19:00:00 : 동  면   27820 ----------


 ---------- 2019-07-10 05:00:00 : 후평1동   27821 ----------


 ---------- 2019-07-10 09:00:00 : 남산면   27822 ----------


 ---------- 2019-07-10 09:00:00 : 소양동   27823 ----------


 ---------- 2019-07-10 11:00:00 : 동내면   27824 ----------


 ---------- 2019-07-10 12:00:00 : 서  면   27825 ----------


 ---------- 2019-07-10 14:00:00 : 강남동   27826 ----------


 ---------- 2019-07-10 14:00:00 : 소양동   27827 ----------


 ---------- 2019-07-10 15:00:00 : 석사동   27828 ----------


 ---------- 2019-07-10 17:00:00 : 서  면   27829 ----------


 ---------- 2019-07-10 18:00:00 : 근화동   27830 ----------


 ---------- 2019-07-11 05:00:00 : 석사동   27831 ----------


 ---------- 2019-07-11 07:00:00 : 후평1동   27832 ----------


 ---------- 2019-07-11 08:00:00 : 동산면   27833 ----------


 ---------- 2019-07-11 10:00:00 : 신동면   27834 ----------


 ---------- 2019-07-11 10:00:00 : 남산면   27835 ----------


 ---------- 2019-07-11 11:00:00 : 강남동   27837 ----------


 ---------- 2019-07-11 11:00:00 : 신북읍   27838 ----------


 ---------- 2019-07-11 13:00:00 : 남산면   27839 ----------


 ---------- 2019-07-11 15:00:00 : 남산면   27840 ----------


 ---------- 2019-07-11 15:00:00 : 퇴계동   27842 ----------


 ---------- 2019-07-11 22:00:00 : 교  동   27843 ----------


 ---------- 2019-07-12 08:00:00 : 후평1동   27844 ----------


 ---------- 2019-07-12 09:00:00 : 사북면   27845 ----------


 ---------- 2019-07-12 09:00:00 : 후평1동   27846 ----------


 ---------- 2019-07-12 11:00:00 : 남  면   27847 ----------


 ---------- 2019-07-12 11:00:00 : 동내면   27848 ----------


 ---------- 2019-07-12 14:00:00 : 신사우동   27849 ----------


 ---------- 2019-07-12 16:00:00 : 신북읍   27850 ----------


 ---------- 2019-07-12 16:00:00 : 북산면   27851 ----------


 ---------- 2019-07-12 17:00:00 : 신북읍   27852 ----------


 ---------- 2019-07-12 18:00:00 : 신북읍   27853 ----------


 ---------- 2019-07-12 19:00:00 : 효자1동   27854 ----------


 ---------- 2019-07-12 20:00:00 : 북산면   27855 ----------


 ---------- 2019-07-12 21:00:00 : 동  면   27856 ----------


 ---------- 2019-07-12 22:00:00 : 강남동   27857 ----------


 ---------- 2019-07-13 08:00:00 : 남산면   27859 ----------


 ---------- 2019-07-13 09:00:00 : 남  면   27860 ----------


 ---------- 2019-07-13 09:00:00 : 사북면   27861 ----------


 ---------- 2019-07-13 09:00:00 : 후평1동   27862 ----------


 ---------- 2019-07-13 10:00:00 : 남  면   27863 ----------


 ---------- 2019-07-13 10:00:00 : 북산면   27864 ----------


 ---------- 2019-07-13 11:00:00 : 서  면   27865 ----------


 ---------- 2019-07-13 11:00:00 : 사북면   27867 ----------


 ---------- 2019-07-13 11:00:00 : 동  면   27868 ----------


 ---------- 2019-07-13 13:00:00 : 강남동   27870 ----------


 ---------- 2019-07-13 13:00:00 : 서  면   27871 ----------


 ---------- 2019-07-13 14:00:00 : 남산면   27872 ----------


 ---------- 2019-07-13 14:00:00 : 동  면   27873 ----------


 ---------- 2019-07-13 15:00:00 : 교  동   27874 ----------


 ---------- 2019-07-13 16:00:00 : 강남동   27875 ----------

 ---------- 2019-07-13 17:00:00 : 신동면   27876 ----------


 ---------- 2019-07-13 17:00:00 : 효자1동   27877 ----------


 ---------- 2019-07-13 18:00:00 : 신북읍   27879 ----------


 ---------- 2019-07-13 18:00:00 : 동산면   27880 ----------


 ---------- 2019-07-13 20:00:00 : 남산면   27881 ----------


 ---------- 2019-07-14 07:00:00 : 서  면   27885 ----------


 ---------- 2019-07-14 07:00:00 : 사북면   27886 ----------


 ---------- 2019-07-14 09:00:00 : 강남동   27887 ----------


 ---------- 2019-07-14 09:00:00 : 남산면   27888 ----------


 ---------- 2019-07-14 11:00:00 : 동  면   27889 ----------


 ---------- 2019-07-14 14:00:00 : 사북면   27890 ----------


 ---------- 2019-07-14 14:00:00 : 동내면   27891 ----------


 ---------- 2019-07-14 15:00:00 : 효자1동   27893 ----------


 ---------- 2019-07-14 16:00:00 : 후평1동   27894 ----------


 ---------- 2019-07-14 19:00:00 : 효자1동   27895 ----------


 ---------- 2019-07-14 23:00:00 : 조운동   27896 ----------


 ---------- 2019-07-15 11:00:00 : 소양동   27898 ----------


 ---------- 2019-07-15 12:00:00 : 남산면   27899 ----------


 ---------- 2019-07-15 13:00:00 : 석사동   27901 ----------


 ---------- 2019-07-15 13:00:00 : 사북면   27902 ----------


 ---------- 2019-07-15 13:00:00 : 근화동   27903 ----------


 ---------- 2019-07-15 13:00:00 : 소양동   27904 ----------


 ---------- 2019-07-15 15:00:00 : 석사동   27905 ----------


 ---------- 2019-07-15 16:00:00 : 남산면   27906 ----------


 ---------- 2019-07-15 16:00:00 : 동  면   27907 ----------


 ---------- 2019-07-15 16:00:00 : 퇴계동   27909 ----------


 ---------- 2019-07-16 08:00:00 : 강남동   27911 ----------


 ---------- 2019-07-16 09:00:00 : 남산면   27912 ----------


 ---------- 2019-07-16 09:00:00 : 동  면   27913 ----------


 ---------- 2019-07-16 09:00:00 : 퇴계동   27914 ----------


 ---------- 2019-07-16 09:00:00 : 북산면   27915 ----------


 ---------- 2019-07-16 10:00:00 : 퇴계동   27916 ----------


 ---------- 2019-07-16 12:00:00 : 서  면   27917 ----------


 ---------- 2019-07-16 12:00:00 : 남산면   27918 ----------


 ---------- 2019-07-16 13:00:00 : 조운동   27919 ----------


 ---------- 2019-07-16 16:00:00 : 신북읍   27921 ----------


 ---------- 2019-07-16 16:00:00 : 후평1동   27922 ----------


 ---------- 2019-07-16 16:00:00 : 북산면   27923 ----------


 ---------- 2019-07-16 17:00:00 : 강남동   27924 ----------


 ---------- 2019-07-16 17:00:00 : 남산면   27925 ----------


 ---------- 2019-07-16 17:00:00 : 동  면   27926 ----------


 ---------- 2019-07-16 18:00:00 : 강남동   27928 ----------


 ---------- 2019-07-16 18:00:00 : 남  면   27929 ----------


 ---------- 2019-07-16 19:00:00 : 석사동   27930 ----------


 ---------- 2019-07-16 20:00:00 : 퇴계동   27932 ----------


 ---------- 2019-07-16 22:00:00 : 효자1동   27933 ----------


 ---------- 2019-07-16 22:00:00 : 북산면   27935 ----------


 ---------- 2019-07-17 05:00:00 : 동  면   27936 ----------


 ---------- 2019-07-17 07:00:00 : 효자1동   27937 ----------


 ---------- 2019-07-17 07:00:00 : 신북읍   27938 ----------


 ---------- 2019-07-17 09:00:00 : 동  면   27939 ----------


 ---------- 2019-07-17 10:00:00 : 신동면   27940 ----------


 ---------- 2019-07-17 10:00:00 : 사북면   27941 ----------


 ---------- 2019-07-17 12:00:00 : 동내면   27942 ----------


 ---------- 2019-07-17 12:00:00 : 남산면   27944 ----------


 ---------- 2019-07-17 13:00:00 : 사북면   27945 ----------


 ---------- 2019-07-17 13:00:00 : 동  면   27946 ----------


 ---------- 2019-07-17 14:00:00 : 남산면   27947 ----------


 ---------- 2019-07-17 15:00:00 : 남  면   27948 ----------


 ---------- 2019-07-17 16:00:00 : 신북읍   27949 ----------


 ---------- 2019-07-17 16:00:00 : 동  면   27950 ----------


 ---------- 2019-07-17 16:00:00 : 퇴계동   27951 ----------


 ---------- 2019-07-17 18:00:00 : 동  면   27952 ----------


 ---------- 2019-07-17 21:00:00 : 동  면   27954 ----------


 ---------- 2019-07-17 21:00:00 : 퇴계동   27955 ----------


 ---------- 2019-07-18 07:00:00 : 사북면   27956 ----------


 ---------- 2019-07-18 08:00:00 : 사북면   27958 ----------


 ---------- 2019-07-18 09:00:00 : 강남동   27959 ----------


 ---------- 2019-07-18 09:00:00 : 남  면   27961 ----------


 ---------- 2019-07-18 09:00:00 : 효자1동   27962 ----------


 ---------- 2019-07-18 11:00:00 : 신동면   27963 ----------


 ---------- 2019-07-18 12:00:00 : 신사우동   27964 ----------


 ---------- 2019-07-18 13:00:00 : 석사동   27965 ----------


 ---------- 2019-07-18 13:00:00 : 효자1동   27966 ----------


 ---------- 2019-07-18 13:00:00 : 신사우동   27967 ----------


 ---------- 2019-07-18 14:00:00 : 후평1동   27968 ----------


 ---------- 2019-07-18 15:00:00 : 동  면   27969 ----------


 ---------- 2019-07-18 15:00:00 : 퇴계동   27971 ----------


 ---------- 2019-07-18 23:00:00 : 후평1동   27972 ----------


 ---------- 2019-07-19 07:00:00 : 동  면   27973 ----------


 ---------- 2019-07-19 08:00:00 : 서  면   27974 ----------


 ---------- 2019-07-19 08:00:00 : 후평1동   27976 ----------


 ---------- 2019-07-19 09:00:00 : 동  면   27977 ----------


 ---------- 2019-07-19 10:00:00 : 강남동   27978 ----------


 ---------- 2019-07-19 10:00:00 : 남산면   27979 ----------


 ---------- 2019-07-19 12:00:00 : 사북면   27980 ----------


 ---------- 2019-07-19 13:00:00 : 서  면   27981 ----------


 ---------- 2019-07-19 14:00:00 : 북산면   27982 ----------


 ---------- 2019-07-19 15:00:00 : 효자1동   27983 ----------


 ---------- 2019-07-19 18:00:00 : 근화동   27984 ----------


 ---------- 2019-07-19 21:00:00 : 남산면   27985 ----------


 ---------- 2019-07-20 00:00:00 : 효자1동   27987 ----------


 ---------- 2019-07-20 06:00:00 : 서  면   27988 ----------


 ---------- 2019-07-20 07:00:00 : 동  면   27989 ----------


 ---------- 2019-07-20 10:00:00 : 강남동   27990 ----------


 ---------- 2019-07-20 10:00:00 : 서  면   27991 ----------


 ---------- 2019-07-20 10:00:00 : 동  면   27993 ----------


 ---------- 2019-07-20 11:00:00 : 강남동   27994 ----------


 ---------- 2019-07-20 12:00:00 : 남산면   27995 ----------


 ---------- 2019-07-20 12:00:00 : 신사우동   27996 ----------


 ---------- 2019-07-20 13:00:00 : 남산면   27997 ----------


 ---------- 2019-07-20 13:00:00 : 동  면   27998 ----------


 ---------- 2019-07-20 13:00:00 : 북산면   28000 ----------


 ---------- 2019-07-20 14:00:00 : 후평1동   28002 ----------


 ---------- 2019-07-20 15:00:00 : 사북면   28003 ----------


 ---------- 2019-07-20 15:00:00 : 근화동   28005 ----------


 ---------- 2019-07-20 15:00:00 : 북산면   28007 ----------


 ---------- 2019-07-20 16:00:00 : 서  면   28008 ----------


 ---------- 2019-07-20 16:00:00 : 효자1동   28009 ----------


 ---------- 2019-07-20 16:00:00 : 남산면   28010 ----------


 ---------- 2019-07-20 17:00:00 : 사북면   28011 ----------


 ---------- 2019-07-20 17:00:00 : 동  면   28012 ----------


 ---------- 2019-07-20 17:00:00 : 동산면   28014 ----------


 ---------- 2019-07-20 18:00:00 : 효자1동   28015 ----------


 ---------- 2019-07-20 18:00:00 : 후평1동   28016 ----------


 ---------- 2019-07-20 19:00:00 : 신사우동   28017 ----------


 ---------- 2019-07-20 20:00:00 : 후평1동   28018 ----------


 ---------- 2019-07-20 22:00:00 : 남산면   28019 ----------


 ---------- 2019-07-20 23:00:00 : 신사우동   28020 ----------


 ---------- 2019-07-21 01:00:00 : 남산면   28021 ----------


 ---------- 2019-07-21 01:00:00 : 퇴계동   28022 ----------


 ---------- 2019-07-21 02:00:00 : 근화동   28023 ----------


 ---------- 2019-07-21 03:00:00 : 퇴계동   28024 ----------


 ---------- 2019-07-21 08:00:00 : 신사우동   28025 ----------


 ---------- 2019-07-21 08:00:00 : 신북읍   28026 ----------


 ---------- 2019-07-21 10:00:00 : 강남동   28027 ----------


 ---------- 2019-07-21 11:00:00 : 서  면   28028 ----------


 ---------- 2019-07-21 11:00:00 : 남산면   28029 ----------


 ---------- 2019-07-21 12:00:00 : 신동면   28030 ----------


 ---------- 2019-07-21 12:00:00 : 남산면   28031 ----------


 ---------- 2019-07-21 13:00:00 : 서  면   28032 ----------


 ---------- 2019-07-21 14:00:00 : 남산면   28033 ----------


 ---------- 2019-07-21 16:00:00 : 효자1동   28034 ----------


 ---------- 2019-07-21 22:00:00 : 동내면   28036 ----------


 ---------- 2019-07-21 23:00:00 : 효자1동   28037 ----------


 ---------- 2019-07-21 23:00:00 : 후평1동   28038 ----------

 ---------- 2019-07-22 08:00:00 : 사북면   28039 ----------


 ---------- 2019-07-22 08:00:00 : 동  면   28040 ----------


 ---------- 2019-07-22 09:00:00 : 사북면   28041 ----------


 ---------- 2019-07-22 10:00:00 : 신사우동   28042 ----------


 ---------- 2019-07-22 11:00:00 : 동산면   28043 ----------


 ---------- 2019-07-22 12:00:00 : 동내면   28044 ----------


 ---------- 2019-07-22 14:00:00 : 동  면   28045 ----------


 ---------- 2019-07-22 14:00:00 : 퇴계동   28046 ----------


 ---------- 2019-07-22 15:00:00 : 남  면   28047 ----------


 ---------- 2019-07-22 15:00:00 : 사북면   28048 ----------


 ---------- 2019-07-22 15:00:00 : 후평1동   28049 ----------


 ---------- 2019-07-22 17:00:00 : 동  면   28050 ----------


 ---------- 2019-07-22 17:00:00 : 후평1동   28051 ----------


 ---------- 2019-07-22 18:00:00 : 남산면   28052 ----------


 ---------- 2019-07-22 20:00:00 : 동내면   28053 ----------


 ---------- 2019-07-22 21:00:00 : 동내면   28054 ----------


 ---------- 2019-07-23 05:00:00 : 동내면   28055 ----------


 ---------- 2019-07-23 07:00:00 : 신북읍   28056 ----------


 ---------- 2019-07-23 09:00:00 : 서  면   28057 ----------


 ---------- 2019-07-23 09:00:00 : 동  면   28058 ----------


 ---------- 2019-07-23 10:00:00 : 동  면   28059 ----------


 ---------- 2019-07-23 10:00:00 : 동산면   28061 ----------


 ---------- 2019-07-23 11:00:00 : 강남동   28062 ----------


 ---------- 2019-07-23 11:00:00 : 남  면   28063 ----------


 ---------- 2019-07-23 12:00:00 : 동내면   28064 ----------


 ---------- 2019-07-23 12:00:00 : 신사우동   28065 ----------


 ---------- 2019-07-23 14:00:00 : 사북면   28066 ----------


 ---------- 2019-07-23 15:00:00 : 석사동   28067 ----------


 ---------- 2019-07-23 15:00:00 : 효자1동   28068 ----------


 ---------- 2019-07-23 23:00:00 : 동  면   28069 ----------


 ---------- 2019-07-24 00:00:00 : 후평1동   28070 ----------


 ---------- 2019-07-24 09:00:00 : 동산면   28071 ----------


 ---------- 2019-07-24 11:00:00 : 강남동   28072 ----------


 ---------- 2019-07-24 13:00:00 : 신동면   28073 ----------


 ---------- 2019-07-24 13:00:00 : 남  면   28074 ----------


 ---------- 2019-07-24 13:00:00 : 동  면   28075 ----------


 ---------- 2019-07-24 13:00:00 : 후평1동   28076 ----------


 ---------- 2019-07-24 14:00:00 : 효자1동   28077 ----------


 ---------- 2019-07-24 15:00:00 : 약사명동   28078 ----------


 ---------- 2019-07-24 16:00:00 : 석사동   28079 ----------


 ---------- 2019-07-24 16:00:00 : 서  면   28081 ----------


 ---------- 2019-07-25 10:00:00 : 소양동   28082 ----------


 ---------- 2019-07-25 11:00:00 : 신동면   28083 ----------


 ---------- 2019-07-25 11:00:00 : 신북읍   28085 ----------


 ---------- 2019-07-25 13:00:00 : 신사우동   28086 ----------


 ---------- 2019-07-25 14:00:00 : 퇴계동   28087 ----------


 ---------- 2019-07-25 15:00:00 : 동  면   28088 ----------


 ---------- 2019-07-25 16:00:00 : 근화동   28089 ----------


 ---------- 2019-07-25 16:00:00 : 동  면   28090 ----------


 ---------- 2019-07-25 17:00:00 : 동  면   28091 ----------


 ---------- 2019-07-26 00:00:00 : 퇴계동   28092 ----------


 ---------- 2019-07-26 08:00:00 : 후평1동   28094 ----------


 ---------- 2019-07-26 08:00:00 : 퇴계동   28095 ----------


 ---------- 2019-07-26 09:00:00 : 신동면   28098 ----------


 ---------- 2019-07-26 10:00:00 : 사북면   28100 ----------


 ---------- 2019-07-26 10:00:00 : 남산면   28101 ----------


 ---------- 2019-07-26 10:00:00 : 후평1동   28102 ----------


 ---------- 2019-07-26 11:00:00 : 서  면   28104 ----------


 ---------- 2019-07-26 11:00:00 : 신사우동   28105 ----------


 ---------- 2019-07-26 12:00:00 : 신동면   28107 ----------


 ---------- 2019-07-26 13:00:00 : 석사동   28108 ----------


 ---------- 2019-07-26 14:00:00 : 강남동   28109 ----------


 ---------- 2019-07-26 14:00:00 : 신사우동   28110 ----------


 ---------- 2019-07-26 15:00:00 : 남산면   28111 ----------


 ---------- 2019-07-26 16:00:00 : 효자1동   28112 ----------


 ---------- 2019-07-26 18:00:00 : 동산면   28113 ----------


 ---------- 2019-07-26 21:00:00 : 강남동   28114 ----------


 ---------- 2019-07-27 07:00:00 : 석사동   28115 ----------


 ---------- 2019-07-27 07:00:00 : 근화동   28116 ----------


 ---------- 2019-07-27 08:00:00 : 서  면   28117 ----------


 ---------- 2019-07-27 08:00:00 : 후평1동   28118 ----------


 ---------- 2019-07-27 09:00:00 : 석사동   28119 ----------


 ---------- 2019-07-27 09:00:00 : 효자1동   28120 ----------


 ---------- 2019-07-27 09:00:00 : 동  면   28121 ----------


 ---------- 2019-07-27 10:00:00 : 후평1동   28122 ----------


 ---------- 2019-07-27 13:00:00 : 강남동   28123 ----------


 ---------- 2019-07-27 13:00:00 : 남  면   28124 ----------


 ---------- 2019-07-27 14:00:00 : 근화동   28125 ----------


 ---------- 2019-07-27 15:00:00 : 남산면   28126 ----------


 ---------- 2019-07-27 15:00:00 : 동  면   28127 ----------


 ---------- 2019-07-27 16:00:00 : 남산면   28128 ----------


 ---------- 2019-07-27 16:00:00 : 동  면   28129 ----------


 ---------- 2019-07-27 17:00:00 : 소양동   28130 ----------


 ---------- 2019-07-27 18:00:00 : 남산면   28131 ----------


 ---------- 2019-07-27 18:00:00 : 신사우동   28132 ----------


 ---------- 2019-07-27 18:00:00 : 소양동   28133 ----------


 ---------- 2019-07-27 20:00:00 : 동내면   28134 ----------


 ---------- 2019-07-28 03:00:00 : 동내면   28135 ----------


 ---------- 2019-07-28 06:00:00 : 후평1동   28136 ----------


 ---------- 2019-07-28 06:00:00 : 퇴계동   28137 ----------


 ---------- 2019-07-28 08:00:00 : 서  면   28139 ----------


 ---------- 2019-07-28 08:00:00 : 신북읍   28140 ----------


 ---------- 2019-07-28 09:00:00 : 신동면   28141 ----------


 ---------- 2019-07-28 09:00:00 : 남산면   28142 ----------


 ---------- 2019-07-28 09:00:00 : 동  면   28143 ----------


 ---------- 2019-07-28 10:00:00 : 석사동   28144 ----------


 ---------- 2019-07-28 10:00:00 : 후평1동   28145 ----------


 ---------- 2019-07-28 11:00:00 : 석사동   28146 ----------


 ---------- 2019-07-28 12:00:00 : 석사동   28147 ----------


 ---------- 2019-07-28 13:00:00 : 강남동   28148 ----------


 ---------- 2019-07-28 14:00:00 : 신동면   28149 ----------


 ---------- 2019-07-28 14:00:00 : 서  면   28150 ----------


 ---------- 2019-07-28 16:00:00 : 남산면   28151 ----------


 ---------- 2019-07-28 16:00:00 : 후평1동   28152 ----------


 ---------- 2019-07-28 16:00:00 : 교  동   28153 ----------


 ---------- 2019-07-29 07:00:00 : 동  면   28154 ----------


 ---------- 2019-07-29 08:00:00 : 근화동   28155 ----------


 ---------- 2019-07-29 08:00:00 : 신사우동   28156 ----------


 ---------- 2019-07-29 08:00:00 : 후평1동   28157 ----------


 ---------- 2019-07-29 08:00:00 : 북산면   28158 ----------


 ---------- 2019-07-29 09:00:00 : 남  면   28161 ----------


 ---------- 2019-07-29 09:00:00 : 사북면   28162 ----------


 ---------- 2019-07-29 09:00:00 : 근화동   28163 ----------


 ---------- 2019-07-29 09:00:00 : 소양동   28164 ----------


 ---------- 2019-07-29 10:00:00 : 효자1동   28165 ----------


 ---------- 2019-07-29 10:00:00 : 남산면   28166 ----------


 ---------- 2019-07-29 11:00:00 : 효자1동   28167 ----------


 ---------- 2019-07-29 12:00:00 : 석사동   28168 ----------


 ---------- 2019-07-29 12:00:00 : 남산면   28169 ----------


 ---------- 2019-07-29 13:00:00 : 석사동   28170 ----------


 ---------- 2019-07-29 13:00:00 : 신북읍   28171 ----------


 ---------- 2019-07-29 13:00:00 : 동  면   28172 ----------


 ---------- 2019-07-29 15:00:00 : 서  면   28173 ----------


 ---------- 2019-07-29 15:00:00 : 교  동   28174 ----------


 ---------- 2019-07-29 16:00:00 : 서  면   28175 ----------


 ---------- 2019-07-29 16:00:00 : 사북면   28176 ----------


 ---------- 2019-07-29 16:00:00 : 동  면   28177 ----------


 ---------- 2019-07-29 18:00:00 : 신북읍   28178 ----------


 ---------- 2019-07-29 18:00:00 : 동  면   28179 ----------


 ---------- 2019-07-29 18:00:00 : 북산면   28180 ----------


 ---------- 2019-07-29 18:00:00 : 조운동   28181 ----------


 ---------- 2019-07-29 21:00:00 : 강남동   28184 ----------


 ---------- 2019-07-30 08:00:00 : 신동면   28185 ----------


 ---------- 2019-07-30 08:00:00 : 소양동   28186 ----------


 ---------- 2019-07-30 08:00:00 : 동  면   28187 ----------


 ---------- 2019-07-30 09:00:00 : 석사동   28188 ----------


 ---------- 2019-07-30 09:00:00 : 신동면   28189 ----------


 ---------- 2019-07-30 09:00:00 : 서  면   28191 ----------

 ---------- 2019-07-30 09:00:00 : 효자1동   28192 ----------


 ---------- 2019-07-30 09:00:00 : 후평1동   28193 ----------


 ---------- 2019-07-30 10:00:00 : 동내면   28194 ----------


 ---------- 2019-07-30 10:00:00 : 남산면   28195 ----------


 ---------- 2019-07-30 11:00:00 : 후평1동   28196 ----------


 ---------- 2019-07-30 11:00:00 : 교  동   28197 ----------


 ---------- 2019-07-30 12:00:00 : 서  면   28198 ----------


 ---------- 2019-07-30 12:00:00 : 남산면   28199 ----------


 ---------- 2019-07-30 12:00:00 : 후평1동   28200 ----------


 ---------- 2019-07-30 12:00:00 : 동산면   28202 ----------


 ---------- 2019-07-30 13:00:00 : 서  면   28203 ----------


 ---------- 2019-07-30 14:00:00 : 사북면   28205 ----------


 ---------- 2019-07-30 14:00:00 : 남산면   28206 ----------


 ---------- 2019-07-30 15:00:00 : 신동면   28207 ----------


 ---------- 2019-07-30 15:00:00 : 소양동   28208 ----------


 ---------- 2019-07-30 17:00:00 : 서  면   28209 ----------


 ---------- 2019-07-30 18:00:00 : 동산면   28213 ----------


 ---------- 2019-07-30 19:00:00 : 동내면   28214 ----------


 ---------- 2019-07-30 22:00:00 : 남산면   28215 ----------


 ---------- 2019-07-31 00:00:00 : 석사동   28217 ----------


 ---------- 2019-07-31 02:00:00 : 효자1동   28219 ----------


 ---------- 2019-07-31 02:00:00 : 퇴계동   28220 ----------


 ---------- 2019-07-31 07:00:00 : 동  면   28221 ----------


 ---------- 2019-07-31 08:00:00 : 동내면   28223 ----------


 ---------- 2019-07-31 08:00:00 : 효자1동   28224 ----------


 ---------- 2019-07-31 08:00:00 : 동  면   28225 ----------


 ---------- 2019-07-31 09:00:00 : 신동면   28226 ----------


 ---------- 2019-07-31 09:00:00 : 남산면   28227 ----------


 ---------- 2019-07-31 10:00:00 : 소양동   28228 ----------


 ---------- 2019-07-31 12:00:00 : 석사동   28230 ----------


 ---------- 2019-07-31 13:00:00 : 서  면   28231 ----------


 ---------- 2019-07-31 13:00:00 : 소양동   28232 ----------


 ---------- 2019-07-31 13:00:00 : 후평1동   28233 ----------


 ---------- 2019-07-31 13:00:00 : 북산면   28234 ----------


 ---------- 2019-07-31 14:00:00 : 서  면   28235 ----------


 ---------- 2019-07-31 14:00:00 : 남  면   28236 ----------


 ---------- 2019-07-31 14:00:00 : 사북면   28237 ----------


 ---------- 2019-07-31 15:00:00 : 남산면   28240 ----------


 ---------- 2019-07-31 16:00:00 : 남산면   28242 ----------


 ---------- 2019-07-31 16:00:00 : 신북읍   28243 ----------


 ---------- 2019-07-31 17:00:00 : 효자1동   28246 ----------


 ---------- 2019-07-31 17:00:00 : 남산면   28248 ----------


 ---------- 2019-07-31 19:00:00 : 강남동   28249 ----------


 ---------- 2019-07-31 19:00:00 : 후평1동   28250 ----------


 ---------- 2019-07-31 20:00:00 : 강남동   28251 ----------


 ---------- 2019-08-01 00:00:00 : 동  면   28252 ----------


 ---------- 2019-08-01 07:00:00 : 약사명동   28253 ----------


 ---------- 2019-08-01 08:00:00 : 신북읍   28254 ----------


 ---------- 2019-08-01 09:00:00 : 동산면   28255 ----------


 ---------- 2019-08-01 10:00:00 : 근화동   28256 ----------


 ---------- 2019-08-01 10:00:00 : 후평1동   28257 ----------


 ---------- 2019-08-01 12:00:00 : 남산면   28258 ----------


 ---------- 2019-08-01 13:00:00 : 석사동   28259 ----------


 ---------- 2019-08-01 13:00:00 : 남산면   28260 ----------


 ---------- 2019-08-01 14:00:00 : 사북면   28261 ----------


 ---------- 2019-08-01 14:00:00 : 효자1동   28262 ----------


 ---------- 2019-08-01 14:00:00 : 북산면   28263 ----------


 ---------- 2019-08-01 15:00:00 : 신북읍   28264 ----------


 ---------- 2019-08-01 16:00:00 : 서  면   28265 ----------


 ---------- 2019-08-01 17:00:00 : 강남동   28267 ----------


 ---------- 2019-08-01 17:00:00 : 북산면   28268 ----------


 ---------- 2019-08-01 18:00:00 : 석사동   28269 ----------


 ---------- 2019-08-01 20:00:00 : 강남동   28270 ----------


 ---------- 2019-08-01 20:00:00 : 퇴계동   28271 ----------


 ---------- 2019-08-01 21:00:00 : 석사동   28272 ----------


 ---------- 2019-08-01 22:00:00 : 사북면   28273 ----------


 ---------- 2019-08-02 01:00:00 : 퇴계동   28274 ----------


 ---------- 2019-08-02 02:00:00 : 남  면   28276 ----------


 ---------- 2019-08-02 08:00:00 : 석사동   28277 ----------


 ---------- 2019-08-02 08:00:00 : 강남동   28278 ----------


 ---------- 2019-08-02 08:00:00 : 남산면   28279 ----------


 ---------- 2019-08-02 09:00:00 : 석사동   28280 ----------


 ---------- 2019-08-02 09:00:00 : 사북면   28281 ----------


 ---------- 2019-08-02 09:00:00 : 동  면   28282 ----------


 ---------- 2019-08-02 10:00:00 : 서  면   28283 ----------


 ---------- 2019-08-02 12:00:00 : 사북면   28284 ----------


 ---------- 2019-08-02 14:00:00 : 서  면   28285 ----------


 ---------- 2019-08-02 14:00:00 : 남산면   28286 ----------


 ---------- 2019-08-02 15:00:00 : 남산면   28287 ----------


 ---------- 2019-08-02 15:00:00 : 근화동   28290 ----------


 ---------- 2019-08-02 16:00:00 : 사북면   28291 ----------


 ---------- 2019-08-02 16:00:00 : 동내면   28292 ----------


 ---------- 2019-08-02 16:00:00 : 남산면   28293 ----------


 ---------- 2019-08-02 17:00:00 : 서  면   28294 ----------


 ---------- 2019-08-02 17:00:00 : 신북읍   28296 ----------


 ---------- 2019-08-02 18:00:00 : 퇴계동   28298 ----------


 ---------- 2019-08-02 19:00:00 : 남산면   28299 ----------


 ---------- 2019-08-02 20:00:00 : 퇴계동   28300 ----------


 ---------- 2019-08-03 00:00:00 : 퇴계동   28301 ----------


 ---------- 2019-08-03 01:00:00 : 강남동   28302 ----------


 ---------- 2019-08-03 08:00:00 : 석사동   28303 ----------


 ---------- 2019-08-03 08:00:00 : 사북면   28306 ----------


 ---------- 2019-08-03 09:00:00 : 사북면   28307 ----------


 ---------- 2019-08-03 09:00:00 : 남산면   28308 ----------


 ---------- 2019-08-03 09:00:00 : 동  면   28309 ----------


 ---------- 2019-08-03 10:00:00 : 신동면   28310 ----------


 ---------- 2019-08-03 10:00:00 : 서  면   28311 ----------


 ---------- 2019-08-03 11:00:00 : 남  면   28312 ----------


 ---------- 2019-08-03 11:00:00 : 동내면   28314 ----------


 ---------- 2019-08-03 11:00:00 : 후평1동   28315 ----------


 ---------- 2019-08-03 12:00:00 : 강남동   28316 ----------


 ---------- 2019-08-03 12:00:00 : 효자1동   28317 ----------


 ---------- 2019-08-03 12:00:00 : 후평1동   28319 ----------


 ---------- 2019-08-03 12:00:00 : 교  동   28320 ----------


 ---------- 2019-08-03 13:00:00 : 신북읍   28322 ----------


 ---------- 2019-08-03 14:00:00 : 후평1동   28323 ----------


 ---------- 2019-08-03 15:00:00 : 서  면   28326 ----------


 ---------- 2019-08-03 16:00:00 : 후평1동   28327 ----------


 ---------- 2019-08-03 17:00:00 : 동내면   28328 ----------


 ---------- 2019-08-03 17:00:00 : 효자1동   28330 ----------


 ---------- 2019-08-03 18:00:00 : 효자1동   28331 ----------


 ---------- 2019-08-03 19:00:00 : 남산면   28332 ----------


 ---------- 2019-08-04 00:00:00 : 석사동   28333 ----------


 ---------- 2019-08-04 01:00:00 : 후평1동   28334 ----------


 ---------- 2019-08-04 07:00:00 : 신사우동   28335 ----------


 ---------- 2019-08-04 07:00:00 : 동  면   28336 ----------


 ---------- 2019-08-04 08:00:00 : 동내면   28337 ----------


 ---------- 2019-08-04 11:00:00 : 신북읍   28338 ----------


 ---------- 2019-08-04 12:00:00 : 효자1동   28339 ----------


 ---------- 2019-08-04 13:00:00 : 남산면   28341 ----------


 ---------- 2019-08-04 13:00:00 : 퇴계동   28342 ----------


 ---------- 2019-08-04 16:00:00 : 강남동   28343 ----------


 ---------- 2019-08-04 16:00:00 : 소양동   28344 ----------


 ---------- 2019-08-04 23:00:00 : 강남동   28345 ----------


 ---------- 2019-08-05 08:00:00 : 교  동   28346 ----------


 ---------- 2019-08-05 09:00:00 : 동내면   28347 ----------


 ---------- 2019-08-05 09:00:00 : 신북읍   28348 ----------


 ---------- 2019-08-05 09:00:00 : 동산면   28349 ----------


 ---------- 2019-08-05 10:00:00 : 신동면   28350 ----------


 ---------- 2019-08-05 10:00:00 : 남  면   28351 ----------


 ---------- 2019-08-05 10:00:00 : 신북읍   28352 ----------


 ---------- 2019-08-05 11:00:00 : 서  면   28353 ----------


 ---------- 2019-08-05 11:00:00 : 동  면   28355 ----------


 ---------- 2019-08-05 11:00:00 : 퇴계동   28357 ----------


 ---------- 2019-08-05 11:00:00 : 교  동   28358 ----------


 ---------- 2019-08-05 12:00:00 : 서  면   28360 ----------

 ---------- 2019-08-05 12:00:00 : 퇴계동   28361 ----------


 ---------- 2019-08-05 13:00:00 : 강남동   28362 ----------


 ---------- 2019-08-05 13:00:00 : 서  면   28363 ----------


 ---------- 2019-08-05 13:00:00 : 효자1동   28365 ----------


 ---------- 2019-08-05 13:00:00 : 동  면   28366 ----------


 ---------- 2019-08-05 14:00:00 : 강남동   28367 ----------


 ---------- 2019-08-05 14:00:00 : 신북읍   28369 ----------


 ---------- 2019-08-05 14:00:00 : 소양동   28370 ----------


 ---------- 2019-08-05 14:00:00 : 동  면   28371 ----------


 ---------- 2019-08-05 15:00:00 : 신북읍   28372 ----------


 ---------- 2019-08-05 17:00:00 : 강남동   28373 ----------


 ---------- 2019-08-05 17:00:00 : 동내면   28374 ----------


 ---------- 2019-08-05 18:00:00 : 동내면   28375 ----------


 ---------- 2019-08-05 20:00:00 : 강남동   28376 ----------


 ---------- 2019-08-05 21:00:00 : 약사명동   28378 ----------


 ---------- 2019-08-05 22:00:00 : 남  면   28379 ----------


 ---------- 2019-08-05 23:00:00 : 석사동   28381 ----------


 ---------- 2019-08-06 00:00:00 : 퇴계동   28382 ----------


 ---------- 2019-08-06 06:00:00 : 동내면   28383 ----------


 ---------- 2019-08-06 08:00:00 : 서  면   28384 ----------


 ---------- 2019-08-06 08:00:00 : 동내면   28385 ----------


 ---------- 2019-08-06 08:00:00 : 효자1동   28386 ----------


 ---------- 2019-08-06 08:00:00 : 후평1동   28387 ----------


 ---------- 2019-08-06 09:00:00 : 석사동   28388 ----------


 ---------- 2019-08-06 09:00:00 : 서  면   28389 ----------


 ---------- 2019-08-06 09:00:00 : 교  동   28390 ----------


 ---------- 2019-08-06 10:00:00 : 신동면   28391 ----------


 ---------- 2019-08-06 10:00:00 : 사북면   28392 ----------


 ---------- 2019-08-06 10:00:00 : 동  면   28393 ----------


 ---------- 2019-08-06 11:00:00 : 석사동   28394 ----------


 ---------- 2019-08-06 12:00:00 : 퇴계동   28396 ----------


 ---------- 2019-08-06 13:00:00 : 남산면   28397 ----------


 ---------- 2019-08-06 13:00:00 : 후평1동   28398 ----------


 ---------- 2019-08-06 13:00:00 : 퇴계동   28399 ----------


 ---------- 2019-08-06 14:00:00 : 신북읍   28400 ----------


 ---------- 2019-08-06 15:00:00 : 석사동   28401 ----------


 ---------- 2019-08-06 15:00:00 : 신사우동   28402 ----------


 ---------- 2019-08-06 16:00:00 : 동산면   28404 ----------


 ---------- 2019-08-06 17:00:00 : 석사동   28405 ----------


 ---------- 2019-08-06 17:00:00 : 사북면   28406 ----------


 ---------- 2019-08-06 19:00:00 : 동내면   28407 ----------


 ---------- 2019-08-06 21:00:00 : 남산면   28409 ----------


 ---------- 2019-08-06 21:00:00 : 교  동   28410 ----------


 ---------- 2019-08-07 04:00:00 : 사북면   28411 ----------


 ---------- 2019-08-07 06:00:00 : 동내면   28412 ----------


 ---------- 2019-08-07 09:00:00 : 신북읍   28415 ----------


 ---------- 2019-08-07 13:00:00 : 강남동   28416 ----------


 ---------- 2019-08-07 13:00:00 : 후평1동   28417 ----------


 ---------- 2019-08-07 16:00:00 : 후평1동   28419 ----------


 ---------- 2019-08-07 17:00:00 : 교  동   28420 ----------


 ---------- 2019-08-07 18:00:00 : 후평1동   28421 ----------


 ---------- 2019-08-07 19:00:00 : 동  면   28422 ----------


 ---------- 2019-08-07 20:00:00 : 동내면   28423 ----------


 ---------- 2019-08-07 22:00:00 : 후평1동   28424 ----------


 ---------- 2019-08-08 04:00:00 : 소양동   28425 ----------


 ---------- 2019-08-08 10:00:00 : 서  면   28426 ----------


 ---------- 2019-08-08 10:00:00 : 사북면   28427 ----------


 ---------- 2019-08-08 11:00:00 : 동내면   28428 ----------


 ---------- 2019-08-08 12:00:00 : 효자1동   28430 ----------


 ---------- 2019-08-08 13:00:00 : 강남동   28431 ----------


 ---------- 2019-08-08 13:00:00 : 근화동   28432 ----------


 ---------- 2019-08-08 13:00:00 : 동  면   28433 ----------


 ---------- 2019-08-08 13:00:00 : 퇴계동   28434 ----------


 ---------- 2019-08-08 13:00:00 : 동산면   28436 ----------


 ---------- 2019-08-08 14:00:00 : 사북면   28437 ----------


 ---------- 2019-08-08 14:00:00 : 효자1동   28439 ----------


 ---------- 2019-08-08 14:00:00 : 소양동   28440 ----------


 ---------- 2019-08-08 15:00:00 : 석사동   28443 ----------


 ---------- 2019-08-08 15:00:00 : 사북면   28444 ----------


 ---------- 2019-08-08 15:00:00 : 근화동   28445 ----------


 ---------- 2019-08-08 15:00:00 : 동  면   28446 ----------


 ---------- 2019-08-08 16:00:00 : 강남동   28447 ----------


 ---------- 2019-08-08 16:00:00 : 사북면   28449 ----------


 ---------- 2019-08-08 16:00:00 : 효자1동   28450 ----------


 ---------- 2019-08-08 16:00:00 : 근화동   28451 ----------


 ---------- 2019-08-08 16:00:00 : 교  동   28452 ----------


 ---------- 2019-08-08 17:00:00 : 석사동   28453 ----------


 ---------- 2019-08-08 17:00:00 : 근화동   28454 ----------


 ---------- 2019-08-08 17:00:00 : 소양동   28455 ----------


 ---------- 2019-08-08 17:00:00 : 동  면   28456 ----------


 ---------- 2019-08-08 18:00:00 : 서  면   28457 ----------


 ---------- 2019-08-08 20:00:00 : 퇴계동   28460 ----------


 ---------- 2019-08-08 22:00:00 : 남산면   28461 ----------


 ---------- 2019-08-09 05:00:00 : 동내면   28462 ----------


 ---------- 2019-08-09 07:00:00 : 동내면   28463 ----------


 ---------- 2019-08-09 08:00:00 : 동내면   28464 ----------


 ---------- 2019-08-09 09:00:00 : 남산면   28465 ----------


 ---------- 2019-08-09 09:00:00 : 퇴계동   28466 ----------


 ---------- 2019-08-09 10:00:00 : 근화동   28467 ----------


 ---------- 2019-08-09 10:00:00 : 신북읍   28468 ----------


 ---------- 2019-08-09 10:00:00 : 소양동   28470 ----------


 ---------- 2019-08-09 10:00:00 : 동  면   28471 ----------


 ---------- 2019-08-09 11:00:00 : 동내면   28472 ----------


 ---------- 2019-08-09 11:00:00 : 남산면   28474 ----------


 ---------- 2019-08-09 11:00:00 : 소양동   28475 ----------


 ---------- 2019-08-09 12:00:00 : 사북면   28476 ----------


 ---------- 2019-08-09 12:00:00 : 동내면   28477 ----------


 ---------- 2019-08-09 12:00:00 : 남산면   28478 ----------


 ---------- 2019-08-09 12:00:00 : 후평1동   28479 ----------


 ---------- 2019-08-09 13:00:00 : 신동면   28480 ----------


 ---------- 2019-08-09 13:00:00 : 근화동   28481 ----------


 ---------- 2019-08-09 14:00:00 : 서  면   28482 ----------


 ---------- 2019-08-09 15:00:00 : 신동면   28483 ----------


 ---------- 2019-08-09 15:00:00 : 남산면   28484 ----------


 ---------- 2019-08-09 15:00:00 : 신북읍   28486 ----------


 ---------- 2019-08-09 16:00:00 : 남산면   28487 ----------


 ---------- 2019-08-09 16:00:00 : 신사우동   28488 ----------


 ---------- 2019-08-09 16:00:00 : 퇴계동   28489 ----------


 ---------- 2019-08-09 17:00:00 : 신사우동   28490 ----------


 ---------- 2019-08-09 18:00:00 : 후평1동   28491 ----------


 ---------- 2019-08-09 18:00:00 : 퇴계동   28492 ----------


 ---------- 2019-08-09 19:00:00 : 동내면   28493 ----------


 ---------- 2019-08-09 19:00:00 : 동  면   28494 ----------


 ---------- 2019-08-09 21:00:00 : 후평1동   28495 ----------


 ---------- 2019-08-09 23:00:00 : 후평1동   28496 ----------


 ---------- 2019-08-10 04:00:00 : 근화동   28498 ----------


 ---------- 2019-08-10 08:00:00 : 남산면   28499 ----------


 ---------- 2019-08-10 09:00:00 : 북산면   28500 ----------


 ---------- 2019-08-10 11:00:00 : 남  면   28501 ----------


 ---------- 2019-08-10 11:00:00 : 동내면   28502 ----------


 ---------- 2019-08-10 12:00:00 : 석사동   28503 ----------


 ---------- 2019-08-10 13:00:00 : 서  면   28504 ----------


 ---------- 2019-08-10 13:00:00 : 동  면   28505 ----------


 ---------- 2019-08-10 14:00:00 : 석사동   28506 ----------


 ---------- 2019-08-10 15:00:00 : 사북면   28507 ----------


 ---------- 2019-08-10 15:00:00 : 후평1동   28508 ----------


 ---------- 2019-08-10 15:00:00 : 동산면   28509 ----------


 ---------- 2019-08-10 16:00:00 : 남산면   28510 ----------


 ---------- 2019-08-10 17:00:00 : 서  면   28511 ----------


 ---------- 2019-08-11 09:00:00 : 석사동   28512 ----------


 ---------- 2019-08-11 09:00:00 : 남  면   28513 ----------


 ---------- 2019-08-11 09:00:00 : 동산면   28514 ----------


 ---------- 2019-08-11 10:00:00 : 신북읍   28515 ----------


 ---------- 2019-08-11 10:00:00 : 퇴계동   28517 ----------


 ---------- 2019-08-11 11:00:00 : 석사동   28518 ----------


 ---------- 2019-08-11 11:00:00 : 신북읍   28519 ----------

 ---------- 2019-08-11 12:00:00 : 소양동   28520 ----------


 ---------- 2019-08-11 13:00:00 : 석사동   28521 ----------


 ---------- 2019-08-11 13:00:00 : 신북읍   28522 ----------


 ---------- 2019-08-11 16:00:00 : 사북면   28523 ----------


 ---------- 2019-08-11 16:00:00 : 근화동   28524 ----------


 ---------- 2019-08-11 16:00:00 : 퇴계동   28526 ----------


 ---------- 2019-08-11 17:00:00 : 남산면   28527 ----------


 ---------- 2019-08-11 18:00:00 : 신동면   28528 ----------


 ---------- 2019-08-12 06:00:00 : 근화동   28529 ----------


 ---------- 2019-08-12 08:00:00 : 강남동   28531 ----------


 ---------- 2019-08-12 08:00:00 : 신사우동   28532 ----------


 ---------- 2019-08-12 09:00:00 : 강남동   28533 ----------


 ---------- 2019-08-12 10:00:00 : 남산면   28534 ----------


 ---------- 2019-08-12 10:00:00 : 조운동   28536 ----------


 ---------- 2019-08-12 11:00:00 : 남산면   28537 ----------


 ---------- 2019-08-12 14:00:00 : 효자1동   28538 ----------


 ---------- 2019-08-12 15:00:00 : 석사동   28539 ----------


 ---------- 2019-08-12 15:00:00 : 동  면   28540 ----------


 ---------- 2019-08-12 15:00:00 : 동산면   28541 ----------


 ---------- 2019-08-12 16:00:00 : 신동면   28542 ----------


 ---------- 2019-08-12 16:00:00 : 동  면   28543 ----------


 ---------- 2019-08-12 16:00:00 : 퇴계동   28545 ----------


 ---------- 2019-08-12 17:00:00 : 신동면   28546 ----------


 ---------- 2019-08-12 17:00:00 : 퇴계동   28547 ----------


 ---------- 2019-08-12 18:00:00 : 효자1동   28549 ----------


 ---------- 2019-08-12 19:00:00 : 근화동   28551 ----------


 ---------- 2019-08-12 19:00:00 : 신북읍   28552 ----------


 ---------- 2019-08-12 20:00:00 : 서  면   28554 ----------


 ---------- 2019-08-12 21:00:00 : 사북면   28555 ----------


 ---------- 2019-08-13 02:00:00 : 교  동   28556 ----------


 ---------- 2019-08-13 07:00:00 : 강남동   28557 ----------


 ---------- 2019-08-13 07:00:00 : 동내면   28558 ----------


 ---------- 2019-08-13 07:00:00 : 동산면   28559 ----------


 ---------- 2019-08-13 08:00:00 : 신동면   28560 ----------


 ---------- 2019-08-13 08:00:00 : 후평1동   28561 ----------


 ---------- 2019-08-13 09:00:00 : 신동면   28562 ----------


 ---------- 2019-08-13 10:00:00 : 신북읍   28563 ----------


 ---------- 2019-08-13 10:00:00 : 동산면   28564 ----------


 ---------- 2019-08-13 12:00:00 : 남산면   28565 ----------


 ---------- 2019-08-13 13:00:00 : 동내면   28566 ----------


 ---------- 2019-08-13 13:00:00 : 근화동   28567 ----------


 ---------- 2019-08-13 15:00:00 : 근화동   28569 ----------


 ---------- 2019-08-13 15:00:00 : 신사우동   28570 ----------


 ---------- 2019-08-13 16:00:00 : 남산면   28571 ----------


 ---------- 2019-08-13 16:00:00 : 교  동   28572 ----------


 ---------- 2019-08-13 17:00:00 : 동  면   28574 ----------


 ---------- 2019-08-13 18:00:00 : 신사우동   28576 ----------


 ---------- 2019-08-13 18:00:00 : 동  면   28577 ----------


 ---------- 2019-08-13 19:00:00 : 석사동   28578 ----------


 ---------- 2019-08-13 21:00:00 : 퇴계동   28579 ----------


 ---------- 2019-08-13 22:00:00 : 석사동   28580 ----------


 ---------- 2019-08-13 22:00:00 : 약사명동   28581 ----------


 ---------- 2019-08-13 23:00:00 : 약사명동   28582 ----------


 ---------- 2019-08-14 00:00:00 : 신북읍   28583 ----------


 ---------- 2019-08-14 02:00:00 : 퇴계동   28584 ----------


 ---------- 2019-08-14 07:00:00 : 신북읍   28585 ----------


 ---------- 2019-08-14 08:00:00 : 동  면   28587 ----------


 ---------- 2019-08-14 09:00:00 : 사북면   28588 ----------


 ---------- 2019-08-14 09:00:00 : 북산면   28589 ----------


 ---------- 2019-08-14 10:00:00 : 석사동   28590 ----------


 ---------- 2019-08-14 10:00:00 : 신동면   28592 ----------


 ---------- 2019-08-14 10:00:00 : 남산면   28594 ----------


 ---------- 2019-08-14 12:00:00 : 남  면   28595 ----------


 ---------- 2019-08-14 13:00:00 : 동  면   28596 ----------


 ---------- 2019-08-14 13:00:00 : 후평1동   28597 ----------


 ---------- 2019-08-14 14:00:00 : 강남동   28598 ----------


 ---------- 2019-08-14 14:00:00 : 동내면   28599 ----------


 ---------- 2019-08-14 14:00:00 : 신사우동   28600 ----------


 ---------- 2019-08-14 14:00:00 : 후평1동   28601 ----------


 ---------- 2019-08-14 15:00:00 : 퇴계동   28603 ----------


 ---------- 2019-08-14 16:00:00 : 신동면   28604 ----------


 ---------- 2019-08-14 18:00:00 : 신동면   28605 ----------


 ---------- 2019-08-15 00:00:00 : 석사동   28606 ----------


 ---------- 2019-08-15 03:00:00 : 퇴계동   28607 ----------


 ---------- 2019-08-15 04:00:00 : 동  면   28608 ----------


 ---------- 2019-08-15 07:00:00 : 동산면   28609 ----------


 ---------- 2019-08-15 09:00:00 : 신동면   28610 ----------


 ---------- 2019-08-15 10:00:00 : 후평1동   28611 ----------


 ---------- 2019-08-15 11:00:00 : 동내면   28612 ----------


 ---------- 2019-08-15 12:00:00 : 동내면   28613 ----------


 ---------- 2019-08-15 14:00:00 : 신동면   28616 ----------


 ---------- 2019-08-15 19:00:00 : 효자1동   28618 ----------


 ---------- 2019-08-15 20:00:00 : 효자1동   28620 ----------


 ---------- 2019-08-16 00:00:00 : 효자1동   28621 ----------


 ---------- 2019-08-16 08:00:00 : 소양동   28622 ----------


 ---------- 2019-08-16 10:00:00 : 석사동   28623 ----------


 ---------- 2019-08-16 10:00:00 : 신동면   28624 ----------


 ---------- 2019-08-16 10:00:00 : 남  면   28625 ----------


 ---------- 2019-08-16 10:00:00 : 동  면   28626 ----------


 ---------- 2019-08-16 11:00:00 : 남산면   28627 ----------


 ---------- 2019-08-16 14:00:00 : 서  면   28628 ----------


 ---------- 2019-08-16 14:00:00 : 남  면   28629 ----------


 ---------- 2019-08-16 14:00:00 : 남산면   28630 ----------


 ---------- 2019-08-16 14:00:00 : 소양동   28631 ----------


 ---------- 2019-08-16 14:00:00 : 동  면   28632 ----------


 ---------- 2019-08-16 14:00:00 : 퇴계동   28633 ----------


 ---------- 2019-08-16 15:00:00 : 후평1동   28634 ----------


 ---------- 2019-08-16 16:00:00 : 강남동   28635 ----------


 ---------- 2019-08-16 16:00:00 : 동내면   28637 ----------


 ---------- 2019-08-16 16:00:00 : 남산면   28638 ----------


 ---------- 2019-08-16 17:00:00 : 사북면   28639 ----------


 ---------- 2019-08-16 17:00:00 : 신북읍   28641 ----------


 ---------- 2019-08-16 17:00:00 : 북산면   28642 ----------


 ---------- 2019-08-16 20:00:00 : 석사동   28643 ----------


 ---------- 2019-08-16 22:00:00 : 사북면   28645 ----------


 ---------- 2019-08-17 02:00:00 : 효자1동   28646 ----------


 ---------- 2019-08-17 08:00:00 : 동  면   28647 ----------


 ---------- 2019-08-17 09:00:00 : 신동면   28648 ----------


 ---------- 2019-08-17 09:00:00 : 소양동   28649 ----------


 ---------- 2019-08-17 10:00:00 : 동내면   28650 ----------


 ---------- 2019-08-17 10:00:00 : 신북읍   28651 ----------


 ---------- 2019-08-17 10:00:00 : 후평1동   28652 ----------


 ---------- 2019-08-17 11:00:00 : 남산면   28653 ----------


 ---------- 2019-08-17 11:00:00 : 소양동   28654 ----------


 ---------- 2019-08-17 12:00:00 : 서  면   28655 ----------


 ---------- 2019-08-17 13:00:00 : 강남동   28657 ----------


 ---------- 2019-08-17 13:00:00 : 서  면   28658 ----------


 ---------- 2019-08-17 13:00:00 : 신사우동   28659 ----------


 ---------- 2019-08-17 14:00:00 : 강남동   28660 ----------


 ---------- 2019-08-17 15:00:00 : 동내면   28661 ----------


 ---------- 2019-08-17 15:00:00 : 신사우동   28663 ----------


 ---------- 2019-08-17 16:00:00 : 근화동   28666 ----------


 ---------- 2019-08-17 16:00:00 : 퇴계동   28667 ----------


 ---------- 2019-08-17 21:00:00 : 남산면   28668 ----------


 ---------- 2019-08-17 21:00:00 : 후평1동   28669 ----------


 ---------- 2019-08-18 02:00:00 : 근화동   28670 ----------


 ---------- 2019-08-18 04:00:00 : 동내면   28671 ----------


 ---------- 2019-08-18 08:00:00 : 서  면   28672 ----------


 ---------- 2019-08-18 09:00:00 : 남산면   28674 ----------


 ---------- 2019-08-18 10:00:00 : 동  면   28676 ----------


 ---------- 2019-08-18 10:00:00 : 동산면   28677 ----------


 ---------- 2019-08-18 11:00:00 : 사북면   28678 ----------


 ---------- 2019-08-18 12:00:00 : 사북면   28679 ----------


 ---------- 2019-08-18 12:00:00 : 신사우동   28680 ----------


 ---------- 2019-08-18 13:00:00 : 후평1동   28682 ----------


 ---------- 2019-08-18 14:00:00 : 남  면   28683 ----------

 ---------- 2019-08-18 15:00:00 : 강남동   28684 ----------


 ---------- 2019-08-18 15:00:00 : 동  면   28685 ----------


 ---------- 2019-08-18 16:00:00 : 신사우동   28686 ----------


 ---------- 2019-08-19 04:00:00 : 석사동   28687 ----------


 ---------- 2019-08-19 06:00:00 : 퇴계동   28688 ----------


 ---------- 2019-08-19 09:00:00 : 석사동   28689 ----------


 ---------- 2019-08-19 09:00:00 : 효자1동   28690 ----------


 ---------- 2019-08-19 09:00:00 : 남산면   28691 ----------


 ---------- 2019-08-19 09:00:00 : 신사우동   28692 ----------


 ---------- 2019-08-19 09:00:00 : 후평1동   28693 ----------


 ---------- 2019-08-19 10:00:00 : 사북면   28694 ----------


 ---------- 2019-08-19 10:00:00 : 동  면   28695 ----------


 ---------- 2019-08-19 10:00:00 : 동산면   28696 ----------


 ---------- 2019-08-19 11:00:00 : 서  면   28697 ----------


 ---------- 2019-08-19 12:00:00 : 신사우동   28698 ----------


 ---------- 2019-08-19 13:00:00 : 서  면   28699 ----------


 ---------- 2019-08-19 13:00:00 : 동내면   28700 ----------


 ---------- 2019-08-19 14:00:00 : 서  면   28702 ----------


 ---------- 2019-08-19 14:00:00 : 남  면   28704 ----------


 ---------- 2019-08-19 14:00:00 : 동내면   28705 ----------


 ---------- 2019-08-19 15:00:00 : 남  면   28706 ----------


 ---------- 2019-08-19 15:00:00 : 동내면   28707 ----------


 ---------- 2019-08-19 15:00:00 : 퇴계동   28708 ----------


 ---------- 2019-08-19 16:00:00 : 서  면   28711 ----------


 ---------- 2019-08-19 16:00:00 : 동산면   28712 ----------


 ---------- 2019-08-19 19:00:00 : 조운동   28713 ----------


 ---------- 2019-08-19 23:00:00 : 효자1동   28714 ----------


 ---------- 2019-08-19 23:00:00 : 조운동   28716 ----------


 ---------- 2019-08-20 07:00:00 : 석사동   28717 ----------


 ---------- 2019-08-20 07:00:00 : 동  면   28718 ----------


 ---------- 2019-08-20 08:00:00 : 강남동   28719 ----------


 ---------- 2019-08-20 09:00:00 : 강남동   28720 ----------


 ---------- 2019-08-20 09:00:00 : 동내면   28721 ----------


 ---------- 2019-08-20 10:00:00 : 남산면   28722 ----------


 ---------- 2019-08-20 11:00:00 : 동  면   28723 ----------


 ---------- 2019-08-20 12:00:00 : 서  면   28725 ----------


 ---------- 2019-08-20 13:00:00 : 동내면   28726 ----------


 ---------- 2019-08-20 14:00:00 : 남  면   28728 ----------


 ---------- 2019-08-20 14:00:00 : 남산면   28730 ----------


 ---------- 2019-08-20 14:00:00 : 신사우동   28732 ----------


 ---------- 2019-08-20 15:00:00 : 서  면   28733 ----------


 ---------- 2019-08-20 18:00:00 : 신사우동   28734 ----------


 ---------- 2019-08-20 19:00:00 : 동  면   28735 ----------


 ---------- 2019-08-20 21:00:00 : 후평1동   28737 ----------


 ---------- 2019-08-21 01:00:00 : 후평1동   28738 ----------


 ---------- 2019-08-21 06:00:00 : 퇴계동   28739 ----------


 ---------- 2019-08-21 07:00:00 : 효자1동   28740 ----------


 ---------- 2019-08-21 07:00:00 : 신사우동   28741 ----------


 ---------- 2019-08-21 09:00:00 : 석사동   28742 ----------


 ---------- 2019-08-21 09:00:00 : 사북면   28743 ----------


 ---------- 2019-08-21 09:00:00 : 동내면   28744 ----------


 ---------- 2019-08-21 09:00:00 : 신북읍   28745 ----------


 ---------- 2019-08-21 10:00:00 : 북산면   28747 ----------


 ---------- 2019-08-21 12:00:00 : 신사우동   28748 ----------


 ---------- 2019-08-21 12:00:00 : 동  면   28749 ----------


 ---------- 2019-08-21 13:00:00 : 서  면   28750 ----------


 ---------- 2019-08-21 13:00:00 : 동산면   28751 ----------


 ---------- 2019-08-21 14:00:00 : 석사동   28752 ----------


 ---------- 2019-08-21 14:00:00 : 서  면   28753 ----------


 ---------- 2019-08-21 14:00:00 : 신사우동   28754 ----------


 ---------- 2019-08-21 14:00:00 : 동  면   28755 ----------


 ---------- 2019-08-21 14:00:00 : 후평1동   28756 ----------


 ---------- 2019-08-21 15:00:00 : 신동면   28757 ----------


 ---------- 2019-08-21 16:00:00 : 신동면   28758 ----------


 ---------- 2019-08-21 16:00:00 : 근화동   28759 ----------


 ---------- 2019-08-21 18:00:00 : 후평1동   28760 ----------


 ---------- 2019-08-22 03:00:00 : 신사우동   28761 ----------


 ---------- 2019-08-22 05:00:00 : 동내면   28762 ----------


 ---------- 2019-08-22 07:00:00 : 동내면   28763 ----------


 ---------- 2019-08-22 08:00:00 : 신북읍   28764 ----------


 ---------- 2019-08-22 09:00:00 : 석사동   28766 ----------


 ---------- 2019-08-22 09:00:00 : 동내면   28767 ----------


 ---------- 2019-08-22 09:00:00 : 후평1동   28768 ----------


 ---------- 2019-08-22 10:00:00 : 동내면   28769 ----------


 ---------- 2019-08-22 10:00:00 : 남산면   28770 ----------


 ---------- 2019-08-22 11:00:00 : 신동면   28771 ----------


 ---------- 2019-08-22 11:00:00 : 동  면   28772 ----------


 ---------- 2019-08-22 11:00:00 : 북산면   28777 ----------


 ---------- 2019-08-22 12:00:00 : 남산면   28778 ----------


 ---------- 2019-08-22 12:00:00 : 동  면   28779 ----------


 ---------- 2019-08-22 12:00:00 : 북산면   28780 ----------


 ---------- 2019-08-22 13:00:00 : 신북읍   28781 ----------


 ---------- 2019-08-22 13:00:00 : 북산면   28782 ----------


 ---------- 2019-08-22 14:00:00 : 동내면   28783 ----------


 ---------- 2019-08-22 14:00:00 : 효자1동   28784 ----------


 ---------- 2019-08-22 15:00:00 : 후평1동   28785 ----------


 ---------- 2019-08-22 16:00:00 : 남산면   28786 ----------


 ---------- 2019-08-22 17:00:00 : 동  면   28788 ----------


 ---------- 2019-08-22 23:00:00 : 동  면   28790 ----------


 ---------- 2019-08-23 03:00:00 : 효자1동   28791 ----------


 ---------- 2019-08-23 03:00:00 : 소양동   28792 ----------


 ---------- 2019-08-23 05:00:00 : 석사동   28793 ----------


 ---------- 2019-08-23 07:00:00 : 동내면   28795 ----------


 ---------- 2019-08-23 07:00:00 : 동산면   28796 ----------


 ---------- 2019-08-23 08:00:00 : 북산면   28800 ----------


 ---------- 2019-08-23 09:00:00 : 신북읍   28801 ----------


 ---------- 2019-08-23 09:00:00 : 동산면   28802 ----------


 ---------- 2019-08-23 10:00:00 : 동내면   28803 ----------


 ---------- 2019-08-23 11:00:00 : 사북면   28804 ----------


 ---------- 2019-08-23 11:00:00 : 신사우동   28805 ----------


 ---------- 2019-08-23 12:00:00 : 강남동   28806 ----------


 ---------- 2019-08-23 12:00:00 : 신사우동   28807 ----------


 ---------- 2019-08-23 12:00:00 : 소양동   28808 ----------


 ---------- 2019-08-23 13:00:00 : 소양동   28809 ----------


 ---------- 2019-08-23 13:00:00 : 동  면   28810 ----------


 ---------- 2019-08-23 14:00:00 : 신북읍   28811 ----------


 ---------- 2019-08-23 14:00:00 : 북산면   28812 ----------


 ---------- 2019-08-23 15:00:00 : 남  면   28815 ----------


 ---------- 2019-08-23 16:00:00 : 강남동   28817 ----------


 ---------- 2019-08-23 16:00:00 : 남  면   28820 ----------


 ---------- 2019-08-23 16:00:00 : 근화동   28821 ----------


 ---------- 2019-08-23 16:00:00 : 신사우동   28822 ----------


 ---------- 2019-08-23 16:00:00 : 신북읍   28823 ----------


 ---------- 2019-08-23 17:00:00 : 퇴계동   28824 ----------


 ---------- 2019-08-23 19:00:00 : 후평1동   28825 ----------


 ---------- 2019-08-23 21:00:00 : 퇴계동   28826 ----------


 ---------- 2019-08-24 02:00:00 : 석사동   28827 ----------


 ---------- 2019-08-24 09:00:00 : 신동면   28828 ----------


 ---------- 2019-08-24 09:00:00 : 강남동   28829 ----------


 ---------- 2019-08-24 10:00:00 : 남산면   28830 ----------


 ---------- 2019-08-24 10:00:00 : 후평1동   28831 ----------


 ---------- 2019-08-24 12:00:00 : 효자1동   28832 ----------


 ---------- 2019-08-24 12:00:00 : 남산면   28833 ----------


 ---------- 2019-08-24 13:00:00 : 석사동   28835 ----------


 ---------- 2019-08-24 13:00:00 : 동  면   28837 ----------


 ---------- 2019-08-24 14:00:00 : 강남동   28838 ----------


 ---------- 2019-08-24 14:00:00 : 사북면   28839 ----------


 ---------- 2019-08-24 14:00:00 : 동내면   28840 ----------


 ---------- 2019-08-24 15:00:00 : 강남동   28841 ----------


 ---------- 2019-08-24 15:00:00 : 동  면   28842 ----------


 ---------- 2019-08-24 16:00:00 : 강남동   28843 ----------


 ---------- 2019-08-24 16:00:00 : 동  면   28846 ----------


 ---------- 2019-08-24 17:00:00 : 후평1동   28847 ----------


 ---------- 2019-08-24 18:00:00 : 효자1동   28848 ----------


 ---------- 2019-08-25 00:00:00 : 신사우동   28849 ----------


 ---------- 2019-08-25 07:00:00 : 신동면   28850 ----------

 ---------- 2019-08-25 08:00:00 : 서  면   28851 ----------


 ---------- 2019-08-25 09:00:00 : 서  면   28852 ----------


 ---------- 2019-08-25 09:00:00 : 남산면   28853 ----------


 ---------- 2019-08-25 10:00:00 : 동내면   28854 ----------


 ---------- 2019-08-25 10:00:00 : 소양동   28855 ----------


 ---------- 2019-08-25 11:00:00 : 남  면   28856 ----------


 ---------- 2019-08-25 13:00:00 : 신동면   28858 ----------


 ---------- 2019-08-25 13:00:00 : 동내면   28860 ----------


 ---------- 2019-08-25 13:00:00 : 효자1동   28861 ----------


 ---------- 2019-08-25 13:00:00 : 남산면   28862 ----------


 ---------- 2019-08-25 13:00:00 : 신북읍   28863 ----------


 ---------- 2019-08-25 13:00:00 : 후평1동   28864 ----------


 ---------- 2019-08-25 14:00:00 : 남  면   28865 ----------


 ---------- 2019-08-25 14:00:00 : 남산면   28866 ----------


 ---------- 2019-08-25 15:00:00 : 동내면   28867 ----------


 ---------- 2019-08-25 15:00:00 : 후평1동   28868 ----------


 ---------- 2019-08-25 18:00:00 : 신북읍   28869 ----------


 ---------- 2019-08-25 19:00:00 : 약사명동   28870 ----------


 ---------- 2019-08-25 20:00:00 : 효자1동   28871 ----------


 ---------- 2019-08-25 20:00:00 : 퇴계동   28872 ----------


 ---------- 2019-08-25 21:00:00 : 동내면   28873 ----------


 ---------- 2019-08-26 07:00:00 : 효자1동   28876 ----------


 ---------- 2019-08-26 07:00:00 : 소양동   28877 ----------


 ---------- 2019-08-26 08:00:00 : 서  면   28878 ----------


 ---------- 2019-08-26 08:00:00 : 남산면   28879 ----------


 ---------- 2019-08-26 08:00:00 : 동산면   28880 ----------


 ---------- 2019-08-26 09:00:00 : 석사동   28881 ----------


 ---------- 2019-08-26 09:00:00 : 효자1동   28882 ----------


 ---------- 2019-08-26 10:00:00 : 남  면   28883 ----------


 ---------- 2019-08-26 10:00:00 : 동  면   28886 ----------


 ---------- 2019-08-26 11:00:00 : 남산면   28887 ----------


 ---------- 2019-08-26 12:00:00 : 신사우동   28888 ----------


 ---------- 2019-08-26 13:00:00 : 서  면   28889 ----------


 ---------- 2019-08-26 13:00:00 : 동내면   28890 ----------


 ---------- 2019-08-26 13:00:00 : 남산면   28891 ----------


 ---------- 2019-08-26 14:00:00 : 남산면   28893 ----------


 ---------- 2019-08-26 14:00:00 : 신북읍   28894 ----------


 ---------- 2019-08-26 14:00:00 : 퇴계동   28895 ----------


 ---------- 2019-08-26 15:00:00 : 서  면   28896 ----------


 ---------- 2019-08-26 15:00:00 : 동  면   28898 ----------


 ---------- 2019-08-26 16:00:00 : 석사동   28899 ----------


 ---------- 2019-08-26 16:00:00 : 남산면   28900 ----------


 ---------- 2019-08-26 16:00:00 : 신북읍   28901 ----------


 ---------- 2019-08-26 16:00:00 : 교  동   28902 ----------


 ---------- 2019-08-26 17:00:00 : 신동면   28903 ----------


 ---------- 2019-08-26 17:00:00 : 남산면   28904 ----------


 ---------- 2019-08-26 17:00:00 : 후평1동   28905 ----------


 ---------- 2019-08-26 20:00:00 : 후평1동   28906 ----------


 ---------- 2019-08-27 01:00:00 : 퇴계동   28907 ----------


 ---------- 2019-08-27 04:00:00 : 동내면   28908 ----------


 ---------- 2019-08-27 06:00:00 : 석사동   28909 ----------


 ---------- 2019-08-27 09:00:00 : 사북면   28910 ----------


 ---------- 2019-08-27 09:00:00 : 퇴계동   28911 ----------


 ---------- 2019-08-27 10:00:00 : 동내면   28912 ----------


 ---------- 2019-08-27 10:00:00 : 근화동   28913 ----------


 ---------- 2019-08-27 10:00:00 : 북산면   28914 ----------


 ---------- 2019-08-27 11:00:00 : 후평1동   28915 ----------


 ---------- 2019-08-27 12:00:00 : 남산면   28916 ----------


 ---------- 2019-08-27 13:00:00 : 남산면   28917 ----------


 ---------- 2019-08-27 14:00:00 : 서  면   28918 ----------


 ---------- 2019-08-27 14:00:00 : 남  면   28919 ----------


 ---------- 2019-08-27 14:00:00 : 근화동   28920 ----------


 ---------- 2019-08-27 15:00:00 : 효자1동   28921 ----------


 ---------- 2019-08-27 15:00:00 : 퇴계동   28922 ----------


 ---------- 2019-08-27 15:00:00 : 동산면   28923 ----------


 ---------- 2019-08-27 16:00:00 : 신북읍   28924 ----------


 ---------- 2019-08-27 16:00:00 : 북산면   28926 ----------


 ---------- 2019-08-27 16:00:00 : 동산면   28927 ----------


 ---------- 2019-08-27 17:00:00 : 퇴계동   28928 ----------


 ---------- 2019-08-27 20:00:00 : 동내면   28929 ----------


 ---------- 2019-08-27 21:00:00 : 석사동   28930 ----------


 ---------- 2019-08-27 21:00:00 : 동산면   28932 ----------


 ---------- 2019-08-27 23:00:00 : 석사동   28933 ----------


 ---------- 2019-08-28 01:00:00 : 북산면   28934 ----------


 ---------- 2019-08-28 03:00:00 : 석사동   28936 ----------


 ---------- 2019-08-28 06:00:00 : 동산면   28937 ----------


 ---------- 2019-08-28 07:00:00 : 약사명동   28938 ----------


 ---------- 2019-08-28 08:00:00 : 서  면   28939 ----------


 ---------- 2019-08-28 09:00:00 : 석사동   28940 ----------


 ---------- 2019-08-28 09:00:00 : 강남동   28941 ----------


 ---------- 2019-08-28 10:00:00 : 효자1동   28942 ----------


 ---------- 2019-08-28 11:00:00 : 동  면   28944 ----------


 ---------- 2019-08-28 12:00:00 : 퇴계동   28946 ----------


 ---------- 2019-08-28 13:00:00 : 효자1동   28947 ----------


 ---------- 2019-08-28 14:00:00 : 남산면   28948 ----------


 ---------- 2019-08-28 15:00:00 : 강남동   28949 ----------


 ---------- 2019-08-28 15:00:00 : 남  면   28950 ----------


 ---------- 2019-08-28 16:00:00 : 동  면   28951 ----------


 ---------- 2019-08-28 18:00:00 : 서  면   28953 ----------


 ---------- 2019-08-28 19:00:00 : 후평1동   28954 ----------


 ---------- 2019-08-29 02:00:00 : 근화동   28955 ----------


 ---------- 2019-08-29 05:00:00 : 석사동   28956 ----------


 ---------- 2019-08-29 05:00:00 : 퇴계동   28960 ----------


 ---------- 2019-08-29 07:00:00 : 서  면   28961 ----------


 ---------- 2019-08-29 08:00:00 : 서  면   28962 ----------


 ---------- 2019-08-29 08:00:00 : 남산면   28963 ----------


 ---------- 2019-08-29 09:00:00 : 동산면   28964 ----------


 ---------- 2019-08-29 10:00:00 : 동  면   28965 ----------


 ---------- 2019-08-29 13:00:00 : 신북읍   28966 ----------


 ---------- 2019-08-29 13:00:00 : 동  면   28967 ----------


 ---------- 2019-08-29 14:00:00 : 신동면   28968 ----------


 ---------- 2019-08-29 15:00:00 : 동산면   28969 ----------


 ---------- 2019-08-29 18:00:00 : 석사동   28970 ----------


 ---------- 2019-08-29 23:00:00 : 퇴계동   28972 ----------


 ---------- 2019-08-30 02:00:00 : 신사우동   28973 ----------


 ---------- 2019-08-30 07:00:00 : 퇴계동   28974 ----------


 ---------- 2019-08-30 08:00:00 : 사북면   28975 ----------


 ---------- 2019-08-30 09:00:00 : 남산면   28977 ----------


 ---------- 2019-08-30 09:00:00 : 동  면   28978 ----------


 ---------- 2019-08-30 09:00:00 : 후평1동   28979 ----------


 ---------- 2019-08-30 10:00:00 : 강남동   28980 ----------


 ---------- 2019-08-30 10:00:00 : 동  면   28981 ----------


 ---------- 2019-08-30 10:00:00 : 동산면   28982 ----------


 ---------- 2019-08-30 12:00:00 : 효자1동   28983 ----------


 ---------- 2019-08-30 13:00:00 : 동산면   28984 ----------


 ---------- 2019-08-30 14:00:00 : 효자1동   28985 ----------


 ---------- 2019-08-30 15:00:00 : 강남동   28986 ----------


 ---------- 2019-08-30 15:00:00 : 신북읍   28987 ----------


 ---------- 2019-08-30 15:00:00 : 퇴계동   28988 ----------


 ---------- 2019-08-30 17:00:00 : 석사동   28989 ----------


 ---------- 2019-08-30 19:00:00 : 석사동   28990 ----------


 ---------- 2019-08-30 20:00:00 : 효자1동   28993 ----------


 ---------- 2019-08-30 23:00:00 : 동  면   28994 ----------


 ---------- 2019-08-31 01:00:00 : 동내면   28995 ----------


 ---------- 2019-08-31 05:00:00 : 효자1동   28996 ----------


 ---------- 2019-08-31 07:00:00 : 신동면   28997 ----------


 ---------- 2019-08-31 07:00:00 : 서  면   28999 ----------


 ---------- 2019-08-31 08:00:00 : 신동면   29000 ----------


 ---------- 2019-08-31 08:00:00 : 퇴계동   29003 ----------


 ---------- 2019-08-31 09:00:00 : 사북면   29004 ----------


 ---------- 2019-08-31 09:00:00 : 퇴계동   29005 ----------


 ---------- 2019-08-31 10:00:00 : 남  면   29006 ----------


 ---------- 2019-08-31 10:00:00 : 동  면   29007 ----------


 ---------- 2019-08-31 11:00:00 : 신동면   29008 ----------


 ---------- 2019-08-31 11:00:00 : 동내면   29009 ----------


 ---------- 2019-08-31 11:00:00 : 근화동   29010 ----------


 ---------- 2019-08-31 11:00:00 : 신사우동   29011 ----------

 ---------- 2019-08-31 12:00:00 : 강남동   29012 ----------


 ---------- 2019-08-31 12:00:00 : 남  면   29013 ----------


 ---------- 2019-08-31 12:00:00 : 후평1동   29014 ----------


 ---------- 2019-08-31 14:00:00 : 신사우동   29015 ----------


 ---------- 2019-08-31 15:00:00 : 동산면   29016 ----------


 ---------- 2019-08-31 16:00:00 : 신사우동   29017 ----------


 ---------- 2019-08-31 18:00:00 : 남산면   29018 ----------


 ---------- 2019-08-31 18:00:00 : 신북읍   29019 ----------


 ---------- 2019-08-31 19:00:00 : 석사동   29020 ----------


 ---------- 2019-08-31 20:00:00 : 동내면   29021 ----------


 ---------- 2019-09-01 06:00:00 : 근화동   29022 ----------


 ---------- 2019-09-01 09:00:00 : 후평1동   29023 ----------


 ---------- 2019-09-01 10:00:00 : 신동면   29024 ----------


 ---------- 2019-09-01 10:00:00 : 북산면   29025 ----------


 ---------- 2019-09-01 11:00:00 : 남산면   29028 ----------


 ---------- 2019-09-01 11:00:00 : 신북읍   29029 ----------


 ---------- 2019-09-01 12:00:00 : 남산면   29032 ----------


 ---------- 2019-09-01 13:00:00 : 신사우동   29034 ----------


 ---------- 2019-09-01 14:00:00 : 동내면   29035 ----------


 ---------- 2019-09-01 14:00:00 : 남산면   29036 ----------


 ---------- 2019-09-01 15:00:00 : 강남동   29037 ----------


 ---------- 2019-09-01 15:00:00 : 사북면   29038 ----------


 ---------- 2019-09-01 16:00:00 : 신동면   29039 ----------


 ---------- 2019-09-01 16:00:00 : 서  면   29041 ----------


 ---------- 2019-09-01 16:00:00 : 교  동   29042 ----------


 ---------- 2019-09-01 17:00:00 : 신사우동   29044 ----------


 ---------- 2019-09-01 18:00:00 : 신북읍   29045 ----------


 ---------- 2019-09-01 21:00:00 : 효자1동   29047 ----------


 ---------- 2019-09-02 04:00:00 : 강남동   29048 ----------


 ---------- 2019-09-02 06:00:00 : 신북읍   29049 ----------


 ---------- 2019-09-02 06:00:00 : 동산면   29050 ----------


 ---------- 2019-09-02 08:00:00 : 강남동   29051 ----------


 ---------- 2019-09-02 08:00:00 : 서  면   29052 ----------


 ---------- 2019-09-02 08:00:00 : 남  면   29054 ----------


 ---------- 2019-09-02 08:00:00 : 동  면   29055 ----------


 ---------- 2019-09-02 09:00:00 : 신동면   29056 ----------


 ---------- 2019-09-02 09:00:00 : 북산면   29057 ----------


 ---------- 2019-09-02 10:00:00 : 석사동   29058 ----------


 ---------- 2019-09-02 10:00:00 : 동내면   29059 ----------


 ---------- 2019-09-02 10:00:00 : 신사우동   29060 ----------


 ---------- 2019-09-02 11:00:00 : 동내면   29061 ----------


 ---------- 2019-09-02 11:00:00 : 신북읍   29062 ----------


 ---------- 2019-09-02 11:00:00 : 퇴계동   29063 ----------


 ---------- 2019-09-02 13:00:00 : 석사동   29064 ----------


 ---------- 2019-09-02 13:00:00 : 강남동   29065 ----------


 ---------- 2019-09-02 13:00:00 : 남산면   29066 ----------


 ---------- 2019-09-02 13:00:00 : 후평1동   29067 ----------


 ---------- 2019-09-02 14:00:00 : 동내면   29068 ----------


 ---------- 2019-09-02 15:00:00 : 석사동   29070 ----------


 ---------- 2019-09-02 15:00:00 : 효자1동   29071 ----------


 ---------- 2019-09-02 15:00:00 : 남산면   29072 ----------


 ---------- 2019-09-02 15:00:00 : 신북읍   29074 ----------


 ---------- 2019-09-02 15:00:00 : 동  면   29075 ----------


 ---------- 2019-09-02 16:00:00 : 석사동   29077 ----------


 ---------- 2019-09-02 16:00:00 : 서  면   29078 ----------


 ---------- 2019-09-02 16:00:00 : 남산면   29079 ----------


 ---------- 2019-09-02 17:00:00 : 신동면   29080 ----------


 ---------- 2019-09-02 17:00:00 : 퇴계동   29082 ----------


 ---------- 2019-09-02 17:00:00 : 북산면   29083 ----------


 ---------- 2019-09-02 19:00:00 : 석사동   29084 ----------


 ---------- 2019-09-02 20:00:00 : 신사우동   29086 ----------


 ---------- 2019-09-02 22:00:00 : 교  동   29087 ----------


 ---------- 2019-09-02 23:00:00 : 석사동   29088 ----------


 ---------- 2019-09-02 23:00:00 : 동  면   29090 ----------


 ---------- 2019-09-03 01:00:00 : 퇴계동   29091 ----------


 ---------- 2019-09-03 06:00:00 : 후평1동   29092 ----------


 ---------- 2019-09-03 07:00:00 : 동내면   29093 ----------


 ---------- 2019-09-03 08:00:00 : 퇴계동   29094 ----------


 ---------- 2019-09-03 08:00:00 : 북산면   29096 ----------


 ---------- 2019-09-03 09:00:00 : 남산면   29097 ----------


 ---------- 2019-09-03 10:00:00 : 동내면   29098 ----------


 ---------- 2019-09-03 10:00:00 : 근화동   29102 ----------


 ---------- 2019-09-03 11:00:00 : 서  면   29103 ----------


 ---------- 2019-09-03 11:00:00 : 남산면   29104 ----------


 ---------- 2019-09-03 11:00:00 : 동  면   29105 ----------


 ---------- 2019-09-03 12:00:00 : 서  면   29106 ----------


 ---------- 2019-09-03 13:00:00 : 남산면   29108 ----------


 ---------- 2019-09-03 13:00:00 : 퇴계동   29109 ----------


 ---------- 2019-09-03 14:00:00 : 강남동   29110 ----------


 ---------- 2019-09-03 14:00:00 : 남산면   29111 ----------


 ---------- 2019-09-03 15:00:00 : 약사명동   29112 ----------


 ---------- 2019-09-03 17:00:00 : 석사동   29113 ----------


 ---------- 2019-09-03 18:00:00 : 남산면   29115 ----------


 ---------- 2019-09-03 20:00:00 : 서  면   29116 ----------


 ---------- 2019-09-03 21:00:00 : 신동면   29117 ----------


 ---------- 2019-09-04 05:00:00 : 근화동   29119 ----------


 ---------- 2019-09-04 06:00:00 : 효자1동   29122 ----------


 ---------- 2019-09-04 07:00:00 : 소양동   29123 ----------


 ---------- 2019-09-04 11:00:00 : 신북읍   29124 ----------


 ---------- 2019-09-04 13:00:00 : 서  면   29126 ----------


 ---------- 2019-09-04 14:00:00 : 동내면   29127 ----------


 ---------- 2019-09-04 14:00:00 : 동  면   29128 ----------


 ---------- 2019-09-05 04:00:00 : 동내면   29129 ----------


 ---------- 2019-09-05 05:00:00 : 후평1동   29130 ----------


 ---------- 2019-09-05 08:00:00 : 남산면   29135 ----------


 ---------- 2019-09-05 09:00:00 : 강남동   29136 ----------


 ---------- 2019-09-05 09:00:00 : 남산면   29137 ----------


 ---------- 2019-09-05 10:00:00 : 석사동   29138 ----------


 ---------- 2019-09-05 10:00:00 : 남  면   29139 ----------


 ---------- 2019-09-05 10:00:00 : 효자1동   29140 ----------


 ---------- 2019-09-05 10:00:00 : 신북읍   29141 ----------


 ---------- 2019-09-05 11:00:00 : 동내면   29142 ----------


 ---------- 2019-09-05 12:00:00 : 동내면   29143 ----------


 ---------- 2019-09-05 12:00:00 : 남산면   29144 ----------


 ---------- 2019-09-05 12:00:00 : 후평1동   29145 ----------


 ---------- 2019-09-05 13:00:00 : 동내면   29146 ----------


 ---------- 2019-09-05 13:00:00 : 남산면   29147 ----------


 ---------- 2019-09-05 13:00:00 : 근화동   29148 ----------


 ---------- 2019-09-05 13:00:00 : 신사우동   29149 ----------


 ---------- 2019-09-05 13:00:00 : 동  면   29150 ----------


 ---------- 2019-09-05 13:00:00 : 퇴계동   29152 ----------


 ---------- 2019-09-05 14:00:00 : 신북읍   29153 ----------


 ---------- 2019-09-05 14:00:00 : 약사명동   29154 ----------


 ---------- 2019-09-05 16:00:00 : 신북읍   29155 ----------


 ---------- 2019-09-05 16:00:00 : 동산면   29157 ----------


 ---------- 2019-09-05 18:00:00 : 동  면   29158 ----------


 ---------- 2019-09-05 20:00:00 : 강남동   29159 ----------


 ---------- 2019-09-05 21:00:00 : 후평1동   29160 ----------


 ---------- 2019-09-05 23:00:00 : 동  면   29162 ----------


 ---------- 2019-09-06 01:00:00 : 후평1동   29163 ----------


 ---------- 2019-09-06 01:00:00 : 조운동   29164 ----------


 ---------- 2019-09-06 07:00:00 : 동내면   29165 ----------


 ---------- 2019-09-06 10:00:00 : 신북읍   29166 ----------


 ---------- 2019-09-06 10:00:00 : 후평1동   29167 ----------


 ---------- 2019-09-06 12:00:00 : 석사동   29168 ----------


 ---------- 2019-09-06 13:00:00 : 동내면   29170 ----------


 ---------- 2019-09-06 13:00:00 : 효자1동   29171 ----------


 ---------- 2019-09-06 14:00:00 : 동  면   29172 ----------


 ---------- 2019-09-06 15:00:00 : 강남동   29173 ----------


 ---------- 2019-09-06 15:00:00 : 퇴계동   29174 ----------


 ---------- 2019-09-06 16:00:00 : 동  면   29175 ----------


 ---------- 2019-09-06 17:00:00 : 강남동   29176 ----------


 ---------- 2019-09-06 17:00:00 : 소양동   29178 ----------


 ---------- 2019-09-06 19:00:00 : 근화동   29179 ----------


 ---------- 2019-09-06 20:00:00 : 소양동   29182 ----------


 ---------- 2019-09-07 02:00:00 : 신사우동   29183 ----------

 ---------- 2019-09-07 10:00:00 : 근화동   29184 ----------


 ---------- 2019-09-07 10:00:00 : 동산면   29186 ----------


 ---------- 2019-09-07 11:00:00 : 동산면   29187 ----------


 ---------- 2019-09-07 12:00:00 : 약사명동   29188 ----------


 ---------- 2019-09-07 12:00:00 : 후평1동   29190 ----------


 ---------- 2019-09-07 13:00:00 : 후평1동   29193 ----------


 ---------- 2019-09-07 13:00:00 : 조운동   29194 ----------


 ---------- 2019-09-07 14:00:00 : 석사동   29195 ----------


 ---------- 2019-09-07 14:00:00 : 강남동   29197 ----------


 ---------- 2019-09-07 14:00:00 : 신사우동   29198 ----------


 ---------- 2019-09-07 14:00:00 : 약사명동   29199 ----------


 ---------- 2019-09-07 14:00:00 : 퇴계동   29200 ----------


 ---------- 2019-09-07 14:00:00 : 교  동   29201 ----------


 ---------- 2019-09-07 15:00:00 : 석사동   29203 ----------


 ---------- 2019-09-07 15:00:00 : 강남동   29205 ----------


 ---------- 2019-09-07 15:00:00 : 서  면   29206 ----------


 ---------- 2019-09-07 15:00:00 : 동내면   29207 ----------


 ---------- 2019-09-07 15:00:00 : 효자1동   29209 ----------


 ---------- 2019-09-07 15:00:00 : 소양동   29210 ----------


 ---------- 2019-09-07 15:00:00 : 후평1동   29212 ----------


 ---------- 2019-09-07 15:00:00 : 북산면   29213 ----------


 ---------- 2019-09-07 16:00:00 : 동내면   29214 ----------


 ---------- 2019-09-07 16:00:00 : 효자1동   29216 ----------


 ---------- 2019-09-07 16:00:00 : 근화동   29217 ----------


 ---------- 2019-09-07 16:00:00 : 신사우동   29218 ----------


 ---------- 2019-09-07 16:00:00 : 북산면   29219 ----------


 ---------- 2019-09-07 16:00:00 : 동산면   29221 ----------


 ---------- 2019-09-07 17:00:00 : 석사동   29224 ----------


 ---------- 2019-09-07 17:00:00 : 효자1동   29227 ----------


 ---------- 2019-09-07 17:00:00 : 신사우동   29228 ----------


 ---------- 2019-09-07 17:00:00 : 소양동   29229 ----------


 ---------- 2019-09-07 17:00:00 : 약사명동   29230 ----------


 ---------- 2019-09-07 17:00:00 : 후평1동   29231 ----------


 ---------- 2019-09-07 17:00:00 : 퇴계동   29233 ----------


 ---------- 2019-09-07 17:00:00 : 조운동   29235 ----------


 ---------- 2019-09-07 17:00:00 : 교  동   29236 ----------


 ---------- 2019-09-07 18:00:00 : 강남동   29237 ----------


 ---------- 2019-09-07 18:00:00 : 효자1동   29238 ----------


 ---------- 2019-09-07 18:00:00 : 신북읍   29239 ----------


 ---------- 2019-09-07 18:00:00 : 소양동   29240 ----------


 ---------- 2019-09-07 18:00:00 : 후평1동   29243 ----------


 ---------- 2019-09-07 18:00:00 : 퇴계동   29245 ----------


 ---------- 2019-09-07 18:00:00 : 조운동   29246 ----------


 ---------- 2019-09-07 19:00:00 : 서  면   29247 ----------


 ---------- 2019-09-07 19:00:00 : 사북면   29248 ----------


 ---------- 2019-09-07 19:00:00 : 근화동   29249 ----------


 ---------- 2019-09-07 19:00:00 : 동  면   29250 ----------


 ---------- 2019-09-07 20:00:00 : 후평1동   29251 ----------


 ---------- 2019-09-07 20:00:00 : 북산면   29252 ----------


 ---------- 2019-09-08 01:00:00 : 후평1동   29255 ----------


 ---------- 2019-09-08 07:00:00 : 석사동   29256 ----------


 ---------- 2019-09-08 07:00:00 : 신동면   29257 ----------


 ---------- 2019-09-08 08:00:00 : 남산면   29259 ----------


 ---------- 2019-09-08 09:00:00 : 신동면   29260 ----------


 ---------- 2019-09-08 09:00:00 : 강남동   29261 ----------


 ---------- 2019-09-08 09:00:00 : 남  면   29262 ----------


 ---------- 2019-09-08 09:00:00 : 동내면   29263 ----------


 ---------- 2019-09-08 09:00:00 : 남산면   29265 ----------


 ---------- 2019-09-08 09:00:00 : 근화동   29266 ----------


 ---------- 2019-09-08 09:00:00 : 퇴계동   29267 ----------


 ---------- 2019-09-08 10:00:00 : 신동면   29268 ----------


 ---------- 2019-09-08 10:00:00 : 신사우동   29270 ----------


 ---------- 2019-09-08 10:00:00 : 신북읍   29271 ----------


 ---------- 2019-09-08 10:00:00 : 약사명동   29272 ----------


 ---------- 2019-09-08 10:00:00 : 조운동   29273 ----------


 ---------- 2019-09-08 11:00:00 : 석사동   29274 ----------


 ---------- 2019-09-08 11:00:00 : 강남동   29275 ----------


 ---------- 2019-09-08 11:00:00 : 신북읍   29276 ----------


 ---------- 2019-09-08 11:00:00 : 퇴계동   29277 ----------


 ---------- 2019-09-08 12:00:00 : 석사동   29278 ----------


 ---------- 2019-09-08 12:00:00 : 남산면   29280 ----------


 ---------- 2019-09-08 12:00:00 : 동산면   29281 ----------


 ---------- 2019-09-08 13:00:00 : 남산면   29283 ----------


 ---------- 2019-09-08 13:00:00 : 교  동   29284 ----------


 ---------- 2019-09-08 14:00:00 : 동  면   29286 ----------


 ---------- 2019-09-08 15:00:00 : 사북면   29287 ----------


 ---------- 2019-09-08 15:00:00 : 신북읍   29288 ----------


 ---------- 2019-09-08 15:00:00 : 동  면   29289 ----------


 ---------- 2019-09-08 16:00:00 : 서  면   29290 ----------


 ---------- 2019-09-08 16:00:00 : 효자1동   29291 ----------


 ---------- 2019-09-08 17:00:00 : 신북읍   29292 ----------


 ---------- 2019-09-08 17:00:00 : 동  면   29293 ----------


 ---------- 2019-09-08 18:00:00 : 신동면   29295 ----------


 ---------- 2019-09-08 20:00:00 : 퇴계동   29298 ----------


 ---------- 2019-09-08 21:00:00 : 교  동   29300 ----------


 ---------- 2019-09-09 02:00:00 : 동  면   29301 ----------


 ---------- 2019-09-09 02:00:00 : 조운동   29302 ----------


 ---------- 2019-09-09 05:00:00 : 효자1동   29303 ----------


 ---------- 2019-09-09 07:00:00 : 후평1동   29304 ----------


 ---------- 2019-09-09 08:00:00 : 신사우동   29305 ----------


 ---------- 2019-09-09 09:00:00 : 동내면   29306 ----------


 ---------- 2019-09-09 10:00:00 : 신동면   29307 ----------


 ---------- 2019-09-09 12:00:00 : 신동면   29308 ----------


 ---------- 2019-09-09 12:00:00 : 남산면   29309 ----------


 ---------- 2019-09-09 13:00:00 : 효자1동   29311 ----------


 ---------- 2019-09-09 14:00:00 : 동내면   29312 ----------


 ---------- 2019-09-09 14:00:00 : 북산면   29313 ----------


 ---------- 2019-09-09 15:00:00 : 신사우동   29314 ----------


 ---------- 2019-09-09 15:00:00 : 퇴계동   29315 ----------


 ---------- 2019-09-09 16:00:00 : 강남동   29316 ----------


 ---------- 2019-09-09 17:00:00 : 퇴계동   29317 ----------


 ---------- 2019-09-09 18:00:00 : 신북읍   29318 ----------


 ---------- 2019-09-10 03:00:00 : 효자1동   29319 ----------


 ---------- 2019-09-10 08:00:00 : 신북읍   29320 ----------


 ---------- 2019-09-10 09:00:00 : 남  면   29321 ----------


 ---------- 2019-09-10 09:00:00 : 동내면   29322 ----------


 ---------- 2019-09-10 09:00:00 : 효자1동   29323 ----------


 ---------- 2019-09-10 09:00:00 : 동산면   29324 ----------


 ---------- 2019-09-10 10:00:00 : 남  면   29325 ----------


 ---------- 2019-09-10 12:00:00 : 신북읍   29326 ----------


 ---------- 2019-09-10 13:00:00 : 서  면   29327 ----------


 ---------- 2019-09-10 13:00:00 : 신사우동   29328 ----------


 ---------- 2019-09-10 14:00:00 : 석사동   29329 ----------


 ---------- 2019-09-10 14:00:00 : 서  면   29330 ----------


 ---------- 2019-09-10 15:00:00 : 효자1동   29333 ----------


 ---------- 2019-09-10 15:00:00 : 신사우동   29334 ----------


 ---------- 2019-09-10 15:00:00 : 후평1동   29335 ----------


 ---------- 2019-09-10 15:00:00 : 퇴계동   29336 ----------


 ---------- 2019-09-10 16:00:00 : 동내면   29337 ----------


 ---------- 2019-09-10 16:00:00 : 근화동   29338 ----------


 ---------- 2019-09-10 16:00:00 : 후평1동   29339 ----------


 ---------- 2019-09-10 17:00:00 : 퇴계동   29341 ----------


 ---------- 2019-09-10 18:00:00 : 동산면   29342 ----------


 ---------- 2019-09-10 19:00:00 : 약사명동   29344 ----------


 ---------- 2019-09-10 22:00:00 : 근화동   29345 ----------


 ---------- 2019-09-11 05:00:00 : 사북면   29348 ----------


 ---------- 2019-09-11 06:00:00 : 신동면   29350 ----------


 ---------- 2019-09-11 06:00:00 : 신북읍   29351 ----------


 ---------- 2019-09-11 07:00:00 : 석사동   29352 ----------


 ---------- 2019-09-11 07:00:00 : 사북면   29353 ----------


 ---------- 2019-09-11 07:00:00 : 동산면   29354 ----------


 ---------- 2019-09-11 08:00:00 : 효자1동   29356 ----------


 ---------- 2019-09-11 09:00:00 : 석사동   29357 ----------


 ---------- 2019-09-11 10:00:00 : 효자1동   29358 ----------


 ---------- 2019-09-11 10:00:00 : 남산면   29359 ----------


 ---------- 2019-09-11 11:00:00 : 신사우동   29363 ----------


 ---------- 2019-09-11 11:00:00 : 신북읍   29364 ----------

 ---------- 2019-09-11 14:00:00 : 동내면   29365 ----------


 ---------- 2019-09-11 14:00:00 : 효자1동   29368 ----------


 ---------- 2019-09-11 14:00:00 : 남산면   29371 ----------


 ---------- 2019-09-11 14:00:00 : 소양동   29373 ----------


 ---------- 2019-09-11 14:00:00 : 약사명동   29374 ----------


 ---------- 2019-09-11 15:00:00 : 효자1동   29375 ----------


 ---------- 2019-09-11 15:00:00 : 남산면   29376 ----------


 ---------- 2019-09-11 17:00:00 : 동내면   29377 ----------


 ---------- 2019-09-11 17:00:00 : 근화동   29378 ----------


 ---------- 2019-09-11 17:00:00 : 북산면   29379 ----------


 ---------- 2019-09-11 18:00:00 : 신사우동   29381 ----------


 ---------- 2019-09-11 19:00:00 : 석사동   29382 ----------


 ---------- 2019-09-11 20:00:00 : 퇴계동   29383 ----------


 ---------- 2019-09-11 21:00:00 : 퇴계동   29384 ----------


 ---------- 2019-09-11 23:00:00 : 석사동   29386 ----------


 ---------- 2019-09-12 09:00:00 : 남산면   29388 ----------


 ---------- 2019-09-12 10:00:00 : 교  동   29389 ----------


 ---------- 2019-09-12 11:00:00 : 북산면   29390 ----------


 ---------- 2019-09-12 12:00:00 : 남산면   29391 ----------


 ---------- 2019-09-12 13:00:00 : 신동면   29392 ----------


 ---------- 2019-09-12 14:00:00 : 서  면   29393 ----------


 ---------- 2019-09-12 15:00:00 : 서  면   29394 ----------


 ---------- 2019-09-12 15:00:00 : 동내면   29395 ----------


 ---------- 2019-09-12 15:00:00 : 효자1동   29397 ----------


 ---------- 2019-09-12 17:00:00 : 석사동   29399 ----------


 ---------- 2019-09-12 18:00:00 : 소양동   29401 ----------


 ---------- 2019-09-12 19:00:00 : 후평1동   29402 ----------


 ---------- 2019-09-12 20:00:00 : 석사동   29403 ----------


 ---------- 2019-09-12 20:00:00 : 강남동   29404 ----------


 ---------- 2019-09-12 20:00:00 : 효자1동   29405 ----------


 ---------- 2019-09-13 01:00:00 : 효자1동   29406 ----------


 ---------- 2019-09-13 07:00:00 : 효자1동   29408 ----------


 ---------- 2019-09-13 08:00:00 : 퇴계동   29409 ----------


 ---------- 2019-09-13 09:00:00 : 퇴계동   29410 ----------


 ---------- 2019-09-13 11:00:00 : 석사동   29411 ----------


 ---------- 2019-09-13 11:00:00 : 남산면   29412 ----------


 ---------- 2019-09-13 12:00:00 : 석사동   29414 ----------


 ---------- 2019-09-13 13:00:00 : 동내면   29415 ----------


 ---------- 2019-09-13 13:00:00 : 근화동   29416 ----------


 ---------- 2019-09-13 13:00:00 : 신북읍   29417 ----------


 ---------- 2019-09-13 14:00:00 : 신동면   29418 ----------


 ---------- 2019-09-13 14:00:00 : 남산면   29419 ----------


 ---------- 2019-09-13 14:00:00 : 신북읍   29420 ----------


 ---------- 2019-09-13 14:00:00 : 소양동   29421 ----------


 ---------- 2019-09-13 17:00:00 : 석사동   29422 ----------


 ---------- 2019-09-13 17:00:00 : 조운동   29423 ----------


 ---------- 2019-09-14 09:00:00 : 서  면   29424 ----------


 ---------- 2019-09-14 09:00:00 : 효자1동   29426 ----------


 ---------- 2019-09-14 09:00:00 : 동산면   29427 ----------


 ---------- 2019-09-14 10:00:00 : 사북면   29428 ----------


 ---------- 2019-09-14 10:00:00 : 동내면   29429 ----------


 ---------- 2019-09-14 11:00:00 : 신동면   29430 ----------


 ---------- 2019-09-14 11:00:00 : 서  면   29431 ----------


 ---------- 2019-09-14 11:00:00 : 남산면   29432 ----------


 ---------- 2019-09-14 11:00:00 : 동  면   29433 ----------


 ---------- 2019-09-14 12:00:00 : 서  면   29434 ----------


 ---------- 2019-09-14 13:00:00 : 서  면   29435 ----------


 ---------- 2019-09-14 13:00:00 : 남산면   29436 ----------


 ---------- 2019-09-14 14:00:00 : 남산면   29437 ----------


 ---------- 2019-09-14 15:00:00 : 신사우동   29439 ----------


 ---------- 2019-09-14 16:00:00 : 서  면   29440 ----------


 ---------- 2019-09-14 17:00:00 : 동내면   29441 ----------


 ---------- 2019-09-14 18:00:00 : 교  동   29442 ----------


 ---------- 2019-09-14 19:00:00 : 동내면   29443 ----------


 ---------- 2019-09-15 04:00:00 : 신사우동   29444 ----------


 ---------- 2019-09-15 06:00:00 : 동내면   29445 ----------


 ---------- 2019-09-15 07:00:00 : 동내면   29446 ----------


 ---------- 2019-09-15 09:00:00 : 서  면   29447 ----------


 ---------- 2019-09-15 10:00:00 : 강남동   29448 ----------


 ---------- 2019-09-15 10:00:00 : 신북읍   29449 ----------


 ---------- 2019-09-15 11:00:00 : 신동면   29450 ----------


 ---------- 2019-09-15 11:00:00 : 남산면   29453 ----------


 ---------- 2019-09-15 11:00:00 : 퇴계동   29454 ----------


 ---------- 2019-09-15 12:00:00 : 근화동   29455 ----------


 ---------- 2019-09-15 13:00:00 : 석사동   29456 ----------


 ---------- 2019-09-15 13:00:00 : 신동면   29457 ----------


 ---------- 2019-09-15 13:00:00 : 동내면   29458 ----------


 ---------- 2019-09-15 16:00:00 : 석사동   29459 ----------


 ---------- 2019-09-15 16:00:00 : 동산면   29460 ----------


 ---------- 2019-09-15 17:00:00 : 효자1동   29461 ----------


 ---------- 2019-09-15 17:00:00 : 교  동   29462 ----------


 ---------- 2019-09-16 08:00:00 : 강남동   29463 ----------


 ---------- 2019-09-16 08:00:00 : 동  면   29464 ----------


 ---------- 2019-09-16 09:00:00 : 동산면   29465 ----------


 ---------- 2019-09-16 10:00:00 : 서  면   29466 ----------


 ---------- 2019-09-16 10:00:00 : 동내면   29467 ----------


 ---------- 2019-09-16 10:00:00 : 남산면   29468 ----------


 ---------- 2019-09-16 10:00:00 : 동  면   29469 ----------


 ---------- 2019-09-16 11:00:00 : 서  면   29470 ----------


 ---------- 2019-09-16 11:00:00 : 효자1동   29471 ----------


 ---------- 2019-09-16 12:00:00 : 동내면   29472 ----------


 ---------- 2019-09-16 13:00:00 : 석사동   29473 ----------


 ---------- 2019-09-16 13:00:00 : 신북읍   29474 ----------


 ---------- 2019-09-16 14:00:00 : 동내면   29475 ----------


 ---------- 2019-09-16 14:00:00 : 남산면   29476 ----------


 ---------- 2019-09-16 15:00:00 : 신사우동   29478 ----------


 ---------- 2019-09-16 15:00:00 : 퇴계동   29479 ----------


 ---------- 2019-09-16 16:00:00 : 석사동   29482 ----------


 ---------- 2019-09-16 16:00:00 : 남산면   29483 ----------


 ---------- 2019-09-16 17:00:00 : 석사동   29485 ----------


 ---------- 2019-09-16 17:00:00 : 서  면   29486 ----------


 ---------- 2019-09-16 20:00:00 : 후평1동   29487 ----------


 ---------- 2019-09-16 22:00:00 : 효자1동   29488 ----------


 ---------- 2019-09-17 05:00:00 : 퇴계동   29489 ----------


 ---------- 2019-09-17 06:00:00 : 동  면   29492 ----------


 ---------- 2019-09-17 07:00:00 : 동내면   29493 ----------


 ---------- 2019-09-17 08:00:00 : 소양동   29495 ----------


 ---------- 2019-09-17 10:00:00 : 사북면   29496 ----------


 ---------- 2019-09-17 10:00:00 : 동  면   29497 ----------


 ---------- 2019-09-17 12:00:00 : 동  면   29498 ----------


 ---------- 2019-09-17 13:00:00 : 서  면   29499 ----------


 ---------- 2019-09-17 13:00:00 : 남산면   29501 ----------


 ---------- 2019-09-17 13:00:00 : 북산면   29502 ----------


 ---------- 2019-09-17 14:00:00 : 동내면   29503 ----------


 ---------- 2019-09-17 14:00:00 : 동  면   29504 ----------


 ---------- 2019-09-17 15:00:00 : 남산면   29505 ----------


 ---------- 2019-09-17 15:00:00 : 동산면   29506 ----------


 ---------- 2019-09-17 16:00:00 : 남산면   29507 ----------


 ---------- 2019-09-17 17:00:00 : 서  면   29508 ----------


 ---------- 2019-09-17 17:00:00 : 동내면   29509 ----------


 ---------- 2019-09-17 17:00:00 : 효자1동   29510 ----------


 ---------- 2019-09-17 19:00:00 : 교  동   29511 ----------


 ---------- 2019-09-17 20:00:00 : 교  동   29512 ----------


 ---------- 2019-09-18 07:00:00 : 강남동   29514 ----------


 ---------- 2019-09-18 08:00:00 : 신북읍   29515 ----------


 ---------- 2019-09-18 08:00:00 : 소양동   29516 ----------


 ---------- 2019-09-18 08:00:00 : 후평1동   29517 ----------


 ---------- 2019-09-18 09:00:00 : 석사동   29519 ----------


 ---------- 2019-09-18 10:00:00 : 근화동   29520 ----------


 ---------- 2019-09-18 10:00:00 : 퇴계동   29521 ----------


 ---------- 2019-09-18 12:00:00 : 효자1동   29522 ----------


 ---------- 2019-09-18 12:00:00 : 남산면   29523 ----------


 ---------- 2019-09-18 12:00:00 : 후평1동   29524 ----------


 ---------- 2019-09-18 13:00:00 : 석사동   29525 ----------


 ---------- 2019-09-18 14:00:00 : 소양동   29526 ----------


 ---------- 2019-09-18 16:00:00 : 석사동   29527 ----------


 ---------- 2019-09-18 16:00:00 : 강남동   29528 ----------

 ---------- 2019-09-18 22:00:00 : 효자1동   29530 ----------


 ---------- 2019-09-19 00:00:00 : 퇴계동   29531 ----------


 ---------- 2019-09-19 03:00:00 : 근화동   29533 ----------


 ---------- 2019-09-19 07:00:00 : 강남동   29536 ----------


 ---------- 2019-09-19 07:00:00 : 남산면   29537 ----------


 ---------- 2019-09-19 09:00:00 : 석사동   29538 ----------


 ---------- 2019-09-19 10:00:00 : 석사동   29541 ----------


 ---------- 2019-09-19 12:00:00 : 석사동   29542 ----------


 ---------- 2019-09-19 12:00:00 : 신동면   29544 ----------


 ---------- 2019-09-19 12:00:00 : 동  면   29545 ----------


 ---------- 2019-09-19 13:00:00 : 신사우동   29547 ----------


 ---------- 2019-09-19 16:00:00 : 신동면   29548 ----------


 ---------- 2019-09-19 17:00:00 : 퇴계동   29549 ----------


 ---------- 2019-09-19 18:00:00 : 효자1동   29550 ----------


 ---------- 2019-09-19 18:00:00 : 퇴계동   29551 ----------


 ---------- 2019-09-20 08:00:00 : 신북읍   29553 ----------


 ---------- 2019-09-20 09:00:00 : 강남동   29554 ----------


 ---------- 2019-09-20 10:00:00 : 신동면   29555 ----------


 ---------- 2019-09-20 10:00:00 : 후평1동   29556 ----------


 ---------- 2019-09-20 12:00:00 : 강남동   29557 ----------


 ---------- 2019-09-20 12:00:00 : 서  면   29558 ----------


 ---------- 2019-09-20 13:00:00 : 남산면   29559 ----------


 ---------- 2019-09-20 14:00:00 : 효자1동   29561 ----------


 ---------- 2019-09-20 14:00:00 : 퇴계동   29562 ----------


 ---------- 2019-09-20 15:00:00 : 효자1동   29563 ----------


 ---------- 2019-09-20 15:00:00 : 퇴계동   29565 ----------


 ---------- 2019-09-20 17:00:00 : 남산면   29567 ----------


 ---------- 2019-09-20 18:00:00 : 동산면   29568 ----------


 ---------- 2019-09-20 19:00:00 : 소양동   29569 ----------


 ---------- 2019-09-20 22:00:00 : 동내면   29570 ----------


 ---------- 2019-09-21 00:00:00 : 효자1동   29572 ----------


 ---------- 2019-09-21 05:00:00 : 퇴계동   29573 ----------


 ---------- 2019-09-21 08:00:00 : 동산면   29575 ----------


 ---------- 2019-09-21 09:00:00 : 남산면   29576 ----------


 ---------- 2019-09-21 10:00:00 : 신동면   29577 ----------


 ---------- 2019-09-21 10:00:00 : 신사우동   29578 ----------


 ---------- 2019-09-21 11:00:00 : 신북읍   29579 ----------


 ---------- 2019-09-21 12:00:00 : 효자1동   29580 ----------


 ---------- 2019-09-21 12:00:00 : 남산면   29582 ----------


 ---------- 2019-09-21 15:00:00 : 석사동   29583 ----------


 ---------- 2019-09-21 15:00:00 : 효자1동   29584 ----------


 ---------- 2019-09-21 18:00:00 : 동내면   29586 ----------


 ---------- 2019-09-22 10:00:00 : 조운동   29588 ----------


 ---------- 2019-09-22 12:00:00 : 후평1동   29589 ----------


 ---------- 2019-09-22 17:00:00 : 후평1동   29590 ----------


 ---------- 2019-09-22 22:00:00 : 후평1동   29592 ----------


 ---------- 2019-09-22 23:00:00 : 신동면   29593 ----------


 ---------- 2019-09-23 06:00:00 : 퇴계동   29595 ----------


 ---------- 2019-09-23 07:00:00 : 신사우동   29596 ----------


 ---------- 2019-09-23 08:00:00 : 동내면   29597 ----------


 ---------- 2019-09-23 09:00:00 : 남산면   29598 ----------


 ---------- 2019-09-23 10:00:00 : 남산면   29599 ----------


 ---------- 2019-09-23 10:00:00 : 신사우동   29601 ----------


 ---------- 2019-09-23 10:00:00 : 신북읍   29602 ----------


 ---------- 2019-09-23 11:00:00 : 효자1동   29604 ----------


 ---------- 2019-09-23 11:00:00 : 동  면   29606 ----------


 ---------- 2019-09-23 12:00:00 : 강남동   29607 ----------


 ---------- 2019-09-23 13:00:00 : 서  면   29608 ----------


 ---------- 2019-09-23 15:00:00 : 석사동   29609 ----------


 ---------- 2019-09-23 15:00:00 : 퇴계동   29610 ----------


 ---------- 2019-09-23 16:00:00 : 퇴계동   29611 ----------


 ---------- 2019-09-23 22:00:00 : 근화동   29612 ----------


 ---------- 2019-09-23 23:00:00 : 약사명동   29613 ----------


 ---------- 2019-09-23 23:00:00 : 후평1동   29615 ----------


 ---------- 2019-09-24 09:00:00 : 소양동   29616 ----------


 ---------- 2019-09-24 11:00:00 : 서  면   29617 ----------


 ---------- 2019-09-24 12:00:00 : 신사우동   29618 ----------


 ---------- 2019-09-24 13:00:00 : 후평1동   29619 ----------


 ---------- 2019-09-24 14:00:00 : 신동면   29620 ----------


 ---------- 2019-09-24 14:00:00 : 서  면   29621 ----------


 ---------- 2019-09-24 14:00:00 : 신북읍   29622 ----------


 ---------- 2019-09-24 15:00:00 : 서  면   29623 ----------


 ---------- 2019-09-25 03:00:00 : 퇴계동   29624 ----------


 ---------- 2019-09-25 09:00:00 : 신사우동   29625 ----------


 ---------- 2019-09-25 09:00:00 : 소양동   29626 ----------


 ---------- 2019-09-25 10:00:00 : 강남동   29627 ----------


 ---------- 2019-09-25 11:00:00 : 사북면   29628 ----------


 ---------- 2019-09-25 11:00:00 : 후평1동   29629 ----------


 ---------- 2019-09-25 12:00:00 : 신북읍   29630 ----------


 ---------- 2019-09-25 15:00:00 : 후평1동   29632 ----------


 ---------- 2019-09-25 16:00:00 : 석사동   29633 ----------


 ---------- 2019-09-25 16:00:00 : 신사우동   29634 ----------


 ---------- 2019-09-25 19:00:00 : 동  면   29637 ----------


 ---------- 2019-09-25 20:00:00 : 후평1동   29638 ----------


 ---------- 2019-09-25 23:00:00 : 후평1동   29639 ----------


 ---------- 2019-09-26 01:00:00 : 근화동   29641 ----------


 ---------- 2019-09-26 09:00:00 : 신동면   29642 ----------


 ---------- 2019-09-26 13:00:00 : 근화동   29643 ----------


 ---------- 2019-09-26 13:00:00 : 신사우동   29644 ----------


 ---------- 2019-09-26 13:00:00 : 후평1동   29645 ----------


 ---------- 2019-09-26 14:00:00 : 동  면   29646 ----------


 ---------- 2019-09-26 14:00:00 : 교  동   29647 ----------


 ---------- 2019-09-26 15:00:00 : 강남동   29648 ----------


 ---------- 2019-09-26 15:00:00 : 서  면   29649 ----------


 ---------- 2019-09-26 15:00:00 : 북산면   29650 ----------


 ---------- 2019-09-26 23:00:00 : 석사동   29651 ----------


 ---------- 2019-09-27 03:00:00 : 약사명동   29652 ----------


 ---------- 2019-09-27 07:00:00 : 남산면   29656 ----------


 ---------- 2019-09-27 08:00:00 : 퇴계동   29658 ----------


 ---------- 2019-09-27 09:00:00 : 퇴계동   29659 ----------


 ---------- 2019-09-27 12:00:00 : 퇴계동   29660 ----------


 ---------- 2019-09-27 13:00:00 : 남산면   29661 ----------


 ---------- 2019-09-27 13:00:00 : 교  동   29662 ----------


 ---------- 2019-09-27 14:00:00 : 근화동   29663 ----------


 ---------- 2019-09-27 15:00:00 : 북산면   29664 ----------


 ---------- 2019-09-27 16:00:00 : 강남동   29665 ----------


 ---------- 2019-09-28 00:00:00 : 후평1동   29666 ----------


 ---------- 2019-09-28 01:00:00 : 퇴계동   29668 ----------


 ---------- 2019-09-28 10:00:00 : 신사우동   29669 ----------


 ---------- 2019-09-28 10:00:00 : 동산면   29674 ----------


 ---------- 2019-09-28 11:00:00 : 서  면   29675 ----------


 ---------- 2019-09-28 11:00:00 : 사북면   29676 ----------


 ---------- 2019-09-28 11:00:00 : 효자1동   29677 ----------


 ---------- 2019-09-28 13:00:00 : 서  면   29678 ----------


 ---------- 2019-09-28 13:00:00 : 사북면   29679 ----------


 ---------- 2019-09-28 13:00:00 : 효자1동   29680 ----------


 ---------- 2019-09-28 13:00:00 : 동산면   29681 ----------


 ---------- 2019-09-28 14:00:00 : 동내면   29682 ----------


 ---------- 2019-09-28 15:00:00 : 강남동   29683 ----------


 ---------- 2019-09-28 15:00:00 : 소양동   29684 ----------


 ---------- 2019-09-28 16:00:00 : 근화동   29685 ----------


 ---------- 2019-09-28 19:00:00 : 동산면   29686 ----------


 ---------- 2019-09-28 21:00:00 : 강남동   29689 ----------


 ---------- 2019-09-29 03:00:00 : 효자1동   29691 ----------


 ---------- 2019-09-29 06:00:00 : 근화동   29692 ----------


 ---------- 2019-09-29 10:00:00 : 사북면   29693 ----------


 ---------- 2019-09-29 11:00:00 : 남산면   29694 ----------


 ---------- 2019-09-29 12:00:00 : 사북면   29695 ----------


 ---------- 2019-09-29 14:00:00 : 서  면   29698 ----------


 ---------- 2019-09-30 00:00:00 : 퇴계동   29699 ----------


 ---------- 2019-09-30 08:00:00 : 동  면   29700 ----------


 ---------- 2019-09-30 13:00:00 : 동내면   29701 ----------


 ---------- 2019-09-30 13:00:00 : 퇴계동   29702 ----------


 ---------- 2019-09-30 14:00:00 : 신북읍   29703 ----------


 ---------- 2019-09-30 15:00:00 : 동내면   29704 ----------


 ---------- 2019-09-30 16:00:00 : 석사동   29708 ----------

 ---------- 2019-09-30 16:00:00 : 신사우동   29709 ----------


 ---------- 2019-09-30 17:00:00 : 석사동   29710 ----------


 ---------- 2019-09-30 17:00:00 : 효자1동   29712 ----------


 ---------- 2019-09-30 17:00:00 : 퇴계동   29713 ----------


 ---------- 2019-09-30 18:00:00 : 근화동   29714 ----------


 ---------- 2019-09-30 21:00:00 : 근화동   29715 ----------


 ---------- 2019-10-01 00:00:00 : 효자1동   29716 ----------


 ---------- 2019-10-01 03:00:00 : 조운동   29718 ----------


 ---------- 2019-10-01 07:00:00 : 신사우동   29720 ----------


 ---------- 2019-10-01 08:00:00 : 남산면   29721 ----------


 ---------- 2019-10-01 09:00:00 : 석사동   29722 ----------


 ---------- 2019-10-01 10:00:00 : 강남동   29724 ----------


 ---------- 2019-10-01 10:00:00 : 퇴계동   29725 ----------


 ---------- 2019-10-01 11:00:00 : 남산면   29727 ----------


 ---------- 2019-10-01 12:00:00 : 서  면   29728 ----------


 ---------- 2019-10-01 13:00:00 : 신사우동   29729 ----------


 ---------- 2019-10-01 14:00:00 : 신사우동   29731 ----------


 ---------- 2019-10-01 15:00:00 : 동  면   29732 ----------


 ---------- 2019-10-01 20:00:00 : 석사동   29733 ----------


 ---------- 2019-10-01 20:00:00 : 동내면   29734 ----------


 ---------- 2019-10-01 21:00:00 : 석사동   29735 ----------


 ---------- 2019-10-01 21:00:00 : 동  면   29737 ----------


 ---------- 2019-10-02 00:00:00 : 효자1동   29738 ----------


 ---------- 2019-10-02 00:00:00 : 소양동   29739 ----------


 ---------- 2019-10-02 08:00:00 : 남  면   29740 ----------


 ---------- 2019-10-02 08:00:00 : 동내면   29741 ----------


 ---------- 2019-10-02 08:00:00 : 퇴계동   29742 ----------


 ---------- 2019-10-02 09:00:00 : 효자1동   29744 ----------


 ---------- 2019-10-02 11:00:00 : 신동면   29745 ----------


 ---------- 2019-10-02 13:00:00 : 신북읍   29748 ----------


 ---------- 2019-10-03 06:00:00 : 신북읍   29749 ----------


 ---------- 2019-10-03 12:00:00 : 신사우동   29750 ----------


 ---------- 2019-10-03 13:00:00 : 강남동   29751 ----------


 ---------- 2019-10-03 13:00:00 : 서  면   29752 ----------


 ---------- 2019-10-03 13:00:00 : 조운동   29754 ----------


 ---------- 2019-10-03 15:00:00 : 동내면   29755 ----------


 ---------- 2019-10-04 03:00:00 : 후평1동   29756 ----------


 ---------- 2019-10-04 09:00:00 : 약사명동   29757 ----------


 ---------- 2019-10-04 10:00:00 : 남  면   29759 ----------


 ---------- 2019-10-04 10:00:00 : 남산면   29760 ----------


 ---------- 2019-10-04 10:00:00 : 퇴계동   29761 ----------


 ---------- 2019-10-04 13:00:00 : 서  면   29762 ----------


 ---------- 2019-10-04 14:00:00 : 서  면   29763 ----------


 ---------- 2019-10-04 15:00:00 : 서  면   29764 ----------


 ---------- 2019-10-04 15:00:00 : 퇴계동   29765 ----------


 ---------- 2019-10-04 19:00:00 : 퇴계동   29766 ----------


 ---------- 2019-10-04 21:00:00 : 강남동   29767 ----------


 ---------- 2019-10-04 22:00:00 : 석사동   29769 ----------


 ---------- 2019-10-05 05:00:00 : 후평1동   29770 ----------


 ---------- 2019-10-05 06:00:00 : 동내면   29772 ----------


 ---------- 2019-10-05 07:00:00 : 신동면   29775 ----------


 ---------- 2019-10-05 09:00:00 : 신동면   29776 ----------


 ---------- 2019-10-05 11:00:00 : 강남동   29777 ----------


 ---------- 2019-10-05 13:00:00 : 동내면   29778 ----------


 ---------- 2019-10-05 13:00:00 : 신사우동   29779 ----------


 ---------- 2019-10-05 14:00:00 : 동내면   29780 ----------


 ---------- 2019-10-05 14:00:00 : 동  면   29782 ----------


 ---------- 2019-10-05 17:00:00 : 동내면   29783 ----------


 ---------- 2019-10-06 04:00:00 : 퇴계동   29785 ----------


 ---------- 2019-10-06 07:00:00 : 후평1동   29787 ----------


 ---------- 2019-10-06 14:00:00 : 강남동   29789 ----------


 ---------- 2019-10-06 14:00:00 : 동  면   29791 ----------


 ---------- 2019-10-06 14:00:00 : 동산면   29795 ----------


 ---------- 2019-10-06 15:00:00 : 신사우동   29796 ----------


 ---------- 2019-10-07 00:00:00 : 강남동   29797 ----------


 ---------- 2019-10-07 06:00:00 : 서  면   29798 ----------


 ---------- 2019-10-07 08:00:00 : 동산면   29799 ----------


 ---------- 2019-10-07 10:00:00 : 동내면   29800 ----------


 ---------- 2019-10-07 10:00:00 : 교  동   29802 ----------


 ---------- 2019-10-07 15:00:00 : 신동면   29806 ----------


 ---------- 2019-10-07 16:00:00 : 동  면   29807 ----------


 ---------- 2019-10-07 18:00:00 : 석사동   29808 ----------


 ---------- 2019-10-07 18:00:00 : 소양동   29809 ----------


 ---------- 2019-10-07 20:00:00 : 동내면   29811 ----------


 ---------- 2019-10-08 08:00:00 : 효자1동   29812 ----------


 ---------- 2019-10-08 12:00:00 : 동내면   29813 ----------


 ---------- 2019-10-08 13:00:00 : 강남동   29814 ----------


 ---------- 2019-10-08 14:00:00 : 석사동   29815 ----------


 ---------- 2019-10-08 21:00:00 : 퇴계동   29816 ----------


 ---------- 2019-10-09 08:00:00 : 남산면   29817 ----------


 ---------- 2019-10-09 10:00:00 : 남  면   29818 ----------


 ---------- 2019-10-09 14:00:00 : 동내면   29819 ----------


 ---------- 2019-10-09 15:00:00 : 후평1동   29820 ----------


 ---------- 2019-10-09 19:00:00 : 동산면   29821 ----------


 ---------- 2019-10-10 01:00:00 : 소양동   29823 ----------


 ---------- 2019-10-10 09:00:00 : 강남동   29824 ----------


 ---------- 2019-10-10 09:00:00 : 서  면   29825 ----------


 ---------- 2019-10-10 09:00:00 : 효자1동   29826 ----------


 ---------- 2019-10-10 09:00:00 : 교  동   29827 ----------


 ---------- 2019-10-10 13:00:00 : 효자1동   29828 ----------


 ---------- 2019-10-10 13:00:00 : 퇴계동   29829 ----------


 ---------- 2019-10-10 16:00:00 : 석사동   29830 ----------


 ---------- 2019-10-10 17:00:00 : 석사동   29831 ----------


 ---------- 2019-10-10 18:00:00 : 동내면   29832 ----------


 ---------- 2019-10-10 19:00:00 : 후평1동   29833 ----------


 ---------- 2019-10-10 21:00:00 : 효자1동   29834 ----------


 ---------- 2019-10-10 22:00:00 : 후평1동   29835 ----------


 ---------- 2019-10-11 02:00:00 : 약사명동   29837 ----------


 ---------- 2019-10-11 06:00:00 : 동내면   29838 ----------


 ---------- 2019-10-11 10:00:00 : 서  면   29839 ----------


 ---------- 2019-10-11 12:00:00 : 서  면   29841 ----------


 ---------- 2019-10-11 12:00:00 : 사북면   29842 ----------


 ---------- 2019-10-11 12:00:00 : 동내면   29843 ----------


 ---------- 2019-10-11 12:00:00 : 남산면   29844 ----------


 ---------- 2019-10-11 13:00:00 : 서  면   29845 ----------


 ---------- 2019-10-11 13:00:00 : 남산면   29847 ----------


 ---------- 2019-10-11 13:00:00 : 신사우동   29848 ----------


 ---------- 2019-10-11 13:00:00 : 신북읍   29849 ----------


 ---------- 2019-10-11 13:00:00 : 동  면   29851 ----------


 ---------- 2019-10-11 14:00:00 : 서  면   29852 ----------


 ---------- 2019-10-11 14:00:00 : 남산면   29853 ----------


 ---------- 2019-10-11 14:00:00 : 신사우동   29854 ----------


 ---------- 2019-10-11 14:00:00 : 북산면   29855 ----------


 ---------- 2019-10-11 16:00:00 : 강남동   29856 ----------


 ---------- 2019-10-11 16:00:00 : 남산면   29857 ----------


 ---------- 2019-10-11 16:00:00 : 동  면   29858 ----------


 ---------- 2019-10-11 18:00:00 : 후평1동   29860 ----------


 ---------- 2019-10-11 22:00:00 : 동내면   29861 ----------


 ---------- 2019-10-12 01:00:00 : 동  면   29864 ----------


 ---------- 2019-10-12 05:00:00 : 근화동   29866 ----------


 ---------- 2019-10-12 05:00:00 : 퇴계동   29867 ----------


 ---------- 2019-10-12 10:00:00 : 신사우동   29868 ----------


 ---------- 2019-10-12 15:00:00 : 사북면   29869 ----------


 ---------- 2019-10-12 15:00:00 : 효자1동   29870 ----------


 ---------- 2019-10-12 23:00:00 : 동내면   29871 ----------


 ---------- 2019-10-12 23:00:00 : 근화동   29874 ----------


 ---------- 2019-10-12 23:00:00 : 후평1동   29875 ----------


 ---------- 2019-10-13 12:00:00 : 사북면   29876 ----------


 ---------- 2019-10-13 13:00:00 : 남산면   29877 ----------


 ---------- 2019-10-13 16:00:00 : 강남동   29879 ----------


 ---------- 2019-10-13 17:00:00 : 동  면   29880 ----------


 ---------- 2019-10-13 18:00:00 : 소양동   29881 ----------


 ---------- 2019-10-13 19:00:00 : 강남동   29882 ----------


 ---------- 2019-10-14 09:00:00 : 신북읍   29883 ----------


 ---------- 2019-10-14 13:00:00 : 석사동   29884 ----------


 ---------- 2019-10-14 13:00:00 : 동내면   29885 ----------

 ---------- 2019-10-14 14:00:00 : 강남동   29886 ----------


 ---------- 2019-10-14 14:00:00 : 남산면   29887 ----------


 ---------- 2019-10-14 15:00:00 : 석사동   29888 ----------


 ---------- 2019-10-14 21:00:00 : 동  면   29889 ----------


 ---------- 2019-10-15 01:00:00 : 석사동   29891 ----------


 ---------- 2019-10-15 01:00:00 : 교  동   29893 ----------


 ---------- 2019-10-15 10:00:00 : 사북면   29895 ----------


 ---------- 2019-10-15 15:00:00 : 남  면   29896 ----------


 ---------- 2019-10-15 15:00:00 : 사북면   29897 ----------


 ---------- 2019-10-15 16:00:00 : 퇴계동   29898 ----------


 ---------- 2019-10-15 17:00:00 : 석사동   29899 ----------


 ---------- 2019-10-15 17:00:00 : 신사우동   29900 ----------


 ---------- 2019-10-15 18:00:00 : 석사동   29901 ----------


 ---------- 2019-10-16 09:00:00 : 서  면   29902 ----------


 ---------- 2019-10-16 11:00:00 : 강남동   29903 ----------


 ---------- 2019-10-16 11:00:00 : 서  면   29904 ----------


 ---------- 2019-10-16 12:00:00 : 후평1동   29905 ----------


 ---------- 2019-10-16 15:00:00 : 후평1동   29906 ----------


 ---------- 2019-10-16 18:00:00 : 동산면   29907 ----------


 ---------- 2019-10-16 19:00:00 : 효자1동   29908 ----------


 ---------- 2019-10-16 21:00:00 : 석사동   29910 ----------


 ---------- 2019-10-17 02:00:00 : 신사우동   29911 ----------


 ---------- 2019-10-17 03:00:00 : 근화동   29912 ----------


 ---------- 2019-10-17 11:00:00 : 효자1동   29913 ----------


 ---------- 2019-10-17 13:00:00 : 서  면   29915 ----------


 ---------- 2019-10-17 13:00:00 : 남산면   29916 ----------


 ---------- 2019-10-17 14:00:00 : 동  면   29917 ----------


 ---------- 2019-10-17 18:00:00 : 신동면   29920 ----------


 ---------- 2019-10-17 21:00:00 : 근화동   29921 ----------


 ---------- 2019-10-17 21:00:00 : 신사우동   29922 ----------


 ---------- 2019-10-17 21:00:00 : 조운동   29923 ----------


 ---------- 2019-10-17 22:00:00 : 강남동   29924 ----------


 ---------- 2019-10-18 10:00:00 : 남산면   29925 ----------


 ---------- 2019-10-18 12:00:00 : 강남동   29926 ----------


 ---------- 2019-10-18 12:00:00 : 남산면   29927 ----------


 ---------- 2019-10-18 13:00:00 : 서  면   29928 ----------


 ---------- 2019-10-18 14:00:00 : 강남동   29929 ----------


 ---------- 2019-10-18 14:00:00 : 서  면   29930 ----------


 ---------- 2019-10-18 14:00:00 : 동내면   29931 ----------


 ---------- 2019-10-18 14:00:00 : 소양동   29932 ----------


 ---------- 2019-10-19 09:00:00 : 동산면   29933 ----------


 ---------- 2019-10-19 10:00:00 : 신동면   29935 ----------


 ---------- 2019-10-19 11:00:00 : 강남동   29938 ----------


 ---------- 2019-10-19 11:00:00 : 남산면   29940 ----------


 ---------- 2019-10-19 12:00:00 : 동내면   29941 ----------


 ---------- 2019-10-19 12:00:00 : 남산면   29942 ----------


 ---------- 2019-10-19 12:00:00 : 근화동   29943 ----------


 ---------- 2019-10-19 13:00:00 : 강남동   29945 ----------


 ---------- 2019-10-19 13:00:00 : 서  면   29946 ----------


 ---------- 2019-10-19 13:00:00 : 남  면   29947 ----------


 ---------- 2019-10-19 13:00:00 : 동내면   29949 ----------


 ---------- 2019-10-19 14:00:00 : 강남동   29950 ----------


 ---------- 2019-10-19 14:00:00 : 서  면   29951 ----------


 ---------- 2019-10-19 16:00:00 : 석사동   29954 ----------


 ---------- 2019-10-19 18:00:00 : 신동면   29955 ----------


 ---------- 2019-10-19 21:00:00 : 남산면   29956 ----------


 ---------- 2019-10-20 09:00:00 : 남  면   29957 ----------


 ---------- 2019-10-20 13:00:00 : 서  면   29958 ----------


 ---------- 2019-10-20 13:00:00 : 남산면   29959 ----------


 ---------- 2019-10-20 13:00:00 : 신북읍   29960 ----------


 ---------- 2019-10-20 16:00:00 : 후평1동   29961 ----------


 ---------- 2019-10-20 17:00:00 : 남  면   29964 ----------


 ---------- 2019-10-20 17:00:00 : 후평1동   29965 ----------


 ---------- 2019-10-21 07:00:00 : 동  면   29967 ----------


 ---------- 2019-10-21 10:00:00 : 서  면   29968 ----------


 ---------- 2019-10-21 10:00:00 : 동산면   29969 ----------


 ---------- 2019-10-21 12:00:00 : 신동면   29970 ----------


 ---------- 2019-10-21 12:00:00 : 동내면   29971 ----------


 ---------- 2019-10-21 13:00:00 : 강남동   29972 ----------


 ---------- 2019-10-21 13:00:00 : 남산면   29973 ----------


 ---------- 2019-10-21 13:00:00 : 동  면   29974 ----------


 ---------- 2019-10-21 14:00:00 : 남산면   29975 ----------


 ---------- 2019-10-21 15:00:00 : 남  면   29977 ----------


 ---------- 2019-10-21 21:00:00 : 석사동   29978 ----------


 ---------- 2019-10-22 00:00:00 : 신북읍   29979 ----------


 ---------- 2019-10-22 08:00:00 : 퇴계동   29980 ----------


 ---------- 2019-10-22 09:00:00 : 동  면   29981 ----------


 ---------- 2019-10-22 11:00:00 : 남산면   29982 ----------


 ---------- 2019-10-22 13:00:00 : 신사우동   29983 ----------


 ---------- 2019-10-22 13:00:00 : 동산면   29984 ----------


 ---------- 2019-10-22 14:00:00 : 석사동   29985 ----------


 ---------- 2019-10-22 14:00:00 : 강남동   29986 ----------


 ---------- 2019-10-22 15:00:00 : 남산면   29987 ----------


 ---------- 2019-10-22 17:00:00 : 강남동   29988 ----------


 ---------- 2019-10-22 17:00:00 : 동내면   29989 ----------


 ---------- 2019-10-22 19:00:00 : 동  면   29992 ----------


 ---------- 2019-10-22 20:00:00 : 효자1동   29994 ----------


 ---------- 2019-10-22 21:00:00 : 효자1동   29995 ----------


 ---------- 2019-10-23 08:00:00 : 신북읍   29997 ----------


 ---------- 2019-10-23 09:00:00 : 남산면   29999 ----------


 ---------- 2019-10-23 09:00:00 : 동  면   30002 ----------


 ---------- 2019-10-23 10:00:00 : 후평1동   30003 ----------


 ---------- 2019-10-23 11:00:00 : 소양동   30004 ----------


 ---------- 2019-10-23 11:00:00 : 동  면   30005 ----------


 ---------- 2019-10-23 14:00:00 : 퇴계동   30006 ----------


 ---------- 2019-10-23 15:00:00 : 효자1동   30007 ----------


 ---------- 2019-10-24 09:00:00 : 석사동   30008 ----------


 ---------- 2019-10-24 09:00:00 : 효자1동   30009 ----------


 ---------- 2019-10-24 16:00:00 : 신사우동   30010 ----------


 ---------- 2019-10-24 23:00:00 : 교  동   30012 ----------


 ---------- 2019-10-25 06:00:00 : 신사우동   30013 ----------


 ---------- 2019-10-25 08:00:00 : 신사우동   30014 ----------


 ---------- 2019-10-25 12:00:00 : 서  면   30015 ----------


 ---------- 2019-10-25 14:00:00 : 동내면   30016 ----------


 ---------- 2019-10-25 15:00:00 : 동  면   30017 ----------


 ---------- 2019-10-25 16:00:00 : 동내면   30018 ----------


 ---------- 2019-10-25 16:00:00 : 소양동   30019 ----------


 ---------- 2019-10-25 18:00:00 : 남산면   30021 ----------


 ---------- 2019-10-25 19:00:00 : 소양동   30022 ----------


 ---------- 2019-10-25 23:00:00 : 소양동   30024 ----------


 ---------- 2019-10-26 10:00:00 : 동내면   30025 ----------


 ---------- 2019-10-26 12:00:00 : 후평1동   30026 ----------


 ---------- 2019-10-26 13:00:00 : 퇴계동   30027 ----------


 ---------- 2019-10-26 14:00:00 : 석사동   30028 ----------


 ---------- 2019-10-26 15:00:00 : 남산면   30029 ----------


 ---------- 2019-10-26 17:00:00 : 석사동   30030 ----------


 ---------- 2019-10-26 19:00:00 : 서  면   30031 ----------


 ---------- 2019-10-26 20:00:00 : 석사동   30033 ----------


 ---------- 2019-10-26 21:00:00 : 석사동   30034 ----------


 ---------- 2019-10-27 02:00:00 : 사북면   30035 ----------


 ---------- 2019-10-27 09:00:00 : 후평1동   30037 ----------


 ---------- 2019-10-27 10:00:00 : 신사우동   30039 ----------


 ---------- 2019-10-27 13:00:00 : 동내면   30041 ----------


 ---------- 2019-10-27 14:00:00 : 신사우동   30043 ----------


 ---------- 2019-10-27 18:00:00 : 강남동   30046 ----------


 ---------- 2019-10-27 21:00:00 : 신동면   30048 ----------


 ---------- 2019-10-28 03:00:00 : 동  면   30049 ----------


 ---------- 2019-10-28 13:00:00 : 남  면   30050 ----------


 ---------- 2019-10-28 16:00:00 : 소양동   30051 ----------


 ---------- 2019-10-28 17:00:00 : 신북읍   30052 ----------


 ---------- 2019-10-29 21:00:00 : 근화동   30053 ----------


 ---------- 2019-10-30 00:00:00 : 소양동   30054 ----------


 ---------- 2019-10-30 10:00:00 : 동  면   30056 ----------


 ---------- 2019-10-30 11:00:00 : 남산면   30057 ----------


 ---------- 2019-10-30 11:00:00 : 동  면   30058 ----------


 ---------- 2019-10-30 12:00:00 : 서  면   30062 ----------

 ---------- 2019-10-30 13:00:00 : 근화동   30064 ----------


 ---------- 2019-10-30 18:00:00 : 서  면   30065 ----------


 ---------- 2019-10-31 13:00:00 : 효자1동   30068 ----------


 ---------- 2019-10-31 15:00:00 : 약사명동   30069 ----------


 ---------- 2019-10-31 16:00:00 : 동내면   30070 ----------


 ---------- 2019-10-31 16:00:00 : 근화동   30071 ----------


 ---------- 2019-10-31 17:00:00 : 석사동   30072 ----------


 ---------- 2019-11-01 05:00:00 : 동산면   30073 ----------


 ---------- 2019-11-01 08:00:00 : 신북읍   30074 ----------


 ---------- 2019-11-01 10:00:00 : 효자1동   30076 ----------


 ---------- 2019-11-01 14:00:00 : 동내면   30077 ----------


 ---------- 2019-11-01 16:00:00 : 남산면   30078 ----------


 ---------- 2019-11-01 21:00:00 : 강남동   30080 ----------


 ---------- 2019-11-02 02:00:00 : 효자1동   30081 ----------


 ---------- 2019-11-02 10:00:00 : 소양동   30082 ----------


 ---------- 2019-11-02 11:00:00 : 남산면   30083 ----------


 ---------- 2019-11-02 13:00:00 : 교  동   30084 ----------


 ---------- 2019-11-02 14:00:00 : 석사동   30085 ----------


 ---------- 2019-11-02 21:00:00 : 석사동   30086 ----------


 ---------- 2019-11-03 08:00:00 : 신사우동   30088 ----------


 ---------- 2019-11-03 09:00:00 : 후평1동   30089 ----------


 ---------- 2019-11-03 10:00:00 : 남산면   30090 ----------


 ---------- 2019-11-03 11:00:00 : 신동면   30091 ----------


 ---------- 2019-11-03 11:00:00 : 강남동   30092 ----------


 ---------- 2019-11-03 12:00:00 : 남산면   30093 ----------


 ---------- 2019-11-03 12:00:00 : 신사우동   30094 ----------


 ---------- 2019-11-03 13:00:00 : 동  면   30095 ----------


 ---------- 2019-11-03 19:00:00 : 동산면   30096 ----------


 ---------- 2019-11-03 22:00:00 : 퇴계동   30097 ----------


 ---------- 2019-11-03 23:00:00 : 남산면   30099 ----------


 ---------- 2019-11-04 08:00:00 : 후평1동   30100 ----------


 ---------- 2019-11-04 09:00:00 : 사북면   30101 ----------


 ---------- 2019-11-04 09:00:00 : 동  면   30102 ----------


 ---------- 2019-11-04 14:00:00 : 동  면   30103 ----------


 ---------- 2019-11-04 17:00:00 : 후평1동   30104 ----------


 ---------- 2019-11-04 23:00:00 : 퇴계동   30105 ----------


 ---------- 2019-11-05 00:00:00 : 동산면   30106 ----------


 ---------- 2019-11-05 09:00:00 : 신사우동   30107 ----------


 ---------- 2019-11-05 11:00:00 : 퇴계동   30109 ----------


 ---------- 2019-11-05 12:00:00 : 석사동   30110 ----------


 ---------- 2019-11-05 12:00:00 : 남산면   30111 ----------


 ---------- 2019-11-05 15:00:00 : 사북면   30112 ----------


 ---------- 2019-11-06 02:00:00 : 동  면   30114 ----------


 ---------- 2019-11-06 10:00:00 : 석사동   30115 ----------


 ---------- 2019-11-06 15:00:00 : 서  면   30116 ----------


 ---------- 2019-11-06 16:00:00 : 서  면   30117 ----------


 ---------- 2019-11-06 18:00:00 : 동내면   30119 ----------


 ---------- 2019-11-06 18:00:00 : 신사우동   30120 ----------


 ---------- 2019-11-07 08:00:00 : 강남동   30121 ----------


 ---------- 2019-11-07 09:00:00 : 신사우동   30122 ----------


 ---------- 2019-11-07 12:00:00 : 후평1동   30123 ----------


 ---------- 2019-11-07 13:00:00 : 남산면   30124 ----------


 ---------- 2019-11-07 17:00:00 : 후평1동   30126 ----------


 ---------- 2019-11-07 18:00:00 : 서  면   30129 ----------


 ---------- 2019-11-07 22:00:00 : 석사동   30131 ----------


 ---------- 2019-11-08 02:00:00 : 신사우동   30132 ----------


 ---------- 2019-11-08 07:00:00 : 동산면   30133 ----------


 ---------- 2019-11-08 10:00:00 : 후평1동   30137 ----------


 ---------- 2019-11-08 12:00:00 : 동  면   30138 ----------


 ---------- 2019-11-08 18:00:00 : 후평1동   30139 ----------


 ---------- 2019-11-09 11:00:00 : 석사동   30140 ----------


 ---------- 2019-11-09 11:00:00 : 퇴계동   30141 ----------


 ---------- 2019-11-09 14:00:00 : 사북면   30142 ----------


 ---------- 2019-11-09 14:00:00 : 동산면   30143 ----------


 ---------- 2019-11-09 16:00:00 : 석사동   30144 ----------


 ---------- 2019-11-09 16:00:00 : 서  면   30145 ----------


 ---------- 2019-11-09 20:00:00 : 신사우동   30146 ----------


 ---------- 2019-11-10 14:00:00 : 남  면   30147 ----------


 ---------- 2019-11-10 18:00:00 : 강남동   30148 ----------


 ---------- 2019-11-10 22:00:00 : 소양동   30149 ----------


 ---------- 2019-11-11 09:00:00 : 동산면   30150 ----------


 ---------- 2019-11-11 11:00:00 : 퇴계동   30151 ----------


 ---------- 2019-11-11 12:00:00 : 사북면   30152 ----------


 ---------- 2019-11-11 14:00:00 : 강남동   30154 ----------


 ---------- 2019-11-11 15:00:00 : 퇴계동   30156 ----------


 ---------- 2019-11-11 17:00:00 : 후평1동   30158 ----------


 ---------- 2019-11-11 22:00:00 : 남산면   30160 ----------


 ---------- 2019-11-12 13:00:00 : 퇴계동   30161 ----------


 ---------- 2019-11-12 18:00:00 : 강남동   30163 ----------


 ---------- 2019-11-12 23:00:00 : 석사동   30164 ----------


 ---------- 2019-11-13 02:00:00 : 석사동   30165 ----------


 ---------- 2019-11-13 08:00:00 : 근화동   30167 ----------


 ---------- 2019-11-13 10:00:00 : 조운동   30169 ----------


 ---------- 2019-11-13 11:00:00 : 남산면   30170 ----------


 ---------- 2019-11-13 16:00:00 : 동  면   30171 ----------


 ---------- 2019-11-14 11:00:00 : 남  면   30172 ----------


 ---------- 2019-11-14 11:00:00 : 동내면   30173 ----------


 ---------- 2019-11-14 11:00:00 : 퇴계동   30174 ----------


 ---------- 2019-11-14 13:00:00 : 석사동   30175 ----------


 ---------- 2019-11-14 13:00:00 : 동내면   30176 ----------


 ---------- 2019-11-14 13:00:00 : 동  면   30177 ----------


 ---------- 2019-11-14 18:00:00 : 효자1동   30179 ----------


 ---------- 2019-11-14 19:00:00 : 남산면   30182 ----------


 ---------- 2019-11-15 01:00:00 : 소양동   30183 ----------


 ---------- 2019-11-15 07:00:00 : 서  면   30184 ----------


 ---------- 2019-11-15 07:00:00 : 근화동   30186 ----------


 ---------- 2019-11-15 08:00:00 : 신북읍   30188 ----------


 ---------- 2019-11-15 09:00:00 : 신북읍   30189 ----------


 ---------- 2019-11-15 10:00:00 : 동내면   30190 ----------


 ---------- 2019-11-15 15:00:00 : 동내면   30191 ----------


 ---------- 2019-11-15 16:00:00 : 신사우동   30193 ----------


 ---------- 2019-11-15 18:00:00 : 남  면   30194 ----------


 ---------- 2019-11-15 22:00:00 : 석사동   30195 ----------


 ---------- 2019-11-16 08:00:00 : 효자1동   30197 ----------


 ---------- 2019-11-16 09:00:00 : 후평1동   30198 ----------


 ---------- 2019-11-16 12:00:00 : 강남동   30200 ----------


 ---------- 2019-11-16 14:00:00 : 강남동   30202 ----------


 ---------- 2019-11-16 14:00:00 : 신북읍   30203 ----------


 ---------- 2019-11-16 15:00:00 : 신사우동   30204 ----------


 ---------- 2019-11-16 16:00:00 : 석사동   30205 ----------


 ---------- 2019-11-16 18:00:00 : 약사명동   30207 ----------


 ---------- 2019-11-16 21:00:00 : 남  면   30209 ----------


 ---------- 2019-11-16 23:00:00 : 퇴계동   30210 ----------


 ---------- 2019-11-17 08:00:00 : 사북면   30211 ----------


 ---------- 2019-11-17 17:00:00 : 강남동   30212 ----------


 ---------- 2019-11-17 18:00:00 : 후평1동   30213 ----------


 ---------- 2019-11-18 06:00:00 : 교  동   30214 ----------


 ---------- 2019-11-18 10:00:00 : 후평1동   30215 ----------


 ---------- 2019-11-18 12:00:00 : 사북면   30217 ----------


 ---------- 2019-11-18 14:00:00 : 후평1동   30218 ----------


 ---------- 2019-11-18 18:00:00 : 후평1동   30219 ----------


 ---------- 2019-11-19 00:00:00 : 석사동   30220 ----------


 ---------- 2019-11-19 03:00:00 : 소양동   30221 ----------


 ---------- 2019-11-19 04:00:00 : 약사명동   30222 ----------


 ---------- 2019-11-19 05:00:00 : 조운동   30224 ----------


 ---------- 2019-11-19 10:00:00 : 소양동   30226 ----------


 ---------- 2019-11-19 11:00:00 : 퇴계동   30228 ----------


 ---------- 2019-11-19 14:00:00 : 효자1동   30229 ----------


 ---------- 2019-11-20 10:00:00 : 동내면   30230 ----------


 ---------- 2019-11-20 10:00:00 : 동산면   30231 ----------


 ---------- 2019-11-20 15:00:00 : 신북읍   30233 ----------


 ---------- 2019-11-21 09:00:00 : 동산면   30234 ----------


 ---------- 2019-11-21 12:00:00 : 남산면   30235 ----------


 ---------- 2019-11-21 13:00:00 : 신사우동   30237 ----------


 ---------- 2019-11-22 00:00:00 : 근화동   30239 ----------


 ---------- 2019-11-22 08:00:00 : 강남동   30240 ----------

 ---------- 2019-11-22 13:00:00 : 후평1동   30242 ----------


 ---------- 2019-11-22 18:00:00 : 석사동   30243 ----------


 ---------- 2019-11-22 18:00:00 : 강남동   30245 ----------


 ---------- 2019-11-23 08:00:00 : 신동면   30247 ----------


 ---------- 2019-11-23 15:00:00 : 소양동   30248 ----------


 ---------- 2019-11-23 19:00:00 : 동  면   30249 ----------


 ---------- 2019-11-24 00:00:00 : 후평1동   30250 ----------


 ---------- 2019-11-24 12:00:00 : 동  면   30251 ----------


 ---------- 2019-11-24 15:00:00 : 남산면   30252 ----------


 ---------- 2019-11-25 08:00:00 : 신동면   30255 ----------


 ---------- 2019-11-25 10:00:00 : 동  면   30256 ----------


 ---------- 2019-11-25 15:00:00 : 강남동   30258 ----------


 ---------- 2019-11-25 16:00:00 : 퇴계동   30260 ----------


 ---------- 2019-11-25 17:00:00 : 신동면   30261 ----------


 ---------- 2019-11-26 08:00:00 : 동  면   30262 ----------


 ---------- 2019-11-26 16:00:00 : 후평1동   30263 ----------


 ---------- 2019-11-27 08:00:00 : 퇴계동   30265 ----------


 ---------- 2019-11-27 12:00:00 : 신북읍   30266 ----------


 ---------- 2019-11-27 12:00:00 : 교  동   30267 ----------


 ---------- 2019-11-27 13:00:00 : 석사동   30268 ----------


 ---------- 2019-11-27 16:00:00 : 퇴계동   30269 ----------


 ---------- 2019-11-27 19:00:00 : 퇴계동   30272 ----------


 ---------- 2019-11-27 23:00:00 : 석사동   30274 ----------


 ---------- 2019-11-28 03:00:00 : 석사동   30277 ----------


 ---------- 2019-11-28 04:00:00 : 후평1동   30279 ----------


 ---------- 2019-11-28 10:00:00 : 북산면   30280 ----------


 ---------- 2019-11-28 16:00:00 : 강남동   30283 ----------


 ---------- 2019-11-28 16:00:00 : 신사우동   30284 ----------


 ---------- 2019-11-28 22:00:00 : 소양동   30285 ----------


 ---------- 2019-11-29 05:00:00 : 신동면   30286 ----------


 ---------- 2019-11-29 05:00:00 : 효자1동   30287 ----------


 ---------- 2019-11-29 09:00:00 : 사북면   30288 ----------


 ---------- 2019-11-29 12:00:00 : 강남동   30290 ----------


 ---------- 2019-11-29 15:00:00 : 소양동   30291 ----------


 ---------- 2019-11-29 17:00:00 : 효자1동   30292 ----------


 ---------- 2019-11-29 17:00:00 : 동  면   30293 ----------


 ---------- 2019-11-29 18:00:00 : 강남동   30295 ----------


 ---------- 2019-11-29 20:00:00 : 동내면   30298 ----------


 ---------- 2019-11-29 22:00:00 : 소양동   30299 ----------


 ---------- 2019-11-30 02:00:00 : 신동면   30302 ----------


 ---------- 2019-11-30 08:00:00 : 동산면   30303 ----------


 ---------- 2019-12-01 06:00:00 : 신사우동   30304 ----------


 ---------- 2019-12-01 15:00:00 : 서  면   30305 ----------


 ---------- 2019-12-01 16:00:00 : 약사명동   30307 ----------


 ---------- 2019-12-01 23:00:00 : 강남동   30308 ----------


 ---------- 2019-12-02 05:00:00 : 동산면   30309 ----------


 ---------- 2019-12-02 10:00:00 : 후평1동   30310 ----------


 ---------- 2019-12-02 13:00:00 : 퇴계동   30311 ----------


 ---------- 2019-12-02 15:00:00 : 남산면   30312 ----------


 ---------- 2019-12-02 21:00:00 : 근화동   30314 ----------


 ---------- 2019-12-03 08:00:00 : 퇴계동   30315 ----------


 ---------- 2019-12-03 16:00:00 : 석사동   30316 ----------


 ---------- 2019-12-03 21:00:00 : 효자1동   30317 ----------


 ---------- 2019-12-04 04:00:00 : 신사우동   30318 ----------


 ---------- 2019-12-04 05:00:00 : 석사동   30319 ----------


 ---------- 2019-12-04 08:00:00 : 신사우동   30320 ----------


 ---------- 2019-12-04 14:00:00 : 교  동   30321 ----------


 ---------- 2019-12-04 16:00:00 : 동내면   30322 ----------


 ---------- 2019-12-04 23:00:00 : 조운동   30323 ----------


 ---------- 2019-12-05 04:00:00 : 강남동   30324 ----------


 ---------- 2019-12-05 08:00:00 : 북산면   30327 ----------


 ---------- 2019-12-05 09:00:00 : 효자1동   30329 ----------


 ---------- 2019-12-05 21:00:00 : 동산면   30332 ----------


 ---------- 2019-12-06 09:00:00 : 북산면   30334 ----------


 ---------- 2019-12-06 19:00:00 : 동  면   30335 ----------


 ---------- 2019-12-06 23:00:00 : 퇴계동   30336 ----------


 ---------- 2019-12-07 01:00:00 : 석사동   30337 ----------


 ---------- 2019-12-07 04:00:00 : 강남동   30338 ----------


 ---------- 2019-12-07 06:00:00 : 후평1동   30339 ----------


 ---------- 2019-12-07 09:00:00 : 약사명동   30340 ----------


 ---------- 2019-12-07 10:00:00 : 신동면   30342 ----------


 ---------- 2019-12-07 10:00:00 : 강남동   30343 ----------


 ---------- 2019-12-07 11:00:00 : 신동면   30344 ----------


 ---------- 2019-12-07 12:00:00 : 퇴계동   30345 ----------


 ---------- 2019-12-07 13:00:00 : 동  면   30347 ----------


 ---------- 2019-12-07 19:00:00 : 소양동   30348 ----------


 ---------- 2019-12-07 21:00:00 : 신사우동   30349 ----------


 ---------- 2019-12-07 23:00:00 : 석사동   30350 ----------


 ---------- 2019-12-08 02:00:00 : 근화동   30351 ----------


 ---------- 2019-12-08 16:00:00 : 신북읍   30352 ----------


 ---------- 2019-12-08 17:00:00 : 후평1동   30354 ----------


 ---------- 2019-12-08 22:00:00 : 퇴계동   30355 ----------


 ---------- 2019-12-09 03:00:00 : 교  동   30356 ----------


 ---------- 2019-12-09 08:00:00 : 약사명동   30357 ----------


 ---------- 2019-12-09 12:00:00 : 퇴계동   30358 ----------


 ---------- 2019-12-09 13:00:00 : 신동면   30359 ----------


 ---------- 2019-12-09 16:00:00 : 석사동   30360 ----------


 ---------- 2019-12-10 00:00:00 : 석사동   30361 ----------


 ---------- 2019-12-10 00:00:00 : 신북읍   30362 ----------


 ---------- 2019-12-10 01:00:00 : 석사동   30363 ----------


 ---------- 2019-12-10 08:00:00 : 효자1동   30364 ----------


 ---------- 2019-12-10 12:00:00 : 강남동   30365 ----------


 ---------- 2019-12-10 13:00:00 : 강남동   30366 ----------


 ---------- 2019-12-10 19:00:00 : 신사우동   30367 ----------


 ---------- 2019-12-10 20:00:00 : 퇴계동   30368 ----------


 ---------- 2019-12-11 15:00:00 : 남  면   30369 ----------


 ---------- 2019-12-11 15:00:00 : 동  면   30370 ----------


 ---------- 2019-12-11 16:00:00 : 동  면   30371 ----------


 ---------- 2019-12-11 17:00:00 : 동  면   30372 ----------


 ---------- 2019-12-11 22:00:00 : 효자1동   30374 ----------


 ---------- 2019-12-11 23:00:00 : 서  면   30376 ----------


 ---------- 2019-12-12 10:00:00 : 퇴계동   30378 ----------


 ---------- 2019-12-12 13:00:00 : 소양동   30380 ----------


 ---------- 2019-12-12 14:00:00 : 신북읍   30381 ----------


 ---------- 2019-12-12 16:00:00 : 서  면   30382 ----------


 ---------- 2019-12-13 03:00:00 : 효자1동   30385 ----------


 ---------- 2019-12-13 12:00:00 : 강남동   30386 ----------


 ---------- 2019-12-13 13:00:00 : 교  동   30391 ----------


 ---------- 2019-12-13 14:00:00 : 남산면   30392 ----------


 ---------- 2019-12-13 16:00:00 : 동내면   30393 ----------


 ---------- 2019-12-13 17:00:00 : 동내면   30394 ----------


 ---------- 2019-12-13 22:00:00 : 후평1동   30395 ----------


 ---------- 2019-12-13 23:00:00 : 동  면   30396 ----------


 ---------- 2019-12-14 02:00:00 : 교  동   30397 ----------


 ---------- 2019-12-14 11:00:00 : 소양동   30398 ----------


 ---------- 2019-12-14 13:00:00 : 석사동   30400 ----------


 ---------- 2019-12-14 13:00:00 : 남산면   30401 ----------


 ---------- 2019-12-14 15:00:00 : 강남동   30403 ----------


 ---------- 2019-12-14 15:00:00 : 후평1동   30404 ----------


 ---------- 2019-12-14 16:00:00 : 강남동   30405 ----------


 ---------- 2019-12-14 19:00:00 : 동내면   30406 ----------


 ---------- 2019-12-14 21:00:00 : 퇴계동   30408 ----------


 ---------- 2019-12-15 02:00:00 : 남산면   30409 ----------


 ---------- 2019-12-15 09:00:00 : 강남동   30410 ----------


 ---------- 2019-12-15 12:00:00 : 동산면   30411 ----------


 ---------- 2019-12-15 13:00:00 : 후평1동   30412 ----------


 ---------- 2019-12-15 15:00:00 : 근화동   30413 ----------


 ---------- 2019-12-15 18:00:00 : 소양동   30414 ----------


 ---------- 2019-12-15 22:00:00 : 효자1동   30415 ----------


 ---------- 2019-12-16 01:00:00 : 강남동   30417 ----------


 ---------- 2019-12-16 05:00:00 : 동  면   30418 ----------


 ---------- 2019-12-16 09:00:00 : 동  면   30419 ----------


 ---------- 2019-12-16 13:00:00 : 후평1동   30420 ----------


 ---------- 2019-12-16 16:00:00 : 동내면   30421 ----------


 ---------- 2019-12-16 18:00:00 : 석사동   30422 ----------


 ---------- 2019-12-16 21:00:00 : 동  면   30424 ----------

 ---------- 2019-12-17 02:00:00 : 동내면   30425 ----------


 ---------- 2019-12-17 04:00:00 : 신사우동   30426 ----------


 ---------- 2019-12-17 06:00:00 : 효자1동   30427 ----------


 ---------- 2019-12-17 12:00:00 : 근화동   30428 ----------


 ---------- 2019-12-17 14:00:00 : 신북읍   30429 ----------


 ---------- 2019-12-17 14:00:00 : 퇴계동   30430 ----------


 ---------- 2019-12-17 17:00:00 : 신사우동   30431 ----------


 ---------- 2019-12-18 00:00:00 : 신사우동   30432 ----------


 ---------- 2019-12-18 00:00:00 : 후평1동   30434 ----------


 ---------- 2019-12-18 09:00:00 : 효자1동   30435 ----------


 ---------- 2019-12-18 14:00:00 : 남산면   30437 ----------


 ---------- 2019-12-18 23:00:00 : 동내면   30438 ----------


 ---------- 2019-12-19 18:00:00 : 신사우동   30439 ----------


 ---------- 2019-12-20 18:00:00 : 퇴계동   30440 ----------


 ---------- 2019-12-21 03:00:00 : 퇴계동   30441 ----------


 ---------- 2019-12-21 12:00:00 : 약사명동   30442 ----------


 ---------- 2019-12-21 15:00:00 : 효자1동   30443 ----------


 ---------- 2019-12-21 17:00:00 : 남  면   30445 ----------


 ---------- 2019-12-22 01:00:00 : 남  면   30446 ----------


 ---------- 2019-12-22 13:00:00 : 동  면   30447 ----------


 ---------- 2019-12-22 14:00:00 : 남  면   30449 ----------


 ---------- 2019-12-22 18:00:00 : 퇴계동   30450 ----------


 ---------- 2019-12-22 19:00:00 : 효자1동   30451 ----------


 ---------- 2019-12-22 23:00:00 : 약사명동   30452 ----------


 ---------- 2019-12-23 03:00:00 : 동산면   30453 ----------


 ---------- 2019-12-23 11:00:00 : 퇴계동   30455 ----------


 ---------- 2019-12-23 12:00:00 : 효자1동   30456 ----------


 ---------- 2019-12-23 15:00:00 : 신사우동   30457 ----------


 ---------- 2019-12-23 21:00:00 : 근화동   30458 ----------


 ---------- 2019-12-24 10:00:00 : 북산면   30459 ----------


 ---------- 2019-12-24 12:00:00 : 남  면   30460 ----------


 ---------- 2019-12-24 14:00:00 : 강남동   30461 ----------


 ---------- 2019-12-24 14:00:00 : 신북읍   30462 ----------


 ---------- 2019-12-24 15:00:00 : 강남동   30463 ----------


 ---------- 2019-12-24 16:00:00 : 퇴계동   30464 ----------


 ---------- 2019-12-24 17:00:00 : 동  면   30466 ----------


 ---------- 2019-12-24 23:00:00 : 동산면   30468 ----------


 ---------- 2019-12-25 15:00:00 : 교  동   30469 ----------


 ---------- 2019-12-26 21:00:00 : 동  면   30470 ----------


 ---------- 2019-12-26 22:00:00 : 효자1동   30471 ----------


 ---------- 2019-12-27 01:00:00 : 효자1동   30472 ----------


 ---------- 2019-12-27 01:00:00 : 퇴계동   30473 ----------


 ---------- 2019-12-27 09:00:00 : 신사우동   30474 ----------


 ---------- 2019-12-27 13:00:00 : 동내면   30476 ----------


 ---------- 2019-12-27 17:00:00 : 후평1동   30478 ----------


 ---------- 2019-12-27 18:00:00 : 동산면   30479 ----------


 ---------- 2019-12-28 02:00:00 : 강남동   30480 ----------


 ---------- 2019-12-28 03:00:00 : 강남동   30481 ----------


 ---------- 2019-12-28 06:00:00 : 근화동   30482 ----------


 ---------- 2019-12-28 15:00:00 : 약사명동   30483 ----------


 ---------- 2019-12-28 16:00:00 : 강남동   30484 ----------


 ---------- 2019-12-29 05:00:00 : 소양동   30485 ----------


 ---------- 2019-12-29 11:00:00 : 근화동   30486 ----------


 ---------- 2019-12-29 13:00:00 : 조운동   30487 ----------


 ---------- 2019-12-29 15:00:00 : 퇴계동   30488 ----------


 ---------- 2019-12-30 10:00:00 : 신북읍   30489 ----------


 ---------- 2019-12-30 21:00:00 : 석사동   30490 ----------


 ---------- 2019-12-30 22:00:00 : 서  면   30491 ----------


 ---------- 2019-12-31 06:00:00 : 석사동   30492 ----------


 ---------- 2020-01-01 00:00:00 : 효자1동   30493 ----------


 ---------- 2020-01-01 00:00:00 : 신사우동   30494 ----------


 ---------- 2020-01-01 01:00:00 : 효자1동   30495 ----------


 ---------- 2020-01-01 07:00:00 : 동  면   30496 ----------


 ---------- 2020-01-01 12:00:00 : 퇴계동   30499 ----------


 ---------- 2020-01-01 13:00:00 : 후평1동   30500 ----------


 ---------- 2020-01-01 18:00:00 : 퇴계동   30501 ----------


 ---------- 2020-01-01 23:00:00 : 소양동   30502 ----------


 ---------- 2020-01-02 00:00:00 : 석사동   30503 ----------


 ---------- 2020-01-02 04:00:00 : 퇴계동   30504 ----------


 ---------- 2020-01-02 05:00:00 : 신사우동   30505 ----------


 ---------- 2020-01-02 09:00:00 : 동  면   30506 ----------


 ---------- 2020-01-02 11:00:00 : 근화동   30507 ----------


 ---------- 2020-01-02 19:00:00 : 석사동   30508 ----------


 ---------- 2020-01-02 21:00:00 : 사북면   30510 ----------


 ---------- 2020-01-03 00:00:00 : 신동면   30511 ----------


 ---------- 2020-01-03 10:00:00 : 동내면   30512 ----------


 ---------- 2020-01-03 11:00:00 : 석사동   30513 ----------


 ---------- 2020-01-03 12:00:00 : 서  면   30514 ----------


 ---------- 2020-01-03 12:00:00 : 후평1동   30515 ----------


 ---------- 2020-01-03 14:00:00 : 효자1동   30517 ----------


 ---------- 2020-01-03 16:00:00 : 근화동   30518 ----------


 ---------- 2020-01-04 08:00:00 : 후평1동   30519 ----------


 ---------- 2020-01-04 14:00:00 : 동내면   30520 ----------


 ---------- 2020-01-04 14:00:00 : 동  면   30521 ----------


 ---------- 2020-01-04 17:00:00 : 신사우동   30522 ----------


 ---------- 2020-01-04 18:00:00 : 후평1동   30524 ----------


 ---------- 2020-01-05 03:00:00 : 남산면   30525 ----------


 ---------- 2020-01-05 06:00:00 : 신북읍   30526 ----------


 ---------- 2020-01-05 07:00:00 : 신북읍   30527 ----------


 ---------- 2020-01-05 10:00:00 : 신동면   30528 ----------


 ---------- 2020-01-05 13:00:00 : 신동면   30529 ----------


 ---------- 2020-01-05 14:00:00 : 북산면   30530 ----------


 ---------- 2020-01-05 17:00:00 : 석사동   30531 ----------


 ---------- 2020-01-05 17:00:00 : 동산면   30532 ----------


 ---------- 2020-01-05 18:00:00 : 효자1동   30533 ----------


 ---------- 2020-01-05 18:00:00 : 퇴계동   30535 ----------


 ---------- 2020-01-05 20:00:00 : 남산면   30539 ----------


 ---------- 2020-01-06 00:00:00 : 신북읍   30540 ----------


 ---------- 2020-01-06 07:00:00 : 신북읍   30541 ----------


 ---------- 2020-01-06 11:00:00 : 서  면   30542 ----------


 ---------- 2020-01-06 11:00:00 : 신북읍   30543 ----------


 ---------- 2020-01-06 12:00:00 : 소양동   30544 ----------


 ---------- 2020-01-06 14:00:00 : 신북읍   30545 ----------


 ---------- 2020-01-06 18:00:00 : 효자1동   30546 ----------


 ---------- 2020-01-06 18:00:00 : 약사명동   30547 ----------


 ---------- 2020-01-06 22:00:00 : 석사동   30548 ----------


 ---------- 2020-01-07 01:00:00 : 서  면   30549 ----------


 ---------- 2020-01-07 08:00:00 : 후평1동   30550 ----------


 ---------- 2020-01-07 08:00:00 : 동산면   30551 ----------


 ---------- 2020-01-07 10:00:00 : 남산면   30552 ----------


 ---------- 2020-01-07 12:00:00 : 동산면   30553 ----------


 ---------- 2020-01-08 00:00:00 : 석사동   30555 ----------


 ---------- 2020-01-08 01:00:00 : 신북읍   30556 ----------


 ---------- 2020-01-08 06:00:00 : 효자1동   30557 ----------


 ---------- 2020-01-08 06:00:00 : 퇴계동   30558 ----------


 ---------- 2020-01-08 17:00:00 : 효자1동   30559 ----------


 ---------- 2020-01-08 21:00:00 : 조운동   30560 ----------


 ---------- 2020-01-08 23:00:00 : 석사동   30561 ----------


 ---------- 2020-01-08 23:00:00 : 퇴계동   30562 ----------


 ---------- 2020-01-09 00:00:00 : 석사동   30563 ----------


 ---------- 2020-01-09 03:00:00 : 효자1동   30564 ----------


 ---------- 2020-01-09 12:00:00 : 퇴계동   30565 ----------


 ---------- 2020-01-09 13:00:00 : 강남동   30566 ----------


 ---------- 2020-01-09 13:00:00 : 퇴계동   30567 ----------


 ---------- 2020-01-09 19:00:00 : 석사동   30568 ----------


 ---------- 2020-01-10 06:00:00 : 강남동   30569 ----------


 ---------- 2020-01-10 15:00:00 : 신사우동   30570 ----------


 ---------- 2020-01-10 16:00:00 : 신북읍   30572 ----------


 ---------- 2020-01-10 17:00:00 : 신북읍   30573 ----------


 ---------- 2020-01-10 21:00:00 : 석사동   30574 ----------


 ---------- 2020-01-10 22:00:00 : 동내면   30575 ----------


 ---------- 2020-01-11 11:00:00 : 효자1동   30576 ----------


 ---------- 2020-01-11 11:00:00 : 동산면   30577 ----------


 ---------- 2020-01-11 12:00:00 : 사북면   30578 ----------


 ---------- 2020-01-11 17:00:00 : 동내면   30579 ----------


 ---------- 2020-01-12 02:00:00 : 동내면   30580 ----------

 ---------- 2020-01-12 03:00:00 : 퇴계동   30581 ----------


 ---------- 2020-01-12 05:00:00 : 북산면   30582 ----------


 ---------- 2020-01-12 11:00:00 : 교  동   30584 ----------


 ---------- 2020-01-12 14:00:00 : 효자1동   30585 ----------


 ---------- 2020-01-12 15:00:00 : 근화동   30588 ----------


 ---------- 2020-01-12 17:00:00 : 석사동   30589 ----------


 ---------- 2020-01-12 22:00:00 : 퇴계동   30591 ----------


 ---------- 2020-01-13 09:00:00 : 동내면   30592 ----------


 ---------- 2020-01-13 13:00:00 : 신사우동   30593 ----------


 ---------- 2020-01-13 18:00:00 : 남산면   30594 ----------


 ---------- 2020-01-14 15:00:00 : 효자1동   30596 ----------


 ---------- 2020-01-14 17:00:00 : 소양동   30597 ----------


 ---------- 2020-01-15 13:00:00 : 남산면   30598 ----------


 ---------- 2020-01-15 14:00:00 : 남산면   30600 ----------


 ---------- 2020-01-15 19:00:00 : 퇴계동   30601 ----------


 ---------- 2020-01-16 09:00:00 : 남  면   30603 ----------


 ---------- 2020-01-16 14:00:00 : 신북읍   30604 ----------


 ---------- 2020-01-16 17:00:00 : 효자1동   30605 ----------


 ---------- 2020-01-16 18:00:00 : 교  동   30606 ----------


 ---------- 2020-01-16 22:00:00 : 석사동   30607 ----------


 ---------- 2020-01-17 06:00:00 : 교  동   30608 ----------


 ---------- 2020-01-17 07:00:00 : 동  면   30610 ----------


 ---------- 2020-01-18 16:00:00 : 신북읍   30611 ----------


 ---------- 2020-01-18 20:00:00 : 강남동   30612 ----------


 ---------- 2020-01-19 04:00:00 : 퇴계동   30613 ----------


 ---------- 2020-01-19 05:00:00 : 조운동   30614 ----------


 ---------- 2020-01-19 07:00:00 : 석사동   30615 ----------


 ---------- 2020-01-19 14:00:00 : 동내면   30616 ----------


 ---------- 2020-01-19 16:00:00 : 동산면   30617 ----------


 ---------- 2020-01-19 17:00:00 : 동  면   30618 ----------


 ---------- 2020-01-20 07:00:00 : 동  면   30619 ----------


 ---------- 2020-01-20 09:00:00 : 강남동   30620 ----------


 ---------- 2020-01-20 10:00:00 : 강남동   30621 ----------


 ---------- 2020-01-20 12:00:00 : 신북읍   30622 ----------


 ---------- 2020-01-20 18:00:00 : 효자1동   30623 ----------


 ---------- 2020-01-21 08:00:00 : 석사동   30624 ----------


 ---------- 2020-01-21 15:00:00 : 소양동   30625 ----------


 ---------- 2020-01-21 21:00:00 : 약사명동   30626 ----------


 ---------- 2020-01-22 03:00:00 : 남  면   30628 ----------


 ---------- 2020-01-22 06:00:00 : 남  면   30629 ----------


 ---------- 2020-01-22 07:00:00 : 남  면   30630 ----------


 ---------- 2020-01-22 09:00:00 : 신사우동   30631 ----------


 ---------- 2020-01-22 11:00:00 : 신사우동   30632 ----------


 ---------- 2020-01-22 17:00:00 : 사북면   30634 ----------


 ---------- 2020-01-23 09:00:00 : 조운동   30635 ----------


 ---------- 2020-01-23 09:00:00 : 교  동   30636 ----------


 ---------- 2020-01-23 13:00:00 : 후평1동   30637 ----------


 ---------- 2020-01-24 08:00:00 : 신북읍   30638 ----------


 ---------- 2020-01-24 16:00:00 : 동내면   30639 ----------


 ---------- 2020-01-24 17:00:00 : 동내면   30640 ----------


 ---------- 2020-01-25 02:00:00 : 퇴계동   30642 ----------


 ---------- 2020-01-25 21:00:00 : 강남동   30644 ----------


 ---------- 2020-01-25 21:00:00 : 후평1동   30645 ----------


 ---------- 2020-01-26 01:00:00 : 소양동   30646 ----------


 ---------- 2020-01-26 15:00:00 : 신사우동   30647 ----------


 ---------- 2020-01-27 11:00:00 : 석사동   30648 ----------


 ---------- 2020-01-27 11:00:00 : 사북면   30649 ----------


 ---------- 2020-01-27 12:00:00 : 동내면   30650 ----------


 ---------- 2020-01-27 21:00:00 : 신사우동   30651 ----------


 ---------- 2020-01-29 09:00:00 : 소양동   30652 ----------


 ---------- 2020-01-29 11:00:00 : 동내면   30653 ----------


 ---------- 2020-01-29 11:00:00 : 소양동   30654 ----------


 ---------- 2020-01-29 11:00:00 : 후평1동   30656 ----------


 ---------- 2020-01-29 21:00:00 : 소양동   30657 ----------


 ---------- 2020-01-29 21:00:00 : 퇴계동   30658 ----------


 ---------- 2020-01-30 14:00:00 : 남산면   30660 ----------


 ---------- 2020-01-31 02:00:00 : 동내면   30661 ----------


 ---------- 2020-01-31 09:00:00 : 후평1동   30662 ----------


 ---------- 2020-01-31 14:00:00 : 퇴계동   30663 ----------


 ---------- 2020-02-01 03:00:00 : 석사동   30664 ----------


 ---------- 2020-02-01 22:00:00 : 후평1동   30665 ----------


 ---------- 2020-02-02 01:00:00 : 동산면   30666 ----------


 ---------- 2020-02-02 03:00:00 : 조운동   30668 ----------


 ---------- 2020-02-02 10:00:00 : 서  면   30669 ----------


 ---------- 2020-02-02 10:00:00 : 남산면   30670 ----------


 ---------- 2020-02-02 12:00:00 : 동  면   30671 ----------


 ---------- 2020-02-03 09:00:00 : 신북읍   30673 ----------


 ---------- 2020-02-03 13:00:00 : 신북읍   30674 ----------


 ---------- 2020-02-03 23:00:00 : 후평1동   30675 ----------


 ---------- 2020-02-04 13:00:00 : 퇴계동   30676 ----------


 ---------- 2020-02-05 09:00:00 : 근화동   30677 ----------


 ---------- 2020-02-05 10:00:00 : 동산면   30678 ----------


 ---------- 2020-02-05 11:00:00 : 퇴계동   30679 ----------


 ---------- 2020-02-05 13:00:00 : 신북읍   30680 ----------


 ---------- 2020-02-05 20:00:00 : 남  면   30681 ----------


 ---------- 2020-02-06 13:00:00 : 서  면   30683 ----------


 ---------- 2020-02-07 03:00:00 : 효자1동   30684 ----------


 ---------- 2020-02-07 07:00:00 : 동  면   30685 ----------


 ---------- 2020-02-07 19:00:00 : 퇴계동   30686 ----------


 ---------- 2020-02-07 21:00:00 : 남산면   30687 ----------


 ---------- 2020-02-08 06:00:00 : 퇴계동   30689 ----------


 ---------- 2020-02-08 12:00:00 : 후평1동   30692 ----------


 ---------- 2020-02-08 16:00:00 : 후평1동   30693 ----------


 ---------- 2020-02-08 18:00:00 : 동산면   30694 ----------


 ---------- 2020-02-08 19:00:00 : 신사우동   30695 ----------


 ---------- 2020-02-08 21:00:00 : 신북읍   30697 ----------


 ---------- 2020-02-09 04:00:00 : 동내면   30698 ----------


 ---------- 2020-02-09 05:00:00 : 동내면   30699 ----------


 ---------- 2020-02-09 07:00:00 : 석사동   30700 ----------


 ---------- 2020-02-09 07:00:00 : 동내면   30701 ----------


 ---------- 2020-02-09 08:00:00 : 석사동   30703 ----------


 ---------- 2020-02-09 11:00:00 : 후평1동   30704 ----------


 ---------- 2020-02-09 13:00:00 : 신북읍   30705 ----------


 ---------- 2020-02-09 14:00:00 : 근화동   30706 ----------


 ---------- 2020-02-09 21:00:00 : 효자1동   30707 ----------


 ---------- 2020-02-09 21:00:00 : 신사우동   30708 ----------


 ---------- 2020-02-10 02:00:00 : 효자1동   30709 ----------


 ---------- 2020-02-10 08:00:00 : 소양동   30710 ----------


 ---------- 2020-02-10 09:00:00 : 신동면   30711 ----------


 ---------- 2020-02-10 10:00:00 : 서  면   30713 ----------


 ---------- 2020-02-10 10:00:00 : 소양동   30714 ----------


 ---------- 2020-02-10 16:00:00 : 동  면   30716 ----------


 ---------- 2020-02-10 17:00:00 : 근화동   30717 ----------


 ---------- 2020-02-10 18:00:00 : 신동면   30718 ----------


 ---------- 2020-02-10 19:00:00 : 후평1동   30719 ----------


 ---------- 2020-02-10 22:00:00 : 동내면   30721 ----------


 ---------- 2020-02-11 05:00:00 : 퇴계동   30722 ----------


 ---------- 2020-02-11 06:00:00 : 동내면   30723 ----------


 ---------- 2020-02-11 15:00:00 : 남산면   30724 ----------


 ---------- 2020-02-11 17:00:00 : 동산면   30725 ----------


 ---------- 2020-02-11 18:00:00 : 효자1동   30726 ----------


 ---------- 2020-02-12 15:00:00 : 북산면   30727 ----------


 ---------- 2020-02-12 19:00:00 : 신사우동   30728 ----------


 ---------- 2020-02-12 23:00:00 : 강남동   30730 ----------


 ---------- 2020-02-13 03:00:00 : 퇴계동   30731 ----------


 ---------- 2020-02-13 17:00:00 : 서  면   30734 ----------


 ---------- 2020-02-13 21:00:00 : 효자1동   30736 ----------


 ---------- 2020-02-14 14:00:00 : 소양동   30737 ----------


 ---------- 2020-02-14 19:00:00 : 석사동   30738 ----------


 ---------- 2020-02-14 20:00:00 : 동내면   30739 ----------


 ---------- 2020-02-15 10:00:00 : 근화동   30740 ----------


 ---------- 2020-02-15 18:00:00 : 동산면   30741 ----------


 ---------- 2020-02-16 00:00:00 : 석사동   30743 ----------


 ---------- 2020-02-16 10:00:00 : 후평1동   30744 ----------


 ---------- 2020-02-16 20:00:00 : 동내면   30745 ----------


 ---------- 2020-02-17 09:00:00 : 교  동   30746 ----------

 ---------- 2020-02-17 14:00:00 : 소양동   30747 ----------


 ---------- 2020-02-17 16:00:00 : 신동면   30748 ----------


 ---------- 2020-02-17 17:00:00 : 후평1동   30749 ----------


 ---------- 2020-02-18 05:00:00 : 약사명동   30750 ----------


 ---------- 2020-02-18 12:00:00 : 서  면   30751 ----------


 ---------- 2020-02-18 21:00:00 : 근화동   30753 ----------


 ---------- 2020-02-18 22:00:00 : 후평1동   30755 ----------


 ---------- 2020-02-19 07:00:00 : 약사명동   30757 ----------


 ---------- 2020-02-19 13:00:00 : 남산면   30758 ----------


 ---------- 2020-02-19 23:00:00 : 후평1동   30759 ----------


 ---------- 2020-02-20 07:00:00 : 강남동   30760 ----------


 ---------- 2020-02-20 11:00:00 : 근화동   30761 ----------


 ---------- 2020-02-20 14:00:00 : 신북읍   30762 ----------


 ---------- 2020-02-20 16:00:00 : 후평1동   30763 ----------


 ---------- 2020-02-20 19:00:00 : 석사동   30764 ----------


 ---------- 2020-02-20 21:00:00 : 후평1동   30765 ----------


 ---------- 2020-02-20 23:00:00 : 효자1동   30766 ----------


 ---------- 2020-02-21 08:00:00 : 신북읍   30768 ----------


 ---------- 2020-02-21 21:00:00 : 효자1동   30770 ----------


 ---------- 2020-02-21 23:00:00 : 석사동   30771 ----------


 ---------- 2020-02-22 05:00:00 : 후평1동   30772 ----------


 ---------- 2020-02-22 08:00:00 : 강남동   30773 ----------


 ---------- 2020-02-22 09:00:00 : 후평1동   30774 ----------


 ---------- 2020-02-22 22:00:00 : 퇴계동   30775 ----------


 ---------- 2020-02-23 00:00:00 : 효자1동   30776 ----------


 ---------- 2020-02-23 08:00:00 : 신북읍   30777 ----------


 ---------- 2020-02-23 21:00:00 : 근화동   30778 ----------


 ---------- 2020-02-24 08:00:00 : 신북읍   30779 ----------


 ---------- 2020-02-24 08:00:00 : 후평1동   30780 ----------


 ---------- 2020-02-24 12:00:00 : 남산면   30781 ----------


 ---------- 2020-02-24 13:00:00 : 남산면   30783 ----------


 ---------- 2020-02-24 17:00:00 : 동  면   30784 ----------


 ---------- 2020-02-24 18:00:00 : 석사동   30785 ----------


 ---------- 2020-02-25 10:00:00 : 소양동   30786 ----------


 ---------- 2020-02-25 11:00:00 : 동  면   30787 ----------


 ---------- 2020-02-25 18:00:00 : 퇴계동   30788 ----------


 ---------- 2020-02-26 11:00:00 : 퇴계동   30789 ----------


 ---------- 2020-02-26 14:00:00 : 퇴계동   30790 ----------


 ---------- 2020-02-26 15:00:00 : 석사동   30791 ----------


 ---------- 2020-02-26 18:00:00 : 석사동   30792 ----------


 ---------- 2020-02-26 21:00:00 : 사북면   30793 ----------


 ---------- 2020-02-27 02:00:00 : 강남동   30795 ----------


 ---------- 2020-02-27 05:00:00 : 효자1동   30796 ----------


 ---------- 2020-02-27 17:00:00 : 신동면   30797 ----------


 ---------- 2020-02-27 18:00:00 : 후평1동   30798 ----------


 ---------- 2020-02-28 14:00:00 : 효자1동   30799 ----------


 ---------- 2020-02-28 17:00:00 : 동  면   30800 ----------


 ---------- 2020-02-28 19:00:00 : 동산면   30801 ----------


 ---------- 2020-02-29 09:00:00 : 후평1동   30802 ----------


 ---------- 2020-02-29 11:00:00 : 북산면   30804 ----------


 ---------- 2020-02-29 12:00:00 : 조운동   30805 ----------


 ---------- 2020-02-29 13:00:00 : 북산면   30806 ----------


 ---------- 2020-02-29 16:00:00 : 강남동   30807 ----------


 ---------- 2020-02-29 17:00:00 : 남산면   30808 ----------


 ---------- 2020-02-29 19:00:00 : 후평1동   30809 ----------


 ---------- 2020-03-01 11:00:00 : 효자1동   30810 ----------


 ---------- 2020-03-01 19:00:00 : 동  면   30811 ----------


 ---------- 2020-03-02 00:00:00 : 강남동   30813 ----------


 ---------- 2020-03-02 17:00:00 : 석사동   30814 ----------


 ---------- 2020-03-03 14:00:00 : 신사우동   30815 ----------


 ---------- 2020-03-03 16:00:00 : 근화동   30816 ----------


 ---------- 2020-03-04 12:00:00 : 효자1동   30817 ----------


 ---------- 2020-03-04 13:00:00 : 남산면   30818 ----------


 ---------- 2020-03-04 19:00:00 : 석사동   30820 ----------


 ---------- 2020-03-04 21:00:00 : 신사우동   30822 ----------


 ---------- 2020-03-05 05:00:00 : 남산면   30824 ----------


 ---------- 2020-03-05 12:00:00 : 신동면   30825 ----------


 ---------- 2020-03-05 15:00:00 : 효자1동   30826 ----------


 ---------- 2020-03-06 04:00:00 : 약사명동   30827 ----------


 ---------- 2020-03-06 13:00:00 : 신동면   30828 ----------


 ---------- 2020-03-06 18:00:00 : 동산면   30829 ----------


 ---------- 2020-03-06 22:00:00 : 남산면   30831 ----------


 ---------- 2020-03-07 00:00:00 : 강남동   30833 ----------


 ---------- 2020-03-07 11:00:00 : 효자1동   30835 ----------


 ---------- 2020-03-08 10:00:00 : 후평1동   30836 ----------


 ---------- 2020-03-08 13:00:00 : 사북면   30837 ----------


 ---------- 2020-03-08 14:00:00 : 동  면   30838 ----------


 ---------- 2020-03-08 16:00:00 : 동산면   30840 ----------


 ---------- 2020-03-08 18:00:00 : 동  면   30842 ----------


 ---------- 2020-03-08 21:00:00 : 강남동   30843 ----------


 ---------- 2020-03-09 01:00:00 : 신사우동   30844 ----------


 ---------- 2020-03-09 14:00:00 : 후평1동   30845 ----------


 ---------- 2020-03-10 03:00:00 : 효자1동   30846 ----------


 ---------- 2020-03-10 10:00:00 : 서  면   30849 ----------


 ---------- 2020-03-10 14:00:00 : 효자1동   30850 ----------


 ---------- 2020-03-10 18:00:00 : 동  면   30851 ----------


 ---------- 2020-03-10 19:00:00 : 서  면   30852 ----------


 ---------- 2020-03-10 20:00:00 : 퇴계동   30853 ----------


 ---------- 2020-03-10 21:00:00 : 동내면   30854 ----------


 ---------- 2020-03-11 09:00:00 : 동내면   30855 ----------


 ---------- 2020-03-11 17:00:00 : 서  면   30857 ----------


 ---------- 2020-03-12 15:00:00 : 서  면   30858 ----------


 ---------- 2020-03-12 15:00:00 : 후평1동   30859 ----------


 ---------- 2020-03-12 17:00:00 : 석사동   30861 ----------


 ---------- 2020-03-13 08:00:00 : 효자1동   30862 ----------


 ---------- 2020-03-13 15:00:00 : 후평1동   30863 ----------


 ---------- 2020-03-13 16:00:00 : 강남동   30864 ----------


 ---------- 2020-03-13 21:00:00 : 근화동   30865 ----------


 ---------- 2020-03-13 23:00:00 : 석사동   30866 ----------


 ---------- 2020-03-14 00:00:00 : 효자1동   30867 ----------


 ---------- 2020-03-14 03:00:00 : 남산면   30868 ----------


 ---------- 2020-03-14 09:00:00 : 남산면   30869 ----------


 ---------- 2020-03-14 10:00:00 : 조운동   30871 ----------


 ---------- 2020-03-14 13:00:00 : 신사우동   30872 ----------


 ---------- 2020-03-15 09:00:00 : 동  면   30873 ----------


 ---------- 2020-03-15 12:00:00 : 동산면   30876 ----------


 ---------- 2020-03-15 14:00:00 : 석사동   30878 ----------


 ---------- 2020-03-15 18:00:00 : 퇴계동   30879 ----------


 ---------- 2020-03-16 10:00:00 : 강남동   30880 ----------


 ---------- 2020-03-16 13:00:00 : 소양동   30881 ----------


 ---------- 2020-03-16 15:00:00 : 사북면   30882 ----------


 ---------- 2020-03-16 17:00:00 : 동내면   30883 ----------


 ---------- 2020-03-17 09:00:00 : 사북면   30885 ----------


 ---------- 2020-03-17 16:00:00 : 효자1동   30886 ----------


 ---------- 2020-03-17 18:00:00 : 소양동   30887 ----------


 ---------- 2020-03-17 18:00:00 : 동산면   30888 ----------


 ---------- 2020-03-17 20:00:00 : 동산면   30889 ----------


 ---------- 2020-03-18 08:00:00 : 동  면   30890 ----------


 ---------- 2020-03-18 10:00:00 : 근화동   30892 ----------


 ---------- 2020-03-18 18:00:00 : 석사동   30893 ----------


 ---------- 2020-03-18 19:00:00 : 강남동   30894 ----------


 ---------- 2020-03-18 20:00:00 : 교  동   30895 ----------


 ---------- 2020-03-19 02:00:00 : 근화동   30896 ----------


 ---------- 2020-03-19 11:00:00 : 퇴계동   30897 ----------


 ---------- 2020-03-19 12:00:00 : 신북읍   30898 ----------


 ---------- 2020-03-19 13:00:00 : 효자1동   30899 ----------


 ---------- 2020-03-19 14:00:00 : 신동면   30900 ----------


 ---------- 2020-03-19 14:00:00 : 신북읍   30903 ----------


 ---------- 2020-03-19 19:00:00 : 소양동   30904 ----------


 ---------- 2020-03-20 13:00:00 : 서  면   30905 ----------


 ---------- 2020-03-20 14:00:00 : 동내면   30906 ----------


 ---------- 2020-03-20 14:00:00 : 후평1동   30907 ----------


 ---------- 2020-03-20 16:00:00 : 퇴계동   30908 ----------


 ---------- 2020-03-20 20:00:00 : 퇴계동   30909 ----------


 ---------- 2020-03-21 06:00:00 : 강남동   30910 ----------


 ---------- 2020-03-21 07:00:00 : 동내면   30911 ----------

 ---------- 2020-03-21 08:00:00 : 후평1동   30912 ----------


 ---------- 2020-03-21 11:00:00 : 후평1동   30913 ----------


 ---------- 2020-03-21 11:00:00 : 교  동   30914 ----------


 ---------- 2020-03-21 18:00:00 : 동  면   30915 ----------


 ---------- 2020-03-21 22:00:00 : 퇴계동   30916 ----------


 ---------- 2020-03-22 01:00:00 : 근화동   30917 ----------


 ---------- 2020-03-22 11:00:00 : 후평1동   30918 ----------


 ---------- 2020-03-22 15:00:00 : 동  면   30919 ----------


 ---------- 2020-03-22 16:00:00 : 근화동   30920 ----------


 ---------- 2020-03-22 17:00:00 : 서  면   30921 ----------


 ---------- 2020-03-23 09:00:00 : 서  면   30922 ----------


 ---------- 2020-03-23 12:00:00 : 사북면   30923 ----------


 ---------- 2020-03-23 15:00:00 : 근화동   30924 ----------


 ---------- 2020-03-23 19:00:00 : 퇴계동   30925 ----------


 ---------- 2020-03-24 09:00:00 : 후평1동   30926 ----------


 ---------- 2020-03-24 11:00:00 : 동내면   30927 ----------


 ---------- 2020-03-24 14:00:00 : 신사우동   30928 ----------


 ---------- 2020-03-25 09:00:00 : 남산면   30930 ----------


 ---------- 2020-03-25 13:00:00 : 동내면   30931 ----------


 ---------- 2020-03-25 21:00:00 : 신북읍   30932 ----------


 ---------- 2020-03-26 01:00:00 : 퇴계동   30933 ----------


 ---------- 2020-03-26 09:00:00 : 동  면   30934 ----------


 ---------- 2020-03-26 17:00:00 : 신북읍   30935 ----------


 ---------- 2020-03-27 17:00:00 : 남산면   30936 ----------


 ---------- 2020-03-28 01:00:00 : 약사명동   30937 ----------


 ---------- 2020-03-28 10:00:00 : 서  면   30939 ----------


 ---------- 2020-03-28 10:00:00 : 퇴계동   30940 ----------


 ---------- 2020-03-28 12:00:00 : 신동면   30941 ----------


 ---------- 2020-03-28 12:00:00 : 후평1동   30943 ----------


 ---------- 2020-03-28 17:00:00 : 동내면   30944 ----------


 ---------- 2020-03-28 17:00:00 : 퇴계동   30946 ----------


 ---------- 2020-03-28 21:00:00 : 동산면   30947 ----------


 ---------- 2020-03-29 04:00:00 : 동내면   30948 ----------


 ---------- 2020-03-29 08:00:00 : 퇴계동   30950 ----------


 ---------- 2020-03-29 13:00:00 : 서  면   30952 ----------


 ---------- 2020-03-29 17:00:00 : 신사우동   30954 ----------


 ---------- 2020-03-29 20:00:00 : 신동면   30955 ----------


 ---------- 2020-03-29 21:00:00 : 서  면   30956 ----------


 ---------- 2020-03-30 08:00:00 : 신사우동   30957 ----------


 ---------- 2020-03-30 12:00:00 : 서  면   30958 ----------


 ---------- 2020-03-30 14:00:00 : 동내면   30960 ----------


 ---------- 2020-03-30 16:00:00 : 신사우동   30961 ----------


 ---------- 2020-03-30 18:00:00 : 동  면   30962 ----------


 ---------- 2020-03-31 11:00:00 : 사북면   30963 ----------


 ---------- 2020-03-31 13:00:00 : 석사동   30964 ----------


 ---------- 2020-03-31 14:00:00 : 후평1동   30965 ----------


 ---------- 2020-03-31 23:00:00 : 근화동   30966 ----------


 ---------- 2020-04-01 12:00:00 : 남산면   30968 ----------


 ---------- 2020-04-01 15:00:00 : 남산면   30970 ----------


 ---------- 2020-04-01 15:00:00 : 조운동   30971 ----------


 ---------- 2020-04-01 18:00:00 : 강남동   30972 ----------


 ---------- 2020-04-02 12:00:00 : 북산면   30973 ----------


 ---------- 2020-04-02 13:00:00 : 조운동   30974 ----------


 ---------- 2020-04-02 18:00:00 : 퇴계동   30975 ----------


 ---------- 2020-04-02 20:00:00 : 신사우동   30976 ----------


 ---------- 2020-04-03 01:00:00 : 효자1동   30977 ----------


 ---------- 2020-04-03 14:00:00 : 효자1동   30978 ----------


 ---------- 2020-04-03 16:00:00 : 동  면   30979 ----------


 ---------- 2020-04-04 09:00:00 : 사북면   30980 ----------


 ---------- 2020-04-04 13:00:00 : 동내면   30981 ----------


 ---------- 2020-04-04 14:00:00 : 신북읍   30982 ----------


 ---------- 2020-04-04 17:00:00 : 효자1동   30984 ----------


 ---------- 2020-04-04 17:00:00 : 소양동   30985 ----------


 ---------- 2020-04-04 19:00:00 : 조운동   30986 ----------


 ---------- 2020-04-05 10:00:00 : 남산면   30988 ----------


 ---------- 2020-04-05 15:00:00 : 동내면   30989 ----------


 ---------- 2020-04-05 19:00:00 : 동내면   30990 ----------


 ---------- 2020-04-06 05:00:00 : 퇴계동   30991 ----------


 ---------- 2020-04-06 09:00:00 : 신사우동   30992 ----------


 ---------- 2020-04-06 15:00:00 : 효자1동   30993 ----------


 ---------- 2020-04-06 15:00:00 : 신사우동   30995 ----------


 ---------- 2020-04-06 15:00:00 : 퇴계동   30996 ----------


 ---------- 2020-04-06 17:00:00 : 신사우동   30997 ----------


 ---------- 2020-04-06 20:00:00 : 동  면   30998 ----------


 ---------- 2020-04-06 21:00:00 : 동  면   30999 ----------


 ---------- 2020-04-07 10:00:00 : 동내면   31000 ----------


 ---------- 2020-04-07 13:00:00 : 동내면   31001 ----------


 ---------- 2020-04-07 18:00:00 : 동내면   31004 ----------


 ---------- 2020-04-07 19:00:00 : 퇴계동   31005 ----------


 ---------- 2020-04-07 20:00:00 : 조운동   31006 ----------


 ---------- 2020-04-08 06:00:00 : 동내면   31007 ----------


 ---------- 2020-04-08 09:00:00 : 신북읍   31008 ----------


 ---------- 2020-04-08 15:00:00 : 강남동   31009 ----------


 ---------- 2020-04-08 16:00:00 : 근화동   31010 ----------


 ---------- 2020-04-08 18:00:00 : 동내면   31011 ----------


 ---------- 2020-04-08 23:00:00 : 후평1동   31012 ----------


 ---------- 2020-04-09 10:00:00 : 강남동   31013 ----------


 ---------- 2020-04-09 14:00:00 : 동내면   31014 ----------


 ---------- 2020-04-09 18:00:00 : 석사동   31015 ----------


 ---------- 2020-04-09 20:00:00 : 동내면   31017 ----------


 ---------- 2020-04-10 06:00:00 : 효자1동   31018 ----------


 ---------- 2020-04-10 06:00:00 : 근화동   31019 ----------


 ---------- 2020-04-10 08:00:00 : 퇴계동   31020 ----------


 ---------- 2020-04-10 12:00:00 : 석사동   31021 ----------


 ---------- 2020-04-10 13:00:00 : 남산면   31022 ----------


 ---------- 2020-04-11 12:00:00 : 강남동   31023 ----------


 ---------- 2020-04-11 12:00:00 : 동  면   31024 ----------


 ---------- 2020-04-11 15:00:00 : 서  면   31026 ----------


 ---------- 2020-04-11 18:00:00 : 신사우동   31030 ----------


 ---------- 2020-04-12 06:00:00 : 교  동   31031 ----------


 ---------- 2020-04-12 07:00:00 : 서  면   31032 ----------


 ---------- 2020-04-12 08:00:00 : 서  면   31033 ----------


 ---------- 2020-04-12 10:00:00 : 남산면   31034 ----------


 ---------- 2020-04-12 11:00:00 : 강남동   31035 ----------


 ---------- 2020-04-12 12:00:00 : 퇴계동   31037 ----------


 ---------- 2020-04-12 14:00:00 : 신사우동   31038 ----------


 ---------- 2020-04-12 15:00:00 : 북산면   31039 ----------


 ---------- 2020-04-13 08:00:00 : 퇴계동   31040 ----------


 ---------- 2020-04-13 13:00:00 : 근화동   31041 ----------


 ---------- 2020-04-13 16:00:00 : 서  면   31043 ----------


 ---------- 2020-04-13 17:00:00 : 석사동   31044 ----------


 ---------- 2020-04-13 17:00:00 : 강남동   31046 ----------


 ---------- 2020-04-13 19:00:00 : 남산면   31047 ----------


 ---------- 2020-04-13 21:00:00 : 동내면   31049 ----------


 ---------- 2020-04-13 22:00:00 : 강남동   31050 ----------


 ---------- 2020-04-14 11:00:00 : 동산면   31051 ----------


 ---------- 2020-04-14 15:00:00 : 근화동   31052 ----------


 ---------- 2020-04-14 17:00:00 : 퇴계동   31053 ----------


 ---------- 2020-04-15 12:00:00 : 사북면   31054 ----------


 ---------- 2020-04-15 15:00:00 : 동내면   31055 ----------


 ---------- 2020-04-15 17:00:00 : 석사동   31056 ----------


 ---------- 2020-04-15 17:00:00 : 서  면   31057 ----------


 ---------- 2020-04-15 19:00:00 : 남산면   31059 ----------


 ---------- 2020-04-16 12:00:00 : 석사동   31060 ----------


 ---------- 2020-04-16 12:00:00 : 남산면   31061 ----------


 ---------- 2020-04-16 12:00:00 : 신사우동   31063 ----------


 ---------- 2020-04-16 13:00:00 : 동내면   31064 ----------


 ---------- 2020-04-16 14:00:00 : 동  면   31066 ----------


 ---------- 2020-04-16 15:00:00 : 근화동   31067 ----------


 ---------- 2020-04-16 17:00:00 : 신북읍   31068 ----------


 ---------- 2020-04-16 18:00:00 : 후평1동   31069 ----------


 ---------- 2020-04-16 21:00:00 : 신동면   31071 ----------


 ---------- 2020-04-16 23:00:00 : 근화동   31072 ----------


 ---------- 2020-04-17 06:00:00 : 서  면   31073 ----------


 ---------- 2020-04-17 10:00:00 : 서  면   31074 ----------


 ---------- 2020-04-17 15:00:00 : 근화동   31076 ----------

 ---------- 2020-04-18 04:00:00 : 동내면   31077 ----------


 ---------- 2020-04-18 10:00:00 : 석사동   31078 ----------


 ---------- 2020-04-18 10:00:00 : 신사우동   31079 ----------


 ---------- 2020-04-18 11:00:00 : 남산면   31081 ----------


 ---------- 2020-04-18 14:00:00 : 후평1동   31082 ----------


 ---------- 2020-04-18 22:00:00 : 조운동   31084 ----------


 ---------- 2020-04-19 05:00:00 : 신사우동   31085 ----------


 ---------- 2020-04-19 10:00:00 : 동내면   31086 ----------


 ---------- 2020-04-19 13:00:00 : 서  면   31087 ----------


 ---------- 2020-04-19 14:00:00 : 후평1동   31088 ----------


 ---------- 2020-04-19 17:00:00 : 동산면   31089 ----------


 ---------- 2020-04-20 14:00:00 : 강남동   31090 ----------


 ---------- 2020-04-20 17:00:00 : 동산면   31091 ----------


 ---------- 2020-04-21 08:00:00 : 석사동   31094 ----------


 ---------- 2020-04-21 08:00:00 : 신사우동   31095 ----------


 ---------- 2020-04-21 11:00:00 : 남산면   31096 ----------


 ---------- 2020-04-21 13:00:00 : 조운동   31097 ----------


 ---------- 2020-04-21 14:00:00 : 효자1동   31098 ----------


 ---------- 2020-04-21 17:00:00 : 신사우동   31099 ----------


 ---------- 2020-04-21 18:00:00 : 석사동   31100 ----------


 ---------- 2020-04-22 08:00:00 : 퇴계동   31101 ----------


 ---------- 2020-04-22 11:00:00 : 신동면   31103 ----------


 ---------- 2020-04-22 14:00:00 : 북산면   31105 ----------


 ---------- 2020-04-22 16:00:00 : 석사동   31106 ----------


 ---------- 2020-04-22 16:00:00 : 남산면   31108 ----------


 ---------- 2020-04-22 20:00:00 : 효자1동   31109 ----------


 ---------- 2020-04-23 13:00:00 : 신북읍   31110 ----------


 ---------- 2020-04-23 14:00:00 : 퇴계동   31112 ----------


 ---------- 2020-04-24 10:00:00 : 신동면   31113 ----------


 ---------- 2020-04-24 11:00:00 : 서  면   31115 ----------


 ---------- 2020-04-24 14:00:00 : 남산면   31116 ----------


 ---------- 2020-04-24 14:00:00 : 퇴계동   31118 ----------


 ---------- 2020-04-24 15:00:00 : 남산면   31119 ----------


 ---------- 2020-04-24 16:00:00 : 신사우동   31120 ----------


 ---------- 2020-04-24 22:00:00 : 동산면   31121 ----------


 ---------- 2020-04-25 00:00:00 : 신사우동   31122 ----------


 ---------- 2020-04-25 06:00:00 : 후평1동   31123 ----------


 ---------- 2020-04-25 08:00:00 : 신동면   31124 ----------


 ---------- 2020-04-25 09:00:00 : 동  면   31125 ----------


 ---------- 2020-04-25 11:00:00 : 효자1동   31127 ----------


 ---------- 2020-04-26 11:00:00 : 동산면   31128 ----------


 ---------- 2020-04-26 13:00:00 : 동  면   31129 ----------


 ---------- 2020-04-26 14:00:00 : 강남동   31130 ----------


 ---------- 2020-04-26 14:00:00 : 동  면   31131 ----------


 ---------- 2020-04-26 16:00:00 : 강남동   31132 ----------


 ---------- 2020-04-27 11:00:00 : 후평1동   31133 ----------


 ---------- 2020-04-27 17:00:00 : 조운동   31134 ----------


 ---------- 2020-04-27 19:00:00 : 조운동   31135 ----------


 ---------- 2020-04-27 22:00:00 : 퇴계동   31137 ----------


 ---------- 2020-04-28 00:00:00 : 후평1동   31138 ----------


 ---------- 2020-04-28 12:00:00 : 후평1동   31139 ----------


 ---------- 2020-04-28 13:00:00 : 강남동   31141 ----------


 ---------- 2020-04-28 13:00:00 : 동내면   31142 ----------


 ---------- 2020-04-28 13:00:00 : 동  면   31145 ----------


 ---------- 2020-04-28 14:00:00 : 서  면   31147 ----------


 ---------- 2020-04-28 15:00:00 : 남산면   31149 ----------


 ---------- 2020-04-28 15:00:00 : 퇴계동   31150 ----------


 ---------- 2020-04-28 16:00:00 : 강남동   31153 ----------


 ---------- 2020-04-28 21:00:00 : 석사동   31154 ----------


 ---------- 2020-04-29 09:00:00 : 소양동   31155 ----------


 ---------- 2020-04-29 19:00:00 : 퇴계동   31156 ----------


 ---------- 2020-04-29 22:00:00 : 신동면   31158 ----------


 ---------- 2020-04-30 01:00:00 : 강남동   31159 ----------


 ---------- 2020-04-30 10:00:00 : 신북읍   31160 ----------


 ---------- 2020-04-30 19:00:00 : 신북읍   31161 ----------


 ---------- 2020-05-01 08:00:00 : 동내면   31162 ----------


 ---------- 2020-05-01 09:00:00 : 후평1동   31163 ----------


 ---------- 2020-05-01 13:00:00 : 석사동   31164 ----------


 ---------- 2020-05-01 14:00:00 : 서  면   31165 ----------


 ---------- 2020-05-01 14:00:00 : 근화동   31167 ----------


 ---------- 2020-05-01 14:00:00 : 동  면   31168 ----------


 ---------- 2020-05-01 15:00:00 : 동  면   31169 ----------


 ---------- 2020-05-01 17:00:00 : 동내면   31170 ----------


 ---------- 2020-05-01 18:00:00 : 동  면   31171 ----------


 ---------- 2020-05-01 19:00:00 : 근화동   31173 ----------


 ---------- 2020-05-01 19:00:00 : 소양동   31174 ----------


 ---------- 2020-05-02 10:00:00 : 퇴계동   31175 ----------


 ---------- 2020-05-02 12:00:00 : 석사동   31176 ----------


 ---------- 2020-05-02 13:00:00 : 석사동   31177 ----------


 ---------- 2020-05-02 15:00:00 : 신사우동   31178 ----------


 ---------- 2020-05-03 02:00:00 : 조운동   31179 ----------


 ---------- 2020-05-03 11:00:00 : 효자1동   31180 ----------


 ---------- 2020-05-03 12:00:00 : 강남동   31181 ----------


 ---------- 2020-05-03 12:00:00 : 남산면   31183 ----------


 ---------- 2020-05-03 12:00:00 : 북산면   31186 ----------


 ---------- 2020-05-03 14:00:00 : 신북읍   31187 ----------


 ---------- 2020-05-03 14:00:00 : 북산면   31188 ----------


 ---------- 2020-05-03 19:00:00 : 남  면   31189 ----------


 ---------- 2020-05-03 20:00:00 : 효자1동   31190 ----------


 ---------- 2020-05-03 21:00:00 : 신사우동   31191 ----------


 ---------- 2020-05-04 02:00:00 : 석사동   31192 ----------


 ---------- 2020-05-04 09:00:00 : 석사동   31193 ----------


 ---------- 2020-05-04 11:00:00 : 강남동   31194 ----------


 ---------- 2020-05-04 16:00:00 : 신북읍   31195 ----------


 ---------- 2020-05-04 17:00:00 : 신북읍   31196 ----------


 ---------- 2020-05-04 18:00:00 : 석사동   31197 ----------


 ---------- 2020-05-04 23:00:00 : 후평1동   31198 ----------


 ---------- 2020-05-05 01:00:00 : 후평1동   31199 ----------


 ---------- 2020-05-05 11:00:00 : 소양동   31200 ----------


 ---------- 2020-05-05 14:00:00 : 소양동   31201 ----------


 ---------- 2020-05-05 20:00:00 : 석사동   31203 ----------


 ---------- 2020-05-05 20:00:00 : 남산면   31204 ----------


 ---------- 2020-05-06 09:00:00 : 후평1동   31205 ----------


 ---------- 2020-05-06 10:00:00 : 소양동   31206 ----------


 ---------- 2020-05-06 16:00:00 : 신북읍   31207 ----------


 ---------- 2020-05-06 18:00:00 : 후평1동   31208 ----------


 ---------- 2020-05-06 18:00:00 : 교  동   31209 ----------


 ---------- 2020-05-06 23:00:00 : 소양동   31210 ----------


 ---------- 2020-05-06 23:00:00 : 조운동   31211 ----------


 ---------- 2020-05-07 00:00:00 : 조운동   31212 ----------


 ---------- 2020-05-07 07:00:00 : 후평1동   31213 ----------


 ---------- 2020-05-07 09:00:00 : 동  면   31214 ----------


 ---------- 2020-05-07 10:00:00 : 동내면   31215 ----------


 ---------- 2020-05-07 11:00:00 : 남  면   31216 ----------


 ---------- 2020-05-07 13:00:00 : 신북읍   31217 ----------


 ---------- 2020-05-07 16:00:00 : 후평1동   31218 ----------


 ---------- 2020-05-08 00:00:00 : 소양동   31219 ----------


 ---------- 2020-05-08 10:00:00 : 석사동   31220 ----------


 ---------- 2020-05-08 13:00:00 : 사북면   31221 ----------


 ---------- 2020-05-08 13:00:00 : 동산면   31222 ----------


 ---------- 2020-05-08 14:00:00 : 동내면   31223 ----------


 ---------- 2020-05-08 15:00:00 : 강남동   31224 ----------


 ---------- 2020-05-08 15:00:00 : 사북면   31225 ----------


 ---------- 2020-05-08 17:00:00 : 강남동   31226 ----------


 ---------- 2020-05-08 18:00:00 : 동  면   31228 ----------


 ---------- 2020-05-09 06:00:00 : 동내면   31229 ----------


 ---------- 2020-05-09 16:00:00 : 효자1동   31230 ----------


 ---------- 2020-05-09 21:00:00 : 남산면   31231 ----------


 ---------- 2020-05-09 23:00:00 : 석사동   31232 ----------


 ---------- 2020-05-10 00:00:00 : 남산면   31233 ----------


 ---------- 2020-05-10 05:00:00 : 약사명동   31235 ----------


 ---------- 2020-05-10 08:00:00 : 신사우동   31236 ----------


 ---------- 2020-05-10 09:00:00 : 소양동   31238 ----------


 ---------- 2020-05-10 22:00:00 : 석사동   31239 ----------


 ---------- 2020-05-10 23:00:00 : 동  면   31240 ----------


 ---------- 2020-05-11 17:00:00 : 동내면   31241 ----------

 ---------- 2020-05-12 08:00:00 : 석사동   31242 ----------


 ---------- 2020-05-12 08:00:00 : 서  면   31243 ----------


 ---------- 2020-05-12 08:00:00 : 동내면   31244 ----------


 ---------- 2020-05-12 09:00:00 : 동내면   31245 ----------


 ---------- 2020-05-12 19:00:00 : 소양동   31246 ----------


 ---------- 2020-05-13 11:00:00 : 효자1동   31247 ----------


 ---------- 2020-05-13 11:00:00 : 후평1동   31248 ----------


 ---------- 2020-05-13 14:00:00 : 후평1동   31249 ----------


 ---------- 2020-05-13 15:00:00 : 효자1동   31250 ----------


 ---------- 2020-05-13 16:00:00 : 강남동   31253 ----------


 ---------- 2020-05-13 22:00:00 : 석사동   31254 ----------


 ---------- 2020-05-13 22:00:00 : 강남동   31255 ----------


 ---------- 2020-05-14 11:00:00 : 신동면   31256 ----------


 ---------- 2020-05-14 18:00:00 : 동  면   31258 ----------


 ---------- 2020-05-15 04:00:00 : 소양동   31259 ----------


 ---------- 2020-05-15 05:00:00 : 동내면   31261 ----------


 ---------- 2020-05-15 11:00:00 : 후평1동   31262 ----------


 ---------- 2020-05-15 13:00:00 : 후평1동   31263 ----------


 ---------- 2020-05-15 14:00:00 : 동산면   31264 ----------


 ---------- 2020-05-15 15:00:00 : 효자1동   31266 ----------


 ---------- 2020-05-15 18:00:00 : 동  면   31267 ----------


 ---------- 2020-05-15 18:00:00 : 퇴계동   31268 ----------


 ---------- 2020-05-15 20:00:00 : 효자1동   31269 ----------


 ---------- 2020-05-15 20:00:00 : 소양동   31270 ----------


 ---------- 2020-05-15 23:00:00 : 동  면   31271 ----------


 ---------- 2020-05-16 09:00:00 : 신북읍   31272 ----------


 ---------- 2020-05-16 11:00:00 : 퇴계동   31273 ----------


 ---------- 2020-05-16 12:00:00 : 신사우동   31274 ----------


 ---------- 2020-05-16 13:00:00 : 동  면   31275 ----------


 ---------- 2020-05-16 14:00:00 : 남  면   31276 ----------


 ---------- 2020-05-16 14:00:00 : 퇴계동   31277 ----------


 ---------- 2020-05-16 15:00:00 : 신북읍   31278 ----------


 ---------- 2020-05-16 16:00:00 : 신북읍   31279 ----------


 ---------- 2020-05-16 17:00:00 : 신사우동   31280 ----------


 ---------- 2020-05-16 17:00:00 : 신북읍   31281 ----------


 ---------- 2020-05-16 22:00:00 : 동산면   31282 ----------


 ---------- 2020-05-17 04:00:00 : 동  면   31283 ----------


 ---------- 2020-05-17 07:00:00 : 교  동   31284 ----------


 ---------- 2020-05-17 10:00:00 : 교  동   31285 ----------


 ---------- 2020-05-17 11:00:00 : 효자1동   31286 ----------


 ---------- 2020-05-17 11:00:00 : 교  동   31287 ----------


 ---------- 2020-05-17 12:00:00 : 소양동   31288 ----------


 ---------- 2020-05-17 13:00:00 : 사북면   31289 ----------


 ---------- 2020-05-17 15:00:00 : 동내면   31290 ----------


 ---------- 2020-05-17 17:00:00 : 석사동   31292 ----------


 ---------- 2020-05-17 18:00:00 : 후평1동   31293 ----------


 ---------- 2020-05-17 21:00:00 : 동내면   31294 ----------


 ---------- 2020-05-18 04:00:00 : 퇴계동   31295 ----------


 ---------- 2020-05-18 08:00:00 : 동산면   31296 ----------


 ---------- 2020-05-18 11:00:00 : 신북읍   31297 ----------


 ---------- 2020-05-18 12:00:00 : 퇴계동   31298 ----------


 ---------- 2020-05-18 16:00:00 : 동  면   31299 ----------


 ---------- 2020-05-18 17:00:00 : 강남동   31300 ----------


 ---------- 2020-05-18 17:00:00 : 남  면   31301 ----------


 ---------- 2020-05-18 17:00:00 : 남산면   31302 ----------


 ---------- 2020-05-18 23:00:00 : 퇴계동   31303 ----------


 ---------- 2020-05-19 08:00:00 : 강남동   31305 ----------


 ---------- 2020-05-19 13:00:00 : 효자1동   31307 ----------


 ---------- 2020-05-19 18:00:00 : 서  면   31309 ----------


 ---------- 2020-05-19 18:00:00 : 소양동   31311 ----------


 ---------- 2020-05-20 01:00:00 : 근화동   31312 ----------


 ---------- 2020-05-20 12:00:00 : 동내면   31313 ----------


 ---------- 2020-05-20 16:00:00 : 퇴계동   31314 ----------


 ---------- 2020-05-20 20:00:00 : 후평1동   31315 ----------


 ---------- 2020-05-21 06:00:00 : 약사명동   31317 ----------


 ---------- 2020-05-21 14:00:00 : 근화동   31318 ----------


 ---------- 2020-05-21 18:00:00 : 효자1동   31319 ----------


 ---------- 2020-05-21 18:00:00 : 동산면   31320 ----------


 ---------- 2020-05-21 20:00:00 : 신사우동   31321 ----------


 ---------- 2020-05-22 11:00:00 : 강남동   31322 ----------


 ---------- 2020-05-22 11:00:00 : 후평1동   31323 ----------


 ---------- 2020-05-22 14:00:00 : 강남동   31324 ----------


 ---------- 2020-05-22 15:00:00 : 석사동   31325 ----------


 ---------- 2020-05-22 16:00:00 : 퇴계동   31326 ----------


 ---------- 2020-05-23 00:00:00 : 효자1동   31327 ----------


 ---------- 2020-05-23 08:00:00 : 신사우동   31328 ----------


 ---------- 2020-05-23 12:00:00 : 후평1동   31329 ----------


 ---------- 2020-05-23 14:00:00 : 동내면   31330 ----------


 ---------- 2020-05-23 17:00:00 : 효자1동   31331 ----------


 ---------- 2020-05-23 18:00:00 : 퇴계동   31332 ----------


 ---------- 2020-05-23 22:00:00 : 효자1동   31333 ----------


 ---------- 2020-05-23 23:00:00 : 신북읍   31334 ----------


 ---------- 2020-05-24 09:00:00 : 사북면   31336 ----------


 ---------- 2020-05-24 15:00:00 : 퇴계동   31338 ----------


 ---------- 2020-05-24 19:00:00 : 효자1동   31339 ----------


 ---------- 2020-05-24 23:00:00 : 석사동   31341 ----------


 ---------- 2020-05-24 23:00:00 : 소양동   31342 ----------


 ---------- 2020-05-25 08:00:00 : 사북면   31343 ----------


 ---------- 2020-05-25 10:00:00 : 신북읍   31344 ----------


 ---------- 2020-05-25 10:00:00 : 동  면   31345 ----------


 ---------- 2020-05-25 15:00:00 : 사북면   31346 ----------


 ---------- 2020-05-25 16:00:00 : 조운동   31347 ----------


 ---------- 2020-05-25 19:00:00 : 서  면   31348 ----------


 ---------- 2020-05-25 19:00:00 : 신사우동   31349 ----------


 ---------- 2020-05-25 21:00:00 : 강남동   31350 ----------


 ---------- 2020-05-25 23:00:00 : 퇴계동   31351 ----------


 ---------- 2020-05-26 01:00:00 : 신사우동   31352 ----------


 ---------- 2020-05-26 07:00:00 : 서  면   31353 ----------


 ---------- 2020-05-26 12:00:00 : 후평1동   31354 ----------


 ---------- 2020-05-26 13:00:00 : 남산면   31355 ----------


 ---------- 2020-05-26 18:00:00 : 동내면   31356 ----------


 ---------- 2020-05-27 08:00:00 : 퇴계동   31357 ----------


 ---------- 2020-05-27 11:00:00 : 남산면   31358 ----------


 ---------- 2020-05-27 14:00:00 : 동내면   31359 ----------


 ---------- 2020-05-27 14:00:00 : 후평1동   31360 ----------


 ---------- 2020-05-27 16:00:00 : 동내면   31361 ----------


 ---------- 2020-05-27 19:00:00 : 동내면   31362 ----------


 ---------- 2020-05-28 08:00:00 : 북산면   31365 ----------


 ---------- 2020-05-28 10:00:00 : 강남동   31366 ----------


 ---------- 2020-05-28 11:00:00 : 퇴계동   31367 ----------


 ---------- 2020-05-28 14:00:00 : 강남동   31368 ----------


 ---------- 2020-05-28 16:00:00 : 후평1동   31369 ----------


 ---------- 2020-05-28 18:00:00 : 후평1동   31370 ----------


 ---------- 2020-05-28 20:00:00 : 남산면   31371 ----------


 ---------- 2020-05-28 21:00:00 : 동  면   31372 ----------


 ---------- 2020-05-29 07:00:00 : 동  면   31373 ----------


 ---------- 2020-05-29 14:00:00 : 동내면   31374 ----------


 ---------- 2020-05-29 14:00:00 : 동  면   31376 ----------


 ---------- 2020-05-29 15:00:00 : 후평1동   31377 ----------


 ---------- 2020-05-29 16:00:00 : 후평1동   31378 ----------


 ---------- 2020-05-29 23:00:00 : 동  면   31380 ----------


 ---------- 2020-05-30 01:00:00 : 퇴계동   31381 ----------


 ---------- 2020-05-30 03:00:00 : 효자1동   31382 ----------


 ---------- 2020-05-30 10:00:00 : 북산면   31383 ----------


 ---------- 2020-05-30 15:00:00 : 남산면   31385 ----------


 ---------- 2020-05-30 19:00:00 : 소양동   31386 ----------


 ---------- 2020-05-30 20:00:00 : 효자1동   31388 ----------


 ---------- 2020-05-31 00:00:00 : 소양동   31389 ----------


 ---------- 2020-05-31 07:00:00 : 퇴계동   31390 ----------


 ---------- 2020-05-31 08:00:00 : 석사동   31391 ----------


 ---------- 2020-05-31 11:00:00 : 동  면   31392 ----------


 ---------- 2020-05-31 13:00:00 : 강남동   31394 ----------


 ---------- 2020-05-31 14:00:00 : 신동면   31395 ----------


 ---------- 2020-05-31 16:00:00 : 동  면   31396 ----------


 ---------- 2020-05-31 18:00:00 : 신사우동   31397 ----------


 ---------- 2020-05-31 19:00:00 : 신북읍   31398 ----------

 ---------- 2020-06-01 08:00:00 : 신북읍   31399 ----------


 ---------- 2020-06-01 09:00:00 : 근화동   31400 ----------


 ---------- 2020-06-01 09:00:00 : 퇴계동   31401 ----------


 ---------- 2020-06-01 17:00:00 : 신북읍   31402 ----------


 ---------- 2020-06-01 18:00:00 : 동산면   31403 ----------


 ---------- 2020-06-01 23:00:00 : 후평1동   31404 ----------


 ---------- 2020-06-02 00:00:00 : 신사우동   31405 ----------


 ---------- 2020-06-02 02:00:00 : 후평1동   31406 ----------


 ---------- 2020-06-02 09:00:00 : 남산면   31407 ----------


 ---------- 2020-06-02 14:00:00 : 동  면   31408 ----------


 ---------- 2020-06-03 07:00:00 : 서  면   31409 ----------


 ---------- 2020-06-03 07:00:00 : 동내면   31411 ----------


 ---------- 2020-06-03 09:00:00 : 동  면   31412 ----------


 ---------- 2020-06-03 12:00:00 : 북산면   31413 ----------


 ---------- 2020-06-03 13:00:00 : 후평1동   31414 ----------


 ---------- 2020-06-03 18:00:00 : 효자1동   31415 ----------


 ---------- 2020-06-03 22:00:00 : 강남동   31416 ----------


 ---------- 2020-06-04 00:00:00 : 석사동   31417 ----------


 ---------- 2020-06-04 01:00:00 : 신사우동   31418 ----------


 ---------- 2020-06-04 06:00:00 : 신사우동   31419 ----------


 ---------- 2020-06-04 10:00:00 : 서  면   31422 ----------


 ---------- 2020-06-04 11:00:00 : 석사동   31423 ----------


 ---------- 2020-06-04 11:00:00 : 서  면   31424 ----------


 ---------- 2020-06-04 11:00:00 : 동  면   31425 ----------


 ---------- 2020-06-04 16:00:00 : 후평1동   31426 ----------


 ---------- 2020-06-04 19:00:00 : 신사우동   31427 ----------


 ---------- 2020-06-04 21:00:00 : 서  면   31429 ----------


 ---------- 2020-06-05 00:00:00 : 신북읍   31430 ----------


 ---------- 2020-06-05 09:00:00 : 동  면   31431 ----------


 ---------- 2020-06-05 14:00:00 : 남산면   31432 ----------


 ---------- 2020-06-05 14:00:00 : 동  면   31433 ----------


 ---------- 2020-06-05 14:00:00 : 퇴계동   31434 ----------


 ---------- 2020-06-05 16:00:00 : 동  면   31435 ----------


 ---------- 2020-06-05 20:00:00 : 동내면   31436 ----------


 ---------- 2020-06-05 23:00:00 : 퇴계동   31439 ----------


 ---------- 2020-06-06 00:00:00 : 석사동   31441 ----------


 ---------- 2020-06-06 02:00:00 : 동내면   31442 ----------


 ---------- 2020-06-06 09:00:00 : 강남동   31443 ----------


 ---------- 2020-06-06 09:00:00 : 서  면   31444 ----------


 ---------- 2020-06-06 09:00:00 : 사북면   31445 ----------


 ---------- 2020-06-06 11:00:00 : 남산면   31447 ----------


 ---------- 2020-06-06 19:00:00 : 소양동   31448 ----------


 ---------- 2020-06-06 22:00:00 : 효자1동   31449 ----------


 ---------- 2020-06-06 22:00:00 : 후평1동   31450 ----------


 ---------- 2020-06-07 13:00:00 : 동산면   31451 ----------


 ---------- 2020-06-07 14:00:00 : 강남동   31452 ----------


 ---------- 2020-06-07 14:00:00 : 신북읍   31454 ----------


 ---------- 2020-06-07 16:00:00 : 강남동   31455 ----------


 ---------- 2020-06-07 22:00:00 : 근화동   31456 ----------


 ---------- 2020-06-08 08:00:00 : 동  면   31457 ----------


 ---------- 2020-06-08 09:00:00 : 동내면   31458 ----------


 ---------- 2020-06-08 10:00:00 : 사북면   31459 ----------


 ---------- 2020-06-08 10:00:00 : 신사우동   31460 ----------


 ---------- 2020-06-08 12:00:00 : 효자1동   31462 ----------


 ---------- 2020-06-08 13:00:00 : 소양동   31463 ----------


 ---------- 2020-06-08 14:00:00 : 서  면   31464 ----------


 ---------- 2020-06-08 18:00:00 : 강남동   31465 ----------


 ---------- 2020-06-08 23:00:00 : 효자1동   31466 ----------


 ---------- 2020-06-09 00:00:00 : 강남동   31467 ----------


 ---------- 2020-06-09 12:00:00 : 퇴계동   31468 ----------


 ---------- 2020-06-09 13:00:00 : 강남동   31470 ----------


 ---------- 2020-06-09 14:00:00 : 후평1동   31471 ----------


 ---------- 2020-06-09 16:00:00 : 신사우동   31472 ----------


 ---------- 2020-06-09 17:00:00 : 동  면   31473 ----------


 ---------- 2020-06-09 20:00:00 : 동  면   31474 ----------


 ---------- 2020-06-09 20:00:00 : 조운동   31475 ----------


 ---------- 2020-06-09 23:00:00 : 퇴계동   31476 ----------


 ---------- 2020-06-10 07:00:00 : 근화동   31477 ----------


 ---------- 2020-06-10 09:00:00 : 동내면   31478 ----------


 ---------- 2020-06-10 11:00:00 : 신동면   31480 ----------


 ---------- 2020-06-10 12:00:00 : 퇴계동   31481 ----------


 ---------- 2020-06-10 13:00:00 : 동  면   31482 ----------


 ---------- 2020-06-10 17:00:00 : 효자1동   31483 ----------


 ---------- 2020-06-10 17:00:00 : 퇴계동   31484 ----------


 ---------- 2020-06-10 19:00:00 : 퇴계동   31486 ----------


 ---------- 2020-06-10 20:00:00 : 동  면   31487 ----------


 ---------- 2020-06-11 04:00:00 : 신사우동   31489 ----------


 ---------- 2020-06-11 08:00:00 : 동  면   31490 ----------


 ---------- 2020-06-11 13:00:00 : 동산면   31491 ----------


 ---------- 2020-06-11 14:00:00 : 신북읍   31492 ----------


 ---------- 2020-06-11 19:00:00 : 석사동   31493 ----------


 ---------- 2020-06-11 23:00:00 : 퇴계동   31494 ----------


 ---------- 2020-06-12 01:00:00 : 석사동   31495 ----------


 ---------- 2020-06-12 10:00:00 : 남산면   31496 ----------


 ---------- 2020-06-12 10:00:00 : 소양동   31497 ----------


 ---------- 2020-06-12 11:00:00 : 석사동   31498 ----------


 ---------- 2020-06-12 11:00:00 : 소양동   31499 ----------


 ---------- 2020-06-12 13:00:00 : 강남동   31500 ----------


 ---------- 2020-06-12 13:00:00 : 효자1동   31502 ----------


 ---------- 2020-06-12 14:00:00 : 북산면   31503 ----------


 ---------- 2020-06-12 15:00:00 : 남산면   31504 ----------


 ---------- 2020-06-12 15:00:00 : 근화동   31505 ----------


 ---------- 2020-06-12 16:00:00 : 서  면   31506 ----------


 ---------- 2020-06-12 17:00:00 : 동  면   31507 ----------


 ---------- 2020-06-12 18:00:00 : 효자1동   31508 ----------


 ---------- 2020-06-12 22:00:00 : 교  동   31509 ----------


 ---------- 2020-06-13 15:00:00 : 동  면   31510 ----------


 ---------- 2020-06-13 18:00:00 : 신북읍   31511 ----------


 ---------- 2020-06-13 20:00:00 : 석사동   31514 ----------


 ---------- 2020-06-13 20:00:00 : 동내면   31516 ----------


 ---------- 2020-06-14 09:00:00 : 동내면   31517 ----------


 ---------- 2020-06-14 10:00:00 : 석사동   31518 ----------


 ---------- 2020-06-14 11:00:00 : 신동면   31521 ----------


 ---------- 2020-06-14 11:00:00 : 서  면   31524 ----------


 ---------- 2020-06-14 11:00:00 : 근화동   31526 ----------


 ---------- 2020-06-14 12:00:00 : 효자1동   31527 ----------


 ---------- 2020-06-14 16:00:00 : 효자1동   31528 ----------


 ---------- 2020-06-14 16:00:00 : 신사우동   31529 ----------


 ---------- 2020-06-14 17:00:00 : 동  면   31530 ----------


 ---------- 2020-06-14 19:00:00 : 효자1동   31531 ----------


 ---------- 2020-06-15 07:00:00 : 서  면   31532 ----------


 ---------- 2020-06-15 09:00:00 : 서  면   31533 ----------


 ---------- 2020-06-15 09:00:00 : 퇴계동   31534 ----------


 ---------- 2020-06-15 10:00:00 : 강남동   31535 ----------


 ---------- 2020-06-15 12:00:00 : 석사동   31536 ----------


 ---------- 2020-06-15 13:00:00 : 신북읍   31537 ----------


 ---------- 2020-06-15 14:00:00 : 퇴계동   31538 ----------


 ---------- 2020-06-15 15:00:00 : 동산면   31539 ----------


 ---------- 2020-06-15 17:00:00 : 효자1동   31540 ----------


 ---------- 2020-06-15 18:00:00 : 남산면   31541 ----------


 ---------- 2020-06-15 18:00:00 : 근화동   31543 ----------


 ---------- 2020-06-16 00:00:00 : 후평1동   31544 ----------


 ---------- 2020-06-16 02:00:00 : 근화동   31545 ----------


 ---------- 2020-06-16 08:00:00 : 효자1동   31546 ----------


 ---------- 2020-06-16 09:00:00 : 서  면   31547 ----------


 ---------- 2020-06-16 10:00:00 : 동내면   31548 ----------


 ---------- 2020-06-16 10:00:00 : 동  면   31549 ----------


 ---------- 2020-06-16 13:00:00 : 신북읍   31550 ----------


 ---------- 2020-06-16 20:00:00 : 동  면   31551 ----------


 ---------- 2020-06-16 21:00:00 : 서  면   31552 ----------


 ---------- 2020-06-17 04:00:00 : 서  면   31553 ----------


 ---------- 2020-06-17 08:00:00 : 신북읍   31554 ----------


 ---------- 2020-06-17 09:00:00 : 신동면   31555 ----------


 ---------- 2020-06-17 11:00:00 : 소양동   31556 ----------


 ---------- 2020-06-17 13:00:00 : 북산면   31557 ----------


 ---------- 2020-06-17 14:00:00 : 효자1동   31559 ----------

 ---------- 2020-06-17 18:00:00 : 신사우동   31560 ----------


 ---------- 2020-06-17 22:00:00 : 퇴계동   31561 ----------


 ---------- 2020-06-18 04:00:00 : 강남동   31562 ----------


 ---------- 2020-06-18 11:00:00 : 동내면   31563 ----------


 ---------- 2020-06-18 11:00:00 : 퇴계동   31564 ----------


 ---------- 2020-06-18 12:00:00 : 석사동   31565 ----------


 ---------- 2020-06-18 13:00:00 : 신동면   31567 ----------


 ---------- 2020-06-18 14:00:00 : 동내면   31568 ----------


 ---------- 2020-06-18 14:00:00 : 신북읍   31569 ----------


 ---------- 2020-06-18 16:00:00 : 동내면   31570 ----------


 ---------- 2020-06-18 17:00:00 : 강남동   31571 ----------


 ---------- 2020-06-19 09:00:00 : 효자1동   31572 ----------


 ---------- 2020-06-19 10:00:00 : 퇴계동   31574 ----------


 ---------- 2020-06-19 11:00:00 : 신동면   31575 ----------


 ---------- 2020-06-19 12:00:00 : 석사동   31576 ----------


 ---------- 2020-06-19 14:00:00 : 석사동   31577 ----------


 ---------- 2020-06-19 15:00:00 : 동내면   31578 ----------


 ---------- 2020-06-19 16:00:00 : 석사동   31579 ----------


 ---------- 2020-06-19 17:00:00 : 신북읍   31580 ----------


 ---------- 2020-06-19 19:00:00 : 약사명동   31582 ----------


 ---------- 2020-06-19 19:00:00 : 퇴계동   31583 ----------


 ---------- 2020-06-19 20:00:00 : 근화동   31584 ----------


 ---------- 2020-06-19 20:00:00 : 동  면   31585 ----------


 ---------- 2020-06-19 22:00:00 : 강남동   31586 ----------


 ---------- 2020-06-19 22:00:00 : 퇴계동   31587 ----------


 ---------- 2020-06-20 00:00:00 : 후평1동   31588 ----------


 ---------- 2020-06-20 09:00:00 : 신사우동   31590 ----------


 ---------- 2020-06-20 10:00:00 : 신사우동   31591 ----------


 ---------- 2020-06-20 11:00:00 : 효자1동   31592 ----------


 ---------- 2020-06-20 11:00:00 : 동  면   31593 ----------


 ---------- 2020-06-20 13:00:00 : 동산면   31594 ----------


 ---------- 2020-06-20 14:00:00 : 강남동   31595 ----------


 ---------- 2020-06-20 14:00:00 : 동  면   31596 ----------


 ---------- 2020-06-20 15:00:00 : 남산면   31597 ----------


 ---------- 2020-06-20 16:00:00 : 신사우동   31598 ----------


 ---------- 2020-06-20 18:00:00 : 남  면   31599 ----------


 ---------- 2020-06-20 18:00:00 : 효자1동   31600 ----------


 ---------- 2020-06-20 18:00:00 : 동  면   31601 ----------


 ---------- 2020-06-20 22:00:00 : 강남동   31602 ----------


 ---------- 2020-06-21 01:00:00 : 서  면   31604 ----------


 ---------- 2020-06-21 01:00:00 : 후평1동   31605 ----------


 ---------- 2020-06-21 08:00:00 : 동내면   31606 ----------


 ---------- 2020-06-21 08:00:00 : 후평1동   31607 ----------


 ---------- 2020-06-21 10:00:00 : 사북면   31608 ----------


 ---------- 2020-06-21 11:00:00 : 퇴계동   31609 ----------


 ---------- 2020-06-21 13:00:00 : 석사동   31610 ----------


 ---------- 2020-06-21 13:00:00 : 강남동   31611 ----------


 ---------- 2020-06-21 14:00:00 : 동  면   31612 ----------


 ---------- 2020-06-21 16:00:00 : 소양동   31614 ----------


 ---------- 2020-06-21 18:00:00 : 동내면   31615 ----------


 ---------- 2020-06-21 19:00:00 : 동  면   31616 ----------


 ---------- 2020-06-22 08:00:00 : 동내면   31617 ----------


 ---------- 2020-06-22 09:00:00 : 소양동   31618 ----------


 ---------- 2020-06-22 13:00:00 : 동산면   31619 ----------


 ---------- 2020-06-22 14:00:00 : 석사동   31621 ----------


 ---------- 2020-06-22 14:00:00 : 강남동   31622 ----------


 ---------- 2020-06-22 16:00:00 : 동  면   31623 ----------


 ---------- 2020-06-23 03:00:00 : 근화동   31624 ----------


 ---------- 2020-06-23 10:00:00 : 후평1동   31625 ----------


 ---------- 2020-06-23 12:00:00 : 남  면   31626 ----------


 ---------- 2020-06-23 15:00:00 : 석사동   31627 ----------


 ---------- 2020-06-23 17:00:00 : 동내면   31628 ----------


 ---------- 2020-06-23 17:00:00 : 효자1동   31629 ----------


 ---------- 2020-06-24 06:00:00 : 석사동   31630 ----------


 ---------- 2020-06-24 08:00:00 : 사북면   31632 ----------


 ---------- 2020-06-24 08:00:00 : 신사우동   31633 ----------


 ---------- 2020-06-24 09:00:00 : 석사동   31634 ----------


 ---------- 2020-06-24 11:00:00 : 신북읍   31635 ----------


 ---------- 2020-06-24 12:00:00 : 동내면   31636 ----------


 ---------- 2020-06-24 14:00:00 : 동  면   31637 ----------


 ---------- 2020-06-24 17:00:00 : 동내면   31638 ----------


 ---------- 2020-06-24 23:00:00 : 강남동   31639 ----------


 ---------- 2020-06-25 07:00:00 : 신동면   31640 ----------


 ---------- 2020-06-25 08:00:00 : 석사동   31641 ----------


 ---------- 2020-06-25 09:00:00 : 후평1동   31643 ----------


 ---------- 2020-06-25 13:00:00 : 남산면   31644 ----------


 ---------- 2020-06-25 13:00:00 : 후평1동   31645 ----------


 ---------- 2020-06-25 14:00:00 : 조운동   31646 ----------


 ---------- 2020-06-25 16:00:00 : 소양동   31647 ----------


 ---------- 2020-06-25 17:00:00 : 동  면   31648 ----------


 ---------- 2020-06-26 10:00:00 : 동  면   31649 ----------


 ---------- 2020-06-26 12:00:00 : 동내면   31650 ----------


 ---------- 2020-06-26 13:00:00 : 동내면   31651 ----------


 ---------- 2020-06-26 14:00:00 : 사북면   31653 ----------


 ---------- 2020-06-26 15:00:00 : 퇴계동   31654 ----------


 ---------- 2020-06-26 16:00:00 : 서  면   31655 ----------


 ---------- 2020-06-26 17:00:00 : 석사동   31656 ----------


 ---------- 2020-06-26 17:00:00 : 서  면   31657 ----------


 ---------- 2020-06-26 17:00:00 : 동내면   31658 ----------


 ---------- 2020-06-26 17:00:00 : 남산면   31659 ----------


 ---------- 2020-06-26 20:00:00 : 퇴계동   31660 ----------


 ---------- 2020-06-27 04:00:00 : 신사우동   31661 ----------


 ---------- 2020-06-27 09:00:00 : 동산면   31662 ----------


 ---------- 2020-06-27 10:00:00 : 강남동   31663 ----------


 ---------- 2020-06-27 17:00:00 : 신북읍   31664 ----------


 ---------- 2020-06-27 17:00:00 : 소양동   31665 ----------


 ---------- 2020-06-27 19:00:00 : 동산면   31667 ----------


 ---------- 2020-06-27 20:00:00 : 석사동   31668 ----------


 ---------- 2020-06-27 20:00:00 : 소양동   31669 ----------


 ---------- 2020-06-27 21:00:00 : 퇴계동   31670 ----------


 ---------- 2020-06-27 22:00:00 : 신사우동   31671 ----------


 ---------- 2020-06-28 05:00:00 : 후평1동   31672 ----------


 ---------- 2020-06-28 08:00:00 : 남산면   31673 ----------


 ---------- 2020-06-28 10:00:00 : 조운동   31674 ----------


 ---------- 2020-06-28 14:00:00 : 서  면   31675 ----------


 ---------- 2020-06-28 16:00:00 : 남  면   31676 ----------


 ---------- 2020-06-28 16:00:00 : 퇴계동   31677 ----------


 ---------- 2020-06-29 09:00:00 : 남산면   31678 ----------


 ---------- 2020-06-29 09:00:00 : 신북읍   31679 ----------


 ---------- 2020-06-29 10:00:00 : 강남동   31680 ----------


 ---------- 2020-06-29 10:00:00 : 신북읍   31681 ----------


 ---------- 2020-06-29 10:00:00 : 후평1동   31682 ----------


 ---------- 2020-06-29 14:00:00 : 석사동   31683 ----------


 ---------- 2020-06-29 15:00:00 : 동내면   31684 ----------


 ---------- 2020-06-29 18:00:00 : 서  면   31686 ----------


 ---------- 2020-06-29 18:00:00 : 동  면   31687 ----------


 ---------- 2020-06-30 07:00:00 : 북산면   31688 ----------


 ---------- 2020-06-30 10:00:00 : 근화동   31689 ----------


 ---------- 2020-06-30 11:00:00 : 동내면   31690 ----------


 ---------- 2020-06-30 12:00:00 : 신동면   31691 ----------


 ---------- 2020-06-30 12:00:00 : 퇴계동   31692 ----------


 ---------- 2020-06-30 13:00:00 : 강남동   31693 ----------


 ---------- 2020-06-30 13:00:00 : 남산면   31694 ----------


 ---------- 2020-06-30 13:00:00 : 신사우동   31695 ----------


 ---------- 2020-06-30 13:00:00 : 퇴계동   31696 ----------


 ---------- 2020-06-30 14:00:00 : 동내면   31697 ----------


 ---------- 2020-06-30 14:00:00 : 효자1동   31698 ----------


 ---------- 2020-06-30 15:00:00 : 효자1동   31699 ----------


 ---------- 2020-07-01 08:00:00 : 동산면   31700 ----------


 ---------- 2020-07-01 10:00:00 : 신사우동   31701 ----------


 ---------- 2020-07-01 11:00:00 : 강남동   31702 ----------


 ---------- 2020-07-01 13:00:00 : 효자1동   31703 ----------


 ---------- 2020-07-01 15:00:00 : 신동면   31704 ----------


 ---------- 2020-07-01 16:00:00 : 남산면   31705 ----------


 ---------- 2020-07-01 17:00:00 : 동내면   31706 ----------


 ---------- 2020-07-01 20:00:00 : 퇴계동   31707 ----------

 ---------- 2020-07-02 02:00:00 : 신사우동   31708 ----------


 ---------- 2020-07-02 07:00:00 : 석사동   31709 ----------


 ---------- 2020-07-02 09:00:00 : 신동면   31710 ----------


 ---------- 2020-07-02 09:00:00 : 동내면   31711 ----------


 ---------- 2020-07-02 10:00:00 : 퇴계동   31712 ----------


 ---------- 2020-07-02 13:00:00 : 남산면   31713 ----------


 ---------- 2020-07-02 14:00:00 : 동내면   31714 ----------


 ---------- 2020-07-02 16:00:00 : 강남동   31715 ----------


 ---------- 2020-07-02 16:00:00 : 퇴계동   31716 ----------


 ---------- 2020-07-03 05:00:00 : 퇴계동   31717 ----------


 ---------- 2020-07-03 08:00:00 : 동산면   31718 ----------


 ---------- 2020-07-03 09:00:00 : 소양동   31719 ----------


 ---------- 2020-07-03 10:00:00 : 남산면   31720 ----------


 ---------- 2020-07-03 12:00:00 : 신사우동   31721 ----------


 ---------- 2020-07-03 14:00:00 : 동내면   31722 ----------


 ---------- 2020-07-03 17:00:00 : 동  면   31723 ----------


 ---------- 2020-07-04 00:00:00 : 동내면   31724 ----------


 ---------- 2020-07-04 01:00:00 : 퇴계동   31725 ----------


 ---------- 2020-07-04 10:00:00 : 퇴계동   31726 ----------


 ---------- 2020-07-04 12:00:00 : 석사동   31727 ----------


 ---------- 2020-07-04 12:00:00 : 남산면   31728 ----------


 ---------- 2020-07-04 12:00:00 : 소양동   31729 ----------


 ---------- 2020-07-04 15:00:00 : 남  면   31733 ----------


 ---------- 2020-07-04 15:00:00 : 동산면   31734 ----------


 ---------- 2020-07-04 16:00:00 : 남산면   31735 ----------


 ---------- 2020-07-04 16:00:00 : 동  면   31736 ----------


 ---------- 2020-07-05 02:00:00 : 퇴계동   31737 ----------


 ---------- 2020-07-05 05:00:00 : 소양동   31738 ----------


 ---------- 2020-07-05 09:00:00 : 신동면   31739 ----------


 ---------- 2020-07-05 11:00:00 : 강남동   31740 ----------


 ---------- 2020-07-05 12:00:00 : 신동면   31742 ----------


 ---------- 2020-07-05 12:00:00 : 강남동   31743 ----------


 ---------- 2020-07-05 12:00:00 : 신북읍   31744 ----------


 ---------- 2020-07-05 13:00:00 : 남산면   31745 ----------


 ---------- 2020-07-05 17:00:00 : 후평1동   31746 ----------


 ---------- 2020-07-05 20:00:00 : 남산면   31747 ----------


 ---------- 2020-07-05 21:00:00 : 교  동   31749 ----------


 ---------- 2020-07-06 09:00:00 : 소양동   31750 ----------


 ---------- 2020-07-06 10:00:00 : 효자1동   31751 ----------


 ---------- 2020-07-06 11:00:00 : 동  면   31752 ----------


 ---------- 2020-07-06 11:00:00 : 동산면   31753 ----------


 ---------- 2020-07-06 14:00:00 : 근화동   31754 ----------


 ---------- 2020-07-06 16:00:00 : 신동면   31755 ----------


 ---------- 2020-07-06 16:00:00 : 신북읍   31756 ----------


 ---------- 2020-07-06 22:00:00 : 강남동   31757 ----------


 ---------- 2020-07-07 07:00:00 : 후평1동   31758 ----------


 ---------- 2020-07-07 08:00:00 : 서  면   31759 ----------


 ---------- 2020-07-07 09:00:00 : 후평1동   31760 ----------


 ---------- 2020-07-07 09:00:00 : 퇴계동   31761 ----------


 ---------- 2020-07-07 10:00:00 : 신동면   31762 ----------


 ---------- 2020-07-07 12:00:00 : 후평1동   31763 ----------


 ---------- 2020-07-07 13:00:00 : 강남동   31764 ----------


 ---------- 2020-07-07 13:00:00 : 퇴계동   31765 ----------


 ---------- 2020-07-07 16:00:00 : 신동면   31766 ----------


 ---------- 2020-07-07 16:00:00 : 사북면   31768 ----------


 ---------- 2020-07-07 16:00:00 : 동  면   31769 ----------


 ---------- 2020-07-07 19:00:00 : 동내면   31770 ----------


 ---------- 2020-07-08 01:00:00 : 서  면   31771 ----------


 ---------- 2020-07-08 02:00:00 : 신북읍   31773 ----------


 ---------- 2020-07-08 07:00:00 : 동내면   31774 ----------


 ---------- 2020-07-08 07:00:00 : 신사우동   31775 ----------


 ---------- 2020-07-08 08:00:00 : 동  면   31776 ----------


 ---------- 2020-07-08 10:00:00 : 후평1동   31777 ----------


 ---------- 2020-07-08 11:00:00 : 서  면   31778 ----------


 ---------- 2020-07-08 11:00:00 : 동산면   31779 ----------


 ---------- 2020-07-08 13:00:00 : 석사동   31780 ----------


 ---------- 2020-07-08 13:00:00 : 근화동   31781 ----------


 ---------- 2020-07-08 14:00:00 : 남  면   31782 ----------


 ---------- 2020-07-08 15:00:00 : 강남동   31783 ----------


 ---------- 2020-07-08 15:00:00 : 동내면   31784 ----------


 ---------- 2020-07-08 15:00:00 : 남산면   31785 ----------


 ---------- 2020-07-08 19:00:00 : 신사우동   31786 ----------


 ---------- 2020-07-09 01:00:00 : 동내면   31787 ----------


 ---------- 2020-07-09 07:00:00 : 동내면   31788 ----------


 ---------- 2020-07-09 09:00:00 : 동산면   31789 ----------


 ---------- 2020-07-09 11:00:00 : 후평1동   31790 ----------


 ---------- 2020-07-09 12:00:00 : 석사동   31791 ----------


 ---------- 2020-07-09 13:00:00 : 강남동   31792 ----------


 ---------- 2020-07-09 13:00:00 : 효자1동   31793 ----------


 ---------- 2020-07-09 13:00:00 : 퇴계동   31794 ----------


 ---------- 2020-07-09 14:00:00 : 효자1동   31795 ----------


 ---------- 2020-07-09 15:00:00 : 동내면   31796 ----------


 ---------- 2020-07-09 15:00:00 : 소양동   31797 ----------


 ---------- 2020-07-09 16:00:00 : 동내면   31798 ----------


 ---------- 2020-07-09 16:00:00 : 효자1동   31800 ----------


 ---------- 2020-07-09 23:00:00 : 신사우동   31801 ----------


 ---------- 2020-07-10 07:00:00 : 사북면   31802 ----------


 ---------- 2020-07-10 09:00:00 : 석사동   31804 ----------


 ---------- 2020-07-10 11:00:00 : 남산면   31805 ----------


 ---------- 2020-07-10 13:00:00 : 남  면   31807 ----------


 ---------- 2020-07-10 14:00:00 : 남  면   31808 ----------


 ---------- 2020-07-10 14:00:00 : 동내면   31809 ----------


 ---------- 2020-07-10 14:00:00 : 효자1동   31811 ----------


 ---------- 2020-07-10 14:00:00 : 퇴계동   31812 ----------


 ---------- 2020-07-10 15:00:00 : 남산면   31813 ----------


 ---------- 2020-07-10 17:00:00 : 효자1동   31814 ----------


 ---------- 2020-07-11 10:00:00 : 사북면   31815 ----------


 ---------- 2020-07-11 11:00:00 : 신동면   31816 ----------


 ---------- 2020-07-11 11:00:00 : 소양동   31817 ----------


 ---------- 2020-07-11 12:00:00 : 후평1동   31818 ----------


 ---------- 2020-07-11 13:00:00 : 강남동   31819 ----------


 ---------- 2020-07-11 14:00:00 : 신동면   31821 ----------


 ---------- 2020-07-11 14:00:00 : 남산면   31822 ----------


 ---------- 2020-07-11 14:00:00 : 퇴계동   31823 ----------


 ---------- 2020-07-11 15:00:00 : 동내면   31825 ----------


 ---------- 2020-07-11 16:00:00 : 신북읍   31826 ----------


 ---------- 2020-07-11 17:00:00 : 후평1동   31827 ----------


 ---------- 2020-07-11 20:00:00 : 후평1동   31828 ----------


 ---------- 2020-07-11 23:00:00 : 효자1동   31830 ----------


 ---------- 2020-07-12 07:00:00 : 남산면   31831 ----------


 ---------- 2020-07-12 09:00:00 : 효자1동   31832 ----------


 ---------- 2020-07-12 10:00:00 : 동내면   31833 ----------


 ---------- 2020-07-12 10:00:00 : 후평1동   31836 ----------


 ---------- 2020-07-12 11:00:00 : 서  면   31837 ----------


 ---------- 2020-07-12 11:00:00 : 동  면   31838 ----------


 ---------- 2020-07-12 13:00:00 : 남  면   31839 ----------


 ---------- 2020-07-12 13:00:00 : 남산면   31840 ----------


 ---------- 2020-07-12 13:00:00 : 동산면   31841 ----------


 ---------- 2020-07-12 18:00:00 : 신사우동   31842 ----------


 ---------- 2020-07-13 09:00:00 : 동  면   31843 ----------


 ---------- 2020-07-13 10:00:00 : 소양동   31844 ----------


 ---------- 2020-07-13 11:00:00 : 석사동   31845 ----------


 ---------- 2020-07-13 12:00:00 : 강남동   31846 ----------


 ---------- 2020-07-13 14:00:00 : 서  면   31847 ----------


 ---------- 2020-07-13 14:00:00 : 동내면   31848 ----------


 ---------- 2020-07-13 15:00:00 : 사북면   31849 ----------


 ---------- 2020-07-13 16:00:00 : 효자1동   31850 ----------


 ---------- 2020-07-13 17:00:00 : 효자1동   31851 ----------


 ---------- 2020-07-14 07:00:00 : 신동면   31852 ----------


 ---------- 2020-07-14 09:00:00 : 신동면   31853 ----------


 ---------- 2020-07-14 10:00:00 : 효자1동   31854 ----------


 ---------- 2020-07-14 11:00:00 : 신사우동   31855 ----------


 ---------- 2020-07-14 13:00:00 : 남산면   31856 ----------


 ---------- 2020-07-14 13:00:00 : 북산면   31857 ----------


 ---------- 2020-07-14 16:00:00 : 소양동   31858 ----------


 ---------- 2020-07-14 16:00:00 : 퇴계동   31859 ----------

 ---------- 2020-07-14 18:00:00 : 신북읍   31860 ----------


 ---------- 2020-07-14 18:00:00 : 퇴계동   31861 ----------


 ---------- 2020-07-14 19:00:00 : 동  면   31862 ----------


 ---------- 2020-07-15 01:00:00 : 후평1동   31863 ----------


 ---------- 2020-07-15 01:00:00 : 퇴계동   31864 ----------


 ---------- 2020-07-15 07:00:00 : 효자1동   31865 ----------


 ---------- 2020-07-15 07:00:00 : 동산면   31866 ----------


 ---------- 2020-07-15 08:00:00 : 남산면   31867 ----------


 ---------- 2020-07-15 08:00:00 : 후평1동   31868 ----------


 ---------- 2020-07-15 09:00:00 : 남산면   31869 ----------


 ---------- 2020-07-15 10:00:00 : 동산면   31870 ----------


 ---------- 2020-07-15 11:00:00 : 동  면   31871 ----------


 ---------- 2020-07-15 13:00:00 : 신사우동   31872 ----------


 ---------- 2020-07-15 13:00:00 : 동  면   31873 ----------


 ---------- 2020-07-15 14:00:00 : 서  면   31874 ----------


 ---------- 2020-07-15 14:00:00 : 남산면   31875 ----------


 ---------- 2020-07-15 14:00:00 : 근화동   31877 ----------


 ---------- 2020-07-15 14:00:00 : 동  면   31878 ----------


 ---------- 2020-07-15 15:00:00 : 신동면   31879 ----------


 ---------- 2020-07-15 16:00:00 : 석사동   31880 ----------


 ---------- 2020-07-15 16:00:00 : 강남동   31881 ----------


 ---------- 2020-07-15 17:00:00 : 신동면   31882 ----------


 ---------- 2020-07-15 17:00:00 : 동  면   31883 ----------


 ---------- 2020-07-15 17:00:00 : 조운동   31884 ----------


 ---------- 2020-07-15 20:00:00 : 퇴계동   31885 ----------


 ---------- 2020-07-16 06:00:00 : 동내면   31886 ----------


 ---------- 2020-07-16 09:00:00 : 서  면   31887 ----------


 ---------- 2020-07-16 10:00:00 : 퇴계동   31888 ----------


 ---------- 2020-07-16 10:00:00 : 교  동   31889 ----------


 ---------- 2020-07-16 11:00:00 : 신북읍   31890 ----------


 ---------- 2020-07-16 12:00:00 : 신북읍   31891 ----------


 ---------- 2020-07-16 13:00:00 : 조운동   31892 ----------


 ---------- 2020-07-16 15:00:00 : 서  면   31893 ----------


 ---------- 2020-07-16 17:00:00 : 석사동   31894 ----------


 ---------- 2020-07-16 17:00:00 : 동  면   31895 ----------


 ---------- 2020-07-16 19:00:00 : 남산면   31896 ----------


 ---------- 2020-07-17 07:00:00 : 신동면   31897 ----------


 ---------- 2020-07-17 09:00:00 : 강남동   31898 ----------


 ---------- 2020-07-17 10:00:00 : 신북읍   31899 ----------


 ---------- 2020-07-17 10:00:00 : 후평1동   31900 ----------


 ---------- 2020-07-17 11:00:00 : 강남동   31901 ----------


 ---------- 2020-07-17 13:00:00 : 동내면   31902 ----------


 ---------- 2020-07-17 13:00:00 : 후평1동   31903 ----------


 ---------- 2020-07-17 13:00:00 : 동산면   31904 ----------


 ---------- 2020-07-17 14:00:00 : 강남동   31905 ----------


 ---------- 2020-07-17 15:00:00 : 신북읍   31906 ----------


 ---------- 2020-07-17 16:00:00 : 석사동   31907 ----------


 ---------- 2020-07-17 16:00:00 : 동내면   31908 ----------


 ---------- 2020-07-17 16:00:00 : 퇴계동   31909 ----------


 ---------- 2020-07-17 17:00:00 : 강남동   31910 ----------


 ---------- 2020-07-17 18:00:00 : 강남동   31911 ----------


 ---------- 2020-07-17 18:00:00 : 후평1동   31912 ----------


 ---------- 2020-07-17 19:00:00 : 동내면   31913 ----------


 ---------- 2020-07-17 19:00:00 : 동산면   31914 ----------


 ---------- 2020-07-18 00:00:00 : 신동면   31916 ----------


 ---------- 2020-07-18 00:00:00 : 효자1동   31917 ----------


 ---------- 2020-07-18 08:00:00 : 서  면   31918 ----------


 ---------- 2020-07-18 08:00:00 : 동  면   31919 ----------


 ---------- 2020-07-18 09:00:00 : 동  면   31920 ----------


 ---------- 2020-07-18 10:00:00 : 동산면   31921 ----------


 ---------- 2020-07-18 13:00:00 : 동내면   31923 ----------


 ---------- 2020-07-18 15:00:00 : 후평1동   31924 ----------


 ---------- 2020-07-18 16:00:00 : 사북면   31925 ----------


 ---------- 2020-07-18 17:00:00 : 사북면   31927 ----------


 ---------- 2020-07-18 18:00:00 : 동  면   31928 ----------


 ---------- 2020-07-18 20:00:00 : 후평1동   31929 ----------


 ---------- 2020-07-19 07:00:00 : 강남동   31930 ----------


 ---------- 2020-07-19 08:00:00 : 동내면   31931 ----------


 ---------- 2020-07-19 08:00:00 : 동  면   31932 ----------


 ---------- 2020-07-19 09:00:00 : 강남동   31934 ----------


 ---------- 2020-07-19 10:00:00 : 서  면   31935 ----------


 ---------- 2020-07-19 10:00:00 : 교  동   31936 ----------


 ---------- 2020-07-19 11:00:00 : 신사우동   31937 ----------


 ---------- 2020-07-19 12:00:00 : 동  면   31938 ----------


 ---------- 2020-07-19 13:00:00 : 동  면   31939 ----------


 ---------- 2020-07-19 14:00:00 : 서  면   31940 ----------


 ---------- 2020-07-19 16:00:00 : 효자1동   31941 ----------


 ---------- 2020-07-19 17:00:00 : 석사동   31942 ----------


 ---------- 2020-07-19 19:00:00 : 동  면   31943 ----------


 ---------- 2020-07-19 21:00:00 : 효자1동   31944 ----------


 ---------- 2020-07-19 21:00:00 : 신사우동   31945 ----------


 ---------- 2020-07-19 22:00:00 : 석사동   31946 ----------


 ---------- 2020-07-20 01:00:00 : 퇴계동   31947 ----------


 ---------- 2020-07-20 09:00:00 : 석사동   31948 ----------


 ---------- 2020-07-20 09:00:00 : 신사우동   31949 ----------


 ---------- 2020-07-20 09:00:00 : 동  면   31950 ----------


 ---------- 2020-07-20 09:00:00 : 후평1동   31951 ----------


 ---------- 2020-07-20 10:00:00 : 동내면   31952 ----------


 ---------- 2020-07-20 10:00:00 : 효자1동   31954 ----------


 ---------- 2020-07-20 10:00:00 : 신사우동   31955 ----------


 ---------- 2020-07-20 11:00:00 : 동  면   31956 ----------


 ---------- 2020-07-20 14:00:00 : 북산면   31957 ----------


 ---------- 2020-07-20 15:00:00 : 강남동   31958 ----------


 ---------- 2020-07-20 15:00:00 : 동내면   31960 ----------


 ---------- 2020-07-20 16:00:00 : 석사동   31961 ----------


 ---------- 2020-07-20 16:00:00 : 서  면   31962 ----------


 ---------- 2020-07-21 03:00:00 : 후평1동   31963 ----------


 ---------- 2020-07-21 07:00:00 : 후평1동   31964 ----------


 ---------- 2020-07-21 08:00:00 : 남산면   31965 ----------


 ---------- 2020-07-21 09:00:00 : 서  면   31966 ----------


 ---------- 2020-07-21 09:00:00 : 사북면   31967 ----------


 ---------- 2020-07-21 09:00:00 : 효자1동   31968 ----------


 ---------- 2020-07-21 09:00:00 : 신사우동   31969 ----------


 ---------- 2020-07-21 10:00:00 : 소양동   31971 ----------


 ---------- 2020-07-21 10:00:00 : 동  면   31972 ----------


 ---------- 2020-07-21 11:00:00 : 강남동   31973 ----------


 ---------- 2020-07-21 12:00:00 : 동내면   31974 ----------


 ---------- 2020-07-21 12:00:00 : 동  면   31975 ----------


 ---------- 2020-07-21 12:00:00 : 교  동   31976 ----------


 ---------- 2020-07-21 14:00:00 : 효자1동   31977 ----------


 ---------- 2020-07-21 15:00:00 : 후평1동   31978 ----------


 ---------- 2020-07-21 16:00:00 : 사북면   31979 ----------


 ---------- 2020-07-21 16:00:00 : 약사명동   31980 ----------


 ---------- 2020-07-21 18:00:00 : 남산면   31981 ----------


 ---------- 2020-07-21 20:00:00 : 동내면   31982 ----------


 ---------- 2020-07-22 09:00:00 : 서  면   31983 ----------


 ---------- 2020-07-22 10:00:00 : 동  면   31984 ----------


 ---------- 2020-07-22 11:00:00 : 신북읍   31985 ----------


 ---------- 2020-07-22 11:00:00 : 퇴계동   31986 ----------


 ---------- 2020-07-22 12:00:00 : 신북읍   31987 ----------


 ---------- 2020-07-22 13:00:00 : 석사동   31988 ----------


 ---------- 2020-07-22 13:00:00 : 강남동   31989 ----------


 ---------- 2020-07-22 14:00:00 : 신북읍   31990 ----------


 ---------- 2020-07-22 15:00:00 : 석사동   31991 ----------


 ---------- 2020-07-22 15:00:00 : 신동면   31992 ----------


 ---------- 2020-07-22 16:00:00 : 북산면   31993 ----------


 ---------- 2020-07-22 16:00:00 : 동산면   31994 ----------


 ---------- 2020-07-22 17:00:00 : 석사동   31995 ----------


 ---------- 2020-07-22 17:00:00 : 남산면   31996 ----------


 ---------- 2020-07-23 06:00:00 : 동내면   31997 ----------


 ---------- 2020-07-23 08:00:00 : 남산면   31998 ----------


 ---------- 2020-07-23 08:00:00 : 동  면   31999 ----------


 ---------- 2020-07-23 09:00:00 : 동내면   32000 ----------


 ---------- 2020-07-23 10:00:00 : 퇴계동   32001 ----------


 ---------- 2020-07-23 11:00:00 : 동내면   32002 ----------


 ---------- 2020-07-23 11:00:00 : 북산면   32003 ----------

 ---------- 2020-07-23 12:00:00 : 효자1동   32004 ----------


 ---------- 2020-07-23 13:00:00 : 동내면   32005 ----------


 ---------- 2020-07-23 13:00:00 : 북산면   32006 ----------


 ---------- 2020-07-23 15:00:00 : 북산면   32007 ----------


 ---------- 2020-07-23 17:00:00 : 남산면   32008 ----------


 ---------- 2020-07-23 21:00:00 : 신북읍   32010 ----------


 ---------- 2020-07-23 22:00:00 : 신북읍   32012 ----------


 ---------- 2020-07-23 23:00:00 : 신북읍   32013 ----------


 ---------- 2020-07-24 06:00:00 : 교  동   32014 ----------


 ---------- 2020-07-24 08:00:00 : 후평1동   32015 ----------


 ---------- 2020-07-24 09:00:00 : 동내면   32017 ----------


 ---------- 2020-07-24 11:00:00 : 남산면   32018 ----------


 ---------- 2020-07-24 12:00:00 : 석사동   32019 ----------


 ---------- 2020-07-24 12:00:00 : 퇴계동   32020 ----------


 ---------- 2020-07-24 13:00:00 : 강남동   32021 ----------


 ---------- 2020-07-24 13:00:00 : 신사우동   32022 ----------


 ---------- 2020-07-24 14:00:00 : 서  면   32023 ----------


 ---------- 2020-07-24 15:00:00 : 남산면   32024 ----------


 ---------- 2020-07-24 15:00:00 : 동  면   32025 ----------


 ---------- 2020-07-24 16:00:00 : 남산면   32026 ----------


 ---------- 2020-07-24 16:00:00 : 퇴계동   32027 ----------


 ---------- 2020-07-24 18:00:00 : 후평1동   32028 ----------


 ---------- 2020-07-24 21:00:00 : 신사우동   32029 ----------


 ---------- 2020-07-25 00:00:00 : 퇴계동   32030 ----------


 ---------- 2020-07-25 00:00:00 : 조운동   32031 ----------


 ---------- 2020-07-25 07:00:00 : 근화동   32032 ----------


 ---------- 2020-07-25 08:00:00 : 서  면   32033 ----------


 ---------- 2020-07-25 09:00:00 : 동내면   32034 ----------


 ---------- 2020-07-25 09:00:00 : 퇴계동   32035 ----------


 ---------- 2020-07-25 10:00:00 : 남산면   32036 ----------


 ---------- 2020-07-25 10:00:00 : 교  동   32037 ----------


 ---------- 2020-07-25 11:00:00 : 동내면   32038 ----------


 ---------- 2020-07-25 13:00:00 : 남  면   32039 ----------


 ---------- 2020-07-25 13:00:00 : 신사우동   32040 ----------


 ---------- 2020-07-25 13:00:00 : 퇴계동   32041 ----------


 ---------- 2020-07-25 13:00:00 : 동산면   32042 ----------


 ---------- 2020-07-25 14:00:00 : 동  면   32043 ----------


 ---------- 2020-07-25 15:00:00 : 남  면   32044 ----------


 ---------- 2020-07-25 16:00:00 : 강남동   32045 ----------


 ---------- 2020-07-25 16:00:00 : 신북읍   32046 ----------


 ---------- 2020-07-25 17:00:00 : 동내면   32047 ----------


 ---------- 2020-07-25 17:00:00 : 퇴계동   32048 ----------


 ---------- 2020-07-25 20:00:00 : 효자1동   32049 ----------


 ---------- 2020-07-26 01:00:00 : 서  면   32050 ----------


 ---------- 2020-07-26 08:00:00 : 동내면   32051 ----------


 ---------- 2020-07-26 09:00:00 : 남  면   32052 ----------


 ---------- 2020-07-26 10:00:00 : 강남동   32053 ----------


 ---------- 2020-07-26 10:00:00 : 신북읍   32054 ----------


 ---------- 2020-07-26 11:00:00 : 남산면   32055 ----------


 ---------- 2020-07-26 11:00:00 : 신사우동   32056 ----------


 ---------- 2020-07-26 12:00:00 : 효자1동   32058 ----------


 ---------- 2020-07-26 14:00:00 : 효자1동   32059 ----------


 ---------- 2020-07-26 14:00:00 : 소양동   32060 ----------


 ---------- 2020-07-26 15:00:00 : 남산면   32061 ----------


 ---------- 2020-07-26 15:00:00 : 신북읍   32062 ----------


 ---------- 2020-07-26 15:00:00 : 소양동   32063 ----------


 ---------- 2020-07-26 15:00:00 : 퇴계동   32064 ----------


 ---------- 2020-07-26 16:00:00 : 석사동   32065 ----------


 ---------- 2020-07-26 16:00:00 : 강남동   32066 ----------


 ---------- 2020-07-26 16:00:00 : 근화동   32067 ----------


 ---------- 2020-07-26 17:00:00 : 후평1동   32068 ----------


 ---------- 2020-07-26 19:00:00 : 퇴계동   32069 ----------


 ---------- 2020-07-26 23:00:00 : 신북읍   32070 ----------


 ---------- 2020-07-27 07:00:00 : 퇴계동   32071 ----------


 ---------- 2020-07-27 10:00:00 : 동내면   32074 ----------


 ---------- 2020-07-27 10:00:00 : 동  면   32075 ----------


 ---------- 2020-07-27 12:00:00 : 약사명동   32076 ----------


 ---------- 2020-07-27 13:00:00 : 동내면   32077 ----------


 ---------- 2020-07-27 13:00:00 : 신북읍   32078 ----------


 ---------- 2020-07-27 13:00:00 : 후평1동   32079 ----------


 ---------- 2020-07-27 15:00:00 : 근화동   32080 ----------


 ---------- 2020-07-27 16:00:00 : 남산면   32081 ----------


 ---------- 2020-07-27 16:00:00 : 퇴계동   32082 ----------


 ---------- 2020-07-27 18:00:00 : 남산면   32083 ----------


 ---------- 2020-07-27 19:00:00 : 석사동   32085 ----------


 ---------- 2020-07-27 23:00:00 : 근화동   32086 ----------


 ---------- 2020-07-28 01:00:00 : 조운동   32087 ----------


 ---------- 2020-07-28 04:00:00 : 석사동   32088 ----------


 ---------- 2020-07-28 08:00:00 : 동  면   32089 ----------


 ---------- 2020-07-28 08:00:00 : 퇴계동   32090 ----------


 ---------- 2020-07-28 09:00:00 : 신동면   32091 ----------


 ---------- 2020-07-28 09:00:00 : 동  면   32092 ----------


 ---------- 2020-07-28 10:00:00 : 신동면   32093 ----------


 ---------- 2020-07-28 10:00:00 : 강남동   32094 ----------


 ---------- 2020-07-28 10:00:00 : 신사우동   32095 ----------


 ---------- 2020-07-28 11:00:00 : 신동면   32096 ----------


 ---------- 2020-07-28 11:00:00 : 퇴계동   32097 ----------


 ---------- 2020-07-28 12:00:00 : 남산면   32098 ----------


 ---------- 2020-07-28 13:00:00 : 서  면   32099 ----------


 ---------- 2020-07-28 13:00:00 : 사북면   32100 ----------


 ---------- 2020-07-28 13:00:00 : 남산면   32101 ----------


 ---------- 2020-07-28 13:00:00 : 약사명동   32102 ----------


 ---------- 2020-07-28 14:00:00 : 강남동   32103 ----------


 ---------- 2020-07-28 14:00:00 : 남산면   32104 ----------


 ---------- 2020-07-28 15:00:00 : 약사명동   32105 ----------


 ---------- 2020-07-28 16:00:00 : 효자1동   32106 ----------


 ---------- 2020-07-29 09:00:00 : 강남동   32107 ----------


 ---------- 2020-07-29 09:00:00 : 서  면   32108 ----------


 ---------- 2020-07-29 09:00:00 : 신사우동   32109 ----------


 ---------- 2020-07-29 10:00:00 : 강남동   32110 ----------


 ---------- 2020-07-29 11:00:00 : 석사동   32112 ----------


 ---------- 2020-07-29 11:00:00 : 강남동   32113 ----------


 ---------- 2020-07-29 11:00:00 : 동  면   32114 ----------


 ---------- 2020-07-29 12:00:00 : 소양동   32115 ----------


 ---------- 2020-07-29 12:00:00 : 동  면   32116 ----------


 ---------- 2020-07-29 13:00:00 : 강남동   32117 ----------


 ---------- 2020-07-29 13:00:00 : 서  면   32118 ----------


 ---------- 2020-07-29 14:00:00 : 퇴계동   32119 ----------


 ---------- 2020-07-29 15:00:00 : 남  면   32120 ----------


 ---------- 2020-07-29 15:00:00 : 동내면   32121 ----------


 ---------- 2020-07-29 15:00:00 : 효자1동   32122 ----------


 ---------- 2020-07-29 15:00:00 : 신북읍   32123 ----------


 ---------- 2020-07-29 19:00:00 : 신사우동   32124 ----------


 ---------- 2020-07-29 19:00:00 : 퇴계동   32125 ----------


 ---------- 2020-07-29 20:00:00 : 소양동   32126 ----------


 ---------- 2020-07-30 00:00:00 : 후평1동   32128 ----------


 ---------- 2020-07-30 00:00:00 : 퇴계동   32129 ----------


 ---------- 2020-07-30 01:00:00 : 석사동   32130 ----------


 ---------- 2020-07-30 02:00:00 : 후평1동   32131 ----------


 ---------- 2020-07-30 07:00:00 : 동내면   32132 ----------


 ---------- 2020-07-30 09:00:00 : 석사동   32133 ----------


 ---------- 2020-07-30 09:00:00 : 동내면   32134 ----------


 ---------- 2020-07-30 09:00:00 : 퇴계동   32135 ----------


 ---------- 2020-07-30 10:00:00 : 동산면   32136 ----------


 ---------- 2020-07-30 11:00:00 : 신사우동   32137 ----------


 ---------- 2020-07-30 11:00:00 : 동  면   32138 ----------


 ---------- 2020-07-30 11:00:00 : 퇴계동   32139 ----------


 ---------- 2020-07-30 12:00:00 : 석사동   32140 ----------


 ---------- 2020-07-30 12:00:00 : 신동면   32141 ----------


 ---------- 2020-07-30 13:00:00 : 남  면   32142 ----------


 ---------- 2020-07-30 13:00:00 : 신북읍   32143 ----------


 ---------- 2020-07-30 14:00:00 : 동내면   32144 ----------


 ---------- 2020-07-30 14:00:00 : 남산면   32145 ----------


 ---------- 2020-07-30 15:00:00 : 신북읍   32146 ----------


 ---------- 2020-07-30 15:00:00 : 동  면   32147 ----------


 ---------- 2020-07-30 16:00:00 : 석사동   32148 ----------


 ---------- 2020-07-30 16:00:00 : 동내면   32149 ----------

 ---------- 2020-07-30 16:00:00 : 남산면   32150 ----------


 ---------- 2020-07-30 16:00:00 : 후평1동   32151 ----------


 ---------- 2020-07-30 16:00:00 : 교  동   32152 ----------


 ---------- 2020-07-30 17:00:00 : 동내면   32153 ----------


 ---------- 2020-07-30 17:00:00 : 동산면   32154 ----------


 ---------- 2020-07-30 18:00:00 : 동내면   32155 ----------


 ---------- 2020-07-30 19:00:00 : 강남동   32156 ----------


 ---------- 2020-07-31 03:00:00 : 근화동   32157 ----------


 ---------- 2020-07-31 08:00:00 : 동  면   32158 ----------


 ---------- 2020-07-31 08:00:00 : 퇴계동   32159 ----------


 ---------- 2020-07-31 09:00:00 : 동내면   32160 ----------


 ---------- 2020-07-31 09:00:00 : 남산면   32161 ----------


 ---------- 2020-07-31 11:00:00 : 남  면   32162 ----------


 ---------- 2020-07-31 11:00:00 : 근화동   32163 ----------


 ---------- 2020-07-31 11:00:00 : 동  면   32164 ----------


 ---------- 2020-07-31 12:00:00 : 강남동   32165 ----------


 ---------- 2020-07-31 12:00:00 : 서  면   32166 ----------


 ---------- 2020-07-31 12:00:00 : 남산면   32167 ----------


 ---------- 2020-07-31 12:00:00 : 동  면   32168 ----------


 ---------- 2020-07-31 13:00:00 : 석사동   32169 ----------


 ---------- 2020-07-31 13:00:00 : 서  면   32170 ----------


 ---------- 2020-07-31 13:00:00 : 남산면   32171 ----------


 ---------- 2020-07-31 13:00:00 : 신북읍   32172 ----------


 ---------- 2020-07-31 13:00:00 : 동산면   32173 ----------


 ---------- 2020-07-31 14:00:00 : 동내면   32174 ----------


 ---------- 2020-07-31 14:00:00 : 신사우동   32175 ----------


 ---------- 2020-07-31 15:00:00 : 효자1동   32176 ----------


 ---------- 2020-07-31 15:00:00 : 남산면   32177 ----------


 ---------- 2020-07-31 15:00:00 : 근화동   32178 ----------


 ---------- 2020-07-31 15:00:00 : 소양동   32179 ----------


 ---------- 2020-07-31 15:00:00 : 동산면   32180 ----------


 ---------- 2020-07-31 16:00:00 : 강남동   32181 ----------


 ---------- 2020-07-31 16:00:00 : 남  면   32182 ----------


 ---------- 2020-07-31 16:00:00 : 동내면   32183 ----------


 ---------- 2020-07-31 17:00:00 : 소양동   32184 ----------


 ---------- 2020-07-31 18:00:00 : 사북면   32185 ----------


 ---------- 2020-08-01 08:00:00 : 남산면   32186 ----------


 ---------- 2020-08-01 09:00:00 : 남산면   32187 ----------


 ---------- 2020-08-01 09:00:00 : 북산면   32188 ----------


 ---------- 2020-08-01 10:00:00 : 사북면   32189 ----------


 ---------- 2020-08-01 12:00:00 : 동내면   32190 ----------


 ---------- 2020-08-01 12:00:00 : 근화동   32191 ----------


 ---------- 2020-08-01 13:00:00 : 석사동   32192 ----------


 ---------- 2020-08-01 13:00:00 : 동내면   32193 ----------


 ---------- 2020-08-01 14:00:00 : 남산면   32195 ----------


 ---------- 2020-08-01 15:00:00 : 남산면   32197 ----------


 ---------- 2020-08-01 15:00:00 : 동산면   32199 ----------


 ---------- 2020-08-01 19:00:00 : 서  면   32200 ----------


 ---------- 2020-08-01 19:00:00 : 효자1동   32201 ----------


 ---------- 2020-08-01 20:00:00 : 강남동   32202 ----------


 ---------- 2020-08-01 21:00:00 : 강남동   32203 ----------


 ---------- 2020-08-02 01:00:00 : 약사명동   32204 ----------


 ---------- 2020-08-02 02:00:00 : 신사우동   32205 ----------


 ---------- 2020-08-02 09:00:00 : 석사동   32206 ----------


 ---------- 2020-08-02 10:00:00 : 신동면   32207 ----------


 ---------- 2020-08-02 10:00:00 : 강남동   32208 ----------


 ---------- 2020-08-02 10:00:00 : 동  면   32209 ----------


 ---------- 2020-08-02 11:00:00 : 동내면   32210 ----------


 ---------- 2020-08-02 11:00:00 : 근화동   32211 ----------


 ---------- 2020-08-02 12:00:00 : 신동면   32212 ----------


 ---------- 2020-08-02 12:00:00 : 동  면   32213 ----------


 ---------- 2020-08-02 13:00:00 : 남산면   32214 ----------


 ---------- 2020-08-02 13:00:00 : 후평1동   32215 ----------


 ---------- 2020-08-02 14:00:00 : 서  면   32216 ----------


 ---------- 2020-08-02 15:00:00 : 남산면   32217 ----------


 ---------- 2020-08-02 15:00:00 : 후평1동   32218 ----------


 ---------- 2020-08-02 18:00:00 : 근화동   32219 ----------


 ---------- 2020-08-02 19:00:00 : 동내면   32220 ----------


 ---------- 2020-08-03 02:00:00 : 남산면   32221 ----------


 ---------- 2020-08-03 04:00:00 : 서  면   32222 ----------


 ---------- 2020-08-03 05:00:00 : 남산면   32224 ----------


 ---------- 2020-08-03 05:00:00 : 후평1동   32225 ----------


 ---------- 2020-08-03 06:00:00 : 근화동   32226 ----------


 ---------- 2020-08-03 06:00:00 : 신북읍   32227 ----------


 ---------- 2020-08-03 08:00:00 : 서  면   32228 ----------


 ---------- 2020-08-03 08:00:00 : 근화동   32230 ----------


 ---------- 2020-08-03 08:00:00 : 신북읍   32233 ----------


 ---------- 2020-08-03 08:00:00 : 후평1동   32234 ----------


 ---------- 2020-08-03 09:00:00 : 남  면   32235 ----------


 ---------- 2020-08-03 09:00:00 : 신북읍   32237 ----------


 ---------- 2020-08-03 10:00:00 : 신동면   32238 ----------


 ---------- 2020-08-03 10:00:00 : 남  면   32241 ----------


 ---------- 2020-08-03 10:00:00 : 남산면   32243 ----------


 ---------- 2020-08-03 10:00:00 : 신사우동   32244 ----------


 ---------- 2020-08-03 11:00:00 : 남산면   32245 ----------


 ---------- 2020-08-03 13:00:00 : 남  면   32247 ----------


 ---------- 2020-08-03 13:00:00 : 약사명동   32248 ----------


 ---------- 2020-08-03 13:00:00 : 동  면   32250 ----------


 ---------- 2020-08-03 16:00:00 : 남산면   32251 ----------


 ---------- 2020-08-03 17:00:00 : 신동면   32252 ----------


 ---------- 2020-08-03 17:00:00 : 동내면   32253 ----------


 ---------- 2020-08-03 18:00:00 : 남  면   32254 ----------


 ---------- 2020-08-03 19:00:00 : 남  면   32255 ----------


 ---------- 2020-08-03 21:00:00 : 석사동   32256 ----------


 ---------- 2020-08-03 22:00:00 : 퇴계동   32257 ----------


 ---------- 2020-08-04 05:00:00 : 석사동   32258 ----------


 ---------- 2020-08-04 06:00:00 : 동산면   32259 ----------


 ---------- 2020-08-04 08:00:00 : 교  동   32260 ----------


 ---------- 2020-08-04 10:00:00 : 퇴계동   32261 ----------


 ---------- 2020-08-04 11:00:00 : 강남동   32262 ----------


 ---------- 2020-08-04 12:00:00 : 신북읍   32263 ----------


 ---------- 2020-08-04 13:00:00 : 강남동   32264 ----------


 ---------- 2020-08-04 13:00:00 : 효자1동   32265 ----------


 ---------- 2020-08-04 13:00:00 : 교  동   32266 ----------


 ---------- 2020-08-04 14:00:00 : 남산면   32267 ----------


 ---------- 2020-08-04 14:00:00 : 근화동   32269 ----------


 ---------- 2020-08-04 14:00:00 : 신북읍   32270 ----------


 ---------- 2020-08-04 14:00:00 : 동  면   32271 ----------


 ---------- 2020-08-04 15:00:00 : 사북면   32272 ----------


 ---------- 2020-08-04 15:00:00 : 동내면   32273 ----------


 ---------- 2020-08-04 17:00:00 : 강남동   32275 ----------


 ---------- 2020-08-04 18:00:00 : 신사우동   32276 ----------


 ---------- 2020-08-04 18:00:00 : 후평1동   32277 ----------


 ---------- 2020-08-04 18:00:00 : 퇴계동   32278 ----------


 ---------- 2020-08-04 19:00:00 : 석사동   32280 ----------


 ---------- 2020-08-04 21:00:00 : 효자1동   32282 ----------


 ---------- 2020-08-04 22:00:00 : 근화동   32283 ----------


 ---------- 2020-08-04 23:00:00 : 퇴계동   32285 ----------


 ---------- 2020-08-05 09:00:00 : 사북면   32286 ----------


 ---------- 2020-08-05 09:00:00 : 동내면   32287 ----------


 ---------- 2020-08-05 09:00:00 : 남산면   32288 ----------


 ---------- 2020-08-05 10:00:00 : 남산면   32289 ----------


 ---------- 2020-08-05 11:00:00 : 동내면   32290 ----------


 ---------- 2020-08-05 11:00:00 : 후평1동   32291 ----------


 ---------- 2020-08-05 12:00:00 : 사북면   32292 ----------


 ---------- 2020-08-05 13:00:00 : 석사동   32293 ----------


 ---------- 2020-08-05 14:00:00 : 동산면   32294 ----------


 ---------- 2020-08-05 15:00:00 : 석사동   32295 ----------


 ---------- 2020-08-05 15:00:00 : 소양동   32296 ----------


 ---------- 2020-08-05 16:00:00 : 강남동   32297 ----------


 ---------- 2020-08-05 16:00:00 : 신사우동   32298 ----------


 ---------- 2020-08-05 17:00:00 : 퇴계동   32299 ----------


 ---------- 2020-08-05 19:00:00 : 후평1동   32300 ----------


 ---------- 2020-08-05 20:00:00 : 신동면   32303 ----------


 ---------- 2020-08-05 22:00:00 : 동내면   32304 ----------


 ---------- 2020-08-05 22:00:00 : 남산면   32306 ----------

 ---------- 2020-08-06 00:00:00 : 신북읍   32307 ----------


 ---------- 2020-08-06 07:00:00 : 신동면   32308 ----------


 ---------- 2020-08-06 08:00:00 : 조운동   32309 ----------


 ---------- 2020-08-06 09:00:00 : 서  면   32310 ----------


 ---------- 2020-08-06 09:00:00 : 신북읍   32311 ----------


 ---------- 2020-08-06 10:00:00 : 동내면   32312 ----------


 ---------- 2020-08-06 10:00:00 : 신북읍   32313 ----------


 ---------- 2020-08-06 11:00:00 : 서  면   32314 ----------


 ---------- 2020-08-06 11:00:00 : 남  면   32315 ----------


 ---------- 2020-08-06 11:00:00 : 남산면   32324 ----------


 ---------- 2020-08-06 11:00:00 : 북산면   32325 ----------


 ---------- 2020-08-06 12:00:00 : 남산면   32328 ----------


 ---------- 2020-08-06 12:00:00 : 신사우동   32329 ----------


 ---------- 2020-08-06 13:00:00 : 남산면   32330 ----------


 ---------- 2020-08-06 14:00:00 : 사북면   32331 ----------


 ---------- 2020-08-06 14:00:00 : 후평1동   32332 ----------


 ---------- 2020-08-06 15:00:00 : 강남동   32333 ----------


 ---------- 2020-08-06 15:00:00 : 남산면   32335 ----------


 ---------- 2020-08-06 16:00:00 : 남산면   32336 ----------


 ---------- 2020-08-06 16:00:00 : 퇴계동   32337 ----------


 ---------- 2020-08-06 22:00:00 : 신사우동   32338 ----------


 ---------- 2020-08-07 01:00:00 : 후평1동   32339 ----------


 ---------- 2020-08-07 04:00:00 : 남산면   32341 ----------


 ---------- 2020-08-07 05:00:00 : 남산면   32343 ----------


 ---------- 2020-08-07 07:00:00 : 사북면   32344 ----------


 ---------- 2020-08-07 07:00:00 : 소양동   32345 ----------


 ---------- 2020-08-07 08:00:00 : 남산면   32351 ----------


 ---------- 2020-08-07 08:00:00 : 후평1동   32352 ----------


 ---------- 2020-08-07 11:00:00 : 남산면   32353 ----------


 ---------- 2020-08-07 12:00:00 : 남  면   32354 ----------


 ---------- 2020-08-07 12:00:00 : 남산면   32355 ----------


 ---------- 2020-08-07 12:00:00 : 퇴계동   32356 ----------


 ---------- 2020-08-07 13:00:00 : 근화동   32357 ----------


 ---------- 2020-08-07 13:00:00 : 소양동   32358 ----------


 ---------- 2020-08-07 15:00:00 : 후평1동   32359 ----------


 ---------- 2020-08-07 16:00:00 : 소양동   32360 ----------


 ---------- 2020-08-07 18:00:00 : 소양동   32361 ----------


 ---------- 2020-08-07 22:00:00 : 소양동   32362 ----------


 ---------- 2020-08-08 00:00:00 : 석사동   32365 ----------


 ---------- 2020-08-08 00:00:00 : 강남동   32366 ----------


 ---------- 2020-08-08 04:00:00 : 남산면   32368 ----------


 ---------- 2020-08-08 05:00:00 : 남산면   32378 ----------


 ---------- 2020-08-08 06:00:00 : 서  면   32379 ----------


 ---------- 2020-08-08 07:00:00 : 퇴계동   32381 ----------


 ---------- 2020-08-08 08:00:00 : 서  면   32382 ----------


 ---------- 2020-08-08 08:00:00 : 동내면   32383 ----------


 ---------- 2020-08-08 08:00:00 : 동산면   32384 ----------


 ---------- 2020-08-08 09:00:00 : 석사동   32385 ----------


 ---------- 2020-08-08 09:00:00 : 남산면   32386 ----------


 ---------- 2020-08-08 09:00:00 : 신사우동   32387 ----------


 ---------- 2020-08-08 10:00:00 : 석사동   32388 ----------


 ---------- 2020-08-08 10:00:00 : 동  면   32389 ----------


 ---------- 2020-08-08 10:00:00 : 후평1동   32390 ----------


 ---------- 2020-08-08 10:00:00 : 북산면   32392 ----------


 ---------- 2020-08-08 11:00:00 : 신북읍   32393 ----------


 ---------- 2020-08-08 11:00:00 : 동산면   32394 ----------


 ---------- 2020-08-08 13:00:00 : 석사동   32395 ----------


 ---------- 2020-08-08 14:00:00 : 서  면   32396 ----------


 ---------- 2020-08-08 14:00:00 : 남산면   32397 ----------


 ---------- 2020-08-08 17:00:00 : 강남동   32398 ----------


 ---------- 2020-08-08 20:00:00 : 동  면   32399 ----------


 ---------- 2020-08-08 20:00:00 : 퇴계동   32400 ----------


 ---------- 2020-08-09 04:00:00 : 남산면   32407 ----------


 ---------- 2020-08-09 04:00:00 : 퇴계동   32408 ----------


 ---------- 2020-08-09 06:00:00 : 동내면   32409 ----------


 ---------- 2020-08-09 06:00:00 : 남산면   32410 ----------


 ---------- 2020-08-09 07:00:00 : 신북읍   32412 ----------


 ---------- 2020-08-09 10:00:00 : 동산면   32413 ----------


 ---------- 2020-08-09 11:00:00 : 동내면   32414 ----------


 ---------- 2020-08-09 11:00:00 : 약사명동   32416 ----------


 ---------- 2020-08-09 12:00:00 : 동내면   32417 ----------


 ---------- 2020-08-09 15:00:00 : 서  면   32418 ----------


 ---------- 2020-08-09 16:00:00 : 강남동   32419 ----------


 ---------- 2020-08-09 17:00:00 : 강남동   32420 ----------


 ---------- 2020-08-09 17:00:00 : 동내면   32421 ----------


 ---------- 2020-08-09 21:00:00 : 동  면   32422 ----------


 ---------- 2020-08-10 01:00:00 : 근화동   32423 ----------


 ---------- 2020-08-10 05:00:00 : 남산면   32433 ----------


 ---------- 2020-08-10 08:00:00 : 동내면   32434 ----------


 ---------- 2020-08-10 08:00:00 : 동  면   32437 ----------


 ---------- 2020-08-10 09:00:00 : 강남동   32439 ----------


 ---------- 2020-08-10 09:00:00 : 동  면   32440 ----------


 ---------- 2020-08-10 09:00:00 : 후평1동   32441 ----------


 ---------- 2020-08-10 10:00:00 : 동내면   32442 ----------


 ---------- 2020-08-10 10:00:00 : 남산면   32443 ----------


 ---------- 2020-08-10 10:00:00 : 북산면   32444 ----------


 ---------- 2020-08-10 11:00:00 : 동내면   32445 ----------


 ---------- 2020-08-10 11:00:00 : 효자1동   32446 ----------


 ---------- 2020-08-10 11:00:00 : 동  면   32448 ----------


 ---------- 2020-08-10 11:00:00 : 퇴계동   32449 ----------


 ---------- 2020-08-10 12:00:00 : 남산면   32450 ----------


 ---------- 2020-08-10 13:00:00 : 후평1동   32451 ----------


 ---------- 2020-08-10 13:00:00 : 동산면   32452 ----------


 ---------- 2020-08-10 14:00:00 : 동  면   32453 ----------


 ---------- 2020-08-10 14:00:00 : 퇴계동   32454 ----------


 ---------- 2020-08-10 15:00:00 : 남산면   32456 ----------


 ---------- 2020-08-10 15:00:00 : 퇴계동   32458 ----------


 ---------- 2020-08-10 16:00:00 : 강남동   32459 ----------


 ---------- 2020-08-10 17:00:00 : 퇴계동   32460 ----------


 ---------- 2020-08-10 18:00:00 : 퇴계동   32461 ----------


 ---------- 2020-08-10 22:00:00 : 약사명동   32462 ----------


 ---------- 2020-08-11 00:00:00 : 퇴계동   32464 ----------


 ---------- 2020-08-11 01:00:00 : 동  면   32465 ----------


 ---------- 2020-08-11 02:00:00 : 남  면   32466 ----------


 ---------- 2020-08-11 03:00:00 : 조운동   32468 ----------


 ---------- 2020-08-11 04:00:00 : 남산면   32469 ----------


 ---------- 2020-08-11 04:00:00 : 신사우동   32470 ----------


 ---------- 2020-08-11 04:00:00 : 조운동   32471 ----------


 ---------- 2020-08-11 05:00:00 : 남산면   32477 ----------


 ---------- 2020-08-11 06:00:00 : 남산면   32479 ----------


 ---------- 2020-08-11 09:00:00 : 강남동   32480 ----------


 ---------- 2020-08-11 10:00:00 : 신사우동   32481 ----------


 ---------- 2020-08-11 13:00:00 : 후평1동   32482 ----------


 ---------- 2020-08-11 14:00:00 : 효자1동   32483 ----------


 ---------- 2020-08-11 14:00:00 : 남산면   32484 ----------


 ---------- 2020-08-11 15:00:00 : 동내면   32485 ----------


 ---------- 2020-08-11 15:00:00 : 남산면   32486 ----------


 ---------- 2020-08-11 16:00:00 : 남산면   32487 ----------


 ---------- 2020-08-11 16:00:00 : 신북읍   32488 ----------


 ---------- 2020-08-11 17:00:00 : 후평1동   32489 ----------


 ---------- 2020-08-11 18:00:00 : 동  면   32490 ----------


 ---------- 2020-08-11 18:00:00 : 후평1동   32491 ----------


 ---------- 2020-08-12 00:00:00 : 동  면   32492 ----------


 ---------- 2020-08-12 04:00:00 : 남산면   32499 ----------


 ---------- 2020-08-12 05:00:00 : 남산면   32501 ----------


 ---------- 2020-08-12 05:00:00 : 동  면   32502 ----------


 ---------- 2020-08-12 06:00:00 : 남산면   32504 ----------


 ---------- 2020-08-12 08:00:00 : 후평1동   32505 ----------


 ---------- 2020-08-12 09:00:00 : 동내면   32506 ----------


 ---------- 2020-08-12 10:00:00 : 신동면   32507 ----------


 ---------- 2020-08-12 10:00:00 : 서  면   32508 ----------


 ---------- 2020-08-12 10:00:00 : 후평1동   32509 ----------


 ---------- 2020-08-12 11:00:00 : 신동면   32510 ----------


 ---------- 2020-08-12 11:00:00 : 남산면   32511 ----------


 ---------- 2020-08-12 12:00:00 : 서  면   32512 ----------


 ---------- 2020-08-12 12:00:00 : 퇴계동   32513 ----------

 ---------- 2020-08-12 13:00:00 : 퇴계동   32514 ----------


 ---------- 2020-08-12 14:00:00 : 동내면   32515 ----------


 ---------- 2020-08-12 14:00:00 : 효자1동   32516 ----------


 ---------- 2020-08-12 14:00:00 : 동산면   32517 ----------


 ---------- 2020-08-12 15:00:00 : 신동면   32518 ----------


 ---------- 2020-08-12 15:00:00 : 퇴계동   32519 ----------


 ---------- 2020-08-12 16:00:00 : 퇴계동   32520 ----------


 ---------- 2020-08-12 16:00:00 : 동산면   32521 ----------


 ---------- 2020-08-12 17:00:00 : 조운동   32522 ----------


 ---------- 2020-08-12 18:00:00 : 동  면   32523 ----------


 ---------- 2020-08-12 20:00:00 : 신사우동   32524 ----------


 ---------- 2020-08-13 05:00:00 : 남산면   32534 ----------


 ---------- 2020-08-13 06:00:00 : 남산면   32536 ----------


 ---------- 2020-08-13 07:00:00 : 서  면   32537 ----------


 ---------- 2020-08-13 08:00:00 : 남  면   32538 ----------


 ---------- 2020-08-13 08:00:00 : 동내면   32539 ----------


 ---------- 2020-08-13 09:00:00 : 석사동   32540 ----------


 ---------- 2020-08-13 09:00:00 : 동내면   32541 ----------


 ---------- 2020-08-13 09:00:00 : 남산면   32542 ----------


 ---------- 2020-08-13 09:00:00 : 신사우동   32543 ----------


 ---------- 2020-08-13 09:00:00 : 소양동   32544 ----------


 ---------- 2020-08-13 10:00:00 : 동내면   32545 ----------


 ---------- 2020-08-13 10:00:00 : 퇴계동   32547 ----------


 ---------- 2020-08-13 11:00:00 : 사북면   32548 ----------


 ---------- 2020-08-13 11:00:00 : 신사우동   32550 ----------


 ---------- 2020-08-13 12:00:00 : 동산면   32551 ----------


 ---------- 2020-08-13 13:00:00 : 석사동   32552 ----------


 ---------- 2020-08-13 13:00:00 : 후평1동   32553 ----------


 ---------- 2020-08-13 14:00:00 : 신동면   32554 ----------


 ---------- 2020-08-13 14:00:00 : 동산면   32557 ----------


 ---------- 2020-08-13 15:00:00 : 동산면   32558 ----------


 ---------- 2020-08-13 16:00:00 : 신동면   32559 ----------


 ---------- 2020-08-13 18:00:00 : 신북읍   32560 ----------


 ---------- 2020-08-13 19:00:00 : 강남동   32561 ----------


 ---------- 2020-08-13 19:00:00 : 퇴계동   32562 ----------


 ---------- 2020-08-13 23:00:00 : 효자1동   32563 ----------


 ---------- 2020-08-13 23:00:00 : 퇴계동   32564 ----------


 ---------- 2020-08-14 00:00:00 : 효자1동   32566 ----------


 ---------- 2020-08-14 02:00:00 : 퇴계동   32567 ----------


 ---------- 2020-08-14 04:00:00 : 남산면   32573 ----------


 ---------- 2020-08-14 06:00:00 : 남산면   32575 ----------


 ---------- 2020-08-14 07:00:00 : 석사동   32576 ----------


 ---------- 2020-08-14 08:00:00 : 동  면   32577 ----------


 ---------- 2020-08-14 09:00:00 : 신사우동   32578 ----------


 ---------- 2020-08-14 09:00:00 : 소양동   32579 ----------


 ---------- 2020-08-14 09:00:00 : 퇴계동   32580 ----------


 ---------- 2020-08-14 10:00:00 : 석사동   32581 ----------


 ---------- 2020-08-14 10:00:00 : 남산면   32582 ----------


 ---------- 2020-08-14 10:00:00 : 동  면   32583 ----------


 ---------- 2020-08-14 11:00:00 : 퇴계동   32584 ----------


 ---------- 2020-08-14 12:00:00 : 퇴계동   32585 ----------


 ---------- 2020-08-14 13:00:00 : 후평1동   32586 ----------


 ---------- 2020-08-14 14:00:00 : 퇴계동   32587 ----------


 ---------- 2020-08-14 15:00:00 : 강남동   32588 ----------


 ---------- 2020-08-14 15:00:00 : 사북면   32590 ----------


 ---------- 2020-08-14 15:00:00 : 동내면   32591 ----------


 ---------- 2020-08-14 16:00:00 : 동  면   32592 ----------


 ---------- 2020-08-14 17:00:00 : 강남동   32593 ----------


 ---------- 2020-08-14 18:00:00 : 남  면   32594 ----------


 ---------- 2020-08-14 19:00:00 : 동  면   32595 ----------


 ---------- 2020-08-14 22:00:00 : 신사우동   32596 ----------


 ---------- 2020-08-14 22:00:00 : 퇴계동   32597 ----------


 ---------- 2020-08-15 04:00:00 : 남산면   32598 ----------


 ---------- 2020-08-15 05:00:00 : 남산면   32605 ----------


 ---------- 2020-08-15 06:00:00 : 남산면   32606 ----------


 ---------- 2020-08-15 12:00:00 : 사북면   32607 ----------


 ---------- 2020-08-15 12:00:00 : 남산면   32608 ----------


 ---------- 2020-08-15 13:00:00 : 신사우동   32609 ----------


 ---------- 2020-08-15 14:00:00 : 효자1동   32610 ----------


 ---------- 2020-08-15 14:00:00 : 근화동   32611 ----------


 ---------- 2020-08-15 14:00:00 : 퇴계동   32613 ----------


 ---------- 2020-08-15 15:00:00 : 조운동   32614 ----------


 ---------- 2020-08-15 16:00:00 : 남산면   32615 ----------


 ---------- 2020-08-15 16:00:00 : 신북읍   32616 ----------


 ---------- 2020-08-15 16:00:00 : 퇴계동   32617 ----------


 ---------- 2020-08-15 16:00:00 : 동산면   32619 ----------


 ---------- 2020-08-15 17:00:00 : 동산면   32620 ----------


 ---------- 2020-08-15 18:00:00 : 남산면   32621 ----------


 ---------- 2020-08-15 19:00:00 : 소양동   32622 ----------


 ---------- 2020-08-15 20:00:00 : 근화동   32623 ----------


 ---------- 2020-08-15 23:00:00 : 퇴계동   32625 ----------


 ---------- 2020-08-15 23:00:00 : 동산면   32626 ----------


 ---------- 2020-08-16 00:00:00 : 신북읍   32627 ----------


 ---------- 2020-08-16 01:00:00 : 신북읍   32628 ----------


 ---------- 2020-08-16 05:00:00 : 남산면   32636 ----------


 ---------- 2020-08-16 06:00:00 : 남산면   32637 ----------


 ---------- 2020-08-16 06:00:00 : 조운동   32638 ----------


 ---------- 2020-08-16 07:00:00 : 석사동   32639 ----------


 ---------- 2020-08-16 08:00:00 : 조운동   32640 ----------


 ---------- 2020-08-16 09:00:00 : 후평1동   32641 ----------


 ---------- 2020-08-16 09:00:00 : 북산면   32642 ----------


 ---------- 2020-08-16 11:00:00 : 남산면   32643 ----------


 ---------- 2020-08-16 12:00:00 : 남  면   32644 ----------


 ---------- 2020-08-16 12:00:00 : 사북면   32645 ----------


 ---------- 2020-08-16 12:00:00 : 동내면   32646 ----------


 ---------- 2020-08-16 13:00:00 : 신동면   32647 ----------


 ---------- 2020-08-16 14:00:00 : 남  면   32648 ----------


 ---------- 2020-08-16 14:00:00 : 동내면   32650 ----------


 ---------- 2020-08-16 14:00:00 : 신북읍   32651 ----------


 ---------- 2020-08-16 14:00:00 : 퇴계동   32652 ----------


 ---------- 2020-08-16 15:00:00 : 효자1동   32653 ----------


 ---------- 2020-08-16 15:00:00 : 후평1동   32655 ----------


 ---------- 2020-08-16 15:00:00 : 북산면   32656 ----------


 ---------- 2020-08-16 18:00:00 : 강남동   32657 ----------


 ---------- 2020-08-16 20:00:00 : 동  면   32658 ----------


 ---------- 2020-08-17 04:00:00 : 남산면   32659 ----------


 ---------- 2020-08-17 05:00:00 : 남산면   32664 ----------


 ---------- 2020-08-17 06:00:00 : 남산면   32665 ----------


 ---------- 2020-08-17 08:00:00 : 강남동   32666 ----------


 ---------- 2020-08-17 08:00:00 : 남산면   32667 ----------


 ---------- 2020-08-17 09:00:00 : 강남동   32668 ----------


 ---------- 2020-08-17 09:00:00 : 효자1동   32669 ----------


 ---------- 2020-08-17 10:00:00 : 효자1동   32671 ----------


 ---------- 2020-08-17 12:00:00 : 남  면   32672 ----------


 ---------- 2020-08-17 12:00:00 : 남산면   32673 ----------


 ---------- 2020-08-17 12:00:00 : 소양동   32675 ----------


 ---------- 2020-08-17 13:00:00 : 퇴계동   32676 ----------


 ---------- 2020-08-17 14:00:00 : 퇴계동   32678 ----------


 ---------- 2020-08-17 15:00:00 : 남  면   32682 ----------


 ---------- 2020-08-17 16:00:00 : 효자1동   32683 ----------


 ---------- 2020-08-17 16:00:00 : 남산면   32684 ----------


 ---------- 2020-08-17 16:00:00 : 소양동   32685 ----------


 ---------- 2020-08-17 16:00:00 : 교  동   32686 ----------


 ---------- 2020-08-17 17:00:00 : 신북읍   32687 ----------


 ---------- 2020-08-17 17:00:00 : 동  면   32688 ----------


 ---------- 2020-08-18 04:00:00 : 남산면   32689 ----------


 ---------- 2020-08-18 05:00:00 : 남산면   32695 ----------


 ---------- 2020-08-18 05:00:00 : 소양동   32696 ----------


 ---------- 2020-08-18 06:00:00 : 서  면   32697 ----------


 ---------- 2020-08-18 06:00:00 : 남산면   32698 ----------


 ---------- 2020-08-18 08:00:00 : 동내면   32699 ----------


 ---------- 2020-08-18 08:00:00 : 퇴계동   32700 ----------


 ---------- 2020-08-18 09:00:00 : 서  면   32701 ----------


 ---------- 2020-08-18 09:00:00 : 동  면   32702 ----------


 ---------- 2020-08-18 09:00:00 : 후평1동   32703 ----------


 ---------- 2020-08-18 10:00:00 : 신동면   32704 ----------

 ---------- 2020-08-18 10:00:00 : 남산면   32705 ----------


 ---------- 2020-08-18 10:00:00 : 퇴계동   32706 ----------


 ---------- 2020-08-18 11:00:00 : 신동면   32707 ----------


 ---------- 2020-08-18 13:00:00 : 강남동   32708 ----------


 ---------- 2020-08-18 13:00:00 : 동  면   32709 ----------


 ---------- 2020-08-18 14:00:00 : 동  면   32710 ----------


 ---------- 2020-08-18 15:00:00 : 강남동   32711 ----------


 ---------- 2020-08-18 15:00:00 : 동  면   32712 ----------


 ---------- 2020-08-18 15:00:00 : 퇴계동   32713 ----------


 ---------- 2020-08-18 16:00:00 : 강남동   32714 ----------


 ---------- 2020-08-18 16:00:00 : 근화동   32715 ----------


 ---------- 2020-08-18 16:00:00 : 소양동   32716 ----------


 ---------- 2020-08-18 16:00:00 : 동  면   32717 ----------


 ---------- 2020-08-18 17:00:00 : 신동면   32718 ----------


 ---------- 2020-08-18 17:00:00 : 소양동   32719 ----------


 ---------- 2020-08-18 17:00:00 : 동  면   32720 ----------


 ---------- 2020-08-18 17:00:00 : 퇴계동   32721 ----------


 ---------- 2020-08-18 19:00:00 : 석사동   32722 ----------


 ---------- 2020-08-18 19:00:00 : 남산면   32723 ----------


 ---------- 2020-08-19 01:00:00 : 후평1동   32724 ----------


 ---------- 2020-08-19 05:00:00 : 남산면   32731 ----------


 ---------- 2020-08-19 06:00:00 : 남산면   32732 ----------


 ---------- 2020-08-19 08:00:00 : 석사동   32733 ----------


 ---------- 2020-08-19 08:00:00 : 강남동   32734 ----------


 ---------- 2020-08-19 08:00:00 : 남산면   32736 ----------


 ---------- 2020-08-19 09:00:00 : 석사동   32737 ----------


 ---------- 2020-08-19 09:00:00 : 동내면   32738 ----------


 ---------- 2020-08-19 09:00:00 : 퇴계동   32740 ----------


 ---------- 2020-08-19 10:00:00 : 석사동   32741 ----------


 ---------- 2020-08-19 10:00:00 : 사북면   32742 ----------


 ---------- 2020-08-19 11:00:00 : 석사동   32743 ----------


 ---------- 2020-08-19 11:00:00 : 신북읍   32744 ----------


 ---------- 2020-08-19 12:00:00 : 동내면   32745 ----------


 ---------- 2020-08-19 12:00:00 : 신사우동   32746 ----------


 ---------- 2020-08-19 13:00:00 : 동  면   32747 ----------


 ---------- 2020-08-19 13:00:00 : 후평1동   32748 ----------


 ---------- 2020-08-19 14:00:00 : 강남동   32749 ----------


 ---------- 2020-08-19 14:00:00 : 남산면   32751 ----------


 ---------- 2020-08-19 15:00:00 : 석사동   32752 ----------


 ---------- 2020-08-19 15:00:00 : 후평1동   32753 ----------


 ---------- 2020-08-19 16:00:00 : 서  면   32754 ----------


 ---------- 2020-08-19 16:00:00 : 동내면   32755 ----------


 ---------- 2020-08-19 16:00:00 : 동  면   32756 ----------


 ---------- 2020-08-19 17:00:00 : 강남동   32757 ----------


 ---------- 2020-08-19 17:00:00 : 효자1동   32759 ----------


 ---------- 2020-08-19 17:00:00 : 남산면   32760 ----------


 ---------- 2020-08-19 17:00:00 : 북산면   32762 ----------


 ---------- 2020-08-19 18:00:00 : 신북읍   32763 ----------


 ---------- 2020-08-19 19:00:00 : 강남동   32764 ----------


 ---------- 2020-08-19 19:00:00 : 퇴계동   32765 ----------


 ---------- 2020-08-19 20:00:00 : 석사동   32766 ----------


 ---------- 2020-08-19 21:00:00 : 퇴계동   32767 ----------


 ---------- 2020-08-20 03:00:00 : 남산면   32772 ----------


 ---------- 2020-08-20 05:00:00 : 남산면   32774 ----------


 ---------- 2020-08-20 06:00:00 : 남산면   32776 ----------


 ---------- 2020-08-20 06:00:00 : 북산면   32780 ----------


 ---------- 2020-08-20 08:00:00 : 강남동   32781 ----------


 ---------- 2020-08-20 08:00:00 : 서  면   32783 ----------


 ---------- 2020-08-20 09:00:00 : 강남동   32784 ----------


 ---------- 2020-08-20 09:00:00 : 남  면   32785 ----------


 ---------- 2020-08-20 09:00:00 : 남산면   32786 ----------


 ---------- 2020-08-20 09:00:00 : 동  면   32788 ----------


 ---------- 2020-08-20 10:00:00 : 동내면   32789 ----------


 ---------- 2020-08-20 10:00:00 : 신북읍   32790 ----------


 ---------- 2020-08-20 11:00:00 : 사북면   32791 ----------


 ---------- 2020-08-20 12:00:00 : 북산면   32792 ----------


 ---------- 2020-08-20 13:00:00 : 효자1동   32793 ----------


 ---------- 2020-08-20 13:00:00 : 남산면   32794 ----------


 ---------- 2020-08-20 13:00:00 : 후평1동   32795 ----------


 ---------- 2020-08-20 14:00:00 : 석사동   32796 ----------


 ---------- 2020-08-20 14:00:00 : 남  면   32797 ----------


 ---------- 2020-08-20 14:00:00 : 사북면   32799 ----------


 ---------- 2020-08-20 14:00:00 : 신사우동   32801 ----------


 ---------- 2020-08-20 14:00:00 : 신북읍   32803 ----------


 ---------- 2020-08-20 14:00:00 : 후평1동   32804 ----------


 ---------- 2020-08-20 15:00:00 : 퇴계동   32806 ----------


 ---------- 2020-08-20 16:00:00 : 효자1동   32807 ----------


 ---------- 2020-08-20 17:00:00 : 신동면   32808 ----------


 ---------- 2020-08-20 18:00:00 : 신동면   32809 ----------


 ---------- 2020-08-20 18:00:00 : 동  면   32810 ----------


 ---------- 2020-08-20 19:00:00 : 효자1동   32812 ----------


 ---------- 2020-08-20 22:00:00 : 신사우동   32813 ----------


 ---------- 2020-08-21 02:00:00 : 후평1동   32814 ----------


 ---------- 2020-08-21 05:00:00 : 신북읍   32815 ----------


 ---------- 2020-08-21 06:00:00 : 남산면   32818 ----------


 ---------- 2020-08-21 07:00:00 : 강남동   32819 ----------


 ---------- 2020-08-21 08:00:00 : 후평1동   32820 ----------


 ---------- 2020-08-21 10:00:00 : 석사동   32821 ----------


 ---------- 2020-08-21 10:00:00 : 서  면   32823 ----------


 ---------- 2020-08-21 10:00:00 : 동산면   32824 ----------


 ---------- 2020-08-21 11:00:00 : 서  면   32825 ----------


 ---------- 2020-08-21 12:00:00 : 석사동   32827 ----------


 ---------- 2020-08-21 13:00:00 : 동산면   32828 ----------


 ---------- 2020-08-21 14:00:00 : 강남동   32829 ----------


 ---------- 2020-08-21 14:00:00 : 동  면   32830 ----------


 ---------- 2020-08-21 15:00:00 : 석사동   32831 ----------


 ---------- 2020-08-21 16:00:00 : 효자1동   32833 ----------


 ---------- 2020-08-21 17:00:00 : 동내면   32834 ----------


 ---------- 2020-08-21 18:00:00 : 동내면   32835 ----------


 ---------- 2020-08-22 07:00:00 : 남산면   32838 ----------


 ---------- 2020-08-22 08:00:00 : 신사우동   32839 ----------


 ---------- 2020-08-22 08:00:00 : 후평1동   32840 ----------


 ---------- 2020-08-22 09:00:00 : 신북읍   32841 ----------


 ---------- 2020-08-22 09:00:00 : 후평1동   32842 ----------


 ---------- 2020-08-22 10:00:00 : 서  면   32843 ----------


 ---------- 2020-08-22 11:00:00 : 서  면   32844 ----------


 ---------- 2020-08-22 11:00:00 : 교  동   32845 ----------


 ---------- 2020-08-22 12:00:00 : 퇴계동   32846 ----------


 ---------- 2020-08-22 13:00:00 : 석사동   32847 ----------


 ---------- 2020-08-22 13:00:00 : 신북읍   32848 ----------


 ---------- 2020-08-22 13:00:00 : 동  면   32849 ----------


 ---------- 2020-08-22 13:00:00 : 후평1동   32850 ----------


 ---------- 2020-08-22 14:00:00 : 남산면   32851 ----------


 ---------- 2020-08-22 14:00:00 : 근화동   32852 ----------


 ---------- 2020-08-22 15:00:00 : 석사동   32853 ----------


 ---------- 2020-08-23 02:00:00 : 퇴계동   32855 ----------


 ---------- 2020-08-23 06:00:00 : 남산면   32856 ----------


 ---------- 2020-08-23 07:00:00 : 남산면   32858 ----------


 ---------- 2020-08-23 07:00:00 : 동산면   32859 ----------


 ---------- 2020-08-23 09:00:00 : 남산면   32860 ----------


 ---------- 2020-08-23 09:00:00 : 신북읍   32861 ----------


 ---------- 2020-08-23 10:00:00 : 북산면   32862 ----------


 ---------- 2020-08-23 11:00:00 : 신동면   32863 ----------


 ---------- 2020-08-23 11:00:00 : 신북읍   32864 ----------


 ---------- 2020-08-23 13:00:00 : 남  면   32865 ----------


 ---------- 2020-08-23 13:00:00 : 신사우동   32866 ----------


 ---------- 2020-08-23 13:00:00 : 퇴계동   32867 ----------


 ---------- 2020-08-23 15:00:00 : 석사동   32868 ----------


 ---------- 2020-08-23 17:00:00 : 퇴계동   32869 ----------


 ---------- 2020-08-23 20:00:00 : 석사동   32870 ----------


 ---------- 2020-08-24 07:00:00 : 남산면   32872 ----------


 ---------- 2020-08-24 08:00:00 : 강남동   32873 ----------


 ---------- 2020-08-24 08:00:00 : 남산면   32874 ----------


 ---------- 2020-08-24 09:00:00 : 동내면   32875 ----------


 ---------- 2020-08-24 09:00:00 : 효자1동   32876 ----------


 ---------- 2020-08-24 09:00:00 : 남산면   32877 ----------


 ---------- 2020-08-24 09:00:00 : 신북읍   32878 ----------

 ---------- 2020-08-24 09:00:00 : 동  면   32879 ----------


 ---------- 2020-08-24 09:00:00 : 후평1동   32881 ----------


 ---------- 2020-08-24 11:00:00 : 석사동   32882 ----------


 ---------- 2020-08-24 12:00:00 : 동내면   32883 ----------


 ---------- 2020-08-24 12:00:00 : 남산면   32884 ----------


 ---------- 2020-08-24 13:00:00 : 강남동   32885 ----------


 ---------- 2020-08-24 13:00:00 : 서  면   32886 ----------


 ---------- 2020-08-24 13:00:00 : 동  면   32887 ----------


 ---------- 2020-08-24 14:00:00 : 서  면   32888 ----------


 ---------- 2020-08-24 14:00:00 : 남산면   32889 ----------


 ---------- 2020-08-24 14:00:00 : 신사우동   32890 ----------


 ---------- 2020-08-24 14:00:00 : 교  동   32891 ----------


 ---------- 2020-08-24 15:00:00 : 남산면   32892 ----------


 ---------- 2020-08-24 15:00:00 : 교  동   32893 ----------


 ---------- 2020-08-24 16:00:00 : 강남동   32894 ----------


 ---------- 2020-08-24 18:00:00 : 효자1동   32895 ----------


 ---------- 2020-08-25 07:00:00 : 서  면   32896 ----------


 ---------- 2020-08-25 07:00:00 : 남산면   32898 ----------


 ---------- 2020-08-25 07:00:00 : 퇴계동   32900 ----------


 ---------- 2020-08-25 08:00:00 : 강남동   32901 ----------


 ---------- 2020-08-25 08:00:00 : 남산면   32902 ----------


 ---------- 2020-08-25 08:00:00 : 동  면   32903 ----------


 ---------- 2020-08-25 09:00:00 : 신북읍   32904 ----------


 ---------- 2020-08-25 11:00:00 : 동내면   32905 ----------


 ---------- 2020-08-25 11:00:00 : 신사우동   32906 ----------


 ---------- 2020-08-25 11:00:00 : 신북읍   32907 ----------


 ---------- 2020-08-25 11:00:00 : 퇴계동   32908 ----------


 ---------- 2020-08-25 12:00:00 : 석사동   32910 ----------


 ---------- 2020-08-25 12:00:00 : 서  면   32911 ----------


 ---------- 2020-08-25 13:00:00 : 동내면   32912 ----------


 ---------- 2020-08-25 15:00:00 : 효자1동   32913 ----------


 ---------- 2020-08-25 15:00:00 : 남산면   32914 ----------


 ---------- 2020-08-25 15:00:00 : 동산면   32915 ----------


 ---------- 2020-08-25 17:00:00 : 효자1동   32916 ----------


 ---------- 2020-08-25 17:00:00 : 남산면   32917 ----------


 ---------- 2020-08-25 18:00:00 : 신동면   32919 ----------


 ---------- 2020-08-26 08:00:00 : 신북읍   32920 ----------


 ---------- 2020-08-26 09:00:00 : 서  면   32921 ----------


 ---------- 2020-08-26 09:00:00 : 신사우동   32922 ----------


 ---------- 2020-08-26 09:00:00 : 동산면   32923 ----------


 ---------- 2020-08-26 10:00:00 : 동  면   32924 ----------


 ---------- 2020-08-26 10:00:00 : 후평1동   32925 ----------


 ---------- 2020-08-26 14:00:00 : 석사동   32926 ----------


 ---------- 2020-08-26 18:00:00 : 후평1동   32927 ----------


 ---------- 2020-08-26 21:00:00 : 석사동   32928 ----------


 ---------- 2020-08-26 23:00:00 : 신사우동   32929 ----------


 ---------- 2020-08-27 00:00:00 : 근화동   32930 ----------


 ---------- 2020-08-27 01:00:00 : 후평1동   32931 ----------


 ---------- 2020-08-27 04:00:00 : 퇴계동   32932 ----------


 ---------- 2020-08-27 05:00:00 : 근화동   32933 ----------


 ---------- 2020-08-27 09:00:00 : 강남동   32934 ----------


 ---------- 2020-08-27 09:00:00 : 남산면   32935 ----------


 ---------- 2020-08-27 09:00:00 : 동  면   32936 ----------


 ---------- 2020-08-27 10:00:00 : 효자1동   32938 ----------


 ---------- 2020-08-27 11:00:00 : 남산면   32939 ----------


 ---------- 2020-08-27 13:00:00 : 신사우동   32940 ----------


 ---------- 2020-08-27 13:00:00 : 신북읍   32941 ----------


 ---------- 2020-08-27 14:00:00 : 신사우동   32942 ----------


 ---------- 2020-08-27 14:00:00 : 동산면   32943 ----------


 ---------- 2020-08-27 16:00:00 : 퇴계동   32944 ----------


 ---------- 2020-08-27 17:00:00 : 신사우동   32945 ----------


 ---------- 2020-08-27 20:00:00 : 후평1동   32946 ----------


 ---------- 2020-08-27 23:00:00 : 효자1동   32947 ----------


 ---------- 2020-08-28 00:00:00 : 신사우동   32948 ----------


 ---------- 2020-08-28 06:00:00 : 근화동   32949 ----------


 ---------- 2020-08-28 07:00:00 : 남산면   32951 ----------


 ---------- 2020-08-28 07:00:00 : 근화동   32952 ----------


 ---------- 2020-08-28 07:00:00 : 후평1동   32953 ----------


 ---------- 2020-08-28 08:00:00 : 후평1동   32954 ----------


 ---------- 2020-08-28 10:00:00 : 효자1동   32955 ----------


 ---------- 2020-08-28 10:00:00 : 동  면   32956 ----------


 ---------- 2020-08-28 11:00:00 : 퇴계동   32957 ----------


 ---------- 2020-08-28 12:00:00 : 사북면   32958 ----------


 ---------- 2020-08-28 12:00:00 : 북산면   32959 ----------


 ---------- 2020-08-28 13:00:00 : 사북면   32960 ----------


 ---------- 2020-08-28 13:00:00 : 효자1동   32961 ----------


 ---------- 2020-08-28 14:00:00 : 강남동   32962 ----------


 ---------- 2020-08-28 15:00:00 : 강남동   32963 ----------


 ---------- 2020-08-28 15:00:00 : 사북면   32964 ----------


 ---------- 2020-08-28 15:00:00 : 신사우동   32965 ----------


 ---------- 2020-08-28 16:00:00 : 서  면   32966 ----------


 ---------- 2020-08-28 16:00:00 : 후평1동   32967 ----------


 ---------- 2020-08-28 17:00:00 : 퇴계동   32968 ----------


 ---------- 2020-08-28 18:00:00 : 동산면   32969 ----------


 ---------- 2020-08-28 21:00:00 : 효자1동   32970 ----------


 ---------- 2020-08-28 22:00:00 : 강남동   32971 ----------


 ---------- 2020-08-29 07:00:00 : 근화동   32973 ----------


 ---------- 2020-08-29 07:00:00 : 소양동   32974 ----------


 ---------- 2020-08-29 08:00:00 : 남산면   32975 ----------


 ---------- 2020-08-29 08:00:00 : 근화동   32976 ----------


 ---------- 2020-08-29 08:00:00 : 동산면   32977 ----------


 ---------- 2020-08-29 09:00:00 : 동내면   32978 ----------


 ---------- 2020-08-29 10:00:00 : 동내면   32979 ----------


 ---------- 2020-08-29 10:00:00 : 후평1동   32980 ----------


 ---------- 2020-08-29 11:00:00 : 동내면   32981 ----------


 ---------- 2020-08-29 13:00:00 : 북산면   32983 ----------


 ---------- 2020-08-29 14:00:00 : 서  면   32984 ----------


 ---------- 2020-08-29 15:00:00 : 신사우동   32985 ----------


 ---------- 2020-08-29 15:00:00 : 신북읍   32987 ----------


 ---------- 2020-08-29 16:00:00 : 사북면   32988 ----------


 ---------- 2020-08-29 16:00:00 : 동  면   32989 ----------


 ---------- 2020-08-29 18:00:00 : 사북면   32990 ----------


 ---------- 2020-08-30 07:00:00 : 신동면   32992 ----------


 ---------- 2020-08-30 07:00:00 : 남산면   32993 ----------


 ---------- 2020-08-30 07:00:00 : 근화동   32994 ----------


 ---------- 2020-08-30 07:00:00 : 교  동   32995 ----------


 ---------- 2020-08-30 08:00:00 : 신동면   32996 ----------


 ---------- 2020-08-30 08:00:00 : 근화동   32997 ----------


 ---------- 2020-08-30 09:00:00 : 강남동   32998 ----------


 ---------- 2020-08-30 10:00:00 : 강남동   32999 ----------


 ---------- 2020-08-30 12:00:00 : 퇴계동   33000 ----------


 ---------- 2020-08-30 13:00:00 : 동내면   33001 ----------


 ---------- 2020-08-30 14:00:00 : 사북면   33002 ----------


 ---------- 2020-08-30 14:00:00 : 동  면   33003 ----------


 ---------- 2020-08-30 15:00:00 : 후평1동   33004 ----------


 ---------- 2020-08-30 15:00:00 : 퇴계동   33005 ----------


 ---------- 2020-08-30 20:00:00 : 후평1동   33006 ----------


 ---------- 2020-08-30 21:00:00 : 근화동   33007 ----------


 ---------- 2020-08-30 23:00:00 : 석사동   33008 ----------


 ---------- 2020-08-30 23:00:00 : 동산면   33009 ----------


 ---------- 2020-08-31 00:00:00 : 퇴계동   33010 ----------


 ---------- 2020-08-31 06:00:00 : 남산면   33012 ----------


 ---------- 2020-08-31 07:00:00 : 남산면   33013 ----------


 ---------- 2020-08-31 08:00:00 : 근화동   33014 ----------


 ---------- 2020-08-31 09:00:00 : 근화동   33015 ----------


 ---------- 2020-08-31 09:00:00 : 후평1동   33016 ----------


 ---------- 2020-08-31 10:00:00 : 남산면   33017 ----------


 ---------- 2020-08-31 10:00:00 : 동  면   33018 ----------


 ---------- 2020-08-31 12:00:00 : 효자1동   33019 ----------


 ---------- 2020-08-31 13:00:00 : 교  동   33020 ----------


 ---------- 2020-08-31 14:00:00 : 후평1동   33021 ----------


 ---------- 2020-08-31 15:00:00 : 신동면   33022 ----------


 ---------- 2020-08-31 15:00:00 : 서  면   33023 ----------


 ---------- 2020-08-31 15:00:00 : 근화동   33024 ----------


 ---------- 2020-08-31 16:00:00 : 동내면   33025 ----------


 ---------- 2020-08-31 16:00:00 : 후평1동   33026 ----------

 ---------- 2020-08-31 18:00:00 : 동내면   33027 ----------


 ---------- 2020-08-31 19:00:00 : 석사동   33029 ----------


 ---------- 2020-08-31 21:00:00 : 소양동   33030 ----------


 ---------- 2020-09-01 06:00:00 : 강남동   33031 ----------


 ---------- 2020-09-01 07:00:00 : 근화동   33032 ----------


 ---------- 2020-09-01 08:00:00 : 사북면   33033 ----------


 ---------- 2020-09-01 08:00:00 : 남산면   33034 ----------


 ---------- 2020-09-01 11:00:00 : 사북면   33035 ----------


 ---------- 2020-09-01 11:00:00 : 효자1동   33036 ----------


 ---------- 2020-09-01 12:00:00 : 석사동   33037 ----------


 ---------- 2020-09-01 12:00:00 : 소양동   33038 ----------


 ---------- 2020-09-01 13:00:00 : 강남동   33039 ----------


 ---------- 2020-09-01 14:00:00 : 효자1동   33040 ----------


 ---------- 2020-09-01 14:00:00 : 남산면   33041 ----------


 ---------- 2020-09-01 14:00:00 : 신사우동   33042 ----------


 ---------- 2020-09-01 14:00:00 : 퇴계동   33043 ----------


 ---------- 2020-09-01 21:00:00 : 퇴계동   33044 ----------


 ---------- 2020-09-02 01:00:00 : 약사명동   33045 ----------


 ---------- 2020-09-02 08:00:00 : 남산면   33046 ----------


 ---------- 2020-09-02 08:00:00 : 퇴계동   33047 ----------


 ---------- 2020-09-02 09:00:00 : 후평1동   33048 ----------


 ---------- 2020-09-02 13:00:00 : 서  면   33050 ----------


 ---------- 2020-09-02 13:00:00 : 동내면   33051 ----------


 ---------- 2020-09-02 14:00:00 : 신북읍   33052 ----------


 ---------- 2020-09-02 15:00:00 : 석사동   33053 ----------


 ---------- 2020-09-02 20:00:00 : 강남동   33054 ----------


 ---------- 2020-09-03 06:00:00 : 소양동   33055 ----------


 ---------- 2020-09-03 07:00:00 : 남산면   33056 ----------


 ---------- 2020-09-03 07:00:00 : 북산면   33057 ----------


 ---------- 2020-09-03 09:00:00 : 남산면   33058 ----------


 ---------- 2020-09-03 10:00:00 : 남산면   33059 ----------


 ---------- 2020-09-03 10:00:00 : 동산면   33060 ----------


 ---------- 2020-09-03 11:00:00 : 동내면   33061 ----------


 ---------- 2020-09-03 12:00:00 : 효자1동   33062 ----------


 ---------- 2020-09-03 12:00:00 : 신북읍   33063 ----------


 ---------- 2020-09-03 13:00:00 : 사북면   33064 ----------


 ---------- 2020-09-03 14:00:00 : 신동면   33065 ----------


 ---------- 2020-09-03 15:00:00 : 사북면   33066 ----------


 ---------- 2020-09-03 15:00:00 : 동내면   33067 ----------


 ---------- 2020-09-03 16:00:00 : 퇴계동   33068 ----------


 ---------- 2020-09-03 17:00:00 : 석사동   33069 ----------


 ---------- 2020-09-04 05:00:00 : 북산면   33070 ----------


 ---------- 2020-09-04 07:00:00 : 근화동   33071 ----------


 ---------- 2020-09-04 08:00:00 : 강남동   33072 ----------


 ---------- 2020-09-04 08:00:00 : 남산면   33073 ----------


 ---------- 2020-09-04 08:00:00 : 동  면   33074 ----------


 ---------- 2020-09-04 09:00:00 : 강남동   33075 ----------


 ---------- 2020-09-04 10:00:00 : 남  면   33076 ----------


 ---------- 2020-09-04 10:00:00 : 동내면   33077 ----------


 ---------- 2020-09-04 12:00:00 : 서  면   33078 ----------


 ---------- 2020-09-04 13:00:00 : 신북읍   33079 ----------


 ---------- 2020-09-04 14:00:00 : 석사동   33080 ----------


 ---------- 2020-09-04 17:00:00 : 강남동   33081 ----------


 ---------- 2020-09-04 18:00:00 : 동내면   33082 ----------


 ---------- 2020-09-04 18:00:00 : 근화동   33083 ----------


 ---------- 2020-09-04 19:00:00 : 동  면   33084 ----------


 ---------- 2020-09-04 22:00:00 : 후평1동   33086 ----------


 ---------- 2020-09-04 23:00:00 : 효자1동   33087 ----------


 ---------- 2020-09-05 04:00:00 : 효자1동   33088 ----------


 ---------- 2020-09-05 06:00:00 : 동내면   33090 ----------


 ---------- 2020-09-05 08:00:00 : 남산면   33092 ----------


 ---------- 2020-09-05 08:00:00 : 소양동   33095 ----------


 ---------- 2020-09-05 09:00:00 : 남산면   33096 ----------


 ---------- 2020-09-05 10:00:00 : 서  면   33097 ----------


 ---------- 2020-09-05 10:00:00 : 사북면   33098 ----------


 ---------- 2020-09-05 13:00:00 : 강남동   33099 ----------


 ---------- 2020-09-05 13:00:00 : 동내면   33100 ----------


 ---------- 2020-09-05 14:00:00 : 신동면   33101 ----------


 ---------- 2020-09-05 16:00:00 : 석사동   33102 ----------


 ---------- 2020-09-05 16:00:00 : 효자1동   33103 ----------


 ---------- 2020-09-05 16:00:00 : 신사우동   33104 ----------


 ---------- 2020-09-06 00:00:00 : 석사동   33105 ----------


 ---------- 2020-09-06 03:00:00 : 퇴계동   33106 ----------


 ---------- 2020-09-06 07:00:00 : 동  면   33107 ----------


 ---------- 2020-09-06 08:00:00 : 서  면   33108 ----------


 ---------- 2020-09-06 08:00:00 : 남산면   33109 ----------


 ---------- 2020-09-06 10:00:00 : 신북읍   33110 ----------


 ---------- 2020-09-06 11:00:00 : 신북읍   33112 ----------


 ---------- 2020-09-06 11:00:00 : 소양동   33113 ----------


 ---------- 2020-09-06 12:00:00 : 강남동   33115 ----------


 ---------- 2020-09-06 12:00:00 : 효자1동   33116 ----------


 ---------- 2020-09-06 13:00:00 : 신사우동   33117 ----------


 ---------- 2020-09-06 13:00:00 : 후평1동   33118 ----------


 ---------- 2020-09-06 14:00:00 : 강남동   33119 ----------


 ---------- 2020-09-06 14:00:00 : 퇴계동   33121 ----------


 ---------- 2020-09-06 15:00:00 : 동산면   33122 ----------


 ---------- 2020-09-06 17:00:00 : 신동면   33123 ----------


 ---------- 2020-09-07 06:00:00 : 서  면   33124 ----------


 ---------- 2020-09-07 12:00:00 : 동  면   33125 ----------


 ---------- 2020-09-07 13:00:00 : 석사동   33126 ----------


 ---------- 2020-09-07 14:00:00 : 동내면   33127 ----------


 ---------- 2020-09-07 14:00:00 : 효자1동   33128 ----------


 ---------- 2020-09-07 16:00:00 : 신북읍   33129 ----------


 ---------- 2020-09-07 17:00:00 : 약사명동   33130 ----------


 ---------- 2020-09-07 22:00:00 : 동  면   33132 ----------


 ---------- 2020-09-07 22:00:00 : 후평1동   33133 ----------


 ---------- 2020-09-08 02:00:00 : 근화동   33134 ----------


 ---------- 2020-09-08 06:00:00 : 신북읍   33135 ----------


 ---------- 2020-09-08 08:00:00 : 강남동   33136 ----------


 ---------- 2020-09-08 10:00:00 : 동내면   33137 ----------


 ---------- 2020-09-08 10:00:00 : 효자1동   33138 ----------


 ---------- 2020-09-08 10:00:00 : 남산면   33139 ----------


 ---------- 2020-09-08 10:00:00 : 신북읍   33140 ----------


 ---------- 2020-09-08 11:00:00 : 남산면   33141 ----------


 ---------- 2020-09-08 11:00:00 : 후평1동   33142 ----------


 ---------- 2020-09-08 12:00:00 : 동내면   33143 ----------


 ---------- 2020-09-08 12:00:00 : 남산면   33144 ----------


 ---------- 2020-09-08 13:00:00 : 동내면   33145 ----------


 ---------- 2020-09-08 14:00:00 : 근화동   33147 ----------


 ---------- 2020-09-08 15:00:00 : 신북읍   33148 ----------


 ---------- 2020-09-08 15:00:00 : 조운동   33149 ----------


 ---------- 2020-09-08 15:00:00 : 교  동   33150 ----------


 ---------- 2020-09-08 16:00:00 : 약사명동   33151 ----------


 ---------- 2020-09-08 20:00:00 : 효자1동   33153 ----------


 ---------- 2020-09-08 21:00:00 : 서  면   33154 ----------


 ---------- 2020-09-08 22:00:00 : 근화동   33156 ----------


 ---------- 2020-09-09 09:00:00 : 남  면   33157 ----------


 ---------- 2020-09-09 12:00:00 : 강남동   33158 ----------


 ---------- 2020-09-09 13:00:00 : 석사동   33159 ----------


 ---------- 2020-09-09 13:00:00 : 신사우동   33162 ----------


 ---------- 2020-09-09 16:00:00 : 석사동   33164 ----------


 ---------- 2020-09-09 17:00:00 : 동산면   33165 ----------


 ---------- 2020-09-09 23:00:00 : 후평1동   33166 ----------


 ---------- 2020-09-10 07:00:00 : 효자1동   33167 ----------


 ---------- 2020-09-10 11:00:00 : 동내면   33168 ----------


 ---------- 2020-09-10 13:00:00 : 효자1동   33169 ----------


 ---------- 2020-09-10 14:00:00 : 강남동   33170 ----------


 ---------- 2020-09-10 14:00:00 : 동산면   33171 ----------


 ---------- 2020-09-10 15:00:00 : 동내면   33172 ----------


 ---------- 2020-09-10 15:00:00 : 후평1동   33174 ----------


 ---------- 2020-09-11 03:00:00 : 퇴계동   33175 ----------


 ---------- 2020-09-11 04:00:00 : 남산면   33176 ----------


 ---------- 2020-09-11 06:00:00 : 신북읍   33177 ----------


 ---------- 2020-09-11 08:00:00 : 북산면   33179 ----------


 ---------- 2020-09-11 09:00:00 : 남산면   33180 ----------


 ---------- 2020-09-11 09:00:00 : 퇴계동   33181 ----------

 ---------- 2020-09-11 10:00:00 : 동산면   33183 ----------


 ---------- 2020-09-11 11:00:00 : 동내면   33184 ----------


 ---------- 2020-09-11 12:00:00 : 조운동   33185 ----------


 ---------- 2020-09-11 13:00:00 : 사북면   33186 ----------


 ---------- 2020-09-11 15:00:00 : 강남동   33187 ----------


 ---------- 2020-09-11 15:00:00 : 동  면   33188 ----------


 ---------- 2020-09-11 16:00:00 : 신북읍   33189 ----------


 ---------- 2020-09-11 16:00:00 : 동  면   33190 ----------


 ---------- 2020-09-11 16:00:00 : 후평1동   33191 ----------


 ---------- 2020-09-11 17:00:00 : 동산면   33192 ----------


 ---------- 2020-09-11 18:00:00 : 퇴계동   33193 ----------


 ---------- 2020-09-12 00:00:00 : 서  면   33194 ----------


 ---------- 2020-09-12 08:00:00 : 신북읍   33195 ----------


 ---------- 2020-09-12 10:00:00 : 강남동   33196 ----------


 ---------- 2020-09-12 14:00:00 : 신사우동   33197 ----------


 ---------- 2020-09-12 16:00:00 : 북산면   33198 ----------


 ---------- 2020-09-13 08:00:00 : 남산면   33199 ----------


 ---------- 2020-09-13 09:00:00 : 신사우동   33200 ----------


 ---------- 2020-09-13 11:00:00 : 남산면   33203 ----------


 ---------- 2020-09-13 11:00:00 : 동  면   33204 ----------


 ---------- 2020-09-13 13:00:00 : 석사동   33206 ----------


 ---------- 2020-09-13 13:00:00 : 남산면   33208 ----------


 ---------- 2020-09-13 15:00:00 : 동  면   33209 ----------


 ---------- 2020-09-13 17:00:00 : 동내면   33210 ----------


 ---------- 2020-09-13 18:00:00 : 신북읍   33211 ----------


 ---------- 2020-09-13 20:00:00 : 서  면   33212 ----------


 ---------- 2020-09-14 00:00:00 : 퇴계동   33213 ----------


 ---------- 2020-09-14 06:00:00 : 효자1동   33215 ----------


 ---------- 2020-09-14 07:00:00 : 신동면   33217 ----------


 ---------- 2020-09-14 08:00:00 : 신동면   33219 ----------


 ---------- 2020-09-14 09:00:00 : 서  면   33221 ----------


 ---------- 2020-09-14 09:00:00 : 후평1동   33223 ----------


 ---------- 2020-09-14 10:00:00 : 효자1동   33225 ----------


 ---------- 2020-09-14 12:00:00 : 서  면   33226 ----------


 ---------- 2020-09-14 13:00:00 : 동  면   33227 ----------


 ---------- 2020-09-14 14:00:00 : 동내면   33228 ----------


 ---------- 2020-09-14 14:00:00 : 동  면   33229 ----------


 ---------- 2020-09-14 15:00:00 : 서  면   33230 ----------


 ---------- 2020-09-14 15:00:00 : 동내면   33231 ----------


 ---------- 2020-09-14 15:00:00 : 약사명동   33232 ----------


 ---------- 2020-09-14 15:00:00 : 후평1동   33234 ----------


 ---------- 2020-09-14 15:00:00 : 북산면   33235 ----------


 ---------- 2020-09-14 16:00:00 : 동내면   33236 ----------


 ---------- 2020-09-15 07:00:00 : 근화동   33237 ----------


 ---------- 2020-09-15 09:00:00 : 북산면   33238 ----------


 ---------- 2020-09-15 10:00:00 : 동  면   33239 ----------


 ---------- 2020-09-15 11:00:00 : 동  면   33240 ----------


 ---------- 2020-09-15 13:00:00 : 소양동   33242 ----------


 ---------- 2020-09-15 14:00:00 : 석사동   33245 ----------


 ---------- 2020-09-15 14:00:00 : 효자1동   33246 ----------


 ---------- 2020-09-15 14:00:00 : 신사우동   33247 ----------


 ---------- 2020-09-15 14:00:00 : 약사명동   33248 ----------


 ---------- 2020-09-15 15:00:00 : 사북면   33249 ----------


 ---------- 2020-09-15 15:00:00 : 동내면   33250 ----------


 ---------- 2020-09-15 16:00:00 : 신북읍   33251 ----------


 ---------- 2020-09-15 16:00:00 : 동  면   33253 ----------


 ---------- 2020-09-15 18:00:00 : 동내면   33254 ----------


 ---------- 2020-09-15 20:00:00 : 강남동   33255 ----------


 ---------- 2020-09-16 07:00:00 : 퇴계동   33256 ----------


 ---------- 2020-09-16 08:00:00 : 후평1동   33257 ----------


 ---------- 2020-09-16 09:00:00 : 사북면   33258 ----------


 ---------- 2020-09-16 21:00:00 : 약사명동   33259 ----------


 ---------- 2020-09-16 23:00:00 : 동내면   33260 ----------


 ---------- 2020-09-17 04:00:00 : 신동면   33262 ----------


 ---------- 2020-09-17 07:00:00 : 강남동   33263 ----------


 ---------- 2020-09-17 08:00:00 : 신북읍   33264 ----------


 ---------- 2020-09-17 11:00:00 : 남산면   33265 ----------


 ---------- 2020-09-17 12:00:00 : 동내면   33266 ----------


 ---------- 2020-09-17 12:00:00 : 동  면   33267 ----------


 ---------- 2020-09-17 12:00:00 : 퇴계동   33268 ----------


 ---------- 2020-09-17 13:00:00 : 신사우동   33270 ----------


 ---------- 2020-09-17 14:00:00 : 동  면   33271 ----------


 ---------- 2020-09-17 14:00:00 : 퇴계동   33272 ----------


 ---------- 2020-09-17 17:00:00 : 사북면   33273 ----------


 ---------- 2020-09-17 17:00:00 : 신사우동   33274 ----------


 ---------- 2020-09-17 17:00:00 : 퇴계동   33275 ----------


 ---------- 2020-09-17 19:00:00 : 동내면   33276 ----------


 ---------- 2020-09-17 21:00:00 : 강남동   33277 ----------


 ---------- 2020-09-18 10:00:00 : 석사동   33278 ----------


 ---------- 2020-09-18 10:00:00 : 남산면   33279 ----------


 ---------- 2020-09-18 10:00:00 : 근화동   33280 ----------


 ---------- 2020-09-18 10:00:00 : 퇴계동   33281 ----------


 ---------- 2020-09-18 12:00:00 : 동내면   33282 ----------


 ---------- 2020-09-18 14:00:00 : 석사동   33283 ----------


 ---------- 2020-09-18 14:00:00 : 동  면   33284 ----------


 ---------- 2020-09-18 15:00:00 : 서  면   33285 ----------


 ---------- 2020-09-18 15:00:00 : 남  면   33286 ----------


 ---------- 2020-09-18 15:00:00 : 동  면   33287 ----------


 ---------- 2020-09-18 17:00:00 : 신동면   33289 ----------


 ---------- 2020-09-18 17:00:00 : 동내면   33291 ----------


 ---------- 2020-09-18 17:00:00 : 퇴계동   33292 ----------


 ---------- 2020-09-18 18:00:00 : 신동면   33293 ----------


 ---------- 2020-09-18 21:00:00 : 후평1동   33294 ----------


 ---------- 2020-09-19 08:00:00 : 서  면   33295 ----------


 ---------- 2020-09-19 09:00:00 : 남산면   33296 ----------


 ---------- 2020-09-19 09:00:00 : 동  면   33297 ----------


 ---------- 2020-09-19 10:00:00 : 신동면   33298 ----------


 ---------- 2020-09-19 11:00:00 : 신북읍   33299 ----------


 ---------- 2020-09-19 12:00:00 : 남산면   33300 ----------


 ---------- 2020-09-19 12:00:00 : 신북읍   33302 ----------


 ---------- 2020-09-19 13:00:00 : 사북면   33303 ----------


 ---------- 2020-09-19 13:00:00 : 동내면   33304 ----------


 ---------- 2020-09-19 14:00:00 : 석사동   33305 ----------


 ---------- 2020-09-19 16:00:00 : 남산면   33306 ----------


 ---------- 2020-09-19 20:00:00 : 신동면   33307 ----------


 ---------- 2020-09-19 20:00:00 : 퇴계동   33308 ----------


 ---------- 2020-09-19 21:00:00 : 신동면   33309 ----------


 ---------- 2020-09-20 01:00:00 : 강남동   33311 ----------


 ---------- 2020-09-20 09:00:00 : 효자1동   33312 ----------


 ---------- 2020-09-20 09:00:00 : 신북읍   33313 ----------


 ---------- 2020-09-20 09:00:00 : 동산면   33314 ----------


 ---------- 2020-09-20 11:00:00 : 남산면   33315 ----------


 ---------- 2020-09-20 12:00:00 : 남산면   33317 ----------


 ---------- 2020-09-20 14:00:00 : 석사동   33318 ----------


 ---------- 2020-09-20 17:00:00 : 동  면   33320 ----------


 ---------- 2020-09-20 18:00:00 : 서  면   33322 ----------


 ---------- 2020-09-20 22:00:00 : 남산면   33323 ----------


 ---------- 2020-09-20 23:00:00 : 후평1동   33324 ----------


 ---------- 2020-09-21 04:00:00 : 효자1동   33326 ----------


 ---------- 2020-09-21 08:00:00 : 후평1동   33327 ----------


 ---------- 2020-09-21 09:00:00 : 신사우동   33328 ----------


 ---------- 2020-09-21 09:00:00 : 후평1동   33329 ----------


 ---------- 2020-09-21 10:00:00 : 동  면   33330 ----------


 ---------- 2020-09-21 12:00:00 : 동  면   33331 ----------


 ---------- 2020-09-21 13:00:00 : 석사동   33332 ----------


 ---------- 2020-09-21 15:00:00 : 석사동   33333 ----------


 ---------- 2020-09-21 15:00:00 : 동내면   33334 ----------


 ---------- 2020-09-21 16:00:00 : 석사동   33336 ----------


 ---------- 2020-09-21 16:00:00 : 강남동   33337 ----------


 ---------- 2020-09-21 16:00:00 : 후평1동   33338 ----------


 ---------- 2020-09-21 16:00:00 : 퇴계동   33339 ----------


 ---------- 2020-09-21 17:00:00 : 동  면   33340 ----------


 ---------- 2020-09-21 22:00:00 : 효자1동   33341 ----------


 ---------- 2020-09-22 01:00:00 : 강남동   33342 ----------


 ---------- 2020-09-22 09:00:00 : 퇴계동   33343 ----------


 ---------- 2020-09-22 12:00:00 : 강남동   33344 ----------


 ---------- 2020-09-22 12:00:00 : 남산면   33345 ----------

 ---------- 2020-09-22 13:00:00 : 근화동   33346 ----------


 ---------- 2020-09-22 14:00:00 : 소양동   33353 ----------


 ---------- 2020-09-22 15:00:00 : 남산면   33354 ----------


 ---------- 2020-09-22 16:00:00 : 사북면   33355 ----------


 ---------- 2020-09-22 16:00:00 : 퇴계동   33356 ----------


 ---------- 2020-09-22 17:00:00 : 석사동   33357 ----------


 ---------- 2020-09-22 19:00:00 : 신북읍   33358 ----------


 ---------- 2020-09-22 21:00:00 : 후평1동   33359 ----------


 ---------- 2020-09-22 23:00:00 : 후평1동   33360 ----------


 ---------- 2020-09-23 08:00:00 : 동산면   33361 ----------


 ---------- 2020-09-23 09:00:00 : 사북면   33362 ----------


 ---------- 2020-09-23 10:00:00 : 서  면   33363 ----------


 ---------- 2020-09-23 11:00:00 : 퇴계동   33364 ----------


 ---------- 2020-09-23 12:00:00 : 퇴계동   33365 ----------


 ---------- 2020-09-23 13:00:00 : 효자1동   33366 ----------


 ---------- 2020-09-23 14:00:00 : 신사우동   33367 ----------


 ---------- 2020-09-23 15:00:00 : 남산면   33368 ----------


 ---------- 2020-09-23 15:00:00 : 퇴계동   33370 ----------


 ---------- 2020-09-23 18:00:00 : 석사동   33371 ----------


 ---------- 2020-09-23 18:00:00 : 강남동   33372 ----------


 ---------- 2020-09-23 23:00:00 : 효자1동   33375 ----------


 ---------- 2020-09-24 09:00:00 : 후평1동   33376 ----------


 ---------- 2020-09-24 10:00:00 : 석사동   33377 ----------


 ---------- 2020-09-24 11:00:00 : 신사우동   33378 ----------


 ---------- 2020-09-24 14:00:00 : 강남동   33379 ----------


 ---------- 2020-09-24 15:00:00 : 강남동   33380 ----------


 ---------- 2020-09-24 15:00:00 : 효자1동   33381 ----------


 ---------- 2020-09-24 16:00:00 : 동내면   33382 ----------


 ---------- 2020-09-24 16:00:00 : 신사우동   33383 ----------


 ---------- 2020-09-24 17:00:00 : 북산면   33387 ----------


 ---------- 2020-09-24 18:00:00 : 남산면   33388 ----------


 ---------- 2020-09-24 19:00:00 : 동  면   33389 ----------


 ---------- 2020-09-25 00:00:00 : 퇴계동   33390 ----------


 ---------- 2020-09-25 03:00:00 : 신사우동   33391 ----------


 ---------- 2020-09-25 07:00:00 : 동내면   33392 ----------


 ---------- 2020-09-25 08:00:00 : 후평1동   33393 ----------


 ---------- 2020-09-25 09:00:00 : 약사명동   33394 ----------


 ---------- 2020-09-25 10:00:00 : 효자1동   33395 ----------


 ---------- 2020-09-25 12:00:00 : 남  면   33396 ----------


 ---------- 2020-09-25 14:00:00 : 동산면   33397 ----------


 ---------- 2020-09-25 15:00:00 : 후평1동   33398 ----------


 ---------- 2020-09-25 18:00:00 : 신북읍   33400 ----------


 ---------- 2020-09-25 19:00:00 : 북산면   33401 ----------


 ---------- 2020-09-25 23:00:00 : 근화동   33402 ----------


 ---------- 2020-09-26 00:00:00 : 강남동   33403 ----------


 ---------- 2020-09-26 09:00:00 : 신북읍   33404 ----------


 ---------- 2020-09-26 09:00:00 : 소양동   33406 ----------


 ---------- 2020-09-26 09:00:00 : 북산면   33408 ----------


 ---------- 2020-09-26 10:00:00 : 남산면   33410 ----------


 ---------- 2020-09-26 10:00:00 : 동  면   33411 ----------


 ---------- 2020-09-26 11:00:00 : 남산면   33413 ----------


 ---------- 2020-09-26 15:00:00 : 강남동   33414 ----------


 ---------- 2020-09-26 17:00:00 : 석사동   33415 ----------


 ---------- 2020-09-26 17:00:00 : 강남동   33416 ----------


 ---------- 2020-09-26 17:00:00 : 소양동   33417 ----------


 ---------- 2020-09-26 22:00:00 : 남산면   33419 ----------


 ---------- 2020-09-27 08:00:00 : 석사동   33420 ----------


 ---------- 2020-09-27 10:00:00 : 남산면   33421 ----------


 ---------- 2020-09-27 14:00:00 : 서  면   33423 ----------


 ---------- 2020-09-27 16:00:00 : 근화동   33425 ----------


 ---------- 2020-09-27 16:00:00 : 후평1동   33426 ----------


 ---------- 2020-09-27 16:00:00 : 북산면   33428 ----------


 ---------- 2020-09-27 18:00:00 : 강남동   33429 ----------


 ---------- 2020-09-27 23:00:00 : 효자1동   33430 ----------


 ---------- 2020-09-28 03:00:00 : 서  면   33431 ----------


 ---------- 2020-09-28 08:00:00 : 교  동   33432 ----------


 ---------- 2020-09-28 09:00:00 : 동내면   33433 ----------


 ---------- 2020-09-28 09:00:00 : 신북읍   33434 ----------


 ---------- 2020-09-28 10:00:00 : 사북면   33435 ----------


 ---------- 2020-09-28 11:00:00 : 동  면   33436 ----------


 ---------- 2020-09-28 14:00:00 : 서  면   33437 ----------


 ---------- 2020-09-28 14:00:00 : 퇴계동   33438 ----------


 ---------- 2020-09-28 15:00:00 : 신사우동   33439 ----------


 ---------- 2020-09-28 16:00:00 : 동내면   33441 ----------


 ---------- 2020-09-28 17:00:00 : 강남동   33442 ----------


 ---------- 2020-09-28 18:00:00 : 동  면   33443 ----------


 ---------- 2020-09-28 19:00:00 : 동  면   33444 ----------


 ---------- 2020-09-29 07:00:00 : 동  면   33445 ----------


 ---------- 2020-09-29 08:00:00 : 신북읍   33446 ----------


 ---------- 2020-09-29 11:00:00 : 효자1동   33447 ----------


 ---------- 2020-09-29 12:00:00 : 동내면   33448 ----------


 ---------- 2020-09-29 15:00:00 : 동산면   33449 ----------


 ---------- 2020-09-29 16:00:00 : 신북읍   33450 ----------


 ---------- 2020-09-29 16:00:00 : 북산면   33452 ----------


 ---------- 2020-09-29 17:00:00 : 퇴계동   33453 ----------


 ---------- 2020-09-29 23:00:00 : 강남동   33454 ----------


 ---------- 2020-09-30 04:00:00 : 근화동   33455 ----------


 ---------- 2020-09-30 09:00:00 : 강남동   33456 ----------


 ---------- 2020-09-30 12:00:00 : 석사동   33457 ----------


 ---------- 2020-09-30 12:00:00 : 사북면   33458 ----------


 ---------- 2020-09-30 13:00:00 : 강남동   33459 ----------


 ---------- 2020-09-30 13:00:00 : 서  면   33460 ----------


 ---------- 2020-09-30 14:00:00 : 신북읍   33461 ----------


 ---------- 2020-09-30 19:00:00 : 서  면   33462 ----------


 ---------- 2020-10-01 00:00:00 : 퇴계동   33463 ----------


 ---------- 2020-10-01 15:00:00 : 신북읍   33464 ----------


 ---------- 2020-10-01 17:00:00 : 신동면   33465 ----------


 ---------- 2020-10-01 17:00:00 : 근화동   33467 ----------


 ---------- 2020-10-01 22:00:00 : 퇴계동   33468 ----------


 ---------- 2020-10-01 22:00:00 : 조운동   33469 ----------


 ---------- 2020-10-01 23:00:00 : 근화동   33470 ----------


 ---------- 2020-10-02 03:00:00 : 소양동   33471 ----------


 ---------- 2020-10-02 09:00:00 : 동내면   33472 ----------


 ---------- 2020-10-02 11:00:00 : 동내면   33473 ----------


 ---------- 2020-10-02 15:00:00 : 북산면   33474 ----------


 ---------- 2020-10-02 17:00:00 : 북산면   33475 ----------


 ---------- 2020-10-02 19:00:00 : 북산면   33476 ----------


 ---------- 2020-10-02 22:00:00 : 신사우동   33477 ----------


 ---------- 2020-10-03 09:00:00 : 후평1동   33478 ----------


 ---------- 2020-10-03 10:00:00 : 강남동   33479 ----------


 ---------- 2020-10-03 12:00:00 : 신북읍   33480 ----------


 ---------- 2020-10-03 13:00:00 : 서  면   33481 ----------


 ---------- 2020-10-03 15:00:00 : 동내면   33482 ----------


 ---------- 2020-10-04 03:00:00 : 동  면   33483 ----------


 ---------- 2020-10-04 08:00:00 : 후평1동   33484 ----------


 ---------- 2020-10-04 10:00:00 : 신동면   33485 ----------


 ---------- 2020-10-04 10:00:00 : 신사우동   33486 ----------


 ---------- 2020-10-04 10:00:00 : 신북읍   33487 ----------


 ---------- 2020-10-04 16:00:00 : 북산면   33490 ----------


 ---------- 2020-10-04 18:00:00 : 동  면   33491 ----------


 ---------- 2020-10-05 03:00:00 : 교  동   33492 ----------


 ---------- 2020-10-05 10:00:00 : 남산면   33494 ----------


 ---------- 2020-10-05 10:00:00 : 동  면   33496 ----------


 ---------- 2020-10-05 11:00:00 : 퇴계동   33497 ----------


 ---------- 2020-10-05 14:00:00 : 강남동   33498 ----------


 ---------- 2020-10-05 17:00:00 : 동내면   33499 ----------


 ---------- 2020-10-05 19:00:00 : 동내면   33501 ----------


 ---------- 2020-10-06 08:00:00 : 신북읍   33502 ----------


 ---------- 2020-10-06 10:00:00 : 서  면   33503 ----------


 ---------- 2020-10-06 10:00:00 : 동내면   33504 ----------


 ---------- 2020-10-06 12:00:00 : 남산면   33505 ----------


 ---------- 2020-10-06 13:00:00 : 동내면   33506 ----------


 ---------- 2020-10-06 14:00:00 : 후평1동   33507 ----------


 ---------- 2020-10-06 17:00:00 : 남  면   33509 ----------


 ---------- 2020-10-06 20:00:00 : 소양동   33510 ----------


 ---------- 2020-10-07 10:00:00 : 남산면   33511 ----------

 ---------- 2020-10-07 12:00:00 : 동산면   33512 ----------


 ---------- 2020-10-07 15:00:00 : 서  면   33513 ----------


 ---------- 2020-10-07 16:00:00 : 동내면   33514 ----------


 ---------- 2020-10-07 17:00:00 : 후평1동   33515 ----------


 ---------- 2020-10-07 18:00:00 : 신사우동   33517 ----------


 ---------- 2020-10-07 23:00:00 : 조운동   33518 ----------


 ---------- 2020-10-08 01:00:00 : 효자1동   33519 ----------


 ---------- 2020-10-08 06:00:00 : 효자1동   33520 ----------


 ---------- 2020-10-08 10:00:00 : 신북읍   33521 ----------


 ---------- 2020-10-08 13:00:00 : 남산면   33523 ----------


 ---------- 2020-10-08 14:00:00 : 남산면   33524 ----------


 ---------- 2020-10-08 14:00:00 : 신북읍   33525 ----------


 ---------- 2020-10-08 15:00:00 : 강남동   33527 ----------


 ---------- 2020-10-08 15:00:00 : 동  면   33528 ----------


 ---------- 2020-10-09 09:00:00 : 동  면   33529 ----------


 ---------- 2020-10-09 10:00:00 : 석사동   33531 ----------


 ---------- 2020-10-09 10:00:00 : 남산면   33532 ----------


 ---------- 2020-10-09 11:00:00 : 남산면   33533 ----------


 ---------- 2020-10-09 13:00:00 : 신북읍   33534 ----------


 ---------- 2020-10-09 16:00:00 : 근화동   33535 ----------


 ---------- 2020-10-09 16:00:00 : 후평1동   33536 ----------


 ---------- 2020-10-09 19:00:00 : 사북면   33537 ----------


 ---------- 2020-10-10 08:00:00 : 서  면   33539 ----------


 ---------- 2020-10-10 09:00:00 : 서  면   33541 ----------


 ---------- 2020-10-10 09:00:00 : 근화동   33542 ----------


 ---------- 2020-10-10 12:00:00 : 서  면   33543 ----------


 ---------- 2020-10-10 14:00:00 : 남산면   33544 ----------


 ---------- 2020-10-10 15:00:00 : 강남동   33545 ----------


 ---------- 2020-10-10 16:00:00 : 남  면   33546 ----------


 ---------- 2020-10-10 17:00:00 : 신동면   33547 ----------


 ---------- 2020-10-10 17:00:00 : 신사우동   33548 ----------


 ---------- 2020-10-10 18:00:00 : 후평1동   33549 ----------


 ---------- 2020-10-11 10:00:00 : 동내면   33550 ----------


 ---------- 2020-10-11 10:00:00 : 남산면   33551 ----------


 ---------- 2020-10-11 13:00:00 : 석사동   33552 ----------


 ---------- 2020-10-11 13:00:00 : 강남동   33553 ----------


 ---------- 2020-10-11 13:00:00 : 서  면   33554 ----------


 ---------- 2020-10-11 13:00:00 : 근화동   33555 ----------


 ---------- 2020-10-11 13:00:00 : 후평1동   33556 ----------


 ---------- 2020-10-11 15:00:00 : 동  면   33557 ----------


 ---------- 2020-10-11 16:00:00 : 동  면   33558 ----------


 ---------- 2020-10-11 23:00:00 : 석사동   33559 ----------


 ---------- 2020-10-12 10:00:00 : 신북읍   33560 ----------


 ---------- 2020-10-12 10:00:00 : 후평1동   33561 ----------


 ---------- 2020-10-12 11:00:00 : 동내면   33562 ----------


 ---------- 2020-10-12 11:00:00 : 남산면   33563 ----------


 ---------- 2020-10-12 13:00:00 : 강남동   33564 ----------


 ---------- 2020-10-12 15:00:00 : 석사동   33565 ----------


 ---------- 2020-10-12 15:00:00 : 신북읍   33566 ----------


 ---------- 2020-10-12 16:00:00 : 퇴계동   33568 ----------


 ---------- 2020-10-12 21:00:00 : 신사우동   33569 ----------


 ---------- 2020-10-13 02:00:00 : 효자1동   33570 ----------


 ---------- 2020-10-13 09:00:00 : 동산면   33571 ----------


 ---------- 2020-10-13 11:00:00 : 동  면   33572 ----------


 ---------- 2020-10-13 12:00:00 : 석사동   33573 ----------


 ---------- 2020-10-13 13:00:00 : 석사동   33574 ----------


 ---------- 2020-10-13 13:00:00 : 신동면   33575 ----------


 ---------- 2020-10-13 14:00:00 : 동  면   33576 ----------


 ---------- 2020-10-13 15:00:00 : 동내면   33577 ----------


 ---------- 2020-10-13 15:00:00 : 근화동   33578 ----------


 ---------- 2020-10-13 15:00:00 : 동  면   33579 ----------


 ---------- 2020-10-13 18:00:00 : 교  동   33580 ----------


 ---------- 2020-10-13 21:00:00 : 후평1동   33581 ----------


 ---------- 2020-10-14 00:00:00 : 신동면   33583 ----------


 ---------- 2020-10-14 10:00:00 : 퇴계동   33584 ----------


 ---------- 2020-10-15 06:00:00 : 동  면   33585 ----------


 ---------- 2020-10-15 07:00:00 : 근화동   33586 ----------


 ---------- 2020-10-15 10:00:00 : 신동면   33587 ----------


 ---------- 2020-10-15 18:00:00 : 소양동   33588 ----------


 ---------- 2020-10-15 23:00:00 : 퇴계동   33590 ----------


 ---------- 2020-10-16 07:00:00 : 석사동   33591 ----------


 ---------- 2020-10-16 08:00:00 : 강남동   33592 ----------


 ---------- 2020-10-16 10:00:00 : 강남동   33593 ----------


 ---------- 2020-10-16 12:00:00 : 효자1동   33594 ----------


 ---------- 2020-10-16 13:00:00 : 서  면   33595 ----------


 ---------- 2020-10-16 17:00:00 : 북산면   33596 ----------


 ---------- 2020-10-16 21:00:00 : 퇴계동   33597 ----------


 ---------- 2020-10-17 08:00:00 : 후평1동   33598 ----------


 ---------- 2020-10-17 10:00:00 : 남산면   33599 ----------


 ---------- 2020-10-17 12:00:00 : 서  면   33600 ----------


 ---------- 2020-10-17 12:00:00 : 소양동   33601 ----------


 ---------- 2020-10-17 13:00:00 : 강남동   33603 ----------


 ---------- 2020-10-17 13:00:00 : 북산면   33604 ----------


 ---------- 2020-10-17 14:00:00 : 강남동   33606 ----------


 ---------- 2020-10-17 14:00:00 : 서  면   33607 ----------


 ---------- 2020-10-17 17:00:00 : 소양동   33608 ----------


 ---------- 2020-10-17 17:00:00 : 약사명동   33609 ----------


 ---------- 2020-10-18 01:00:00 : 후평1동   33610 ----------


 ---------- 2020-10-18 09:00:00 : 강남동   33611 ----------


 ---------- 2020-10-18 10:00:00 : 신북읍   33612 ----------


 ---------- 2020-10-18 11:00:00 : 서  면   33613 ----------


 ---------- 2020-10-18 11:00:00 : 동내면   33615 ----------


 ---------- 2020-10-18 12:00:00 : 신사우동   33616 ----------


 ---------- 2020-10-18 12:00:00 : 후평1동   33617 ----------


 ---------- 2020-10-18 13:00:00 : 동산면   33618 ----------


 ---------- 2020-10-18 15:00:00 : 동산면   33619 ----------


 ---------- 2020-10-18 16:00:00 : 후평1동   33620 ----------


 ---------- 2020-10-18 16:00:00 : 북산면   33621 ----------


 ---------- 2020-10-19 00:00:00 : 효자1동   33622 ----------


 ---------- 2020-10-19 04:00:00 : 동내면   33624 ----------


 ---------- 2020-10-19 10:00:00 : 퇴계동   33625 ----------


 ---------- 2020-10-19 13:00:00 : 사북면   33626 ----------


 ---------- 2020-10-19 14:00:00 : 신동면   33627 ----------


 ---------- 2020-10-19 14:00:00 : 서  면   33628 ----------


 ---------- 2020-10-19 14:00:00 : 신사우동   33629 ----------


 ---------- 2020-10-19 15:00:00 : 사북면   33630 ----------


 ---------- 2020-10-19 15:00:00 : 퇴계동   33631 ----------


 ---------- 2020-10-19 16:00:00 : 서  면   33632 ----------


 ---------- 2020-10-20 08:00:00 : 신동면   33633 ----------


 ---------- 2020-10-20 08:00:00 : 동  면   33634 ----------


 ---------- 2020-10-20 09:00:00 : 신동면   33635 ----------


 ---------- 2020-10-20 10:00:00 : 석사동   33636 ----------


 ---------- 2020-10-20 10:00:00 : 남  면   33638 ----------


 ---------- 2020-10-20 11:00:00 : 효자1동   33640 ----------


 ---------- 2020-10-20 12:00:00 : 동산면   33641 ----------


 ---------- 2020-10-20 13:00:00 : 남산면   33642 ----------


 ---------- 2020-10-20 13:00:00 : 신북읍   33643 ----------


 ---------- 2020-10-20 14:00:00 : 동내면   33644 ----------


 ---------- 2020-10-20 14:00:00 : 신사우동   33645 ----------


 ---------- 2020-10-20 15:00:00 : 신북읍   33646 ----------


 ---------- 2020-10-20 16:00:00 : 신북읍   33647 ----------


 ---------- 2020-10-20 17:00:00 : 동  면   33648 ----------


 ---------- 2020-10-21 08:00:00 : 신북읍   33649 ----------


 ---------- 2020-10-21 09:00:00 : 북산면   33650 ----------


 ---------- 2020-10-21 11:00:00 : 효자1동   33651 ----------


 ---------- 2020-10-21 12:00:00 : 근화동   33652 ----------


 ---------- 2020-10-21 12:00:00 : 후평1동   33653 ----------


 ---------- 2020-10-21 13:00:00 : 효자1동   33654 ----------


 ---------- 2020-10-21 15:00:00 : 퇴계동   33655 ----------


 ---------- 2020-10-21 16:00:00 : 동내면   33656 ----------


 ---------- 2020-10-21 16:00:00 : 후평1동   33657 ----------


 ---------- 2020-10-21 18:00:00 : 신사우동   33658 ----------


 ---------- 2020-10-22 01:00:00 : 동  면   33659 ----------


 ---------- 2020-10-22 04:00:00 : 석사동   33661 ----------


 ---------- 2020-10-22 09:00:00 : 서  면   33662 ----------


 ---------- 2020-10-22 10:00:00 : 동내면   33663 ----------

 ---------- 2020-10-22 14:00:00 : 퇴계동   33664 ----------


 ---------- 2020-10-22 15:00:00 : 소양동   33665 ----------


 ---------- 2020-10-22 17:00:00 : 동산면   33666 ----------


 ---------- 2020-10-22 19:00:00 : 후평1동   33667 ----------


 ---------- 2020-10-23 01:00:00 : 후평1동   33668 ----------


 ---------- 2020-10-23 14:00:00 : 효자1동   33669 ----------


 ---------- 2020-10-23 18:00:00 : 석사동   33671 ----------


 ---------- 2020-10-23 18:00:00 : 효자1동   33672 ----------


 ---------- 2020-10-23 18:00:00 : 북산면   33673 ----------


 ---------- 2020-10-23 20:00:00 : 석사동   33674 ----------


 ---------- 2020-10-24 01:00:00 : 동내면   33675 ----------


 ---------- 2020-10-24 01:00:00 : 후평1동   33676 ----------


 ---------- 2020-10-24 13:00:00 : 동  면   33677 ----------


 ---------- 2020-10-24 13:00:00 : 퇴계동   33678 ----------


 ---------- 2020-10-24 15:00:00 : 후평1동   33679 ----------


 ---------- 2020-10-24 18:00:00 : 신동면   33680 ----------


 ---------- 2020-10-24 18:00:00 : 서  면   33681 ----------


 ---------- 2020-10-24 18:00:00 : 후평1동   33683 ----------


 ---------- 2020-10-24 19:00:00 : 신북읍   33684 ----------


 ---------- 2020-10-25 09:00:00 : 석사동   33685 ----------


 ---------- 2020-10-25 11:00:00 : 석사동   33686 ----------


 ---------- 2020-10-25 16:00:00 : 동내면   33688 ----------


 ---------- 2020-10-25 18:00:00 : 신사우동   33690 ----------


 ---------- 2020-10-26 01:00:00 : 퇴계동   33691 ----------


 ---------- 2020-10-26 17:00:00 : 서  면   33692 ----------


 ---------- 2020-10-26 19:00:00 : 석사동   33693 ----------


 ---------- 2020-10-27 02:00:00 : 신동면   33695 ----------


 ---------- 2020-10-27 07:00:00 : 남  면   33696 ----------


 ---------- 2020-10-27 09:00:00 : 북산면   33697 ----------


 ---------- 2020-10-27 12:00:00 : 강남동   33698 ----------


 ---------- 2020-10-27 13:00:00 : 근화동   33699 ----------


 ---------- 2020-10-27 14:00:00 : 약사명동   33702 ----------


 ---------- 2020-10-27 14:00:00 : 동  면   33703 ----------


 ---------- 2020-10-27 16:00:00 : 석사동   33704 ----------


 ---------- 2020-10-27 16:00:00 : 퇴계동   33705 ----------


 ---------- 2020-10-27 17:00:00 : 후평1동   33706 ----------


 ---------- 2020-10-28 00:00:00 : 남산면   33707 ----------


 ---------- 2020-10-28 08:00:00 : 후평1동   33708 ----------


 ---------- 2020-10-28 10:00:00 : 석사동   33709 ----------


 ---------- 2020-10-28 13:00:00 : 신북읍   33710 ----------


 ---------- 2020-10-28 16:00:00 : 후평1동   33711 ----------


 ---------- 2020-10-28 19:00:00 : 효자1동   33712 ----------


 ---------- 2020-10-29 05:00:00 : 석사동   33713 ----------


 ---------- 2020-10-29 12:00:00 : 신사우동   33714 ----------


 ---------- 2020-10-29 15:00:00 : 퇴계동   33715 ----------


 ---------- 2020-10-29 15:00:00 : 동산면   33717 ----------


 ---------- 2020-10-29 22:00:00 : 동내면   33718 ----------


 ---------- 2020-10-30 00:00:00 : 근화동   33719 ----------


 ---------- 2020-10-30 21:00:00 : 신사우동   33720 ----------


 ---------- 2020-10-31 10:00:00 : 서  면   33721 ----------


 ---------- 2020-10-31 12:00:00 : 퇴계동   33722 ----------


 ---------- 2020-10-31 13:00:00 : 신동면   33723 ----------


 ---------- 2020-10-31 13:00:00 : 퇴계동   33725 ----------


 ---------- 2020-10-31 15:00:00 : 서  면   33726 ----------


 ---------- 2020-10-31 20:00:00 : 신사우동   33727 ----------


 ---------- 2020-11-01 00:00:00 : 동내면   33730 ----------


 ---------- 2020-11-01 15:00:00 : 후평1동   33731 ----------


 ---------- 2020-11-01 16:00:00 : 효자1동   33732 ----------


 ---------- 2020-11-01 21:00:00 : 동내면   33734 ----------


 ---------- 2020-11-02 02:00:00 : 동내면   33737 ----------


 ---------- 2020-11-02 08:00:00 : 동  면   33738 ----------


 ---------- 2020-11-02 09:00:00 : 후평1동   33739 ----------


 ---------- 2020-11-02 10:00:00 : 남산면   33740 ----------


 ---------- 2020-11-02 10:00:00 : 퇴계동   33741 ----------


 ---------- 2020-11-02 13:00:00 : 동내면   33742 ----------


 ---------- 2020-11-02 13:00:00 : 동  면   33743 ----------


 ---------- 2020-11-02 16:00:00 : 신사우동   33745 ----------


 ---------- 2020-11-03 06:00:00 : 남산면   33746 ----------


 ---------- 2020-11-03 07:00:00 : 동내면   33748 ----------


 ---------- 2020-11-03 08:00:00 : 후평1동   33749 ----------


 ---------- 2020-11-03 09:00:00 : 북산면   33750 ----------


 ---------- 2020-11-03 12:00:00 : 신북읍   33751 ----------


 ---------- 2020-11-03 17:00:00 : 후평1동   33752 ----------


 ---------- 2020-11-03 19:00:00 : 후평1동   33753 ----------


 ---------- 2020-11-03 20:00:00 : 효자1동   33754 ----------


 ---------- 2020-11-04 06:00:00 : 북산면   33756 ----------


 ---------- 2020-11-04 07:00:00 : 북산면   33757 ----------


 ---------- 2020-11-04 08:00:00 : 동산면   33759 ----------


 ---------- 2020-11-04 12:00:00 : 신사우동   33760 ----------


 ---------- 2020-11-04 17:00:00 : 동  면   33761 ----------


 ---------- 2020-11-04 19:00:00 : 동  면   33762 ----------


 ---------- 2020-11-05 07:00:00 : 신북읍   33763 ----------


 ---------- 2020-11-05 08:00:00 : 신사우동   33764 ----------


 ---------- 2020-11-05 09:00:00 : 동  면   33766 ----------


 ---------- 2020-11-05 14:00:00 : 신북읍   33768 ----------


 ---------- 2020-11-05 19:00:00 : 동  면   33769 ----------


 ---------- 2020-11-05 19:00:00 : 퇴계동   33770 ----------


 ---------- 2020-11-05 22:00:00 : 강남동   33772 ----------


 ---------- 2020-11-05 23:00:00 : 후평1동   33773 ----------


 ---------- 2020-11-06 07:00:00 : 신북읍   33774 ----------


 ---------- 2020-11-06 10:00:00 : 신북읍   33775 ----------


 ---------- 2020-11-06 12:00:00 : 퇴계동   33776 ----------


 ---------- 2020-11-06 14:00:00 : 강남동   33777 ----------


 ---------- 2020-11-06 17:00:00 : 효자1동   33778 ----------


 ---------- 2020-11-06 20:00:00 : 효자1동   33779 ----------


 ---------- 2020-11-06 22:00:00 : 효자1동   33781 ----------


 ---------- 2020-11-07 02:00:00 : 후평1동   33782 ----------


 ---------- 2020-11-07 05:00:00 : 남산면   33783 ----------


 ---------- 2020-11-07 07:00:00 : 신북읍   33784 ----------


 ---------- 2020-11-07 10:00:00 : 효자1동   33786 ----------


 ---------- 2020-11-07 11:00:00 : 소양동   33789 ----------


 ---------- 2020-11-07 12:00:00 : 근화동   33790 ----------


 ---------- 2020-11-07 12:00:00 : 신사우동   33791 ----------


 ---------- 2020-11-07 13:00:00 : 효자1동   33793 ----------


 ---------- 2020-11-07 15:00:00 : 후평1동   33794 ----------


 ---------- 2020-11-07 16:00:00 : 효자1동   33796 ----------


 ---------- 2020-11-07 16:00:00 : 신북읍   33797 ----------


 ---------- 2020-11-07 18:00:00 : 강남동   33798 ----------


 ---------- 2020-11-07 18:00:00 : 소양동   33799 ----------


 ---------- 2020-11-07 19:00:00 : 석사동   33803 ----------


 ---------- 2020-11-08 12:00:00 : 신북읍   33804 ----------


 ---------- 2020-11-08 14:00:00 : 석사동   33806 ----------


 ---------- 2020-11-08 17:00:00 : 남산면   33807 ----------


 ---------- 2020-11-08 23:00:00 : 효자1동   33808 ----------


 ---------- 2020-11-09 10:00:00 : 남  면   33809 ----------


 ---------- 2020-11-09 14:00:00 : 강남동   33810 ----------


 ---------- 2020-11-09 22:00:00 : 후평1동   33812 ----------


 ---------- 2020-11-10 01:00:00 : 동내면   33814 ----------


 ---------- 2020-11-10 05:00:00 : 석사동   33816 ----------


 ---------- 2020-11-10 08:00:00 : 신사우동   33817 ----------


 ---------- 2020-11-10 11:00:00 : 신북읍   33819 ----------


 ---------- 2020-11-10 13:00:00 : 소양동   33820 ----------


 ---------- 2020-11-10 14:00:00 : 동산면   33822 ----------


 ---------- 2020-11-10 15:00:00 : 서  면   33823 ----------


 ---------- 2020-11-10 16:00:00 : 남  면   33824 ----------


 ---------- 2020-11-10 22:00:00 : 효자1동   33825 ----------


 ---------- 2020-11-11 08:00:00 : 효자1동   33826 ----------


 ---------- 2020-11-11 11:00:00 : 동내면   33827 ----------


 ---------- 2020-11-11 11:00:00 : 남산면   33828 ----------


 ---------- 2020-11-11 12:00:00 : 후평1동   33829 ----------


 ---------- 2020-11-11 17:00:00 : 석사동   33830 ----------


 ---------- 2020-11-12 17:00:00 : 동내면   33832 ----------


 ---------- 2020-11-12 19:00:00 : 후평1동   33833 ----------


 ---------- 2020-11-13 01:00:00 : 교  동   33834 ----------


 ---------- 2020-11-13 09:00:00 : 석사동   33835 ----------


 ---------- 2020-11-13 10:00:00 : 남  면   33836 ----------

 ---------- 2020-11-13 10:00:00 : 신사우동   33837 ----------


 ---------- 2020-11-13 10:00:00 : 후평1동   33838 ----------


 ---------- 2020-11-13 17:00:00 : 서  면   33839 ----------


 ---------- 2020-11-13 21:00:00 : 신북읍   33840 ----------


 ---------- 2020-11-13 22:00:00 : 후평1동   33842 ----------


 ---------- 2020-11-13 23:00:00 : 석사동   33843 ----------


 ---------- 2020-11-13 23:00:00 : 서  면   33845 ----------


 ---------- 2020-11-14 09:00:00 : 석사동   33846 ----------


 ---------- 2020-11-14 10:00:00 : 동산면   33847 ----------


 ---------- 2020-11-14 12:00:00 : 북산면   33848 ----------


 ---------- 2020-11-14 14:00:00 : 강남동   33849 ----------


 ---------- 2020-11-14 15:00:00 : 남산면   33851 ----------


 ---------- 2020-11-14 23:00:00 : 석사동   33853 ----------


 ---------- 2020-11-15 05:00:00 : 후평1동   33854 ----------


 ---------- 2020-11-15 11:00:00 : 동산면   33855 ----------


 ---------- 2020-11-15 23:00:00 : 효자1동   33856 ----------


 ---------- 2020-11-16 00:00:00 : 석사동   33859 ----------


 ---------- 2020-11-16 00:00:00 : 신북읍   33860 ----------


 ---------- 2020-11-16 02:00:00 : 효자1동   33861 ----------


 ---------- 2020-11-16 03:00:00 : 교  동   33862 ----------


 ---------- 2020-11-16 12:00:00 : 교  동   33863 ----------


 ---------- 2020-11-16 15:00:00 : 동산면   33865 ----------


 ---------- 2020-11-16 17:00:00 : 후평1동   33866 ----------


 ---------- 2020-11-16 21:00:00 : 신동면   33867 ----------


 ---------- 2020-11-17 07:00:00 : 퇴계동   33869 ----------


 ---------- 2020-11-17 10:00:00 : 효자1동   33870 ----------


 ---------- 2020-11-17 12:00:00 : 남산면   33871 ----------


 ---------- 2020-11-17 15:00:00 : 동  면   33872 ----------


 ---------- 2020-11-17 16:00:00 : 남산면   33874 ----------


 ---------- 2020-11-18 12:00:00 : 동내면   33876 ----------


 ---------- 2020-11-18 16:00:00 : 후평1동   33877 ----------


 ---------- 2020-11-19 07:00:00 : 동  면   33878 ----------


 ---------- 2020-11-19 08:00:00 : 사북면   33879 ----------


 ---------- 2020-11-19 09:00:00 : 동산면   33881 ----------


 ---------- 2020-11-19 16:00:00 : 효자1동   33883 ----------


 ---------- 2020-11-20 00:00:00 : 후평1동   33884 ----------


 ---------- 2020-11-20 16:00:00 : 후평1동   33885 ----------


 ---------- 2020-11-21 02:00:00 : 효자1동   33886 ----------


 ---------- 2020-11-21 04:00:00 : 효자1동   33887 ----------


 ---------- 2020-11-21 10:00:00 : 신북읍   33888 ----------


 ---------- 2020-11-21 17:00:00 : 동  면   33889 ----------


 ---------- 2020-11-21 18:00:00 : 동산면   33890 ----------


 ---------- 2020-11-22 16:00:00 : 근화동   33891 ----------


 ---------- 2020-11-22 21:00:00 : 동내면   33893 ----------


 ---------- 2020-11-23 03:00:00 : 소양동   33895 ----------


 ---------- 2020-11-23 06:00:00 : 남산면   33898 ----------


 ---------- 2020-11-23 08:00:00 : 동내면   33900 ----------


 ---------- 2020-11-23 10:00:00 : 신북읍   33901 ----------


 ---------- 2020-11-23 14:00:00 : 서  면   33902 ----------


 ---------- 2020-11-23 14:00:00 : 후평1동   33903 ----------


 ---------- 2020-11-23 22:00:00 : 동  면   33904 ----------


 ---------- 2020-11-24 15:00:00 : 강남동   33905 ----------


 ---------- 2020-11-24 18:00:00 : 후평1동   33906 ----------


 ---------- 2020-11-24 19:00:00 : 신사우동   33907 ----------


 ---------- 2020-11-25 07:00:00 : 효자1동   33908 ----------


 ---------- 2020-11-25 10:00:00 : 효자1동   33910 ----------


 ---------- 2020-11-25 10:00:00 : 후평1동   33911 ----------


 ---------- 2020-11-25 14:00:00 : 후평1동   33912 ----------


 ---------- 2020-11-25 16:00:00 : 효자1동   33914 ----------


 ---------- 2020-11-25 19:00:00 : 효자1동   33915 ----------


 ---------- 2020-11-25 19:00:00 : 동산면   33917 ----------


 ---------- 2020-11-26 11:00:00 : 신북읍   33919 ----------


 ---------- 2020-11-26 13:00:00 : 신북읍   33920 ----------


 ---------- 2020-11-26 16:00:00 : 동  면   33921 ----------


 ---------- 2020-11-26 18:00:00 : 신사우동   33922 ----------


 ---------- 2020-11-26 21:00:00 : 조운동   33923 ----------


 ---------- 2020-11-27 11:00:00 : 효자1동   33925 ----------


 ---------- 2020-11-27 14:00:00 : 강남동   33927 ----------


 ---------- 2020-11-27 16:00:00 : 남산면   33929 ----------


 ---------- 2020-11-27 17:00:00 : 남  면   33933 ----------


 ---------- 2020-11-27 20:00:00 : 동  면   33934 ----------


 ---------- 2020-11-27 22:00:00 : 강남동   33935 ----------


 ---------- 2020-11-28 07:00:00 : 동  면   33936 ----------


 ---------- 2020-11-28 09:00:00 : 석사동   33938 ----------


 ---------- 2020-11-28 09:00:00 : 신동면   33941 ----------


 ---------- 2020-11-28 14:00:00 : 퇴계동   33942 ----------


 ---------- 2020-11-28 14:00:00 : 북산면   33944 ----------


 ---------- 2020-11-28 15:00:00 : 남산면   33946 ----------


 ---------- 2020-11-28 16:00:00 : 석사동   33947 ----------


 ---------- 2020-11-28 17:00:00 : 후평1동   33948 ----------


 ---------- 2020-11-29 01:00:00 : 후평1동   33949 ----------


 ---------- 2020-11-30 09:00:00 : 사북면   33950 ----------


 ---------- 2020-11-30 09:00:00 : 동산면   33951 ----------


 ---------- 2020-11-30 10:00:00 : 남산면   33952 ----------


 ---------- 2020-11-30 13:00:00 : 신사우동   33953 ----------


 ---------- 2020-11-30 13:00:00 : 동  면   33954 ----------


 ---------- 2020-11-30 15:00:00 : 남산면   33956 ----------


 ---------- 2020-11-30 19:00:00 : 동  면   33958 ----------


 ---------- 2020-11-30 23:00:00 : 석사동   33959 ----------


 ---------- 2020-12-01 05:00:00 : 신북읍   33961 ----------


 ---------- 2020-12-01 08:00:00 : 서  면   33962 ----------


 ---------- 2020-12-01 09:00:00 : 동  면   33964 ----------


 ---------- 2020-12-01 15:00:00 : 서  면   33966 ----------


 ---------- 2020-12-01 18:00:00 : 강남동   33968 ----------


 ---------- 2020-12-02 07:00:00 : 신사우동   33969 ----------


 ---------- 2020-12-02 09:00:00 : 후평1동   33970 ----------


 ---------- 2020-12-02 13:00:00 : 남산면   33972 ----------


 ---------- 2020-12-02 16:00:00 : 동내면   33974 ----------


 ---------- 2020-12-03 09:00:00 : 석사동   33975 ----------


 ---------- 2020-12-03 15:00:00 : 신동면   33977 ----------


 ---------- 2020-12-03 15:00:00 : 강남동   33978 ----------


 ---------- 2020-12-03 22:00:00 : 효자1동   33980 ----------


 ---------- 2020-12-04 02:00:00 : 동내면   33982 ----------


 ---------- 2020-12-04 13:00:00 : 동내면   33984 ----------


 ---------- 2020-12-05 08:00:00 : 강남동   33985 ----------


 ---------- 2020-12-05 10:00:00 : 동  면   33986 ----------


 ---------- 2020-12-05 11:00:00 : 효자1동   33987 ----------


 ---------- 2020-12-05 13:00:00 : 남산면   33989 ----------


 ---------- 2020-12-05 13:00:00 : 동  면   33990 ----------


 ---------- 2020-12-05 16:00:00 : 동내면   33991 ----------


 ---------- 2020-12-05 16:00:00 : 남산면   33992 ----------


 ---------- 2020-12-05 18:00:00 : 신북읍   33993 ----------


 ---------- 2020-12-05 18:00:00 : 소양동   33994 ----------


 ---------- 2020-12-05 21:00:00 : 남산면   33996 ----------


 ---------- 2020-12-06 08:00:00 : 근화동   33999 ----------


 ---------- 2020-12-06 13:00:00 : 신북읍   34000 ----------


 ---------- 2020-12-06 18:00:00 : 동내면   34001 ----------


 ---------- 2020-12-07 09:00:00 : 신북읍   34002 ----------


 ---------- 2020-12-07 12:00:00 : 후평1동   34003 ----------


 ---------- 2020-12-07 17:00:00 : 퇴계동   34004 ----------


 ---------- 2020-12-07 20:00:00 : 소양동   34005 ----------


 ---------- 2020-12-08 04:00:00 : 퇴계동   34006 ----------


 ---------- 2020-12-09 11:00:00 : 후평1동   34007 ----------


 ---------- 2020-12-09 13:00:00 : 효자1동   34010 ----------


 ---------- 2020-12-10 17:00:00 : 신북읍   34012 ----------


 ---------- 2020-12-10 22:00:00 : 석사동   34014 ----------


 ---------- 2020-12-11 09:00:00 : 강남동   34015 ----------


 ---------- 2020-12-11 10:00:00 : 근화동   34017 ----------


 ---------- 2020-12-11 11:00:00 : 동내면   34019 ----------


 ---------- 2020-12-11 14:00:00 : 강남동   34020 ----------


 ---------- 2020-12-11 14:00:00 : 서  면   34021 ----------


 ---------- 2020-12-11 19:00:00 : 동내면   34022 ----------


 ---------- 2020-12-12 08:00:00 : 서  면   34023 ----------


 ---------- 2020-12-12 11:00:00 : 신북읍   34024 ----------


 ---------- 2020-12-12 11:00:00 : 퇴계동   34026 ----------


 ---------- 2020-12-12 14:00:00 : 동내면   34027 ----------

 ---------- 2020-12-12 15:00:00 : 교  동   34028 ----------


 ---------- 2020-12-12 19:00:00 : 동  면   34029 ----------


 ---------- 2020-12-12 20:00:00 : 후평1동   34030 ----------


 ---------- 2020-12-13 01:00:00 : 동  면   34032 ----------


 ---------- 2020-12-13 08:00:00 : 동산면   34033 ----------


 ---------- 2020-12-13 11:00:00 : 동  면   34034 ----------


 ---------- 2020-12-13 18:00:00 : 동내면   34036 ----------


 ---------- 2020-12-13 20:00:00 : 소양동   34037 ----------


 ---------- 2020-12-14 08:00:00 : 후평1동   34038 ----------


 ---------- 2020-12-14 15:00:00 : 퇴계동   34039 ----------


 ---------- 2020-12-14 17:00:00 : 신북읍   34040 ----------


 ---------- 2020-12-14 23:00:00 : 동산면   34041 ----------


 ---------- 2020-12-15 05:00:00 : 동  면   34042 ----------


 ---------- 2020-12-15 09:00:00 : 신북읍   34043 ----------


 ---------- 2020-12-15 11:00:00 : 효자1동   34044 ----------


 ---------- 2020-12-15 12:00:00 : 남산면   34045 ----------


 ---------- 2020-12-15 17:00:00 : 신사우동   34047 ----------


 ---------- 2020-12-15 17:00:00 : 동  면   34049 ----------


 ---------- 2020-12-15 20:00:00 : 퇴계동   34050 ----------


 ---------- 2020-12-15 22:00:00 : 후평1동   34051 ----------


 ---------- 2020-12-16 03:00:00 : 효자1동   34052 ----------


 ---------- 2020-12-16 06:00:00 : 소양동   34053 ----------


 ---------- 2020-12-16 07:00:00 : 후평1동   34054 ----------


 ---------- 2020-12-16 10:00:00 : 남산면   34055 ----------


 ---------- 2020-12-16 10:00:00 : 소양동   34056 ----------


 ---------- 2020-12-16 12:00:00 : 석사동   34058 ----------


 ---------- 2020-12-16 12:00:00 : 신사우동   34059 ----------


 ---------- 2020-12-16 14:00:00 : 서  면   34060 ----------


 ---------- 2020-12-16 15:00:00 : 동  면   34061 ----------


 ---------- 2020-12-16 17:00:00 : 후평1동   34062 ----------


 ---------- 2020-12-16 19:00:00 : 석사동   34064 ----------


 ---------- 2020-12-16 19:00:00 : 후평1동   34065 ----------


 ---------- 2020-12-17 05:00:00 : 퇴계동   34066 ----------


 ---------- 2020-12-17 08:00:00 : 신북읍   34067 ----------


 ---------- 2020-12-18 00:00:00 : 후평1동   34068 ----------


 ---------- 2020-12-18 10:00:00 : 신북읍   34069 ----------


 ---------- 2020-12-18 11:00:00 : 석사동   34071 ----------


 ---------- 2020-12-18 14:00:00 : 남산면   34072 ----------


 ---------- 2020-12-18 17:00:00 : 후평1동   34073 ----------


 ---------- 2020-12-18 18:00:00 : 퇴계동   34075 ----------


 ---------- 2020-12-18 21:00:00 : 후평1동   34077 ----------


 ---------- 2020-12-18 22:00:00 : 퇴계동   34078 ----------


 ---------- 2020-12-19 07:00:00 : 동산면   34083 ----------


 ---------- 2020-12-19 11:00:00 : 강남동   34084 ----------


 ---------- 2020-12-19 14:00:00 : 동산면   34085 ----------


 ---------- 2020-12-19 15:00:00 : 효자1동   34087 ----------


 ---------- 2020-12-19 17:00:00 : 신동면   34088 ----------


 ---------- 2020-12-19 17:00:00 : 효자1동   34089 ----------


 ---------- 2020-12-19 20:00:00 : 신사우동   34090 ----------


 ---------- 2020-12-19 23:00:00 : 석사동   34091 ----------


 ---------- 2020-12-19 23:00:00 : 후평1동   34092 ----------


 ---------- 2020-12-20 07:00:00 : 석사동   34093 ----------


 ---------- 2020-12-20 08:00:00 : 신사우동   34094 ----------


 ---------- 2020-12-20 11:00:00 : 소양동   34095 ----------


 ---------- 2020-12-20 12:00:00 : 동산면   34097 ----------


 ---------- 2020-12-20 14:00:00 : 서  면   34098 ----------


 ---------- 2020-12-20 19:00:00 : 동내면   34099 ----------


 ---------- 2020-12-20 20:00:00 : 효자1동   34100 ----------


 ---------- 2020-12-21 13:00:00 : 신북읍   34101 ----------


 ---------- 2020-12-21 18:00:00 : 신사우동   34103 ----------


 ---------- 2020-12-21 18:00:00 : 북산면   34106 ----------


 ---------- 2020-12-21 20:00:00 : 교  동   34107 ----------


 ---------- 2020-12-22 04:00:00 : 동내면   34108 ----------


 ---------- 2020-12-22 04:00:00 : 후평1동   34109 ----------


 ---------- 2020-12-22 08:00:00 : 신북읍   34110 ----------


 ---------- 2020-12-22 13:00:00 : 동내면   34111 ----------


 ---------- 2020-12-22 17:00:00 : 신사우동   34112 ----------


 ---------- 2020-12-22 23:00:00 : 근화동   34113 ----------


 ---------- 2020-12-23 03:00:00 : 동산면   34114 ----------


 ---------- 2020-12-23 08:00:00 : 근화동   34115 ----------


 ---------- 2020-12-23 15:00:00 : 동  면   34116 ----------


 ---------- 2020-12-23 15:00:00 : 후평1동   34117 ----------


 ---------- 2020-12-23 16:00:00 : 석사동   34119 ----------


 ---------- 2020-12-23 20:00:00 : 후평1동   34120 ----------


 ---------- 2020-12-24 08:00:00 : 서  면   34123 ----------


 ---------- 2020-12-24 15:00:00 : 서  면   34124 ----------


 ---------- 2020-12-24 16:00:00 : 신동면   34125 ----------


 ---------- 2020-12-25 13:00:00 : 동산면   34126 ----------


 ---------- 2020-12-25 17:00:00 : 효자1동   34127 ----------


 ---------- 2020-12-25 19:00:00 : 신사우동   34129 ----------


 ---------- 2020-12-25 21:00:00 : 효자1동   34131 ----------


 ---------- 2020-12-26 16:00:00 : 신북읍   34132 ----------


 ---------- 2020-12-26 17:00:00 : 신북읍   34134 ----------


 ---------- 2020-12-26 21:00:00 : 근화동   34135 ----------


 ---------- 2020-12-27 02:00:00 : 신사우동   34136 ----------


 ---------- 2020-12-28 13:00:00 : 효자1동   34137 ----------


 ---------- 2020-12-28 17:00:00 : 강남동   34138 ----------


 ---------- 2020-12-28 17:00:00 : 퇴계동   34139 ----------


 ---------- 2020-12-29 00:00:00 : 신사우동   34140 ----------


 ---------- 2020-12-29 06:00:00 : 신사우동   34142 ----------


 ---------- 2020-12-29 08:00:00 : 신사우동   34143 ----------


 ---------- 2020-12-29 10:00:00 : 신북읍   34145 ----------


 ---------- 2020-12-29 21:00:00 : 퇴계동   34146 ----------


 ---------- 2020-12-29 22:00:00 : 동  면   34147 ----------


 ---------- 2020-12-30 03:00:00 : 석사동   34148 ----------


 ---------- 2020-12-30 10:00:00 : 강남동   34149 ----------


 ---------- 2020-12-30 10:00:00 : 동산면   34151 ----------


 ---------- 2020-12-30 15:00:00 : 근화동   34152 ----------


 ---------- 2020-12-31 17:00:00 : 후평1동   34153 ----------


 ---------- 2021-01-01 07:00:00 : 동  면   34154 ----------


 ---------- 2021-01-01 12:00:00 : 퇴계동   34156 ----------


 ---------- 2021-01-01 18:00:00 : 효자1동   34158 ----------


 ---------- 2021-01-01 21:00:00 : 퇴계동   34161 ----------


 ---------- 2021-01-01 22:00:00 : 효자1동   34162 ----------


 ---------- 2021-01-02 08:00:00 : 강남동   34163 ----------


 ---------- 2021-01-02 08:00:00 : 신사우동   34165 ----------


 ---------- 2021-01-02 11:00:00 : 동산면   34166 ----------


 ---------- 2021-01-02 13:00:00 : 동산면   34167 ----------


 ---------- 2021-01-03 00:00:00 : 동  면   34170 ----------


 ---------- 2021-01-03 04:00:00 : 효자1동   34173 ----------


 ---------- 2021-01-03 11:00:00 : 석사동   34174 ----------


 ---------- 2021-01-03 12:00:00 : 동내면   34176 ----------


 ---------- 2021-01-03 12:00:00 : 퇴계동   34177 ----------


 ---------- 2021-01-03 14:00:00 : 석사동   34179 ----------


 ---------- 2021-01-03 20:00:00 : 퇴계동   34181 ----------


 ---------- 2021-01-04 10:00:00 : 신북읍   34182 ----------


 ---------- 2021-01-04 13:00:00 : 강남동   34183 ----------


 ---------- 2021-01-04 14:00:00 : 효자1동   34185 ----------


 ---------- 2021-01-04 15:00:00 : 동  면   34186 ----------


 ---------- 2021-01-04 16:00:00 : 서  면   34187 ----------


 ---------- 2021-01-04 21:00:00 : 후평1동   34189 ----------


 ---------- 2021-01-05 13:00:00 : 효자1동   34190 ----------


 ---------- 2021-01-05 14:00:00 : 신북읍   34191 ----------


 ---------- 2021-01-06 03:00:00 : 효자1동   34194 ----------


 ---------- 2021-01-06 07:00:00 : 신북읍   34196 ----------


 ---------- 2021-01-06 11:00:00 : 동  면   34199 ----------


 ---------- 2021-01-07 01:00:00 : 후평1동   34200 ----------


 ---------- 2021-01-07 08:00:00 : 신북읍   34202 ----------


 ---------- 2021-01-07 09:00:00 : 석사동   34204 ----------


 ---------- 2021-01-07 13:00:00 : 북산면   34207 ----------


 ---------- 2021-01-07 14:00:00 : 후평1동   34208 ----------


 ---------- 2021-01-07 15:00:00 : 서  면   34209 ----------


 ---------- 2021-01-07 15:00:00 : 동산면   34213 ----------


 ---------- 2021-01-07 18:00:00 : 조운동   34214 ----------


 ---------- 2021-01-07 23:00:00 : 퇴계동   34215 ----------


 ---------- 2021-01-08 00:00:00 : 조운동   34216 ----------

 ---------- 2021-01-08 08:00:00 : 남  면   34218 ----------


 ---------- 2021-01-08 13:00:00 : 신사우동   34221 ----------


 ---------- 2021-01-08 14:00:00 : 퇴계동   34222 ----------


 ---------- 2021-01-08 15:00:00 : 퇴계동   34223 ----------


 ---------- 2021-01-08 18:00:00 : 후평1동   34224 ----------


 ---------- 2021-01-08 19:00:00 : 소양동   34225 ----------


 ---------- 2021-01-08 20:00:00 : 동  면   34227 ----------


 ---------- 2021-01-09 00:00:00 : 석사동   34228 ----------


 ---------- 2021-01-09 01:00:00 : 석사동   34229 ----------


 ---------- 2021-01-09 01:00:00 : 사북면   34230 ----------


 ---------- 2021-01-09 02:00:00 : 신사우동   34232 ----------


 ---------- 2021-01-09 07:00:00 : 강남동   34233 ----------


 ---------- 2021-01-09 11:00:00 : 강남동   34234 ----------


 ---------- 2021-01-09 12:00:00 : 퇴계동   34239 ----------


 ---------- 2021-01-09 13:00:00 : 신북읍   34240 ----------


 ---------- 2021-01-09 13:00:00 : 소양동   34241 ----------


 ---------- 2021-01-09 13:00:00 : 조운동   34242 ----------


 ---------- 2021-01-09 15:00:00 : 신사우동   34244 ----------


 ---------- 2021-01-09 19:00:00 : 남산면   34245 ----------


 ---------- 2021-01-09 20:00:00 : 신사우동   34246 ----------


 ---------- 2021-01-09 21:00:00 : 강남동   34247 ----------


 ---------- 2021-01-10 10:00:00 : 남산면   34248 ----------


 ---------- 2021-01-10 13:00:00 : 석사동   34249 ----------


 ---------- 2021-01-10 14:00:00 : 서  면   34251 ----------


 ---------- 2021-01-10 15:00:00 : 동  면   34253 ----------


 ---------- 2021-01-10 17:00:00 : 효자1동   34254 ----------


 ---------- 2021-01-10 17:00:00 : 퇴계동   34255 ----------


 ---------- 2021-01-10 20:00:00 : 효자1동   34258 ----------


 ---------- 2021-01-11 07:00:00 : 동  면   34262 ----------


 ---------- 2021-01-11 08:00:00 : 동  면   34264 ----------


 ---------- 2021-01-11 10:00:00 : 동  면   34265 ----------


 ---------- 2021-01-11 11:00:00 : 동  면   34266 ----------


 ---------- 2021-01-11 13:00:00 : 조운동   34267 ----------


 ---------- 2021-01-11 14:00:00 : 서  면   34268 ----------


 ---------- 2021-01-11 14:00:00 : 근화동   34269 ----------


 ---------- 2021-01-11 14:00:00 : 후평1동   34270 ----------


 ---------- 2021-01-11 18:00:00 : 북산면   34271 ----------


 ---------- 2021-01-11 20:00:00 : 후평1동   34272 ----------


 ---------- 2021-01-11 20:00:00 : 교  동   34274 ----------


 ---------- 2021-01-12 02:00:00 : 사북면   34277 ----------


 ---------- 2021-01-12 06:00:00 : 동  면   34280 ----------


 ---------- 2021-01-12 07:00:00 : 효자1동   34281 ----------


 ---------- 2021-01-12 09:00:00 : 후평1동   34284 ----------


 ---------- 2021-01-12 10:00:00 : 강남동   34285 ----------


 ---------- 2021-01-12 11:00:00 : 후평1동   34288 ----------


 ---------- 2021-01-12 12:00:00 : 석사동   34290 ----------


 ---------- 2021-01-12 12:00:00 : 신북읍   34291 ----------


 ---------- 2021-01-12 17:00:00 : 퇴계동   34292 ----------


 ---------- 2021-01-12 18:00:00 : 신북읍   34293 ----------


 ---------- 2021-01-12 22:00:00 : 신북읍   34295 ----------


 ---------- 2021-01-13 06:00:00 : 사북면   34297 ----------


 ---------- 2021-01-13 08:00:00 : 후평1동   34298 ----------


 ---------- 2021-01-13 09:00:00 : 효자1동   34299 ----------


 ---------- 2021-01-13 13:00:00 : 조운동   34300 ----------


 ---------- 2021-01-13 14:00:00 : 석사동   34301 ----------


 ---------- 2021-01-13 15:00:00 : 효자1동   34302 ----------


 ---------- 2021-01-13 16:00:00 : 후평1동   34303 ----------


 ---------- 2021-01-13 20:00:00 : 북산면   34304 ----------


 ---------- 2021-01-13 22:00:00 : 석사동   34305 ----------


 ---------- 2021-01-14 08:00:00 : 남산면   34306 ----------


 ---------- 2021-01-14 09:00:00 : 후평1동   34307 ----------


 ---------- 2021-01-14 10:00:00 : 동산면   34308 ----------


 ---------- 2021-01-14 11:00:00 : 동  면   34309 ----------


 ---------- 2021-01-14 13:00:00 : 남산면   34310 ----------


 ---------- 2021-01-14 13:00:00 : 퇴계동   34315 ----------


 ---------- 2021-01-14 14:00:00 : 효자1동   34317 ----------


 ---------- 2021-01-14 15:00:00 : 후평1동   34318 ----------


 ---------- 2021-01-14 16:00:00 : 후평1동   34321 ----------


 ---------- 2021-01-14 16:00:00 : 퇴계동   34322 ----------


 ---------- 2021-01-14 17:00:00 : 동내면   34323 ----------


 ---------- 2021-01-15 00:00:00 : 후평1동   34324 ----------


 ---------- 2021-01-15 03:00:00 : 조운동   34326 ----------


 ---------- 2021-01-15 08:00:00 : 신동면   34327 ----------


 ---------- 2021-01-15 09:00:00 : 신북읍   34328 ----------


 ---------- 2021-01-15 13:00:00 : 석사동   34329 ----------


 ---------- 2021-01-15 13:00:00 : 효자1동   34330 ----------


 ---------- 2021-01-15 14:00:00 : 서  면   34331 ----------


 ---------- 2021-01-15 14:00:00 : 퇴계동   34335 ----------


 ---------- 2021-01-15 21:00:00 : 석사동   34336 ----------


 ---------- 2021-01-16 02:00:00 : 퇴계동   34339 ----------


 ---------- 2021-01-16 11:00:00 : 소양동   34340 ----------


 ---------- 2021-01-16 13:00:00 : 강남동   34341 ----------


 ---------- 2021-01-17 02:00:00 : 효자1동   34343 ----------


 ---------- 2021-01-17 13:00:00 : 남산면   34347 ----------


 ---------- 2021-01-17 14:00:00 : 동내면   34348 ----------


 ---------- 2021-01-18 00:00:00 : 신사우동   34349 ----------


 ---------- 2021-01-18 04:00:00 : 서  면   34352 ----------


 ---------- 2021-01-18 11:00:00 : 동산면   34357 ----------


 ---------- 2021-01-18 12:00:00 : 동  면   34358 ----------


 ---------- 2021-01-18 14:00:00 : 동산면   34359 ----------


 ---------- 2021-01-18 16:00:00 : 남산면   34361 ----------


 ---------- 2021-01-18 18:00:00 : 서  면   34363 ----------


 ---------- 2021-01-18 20:00:00 : 후평1동   34364 ----------


 ---------- 2021-01-18 21:00:00 : 신북읍   34365 ----------


 ---------- 2021-01-18 23:00:00 : 근화동   34367 ----------


 ---------- 2021-01-18 23:00:00 : 신사우동   34369 ----------


 ---------- 2021-01-19 08:00:00 : 조운동   34370 ----------


 ---------- 2021-01-19 09:00:00 : 동내면   34374 ----------


 ---------- 2021-01-19 10:00:00 : 신북읍   34375 ----------


 ---------- 2021-01-19 14:00:00 : 서  면   34376 ----------


 ---------- 2021-01-19 15:00:00 : 사북면   34377 ----------


 ---------- 2021-01-19 18:00:00 : 신북읍   34378 ----------


 ---------- 2021-01-19 21:00:00 : 석사동   34381 ----------


 ---------- 2021-01-20 03:00:00 : 동  면   34384 ----------


 ---------- 2021-01-20 13:00:00 : 신북읍   34385 ----------


 ---------- 2021-01-20 14:00:00 : 동내면   34386 ----------


 ---------- 2021-01-20 20:00:00 : 석사동   34387 ----------


 ---------- 2021-01-20 21:00:00 : 퇴계동   34388 ----------


 ---------- 2021-01-20 22:00:00 : 서  면   34389 ----------


 ---------- 2021-01-21 00:00:00 : 석사동   34390 ----------


 ---------- 2021-01-21 00:00:00 : 퇴계동   34391 ----------


 ---------- 2021-01-21 10:00:00 : 신북읍   34393 ----------


 ---------- 2021-01-21 14:00:00 : 효자1동   34397 ----------


 ---------- 2021-01-21 14:00:00 : 소양동   34398 ----------


 ---------- 2021-01-21 15:00:00 : 후평1동   34399 ----------


 ---------- 2021-01-21 17:00:00 : 동  면   34400 ----------


 ---------- 2021-01-21 21:00:00 : 동  면   34403 ----------


 ---------- 2021-01-22 05:00:00 : 후평1동   34404 ----------


 ---------- 2021-01-22 07:00:00 : 석사동   34405 ----------


 ---------- 2021-01-22 11:00:00 : 신동면   34409 ----------


 ---------- 2021-01-22 20:00:00 : 신동면   34410 ----------


 ---------- 2021-01-23 21:00:00 : 퇴계동   34413 ----------


 ---------- 2021-01-24 08:00:00 : 후평1동   34414 ----------


 ---------- 2021-01-24 12:00:00 : 사북면   34415 ----------


 ---------- 2021-01-24 18:00:00 : 석사동   34417 ----------


 ---------- 2021-01-24 18:00:00 : 남산면   34420 ----------


 ---------- 2021-01-25 13:00:00 : 서  면   34422 ----------


 ---------- 2021-01-25 18:00:00 : 효자1동   34423 ----------


 ---------- 2021-01-26 01:00:00 : 강남동   34424 ----------


 ---------- 2021-01-26 13:00:00 : 후평1동   34425 ----------


 ---------- 2021-01-26 14:00:00 : 신북읍   34426 ----------


 ---------- 2021-01-26 15:00:00 : 신북읍   34428 ----------


 ---------- 2021-01-26 16:00:00 : 효자1동   34429 ----------


 ---------- 2021-01-26 17:00:00 : 강남동   34432 ----------


 ---------- 2021-01-26 18:00:00 : 석사동   34433 ----------


 ---------- 2021-01-26 18:00:00 : 퇴계동   34434 ----------

 ---------- 2021-01-27 06:00:00 : 퇴계동   34435 ----------


 ---------- 2021-01-27 08:00:00 : 동내면   34437 ----------


 ---------- 2021-01-27 10:00:00 : 동내면   34438 ----------


 ---------- 2021-01-27 10:00:00 : 신북읍   34439 ----------


 ---------- 2021-01-27 14:00:00 : 서  면   34440 ----------


 ---------- 2021-01-27 23:00:00 : 퇴계동   34442 ----------


 ---------- 2021-01-28 07:00:00 : 서  면   34444 ----------


 ---------- 2021-01-28 07:00:00 : 소양동   34446 ----------


 ---------- 2021-01-28 09:00:00 : 신북읍   34448 ----------


 ---------- 2021-01-28 14:00:00 : 신북읍   34449 ----------


 ---------- 2021-01-28 15:00:00 : 강남동   34451 ----------


 ---------- 2021-01-28 16:00:00 : 효자1동   34452 ----------


 ---------- 2021-01-28 18:00:00 : 신동면   34454 ----------


 ---------- 2021-01-28 18:00:00 : 근화동   34456 ----------


 ---------- 2021-01-28 19:00:00 : 강남동   34457 ----------


 ---------- 2021-01-28 22:00:00 : 소양동   34459 ----------


 ---------- 2021-01-29 09:00:00 : 신북읍   34460 ----------


 ---------- 2021-01-29 12:00:00 : 효자1동   34461 ----------


 ---------- 2021-01-29 12:00:00 : 신사우동   34462 ----------


 ---------- 2021-01-29 13:00:00 : 근화동   34464 ----------


 ---------- 2021-01-29 14:00:00 : 석사동   34465 ----------


 ---------- 2021-01-29 15:00:00 : 동내면   34466 ----------


 ---------- 2021-01-29 23:00:00 : 동내면   34467 ----------


 ---------- 2021-01-30 08:00:00 : 근화동   34470 ----------


 ---------- 2021-01-30 08:00:00 : 후평1동   34472 ----------


 ---------- 2021-01-30 09:00:00 : 근화동   34473 ----------


 ---------- 2021-01-30 10:00:00 : 서  면   34475 ----------


 ---------- 2021-01-30 11:00:00 : 동내면   34476 ----------


 ---------- 2021-01-30 16:00:00 : 동내면   34477 ----------


 ---------- 2021-01-30 17:00:00 : 석사동   34479 ----------


 ---------- 2021-01-31 02:00:00 : 신사우동   34482 ----------


 ---------- 2021-01-31 05:00:00 : 석사동   34484 ----------


 ---------- 2021-01-31 06:00:00 : 동내면   34485 ----------


 ---------- 2021-01-31 12:00:00 : 남산면   34487 ----------


 ---------- 2021-01-31 18:00:00 : 석사동   34489 ----------


 ---------- 2021-01-31 23:00:00 : 효자1동   34490 ----------


 ---------- 2021-02-01 03:00:00 : 신사우동   34492 ----------


 ---------- 2021-02-01 09:00:00 : 신북읍   34494 ----------


 ---------- 2021-02-01 10:00:00 : 후평1동   34495 ----------


 ---------- 2021-02-01 12:00:00 : 동내면   34496 ----------


 ---------- 2021-02-01 13:00:00 : 동  면   34500 ----------


 ---------- 2021-02-01 15:00:00 : 석사동   34503 ----------


 ---------- 2021-02-01 19:00:00 : 후평1동   34506 ----------


 ---------- 2021-02-02 01:00:00 : 조운동   34507 ----------


 ---------- 2021-02-02 11:00:00 : 신북읍   34508 ----------


 ---------- 2021-02-02 11:00:00 : 소양동   34509 ----------


 ---------- 2021-02-02 15:00:00 : 서  면   34510 ----------


 ---------- 2021-02-02 16:00:00 : 신사우동   34511 ----------


 ---------- 2021-02-02 17:00:00 : 후평1동   34515 ----------


 ---------- 2021-02-03 12:00:00 : 후평1동   34517 ----------


 ---------- 2021-02-03 14:00:00 : 동내면   34518 ----------


 ---------- 2021-02-03 15:00:00 : 남  면   34519 ----------


 ---------- 2021-02-03 20:00:00 : 퇴계동   34521 ----------


 ---------- 2021-02-04 07:00:00 : 퇴계동   34524 ----------


 ---------- 2021-02-04 08:00:00 : 동산면   34525 ----------


 ---------- 2021-02-04 09:00:00 : 신북읍   34526 ----------


 ---------- 2021-02-04 13:00:00 : 남  면   34527 ----------


 ---------- 2021-02-04 14:00:00 : 소양동   34531 ----------


 ---------- 2021-02-04 15:00:00 : 강남동   34534 ----------


 ---------- 2021-02-04 15:00:00 : 소양동   34539 ----------


 ---------- 2021-02-04 16:00:00 : 소양동   34542 ----------


 ---------- 2021-02-04 18:00:00 : 교  동   34543 ----------


 ---------- 2021-02-05 01:00:00 : 효자1동   34544 ----------


 ---------- 2021-02-05 02:00:00 : 효자1동   34545 ----------


 ---------- 2021-02-05 09:00:00 : 교  동   34546 ----------


 ---------- 2021-02-05 12:00:00 : 근화동   34547 ----------


 ---------- 2021-02-06 00:00:00 : 효자1동   34550 ----------


 ---------- 2021-02-06 08:00:00 : 신동면   34551 ----------


 ---------- 2021-02-06 08:00:00 : 신북읍   34553 ----------


 ---------- 2021-02-06 09:00:00 : 신북읍   34554 ----------


 ---------- 2021-02-06 10:00:00 : 신북읍   34555 ----------


 ---------- 2021-02-06 11:00:00 : 강남동   34556 ----------


 ---------- 2021-02-06 12:00:00 : 신북읍   34557 ----------


 ---------- 2021-02-06 14:00:00 : 동  면   34558 ----------


 ---------- 2021-02-06 15:00:00 : 사북면   34562 ----------


 ---------- 2021-02-06 15:00:00 : 약사명동   34564 ----------


 ---------- 2021-02-06 16:00:00 : 교  동   34566 ----------


 ---------- 2021-02-07 00:00:00 : 동내면   34567 ----------


 ---------- 2021-02-07 01:00:00 : 동내면   34568 ----------


 ---------- 2021-02-07 02:00:00 : 신북읍   34569 ----------


 ---------- 2021-02-07 04:00:00 : 효자1동   34572 ----------


 ---------- 2021-02-07 07:00:00 : 후평1동   34575 ----------


 ---------- 2021-02-07 08:00:00 : 신북읍   34578 ----------


 ---------- 2021-02-07 10:00:00 : 신북읍   34579 ----------


 ---------- 2021-02-07 11:00:00 : 후평1동   34581 ----------


 ---------- 2021-02-08 12:00:00 : 동내면   34584 ----------


 ---------- 2021-02-08 13:00:00 : 신북읍   34585 ----------


 ---------- 2021-02-08 15:00:00 : 동  면   34586 ----------


 ---------- 2021-02-08 15:00:00 : 후평1동   34587 ----------


 ---------- 2021-02-08 16:00:00 : 신사우동   34590 ----------


 ---------- 2021-02-08 17:00:00 : 조운동   34593 ----------


 ---------- 2021-02-08 19:00:00 : 북산면   34595 ----------


 ---------- 2021-02-08 20:00:00 : 동  면   34596 ----------


 ---------- 2021-02-09 05:00:00 : 신동면   34599 ----------


 ---------- 2021-02-09 12:00:00 : 후평1동   34600 ----------


 ---------- 2021-02-09 15:00:00 : 소양동   34602 ----------


 ---------- 2021-02-09 16:00:00 : 서  면   34603 ----------


 ---------- 2021-02-10 00:00:00 : 소양동   34606 ----------


 ---------- 2021-02-10 01:00:00 : 석사동   34607 ----------


 ---------- 2021-02-10 08:00:00 : 효자1동   34609 ----------


 ---------- 2021-02-10 13:00:00 : 신북읍   34610 ----------


 ---------- 2021-02-10 19:00:00 : 근화동   34611 ----------


 ---------- 2021-02-10 20:00:00 : 신북읍   34612 ----------


 ---------- 2021-02-10 22:00:00 : 신북읍   34613 ----------


 ---------- 2021-02-11 03:00:00 : 신북읍   34614 ----------


 ---------- 2021-02-11 11:00:00 : 신동면   34617 ----------


 ---------- 2021-02-11 12:00:00 : 신동면   34618 ----------


 ---------- 2021-02-11 13:00:00 : 근화동   34619 ----------


 ---------- 2021-02-12 00:00:00 : 약사명동   34621 ----------


 ---------- 2021-02-13 12:00:00 : 후평1동   34622 ----------


 ---------- 2021-02-13 21:00:00 : 신북읍   34623 ----------


 ---------- 2021-02-14 13:00:00 : 후평1동   34625 ----------


 ---------- 2021-02-14 14:00:00 : 근화동   34627 ----------


 ---------- 2021-02-14 21:00:00 : 조운동   34628 ----------


 ---------- 2021-02-14 22:00:00 : 신사우동   34629 ----------


 ---------- 2021-02-14 23:00:00 : 효자1동   34631 ----------


 ---------- 2021-02-15 03:00:00 : 신사우동   34632 ----------


 ---------- 2021-02-15 13:00:00 : 신북읍   34634 ----------


 ---------- 2021-02-15 15:00:00 : 퇴계동   34637 ----------


 ---------- 2021-02-15 17:00:00 : 후평1동   34638 ----------


 ---------- 2021-02-16 00:00:00 : 교  동   34639 ----------


 ---------- 2021-02-16 15:00:00 : 퇴계동   34642 ----------


 ---------- 2021-02-16 17:00:00 : 사북면   34643 ----------


 ---------- 2021-02-16 17:00:00 : 동내면   34644 ----------


 ---------- 2021-02-16 18:00:00 : 사북면   34645 ----------


 ---------- 2021-02-16 23:00:00 : 석사동   34646 ----------


 ---------- 2021-02-16 23:00:00 : 후평1동   34647 ----------


 ---------- 2021-02-17 09:00:00 : 석사동   34649 ----------


 ---------- 2021-02-17 10:00:00 : 신북읍   34650 ----------


 ---------- 2021-02-17 12:00:00 : 동  면   34653 ----------


 ---------- 2021-02-17 12:00:00 : 후평1동   34654 ----------


 ---------- 2021-02-17 13:00:00 : 동  면   34658 ----------


 ---------- 2021-02-17 15:00:00 : 조운동   34659 ----------


 ---------- 2021-02-17 17:00:00 : 조운동   34660 ----------


 ---------- 2021-02-17 18:00:00 : 교  동   34661 ----------


 ---------- 2021-02-17 21:00:00 : 강남동   34662 ----------

 ---------- 2021-02-17 21:00:00 : 신사우동   34664 ----------


 ---------- 2021-02-18 04:00:00 : 후평1동   34670 ----------


 ---------- 2021-02-18 10:00:00 : 사북면   34671 ----------


 ---------- 2021-02-18 14:00:00 : 석사동   34673 ----------


 ---------- 2021-02-18 20:00:00 : 남산면   34674 ----------


 ---------- 2021-02-18 21:00:00 : 후평1동   34676 ----------


 ---------- 2021-02-19 05:00:00 : 석사동   34679 ----------


 ---------- 2021-02-19 08:00:00 : 남산면   34680 ----------


 ---------- 2021-02-19 11:00:00 : 강남동   34681 ----------


 ---------- 2021-02-19 12:00:00 : 신동면   34684 ----------


 ---------- 2021-02-19 12:00:00 : 남산면   34689 ----------


 ---------- 2021-02-19 13:00:00 : 후평1동   34690 ----------


 ---------- 2021-02-19 19:00:00 : 서  면   34691 ----------


 ---------- 2021-02-19 19:00:00 : 후평1동   34692 ----------


 ---------- 2021-02-19 20:00:00 : 후평1동   34693 ----------


 ---------- 2021-02-20 10:00:00 : 후평1동   34694 ----------


 ---------- 2021-02-20 10:00:00 : 퇴계동   34695 ----------


 ---------- 2021-02-20 12:00:00 : 강남동   34698 ----------


 ---------- 2021-02-20 12:00:00 : 동내면   34699 ----------


 ---------- 2021-02-20 14:00:00 : 서  면   34700 ----------


 ---------- 2021-02-20 14:00:00 : 퇴계동   34703 ----------


 ---------- 2021-02-20 14:00:00 : 동산면   34705 ----------


 ---------- 2021-02-20 15:00:00 : 동산면   34706 ----------


 ---------- 2021-02-20 15:00:00 : 교  동   34707 ----------


 ---------- 2021-02-20 18:00:00 : 동  면   34708 ----------


 ---------- 2021-02-20 19:00:00 : 퇴계동   34709 ----------


 ---------- 2021-02-20 20:00:00 : 퇴계동   34712 ----------


 ---------- 2021-02-21 00:00:00 : 남산면   34714 ----------


 ---------- 2021-02-21 03:00:00 : 신사우동   34717 ----------


 ---------- 2021-02-21 03:00:00 : 퇴계동   34721 ----------


 ---------- 2021-02-21 05:00:00 : 효자1동   34722 ----------


 ---------- 2021-02-21 06:00:00 : 동산면   34723 ----------


 ---------- 2021-02-21 08:00:00 : 남  면   34724 ----------


 ---------- 2021-02-21 09:00:00 : 서  면   34726 ----------


 ---------- 2021-02-21 10:00:00 : 효자1동   34728 ----------


 ---------- 2021-02-21 11:00:00 : 후평1동   34730 ----------


 ---------- 2021-02-21 13:00:00 : 신동면   34732 ----------


 ---------- 2021-02-21 13:00:00 : 효자1동   34733 ----------


 ---------- 2021-02-21 17:00:00 : 소양동   34735 ----------


 ---------- 2021-02-21 20:00:00 : 후평1동   34736 ----------


 ---------- 2021-02-21 22:00:00 : 효자1동   34739 ----------


 ---------- 2021-02-21 23:00:00 : 효자1동   34741 ----------


 ---------- 2021-02-22 09:00:00 : 석사동   34744 ----------


 ---------- 2021-02-22 20:00:00 : 근화동   34747 ----------


 ---------- 2021-02-23 02:00:00 : 동내면   34748 ----------


 ---------- 2021-02-23 10:00:00 : 동내면   34750 ----------


 ---------- 2021-02-23 13:00:00 : 소양동   34752 ----------


 ---------- 2021-02-23 16:00:00 : 신북읍   34754 ----------


 ---------- 2021-02-23 16:00:00 : 후평1동   34755 ----------


 ---------- 2021-02-23 17:00:00 : 효자1동   34756 ----------


 ---------- 2021-02-23 17:00:00 : 퇴계동   34758 ----------


 ---------- 2021-02-23 18:00:00 : 근화동   34759 ----------


 ---------- 2021-02-23 18:00:00 : 동  면   34760 ----------


 ---------- 2021-02-23 22:00:00 : 후평1동   34762 ----------


 ---------- 2021-02-24 09:00:00 : 동내면   34765 ----------


 ---------- 2021-02-24 11:00:00 : 강남동   34766 ----------


 ---------- 2021-02-24 13:00:00 : 후평1동   34767 ----------


 ---------- 2021-02-24 14:00:00 : 신북읍   34768 ----------


 ---------- 2021-02-24 19:00:00 : 남산면   34770 ----------


 ---------- 2021-02-24 22:00:00 : 동내면   34771 ----------


 ---------- 2021-02-25 09:00:00 : 신사우동   34772 ----------


 ---------- 2021-02-25 09:00:00 : 퇴계동   34775 ----------


 ---------- 2021-02-25 15:00:00 : 남산면   34776 ----------


 ---------- 2021-02-25 16:00:00 : 후평1동   34777 ----------


 ---------- 2021-02-25 18:00:00 : 신북읍   34778 ----------


 ---------- 2021-02-26 09:00:00 : 동내면   34782 ----------


 ---------- 2021-02-26 10:00:00 : 퇴계동   34784 ----------


 ---------- 2021-02-26 12:00:00 : 강남동   34786 ----------


 ---------- 2021-02-26 13:00:00 : 신북읍   34787 ----------


 ---------- 2021-02-26 17:00:00 : 남산면   34788 ----------


 ---------- 2021-02-26 22:00:00 : 석사동   34789 ----------


 ---------- 2021-02-28 10:00:00 : 서  면   34790 ----------


 ---------- 2021-02-28 11:00:00 : 동내면   34792 ----------


 ---------- 2021-02-28 12:00:00 : 신사우동   34793 ----------


 ---------- 2021-02-28 16:00:00 : 서  면   34794 ----------


 ---------- 2021-02-28 16:00:00 : 북산면   34796 ----------


 ---------- 2021-02-28 17:00:00 : 북산면   34802 ----------


 ---------- 2021-02-28 22:00:00 : 신동면   34803 ----------


 ---------- 2021-02-28 22:00:00 : 강남동   34804 ----------


 ---------- 2021-03-01 00:00:00 : 신동면   34806 ----------


 ---------- 2021-03-01 09:00:00 : 서  면   34807 ----------


 ---------- 2021-03-01 10:00:00 : 서  면   34809 ----------


 ---------- 2021-03-01 10:00:00 : 동내면   34810 ----------


 ---------- 2021-03-01 10:00:00 : 동산면   34811 ----------


 ---------- 2021-03-01 11:00:00 : 동산면   34813 ----------


 ---------- 2021-03-01 16:00:00 : 동내면   34814 ----------


 ---------- 2021-03-01 16:00:00 : 효자1동   34817 ----------


 ---------- 2021-03-01 16:00:00 : 동산면   34819 ----------


 ---------- 2021-03-01 18:00:00 : 후평1동   34821 ----------


 ---------- 2021-03-01 19:00:00 : 석사동   34822 ----------


 ---------- 2021-03-01 19:00:00 : 서  면   34823 ----------


 ---------- 2021-03-01 19:00:00 : 신북읍   34824 ----------


 ---------- 2021-03-01 19:00:00 : 퇴계동   34825 ----------


 ---------- 2021-03-01 20:00:00 : 강남동   34826 ----------


 ---------- 2021-03-01 20:00:00 : 서  면   34827 ----------


 ---------- 2021-03-01 20:00:00 : 남산면   34828 ----------


 ---------- 2021-03-01 20:00:00 : 퇴계동   34829 ----------


 ---------- 2021-03-01 21:00:00 : 석사동   34830 ----------


 ---------- 2021-03-01 21:00:00 : 강남동   34831 ----------


 ---------- 2021-03-01 21:00:00 : 동  면   34832 ----------


 ---------- 2021-03-01 22:00:00 : 석사동   34833 ----------


 ---------- 2021-03-01 22:00:00 : 서  면   34836 ----------


 ---------- 2021-03-01 22:00:00 : 북산면   34837 ----------


 ---------- 2021-03-01 23:00:00 : 강남동   34839 ----------


 ---------- 2021-03-01 23:00:00 : 신북읍   34840 ----------


 ---------- 2021-03-02 00:00:00 : 석사동   34841 ----------


 ---------- 2021-03-02 06:00:00 : 서  면   34842 ----------


 ---------- 2021-03-02 07:00:00 : 동  면   34843 ----------


 ---------- 2021-03-02 08:00:00 : 신북읍   34844 ----------


 ---------- 2021-03-02 09:00:00 : 신북읍   34845 ----------


 ---------- 2021-03-02 10:00:00 : 서  면   34847 ----------


 ---------- 2021-03-02 17:00:00 : 후평1동   34851 ----------


 ---------- 2021-03-02 23:00:00 : 효자1동   34853 ----------


 ---------- 2021-03-03 00:00:00 : 효자1동   34855 ----------


 ---------- 2021-03-03 10:00:00 : 신북읍   34856 ----------


 ---------- 2021-03-03 13:00:00 : 퇴계동   34858 ----------


 ---------- 2021-03-03 14:00:00 : 후평1동   34859 ----------


 ---------- 2021-03-03 18:00:00 : 동  면   34860 ----------


 ---------- 2021-03-04 05:00:00 : 동산면   34861 ----------


 ---------- 2021-03-04 07:00:00 : 동산면   34862 ----------


 ---------- 2021-03-04 09:00:00 : 후평1동   34864 ----------


 ---------- 2021-03-04 13:00:00 : 신북읍   34865 ----------


 ---------- 2021-03-04 14:00:00 : 동내면   34866 ----------


 ---------- 2021-03-04 20:00:00 : 후평1동   34868 ----------


 ---------- 2021-03-04 21:00:00 : 퇴계동   34869 ----------


 ---------- 2021-03-05 08:00:00 : 교  동   34872 ----------


 ---------- 2021-03-05 09:00:00 : 서  면   34873 ----------


 ---------- 2021-03-05 10:00:00 : 퇴계동   34876 ----------


 ---------- 2021-03-05 13:00:00 : 신북읍   34877 ----------


 ---------- 2021-03-05 17:00:00 : 조운동   34880 ----------


 ---------- 2021-03-06 07:00:00 : 신북읍   34882 ----------


 ---------- 2021-03-06 16:00:00 : 석사동   34883 ----------


 ---------- 2021-03-06 17:00:00 : 후평1동   34884 ----------


 ---------- 2021-03-06 20:00:00 : 석사동   34885 ----------


 ---------- 2021-03-07 01:00:00 : 퇴계동   34886 ----------


 ---------- 2021-03-07 08:00:00 : 서  면   34887 ----------

 ---------- 2021-03-07 11:00:00 : 석사동   34888 ----------


 ---------- 2021-03-07 15:00:00 : 강남동   34890 ----------


 ---------- 2021-03-07 17:00:00 : 동  면   34891 ----------


 ---------- 2021-03-07 17:00:00 : 후평1동   34894 ----------


 ---------- 2021-03-07 18:00:00 : 약사명동   34898 ----------


 ---------- 2021-03-07 19:00:00 : 근화동   34899 ----------


 ---------- 2021-03-08 01:00:00 : 근화동   34900 ----------


 ---------- 2021-03-08 10:00:00 : 동내면   34901 ----------


 ---------- 2021-03-08 23:00:00 : 강남동   34902 ----------


 ---------- 2021-03-09 13:00:00 : 신북읍   34903 ----------


 ---------- 2021-03-09 16:00:00 : 퇴계동   34905 ----------


 ---------- 2021-03-10 06:00:00 : 동내면   34906 ----------


 ---------- 2021-03-10 12:00:00 : 효자1동   34907 ----------


 ---------- 2021-03-10 12:00:00 : 남산면   34909 ----------


 ---------- 2021-03-10 15:00:00 : 퇴계동   34911 ----------


 ---------- 2021-03-10 16:00:00 : 서  면   34912 ----------


 ---------- 2021-03-10 23:00:00 : 서  면   34914 ----------


 ---------- 2021-03-11 08:00:00 : 석사동   34915 ----------


 ---------- 2021-03-11 09:00:00 : 신북읍   34917 ----------


 ---------- 2021-03-11 11:00:00 : 효자1동   34919 ----------


 ---------- 2021-03-11 11:00:00 : 남산면   34921 ----------


 ---------- 2021-03-11 12:00:00 : 동내면   34922 ----------


 ---------- 2021-03-11 16:00:00 : 강남동   34923 ----------


 ---------- 2021-03-12 03:00:00 : 효자1동   34924 ----------


 ---------- 2021-03-12 07:00:00 : 신사우동   34927 ----------


 ---------- 2021-03-12 10:00:00 : 신북읍   34929 ----------


 ---------- 2021-03-12 12:00:00 : 신사우동   34931 ----------


 ---------- 2021-03-12 13:00:00 : 신북읍   34932 ----------


 ---------- 2021-03-12 18:00:00 : 교  동   34934 ----------


 ---------- 2021-03-12 21:00:00 : 남산면   34935 ----------


 ---------- 2021-03-13 00:00:00 : 신사우동   34939 ----------


 ---------- 2021-03-13 06:00:00 : 신사우동   34940 ----------


 ---------- 2021-03-13 10:00:00 : 신사우동   34945 ----------


 ---------- 2021-03-13 12:00:00 : 소양동   34946 ----------


 ---------- 2021-03-13 12:00:00 : 후평1동   34947 ----------


 ---------- 2021-03-13 13:00:00 : 동내면   34948 ----------


 ---------- 2021-03-13 17:00:00 : 동  면   34949 ----------


 ---------- 2021-03-13 19:00:00 : 신사우동   34950 ----------


 ---------- 2021-03-13 21:00:00 : 동내면   34954 ----------


 ---------- 2021-03-14 00:00:00 : 효자1동   34957 ----------


 ---------- 2021-03-14 04:00:00 : 근화동   34958 ----------


 ---------- 2021-03-14 07:00:00 : 서  면   34959 ----------


 ---------- 2021-03-14 07:00:00 : 조운동   34961 ----------


 ---------- 2021-03-14 08:00:00 : 동  면   34963 ----------


 ---------- 2021-03-14 10:00:00 : 효자1동   34964 ----------


 ---------- 2021-03-14 17:00:00 : 신북읍   34966 ----------


 ---------- 2021-03-14 19:00:00 : 신북읍   34968 ----------


 ---------- 2021-03-14 20:00:00 : 소양동   34969 ----------


 ---------- 2021-03-15 00:00:00 : 신사우동   34972 ----------


 ---------- 2021-03-15 00:00:00 : 퇴계동   34973 ----------


 ---------- 2021-03-15 09:00:00 : 서  면   34974 ----------


 ---------- 2021-03-15 11:00:00 : 신사우동   34977 ----------


 ---------- 2021-03-15 12:00:00 : 석사동   34978 ----------


 ---------- 2021-03-15 15:00:00 : 동내면   34979 ----------


 ---------- 2021-03-16 02:00:00 : 석사동   34980 ----------


 ---------- 2021-03-16 02:00:00 : 퇴계동   34982 ----------


 ---------- 2021-03-16 08:00:00 : 신북읍   34983 ----------


 ---------- 2021-03-16 10:00:00 : 근화동   34985 ----------


 ---------- 2021-03-16 10:00:00 : 신북읍   34986 ----------


 ---------- 2021-03-16 14:00:00 : 신동면   34987 ----------


 ---------- 2021-03-16 17:00:00 : 교  동   34989 ----------


 ---------- 2021-03-16 20:00:00 : 후평1동   34990 ----------


 ---------- 2021-03-16 23:00:00 : 근화동   34993 ----------


 ---------- 2021-03-17 02:00:00 : 후평1동   34994 ----------


 ---------- 2021-03-17 10:00:00 : 남산면   34996 ----------


 ---------- 2021-03-17 10:00:00 : 퇴계동   34998 ----------


 ---------- 2021-03-17 15:00:00 : 강남동   34999 ----------


 ---------- 2021-03-17 18:00:00 : 소양동   35000 ----------


 ---------- 2021-03-17 19:00:00 : 효자1동   35002 ----------


 ---------- 2021-03-18 17:00:00 : 신동면   35003 ----------


 ---------- 2021-03-18 18:00:00 : 동내면   35004 ----------


 ---------- 2021-03-18 21:00:00 : 동  면   35005 ----------


 ---------- 2021-03-18 22:00:00 : 동  면   35006 ----------


 ---------- 2021-03-19 00:00:00 : 효자1동   35008 ----------


 ---------- 2021-03-19 00:00:00 : 퇴계동   35009 ----------


 ---------- 2021-03-19 01:00:00 : 후평1동   35010 ----------


 ---------- 2021-03-19 03:00:00 : 신북읍   35012 ----------


 ---------- 2021-03-19 07:00:00 : 퇴계동   35013 ----------


 ---------- 2021-03-19 09:00:00 : 강남동   35015 ----------


 ---------- 2021-03-19 15:00:00 : 동산면   35019 ----------


 ---------- 2021-03-19 18:00:00 : 효자1동   35021 ----------


 ---------- 2021-03-20 10:00:00 : 남산면   35022 ----------


 ---------- 2021-03-20 18:00:00 : 서  면   35024 ----------


 ---------- 2021-03-21 09:00:00 : 후평1동   35025 ----------


 ---------- 2021-03-21 17:00:00 : 소양동   35026 ----------


 ---------- 2021-03-22 09:00:00 : 퇴계동   35027 ----------


 ---------- 2021-03-22 13:00:00 : 동산면   35028 ----------


 ---------- 2021-03-22 22:00:00 : 강남동   35030 ----------


 ---------- 2021-03-23 00:00:00 : 강남동   35031 ----------


 ---------- 2021-03-23 14:00:00 : 근화동   35035 ----------


 ---------- 2021-03-23 14:00:00 : 후평1동   35037 ----------


 ---------- 2021-03-23 15:00:00 : 후평1동   35040 ----------


 ---------- 2021-03-23 17:00:00 : 효자1동   35042 ----------


 ---------- 2021-03-23 18:00:00 : 신동면   35043 ----------


 ---------- 2021-03-23 19:00:00 : 퇴계동   35046 ----------


 ---------- 2021-03-24 02:00:00 : 효자1동   35049 ----------


 ---------- 2021-03-24 03:00:00 : 후평1동   35050 ----------


 ---------- 2021-03-24 10:00:00 : 효자1동   35051 ----------


 ---------- 2021-03-24 10:00:00 : 후평1동   35054 ----------


 ---------- 2021-03-24 16:00:00 : 남산면   35055 ----------


 ---------- 2021-03-24 20:00:00 : 동내면   35056 ----------


 ---------- 2021-03-24 21:00:00 : 퇴계동   35057 ----------


 ---------- 2021-03-24 22:00:00 : 남  면   35060 ----------


 ---------- 2021-03-25 08:00:00 : 서  면   35061 ----------


 ---------- 2021-03-25 14:00:00 : 동내면   35062 ----------


 ---------- 2021-03-25 14:00:00 : 동  면   35065 ----------


 ---------- 2021-03-25 16:00:00 : 신북읍   35066 ----------


 ---------- 2021-03-25 16:00:00 : 후평1동   35068 ----------


 ---------- 2021-03-25 17:00:00 : 서  면   35069 ----------


 ---------- 2021-03-25 17:00:00 : 신북읍   35070 ----------


 ---------- 2021-03-25 20:00:00 : 약사명동   35072 ----------


 ---------- 2021-03-26 02:00:00 : 동내면   35073 ----------


 ---------- 2021-03-26 03:00:00 : 석사동   35075 ----------


 ---------- 2021-03-26 06:00:00 : 동  면   35078 ----------


 ---------- 2021-03-26 10:00:00 : 효자1동   35079 ----------


 ---------- 2021-03-26 10:00:00 : 동  면   35080 ----------


 ---------- 2021-03-26 11:00:00 : 강남동   35082 ----------


 ---------- 2021-03-26 15:00:00 : 서  면   35083 ----------


 ---------- 2021-03-26 16:00:00 : 퇴계동   35084 ----------


 ---------- 2021-03-26 17:00:00 : 강남동   35089 ----------


 ---------- 2021-03-27 09:00:00 : 효자1동   35091 ----------


 ---------- 2021-03-27 09:00:00 : 퇴계동   35093 ----------


 ---------- 2021-03-27 11:00:00 : 남  면   35095 ----------


 ---------- 2021-03-27 12:00:00 : 석사동   35097 ----------


 ---------- 2021-03-27 13:00:00 : 동내면   35098 ----------


 ---------- 2021-03-27 16:00:00 : 남산면   35101 ----------


 ---------- 2021-03-27 17:00:00 : 석사동   35103 ----------


 ---------- 2021-03-27 17:00:00 : 강남동   35106 ----------


 ---------- 2021-03-27 18:00:00 : 남산면   35107 ----------


 ---------- 2021-03-28 01:00:00 : 동내면   35108 ----------


 ---------- 2021-03-28 10:00:00 : 남산면   35109 ----------


 ---------- 2021-03-28 13:00:00 : 효자1동   35112 ----------


 ---------- 2021-03-28 15:00:00 : 남산면   35113 ----------


 ---------- 2021-03-28 22:00:00 : 후평1동   35116 ----------


 ---------- 2021-03-29 00:00:00 : 신사우동   35119 ----------


 ---------- 2021-03-29 11:00:00 : 남산면   35122 ----------

 ---------- 2021-03-30 10:00:00 : 효자1동   35123 ----------


 ---------- 2021-03-30 12:00:00 : 약사명동   35125 ----------


 ---------- 2021-03-30 13:00:00 : 신사우동   35126 ----------


 ---------- 2021-03-31 01:00:00 : 석사동   35129 ----------


 ---------- 2021-03-31 04:00:00 : 효자1동   35130 ----------


 ---------- 2021-03-31 11:00:00 : 동  면   35133 ----------


 ---------- 2021-03-31 12:00:00 : 소양동   35136 ----------


 ---------- 2021-03-31 15:00:00 : 효자1동   35138 ----------


 ---------- 2021-03-31 20:00:00 : 남산면   35139 ----------


 ---------- 2021-03-31 23:00:00 : 후평1동   35140 ----------


 ---------- 2021-04-01 03:00:00 : 퇴계동   35141 ----------


 ---------- 2021-04-01 09:00:00 : 신동면   35143 ----------


 ---------- 2021-04-01 09:00:00 : 북산면   35144 ----------


 ---------- 2021-04-01 11:00:00 : 석사동   35146 ----------


 ---------- 2021-04-01 12:00:00 : 신북읍   35148 ----------


 ---------- 2021-04-01 13:00:00 : 석사동   35151 ----------


 ---------- 2021-04-01 19:00:00 : 동  면   35152 ----------


 ---------- 2021-04-01 21:00:00 : 신동면   35153 ----------


 ---------- 2021-04-01 22:00:00 : 근화동   35154 ----------


 ---------- 2021-04-02 09:00:00 : 신사우동   35155 ----------


 ---------- 2021-04-02 17:00:00 : 남  면   35156 ----------


 ---------- 2021-04-02 18:00:00 : 동내면   35160 ----------


 ---------- 2021-04-02 20:00:00 : 동산면   35161 ----------


 ---------- 2021-04-03 00:00:00 : 신동면   35163 ----------


 ---------- 2021-04-03 11:00:00 : 신동면   35165 ----------


 ---------- 2021-04-03 11:00:00 : 남  면   35167 ----------


 ---------- 2021-04-04 02:00:00 : 동내면   35168 ----------


 ---------- 2021-04-04 02:00:00 : 소양동   35171 ----------


 ---------- 2021-04-04 02:00:00 : 동  면   35172 ----------


 ---------- 2021-04-04 14:00:00 : 강남동   35175 ----------


 ---------- 2021-04-04 15:00:00 : 강남동   35176 ----------


 ---------- 2021-04-04 18:00:00 : 후평1동   35177 ----------


 ---------- 2021-04-05 07:00:00 : 남산면   35178 ----------


 ---------- 2021-04-05 09:00:00 : 사북면   35180 ----------


 ---------- 2021-04-05 12:00:00 : 북산면   35181 ----------


 ---------- 2021-04-05 15:00:00 : 신북읍   35182 ----------


 ---------- 2021-04-05 18:00:00 : 신북읍   35183 ----------


 ---------- 2021-04-05 18:00:00 : 후평1동   35185 ----------


 ---------- 2021-04-05 19:00:00 : 후평1동   35186 ----------


 ---------- 2021-04-05 20:00:00 : 조운동   35187 ----------


 ---------- 2021-04-06 00:00:00 : 소양동   35188 ----------


 ---------- 2021-04-06 09:00:00 : 북산면   35190 ----------


 ---------- 2021-04-06 10:00:00 : 북산면   35191 ----------


 ---------- 2021-04-06 11:00:00 : 퇴계동   35193 ----------


 ---------- 2021-04-06 13:00:00 : 남산면   35194 ----------


 ---------- 2021-04-06 13:00:00 : 근화동   35195 ----------


 ---------- 2021-04-06 16:00:00 : 퇴계동   35196 ----------


 ---------- 2021-04-06 23:00:00 : 석사동   35197 ----------


 ---------- 2021-04-07 02:00:00 : 퇴계동   35202 ----------


 ---------- 2021-04-07 04:00:00 : 후평1동   35205 ----------


 ---------- 2021-04-07 05:00:00 : 후평1동   35207 ----------


 ---------- 2021-04-07 09:00:00 : 석사동   35209 ----------


 ---------- 2021-04-07 10:00:00 : 후평1동   35212 ----------


 ---------- 2021-04-07 10:00:00 : 퇴계동   35217 ----------


 ---------- 2021-04-07 15:00:00 : 교  동   35218 ----------


 ---------- 2021-04-07 16:00:00 : 북산면   35220 ----------


 ---------- 2021-04-08 00:00:00 : 퇴계동   35223 ----------


 ---------- 2021-04-08 01:00:00 : 석사동   35226 ----------


 ---------- 2021-04-08 03:00:00 : 신북읍   35229 ----------


 ---------- 2021-04-08 09:00:00 : 퇴계동   35230 ----------


 ---------- 2021-04-08 16:00:00 : 신사우동   35232 ----------


 ---------- 2021-04-08 16:00:00 : 동  면   35233 ----------


 ---------- 2021-04-08 17:00:00 : 동내면   35237 ----------


 ---------- 2021-04-08 19:00:00 : 석사동   35239 ----------


 ---------- 2021-04-08 19:00:00 : 후평1동   35240 ----------


 ---------- 2021-04-08 23:00:00 : 퇴계동   35241 ----------


 ---------- 2021-04-09 14:00:00 : 동산면   35242 ----------


 ---------- 2021-04-09 17:00:00 : 남산면   35243 ----------


 ---------- 2021-04-09 18:00:00 : 석사동   35244 ----------


 ---------- 2021-04-09 22:00:00 : 효자1동   35246 ----------


 ---------- 2021-04-10 00:00:00 : 후평1동   35247 ----------


 ---------- 2021-04-10 12:00:00 : 소양동   35248 ----------


 ---------- 2021-04-10 12:00:00 : 동  면   35253 ----------


 ---------- 2021-04-10 21:00:00 : 동  면   35256 ----------


 ---------- 2021-04-11 02:00:00 : 퇴계동   35259 ----------


 ---------- 2021-04-11 11:00:00 : 남산면   35260 ----------


 ---------- 2021-04-11 14:00:00 : 동  면   35263 ----------


 ---------- 2021-04-11 15:00:00 : 동내면   35267 ----------


 ---------- 2021-04-11 15:00:00 : 효자1동   35268 ----------


 ---------- 2021-04-11 15:00:00 : 남산면   35270 ----------


 ---------- 2021-04-11 15:00:00 : 동  면   35271 ----------


 ---------- 2021-04-11 16:00:00 : 동  면   35272 ----------


 ---------- 2021-04-11 19:00:00 : 신사우동   35275 ----------


 ---------- 2021-04-11 23:00:00 : 석사동   35277 ----------


 ---------- 2021-04-12 12:00:00 : 남  면   35278 ----------


 ---------- 2021-04-12 14:00:00 : 동내면   35281 ----------


 ---------- 2021-04-12 19:00:00 : 동  면   35284 ----------


 ---------- 2021-04-13 05:00:00 : 후평1동   35287 ----------


 ---------- 2021-04-13 10:00:00 : 강남동   35288 ----------


 ---------- 2021-04-13 15:00:00 : 서  면   35289 ----------


 ---------- 2021-04-14 13:00:00 : 서  면   35290 ----------


 ---------- 2021-04-14 15:00:00 : 동내면   35291 ----------


 ---------- 2021-04-14 16:00:00 : 퇴계동   35293 ----------


 ---------- 2021-04-14 17:00:00 : 퇴계동   35294 ----------


 ---------- 2021-04-14 17:00:00 : 교  동   35295 ----------


 ---------- 2021-04-14 19:00:00 : 효자1동   35299 ----------


 ---------- 2021-04-14 20:00:00 : 동  면   35300 ----------


 ---------- 2021-04-14 21:00:00 : 효자1동   35302 ----------


 ---------- 2021-04-15 08:00:00 : 조운동   35304 ----------


 ---------- 2021-04-15 10:00:00 : 약사명동   35305 ----------


 ---------- 2021-04-15 15:00:00 : 신동면   35306 ----------


 ---------- 2021-04-15 15:00:00 : 강남동   35308 ----------


 ---------- 2021-04-16 09:00:00 : 신북읍   35309 ----------


 ---------- 2021-04-16 12:00:00 : 약사명동   35310 ----------


 ---------- 2021-04-16 17:00:00 : 강남동   35311 ----------


 ---------- 2021-04-16 20:00:00 : 석사동   35312 ----------


 ---------- 2021-04-16 23:00:00 : 신사우동   35315 ----------


 ---------- 2021-04-17 01:00:00 : 후평1동   35316 ----------


 ---------- 2021-04-17 05:00:00 : 신사우동   35319 ----------


 ---------- 2021-04-17 09:00:00 : 강남동   35321 ----------


 ---------- 2021-04-17 09:00:00 : 근화동   35324 ----------


 ---------- 2021-04-17 10:00:00 : 강남동   35326 ----------


 ---------- 2021-04-17 11:00:00 : 강남동   35328 ----------


 ---------- 2021-04-17 12:00:00 : 남산면   35332 ----------


 ---------- 2021-04-17 16:00:00 : 강남동   35338 ----------


 ---------- 2021-04-17 16:00:00 : 근화동   35340 ----------


 ---------- 2021-04-17 16:00:00 : 약사명동   35342 ----------


 ---------- 2021-04-17 16:00:00 : 후평1동   35345 ----------


 ---------- 2021-04-17 16:00:00 : 퇴계동   35347 ----------


 ---------- 2021-04-17 19:00:00 : 퇴계동   35348 ----------


 ---------- 2021-04-17 23:00:00 : 후평1동   35349 ----------


 ---------- 2021-04-18 00:00:00 : 강남동   35351 ----------


 ---------- 2021-04-18 09:00:00 : 신동면   35355 ----------


 ---------- 2021-04-18 17:00:00 : 동내면   35357 ----------


 ---------- 2021-04-18 17:00:00 : 근화동   35360 ----------


 ---------- 2021-04-19 00:00:00 : 강남동   35361 ----------


 ---------- 2021-04-19 00:00:00 : 효자1동   35363 ----------


 ---------- 2021-04-19 10:00:00 : 근화동   35365 ----------


 ---------- 2021-04-19 13:00:00 : 교  동   35368 ----------


 ---------- 2021-04-19 14:00:00 : 신북읍   35369 ----------


 ---------- 2021-04-19 15:00:00 : 서  면   35370 ----------


 ---------- 2021-04-19 15:00:00 : 후평1동   35371 ----------


 ---------- 2021-04-19 16:00:00 : 동내면   35372 ----------


 ---------- 2021-04-19 16:00:00 : 효자1동   35373 ----------


 ---------- 2021-04-19 16:00:00 : 남산면   35374 ----------


 ---------- 2021-04-19 16:00:00 : 소양동   35377 ----------


 ---------- 2021-04-19 16:00:00 : 후평1동   35378 ----------

 ---------- 2021-04-19 21:00:00 : 신동면   35380 ----------


 ---------- 2021-04-20 07:00:00 : 신북읍   35384 ----------


 ---------- 2021-04-20 08:00:00 : 효자1동   35386 ----------


 ---------- 2021-04-20 11:00:00 : 남  면   35388 ----------


 ---------- 2021-04-20 13:00:00 : 사북면   35391 ----------


 ---------- 2021-04-20 16:00:00 : 강남동   35392 ----------


 ---------- 2021-04-20 16:00:00 : 동내면   35393 ----------


 ---------- 2021-04-20 16:00:00 : 조운동   35394 ----------


 ---------- 2021-04-20 17:00:00 : 석사동   35395 ----------


 ---------- 2021-04-20 19:00:00 : 남산면   35396 ----------


 ---------- 2021-04-20 21:00:00 : 석사동   35397 ----------


 ---------- 2021-04-20 21:00:00 : 후평1동   35399 ----------


 ---------- 2021-04-21 02:00:00 : 후평1동   35402 ----------


 ---------- 2021-04-21 17:00:00 : 효자1동   35404 ----------


 ---------- 2021-04-21 21:00:00 : 신사우동   35407 ----------


 ---------- 2021-04-21 23:00:00 : 효자1동   35410 ----------


 ---------- 2021-04-21 23:00:00 : 후평1동   35413 ----------


 ---------- 2021-04-22 00:00:00 : 후평1동   35414 ----------


 ---------- 2021-04-22 05:00:00 : 동내면   35418 ----------


 ---------- 2021-04-22 09:00:00 : 강남동   35419 ----------


 ---------- 2021-04-22 11:00:00 : 신사우동   35421 ----------


 ---------- 2021-04-23 02:00:00 : 동산면   35424 ----------


 ---------- 2021-04-23 11:00:00 : 남  면   35428 ----------


 ---------- 2021-04-23 12:00:00 : 석사동   35429 ----------


 ---------- 2021-04-23 12:00:00 : 효자1동   35431 ----------


 ---------- 2021-04-23 12:00:00 : 교  동   35433 ----------


 ---------- 2021-04-23 13:00:00 : 퇴계동   35436 ----------


 ---------- 2021-04-23 15:00:00 : 남산면   35439 ----------


 ---------- 2021-04-23 16:00:00 : 남산면   35440 ----------


 ---------- 2021-04-23 17:00:00 : 강남동   35441 ----------


 ---------- 2021-04-23 19:00:00 : 소양동   35444 ----------


 ---------- 2021-04-24 01:00:00 : 후평1동   35445 ----------


 ---------- 2021-04-24 03:00:00 : 후평1동   35447 ----------


 ---------- 2021-04-24 14:00:00 : 강남동   35450 ----------


 ---------- 2021-04-24 14:00:00 : 약사명동   35453 ----------


 ---------- 2021-04-24 16:00:00 : 신사우동   35455 ----------


 ---------- 2021-04-24 18:00:00 : 강남동   35458 ----------


 ---------- 2021-04-24 18:00:00 : 동내면   35460 ----------


 ---------- 2021-04-24 20:00:00 : 퇴계동   35463 ----------


 ---------- 2021-04-25 01:00:00 : 근화동   35464 ----------


 ---------- 2021-04-25 10:00:00 : 서  면   35466 ----------


 ---------- 2021-04-25 10:00:00 : 퇴계동   35467 ----------


 ---------- 2021-04-25 12:00:00 : 석사동   35468 ----------


 ---------- 2021-04-25 15:00:00 : 신사우동   35470 ----------


 ---------- 2021-04-25 15:00:00 : 약사명동   35473 ----------


 ---------- 2021-04-25 16:00:00 : 남산면   35475 ----------


 ---------- 2021-04-25 20:00:00 : 석사동   35476 ----------


 ---------- 2021-04-25 21:00:00 : 신사우동   35477 ----------


 ---------- 2021-04-25 22:00:00 : 석사동   35479 ----------


 ---------- 2021-04-26 02:00:00 : 신동면   35481 ----------


 ---------- 2021-04-26 08:00:00 : 후평1동   35482 ----------


 ---------- 2021-04-26 09:00:00 : 동내면   35483 ----------


 ---------- 2021-04-26 12:00:00 : 석사동   35485 ----------


 ---------- 2021-04-26 13:00:00 : 신북읍   35486 ----------


 ---------- 2021-04-26 14:00:00 : 신북읍   35488 ----------


 ---------- 2021-04-26 18:00:00 : 석사동   35490 ----------


 ---------- 2021-04-26 22:00:00 : 후평1동   35491 ----------


 ---------- 2021-04-27 00:00:00 : 소양동   35494 ----------


 ---------- 2021-04-27 08:00:00 : 동내면   35499 ----------


 ---------- 2021-04-27 08:00:00 : 남산면   35501 ----------


 ---------- 2021-04-27 13:00:00 : 후평1동   35502 ----------


 ---------- 2021-04-27 14:00:00 : 신동면   35506 ----------


 ---------- 2021-04-27 15:00:00 : 효자1동   35507 ----------


 ---------- 2021-04-28 05:00:00 : 동내면   35508 ----------


 ---------- 2021-04-28 05:00:00 : 신북읍   35509 ----------


 ---------- 2021-04-28 06:00:00 : 동내면   35510 ----------


 ---------- 2021-04-28 09:00:00 : 후평1동   35511 ----------


 ---------- 2021-04-28 10:00:00 : 후평1동   35513 ----------


 ---------- 2021-04-28 12:00:00 : 강남동   35515 ----------


 ---------- 2021-04-28 21:00:00 : 후평1동   35517 ----------


 ---------- 2021-04-28 22:00:00 : 소양동   35521 ----------


 ---------- 2021-04-29 06:00:00 : 서  면   35524 ----------


 ---------- 2021-04-29 08:00:00 : 효자1동   35526 ----------


 ---------- 2021-04-29 09:00:00 : 동내면   35527 ----------


 ---------- 2021-04-29 18:00:00 : 서  면   35528 ----------


 ---------- 2021-04-29 22:00:00 : 후평1동   35530 ----------


 ---------- 2021-04-29 22:00:00 : 북산면   35531 ----------


 ---------- 2021-04-30 06:00:00 : 강남동   35532 ----------


 ---------- 2021-04-30 09:00:00 : 사북면   35534 ----------


 ---------- 2021-04-30 09:00:00 : 효자1동   35535 ----------


 ---------- 2021-04-30 12:00:00 : 효자1동   35536 ----------


 ---------- 2021-04-30 17:00:00 : 소양동   35537 ----------


 ---------- 2021-04-30 18:00:00 : 신북읍   35539 ----------


 ---------- 2021-04-30 19:00:00 : 근화동   35542 ----------


 ---------- 2021-05-01 08:00:00 : 효자1동   35547 ----------


 ---------- 2021-05-01 09:00:00 : 동내면   35550 ----------


 ---------- 2021-05-01 10:00:00 : 사북면   35551 ----------


 ---------- 2021-05-01 21:00:00 : 동  면   35553 ----------


 ---------- 2021-05-02 01:00:00 : 효자1동   35554 ----------


 ---------- 2021-05-02 04:00:00 : 남산면   35556 ----------


 ---------- 2021-05-02 10:00:00 : 강남동   35557 ----------


 ---------- 2021-05-02 12:00:00 : 효자1동   35560 ----------


 ---------- 2021-05-02 16:00:00 : 서  면   35562 ----------


 ---------- 2021-05-02 16:00:00 : 남산면   35564 ----------


 ---------- 2021-05-03 08:00:00 : 조운동   35565 ----------


 ---------- 2021-05-03 13:00:00 : 남산면   35566 ----------


 ---------- 2021-05-03 15:00:00 : 석사동   35569 ----------


 ---------- 2021-05-03 16:00:00 : 퇴계동   35570 ----------


 ---------- 2021-05-03 17:00:00 : 서  면   35574 ----------


 ---------- 2021-05-03 18:00:00 : 사북면   35575 ----------


 ---------- 2021-05-03 20:00:00 : 강남동   35577 ----------


 ---------- 2021-05-03 21:00:00 : 조운동   35580 ----------


 ---------- 2021-05-03 22:00:00 : 동산면   35581 ----------


 ---------- 2021-05-04 11:00:00 : 소양동   35585 ----------


 ---------- 2021-05-04 12:00:00 : 동산면   35587 ----------


 ---------- 2021-05-04 16:00:00 : 강남동   35591 ----------


 ---------- 2021-05-04 18:00:00 : 서  면   35592 ----------


 ---------- 2021-05-04 19:00:00 : 신동면   35596 ----------


 ---------- 2021-05-04 22:00:00 : 효자1동   35599 ----------


 ---------- 2021-05-05 07:00:00 : 동산면   35602 ----------


 ---------- 2021-05-05 09:00:00 : 서  면   35603 ----------


 ---------- 2021-05-05 10:00:00 : 동내면   35604 ----------


 ---------- 2021-05-05 11:00:00 : 서  면   35605 ----------


 ---------- 2021-05-05 12:00:00 : 동내면   35607 ----------


 ---------- 2021-05-05 17:00:00 : 사북면   35609 ----------


 ---------- 2021-05-05 18:00:00 : 사북면   35610 ----------


 ---------- 2021-05-05 18:00:00 : 소양동   35612 ----------


 ---------- 2021-05-05 22:00:00 : 신사우동   35615 ----------


 ---------- 2021-05-06 06:00:00 : 신동면   35619 ----------


 ---------- 2021-05-06 09:00:00 : 소양동   35623 ----------


 ---------- 2021-05-06 12:00:00 : 효자1동   35624 ----------


 ---------- 2021-05-06 15:00:00 : 효자1동   35625 ----------


 ---------- 2021-05-06 15:00:00 : 신북읍   35626 ----------


 ---------- 2021-05-06 17:00:00 : 퇴계동   35628 ----------


 ---------- 2021-05-06 18:00:00 : 효자1동   35629 ----------


 ---------- 2021-05-07 10:00:00 : 약사명동   35633 ----------


 ---------- 2021-05-07 11:00:00 : 강남동   35636 ----------


 ---------- 2021-05-07 13:00:00 : 남  면   35639 ----------


 ---------- 2021-05-07 14:00:00 : 남산면   35640 ----------


 ---------- 2021-05-07 16:00:00 : 남산면   35642 ----------


 ---------- 2021-05-07 18:00:00 : 근화동   35643 ----------


 ---------- 2021-05-07 18:00:00 : 약사명동   35648 ----------


 ---------- 2021-05-07 19:00:00 : 후평1동   35651 ----------


 ---------- 2021-05-08 00:00:00 : 후평1동   35654 ----------


 ---------- 2021-05-08 03:00:00 : 후평1동   35657 ----------


 ---------- 2021-05-08 07:00:00 : 신사우동   35658 ----------

 ---------- 2021-05-08 10:00:00 : 석사동   35659 ----------


 ---------- 2021-05-08 11:00:00 : 후평1동   35661 ----------


 ---------- 2021-05-08 12:00:00 : 약사명동   35663 ----------


 ---------- 2021-05-08 14:00:00 : 서  면   35665 ----------


 ---------- 2021-05-08 14:00:00 : 남산면   35667 ----------


 ---------- 2021-05-08 18:00:00 : 강남동   35668 ----------


 ---------- 2021-05-08 18:00:00 : 퇴계동   35669 ----------


 ---------- 2021-05-08 19:00:00 : 후평1동   35671 ----------


 ---------- 2021-05-08 20:00:00 : 효자1동   35672 ----------


 ---------- 2021-05-09 06:00:00 : 동내면   35673 ----------


 ---------- 2021-05-09 06:00:00 : 교  동   35674 ----------


 ---------- 2021-05-09 07:00:00 : 서  면   35678 ----------


 ---------- 2021-05-09 09:00:00 : 서  면   35679 ----------


 ---------- 2021-05-09 11:00:00 : 신사우동   35681 ----------


 ---------- 2021-05-09 12:00:00 : 후평1동   35682 ----------


 ---------- 2021-05-09 14:00:00 : 후평1동   35683 ----------


 ---------- 2021-05-09 14:00:00 : 조운동   35685 ----------


 ---------- 2021-05-09 16:00:00 : 동내면   35686 ----------


 ---------- 2021-05-10 01:00:00 : 신사우동   35688 ----------


 ---------- 2021-05-10 08:00:00 : 신사우동   35691 ----------


 ---------- 2021-05-10 10:00:00 : 사북면   35693 ----------


 ---------- 2021-05-10 13:00:00 : 석사동   35694 ----------


 ---------- 2021-05-10 14:00:00 : 효자1동   35695 ----------


 ---------- 2021-05-10 14:00:00 : 후평1동   35696 ----------


 ---------- 2021-05-10 14:00:00 : 퇴계동   35697 ----------


 ---------- 2021-05-10 18:00:00 : 효자1동   35698 ----------


 ---------- 2021-05-11 11:00:00 : 강남동   35699 ----------


 ---------- 2021-05-11 12:00:00 : 조운동   35700 ----------


 ---------- 2021-05-11 13:00:00 : 교  동   35701 ----------


 ---------- 2021-05-11 14:00:00 : 약사명동   35702 ----------


 ---------- 2021-05-11 15:00:00 : 교  동   35703 ----------


 ---------- 2021-05-11 16:00:00 : 북산면   35705 ----------


 ---------- 2021-05-11 17:00:00 : 석사동   35706 ----------


 ---------- 2021-05-11 17:00:00 : 북산면   35707 ----------


 ---------- 2021-05-11 22:00:00 : 근화동   35708 ----------


 ---------- 2021-05-12 10:00:00 : 후평1동   35711 ----------


 ---------- 2021-05-12 12:00:00 : 신사우동   35715 ----------


 ---------- 2021-05-12 12:00:00 : 신북읍   35720 ----------


 ---------- 2021-05-12 14:00:00 : 소양동   35724 ----------


 ---------- 2021-05-12 18:00:00 : 후평1동   35725 ----------


 ---------- 2021-05-12 19:00:00 : 효자1동   35726 ----------


 ---------- 2021-05-12 19:00:00 : 남산면   35730 ----------


 ---------- 2021-05-13 10:00:00 : 동산면   35733 ----------


 ---------- 2021-05-13 11:00:00 : 동내면   35734 ----------


 ---------- 2021-05-13 12:00:00 : 약사명동   35735 ----------


 ---------- 2021-05-13 14:00:00 : 신북읍   35738 ----------


 ---------- 2021-05-13 15:00:00 : 동내면   35742 ----------


 ---------- 2021-05-13 15:00:00 : 퇴계동   35743 ----------


 ---------- 2021-05-13 17:00:00 : 사북면   35744 ----------


 ---------- 2021-05-13 18:00:00 : 신사우동   35745 ----------


 ---------- 2021-05-13 23:00:00 : 후평1동   35748 ----------


 ---------- 2021-05-14 09:00:00 : 신사우동   35749 ----------


 ---------- 2021-05-14 10:00:00 : 남  면   35750 ----------


 ---------- 2021-05-14 12:00:00 : 석사동   35751 ----------


 ---------- 2021-05-14 12:00:00 : 후평1동   35752 ----------


 ---------- 2021-05-14 13:00:00 : 석사동   35754 ----------


 ---------- 2021-05-14 15:00:00 : 신사우동   35755 ----------


 ---------- 2021-05-14 15:00:00 : 후평1동   35756 ----------


 ---------- 2021-05-14 16:00:00 : 퇴계동   35757 ----------


 ---------- 2021-05-14 16:00:00 : 조운동   35759 ----------


 ---------- 2021-05-14 17:00:00 : 동내면   35760 ----------


 ---------- 2021-05-14 18:00:00 : 퇴계동   35761 ----------


 ---------- 2021-05-14 20:00:00 : 퇴계동   35762 ----------


 ---------- 2021-05-14 21:00:00 : 효자1동   35764 ----------


 ---------- 2021-05-14 23:00:00 : 후평1동   35765 ----------


 ---------- 2021-05-15 02:00:00 : 석사동   35766 ----------


 ---------- 2021-05-15 05:00:00 : 강남동   35770 ----------


 ---------- 2021-05-15 08:00:00 : 석사동   35771 ----------


 ---------- 2021-05-15 08:00:00 : 동내면   35772 ----------


 ---------- 2021-05-15 11:00:00 : 동내면   35773 ----------


 ---------- 2021-05-15 12:00:00 : 동산면   35776 ----------


 ---------- 2021-05-15 15:00:00 : 후평1동   35779 ----------


 ---------- 2021-05-15 16:00:00 : 효자1동   35780 ----------


 ---------- 2021-05-15 16:00:00 : 후평1동   35781 ----------


 ---------- 2021-05-15 18:00:00 : 퇴계동   35782 ----------


 ---------- 2021-05-15 19:00:00 : 조운동   35783 ----------


 ---------- 2021-05-15 23:00:00 : 신사우동   35784 ----------


 ---------- 2021-05-16 00:00:00 : 신사우동   35787 ----------


 ---------- 2021-05-16 01:00:00 : 조운동   35788 ----------


 ---------- 2021-05-16 03:00:00 : 약사명동   35792 ----------


 ---------- 2021-05-16 04:00:00 : 동내면   35793 ----------


 ---------- 2021-05-16 08:00:00 : 동산면   35796 ----------


 ---------- 2021-05-16 15:00:00 : 석사동   35797 ----------


 ---------- 2021-05-16 15:00:00 : 동  면   35798 ----------


 ---------- 2021-05-16 16:00:00 : 후평1동   35799 ----------


 ---------- 2021-05-16 19:00:00 : 조운동   35800 ----------


 ---------- 2021-05-16 20:00:00 : 강남동   35801 ----------


 ---------- 2021-05-16 21:00:00 : 동  면   35804 ----------


 ---------- 2021-05-17 05:00:00 : 남  면   35806 ----------


 ---------- 2021-05-17 06:00:00 : 남  면   35807 ----------


 ---------- 2021-05-17 09:00:00 : 퇴계동   35810 ----------


 ---------- 2021-05-17 12:00:00 : 소양동   35811 ----------


 ---------- 2021-05-17 13:00:00 : 서  면   35814 ----------


 ---------- 2021-05-17 14:00:00 : 신사우동   35815 ----------


 ---------- 2021-05-17 21:00:00 : 후평1동   35816 ----------


 ---------- 2021-05-17 23:00:00 : 동내면   35817 ----------


 ---------- 2021-05-18 00:00:00 : 강남동   35818 ----------


 ---------- 2021-05-18 09:00:00 : 동내면   35819 ----------


 ---------- 2021-05-18 09:00:00 : 신북읍   35820 ----------


 ---------- 2021-05-18 11:00:00 : 서  면   35821 ----------


 ---------- 2021-05-18 15:00:00 : 동내면   35824 ----------


 ---------- 2021-05-18 17:00:00 : 효자1동   35828 ----------


 ---------- 2021-05-18 18:00:00 : 퇴계동   35829 ----------


 ---------- 2021-05-19 00:00:00 : 효자1동   35830 ----------


 ---------- 2021-05-19 01:00:00 : 후평1동   35832 ----------


 ---------- 2021-05-19 04:00:00 : 강남동   35834 ----------


 ---------- 2021-05-19 08:00:00 : 동내면   35837 ----------


 ---------- 2021-05-19 08:00:00 : 신사우동   35840 ----------


 ---------- 2021-05-19 11:00:00 : 남산면   35842 ----------


 ---------- 2021-05-19 11:00:00 : 신사우동   35843 ----------


 ---------- 2021-05-19 13:00:00 : 신사우동   35844 ----------


 ---------- 2021-05-19 14:00:00 : 후평1동   35845 ----------


 ---------- 2021-05-19 16:00:00 : 후평1동   35846 ----------


 ---------- 2021-05-19 17:00:00 : 동내면   35847 ----------


 ---------- 2021-05-19 21:00:00 : 강남동   35850 ----------


 ---------- 2021-05-20 07:00:00 : 서  면   35853 ----------


 ---------- 2021-05-20 09:00:00 : 동내면   35856 ----------


 ---------- 2021-05-20 10:00:00 : 강남동   35858 ----------


 ---------- 2021-05-20 17:00:00 : 동  면   35861 ----------


 ---------- 2021-05-20 19:00:00 : 강남동   35864 ----------


 ---------- 2021-05-21 07:00:00 : 강남동   35865 ----------


 ---------- 2021-05-21 10:00:00 : 효자1동   35866 ----------


 ---------- 2021-05-21 15:00:00 : 퇴계동   35867 ----------


 ---------- 2021-05-21 16:00:00 : 석사동   35868 ----------


 ---------- 2021-05-21 18:00:00 : 강남동   35872 ----------


 ---------- 2021-05-21 19:00:00 : 동  면   35873 ----------


 ---------- 2021-05-21 21:00:00 : 효자1동   35874 ----------


 ---------- 2021-05-22 11:00:00 : 서  면   35876 ----------


 ---------- 2021-05-22 11:00:00 : 소양동   35877 ----------


 ---------- 2021-05-22 15:00:00 : 석사동   35882 ----------


 ---------- 2021-05-22 15:00:00 : 후평1동   35885 ----------


 ---------- 2021-05-22 16:00:00 : 동  면   35889 ----------


 ---------- 2021-05-22 17:00:00 : 동  면   35890 ----------


 ---------- 2021-05-22 18:00:00 : 효자1동   35891 ----------


 ---------- 2021-05-22 20:00:00 : 남  면   35893 ----------


 ---------- 2021-05-22 22:00:00 : 석사동   35896 ----------

 ---------- 2021-05-23 06:00:00 : 신북읍   35898 ----------


 ---------- 2021-05-23 12:00:00 : 동  면   35899 ----------


 ---------- 2021-05-23 14:00:00 : 동  면   35900 ----------


 ---------- 2021-05-23 16:00:00 : 근화동   35903 ----------


 ---------- 2021-05-23 16:00:00 : 후평1동   35907 ----------


 ---------- 2021-05-23 17:00:00 : 남산면   35909 ----------


 ---------- 2021-05-24 10:00:00 : 후평1동   35910 ----------


 ---------- 2021-05-24 11:00:00 : 석사동   35911 ----------


 ---------- 2021-05-24 11:00:00 : 신동면   35914 ----------


 ---------- 2021-05-24 13:00:00 : 서  면   35915 ----------


 ---------- 2021-05-24 13:00:00 : 약사명동   35916 ----------


 ---------- 2021-05-24 14:00:00 : 동내면   35917 ----------


 ---------- 2021-05-24 14:00:00 : 남산면   35920 ----------


 ---------- 2021-05-24 14:00:00 : 신북읍   35921 ----------


 ---------- 2021-05-24 17:00:00 : 서  면   35922 ----------


 ---------- 2021-05-24 19:00:00 : 강남동   35923 ----------


 ---------- 2021-05-24 20:00:00 : 근화동   35926 ----------


 ---------- 2021-05-24 23:00:00 : 근화동   35929 ----------


 ---------- 2021-05-25 05:00:00 : 강남동   35933 ----------


 ---------- 2021-05-25 16:00:00 : 석사동   35934 ----------


 ---------- 2021-05-25 16:00:00 : 퇴계동   35936 ----------


 ---------- 2021-05-25 17:00:00 : 동  면   35937 ----------


 ---------- 2021-05-26 10:00:00 : 서  면   35939 ----------


 ---------- 2021-05-26 12:00:00 : 동내면   35940 ----------


 ---------- 2021-05-26 13:00:00 : 신북읍   35941 ----------


 ---------- 2021-05-26 15:00:00 : 사북면   35942 ----------


 ---------- 2021-05-26 18:00:00 : 퇴계동   35944 ----------


 ---------- 2021-05-26 18:00:00 : 동산면   35945 ----------


 ---------- 2021-05-26 20:00:00 : 강남동   35948 ----------


 ---------- 2021-05-27 06:00:00 : 동내면   35949 ----------


 ---------- 2021-05-27 08:00:00 : 강남동   35951 ----------


 ---------- 2021-05-27 09:00:00 : 효자1동   35954 ----------


 ---------- 2021-05-27 12:00:00 : 강남동   35958 ----------


 ---------- 2021-05-27 12:00:00 : 동  면   35961 ----------


 ---------- 2021-05-27 16:00:00 : 교  동   35962 ----------


 ---------- 2021-05-27 18:00:00 : 남산면   35967 ----------


 ---------- 2021-05-27 18:00:00 : 동산면   35969 ----------


 ---------- 2021-05-27 19:00:00 : 근화동   35973 ----------


 ---------- 2021-05-27 22:00:00 : 서  면   35976 ----------


 ---------- 2021-05-27 23:00:00 : 근화동   35979 ----------


 ---------- 2021-05-28 04:00:00 : 신북읍   35982 ----------


 ---------- 2021-05-28 15:00:00 : 강남동   35984 ----------


 ---------- 2021-05-28 16:00:00 : 석사동   35986 ----------


 ---------- 2021-05-28 18:00:00 : 효자1동   35988 ----------


 ---------- 2021-05-28 19:00:00 : 서  면   35989 ----------


 ---------- 2021-05-28 19:00:00 : 소양동   35990 ----------


 ---------- 2021-05-28 20:00:00 : 효자1동   35991 ----------


 ---------- 2021-05-28 20:00:00 : 신북읍   35992 ----------


 ---------- 2021-05-29 08:00:00 : 효자1동   35994 ----------


 ---------- 2021-05-29 09:00:00 : 후평1동   35995 ----------


 ---------- 2021-05-29 10:00:00 : 서  면   35997 ----------


 ---------- 2021-05-29 10:00:00 : 후평1동   35998 ----------


 ---------- 2021-05-29 13:00:00 : 동  면   35999 ----------


 ---------- 2021-05-29 14:00:00 : 동내면   36002 ----------


 ---------- 2021-05-29 14:00:00 : 효자1동   36004 ----------


 ---------- 2021-05-29 17:00:00 : 남산면   36006 ----------


 ---------- 2021-05-29 17:00:00 : 근화동   36007 ----------


 ---------- 2021-05-29 18:00:00 : 근화동   36008 ----------


 ---------- 2021-05-29 18:00:00 : 북산면   36012 ----------


 ---------- 2021-05-30 05:00:00 : 동내면   36014 ----------


 ---------- 2021-05-30 10:00:00 : 석사동   36018 ----------


 ---------- 2021-05-30 10:00:00 : 후평1동   36022 ----------


 ---------- 2021-05-30 11:00:00 : 신동면   36027 ----------


 ---------- 2021-05-30 12:00:00 : 남산면   36028 ----------


 ---------- 2021-05-30 14:00:00 : 강남동   36029 ----------


 ---------- 2021-05-30 14:00:00 : 서  면   36031 ----------


 ---------- 2021-05-30 14:00:00 : 조운동   36032 ----------


 ---------- 2021-05-30 15:00:00 : 근화동   36035 ----------


 ---------- 2021-05-30 15:00:00 : 동  면   36037 ----------


 ---------- 2021-05-30 17:00:00 : 석사동   36038 ----------


 ---------- 2021-05-30 17:00:00 : 교  동   36043 ----------


 ---------- 2021-05-30 19:00:00 : 교  동   36044 ----------


 ---------- 2021-05-31 08:00:00 : 남산면   36045 ----------


 ---------- 2021-05-31 10:00:00 : 퇴계동   36046 ----------


 ---------- 2021-05-31 13:00:00 : 석사동   36049 ----------


 ---------- 2021-05-31 14:00:00 : 석사동   36050 ----------


 ---------- 2021-05-31 16:00:00 : 근화동   36051 ----------


 ---------- 2021-05-31 18:00:00 : 퇴계동   36054 ----------


 ---------- 2021-05-31 19:00:00 : 북산면   36056 ----------


 ---------- 2021-05-31 22:00:00 : 신사우동   36057 ----------


 ---------- 2021-06-01 00:00:00 : 동  면   36058 ----------


 ---------- 2021-06-01 05:00:00 : 신북읍   36060 ----------


 ---------- 2021-06-01 09:00:00 : 동산면   36061 ----------


 ---------- 2021-06-01 13:00:00 : 석사동   36062 ----------


 ---------- 2021-06-01 15:00:00 : 동산면   36063 ----------


 ---------- 2021-06-01 16:00:00 : 교  동   36064 ----------


 ---------- 2021-06-01 18:00:00 : 소양동   36065 ----------


 ---------- 2021-06-01 20:00:00 : 퇴계동   36066 ----------


 ---------- 2021-06-01 22:00:00 : 동  면   36069 ----------


 ---------- 2021-06-02 10:00:00 : 신사우동   36070 ----------


 ---------- 2021-06-02 11:00:00 : 신북읍   36073 ----------


 ---------- 2021-06-02 22:00:00 : 석사동   36077 ----------


 ---------- 2021-06-02 23:00:00 : 석사동   36078 ----------


 ---------- 2021-06-03 05:00:00 : 소양동   36080 ----------


 ---------- 2021-06-03 06:00:00 : 소양동   36081 ----------


 ---------- 2021-06-03 08:00:00 : 동산면   36084 ----------


 ---------- 2021-06-03 09:00:00 : 근화동   36085 ----------


 ---------- 2021-06-03 09:00:00 : 신사우동   36086 ----------


 ---------- 2021-06-03 11:00:00 : 동  면   36087 ----------


 ---------- 2021-06-03 15:00:00 : 동산면   36090 ----------


 ---------- 2021-06-03 22:00:00 : 효자1동   36093 ----------


 ---------- 2021-06-03 23:00:00 : 조운동   36095 ----------


 ---------- 2021-06-04 08:00:00 : 신북읍   36096 ----------


 ---------- 2021-06-04 09:00:00 : 강남동   36097 ----------


 ---------- 2021-06-04 12:00:00 : 강남동   36100 ----------


 ---------- 2021-06-04 14:00:00 : 효자1동   36101 ----------


 ---------- 2021-06-04 15:00:00 : 신동면   36103 ----------


 ---------- 2021-06-04 18:00:00 : 신사우동   36104 ----------


 ---------- 2021-06-04 19:00:00 : 강남동   36105 ----------


 ---------- 2021-06-04 21:00:00 : 석사동   36106 ----------


 ---------- 2021-06-05 10:00:00 : 석사동   36108 ----------


 ---------- 2021-06-05 10:00:00 : 퇴계동   36110 ----------


 ---------- 2021-06-05 11:00:00 : 남산면   36111 ----------


 ---------- 2021-06-05 11:00:00 : 교  동   36113 ----------


 ---------- 2021-06-05 13:00:00 : 강남동   36116 ----------


 ---------- 2021-06-05 16:00:00 : 소양동   36117 ----------


 ---------- 2021-06-05 18:00:00 : 서  면   36120 ----------


 ---------- 2021-06-05 19:00:00 : 후평1동   36123 ----------


 ---------- 2021-06-05 20:00:00 : 신사우동   36125 ----------


 ---------- 2021-06-06 02:00:00 : 효자1동   36126 ----------


 ---------- 2021-06-06 10:00:00 : 후평1동   36127 ----------


 ---------- 2021-06-06 11:00:00 : 퇴계동   36129 ----------


 ---------- 2021-06-06 12:00:00 : 소양동   36130 ----------


 ---------- 2021-06-06 14:00:00 : 석사동   36133 ----------


 ---------- 2021-06-06 17:00:00 : 후평1동   36135 ----------


 ---------- 2021-06-07 05:00:00 : 후평1동   36136 ----------


 ---------- 2021-06-07 09:00:00 : 강남동   36137 ----------


 ---------- 2021-06-07 10:00:00 : 석사동   36138 ----------


 ---------- 2021-06-07 11:00:00 : 서  면   36139 ----------


 ---------- 2021-06-07 12:00:00 : 서  면   36140 ----------


 ---------- 2021-06-07 12:00:00 : 동내면   36142 ----------


 ---------- 2021-06-07 13:00:00 : 교  동   36143 ----------


 ---------- 2021-06-07 16:00:00 : 소양동   36144 ----------


 ---------- 2021-06-07 16:00:00 : 후평1동   36145 ----------


 ---------- 2021-06-07 17:00:00 : 남산면   36146 ----------


 ---------- 2021-06-08 09:00:00 : 교  동   36148 ----------

 ---------- 2021-06-08 11:00:00 : 강남동   36150 ----------


 ---------- 2021-06-08 12:00:00 : 서  면   36151 ----------


 ---------- 2021-06-08 12:00:00 : 교  동   36152 ----------


 ---------- 2021-06-08 20:00:00 : 강남동   36155 ----------


 ---------- 2021-06-09 00:00:00 : 동산면   36156 ----------


 ---------- 2021-06-09 05:00:00 : 강남동   36159 ----------


 ---------- 2021-06-09 06:00:00 : 동내면   36160 ----------


 ---------- 2021-06-09 09:00:00 : 남산면   36161 ----------


 ---------- 2021-06-09 10:00:00 : 남산면   36164 ----------


 ---------- 2021-06-09 10:00:00 : 동  면   36165 ----------


 ---------- 2021-06-09 11:00:00 : 약사명동   36166 ----------


 ---------- 2021-06-09 13:00:00 : 신북읍   36167 ----------


 ---------- 2021-06-09 15:00:00 : 남  면   36168 ----------


 ---------- 2021-06-09 15:00:00 : 후평1동   36169 ----------


 ---------- 2021-06-09 16:00:00 : 동  면   36170 ----------


 ---------- 2021-06-09 17:00:00 : 동  면   36173 ----------


 ---------- 2021-06-09 18:00:00 : 신사우동   36176 ----------


 ---------- 2021-06-09 19:00:00 : 강남동   36179 ----------


 ---------- 2021-06-09 20:00:00 : 강남동   36181 ----------


 ---------- 2021-06-09 23:00:00 : 강남동   36185 ----------


 ---------- 2021-06-10 09:00:00 : 교  동   36186 ----------


 ---------- 2021-06-10 12:00:00 : 약사명동   36188 ----------


 ---------- 2021-06-10 12:00:00 : 동  면   36189 ----------


 ---------- 2021-06-10 14:00:00 : 교  동   36190 ----------


 ---------- 2021-06-10 15:00:00 : 동  면   36191 ----------


 ---------- 2021-06-10 16:00:00 : 효자1동   36193 ----------


 ---------- 2021-06-10 19:00:00 : 동내면   36196 ----------


 ---------- 2021-06-10 19:00:00 : 교  동   36197 ----------


 ---------- 2021-06-10 20:00:00 : 동  면   36199 ----------


 ---------- 2021-06-11 03:00:00 : 동내면   36200 ----------


 ---------- 2021-06-11 08:00:00 : 후평1동   36201 ----------


 ---------- 2021-06-11 10:00:00 : 동내면   36205 ----------


 ---------- 2021-06-11 11:00:00 : 신동면   36207 ----------


 ---------- 2021-06-11 16:00:00 : 동  면   36209 ----------


 ---------- 2021-06-11 19:00:00 : 신북읍   36212 ----------


 ---------- 2021-06-11 19:00:00 : 후평1동   36214 ----------


 ---------- 2021-06-11 22:00:00 : 후평1동   36217 ----------


 ---------- 2021-06-11 23:00:00 : 근화동   36220 ----------


 ---------- 2021-06-12 03:00:00 : 동  면   36221 ----------


 ---------- 2021-06-12 05:00:00 : 서  면   36224 ----------


 ---------- 2021-06-12 11:00:00 : 효자1동   36226 ----------


 ---------- 2021-06-12 12:00:00 : 동산면   36227 ----------


 ---------- 2021-06-12 20:00:00 : 남  면   36229 ----------


 ---------- 2021-06-13 00:00:00 : 석사동   36230 ----------


 ---------- 2021-06-13 01:00:00 : 효자1동   36231 ----------


 ---------- 2021-06-13 08:00:00 : 동  면   36232 ----------


 ---------- 2021-06-13 09:00:00 : 퇴계동   36233 ----------


 ---------- 2021-06-13 12:00:00 : 신사우동   36234 ----------


 ---------- 2021-06-13 14:00:00 : 소양동   36235 ----------


 ---------- 2021-06-13 14:00:00 : 동  면   36236 ----------


 ---------- 2021-06-13 16:00:00 : 강남동   36238 ----------


 ---------- 2021-06-13 16:00:00 : 후평1동   36239 ----------


 ---------- 2021-06-13 17:00:00 : 신동면   36240 ----------


 ---------- 2021-06-14 03:00:00 : 효자1동   36242 ----------


 ---------- 2021-06-14 06:00:00 : 효자1동   36243 ----------


 ---------- 2021-06-14 09:00:00 : 석사동   36244 ----------


 ---------- 2021-06-14 09:00:00 : 동  면   36245 ----------


 ---------- 2021-06-14 10:00:00 : 신동면   36246 ----------


 ---------- 2021-06-14 10:00:00 : 동내면   36247 ----------


 ---------- 2021-06-14 12:00:00 : 근화동   36249 ----------


 ---------- 2021-06-14 14:00:00 : 효자1동   36250 ----------


 ---------- 2021-06-14 18:00:00 : 효자1동   36252 ----------


 ---------- 2021-06-14 20:00:00 : 퇴계동   36257 ----------


 ---------- 2021-06-14 22:00:00 : 효자1동   36260 ----------


 ---------- 2021-06-15 08:00:00 : 신북읍   36263 ----------


 ---------- 2021-06-15 09:00:00 : 소양동   36264 ----------


 ---------- 2021-06-15 11:00:00 : 동내면   36265 ----------


 ---------- 2021-06-15 13:00:00 : 강남동   36268 ----------


 ---------- 2021-06-15 14:00:00 : 신사우동   36269 ----------


 ---------- 2021-06-15 14:00:00 : 신북읍   36270 ----------


 ---------- 2021-06-15 14:00:00 : 약사명동   36272 ----------


 ---------- 2021-06-15 16:00:00 : 동  면   36275 ----------


 ---------- 2021-06-15 16:00:00 : 후평1동   36278 ----------


 ---------- 2021-06-15 19:00:00 : 소양동   36281 ----------


 ---------- 2021-06-15 19:00:00 : 조운동   36282 ----------


 ---------- 2021-06-15 22:00:00 : 석사동   36283 ----------


 ---------- 2021-06-16 02:00:00 : 동내면   36286 ----------


 ---------- 2021-06-16 10:00:00 : 동산면   36287 ----------


 ---------- 2021-06-16 11:00:00 : 신동면   36288 ----------


 ---------- 2021-06-16 12:00:00 : 석사동   36290 ----------


 ---------- 2021-06-16 13:00:00 : 남산면   36292 ----------


 ---------- 2021-06-16 14:00:00 : 동내면   36293 ----------


 ---------- 2021-06-16 14:00:00 : 신북읍   36294 ----------


 ---------- 2021-06-16 15:00:00 : 후평1동   36295 ----------


 ---------- 2021-06-17 09:00:00 : 동내면   36296 ----------


 ---------- 2021-06-17 11:00:00 : 퇴계동   36299 ----------


 ---------- 2021-06-17 12:00:00 : 효자1동   36302 ----------


 ---------- 2021-06-17 13:00:00 : 동내면   36305 ----------


 ---------- 2021-06-17 15:00:00 : 강남동   36307 ----------


 ---------- 2021-06-17 15:00:00 : 신사우동   36308 ----------


 ---------- 2021-06-17 18:00:00 : 근화동   36311 ----------


 ---------- 2021-06-17 20:00:00 : 신동면   36314 ----------


 ---------- 2021-06-17 23:00:00 : 강남동   36315 ----------


 ---------- 2021-06-18 04:00:00 : 동산면   36316 ----------


 ---------- 2021-06-18 06:00:00 : 강남동   36319 ----------


 ---------- 2021-06-18 08:00:00 : 동산면   36320 ----------


 ---------- 2021-06-18 09:00:00 : 퇴계동   36321 ----------


 ---------- 2021-06-18 10:00:00 : 석사동   36327 ----------


 ---------- 2021-06-18 12:00:00 : 신동면   36331 ----------


 ---------- 2021-06-18 12:00:00 : 동  면   36332 ----------


 ---------- 2021-06-18 15:00:00 : 효자1동   36333 ----------


 ---------- 2021-06-18 18:00:00 : 석사동   36337 ----------


 ---------- 2021-06-18 18:00:00 : 동  면   36341 ----------


 ---------- 2021-06-18 20:00:00 : 남산면   36342 ----------


 ---------- 2021-06-18 22:00:00 : 신사우동   36344 ----------


 ---------- 2021-06-19 00:00:00 : 강남동   36348 ----------


 ---------- 2021-06-19 07:00:00 : 북산면   36351 ----------


 ---------- 2021-06-19 08:00:00 : 서  면   36352 ----------


 ---------- 2021-06-19 09:00:00 : 퇴계동   36353 ----------


 ---------- 2021-06-19 10:00:00 : 신동면   36354 ----------


 ---------- 2021-06-19 11:00:00 : 효자1동   36356 ----------


 ---------- 2021-06-19 11:00:00 : 남산면   36357 ----------


 ---------- 2021-06-19 12:00:00 : 신동면   36358 ----------


 ---------- 2021-06-19 13:00:00 : 조운동   36359 ----------


 ---------- 2021-06-19 14:00:00 : 신북읍   36360 ----------


 ---------- 2021-06-19 14:00:00 : 동  면   36361 ----------


 ---------- 2021-06-19 15:00:00 : 동산면   36366 ----------


 ---------- 2021-06-20 01:00:00 : 효자1동   36369 ----------


 ---------- 2021-06-20 02:00:00 : 효자1동   36371 ----------


 ---------- 2021-06-20 06:00:00 : 퇴계동   36373 ----------


 ---------- 2021-06-20 10:00:00 : 신북읍   36374 ----------


 ---------- 2021-06-20 11:00:00 : 신북읍   36375 ----------


 ---------- 2021-06-20 11:00:00 : 동  면   36376 ----------


 ---------- 2021-06-20 15:00:00 : 소양동   36377 ----------


 ---------- 2021-06-20 16:00:00 : 강남동   36378 ----------


 ---------- 2021-06-20 21:00:00 : 효자1동   36380 ----------


 ---------- 2021-06-20 22:00:00 : 강남동   36381 ----------


 ---------- 2021-06-21 06:00:00 : 소양동   36382 ----------


 ---------- 2021-06-21 09:00:00 : 효자1동   36383 ----------


 ---------- 2021-06-21 10:00:00 : 신사우동   36386 ----------


 ---------- 2021-06-21 12:00:00 : 동내면   36389 ----------


 ---------- 2021-06-21 14:00:00 : 신사우동   36390 ----------


 ---------- 2021-06-21 16:00:00 : 퇴계동   36393 ----------


 ---------- 2021-06-21 19:00:00 : 강남동   36395 ----------


 ---------- 2021-06-21 21:00:00 : 석사동   36398 ----------


 ---------- 2021-06-21 21:00:00 : 동산면   36400 ----------

 ---------- 2021-06-22 01:00:00 : 소양동   36401 ----------


 ---------- 2021-06-22 06:00:00 : 후평1동   36404 ----------


 ---------- 2021-06-22 07:00:00 : 석사동   36407 ----------


 ---------- 2021-06-22 09:00:00 : 서  면   36408 ----------


 ---------- 2021-06-22 11:00:00 : 남산면   36409 ----------


 ---------- 2021-06-22 12:00:00 : 신사우동   36410 ----------


 ---------- 2021-06-22 12:00:00 : 후평1동   36411 ----------


 ---------- 2021-06-22 13:00:00 : 동  면   36412 ----------


 ---------- 2021-06-22 14:00:00 : 서  면   36413 ----------


 ---------- 2021-06-22 14:00:00 : 동내면   36414 ----------


 ---------- 2021-06-22 15:00:00 : 후평1동   36415 ----------


 ---------- 2021-06-22 16:00:00 : 동내면   36416 ----------


 ---------- 2021-06-22 16:00:00 : 남산면   36417 ----------


 ---------- 2021-06-22 19:00:00 : 신북읍   36418 ----------


 ---------- 2021-06-23 00:00:00 : 석사동   36419 ----------


 ---------- 2021-06-23 08:00:00 : 퇴계동   36420 ----------


 ---------- 2021-06-23 09:00:00 : 신북읍   36421 ----------


 ---------- 2021-06-23 10:00:00 : 동  면   36424 ----------


 ---------- 2021-06-23 11:00:00 : 남산면   36425 ----------


 ---------- 2021-06-23 11:00:00 : 퇴계동   36427 ----------


 ---------- 2021-06-23 16:00:00 : 동내면   36429 ----------


 ---------- 2021-06-23 17:00:00 : 신북읍   36432 ----------


 ---------- 2021-06-23 17:00:00 : 후평1동   36433 ----------


 ---------- 2021-06-23 18:00:00 : 북산면   36435 ----------


 ---------- 2021-06-23 23:00:00 : 신사우동   36438 ----------


 ---------- 2021-06-24 07:00:00 : 후평1동   36441 ----------


 ---------- 2021-06-24 08:00:00 : 효자1동   36442 ----------


 ---------- 2021-06-24 09:00:00 : 석사동   36443 ----------


 ---------- 2021-06-24 10:00:00 : 서  면   36445 ----------


 ---------- 2021-06-24 10:00:00 : 남산면   36446 ----------


 ---------- 2021-06-24 11:00:00 : 동내면   36447 ----------


 ---------- 2021-06-24 11:00:00 : 효자1동   36449 ----------


 ---------- 2021-06-24 11:00:00 : 조운동   36450 ----------


 ---------- 2021-06-24 12:00:00 : 강남동   36451 ----------


 ---------- 2021-06-24 12:00:00 : 신북읍   36452 ----------


 ---------- 2021-06-24 15:00:00 : 소양동   36454 ----------


 ---------- 2021-06-24 15:00:00 : 후평1동   36457 ----------


 ---------- 2021-06-24 16:00:00 : 서  면   36458 ----------


 ---------- 2021-06-24 18:00:00 : 효자1동   36461 ----------


 ---------- 2021-06-24 20:00:00 : 동내면   36462 ----------


 ---------- 2021-06-24 23:00:00 : 후평1동   36465 ----------


 ---------- 2021-06-25 00:00:00 : 동  면   36466 ----------


 ---------- 2021-06-25 01:00:00 : 근화동   36470 ----------


 ---------- 2021-06-25 11:00:00 : 동내면   36471 ----------


 ---------- 2021-06-25 15:00:00 : 서  면   36472 ----------


 ---------- 2021-06-25 15:00:00 : 남산면   36473 ----------


 ---------- 2021-06-25 16:00:00 : 석사동   36475 ----------


 ---------- 2021-06-25 16:00:00 : 신사우동   36476 ----------


 ---------- 2021-06-25 17:00:00 : 후평1동   36477 ----------


 ---------- 2021-06-25 20:00:00 : 석사동   36478 ----------


 ---------- 2021-06-25 22:00:00 : 후평1동   36479 ----------


 ---------- 2021-06-26 01:00:00 : 효자1동   36482 ----------


 ---------- 2021-06-26 02:00:00 : 퇴계동   36483 ----------


 ---------- 2021-06-26 03:00:00 : 강남동   36484 ----------


 ---------- 2021-06-26 04:00:00 : 효자1동   36485 ----------


 ---------- 2021-06-26 10:00:00 : 서  면   36486 ----------


 ---------- 2021-06-26 10:00:00 : 효자1동   36488 ----------


 ---------- 2021-06-26 10:00:00 : 근화동   36491 ----------


 ---------- 2021-06-26 11:00:00 : 신사우동   36492 ----------


 ---------- 2021-06-26 12:00:00 : 북산면   36496 ----------


 ---------- 2021-06-26 13:00:00 : 퇴계동   36497 ----------


 ---------- 2021-06-26 14:00:00 : 근화동   36499 ----------


 ---------- 2021-06-26 16:00:00 : 퇴계동   36503 ----------


 ---------- 2021-06-26 18:00:00 : 조운동   36504 ----------


 ---------- 2021-06-26 22:00:00 : 퇴계동   36508 ----------


 ---------- 2021-06-26 23:00:00 : 남산면   36511 ----------


 ---------- 2021-06-26 23:00:00 : 신사우동   36513 ----------


 ---------- 2021-06-27 01:00:00 : 강남동   36514 ----------


 ---------- 2021-06-27 06:00:00 : 남산면   36518 ----------


 ---------- 2021-06-27 09:00:00 : 강남동   36520 ----------


 ---------- 2021-06-27 10:00:00 : 효자1동   36524 ----------


 ---------- 2021-06-27 12:00:00 : 석사동   36525 ----------


 ---------- 2021-06-27 13:00:00 : 남산면   36526 ----------


 ---------- 2021-06-27 14:00:00 : 강남동   36529 ----------


 ---------- 2021-06-27 14:00:00 : 신사우동   36530 ----------


 ---------- 2021-06-27 16:00:00 : 강남동   36531 ----------


 ---------- 2021-06-27 16:00:00 : 효자1동   36532 ----------


 ---------- 2021-06-27 16:00:00 : 신북읍   36533 ----------


 ---------- 2021-06-28 01:00:00 : 약사명동   36534 ----------


 ---------- 2021-06-28 07:00:00 : 동내면   36535 ----------


 ---------- 2021-06-28 08:00:00 : 석사동   36539 ----------


 ---------- 2021-06-28 08:00:00 : 강남동   36542 ----------


 ---------- 2021-06-28 08:00:00 : 신사우동   36545 ----------


 ---------- 2021-06-28 09:00:00 : 강남동   36546 ----------


 ---------- 2021-06-28 11:00:00 : 서  면   36547 ----------


 ---------- 2021-06-28 13:00:00 : 퇴계동   36548 ----------


 ---------- 2021-06-28 17:00:00 : 후평1동   36551 ----------


 ---------- 2021-06-28 18:00:00 : 동내면   36552 ----------


 ---------- 2021-06-28 20:00:00 : 강남동   36553 ----------


 ---------- 2021-06-28 22:00:00 : 소양동   36555 ----------


 ---------- 2021-06-28 23:00:00 : 강남동   36556 ----------


 ---------- 2021-06-29 00:00:00 : 신사우동   36559 ----------


 ---------- 2021-06-29 00:00:00 : 동산면   36560 ----------


 ---------- 2021-06-29 02:00:00 : 신사우동   36563 ----------


 ---------- 2021-06-29 08:00:00 : 신사우동   36565 ----------


 ---------- 2021-06-29 09:00:00 : 동내면   36566 ----------


 ---------- 2021-06-29 10:00:00 : 퇴계동   36567 ----------


 ---------- 2021-06-29 11:00:00 : 남  면   36568 ----------


 ---------- 2021-06-29 11:00:00 : 효자1동   36569 ----------


 ---------- 2021-06-29 11:00:00 : 동  면   36570 ----------


 ---------- 2021-06-29 13:00:00 : 신사우동   36572 ----------


 ---------- 2021-06-29 13:00:00 : 퇴계동   36576 ----------


 ---------- 2021-06-29 14:00:00 : 동내면   36578 ----------


 ---------- 2021-06-29 14:00:00 : 소양동   36579 ----------


 ---------- 2021-06-29 17:00:00 : 동내면   36580 ----------


 ---------- 2021-06-29 18:00:00 : 신북읍   36582 ----------


 ---------- 2021-06-29 23:00:00 : 강남동   36585 ----------


 ---------- 2021-06-30 11:00:00 : 서  면   36586 ----------


 ---------- 2021-06-30 11:00:00 : 동  면   36587 ----------


 ---------- 2021-06-30 14:00:00 : 신사우동   36589 ----------


 ---------- 2021-06-30 15:00:00 : 근화동   36591 ----------


 ---------- 2021-06-30 16:00:00 : 동내면   36592 ----------


 ---------- 2021-06-30 17:00:00 : 동내면   36593 ----------


 ---------- 2021-06-30 18:00:00 : 석사동   36596 ----------


 ---------- 2021-06-30 19:00:00 : 퇴계동   36600 ----------


 ---------- 2021-06-30 22:00:00 : 동  면   36601 ----------


 ---------- 2021-07-01 08:00:00 : 퇴계동   36603 ----------


 ---------- 2021-07-01 09:00:00 : 신북읍   36604 ----------


 ---------- 2021-07-01 11:00:00 : 동  면   36605 ----------


 ---------- 2021-07-01 12:00:00 : 신북읍   36606 ----------


 ---------- 2021-07-01 12:00:00 : 퇴계동   36608 ----------


 ---------- 2021-07-01 15:00:00 : 강남동   36609 ----------


 ---------- 2021-07-01 15:00:00 : 신북읍   36610 ----------


 ---------- 2021-07-01 15:00:00 : 동산면   36611 ----------


 ---------- 2021-07-01 16:00:00 : 동내면   36612 ----------


 ---------- 2021-07-01 17:00:00 : 후평1동   36613 ----------


 ---------- 2021-07-01 19:00:00 : 신사우동   36614 ----------


 ---------- 2021-07-02 09:00:00 : 남산면   36615 ----------


 ---------- 2021-07-02 09:00:00 : 동산면   36616 ----------


 ---------- 2021-07-02 10:00:00 : 후평1동   36622 ----------


 ---------- 2021-07-02 10:00:00 : 교  동   36624 ----------


 ---------- 2021-07-02 13:00:00 : 석사동   36625 ----------


 ---------- 2021-07-02 14:00:00 : 퇴계동   36626 ----------


 ---------- 2021-07-02 15:00:00 : 퇴계동   36630 ----------


 ---------- 2021-07-02 17:00:00 : 동산면   36632 ----------


 ---------- 2021-07-02 18:00:00 : 교  동   36634 ----------

 ---------- 2021-07-02 19:00:00 : 동  면   36636 ----------


 ---------- 2021-07-02 20:00:00 : 동내면   36638 ----------


 ---------- 2021-07-02 20:00:00 : 동  면   36640 ----------


 ---------- 2021-07-02 20:00:00 : 후평1동   36642 ----------


 ---------- 2021-07-02 23:00:00 : 동내면   36643 ----------


 ---------- 2021-07-03 00:00:00 : 강남동   36646 ----------


 ---------- 2021-07-03 09:00:00 : 신북읍   36647 ----------


 ---------- 2021-07-03 10:00:00 : 신동면   36648 ----------


 ---------- 2021-07-03 11:00:00 : 사북면   36649 ----------


 ---------- 2021-07-03 12:00:00 : 남산면   36650 ----------


 ---------- 2021-07-03 14:00:00 : 동  면   36651 ----------


 ---------- 2021-07-03 15:00:00 : 석사동   36652 ----------


 ---------- 2021-07-03 16:00:00 : 서  면   36653 ----------


 ---------- 2021-07-04 04:00:00 : 동산면   36654 ----------


 ---------- 2021-07-04 05:00:00 : 약사명동   36657 ----------


 ---------- 2021-07-04 08:00:00 : 신사우동   36658 ----------


 ---------- 2021-07-04 12:00:00 : 강남동   36659 ----------


 ---------- 2021-07-04 13:00:00 : 동내면   36660 ----------


 ---------- 2021-07-04 13:00:00 : 동  면   36661 ----------


 ---------- 2021-07-04 14:00:00 : 신북읍   36662 ----------


 ---------- 2021-07-04 15:00:00 : 퇴계동   36663 ----------


 ---------- 2021-07-04 19:00:00 : 효자1동   36664 ----------


 ---------- 2021-07-04 19:00:00 : 동  면   36666 ----------


 ---------- 2021-07-04 21:00:00 : 근화동   36667 ----------


 ---------- 2021-07-04 22:00:00 : 후평1동   36668 ----------


 ---------- 2021-07-04 22:00:00 : 퇴계동   36670 ----------


 ---------- 2021-07-04 22:00:00 : 교  동   36673 ----------


 ---------- 2021-07-04 23:00:00 : 남산면   36674 ----------


 ---------- 2021-07-05 03:00:00 : 후평1동   36676 ----------


 ---------- 2021-07-05 04:00:00 : 동내면   36680 ----------


 ---------- 2021-07-05 06:00:00 : 신북읍   36682 ----------


 ---------- 2021-07-05 08:00:00 : 강남동   36686 ----------


 ---------- 2021-07-05 08:00:00 : 동내면   36687 ----------


 ---------- 2021-07-05 09:00:00 : 석사동   36688 ----------


 ---------- 2021-07-05 09:00:00 : 동내면   36690 ----------


 ---------- 2021-07-05 10:00:00 : 퇴계동   36692 ----------


 ---------- 2021-07-05 12:00:00 : 신동면   36696 ----------


 ---------- 2021-07-05 12:00:00 : 퇴계동   36697 ----------


 ---------- 2021-07-05 17:00:00 : 석사동   36698 ----------


 ---------- 2021-07-05 17:00:00 : 강남동   36703 ----------


 ---------- 2021-07-05 17:00:00 : 퇴계동   36704 ----------


 ---------- 2021-07-06 09:00:00 : 서  면   36705 ----------


 ---------- 2021-07-06 09:00:00 : 신북읍   36706 ----------


 ---------- 2021-07-06 09:00:00 : 동  면   36707 ----------


 ---------- 2021-07-06 10:00:00 : 석사동   36708 ----------


 ---------- 2021-07-06 10:00:00 : 사북면   36709 ----------


 ---------- 2021-07-06 11:00:00 : 소양동   36711 ----------


 ---------- 2021-07-06 12:00:00 : 석사동   36712 ----------


 ---------- 2021-07-06 16:00:00 : 남  면   36717 ----------


 ---------- 2021-07-06 20:00:00 : 강남동   36719 ----------


 ---------- 2021-07-06 21:00:00 : 석사동   36722 ----------


 ---------- 2021-07-06 21:00:00 : 신사우동   36724 ----------


 ---------- 2021-07-07 03:00:00 : 남산면   36726 ----------


 ---------- 2021-07-07 06:00:00 : 후평1동   36728 ----------


 ---------- 2021-07-07 11:00:00 : 효자1동   36729 ----------


 ---------- 2021-07-07 12:00:00 : 석사동   36730 ----------


 ---------- 2021-07-07 13:00:00 : 동내면   36731 ----------


 ---------- 2021-07-07 13:00:00 : 남산면   36732 ----------


 ---------- 2021-07-07 14:00:00 : 효자1동   36733 ----------


 ---------- 2021-07-07 15:00:00 : 동  면   36734 ----------


 ---------- 2021-07-07 17:00:00 : 근화동   36736 ----------


 ---------- 2021-07-07 17:00:00 : 퇴계동   36737 ----------


 ---------- 2021-07-07 18:00:00 : 동내면   36738 ----------


 ---------- 2021-07-07 18:00:00 : 동  면   36740 ----------


 ---------- 2021-07-07 20:00:00 : 신북읍   36742 ----------


 ---------- 2021-07-08 08:00:00 : 강남동   36746 ----------


 ---------- 2021-07-08 08:00:00 : 후평1동   36748 ----------


 ---------- 2021-07-08 09:00:00 : 신동면   36750 ----------


 ---------- 2021-07-08 11:00:00 : 동내면   36752 ----------


 ---------- 2021-07-08 11:00:00 : 동산면   36757 ----------


 ---------- 2021-07-08 15:00:00 : 신동면   36758 ----------


 ---------- 2021-07-08 15:00:00 : 동  면   36760 ----------


 ---------- 2021-07-08 16:00:00 : 신동면   36761 ----------


 ---------- 2021-07-08 16:00:00 : 퇴계동   36762 ----------


 ---------- 2021-07-08 19:00:00 : 약사명동   36765 ----------


 ---------- 2021-07-08 20:00:00 : 소양동   36766 ----------


 ---------- 2021-07-08 20:00:00 : 조운동   36768 ----------


 ---------- 2021-07-09 03:00:00 : 신북읍   36770 ----------


 ---------- 2021-07-09 06:00:00 : 동내면   36771 ----------


 ---------- 2021-07-09 06:00:00 : 후평1동   36772 ----------


 ---------- 2021-07-09 07:00:00 : 근화동   36775 ----------


 ---------- 2021-07-09 11:00:00 : 남산면   36776 ----------


 ---------- 2021-07-09 12:00:00 : 서  면   36777 ----------


 ---------- 2021-07-09 12:00:00 : 동  면   36779 ----------


 ---------- 2021-07-09 13:00:00 : 강남동   36780 ----------


 ---------- 2021-07-09 13:00:00 : 신사우동   36781 ----------


 ---------- 2021-07-09 15:00:00 : 강남동   36782 ----------


 ---------- 2021-07-09 16:00:00 : 동산면   36783 ----------


 ---------- 2021-07-09 17:00:00 : 효자1동   36784 ----------


 ---------- 2021-07-09 18:00:00 : 효자1동   36785 ----------


 ---------- 2021-07-09 19:00:00 : 동내면   36786 ----------


 ---------- 2021-07-09 21:00:00 : 동  면   36787 ----------


 ---------- 2021-07-10 02:00:00 : 동내면   36788 ----------


 ---------- 2021-07-10 10:00:00 : 동  면   36792 ----------


 ---------- 2021-07-10 10:00:00 : 퇴계동   36794 ----------


 ---------- 2021-07-10 11:00:00 : 강남동   36795 ----------


 ---------- 2021-07-10 11:00:00 : 동내면   36796 ----------


 ---------- 2021-07-10 11:00:00 : 남산면   36798 ----------


 ---------- 2021-07-10 11:00:00 : 퇴계동   36799 ----------


 ---------- 2021-07-10 13:00:00 : 서  면   36801 ----------


 ---------- 2021-07-10 13:00:00 : 효자1동   36802 ----------


 ---------- 2021-07-10 13:00:00 : 동산면   36803 ----------


 ---------- 2021-07-10 15:00:00 : 동  면   36804 ----------


 ---------- 2021-07-10 15:00:00 : 퇴계동   36805 ----------


 ---------- 2021-07-10 16:00:00 : 퇴계동   36806 ----------


 ---------- 2021-07-10 17:00:00 : 효자1동   36807 ----------


 ---------- 2021-07-10 18:00:00 : 소양동   36808 ----------


 ---------- 2021-07-10 18:00:00 : 퇴계동   36811 ----------


 ---------- 2021-07-10 20:00:00 : 동내면   36812 ----------


 ---------- 2021-07-10 21:00:00 : 동내면   36813 ----------


 ---------- 2021-07-10 23:00:00 : 동  면   36814 ----------


 ---------- 2021-07-11 01:00:00 : 사북면   36815 ----------


 ---------- 2021-07-11 07:00:00 : 남산면   36816 ----------


 ---------- 2021-07-11 09:00:00 : 석사동   36817 ----------


 ---------- 2021-07-11 09:00:00 : 강남동   36818 ----------


 ---------- 2021-07-11 10:00:00 : 서  면   36820 ----------


 ---------- 2021-07-11 11:00:00 : 동내면   36821 ----------


 ---------- 2021-07-11 11:00:00 : 남산면   36825 ----------


 ---------- 2021-07-11 13:00:00 : 동  면   36826 ----------


 ---------- 2021-07-11 14:00:00 : 후평1동   36829 ----------


 ---------- 2021-07-11 15:00:00 : 퇴계동   36833 ----------


 ---------- 2021-07-11 17:00:00 : 신사우동   36834 ----------


 ---------- 2021-07-11 19:00:00 : 후평1동   36837 ----------


 ---------- 2021-07-11 21:00:00 : 동내면   36840 ----------


 ---------- 2021-07-11 22:00:00 : 신사우동   36842 ----------


 ---------- 2021-07-12 07:00:00 : 후평1동   36843 ----------


 ---------- 2021-07-12 08:00:00 : 신동면   36844 ----------


 ---------- 2021-07-12 08:00:00 : 남산면   36845 ----------


 ---------- 2021-07-12 09:00:00 : 서  면   36846 ----------


 ---------- 2021-07-12 09:00:00 : 후평1동   36847 ----------


 ---------- 2021-07-12 10:00:00 : 신북읍   36848 ----------


 ---------- 2021-07-12 11:00:00 : 신사우동   36850 ----------


 ---------- 2021-07-12 12:00:00 : 동  면   36851 ----------


 ---------- 2021-07-12 13:00:00 : 석사동   36852 ----------


 ---------- 2021-07-12 14:00:00 : 석사동   36853 ----------


 ---------- 2021-07-12 16:00:00 : 후평1동   36854 ----------

 ---------- 2021-07-12 18:00:00 : 신동면   36856 ----------


 ---------- 2021-07-12 18:00:00 : 사북면   36857 ----------


 ---------- 2021-07-12 19:00:00 : 석사동   36859 ----------


 ---------- 2021-07-12 19:00:00 : 신북읍   36860 ----------


 ---------- 2021-07-12 21:00:00 : 신사우동   36861 ----------


 ---------- 2021-07-13 00:00:00 : 소양동   36863 ----------


 ---------- 2021-07-13 01:00:00 : 후평1동   36864 ----------


 ---------- 2021-07-13 02:00:00 : 후평1동   36865 ----------


 ---------- 2021-07-13 05:00:00 : 신사우동   36868 ----------


 ---------- 2021-07-13 08:00:00 : 강남동   36869 ----------


 ---------- 2021-07-13 09:00:00 : 남산면   36870 ----------


 ---------- 2021-07-13 09:00:00 : 동산면   36871 ----------


 ---------- 2021-07-13 10:00:00 : 신동면   36872 ----------


 ---------- 2021-07-13 10:00:00 : 동  면   36873 ----------


 ---------- 2021-07-13 12:00:00 : 서  면   36874 ----------


 ---------- 2021-07-13 12:00:00 : 동내면   36878 ----------


 ---------- 2021-07-13 12:00:00 : 신북읍   36879 ----------


 ---------- 2021-07-13 13:00:00 : 강남동   36880 ----------


 ---------- 2021-07-13 14:00:00 : 서  면   36881 ----------


 ---------- 2021-07-13 14:00:00 : 남산면   36882 ----------


 ---------- 2021-07-13 14:00:00 : 동  면   36883 ----------


 ---------- 2021-07-13 16:00:00 : 교  동   36886 ----------


 ---------- 2021-07-13 17:00:00 : 동내면   36887 ----------


 ---------- 2021-07-13 18:00:00 : 동  면   36888 ----------


 ---------- 2021-07-13 19:00:00 : 석사동   36891 ----------


 ---------- 2021-07-13 23:00:00 : 남산면   36892 ----------


 ---------- 2021-07-14 01:00:00 : 퇴계동   36896 ----------


 ---------- 2021-07-14 04:00:00 : 사북면   36898 ----------


 ---------- 2021-07-14 09:00:00 : 신동면   36899 ----------


 ---------- 2021-07-14 09:00:00 : 약사명동   36900 ----------


 ---------- 2021-07-14 10:00:00 : 신동면   36901 ----------


 ---------- 2021-07-14 10:00:00 : 동산면   36904 ----------


 ---------- 2021-07-14 10:00:00 : 교  동   36906 ----------


 ---------- 2021-07-14 11:00:00 : 신동면   36907 ----------


 ---------- 2021-07-14 11:00:00 : 강남동   36910 ----------


 ---------- 2021-07-14 11:00:00 : 동내면   36911 ----------


 ---------- 2021-07-14 13:00:00 : 동내면   36912 ----------


 ---------- 2021-07-14 14:00:00 : 강남동   36916 ----------


 ---------- 2021-07-14 14:00:00 : 남산면   36918 ----------


 ---------- 2021-07-14 16:00:00 : 사북면   36919 ----------


 ---------- 2021-07-14 16:00:00 : 동내면   36920 ----------


 ---------- 2021-07-14 16:00:00 : 퇴계동   36921 ----------


 ---------- 2021-07-14 17:00:00 : 효자1동   36922 ----------


 ---------- 2021-07-14 18:00:00 : 동내면   36923 ----------


 ---------- 2021-07-14 18:00:00 : 퇴계동   36924 ----------


 ---------- 2021-07-14 19:00:00 : 효자1동   36926 ----------


 ---------- 2021-07-14 19:00:00 : 신북읍   36928 ----------


 ---------- 2021-07-14 19:00:00 : 조운동   36929 ----------


 ---------- 2021-07-14 21:00:00 : 근화동   36930 ----------


 ---------- 2021-07-14 21:00:00 : 북산면   36932 ----------


 ---------- 2021-07-14 23:00:00 : 동내면   36933 ----------


 ---------- 2021-07-15 01:00:00 : 강남동   36936 ----------


 ---------- 2021-07-15 01:00:00 : 약사명동   36939 ----------


 ---------- 2021-07-15 06:00:00 : 후평1동   36942 ----------


 ---------- 2021-07-15 08:00:00 : 강남동   36943 ----------


 ---------- 2021-07-15 08:00:00 : 동  면   36944 ----------


 ---------- 2021-07-15 09:00:00 : 동내면   36946 ----------


 ---------- 2021-07-15 09:00:00 : 후평1동   36947 ----------


 ---------- 2021-07-15 10:00:00 : 석사동   36949 ----------


 ---------- 2021-07-15 10:00:00 : 조운동   36950 ----------


 ---------- 2021-07-15 10:00:00 : 동산면   36952 ----------


 ---------- 2021-07-15 12:00:00 : 신동면   36953 ----------


 ---------- 2021-07-15 12:00:00 : 남산면   36954 ----------


 ---------- 2021-07-15 13:00:00 : 동  면   36955 ----------


 ---------- 2021-07-15 14:00:00 : 석사동   36956 ----------


 ---------- 2021-07-15 14:00:00 : 강남동   36957 ----------


 ---------- 2021-07-15 14:00:00 : 서  면   36958 ----------


 ---------- 2021-07-15 14:00:00 : 남  면   36959 ----------


 ---------- 2021-07-15 14:00:00 : 사북면   36960 ----------


 ---------- 2021-07-15 15:00:00 : 동  면   36961 ----------


 ---------- 2021-07-15 15:00:00 : 후평1동   36962 ----------


 ---------- 2021-07-15 17:00:00 : 남산면   36963 ----------


 ---------- 2021-07-15 17:00:00 : 신북읍   36964 ----------


 ---------- 2021-07-15 18:00:00 : 석사동   36966 ----------


 ---------- 2021-07-15 19:00:00 : 소양동   36967 ----------


 ---------- 2021-07-16 01:00:00 : 동산면   36969 ----------


 ---------- 2021-07-16 01:00:00 : 교  동   36970 ----------


 ---------- 2021-07-16 03:00:00 : 서  면   36973 ----------


 ---------- 2021-07-16 07:00:00 : 동내면   36974 ----------


 ---------- 2021-07-16 07:00:00 : 신북읍   36975 ----------


 ---------- 2021-07-16 09:00:00 : 신북읍   36976 ----------


 ---------- 2021-07-16 10:00:00 : 동내면   36979 ----------


 ---------- 2021-07-16 12:00:00 : 동  면   36980 ----------


 ---------- 2021-07-16 12:00:00 : 퇴계동   36983 ----------


 ---------- 2021-07-17 01:00:00 : 신북읍   36985 ----------


 ---------- 2021-07-17 02:00:00 : 후평1동   36988 ----------


 ---------- 2021-07-17 04:00:00 : 근화동   36991 ----------


 ---------- 2021-07-17 10:00:00 : 남산면   36992 ----------


 ---------- 2021-07-17 12:00:00 : 퇴계동   36993 ----------


 ---------- 2021-07-17 13:00:00 : 효자1동   36994 ----------


 ---------- 2021-07-17 13:00:00 : 후평1동   36995 ----------


 ---------- 2021-07-17 14:00:00 : 효자1동   36996 ----------


 ---------- 2021-07-17 14:00:00 : 후평1동   36997 ----------


 ---------- 2021-07-17 17:00:00 : 효자1동   36998 ----------


 ---------- 2021-07-17 18:00:00 : 퇴계동   36999 ----------


 ---------- 2021-07-17 22:00:00 : 남  면   37002 ----------


 ---------- 2021-07-17 23:00:00 : 소양동   37003 ----------


 ---------- 2021-07-18 01:00:00 : 석사동   37004 ----------


 ---------- 2021-07-18 02:00:00 : 후평1동   37007 ----------


 ---------- 2021-07-18 04:00:00 : 강남동   37009 ----------


 ---------- 2021-07-18 07:00:00 : 효자1동   37010 ----------


 ---------- 2021-07-18 09:00:00 : 신사우동   37011 ----------


 ---------- 2021-07-18 09:00:00 : 후평1동   37012 ----------


 ---------- 2021-07-18 10:00:00 : 후평1동   37013 ----------


 ---------- 2021-07-18 12:00:00 : 서  면   37014 ----------


 ---------- 2021-07-18 12:00:00 : 퇴계동   37015 ----------


 ---------- 2021-07-18 13:00:00 : 남  면   37016 ----------


 ---------- 2021-07-18 13:00:00 : 남산면   37017 ----------


 ---------- 2021-07-18 13:00:00 : 신북읍   37018 ----------


 ---------- 2021-07-18 15:00:00 : 석사동   37019 ----------


 ---------- 2021-07-18 15:00:00 : 강남동   37020 ----------


 ---------- 2021-07-18 15:00:00 : 동  면   37021 ----------


 ---------- 2021-07-18 16:00:00 : 남산면   37022 ----------


 ---------- 2021-07-18 17:00:00 : 서  면   37024 ----------


 ---------- 2021-07-18 18:00:00 : 서  면   37025 ----------


 ---------- 2021-07-18 18:00:00 : 남산면   37027 ----------


 ---------- 2021-07-18 19:00:00 : 석사동   37028 ----------


 ---------- 2021-07-18 20:00:00 : 동내면   37030 ----------


 ---------- 2021-07-18 20:00:00 : 신사우동   37032 ----------


 ---------- 2021-07-18 21:00:00 : 석사동   37034 ----------


 ---------- 2021-07-18 22:00:00 : 동내면   37035 ----------


 ---------- 2021-07-19 07:00:00 : 퇴계동   37037 ----------


 ---------- 2021-07-19 08:00:00 : 동내면   37038 ----------


 ---------- 2021-07-19 09:00:00 : 동내면   37039 ----------


 ---------- 2021-07-19 09:00:00 : 후평1동   37040 ----------


 ---------- 2021-07-19 10:00:00 : 동내면   37043 ----------


 ---------- 2021-07-19 10:00:00 : 후평1동   37044 ----------


 ---------- 2021-07-19 10:00:00 : 퇴계동   37045 ----------


 ---------- 2021-07-19 11:00:00 : 석사동   37046 ----------


 ---------- 2021-07-19 12:00:00 : 서  면   37047 ----------


 ---------- 2021-07-19 12:00:00 : 남산면   37049 ----------


 ---------- 2021-07-19 12:00:00 : 동  면   37051 ----------


 ---------- 2021-07-19 13:00:00 : 남산면   37052 ----------


 ---------- 2021-07-19 14:00:00 : 사북면   37053 ----------


 ---------- 2021-07-19 15:00:00 : 소양동   37054 ----------


 ---------- 2021-07-19 16:00:00 : 강남동   37055 ----------

 ---------- 2021-07-19 17:00:00 : 신북읍   37056 ----------


 ---------- 2021-07-19 17:00:00 : 퇴계동   37058 ----------


 ---------- 2021-07-19 19:00:00 : 퇴계동   37059 ----------


 ---------- 2021-07-19 20:00:00 : 남산면   37061 ----------


 ---------- 2021-07-20 00:00:00 : 효자1동   37062 ----------


 ---------- 2021-07-20 00:00:00 : 근화동   37064 ----------


 ---------- 2021-07-20 09:00:00 : 신동면   37065 ----------


 ---------- 2021-07-20 09:00:00 : 근화동   37068 ----------


 ---------- 2021-07-20 10:00:00 : 석사동   37069 ----------


 ---------- 2021-07-20 10:00:00 : 교  동   37073 ----------


 ---------- 2021-07-20 11:00:00 : 동  면   37074 ----------


 ---------- 2021-07-20 12:00:00 : 동  면   37075 ----------


 ---------- 2021-07-20 13:00:00 : 신북읍   37076 ----------


 ---------- 2021-07-20 13:00:00 : 퇴계동   37079 ----------


 ---------- 2021-07-20 14:00:00 : 신동면   37080 ----------


 ---------- 2021-07-20 14:00:00 : 소양동   37081 ----------


 ---------- 2021-07-20 15:00:00 : 퇴계동   37085 ----------


 ---------- 2021-07-20 16:00:00 : 남산면   37086 ----------


 ---------- 2021-07-20 16:00:00 : 신사우동   37088 ----------


 ---------- 2021-07-20 16:00:00 : 동  면   37089 ----------


 ---------- 2021-07-20 16:00:00 : 퇴계동   37090 ----------


 ---------- 2021-07-20 17:00:00 : 신북읍   37094 ----------


 ---------- 2021-07-20 18:00:00 : 석사동   37095 ----------


 ---------- 2021-07-20 18:00:00 : 신동면   37096 ----------


 ---------- 2021-07-20 18:00:00 : 소양동   37097 ----------


 ---------- 2021-07-20 19:00:00 : 신동면   37098 ----------


 ---------- 2021-07-20 19:00:00 : 동내면   37099 ----------


 ---------- 2021-07-20 20:00:00 : 강남동   37102 ----------


 ---------- 2021-07-20 21:00:00 : 동내면   37103 ----------


 ---------- 2021-07-20 22:00:00 : 강남동   37106 ----------


 ---------- 2021-07-20 22:00:00 : 동내면   37109 ----------


 ---------- 2021-07-20 22:00:00 : 근화동   37110 ----------


 ---------- 2021-07-21 00:00:00 : 동내면   37111 ----------


 ---------- 2021-07-21 04:00:00 : 퇴계동   37115 ----------


 ---------- 2021-07-21 06:00:00 : 강남동   37116 ----------


 ---------- 2021-07-21 06:00:00 : 동내면   37117 ----------


 ---------- 2021-07-21 08:00:00 : 강남동   37122 ----------


 ---------- 2021-07-21 08:00:00 : 서  면   37123 ----------


 ---------- 2021-07-21 09:00:00 : 서  면   37124 ----------


 ---------- 2021-07-21 11:00:00 : 석사동   37125 ----------


 ---------- 2021-07-21 13:00:00 : 동  면   37126 ----------


 ---------- 2021-07-21 14:00:00 : 강남동   37128 ----------


 ---------- 2021-07-21 14:00:00 : 신사우동   37129 ----------


 ---------- 2021-07-21 14:00:00 : 후평1동   37130 ----------


 ---------- 2021-07-21 16:00:00 : 강남동   37131 ----------


 ---------- 2021-07-21 18:00:00 : 퇴계동   37132 ----------


 ---------- 2021-07-21 19:00:00 : 효자1동   37133 ----------


 ---------- 2021-07-21 20:00:00 : 서  면   37135 ----------


 ---------- 2021-07-22 08:00:00 : 석사동   37136 ----------


 ---------- 2021-07-22 08:00:00 : 강남동   37137 ----------


 ---------- 2021-07-22 09:00:00 : 강남동   37138 ----------


 ---------- 2021-07-22 09:00:00 : 남산면   37140 ----------


 ---------- 2021-07-22 09:00:00 : 동  면   37141 ----------


 ---------- 2021-07-22 10:00:00 : 강남동   37142 ----------


 ---------- 2021-07-22 11:00:00 : 사북면   37143 ----------


 ---------- 2021-07-22 11:00:00 : 동내면   37144 ----------


 ---------- 2021-07-22 13:00:00 : 후평1동   37145 ----------


 ---------- 2021-07-22 14:00:00 : 동내면   37146 ----------


 ---------- 2021-07-22 14:00:00 : 퇴계동   37149 ----------


 ---------- 2021-07-22 17:00:00 : 석사동   37150 ----------


 ---------- 2021-07-22 18:00:00 : 신동면   37151 ----------


 ---------- 2021-07-22 18:00:00 : 강남동   37154 ----------


 ---------- 2021-07-22 18:00:00 : 남산면   37155 ----------


 ---------- 2021-07-22 18:00:00 : 후평1동   37156 ----------


 ---------- 2021-07-22 19:00:00 : 동내면   37158 ----------


 ---------- 2021-07-22 20:00:00 : 신동면   37159 ----------


 ---------- 2021-07-22 20:00:00 : 근화동   37160 ----------


 ---------- 2021-07-23 04:00:00 : 동산면   37163 ----------


 ---------- 2021-07-23 07:00:00 : 동내면   37164 ----------


 ---------- 2021-07-23 08:00:00 : 신동면   37165 ----------


 ---------- 2021-07-23 08:00:00 : 사북면   37166 ----------


 ---------- 2021-07-23 08:00:00 : 동산면   37168 ----------


 ---------- 2021-07-23 09:00:00 : 사북면   37169 ----------


 ---------- 2021-07-23 09:00:00 : 남산면   37170 ----------


 ---------- 2021-07-23 10:00:00 : 강남동   37173 ----------


 ---------- 2021-07-23 10:00:00 : 동  면   37174 ----------


 ---------- 2021-07-23 11:00:00 : 동  면   37176 ----------


 ---------- 2021-07-23 12:00:00 : 동내면   37177 ----------


 ---------- 2021-07-23 13:00:00 : 동내면   37180 ----------


 ---------- 2021-07-23 13:00:00 : 퇴계동   37181 ----------


 ---------- 2021-07-23 13:00:00 : 교  동   37183 ----------


 ---------- 2021-07-23 14:00:00 : 효자1동   37184 ----------


 ---------- 2021-07-23 16:00:00 : 석사동   37187 ----------


 ---------- 2021-07-23 16:00:00 : 동내면   37188 ----------


 ---------- 2021-07-23 17:00:00 : 남산면   37189 ----------


 ---------- 2021-07-23 17:00:00 : 동  면   37190 ----------


 ---------- 2021-07-23 17:00:00 : 후평1동   37191 ----------


 ---------- 2021-07-23 18:00:00 : 동내면   37192 ----------


 ---------- 2021-07-23 19:00:00 : 강남동   37195 ----------


 ---------- 2021-07-23 19:00:00 : 효자1동   37197 ----------


 ---------- 2021-07-24 00:00:00 : 서  면   37200 ----------


 ---------- 2021-07-24 03:00:00 : 석사동   37201 ----------


 ---------- 2021-07-24 06:00:00 : 후평1동   37202 ----------


 ---------- 2021-07-24 07:00:00 : 소양동   37205 ----------


 ---------- 2021-07-24 09:00:00 : 사북면   37206 ----------


 ---------- 2021-07-24 09:00:00 : 동내면   37207 ----------


 ---------- 2021-07-24 10:00:00 : 효자1동   37209 ----------


 ---------- 2021-07-24 11:00:00 : 강남동   37210 ----------


 ---------- 2021-07-24 12:00:00 : 서  면   37212 ----------


 ---------- 2021-07-24 13:00:00 : 서  면   37213 ----------


 ---------- 2021-07-24 14:00:00 : 사북면   37215 ----------


 ---------- 2021-07-24 14:00:00 : 동내면   37216 ----------


 ---------- 2021-07-24 15:00:00 : 석사동   37217 ----------


 ---------- 2021-07-24 15:00:00 : 사북면   37218 ----------


 ---------- 2021-07-24 17:00:00 : 효자1동   37219 ----------


 ---------- 2021-07-24 17:00:00 : 소양동   37220 ----------


 ---------- 2021-07-24 18:00:00 : 효자1동   37222 ----------


 ---------- 2021-07-24 21:00:00 : 강남동   37223 ----------


 ---------- 2021-07-24 23:00:00 : 강남동   37224 ----------


 ---------- 2021-07-25 03:00:00 : 동내면   37226 ----------


 ---------- 2021-07-25 06:00:00 : 강남동   37227 ----------


 ---------- 2021-07-25 07:00:00 : 동  면   37228 ----------


 ---------- 2021-07-25 08:00:00 : 남산면   37229 ----------


 ---------- 2021-07-25 09:00:00 : 퇴계동   37230 ----------


 ---------- 2021-07-25 10:00:00 : 동내면   37231 ----------


 ---------- 2021-07-25 10:00:00 : 남산면   37232 ----------


 ---------- 2021-07-25 10:00:00 : 교  동   37233 ----------


 ---------- 2021-07-25 11:00:00 : 남산면   37237 ----------


 ---------- 2021-07-25 12:00:00 : 석사동   37238 ----------


 ---------- 2021-07-25 15:00:00 : 석사동   37239 ----------


 ---------- 2021-07-25 15:00:00 : 교  동   37240 ----------


 ---------- 2021-07-25 16:00:00 : 사북면   37241 ----------


 ---------- 2021-07-25 17:00:00 : 신북읍   37242 ----------


 ---------- 2021-07-25 17:00:00 : 동  면   37243 ----------


 ---------- 2021-07-25 18:00:00 : 신동면   37244 ----------


 ---------- 2021-07-25 19:00:00 : 사북면   37246 ----------


 ---------- 2021-07-25 19:00:00 : 동내면   37247 ----------


 ---------- 2021-07-25 22:00:00 : 동내면   37249 ----------


 ---------- 2021-07-25 23:00:00 : 강남동   37250 ----------


 ---------- 2021-07-26 02:00:00 : 퇴계동   37251 ----------


 ---------- 2021-07-26 06:00:00 : 신사우동   37254 ----------


 ---------- 2021-07-26 07:00:00 : 후평1동   37257 ----------


 ---------- 2021-07-26 08:00:00 : 근화동   37259 ----------


 ---------- 2021-07-26 09:00:00 : 신북읍   37260 ----------


 ---------- 2021-07-26 09:00:00 : 소양동   37261 ----------


 ---------- 2021-07-26 09:00:00 : 동  면   37262 ----------


 ---------- 2021-07-26 09:00:00 : 후평1동   37264 ----------

 ---------- 2021-07-26 10:00:00 : 동내면   37265 ----------


 ---------- 2021-07-26 10:00:00 : 퇴계동   37266 ----------


 ---------- 2021-07-26 10:00:00 : 교  동   37267 ----------


 ---------- 2021-07-26 11:00:00 : 강남동   37268 ----------


 ---------- 2021-07-26 12:00:00 : 강남동   37269 ----------


 ---------- 2021-07-26 12:00:00 : 동  면   37270 ----------


 ---------- 2021-07-26 13:00:00 : 후평1동   37273 ----------


 ---------- 2021-07-26 15:00:00 : 동  면   37274 ----------


 ---------- 2021-07-26 16:00:00 : 근화동   37275 ----------


 ---------- 2021-07-26 17:00:00 : 동내면   37276 ----------


 ---------- 2021-07-26 18:00:00 : 후평1동   37277 ----------


 ---------- 2021-07-26 18:00:00 : 퇴계동   37280 ----------


 ---------- 2021-07-26 22:00:00 : 근화동   37282 ----------


 ---------- 2021-07-26 23:00:00 : 후평1동   37283 ----------


 ---------- 2021-07-27 00:00:00 : 석사동   37285 ----------


 ---------- 2021-07-27 03:00:00 : 소양동   37288 ----------


 ---------- 2021-07-27 07:00:00 : 석사동   37289 ----------


 ---------- 2021-07-27 09:00:00 : 후평1동   37290 ----------


 ---------- 2021-07-27 12:00:00 : 강남동   37291 ----------


 ---------- 2021-07-27 13:00:00 : 석사동   37292 ----------


 ---------- 2021-07-27 13:00:00 : 효자1동   37297 ----------


 ---------- 2021-07-27 13:00:00 : 퇴계동   37299 ----------


 ---------- 2021-07-27 14:00:00 : 서  면   37300 ----------


 ---------- 2021-07-27 14:00:00 : 사북면   37301 ----------


 ---------- 2021-07-27 14:00:00 : 신사우동   37302 ----------


 ---------- 2021-07-27 14:00:00 : 동  면   37303 ----------


 ---------- 2021-07-27 15:00:00 : 동내면   37304 ----------


 ---------- 2021-07-27 16:00:00 : 효자1동   37305 ----------


 ---------- 2021-07-27 16:00:00 : 신사우동   37306 ----------


 ---------- 2021-07-27 17:00:00 : 석사동   37307 ----------


 ---------- 2021-07-27 19:00:00 : 퇴계동   37309 ----------


 ---------- 2021-07-27 22:00:00 : 신동면   37312 ----------


 ---------- 2021-07-28 03:00:00 : 강남동   37313 ----------


 ---------- 2021-07-28 09:00:00 : 동  면   37314 ----------


 ---------- 2021-07-28 09:00:00 : 동산면   37317 ----------


 ---------- 2021-07-28 10:00:00 : 효자1동   37318 ----------


 ---------- 2021-07-28 10:00:00 : 퇴계동   37319 ----------


 ---------- 2021-07-28 11:00:00 : 동내면   37322 ----------


 ---------- 2021-07-28 13:00:00 : 강남동   37323 ----------


 ---------- 2021-07-28 13:00:00 : 동산면   37324 ----------


 ---------- 2021-07-28 14:00:00 : 남산면   37325 ----------


 ---------- 2021-07-28 16:00:00 : 동  면   37326 ----------


 ---------- 2021-07-28 16:00:00 : 후평1동   37327 ----------


 ---------- 2021-07-28 17:00:00 : 후평1동   37328 ----------


 ---------- 2021-07-28 18:00:00 : 사북면   37329 ----------


 ---------- 2021-07-28 18:00:00 : 근화동   37330 ----------


 ---------- 2021-07-28 22:00:00 : 소양동   37331 ----------


 ---------- 2021-07-29 02:00:00 : 석사동   37333 ----------


 ---------- 2021-07-29 04:00:00 : 효자1동   37334 ----------


 ---------- 2021-07-29 04:00:00 : 퇴계동   37335 ----------


 ---------- 2021-07-29 07:00:00 : 서  면   37336 ----------


 ---------- 2021-07-29 07:00:00 : 동산면   37339 ----------


 ---------- 2021-07-29 08:00:00 : 퇴계동   37341 ----------


 ---------- 2021-07-29 08:00:00 : 교  동   37342 ----------


 ---------- 2021-07-29 09:00:00 : 석사동   37343 ----------


 ---------- 2021-07-29 09:00:00 : 동내면   37344 ----------


 ---------- 2021-07-29 09:00:00 : 동  면   37345 ----------


 ---------- 2021-07-29 10:00:00 : 후평1동   37346 ----------


 ---------- 2021-07-29 10:00:00 : 퇴계동   37348 ----------


 ---------- 2021-07-29 10:00:00 : 동산면   37349 ----------


 ---------- 2021-07-29 11:00:00 : 조운동   37350 ----------


 ---------- 2021-07-29 12:00:00 : 강남동   37351 ----------


 ---------- 2021-07-29 12:00:00 : 동  면   37352 ----------


 ---------- 2021-07-29 15:00:00 : 강남동   37353 ----------


 ---------- 2021-07-29 15:00:00 : 사북면   37354 ----------


 ---------- 2021-07-29 15:00:00 : 동내면   37356 ----------


 ---------- 2021-07-29 15:00:00 : 남산면   37357 ----------


 ---------- 2021-07-29 16:00:00 : 조운동   37358 ----------


 ---------- 2021-07-29 18:00:00 : 서  면   37361 ----------


 ---------- 2021-07-29 18:00:00 : 남산면   37362 ----------


 ---------- 2021-07-29 18:00:00 : 동산면   37363 ----------


 ---------- 2021-07-30 07:00:00 : 후평1동   37367 ----------


 ---------- 2021-07-30 08:00:00 : 남  면   37368 ----------


 ---------- 2021-07-30 09:00:00 : 근화동   37371 ----------


 ---------- 2021-07-30 10:00:00 : 남산면   37372 ----------


 ---------- 2021-07-30 13:00:00 : 강남동   37373 ----------


 ---------- 2021-07-30 13:00:00 : 남산면   37377 ----------


 ---------- 2021-07-30 13:00:00 : 동산면   37378 ----------


 ---------- 2021-07-30 14:00:00 : 남산면   37379 ----------


 ---------- 2021-07-30 14:00:00 : 퇴계동   37381 ----------


 ---------- 2021-07-30 15:00:00 : 강남동   37382 ----------


 ---------- 2021-07-30 16:00:00 : 석사동   37383 ----------


 ---------- 2021-07-30 16:00:00 : 신동면   37384 ----------


 ---------- 2021-07-30 17:00:00 : 퇴계동   37385 ----------


 ---------- 2021-07-31 03:00:00 : 소양동   37386 ----------


 ---------- 2021-07-31 04:00:00 : 신북읍   37387 ----------


 ---------- 2021-07-31 08:00:00 : 석사동   37388 ----------


 ---------- 2021-07-31 08:00:00 : 강남동   37389 ----------


 ---------- 2021-07-31 10:00:00 : 강남동   37390 ----------


 ---------- 2021-07-31 10:00:00 : 남  면   37391 ----------


 ---------- 2021-07-31 10:00:00 : 동산면   37392 ----------


 ---------- 2021-07-31 11:00:00 : 남산면   37393 ----------


 ---------- 2021-07-31 12:00:00 : 강남동   37394 ----------


 ---------- 2021-07-31 14:00:00 : 동  면   37395 ----------


 ---------- 2021-07-31 14:00:00 : 퇴계동   37396 ----------


 ---------- 2021-07-31 15:00:00 : 퇴계동   37397 ----------


 ---------- 2021-07-31 18:00:00 : 후평1동   37398 ----------


 ---------- 2021-08-01 07:00:00 : 신사우동   37400 ----------


 ---------- 2021-08-01 09:00:00 : 동  면   37401 ----------


 ---------- 2021-08-01 09:00:00 : 후평1동   37402 ----------


 ---------- 2021-08-01 10:00:00 : 동내면   37403 ----------


 ---------- 2021-08-01 11:00:00 : 남산면   37404 ----------


 ---------- 2021-08-01 11:00:00 : 신북읍   37405 ----------


 ---------- 2021-08-01 11:00:00 : 동산면   37408 ----------


 ---------- 2021-08-01 12:00:00 : 남산면   37409 ----------


 ---------- 2021-08-01 12:00:00 : 후평1동   37410 ----------


 ---------- 2021-08-01 13:00:00 : 소양동   37412 ----------


 ---------- 2021-08-01 16:00:00 : 동내면   37413 ----------


 ---------- 2021-08-01 16:00:00 : 효자1동   37414 ----------


 ---------- 2021-08-01 18:00:00 : 근화동   37417 ----------


 ---------- 2021-08-01 20:00:00 : 약사명동   37420 ----------


 ---------- 2021-08-01 21:00:00 : 신동면   37421 ----------


 ---------- 2021-08-01 21:00:00 : 강남동   37422 ----------


 ---------- 2021-08-01 22:00:00 : 남산면   37423 ----------


 ---------- 2021-08-01 23:00:00 : 근화동   37425 ----------


 ---------- 2021-08-01 23:00:00 : 신북읍   37426 ----------


 ---------- 2021-08-02 07:00:00 : 근화동   37427 ----------


 ---------- 2021-08-02 08:00:00 : 후평1동   37428 ----------


 ---------- 2021-08-02 09:00:00 : 조운동   37429 ----------


 ---------- 2021-08-02 10:00:00 : 석사동   37432 ----------


 ---------- 2021-08-02 11:00:00 : 퇴계동   37433 ----------


 ---------- 2021-08-02 12:00:00 : 후평1동   37434 ----------


 ---------- 2021-08-02 12:00:00 : 퇴계동   37435 ----------


 ---------- 2021-08-02 13:00:00 : 교  동   37436 ----------


 ---------- 2021-08-02 14:00:00 : 석사동   37437 ----------


 ---------- 2021-08-02 14:00:00 : 남산면   37438 ----------


 ---------- 2021-08-02 14:00:00 : 신북읍   37439 ----------


 ---------- 2021-08-02 15:00:00 : 퇴계동   37440 ----------


 ---------- 2021-08-02 16:00:00 : 동내면   37441 ----------


 ---------- 2021-08-02 16:00:00 : 소양동   37442 ----------


 ---------- 2021-08-02 16:00:00 : 약사명동   37443 ----------


 ---------- 2021-08-02 17:00:00 : 신사우동   37444 ----------


 ---------- 2021-08-02 18:00:00 : 석사동   37445 ----------


 ---------- 2021-08-02 18:00:00 : 신사우동   37446 ----------


 ---------- 2021-08-02 19:00:00 : 동내면   37447 ----------


 ---------- 2021-08-02 21:00:00 : 신사우동   37450 ----------


 ---------- 2021-08-02 21:00:00 : 후평1동   37451 ----------

 ---------- 2021-08-02 23:00:00 : 퇴계동   37452 ----------


 ---------- 2021-08-03 03:00:00 : 교  동   37454 ----------


 ---------- 2021-08-03 06:00:00 : 강남동   37455 ----------


 ---------- 2021-08-03 07:00:00 : 퇴계동   37456 ----------


 ---------- 2021-08-03 08:00:00 : 서  면   37457 ----------


 ---------- 2021-08-03 08:00:00 : 동내면   37458 ----------


 ---------- 2021-08-03 08:00:00 : 후평1동   37459 ----------


 ---------- 2021-08-03 08:00:00 : 퇴계동   37460 ----------


 ---------- 2021-08-03 10:00:00 : 신동면   37461 ----------


 ---------- 2021-08-03 11:00:00 : 효자1동   37462 ----------


 ---------- 2021-08-03 13:00:00 : 신동면   37463 ----------


 ---------- 2021-08-03 14:00:00 : 신사우동   37464 ----------


 ---------- 2021-08-03 14:00:00 : 소양동   37465 ----------


 ---------- 2021-08-03 14:00:00 : 교  동   37466 ----------


 ---------- 2021-08-03 15:00:00 : 사북면   37467 ----------


 ---------- 2021-08-03 15:00:00 : 후평1동   37470 ----------


 ---------- 2021-08-03 15:00:00 : 퇴계동   37471 ----------


 ---------- 2021-08-03 17:00:00 : 소양동   37472 ----------


 ---------- 2021-08-03 19:00:00 : 석사동   37473 ----------


 ---------- 2021-08-03 19:00:00 : 효자1동   37474 ----------


 ---------- 2021-08-03 19:00:00 : 퇴계동   37475 ----------


 ---------- 2021-08-03 23:00:00 : 효자1동   37476 ----------


 ---------- 2021-08-04 00:00:00 : 동  면   37478 ----------


 ---------- 2021-08-04 03:00:00 : 강남동   37479 ----------


 ---------- 2021-08-04 06:00:00 : 신북읍   37480 ----------


 ---------- 2021-08-04 09:00:00 : 동내면   37481 ----------


 ---------- 2021-08-04 09:00:00 : 근화동   37482 ----------


 ---------- 2021-08-04 10:00:00 : 석사동   37485 ----------


 ---------- 2021-08-04 10:00:00 : 강남동   37486 ----------


 ---------- 2021-08-04 11:00:00 : 후평1동   37487 ----------


 ---------- 2021-08-04 13:00:00 : 신동면   37488 ----------


 ---------- 2021-08-04 13:00:00 : 효자1동   37492 ----------


 ---------- 2021-08-04 14:00:00 : 남산면   37493 ----------


 ---------- 2021-08-04 15:00:00 : 퇴계동   37496 ----------


 ---------- 2021-08-04 16:00:00 : 동  면   37497 ----------


 ---------- 2021-08-04 18:00:00 : 석사동   37498 ----------


 ---------- 2021-08-04 18:00:00 : 남산면   37499 ----------


 ---------- 2021-08-04 20:00:00 : 퇴계동   37500 ----------


 ---------- 2021-08-04 21:00:00 : 서  면   37503 ----------


 ---------- 2021-08-04 22:00:00 : 동  면   37504 ----------


 ---------- 2021-08-05 09:00:00 : 서  면   37505 ----------


 ---------- 2021-08-05 09:00:00 : 남산면   37506 ----------


 ---------- 2021-08-05 11:00:00 : 신동면   37507 ----------


 ---------- 2021-08-05 11:00:00 : 동내면   37508 ----------


 ---------- 2021-08-05 12:00:00 : 석사동   37509 ----------


 ---------- 2021-08-05 12:00:00 : 서  면   37512 ----------


 ---------- 2021-08-05 12:00:00 : 남산면   37513 ----------


 ---------- 2021-08-05 14:00:00 : 남  면   37515 ----------


 ---------- 2021-08-05 15:00:00 : 신동면   37516 ----------


 ---------- 2021-08-05 15:00:00 : 남  면   37517 ----------


 ---------- 2021-08-05 15:00:00 : 동  면   37519 ----------


 ---------- 2021-08-05 15:00:00 : 후평1동   37520 ----------


 ---------- 2021-08-05 15:00:00 : 퇴계동   37521 ----------


 ---------- 2021-08-05 16:00:00 : 퇴계동   37522 ----------


 ---------- 2021-08-05 17:00:00 : 신사우동   37523 ----------


 ---------- 2021-08-05 22:00:00 : 퇴계동   37524 ----------


 ---------- 2021-08-06 00:00:00 : 효자1동   37525 ----------


 ---------- 2021-08-06 06:00:00 : 서  면   37526 ----------


 ---------- 2021-08-06 08:00:00 : 동내면   37527 ----------


 ---------- 2021-08-06 09:00:00 : 동  면   37528 ----------


 ---------- 2021-08-06 11:00:00 : 신동면   37531 ----------


 ---------- 2021-08-06 11:00:00 : 동내면   37532 ----------


 ---------- 2021-08-06 11:00:00 : 퇴계동   37533 ----------


 ---------- 2021-08-06 12:00:00 : 남  면   37535 ----------


 ---------- 2021-08-06 13:00:00 : 퇴계동   37536 ----------


 ---------- 2021-08-06 14:00:00 : 남산면   37537 ----------


 ---------- 2021-08-06 14:00:00 : 동  면   37538 ----------


 ---------- 2021-08-06 14:00:00 : 동산면   37539 ----------


 ---------- 2021-08-06 15:00:00 : 남산면   37540 ----------


 ---------- 2021-08-06 15:00:00 : 동산면   37543 ----------


 ---------- 2021-08-06 17:00:00 : 석사동   37544 ----------


 ---------- 2021-08-06 18:00:00 : 강남동   37545 ----------


 ---------- 2021-08-07 01:00:00 : 동내면   37547 ----------


 ---------- 2021-08-07 01:00:00 : 소양동   37548 ----------


 ---------- 2021-08-07 06:00:00 : 남산면   37549 ----------


 ---------- 2021-08-07 08:00:00 : 석사동   37550 ----------


 ---------- 2021-08-07 09:00:00 : 사북면   37551 ----------


 ---------- 2021-08-07 09:00:00 : 퇴계동   37553 ----------


 ---------- 2021-08-07 10:00:00 : 서  면   37554 ----------


 ---------- 2021-08-07 11:00:00 : 동내면   37555 ----------


 ---------- 2021-08-07 11:00:00 : 신사우동   37556 ----------


 ---------- 2021-08-07 11:00:00 : 동산면   37557 ----------


 ---------- 2021-08-07 12:00:00 : 신북읍   37559 ----------


 ---------- 2021-08-07 13:00:00 : 동내면   37560 ----------


 ---------- 2021-08-07 13:00:00 : 신북읍   37561 ----------


 ---------- 2021-08-07 13:00:00 : 후평1동   37562 ----------


 ---------- 2021-08-07 13:00:00 : 퇴계동   37563 ----------


 ---------- 2021-08-07 14:00:00 : 남산면   37568 ----------


 ---------- 2021-08-07 14:00:00 : 근화동   37569 ----------


 ---------- 2021-08-07 16:00:00 : 석사동   37570 ----------


 ---------- 2021-08-07 16:00:00 : 신동면   37571 ----------


 ---------- 2021-08-07 16:00:00 : 강남동   37572 ----------


 ---------- 2021-08-07 16:00:00 : 북산면   37573 ----------


 ---------- 2021-08-07 18:00:00 : 남  면   37574 ----------


 ---------- 2021-08-07 18:00:00 : 교  동   37575 ----------


 ---------- 2021-08-07 19:00:00 : 동내면   37576 ----------


 ---------- 2021-08-07 19:00:00 : 퇴계동   37577 ----------


 ---------- 2021-08-07 20:00:00 : 남산면   37579 ----------


 ---------- 2021-08-07 22:00:00 : 신사우동   37581 ----------


 ---------- 2021-08-08 09:00:00 : 동내면   37582 ----------


 ---------- 2021-08-08 09:00:00 : 약사명동   37584 ----------


 ---------- 2021-08-08 10:00:00 : 서  면   37585 ----------


 ---------- 2021-08-08 10:00:00 : 남산면   37586 ----------


 ---------- 2021-08-08 10:00:00 : 후평1동   37587 ----------


 ---------- 2021-08-08 10:00:00 : 퇴계동   37588 ----------


 ---------- 2021-08-08 12:00:00 : 동  면   37589 ----------


 ---------- 2021-08-08 12:00:00 : 퇴계동   37590 ----------


 ---------- 2021-08-08 14:00:00 : 후평1동   37591 ----------


 ---------- 2021-08-08 15:00:00 : 남  면   37592 ----------


 ---------- 2021-08-08 15:00:00 : 신북읍   37593 ----------


 ---------- 2021-08-08 15:00:00 : 퇴계동   37594 ----------


 ---------- 2021-08-08 16:00:00 : 서  면   37597 ----------


 ---------- 2021-08-08 17:00:00 : 석사동   37598 ----------


 ---------- 2021-08-08 17:00:00 : 효자1동   37599 ----------


 ---------- 2021-08-08 17:00:00 : 근화동   37600 ----------


 ---------- 2021-08-08 20:00:00 : 석사동   37601 ----------


 ---------- 2021-08-08 20:00:00 : 동내면   37602 ----------


 ---------- 2021-08-08 21:00:00 : 신사우동   37604 ----------


 ---------- 2021-08-09 07:00:00 : 효자1동   37605 ----------


 ---------- 2021-08-09 08:00:00 : 동내면   37606 ----------


 ---------- 2021-08-09 08:00:00 : 효자1동   37607 ----------


 ---------- 2021-08-09 08:00:00 : 퇴계동   37608 ----------


 ---------- 2021-08-09 09:00:00 : 신동면   37609 ----------


 ---------- 2021-08-09 09:00:00 : 효자1동   37610 ----------


 ---------- 2021-08-09 09:00:00 : 신북읍   37611 ----------


 ---------- 2021-08-09 09:00:00 : 동  면   37613 ----------


 ---------- 2021-08-09 10:00:00 : 석사동   37614 ----------


 ---------- 2021-08-09 10:00:00 : 동내면   37615 ----------


 ---------- 2021-08-09 10:00:00 : 동  면   37618 ----------


 ---------- 2021-08-09 11:00:00 : 신동면   37619 ----------


 ---------- 2021-08-09 11:00:00 : 동내면   37621 ----------


 ---------- 2021-08-09 12:00:00 : 강남동   37622 ----------


 ---------- 2021-08-09 12:00:00 : 신북읍   37623 ----------


 ---------- 2021-08-09 12:00:00 : 후평1동   37624 ----------


 ---------- 2021-08-09 13:00:00 : 동내면   37625 ----------


 ---------- 2021-08-09 16:00:00 : 남  면   37626 ----------

 ---------- 2021-08-10 04:00:00 : 동산면   37627 ----------


 ---------- 2021-08-10 08:00:00 : 효자1동   37628 ----------


 ---------- 2021-08-10 08:00:00 : 동산면   37629 ----------


 ---------- 2021-08-10 09:00:00 : 석사동   37630 ----------


 ---------- 2021-08-10 09:00:00 : 근화동   37631 ----------


 ---------- 2021-08-10 09:00:00 : 신북읍   37633 ----------


 ---------- 2021-08-10 10:00:00 : 신동면   37634 ----------


 ---------- 2021-08-10 10:00:00 : 신사우동   37635 ----------


 ---------- 2021-08-10 10:00:00 : 동  면   37636 ----------


 ---------- 2021-08-10 10:00:00 : 후평1동   37638 ----------


 ---------- 2021-08-10 11:00:00 : 신북읍   37639 ----------


 ---------- 2021-08-10 11:00:00 : 후평1동   37640 ----------


 ---------- 2021-08-10 12:00:00 : 석사동   37641 ----------


 ---------- 2021-08-10 12:00:00 : 신북읍   37642 ----------


 ---------- 2021-08-10 13:00:00 : 동내면   37643 ----------


 ---------- 2021-08-10 13:00:00 : 효자1동   37644 ----------


 ---------- 2021-08-10 13:00:00 : 남산면   37645 ----------


 ---------- 2021-08-10 13:00:00 : 신북읍   37647 ----------


 ---------- 2021-08-10 13:00:00 : 동산면   37650 ----------


 ---------- 2021-08-10 14:00:00 : 사북면   37652 ----------


 ---------- 2021-08-10 15:00:00 : 동내면   37653 ----------


 ---------- 2021-08-10 15:00:00 : 교  동   37655 ----------


 ---------- 2021-08-10 17:00:00 : 신사우동   37656 ----------


 ---------- 2021-08-10 17:00:00 : 후평1동   37657 ----------


 ---------- 2021-08-10 18:00:00 : 효자1동   37663 ----------


 ---------- 2021-08-10 22:00:00 : 석사동   37664 ----------


 ---------- 2021-08-10 22:00:00 : 조운동   37665 ----------


 ---------- 2021-08-10 23:00:00 : 석사동   37666 ----------


 ---------- 2021-08-11 01:00:00 : 동  면   37668 ----------


 ---------- 2021-08-11 03:00:00 : 동산면   37671 ----------


 ---------- 2021-08-11 09:00:00 : 동내면   37672 ----------


 ---------- 2021-08-11 09:00:00 : 후평1동   37673 ----------


 ---------- 2021-08-11 09:00:00 : 퇴계동   37674 ----------


 ---------- 2021-08-11 10:00:00 : 사북면   37675 ----------


 ---------- 2021-08-11 11:00:00 : 동내면   37676 ----------


 ---------- 2021-08-11 11:00:00 : 효자1동   37678 ----------


 ---------- 2021-08-11 11:00:00 : 근화동   37679 ----------


 ---------- 2021-08-11 13:00:00 : 석사동   37680 ----------


 ---------- 2021-08-11 13:00:00 : 강남동   37681 ----------


 ---------- 2021-08-11 13:00:00 : 효자1동   37683 ----------


 ---------- 2021-08-11 14:00:00 : 강남동   37684 ----------


 ---------- 2021-08-11 14:00:00 : 동  면   37685 ----------


 ---------- 2021-08-11 15:00:00 : 신동면   37686 ----------


 ---------- 2021-08-11 17:00:00 : 서  면   37687 ----------


 ---------- 2021-08-11 17:00:00 : 퇴계동   37688 ----------


 ---------- 2021-08-11 22:00:00 : 효자1동   37689 ----------


 ---------- 2021-08-12 01:00:00 : 신사우동   37691 ----------


 ---------- 2021-08-12 05:00:00 : 서  면   37692 ----------


 ---------- 2021-08-12 09:00:00 : 신동면   37693 ----------


 ---------- 2021-08-12 09:00:00 : 동  면   37694 ----------


 ---------- 2021-08-12 09:00:00 : 퇴계동   37695 ----------


 ---------- 2021-08-12 10:00:00 : 동내면   37696 ----------


 ---------- 2021-08-12 10:00:00 : 효자1동   37697 ----------


 ---------- 2021-08-12 11:00:00 : 근화동   37698 ----------


 ---------- 2021-08-12 11:00:00 : 동산면   37699 ----------


 ---------- 2021-08-12 12:00:00 : 석사동   37700 ----------


 ---------- 2021-08-12 13:00:00 : 효자1동   37702 ----------


 ---------- 2021-08-12 13:00:00 : 동  면   37703 ----------


 ---------- 2021-08-12 14:00:00 : 사북면   37704 ----------


 ---------- 2021-08-12 14:00:00 : 효자1동   37705 ----------


 ---------- 2021-08-12 14:00:00 : 퇴계동   37706 ----------


 ---------- 2021-08-12 15:00:00 : 사북면   37707 ----------


 ---------- 2021-08-12 17:00:00 : 동내면   37708 ----------


 ---------- 2021-08-12 17:00:00 : 후평1동   37709 ----------


 ---------- 2021-08-12 19:00:00 : 신북읍   37711 ----------


 ---------- 2021-08-12 19:00:00 : 후평1동   37712 ----------


 ---------- 2021-08-12 21:00:00 : 신사우동   37713 ----------


 ---------- 2021-08-12 22:00:00 : 후평1동   37715 ----------


 ---------- 2021-08-13 04:00:00 : 동내면   37716 ----------


 ---------- 2021-08-13 08:00:00 : 신사우동   37717 ----------


 ---------- 2021-08-13 09:00:00 : 신사우동   37718 ----------


 ---------- 2021-08-13 09:00:00 : 후평1동   37719 ----------


 ---------- 2021-08-13 10:00:00 : 강남동   37720 ----------


 ---------- 2021-08-13 10:00:00 : 동  면   37722 ----------


 ---------- 2021-08-13 13:00:00 : 서  면   37723 ----------


 ---------- 2021-08-13 13:00:00 : 후평1동   37724 ----------


 ---------- 2021-08-13 14:00:00 : 석사동   37725 ----------


 ---------- 2021-08-13 14:00:00 : 신동면   37726 ----------


 ---------- 2021-08-13 15:00:00 : 퇴계동   37729 ----------


 ---------- 2021-08-13 17:00:00 : 석사동   37731 ----------


 ---------- 2021-08-13 17:00:00 : 퇴계동   37732 ----------


 ---------- 2021-08-13 19:00:00 : 강남동   37733 ----------


 ---------- 2021-08-13 19:00:00 : 사북면   37734 ----------


 ---------- 2021-08-13 22:00:00 : 후평1동   37736 ----------


 ---------- 2021-08-13 23:00:00 : 석사동   37738 ----------


 ---------- 2021-08-14 07:00:00 : 동내면   37739 ----------


 ---------- 2021-08-14 08:00:00 : 신동면   37740 ----------


 ---------- 2021-08-14 08:00:00 : 약사명동   37741 ----------


 ---------- 2021-08-14 09:00:00 : 신동면   37742 ----------


 ---------- 2021-08-14 09:00:00 : 퇴계동   37745 ----------


 ---------- 2021-08-14 10:00:00 : 남  면   37746 ----------


 ---------- 2021-08-14 10:00:00 : 동내면   37747 ----------


 ---------- 2021-08-14 10:00:00 : 동산면   37748 ----------


 ---------- 2021-08-14 11:00:00 : 소양동   37749 ----------


 ---------- 2021-08-14 11:00:00 : 후평1동   37750 ----------


 ---------- 2021-08-14 12:00:00 : 서  면   37751 ----------


 ---------- 2021-08-14 13:00:00 : 신동면   37752 ----------


 ---------- 2021-08-14 13:00:00 : 동내면   37753 ----------


 ---------- 2021-08-14 14:00:00 : 서  면   37755 ----------


 ---------- 2021-08-14 14:00:00 : 사북면   37756 ----------


 ---------- 2021-08-14 16:00:00 : 서  면   37757 ----------


 ---------- 2021-08-14 16:00:00 : 남산면   37758 ----------


 ---------- 2021-08-14 17:00:00 : 서  면   37759 ----------


 ---------- 2021-08-14 17:00:00 : 퇴계동   37760 ----------


 ---------- 2021-08-14 22:00:00 : 동내면   37761 ----------


 ---------- 2021-08-14 22:00:00 : 동산면   37763 ----------


 ---------- 2021-08-15 01:00:00 : 남산면   37765 ----------


 ---------- 2021-08-15 04:00:00 : 신사우동   37767 ----------


 ---------- 2021-08-15 09:00:00 : 후평1동   37768 ----------


 ---------- 2021-08-15 10:00:00 : 서  면   37770 ----------


 ---------- 2021-08-15 11:00:00 : 서  면   37771 ----------


 ---------- 2021-08-15 11:00:00 : 남  면   37772 ----------


 ---------- 2021-08-15 13:00:00 : 남  면   37773 ----------


 ---------- 2021-08-15 13:00:00 : 동  면   37774 ----------


 ---------- 2021-08-15 17:00:00 : 효자1동   37775 ----------


 ---------- 2021-08-15 17:00:00 : 남산면   37776 ----------


 ---------- 2021-08-15 17:00:00 : 신북읍   37777 ----------


 ---------- 2021-08-15 17:00:00 : 소양동   37778 ----------


 ---------- 2021-08-15 17:00:00 : 퇴계동   37779 ----------


 ---------- 2021-08-15 18:00:00 : 사북면   37780 ----------


 ---------- 2021-08-15 19:00:00 : 퇴계동   37781 ----------


 ---------- 2021-08-15 21:00:00 : 석사동   37782 ----------


 ---------- 2021-08-15 21:00:00 : 동내면   37783 ----------


 ---------- 2021-08-15 22:00:00 : 석사동   37784 ----------


 ---------- 2021-08-16 04:00:00 : 남산면   37785 ----------


 ---------- 2021-08-16 08:00:00 : 신동면   37788 ----------


 ---------- 2021-08-16 09:00:00 : 사북면   37789 ----------


 ---------- 2021-08-16 10:00:00 : 남산면   37790 ----------


 ---------- 2021-08-16 10:00:00 : 근화동   37791 ----------


 ---------- 2021-08-16 10:00:00 : 퇴계동   37792 ----------


 ---------- 2021-08-16 11:00:00 : 강남동   37793 ----------


 ---------- 2021-08-16 11:00:00 : 퇴계동   37794 ----------


 ---------- 2021-08-16 12:00:00 : 동  면   37795 ----------


 ---------- 2021-08-16 12:00:00 : 후평1동   37798 ----------


 ---------- 2021-08-16 13:00:00 : 강남동   37801 ----------


 ---------- 2021-08-16 14:00:00 : 석사동   37802 ----------

 ---------- 2021-08-16 16:00:00 : 서  면   37803 ----------


 ---------- 2021-08-16 16:00:00 : 동내면   37804 ----------


 ---------- 2021-08-16 17:00:00 : 강남동   37805 ----------


 ---------- 2021-08-16 20:00:00 : 석사동   37806 ----------


 ---------- 2021-08-16 20:00:00 : 남  면   37807 ----------


 ---------- 2021-08-16 20:00:00 : 소양동   37808 ----------


 ---------- 2021-08-16 21:00:00 : 퇴계동   37809 ----------


 ---------- 2021-08-17 08:00:00 : 사북면   37810 ----------


 ---------- 2021-08-17 08:00:00 : 소양동   37812 ----------


 ---------- 2021-08-17 10:00:00 : 동내면   37813 ----------


 ---------- 2021-08-17 10:00:00 : 남산면   37814 ----------


 ---------- 2021-08-17 10:00:00 : 퇴계동   37815 ----------


 ---------- 2021-08-17 11:00:00 : 사북면   37816 ----------


 ---------- 2021-08-17 12:00:00 : 남  면   37817 ----------


 ---------- 2021-08-17 13:00:00 : 석사동   37819 ----------


 ---------- 2021-08-17 13:00:00 : 후평1동   37820 ----------


 ---------- 2021-08-17 14:00:00 : 교  동   37821 ----------


 ---------- 2021-08-17 15:00:00 : 사북면   37822 ----------


 ---------- 2021-08-17 15:00:00 : 근화동   37823 ----------


 ---------- 2021-08-17 15:00:00 : 퇴계동   37824 ----------


 ---------- 2021-08-17 16:00:00 : 효자1동   37825 ----------


 ---------- 2021-08-17 16:00:00 : 동  면   37826 ----------


 ---------- 2021-08-17 17:00:00 : 강남동   37827 ----------


 ---------- 2021-08-17 17:00:00 : 동내면   37828 ----------


 ---------- 2021-08-17 17:00:00 : 남산면   37829 ----------


 ---------- 2021-08-17 17:00:00 : 동  면   37830 ----------


 ---------- 2021-08-17 19:00:00 : 퇴계동   37831 ----------


 ---------- 2021-08-17 21:00:00 : 후평1동   37832 ----------


 ---------- 2021-08-18 00:00:00 : 석사동   37833 ----------


 ---------- 2021-08-18 04:00:00 : 동내면   37834 ----------


 ---------- 2021-08-18 07:00:00 : 효자1동   37835 ----------


 ---------- 2021-08-18 10:00:00 : 석사동   37836 ----------


 ---------- 2021-08-18 10:00:00 : 후평1동   37837 ----------


 ---------- 2021-08-18 10:00:00 : 조운동   37838 ----------


 ---------- 2021-08-18 11:00:00 : 신동면   37839 ----------


 ---------- 2021-08-18 11:00:00 : 강남동   37840 ----------


 ---------- 2021-08-18 11:00:00 : 효자1동   37844 ----------


 ---------- 2021-08-18 12:00:00 : 석사동   37845 ----------


 ---------- 2021-08-18 12:00:00 : 강남동   37846 ----------


 ---------- 2021-08-18 13:00:00 : 강남동   37847 ----------


 ---------- 2021-08-18 13:00:00 : 사북면   37848 ----------


 ---------- 2021-08-18 13:00:00 : 동내면   37849 ----------


 ---------- 2021-08-18 14:00:00 : 남  면   37850 ----------


 ---------- 2021-08-18 14:00:00 : 근화동   37851 ----------


 ---------- 2021-08-18 14:00:00 : 신사우동   37852 ----------


 ---------- 2021-08-18 14:00:00 : 퇴계동   37853 ----------


 ---------- 2021-08-18 15:00:00 : 동  면   37854 ----------


 ---------- 2021-08-18 16:00:00 : 교  동   37855 ----------


 ---------- 2021-08-18 17:00:00 : 동내면   37856 ----------


 ---------- 2021-08-18 17:00:00 : 근화동   37858 ----------


 ---------- 2021-08-18 18:00:00 : 신사우동   37859 ----------


 ---------- 2021-08-19 01:00:00 : 남산면   37860 ----------


 ---------- 2021-08-19 03:00:00 : 동내면   37861 ----------


 ---------- 2021-08-19 05:00:00 : 신사우동   37862 ----------


 ---------- 2021-08-19 09:00:00 : 석사동   37863 ----------


 ---------- 2021-08-19 09:00:00 : 동내면   37864 ----------


 ---------- 2021-08-19 09:00:00 : 효자1동   37865 ----------


 ---------- 2021-08-19 09:00:00 : 동  면   37867 ----------


 ---------- 2021-08-19 10:00:00 : 소양동   37868 ----------


 ---------- 2021-08-19 11:00:00 : 소양동   37869 ----------


 ---------- 2021-08-19 12:00:00 : 남산면   37871 ----------


 ---------- 2021-08-19 12:00:00 : 북산면   37872 ----------


 ---------- 2021-08-19 13:00:00 : 강남동   37873 ----------


 ---------- 2021-08-19 14:00:00 : 석사동   37874 ----------


 ---------- 2021-08-19 14:00:00 : 후평1동   37877 ----------


 ---------- 2021-08-19 14:00:00 : 퇴계동   37879 ----------


 ---------- 2021-08-19 16:00:00 : 석사동   37880 ----------


 ---------- 2021-08-19 16:00:00 : 신사우동   37881 ----------


 ---------- 2021-08-19 16:00:00 : 신북읍   37882 ----------


 ---------- 2021-08-19 16:00:00 : 소양동   37885 ----------


 ---------- 2021-08-19 17:00:00 : 석사동   37886 ----------


 ---------- 2021-08-19 17:00:00 : 근화동   37887 ----------


 ---------- 2021-08-19 17:00:00 : 신북읍   37891 ----------


 ---------- 2021-08-19 17:00:00 : 퇴계동   37894 ----------


 ---------- 2021-08-19 17:00:00 : 동산면   37898 ----------


 ---------- 2021-08-19 18:00:00 : 남산면   37900 ----------


 ---------- 2021-08-19 18:00:00 : 소양동   37901 ----------


 ---------- 2021-08-19 20:00:00 : 후평1동   37902 ----------


 ---------- 2021-08-19 22:00:00 : 석사동   37903 ----------


 ---------- 2021-08-19 22:00:00 : 후평1동   37904 ----------


 ---------- 2021-08-20 08:00:00 : 석사동   37905 ----------


 ---------- 2021-08-20 08:00:00 : 서  면   37908 ----------


 ---------- 2021-08-20 09:00:00 : 동  면   37912 ----------


 ---------- 2021-08-20 09:00:00 : 퇴계동   37913 ----------


 ---------- 2021-08-20 10:00:00 : 동내면   37914 ----------


 ---------- 2021-08-20 11:00:00 : 동내면   37915 ----------


 ---------- 2021-08-20 11:00:00 : 신사우동   37916 ----------


 ---------- 2021-08-20 12:00:00 : 신동면   37917 ----------


 ---------- 2021-08-20 12:00:00 : 남산면   37918 ----------


 ---------- 2021-08-20 12:00:00 : 신북읍   37919 ----------


 ---------- 2021-08-20 12:00:00 : 소양동   37920 ----------


 ---------- 2021-08-20 13:00:00 : 강남동   37921 ----------


 ---------- 2021-08-20 13:00:00 : 서  면   37922 ----------


 ---------- 2021-08-20 13:00:00 : 퇴계동   37923 ----------


 ---------- 2021-08-20 15:00:00 : 신사우동   37924 ----------


 ---------- 2021-08-20 16:00:00 : 동내면   37926 ----------


 ---------- 2021-08-20 17:00:00 : 신동면   37927 ----------


 ---------- 2021-08-20 18:00:00 : 사북면   37928 ----------


 ---------- 2021-08-20 19:00:00 : 효자1동   37929 ----------


 ---------- 2021-08-20 22:00:00 : 석사동   37931 ----------


 ---------- 2021-08-20 23:00:00 : 동  면   37932 ----------


 ---------- 2021-08-21 08:00:00 : 남  면   37933 ----------


 ---------- 2021-08-21 08:00:00 : 퇴계동   37934 ----------


 ---------- 2021-08-21 09:00:00 : 서  면   37935 ----------


 ---------- 2021-08-21 09:00:00 : 신사우동   37936 ----------


 ---------- 2021-08-21 09:00:00 : 교  동   37937 ----------


 ---------- 2021-08-21 11:00:00 : 강남동   37938 ----------


 ---------- 2021-08-21 11:00:00 : 신사우동   37939 ----------


 ---------- 2021-08-21 12:00:00 : 서  면   37941 ----------


 ---------- 2021-08-21 14:00:00 : 효자1동   37942 ----------


 ---------- 2021-08-21 15:00:00 : 후평1동   37943 ----------


 ---------- 2021-08-21 16:00:00 : 동내면   37944 ----------


 ---------- 2021-08-21 16:00:00 : 남산면   37945 ----------


 ---------- 2021-08-21 17:00:00 : 석사동   37946 ----------


 ---------- 2021-08-21 17:00:00 : 강남동   37948 ----------


 ---------- 2021-08-21 18:00:00 : 신북읍   37949 ----------


 ---------- 2021-08-21 20:00:00 : 동내면   37950 ----------


 ---------- 2021-08-21 22:00:00 : 신북읍   37951 ----------


 ---------- 2021-08-22 07:00:00 : 후평1동   37952 ----------


 ---------- 2021-08-22 08:00:00 : 동내면   37953 ----------


 ---------- 2021-08-22 08:00:00 : 동  면   37955 ----------


 ---------- 2021-08-22 12:00:00 : 동  면   37957 ----------


 ---------- 2021-08-22 13:00:00 : 남산면   37959 ----------


 ---------- 2021-08-22 13:00:00 : 동  면   37960 ----------


 ---------- 2021-08-22 14:00:00 : 남산면   37962 ----------


 ---------- 2021-08-22 14:00:00 : 동  면   37963 ----------


 ---------- 2021-08-22 14:00:00 : 퇴계동   37965 ----------


 ---------- 2021-08-22 15:00:00 : 남산면   37966 ----------


 ---------- 2021-08-22 16:00:00 : 효자1동   37967 ----------


 ---------- 2021-08-22 17:00:00 : 소양동   37969 ----------


 ---------- 2021-08-22 19:00:00 : 효자1동   37970 ----------


 ---------- 2021-08-22 19:00:00 : 후평1동   37971 ----------


 ---------- 2021-08-23 01:00:00 : 교  동   37972 ----------


 ---------- 2021-08-23 06:00:00 : 신북읍   37974 ----------


 ---------- 2021-08-23 07:00:00 : 퇴계동   37975 ----------


 ---------- 2021-08-23 07:00:00 : 동산면   37977 ----------

 ---------- 2021-08-23 08:00:00 : 신사우동   37978 ----------


 ---------- 2021-08-23 10:00:00 : 후평1동   37979 ----------


 ---------- 2021-08-23 11:00:00 : 남  면   37980 ----------


 ---------- 2021-08-23 13:00:00 : 동  면   37983 ----------


 ---------- 2021-08-23 16:00:00 : 석사동   37984 ----------


 ---------- 2021-08-23 17:00:00 : 강남동   37986 ----------


 ---------- 2021-08-23 18:00:00 : 동내면   37987 ----------


 ---------- 2021-08-23 19:00:00 : 신사우동   37988 ----------


 ---------- 2021-08-23 19:00:00 : 동산면   37989 ----------


 ---------- 2021-08-23 23:00:00 : 동내면   37990 ----------


 ---------- 2021-08-24 07:00:00 : 약사명동   37991 ----------


 ---------- 2021-08-24 09:00:00 : 석사동   37992 ----------


 ---------- 2021-08-24 09:00:00 : 소양동   37993 ----------


 ---------- 2021-08-24 11:00:00 : 효자1동   37994 ----------


 ---------- 2021-08-24 11:00:00 : 후평1동   37995 ----------


 ---------- 2021-08-24 12:00:00 : 동내면   37996 ----------


 ---------- 2021-08-24 13:00:00 : 신사우동   37997 ----------


 ---------- 2021-08-24 14:00:00 : 동  면   37998 ----------


 ---------- 2021-08-24 15:00:00 : 신북읍   37999 ----------


 ---------- 2021-08-24 17:00:00 : 후평1동   38000 ----------


 ---------- 2021-08-24 19:00:00 : 동내면   38001 ----------


 ---------- 2021-08-24 19:00:00 : 후평1동   38002 ----------


 ---------- 2021-08-25 02:00:00 : 후평1동   38004 ----------


 ---------- 2021-08-25 03:00:00 : 남산면   38005 ----------


 ---------- 2021-08-25 09:00:00 : 강남동   38006 ----------


 ---------- 2021-08-25 10:00:00 : 신사우동   38007 ----------


 ---------- 2021-08-25 11:00:00 : 강남동   38008 ----------


 ---------- 2021-08-25 11:00:00 : 남  면   38009 ----------


 ---------- 2021-08-25 14:00:00 : 사북면   38010 ----------


 ---------- 2021-08-25 14:00:00 : 동산면   38012 ----------


 ---------- 2021-08-25 15:00:00 : 효자1동   38013 ----------


 ---------- 2021-08-25 15:00:00 : 신사우동   38015 ----------


 ---------- 2021-08-25 16:00:00 : 소양동   38017 ----------


 ---------- 2021-08-25 16:00:00 : 교  동   38018 ----------


 ---------- 2021-08-25 17:00:00 : 서  면   38020 ----------


 ---------- 2021-08-25 18:00:00 : 교  동   38021 ----------


 ---------- 2021-08-25 22:00:00 : 후평1동   38022 ----------


 ---------- 2021-08-26 06:00:00 : 강남동   38024 ----------


 ---------- 2021-08-26 08:00:00 : 사북면   38025 ----------


 ---------- 2021-08-26 08:00:00 : 신사우동   38026 ----------


 ---------- 2021-08-26 08:00:00 : 퇴계동   38027 ----------


 ---------- 2021-08-26 10:00:00 : 퇴계동   38028 ----------


 ---------- 2021-08-26 11:00:00 : 근화동   38029 ----------


 ---------- 2021-08-26 11:00:00 : 신북읍   38030 ----------


 ---------- 2021-08-26 11:00:00 : 후평1동   38031 ----------


 ---------- 2021-08-26 11:00:00 : 퇴계동   38032 ----------


 ---------- 2021-08-26 13:00:00 : 동내면   38033 ----------


 ---------- 2021-08-26 13:00:00 : 동산면   38034 ----------


 ---------- 2021-08-26 14:00:00 : 소양동   38035 ----------


 ---------- 2021-08-26 15:00:00 : 동  면   38036 ----------


 ---------- 2021-08-26 17:00:00 : 신사우동   38037 ----------


 ---------- 2021-08-26 20:00:00 : 신사우동   38038 ----------


 ---------- 2021-08-26 22:00:00 : 석사동   38039 ----------


 ---------- 2021-08-26 22:00:00 : 남  면   38041 ----------


 ---------- 2021-08-27 06:00:00 : 사북면   38042 ----------


 ---------- 2021-08-27 08:00:00 : 후평1동   38043 ----------


 ---------- 2021-08-27 09:00:00 : 석사동   38044 ----------


 ---------- 2021-08-27 10:00:00 : 강남동   38045 ----------


 ---------- 2021-08-27 13:00:00 : 동  면   38046 ----------


 ---------- 2021-08-27 14:00:00 : 강남동   38047 ----------


 ---------- 2021-08-27 14:00:00 : 남  면   38049 ----------


 ---------- 2021-08-27 15:00:00 : 퇴계동   38050 ----------


 ---------- 2021-08-27 18:00:00 : 후평1동   38051 ----------


 ---------- 2021-08-27 19:00:00 : 후평1동   38053 ----------


 ---------- 2021-08-27 22:00:00 : 후평1동   38055 ----------


 ---------- 2021-08-28 03:00:00 : 동내면   38056 ----------


 ---------- 2021-08-28 06:00:00 : 강남동   38057 ----------


 ---------- 2021-08-28 07:00:00 : 동  면   38058 ----------


 ---------- 2021-08-28 10:00:00 : 석사동   38059 ----------


 ---------- 2021-08-28 10:00:00 : 효자1동   38060 ----------


 ---------- 2021-08-28 12:00:00 : 석사동   38061 ----------


 ---------- 2021-08-28 12:00:00 : 효자1동   38062 ----------


 ---------- 2021-08-28 12:00:00 : 남산면   38063 ----------


 ---------- 2021-08-28 12:00:00 : 후평1동   38064 ----------


 ---------- 2021-08-28 14:00:00 : 퇴계동   38067 ----------


 ---------- 2021-08-28 15:00:00 : 신북읍   38068 ----------


 ---------- 2021-08-28 15:00:00 : 퇴계동   38069 ----------


 ---------- 2021-08-28 16:00:00 : 사북면   38070 ----------


 ---------- 2021-08-28 16:00:00 : 동내면   38071 ----------


 ---------- 2021-08-28 17:00:00 : 남산면   38074 ----------


 ---------- 2021-08-28 18:00:00 : 강남동   38075 ----------


 ---------- 2021-08-28 22:00:00 : 강남동   38077 ----------


 ---------- 2021-08-28 22:00:00 : 약사명동   38078 ----------


 ---------- 2021-08-28 22:00:00 : 동  면   38080 ----------


 ---------- 2021-08-28 22:00:00 : 조운동   38081 ----------


 ---------- 2021-08-28 23:00:00 : 효자1동   38083 ----------


 ---------- 2021-08-29 03:00:00 : 효자1동   38084 ----------


 ---------- 2021-08-29 05:00:00 : 효자1동   38085 ----------


 ---------- 2021-08-29 05:00:00 : 동산면   38088 ----------


 ---------- 2021-08-29 10:00:00 : 신사우동   38090 ----------


 ---------- 2021-08-29 10:00:00 : 동  면   38091 ----------


 ---------- 2021-08-29 11:00:00 : 동  면   38092 ----------


 ---------- 2021-08-29 13:00:00 : 효자1동   38093 ----------


 ---------- 2021-08-29 14:00:00 : 효자1동   38094 ----------


 ---------- 2021-08-29 14:00:00 : 근화동   38095 ----------


 ---------- 2021-08-29 16:00:00 : 남  면   38096 ----------


 ---------- 2021-08-29 16:00:00 : 동산면   38097 ----------


 ---------- 2021-08-29 18:00:00 : 북산면   38100 ----------


 ---------- 2021-08-29 19:00:00 : 동내면   38101 ----------


 ---------- 2021-08-29 21:00:00 : 동내면   38103 ----------


 ---------- 2021-08-30 03:00:00 : 신사우동   38104 ----------


 ---------- 2021-08-30 07:00:00 : 소양동   38105 ----------


 ---------- 2021-08-30 07:00:00 : 퇴계동   38106 ----------


 ---------- 2021-08-30 10:00:00 : 서  면   38107 ----------


 ---------- 2021-08-30 10:00:00 : 근화동   38108 ----------


 ---------- 2021-08-30 10:00:00 : 동  면   38109 ----------


 ---------- 2021-08-30 11:00:00 : 강남동   38112 ----------


 ---------- 2021-08-30 12:00:00 : 효자1동   38113 ----------


 ---------- 2021-08-30 13:00:00 : 신사우동   38114 ----------


 ---------- 2021-08-30 13:00:00 : 후평1동   38115 ----------


 ---------- 2021-08-30 14:00:00 : 강남동   38116 ----------


 ---------- 2021-08-30 16:00:00 : 석사동   38117 ----------


 ---------- 2021-08-30 16:00:00 : 남산면   38118 ----------


 ---------- 2021-08-30 17:00:00 : 서  면   38120 ----------


 ---------- 2021-08-30 17:00:00 : 근화동   38121 ----------


 ---------- 2021-08-30 19:00:00 : 강남동   38123 ----------


 ---------- 2021-08-30 20:00:00 : 효자1동   38124 ----------


 ---------- 2021-08-30 21:00:00 : 강남동   38125 ----------


 ---------- 2021-08-30 21:00:00 : 신사우동   38126 ----------


 ---------- 2021-08-31 01:00:00 : 퇴계동   38129 ----------


 ---------- 2021-08-31 09:00:00 : 신사우동   38130 ----------


 ---------- 2021-08-31 10:00:00 : 사북면   38131 ----------


 ---------- 2021-08-31 10:00:00 : 동내면   38132 ----------


 ---------- 2021-08-31 10:00:00 : 신북읍   38133 ----------


 ---------- 2021-08-31 11:00:00 : 신북읍   38134 ----------


 ---------- 2021-08-31 12:00:00 : 신사우동   38135 ----------


 ---------- 2021-08-31 12:00:00 : 신북읍   38136 ----------


 ---------- 2021-08-31 14:00:00 : 석사동   38137 ----------


 ---------- 2021-08-31 15:00:00 : 강남동   38139 ----------


 ---------- 2021-08-31 15:00:00 : 동산면   38140 ----------


 ---------- 2021-08-31 21:00:00 : 석사동   38143 ----------


 ---------- 2021-08-31 21:00:00 : 효자1동   38144 ----------


 ---------- 2021-09-01 03:00:00 : 남산면   38145 ----------


 ---------- 2021-09-01 04:00:00 : 남  면   38146 ----------


 ---------- 2021-09-01 05:00:00 : 강남동   38148 ----------


 ---------- 2021-09-01 06:00:00 : 석사동   38149 ----------

 ---------- 2021-09-01 08:00:00 : 약사명동   38150 ----------


 ---------- 2021-09-01 10:00:00 : 효자1동   38151 ----------


 ---------- 2021-09-01 11:00:00 : 남산면   38152 ----------


 ---------- 2021-09-01 13:00:00 : 남산면   38153 ----------


 ---------- 2021-09-01 14:00:00 : 석사동   38154 ----------


 ---------- 2021-09-01 14:00:00 : 남산면   38155 ----------


 ---------- 2021-09-01 14:00:00 : 소양동   38156 ----------


 ---------- 2021-09-01 15:00:00 : 강남동   38157 ----------


 ---------- 2021-09-01 15:00:00 : 효자1동   38158 ----------


 ---------- 2021-09-01 15:00:00 : 남산면   38159 ----------


 ---------- 2021-09-01 16:00:00 : 효자1동   38160 ----------


 ---------- 2021-09-01 16:00:00 : 남산면   38161 ----------


 ---------- 2021-09-01 17:00:00 : 퇴계동   38162 ----------


 ---------- 2021-09-01 18:00:00 : 동산면   38164 ----------


 ---------- 2021-09-01 19:00:00 : 소양동   38165 ----------


 ---------- 2021-09-01 22:00:00 : 석사동   38167 ----------


 ---------- 2021-09-02 02:00:00 : 동내면   38169 ----------


 ---------- 2021-09-02 07:00:00 : 신북읍   38170 ----------


 ---------- 2021-09-02 09:00:00 : 퇴계동   38171 ----------


 ---------- 2021-09-02 09:00:00 : 동산면   38175 ----------


 ---------- 2021-09-02 10:00:00 : 동내면   38176 ----------


 ---------- 2021-09-02 11:00:00 : 신동면   38177 ----------


 ---------- 2021-09-02 12:00:00 : 강남동   38178 ----------


 ---------- 2021-09-02 12:00:00 : 서  면   38179 ----------


 ---------- 2021-09-02 14:00:00 : 효자1동   38180 ----------


 ---------- 2021-09-02 15:00:00 : 동내면   38181 ----------


 ---------- 2021-09-02 15:00:00 : 효자1동   38182 ----------


 ---------- 2021-09-02 16:00:00 : 남산면   38183 ----------


 ---------- 2021-09-02 16:00:00 : 퇴계동   38184 ----------


 ---------- 2021-09-02 17:00:00 : 동내면   38185 ----------


 ---------- 2021-09-02 21:00:00 : 후평1동   38186 ----------


 ---------- 2021-09-03 02:00:00 : 퇴계동   38187 ----------


 ---------- 2021-09-03 03:00:00 : 석사동   38189 ----------


 ---------- 2021-09-03 03:00:00 : 후평1동   38190 ----------


 ---------- 2021-09-03 05:00:00 : 강남동   38192 ----------


 ---------- 2021-09-03 07:00:00 : 후평1동   38194 ----------


 ---------- 2021-09-03 07:00:00 : 북산면   38195 ----------


 ---------- 2021-09-03 09:00:00 : 효자1동   38196 ----------


 ---------- 2021-09-03 09:00:00 : 후평1동   38197 ----------


 ---------- 2021-09-03 10:00:00 : 사북면   38198 ----------


 ---------- 2021-09-03 10:00:00 : 남산면   38199 ----------


 ---------- 2021-09-03 10:00:00 : 후평1동   38200 ----------


 ---------- 2021-09-03 12:00:00 : 동  면   38201 ----------


 ---------- 2021-09-03 13:00:00 : 석사동   38203 ----------


 ---------- 2021-09-03 13:00:00 : 서  면   38204 ----------


 ---------- 2021-09-03 13:00:00 : 퇴계동   38205 ----------


 ---------- 2021-09-03 15:00:00 : 강남동   38206 ----------


 ---------- 2021-09-03 15:00:00 : 서  면   38207 ----------


 ---------- 2021-09-03 15:00:00 : 효자1동   38208 ----------


 ---------- 2021-09-03 15:00:00 : 남산면   38209 ----------


 ---------- 2021-09-03 16:00:00 : 석사동   38214 ----------


 ---------- 2021-09-03 16:00:00 : 서  면   38217 ----------


 ---------- 2021-09-03 16:00:00 : 효자1동   38218 ----------


 ---------- 2021-09-03 17:00:00 : 서  면   38219 ----------


 ---------- 2021-09-03 17:00:00 : 동내면   38220 ----------


 ---------- 2021-09-03 17:00:00 : 근화동   38221 ----------


 ---------- 2021-09-03 18:00:00 : 동산면   38222 ----------


 ---------- 2021-09-03 19:00:00 : 서  면   38223 ----------


 ---------- 2021-09-03 19:00:00 : 동  면   38224 ----------


 ---------- 2021-09-03 23:00:00 : 효자1동   38225 ----------


 ---------- 2021-09-04 05:00:00 : 동내면   38227 ----------


 ---------- 2021-09-04 06:00:00 : 서  면   38228 ----------


 ---------- 2021-09-04 06:00:00 : 후평1동   38229 ----------


 ---------- 2021-09-04 07:00:00 : 동  면   38232 ----------


 ---------- 2021-09-04 08:00:00 : 동산면   38233 ----------


 ---------- 2021-09-04 09:00:00 : 남  면   38234 ----------


 ---------- 2021-09-04 10:00:00 : 사북면   38236 ----------


 ---------- 2021-09-04 10:00:00 : 퇴계동   38237 ----------


 ---------- 2021-09-04 11:00:00 : 강남동   38238 ----------


 ---------- 2021-09-04 11:00:00 : 서  면   38239 ----------


 ---------- 2021-09-04 11:00:00 : 후평1동   38240 ----------


 ---------- 2021-09-04 12:00:00 : 신동면   38241 ----------


 ---------- 2021-09-04 12:00:00 : 동내면   38242 ----------


 ---------- 2021-09-04 13:00:00 : 석사동   38243 ----------


 ---------- 2021-09-04 15:00:00 : 동내면   38244 ----------


 ---------- 2021-09-04 15:00:00 : 남산면   38246 ----------


 ---------- 2021-09-04 16:00:00 : 남산면   38247 ----------


 ---------- 2021-09-04 16:00:00 : 신사우동   38248 ----------


 ---------- 2021-09-04 16:00:00 : 소양동   38250 ----------


 ---------- 2021-09-04 16:00:00 : 동  면   38251 ----------


 ---------- 2021-09-04 18:00:00 : 퇴계동   38252 ----------


 ---------- 2021-09-04 21:00:00 : 퇴계동   38253 ----------


 ---------- 2021-09-05 04:00:00 : 남산면   38254 ----------


 ---------- 2021-09-05 04:00:00 : 근화동   38255 ----------


 ---------- 2021-09-05 05:00:00 : 서  면   38256 ----------


 ---------- 2021-09-05 07:00:00 : 석사동   38257 ----------


 ---------- 2021-09-05 09:00:00 : 서  면   38258 ----------


 ---------- 2021-09-05 09:00:00 : 효자1동   38259 ----------


 ---------- 2021-09-05 09:00:00 : 후평1동   38260 ----------


 ---------- 2021-09-05 10:00:00 : 남  면   38261 ----------


 ---------- 2021-09-05 10:00:00 : 후평1동   38262 ----------


 ---------- 2021-09-05 11:00:00 : 동내면   38263 ----------


 ---------- 2021-09-05 11:00:00 : 동  면   38264 ----------


 ---------- 2021-09-05 11:00:00 : 후평1동   38265 ----------


 ---------- 2021-09-05 12:00:00 : 동내면   38266 ----------


 ---------- 2021-09-05 12:00:00 : 근화동   38267 ----------


 ---------- 2021-09-05 13:00:00 : 효자1동   38268 ----------


 ---------- 2021-09-05 13:00:00 : 동  면   38269 ----------


 ---------- 2021-09-05 14:00:00 : 사북면   38270 ----------


 ---------- 2021-09-05 14:00:00 : 후평1동   38271 ----------


 ---------- 2021-09-05 17:00:00 : 동내면   38272 ----------


 ---------- 2021-09-05 17:00:00 : 신사우동   38273 ----------


 ---------- 2021-09-05 22:00:00 : 강남동   38275 ----------


 ---------- 2021-09-05 23:00:00 : 강남동   38276 ----------


 ---------- 2021-09-06 04:00:00 : 남  면   38278 ----------


 ---------- 2021-09-06 08:00:00 : 퇴계동   38279 ----------


 ---------- 2021-09-06 09:00:00 : 남  면   38280 ----------


 ---------- 2021-09-06 10:00:00 : 남산면   38281 ----------


 ---------- 2021-09-06 11:00:00 : 후평1동   38282 ----------


 ---------- 2021-09-06 12:00:00 : 동  면   38283 ----------


 ---------- 2021-09-06 13:00:00 : 석사동   38284 ----------


 ---------- 2021-09-06 13:00:00 : 강남동   38285 ----------


 ---------- 2021-09-06 13:00:00 : 소양동   38286 ----------


 ---------- 2021-09-06 13:00:00 : 퇴계동   38287 ----------


 ---------- 2021-09-06 14:00:00 : 약사명동   38288 ----------


 ---------- 2021-09-06 16:00:00 : 석사동   38289 ----------


 ---------- 2021-09-06 16:00:00 : 신북읍   38290 ----------


 ---------- 2021-09-06 17:00:00 : 석사동   38292 ----------


 ---------- 2021-09-06 20:00:00 : 조운동   38293 ----------


 ---------- 2021-09-07 08:00:00 : 조운동   38294 ----------


 ---------- 2021-09-07 09:00:00 : 신사우동   38295 ----------


 ---------- 2021-09-07 13:00:00 : 후평1동   38296 ----------


 ---------- 2021-09-07 15:00:00 : 북산면   38297 ----------


 ---------- 2021-09-07 16:00:00 : 북산면   38298 ----------


 ---------- 2021-09-07 18:00:00 : 서  면   38299 ----------


 ---------- 2021-09-07 22:00:00 : 동산면   38300 ----------


 ---------- 2021-09-08 04:00:00 : 동산면   38303 ----------


 ---------- 2021-09-08 06:00:00 : 남산면   38304 ----------


 ---------- 2021-09-08 07:00:00 : 남산면   38305 ----------


 ---------- 2021-09-08 08:00:00 : 약사명동   38306 ----------


 ---------- 2021-09-08 09:00:00 : 북산면   38310 ----------


 ---------- 2021-09-08 10:00:00 : 동  면   38311 ----------


 ---------- 2021-09-08 11:00:00 : 후평1동   38312 ----------


 ---------- 2021-09-08 12:00:00 : 동내면   38313 ----------


 ---------- 2021-09-08 13:00:00 : 동내면   38314 ----------


 ---------- 2021-09-08 13:00:00 : 동  면   38315 ----------

 ---------- 2021-09-08 14:00:00 : 남산면   38317 ----------


 ---------- 2021-09-08 14:00:00 : 후평1동   38318 ----------


 ---------- 2021-09-08 14:00:00 : 동산면   38319 ----------


 ---------- 2021-09-08 16:00:00 : 동내면   38320 ----------


 ---------- 2021-09-08 16:00:00 : 동  면   38321 ----------


 ---------- 2021-09-08 17:00:00 : 강남동   38322 ----------


 ---------- 2021-09-08 17:00:00 : 서  면   38324 ----------


 ---------- 2021-09-08 20:00:00 : 동내면   38326 ----------


 ---------- 2021-09-08 21:00:00 : 후평1동   38327 ----------


 ---------- 2021-09-09 07:00:00 : 후평1동   38328 ----------


 ---------- 2021-09-09 08:00:00 : 북산면   38330 ----------


 ---------- 2021-09-09 09:00:00 : 동  면   38331 ----------


 ---------- 2021-09-09 09:00:00 : 후평1동   38332 ----------


 ---------- 2021-09-09 09:00:00 : 북산면   38333 ----------


 ---------- 2021-09-09 10:00:00 : 동내면   38334 ----------


 ---------- 2021-09-09 10:00:00 : 동  면   38335 ----------


 ---------- 2021-09-09 10:00:00 : 북산면   38336 ----------


 ---------- 2021-09-09 11:00:00 : 신북읍   38337 ----------


 ---------- 2021-09-09 12:00:00 : 교  동   38338 ----------


 ---------- 2021-09-09 13:00:00 : 동내면   38339 ----------


 ---------- 2021-09-09 13:00:00 : 효자1동   38340 ----------


 ---------- 2021-09-09 14:00:00 : 석사동   38341 ----------


 ---------- 2021-09-09 16:00:00 : 서  면   38343 ----------


 ---------- 2021-09-09 16:00:00 : 퇴계동   38344 ----------


 ---------- 2021-09-09 17:00:00 : 동내면   38345 ----------


 ---------- 2021-09-09 18:00:00 : 약사명동   38346 ----------


 ---------- 2021-09-10 00:00:00 : 퇴계동   38347 ----------


 ---------- 2021-09-10 01:00:00 : 퇴계동   38348 ----------


 ---------- 2021-09-10 03:00:00 : 사북면   38349 ----------


 ---------- 2021-09-10 09:00:00 : 동  면   38350 ----------


 ---------- 2021-09-10 09:00:00 : 퇴계동   38351 ----------


 ---------- 2021-09-10 10:00:00 : 신사우동   38352 ----------


 ---------- 2021-09-10 11:00:00 : 석사동   38354 ----------


 ---------- 2021-09-10 11:00:00 : 효자1동   38355 ----------


 ---------- 2021-09-10 12:00:00 : 근화동   38356 ----------


 ---------- 2021-09-10 13:00:00 : 동내면   38357 ----------


 ---------- 2021-09-10 13:00:00 : 효자1동   38358 ----------


 ---------- 2021-09-10 13:00:00 : 교  동   38359 ----------


 ---------- 2021-09-10 14:00:00 : 석사동   38360 ----------


 ---------- 2021-09-10 14:00:00 : 서  면   38361 ----------


 ---------- 2021-09-10 15:00:00 : 동내면   38362 ----------


 ---------- 2021-09-10 15:00:00 : 신사우동   38363 ----------


 ---------- 2021-09-10 15:00:00 : 후평1동   38364 ----------


 ---------- 2021-09-10 16:00:00 : 퇴계동   38365 ----------


 ---------- 2021-09-10 17:00:00 : 조운동   38366 ----------


 ---------- 2021-09-10 18:00:00 : 동  면   38367 ----------


 ---------- 2021-09-10 18:00:00 : 퇴계동   38368 ----------


 ---------- 2021-09-10 19:00:00 : 강남동   38369 ----------


 ---------- 2021-09-10 20:00:00 : 후평1동   38370 ----------


 ---------- 2021-09-10 22:00:00 : 신북읍   38372 ----------


 ---------- 2021-09-11 09:00:00 : 남  면   38373 ----------


 ---------- 2021-09-11 09:00:00 : 동내면   38374 ----------


 ---------- 2021-09-11 09:00:00 : 효자1동   38375 ----------


 ---------- 2021-09-11 10:00:00 : 강남동   38376 ----------


 ---------- 2021-09-11 10:00:00 : 남산면   38377 ----------


 ---------- 2021-09-11 10:00:00 : 신사우동   38378 ----------


 ---------- 2021-09-11 10:00:00 : 신북읍   38379 ----------


 ---------- 2021-09-11 10:00:00 : 퇴계동   38380 ----------


 ---------- 2021-09-11 11:00:00 : 석사동   38381 ----------


 ---------- 2021-09-11 11:00:00 : 효자1동   38382 ----------


 ---------- 2021-09-11 11:00:00 : 신사우동   38383 ----------


 ---------- 2021-09-11 11:00:00 : 퇴계동   38384 ----------


 ---------- 2021-09-11 12:00:00 : 남산면   38385 ----------


 ---------- 2021-09-11 12:00:00 : 퇴계동   38386 ----------


 ---------- 2021-09-11 12:00:00 : 동산면   38387 ----------


 ---------- 2021-09-11 15:00:00 : 서  면   38388 ----------


 ---------- 2021-09-11 16:00:00 : 강남동   38389 ----------


 ---------- 2021-09-11 16:00:00 : 남  면   38390 ----------


 ---------- 2021-09-11 17:00:00 : 석사동   38391 ----------


 ---------- 2021-09-11 18:00:00 : 강남동   38392 ----------


 ---------- 2021-09-11 23:00:00 : 강남동   38393 ----------


 ---------- 2021-09-12 00:00:00 : 석사동   38394 ----------


 ---------- 2021-09-12 00:00:00 : 강남동   38396 ----------


 ---------- 2021-09-12 09:00:00 : 효자1동   38397 ----------


 ---------- 2021-09-12 09:00:00 : 신북읍   38398 ----------


 ---------- 2021-09-12 10:00:00 : 강남동   38399 ----------


 ---------- 2021-09-12 10:00:00 : 신북읍   38400 ----------


 ---------- 2021-09-12 10:00:00 : 후평1동   38401 ----------


 ---------- 2021-09-12 11:00:00 : 신동면   38402 ----------


 ---------- 2021-09-12 11:00:00 : 동내면   38405 ----------


 ---------- 2021-09-12 13:00:00 : 신동면   38406 ----------


 ---------- 2021-09-12 13:00:00 : 동내면   38407 ----------


 ---------- 2021-09-12 14:00:00 : 후평1동   38408 ----------


 ---------- 2021-09-12 17:00:00 : 강남동   38409 ----------


 ---------- 2021-09-12 18:00:00 : 동내면   38411 ----------


 ---------- 2021-09-12 18:00:00 : 동  면   38413 ----------


 ---------- 2021-09-12 21:00:00 : 퇴계동   38414 ----------


 ---------- 2021-09-13 00:00:00 : 동산면   38415 ----------


 ---------- 2021-09-13 07:00:00 : 신북읍   38416 ----------


 ---------- 2021-09-13 08:00:00 : 강남동   38418 ----------


 ---------- 2021-09-13 09:00:00 : 서  면   38419 ----------


 ---------- 2021-09-13 09:00:00 : 퇴계동   38420 ----------


 ---------- 2021-09-13 10:00:00 : 강남동   38421 ----------


 ---------- 2021-09-13 10:00:00 : 남  면   38422 ----------


 ---------- 2021-09-13 10:00:00 : 동내면   38423 ----------


 ---------- 2021-09-13 10:00:00 : 효자1동   38425 ----------


 ---------- 2021-09-13 10:00:00 : 동  면   38426 ----------


 ---------- 2021-09-13 11:00:00 : 서  면   38427 ----------


 ---------- 2021-09-13 11:00:00 : 퇴계동   38428 ----------


 ---------- 2021-09-13 12:00:00 : 동내면   38429 ----------


 ---------- 2021-09-13 12:00:00 : 남산면   38430 ----------


 ---------- 2021-09-13 14:00:00 : 신북읍   38431 ----------


 ---------- 2021-09-13 15:00:00 : 강남동   38432 ----------


 ---------- 2021-09-13 15:00:00 : 조운동   38433 ----------


 ---------- 2021-09-13 16:00:00 : 동내면   38434 ----------


 ---------- 2021-09-13 17:00:00 : 퇴계동   38435 ----------


 ---------- 2021-09-13 22:00:00 : 강남동   38438 ----------


 ---------- 2021-09-14 09:00:00 : 동내면   38439 ----------


 ---------- 2021-09-14 09:00:00 : 신북읍   38440 ----------


 ---------- 2021-09-14 10:00:00 : 동내면   38441 ----------


 ---------- 2021-09-14 11:00:00 : 동  면   38445 ----------


 ---------- 2021-09-14 12:00:00 : 신북읍   38446 ----------


 ---------- 2021-09-14 12:00:00 : 후평1동   38447 ----------


 ---------- 2021-09-14 13:00:00 : 석사동   38448 ----------


 ---------- 2021-09-14 13:00:00 : 신북읍   38449 ----------


 ---------- 2021-09-14 13:00:00 : 후평1동   38450 ----------


 ---------- 2021-09-14 14:00:00 : 북산면   38451 ----------


 ---------- 2021-09-14 15:00:00 : 석사동   38452 ----------


 ---------- 2021-09-14 15:00:00 : 강남동   38453 ----------


 ---------- 2021-09-14 16:00:00 : 강남동   38455 ----------


 ---------- 2021-09-14 16:00:00 : 남산면   38456 ----------


 ---------- 2021-09-14 16:00:00 : 동  면   38457 ----------


 ---------- 2021-09-14 16:00:00 : 퇴계동   38458 ----------


 ---------- 2021-09-14 17:00:00 : 서  면   38459 ----------


 ---------- 2021-09-14 17:00:00 : 효자1동   38462 ----------


 ---------- 2021-09-14 18:00:00 : 동  면   38463 ----------


 ---------- 2021-09-14 22:00:00 : 효자1동   38464 ----------


 ---------- 2021-09-15 00:00:00 : 강남동   38465 ----------


 ---------- 2021-09-15 01:00:00 : 소양동   38466 ----------


 ---------- 2021-09-15 05:00:00 : 소양동   38467 ----------


 ---------- 2021-09-15 08:00:00 : 강남동   38468 ----------


 ---------- 2021-09-15 09:00:00 : 신사우동   38469 ----------


 ---------- 2021-09-15 09:00:00 : 후평1동   38470 ----------


 ---------- 2021-09-15 11:00:00 : 신동면   38474 ----------


 ---------- 2021-09-15 11:00:00 : 남  면   38475 ----------


 ---------- 2021-09-15 11:00:00 : 신사우동   38478 ----------


 ---------- 2021-09-15 11:00:00 : 신북읍   38479 ----------


 ---------- 2021-09-15 11:00:00 : 후평1동   38480 ----------

 ---------- 2021-09-15 11:00:00 : 퇴계동   38483 ----------


 ---------- 2021-09-15 12:00:00 : 남산면   38484 ----------


 ---------- 2021-09-15 12:00:00 : 약사명동   38485 ----------


 ---------- 2021-09-15 13:00:00 : 서  면   38486 ----------


 ---------- 2021-09-15 13:00:00 : 퇴계동   38487 ----------


 ---------- 2021-09-15 14:00:00 : 강남동   38489 ----------


 ---------- 2021-09-15 15:00:00 : 신북읍   38490 ----------


 ---------- 2021-09-15 17:00:00 : 서  면   38491 ----------


 ---------- 2021-09-16 00:00:00 : 근화동   38492 ----------


 ---------- 2021-09-16 08:00:00 : 강남동   38493 ----------


 ---------- 2021-09-16 09:00:00 : 서  면   38494 ----------


 ---------- 2021-09-16 09:00:00 : 동  면   38495 ----------


 ---------- 2021-09-16 10:00:00 : 신북읍   38497 ----------


 ---------- 2021-09-16 11:00:00 : 동내면   38498 ----------


 ---------- 2021-09-16 11:00:00 : 퇴계동   38500 ----------


 ---------- 2021-09-16 12:00:00 : 효자1동   38501 ----------


 ---------- 2021-09-16 13:00:00 : 강남동   38502 ----------


 ---------- 2021-09-16 14:00:00 : 효자1동   38503 ----------


 ---------- 2021-09-16 14:00:00 : 남산면   38504 ----------


 ---------- 2021-09-16 16:00:00 : 동내면   38505 ----------


 ---------- 2021-09-16 16:00:00 : 남산면   38507 ----------


 ---------- 2021-09-16 17:00:00 : 강남동   38508 ----------


 ---------- 2021-09-16 17:00:00 : 남산면   38509 ----------


 ---------- 2021-09-16 19:00:00 : 동산면   38510 ----------


 ---------- 2021-09-16 20:00:00 : 석사동   38511 ----------


 ---------- 2021-09-16 21:00:00 : 동  면   38512 ----------


 ---------- 2021-09-17 01:00:00 : 석사동   38513 ----------


 ---------- 2021-09-17 06:00:00 : 동  면   38514 ----------


 ---------- 2021-09-17 09:00:00 : 석사동   38515 ----------


 ---------- 2021-09-17 09:00:00 : 효자1동   38516 ----------


 ---------- 2021-09-17 14:00:00 : 동  면   38519 ----------


 ---------- 2021-09-17 15:00:00 : 서  면   38521 ----------


 ---------- 2021-09-17 15:00:00 : 남산면   38522 ----------


 ---------- 2021-09-17 15:00:00 : 신사우동   38524 ----------


 ---------- 2021-09-17 16:00:00 : 동  면   38525 ----------


 ---------- 2021-09-17 17:00:00 : 서  면   38527 ----------


 ---------- 2021-09-17 17:00:00 : 남산면   38528 ----------


 ---------- 2021-09-17 17:00:00 : 소양동   38529 ----------


 ---------- 2021-09-17 17:00:00 : 후평1동   38530 ----------


 ---------- 2021-09-18 09:00:00 : 동내면   38531 ----------


 ---------- 2021-09-18 11:00:00 : 효자1동   38532 ----------


 ---------- 2021-09-18 12:00:00 : 동  면   38533 ----------


 ---------- 2021-09-18 12:00:00 : 조운동   38534 ----------


 ---------- 2021-09-18 13:00:00 : 효자1동   38535 ----------


 ---------- 2021-09-18 15:00:00 : 신사우동   38536 ----------


 ---------- 2021-09-18 16:00:00 : 사북면   38537 ----------


 ---------- 2021-09-18 17:00:00 : 신사우동   38538 ----------


 ---------- 2021-09-18 19:00:00 : 동  면   38539 ----------


 ---------- 2021-09-19 08:00:00 : 강남동   38540 ----------


 ---------- 2021-09-19 14:00:00 : 신사우동   38541 ----------


 ---------- 2021-09-19 14:00:00 : 약사명동   38542 ----------


 ---------- 2021-09-19 15:00:00 : 사북면   38544 ----------


 ---------- 2021-09-19 16:00:00 : 강남동   38547 ----------


 ---------- 2021-09-19 16:00:00 : 서  면   38548 ----------


 ---------- 2021-09-19 16:00:00 : 효자1동   38549 ----------


 ---------- 2021-09-19 19:00:00 : 신동면   38553 ----------


 ---------- 2021-09-19 19:00:00 : 동내면   38554 ----------


 ---------- 2021-09-19 21:00:00 : 서  면   38555 ----------


 ---------- 2021-09-19 21:00:00 : 효자1동   38556 ----------


 ---------- 2021-09-19 23:00:00 : 신사우동   38557 ----------


 ---------- 2021-09-20 00:00:00 : 신사우동   38558 ----------


 ---------- 2021-09-20 08:00:00 : 강남동   38560 ----------


 ---------- 2021-09-20 08:00:00 : 동  면   38561 ----------


 ---------- 2021-09-20 10:00:00 : 서  면   38562 ----------


 ---------- 2021-09-20 10:00:00 : 동내면   38563 ----------


 ---------- 2021-09-20 12:00:00 : 동  면   38564 ----------


 ---------- 2021-09-20 14:00:00 : 동내면   38565 ----------


 ---------- 2021-09-20 17:00:00 : 신사우동   38566 ----------


 ---------- 2021-09-20 17:00:00 : 신북읍   38567 ----------


 ---------- 2021-09-21 00:00:00 : 북산면   38568 ----------


 ---------- 2021-09-21 02:00:00 : 후평1동   38569 ----------


 ---------- 2021-09-21 06:00:00 : 신사우동   38571 ----------


 ---------- 2021-09-21 06:00:00 : 동산면   38572 ----------


 ---------- 2021-09-21 09:00:00 : 신사우동   38573 ----------


 ---------- 2021-09-21 09:00:00 : 퇴계동   38574 ----------


 ---------- 2021-09-21 10:00:00 : 후평1동   38575 ----------


 ---------- 2021-09-21 11:00:00 : 강남동   38576 ----------


 ---------- 2021-09-21 11:00:00 : 신북읍   38578 ----------


 ---------- 2021-09-21 11:00:00 : 동  면   38579 ----------


 ---------- 2021-09-21 13:00:00 : 강남동   38580 ----------


 ---------- 2021-09-21 13:00:00 : 동내면   38582 ----------


 ---------- 2021-09-21 13:00:00 : 동  면   38583 ----------


 ---------- 2021-09-21 15:00:00 : 동내면   38585 ----------


 ---------- 2021-09-21 15:00:00 : 동  면   38586 ----------


 ---------- 2021-09-22 02:00:00 : 퇴계동   38587 ----------


 ---------- 2021-09-22 06:00:00 : 신동면   38589 ----------


 ---------- 2021-09-22 10:00:00 : 신북읍   38590 ----------


 ---------- 2021-09-22 11:00:00 : 효자1동   38591 ----------


 ---------- 2021-09-22 14:00:00 : 퇴계동   38592 ----------


 ---------- 2021-09-22 15:00:00 : 사북면   38594 ----------


 ---------- 2021-09-22 17:00:00 : 강남동   38595 ----------


 ---------- 2021-09-23 05:00:00 : 석사동   38596 ----------


 ---------- 2021-09-23 09:00:00 : 신사우동   38597 ----------


 ---------- 2021-09-23 09:00:00 : 동  면   38598 ----------


 ---------- 2021-09-23 09:00:00 : 퇴계동   38599 ----------


 ---------- 2021-09-23 10:00:00 : 퇴계동   38600 ----------


 ---------- 2021-09-23 12:00:00 : 효자1동   38601 ----------


 ---------- 2021-09-23 12:00:00 : 신사우동   38602 ----------


 ---------- 2021-09-23 14:00:00 : 효자1동   38603 ----------


 ---------- 2021-09-23 17:00:00 : 강남동   38604 ----------


 ---------- 2021-09-23 17:00:00 : 신북읍   38605 ----------


 ---------- 2021-09-23 18:00:00 : 후평1동   38606 ----------


 ---------- 2021-09-23 20:00:00 : 동  면   38607 ----------


 ---------- 2021-09-24 08:00:00 : 퇴계동   38608 ----------


 ---------- 2021-09-24 10:00:00 : 효자1동   38610 ----------


 ---------- 2021-09-24 10:00:00 : 동  면   38611 ----------


 ---------- 2021-09-24 11:00:00 : 소양동   38613 ----------


 ---------- 2021-09-24 13:00:00 : 석사동   38615 ----------


 ---------- 2021-09-24 13:00:00 : 남산면   38616 ----------


 ---------- 2021-09-24 14:00:00 : 동내면   38617 ----------


 ---------- 2021-09-24 14:00:00 : 소양동   38618 ----------


 ---------- 2021-09-24 15:00:00 : 석사동   38619 ----------


 ---------- 2021-09-24 15:00:00 : 동내면   38622 ----------


 ---------- 2021-09-24 15:00:00 : 소양동   38624 ----------


 ---------- 2021-09-24 16:00:00 : 사북면   38625 ----------


 ---------- 2021-09-24 16:00:00 : 동내면   38626 ----------


 ---------- 2021-09-24 17:00:00 : 서  면   38627 ----------


 ---------- 2021-09-24 18:00:00 : 퇴계동   38628 ----------


 ---------- 2021-09-24 23:00:00 : 소양동   38629 ----------


 ---------- 2021-09-25 11:00:00 : 신북읍   38630 ----------


 ---------- 2021-09-25 12:00:00 : 서  면   38631 ----------


 ---------- 2021-09-25 13:00:00 : 신사우동   38632 ----------


 ---------- 2021-09-25 15:00:00 : 석사동   38633 ----------


 ---------- 2021-09-25 15:00:00 : 동내면   38634 ----------


 ---------- 2021-09-25 15:00:00 : 북산면   38635 ----------


 ---------- 2021-09-25 16:00:00 : 동내면   38636 ----------


 ---------- 2021-09-25 16:00:00 : 퇴계동   38638 ----------


 ---------- 2021-09-25 17:00:00 : 동내면   38641 ----------


 ---------- 2021-09-25 19:00:00 : 퇴계동   38643 ----------


 ---------- 2021-09-25 22:00:00 : 강남동   38644 ----------


 ---------- 2021-09-25 23:00:00 : 효자1동   38646 ----------


 ---------- 2021-09-26 01:00:00 : 북산면   38647 ----------


 ---------- 2021-09-26 04:00:00 : 후평1동   38648 ----------


 ---------- 2021-09-26 05:00:00 : 강남동   38649 ----------


 ---------- 2021-09-26 10:00:00 : 석사동   38650 ----------


 ---------- 2021-09-26 10:00:00 : 서  면   38651 ----------

 ---------- 2021-09-26 10:00:00 : 북산면   38652 ----------


 ---------- 2021-09-26 11:00:00 : 신사우동   38653 ----------


 ---------- 2021-09-26 12:00:00 : 동내면   38654 ----------


 ---------- 2021-09-26 12:00:00 : 퇴계동   38655 ----------


 ---------- 2021-09-26 13:00:00 : 석사동   38656 ----------


 ---------- 2021-09-26 15:00:00 : 석사동   38657 ----------


 ---------- 2021-09-26 16:00:00 : 북산면   38660 ----------


 ---------- 2021-09-26 17:00:00 : 근화동   38661 ----------


 ---------- 2021-09-26 17:00:00 : 신북읍   38662 ----------


 ---------- 2021-09-26 17:00:00 : 북산면   38663 ----------


 ---------- 2021-09-26 18:00:00 : 신사우동   38664 ----------


 ---------- 2021-09-26 18:00:00 : 후평1동   38665 ----------


 ---------- 2021-09-26 20:00:00 : 퇴계동   38666 ----------


 ---------- 2021-09-27 07:00:00 : 동내면   38668 ----------


 ---------- 2021-09-27 08:00:00 : 석사동   38669 ----------


 ---------- 2021-09-27 08:00:00 : 강남동   38670 ----------


 ---------- 2021-09-27 09:00:00 : 약사명동   38671 ----------


 ---------- 2021-09-27 10:00:00 : 석사동   38672 ----------


 ---------- 2021-09-27 10:00:00 : 신북읍   38673 ----------


 ---------- 2021-09-27 11:00:00 : 교  동   38674 ----------


 ---------- 2021-09-27 15:00:00 : 강남동   38675 ----------


 ---------- 2021-09-27 15:00:00 : 신북읍   38676 ----------


 ---------- 2021-09-27 16:00:00 : 강남동   38677 ----------


 ---------- 2021-09-27 16:00:00 : 동산면   38678 ----------


 ---------- 2021-09-27 20:00:00 : 남산면   38679 ----------


 ---------- 2021-09-27 20:00:00 : 동  면   38681 ----------


 ---------- 2021-09-27 20:00:00 : 퇴계동   38682 ----------


 ---------- 2021-09-28 04:00:00 : 퇴계동   38683 ----------


 ---------- 2021-09-28 07:00:00 : 남산면   38684 ----------


 ---------- 2021-09-28 10:00:00 : 신북읍   38686 ----------


 ---------- 2021-09-28 12:00:00 : 신동면   38687 ----------


 ---------- 2021-09-28 13:00:00 : 소양동   38688 ----------


 ---------- 2021-09-28 15:00:00 : 신동면   38689 ----------


 ---------- 2021-09-28 15:00:00 : 서  면   38691 ----------


 ---------- 2021-09-28 15:00:00 : 퇴계동   38693 ----------


 ---------- 2021-09-28 16:00:00 : 동내면   38694 ----------


 ---------- 2021-09-28 16:00:00 : 신북읍   38695 ----------


 ---------- 2021-09-28 16:00:00 : 약사명동   38696 ----------


 ---------- 2021-09-28 18:00:00 : 강남동   38697 ----------


 ---------- 2021-09-28 20:00:00 : 동산면   38698 ----------


 ---------- 2021-09-29 05:00:00 : 효자1동   38699 ----------


 ---------- 2021-09-29 09:00:00 : 후평1동   38700 ----------


 ---------- 2021-09-29 11:00:00 : 강남동   38701 ----------


 ---------- 2021-09-29 19:00:00 : 신사우동   38702 ----------


 ---------- 2021-09-29 23:00:00 : 석사동   38703 ----------


 ---------- 2021-09-30 02:00:00 : 효자1동   38704 ----------


 ---------- 2021-09-30 04:00:00 : 조운동   38705 ----------


 ---------- 2021-09-30 11:00:00 : 동내면   38706 ----------


 ---------- 2021-09-30 13:00:00 : 퇴계동   38707 ----------


 ---------- 2021-09-30 14:00:00 : 동내면   38708 ----------


 ---------- 2021-09-30 14:00:00 : 퇴계동   38709 ----------


 ---------- 2021-09-30 15:00:00 : 남산면   38710 ----------


 ---------- 2021-09-30 17:00:00 : 동산면   38712 ----------


 ---------- 2021-09-30 19:00:00 : 근화동   38713 ----------


 ---------- 2021-09-30 20:00:00 : 신사우동   38714 ----------


 ---------- 2021-09-30 21:00:00 : 근화동   38715 ----------


 ---------- 2021-09-30 22:00:00 : 북산면   38716 ----------


 ---------- 2021-10-01 01:00:00 : 신동면   38717 ----------


 ---------- 2021-10-01 03:00:00 : 소양동   38718 ----------


 ---------- 2021-10-01 05:00:00 : 소양동   38719 ----------


 ---------- 2021-10-01 10:00:00 : 남  면   38720 ----------


 ---------- 2021-10-01 10:00:00 : 소양동   38721 ----------


 ---------- 2021-10-01 12:00:00 : 동산면   38724 ----------


 ---------- 2021-10-01 12:00:00 : 교  동   38725 ----------


 ---------- 2021-10-01 13:00:00 : 강남동   38726 ----------


 ---------- 2021-10-01 14:00:00 : 사북면   38727 ----------


 ---------- 2021-10-01 14:00:00 : 후평1동   38728 ----------


 ---------- 2021-10-01 15:00:00 : 신사우동   38729 ----------


 ---------- 2021-10-01 15:00:00 : 동  면   38730 ----------


 ---------- 2021-10-01 17:00:00 : 석사동   38731 ----------


 ---------- 2021-10-01 17:00:00 : 남  면   38732 ----------


 ---------- 2021-10-01 17:00:00 : 신북읍   38733 ----------


 ---------- 2021-10-01 17:00:00 : 후평1동   38734 ----------


 ---------- 2021-10-01 17:00:00 : 동산면   38735 ----------


 ---------- 2021-10-01 18:00:00 : 석사동   38738 ----------


 ---------- 2021-10-01 18:00:00 : 신사우동   38739 ----------


 ---------- 2021-10-01 20:00:00 : 효자1동   38740 ----------


 ---------- 2021-10-01 22:00:00 : 석사동   38741 ----------


 ---------- 2021-10-02 01:00:00 : 동산면   38742 ----------


 ---------- 2021-10-02 09:00:00 : 석사동   38743 ----------


 ---------- 2021-10-02 09:00:00 : 동  면   38744 ----------


 ---------- 2021-10-02 10:00:00 : 퇴계동   38745 ----------


 ---------- 2021-10-02 11:00:00 : 효자1동   38746 ----------


 ---------- 2021-10-02 15:00:00 : 서  면   38748 ----------


 ---------- 2021-10-02 16:00:00 : 강남동   38749 ----------


 ---------- 2021-10-02 17:00:00 : 퇴계동   38751 ----------


 ---------- 2021-10-02 19:00:00 : 효자1동   38752 ----------


 ---------- 2021-10-02 21:00:00 : 동내면   38753 ----------


 ---------- 2021-10-03 05:00:00 : 퇴계동   38755 ----------


 ---------- 2021-10-03 10:00:00 : 강남동   38757 ----------


 ---------- 2021-10-03 12:00:00 : 강남동   38759 ----------


 ---------- 2021-10-03 13:00:00 : 신사우동   38760 ----------


 ---------- 2021-10-03 13:00:00 : 퇴계동   38761 ----------


 ---------- 2021-10-03 14:00:00 : 신사우동   38762 ----------


 ---------- 2021-10-03 15:00:00 : 퇴계동   38763 ----------


 ---------- 2021-10-04 06:00:00 : 석사동   38764 ----------


 ---------- 2021-10-04 07:00:00 : 동내면   38765 ----------


 ---------- 2021-10-04 09:00:00 : 효자1동   38766 ----------


 ---------- 2021-10-04 09:00:00 : 신북읍   38767 ----------


 ---------- 2021-10-04 11:00:00 : 근화동   38768 ----------


 ---------- 2021-10-04 11:00:00 : 동  면   38769 ----------


 ---------- 2021-10-04 15:00:00 : 남산면   38770 ----------


 ---------- 2021-10-04 17:00:00 : 신사우동   38771 ----------


 ---------- 2021-10-04 21:00:00 : 남산면   38773 ----------


 ---------- 2021-10-05 02:00:00 : 후평1동   38774 ----------


 ---------- 2021-10-05 03:00:00 : 석사동   38775 ----------


 ---------- 2021-10-05 04:00:00 : 강남동   38776 ----------


 ---------- 2021-10-05 10:00:00 : 서  면   38777 ----------


 ---------- 2021-10-05 10:00:00 : 효자1동   38779 ----------


 ---------- 2021-10-05 10:00:00 : 신북읍   38780 ----------


 ---------- 2021-10-05 13:00:00 : 신북읍   38781 ----------


 ---------- 2021-10-05 14:00:00 : 동  면   38782 ----------


 ---------- 2021-10-05 14:00:00 : 후평1동   38783 ----------


 ---------- 2021-10-05 14:00:00 : 퇴계동   38784 ----------


 ---------- 2021-10-05 15:00:00 : 효자1동   38785 ----------


 ---------- 2021-10-05 15:00:00 : 신사우동   38786 ----------


 ---------- 2021-10-05 15:00:00 : 후평1동   38789 ----------


 ---------- 2021-10-05 18:00:00 : 교  동   38790 ----------


 ---------- 2021-10-05 19:00:00 : 동  면   38791 ----------


 ---------- 2021-10-05 20:00:00 : 퇴계동   38792 ----------


 ---------- 2021-10-06 01:00:00 : 동  면   38793 ----------


 ---------- 2021-10-06 08:00:00 : 신북읍   38794 ----------


 ---------- 2021-10-06 11:00:00 : 강남동   38796 ----------


 ---------- 2021-10-06 11:00:00 : 남  면   38797 ----------


 ---------- 2021-10-06 13:00:00 : 강남동   38798 ----------


 ---------- 2021-10-06 13:00:00 : 동  면   38799 ----------


 ---------- 2021-10-06 14:00:00 : 동  면   38800 ----------


 ---------- 2021-10-06 16:00:00 : 남  면   38801 ----------


 ---------- 2021-10-06 16:00:00 : 동  면   38802 ----------


 ---------- 2021-10-06 22:00:00 : 소양동   38803 ----------


 ---------- 2021-10-06 22:00:00 : 퇴계동   38806 ----------


 ---------- 2021-10-06 23:00:00 : 석사동   38807 ----------


 ---------- 2021-10-07 05:00:00 : 퇴계동   38809 ----------


 ---------- 2021-10-07 08:00:00 : 동내면   38810 ----------


 ---------- 2021-10-07 10:00:00 : 신사우동   38812 ----------


 ---------- 2021-10-07 11:00:00 : 사북면   38813 ----------

 ---------- 2021-10-07 16:00:00 : 퇴계동   38814 ----------


 ---------- 2021-10-07 18:00:00 : 동내면   38815 ----------


 ---------- 2021-10-07 18:00:00 : 퇴계동   38817 ----------


 ---------- 2021-10-07 23:00:00 : 남산면   38818 ----------


 ---------- 2021-10-08 01:00:00 : 동내면   38819 ----------


 ---------- 2021-10-08 09:00:00 : 사북면   38820 ----------


 ---------- 2021-10-08 09:00:00 : 남산면   38821 ----------


 ---------- 2021-10-08 10:00:00 : 동  면   38822 ----------


 ---------- 2021-10-08 13:00:00 : 신북읍   38823 ----------


 ---------- 2021-10-08 14:00:00 : 북산면   38824 ----------


 ---------- 2021-10-09 10:00:00 : 서  면   38826 ----------


 ---------- 2021-10-09 11:00:00 : 강남동   38827 ----------


 ---------- 2021-10-09 11:00:00 : 퇴계동   38828 ----------


 ---------- 2021-10-09 12:00:00 : 동내면   38829 ----------


 ---------- 2021-10-09 14:00:00 : 사북면   38830 ----------


 ---------- 2021-10-09 15:00:00 : 서  면   38831 ----------


 ---------- 2021-10-09 15:00:00 : 남  면   38833 ----------


 ---------- 2021-10-09 18:00:00 : 동  면   38835 ----------


 ---------- 2021-10-09 19:00:00 : 신사우동   38836 ----------


 ---------- 2021-10-09 23:00:00 : 신북읍   38837 ----------


 ---------- 2021-10-10 00:00:00 : 후평1동   38838 ----------


 ---------- 2021-10-10 03:00:00 : 강남동   38839 ----------


 ---------- 2021-10-10 08:00:00 : 신북읍   38840 ----------


 ---------- 2021-10-10 10:00:00 : 신북읍   38841 ----------


 ---------- 2021-10-10 10:00:00 : 후평1동   38842 ----------


 ---------- 2021-10-10 16:00:00 : 후평1동   38843 ----------


 ---------- 2021-10-10 17:00:00 : 퇴계동   38844 ----------


 ---------- 2021-10-10 19:00:00 : 후평1동   38845 ----------


 ---------- 2021-10-10 20:00:00 : 후평1동   38846 ----------


 ---------- 2021-10-11 02:00:00 : 퇴계동   38847 ----------


 ---------- 2021-10-11 03:00:00 : 신북읍   38848 ----------


 ---------- 2021-10-11 10:00:00 : 신동면   38849 ----------


 ---------- 2021-10-11 10:00:00 : 강남동   38850 ----------


 ---------- 2021-10-11 10:00:00 : 서  면   38851 ----------


 ---------- 2021-10-11 10:00:00 : 동산면   38852 ----------


 ---------- 2021-10-11 11:00:00 : 신사우동   38853 ----------


 ---------- 2021-10-11 12:00:00 : 소양동   38854 ----------


 ---------- 2021-10-11 15:00:00 : 남산면   38856 ----------


 ---------- 2021-10-11 17:00:00 : 석사동   38858 ----------


 ---------- 2021-10-11 21:00:00 : 후평1동   38859 ----------


 ---------- 2021-10-12 00:00:00 : 후평1동   38860 ----------


 ---------- 2021-10-12 06:00:00 : 소양동   38861 ----------


 ---------- 2021-10-12 08:00:00 : 동  면   38863 ----------


 ---------- 2021-10-12 09:00:00 : 소양동   38864 ----------


 ---------- 2021-10-12 10:00:00 : 동내면   38865 ----------


 ---------- 2021-10-12 11:00:00 : 강남동   38866 ----------


 ---------- 2021-10-12 11:00:00 : 동내면   38867 ----------


 ---------- 2021-10-12 12:00:00 : 석사동   38869 ----------


 ---------- 2021-10-12 12:00:00 : 동내면   38870 ----------


 ---------- 2021-10-12 14:00:00 : 퇴계동   38873 ----------


 ---------- 2021-10-12 14:00:00 : 동산면   38876 ----------


 ---------- 2021-10-12 15:00:00 : 강남동   38878 ----------


 ---------- 2021-10-12 16:00:00 : 효자1동   38879 ----------


 ---------- 2021-10-12 20:00:00 : 석사동   38880 ----------


 ---------- 2021-10-13 02:00:00 : 강남동   38882 ----------


 ---------- 2021-10-13 02:00:00 : 퇴계동   38883 ----------


 ---------- 2021-10-13 05:00:00 : 후평1동   38884 ----------


 ---------- 2021-10-13 07:00:00 : 근화동   38885 ----------


 ---------- 2021-10-13 07:00:00 : 약사명동   38886 ----------


 ---------- 2021-10-13 11:00:00 : 동내면   38887 ----------


 ---------- 2021-10-13 11:00:00 : 조운동   38888 ----------


 ---------- 2021-10-13 12:00:00 : 신북읍   38889 ----------


 ---------- 2021-10-13 13:00:00 : 서  면   38890 ----------


 ---------- 2021-10-13 13:00:00 : 동내면   38892 ----------


 ---------- 2021-10-13 14:00:00 : 서  면   38893 ----------


 ---------- 2021-10-13 14:00:00 : 동내면   38894 ----------


 ---------- 2021-10-13 14:00:00 : 신북읍   38895 ----------


 ---------- 2021-10-13 15:00:00 : 동내면   38896 ----------


 ---------- 2021-10-13 16:00:00 : 서  면   38897 ----------


 ---------- 2021-10-13 19:00:00 : 강남동   38898 ----------


 ---------- 2021-10-13 21:00:00 : 강남동   38899 ----------


 ---------- 2021-10-14 05:00:00 : 서  면   38902 ----------


 ---------- 2021-10-14 06:00:00 : 남산면   38903 ----------


 ---------- 2021-10-14 07:00:00 : 석사동   38904 ----------


 ---------- 2021-10-14 10:00:00 : 석사동   38905 ----------


 ---------- 2021-10-14 12:00:00 : 후평1동   38907 ----------


 ---------- 2021-10-14 13:00:00 : 서  면   38908 ----------


 ---------- 2021-10-14 13:00:00 : 동내면   38909 ----------


 ---------- 2021-10-14 16:00:00 : 동  면   38910 ----------


 ---------- 2021-10-14 18:00:00 : 강남동   38911 ----------


 ---------- 2021-10-14 23:00:00 : 퇴계동   38913 ----------


 ---------- 2021-10-15 05:00:00 : 남산면   38915 ----------


 ---------- 2021-10-15 07:00:00 : 신사우동   38916 ----------


 ---------- 2021-10-15 09:00:00 : 퇴계동   38917 ----------


 ---------- 2021-10-15 11:00:00 : 퇴계동   38918 ----------


 ---------- 2021-10-15 12:00:00 : 남산면   38919 ----------


 ---------- 2021-10-15 13:00:00 : 남산면   38921 ----------


 ---------- 2021-10-15 13:00:00 : 동  면   38922 ----------


 ---------- 2021-10-15 14:00:00 : 남  면   38923 ----------


 ---------- 2021-10-15 16:00:00 : 석사동   38924 ----------


 ---------- 2021-10-15 18:00:00 : 동내면   38925 ----------


 ---------- 2021-10-15 20:00:00 : 신북읍   38926 ----------


 ---------- 2021-10-15 22:00:00 : 퇴계동   38927 ----------


 ---------- 2021-10-16 06:00:00 : 석사동   38928 ----------


 ---------- 2021-10-16 09:00:00 : 신사우동   38929 ----------


 ---------- 2021-10-16 12:00:00 : 남산면   38930 ----------


 ---------- 2021-10-16 16:00:00 : 남  면   38931 ----------


 ---------- 2021-10-16 19:00:00 : 강남동   38932 ----------


 ---------- 2021-10-16 21:00:00 : 남산면   38933 ----------


 ---------- 2021-10-17 03:00:00 : 퇴계동   38934 ----------


 ---------- 2021-10-17 09:00:00 : 퇴계동   38936 ----------


 ---------- 2021-10-17 10:00:00 : 소양동   38937 ----------


 ---------- 2021-10-17 13:00:00 : 신북읍   38939 ----------


 ---------- 2021-10-17 15:00:00 : 퇴계동   38941 ----------


 ---------- 2021-10-17 20:00:00 : 소양동   38942 ----------


 ---------- 2021-10-18 01:00:00 : 후평1동   38943 ----------


 ---------- 2021-10-18 04:00:00 : 서  면   38944 ----------


 ---------- 2021-10-18 05:00:00 : 후평1동   38945 ----------


 ---------- 2021-10-18 05:00:00 : 퇴계동   38947 ----------


 ---------- 2021-10-18 09:00:00 : 동산면   38949 ----------


 ---------- 2021-10-18 10:00:00 : 석사동   38950 ----------


 ---------- 2021-10-18 13:00:00 : 동  면   38952 ----------


 ---------- 2021-10-18 13:00:00 : 동산면   38953 ----------


 ---------- 2021-10-18 14:00:00 : 신동면   38956 ----------


 ---------- 2021-10-18 14:00:00 : 소양동   38957 ----------


 ---------- 2021-10-18 15:00:00 : 동  면   38958 ----------


 ---------- 2021-10-18 17:00:00 : 동내면   38960 ----------


 ---------- 2021-10-19 07:00:00 : 후평1동   38963 ----------


 ---------- 2021-10-19 09:00:00 : 강남동   38964 ----------


 ---------- 2021-10-19 14:00:00 : 효자1동   38965 ----------


 ---------- 2021-10-19 15:00:00 : 강남동   38966 ----------


 ---------- 2021-10-19 21:00:00 : 강남동   38967 ----------


 ---------- 2021-10-20 00:00:00 : 동  면   38968 ----------


 ---------- 2021-10-20 10:00:00 : 소양동   38969 ----------


 ---------- 2021-10-20 14:00:00 : 효자1동   38970 ----------


 ---------- 2021-10-20 18:00:00 : 후평1동   38971 ----------


 ---------- 2021-10-20 19:00:00 : 동  면   38972 ----------


 ---------- 2021-10-20 23:00:00 : 석사동   38973 ----------


 ---------- 2021-10-21 03:00:00 : 퇴계동   38974 ----------


 ---------- 2021-10-21 06:00:00 : 신북읍   38975 ----------


 ---------- 2021-10-21 07:00:00 : 신북읍   38976 ----------


 ---------- 2021-10-21 08:00:00 : 동내면   38977 ----------


 ---------- 2021-10-21 10:00:00 : 퇴계동   38978 ----------


 ---------- 2021-10-21 12:00:00 : 효자1동   38979 ----------


 ---------- 2021-10-21 13:00:00 : 석사동   38980 ----------


 ---------- 2021-10-21 13:00:00 : 사북면   38981 ----------

 ---------- 2021-10-21 14:00:00 : 후평1동   38982 ----------


 ---------- 2021-10-21 15:00:00 : 퇴계동   38983 ----------


 ---------- 2021-10-21 16:00:00 : 신동면   38984 ----------


 ---------- 2021-10-21 16:00:00 : 강남동   38985 ----------


 ---------- 2021-10-21 16:00:00 : 퇴계동   38986 ----------


 ---------- 2021-10-21 19:00:00 : 동  면   38987 ----------


 ---------- 2021-10-21 22:00:00 : 퇴계동   38991 ----------


 ---------- 2021-10-22 08:00:00 : 서  면   38992 ----------


 ---------- 2021-10-22 08:00:00 : 퇴계동   38997 ----------


 ---------- 2021-10-22 10:00:00 : 후평1동   38998 ----------


 ---------- 2021-10-22 11:00:00 : 조운동   38999 ----------


 ---------- 2021-10-22 12:00:00 : 소양동   39000 ----------


 ---------- 2021-10-22 12:00:00 : 조운동   39001 ----------


 ---------- 2021-10-22 14:00:00 : 강남동   39002 ----------


 ---------- 2021-10-22 14:00:00 : 남  면   39005 ----------


 ---------- 2021-10-22 15:00:00 : 신사우동   39006 ----------


 ---------- 2021-10-22 16:00:00 : 퇴계동   39007 ----------


 ---------- 2021-10-22 21:00:00 : 효자1동   39008 ----------


 ---------- 2021-10-23 00:00:00 : 후평1동   39010 ----------


 ---------- 2021-10-23 02:00:00 : 신사우동   39012 ----------


 ---------- 2021-10-23 06:00:00 : 서  면   39014 ----------


 ---------- 2021-10-23 11:00:00 : 효자1동   39015 ----------


 ---------- 2021-10-23 14:00:00 : 효자1동   39016 ----------


 ---------- 2021-10-23 15:00:00 : 서  면   39017 ----------


 ---------- 2021-10-23 16:00:00 : 서  면   39019 ----------


 ---------- 2021-10-23 17:00:00 : 서  면   39020 ----------


 ---------- 2021-10-23 18:00:00 : 서  면   39021 ----------


 ---------- 2021-10-23 18:00:00 : 신사우동   39022 ----------


 ---------- 2021-10-24 06:00:00 : 강남동   39023 ----------


 ---------- 2021-10-24 07:00:00 : 남산면   39025 ----------


 ---------- 2021-10-24 10:00:00 : 동  면   39026 ----------


 ---------- 2021-10-24 16:00:00 : 신동면   39028 ----------


 ---------- 2021-10-24 21:00:00 : 소양동   39029 ----------


 ---------- 2021-10-25 07:00:00 : 효자1동   39030 ----------


 ---------- 2021-10-25 12:00:00 : 퇴계동   39031 ----------


 ---------- 2021-10-25 13:00:00 : 동내면   39032 ----------


 ---------- 2021-10-25 16:00:00 : 남산면   39033 ----------


 ---------- 2021-10-25 17:00:00 : 남산면   39034 ----------


 ---------- 2021-10-25 20:00:00 : 석사동   39035 ----------


 ---------- 2021-10-26 00:00:00 : 신사우동   39037 ----------


 ---------- 2021-10-26 07:00:00 : 신북읍   39039 ----------


 ---------- 2021-10-26 08:00:00 : 신동면   39043 ----------


 ---------- 2021-10-26 10:00:00 : 강남동   39044 ----------


 ---------- 2021-10-26 10:00:00 : 효자1동   39045 ----------


 ---------- 2021-10-26 11:00:00 : 신사우동   39046 ----------


 ---------- 2021-10-26 14:00:00 : 동  면   39047 ----------


 ---------- 2021-10-26 15:00:00 : 동내면   39048 ----------


 ---------- 2021-10-26 19:00:00 : 신동면   39049 ----------


 ---------- 2021-10-26 20:00:00 : 신북읍   39050 ----------


 ---------- 2021-10-26 20:00:00 : 후평1동   39051 ----------


 ---------- 2021-10-26 21:00:00 : 동내면   39052 ----------


 ---------- 2021-10-27 03:00:00 : 북산면   39053 ----------


 ---------- 2021-10-27 04:00:00 : 신북읍   39054 ----------


 ---------- 2021-10-27 07:00:00 : 강남동   39055 ----------


 ---------- 2021-10-27 08:00:00 : 동  면   39056 ----------


 ---------- 2021-10-27 10:00:00 : 신북읍   39057 ----------


 ---------- 2021-10-27 11:00:00 : 신동면   39058 ----------


 ---------- 2021-10-27 11:00:00 : 동산면   39062 ----------


 ---------- 2021-10-27 12:00:00 : 소양동   39063 ----------


 ---------- 2021-10-27 13:00:00 : 신북읍   39064 ----------


 ---------- 2021-10-27 14:00:00 : 퇴계동   39065 ----------


 ---------- 2021-10-27 15:00:00 : 서  면   39066 ----------


 ---------- 2021-10-27 15:00:00 : 효자1동   39067 ----------


 ---------- 2021-10-27 19:00:00 : 근화동   39068 ----------


 ---------- 2021-10-27 20:00:00 : 신동면   39069 ----------


 ---------- 2021-10-27 21:00:00 : 강남동   39070 ----------


 ---------- 2021-10-27 21:00:00 : 퇴계동   39072 ----------


 ---------- 2021-10-27 22:00:00 : 효자1동   39073 ----------


 ---------- 2021-10-27 23:00:00 : 퇴계동   39074 ----------


 ---------- 2021-10-28 09:00:00 : 퇴계동   39075 ----------


 ---------- 2021-10-28 11:00:00 : 약사명동   39076 ----------


 ---------- 2021-10-28 12:00:00 : 동  면   39077 ----------


 ---------- 2021-10-28 14:00:00 : 신북읍   39078 ----------


 ---------- 2021-10-28 15:00:00 : 근화동   39079 ----------


 ---------- 2021-10-28 17:00:00 : 약사명동   39080 ----------


 ---------- 2021-10-28 17:00:00 : 퇴계동   39082 ----------


 ---------- 2021-10-29 05:00:00 : 약사명동   39083 ----------


 ---------- 2021-10-29 06:00:00 : 강남동   39084 ----------


 ---------- 2021-10-29 07:00:00 : 강남동   39086 ----------


 ---------- 2021-10-29 08:00:00 : 남산면   39087 ----------


 ---------- 2021-10-29 09:00:00 : 후평1동   39088 ----------


 ---------- 2021-10-29 11:00:00 : 신동면   39089 ----------


 ---------- 2021-10-29 15:00:00 : 신사우동   39091 ----------


 ---------- 2021-10-29 21:00:00 : 석사동   39092 ----------


 ---------- 2021-10-30 04:00:00 : 석사동   39093 ----------


 ---------- 2021-10-30 11:00:00 : 서  면   39094 ----------


 ---------- 2021-10-30 11:00:00 : 동산면   39095 ----------


 ---------- 2021-10-30 12:00:00 : 동내면   39096 ----------


 ---------- 2021-10-30 14:00:00 : 북산면   39099 ----------


 ---------- 2021-10-30 15:00:00 : 동내면   39100 ----------


 ---------- 2021-10-30 17:00:00 : 후평1동   39101 ----------


 ---------- 2021-10-30 18:00:00 : 동  면   39102 ----------


 ---------- 2021-10-30 19:00:00 : 근화동   39104 ----------


 ---------- 2021-10-30 20:00:00 : 강남동   39105 ----------


 ---------- 2021-10-30 20:00:00 : 동산면   39107 ----------


 ---------- 2021-10-30 23:00:00 : 근화동   39108 ----------


 ---------- 2021-10-30 23:00:00 : 후평1동   39110 ----------


 ---------- 2021-10-31 00:00:00 : 퇴계동   39111 ----------


 ---------- 2021-10-31 08:00:00 : 석사동   39113 ----------


 ---------- 2021-10-31 10:00:00 : 퇴계동   39114 ----------


 ---------- 2021-10-31 13:00:00 : 효자1동   39115 ----------


 ---------- 2021-10-31 14:00:00 : 남산면   39116 ----------


 ---------- 2021-10-31 16:00:00 : 신동면   39118 ----------


 ---------- 2021-10-31 20:00:00 : 퇴계동   39119 ----------


 ---------- 2021-10-31 23:00:00 : 퇴계동   39120 ----------


 ---------- 2021-11-01 13:00:00 : 동내면   39121 ----------


 ---------- 2021-11-01 14:00:00 : 근화동   39123 ----------


 ---------- 2021-11-01 15:00:00 : 강남동   39124 ----------


 ---------- 2021-11-01 15:00:00 : 신사우동   39125 ----------


 ---------- 2021-11-01 16:00:00 : 신동면   39126 ----------


 ---------- 2021-11-01 16:00:00 : 남산면   39127 ----------


 ---------- 2021-11-01 17:00:00 : 남산면   39128 ----------


 ---------- 2021-11-01 17:00:00 : 퇴계동   39130 ----------


 ---------- 2021-11-01 20:00:00 : 석사동   39131 ----------


 ---------- 2021-11-01 23:00:00 : 신사우동   39132 ----------


 ---------- 2021-11-02 02:00:00 : 동내면   39134 ----------


 ---------- 2021-11-02 03:00:00 : 남산면   39136 ----------


 ---------- 2021-11-02 08:00:00 : 효자1동   39140 ----------


 ---------- 2021-11-02 08:00:00 : 후평1동   39141 ----------


 ---------- 2021-11-02 08:00:00 : 퇴계동   39144 ----------


 ---------- 2021-11-02 12:00:00 : 서  면   39145 ----------


 ---------- 2021-11-02 12:00:00 : 소양동   39146 ----------


 ---------- 2021-11-02 13:00:00 : 신동면   39149 ----------


 ---------- 2021-11-02 17:00:00 : 남산면   39150 ----------


 ---------- 2021-11-02 17:00:00 : 퇴계동   39154 ----------


 ---------- 2021-11-02 19:00:00 : 석사동   39156 ----------


 ---------- 2021-11-02 19:00:00 : 신북읍   39157 ----------


 ---------- 2021-11-02 19:00:00 : 후평1동   39158 ----------


 ---------- 2021-11-02 20:00:00 : 신북읍   39160 ----------


 ---------- 2021-11-02 22:00:00 : 남산면   39161 ----------


 ---------- 2021-11-03 02:00:00 : 석사동   39162 ----------


 ---------- 2021-11-03 10:00:00 : 강남동   39163 ----------


 ---------- 2021-11-03 12:00:00 : 동내면   39164 ----------


 ---------- 2021-11-03 17:00:00 : 퇴계동   39166 ----------


 ---------- 2021-11-03 19:00:00 : 석사동   39167 ----------


 ---------- 2021-11-03 21:00:00 : 남산면   39168 ----------

 ---------- 2021-11-04 05:00:00 : 남  면   39170 ----------


 ---------- 2021-11-04 06:00:00 : 남산면   39171 ----------


 ---------- 2021-11-04 09:00:00 : 교  동   39172 ----------


 ---------- 2021-11-04 15:00:00 : 효자1동   39173 ----------


 ---------- 2021-11-04 16:00:00 : 약사명동   39174 ----------


 ---------- 2021-11-04 19:00:00 : 후평1동   39175 ----------


 ---------- 2021-11-04 20:00:00 : 퇴계동   39177 ----------


 ---------- 2021-11-04 23:00:00 : 석사동   39178 ----------


 ---------- 2021-11-05 01:00:00 : 강남동   39179 ----------


 ---------- 2021-11-05 07:00:00 : 효자1동   39180 ----------


 ---------- 2021-11-05 10:00:00 : 서  면   39181 ----------


 ---------- 2021-11-05 10:00:00 : 동내면   39184 ----------


 ---------- 2021-11-05 10:00:00 : 동산면   39186 ----------


 ---------- 2021-11-05 11:00:00 : 효자1동   39187 ----------


 ---------- 2021-11-05 14:00:00 : 동내면   39188 ----------


 ---------- 2021-11-05 15:00:00 : 신북읍   39189 ----------


 ---------- 2021-11-05 18:00:00 : 동내면   39190 ----------


 ---------- 2021-11-05 18:00:00 : 효자1동   39191 ----------


 ---------- 2021-11-05 18:00:00 : 신사우동   39193 ----------


 ---------- 2021-11-05 18:00:00 : 소양동   39194 ----------


 ---------- 2021-11-05 18:00:00 : 약사명동   39196 ----------


 ---------- 2021-11-06 05:00:00 : 효자1동   39197 ----------


 ---------- 2021-11-06 14:00:00 : 서  면   39199 ----------


 ---------- 2021-11-06 16:00:00 : 신사우동   39200 ----------


 ---------- 2021-11-06 22:00:00 : 강남동   39201 ----------


 ---------- 2021-11-07 02:00:00 : 강남동   39203 ----------


 ---------- 2021-11-07 08:00:00 : 약사명동   39204 ----------


 ---------- 2021-11-07 08:00:00 : 동산면   39205 ----------


 ---------- 2021-11-07 09:00:00 : 효자1동   39206 ----------


 ---------- 2021-11-07 09:00:00 : 교  동   39207 ----------


 ---------- 2021-11-07 11:00:00 : 강남동   39208 ----------


 ---------- 2021-11-07 12:00:00 : 효자1동   39209 ----------


 ---------- 2021-11-07 13:00:00 : 신북읍   39210 ----------


 ---------- 2021-11-07 16:00:00 : 남산면   39211 ----------


 ---------- 2021-11-07 23:00:00 : 신사우동   39212 ----------


 ---------- 2021-11-08 00:00:00 : 석사동   39213 ----------


 ---------- 2021-11-08 00:00:00 : 동  면   39214 ----------


 ---------- 2021-11-08 03:00:00 : 석사동   39215 ----------


 ---------- 2021-11-08 08:00:00 : 강남동   39217 ----------


 ---------- 2021-11-08 09:00:00 : 동내면   39218 ----------


 ---------- 2021-11-08 10:00:00 : 강남동   39219 ----------


 ---------- 2021-11-08 11:00:00 : 동산면   39222 ----------


 ---------- 2021-11-08 12:00:00 : 후평1동   39223 ----------


 ---------- 2021-11-08 13:00:00 : 후평1동   39224 ----------


 ---------- 2021-11-08 13:00:00 : 퇴계동   39225 ----------


 ---------- 2021-11-08 16:00:00 : 후평1동   39226 ----------


 ---------- 2021-11-08 16:00:00 : 동산면   39227 ----------


 ---------- 2021-11-08 17:00:00 : 석사동   39230 ----------


 ---------- 2021-11-08 17:00:00 : 서  면   39232 ----------


 ---------- 2021-11-08 19:00:00 : 후평1동   39235 ----------


 ---------- 2021-11-08 22:00:00 : 신동면   39237 ----------


 ---------- 2021-11-08 23:00:00 : 동내면   39238 ----------


 ---------- 2021-11-09 01:00:00 : 후평1동   39239 ----------


 ---------- 2021-11-09 08:00:00 : 퇴계동   39240 ----------


 ---------- 2021-11-09 09:00:00 : 강남동   39241 ----------


 ---------- 2021-11-09 11:00:00 : 교  동   39242 ----------


 ---------- 2021-11-09 14:00:00 : 동내면   39243 ----------


 ---------- 2021-11-09 18:00:00 : 신북읍   39244 ----------


 ---------- 2021-11-09 20:00:00 : 동산면   39245 ----------


 ---------- 2021-11-10 01:00:00 : 동내면   39246 ----------


 ---------- 2021-11-10 02:00:00 : 신사우동   39247 ----------


 ---------- 2021-11-10 03:00:00 : 남  면   39248 ----------


 ---------- 2021-11-10 08:00:00 : 사북면   39250 ----------


 ---------- 2021-11-10 09:00:00 : 효자1동   39251 ----------


 ---------- 2021-11-10 13:00:00 : 효자1동   39252 ----------


 ---------- 2021-11-10 14:00:00 : 동산면   39253 ----------


 ---------- 2021-11-10 16:00:00 : 효자1동   39254 ----------


 ---------- 2021-11-10 18:00:00 : 석사동   39255 ----------


 ---------- 2021-11-10 19:00:00 : 강남동   39256 ----------


 ---------- 2021-11-10 20:00:00 : 석사동   39257 ----------


 ---------- 2021-11-10 22:00:00 : 근화동   39258 ----------


 ---------- 2021-11-11 09:00:00 : 약사명동   39260 ----------


 ---------- 2021-11-11 09:00:00 : 동산면   39263 ----------


 ---------- 2021-11-11 12:00:00 : 신북읍   39265 ----------


 ---------- 2021-11-11 12:00:00 : 동  면   39266 ----------


 ---------- 2021-11-11 17:00:00 : 신사우동   39267 ----------


 ---------- 2021-11-11 18:00:00 : 후평1동   39268 ----------


 ---------- 2021-11-12 05:00:00 : 효자1동   39269 ----------


 ---------- 2021-11-12 08:00:00 : 교  동   39271 ----------


 ---------- 2021-11-12 09:00:00 : 소양동   39272 ----------


 ---------- 2021-11-12 09:00:00 : 교  동   39273 ----------


 ---------- 2021-11-12 10:00:00 : 신동면   39275 ----------


 ---------- 2021-11-12 14:00:00 : 신사우동   39276 ----------


 ---------- 2021-11-12 14:00:00 : 퇴계동   39277 ----------


 ---------- 2021-11-12 16:00:00 : 신북읍   39279 ----------


 ---------- 2021-11-12 17:00:00 : 동  면   39280 ----------


 ---------- 2021-11-12 17:00:00 : 후평1동   39281 ----------


 ---------- 2021-11-12 22:00:00 : 소양동   39282 ----------


 ---------- 2021-11-12 23:00:00 : 퇴계동   39284 ----------


 ---------- 2021-11-13 00:00:00 : 퇴계동   39285 ----------


 ---------- 2021-11-13 06:00:00 : 석사동   39286 ----------


 ---------- 2021-11-13 08:00:00 : 동산면   39287 ----------


 ---------- 2021-11-13 11:00:00 : 근화동   39288 ----------


 ---------- 2021-11-13 11:00:00 : 신북읍   39289 ----------


 ---------- 2021-11-13 15:00:00 : 신북읍   39291 ----------


 ---------- 2021-11-13 19:00:00 : 신북읍   39292 ----------


 ---------- 2021-11-13 20:00:00 : 강남동   39293 ----------


 ---------- 2021-11-13 21:00:00 : 동  면   39294 ----------


 ---------- 2021-11-14 01:00:00 : 남산면   39295 ----------


 ---------- 2021-11-14 08:00:00 : 퇴계동   39296 ----------


 ---------- 2021-11-14 08:00:00 : 동산면   39297 ----------


 ---------- 2021-11-14 10:00:00 : 퇴계동   39298 ----------


 ---------- 2021-11-14 12:00:00 : 조운동   39299 ----------


 ---------- 2021-11-14 15:00:00 : 소양동   39302 ----------


 ---------- 2021-11-14 16:00:00 : 강남동   39304 ----------


 ---------- 2021-11-14 16:00:00 : 동내면   39305 ----------


 ---------- 2021-11-14 17:00:00 : 남  면   39308 ----------


 ---------- 2021-11-14 19:00:00 : 신사우동   39310 ----------


 ---------- 2021-11-15 10:00:00 : 남  면   39311 ----------


 ---------- 2021-11-15 10:00:00 : 후평1동   39313 ----------


 ---------- 2021-11-15 12:00:00 : 신북읍   39314 ----------


 ---------- 2021-11-15 13:00:00 : 신북읍   39315 ----------


 ---------- 2021-11-15 13:00:00 : 소양동   39316 ----------


 ---------- 2021-11-15 16:00:00 : 동내면   39317 ----------


 ---------- 2021-11-15 19:00:00 : 후평1동   39318 ----------


 ---------- 2021-11-15 22:00:00 : 신북읍   39319 ----------


 ---------- 2021-11-16 10:00:00 : 신북읍   39321 ----------


 ---------- 2021-11-17 00:00:00 : 효자1동   39322 ----------


 ---------- 2021-11-17 04:00:00 : 동내면   39323 ----------


 ---------- 2021-11-17 09:00:00 : 동내면   39324 ----------


 ---------- 2021-11-17 10:00:00 : 후평1동   39325 ----------


 ---------- 2021-11-17 12:00:00 : 신동면   39326 ----------


 ---------- 2021-11-17 15:00:00 : 남산면   39328 ----------


 ---------- 2021-11-17 15:00:00 : 소양동   39329 ----------


 ---------- 2021-11-17 16:00:00 : 동  면   39330 ----------


 ---------- 2021-11-17 17:00:00 : 소양동   39332 ----------


 ---------- 2021-11-17 19:00:00 : 석사동   39333 ----------


 ---------- 2021-11-18 01:00:00 : 동내면   39334 ----------


 ---------- 2021-11-18 04:00:00 : 석사동   39336 ----------


 ---------- 2021-11-18 04:00:00 : 동내면   39337 ----------


 ---------- 2021-11-18 06:00:00 : 신북읍   39338 ----------


 ---------- 2021-11-18 06:00:00 : 동산면   39341 ----------


 ---------- 2021-11-18 07:00:00 : 효자1동   39342 ----------


 ---------- 2021-11-18 07:00:00 : 남산면   39345 ----------


 ---------- 2021-11-18 09:00:00 : 남산면   39346 ----------


 ---------- 2021-11-18 14:00:00 : 남산면   39347 ----------

 ---------- 2021-11-18 16:00:00 : 신북읍   39349 ----------


 ---------- 2021-11-18 18:00:00 : 신북읍   39350 ----------


 ---------- 2021-11-18 21:00:00 : 강남동   39351 ----------


 ---------- 2021-11-19 02:00:00 : 후평1동   39352 ----------


 ---------- 2021-11-19 07:00:00 : 남산면   39357 ----------


 ---------- 2021-11-19 08:00:00 : 약사명동   39358 ----------


 ---------- 2021-11-19 10:00:00 : 신동면   39359 ----------


 ---------- 2021-11-19 11:00:00 : 교  동   39360 ----------


 ---------- 2021-11-19 14:00:00 : 석사동   39361 ----------


 ---------- 2021-11-19 14:00:00 : 남산면   39364 ----------


 ---------- 2021-11-19 16:00:00 : 약사명동   39365 ----------


 ---------- 2021-11-19 19:00:00 : 서  면   39366 ----------


 ---------- 2021-11-19 22:00:00 : 석사동   39367 ----------


 ---------- 2021-11-19 23:00:00 : 서  면   39368 ----------


 ---------- 2021-11-20 01:00:00 : 후평1동   39369 ----------


 ---------- 2021-11-20 10:00:00 : 서  면   39370 ----------


 ---------- 2021-11-20 10:00:00 : 퇴계동   39371 ----------


 ---------- 2021-11-20 11:00:00 : 석사동   39372 ----------


 ---------- 2021-11-20 11:00:00 : 신동면   39375 ----------


 ---------- 2021-11-20 11:00:00 : 남산면   39376 ----------


 ---------- 2021-11-20 16:00:00 : 석사동   39377 ----------


 ---------- 2021-11-20 16:00:00 : 동내면   39378 ----------


 ---------- 2021-11-20 17:00:00 : 신북읍   39379 ----------


 ---------- 2021-11-20 18:00:00 : 동내면   39380 ----------


 ---------- 2021-11-20 20:00:00 : 후평1동   39381 ----------


 ---------- 2021-11-20 23:00:00 : 동  면   39382 ----------


 ---------- 2021-11-21 01:00:00 : 동  면   39383 ----------


 ---------- 2021-11-21 01:00:00 : 퇴계동   39384 ----------


 ---------- 2021-11-21 04:00:00 : 퇴계동   39385 ----------


 ---------- 2021-11-21 09:00:00 : 후평1동   39386 ----------


 ---------- 2021-11-21 11:00:00 : 소양동   39387 ----------


 ---------- 2021-11-21 13:00:00 : 강남동   39388 ----------


 ---------- 2021-11-21 15:00:00 : 후평1동   39389 ----------


 ---------- 2021-11-21 19:00:00 : 퇴계동   39390 ----------


 ---------- 2021-11-21 20:00:00 : 석사동   39392 ----------


 ---------- 2021-11-21 20:00:00 : 후평1동   39393 ----------


 ---------- 2021-11-22 12:00:00 : 소양동   39394 ----------


 ---------- 2021-11-22 14:00:00 : 신동면   39395 ----------


 ---------- 2021-11-22 14:00:00 : 동산면   39396 ----------


 ---------- 2021-11-22 15:00:00 : 소양동   39397 ----------


 ---------- 2021-11-22 15:00:00 : 동  면   39398 ----------


 ---------- 2021-11-23 08:00:00 : 석사동   39399 ----------


 ---------- 2021-11-23 09:00:00 : 동내면   39400 ----------


 ---------- 2021-11-23 22:00:00 : 동내면   39401 ----------


 ---------- 2021-11-24 01:00:00 : 동  면   39404 ----------


 ---------- 2021-11-24 06:00:00 : 퇴계동   39405 ----------


 ---------- 2021-11-24 08:00:00 : 신북읍   39406 ----------


 ---------- 2021-11-24 11:00:00 : 신사우동   39407 ----------


 ---------- 2021-11-24 11:00:00 : 동  면   39409 ----------


 ---------- 2021-11-24 13:00:00 : 강남동   39410 ----------


 ---------- 2021-11-24 16:00:00 : 강남동   39411 ----------


 ---------- 2021-11-24 19:00:00 : 조운동   39412 ----------


 ---------- 2021-11-24 20:00:00 : 강남동   39414 ----------


 ---------- 2021-11-25 03:00:00 : 신북읍   39415 ----------


 ---------- 2021-11-25 07:00:00 : 후평1동   39416 ----------


 ---------- 2021-11-25 09:00:00 : 동산면   39417 ----------


 ---------- 2021-11-25 10:00:00 : 신동면   39419 ----------


 ---------- 2021-11-25 12:00:00 : 신사우동   39420 ----------


 ---------- 2021-11-25 19:00:00 : 후평1동   39421 ----------


 ---------- 2021-11-25 21:00:00 : 신사우동   39422 ----------


 ---------- 2021-11-26 08:00:00 : 남산면   39424 ----------


 ---------- 2021-11-26 10:00:00 : 석사동   39425 ----------


 ---------- 2021-11-26 11:00:00 : 동내면   39426 ----------


 ---------- 2021-11-26 11:00:00 : 효자1동   39428 ----------


 ---------- 2021-11-26 12:00:00 : 동내면   39429 ----------


 ---------- 2021-11-26 14:00:00 : 석사동   39430 ----------


 ---------- 2021-11-26 15:00:00 : 조운동   39431 ----------


 ---------- 2021-11-26 21:00:00 : 석사동   39432 ----------


 ---------- 2021-11-27 00:00:00 : 퇴계동   39433 ----------


 ---------- 2021-11-27 03:00:00 : 퇴계동   39434 ----------


 ---------- 2021-11-27 11:00:00 : 퇴계동   39435 ----------


 ---------- 2021-11-27 23:00:00 : 후평1동   39436 ----------


 ---------- 2021-11-28 12:00:00 : 후평1동   39437 ----------


 ---------- 2021-11-28 13:00:00 : 약사명동   39438 ----------


 ---------- 2021-11-28 13:00:00 : 동  면   39440 ----------


 ---------- 2021-11-28 14:00:00 : 신북읍   39441 ----------


 ---------- 2021-11-28 15:00:00 : 강남동   39442 ----------


 ---------- 2021-11-28 16:00:00 : 퇴계동   39443 ----------


 ---------- 2021-11-28 17:00:00 : 효자1동   39444 ----------


 ---------- 2021-11-28 18:00:00 : 신사우동   39446 ----------


 ---------- 2021-11-28 20:00:00 : 퇴계동   39448 ----------


 ---------- 2021-11-29 05:00:00 : 남  면   39450 ----------


 ---------- 2021-11-29 05:00:00 : 사북면   39451 ----------


 ---------- 2021-11-29 09:00:00 : 동내면   39452 ----------


 ---------- 2021-11-29 12:00:00 : 신동면   39453 ----------


 ---------- 2021-11-29 12:00:00 : 남산면   39454 ----------


 ---------- 2021-11-29 13:00:00 : 석사동   39455 ----------


 ---------- 2021-11-29 16:00:00 : 서  면   39456 ----------


 ---------- 2021-11-29 16:00:00 : 남산면   39457 ----------


 ---------- 2021-11-29 16:00:00 : 약사명동   39458 ----------


 ---------- 2021-11-29 17:00:00 : 석사동   39462 ----------


 ---------- 2021-11-29 20:00:00 : 동내면   39464 ----------


 ---------- 2021-11-29 21:00:00 : 동내면   39465 ----------


 ---------- 2021-11-29 22:00:00 : 후평1동   39467 ----------


 ---------- 2021-11-29 23:00:00 : 후평1동   39469 ----------


 ---------- 2021-11-30 09:00:00 : 효자1동   39471 ----------


 ---------- 2021-11-30 11:00:00 : 서  면   39472 ----------


 ---------- 2021-11-30 11:00:00 : 신북읍   39473 ----------


 ---------- 2021-11-30 19:00:00 : 약사명동   39474 ----------


 ---------- 2021-11-30 21:00:00 : 신사우동   39475 ----------


 ---------- 2021-11-30 22:00:00 : 약사명동   39477 ----------


 ---------- 2021-12-01 10:00:00 : 효자1동   39478 ----------


 ---------- 2021-12-01 20:00:00 : 동내면   39480 ----------


 ---------- 2021-12-01 20:00:00 : 조운동   39481 ----------


 ---------- 2021-12-02 07:00:00 : 후평1동   39482 ----------


 ---------- 2021-12-02 10:00:00 : 석사동   39483 ----------


 ---------- 2021-12-02 11:00:00 : 퇴계동   39485 ----------


 ---------- 2021-12-02 12:00:00 : 효자1동   39488 ----------


 ---------- 2021-12-02 13:00:00 : 동내면   39489 ----------


 ---------- 2021-12-02 15:00:00 : 강남동   39490 ----------


 ---------- 2021-12-02 15:00:00 : 동내면   39491 ----------


 ---------- 2021-12-02 15:00:00 : 효자1동   39493 ----------


 ---------- 2021-12-02 15:00:00 : 남산면   39494 ----------


 ---------- 2021-12-02 21:00:00 : 후평1동   39495 ----------


 ---------- 2021-12-03 16:00:00 : 강남동   39496 ----------


 ---------- 2021-12-03 16:00:00 : 신사우동   39497 ----------


 ---------- 2021-12-03 19:00:00 : 동  면   39498 ----------


 ---------- 2021-12-04 02:00:00 : 동산면   39499 ----------


 ---------- 2021-12-04 08:00:00 : 퇴계동   39500 ----------


 ---------- 2021-12-04 09:00:00 : 석사동   39501 ----------


 ---------- 2021-12-04 19:00:00 : 퇴계동   39503 ----------


 ---------- 2021-12-05 02:00:00 : 서  면   39504 ----------


 ---------- 2021-12-05 03:00:00 : 동내면   39505 ----------


 ---------- 2021-12-05 08:00:00 : 약사명동   39507 ----------


 ---------- 2021-12-05 12:00:00 : 근화동   39508 ----------


 ---------- 2021-12-05 13:00:00 : 퇴계동   39509 ----------


 ---------- 2021-12-05 14:00:00 : 석사동   39510 ----------


 ---------- 2021-12-05 14:00:00 : 서  면   39511 ----------


 ---------- 2021-12-05 16:00:00 : 효자1동   39512 ----------


 ---------- 2021-12-05 20:00:00 : 퇴계동   39513 ----------


 ---------- 2021-12-06 00:00:00 : 후평1동   39515 ----------


 ---------- 2021-12-06 07:00:00 : 강남동   39516 ----------


 ---------- 2021-12-06 07:00:00 : 동산면   39520 ----------


 ---------- 2021-12-06 08:00:00 : 동내면   39522 ----------


 ---------- 2021-12-06 14:00:00 : 신북읍   39524 ----------


 ---------- 2021-12-06 15:00:00 : 남산면   39526 ----------

 ---------- 2021-12-06 16:00:00 : 신북읍   39527 ----------


 ---------- 2021-12-06 17:00:00 : 강남동   39528 ----------


 ---------- 2021-12-06 22:00:00 : 효자1동   39529 ----------


 ---------- 2021-12-06 23:00:00 : 효자1동   39530 ----------


 ---------- 2021-12-07 12:00:00 : 남산면   39531 ----------


 ---------- 2021-12-07 13:00:00 : 동  면   39532 ----------


 ---------- 2021-12-07 14:00:00 : 강남동   39533 ----------


 ---------- 2021-12-07 15:00:00 : 남산면   39535 ----------


 ---------- 2021-12-07 16:00:00 : 신사우동   39536 ----------


 ---------- 2021-12-07 16:00:00 : 퇴계동   39537 ----------


 ---------- 2021-12-07 17:00:00 : 동산면   39540 ----------


 ---------- 2021-12-08 03:00:00 : 후평1동   39541 ----------


 ---------- 2021-12-08 10:00:00 : 동내면   39542 ----------


 ---------- 2021-12-08 10:00:00 : 후평1동   39543 ----------


 ---------- 2021-12-08 13:00:00 : 퇴계동   39544 ----------


 ---------- 2021-12-08 14:00:00 : 신사우동   39546 ----------


 ---------- 2021-12-08 14:00:00 : 동  면   39547 ----------


 ---------- 2021-12-08 15:00:00 : 동내면   39548 ----------


 ---------- 2021-12-08 15:00:00 : 교  동   39549 ----------


 ---------- 2021-12-08 18:00:00 : 서  면   39550 ----------


 ---------- 2021-12-08 22:00:00 : 후평1동   39551 ----------


 ---------- 2021-12-09 00:00:00 : 동내면   39552 ----------


 ---------- 2021-12-09 02:00:00 : 퇴계동   39553 ----------


 ---------- 2021-12-09 05:00:00 : 동내면   39554 ----------


 ---------- 2021-12-09 08:00:00 : 교  동   39556 ----------


 ---------- 2021-12-09 10:00:00 : 신사우동   39557 ----------


 ---------- 2021-12-09 11:00:00 : 퇴계동   39558 ----------


 ---------- 2021-12-09 12:00:00 : 후평1동   39559 ----------


 ---------- 2021-12-09 15:00:00 : 효자1동   39561 ----------


 ---------- 2021-12-09 15:00:00 : 동  면   39562 ----------


 ---------- 2021-12-09 21:00:00 : 북산면   39563 ----------


 ---------- 2021-12-10 06:00:00 : 약사명동   39564 ----------


 ---------- 2021-12-10 10:00:00 : 석사동   39565 ----------


 ---------- 2021-12-10 10:00:00 : 후평1동   39566 ----------


 ---------- 2021-12-10 12:00:00 : 강남동   39567 ----------


 ---------- 2021-12-10 13:00:00 : 신사우동   39568 ----------


 ---------- 2021-12-10 14:00:00 : 동내면   39569 ----------


 ---------- 2021-12-10 14:00:00 : 동  면   39570 ----------


 ---------- 2021-12-10 15:00:00 : 신사우동   39571 ----------


 ---------- 2021-12-10 16:00:00 : 후평1동   39572 ----------


 ---------- 2021-12-10 17:00:00 : 퇴계동   39573 ----------


 ---------- 2021-12-11 01:00:00 : 퇴계동   39574 ----------


 ---------- 2021-12-11 08:00:00 : 석사동   39575 ----------


 ---------- 2021-12-11 09:00:00 : 석사동   39576 ----------


 ---------- 2021-12-11 09:00:00 : 퇴계동   39579 ----------


 ---------- 2021-12-11 11:00:00 : 후평1동   39580 ----------


 ---------- 2021-12-11 11:00:00 : 동산면   39581 ----------


 ---------- 2021-12-11 12:00:00 : 후평1동   39584 ----------


 ---------- 2021-12-11 13:00:00 : 동  면   39585 ----------


 ---------- 2021-12-11 15:00:00 : 서  면   39588 ----------


 ---------- 2021-12-11 15:00:00 : 신북읍   39590 ----------


 ---------- 2021-12-11 15:00:00 : 퇴계동   39591 ----------


 ---------- 2021-12-11 16:00:00 : 석사동   39592 ----------


 ---------- 2021-12-11 16:00:00 : 남산면   39593 ----------


 ---------- 2021-12-11 17:00:00 : 퇴계동   39594 ----------


 ---------- 2021-12-11 18:00:00 : 석사동   39597 ----------


 ---------- 2021-12-11 20:00:00 : 신사우동   39599 ----------


 ---------- 2021-12-12 03:00:00 : 근화동   39601 ----------


 ---------- 2021-12-12 07:00:00 : 후평1동   39603 ----------


 ---------- 2021-12-12 13:00:00 : 사북면   39604 ----------


 ---------- 2021-12-12 14:00:00 : 퇴계동   39606 ----------


 ---------- 2021-12-12 19:00:00 : 효자1동   39607 ----------


 ---------- 2021-12-12 22:00:00 : 강남동   39608 ----------


 ---------- 2021-12-12 23:00:00 : 퇴계동   39609 ----------


 ---------- 2021-12-13 03:00:00 : 남산면   39610 ----------


 ---------- 2021-12-13 05:00:00 : 신사우동   39611 ----------


 ---------- 2021-12-13 07:00:00 : 신사우동   39612 ----------


 ---------- 2021-12-13 11:00:00 : 서  면   39613 ----------


 ---------- 2021-12-13 13:00:00 : 조운동   39614 ----------


 ---------- 2021-12-13 14:00:00 : 퇴계동   39616 ----------


 ---------- 2021-12-13 17:00:00 : 신북읍   39617 ----------


 ---------- 2021-12-13 18:00:00 : 동내면   39619 ----------


 ---------- 2021-12-14 00:00:00 : 강남동   39620 ----------


 ---------- 2021-12-14 06:00:00 : 약사명동   39621 ----------


 ---------- 2021-12-14 09:00:00 : 동산면   39622 ----------


 ---------- 2021-12-14 10:00:00 : 신북읍   39623 ----------


 ---------- 2021-12-14 11:00:00 : 후평1동   39624 ----------


 ---------- 2021-12-14 11:00:00 : 조운동   39626 ----------


 ---------- 2021-12-14 12:00:00 : 퇴계동   39629 ----------


 ---------- 2021-12-14 13:00:00 : 서  면   39631 ----------


 ---------- 2021-12-14 13:00:00 : 퇴계동   39632 ----------


 ---------- 2021-12-14 14:00:00 : 동내면   39634 ----------


 ---------- 2021-12-14 15:00:00 : 동내면   39635 ----------


 ---------- 2021-12-14 16:00:00 : 동산면   39636 ----------


 ---------- 2021-12-14 17:00:00 : 신동면   39638 ----------


 ---------- 2021-12-14 19:00:00 : 동내면   39639 ----------


 ---------- 2021-12-14 21:00:00 : 퇴계동   39640 ----------


 ---------- 2021-12-15 07:00:00 : 효자1동   39641 ----------


 ---------- 2021-12-15 11:00:00 : 강남동   39642 ----------


 ---------- 2021-12-15 12:00:00 : 소양동   39643 ----------


 ---------- 2021-12-15 13:00:00 : 동내면   39644 ----------


 ---------- 2021-12-15 15:00:00 : 효자1동   39645 ----------


 ---------- 2021-12-15 23:00:00 : 퇴계동   39646 ----------


 ---------- 2021-12-16 04:00:00 : 후평1동   39647 ----------


 ---------- 2021-12-16 09:00:00 : 서  면   39648 ----------


 ---------- 2021-12-16 11:00:00 : 동  면   39649 ----------


 ---------- 2021-12-16 14:00:00 : 퇴계동   39650 ----------


 ---------- 2021-12-16 17:00:00 : 서  면   39652 ----------


 ---------- 2021-12-17 04:00:00 : 석사동   39653 ----------


 ---------- 2021-12-17 04:00:00 : 후평1동   39655 ----------


 ---------- 2021-12-17 06:00:00 : 신사우동   39656 ----------


 ---------- 2021-12-17 08:00:00 : 퇴계동   39657 ----------


 ---------- 2021-12-17 08:00:00 : 교  동   39658 ----------


 ---------- 2021-12-17 14:00:00 : 동내면   39659 ----------


 ---------- 2021-12-17 15:00:00 : 남산면   39660 ----------


 ---------- 2021-12-17 15:00:00 : 퇴계동   39661 ----------


 ---------- 2021-12-17 16:00:00 : 조운동   39662 ----------


 ---------- 2021-12-17 17:00:00 : 약사명동   39663 ----------


 ---------- 2021-12-17 17:00:00 : 동  면   39665 ----------


 ---------- 2021-12-17 19:00:00 : 석사동   39666 ----------


 ---------- 2021-12-17 19:00:00 : 소양동   39667 ----------


 ---------- 2021-12-17 20:00:00 : 조운동   39668 ----------


 ---------- 2021-12-17 22:00:00 : 근화동   39669 ----------


 ---------- 2021-12-17 23:00:00 : 남  면   39670 ----------


 ---------- 2021-12-17 23:00:00 : 퇴계동   39671 ----------


 ---------- 2021-12-18 09:00:00 : 동내면   39672 ----------


 ---------- 2021-12-18 13:00:00 : 남  면   39673 ----------


 ---------- 2021-12-18 19:00:00 : 남  면   39674 ----------


 ---------- 2021-12-19 02:00:00 : 약사명동   39675 ----------


 ---------- 2021-12-19 05:00:00 : 신사우동   39676 ----------


 ---------- 2021-12-19 10:00:00 : 신동면   39678 ----------


 ---------- 2021-12-19 11:00:00 : 사북면   39679 ----------


 ---------- 2021-12-19 14:00:00 : 후평1동   39680 ----------


 ---------- 2021-12-19 16:00:00 : 조운동   39681 ----------


 ---------- 2021-12-19 19:00:00 : 신북읍   39682 ----------


 ---------- 2021-12-19 21:00:00 : 강남동   39683 ----------


 ---------- 2021-12-20 06:00:00 : 신사우동   39684 ----------


 ---------- 2021-12-20 09:00:00 : 남산면   39686 ----------


 ---------- 2021-12-20 09:00:00 : 퇴계동   39687 ----------


 ---------- 2021-12-20 11:00:00 : 동내면   39688 ----------


 ---------- 2021-12-20 11:00:00 : 후평1동   39689 ----------


 ---------- 2021-12-20 12:00:00 : 신사우동   39691 ----------


 ---------- 2021-12-20 12:00:00 : 후평1동   39692 ----------


 ---------- 2021-12-20 13:00:00 : 서  면   39693 ----------


 ---------- 2021-12-20 13:00:00 : 후평1동   39695 ----------


 ---------- 2021-12-20 18:00:00 : 효자1동   39697 ----------

 ---------- 2021-12-20 18:00:00 : 퇴계동   39698 ----------


 ---------- 2021-12-20 19:00:00 : 사북면   39699 ----------


 ---------- 2021-12-20 19:00:00 : 동  면   39700 ----------


 ---------- 2021-12-20 22:00:00 : 신동면   39701 ----------


 ---------- 2021-12-21 11:00:00 : 동내면   39702 ----------


 ---------- 2021-12-21 11:00:00 : 신사우동   39704 ----------


 ---------- 2021-12-21 13:00:00 : 동산면   39705 ----------


 ---------- 2021-12-21 17:00:00 : 교  동   39706 ----------


 ---------- 2021-12-21 19:00:00 : 석사동   39707 ----------


 ---------- 2021-12-21 20:00:00 : 강남동   39708 ----------


 ---------- 2021-12-22 09:00:00 : 강남동   39709 ----------


 ---------- 2021-12-22 10:00:00 : 강남동   39711 ----------


 ---------- 2021-12-22 10:00:00 : 동산면   39712 ----------


 ---------- 2021-12-22 11:00:00 : 후평1동   39713 ----------


 ---------- 2021-12-22 13:00:00 : 소양동   39714 ----------


 ---------- 2021-12-22 14:00:00 : 동  면   39715 ----------


 ---------- 2021-12-22 16:00:00 : 후평1동   39716 ----------


 ---------- 2021-12-22 17:00:00 : 후평1동   39717 ----------


 ---------- 2021-12-23 08:00:00 : 사북면   39719 ----------


 ---------- 2021-12-23 09:00:00 : 동내면   39720 ----------


 ---------- 2021-12-23 11:00:00 : 석사동   39721 ----------


 ---------- 2021-12-23 11:00:00 : 신동면   39722 ----------


 ---------- 2021-12-23 12:00:00 : 서  면   39723 ----------


 ---------- 2021-12-23 16:00:00 : 석사동   39724 ----------


 ---------- 2021-12-23 16:00:00 : 신북읍   39725 ----------


 ---------- 2021-12-23 17:00:00 : 동내면   39726 ----------


 ---------- 2021-12-23 19:00:00 : 효자1동   39728 ----------


 ---------- 2021-12-23 20:00:00 : 석사동   39729 ----------


 ---------- 2021-12-24 01:00:00 : 신동면   39730 ----------


 ---------- 2021-12-24 02:00:00 : 동  면   39731 ----------


 ---------- 2021-12-24 10:00:00 : 석사동   39732 ----------


 ---------- 2021-12-24 17:00:00 : 남  면   39733 ----------


 ---------- 2021-12-24 19:00:00 : 남산면   39735 ----------


 ---------- 2021-12-24 20:00:00 : 퇴계동   39736 ----------


 ---------- 2021-12-24 22:00:00 : 신북읍   39737 ----------


 ---------- 2021-12-25 09:00:00 : 남  면   39738 ----------


 ---------- 2021-12-25 12:00:00 : 퇴계동   39739 ----------


 ---------- 2021-12-25 13:00:00 : 퇴계동   39741 ----------


 ---------- 2021-12-25 14:00:00 : 신북읍   39742 ----------


 ---------- 2021-12-25 15:00:00 : 근화동   39743 ----------


 ---------- 2021-12-25 22:00:00 : 석사동   39744 ----------


 ---------- 2021-12-26 00:00:00 : 퇴계동   39745 ----------


 ---------- 2021-12-26 08:00:00 : 신동면   39746 ----------


 ---------- 2021-12-26 08:00:00 : 효자1동   39747 ----------


 ---------- 2021-12-26 09:00:00 : 강남동   39748 ----------


 ---------- 2021-12-26 09:00:00 : 서  면   39750 ----------


 ---------- 2021-12-26 09:00:00 : 교  동   39752 ----------


 ---------- 2021-12-26 10:00:00 : 효자1동   39753 ----------


 ---------- 2021-12-26 10:00:00 : 소양동   39755 ----------


 ---------- 2021-12-26 12:00:00 : 효자1동   39756 ----------


 ---------- 2021-12-26 14:00:00 : 후평1동   39758 ----------


 ---------- 2021-12-26 15:00:00 : 신북읍   39759 ----------


 ---------- 2021-12-26 15:00:00 : 퇴계동   39760 ----------


 ---------- 2021-12-26 16:00:00 : 강남동   39762 ----------


 ---------- 2021-12-26 18:00:00 : 퇴계동   39763 ----------


 ---------- 2021-12-26 19:00:00 : 석사동   39764 ----------


 ---------- 2021-12-26 19:00:00 : 동  면   39765 ----------


 ---------- 2021-12-26 20:00:00 : 근화동   39767 ----------


 ---------- 2021-12-26 21:00:00 : 남산면   39769 ----------


 ---------- 2021-12-26 22:00:00 : 동  면   39770 ----------


 ---------- 2021-12-27 06:00:00 : 동  면   39772 ----------


 ---------- 2021-12-27 07:00:00 : 동  면   39776 ----------


 ---------- 2021-12-27 08:00:00 : 신동면   39778 ----------


 ---------- 2021-12-27 09:00:00 : 약사명동   39779 ----------


 ---------- 2021-12-27 12:00:00 : 효자1동   39780 ----------


 ---------- 2021-12-27 14:00:00 : 신북읍   39781 ----------


 ---------- 2021-12-27 15:00:00 : 동산면   39782 ----------


 ---------- 2021-12-27 18:00:00 : 신북읍   39783 ----------


 ---------- 2021-12-27 18:00:00 : 동  면   39784 ----------


 ---------- 2021-12-27 23:00:00 : 근화동   39787 ----------


 ---------- 2021-12-27 23:00:00 : 교  동   39788 ----------


 ---------- 2021-12-28 00:00:00 : 후평1동   39790 ----------


 ---------- 2021-12-28 03:00:00 : 조운동   39791 ----------


 ---------- 2021-12-28 07:00:00 : 퇴계동   39792 ----------


 ---------- 2021-12-28 09:00:00 : 퇴계동   39795 ----------


 ---------- 2021-12-28 10:00:00 : 석사동   39796 ----------


 ---------- 2021-12-28 13:00:00 : 서  면   39797 ----------


 ---------- 2021-12-28 13:00:00 : 효자1동   39799 ----------


 ---------- 2021-12-28 15:00:00 : 남산면   39801 ----------


 ---------- 2021-12-28 16:00:00 : 퇴계동   39804 ----------


 ---------- 2021-12-28 16:00:00 : 교  동   39805 ----------


 ---------- 2021-12-28 18:00:00 : 강남동   39806 ----------


 ---------- 2021-12-28 18:00:00 : 남산면   39808 ----------


 ---------- 2021-12-28 18:00:00 : 동  면   39809 ----------


 ---------- 2021-12-28 19:00:00 : 서  면   39810 ----------


 ---------- 2021-12-28 19:00:00 : 동내면   39812 ----------


 ---------- 2021-12-28 22:00:00 : 후평1동   39813 ----------


 ---------- 2021-12-28 23:00:00 : 효자1동   39815 ----------


 ---------- 2021-12-28 23:00:00 : 조운동   39816 ----------


 ---------- 2021-12-29 00:00:00 : 소양동   39818 ----------


 ---------- 2021-12-29 02:00:00 : 퇴계동   39819 ----------


 ---------- 2021-12-29 09:00:00 : 석사동   39820 ----------


 ---------- 2021-12-29 09:00:00 : 신북읍   39821 ----------


 ---------- 2021-12-29 10:00:00 : 퇴계동   39823 ----------


 ---------- 2021-12-29 13:00:00 : 동내면   39824 ----------


 ---------- 2021-12-29 13:00:00 : 효자1동   39827 ----------


 ---------- 2021-12-29 18:00:00 : 신사우동   39828 ----------


 ---------- 2021-12-29 18:00:00 : 동  면   39832 ----------


 ---------- 2021-12-29 18:00:00 : 후평1동   39833 ----------


 ---------- 2021-12-29 21:00:00 : 동  면   39834 ----------


 ---------- 2021-12-30 00:00:00 : 효자1동   39835 ----------


 ---------- 2021-12-30 07:00:00 : 동산면   39836 ----------


 ---------- 2021-12-30 10:00:00 : 동  면   39838 ----------


 ---------- 2021-12-30 11:00:00 : 약사명동   39839 ----------


 ---------- 2021-12-30 13:00:00 : 사북면   39840 ----------


 ---------- 2021-12-30 15:00:00 : 신동면   39841 ----------


 ---------- 2021-12-30 16:00:00 : 석사동   39843 ----------


 ---------- 2021-12-30 16:00:00 : 동내면   39844 ----------


 ---------- 2021-12-30 17:00:00 : 남산면   39845 ----------


 ---------- 2021-12-30 19:00:00 : 퇴계동   39846 ----------


 ---------- 2021-12-31 00:00:00 : 신사우동   39848 ----------


 ---------- 2021-12-31 07:00:00 : 서  면   39849 ----------


 ---------- 2021-12-31 08:00:00 : 남산면   39850 ----------


 ---------- 2021-12-31 08:00:00 : 후평1동   39851 ----------


 ---------- 2021-12-31 10:00:00 : 소양동   39852 ----------


 ---------- 2021-12-31 10:00:00 : 동산면   39853 ----------


 ---------- 2021-12-31 11:00:00 : 효자1동   39855 ----------


 ---------- 2021-12-31 12:00:00 : 사북면   39856 ----------


 ---------- 2021-12-31 13:00:00 : 소양동   39857 ----------


 ---------- 2021-12-31 14:00:00 : 소양동   39858 ----------


 ---------- 2021-12-31 18:00:00 : 후평1동   39860 ----------


 ---------- 2021-12-31 19:00:00 : 후평1동   39862 ----------


 ---------- 2021-12-31 20:00:00 : 강남동   39863 ----------


 ---------- 2021-12-31 23:00:00 : 소양동   39865 ----------


 ---------- 2022-01-01 09:00:00 : 효자1동   39867 ----------


 ---------- 2022-01-01 10:00:00 : 석사동   39868 ----------


 ---------- 2022-01-01 10:00:00 : 근화동   39869 ----------


 ---------- 2022-01-01 10:00:00 : 약사명동   39871 ----------


 ---------- 2022-01-01 11:00:00 : 퇴계동   39874 ----------


 ---------- 2022-01-01 13:00:00 : 동  면   39877 ----------


 ---------- 2022-01-01 13:00:00 : 교  동   39878 ----------


 ---------- 2022-01-01 14:00:00 : 석사동   39879 ----------


 ---------- 2022-01-01 16:00:00 : 동  면   39880 ----------


 ---------- 2022-01-01 18:00:00 : 퇴계동   39881 ----------


 ---------- 2022-01-01 21:00:00 : 석사동   39882 ----------


 ---------- 2022-01-01 21:00:00 : 동내면   39883 ----------


 ---------- 2022-01-01 22:00:00 : 후평1동   39884 ----------

 ---------- 2022-01-01 23:00:00 : 근화동   39886 ----------


 ---------- 2022-01-02 01:00:00 : 퇴계동   39887 ----------


 ---------- 2022-01-02 03:00:00 : 퇴계동   39888 ----------


 ---------- 2022-01-02 10:00:00 : 효자1동   39889 ----------


 ---------- 2022-01-02 13:00:00 : 동  면   39890 ----------


 ---------- 2022-01-02 17:00:00 : 효자1동   39891 ----------


 ---------- 2022-01-02 18:00:00 : 석사동   39892 ----------


 ---------- 2022-01-02 18:00:00 : 후평1동   39893 ----------


 ---------- 2022-01-03 00:00:00 : 신사우동   39895 ----------


 ---------- 2022-01-03 05:00:00 : 동내면   39896 ----------


 ---------- 2022-01-03 06:00:00 : 석사동   39897 ----------


 ---------- 2022-01-03 07:00:00 : 동내면   39898 ----------


 ---------- 2022-01-03 09:00:00 : 약사명동   39899 ----------


 ---------- 2022-01-03 10:00:00 : 동  면   39900 ----------


 ---------- 2022-01-03 11:00:00 : 근화동   39901 ----------


 ---------- 2022-01-03 11:00:00 : 동  면   39902 ----------


 ---------- 2022-01-03 11:00:00 : 후평1동   39903 ----------


 ---------- 2022-01-03 13:00:00 : 효자1동   39904 ----------


 ---------- 2022-01-03 15:00:00 : 퇴계동   39905 ----------


 ---------- 2022-01-04 02:00:00 : 동  면   39906 ----------


 ---------- 2022-01-04 08:00:00 : 석사동   39907 ----------


 ---------- 2022-01-04 10:00:00 : 동  면   39909 ----------


 ---------- 2022-01-04 10:00:00 : 동산면   39910 ----------


 ---------- 2022-01-04 11:00:00 : 조운동   39911 ----------


 ---------- 2022-01-04 13:00:00 : 석사동   39912 ----------


 ---------- 2022-01-04 13:00:00 : 강남동   39913 ----------


 ---------- 2022-01-04 13:00:00 : 동산면   39914 ----------


 ---------- 2022-01-04 14:00:00 : 석사동   39917 ----------


 ---------- 2022-01-04 14:00:00 : 약사명동   39918 ----------


 ---------- 2022-01-04 15:00:00 : 동내면   39919 ----------


 ---------- 2022-01-04 16:00:00 : 동내면   39920 ----------


 ---------- 2022-01-04 20:00:00 : 석사동   39921 ----------


 ---------- 2022-01-04 21:00:00 : 후평1동   39923 ----------


 ---------- 2022-01-04 22:00:00 : 신동면   39924 ----------


 ---------- 2022-01-04 22:00:00 : 강남동   39925 ----------


 ---------- 2022-01-05 11:00:00 : 후평1동   39926 ----------


 ---------- 2022-01-05 17:00:00 : 강남동   39927 ----------


 ---------- 2022-01-05 22:00:00 : 후평1동   39928 ----------


 ---------- 2022-01-06 09:00:00 : 강남동   39929 ----------


 ---------- 2022-01-06 09:00:00 : 퇴계동   39930 ----------


 ---------- 2022-01-06 12:00:00 : 동내면   39931 ----------


 ---------- 2022-01-06 13:00:00 : 신동면   39932 ----------


 ---------- 2022-01-06 14:00:00 : 퇴계동   39933 ----------


 ---------- 2022-01-06 15:00:00 : 강남동   39934 ----------


 ---------- 2022-01-06 18:00:00 : 강남동   39935 ----------


 ---------- 2022-01-06 20:00:00 : 신북읍   39937 ----------


 ---------- 2022-01-06 20:00:00 : 교  동   39938 ----------


 ---------- 2022-01-06 21:00:00 : 동내면   39939 ----------


 ---------- 2022-01-07 08:00:00 : 퇴계동   39941 ----------


 ---------- 2022-01-07 10:00:00 : 근화동   39942 ----------


 ---------- 2022-01-07 10:00:00 : 후평1동   39944 ----------


 ---------- 2022-01-07 11:00:00 : 퇴계동   39947 ----------


 ---------- 2022-01-07 12:00:00 : 남산면   39949 ----------


 ---------- 2022-01-07 12:00:00 : 근화동   39950 ----------


 ---------- 2022-01-07 12:00:00 : 소양동   39952 ----------


 ---------- 2022-01-07 13:00:00 : 후평1동   39953 ----------


 ---------- 2022-01-07 15:00:00 : 근화동   39955 ----------


 ---------- 2022-01-07 17:00:00 : 퇴계동   39959 ----------


 ---------- 2022-01-07 18:00:00 : 효자1동   39960 ----------


 ---------- 2022-01-07 18:00:00 : 후평1동   39961 ----------


 ---------- 2022-01-07 19:00:00 : 근화동   39962 ----------


 ---------- 2022-01-07 19:00:00 : 약사명동   39964 ----------


 ---------- 2022-01-07 20:00:00 : 강남동   39965 ----------


 ---------- 2022-01-07 20:00:00 : 퇴계동   39966 ----------


 ---------- 2022-01-07 21:00:00 : 석사동   39967 ----------


 ---------- 2022-01-07 21:00:00 : 동내면   39968 ----------


 ---------- 2022-01-07 23:00:00 : 석사동   39969 ----------


 ---------- 2022-01-07 23:00:00 : 신사우동   39970 ----------


 ---------- 2022-01-08 01:00:00 : 동내면   39971 ----------


 ---------- 2022-01-08 06:00:00 : 동내면   39972 ----------


 ---------- 2022-01-08 10:00:00 : 남산면   39974 ----------


 ---------- 2022-01-08 15:00:00 : 퇴계동   39975 ----------


 ---------- 2022-01-08 18:00:00 : 서  면   39976 ----------


 ---------- 2022-01-09 08:00:00 : 후평1동   39977 ----------


 ---------- 2022-01-09 11:00:00 : 동  면   39979 ----------


 ---------- 2022-01-09 12:00:00 : 후평1동   39980 ----------


 ---------- 2022-01-09 13:00:00 : 신사우동   39981 ----------


 ---------- 2022-01-09 16:00:00 : 후평1동   39982 ----------


 ---------- 2022-01-09 21:00:00 : 신동면   39983 ----------


 ---------- 2022-01-10 10:00:00 : 서  면   39984 ----------


 ---------- 2022-01-10 11:00:00 : 동내면   39985 ----------


 ---------- 2022-01-10 14:00:00 : 소양동   39986 ----------


 ---------- 2022-01-10 14:00:00 : 후평1동   39987 ----------


 ---------- 2022-01-10 15:00:00 : 강남동   39988 ----------


 ---------- 2022-01-10 18:00:00 : 동내면   39989 ----------


 ---------- 2022-01-10 18:00:00 : 소양동   39990 ----------


 ---------- 2022-01-10 19:00:00 : 후평1동   39992 ----------


 ---------- 2022-01-10 20:00:00 : 후평1동   39993 ----------


 ---------- 2022-01-10 20:00:00 : 퇴계동   39995 ----------


 ---------- 2022-01-10 22:00:00 : 근화동   39997 ----------


 ---------- 2022-01-10 22:00:00 : 후평1동   39998 ----------


 ---------- 2022-01-11 01:00:00 : 강남동   39999 ----------


 ---------- 2022-01-11 03:00:00 : 소양동   40000 ----------


 ---------- 2022-01-11 04:00:00 : 소양동   40001 ----------


 ---------- 2022-01-11 04:00:00 : 퇴계동   40002 ----------


 ---------- 2022-01-11 15:00:00 : 교  동   40004 ----------


 ---------- 2022-01-11 18:00:00 : 석사동   40005 ----------


 ---------- 2022-01-11 18:00:00 : 동  면   40006 ----------


 ---------- 2022-01-12 00:00:00 : 소양동   40007 ----------


 ---------- 2022-01-12 09:00:00 : 강남동   40008 ----------


 ---------- 2022-01-12 09:00:00 : 동  면   40009 ----------


 ---------- 2022-01-12 10:00:00 : 강남동   40010 ----------


 ---------- 2022-01-12 12:00:00 : 퇴계동   40011 ----------


 ---------- 2022-01-12 14:00:00 : 강남동   40012 ----------


 ---------- 2022-01-12 16:00:00 : 북산면   40013 ----------


 ---------- 2022-01-12 17:00:00 : 동  면   40014 ----------


 ---------- 2022-01-12 20:00:00 : 근화동   40015 ----------


 ---------- 2022-01-12 23:00:00 : 신동면   40017 ----------


 ---------- 2022-01-12 23:00:00 : 신사우동   40018 ----------


 ---------- 2022-01-13 09:00:00 : 석사동   40019 ----------


 ---------- 2022-01-13 11:00:00 : 근화동   40020 ----------


 ---------- 2022-01-13 13:00:00 : 퇴계동   40022 ----------


 ---------- 2022-01-13 14:00:00 : 동내면   40023 ----------


 ---------- 2022-01-13 16:00:00 : 퇴계동   40024 ----------


 ---------- 2022-01-13 18:00:00 : 동내면   40025 ----------


 ---------- 2022-01-13 18:00:00 : 후평1동   40026 ----------


 ---------- 2022-01-13 19:00:00 : 동내면   40027 ----------


 ---------- 2022-01-13 20:00:00 : 석사동   40028 ----------


 ---------- 2022-01-13 21:00:00 : 퇴계동   40029 ----------


 ---------- 2022-01-13 22:00:00 : 신사우동   40030 ----------


 ---------- 2022-01-14 02:00:00 : 석사동   40031 ----------


 ---------- 2022-01-14 03:00:00 : 효자1동   40032 ----------


 ---------- 2022-01-14 05:00:00 : 효자1동   40034 ----------


 ---------- 2022-01-14 08:00:00 : 약사명동   40035 ----------


 ---------- 2022-01-14 08:00:00 : 동산면   40036 ----------


 ---------- 2022-01-14 10:00:00 : 소양동   40037 ----------


 ---------- 2022-01-14 11:00:00 : 신북읍   40038 ----------


 ---------- 2022-01-14 13:00:00 : 강남동   40039 ----------


 ---------- 2022-01-14 14:00:00 : 효자1동   40040 ----------


 ---------- 2022-01-14 14:00:00 : 소양동   40041 ----------


 ---------- 2022-01-14 21:00:00 : 소양동   40042 ----------


 ---------- 2022-01-14 22:00:00 : 동  면   40043 ----------


 ---------- 2022-01-15 01:00:00 : 동내면   40044 ----------


 ---------- 2022-01-15 07:00:00 : 후평1동   40045 ----------


 ---------- 2022-01-15 08:00:00 : 효자1동   40046 ----------


 ---------- 2022-01-15 09:00:00 : 강남동   40047 ----------

 ---------- 2022-01-15 09:00:00 : 신북읍   40048 ----------


 ---------- 2022-01-15 11:00:00 : 신동면   40049 ----------


 ---------- 2022-01-15 14:00:00 : 후평1동   40050 ----------


 ---------- 2022-01-15 18:00:00 : 신북읍   40051 ----------


 ---------- 2022-01-15 23:00:00 : 효자1동   40053 ----------


 ---------- 2022-01-16 11:00:00 : 동내면   40054 ----------


 ---------- 2022-01-16 13:00:00 : 퇴계동   40055 ----------


 ---------- 2022-01-16 14:00:00 : 남산면   40057 ----------


 ---------- 2022-01-16 15:00:00 : 퇴계동   40058 ----------


 ---------- 2022-01-16 17:00:00 : 퇴계동   40059 ----------


 ---------- 2022-01-16 20:00:00 : 후평1동   40060 ----------


 ---------- 2022-01-17 00:00:00 : 석사동   40061 ----------


 ---------- 2022-01-17 03:00:00 : 사북면   40063 ----------


 ---------- 2022-01-17 13:00:00 : 강남동   40064 ----------


 ---------- 2022-01-17 13:00:00 : 동  면   40065 ----------


 ---------- 2022-01-17 15:00:00 : 강남동   40066 ----------


 ---------- 2022-01-17 15:00:00 : 조운동   40067 ----------


 ---------- 2022-01-17 16:00:00 : 신사우동   40068 ----------


 ---------- 2022-01-18 08:00:00 : 효자1동   40069 ----------


 ---------- 2022-01-18 13:00:00 : 서  면   40071 ----------


 ---------- 2022-01-18 15:00:00 : 서  면   40072 ----------


 ---------- 2022-01-18 15:00:00 : 남산면   40073 ----------


 ---------- 2022-01-18 16:00:00 : 퇴계동   40074 ----------


 ---------- 2022-01-18 17:00:00 : 신사우동   40075 ----------


 ---------- 2022-01-18 19:00:00 : 소양동   40077 ----------


 ---------- 2022-01-19 07:00:00 : 남산면   40080 ----------


 ---------- 2022-01-19 12:00:00 : 동내면   40081 ----------


 ---------- 2022-01-19 14:00:00 : 남산면   40082 ----------


 ---------- 2022-01-19 15:00:00 : 신동면   40083 ----------


 ---------- 2022-01-19 15:00:00 : 퇴계동   40085 ----------


 ---------- 2022-01-19 20:00:00 : 퇴계동   40087 ----------


 ---------- 2022-01-19 21:00:00 : 서  면   40090 ----------


 ---------- 2022-01-20 01:00:00 : 퇴계동   40092 ----------


 ---------- 2022-01-20 05:00:00 : 효자1동   40094 ----------


 ---------- 2022-01-20 07:00:00 : 동산면   40095 ----------


 ---------- 2022-01-20 08:00:00 : 신동면   40096 ----------


 ---------- 2022-01-20 09:00:00 : 신동면   40097 ----------


 ---------- 2022-01-20 10:00:00 : 소양동   40098 ----------


 ---------- 2022-01-20 10:00:00 : 퇴계동   40099 ----------


 ---------- 2022-01-20 13:00:00 : 효자1동   40100 ----------


 ---------- 2022-01-20 15:00:00 : 신사우동   40103 ----------


 ---------- 2022-01-21 01:00:00 : 신사우동   40104 ----------


 ---------- 2022-01-21 03:00:00 : 동내면   40106 ----------


 ---------- 2022-01-21 06:00:00 : 조운동   40107 ----------


 ---------- 2022-01-21 08:00:00 : 신북읍   40108 ----------


 ---------- 2022-01-21 09:00:00 : 신사우동   40110 ----------


 ---------- 2022-01-21 10:00:00 : 후평1동   40111 ----------


 ---------- 2022-01-21 11:00:00 : 북산면   40113 ----------


 ---------- 2022-01-21 12:00:00 : 신사우동   40114 ----------


 ---------- 2022-01-21 13:00:00 : 소양동   40115 ----------


 ---------- 2022-01-21 15:00:00 : 신사우동   40117 ----------


 ---------- 2022-01-21 15:00:00 : 소양동   40118 ----------


 ---------- 2022-01-21 16:00:00 : 신북읍   40119 ----------


 ---------- 2022-01-22 07:00:00 : 남  면   40120 ----------


 ---------- 2022-01-22 07:00:00 : 후평1동   40121 ----------


 ---------- 2022-01-22 09:00:00 : 신동면   40124 ----------


 ---------- 2022-01-22 11:00:00 : 남산면   40126 ----------


 ---------- 2022-01-22 13:00:00 : 남산면   40127 ----------


 ---------- 2022-01-22 15:00:00 : 퇴계동   40128 ----------


 ---------- 2022-01-22 16:00:00 : 동내면   40130 ----------


 ---------- 2022-01-22 17:00:00 : 강남동   40132 ----------


 ---------- 2022-01-22 20:00:00 : 신사우동   40133 ----------


 ---------- 2022-01-22 21:00:00 : 퇴계동   40135 ----------


 ---------- 2022-01-22 23:00:00 : 근화동   40136 ----------


 ---------- 2022-01-22 23:00:00 : 동  면   40138 ----------


 ---------- 2022-01-23 04:00:00 : 퇴계동   40139 ----------


 ---------- 2022-01-23 06:00:00 : 강남동   40141 ----------


 ---------- 2022-01-23 13:00:00 : 후평1동   40142 ----------


 ---------- 2022-01-23 14:00:00 : 석사동   40143 ----------


 ---------- 2022-01-23 16:00:00 : 퇴계동   40144 ----------


 ---------- 2022-01-23 20:00:00 : 효자1동   40145 ----------


 ---------- 2022-01-24 08:00:00 : 동  면   40146 ----------


 ---------- 2022-01-24 09:00:00 : 석사동   40148 ----------


 ---------- 2022-01-24 10:00:00 : 효자1동   40149 ----------


 ---------- 2022-01-24 11:00:00 : 효자1동   40150 ----------


 ---------- 2022-01-24 11:00:00 : 동  면   40151 ----------


 ---------- 2022-01-24 14:00:00 : 동내면   40152 ----------


 ---------- 2022-01-24 14:00:00 : 약사명동   40153 ----------


 ---------- 2022-01-24 18:00:00 : 효자1동   40154 ----------


 ---------- 2022-01-24 19:00:00 : 효자1동   40155 ----------


 ---------- 2022-01-24 21:00:00 : 퇴계동   40156 ----------


 ---------- 2022-01-25 02:00:00 : 석사동   40158 ----------


 ---------- 2022-01-25 05:00:00 : 근화동   40160 ----------


 ---------- 2022-01-25 10:00:00 : 동  면   40161 ----------


 ---------- 2022-01-25 11:00:00 : 동내면   40163 ----------


 ---------- 2022-01-25 12:00:00 : 퇴계동   40164 ----------


 ---------- 2022-01-25 14:00:00 : 남산면   40165 ----------


 ---------- 2022-01-25 15:00:00 : 후평1동   40167 ----------


 ---------- 2022-01-25 16:00:00 : 신북읍   40168 ----------


 ---------- 2022-01-25 18:00:00 : 서  면   40170 ----------


 ---------- 2022-01-25 18:00:00 : 근화동   40172 ----------


 ---------- 2022-01-25 20:00:00 : 남  면   40173 ----------


 ---------- 2022-01-25 21:00:00 : 효자1동   40175 ----------


 ---------- 2022-01-25 23:00:00 : 효자1동   40177 ----------


 ---------- 2022-01-26 01:00:00 : 효자1동   40178 ----------


 ---------- 2022-01-26 01:00:00 : 퇴계동   40179 ----------


 ---------- 2022-01-26 02:00:00 : 서  면   40180 ----------


 ---------- 2022-01-26 12:00:00 : 동  면   40183 ----------


 ---------- 2022-01-26 13:00:00 : 석사동   40184 ----------


 ---------- 2022-01-26 14:00:00 : 신북읍   40185 ----------


 ---------- 2022-01-26 18:00:00 : 강남동   40186 ----------


 ---------- 2022-01-27 00:00:00 : 신북읍   40187 ----------


 ---------- 2022-01-27 03:00:00 : 강남동   40188 ----------


 ---------- 2022-01-27 03:00:00 : 퇴계동   40189 ----------


 ---------- 2022-01-27 08:00:00 : 강남동   40190 ----------


 ---------- 2022-01-27 09:00:00 : 동내면   40191 ----------


 ---------- 2022-01-27 10:00:00 : 조운동   40192 ----------


 ---------- 2022-01-27 13:00:00 : 석사동   40194 ----------


 ---------- 2022-01-27 15:00:00 : 석사동   40196 ----------


 ---------- 2022-01-27 15:00:00 : 신사우동   40197 ----------


 ---------- 2022-01-27 15:00:00 : 신북읍   40198 ----------


 ---------- 2022-01-27 16:00:00 : 소양동   40199 ----------


 ---------- 2022-01-27 17:00:00 : 서  면   40200 ----------


 ---------- 2022-01-27 21:00:00 : 퇴계동   40203 ----------


 ---------- 2022-01-28 00:00:00 : 효자1동   40205 ----------


 ---------- 2022-01-28 08:00:00 : 소양동   40207 ----------


 ---------- 2022-01-28 09:00:00 : 신북읍   40208 ----------


 ---------- 2022-01-28 11:00:00 : 남산면   40210 ----------


 ---------- 2022-01-28 16:00:00 : 소양동   40212 ----------


 ---------- 2022-01-28 18:00:00 : 퇴계동   40214 ----------


 ---------- 2022-01-28 23:00:00 : 소양동   40216 ----------


 ---------- 2022-01-29 00:00:00 : 효자1동   40218 ----------


 ---------- 2022-01-29 05:00:00 : 사북면   40220 ----------


 ---------- 2022-01-29 06:00:00 : 후평1동   40221 ----------


 ---------- 2022-01-29 07:00:00 : 남산면   40223 ----------


 ---------- 2022-01-29 10:00:00 : 신동면   40226 ----------


 ---------- 2022-01-29 10:00:00 : 효자1동   40227 ----------


 ---------- 2022-01-29 14:00:00 : 동내면   40228 ----------


 ---------- 2022-01-29 15:00:00 : 동내면   40229 ----------


 ---------- 2022-01-29 16:00:00 : 남  면   40230 ----------


 ---------- 2022-01-29 18:00:00 : 동내면   40232 ----------


 ---------- 2022-01-29 20:00:00 : 석사동   40233 ----------


 ---------- 2022-01-29 22:00:00 : 후평1동   40234 ----------


 ---------- 2022-01-30 01:00:00 : 효자1동   40235 ----------


 ---------- 2022-01-30 06:00:00 : 남  면   40236 ----------


 ---------- 2022-01-30 08:00:00 : 소양동   40237 ----------

 ---------- 2022-01-30 10:00:00 : 강남동   40238 ----------


 ---------- 2022-01-30 10:00:00 : 약사명동   40239 ----------


 ---------- 2022-01-30 19:00:00 : 강남동   40240 ----------


 ---------- 2022-01-30 20:00:00 : 사북면   40241 ----------


 ---------- 2022-01-30 20:00:00 : 효자1동   40242 ----------


 ---------- 2022-01-30 21:00:00 : 동내면   40244 ----------


 ---------- 2022-01-30 21:00:00 : 동  면   40245 ----------


 ---------- 2022-01-31 09:00:00 : 강남동   40247 ----------


 ---------- 2022-01-31 09:00:00 : 서  면   40249 ----------


 ---------- 2022-01-31 10:00:00 : 동산면   40250 ----------


 ---------- 2022-01-31 11:00:00 : 후평1동   40251 ----------


 ---------- 2022-01-31 12:00:00 : 석사동   40254 ----------


 ---------- 2022-01-31 12:00:00 : 남  면   40259 ----------


 ---------- 2022-01-31 13:00:00 : 강남동   40260 ----------


 ---------- 2022-01-31 14:00:00 : 남  면   40264 ----------


 ---------- 2022-01-31 18:00:00 : 퇴계동   40265 ----------


 ---------- 2022-01-31 19:00:00 : 동  면   40266 ----------


 ---------- 2022-01-31 21:00:00 : 남  면   40267 ----------


 ---------- 2022-01-31 21:00:00 : 소양동   40268 ----------


 ---------- 2022-02-01 07:00:00 : 동산면   40270 ----------


 ---------- 2022-02-01 14:00:00 : 동  면   40272 ----------


 ---------- 2022-02-02 02:00:00 : 효자1동   40273 ----------


 ---------- 2022-02-02 10:00:00 : 남  면   40274 ----------


 ---------- 2022-02-02 12:00:00 : 신사우동   40276 ----------


 ---------- 2022-02-02 12:00:00 : 퇴계동   40278 ----------


 ---------- 2022-02-02 13:00:00 : 강남동   40279 ----------


 ---------- 2022-02-02 15:00:00 : 사북면   40281 ----------


 ---------- 2022-02-02 15:00:00 : 퇴계동   40284 ----------


 ---------- 2022-02-02 16:00:00 : 신사우동   40287 ----------


 ---------- 2022-02-02 21:00:00 : 퇴계동   40289 ----------


 ---------- 2022-02-03 05:00:00 : 강남동   40290 ----------


 ---------- 2022-02-03 08:00:00 : 조운동   40291 ----------


 ---------- 2022-02-03 09:00:00 : 강남동   40293 ----------


 ---------- 2022-02-03 11:00:00 : 신사우동   40295 ----------


 ---------- 2022-02-03 15:00:00 : 강남동   40297 ----------


 ---------- 2022-02-03 17:00:00 : 소양동   40298 ----------


 ---------- 2022-02-04 08:00:00 : 동  면   40299 ----------


 ---------- 2022-02-04 08:00:00 : 동산면   40300 ----------


 ---------- 2022-02-04 09:00:00 : 신사우동   40301 ----------


 ---------- 2022-02-04 12:00:00 : 소양동   40303 ----------


 ---------- 2022-02-04 16:00:00 : 소양동   40304 ----------


 ---------- 2022-02-04 23:00:00 : 석사동   40306 ----------


 ---------- 2022-02-05 04:00:00 : 효자1동   40308 ----------


 ---------- 2022-02-05 09:00:00 : 신북읍   40309 ----------


 ---------- 2022-02-05 10:00:00 : 퇴계동   40310 ----------


 ---------- 2022-02-05 12:00:00 : 남산면   40311 ----------


 ---------- 2022-02-05 15:00:00 : 동  면   40312 ----------


 ---------- 2022-02-05 21:00:00 : 후평1동   40313 ----------


 ---------- 2022-02-05 23:00:00 : 후평1동   40316 ----------


 ---------- 2022-02-06 02:00:00 : 신사우동   40317 ----------


 ---------- 2022-02-06 13:00:00 : 신북읍   40318 ----------


 ---------- 2022-02-06 13:00:00 : 퇴계동   40320 ----------


 ---------- 2022-02-07 05:00:00 : 퇴계동   40322 ----------


 ---------- 2022-02-07 08:00:00 : 퇴계동   40323 ----------


 ---------- 2022-02-07 09:00:00 : 서  면   40324 ----------


 ---------- 2022-02-07 10:00:00 : 남산면   40325 ----------


 ---------- 2022-02-07 13:00:00 : 후평1동   40326 ----------


 ---------- 2022-02-07 14:00:00 : 강남동   40327 ----------


 ---------- 2022-02-07 18:00:00 : 신북읍   40328 ----------


 ---------- 2022-02-07 22:00:00 : 동  면   40329 ----------


 ---------- 2022-02-08 08:00:00 : 후평1동   40330 ----------


 ---------- 2022-02-08 09:00:00 : 교  동   40332 ----------


 ---------- 2022-02-08 10:00:00 : 퇴계동   40333 ----------


 ---------- 2022-02-08 18:00:00 : 퇴계동   40335 ----------


 ---------- 2022-02-08 20:00:00 : 후평1동   40336 ----------


 ---------- 2022-02-08 23:00:00 : 강남동   40338 ----------


 ---------- 2022-02-09 07:00:00 : 석사동   40339 ----------


 ---------- 2022-02-09 08:00:00 : 석사동   40340 ----------


 ---------- 2022-02-09 08:00:00 : 동  면   40341 ----------


 ---------- 2022-02-09 11:00:00 : 석사동   40342 ----------


 ---------- 2022-02-09 11:00:00 : 신북읍   40343 ----------


 ---------- 2022-02-09 11:00:00 : 약사명동   40345 ----------


 ---------- 2022-02-09 20:00:00 : 사북면   40346 ----------


 ---------- 2022-02-10 08:00:00 : 후평1동   40347 ----------


 ---------- 2022-02-10 14:00:00 : 신북읍   40349 ----------


 ---------- 2022-02-11 11:00:00 : 신사우동   40350 ----------


 ---------- 2022-02-11 15:00:00 : 서  면   40351 ----------


 ---------- 2022-02-11 15:00:00 : 효자1동   40352 ----------


 ---------- 2022-02-11 22:00:00 : 석사동   40353 ----------


 ---------- 2022-02-12 01:00:00 : 신북읍   40355 ----------


 ---------- 2022-02-12 09:00:00 : 효자1동   40357 ----------


 ---------- 2022-02-12 10:00:00 : 동  면   40358 ----------


 ---------- 2022-02-12 12:00:00 : 석사동   40359 ----------


 ---------- 2022-02-12 13:00:00 : 동  면   40360 ----------


 ---------- 2022-02-12 14:00:00 : 후평1동   40361 ----------


 ---------- 2022-02-12 15:00:00 : 효자1동   40362 ----------


 ---------- 2022-02-12 17:00:00 : 석사동   40363 ----------


 ---------- 2022-02-12 21:00:00 : 신북읍   40364 ----------


 ---------- 2022-02-13 09:00:00 : 교  동   40365 ----------


 ---------- 2022-02-13 11:00:00 : 동산면   40366 ----------


 ---------- 2022-02-13 15:00:00 : 후평1동   40367 ----------


 ---------- 2022-02-13 19:00:00 : 신사우동   40368 ----------


 ---------- 2022-02-13 19:00:00 : 퇴계동   40369 ----------


 ---------- 2022-02-13 23:00:00 : 퇴계동   40371 ----------


 ---------- 2022-02-14 05:00:00 : 신사우동   40372 ----------


 ---------- 2022-02-14 10:00:00 : 근화동   40373 ----------


 ---------- 2022-02-14 12:00:00 : 효자1동   40374 ----------


 ---------- 2022-02-14 14:00:00 : 퇴계동   40378 ----------


 ---------- 2022-02-14 17:00:00 : 조운동   40379 ----------


 ---------- 2022-02-14 21:00:00 : 동내면   40380 ----------


 ---------- 2022-02-15 09:00:00 : 석사동   40381 ----------


 ---------- 2022-02-15 09:00:00 : 퇴계동   40384 ----------


 ---------- 2022-02-15 10:00:00 : 동산면   40386 ----------


 ---------- 2022-02-15 13:00:00 : 효자1동   40388 ----------


 ---------- 2022-02-15 15:00:00 : 석사동   40389 ----------


 ---------- 2022-02-16 02:00:00 : 퇴계동   40390 ----------


 ---------- 2022-02-16 08:00:00 : 동  면   40393 ----------


 ---------- 2022-02-16 10:00:00 : 석사동   40394 ----------


 ---------- 2022-02-16 11:00:00 : 북산면   40397 ----------


 ---------- 2022-02-16 14:00:00 : 강남동   40398 ----------


 ---------- 2022-02-16 16:00:00 : 후평1동   40399 ----------


 ---------- 2022-02-17 08:00:00 : 강남동   40400 ----------


 ---------- 2022-02-17 08:00:00 : 신사우동   40401 ----------


 ---------- 2022-02-17 09:00:00 : 신사우동   40402 ----------


 ---------- 2022-02-17 10:00:00 : 퇴계동   40403 ----------


 ---------- 2022-02-17 12:00:00 : 서  면   40404 ----------


 ---------- 2022-02-17 18:00:00 : 후평1동   40405 ----------


 ---------- 2022-02-17 21:00:00 : 사북면   40406 ----------


 ---------- 2022-02-18 07:00:00 : 후평1동   40407 ----------


 ---------- 2022-02-18 07:00:00 : 퇴계동   40408 ----------


 ---------- 2022-02-18 09:00:00 : 동내면   40409 ----------


 ---------- 2022-02-18 09:00:00 : 신사우동   40411 ----------


 ---------- 2022-02-18 12:00:00 : 신사우동   40413 ----------


 ---------- 2022-02-18 19:00:00 : 퇴계동   40414 ----------


 ---------- 2022-02-18 21:00:00 : 근화동   40415 ----------


 ---------- 2022-02-18 21:00:00 : 북산면   40416 ----------


 ---------- 2022-02-19 00:00:00 : 소양동   40417 ----------


 ---------- 2022-02-19 09:00:00 : 퇴계동   40418 ----------


 ---------- 2022-02-19 09:00:00 : 북산면   40420 ----------


 ---------- 2022-02-19 17:00:00 : 근화동   40421 ----------


 ---------- 2022-02-19 20:00:00 : 강남동   40422 ----------


 ---------- 2022-02-19 23:00:00 : 신동면   40423 ----------


 ---------- 2022-02-20 05:00:00 : 남산면   40424 ----------


 ---------- 2022-02-20 09:00:00 : 서  면   40425 ----------


 ---------- 2022-02-20 11:00:00 : 서  면   40428 ----------


 ---------- 2022-02-20 12:00:00 : 동내면   40429 ----------

 ---------- 2022-02-20 21:00:00 : 퇴계동   40431 ----------


 ---------- 2022-02-20 22:00:00 : 석사동   40432 ----------


 ---------- 2022-02-20 23:00:00 : 사북면   40433 ----------


 ---------- 2022-02-21 08:00:00 : 신동면   40434 ----------


 ---------- 2022-02-21 14:00:00 : 퇴계동   40435 ----------


 ---------- 2022-02-21 15:00:00 : 동산면   40437 ----------


 ---------- 2022-02-21 16:00:00 : 남  면   40440 ----------


 ---------- 2022-02-21 18:00:00 : 퇴계동   40441 ----------


 ---------- 2022-02-21 20:00:00 : 동내면   40442 ----------


 ---------- 2022-02-22 18:00:00 : 소양동   40443 ----------


 ---------- 2022-02-22 18:00:00 : 후평1동   40444 ----------


 ---------- 2022-02-22 22:00:00 : 후평1동   40445 ----------


 ---------- 2022-02-23 07:00:00 : 서  면   40446 ----------


 ---------- 2022-02-23 10:00:00 : 신사우동   40447 ----------


 ---------- 2022-02-23 11:00:00 : 신사우동   40449 ----------


 ---------- 2022-02-23 14:00:00 : 강남동   40450 ----------


 ---------- 2022-02-23 16:00:00 : 근화동   40451 ----------


 ---------- 2022-02-23 20:00:00 : 동  면   40452 ----------


 ---------- 2022-02-24 12:00:00 : 퇴계동   40454 ----------


 ---------- 2022-02-24 15:00:00 : 석사동   40456 ----------


 ---------- 2022-02-24 20:00:00 : 남산면   40458 ----------


 ---------- 2022-02-24 20:00:00 : 동  면   40459 ----------


 ---------- 2022-02-25 02:00:00 : 강남동   40460 ----------


 ---------- 2022-02-25 10:00:00 : 강남동   40461 ----------


 ---------- 2022-02-25 15:00:00 : 효자1동   40462 ----------


 ---------- 2022-02-26 08:00:00 : 조운동   40463 ----------


 ---------- 2022-02-26 10:00:00 : 신북읍   40464 ----------


 ---------- 2022-02-26 11:00:00 : 조운동   40465 ----------


 ---------- 2022-02-26 12:00:00 : 신북읍   40466 ----------


 ---------- 2022-02-26 13:00:00 : 후평1동   40467 ----------


 ---------- 2022-02-26 14:00:00 : 조운동   40468 ----------


 ---------- 2022-02-26 16:00:00 : 효자1동   40469 ----------


 ---------- 2022-02-26 17:00:00 : 퇴계동   40470 ----------


 ---------- 2022-02-26 19:00:00 : 동  면   40471 ----------


 ---------- 2022-02-26 22:00:00 : 효자1동   40472 ----------


 ---------- 2022-02-27 12:00:00 : 신북읍   40474 ----------


 ---------- 2022-02-27 21:00:00 : 후평1동   40475 ----------


 ---------- 2022-02-27 22:00:00 : 동산면   40476 ----------


 ---------- 2022-02-28 00:00:00 : 효자1동   40478 ----------


 ---------- 2022-02-28 10:00:00 : 신북읍   40479 ----------


 ---------- 2022-02-28 11:00:00 : 신사우동   40480 ----------


 ---------- 2022-02-28 16:00:00 : 신동면   40481 ----------


 ---------- 2022-02-28 16:00:00 : 후평1동   40483 ----------

In [14]:
data['REG_DTIME'].unique()

array(['2015-01-01T00:00:00.000000000', '2015-01-01T01:00:00.000000000',
       '2015-01-01T02:00:00.000000000', ...,
       '2022-02-28T22:00:00.000000000', '2022-02-28T23:00:00.000000000',
       '2022-03-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [6]:
data.to_csv('2010_2022_count.csv')

In [11]:
data[data['count'] > 0]

,REG_DTIME,h_dong,count,ACT_DESC,GUIDE
189,2015-01-01 09:00:00,효자1동,1,[모닝차량이 나무와 충돌한 상황으로 현장도착한바 구조사항 없다하여 귀대함.],[None]
274,2015-01-01 13:00:00,석사동,1,[상기장소 시건개방 출동으로 자체처리 되었다는 신고로 출동전 취소됨. ],[None]
359,2015-01-01 17:00:00,후평1동,1,[상기장소 화재출동으로 현장 출동 하여 확인 중 춘천지휘에서 구조상황 없다하여 구조...,[None]
379,2015-01-01 18:00:00,석사동,1,[화재접보로 현장출동 중 자체진화되었다는 상황실무전을 받고 회차 귀서함.],[None]
715,2015-01-02 10:00:00,석사동,1,"[화재출동으로 현장으로 출동중 선착한 석사펌프에서 주택 내 쓰레기더미 화재이며, 구...",[None]
...,...,...,...,...,...
1317960,2022-02-28 00:00:00,효자1동,2,"[80대 노인 행방불명으로 출동지령나왔으나, 구조대 출동하지말라는 유선연락 수신 후...","[None, None]"
1318175,2022-02-28 10:00:00,신북읍,1,[- 고양이가 지붕위로 올라가서 못내려오고있다는 신고로 출동. - 현장도착하여 동...,[None]
1318208,2022-02-28 11:00:00,신사우동,1,[차량화재 신고로 출동중 아스팔트 녹이는 중이며 선착한 펌프에서 진압 가능하다하여 ...,[None]
1318298,2022-02-28 16:00:00,후평1동,2,[[위치추척] 아내 자살기도 추정 위치추적 출동. 출동 중 신북구급 출동으로 구조...,"[출동 중 귀소., None]"
1318309,2022-02-28 16:00:00,신동면,1,[[고양이 구조] 고양이가 본인 집 하수구에 끼어 못나온다는 신고. 구조대 현장 ...,[배수구 뚜껑 개방]

In [21]:
pdata.data[pdata.data['REG_DTIME'] > '2022-01-01 00:00:00.000']

,REG_DTIME,ACT_DESC,GUIDE,h_dong
372165,2022-01-01 09:00:00,자동화재속보설비 출동건으로 현장 출동중 관계자에 의해 오작동 확인되어 출동중 귀소함,None,효자1동
372152,2022-01-01 09:00:00,소방시설오작동으로 춘천구조 안전하게 중도귀소완료.,소방시설 오작동으로 중도귀소.,효자1동
372162,2022-01-01 10:00:00,"쓰레기를 태우다 폐기물더미(냉장고, 침대 매트리스 등)으로 옮겨붙은 화재로 수관 2...",None,근화동
372161,2022-01-01 10:00:00,자동화재속보설비 작동으로 현장 도착하여 1층 처치실 차동식감지기 오작동 확인 화재징...,None,약사명동
372167,2022-01-01 10:00:00,어머니께서 말씀이 어눌하고 손 감각이 이상하다는 신고로 현장도착한바 스스로 걸어나오...,안전조치,석사동
...,...,...,...,...
377100,2022-02-28 10:00:00,- 고양이가 지붕위로 올라가서 못내려오고있다는 신고로 출동. - 현장도착하여 동물...,None,신북읍
377102,2022-02-28 11:00:00,차량화재 신고로 출동중 아스팔트 녹이는 중이며 선착한 펌프에서 진압 가능하다하여 지...,None,신사우동
377099,2022-02-28 16:00:00,[고양이 구조] 고양이가 본인 집 하수구에 끼어 못나온다는 신고. 구조대 현장 도...,배수구 뚜껑 개방,신동면
377103,2022-02-28 16:00:00,[위치추척] 아내 자살기도 추정 위치추적 출동. 출동 중 신북구급 출동으로 구조대...,출동 중 귀소.,후평1동
377105,2022-02-28 16:00:00,3일 전 부부싸움 후 아내가 집을 나간 것 같다. 자살 추정 실종자 수색 건으로 현...,None,후평1동

In [18]:
sum(data[data['count'] > 0]['count'])

613